var s_iOffsetX=0,s_iOffsetY=0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}window.addEventListener("orientationchange",onOrientationChange);
function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(a){var c=a.toLowerCase(),b=window.document,e=b.documentElement;if(void 0===window["inner"+a])a=e["client"+a];else if(window["inner"+a]!=e["client"+a]){var f=b.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var d=b.createElement("div");d.id="vpw-test-d";d.style.cssText="position:absolute;top:-1000px";d.innerHTML="<style>@media("+c+":"+e["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";f.appendChild(d);e.insertBefore(f,b.head);
a=7==d["offset"+a]?e["client"+a]:window["inner"+a];e.removeChild(f)}else a=window["inner"+a];return a}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width");_checkOrientation(c,a);s_iScaleFactor=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH);var b=CANVAS_WIDTH*s_iScaleFactor,e=CANVAS_HEIGHT*s_iScaleFactor,f;e<a?(f=a-e,e+=f,b+=CANVAS_WIDTH/CANVAS_HEIGHT*f):b<c&&(f=c-b,b+=f,e+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-e/2;var d=c/2-b/2,g=CANVAS_WIDTH/b;if(d*g<-EDGEBOARD_X||f*g<-EDGEBOARD_Y)s_iScaleFactor=
Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=CANVAS_WIDTH*s_iScaleFactor,e=CANVAS_HEIGHT*s_iScaleFactor,f=(a-e)/2,d=(c-b)/2,g=CANVAS_WIDTH/b;s_iOffsetX=-1*d*g;s_iOffsetY=-1*f*g;0<=f&&(s_iOffsetY=0);0<=d&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oHelpPanel&&s_oHelpPanel.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile&&!s_bIsIphone?($("#canvas").css("width",
b+"px"),$("#canvas").css("height",e+"px")):(s_oStage.canvas.width=b,s_oStage.canvas.height=e,s_oStage.scaleX=s_oStage.scaleY=Math.min(b/CANVAS_WIDTH,e/CANVAS_HEIGHT));0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",d+"px")}}
function _checkOrientation(a,c){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>c?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function createBitmap(a,c,b){var e=new createjs.Bitmap(a),f=new createjs.Shape;c&&b?f.graphics.beginFill("#fff").drawRect(-c/2,-b/2,c,b):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);e.hitArea=f;return e}
function createSprite(a,c,b,e,f,d){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-e,f,d);a.hitArea=c;return a}function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function shuffle(a){for(var c=a.length,b,e;0!==c;)e=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[e],a[e]=b;return a}
function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=parseFloat(a-60*c).toFixed(1);var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,c){var b,e;b=getBounds(a,.9);e=getBounds(c,.98);return calculateIntersection(b,e)}
function calculateIntersection(a,c){var b,e,f,d,g,h,k,l;b=a.x+(f=a.width/2);e=a.y+(d=a.height/2);g=c.x+(h=c.width/2);k=c.y+(l=c.height/2);b=Math.abs(b-g)-(f+h);e=Math.abs(e-k)-(d+l);return 0>b&&0>e?(b=Math.min(Math.min(a.width,c.width),-b),e=Math.min(Math.min(a.height,c.height),-e),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:b,height:e,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var e=a.children,f=e.length,d,g;for(g=0;g<f;g++)d=getBounds(e[g],1),d.x<b.x&&(b.x=d.x),d.y<b.y&&(b.y=d.y),d.x+d.width>b.x2&&(b.x2=d.x+d.width),d.y+d.height>b.y2&&(b.y2=d.y+d.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var h,k;a instanceof createjs.Bitmap?
(f=a.sourceRect||a.image,g=f.width*c,h=f.height*c):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(f=a.spriteSheet.getFrame(a.currentFrame),g=f.rect.width,h=f.rect.height,e=f.regX,k=f.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);e=e||0;g=g||0;k=k||0;h=h||0;b.regX=e;b.regY=k;f=a.localToGlobal(0-e,0-k);d=a.localToGlobal(g-e,h-k);g=a.localToGlobal(g-e,0-k);e=a.localToGlobal(0-e,h-k);b.x=Math.min(Math.min(Math.min(f.x,
d.x),g.x),e.x);b.y=Math.min(Math.min(Math.min(f.y,d.y),g.y),e.y);b.width=Math.max(Math.max(Math.max(f.x,d.x),g.x),e.x)-b.x;b.height=Math.max(Math.max(Math.max(f.y,d.y),g.y),e.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function playSound(a,c,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:c}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}
function setVolume(a,c){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=c}function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(c)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var e=c[b].split("=");if(e[0]==a)return e[1]}}
function distanceV2(a,c){var b=a.x-c.x,e=a.y-c.y;return Math.sqrt(b*b+e*e)}function randomRange(a,c){return Math.floor(Math.random()*(c-a))+a}function saveItem(a,c){localStorage.setItem(a,c)}function getItem(a){return localStorage.getItem(a)}function clearAllItem(){localStorage.clear()}function centerBetweenPointsV2(a,c){var b=new CVector2;b.set(.5*(a.getX()+c.getX()),.5*(a.getY()+c.getY()));return b}function perpProductV2(a,c){return a.getX()*c.getY()-a.getY()*c.getX()}
function dotProductV2(a,c){return a.getX()*c.getX()+a.getY()*c.getY()}function inSegment(a,c){if(c.getPointA().x!=c.getPointB().getX()){if(c.getPointA().getX()<=a.getX()&&a.getX()<=c.getPointB().getX()||c.getPointA().getX()>=a.getX()&&a.getX()>=c.getPointB().getX())return 1}else if(c.getPointA().getY()<=a.getY()&&a.getY()<=c.getPointB().getY()||c.getPointA().getY()>=a.getY()&&a.getY()>=c.getPointB().getY())return 1;return 0}
function intersect2D_Segments(a,c,b,e){var f=new CVector2,d=new CVector2,g=new CVector2;f.set(a.getPointB().getX()-a.getPointA().getX(),a.getPointB().getY()-a.getPointA().getY());d.set(c.getPointB().getX()-c.getPointA().getX(),c.getPointB().getY()-c.getPointA().getY());g.set(a.getPointA().getX()-c.getPointA().getX(),a.getPointA().getY()-c.getPointA().getY());var h=perpProductV2(f,d);if(1E-8>Math.abs(h)){f=dotProductV2(f,f);h=dotProductV2(d,d);if(0==f&&0==h){if(a.getPointA().getX()!=c.getPointA().getX()||
a.getPointA().getY()!=c.getPointA().getY())return 0;a.getPointA();return 1}if(0==f){if(0==inSegment(a.getPointA(),c))return 0;a.getPointA();return 1}if(0==h){if(0==inSegment(c.getPointA(),a))return 0;c.getPointA();return 1}f=new CVector2;f.set(a.getPointB().getX()-c.getPointA().getX(),a.getPointB().getY()-c.getPointA().getY());0!=d.getX()?(a=g.getX()/d.getX(),g=f.getX()/d.getX()):(a=g.getY()/d.getY(),g=f.getY()/d.getY());a>g&&(f=a,a=g,g=f);if(1<a||0>g)return 0;a=0>a?0:a;g=1<g?1:g;if(a==g)return b.set(c.getPointA().getX()+
a*d.getX(),c.getPointA().getY()+a*d.getY()),1;b.set(c.getPointA().getX()+a*d.getX(),c.getPointA().getY()+a*d.getY());e.set(c.getPointA().getX()+g*d.getX(),c.getPointA().getY()+g*d.getY());return 2}c=perpProductV2(d,g)/h;if(0>c||1<c)return 0;e=perpProductV2(f,g)/h;if(0>e||1<e)return 0;b.set(a.getPointA().getX()+c*f.getX(),a.getPointA().getY()+c*f.getY());trace("####################");trace("S1.getPointA().getX() + sI * u.x: "+b.getX());return 1}
function getRandomColor(){return"rgba("+(Math.floor(127*Math.random()+255)-127)+","+(Math.floor(127*Math.random()+255)-127)+","+(Math.floor(127*Math.random()+255)-127)+",1)"}function colorLuminance(a,c){a=String(a).replace(/[^0-9a-f]/gi,"");6>a.length&&(a=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);c=c||0;var b="#",e,f;for(f=0;3>f;f++)e=parseInt(a.substr(2*f,2),16),e=Math.round(Math.min(Math.max(0,e+e*c),255)).toString(16),b+=("00"+e).substr(e.length);return b}function linearLerp(a,c,b){return(1-b)*a+b*c}
function colorLerpShape(a,c,b,e,f,d,g,h,k,l){var m={},n=createjs.Tween.get(c,{override:!0}).wait(e).to({lerp:b.lerp},f,g).call(function(){null!==l&&l();createjs.Tween.removeTweens(n)}).addEventListener("change",function(){var a=parseInt(linearLerp(c.r,b.r,c.lerp)),f=parseInt(linearLerp(c.g,b.g,c.lerp)),e=parseInt(linearLerp(c.b,b.b,c.lerp));m[k]="rgba("+a+","+f+","+e+",1)";d(h,m)})}
function hexToRgb(a){return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16)}:null}
function BoundingBoxEdge(a){for(var c=a[0].getPointA().getX(),b=a[0].getPointA().getY(),e=a[0].getPointA().getX(),f=a[0].getPointA().getY(),d=1;d<a.length;d++)a[d].getPointA().getX()<c?c=a[d].getPointA().getX():a[d].getPointA().getX()>e&&(e=a[d].getPointA().getX()),a[d].getPointA().getY()<b?b=a[d].getPointA().getY():a[d].getPointA().getY()>f&&(f=a[d].getPointA().getY());return{xMin:c,yMin:b,xMax:e,yMax:f}}
function BoundingBox(a){for(var c=a[0].x,b=a[0].y,e=a[0].x,f=a[0].y,d=1;d<a.length;d++)a[d].x<c?c=a[d].x:a[d].x>e&&(e=a[d].x),a[d].y<b?b=a[d].y:a[d].y>f&&(f=a[d].y);return{xMin:c,yMin:b,xMax:e,yMax:f}}
function CSpriteLibrary(){var a,c,b,e,f,d;this.init=function(g,h,k){b=c=0;e=g;f=h;d=k;a={}};this.addSprite=function(b,f){a.hasOwnProperty(b)||(a[b]={szPath:f,oSprite:new Image},c++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(d)};this._onSpriteLoaded=function(){e.call(d);++b==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=840,CANVAS_HEIGHT=1360,CANVAS_WIDTH_HALF=.5*CANVAS_WIDTH,CANVAS_HEIGHT_HALF=.5*CANVAS_HEIGHT,EDGEBOARD_X=72,EDGEBOARD_Y=170,CONFIRMATION_EXIT=0,CONFIRMATION_RESET=1,DISABLE_SOUND_MOBILE=!1,FONT_GAME="Odin-Bold",TEXT_COLOR="#fff",TEXT_COLOR_STROKE="#555555",TEXT_COLOR_BEST_SORE="#fff",FPS_TIME=1E3/30,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_INIT=0,STATE_PLAY=1,STATE_FINISH=2,STATE_PAUSE=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=
4,ON_DRAG_END=5,ON_BUT_NO_DOWN=6,ON_BUT_YES_DOWN=7,NUM_OF_EDGES_FOR_STACK=4,SHOW_EDGES=!0,SHOW_FILL=!0,LEFT_UP=3,RIGHT_UP=2,LEFT_DOWN=1,RIGHT_DOWN=0,NO_DIR=4,EDGE_RIGHT_UP=0,EDGE_RIGHT_DOWN=1,EDGE_LEFT_DOWN=2,EDGE_LEFT_UP=3,STACK_DIRECTIONS={x:.5,y:.5},MS_FADE_ANIM=250,MS_SCROLL_CONTAINER_STACK=750,MS_PERFECT_TEXT=1E3,PERFECT_TEXT_START_POINT={x:CANVAS_WIDTH_HALF,y:CANVAS_HEIGHT-150},PERFECT_TEXT_END_POINT={x:CANVAS_WIDTH_HALF,y:CANVAS_HEIGHT-300},MS_WAIT_SHOW_GAME_OVER_PANEL=500,PLANES_COLOR_1={r:200,
g:0,b:0,a:1},LINES_COLOR_1={r:0,g:200,b:0,a:1},PLANES_COLOR_2={r:0,g:0,b:200,a:1},LINES_COLOR_2={r:255,g:255,b:0,a:1},MS_TIME_ZOOM_OUT=1E3,MS_TIME_PERFECT_HIT=500,CONTAINER_STACK_POS={x:CANVAS_WIDTH_HALF,y:CANVAS_HEIGHT_HALF},LINES_WIDTH=1,ANGLE_STACK=Math.PI/180*35,DEFAULT_DIR={x:Math.cos(ANGLE_STACK),y:Math.sin(ANGLE_STACK)},DIRECTION_STACKS=[DEFAULT_DIR,{x:-DEFAULT_DIR.x,y:DEFAULT_DIR.y},{x:DEFAULT_DIR.x,y:-DEFAULT_DIR.y},{x:-DEFAULT_DIR.x,y:-DEFAULT_DIR.y},{x:0,y:0}],STACK_DIMENSION={x:200,y:140},
STACK_DEPTH_SIZE=50,STACK_HEIGHT_OFFSET=100,STACK_HEIGHT_OFFSET_HALF=.5*STACK_HEIGHT_OFFSET,STACKS_DISTANCE_OFFSET=300,PERFECT_RANGE=10,DEFAULT_COLOR=["#cc0000","#00cc00","#0000cc","#ffff00"],DEPTH_LUMINANCE=-.2,COLOR_GRADIENTS_STACKS="#FF5858 #FF6058 #FF6958 #FF7158 #FF7A58 #FF8358 #FF8B58 #FF9458 #FF9D58 #FFA558 #FFAE58 #FFB658 #FFBF58 #FFC858 #FFD058 #FFD958 #FFE258 #F4E358 #EAE559 #DFE659 #D5E85A #CAEA5B #C0EB5B #B5ED5C #ABEF5D #A0F05D #96F25E #8BF35E #81F55F #76F760 #6CF860 #61FA61 #57FC62 #5AF26B #5DE975 #60E07E #64D788 #67CE91 #6AC49B #6DBBA4 #71B2AE #74A9B7 #77A0C1 #7A96CA #7E8DD4 #8184DD #847BE7 #8772F0 #8B69FA #9267EF #9A66E4 #A265D9 #A964CE #B163C4 #B962B9 #C161AE #C85FA3 #D05E98 #D85D8E #E05C83 #E75B78 #EF5A6D #F75962 #FF5858".split(" "),
SHOW_CUT_EDGES=!1,STACKS_LIMIT_POSITION=[{x:966,y:620},{x:425,y:598},{x:942,y:236.5},{x:426,y:242}],STACKS_START_POSITION=[{x:426,y:242,dir:LEFT_UP},{x:942,y:236.5,dir:LEFT_DOWN}],START_EDGES_POSITION=[{startX:0,startY:-STACK_DIMENSION.y,endX:STACK_DIMENSION.x,endY:0,type:EDGE_RIGHT_UP},{startX:STACK_DIMENSION.x,startY:0,endX:0,endY:STACK_DIMENSION.y,type:EDGE_RIGHT_DOWN},{startX:0,startY:STACK_DIMENSION.y,endX:-STACK_DIMENSION.x,endY:0,type:EDGE_LEFT_DOWN},{startX:-STACK_DIMENSION.x,startY:0,endX:0,
endY:-STACK_DIMENSION.y,type:EDGE_LEFT_UP}],ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;TEXT_GAMEOVER="GAME OVER";TEXT_COMMANDS="CONTROLS";TEXT_COMPLETE="COMPLETE";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";TEXT_SCORE="SCORE";TEXT_BEST_SCORE="BEST SCORE";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_CONTROLS="CONTROLS";TEXT_PERFECT="PERFECT";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var a,c,b,e,f,d,g,h,k;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.png");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();k=new createjs.Container;s_oStage.addChild(k)};this.unload=function(){k.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(d).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){g=new createjs.Shape;g.graphics.beginFill(COLOR_GRADIENTS_STACKS[Math.floor(Math.random()*COLOR_GRADIENTS_STACKS.length)]).drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.addChild(g);h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));k.addChild(h);var l=s_oSpriteLibrary.getSprite("progress_bar");e=createBitmap(l);e.x=CANVAS_WIDTH/
2-l.width/2;e.y=CANVAS_HEIGHT-200;k.addChild(e);a=l.width;c=l.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,1,c);k.addChild(f);e.mask=f;b=new createjs.Text("","30px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-200;b.textBaseline="alphabetic";b.textAlign="center";k.addChild(b);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;k.addChild(d)};this.refreshLoader=function(d){b.text=d+"%";f.graphics.clear();
d=Math.floor(d*a/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,d,c)};this._init()}
function CMain(a){var c,b=0,e=0,f=STATE_LOADING,d,g,h;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_oStage.preventSelection=!1;s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader;c=!0};this.soundLoaded=function(){b++;g.refreshLoader(Math.floor(b/e*100));b===e&&this._onRemovePreloader()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.ogg",
"click"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/cut.ogg","cut"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/perfect.ogg","perfect")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.mp3","click"),createjs.Sound.registerSound("./sounds/soundtrack.mp3",
"soundtrack"),createjs.Sound.registerSound("./sounds/cut.mp3","cut"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/perfect.mp3","perfect")),e+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("but_restart_small",
"./sprites/but_restart_small.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.png");s_oSpriteLibrary.addSprite("bg_game",
"./sprites/bg_game.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.addSprite("bg_score","./sprites/bg_score.png");s_oSpriteLibrary.addSprite("bg_bestscore","./sprites/bg_bestscore.png");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=
function(){b++;g.refreshLoader(Math.floor(b/e*100));b===e&&this._onRemovePreloader()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();c=!0};this._onRemovePreloader=function(){g.unload();isIOS()||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1}));this.gotoMenu()};this.gotoMenu=function(){new CMenu;
f=STATE_MENU};this.gotoGame=function(){h=new CGame(d);f=STATE_GAME};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.gotoCongratulations=function(a,b){new CCongratulations(a,b);f=STATE_MENU};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=
function(a){if(!1!==c){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;d=a;ENABLE_CHECK_ORIENTATION=d.check_orientation;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_bFullscreen=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oAdsLevel=1,s_iBestScore,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null;
function CTextButton(a,c,b,e,f,d,g,h){var k,l,m,n;this._init=function(a,b,f,c,e,d,g){k=[];l=[];var h=createBitmap(f),p=Math.ceil(g/20),t=new createjs.Text(c,"bold "+g+"px "+e,"#000000");t.textAlign="center";t.textBaseline="alphabetic";var q=t.getBounds();t.x=f.width/2+p;t.y=Math.floor(f.height/2)+q.height/3+p;c=new createjs.Text(c,"bold "+g+"px "+e,d);c.textAlign="center";c.textBaseline="alphabetic";q=c.getBounds();c.x=f.width/2;c.y=Math.floor(f.height/2)+q.height/3;m=new createjs.Container;m.x=a;
m.y=b;m.regX=f.width/2;m.regY=f.height/2;m.addChild(h,t,c);s_bMobile||(m.cursor="pointer");n.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown");m.off("pressup");n.removeChild(m)};this.setVisible=function(a){m.visible=a};this._initListener=function(){oParent=this;m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,f){k[a]=b;l[a]=f};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;playSound("click",1,0);k[ON_MOUSE_UP]&&
k[ON_MOUSE_UP].call(l[ON_MOUSE_UP])};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.setPosition=function(a,b){m.x=a;m.y=b};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};n=h;this._init(a,c,b,e,f,d,g);return this}
function CToggle(a,c,b,e,f){var d,g,h,k,l;this._init=function(a,b,f,c,e){l=void 0!==e?e:s_oStage;g=[];h=[];e=new createjs.SpriteSheet({images:[f],frames:{width:f.width/2,height:f.height,regX:f.width/2/2,regY:f.height/2},animations:{state_true:[0],state_false:[1]}});d=c;k=createSprite(e,"state_"+d,f.width/2/2,f.height/2,f.width/2,f.height);k.x=a;k.y=b;k.stop();s_bMobile||(k.cursor="pointer");l.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",
this.buttonRelease);l.removeChild(k)};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,f){g[a]=b;h[a]=f};this.setCursorType=function(a){k.cursor=a};this.setActive=function(a){d=a;k.gotoAndStop("state_"+d)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("click",1,0);d=!d;k.gotoAndStop("state_"+d);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(h[ON_MOUSE_UP],d)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=
.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=function(a,b){k.x=a;k.y=b};this._init(a,c,b,e,f)}
function CGfxButton(a,c,b,e){var f,d,g,h,k,l,m,n=!1,q;this._init=function(a,b,c){f=[];d=[];g=createBitmap(c);g.x=a;g.y=b;l=k=1;g.regX=c.width/2;g.regY=c.height/2;s_bMobile||(g.cursor="pointer");q.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);q.removeChild(g)};this.setVisible=function(a){g.visible=a};this.setCursorType=function(a){g.cursor=a};this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",
this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;d[a]=c};this.addEventListenerWithParams=function(a,b,c,e){f[a]=b;d[a]=c;h=e};this.buttonRelease=function(){n||(g.scaleX=0<k?1:-1,g.scaleY=1,playSound("click",1,0),f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(d[ON_MOUSE_UP],h))};this.buttonDown=function(){n||(g.scaleX=0<k?.9:-.9,g.scaleY=.9,f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(d[ON_MOUSE_DOWN],h))};this.rotation=function(a){g.rotation=a};this.getButton=function(){return g};this.setPosition=
function(a,b){g.x=a;g.y=b};this.setX=function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.block=function(a){n=a;g.scaleX=k;g.scaleY=l};this.setScaleX=function(a){k=g.scaleX=a};this.getX=function(){return g.x};this.getY=function(){return g.y};this.pulseAnimation=function(){createjs.Tween.get(g).to({scaleX:.9*k,scaleY:.9*l},850,createjs.Ease.quadOut).to({scaleX:k,scaleY:l},650,createjs.Ease.quadIn).call(function(){m.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(g).to({rotation:5},
75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){m.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(g)};q=e;this._init(a,c,b);m=this;return this}
function CMenu(){var a,c,b,e,f,d,g,h,k,l,m,n,q,p,v,x,y,t=null,z=null,A;this._init=function(){s_iBestScore=getItem("box_best_score");null===s_iBestScore&&(s_iBestScore=0);var r=Math.floor(Math.random()*COLOR_GRADIENTS_STACKS.length);k=new createjs.Shape;k.graphics.beginFill(COLOR_GRADIENTS_STACKS[r]).drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(k);l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(l);x=new createjs.Container;s_oStage.addChild(x);for(var u=[],w=0;w<
NUM_OF_EDGES_FOR_STACK;w++)u.push(new CEdge(1.3*START_EDGES_POSITION[w].startX,1.3*START_EDGES_POSITION[w].startY,1.3*START_EDGES_POSITION[w].endX,1.3*START_EDGES_POSITION[w].endY));r+=32;r>=COLOR_GRADIENTS_STACKS.length&&(r-=COLOR_GRADIENTS_STACKS.length);var w=CANVAS_WIDTH_HALF-122,B=CANVAS_HEIGHT_HALF+30;new CStack({x:w+(1.3*DIRECTION_STACKS[2].x*STACK_DIMENSION.x+STACK_DEPTH_SIZE-19.5),y:B+(1.3*DIRECTION_STACKS[2].y*STACK_DIMENSION.y-12*1.3)-STACK_DEPTH_SIZE,dir:NO_DIR},{line:COLOR_GRADIENTS_STACKS[r],
plane:COLOR_GRADIENTS_STACKS[r],width:LINES_WIDTH,depth:null},u,x);new CStack({x:w,y:B,dir:NO_DIR},{line:COLOR_GRADIENTS_STACKS[r],plane:COLOR_GRADIENTS_STACKS[r],width:LINES_WIDTH,depth:null},u,x);u=s_oSpriteLibrary.getSprite("logo_menu");A=createBitmap(u);A.x=CANVAS_WIDTH_HALF+56;A.y=.5*-u.width;A.regX=.5*u.width;A.regY=.5*u.height;A.rotation=-15;s_oStage.addChild(A);u=s_oSpriteLibrary.getSprite("but_play");f=CANVAS_WIDTH/2;d=CANVAS_HEIGHT-435;m=new CGfxButton(f,d,u,s_oStage);m.addEventListener(ON_MOUSE_UP,
this._onButPlayRelease,this);m.pulseAnimation();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u=s_oSpriteLibrary.getSprite("audio_icon"),g=CANVAS_WIDTH-u.height/2-15,h=u.height/2+15,p=new CToggle(g,h,u,s_bAudioActive,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);u=s_oSpriteLibrary.getSprite("but_info");b=u.height/2+17;e=u.height/2+15;n=new CGfxButton(b,e,u,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onButInfoRelease,this);u=window.document;r=u.documentElement;t=r.requestFullscreen||
r.mozRequestFullScreen||r.webkitRequestFullScreen||r.msRequestFullscreen;z=u.exitFullscreen||u.mozCancelFullScreen||u.webkitExitFullscreen||u.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(t=!1);t&&!1===inIframe()&&(u=s_oSpriteLibrary.getSprite("but_fullscreen"),a=b+u.width/2+15,c=u.height/2+15,y=new CToggle(a,c,u,s_bFullscreen,s_oStage),y.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));v=new createjs.Container;s_oStage.addChild(v);q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,
CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(q);createjs.Tween.get(A).wait(300).to({rotation:0},1E3,createjs.Ease.cubicOut);createjs.Tween.get(A).wait(300).to({y:CANVAS_HEIGHT_HALF-96},1E3,createjs.Ease.bounceOut);createjs.Tween.get(q,{override:!0}).to({alpha:0},500,createjs.Ease.cubicOut).call(function(){q.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(f,d){n.setPosition(b+f,e+d);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(g-f,d+h);t&&!1===
inIframe()&&y.setPosition(a+f,c+d)};this.unload=function(){m.unload();m=null;n.unload();n=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;t&&!1===inIframe()&&y.unload();s_oStage.removeAllChildren();s_oMenu=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButInfoRelease=function(){new CCreditsPanel};this._onButPlayRelease=function(){!isIOS()||null!==s_oSoundTrack||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundTrack=
createjs.Sound.play("soundtrack",{loop:-1}));this.fadeAnim()};this._onFullscreen=function(){s_bFullscreen?(z.call(window.document),s_bFullscreen=!1):(t.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};this.fadeAnim=function(){var a=this;q.visible=!0;createjs.Tween.get(q,{override:!0}).to({alpha:1},MS_FADE_ANIM,createjs.Ease.cubicIn).call(function(){a.unload();s_oMain.gotoGame()})};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var c,b;function e(a){g||k!==STATE_PLAY||32!==a.keyCode||(s_oGame.onMouseDown(),g=!0);a.preventDefault();return!1}function f(a){32===a.keyCode&&(g=!1);a.preventDefault();return!1}var d=!0,g=!1,h=0,k=STATE_PAUSE,l=1,m,n,q,p=0,v,x,y,t,z,A,r,u,w;this._init=function(){$(s_oMain).trigger("start_session");$(s_oMain).trigger("start_level",1);w=[];this.restartColorGrandients();x=new createjs.Shape;x.graphics.beginFill(COLOR_GRADIENTS_STACKS[q]).drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);x.cache(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(x);var a=s_oSpriteLibrary.getSprite("bg_game");y=createBitmap(a);s_oStage.addChild(y);y.cache(0,0,a.width,a.height);z=new createjs.Container;z.tickChildren=!1;this.resetContainerStacks();s_oStage.addChild(z);u=new createjs.Shape;u.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);u.on("mousedown",this.onMouseDown);s_oStage.addChild(u);v=new CInterface;v.refreshScoreText(h);v.refreshBestScore(s_iBestScore,!1);this.createStartStacks();
t=new createjs.Shape;t.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b=c=0;s_oStage.addChild(t);s_bMobile||(document.onkeydown=e,document.onkeyup=f);this.startFade()};this.restartColorGrandients=function(){n=Math.floor(Math.random()*COLOR_GRADIENTS_STACKS.length);q=n+10;q>=COLOR_GRADIENTS_STACKS.length&&(q-=COLOR_GRADIENTS_STACKS.length)};this.startFade=function(){t.visible=!0;t.alpha=1;createjs.Tween.get(t).to({alpha:0},MS_FADE_ANIM,createjs.Ease.cubicOut).call(function(){t.visible=
!1})};this.resetContainerStacks=function(){z.x=CANVAS_WIDTH_HALF;z.y=CANVAS_HEIGHT;z.regX=CANVAS_WIDTH_HALF;z.regY=CANVAS_HEIGHT;z.scaleX=z.scaleY=1;m=z.y};this.createStartStacks=function(){for(var a=[],b=0;b<NUM_OF_EDGES_FOR_STACK;b++)a.push(new CEdge(START_EDGES_POSITION[b].startX,START_EDGES_POSITION[b].startY,START_EDGES_POSITION[b].endX,START_EDGES_POSITION[b].endY));A=new CStack({x:CANVAS_WIDTH_HALF,y:CANVAS_HEIGHT_HALF+150,dir:NO_DIR},{line:COLOR_GRADIENTS_STACKS[n],plane:COLOR_GRADIENTS_STACKS[n],
width:LINES_WIDTH,depth:null},a,z);A.setID(0);w.push(A);this.nextColorGradient();r=new CStack({x:STACKS_START_POSITION[l].x,y:STACKS_START_POSITION[l].y-STACK_DEPTH_SIZE,dir:STACKS_START_POSITION[l].dir},{line:COLOR_GRADIENTS_STACKS[n],plane:COLOR_GRADIENTS_STACKS[n],width:LINES_WIDTH,depth:null},a,z);r.setID(1);a=A.getPos();a.y-=STACK_DEPTH_SIZE;r.setLimitPosition(this.getLimitPos(a));r.setPosition(r.getLimitPosition(3-l).x,r.getLimitPosition(3-l).y);this.nextColorGradient();w.push(r)};this.zoomOutContainerStacks=
function(){var a=1/(.06*h);1<a&&(a=1);var b=z.y+(w[Math.floor(w.length-1)].getPos().y-w[0].getPos().y);createjs.Tween.get(z).to({scaleX:a,scaleY:a,y:b},MS_TIME_ZOOM_OUT,createjs.Ease.quartOut)};this.gameOver=function(){k=STATE_FINISH;r.fallEffect();this.zoomOutContainerStacks();this.visibleAllStacks();h>s_iBestScore&&(s_iBestScore=h,saveItem("box_best_score",h));v.createWinPanel(h)};this.onMouseDown=function(){r.updateEdgesPosition();var a=s_oGame.intersectionPointsStacks(A,r);!1===a.result?k===STATE_PLAY&&
s_oGame.gameOver():(s_oGame.nextColorGradient(),s_oGame.moveContainerStack(),r.updateSize(),r.cacheStack(),s_oGame.changeDirStack(),s_oGame.createNewStack(r.getEdges(),a.point,a.cut),s_oGame.addScore(1),s_oGame.animPerfectText(a.cut),s_oGame.checkVisibleStack())};this.animPerfectText=function(a){a||v.animPerfectText()};this.nextColorGradient=function(){n++;q++;n===COLOR_GRADIENTS_STACKS.length&&(n=0);q===COLOR_GRADIENTS_STACKS.length&&(q=0);x.graphics.clear();x.graphics.beginFill(COLOR_GRADIENTS_STACKS[q]).drawRect(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT).endFill();x.updateCache()};this.checkVisibleStack=function(){for(var a=p;a<w.length;a++)if(w[a].isVisible()&&w[a].getPosLocal().y>CANVAS_HEIGHT){w[a].setVisible(!1);p=a;break}};this.visibleAllStacks=function(){for(var a=0;a<w.length;a++)w[a].setVisible(!0)};this.addScore=function(a){h+=a;v.refreshScoreText(h);h>s_iBestScore&&v.refreshBestScore(h,!0)};this.intersectionPointsStacks=function(a,b){var f=1;if(b.getDirID()===LEFT_UP||b.getDirID()===RIGHT_DOWN)f=0;var c,e,d,
g,h;0===f?(c=a.getLeftDownAndRightUpEdges(),e=b.getLeftDownAndRightUpEdges(),d=b.getLeftUpAndRightDownEdges()):(c=a.getLeftUpAndRightDownEdges(),e=b.getLeftUpAndRightDownEdges(),d=b.getLeftDownAndRightUpEdges());g=this.checkIntersectionPoint(c[0],e[0]);h=this.checkIntersectionPoint(c[1],e[1]);if(0===h.result||1===h.result||0===g.result||1===g.result)return{result:!1};c=e[0].getPointA().getX()-g.vec1.getX();var k=e[1].getPointA().getX()-h.vec1.getX(),n=e[0].getPointA().getY()-g.vec1.getY(),l=e[1].getPointA().getY()-
h.vec1.getY(),t=e[0].getPointB().getX()-g.vec2.getX(),B=e[1].getPointB().getX()-h.vec2.getX();g=e[0].getPointB().getY()-g.vec2.getY();h=e[1].getPointB().getY()-h.vec2.getY();var p={x:0,y:0},m=!1,q,w,C=!1;0===f?0!==c&&0!==B?(p={x:c,y:n},Math.abs(c)>PERFECT_RANGE&&Math.abs(B)>PERFECT_RANGE&&(C=!0,q=d[1],w=new CEdge(d[1].getPointB().getX(),d[1].getPointB().getY(),d[1].getPointA().getX(),d[1].getPointA().getY(),d[1].getInfo()),this.newEdgesPosition({right:e[0],left:e[1],distance:d[1],point1:{x:c,y:n},
point2:{x:B,y:h}}),m=!0)):0!==t&&0!==k&&(p={x:k,y:l},Math.abs(t)>PERFECT_RANGE&&Math.abs(k)>PERFECT_RANGE&&(q=d[0],w=new CEdge(d[0].getPointB().getX(),d[0].getPointB().getY(),d[0].getPointA().getX(),d[0].getPointA().getY(),d[0].getInfo()),this.newEdgesPosition({right:e[1],left:e[0],distance:d[0],point1:{x:t,y:g},point2:{x:k,y:l}}),m=!0)):0!==c&&0!==B?(p={x:B,y:h},Math.abs(c)>PERFECT_RANGE&&Math.abs(B)>PERFECT_RANGE&&(q=d[0],w=new CEdge(d[0].getPointB().getX(),d[0].getPointB().getY(),d[0].getPointA().getX(),
d[0].getPointA().getY(),d[0].getInfo()),this.newEdgesPosition({right:e[0],left:e[1],distance:d[0],point1:{x:c,y:n},point2:{x:B,y:h}}),m=!0)):0!==t&&0!==k&&(C=!0,p={x:t,y:g},Math.abs(t)>PERFECT_RANGE&&Math.abs(k)>PERFECT_RANGE&&(w=new CEdge(d[1].getPointB().getX(),d[1].getPointB().getY(),d[1].getPointA().getX(),d[1].getPointA().getY(),d[1].getInfo()),q=d[1],this.newEdgesPosition({right:e[1],left:e[0],distance:d[1],point1:{x:t,y:g},point2:{x:k,y:l}}),m=!0));m&&this.cutStack(q,w,p,C);return{result:!0,
point:p,cut:m}};this.cutStack=function(a,b,f,c){var d=[];switch(r.getDirID()){case 0:case 3:c?(d.push(new CEdge(b.getPointA().getX(),b.getPointA().getY(),a.getPointB().getX(),a.getPointB().getY())),d.push(new CEdge(a.getPointB().getX(),a.getPointB().getY(),a.getPointA().getX(),a.getPointA().getY())),d.push(new CEdge(a.getPointA().getX(),a.getPointA().getY(),b.getPointB().getX(),b.getPointB().getY())),d.push(new CEdge(b.getPointB().getX(),b.getPointB().getY(),b.getPointA().getX(),b.getPointA().getY()))):
(d.push(new CEdge(a.getPointA().getX(),a.getPointA().getY(),b.getPointB().getX(),b.getPointB().getY())),d.push(new CEdge(b.getPointB().getX(),b.getPointB().getY(),b.getPointA().getX(),b.getPointA().getY())),d.push(new CEdge(b.getPointA().getX(),b.getPointA().getY(),a.getPointB().getX(),a.getPointB().getY())),d.push(new CEdge(a.getPointB().getX(),a.getPointB().getY(),a.getPointA().getX(),a.getPointA().getY())));break;case 1:case 2:c?(d.push(new CEdge(a.getPointB().getX(),a.getPointB().getY(),a.getPointA().getX(),
a.getPointA().getY())),d.push(new CEdge(a.getPointA().getX(),a.getPointA().getY(),b.getPointB().getX(),b.getPointB().getY())),d.push(new CEdge(b.getPointB().getX(),b.getPointB().getY(),b.getPointA().getX(),b.getPointA().getY())),d.push(new CEdge(b.getPointA().getX(),b.getPointA().getY(),a.getPointB().getX(),a.getPointB().getY()))):(d.push(new CEdge(b.getPointB().getX(),b.getPointB().getY(),b.getPointA().getX(),b.getPointA().getY())),d.push(new CEdge(b.getPointA().getX(),b.getPointA().getY(),a.getPointB().getX(),
a.getPointB().getY())),d.push(new CEdge(a.getPointB().getX(),a.getPointB().getY(),a.getPointA().getX(),a.getPointA().getY())),d.push(new CEdge(a.getPointA().getX(),a.getPointA().getY(),b.getPointB().getX(),b.getPointB().getY())))}a={x:r.getPos().x,y:r.getPos().y,dir:NO_DIR};if(SHOW_CUT_EDGES)for(b=0;b<d.length;b++){c=new createjs.Shape;c.graphics.beginStroke(DEFAULT_COLOR[b]);c.graphics.setStrokeStyle(LINES_WIDTH);c.graphics.moveTo(d[b].getPointA().getX(),d[b].getPointA().getY());c.graphics.lineTo(d[b].getPointB().getX(),
d[b].getPointB().getY());var e=new createjs.Shape;e.graphics.beginFill("#fff").drawCircle(d[b].getPointA().getX(),d[b].getPointA().getY(),10);var g=new createjs.Shape;g.graphics.beginFill("#000").drawCircle(d[b].getPointB().getX(),d[b].getPointB().getY(),10);z.addChild(c,g,e)}d=this.createStack(d,{x:0,y:0},a,r.getColor());0>f.x&&0>f.y?d.setChildIndex(0):0<f.x&&0>f.y&&d.setChildIndex(0);d.fallEffect()};this.newEdgesPosition=function(a){a.right.set(a.right.getPointA().getX()-a.point1.x,a.right.getPointA().getY()-
a.point1.y,a.right.getPointB().getX(),a.right.getPointB().getY());a.left.set(a.left.getPointA().getX(),a.left.getPointA().getY(),a.left.getPointB().getX()-a.point2.x,a.left.getPointB().getY()-a.point2.y);a.distance.set(a.left.getPointB().getX(),a.left.getPointB().getY(),a.right.getPointA().getX(),a.right.getPointA().getY())};this.checkIntersectionPoint=function(a,b){var f=new CVector2(0,0),d=new CVector2(0,0),c=new CEdge(a.getPointA().getX()+0,a.getPointA().getY()+0,a.getPointB().getX()+0,a.getPointB().getY()+
0),c=intersect2D_Segments(c,b,f,d);return{vec1:f,vec2:d,result:c}};this.createNewStack=function(a,f,d){d?(playSound("cut",1,0),d={x:r.getPos().x-f.x,y:r.getPos().y-STACK_DEPTH_SIZE-f.y,dir:STACKS_START_POSITION[l].dir}):(playSound("perfect",1,0),r.perfectPosition(),r.setPosition(A.getPos().x-c,A.getPos().y-b-STACK_DEPTH_SIZE),r.updateEdgesPosition(),d={x:r.getPos().x+c-f.x,y:r.getPos().y-STACK_DEPTH_SIZE+b-f.y,dir:STACKS_START_POSITION[l].dir});c=f.x;b=f.y;a=this.createStack(a,f,d,{line:COLOR_GRADIENTS_STACKS[n],
plane:COLOR_GRADIENTS_STACKS[n],width:LINES_WIDTH,depth:null});a.setLimitPosition(this.getLimitPos(d));a.setPosition(a.getLimitPosition(3-l).x,a.getLimitPosition(3-l).y);w.push(a);A=r;r=a};this.createStack=function(a,b,f,d){for(var c=r.getPos(),e=[],g=0;g<a.length;g++)e[g]=new CEdge(a[g].getPointA().getX()-c.x+b.x,a[g].getPointA().getY()-c.y+b.y,a[g].getPointB().getX()-c.x+b.x,a[g].getPointB().getY()-c.y+b.y,START_EDGES_POSITION[g].type);return new CStack(f,d,e,z)};this.changeDirStack=function(){1===
l?l=0:l++};this.moveContainerStack=function(){m+=STACK_DEPTH_SIZE;createjs.Tween.get(z,{override:!0}).to({y:m},MS_SCROLL_CONTAINER_STACK,createjs.Ease.cubicOut).call(function(){},null,this)};this.getLimitPos=function(a){for(var b=[],f=0;f<STACKS_LIMIT_POSITION.length;f++)b.push({x:a.x+DIRECTION_STACKS[f].x*STACKS_DISTANCE_OFFSET,y:a.y+DIRECTION_STACKS[f].y*STACKS_DISTANCE_OFFSET});return b};this.unload=function(){d=!1;v.unload();s_oStage.removeAllChildren();createjs.Tween.removeAllTweens()};this.onExit=
function(){$(s_oMain).trigger("end_session");$(s_oMain).trigger("end_level",1);var a=this;t.visible=!0;createjs.Tween.get(t,{override:!0}).to({alpha:1},MS_FADE_ANIM,createjs.Ease.cubicOut).call(function(){$(s_oMain).trigger("show_interlevel_ad");a.unload();setVolume(s_oSoundTrack,1);s_oMain.gotoMenu()})};this._onStart=function(){k=STATE_PLAY;setVolume(s_oSoundTrack,.3)};this.restartGame=function(){t.visible=!0;createjs.Tween.get(t,{ignoreGlobalPause:!0,override:!0}).to({alpha:1},MS_FADE_ANIM,createjs.Ease.cubicOut).call(function(){for(var a=
0;a<w.length;a++)w[a].unload();w=[];s_oGame.resetContainerStacks();A=null;h=b=c=0;v.refreshScoreText(h);s_oGame.restartColorGrandients();s_oGame.createStartStacks();s_oGame.startFade();v.refreshBestScore(s_iBestScore,!1);k=STATE_PLAY})};this.unpause=function(a){d=a};this._onEnd=function(){t.visible=!0;createjs.Tween.get(t,{ignoreGlobalPause:!0}).to({alpha:1},MS_FADE_ANIM,createjs.Ease.cubicOut).call(function(){s_oGame.unload();$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("end_session");setVolume(s_oSoundTrack,
1);s_oMain.gotoMenu()})};this._updatePlay=function(){d&&r.update(STACK_VELOCITY)};this.update=function(){switch(k){case STATE_PLAY:this._updatePlay()}};s_oGame=this;STACK_VELOCITY=a.stack_velocity;NUM_LEVEL_FOR_ADS=a.num_levels_for_ads;ENABLE_FULLSCREEN=a.fullscreen;this._init()}var s_oGame;
function CInterface(a,c){var b,e,f,d,g,h,k,l,m,n,q,p,v,x,y,t,z,A,r=null,u=null;this._init=function(){var a=s_oSpriteLibrary.getSprite("but_exit");f=CANVAS_WIDTH-a.height/2-15;d=a.height/2+15;k=new CGfxButton(f,d,a,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onExit,this);a=s_oSpriteLibrary.getSprite("but_restart_small");h={x:f-a.height-15,y:d};l=new CGfxButton(h.x,h.y,a,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onRestart,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(a=s_oSpriteLibrary.getSprite("audio_icon"),
g={x:h.x-a.height-15,y:d},p=new CToggle(g.x,g.y,a,s_bAudioActive,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)):g=h;var a=window.document,c=a.documentElement;r=c.requestFullscreen||c.mozRequestFullScreen||c.webkitRequestFullScreen||c.msRequestFullscreen;u=a.exitFullscreen||a.mozCancelFullScreen||a.webkitExitFullscreen||a.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(r=!1);r&&!1===inIframe()&&(a=s_oSpriteLibrary.getSprite("but_fullscreen"),b=g.x-a.width/2-15,e=d,A=new CToggle(b,e,
a,s_bFullscreen,s_oStage),A.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));y=new CScoreBoard(s_oStage);t=new CTextPerfect(s_oStage);this.createButStart();this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.createButStart=function(){n=new createjs.Shape;n.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);n.on("click",function(){});s_oStage.addChild(n);var a=s_oSpriteLibrary.getSprite("but_start");m=new CGfxButton(CANVAS_WIDTH_HALF,CANVAS_HEIGHT_HALF,a,s_oStage);
m.addEventListener(ON_MOUSE_UP,this._onMouseUpStart,this);m.pulseAnimation()};this.refreshButtonPos=function(a,c){k.setPosition(f-a,c+d);l.setPosition(h.x-a,c+h.y);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(g.x-a,c+g.y);var n=y.getStartPosScore();y.setPosScore(n.x+a,n.y+c);r&&!1===inIframe()&&A.setPosition(b-a,e+c);t.updatePoints(a,c)};this._onMouseUpStart=function(){n.removeAllEventListeners();s_oStage.removeChild(n);s_oGame._onStart();m.unload();m=null};this.unload=function(){k.unload();
k=null;l.unload();l=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;r&&!1===inIframe()&&A.unload();s_oInterface=null};this.createHelpPanel=function(){q=new CHelpPanel(0,0,s_oSpriteLibrary.getSprite("msg_box"))};this.createLosePanel=function(a,b){v=new CLosePanel(s_oSpriteLibrary.getSprite("bg_congratulations"));v.show(a,b,_iPlayerTeam,_iOpponentTeam)};this.createWinPanel=function(a){x=new CWinPanel(s_oSpriteLibrary.getSprite("msg_box"));x.show(a)};this.unloadHelpPanel=function(){q&&
(q.unload(),q=null)};this.createPauseInterface=function(){z=new CPause};this.refreshScoreText=function(a){y.refreshTextScore(a)};this.refreshBestScore=function(a,b){y.refreshTextBestScore(a,b)};this.animPerfectText=function(){t.animText()};this.refreshLevelText=function(a){(void 0).refreshTextLevel(a)};this.unloadPause=function(){z.unload();z=null};this.subEffect=function(a){y.effectSubtractScore(a)};this._onFullscreen=function(){s_bFullscreen?(u.call(window.document),s_bFullscreen=!1):(r.call(window.document.documentElement),
s_bFullscreen=!0);sizeHandler()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){(new CAreYouSurePanel(s_oStage)).show()};this.blockCommand=function(a){s_bMobile&&(void 0).block(a)};this._onRestart=function(){s_oGame.restartGame()};s_oInterface=this;this._init(a,c);return this}var s_oInterface=null;
function CHelpPanel(a,c,b){var e,f,d,g,h,k,l,m,n,q,p,v=!1;this._init=function(a,b,f){d=createBitmap(f);d.x=.5*CANVAS_WIDTH;d.y=.5*CANVAS_HEIGHT;d.regX=.5*f.width;d.regY=.5*f.height;g=new createjs.Container;g.x=a;g.y=b;k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=.5;g.addChild(k);g.addChild(d);s_oStage.addChild(g);g.on("pressup",function(){s_oHelpPanel._onExitHelp()},null,!0);h=new createjs.Container;h.alpha=0;this.page1(h);s_bMobile||(k.cursor=
"pointer")};this.page1=function(a){var b;b=new createjs.Text(TEXT_CONTROLS,"32px "+FONT_GAME,"#ff6000");b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT-200;b.textAlign="center";b.outline=5;a.addChild(b);var c;c=new createjs.Text(TEXT_CONTROLS,"32px "+FONT_GAME,TEXT_COLOR);c.x=.5*CANVAS_WIDTH;c.y=b.y;c.textAlign="center";a.addChild(c);e=CANVAS_WIDTH_HALF;f=340;m=new CArrow(e,f,a);m.animateMask(1E3);b=s_oSpriteLibrary.getSprite("ball");c=s_bMobile?s_oSpriteLibrary.getSprite("help_touch"):s_oSpriteLibrary.getSprite("help_mouse");
q=createBitmap(c);q.x=e-130;q.y=f-10;q.regX=.5*c.width;q.regY=.5*c.height;a.addChild(q);new CBall(e,f,null,b,a);this.animateInputPower(1E3);n=new CArrow(e,f+160,a);n.animateRotation(1E3);n.mask(100);p=createBitmap(c);p.x=e-150;p.y=f+160;p.regX=.5*c.width;p.regY=.5*c.height;a.addChild(p);new CBall(e,f+160,null,b,a);this.animateInputRotate(1E3);createjs.Tween.get(a).to({alpha:1},300,createjs.Ease.cubicOut);b=s_oSpriteLibrary.getSprite("but_continue");l=new CGfxButton(.5*CANVAS_WIDTH+310,.5*CANVAS_HEIGHT+
145,b,a);l.addEventListener(ON_MOUSE_UP,this._onExitHelp,this);l.pulseAnimation();s_oStage.addChild(a)};this.animateInputPower=function(a){createjs.Tween.get(q).to({x:e-230},a,createjs.Ease.cubicInOut).call(function(){createjs.Tween.get(q).to({x:e-130},a,createjs.Ease.cubicInOut).call(function(){s_oHelpPanel.animateInputPower(a)})})};this.animateInputRotate=function(a){createjs.Tween.get(p).to({y:f+60},a,createjs.Ease.cubicInOut).call(function(){createjs.Tween.get(p).to({y:f+180},a,createjs.Ease.cubicInOut).call(function(){s_oHelpPanel.animateInputRotate(a)})})};
this.unload=function(){s_oStage.removeChild(g,h);s_oHelpPanel=null;g.off("pressup",function(){s_oHelpPanel._onExitHelp()},null,!0);l.unload();l=null;createjs.Tween.removeAllTweens()};this._onExitHelp=function(){if(!v){v=!0;playSound("click",1,0);var a=this;createjs.Tween.get(h).to({alpha:0},300,createjs.Ease.cubicOut).call(function(){a.unload();s_oGame._onExitHelp()})}};s_oHelpPanel=this;this._init(a,c,b)}var s_oHelpPanel=null;
function CWinPanel(a,c){var b,e,f,d,g,h,k,l,m,n,q;this._init=function(a){l=new createjs.Container;l.alpha=0;l.visible=!1;var c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=.5;l.addChild(c);b=createBitmap(a);b.x=CANVAS_WIDTH_HALF;b.y=CANVAS_HEIGHT_HALF;b.regX=.5*a.width;b.regY=.5*a.height;l.addChild(b);e=new createjs.Text("","100px "+FONT_GAME,TEXT_COLOR_STROKE);e.x=CANVAS_WIDTH/2;e.y=500;e.textAlign="center";e.outline=5;l.addChild(e);f=new createjs.Text("",
"100px "+FONT_GAME,TEXT_COLOR);f.x=CANVAS_WIDTH/2;f.y=e.y;f.textAlign="center";l.addChild(f);d=new createjs.Text("","50px "+FONT_GAME,TEXT_COLOR_STROKE);d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT_HALF-50;d.textAlign="center";d.outline=5;l.addChild(d);g=new createjs.Text("","50px "+FONT_GAME,TEXT_COLOR);g.x=CANVAS_WIDTH/2;g.y=d.y;g.textAlign="center";l.addChild(g);h=new createjs.Text("","50px "+FONT_GAME,TEXT_COLOR_STROKE);h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT_HALF+50;h.textAlign="center";h.outline=5;l.addChild(h);
k=new createjs.Text("","50px "+FONT_GAME,TEXT_COLOR);k.x=CANVAS_WIDTH/2;k.y=h.y;k.textAlign="center";l.addChild(k);a=s_oSpriteLibrary.getSprite("but_restart");n=new CGfxButton(.5*CANVAS_WIDTH+290,.5*CANVAS_HEIGHT+130,a,l);n.pulseAnimation();n.addEventListener(ON_MOUSE_DOWN,this._onRestart,this);a=s_oSpriteLibrary.getSprite("but_home");m=new CGfxButton(.5*CANVAS_WIDTH-290,.5*CANVAS_HEIGHT+130,a,l);m.addEventListener(ON_MOUSE_DOWN,this._onExit,this);q=new createjs.Container;l.addChild(q);l.on("click",
function(){});s_oStage.addChild(l)};this.unload=function(){l.removeAllEventListeners();s_oStage.removeChild(l);m&&(m.unload(),m=null);n&&(n.unload(),n=null)};this.show=function(a){e.text=TEXT_GAMEOVER;f.text=TEXT_GAMEOVER;d.text=TEXT_SCORE+": "+a;g.text=TEXT_SCORE+": "+a;h.text=TEXT_BEST_SCORE+": "+s_iBestScore;k.text=TEXT_BEST_SCORE+": "+s_iBestScore;l.visible=!0;createjs.Tween.get(l).wait(MS_WAIT_SHOW_GAME_OVER_PANEL).to({alpha:1},1250,createjs.Ease.cubicOut).call(function(){s_oAdsLevel===NUM_LEVEL_FOR_ADS?
($(s_oMain).trigger("show_interlevel_ad"),s_oAdsLevel=1):s_oAdsLevel++});$(s_oMain).trigger("save_score",a);$(s_oMain).trigger("share_event",a)};this._onContinue=function(){var a=this;createjs.Tween.get(l,{override:!0}).to({alpha:0},750,createjs.Ease.cubicOut).call(function(){a.unload()});_oButContinue.block(!0);m.block(!0);s_oGame.onContinue()};this._onRestart=function(){n.block(!0);this.unload();s_oGame.restartGame()};this._onExit=function(){this.unload();s_oGame.onExit()};this._init(a,c);return this}
var _0x5059="_init;addChild;drawRect;black;beginFill;graphics;alpha;msg_box;getSprite;x;y;regX;width;regY;height;#0f0f0f;click;on;cursor;pointer;secret;but_exit;unload;addEventListener;40px ;textAlign;center;textBaseline;alphabetic;outline;logo_ctl;WWW.CODETHISLAB.COM;50px ;CREATED BY GENNARO PALLADINO EX CODETHISLAB DEVELOPER;lineWidth;getBounds;removeChild;call;cubicOut;Ease;to;wait;bounceOut;get;Tween;off;_onLogoButRelease;http://www.codethislab.com/index.php?&l=en;_blank;open".split(";");
function CCreditsPanel(){var a,c,b,e,f,d,g,h,k,l,m=0;this[_0x5059[0]]=function(){l=new createjs.Container;s_oStage[_0x5059[1]](l);var n=new createjs.Shape;n[_0x5059[5]][_0x5059[4]](_0x5059[3])[_0x5059[2]](0,0,CANVAS_WIDTH,CANVAS_HEIGHT);n[_0x5059[6]]=.6;l[_0x5059[1]](n);n=s_oSpriteLibrary[_0x5059[8]](_0x5059[7]);a=createBitmap(n);a[_0x5059[9]]=CANVAS_WIDTH_HALF;a[_0x5059[10]]=CANVAS_HEIGHT_HALF;a[_0x5059[11]]=.5*n[_0x5059[12]];a[_0x5059[13]]=.5*n[_0x5059[14]];l[_0x5059[1]](a);d=new createjs.Shape;
d[_0x5059[5]][_0x5059[4]](_0x5059[15])[_0x5059[2]](0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d[_0x5059[6]]=.01;d[_0x5059[17]](_0x5059[16],this._onLogoButRelease);d[_0x5059[18]]=_0x5059[19];l[_0x5059[1]](d);n=new createjs.Shape;n[_0x5059[5]][_0x5059[4]](_0x5059[15])[_0x5059[2]](CANVAS_WIDTH-2*EDGEBOARD_X,CANVAS_HEIGHT-2*EDGEBOARD_Y,2*EDGEBOARD_X,2*EDGEBOARD_Y);n[_0x5059[6]]=.01;n[_0x5059[17]](_0x5059[16],this[_0x5059[20]]);n[_0x5059[18]]=_0x5059[19];l[_0x5059[1]](n);n=s_oSpriteLibrary[_0x5059[8]](_0x5059[21]);
k={x:.5*CANVAS_WIDTH+330,y:510};b=new CGfxButton(k[_0x5059[9]],k[_0x5059[10]],n,l);b[_0x5059[23]](ON_MOUSE_UP,this[_0x5059[22]],this);f=new createjs.Text(TEXT_CREDITS_DEVELOPED,_0x5059[24]+FONT_GAME,TEXT_COLOR_STROKE);f[_0x5059[25]]=_0x5059[26];f[_0x5059[27]]=_0x5059[28];f[_0x5059[9]]=CANVAS_WIDTH/2;f[_0x5059[10]]=560;f[_0x5059[29]]=1;l[_0x5059[1]](f);e=new createjs.Text(TEXT_CREDITS_DEVELOPED,_0x5059[24]+FONT_GAME,TEXT_COLOR);e[_0x5059[25]]=_0x5059[26];e[_0x5059[27]]=_0x5059[28];e[_0x5059[9]]=f[_0x5059[9]];
e[_0x5059[10]]=f[_0x5059[10]];l[_0x5059[1]](e);n=s_oSpriteLibrary[_0x5059[8]](_0x5059[30]);c=createBitmap(n);c[_0x5059[11]]=n[_0x5059[12]]/2;c[_0x5059[13]]=n[_0x5059[14]]/2;c[_0x5059[9]]=CANVAS_WIDTH/2;c[_0x5059[10]]=f[_0x5059[10]]+100;l[_0x5059[1]](c);h=new createjs.Text(_0x5059[31],_0x5059[32]+FONT_GAME,TEXT_COLOR_STROKE);h[_0x5059[25]]=_0x5059[26];h[_0x5059[27]]=_0x5059[28];h[_0x5059[9]]=CANVAS_WIDTH/2;h[_0x5059[10]]=f[_0x5059[10]]+240;h[_0x5059[29]]=1;l[_0x5059[1]](h);g=new createjs.Text(_0x5059[31],
_0x5059[32]+FONT_GAME,TEXT_COLOR);g[_0x5059[25]]=_0x5059[26];g[_0x5059[27]]=_0x5059[28];g[_0x5059[9]]=h[_0x5059[9]];g[_0x5059[10]]=h[_0x5059[10]];l[_0x5059[1]](g)};this[_0x5059[20]]=function(){if(5===m){var a=new createjs.Text(_0x5059[33],_0x5059[24]+FONT_GAME,TEXT_COLOR);a[_0x5059[25]]=_0x5059[26];a[_0x5059[27]]=_0x5059[28];a[_0x5059[34]]=500;var b=new createjs.Text(_0x5059[33],_0x5059[24]+FONT_GAME,TEXT_COLOR_STROKE);b[_0x5059[25]]=_0x5059[26];b[_0x5059[27]]=_0x5059[28];b[_0x5059[34]]=500;b[_0x5059[29]]=
1;var c=new createjs.Container;c[_0x5059[1]](a);c[_0x5059[1]](b);c[_0x5059[9]]=CANVAS_WIDTH_HALF;c[_0x5059[10]]=-a[_0x5059[35]]()[_0x5059[14]];l[_0x5059[1]](c);createjs[_0x5059[44]][_0x5059[43]](c)[_0x5059[40]]({y:CANVAS_HEIGHT_HALF+300},1E3,createjs[_0x5059[39]][_0x5059[42]])[_0x5059[41]](3E3)[_0x5059[40]]({alpha:0},1E3,createjs[_0x5059[39]][_0x5059[38]])[_0x5059[37]](function(){l[_0x5059[36]](a);m=0})}m++};this[_0x5059[22]]=function(){d[_0x5059[45]](_0x5059[16],this._onLogoButRelease);b[_0x5059[22]]();
b=null;s_oStage[_0x5059[36]](l)};this[_0x5059[46]]=function(){window[_0x5059[49]](_0x5059[47],_0x5059[48])};this._init()}
function CPause(){var a;this._init=function(){var c=new createjs.Container;c.alpha=0;a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=.5;var b=new createjs.Shape;b.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.hitArea=b;a.on("click",function(){});c.addChild(a);b=new createjs.Text(TEXT_PAUSE,"50px "+FONT_GAME,"#000000");b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT-130;b.textAlign="center";b.outline=5;c.addChild(b);var e=new createjs.Text(TEXT_PAUSE,
"50px "+FONT_GAME,TEXT_COLOR);e.x=b.x;e.y=b.y;e.textAlign="center";c.addChild(e);b=s_oSpriteLibrary.getSprite("but_continue");(new CGfxButton(.5*CANVAS_WIDTH,.5*CANVAS_HEIGHT+70,b,c)).addEventListenerWithParams(ON_MOUSE_UP,this._onLeavePause,this,c);s_oStage.addChild(c);createjs.Tween.get(c).to({alpha:1},300,createjs.quartOut)};this.unload=function(){a.off("click",function(){});s_oStage.removeChild(void 0)};this._onLeavePause=function(a){createjs.Tween.get(a).to({alpha:0},300,createjs.quartIn).call(function(){s_oInterface.unloadPause();
s_oGame.unpause(!0)})};this._init();return this}
function CAreYouSurePanel(a){var c,b,e,f,d,g;this._init=function(){d=new createjs.Container;d.alpha=0;g.addChild(d);var a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=.5;d.addChild(a);var a=s_oSpriteLibrary.getSprite("msg_box"),k=createBitmap(a);k.x=CANVAS_WIDTH_HALF;k.y=CANVAS_HEIGHT_HALF;k.regX=.5*a.width;k.regY=.5*a.height;d.addChild(k);c=new createjs.Text(TEXT_ARE_SURE,"80px "+FONT_GAME,TEXT_COLOR_STROKE);c.x=CANVAS_WIDTH/2;c.y=550;c.textAlign=
"center";c.textBaseline="middle";c.outline=1;d.addChild(c);b=new createjs.Text(c.text,"80px "+FONT_GAME,TEXT_COLOR);b.x=c.x;b.y=c.y;b.textAlign="center";b.textBaseline="middle";d.addChild(b);d.on("click",function(){});e=new CGfxButton(CANVAS_WIDTH/2+280,CANVAS_HEIGHT_HALF+120,s_oSpriteLibrary.getSprite("but_yes"),d);e.addEventListener(ON_MOUSE_UP,this._onButYes,this);f=new CGfxButton(CANVAS_WIDTH/2-280,CANVAS_HEIGHT_HALF+120,s_oSpriteLibrary.getSprite("but_no"),d);f.addEventListener(ON_MOUSE_UP,this._onButNo,
this);f.pulseAnimation()};this.show=function(){s_oGame.unpause(!1);createjs.Tween.get(d,{ignoreGlobalPause:!0}).to({alpha:1},500,createjs.Ease.cubicOut)};this._onButYes=function(){s_oGame.unpause(!0);this.unload();s_oGame.onExit()};this._onButNo=function(){var a=this;createjs.Tween.get(d,{ignoreGlobalPause:!0}).to({alpha:0},500,createjs.Ease.cubicOut).call(function(){s_oGame.unpause(!0);a.unload()})};this.unload=function(){e.unload();e=null;f.unload();f=null;d.removeAllEventListeners();s_oStage.removeChild(d)};
g=a;this._init()}
function CVector2(a,c){var b,e;this._init=function(a,c){b=a;e=c};this.add=function(a,c){b+=a;e+=c};this.addV=function(a){b+=a.getX();e+=a.getY()};this.scalarDivision=function(a){b/=a;e/=a};this.subtract=function(a){b-=a.getX();e-=a.getY()};this.scalarProduct=function(a){b*=a;e*=a};this.invert=function(){b*=-1;e*=-1};this.dotProduct=function(a){return b*a.getX()+e*a.getY()};this.set=function(a,c){b=a;e=c};this.setV=function(a){b=a.getX();e=a.getY()};this.length=function(){return Math.sqrt(b*b+e*e)};
this.length2=function(){return b*b+e*e};this.normalize=function(){var a=this.length();0<a&&(b/=a,e/=a)};this.angleBetweenVectors=function(a){a=Math.acos(this.dotProduct(a)/(this.length()*a.length()));return!0===isNaN(a)?0:a};this.getNormalize=function(a){this.length();a.set(b,e);a.normalize()};this.rot90CCW=function(){var a=b;b=-e;e=a};this.rot90CW=function(){var a=b;b=e;e=-a};this.getRotCCW=function(a){a.set(b,e);a.rot90CCW()};this.getRotCW=function(a){a.set(b,e);a.rot90CW()};this.ceil=function(){b=
Math.ceil(b);e=Math.ceil(e)};this.round=function(){b=Math.round(b);e=Math.round(e)};this.toString=function(){return"Vector2: "+b+", "+e};this.print=function(){trace("Vector2: "+b+", "+e+"")};this.getX=function(){return b};this.getY=function(){return e};this.rotate=function(a){var c=b,f=e;b=c*Math.cos(a)+f*Math.sin(a);e=c*-Math.sin(a)+f*Math.cos(a)};this._init(a,c)}
function CEdge(a,c,b,e,f){var d=null,g=null,h=null,k=null,l=null,m=null;this._init=function(a,b,c,d,f){this.set(a,b,c,d);m=f};this.destroy=function(){l=k=h=g=d=null};this.render=function(a){a.moveTo(d.x,d.y);a.lineTo(g.x,g.y)};this.toString=function(a){trace(a+" "+d.x+" "+d.y+" "+g.x+" "+g.y)};this.add=function(a){d.addV(a);g.addV(a)};this.set=function(a,b,c,f){d=new CVector2;g=new CVector2;d.set(a,b);g.set(c,f);this.calculateNormal();this.calculateCenter()};this.scale=function(a){d.scalarProduct(a);
g.scalarProduct(a);this.calculateNormal();this.calculateCenter()};this.calculateNormal=function(){l=null;l=new CVector2;l.setV(g);l.subtract(d);l.rot90CCW();l.normalize()};this.calculateCenter=function(){h=null;h=centerBetweenPointsV2(d,g);k=new CVector2;k.setV(l);k.scalarProduct(5);k.addV(h)};this.getPointA=function(){return d};this.m_pCenter=function(){return h};this.getPointB=function(){return g};this.getNormal=function(){return l};this.getInfo=function(){return f};this.toString=function(){return"A: "+
d.toString()+" B: "+g.toString()+" oInfo: "+m};this.renderNormal=function(a){a.moveTo(h.x,h.y);a.lineTo(k.x,k.y)};this._init(a,c,b,e,f);return this}
function CScoreBoard(a){var c,b,e,f,d,g,h,k,l,m;this._init=function(){k=new createjs.Container;l=new createjs.Container;l.x=-360;l.y=120;c={x:.5*CANVAS_WIDTH,y:61};h=new createjs.Container;h.x=c.x;h.y=c.y;a.addChild(h);h.addChild(l,k);f=new createjs.Text("999","40px "+FONT_GAME,TEXT_COLOR_STROKE);f.textAlign="center";f.textBaseline="middle";f.x=-7;f.outline=3;k.addChild(f);e=new createjs.Text("999","40px "+FONT_GAME,TEXT_COLOR);e.textAlign="center";e.textBaseline="middle";e.x=f.x;k.addChild(e);var n=
s_oSpriteLibrary.getSprite("bg_score"),q=createBitmap(n);q.regX=.5*n.width;q.regY=.5*n.height;k.addChild(q);k.x=-360;g=new createjs.Text("25","40px "+FONT_GAME,TEXT_COLOR_STROKE);g.textAlign="center";g.textBaseline="middle";g.outline=3;g.x=-5;l.addChild(g);d=new createjs.Text("25","40px "+FONT_GAME,TEXT_COLOR);d.textAlign="center";d.textBaseline="middle";d.x=g.x;l.addChild(d);b={x:l.x,y:0};n=this.createStar();l.addChild(n);m=this.createStar();m.visible=!1;m.alpha=0;l.addChild(m)};this.createStar=
function(){var a=s_oSpriteLibrary.getSprite("bg_bestscore"),a=new createjs.SpriteSheet({images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{normal:[0],active:[1]}}),a=createSprite(a,"normal",a.width/2/2,a.height/2,a.width/2,a.height);a.y=-5;a.x=5;return a};this.getStartPosScore=function(){return c};this.getStartPosBestScore=function(){return b};this.setBestScorePos=function(a,b){l.x=a;l.y=b};this.setPosScore=function(a,b){h.x=a;h.y=b};this.refreshTextBestScore=
function(a,b){d.text=a;g.text=a;b&&(m.visible=!0,createjs.Tween.get(m,{override:!0}).to({alpha:1},250,createjs.Ease.cubicOut).to({alpha:0},250,createjs.Ease.cubicIn).set({visible:!1}))};this.refreshTextScore=function(a){e.text=a;f.text=a};this._init();return this}
function CStack(a,c,b,e){var f,d,g,h,k,l,m=0,n,q,p,v,x,y;this._init=function(a,b,c){p=new createjs.Container;e.addChild(p);v=new createjs.Shape;x=new createjs.Shape;y=b;m=a.dir;l=new CVector2(DIRECTION_STACKS[a.dir].x,DIRECTION_STACKS[a.dir].y);k=[];this.setPosition(a.x,a.y);this.setEdges(c,{x:p.x,y:p.y});this.updateSize();p.addChild(v);p.addChild(x)};this.setLimitPosition=function(a){for(var b=0;b<a.length;b++)k.push(a[b])};this.getLimitPosition=function(a){return k[a]};this.getAllLimitPosition=
function(){return k};this.getLeftDownAndRightUpEdges=function(){return d};this.getLeftUpAndRightDownEdges=function(){return g};this.setDir=function(a){l.set(a.x,a.y)};this.getDir=function(){return l};this.isVisible=function(){return p.visible};this.setVisible=function(a){p.visible=a};this.getPosLocal=function(){return e.localToGlobal(p.x,p.y)};this.getDirID=function(){return m};this.getID=function(){return n};this.setID=function(a){n=a};this.cacheStack=function(){};this.updateCache=function(){};this.updateSize=
function(){this.createGraph(f,y);this.createDepthEdge();this.updateDepthEffect(h,y,!0)};this.createDepthEdge=function(){h=[];h.push({x:f[1].getPointA().getX(),y:f[1].getPointA().getY()});h.push({x:f[1].getPointB().getX(),y:f[1].getPointB().getY()});h.push({x:f[2].getPointB().getX(),y:f[2].getPointB().getY()});h.push({x:f[2].getPointB().getX(),y:f[2].getPointB().getY()+STACK_DEPTH_SIZE});h.push({x:f[1].getPointB().getX(),y:f[1].getPointB().getY()+STACK_DEPTH_SIZE});h.push({x:f[1].getPointA().getX(),
y:f[1].getPointA().getY()+STACK_DEPTH_SIZE})};this.updateDepthEffect=function(a,b,c){c&&(y.depth=colorLuminance(y.plane,DEPTH_LUMINANCE));x.graphics.clear();SHOW_EDGES&&x.graphics.beginStroke(b.depth);SHOW_FILL&&x.graphics.beginFill(b.depth);x.graphics.setStrokeStyle(y.width);for(b=0;b<a.length;b++)x.graphics.lineTo(a[b].x,a[b].y);x.graphics.closePath();x.x=-p.x;x.y=-p.y};this.perfectPosition=function(){var a=hexToRgb(y.plane),b=hexToRgb(colorLuminance(y.plane,.5)),c=this;new colorLerpShape(v,{r:a.r,
g:a.g,b:a.b,lerp:0},{r:b.r,g:b.g,b:b.b,lerp:1},0,MS_TIME_PERFECT_HIT,this.createGraph,createjs.Ease.cubicOut,f,"plane",function(){new colorLerpShape(v,{r:b.r,g:b.g,b:b.b,lerp:0},{r:a.r,g:a.g,b:a.b,lerp:1},0,MS_TIME_PERFECT_HIT,c.createGraph,createjs.Ease.cubicOut,f,"plane",null)});var d=hexToRgb(y.depth),e=hexToRgb(colorLuminance(y.depth,.5));new colorLerpShape(x,{r:d.r,g:d.g,b:d.b,lerp:0},{r:e.r,g:e.g,b:e.b,lerp:1},0,MS_TIME_PERFECT_HIT,this.updateDepthEffect,createjs.Ease.cubicOut,h,"depth",function(){new colorLerpShape(x,
{r:e.r,g:e.g,b:e.b,lerp:0},{r:d.r,g:d.g,b:d.b,lerp:1},0,MS_TIME_PERFECT_HIT,c.updateDepthEffect,createjs.Ease.cubicOut,h,"depth",null)})};this.updateEdgesPosition=function(){for(var a=0;a<f.length;a++)f[a].set(p.x+q[a].getPointA().getX(),p.y+q[a].getPointA().getY(),p.x+q[a].getPointB().getX(),p.y+q[a].getPointB().getY())};this.createGraph=function(a,b){v.graphics.clear();SHOW_EDGES&&v.graphics.beginStroke(b.plane);SHOW_FILL&&v.graphics.beginFill(b.plane);v.graphics.setStrokeStyle(y.width);for(var c=
0;c<a.length;c++)v.graphics.lineTo(a[c].getPointA().getX(),a[c].getPointA().getY());v.graphics.closePath();v.x=-p.x;v.y=-p.y};this.setChildIndex=function(a){e.setChildIndex(p,a)};this.getChildIndex=function(){return e.getChildIndex(p)};this.fallEffect=function(){createjs.Tween.get(p).to({y:CANVAS_HEIGHT,alpha:0},1500,createjs.Ease.cubicIn).call(function(){e.removeChild(p)})};this.getColor=function(){return y};this.setPosition=function(a,b){p.x=a;p.y=b};this.getPos=function(){return{x:p.x,y:p.y}};
this.getEdges=function(){return f};this.getLocalEdges=function(){return q};this.setEdges=function(a,b){q=[];f=[];d=[];g=[];for(var c=0;c<NUM_OF_EDGES_FOR_STACK;c++){q[c]=new CEdge(a[c].getPointA().getX(),a[c].getPointA().getY(),a[c].getPointB().getX(),a[c].getPointB().getY(),START_EDGES_POSITION[c].type);var e=new CEdge(a[c].getPointA().getX()+b.x,a[c].getPointA().getY()+b.y,a[c].getPointB().getX()+b.x,a[c].getPointB().getY()+b.y,START_EDGES_POSITION[c].type);START_EDGES_POSITION[c].type===EDGE_RIGHT_UP||
START_EDGES_POSITION[c].type===EDGE_LEFT_DOWN?d.push(e):g.push(e);f.push(e)}};this.edgesToString=function(a){console.log("------------"+a+"-------------");for(a=0;a<NUM_OF_EDGES_FOR_STACK;a++)console.log(f[a].toString())};this.limitLeftDown=function(){(p.x<=k[m].x||p.y>=k[m].y)&&this.resetStack(RIGHT_UP)};this.limitRightDown=function(){(p.x>=k[m].x||p.y>=k[m].y)&&this.resetStack(LEFT_UP)};this.limitLeftUp=function(){(p.x<=k[m].x||p.y<=k[m].y)&&this.resetStack(RIGHT_DOWN)};this.limitRightUp=function(){(p.x>=
k[m].x||p.y<=k[m].y)&&this.resetStack(LEFT_DOWN)};this.unload=function(){e.removeChild(p)};this.resetStack=function(a){m=a;l.set(DIRECTION_STACKS[m].x,DIRECTION_STACKS[m].y)};this.update=function(a){p.x+=l.getX()*a;p.y+=l.getY()*a;switch(m){case LEFT_DOWN:this.limitLeftDown();break;case RIGHT_DOWN:this.limitRightDown();break;case LEFT_UP:this.limitLeftUp();break;case RIGHT_UP:this.limitRightUp()}};this._init(a,c,b);return this}
function CTextPerfect(a){var c,b,e,f,d,g,h;this._init=function(){h=new createjs.Container;a.addChild(h);d=new createjs.Text(TEXT_PERFECT,"100px "+FONT_GAME,TEXT_COLOR);d.textAlign="center";g=new createjs.Text(TEXT_PERFECT,"100px "+FONT_GAME,TEXT_COLOR_STROKE);g.textAlign="center";g.outline=3;e=PERFECT_TEXT_START_POINT.x;f=PERFECT_TEXT_START_POINT.y-s_iOffsetY;c=PERFECT_TEXT_END_POINT.x;b=PERFECT_TEXT_END_POINT.y-s_iOffsetY;h.addChild(g,d);h.visible=!1};this.updatePoints=function(a,c){f=PERFECT_TEXT_START_POINT.y-
c;b=PERFECT_TEXT_END_POINT.y-c};this.animText=function(){h.x=e;h.y=f;h.visible=!0;h.alpha=1;createjs.Tween.get(h,{override:!0}).to({x:c,y:b,alpha:0},MS_PERFECT_TEXT,createjs.Ease.cubicOut).set({visible:!1})};this._init();return this};
