(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);function trace(a){console.log(a)}$(window).resize(function(){sizeHandler()});function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function playSound(a,d,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:d}):null}
function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}function setVolume(a,d){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=d}function setMute(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(d)}
function getSize(a){var d=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var e=b.createElement("body");e.id="vpw-test-b";e.style.cssText="overflow:scroll";var g=b.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+d+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";e.appendChild(g);c.insertBefore(e,b.head);
a=7==g["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(e)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH),c=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,e;b<a?(e=a-b,b+=e,c+=CANVAS_WIDTH/CANVAS_HEIGHT*e):c<d&&(e=d-c,c+=e,b+=CANVAS_HEIGHT/CANVAS_WIDTH*e);e=a/2-b/2;var g=d/2-c/2,f=CANVAS_WIDTH/c;if(g*f<-EDGEBOARD_X||e*f<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),d/(CANVAS_WIDTH-2*EDGEBOARD_X)),
c=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,e=(a-b)/2,g=(d-c)/2,f=CANVAS_WIDTH/c;s_iOffsetX=-1*g*f;s_iOffsetY=-1*e*f;0<=e&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oHealtBar&&s_oHealtBar.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMobileControls&&s_oMobileControls.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oModeSelect&&s_oModeSelect.refreshButtonPos(s_iOffsetX,
s_iOffsetY);null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oSelectTeam&&s_oSelectTeam.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile&&!s_bIsIphone?($("#canvas").css("width",c+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=c,s_oStage.canvas.height=b,s_oStage.scaleX=s_oStage.scaleY=Math.min(c/CANVAS_WIDTH,b/CANVAS_HEIGHT));0>e?$("#canvas").css("top",e+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",g+"px")}}
function createBitmap(a,d,b){var c=new createjs.Bitmap(a),e=new createjs.Shape;d&&b?e.graphics.beginFill("#fff").drawRect(0,0,d,b):e.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=e;return c}function createSprite(a,d,b,c,e,g){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-b,-c,e,g);a.hitArea=d;return a}
function randomFloatBetween(a,d,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(b))}function rotateVector2D(a,d){var b=d.getX()*Math.cos(a)+d.getY()*Math.sin(a),c=d.getX()*-Math.sin(a)+d.getY()*Math.cos(a);d.set(b,c)}function tweenVectorsOnX(a,d,b){return a+b*(d-a)}function shuffle(a){for(var d=a.length,b,c;0!==d;)c=Math.floor(Math.random()*d),--d,b=a[d],a[d]=a[c],a[c]=b;return a}
function bubbleSort(a){var d;do{d=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(d=a[b],a[b]=a[b+1],a[b+1]=d,d=!0)}while(d)}function compare(a,d){return a.index>d.index?-1:a.index<d.index?1:0}function easeLinear(a,d,b,c){return b*a/c+d}function easeInQuad(a,d,b,c){return b*(a/=c)*a+d}function easeInSine(a,d,b,c){return-b*Math.cos(a/c*(Math.PI/2))+b+d}function easeInCubic(a,d,b,c){return b*(a/=c)*a*a+d}function easeOutCubic(a,d,b,c,e){return b*((a=a/c-1)*a*a+1)+d}
function getTrajectoryPoint(a,d){var b=new createjs.Point,c=(1-a)*(1-a),e=a*a;b.x=c*d.start.x+2*(1-a)*a*d.traj.x+e*d.end.x;b.y=c*d.start.y+2*(1-a)*a*d.traj.y+e*d.end.y;return b}function formatTime(a){a/=1E3;var d=Math.floor(a/60),b=Math.floor(a-60*d),c=Math.floor(1E3*a%1E3);a=":"+c;10>c?a=":00"+c:100>c&&(a=":0"+c);c="";c=10>d?c+("0"+d+":"):c+(d+":");return(10>b?c+("0"+b):c+b)+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,d){var b,c;b=getBounds(a,.9);c=getBounds(d,.98);return calculateIntersection(b,c)}function calculateIntersection(a,d){var b,c,e,g,f,h,k,l;b=a.x+(e=a.width/2);c=a.y+(g=a.height/2);f=d.x+(h=d.width/2);k=d.y+(l=d.height/2);b=Math.abs(b-f)-(e+h);c=Math.abs(c-k)-(g+l);return 0>b&&0>c?(b=Math.min(Math.min(a.width,d.width),-b),c=Math.min(Math.min(a.height,d.height),-c),{x:Math.max(a.x,d.x),y:Math.max(a.y,d.y),width:b,height:c,rect1:a,rect2:d}):null}
function getBounds(a,d){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,e=c.length,g,f;for(f=0;f<e;f++)g=getBounds(c[f],1),g.x<b.x&&(b.x=g.x),g.y<b.y&&(b.y=g.y),g.x+g.width>b.x2&&(b.x2=g.x+g.width),g.y+g.height>b.y2&&(b.y2=g.y+g.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var h,k;a instanceof createjs.Bitmap?
(e=a.sourceRect||a.image,f=e.width*d,h=e.height*d):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(e=a.spriteSheet.getFrame(a.currentFrame),f=e.rect.width,h=e.rect.height,c=e.regX,k=e.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);c=c||0;f=f||0;k=k||0;h=h||0;b.regX=c;b.regY=k;e=a.localToGlobal(0-c,0-k);g=a.localToGlobal(f-c,h-k);f=a.localToGlobal(f-c,0-k);c=a.localToGlobal(0-c,h-k);b.x=Math.min(Math.min(Math.min(e.x,
g.x),f.x),c.x);b.y=Math.min(Math.min(Math.min(e.y,g.y),f.y),c.y);b.width=Math.max(Math.max(Math.max(e.x,g.x),f.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(e.y,g.y),f.y),c.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,b,c;0<d;)c=Math.floor(Math.random()*d),d--,b=a[d],a[d]=a[c],a[c]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),b=0;b<d.length;b++){var c=d[b].split("=");if(c[0]==a)return c[1]}}
function CSpriteLibrary(){var a,d,b,c,e,g;this.init=function(f,h,k){b=d=0;c=f;e=h;g=k;a={}};this.addSprite=function(c,b){a.hasOwnProperty(c)||(a[c]={szPath:b,oSprite:new Image},d++)};this.getSprite=function(c){return a.hasOwnProperty(c)?a[c].oSprite:null};this._onSpritesLoaded=function(){e.call(g)};this._onSpriteLoaded=function(){c.call(g);++b==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var c in a)a[c].oSprite.oSpriteLibrary=this,a[c].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[c].oSprite.src=a[c].szPath};this.getNumSprites=function(){return d}}
function CVector2(a,d){var b,c;this._init=function(a,d){b=a;c=d};this.add=function(a,d){b+=a;c+=d};this.addV=function(a){b+=a.getX();c+=a.getY()};this.scalarDivision=function(a){b/=a;c/=a};this.subV=function(a){b-=a.getX();c-=a.getY()};this.scalarProduct=function(a){b*=a;c*=a};this.invert=function(){b*=-1;c*=-1};this.dotProduct=function(a){return b*a.getX()+c*a.getY()};this.set=function(a,d){b=a;c=d};this.setV=function(a){b=a.getX();c=a.getY()};this.length=function(){return Math.sqrt(b*b+c*c)};this.length2=
function(){return b*b+c*c};this.normalize=function(){var a=this.length();0<a&&(b/=a,c/=a)};this.getNormalize=function(a){this.length();a.set(b,c);a.normalize()};this.rot90CCW=function(){var a=b;b=-c;c=a};this.rot90CW=function(){var a=b;b=c;c=-a};this.getRotCCW=function(a){a.set(b,c);a.rot90CCW()};this.getRotCW=function(a){a.set(b,c);a.rot90CW()};this.ceil=function(){b=Math.ceil(b);c=Math.ceil(c)};this.round=function(){b=Math.round(b);c=Math.round(c)};this.toString=function(){return"Vector2: "+b+", "+
c};this.print=function(){trace("Vector2: "+b+", "+c+"")};this.getX=function(){return b};this.getY=function(){return c};this._init(a,d)}
var CANVAS_WIDTH=1360,CANVAS_HEIGHT=640,EDGEBOARD_X=275,EDGEBOARD_Y=50,FONT="arialbold",FONT_2="pixel_lcd7regular",FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,PLAYER_X_POSITION_IN_SELECTION=CANVAS_WIDTH/2,PLAYER_Y_POSITION_IN_SELECTION=CANVAS_HEIGHT/2+29,NUM_SWIMMERS=8,HALF_DIVE_ANIMATION_FRAME=7,HALF_TURN_ANIMATION_FRAME=8,PLAYER_DIVE_WIDTH=131,PLAYER_DIVE_HEIGHT=170,WATER_DIVE_WIDTH=113,WATER_DIVE_HEIGHT=135,PLAYER_SWIMMING_WIDTH=137,PLAYER_SWIMMING_HEIGHT=85,PLAYER_SWIMMING_FRONT_WIDTH=139,
PLAYER_SWIMMING_FRONT_HEIGHT=83,PLAYER_TURN_WIDTH=145,PLAYER_TURN_HEIGHT=107,PLAYER_IDLE_WIDTH=82,PLAYER_IDLE_HEIGHT=120,SHOT_INDICATOR_SPEED,NUM_ROUNDS,NUM_POWER_UP_AVAILABLE=4,RANGE_HEIGHT=5,BARX=44,BARY=359,CURSOR_X=41,CURSOR_Y=41,PLAYER_MAX_SPEED,PLAYER_MIN_SPEED,PLAYER_ENERGY,PLAYER_RESISTENCE_STEP,PLAYER_MAX_SPEED_ADDER,PLAYER_ENERGY_ADDER,DIVE_ANIMATION=0,SWIMMING_ANIMATION=1,TURN_ANIMATION=2,SWIMMING_FRONT_ANIMATION=3,TURN_FRONT_ANIMATION=4,IDLE_ANIMATION=5,SPEED_ON_DIVE=8,DECELERATION_ON_TURN=
.75,SPEED_DECELERATION=.03,SPEED_MIN_ON_TURN=.2,SPEED_MIN_FOR_IDLE=.15,MODIFIER_SPEED_ADDER=.5,ENEMY_MAX_SPEED=[4,4,5,,6,5,4,4],ENEMY_MIN_SPEED=[1,2,3,,3,2,2,1],ENEMY_ENERGY=[100,100,100,,100,100,100,100],ENEMY_RESISTENCE_STEP=[1.3,1.5,1.5,,1.5,1.5,1.5,1.3],ENEMY_OCCURRENCE_SWIM=[.2,.15,.2,,.25,.2,.15,.2],PLAYER_NAME_AND_SPRITE,WAIT_FOR_GAME_START=0,CONFIRMATION_ON_EXIT=1,CONFIRMATION_ON_CAREER_RESET=2,TEAM_0=0,TEAM_1=1,TEAM_2=2,TEAM_3=3,TEAM_4=4,TEAM_5=5,TEAM_6=6,TEAM_7=7,LEFT_DIR=37,UP_DIR=38,RIGHT_DIR=
39,DOWN_DIR=40,SPACEBAR=32,EASY=1,NORMAL=2,HARD=4,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,SHOW_CREDITS=!1;TEXT_SCORE="SCORE: ";TEXT_POSITION="\u00b0 PLACE";TEXT_SCORE="SCORE:       ";TEXT_CREDITS_DEVELOPED="Developed by";TEXT_LINK1="www.codethislab.com";TEXT_START_MOVEMENT="MASH THE LEFT AND RIGHT KEYS TO BOOST YOUR POWER";HELP_TEXT_BAR="PRESS THE SPACE BAR WHEN THE ARROW IS AT THE VERY CENTRE TO MAKE THE PERFECT TURN";
TEXT_START_MOVEMENT_MOBILE="MASH THE LEFT AND RIGHT BUTTONS TO BOOST YOUR POWER";HELP_TEXT_BAR_MOBILE="PRESS THE BUTTON WHEN THE ARROW IS AT THE VERY CENTRE TO MAKE THE PERFECT TURN";HELP_ENERGY="KEEP YOUR ENERGY BAR FULL TO GO FASTER!";TEXT_ON_EXIT="ARE YOU SURE?";TEXT_ON_CAREER_RESET="ARE YOU SURE? ALL YOUR PREVIOUS SCORES WILL BE DELETED!";TEXT_CURRENCY="$";TEXT_LANE="Lane";TEXT_TIME="Time";TEXT_TEAM_0="U.S.A.";TEXT_TEAM_1="CHINA";TEXT_TEAM_2="U.K.";TEXT_TEAM_3="FRANCE";TEXT_TEAM_4="AUSTRALIA";
TEXT_TEAM_5="GERMANY";TEXT_TEAM_6="ITALY";TEXT_TEAM_7="BRAZIL";TEXT_CREDITS="CREDITS";TEXT_SWIMMER="SELECT SWIMMER";TEXT_MODE="SELECT MODE";TEXT_CHALLENGE="SELECT CHALLENGE";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var a,d,b,c,e,g,f;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();f=new createjs.Container;s_oStage.addChild(f)};this.unload=function(){f.removeAllChildren()};this.hide=function(){var c=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){c.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));f.addChild(h);h=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(h);c.x=CANVAS_WIDTH/2-h.width/2;c.y=CANVAS_HEIGHT-145;f.addChild(c);a=h.width;d=h.height;e=new createjs.Shape;e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,d);f.addChild(e);c.mask=
e;b=new createjs.Text("","30px Arial","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-150;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";f.addChild(b);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;f.addChild(g)};this.refreshLoader=function(g){b.text=g+"%";e.graphics.clear();g=Math.floor(g*a/100);e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,g,d)};this._init()}
function CMain(a){var d,b=0,c=0,e=STATE_LOADING,g,f,h;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(c){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;f=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();d=!0};this.soundLoaded=function(){b++;f.refreshLoader(Math.floor(b/c*100));if(b===c){f.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||
0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/applauses.ogg","applauses"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/crowd-cheers.ogg","crowd_cheers"),createjs.Sound.registerSound("./sounds/crowd.ogg","crowd"),createjs.Sound.registerSound("./sounds/dive.ogg",
"dive"),createjs.Sound.registerSound("./sounds/stop_bar.ogg","stop_bar")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/applauses.mp3","applauses"),createjs.Sound.registerSound("./sounds/press_button.mp3","click"),createjs.Sound.registerSound("./sounds/crowd-cheers.mp3","crowd_cheers"),createjs.Sound.registerSound("./sounds/crowd.mp3",
"crowd"),createjs.Sound.registerSound("./sounds/dive.mp3","dive"),createjs.Sound.registerSound("./sounds/stop_bar.mp3","stop_bar")),c+=7)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_continue_small","./sprites/but_continue_small.png");
s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("left_button","./sprites/left_button.png");s_oSpriteLibrary.addSprite("right_button","./sprites/right_button.png");s_oSpriteLibrary.addSprite("but_skip","./sprites/but_skip.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_select_team",
"./sprites/bg_select_team.jpg");s_oSpriteLibrary.addSprite("bg_podium","./sprites/bg_podium.jpg");s_oSpriteLibrary.addSprite("result_panel","./sprites/result_panel.png");s_oSpriteLibrary.addSprite("upgrade_panel","./sprites/upgrade_panel.png");s_oSpriteLibrary.addSprite("select_challenge","./sprites/select_challenge.png");s_oSpriteLibrary.addSprite("various_help_box","./sprites/various_help_box.png");s_oSpriteLibrary.addSprite("various_help_box_2","./sprites/various_help_box_2.png");s_oSpriteLibrary.addSprite("final_score",
"./sprites/final_score.png");s_oSpriteLibrary.addSprite("logo_credits","./sprites/logo_credits.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("100_m","./sprites/but_100m.png");s_oSpriteLibrary.addSprite("200_m","./sprites/but_200m.png");s_oSpriteLibrary.addSprite("400_m","./sprites/but_400m.png");s_oSpriteLibrary.addSprite("level_sprite","./sprites/level_sprite.png");s_oSpriteLibrary.addSprite("energy_bar","./sprites/energy_bar.png");s_oSpriteLibrary.addSprite("healt",
"./sprites/healt.png");s_oSpriteLibrary.addSprite("arrow_keys","./sprites/arrow_keys.png");s_oSpriteLibrary.addSprite("vertical_bar","./sprites/vertical_bar.png");s_oSpriteLibrary.addSprite("horizontal_bar","./sprites/horizontal_bar.png");s_oSpriteLibrary.addSprite("arrival_panel","./sprites/arrival_panel.png");s_oSpriteLibrary.addSprite("bar-1","./sprites/bar-1.png");s_oSpriteLibrary.addSprite("bar-2","./sprites/bar-2.png");s_oSpriteLibrary.addSprite("gold_medal","./sprites/gold_medal.png");s_oSpriteLibrary.addSprite("silver_medal",
"./sprites/silver_medal.png");s_oSpriteLibrary.addSprite("bronze_medal","./sprites/bronze_medal.png");s_oSpriteLibrary.addSprite("right_bar","./sprites/right_bar.png");s_oSpriteLibrary.addSprite("arrow_bar","./sprites/arrow_bar.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("splash_sprite","./sprites/splash_sprite.png");for(var a=0;a<NUM_SWIMMERS;a++)s_oSpriteLibrary.addSprite("flag_swimmer_"+
a,"./sprites/flag_swimmer_"+a+".png"),s_oSpriteLibrary.addSprite("flag_swimmer_"+a+"_game","./sprites/flag_swimmer_"+a+"_game.jpg"),s_oSpriteLibrary.addSprite("swimmer_"+a+"_dive","./sprites/swimmer/swimmer_"+a+"/swimmer_"+a+"_dive.png"),s_oSpriteLibrary.addSprite("swimmer_"+a+"_swimming_back","./sprites/swimmer/swimmer_"+a+"/swimmer_"+a+"_swimming_back.png"),s_oSpriteLibrary.addSprite("swimmer_"+a+"_swimming_front","./sprites/swimmer/swimmer_"+a+"/swimmer_"+a+"_swimming_front.png"),s_oSpriteLibrary.addSprite("swimmer_"+
a+"_turn_back","./sprites/swimmer/swimmer_"+a+"/swimmer_"+a+"_turn_back.png"),s_oSpriteLibrary.addSprite("swimmer_"+a+"_turn_front","./sprites/swimmer/swimmer_"+a+"/swimmer_"+a+"_turn_front.png"),s_oSpriteLibrary.addSprite("swimmer_"+a+"_idle","./sprites/swimmer/swimmer_"+a+"/swimmer_"+a+"_idle.png"),s_oSpriteLibrary.addSprite("swimmer_"+a+"_pose","./sprites/swimmer/poses/swimmer_"+a+".png");s_oSpriteLibrary.addSprite("glow","./sprites/glow.png");s_oSpriteLibrary.addSprite("blue_rope","./sprites/blue_lane_rope.png");
s_oSpriteLibrary.addSprite("green_rope","./sprites/green_lane_rope.png");s_oSpriteLibrary.addSprite("yellow_rope","./sprites/yellow_lane_rope.png");s_oSpriteLibrary.addSprite("pool_0","./sprites/pool/01.png");s_oSpriteLibrary.addSprite("pool_1","./sprites/pool/02.png");s_oSpriteLibrary.addSprite("pool_2","./sprites/pool/03.png");s_oSpriteLibrary.addSprite("pool_3","./sprites/pool/04.png");s_oSpriteLibrary.addSprite("water_0","./sprites/pool/water/water_00.jpg");s_oSpriteLibrary.addSprite("water_1",
"./sprites/pool/water/water_01.jpg");s_oSpriteLibrary.addSprite("water_2","./sprites/pool/water/water_02.jpg");s_oSpriteLibrary.addSprite("water_3","./sprites/pool/water/water_03.jpg");s_oSpriteLibrary.addSprite("water_4","./sprites/pool/water/water_04.jpg");s_oSpriteLibrary.addSprite("water_5","./sprites/pool/water/water_05.jpg");s_oSpriteLibrary.addSprite("water_6","./sprites/pool/water/water_06.jpg");s_oSpriteLibrary.addSprite("water_7","./sprites/pool/water/water_07.jpg");s_oSpriteLibrary.addSprite("water_8",
"./sprites/pool/water/water_08.jpg");s_oSpriteLibrary.addSprite("water_9","./sprites/pool/water/water_09.jpg");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;f.refreshLoader(Math.floor(b/c*100));if(b===c){f.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=
function(){new CMenu;e=STATE_MENU};this.gotoTeamSelect=function(){new CSelectTeam;e=STATE_MENU};this.gotoModeSelect=function(){new CModeSelect;e=STATE_MENU};this.gotoSelectLevel=function(){new CLevelMenu;e=STATE_MENU};this.gotoGame=function(a,c){h=new CGame(g,a,c);e=STATE_GAME};this.gotoPlayerProgress=function(){new CPlayerProgress;e=STATE_MENU};this.gotoHelp=function(){new CHelp;e=STATE_HELP};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=
function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==d){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;g=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_bIsIphone=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iMode,s_iLevelReached=1,s_iModeSelected=0,s_iPlayerMoney=0,s_iSpeedBought=0,s_iEnergyBought=0,s_iSpeedAdder=0,s_iEnergyAdder=0,s_iTeamSelected=0,s_szTeamSelectedSprite="swimmer_0",s_aSwimmersScore=[0,0,0,0,0,0,0,0],s_oCityInfos=null,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack,s_oCanvas;
function CTextButton(a,d,b,c,e,g,f){var h,k,l,n,q;this._init=function(a,c,b,d,e,g,f){h=[];k=[];var E=createBitmap(b),H=Math.ceil(f/20);q=new createjs.Text(d," "+f+"px "+e,"#000000");q.textAlign="center";q.textBaseline="alphabetic";var D=q.getBounds();q.x=b.width/2+H;q.y=Math.floor(b.height/2)+D.height/3+H;n=new createjs.Text(d," "+f+"px "+e,g);n.textAlign="center";n.textBaseline="alphabetic";D=n.getBounds();n.x=b.width/2;n.y=Math.floor(b.height/2)+D.height/3;l=new createjs.Container;l.x=a;l.y=c;l.regX=
b.width/2;l.regY=b.height/2;l.addChild(E,q,n);s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){h[a]=c;k[a]=b};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=
function(){l.scaleX=.9;l.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setTextPosition=function(a){n.y=a;q.y=a+2};this.setPosition=function(a,c){l.x=a;l.y=c};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(a,d,b,c,e,g,f);return this}
function CToggle(a,d,b,c){var e,g,f,h=[],k;this._init=function(a,c,b,d){g=[];f=[];var h=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}});e=d;k=createSprite(h,"state_"+e,b.width/2/2,b.height/2,b.width/2,b.height);k.x=a;k.y=c;k.cursor="pointer";k.stop();s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);s_oStage.removeChild(k)};
this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){g[a]=c;f[a]=b};this.addEventListenerWithParams=function(a,c,b,d){g[a]=c;f[a]=b;h=d};this.setActive=function(a){e=a;k.gotoAndStop("state_"+e)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");e=!e;k.gotoAndStop("state_"+e);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(f[ON_MOUSE_UP],h)};this.buttonDown=
function(){k.scaleX=.9;k.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],h)};this.setPosition=function(a,c){k.x=a;k.y=c};this.setVisible=function(a){k.visible=a};this.getY=function(){return k.y};this._init(a,d,b,c)}
function CGfxButton(a,d,b){var c,e,g,f=[],h;this._init=function(a,b,d){c=1;e=[];g=[];h=createBitmap(d);h.x=a;h.y=b;h.regX=d.width/2;h.regY=d.height/2;h.cursor="pointer";s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);s_oStage.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,
c,b){e[a]=c;g[a]=b};this.addEventListenerWithParams=function(a,c,b,d){e[a]=c;g[a]=b;f=d};this.buttonRelease=function(){h.scaleX=c;h.scaleY=c;e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(g[ON_MOUSE_UP],f)};this.buttonDown=function(){h.scaleX=.9*c;h.scaleY=.9*c;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],f)};this.setScale=function(a){c=a;h.scaleX=a;h.scaleY=a};this.setPosition=function(a,c){h.x=a;h.y=c};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};
this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(a,d,b);return this}
function CMenu(){var a,d,b,c,e,g,f,h,k,l,n=null,q,m,p,r=null;this._init=function(){null===localStorage.getItem("Mode")||s_iLevelReached>=s_oCityInfos.getNumLevels()?this.removeLocalStorage():(s_iMode=+localStorage.getItem("Mode"),s_iLevelReached=+localStorage.getItem("LevelReached"),s_iModeSelected=+localStorage.getItem("ModeSelected"),s_iPlayerMoney=+localStorage.getItem("Money"),s_iSpeedBought=+localStorage.getItem("SpeedBought"),s_iEnergyBought=+localStorage.getItem("EnergyBought"),s_iSpeedAdder=
+localStorage.getItem("SpeedAdder"),s_iEnergyAdder=+localStorage.getItem("EnergyAdder"),s_iTeamSelected=+localStorage.getItem("TeamSelected"),s_szTeamSelectedSprite=localStorage.getItem("TeamSelectedSprite"),s_aSwimmersScore=JSON.parse(localStorage.getItem("Scores")),s_oCityInfos.getCitiesStorage());k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(k);if(null===localStorage.getItem("Mode")){var t=s_oSpriteLibrary.getSprite("but_play");e=CANVAS_WIDTH/2;g=CANVAS_HEIGHT-110;l=new CGfxButton(e,
g,t);l.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this)}else t=s_oSpriteLibrary.getSprite("but_play"),e=CANVAS_WIDTH/2-200,g=CANVAS_HEIGHT-110,l=new CGfxButton(e,g,t),l.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this),t=s_oSpriteLibrary.getSprite("but_continue"),b=CANVAS_WIDTH/2+200,c=CANVAS_HEIGHT-110,n=new CGfxButton(b,c,t),n.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this);SHOW_CREDITS&&(t=s_oSpriteLibrary.getSprite("but_credits"),a=10+t.width/2,d=10+t.height/2,q=
new CGfxButton(a,d,t),q.addEventListener(ON_MOUSE_UP,this._onCredits,this));if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)t=s_oSpriteLibrary.getSprite("audio_icon"),f=CANVAS_WIDTH-t.height/2-10,h=t.height/2+10,p=new CToggle(f,h,t,s_bAudioActive),p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(m);createjs.Tween.get(m).to({alpha:0},1E3).call(function(){m.visible=!1});this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.unload=function(){l.unload();l=null;m.visible=!1;SHOW_CREDITS&&q.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;null!==r&&(r.unload(),r=null);s_oStage.removeChild(k);s_oMenu=k=null};this.removeLocalStorage=function(){s_iMode=0;s_iLevelReached=1;s_iTeamSelected=s_iEnergyAdder=s_iSpeedAdder=s_iEnergyBought=s_iSpeedBought=s_iPlayerMoney=s_iModeSelected=0;s_szTeamSelectedSprite="swimmer_0";s_aSwimmersScore=[0,0,0,0,0,0,0,0];s_oCityInfos.removeCitiesStorage();
localStorage.removeItem("Mode");localStorage.removeItem("LevelReached");localStorage.removeItem("ModeSelected");localStorage.removeItem("Money");localStorage.removeItem("SpeedBought");localStorage.removeItem("EnergyBought");localStorage.removeItem("SpeedAdder");localStorage.removeItem("EnergyAdder");localStorage.removeItem("TeamSelected");localStorage.removeItem("TeamSelectedSprite");localStorage.removeItem("Scores")};this.refreshButtonPos=function(k,m){p.setPosition(f-k,m+h);l.setPosition(e,g-m);
n&&n.setPosition(b,c-m);SHOW_CREDITS&&q.setPosition(a+k,m+d)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCredits=function(){new CCreditsPanel};this._onButPlayRelease=function(){$(s_oMain).trigger("start_session");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");null===localStorage.getItem("Mode")?(this.unload(),s_oMain.gotoTeamSelect()):null===r&&(r=new CVariousHelp(TEXT_ON_CAREER_RESET,CONFIRMATION_ON_CAREER_RESET))};
this._onButContinueRelease=function(){$(s_oMain).trigger("start_session");this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoSelectLevel()};this.unloadVariousHelp=function(){r.unload();r=null};this.onContinue=function(){this.removeLocalStorage();this.unload();s_oMain.gotoTeamSelect()};s_oMenu=this;null!==s_oCityInfos&&(s_oCityInfos.unload(),s_oCityInfos=null);s_oCityInfos=new CCitySettings;this._init()}var s_oMenu=null;
function CSelectTeam(){var a,d,b,c,e,g,f=0,h,k,l,n,q,m,p,r,t,v,A,B,E,H,D,u;this._init=function(){s_iTeamSelected=0;s_szTeamSelectedSprite="swimmer_0";H=createBitmap(s_oSpriteLibrary.getSprite("bg_select_team"));s_oStage.addChild(H);var f=s_oSpriteLibrary.getSprite("select_challenge"),k=createBitmap(f);k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2;k.regX=f.width/2;k.regY=f.height/2;s_oStage.addChild(k);l=new createjs.Text(TEXT_SWIMMER," 20px "+FONT,"#ffffff");l.x=CANVAS_WIDTH/2-180;l.y=128;l.textAlign="left";
l.textBaseline="alphabetic";l.lineWidth=1E3;s_oStage.addChild(l);n=new createjs.Text(TEXT_TEAM_0," 20px "+FONT,"#ffffff");n.x=CANVAS_WIDTH/2-180;n.y=155;n.textAlign="left";n.textBaseline="alphabetic";n.lineWidth=1E3;s_oStage.addChild(n);f=s_oSpriteLibrary.getSprite("glow");k=createBitmap(f);k.x=PLAYER_X_POSITION_IN_SELECTION;k.y=PLAYER_Y_POSITION_IN_SELECTION-1;k.regX=f.width/2;k.regY=f.height/2;s_oStage.addChild(k);f=s_oSpriteLibrary.getSprite("but_continue_small");a=CANVAS_WIDTH/2+340;d=CANVAS_HEIGHT-
148;q=new CGfxButton(a,d,f,s_oStage);q.addEventListener(ON_MOUSE_UP,this._onButNextRelease,this);f=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-f.height/2-10;g=f.height/2+10;D=new CGfxButton(e,g,f,s_oStage);D.addEventListener(ON_MOUSE_UP,this._onExit,this);b=CANVAS_WIDTH-f.width/2-90;c=f.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=s_oSpriteLibrary.getSprite("audio_icon"),u=new CToggle(b,c,f,s_bAudioActive),u.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);h=new createjs.Container;
s_oStage.addChild(h);this.showIdleAnimation(PLAYER_X_POSITION_IN_SELECTION,PLAYER_Y_POSITION_IN_SELECTION,s_szTeamSelectedSprite);f=s_oSpriteLibrary.getSprite("flag_swimmer_0");E=new CToggle(CANVAS_WIDTH/2-180,CANVAS_HEIGHT/2-100,f,!1);E.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_0);f=s_oSpriteLibrary.getSprite("flag_swimmer_1");B=new CToggle(CANVAS_WIDTH/2-180,CANVAS_HEIGHT/2-20,f,!0);B.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_1);f=s_oSpriteLibrary.getSprite("flag_swimmer_2");
r=new CToggle(CANVAS_WIDTH/2-180,CANVAS_HEIGHT/2+60,f,!0);r.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_2);f=s_oSpriteLibrary.getSprite("flag_swimmer_3");t=new CToggle(CANVAS_WIDTH/2-180,CANVAS_HEIGHT/2+145,f,!0);t.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_3);f=s_oSpriteLibrary.getSprite("flag_swimmer_4");m=new CToggle(CANVAS_WIDTH/2+180,CANVAS_HEIGHT/2-100,f,!0);m.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_4);f=s_oSpriteLibrary.getSprite("flag_swimmer_5");
v=new CToggle(CANVAS_WIDTH/2+180,CANVAS_HEIGHT/2-20,f,!0);v.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_5);f=s_oSpriteLibrary.getSprite("flag_swimmer_6");A=new CToggle(CANVAS_WIDTH/2+180,CANVAS_HEIGHT/2+60,f,!0);A.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_6);f=s_oSpriteLibrary.getSprite("flag_swimmer_7");p=new CToggle(CANVAS_WIDTH/2+180,CANVAS_HEIGHT/2+145,f,!0);p.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_7);this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this._onModeToggle=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("select_team");var c;switch(a){case TEAM_0:E.setActive(!1);B.setActive(!0);r.setActive(!0);t.setActive(!0);m.setActive(!0);v.setActive(!0);A.setActive(!0);p.setActive(!0);f=TEAM_0;n.text=TEXT_TEAM_0;c="swimmer_0";break;case TEAM_1:E.setActive(!0);B.setActive(!1);r.setActive(!0);t.setActive(!0);m.setActive(!0);v.setActive(!0);A.setActive(!0);p.setActive(!0);f=TEAM_1;n.text=TEXT_TEAM_1;c="swimmer_1";
break;case TEAM_2:E.setActive(!0);B.setActive(!0);r.setActive(!1);t.setActive(!0);m.setActive(!0);v.setActive(!0);A.setActive(!0);p.setActive(!0);f=TEAM_2;n.text=TEXT_TEAM_2;c="swimmer_2";break;case TEAM_3:E.setActive(!0);B.setActive(!0);r.setActive(!0);t.setActive(!1);m.setActive(!0);v.setActive(!0);A.setActive(!0);p.setActive(!0);f=TEAM_3;n.text=TEXT_TEAM_3;c="swimmer_3";break;case TEAM_4:E.setActive(!0);B.setActive(!0);r.setActive(!0);t.setActive(!0);m.setActive(!1);v.setActive(!0);A.setActive(!0);
p.setActive(!0);f=TEAM_4;n.text=TEXT_TEAM_4;c="swimmer_4";break;case TEAM_5:E.setActive(!0);B.setActive(!0);r.setActive(!0);t.setActive(!0);m.setActive(!0);v.setActive(!1);A.setActive(!0);p.setActive(!0);f=TEAM_5;n.text=TEXT_TEAM_5;c="swimmer_5";break;case TEAM_6:E.setActive(!0);B.setActive(!0);r.setActive(!0);t.setActive(!0);m.setActive(!0);v.setActive(!0);A.setActive(!1);p.setActive(!0);f=TEAM_6;n.text=TEXT_TEAM_6;c="swimmer_6";break;case TEAM_7:E.setActive(!0),B.setActive(!0),r.setActive(!0),t.setActive(!0),
m.setActive(!0),v.setActive(!0),A.setActive(!0),p.setActive(!1),f=TEAM_7,n.text=TEXT_TEAM_7,c="swimmer_7"}this.showIdleAnimation(PLAYER_X_POSITION_IN_SELECTION,PLAYER_Y_POSITION_IN_SELECTION,c);s_iTeamSelected=f;s_szTeamSelectedSprite=c};this.showIdleAnimation=function(a,c,b){s_oStage.removeChild(k);b=s_oSpriteLibrary.getSprite(b+"_pose");k=createBitmap(b);k.x=a;k.y=c;k.regX=b.width/2;k.regY=b.height/2;s_oStage.addChild(k)};this._onExit=function(){s_oMain.gotoMenu();$(s_oMain).trigger("show_interlevel_ad");
$(s_oMain).trigger("end_session")};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.unload=function(){m.unload();p.unload();v.unload();r.unload();A.unload();t.unload();B.unload();E.unload();s_oSelectTeam=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(a,d){D.setPosition(e-a,d+g);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||u.setPosition(b-a,d+c)};this._onButNextRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==
s_bMobile||createjs.Sound.play("click");s_oMain.gotoModeSelect()};s_oSelectTeam=this;this._init()}var s_oSelectTeam=null;
function CGame(a,d,b){var c=0,e=0,g=s_iTeamSelected,f=0,h=!1,k=!1,l=!1,n=!1,q=!1,m,p,r,t,v=null,A=null,B,E,H,D,u,G,C=null,y=[],M=[],I=[TEAM_0,TEAM_1,TEAM_2,TEAM_3,TEAM_4,TEAM_5,TEAM_6,TEAM_7],J=[{x:245,y:165},{x:329,y:203},{x:407,y:240},{x:487,y:280},{x:568,y:317},{x:650,y:353},{x:730,y:393},{x:813,y:431}],Q=[{x:1545,y:-140},{x:1628,y:-102},{x:1712,y:-61},{x:1796,y:-22},{x:1880,y:22},{x:1949,y:58},{x:2041,y:100},{x:2125,y:122}],K=[{x:267,y:190},{x:352,y:230},{x:435,y:268},{x:520,y:308},{x:605,y:348},
{x:689,y:388},{x:773,y:428},{x:858,y:468}],z=[!1,!1,!1,!1,!1,!1,!1,!1],N=[],L=[],F=[];this._init=function(){$(s_oMain).trigger("start_level",b);playSound("crowd",.5,-1);setVolume(s_oSoundtrack,.2);H=new createjs.Container;s_oStage.addChild(H);E=new CWater(H);u=new createjs.Container;s_oStage.addChild(u);D=new CScrollingBg(u);D.setEndPositions(Q);D.setArrivalPositions(K);var a=s_oCityInfos.getValuesToAdd(b),c=I[g];I[g]=null;for(var e=0;e<NUM_SWIMMERS;e++)if(3!==e){null!==I[e]?(F.push(I[e]),I[e]=null):
e===NUM_SWIMMERS-1?(F.push(I[3]),I[3]=null):(F.push(I[e+1]),I[e+1]=null);var f=ENEMY_MAX_SPEED[e]+a.speed,h=ENEMY_MIN_SPEED[e],q=ENEMY_ENERGY[e]+a.energy,n=ENEMY_RESISTENCE_STEP[e],k=ENEMY_OCCURRENCE_SWIM[e];M.push(new createjs.Container);s_oStage.addChild(M[e]);y.push(new CSwimmer(J[e].x,J[e].y,M[e],e,!1,PLAYER_NAME_AND_SPRITE[F[F.length-1]],d,f,h,q,n,k))}else F.push(c),f=PLAYER_MAX_SPEED+s_iSpeedAdder,h=PLAYER_MIN_SPEED,q=PLAYER_ENERGY+s_iEnergyAdder,n=PLAYER_RESISTENCE_STEP,k=0,M.push(new createjs.Container),
s_oStage.addChild(M[e]),y.push(new CSwimmer(J[e].x,J[e].y,M[e],e,!0,PLAYER_NAME_AND_SPRITE[F[F.length-1]],d,f,h,q,n,k));p=new CInterface;r=new CHealtBar;s_bMobile?t=new CMobileControls:document.onkeydown=this.onKeyDown;this.enableMovement()};this.enableMovement=function(){for(var a=[],c=0;c<NUM_SWIMMERS;c++)a.push(y[c].getInfos());m=new CShowNationalityInLane(a);v=new CVariousHelp(TEXT_START_MOVEMENT,WAIT_FOR_GAME_START)};this.onKeyDown=function(a){null!==v&&(B.unloadVariousHelp(),m&&(m.unload(),
m=null),h=!0,p.setGUIClickable());if(h)return a||(a=window.event),a.keyCode===LEFT_DIR&&null===C?(l=!0,k||(B.startGame(),k=!0)):a.keyCode===RIGHT_DIR&&null===C?(n=!0,k||(B.startGame(),k=!0)):a.keyCode===SPACEBAR&&null!==C&&B.turnPlayer(),l&&n?(y[3].addSpeed(),l=!1,n=!0):y[3].decreaseSpeed(),a.preventDefault(),!1};this.onButtonDown=function(a){null!==v&&(B.unloadVariousHelp(),m.unload(),m=null,h=!0,p.setGUIClickable());h&&(a===LEFT_DIR?(l=!0,k||(B.startGame(),k=!0)):a===RIGHT_DIR&&(n=!0,k||(B.startGame(),
k=!0)),l&&n?(y[3].addSpeed(),l=!1,n=!0):y[3].decreaseSpeed())};this.startGame=function(){for(var a=0;a<NUM_SWIMMERS;a++)y[a].playAnimation()};this.halfAnimationDive=function(){if(!q){playSound("dive",.5,0);s_oStage.setChildIndex(H,0);for(var a=1;a<=NUM_SWIMMERS;a++)s_oStage.setChildIndex(M[a-1],a);s_oStage.setChildIndex(D,a);q=!0}};this.spawnBar=function(){k=!1;C=new CIndicatorController(BARY/RANGE_HEIGHT);C.scaleBar(.5);C.startAnimation();G=new createjs.Shape;G.graphics.beginFill("Black").drawRect(0,
160,CANVAS_WIDTH,CANVAS_HEIGHT-160);G.alpha=.01;s_oStage.addChild(G);s_bMobile&&t.spawnButtonForBar();for(var a=0;a<NUM_SWIMMERS;a++)y[a].stopAnimation()};this.turnPlayer=function(){C.endAnimation();var a=C.getPosition();z[3]?y[3].showFrontAnimationTurn(a):y[3].showAnimationTurn(a);k=!0;s_bMobile?(t.hideButtonForBar(),C.unload()):(G.off("mousedown",this.handleClick,this),C.unload(),s_oStage.removeChild(G));for(a=0;a<NUM_SWIMMERS;a++)y[a].playAnimation();C=null};this.moveSwimmersWithBG=function(a){var c=
D.getDirectionVector();D.move(a);E.move(a);for(var b=0;b<NUM_SWIMMERS;b++)y[b].movementAffectedByPlayer(a,c),y[b].update()};this.moveEnemies=function(){for(var a=0;a<NUM_SWIMMERS;a++)3!==a&&(Math.random()<y[a].getOccurrenceSwim()*y[a].getEnergyProportion()?y[a].addSpeed():y[a].decreaseSpeed(),y[a].move()),y[a].increaseEnergy()};this.checkIfIsElapsedTooMuchTimeBetweenPress=function(){l||n?(c+=s_iTimeElaps,200<c&&(c=0,n=l=!1)):y[3].decreaseSpeed()};this.checkDistanceFromArrivalPoint=function(){for(var a=
0;a<NUM_SWIMMERS;a++)z[a]?y[a].checkDistance(D.getArrivalPositions(a)):y[a].checkDistance(D.getEndPositions(a))};this.addInArrayPlayerArrived=function(a,c){N.push({lane:a,name:c,time:formatTime(e)});1===N.length&&playSound("crowd_cheers",.5,0);var d=N.length-1;L.push({player:F[a],position:d});p.addArrivalPanel(N[d]);3===a&&3>=d+1?(f=d,s_oCityInfos.setRewardTaken(b,f)):3===a&&(f=d);3===a&&null!==s_oCityInfos.getTimeSpent(b)?s_oCityInfos.getTimeSpent(b)>e&&s_oCityInfos.setTimeSpent(b,e):3===a&&s_oCityInfos.setTimeSpent(b,
e);if(N.length===NUM_SWIMMERS){for(d=0;d<L.length;d++);s_oCityInfos.setPlayersArrivals(b,L);setTimeout(this.gameOver(),1E3)}};this.haveTurned=function(a){z[a]=!z[a]};this.changeBGsDirection=function(){D.changeDir();E.changeDir()};this.unloadVariousHelp=function(a){v.unload();v=null;if(a===CONFIRMATION_ON_EXIT&&(h=!0,!C))for(k=!0,a=0;a<NUM_SWIMMERS;a++)y[a].playAnimation();m&&(m.unload(),m=null);p.setGUIClickable()};this.unload=function(){p.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};
this.onInfo=function(){v=new CVariousHelp(TEXT_START_MOVEMENT,WAIT_FOR_GAME_START);k=!1;for(var a=0;a<NUM_SWIMMERS;a++)y[a].stopAnimation()};this.onInfoExit=function(){v.unload();v=null;if(h){k=!0;for(var a=0;a<NUM_SWIMMERS;a++)y[a].playAnimation()}};this.onExitMessage=function(){if(null===v){v=new CVariousHelp(TEXT_ON_EXIT,CONFIRMATION_ON_EXIT);h=k=!1;for(var a=0;a<NUM_SWIMMERS;a++)y[a].stopAnimation()}};this.onExit=function(){$(s_oMain).trigger("end_level");$(s_oMain).trigger("show_interlevel_ad");
$(s_oMain).trigger("end_session");this.unload();s_oMain.gotoMenu();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack.volume=1;$(s_oMain).trigger("restart")};this.onContinue=function(){$(s_oMain).trigger("end_level");$(s_oMain).trigger("show_interlevel_ad");this.unload();s_oMain.gotoPlayerProgress()};this.gameOver=function(){3>f&&s_iLevelReached<b+2&&(s_iLevelReached=b+2);playSound("applauses",.5,0);setTimeout(function(){t&&t.hideButtons();p.unloadArrivalPanel();h=k=!1},500);A=b<s_oCityInfos.getNumLevels()-
1?CEndPanel(N,b):new CPodiumScreen(b);A.show()};this.update=function(){if(k){var a=y[3].getSpeed();e+=s_iTimeElaps;p.refreshTime(formatTime(e));s_bMobile&&!s_bIsIphone||E.update();this.moveSwimmersWithBG(a);this.moveEnemies();r.refreshMask(y[3].getEnergy());this.checkIfIsElapsedTooMuchTimeBetweenPress();this.checkDistanceFromArrivalPoint()}};SHOT_INDICATOR_SPEED=a.shot_indicator_spd;NUM_ROUNDS=a.num_rounds;PLAYER_MAX_SPEED=a.player_max_speed;PLAYER_MIN_SPEED=a.player_min_speed;PLAYER_ENERGY=a.player_energy;
PLAYER_RESISTENCE_STEP=a.player_resistence_step;PLAYER_MAX_SPEED_ADDER=a.player_max_speed_adder;PLAYER_ENERGY_ADDER=a.player_energy_adder;PLAYER_NAME_AND_SPRITE=[{name:TEXT_TEAM_0,sprite:0},{name:TEXT_TEAM_1,sprite:1},{name:TEXT_TEAM_2,sprite:2},{name:TEXT_TEAM_3,sprite:3},{name:TEXT_TEAM_4,sprite:4},{name:TEXT_TEAM_5,sprite:5},{name:TEXT_TEAM_6,sprite:6},{name:TEXT_TEAM_7,sprite:7}];s_oGame=this;B=this;this._init()}var s_oGame;
function CInterface(a){var d,b,c,e,g,f,h,k,l,n=s_oSpriteLibrary.getSprite("arrival_panel"),q=[],m=[{x:CANVAS_WIDTH-250,y:100},{x:CANVAS_WIDTH-250,y:150},{x:CANVAS_WIDTH-250,y:200},{x:CANVAS_WIDTH-250,y:250},{x:CANVAS_WIDTH-250,y:300},{x:CANVAS_WIDTH-250,y:350},{x:CANVAS_WIDTH-250,y:400},{x:CANVAS_WIDTH-250,y:450}],p=[],r=0,t=!1,v,A;this._init=function(){var a=s_oSpriteLibrary.getSprite("but_exit");g=CANVAS_WIDTH-a.width/2-10;f=a.height/2+10;k=new CGfxButton(g,f,a,s_oStage);k.addEventListener(ON_MOUSE_UP,
this._onExit,this);a=s_oSpriteLibrary.getSprite("but_info");c=CANVAS_WIDTH-a.width/2-90;e=a.height/2+10;l=new CGfxButton(c,e,a,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onInfo,this);d=CANVAS_WIDTH-a.width/2-170;b=a.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a=s_oSpriteLibrary.getSprite("audio_icon"),h=new CToggle(d,b,a,s_bAudioActive),h.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);v=createBitmap(n);v.x=10;v.y=15;v.scaleX=.85;s_oStage.addChild(v);A=new createjs.Text("00:00:000",
" 30px "+FONT_2,"#f1aa00");A.x=20;A.y=51;A.textAlign="left";A.textBaseline="alphabetic";s_oStage.addChild(A);for(a=0;a<NUM_SWIMMERS;a++){q.push(createBitmap(n));var p=q.length-1;q[p].x=CANVAS_WIDTH+n.width;q[p].y=m[p].y;q[p].visible=!1;s_oStage.addChild(q[p])}this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.addArrivalPanel=function(a){var c=q[r].x;q[r].x=CANVAS_WIDTH+n.width;q[r].visible=!0;createjs.Tween.get(q[r]).to({x:c},100,createjs.Ease.quadInOut).call(function(){});p.push(new CPrintInfosOnPanel(c,
q[r].y,a,r));r++};this.unloadArrivalPanel=function(){for(var a=0;a<q.length;a++)createjs.Tween.get(q[a]).to({x:CANVAS_WIDTH+n.width},300,createjs.Ease.quadInOut).call(function(){}),p[a].unload()};this.getInfosArrivals=function(){return p};this.refreshTime=function(a){A.text=a};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h.unload(),h=null;k.unload();l.unload();s_oInterface=null};this.refreshButtonPos=function(a,n){k.setPosition(g-a,n+f);l.setPosition(c-a,n+e);!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||h.setPosition(d-a,n+b);A.x=20+a;A.y=51+n;v.x=10+a;v.y=15+n;for(var t=0;t<NUM_SWIMMERS;t++)q[t].x=m[t].x-a,q[t].y=m[t].y+n,p[t]&&p[t].setPos(m[t].x-a,m[t].y+n)};this.setGUIClickable=function(){t=!0};this._onButRestartRelease=function(){s_oGame.restartGame()};this.onExitFromHelp=function(){_oHelpPanel.unload()};this._onAudioToggle=function(){t?(createjs.Sound.setMute(s_bAudioActive),s_bAudioActive=!s_bAudioActive):h.setActive(!0)};this._onInfo=function(){if(t)s_oGame.onInfo()};this._onExit=
function(){if(t)s_oGame.onExitMessage()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CEndPanel(a,d){var b,c,e=0,g,f,h=CANVAS_WIDTH/2-180,k=CANVAS_HEIGHT/2-163,l,n=CANVAS_WIDTH/2-180,q=CANVAS_HEIGHT/2-134,m,p,r,t=s_oCityInfos.getPlayersArrivals(),v=[],A=[100,50,25,10,9,8,7,6];this._init=function(){var a=s_oSpriteLibrary.getSprite("result_panel");m=createBitmap(a);m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2;m.regX=a.width/2;m.regY=a.height/2;s_oStage.addChild(m);p=new createjs.Container;p.alpha=0;p.visible=!1;p.addChild(m);f=new createjs.Text("MEN'S "+100*s_iModeSelected+"M FREESTYLE",
" 20px "+FONT,"#ffffff");f.x=h;f.y=k;f.textAlign="left";f.textBaseline="alphabetic";p.addChild(f);l=new createjs.Text("Result"," 22px "+FONT,"#ffffff");l.x=n;l.y=q;l.textAlign="left";l.textBaseline="alphabetic";p.addChild(l);s_oStage.addChild(p);a=s_oSpriteLibrary.getSprite("but_continue_small");b=CANVAS_WIDTH/2+340;c=CANVAS_HEIGHT-178;r=new CGfxButton(b,c,a);r.addEventListener(ON_MOUSE_UP,this._onContinue,this);this.getSwimmerInLane();this.addScoreToPlayers()};this.show=function(){for(var c=460,
b=207,f=0;f<t[d].length;f++){var g=createBitmap(s_oSpriteLibrary.getSprite("flag_swimmer_"+t[d][f].player+"_game"));g.x=c;g.y=b;g.scaleX=g.scaleY=.3;p.addChild(g);c+=110;b+=17;g=new createjs.Text(a[f].name," 20px "+FONT,"#ffffff");g.x=c;g.y=b;g.textAlign="left";g.textBaseline="alphabetic";p.addChild(g);c+=305;g=new createjs.Text(a[f].time," 20px "+FONT,"#ffffff");g.x=c;g.y=b;g.textAlign="left";g.textBaseline="alphabetic";p.addChild(g);c=460;b+=21}p.visible=!0;createjs.Tween.get(p).to({alpha:1},500).call(function(){});
$(s_oMain).trigger("share_event",e);$(s_oMain).trigger("save_score",[e]);localStorage.setItem("Mode",s_iMode);localStorage.setItem("LevelReached",s_iLevelReached);localStorage.setItem("ModeSelected",s_iModeSelected);localStorage.setItem("Money",s_iPlayerMoney);localStorage.setItem("SpeedBought",s_iSpeedBought);localStorage.setItem("EnergyBought",s_iEnergyBought);localStorage.setItem("SpeedAdder",s_iSpeedAdder);localStorage.setItem("EnergyAdder",s_iEnergyAdder);localStorage.setItem("TeamSelected",
s_iTeamSelected);localStorage.setItem("TeamSelectedSprite",s_szTeamSelectedSprite);localStorage.setItem("Scores",JSON.stringify(s_aSwimmersScore));s_oCityInfos.addCitiesStorage()};this.getSwimmerInLane=function(){for(var a=0;a<t[0].length;a++)v.push(PLAYER_NAME_AND_SPRITE[t[d][a].player].sprite),v[a]===s_iTeamSelected&&(g=a)};this.addScoreToPlayers=function(){for(var a=0;a<t[d].length;a++)s_aSwimmersScore[t[d][a].player]+=A[t[d][a].position];e=s_aSwimmersScore[t[d][g].player]};this._onContinue=function(){playSound("click",
.5,0);s_oStage.removeChild(p);r.unload();s_oGame.onContinue()};this._init();return this}
function CSwimmer(a,d,b,c,e,g,f,h,k,l,n,q){var m=0,p=0,r=0,t,v,A=NUM_ROUNDS*f,B=l,E=B,H=g.name,D=g.sprite,u,G,C,y,M,I,J,Q,K,z,N=!1,L=!1,F=!0,O=!1,P=!1,x=!1,w=new CVector2(0,1),R=new CVector2;this._init=function(){switch(c){case 0:this.createSwimmer(s_oSpriteLibrary.getSprite("green_rope"));break;case 1:this.createSwimmer(s_oSpriteLibrary.getSprite("blue_rope"));break;case 2:this.createSwimmer(s_oSpriteLibrary.getSprite("yellow_rope"));break;case 3:this.createSwimmer(s_oSpriteLibrary.getSprite("yellow_rope"));
break;case 4:this.createSwimmer(s_oSpriteLibrary.getSprite("yellow_rope"));break;case 5:this.createSwimmer(s_oSpriteLibrary.getSprite("blue_rope"));break;case 6:this.createSwimmer(s_oSpriteLibrary.getSprite("green_rope"));break;case 7:this.createSwimmer(s_oSpriteLibrary.getSprite("edge"))}};this.createSwimmer=function(e){var f=s_oSpriteLibrary.getSprite("swimmer_"+D+"_dive"),f={images:[f],framerate:15,frames:{width:PLAYER_DIVE_WIDTH,height:PLAYER_DIVE_HEIGHT,regX:PLAYER_DIVE_WIDTH/2,regY:PLAYER_DIVE_HEIGHT/
2},animations:{idle:[0,18,"last_frame"],last_frame:[18]}};G=new createjs.SpriteSheet(f);t=G.getNumFrames("idle");f={images:[s_oSpriteLibrary.getSprite("splash_sprite")],framerate:15,frames:{width:WATER_DIVE_WIDTH,height:WATER_DIVE_HEIGHT,regX:WATER_DIVE_WIDTH/2,regY:WATER_DIVE_HEIGHT/2},animations:{idle:[0,9,"last_frame"],last_frame:[10]}};f=new createjs.SpriteSheet(f);C=createSprite(f,"idle",0,0,WATER_DIVE_WIDTH,WATER_DIVE_HEIGHT);C.x=a;C.y=d;C.currentAnimationFrame=0;C.visible=!1;C.stop();b.addChild(C);
f=s_oSpriteLibrary.getSprite("swimmer_"+D+"_swimming_back");y=new createjs.SpriteSheet({images:[f],framerate:15,frames:{width:PLAYER_SWIMMING_WIDTH,height:PLAYER_SWIMMING_HEIGHT,regX:PLAYER_SWIMMING_WIDTH/2,regY:PLAYER_SWIMMING_HEIGHT/2},animations:{swim:[0,14,"swim"]}});f=s_oSpriteLibrary.getSprite("swimmer_"+D+"_swimming_front");I=new createjs.SpriteSheet({images:[f],framerate:15,frames:{width:PLAYER_SWIMMING_FRONT_WIDTH,height:PLAYER_SWIMMING_FRONT_HEIGHT,regX:PLAYER_SWIMMING_FRONT_WIDTH/2,regY:PLAYER_SWIMMING_FRONT_HEIGHT/
2+2},animations:{swim:[0,14,"swim"]}});f=s_oSpriteLibrary.getSprite("swimmer_"+D+"_turn_back");M=new createjs.SpriteSheet({images:[f],framerate:15,frames:{width:PLAYER_TURN_WIDTH,height:PLAYER_TURN_HEIGHT,regX:PLAYER_TURN_WIDTH/2,regY:PLAYER_TURN_HEIGHT/2},animations:{turn:[0,14,"turn"]}});v=M.getNumFrames("turn");f=s_oSpriteLibrary.getSprite("swimmer_"+D+"_turn_front");J=new createjs.SpriteSheet({images:[f],framerate:15,frames:{width:PLAYER_TURN_WIDTH,height:PLAYER_TURN_HEIGHT,regX:PLAYER_TURN_WIDTH/
2,regY:PLAYER_TURN_HEIGHT/2},animations:{turn:[0,14,"turn"]}});f=s_oSpriteLibrary.getSprite("swimmer_"+D+"_idle");Q=new createjs.SpriteSheet({images:[f],framerate:15,frames:{width:PLAYER_IDLE_WIDTH,height:PLAYER_IDLE_HEIGHT,regX:PLAYER_IDLE_WIDTH/2,regY:PLAYER_IDLE_HEIGHT/3},animations:{idle:[0,12,"idle"]}});u=new createjs.Sprite(G,"idle");u.x=a;u.y=d;u.currentAnimationFrame=0;b.addChild(u);c!==NUM_SWIMMERS-1&&(K=createBitmap(e),K.x=u.x+80,K.y=u.y+45,K.rotation=-14,b.addChild(K));r=DIVE_ANIMATION;
u.stop();rotateVector2D(Math.PI/180*104,w)};this.stopAnimation=function(){u.stop()};this.playAnimation=function(){u.play()};this.checkDistance=function(a){L||(a=this.distance2(R,a)/100,10>a&&r===SWIMMING_ANIMATION&&!N&&(e?(s_oGame.spawnBar(),this.stopAnimation()):this.showAnimationTurn(Math.floor(4*Math.random()))),10>a&&r===SWIMMING_FRONT_ANIMATION&&(1<A?(e?(s_oGame.spawnBar(),this.stopAnimation(),L=!0):this.showFrontAnimationTurn(Math.floor(4*Math.random())),A--):(F&&(F=!1,s_oGame.addInArrayPlayerArrived(c,
H)),m=0)))};this.showIdleAnimation=function(){z&&createjs.Tween.get(z).to({alpha:0},500).call(function(){});u.spriteSheet=Q;u.currentAnimationFrame=0;r=SWIMMING_ANIMATION;u.gotoAndPlay("idle")};this.showSwimmingAnimation=function(){setTimeout(function(){N=!1},500);u.spriteSheet=y;u.currentAnimationFrame=0;r===DIVE_ANIMATION&&(u.x+=10,u.y+=30,e&&(z=createBitmap(s_oSpriteLibrary.getSprite("arrow_bar")),z.x=u.x,z.y=u.y-55,z.scaleX=.4,z.scaleY=.4,z.alpha=0,s_oStage.addChild(z),this.cursorAnimationDown()));
z&&(z.x=u.x+20,createjs.Tween.get(z).to({alpha:1},500).call(function(){}));r===TURN_FRONT_ANIMATION&&(u.y-=10);r=SWIMMING_ANIMATION;u.gotoAndPlay("swim");e&&R.set(u.x,u.y)};this.cursorAnimationDown=function(){createjs.Tween.get(z).to({y:z.y+10},500).call(function(){S.cursorAnimationUp()})};this.cursorAnimationUp=function(){createjs.Tween.get(z).to({y:z.y-10},500).call(function(){S.cursorAnimationDown()})};this.showFrontSwimmingAnimation=function(){u.spriteSheet=I;u.currentAnimationFrame=0;r=SWIMMING_FRONT_ANIMATION;
u.gotoAndPlay("swim");z&&(z.x=u.x-30,createjs.Tween.get(z).to({alpha:1},500).call(function(){}))};this.showAnimationTurn=function(a){z&&createjs.Tween.get(z).to({alpha:0},500).call(function(){});L=N=!0;O=!1;r===SWIMMING_ANIMATION&&(u.y+=10);r=TURN_ANIMATION;u.spriteSheet=M;u.currentAnimationFrame=0;u.gotoAndPlay("turn");switch(a){case 0:case 4:u.framerate=11;break;case 1:case 3:u.framerate=13;break;case 2:u.framerate=15}p=.8*m};this.showFrontAnimationTurn=function(a){z&&createjs.Tween.get(z).to({alpha:0},
500).call(function(){});L=N=!0;O=!1;r=TURN_FRONT_ANIMATION;u.spriteSheet=J;u.currentAnimationFrame=0;u.gotoAndPlay("turn");switch(a){case 0:case 4:u.framerate=11;break;case 1:case 3:u.framerate=13;break;case 2:u.framerate=15}p=.8*m};this.distance2=function(a,c){return(c.getX()-a.getX())*(c.getX()-a.getX())+(c.getY()-a.getY())*(c.getY()-a.getY())};this.move=function(){F&&(u.x+=m*w.getX(),u.y+=m*w.getY(),R.set(u.x,u.y))};this.movementAffectedByPlayer=function(a,b){e||(u.x+=a*b.getX(),u.y+=a*b.getY());
c!==NUM_SWIMMERS-1&&(K.x+=a*b.getX(),K.y+=a*b.getY());C.x-=m*w.getX();C.y-=m*w.getY()};this.addSpeed=function(){!L&&F&&(m>=h&&(m=h),0<=B&&(B-=n,m+=B/E*MODIFIER_SPEED_ADDER,m<=k&&(m=k)))};this.changeDirection=function(){rotateVector2D(Math.PI/180*180,w)};this.decreaseSpeed=function(){!L&&F&&(m-=SPEED_DECELERATION,m<=k&&(m=k))};this.increaseEnergy=function(){B<E&&(B+=.14)};this.getEnergyProportion=function(){return B/E};this.getOccurrenceSwim=function(){return q};this.getInfos=function(){return{sprite:D,
nationality:H}};this.getSpeed=function(){return m};this.getEnergy=function(){return B};this.unload=function(){u=null;b.removeAllChildren()};this.update=function(){r===DIVE_ANIMATION&&u.currentFrame>=SWIMMING_FRONT_ANIMATION&&(m=SPEED_ON_DIVE,u.currentFrame===t-1&&(this.showSwimmingAnimation(),C.stop(),C.visible=!1),u.currentFrame>=HALF_DIVE_ANIMATION_FRAME&&!x&&(e&&s_oGame.halfAnimationDive(),C.x=u.x+35,C.y=u.y,C.play(),x=C.visible=!0));if(r===TURN_ANIMATION||r===TURN_FRONT_ANIMATION)u.currentFrame===
v-1&&(r===TURN_ANIMATION?this.showFrontSwimmingAnimation():this.showSwimmingAnimation(),s_oGame.haveTurned(c)),u.currentFrame>=HALF_TURN_ANIMATION_FRAME&&!O&&(O=!0,e?s_oGame.changeBGsDirection():S.changeDirection(),m=p,L=!1),O||(m*=DECELERATION_ON_TURN,m<=SPEED_MIN_ON_TURN&&(m=SPEED_MIN_ON_TURN));m<=SPEED_MIN_FOR_IDLE&&!P&&r>DIVE_ANIMATION&&(this.showIdleAnimation(),P=!0)};var S=this;s_oPlayer=this;this._init()}s_oPlayer=null;
function CScrollingBg(a){var d=[],b,c,e=new CVector2(0,1);this._init=function(){var c=s_oSpriteLibrary.getSprite("pool_0");d[0]=createBitmap(c);d[0].y=-CANVAS_HEIGHT;d[0].scaleX=d[0].scaleY=2;a.addChild(d[0]);c=s_oSpriteLibrary.getSprite("pool_1");d[1]=createBitmap(c);d[1].x=CANVAS_WIDTH;d[1].y=-CANVAS_HEIGHT;d[1].scaleX=d[1].scaleY=2;a.addChild(d[1]);c=s_oSpriteLibrary.getSprite("pool_2");d[2]=createBitmap(c);d[2].scaleX=d[2].scaleY=2;a.addChild(d[2]);c=s_oSpriteLibrary.getSprite("pool_3");d[3]=
createBitmap(c);d[3].x=CANVAS_WIDTH;d[3].scaleX=d[3].scaleY=2;a.addChild(d[3]);rotateVector2D(Math.PI/180*-76,e)};this.setArrivalPositions=function(a){c=a};this.setEndPositions=function(a){b=a};this.changeDir=function(){rotateVector2D(Math.PI/180*180,e)};this.move=function(a){for(var f=0;f<d.length;f++)d[f].x+=a*e.getX(),d[f].y+=a*e.getY();for(f=0;f<c.length;f++)c[f].x+=a*e.getX(),c[f].y+=a*e.getY();for(f=0;f<b.length;f++)b[f].x+=a*e.getX(),b[f].y+=a*e.getY()};this.getArrivalPositions=function(a){return new CVector2(c[a].x,
c[a].y)};this.getEndPositions=function(a){return new CVector2(b[a].x,b[a].y)};this.getDirectionVector=function(){return e};this._init()}
function CHealtBar(){var a,d,b=100,c,e,g,f=CANVAS_WIDTH/2+170,h=CANVAS_HEIGHT-60,k=CANVAS_WIDTH/2+170,l=CANVAS_HEIGHT-56;this.init=function(){var b=s_oSpriteLibrary.getSprite("healt");e=createBitmap(b);e.x=k;e.y=l;e.regX=b.width;e.alpha=.9;s_oStage.addChild(e);a=b.width;d=b.height-6;g=new createjs.Shape;g.graphics.beginFill("rgba(0,255,255,1)").drawRect(e.x-a,e.y,a,d+3);s_oStage.addChild(g);b=s_oSpriteLibrary.getSprite("energy_bar");c=createBitmap(b);c.x=f;c.y=h;c.regX=b.width;s_oStage.addChild(c);
e.mask=g;this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshMask=function(c){b=c;g.graphics.clear();c=Math.floor(b*a/100);g.graphics.beginFill("rgba(0,255,255,0.01)").drawRect(e.x-a,e.y+3,c,d)};this.refreshButtonPos=function(a,d){e.y=l-d;c.y=h-d;this.refreshMask(b)};s_oHealtBar=this;this.init()}var s_oHealtBar=null;
function CIndicatorController(a){var d,b,c,e,g=!0,f,h,k,l,n,q,m,p,r=!0;this.init=function(){k=a;q=new createjs.Container;s_oStage.addChild(q);q.alpha=0;var f=s_oSpriteLibrary.getSprite("right_bar");m=createBitmap(f);q.addChild(m);q.x=CANVAS_WIDTH/2;q.y=CANVAS_HEIGHT/2-130;f=s_oSpriteLibrary.getSprite("arrow_bar");p=createBitmap(f);p.x=40;p.y=0;p.rotation=90;q.addChild(p);c=CANVAS_WIDTH/2;e=0;d=CANVAS_WIDTH/2;b=BARY-50;this.reset();createjs.Tween.get(q).to({alpha:1},500,createjs.Ease.quadInOut).call(function(){})};
this.scaleBar=function(a){f=a;m.scaleX=f;m.scaleY=f;p.scaleX=f;p.scaleY=f;d*=a;b*=a};this.reset=function(){h=SHOT_INDICATOR_SPEED;l=new CVector2;l.set(c,e);n=new CVector2;n.set(d,b)};this.increaseSpeed=function(){h-=DECREASE_SHOT_INDICATOR_SPEED};this.show=function(){g=!0;q.visible=g};this.hide=function(){g=!1;q.visible=g};this.getPosition=function(){return Math.floor(p.y/k)};this.startAnimation=function(){var a=this;r?createjs.Tween.get(p,{override:!0}).to({y:b},h,createjs.Ease.quadInOut).call(function(){r=
!r;a.startAnimation()}):createjs.Tween.get(p,{override:!0}).to({y:e},h,createjs.Ease.quadInOut).call(function(){r=!r;a.startAnimation()})};this.endAnimation=function(){createjs.Tween.get(p,{override:!0}).to({y:p.y},0).call(function(){})};this.unload=function(){createjs.Tween.get(q).to({alpha:0},500,createjs.Ease.quadInOut).call(function(){s_oStage.removeChild(q)})};this.init()}
function CMobileControls(){var a=CANVAS_HEIGHT-150,d,b=CANVAS_WIDTH-100,c=CANVAS_HEIGHT-150,e,g={x:CANVAS_WIDTH/2,y:410};this.init=function(){var f=s_oSpriteLibrary.getSprite("left_button");d=new CGfxButton(100,a,f,s_oStage);d.addEventListenerWithParams(ON_MOUSE_DOWN,s_oGame.onButtonDown,this,LEFT_DIR);f=s_oSpriteLibrary.getSprite("right_button");e=new CGfxButton(b,c,f,s_oStage);e.addEventListenerWithParams(ON_MOUSE_DOWN,s_oGame.onButtonDown,this,RIGHT_DIR);f=s_oSpriteLibrary.getSprite("but_continue_small");
g=new CGfxButton(g.x,g.y,f,s_oStage);g.addEventListener(ON_MOUSE_DOWN,s_oGame.turnPlayer,this);g.setVisible(!1);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.spawnButtonForBar=function(){d.setVisible(!1);e.setVisible(!1);g.setVisible(!0)};this.hideButtonForBar=function(){d.setVisible(!0);e.setVisible(!0);g.setVisible(!1)};this.hideButtons=function(){d.setVisible(!1);e.setVisible(!1)};this.refreshButtonPos=function(f,g){d.setPosition(100+f,a);e.setPosition(b-f,c)};this.unload=function(){d.unload();
e.unload()};s_oMobileControls=this;this.init()}var s_oMobileControls=null;
function CPrintInfosOnPanel(a,d,b,c){var e=c+1,g,f=b.lane+1,h=b.name,k=b.time,l;this.init=function(){l=new createjs.Container;l.x=a;l.y=d;l.alpha=0;s_oStage.addChild(l);switch(e){case 1:g=e+"st";break;case 2:g=e+"nd";break;case 3:g=e+"rd";break;case 4:case 5:case 6:case 7:case 8:g=e+"th"}var c=new createjs.Text(g," 15px "+FONT,"#ffffff");c.x=10;c.y=20;c.textAlign="left";c.textBaseline="alphabetic";l.addChild(c);c=new createjs.Text(h," 15px "+FONT,"#ffffff");c.x=10;c.y=40;c.textAlign="left";c.textBaseline=
"alphabetic";l.addChild(c);c=new createjs.Text(TEXT_LANE+": "+f," 15px "+FONT,"#ffffff");c.x=230;c.y=20;c.textAlign="right";c.textBaseline="alphabetic";l.addChild(c);c=new createjs.Text(TEXT_TIME+": "+k," 15px "+FONT,"#ffffff");c.x=230;c.y=40;c.textAlign="right";c.textBaseline="alphabetic";l.addChild(c);createjs.Tween.get(l).to({alpha:1},400,createjs.Ease.quadInOut).call(function(){})};this.setPos=function(a,c){l.x=a;l.y=c};this.unload=function(){createjs.Tween.get(l).to({alpha:0},400,createjs.Ease.quadInOut).call(function(){s_oStage.removeChild(l)})};
this.init()}
function CModeSelect(){var a,d,b,c,e,g,f=1,h,k,l,n,q,m,p,r;this._init=function(){m=createBitmap(s_oSpriteLibrary.getSprite("bg_select_team"));s_oStage.addChild(m);var f=s_oSpriteLibrary.getSprite("select_challenge"),v=createBitmap(f);v.x=CANVAS_WIDTH/2;v.y=CANVAS_HEIGHT/2;v.regX=f.width/2;v.regY=f.height/2;s_oStage.addChild(v);f=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-f.height/2-10;g=f.height/2+10;p=new CGfxButton(e,g,f,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onExit,this);b=CANVAS_WIDTH-
f.width/2-90;c=f.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=s_oSpriteLibrary.getSprite("audio_icon"),r=new CToggle(b,c,f,s_bAudioActive),r.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);q=new createjs.Text(TEXT_MODE," 20px "+FONT,"#ffffff");q.x=CANVAS_WIDTH/2-180;q.y=128;q.textAlign="left";q.textBaseline="alphabetic";q.lineWidth=1E3;s_oStage.addChild(q);f=s_oSpriteLibrary.getSprite("100_m");k=new CToggle(CANVAS_WIDTH/2-180,CANVAS_HEIGHT/2-25,f,!0);k.addEventListenerWithParams(ON_MOUSE_UP,
this._onModeToggle,this,EASY);f=s_oSpriteLibrary.getSprite("200_m");l=new CToggle(CANVAS_WIDTH/2,CANVAS_HEIGHT/2-25,f,!1);l.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,NORMAL);f=s_oSpriteLibrary.getSprite("400_m");n=new CToggle(CANVAS_WIDTH/2+180,CANVAS_HEIGHT/2-25,f,!1);n.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,HARD);f=s_oSpriteLibrary.getSprite("but_continue_small");a=CANVAS_WIDTH/2;d=CANVAS_HEIGHT/2+125;h=new CGfxButton(a,d,f,s_oStage);h.addEventListener(ON_MOUSE_UP,
this._onButNextRelease,this);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this._onModeToggle=function(a){f=a;switch(f){case EASY:k.setActive(!0);l.setActive(!1);n.setActive(!1);break;case NORMAL:k.setActive(!1);l.setActive(!0);n.setActive(!1);break;case HARD:k.setActive(!1),l.setActive(!1),n.setActive(!0)}};this._onExit=function(){s_oMain.gotoMenu();$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=
!s_bAudioActive};this.unload=function(){k.unload();l.unload();n.unload();s_oStage.removeAllChildren()};this.refreshButtonPos=function(a,d){p.setPosition(e-a,d+g);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.setPosition(b-a,d+c)};this._onButNextRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_iModeSelected=f;s_oMain.gotoSelectLevel()};s_oModeSelect=this;this._init()}var s_oModeSelect=null;
function CLevelMenu(){var a,d,b,c,e=s_iModeSelected,g,f=[],h,k,l;this._init=function(){h=createBitmap(s_oSpriteLibrary.getSprite("bg_select_team"));s_oStage.addChild(h);var e=s_oSpriteLibrary.getSprite("select_challenge");h=createBitmap(e);h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2;h.regX=e.width/2;h.regY=e.height/2;s_oStage.addChild(h);g=new createjs.Text(TEXT_CHALLENGE," 20px "+FONT,"#ffffff");g.x=CANVAS_WIDTH/2-180;g.y=128;g.textAlign="left";g.textBaseline="alphabetic";g.lineWidth=1E3;s_oStage.addChild(g);
for(var e=CANVAS_WIDTH/2-240,q=0,m=50,p=0;p<s_oCityInfos.getNumLevels();p++,q+=120){500<q&&(q=0,m+=175);var r=s_oCityInfos.getCityName(p),t=s_oCityInfos.getRewards(p);p<s_iLevelReached?f.push(new CLevelBut(e+q,215+m,s_oSpriteLibrary.getSprite("level_sprite"),!0,p+1,r,t)):f.push(new CLevelBut(e+q,215+m,s_oSpriteLibrary.getSprite("level_sprite"),!1,p+1,r,t));f[p].addEventListenerWithParams(ON_MOUSE_UP,this._onClick,this,p);f[p].addEventListenerWithParams(ON_MOUSE_DOWN,this._onMouseDown,this,p);s_bFirstTime=
!0}e=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-e.height/2-10;c=e.height/2+10;k=new CGfxButton(b,c,e,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onExit,this);a=CANVAS_WIDTH-e.width/2-90;d=e.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e=s_oSpriteLibrary.getSprite("audio_icon"),l=new CToggle(a,d,e,s_bAudioActive),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){for(var a=0;a<s_oCityInfos.getNumLevels();a++)f[a].unload();
s_oLevelMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(e,f){k.setPosition(b-e,f+c);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(a-e,f+d)};this._onNumModeToggle=function(a){a===NUM_ACTIVE?((void 0).setActive(!1),(void 0).setActive(!0)):((void 0).setActive(!0),(void 0).setActive(!1))};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onMouseDown=function(a){f[a].scaleText()};this._onClick=function(a){!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");f[a].ifClickable()&&(s_oLevelMenu.unload(),s_oMain.gotoGame(e,a))};this._onExit=function(){s_oLevelMenu.unload();s_oMain.gotoMenu();$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(a,d,b,c,e,g,f){var h,k,l,n=[],q=[],m,p,r,t,v;this._init=function(a,c,b,d){k=[];l=[];v=new createjs.Container;v.x=a;v.y=c;s_oStage.addChild(v);var e=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}});h=d;m=createSprite(e,"state_"+h,b.width/2/2,b.height/2,b.width/2,b.height);m.mouseEnabled=d;m.x=0;m.y=0;m.cursor="pointer";m.stop();v.addChild(m);n.push(m);b=new createjs.Text(g,
" 15px "+FONT,"#ffffff");b.x=a;b.y=c-70;b.textAlign="center";b.textBaseline="alphabetic";b.lineWidth=200;s_oStage.addChild(b);p=new createjs.Text(f.first+TEXT_CURRENCY," 20px "+FONT,"#fff");p.x=8;p.y=-40;p.textAlign="center";p.textBaseline="middle";p.lineWidth=200;v.addChild(p);r=new createjs.Text(f.second+TEXT_CURRENCY," 20px "+FONT,"#fff");r.x=8;r.y=p.y+35;r.textAlign="center";r.textBaseline="middle";r.lineWidth=200;v.addChild(r);t=new createjs.Text(f.third+TEXT_CURRENCY," 20px "+FONT,"#fff");t.x=
8;t.y=p.y+70;t.textAlign="center";t.textBaseline="middle";t.lineWidth=200;v.addChild(t);this._initListener()};this.scaleText=function(){v.scaleY=.9};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);s_oStage.removeChild(m)};this._initListener=function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.viewBut=function(a){s_oStage.addChild(a)};this.addEventListener=function(a,c,b){k[a]=c;l[a]=b};this.addEventListenerWithParams=function(a,
c,b,d){k[a]=c;l[a]=b;q=d};this.ifClickable=function(){return!0===m.mouseEnabled?1:0};this.setActive=function(a,c){h=c;n[a].gotoAndStop("state_"+h);n[a].mouseEnabled=!0};this.buttonRelease=function(){v.scaleX=1;v.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");h=!h;m.gotoAndStop("state_"+h);k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(l[ON_MOUSE_UP],q)};this.buttonDown=function(){v.scaleX=.9;v.scaleY=.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],q)};this.setPosition=
function(a,c){m.x=a;m.y=c};this.setVisible=function(a){m.visible=a};this._init(a,d,b,c)}
function CCitySettings(){var a=[],d=[],b=[],c=[],e=[],g=[],f=[];this._init=function(){this.initCityName();this.initRewards();this.initRewardTaken();this.initTimeSpent();this.initRewardEarned();this.initValueToAddInEachLevelToCPU();this.initArrivalsPosition()};this.initCityName=function(){a.push("Seattle");a.push("San Francisco");a.push("Miami");a.push("New Orleans");a.push("Chicago");a.push("Washington");a.push("New York");a.push("Los Angeles");a.push("Cleveland");a.push("Rio")};this.initRewards=
function(){d.push({first:100,second:50,third:25});d.push({first:100,second:50,third:25});d.push({first:100,second:50,third:25});d.push({first:100,second:50,third:25});d.push({first:100,second:50,third:25});d.push({first:100,second:50,third:25});d.push({first:100,second:50,third:25});d.push({first:100,second:50,third:25});d.push({first:125,second:75,third:50});d.push({first:150,second:100,third:75})};this.initRewardTaken=function(){b.push(!1);b.push(!1);b.push(!1);b.push(!1);b.push(!1);b.push(!1);
b.push(!1);b.push(!1);b.push(!1);b.push(!1)};this.initTimeSpent=function(){c.push(null);c.push(null);c.push(null);c.push(null);c.push(null);c.push(null);c.push(null);c.push(null);c.push(null);c.push(null)};this.initRewardEarned=function(){e.push(null);e.push(null);e.push(null);e.push(null);e.push(null);e.push(null);e.push(null);e.push(null);e.push(null);e.push(null)};this.initValueToAddInEachLevelToCPU=function(){g.push({speed:0,energy:0});g.push({speed:.2,energy:2});g.push({speed:.4,energy:4});g.push({speed:.6,
energy:6});g.push({speed:.8,energy:8});g.push({speed:1,energy:10});g.push({speed:1.2,energy:12});g.push({speed:1.4,energy:14});g.push({speed:1.6,energy:16});g.push({speed:1.8,energy:18})};this.initArrivalsPosition=function(){f.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);f.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,
position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);f.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);f.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);f.push([{player:0,
position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);f.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);f.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,
position:-1},{player:0,position:-1},{player:0,position:-1}]);f.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);f.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);f.push([{player:0,position:-1},{player:0,position:-1},
{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}])};this.addCitiesStorage=function(){localStorage.setItem("RewardTaken",JSON.stringify(b));localStorage.setItem("TimeSpent",JSON.stringify(c));localStorage.setItem("RewardEarned",JSON.stringify(e));localStorage.setItem("ArrivalsPosition",JSON.stringify(f))};this.removeCitiesStorage=function(){b=[];c=[];e=[];f=[];this.initRewardTaken();this.initTimeSpent();this.initRewardEarned();
this.initArrivalsPosition();localStorage.removeItem("RewardTaken");localStorage.removeItem("TimeSpent");localStorage.removeItem("RewardEarned");localStorage.removeItem("ArrivalsPosition")};this.getCitiesStorage=function(){b=JSON.parse(localStorage.getItem("RewardTaken"));c=JSON.parse(localStorage.getItem("TimeSpent"));e=JSON.parse(localStorage.getItem("RewardEarned"));f=JSON.parse(localStorage.getItem("ArrivalsPosition"))};this.getLevel=function(a){return a};this.getNumLevels=function(){return a.length};
this.getCityName=function(c){return a[c]};this.getRewards=function(a){return d[a]};this.getValuesToAdd=function(a){return g[a]};this.setRewardTaken=function(a,c){if(!b[a]){b[a]=!0;switch(c){case 0:e[a]=d[a].first;break;case 1:e[a]=d[a].second;break;case 2:e[a]=d[a].third}s_iPlayerMoney+=e[a]}};this.setPlayersArrivals=function(a,c){f[a]=c};this.getPlayersArrivals=function(){return f};this.getRewardTaken=function(a){return b[a]?e[a]:0};this.getMedal=function(a){return e[a]===d[a].first?"gold":e[a]===
d[a].second?"silver":e[a]===d[a].third?"bronze":null};this.setTimeSpent=function(a,b){c[a]=b};this.getTimeSpent=function(a){return c[a]};this.unload=function(){a=[];d=[];b=[];c=[];e=[];g=[];f=[]};this._init()}
function CShowNationalityInLane(a){var d,b=[{x:90,y:190},{x:170,y:227},{x:250,y:265},{x:330,y:303},{x:410,y:340},{x:490,y:378},{x:575,y:418},{x:665,y:460}],c;this._init=function(){d=new createjs.Container;s_oStage.addChild(d);for(var e=0;e<a.length;e++){var g=s_oSpriteLibrary.getSprite("flag_swimmer_"+a[e].sprite+"_game");c=createBitmap(g);c.x=b[e].x;c.y=b[e].y;c.skewX=-60;c.rotation=-14;d.addChild(c)}};this._onButNextRelease=function(){s_oGame.enableMovement();this.unload()};this.unload=function(){createjs.Tween.get(d).to({alpha:0},
500).call(function(){s_oStage.removeChild(d)})};s_oShowLevelInfos=this;this._init()}var s_oShowLevelInfos=null;
function CPlayerProgress(){var a,d,b=[100,150,200,250],c,e=[50,75,100,125],g,f,h=[],k=[],l=CANVAS_WIDTH/2-135,n=175,q,m=[],p=[],r=CANVAS_WIDTH/2+165,t=175,v=s_iPlayerMoney,A,B,E,H=CANVAS_WIDTH/2-275,D=CANVAS_WIDTH/2+30,u=CANVAS_WIDTH/2-180,G,C=CANVAS_WIDTH/2-190,y=218,M=CANVAS_WIDTH/2-120,I=233,J,Q=CANVAS_WIDTH/2-265,K=233,z,N=CANVAS_WIDTH/2+200,L=233,F,O;this._init=function(){var x=createBitmap(s_oSpriteLibrary.getSprite("bg_select_team"));s_oStage.addChild(x);var x=s_oSpriteLibrary.getSprite("upgrade_panel"),
w=createBitmap(x);w.x=CANVAS_WIDTH/2;w.y=CANVAS_HEIGHT/2;w.regX=x.width/2;w.regY=x.height/2;s_oStage.addChild(w);x=new createjs.Text("Upgrades - Medals"," 20px "+FONT,"#ffffff");x.x=CANVAS_WIDTH/2-180;x.y=70;x.textAlign="left";x.textBaseline="alphabetic";s_oStage.addChild(x);f=new createjs.Shape;f.graphics.beginFill("#000000").drawRect(l-165,n-60,285,90);f.alpha=.01;f.on("mousedown",this.tryingToBuySpeed);f.cursor="pointer";s_oStage.addChild(f);q=new createjs.Shape;q.graphics.beginFill("#000000").drawRect(r-
160,t-60,285,90);q.alpha=.01;q.on("mousedown",this.tryingToBuyEnergy);q.cursor="pointer";s_oStage.addChild(q);x=new createjs.Text("BUY"," 20px "+FONT,"#ffffff");x.x=H;x.y=165;x.textAlign="left";x.textBaseline="alphabetic";s_oStage.addChild(x);x=new createjs.Text("BUY"," 20px "+FONT,"#ffffff");x.x=D;x.y=165;x.textAlign="left";x.textBaseline="alphabetic";s_oStage.addChild(x);for(w=0;w<NUM_POWER_UP_AVAILABLE;w++)h.push(createBitmap(s_oSpriteLibrary.getSprite("bar-1"))),h[w].x=l,h[w].y=n,s_oStage.addChild(h[w]),
k.push(createBitmap(s_oSpriteLibrary.getSprite("bar-2"))),k[w].x=l,k[w].y=n,k[w].visible=!1,s_oStage.addChild(k[w]),c=new createjs.Text(b[w]+TEXT_CURRENCY," 10px "+FONT,"#ffffff"),c.x=l+100,c.y=n+10,c.textAlign="center",c.textBaseline="alphabetic",s_oStage.addChild(c),m.push(createBitmap(s_oSpriteLibrary.getSprite("bar-1"))),m[w].x=r,m[w].y=t,s_oStage.addChild(m[w]),p.push(createBitmap(s_oSpriteLibrary.getSprite("bar-2"))),p[w].x=r,p[w].y=t,p[w].visible=!1,s_oStage.addChild(p[w]),g=new createjs.Text(e[w]+
TEXT_CURRENCY," 10px "+FONT,"#ffffff"),g.x=r+100,g.y=t+10,g.textAlign="center",g.textBaseline="alphabetic",s_oStage.addChild(g),n-=15,t-=15;for(w=0;w<s_iSpeedBought;w++)this.makeVisibleSpeedBought(w);for(w=0;w<s_iEnergyBought;w++)this.makeVisibleEnergyBought(w);G=new createjs.Text("Money:       "+v+TEXT_CURRENCY," 20px "+FONT,"#ffffff");G.x=u;G.y=100;G.textAlign="left";G.textBaseline="alphabetic";s_oStage.addChild(G);for(w=0;w<s_oCityInfos.getNumLevels();w++)A=s_oCityInfos.getCityName(w),B=formatTime(s_oCityInfos.getTimeSpent(w)),
E=s_oCityInfos.getRewardTaken(w),x=s_oCityInfos.getMedal(w),z=new createjs.Text(E+TEXT_CURRENCY," 15px "+FONT,"#ffffff"),z.x=Q,z.y=K,z.textAlign="center",z.textBaseline="alphabetic",s_oStage.addChild(z),x&&(x=createBitmap(s_oSpriteLibrary.getSprite(x+"_medal")),x.x=C,x.y=y,x.scaleX=.6,x.scaleY=.6,s_oStage.addChild(x)),J=new createjs.Text(A," 15px "+FONT,"#ffffff"),J.x=M,J.y=I,J.textAlign="left",J.textBaseline="alphabetic",s_oStage.addChild(J),F=new createjs.Text(B," 15px "+FONT,"#ffffff"),F.x=N,F.y=
L,F.textAlign="left",F.textBaseline="alphabetic",s_oStage.addChild(F),I+=38,y+=38,K+=38,L+=38;x=s_oSpriteLibrary.getSprite("but_continue_small");a=CANVAS_WIDTH/2+340;d=CANVAS_HEIGHT-91;O=new CGfxButton(a,d,x,s_oStage);O.addEventListener(ON_MOUSE_UP,this._onButNextRelease,this)};this.makeVisibleSpeedBought=function(a){h[a].visible=!1;k[a].visible=!0};this.makeVisibleEnergyBought=function(a){m[a].visible=!1;p[a].visible=!0};this.tryingToBuySpeed=function(){s_iSpeedBought<NUM_POWER_UP_AVAILABLE&&s_iPlayerMoney>=
b[s_iSpeedBought]&&(P.makeVisibleSpeedBought(s_iSpeedBought),s_iSpeedAdder+=PLAYER_MAX_SPEED_ADDER,s_iPlayerMoney-=b[s_iSpeedBought],P.refreshMoneyCurrency(),s_iSpeedBought++,localStorage.setItem("Money",s_iPlayerMoney),localStorage.setItem("SpeedBought",s_iSpeedBought),localStorage.setItem("SpeedAdder",s_iSpeedAdder),s_iSpeedBought<NUM_POWER_UP_AVAILABLE&&playSound("click",.5,0))};this.tryingToBuyEnergy=function(){s_iEnergyBought<NUM_POWER_UP_AVAILABLE&&s_iPlayerMoney>=e[s_iEnergyBought]&&(P.makeVisibleEnergyBought(s_iEnergyBought),
s_iEnergyAdder+=PLAYER_ENERGY_ADDER,s_iPlayerMoney-=e[s_iEnergyBought],P.refreshMoneyCurrency(),s_iEnergyBought++,localStorage.setItem("Money",s_iPlayerMoney),localStorage.setItem("EnergyBought",s_iEnergyBought),localStorage.setItem("EnergyAdder",s_iEnergyAdder),s_iEnergyBought<NUM_POWER_UP_AVAILABLE&&playSound("click",.5,0))};this.refreshMoneyCurrency=function(){G.text="Money:           "+s_iPlayerMoney+TEXT_CURRENCY};this._onButNextRelease=function(){this.unload();s_oMain.gotoSelectLevel(v)};this.unload=
function(){s_oStage.removeAllChildren();O.unload()};var P=this;this._init()}
function CVariousHelp(a,d){var b=this,c,e,g=CANVAS_WIDTH/2,f=CANVAS_HEIGHT/2,h,k,l,n;this._init=function(){e=new createjs.Container;e.x=g;e.y=f;e.alpha=0;k=new createjs.Shape;k.graphics.beginFill("#000000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=.7;k.on("mousedown",this._onClick);s_oStage.addChild(k);if(d===WAIT_FOR_GAME_START){var b=s_oSpriteLibrary.getSprite("select_challenge");c=createBitmap(b);c.regX=b.width/2;c.regY=b.height/2;e.addChild(c);h=new createjs.Text("HELP"," 20px "+FONT,
"#ffffff");h.x=-155;h.y=-193;h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=200;e.addChild(h);h=new createjs.Text(a," 20px "+FONT,"#ffb400");h.x=-150;h.y=-90;h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=200;e.addChild(h);s_bMobile?(h.text=TEXT_START_MOVEMENT_MOBILE,b=createBitmap(s_oSpriteLibrary.getSprite("left_button")),b.x=-215,b.y=5,b.scaleX=b.scaleY=.3,e.addChild(b),b=createBitmap(s_oSpriteLibrary.getSprite("right_button")),b.x=-130,b.y=5,b.scaleX=b.scaleY=.3,e.addChild(b),
b=new createjs.Text(HELP_TEXT_BAR_MOBILE," 15px "+FONT,"#ffb400"),b.x=120,b.y=-90,b.textAlign="center",b.textBaseline="alphabetic",b.lineWidth=200,e.addChild(b),b=createBitmap(s_oSpriteLibrary.getSprite("but_continue_small")),b.x=100,b.y=5,b.scaleX=.5,b.scaleY=.5):(b=createBitmap(s_oSpriteLibrary.getSprite("arrow_keys")),b.x=-200,b.scaleX=.5,b.scaleY=.5,e.addChild(b),b=new createjs.Text(HELP_TEXT_BAR," 20px "+FONT,"#ffb400"),b.x=120,b.y=-90,b.textAlign="center",b.textBaseline="alphabetic",b.lineWidth=
200);e.addChild(b);b=createBitmap(s_oSpriteLibrary.getSprite("vertical_bar"));b.x=0;b.y=-90;b.scaleX=.5;b.scaleY=.5;e.addChild(b);b=createBitmap(s_oSpriteLibrary.getSprite("right_bar"));b.x=250;b.y=-100;b.scaleX=.4;b.scaleY=.4;e.addChild(b);b=createBitmap(s_oSpriteLibrary.getSprite("arrow_bar"));b.x=280;b.y=-30;b.scaleX=.4;b.scaleY=.4;b.rotation=90;e.addChild(b);b=createBitmap(s_oSpriteLibrary.getSprite("horizontal_bar"));b.x=-140;b.y=60;b.scaleX=.5;b.scaleY=.5;e.addChild(b);b=new createjs.Text(HELP_ENERGY,
" 18px "+FONT,"#ffb400");b.x=0;b.y=135;b.textAlign="center";b.textBaseline="alphabetic";b.lineWidth=350;e.addChild(b);var b=s_oSpriteLibrary.getSprite("healt"),m=createBitmap(b);m.x=100;m.y=89;m.regX=b.width;m.scaleX=.59;m.scaleY=.5;m.alpha=.9;e.addChild(m);b=s_oSpriteLibrary.getSprite("energy_bar");m=createBitmap(b);m.x=100;m.y=85;m.scaleX=.6;m.scaleY=.6;m.regX=b.width;e.addChild(m)}else d===CONFIRMATION_ON_EXIT?(b=s_oSpriteLibrary.getSprite("various_help_box_2"),c=createBitmap(b),c.regX=b.width/
2,c.regY=b.height/2,e.addChild(c),h=new createjs.Text(a," 30px "+FONT,"#ffb400"),h.x=0,h.y=-40,h.textAlign="center",h.textBaseline="alphabetic",h.lineWidth=300,e.addChild(h),l=createBitmap(s_oSpriteLibrary.getSprite("but_exit")),l.x=-50,l.y=40,l.regX=30,l.regY=43,l.scaleX=-1,l.cursor="pointer",e.addChild(l),n=createBitmap(s_oSpriteLibrary.getSprite("but_yes")),n.x=50,n.y=40,n.regX=30,n.regY=43,n.cursor="pointer",e.addChild(n)):d===CONFIRMATION_ON_CAREER_RESET&&(b=s_oSpriteLibrary.getSprite("various_help_box_2"),
c=createBitmap(b),c.regX=b.width/2,c.regY=b.height/2,e.addChild(c),h=new createjs.Text(a," 30px "+FONT,"#ffb400"),h.x=0,h.y=-80,h.textAlign="center",h.textBaseline="alphabetic",h.lineWidth=300,e.addChild(h),l=createBitmap(s_oSpriteLibrary.getSprite("but_exit")),l.x=-50,l.y=70,l.regX=30,l.regY=43,l.scaleX=-1,l.cursor="pointer",e.addChild(l),n=createBitmap(s_oSpriteLibrary.getSprite("but_yes")),n.x=50,n.y=70,n.regX=30,n.regY=43,n.cursor="pointer",e.addChild(n));s_oStage.addChild(e);this.show()};this._initListener=
function(){d===CONFIRMATION_ON_EXIT?(l.addEventListener("click",this._onNo),n.addEventListener("click",this._onYes)):d===CONFIRMATION_ON_CAREER_RESET&&(l.addEventListener("click",this._onNoCareerReset),n.addEventListener("click",this._onYesCareerReset))};this.show=function(){createjs.Tween.get(e).to({alpha:1},500).call(function(){b._initListener()})};this._onNo=function(){s_oGame.unloadVariousHelp(d)};this._onYes=function(){s_oGame.onExit()};this._onNoCareerReset=function(){s_oMenu.unloadVariousHelp()};
this._onYesCareerReset=function(){s_oMenu.onContinue()};this._onClick=function(){d===WAIT_FOR_GAME_START&&s_oGame.unloadVariousHelp(CONFIRMATION_ON_EXIT)};this.unload=function(){createjs.Tween.get(e).to({alpha:0},500).call(function(){s_oStage.removeChild(e)});s_oStage.removeChild(k)};this._init();s_oVariousHelp=this;return this}var s_oVariousHelp=null;
function CPodiumScreen(a){var d,b,c=0,e,g,f,h,k=[],l=s_oCityInfos.getPlayersArrivals(),n=[100,50,25,10,9,8,7,6],q=[0,1,2,3,4,5,6,7],m=[{x:CANVAS_WIDTH/2-235,y:CANVAS_HEIGHT/2-60},{x:CANVAS_WIDTH/2-162,y:CANVAS_HEIGHT/2-10},{x:CANVAS_WIDTH/2-305,y:CANVAS_HEIGHT/2-10}];this._init=function(){this.getSwimmerInLane();this.addScoreToPlayers();this.findBestSwimmers();g=createBitmap(s_oSpriteLibrary.getSprite("bg_podium"));var a=createBitmap(s_oSpriteLibrary.getSprite("final_score"));a.x=CANVAS_WIDTH/2;a.y=
CANVAS_HEIGHT/2-150;f=new createjs.Container;f.alpha=0;f.visible=!1;f.addChild(g);f.addChild(a);s_oStage.addChild(f);var e=s_oSpriteLibrary.getSprite("but_restart");d=CANVAS_WIDTH/2+150;b=CANVAS_HEIGHT-160;h=new CGfxButton(d,b,e);h.addEventListener(ON_MOUSE_UP,this._onContinue,this);for(var k=0;3>k;k++)e=s_oSpriteLibrary.getSprite("swimmer_"+q[k]+"_pose"),a=createBitmap(e),a.x=m[k].x,a.y=m[k].y,a.regX=e.width/2,a.regY=e.height/2,a.scaleX=-.6,a.scaleY=.6,s_oStage.addChild(a);for(k=0;k<q.length;k++)q[k]===
s_iTeamSelected&&(a=new createjs.Text(k+1+TEXT_POSITION," 30px "+FONT,"#ffffff"),a.x=CANVAS_WIDTH/2+180,a.y=CANVAS_HEIGHT/2-90,a.textAlign="center",a.textBaseline="alphabetic",s_oStage.addChild(a),a=new createjs.Text(TEXT_SCORE+c," 30px "+FONT,"#ffffff"),a.x=CANVAS_WIDTH/2+20,a.y=CANVAS_HEIGHT/2-23,a.textAlign="left",a.textBaseline="alphabetic",s_oStage.addChild(a));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.show=function(){f.visible=!0;createjs.Tween.get(f).to({alpha:1},500).call(function(){});
$(s_oMain).trigger("share_event",c);$(s_oMain).trigger("save_score",[c])};this.getSwimmerInLane=function(){for(var c=0;c<l[0].length;c++)k.push(PLAYER_NAME_AND_SPRITE[l[a][c].player].sprite),k[c]===s_iTeamSelected&&(e=c)};this.addScoreToPlayers=function(){for(var b=0;b<l[a].length;b++)s_aSwimmersScore[l[a][b].player]+=n[l[a][b].position];c=s_aSwimmersScore[l[a][e].player]};this.findBestSwimmers=function(){for(var a=[],c=0;c<s_aSwimmersScore.length;c++)a[c]=s_aSwimmersScore[c];var b;do for(b=!1,c=
0;c<a.length;c++)a[c]<a[c+1]&&(b=a[c],a[c]=a[c+1],a[c+1]=b,b=q[c],q[c]=q[c+1],q[c+1]=b,b=!0);while(b)};this._onContinue=function(){s_oStage.removeChild(f);h.unload();s_oGame.onExit()};this.refreshButtonPos=function(a,c){h.setPosition(d,b-c)};this._init();return this}
function CWater(a){var d=0,b=0,c=[],e=new CVector2(0,1);this._init=function(){var b=s_oSpriteLibrary.getSprite("water_0");c[0]=createBitmap(b);c[0].x=205;c[0].y=-176;a.addChild(c[0]);c[0].scaleX=c[0].scaleY=2;c[0].visible=!0;if(!s_bMobile||s_bIsIphone)b=s_oSpriteLibrary.getSprite("water_1"),c[1]=createBitmap(b),c[1].x=205,c[1].y=-176,a.addChild(c[1]),c[1].scaleX=c[1].scaleY=2,c[1].sibile=!1,b=s_oSpriteLibrary.getSprite("water_2"),c[2]=createBitmap(b),c[2].x=205,c[2].y=-176,a.addChild(c[2]),c[2].scaleX=
c[2].scaleY=2,c[2].visible=!1,b=s_oSpriteLibrary.getSprite("water_3"),c[3]=createBitmap(b),c[3].x=205,c[3].y=-176,a.addChild(c[3]),c[3].scaleX=c[3].scaleY=2,c[3].visible=!1,b=s_oSpriteLibrary.getSprite("water_4"),c[4]=createBitmap(b),c[4].x=205,c[4].y=-176,a.addChild(c[4]),c[4].scaleX=c[4].scaleY=2,c[4].visible=!1,b=s_oSpriteLibrary.getSprite("water_5"),c[5]=createBitmap(b),c[5].x=205,c[5].y=-176,a.addChild(c[5]),c[5].scaleX=c[5].scaleY=2,c[5].visible=!1,b=s_oSpriteLibrary.getSprite("water_6"),c[6]=
createBitmap(b),c[6].x=205,c[6].y=-176,a.addChild(c[6]),c[6].scaleX=c[6].scaleY=2,c[6].visible=!1,b=s_oSpriteLibrary.getSprite("water_7"),c[7]=createBitmap(b),c[7].x=205,c[7].y=-176,a.addChild(c[7]),c[7].scaleX=c[7].scaleY=2,c[7].visible=!1,b=s_oSpriteLibrary.getSprite("water_8"),c[8]=createBitmap(b),c[8].x=205,c[8].y=-176,a.addChild(c[8]),c[8].scaleX=c[8].scaleY=2,c[8].visible=!1,b=s_oSpriteLibrary.getSprite("water_9"),c[9]=createBitmap(b),c[9].x=205,c[9].y=-176,a.addChild(c[9]),c[9].scaleX=c[9].scaleY=
2,c[9].visible=!1;rotateVector2D(Math.PI/180*-76,e)};this.update=function(){d+=s_iTimeElaps;100<=d&&(b<c.length-1?(c[b].visible=!1,b++):(c[b].visible=!1,b=0),c[b].visible=!0,d=0)};this.changeDir=function(){rotateVector2D(Math.PI/180*180,e)};this.move=function(a){for(var b=0;b<c.length;b++)c[b].x+=a*e.getX(),c[b].y+=a*e.getY()};this.getDirectionVector=function(){return e};this._init()}
function CCreditsPanel(){var a,d,b,c,e,g,f,h,k;this._init=function(){f=new createjs.Shape;f.graphics.beginFill("#000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=.7;s_oStage.addChild(f);var l=s_oSpriteLibrary.getSprite("select_challenge");d=createBitmap(l);d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2;d.regX=l.width/2;d.regY=l.height/2;s_oStage.addChild(d);h=new createjs.Shape;h.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=.01;h.on("click",this._onLogoButRelease);
s_oStage.addChild(h);l=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-l.height/2-395;c=new CGfxButton(a,215,l,s_oStage);c.addEventListener(ON_MOUSE_UP,this.unload,this);g=new createjs.Text(TEXT_CREDITS," 20px "+FONT,"#ffffff");g.x=CANVAS_WIDTH/2-180;g.y=126;g.textAlign="left";g.textBaseline="alphabetic";g.lineWidth=1E3;s_oStage.addChild(g);e=new CFormatText(CANVAS_WIDTH/2,250,TEXT_CREDITS_DEVELOPED,"#ffffff",s_oStage,"#410701",40);l=s_oSpriteLibrary.getSprite("logo_credits");b=createBitmap(l);
b.regX=l.width/2;b.regY=l.height/2;b.x=CANVAS_WIDTH/2;b.y=350;s_oStage.addChild(b);k=new CFormatText(CANVAS_WIDTH/2,450,TEXT_LINK1,"#ffffff",s_oStage,"#410701",40)};this.unload=function(){h.off("click",this._onLogoButRelease);c.unload();c=null;e.unload();k.unload();s_oStage.removeChild(d);s_oStage.removeChild(b);s_oStage.removeChild(h);s_oStage.removeChild(g);s_oStage.removeChild(f)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()}
function CFormatText(a,d,b,c,e,g,f){var h,k,l,n,q,m;this._init=function(a,b,c,d,e,f,g){h=c;n=new createjs.Container;n.x=a;n.y=b;e.addChild(n);a=g+"px";k=new createjs.Text;k.text=h;k.font="bold "+a+" "+FONT;k.color=f;k.textAlign="center";k.textBaseline="middle";k.lineWidth=600;k.outline=4;l=new createjs.Text;l.text=h;l.font="bold "+a+" "+FONT;l.color=d;l.textAlign="center";l.textBaseline="middle";l.lineWidth=600;n.addChild(l)};this.unload=function(){e.removeChild(n)};this.disableOutline=function(){n.removeChild(k)};
this.setVisible=function(a){n.visible=a};this.isVisible=function(){return n.visible};this.setOutline=function(a){k.outline=a};this.setShadow=function(a){k.shadow=a?new createjs.Shadow("#333333",2,2,6):null};this.setAlign=function(a){k.textAlign=a;l.textAlign=a};this.setWidth=function(a){k.lineWidth=a;l.lineWidth=a};this.setText=function(a){l.text=a;k.text=a};this.setColor=function(a,b){l.color=a;k.color=b};this.setFont=function(a){var b=f+"px";l.font="bold "+b+" "+a;k.font="bold "+b+" "+a};this.getText=
function(){return n};this.setPos=function(a){n.y=a};this.getPos=function(){return{x:n.x,y:n.y}};this.playText=function(){q="";this.setText("");this._slideText(0)};this._slideText=function(a){q+=b[a];this.setText(q);a<b.length-1&&setTimeout(function(){m._slideText(a+1)},40)};this.setPosition=function(a,b){n.x=a;n.y=b};m=this;this._init(a,d,b,c,e,g,f)};
