var s_iOffsetX=0,s_iOffsetY=0;
(function(b){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(b)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(b.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(b){console.log(b)}function isIOS(){for(var b="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");b.length;)if(navigator.platform===b.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}window.addEventListener("orientationchange",onOrientationChange);
function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(b){var c=b.toLowerCase(),a=window.document,f=a.documentElement;if(void 0===window["inner"+b])b=f["client"+b];else if(window["inner"+b]!=f["client"+b]){var d=a.createElement("body");d.id="vpw-test-b";d.style.cssText="overflow:scroll";var e=a.createElement("div");e.id="vpw-test-d";e.style.cssText="position:absolute;top:-1000px";e.innerHTML="<style>@media("+c+":"+f["client"+b]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";d.appendChild(e);f.insertBefore(d,a.head);
b=7==e["offset"+b]?f["client"+b]:window["inner"+b];f.removeChild(d)}else b=window["inner"+b];return b}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var b=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<b?b:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var b;b=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width");_checkOrientation(c,b);s_iScaleFactor=Math.min(b/CANVAS_HEIGHT,c/CANVAS_WIDTH);var a=CANVAS_WIDTH*s_iScaleFactor,f=CANVAS_HEIGHT*s_iScaleFactor,d;f<b?(d=b-f,f+=d,a+=CANVAS_WIDTH/CANVAS_HEIGHT*d):a<c&&(d=c-a,a+=d,f+=CANVAS_HEIGHT/CANVAS_WIDTH*d);d=b/2-f/2;var e=c/2-a/2,g=CANVAS_WIDTH/a;if(e*g<-EDGEBOARD_X||d*g<-EDGEBOARD_Y)s_iScaleFactor=
Math.min(b/(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*EDGEBOARD_X)),a=CANVAS_WIDTH*s_iScaleFactor,f=CANVAS_HEIGHT*s_iScaleFactor,d=(b-f)/2,e=(c-a)/2,g=CANVAS_WIDTH/a;s_iOffsetX=-1*e*g;s_iOffsetY=-1*d*g;0<=d&&(s_iOffsetY=0);0<=e&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",a+"px");$("#canvas").css("height",f+"px");0>d?$("#canvas").css("top",d+"px"):$("#canvas").css("top",
"0px");$("#canvas").css("left",e+"px")}}
function _checkOrientation(b,c){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(b>c?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(b){return!0}}function createBitmap(b,c,a){var f=new createjs.Bitmap(b),d=new createjs.Shape;c&&a?d.graphics.beginFill("#fff").drawRect(0,0,c,a):d.graphics.beginFill("#ff0").drawRect(0,0,b.width,b.height);f.hitArea=d;return f}function createSprite(b,c,a,f,d,e){b=null!==c?new createjs.Sprite(b,c):new createjs.Sprite(b);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-a,-f,d,e);b.hitArea=c;return b}
function randomFloatBetween(b,c,a){"undefined"===typeof a&&(a=2);return parseFloat(Math.min(b+Math.random()*(c-b),c).toFixed(a))}function shuffle(b){for(var c=b.length,a,f;0!==c;)f=Math.floor(Math.random()*c),--c,a=b[c],b[c]=b[f],b[f]=a;return b}function formatTime(b){b/=1E3;var c=Math.floor(b/60);b=parseFloat(b-60*c).toFixed(1);var a="",a=10>c?a+("0"+c+":"):a+(c+":");return 10>b?a+("0"+b):a+b}function degreesToRadians(b){return b*Math.PI/180}
function checkRectCollision(b,c){var a,f;a=getBounds(b,.9);f=getBounds(c,.98);return calculateIntersection(a,f)}function calculateIntersection(b,c){var a,f,d,e,g,h,k,l;a=b.x+(d=b.width/2);f=b.y+(e=b.height/2);g=c.x+(h=c.width/2);k=c.y+(l=c.height/2);a=Math.abs(a-g)-(d+h);f=Math.abs(f-k)-(e+l);return 0>a&&0>f?(a=Math.min(Math.min(b.width,c.width),-a),f=Math.min(Math.min(b.height,c.height),-f),{x:Math.max(b.x,c.x),y:Math.max(b.y,c.y),width:a,height:f,rect1:b,rect2:c}):null}
function getBounds(b,c){var a={x:Infinity,y:Infinity,width:0,height:0};if(b instanceof createjs.Container){a.x2=-Infinity;a.y2=-Infinity;var f=b.children,d=f.length,e,g;for(g=0;g<d;g++)e=getBounds(f[g],1),e.x<a.x&&(a.x=e.x),e.y<a.y&&(a.y=e.y),e.x+e.width>a.x2&&(a.x2=e.x+e.width),e.y+e.height>a.y2&&(a.y2=e.y+e.height);Infinity==a.x&&(a.x=0);Infinity==a.y&&(a.y=0);Infinity==a.x2&&(a.x2=0);Infinity==a.y2&&(a.y2=0);a.width=a.x2-a.x;a.height=a.y2-a.y;delete a.x2;delete a.y2}else{var h,k;b instanceof createjs.Bitmap?
(d=b.sourceRect||b.image,g=d.width*c,h=d.height*c):b instanceof createjs.Sprite?b.spriteSheet._frames&&b.spriteSheet._frames[b.currentFrame]&&b.spriteSheet._frames[b.currentFrame].image?(d=b.spriteSheet.getFrame(b.currentFrame),g=d.rect.width,h=d.rect.height,f=d.regX,k=d.regY):(a.x=b.x||0,a.y=b.y||0):(a.x=b.x||0,a.y=b.y||0);f=f||0;g=g||0;k=k||0;h=h||0;a.regX=f;a.regY=k;d=b.localToGlobal(0-f,0-k);e=b.localToGlobal(g-f,h-k);g=b.localToGlobal(g-f,0-k);f=b.localToGlobal(0-f,h-k);a.x=Math.min(Math.min(Math.min(d.x,
e.x),g.x),f.x);a.y=Math.min(Math.min(Math.min(d.y,e.y),g.y),f.y);a.width=Math.max(Math.max(Math.max(d.x,e.x),g.x),f.x)-a.x;a.height=Math.max(Math.max(Math.max(d.y,e.y),g.y),f.y)-a.y}return a}function NoClickDelay(b){this.element=b;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(b){switch(b.type){case "touchstart":this.onTouchStart(b);break;case "touchmove":this.onTouchMove(b);break;case "touchend":this.onTouchEnd(b)}},onTouchStart:function(b){b.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(b){this.moved=!0},onTouchEnd:function(b){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){b=document.elementFromPoint(b.changedTouches[0].clientX,b.changedTouches[0].clientY);3==b.nodeType&&(b=b.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);b.dispatchEvent(c)}}};
(function(){function b(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",b):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",b):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",b):(c="msHidden")in document?document.addEventListener("msvisibilitychange",b):"onfocusin"in document?document.onfocusin=document.onfocusout=b:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=b})();function playSound(b,c,a){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(b,{loop:a,volume:c}):null}function stopSound(b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||b.stop()}
function setVolume(b,c){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)b.volume=c}function setMute(b,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||b.setMute(c)}function playExistingSound(b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||b.play()}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(b){for(var c=window.location.search.substring(1).split("&"),a=0;a<c.length;a++){var f=c[a].split("=");if(f[0]==b)return f[1]}}function getRandomColor(){return"rgba("+(Math.floor(127*Math.random()+255)-127)+","+(Math.floor(127*Math.random()+255)-127)+","+(Math.floor(127*Math.random()+255)-127)+",1)"}function distance(b,c){return Math.sqrt((c.x-b.x)*(c.x-b.x)+(c.y-b.y)*(c.y-b.y))}function distanceWithoutSQRT(b,c){return(c.x-b.x)*(c.x-b.x)+(c.y-b.y)*(c.y-b.y)}
function dotProductV2(b,c){return b.getX()*c.getX()+b.getY()*c.getY()}function reflectVectorV2(b,c){var a=dotProductV2(b,c);b.set(b.getX()-2*a*c.getX(),b.getY()-2*a*c.getY());return b}
function CSpriteLibrary(){var b,c,a,f,d,e;this.init=function(g,h,k){a=c=0;f=g;d=h;e=k;b={}};this.addSprite=function(a,d){b.hasOwnProperty(a)||(b[a]={szPath:d,oSprite:new Image},c++)};this.getSprite=function(a){return b.hasOwnProperty(a)?b[a].oSprite:null};this._onSpritesLoaded=function(){d.call(e)};this._onSpriteLoaded=function(){f.call(e);++a==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in b)b[a].oSprite.oSpriteLibrary=this,b[a].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
b[a].oSprite.src=b[a].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=1360,CANVAS_HEIGHT=768,CANVAS_WIDTH_HALF=.5*CANVAS_WIDTH,CANVAS_HEIGHT_HALF=.5*CANVAS_HEIGHT,EDGEBOARD_X=175,EDGEBOARD_Y=90,DISABLE_SOUND_MOBILE=!1,FONT_GAME="palamecia_titlingregular",FPS=30,FPS_TIME=1/FPS,SNAKE_TYPES=5,FRAMES_NUM_HELP=[null,16,17,22],BUFFER_ANIM_MONITOR=[null,80,80,80],PLAYER=4,ENEMY_SNAKES=[0,1,2,3],AI_PLAYER=0,AI_FOODS=1,COLLISION_OFFSET_FOOD=[{x:-20,y:-10}],REG_FOOD_OFFSET=[{x:-12,y:0}],OPEN_MOUNTH_DISTANCE_RATE=2,MOUNTH_OFFSET_DETECT=-50,EATEN_OFFSET_DETECT=
-30,SNAKES_TOKEN_RADIUS_FOOD_DETECT=10,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_INIT=0,STATE_PLAY=1,STATE_FINISH=2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,MENU_SNAKES_VELOCITY=20,MENU_SNAKE_GOOD_ROTATION=9,MENU_SNAKE_BAD_ROTATION=5,MENU_SNAKE_GOOD_TIME_ROTATION=150,MENU_SNAKE_BAD_TIME_ROTATION=150,MENU_BAD_SNAKE_DELAY=1500,WIDTH_OF_HORIZONTAL_RECT=130,HEIGHT_OF_HORIZONTAL_RECT=50,WIDTH_OF_VERTICAL_RECT=60,HEIGHT_OF_VERTICAL_RECT=
320,MAX_AI_FOLLOW_PLAYER=1,EATEN_FOOD_SNAKE_INTERVAL=100,EDGES_PROPERTIES={x:0,y:0,h:2,w:3,xMax:0,yMax:0},SCROLL_LIMIT={xMin:-1712,yMin:-1330,xMax:0,yMax:0},PLAYER_CAMERA_OFFSET={x:680,y:384},SPAWN_FOODS_RANGE={xMin:EDGES_PROPERTIES.x+EDGEBOARD_X,yMin:EDGES_PROPERTIES.y+EDGEBOARD_Y,xMax:2048,yMax:1024},FIELD_SECTION_SUBDIVISION={w:5,h:2,tot:10},FOODS_OCCURRENCE=[100],MAX_FOODS_INSTANCE=100,FOOD_STATE=[4],AI_SNAKES=[{type:ENEMY_SNAKES[0],x:250,y:250,time_follow:2E3},{type:ENEMY_SNAKES[1],x:2762,y:250,
time_follow:3E3},{type:ENEMY_SNAKES[2],x:250,y:1798,time_follow:2500},{type:ENEMY_SNAKES[3],x:2762,y:1798,time_follow:3E3}],MS_TIME_SHOW_WIN_PANEL=1E3,WAIT_TIME_UPDATE_POS_QUEUE=30,START_QUEUE_SNAKES=[50,40,65,80,6],MS_DECREASE_TIME_EATEN_QUEUE=250,LERP_RATE=.03,DISTANCE_SINGLE_QUEUE=4,REG_Y_OFFSET_QUEUE=-36,INTERVAL_SPAWN_FOOD=500,MS_FADE_TIME=250,TIME_FOOD_SPAWN_ANIM=1E3,WAIT_TIME_SPAWN_QUEUE=250,TIME_SPAWN_QUEUE=1E3,TIME_EATEN_EFFECT=250,MAXT_TIME_WAIT_FOOD_SPAWN_ANIM=250,MAX_AI_QUEUE_LENGTH=100,
SINGLE_QUEUE_RADIUS=14,VERTICAL_RECT_STYLE_BLOCK,HORIZONTAL_RECT_STYLE_BLOCK,MAX_SECOND_FOR_ANIM_VERTICAL_RECT=10,DISPLAY_SHOCK_X=30,DISPLAY_SHOCK_Y=50,DISTANCE_AI_DETECT_FOOD=500,AI_ANGLE_DETECT_FOODS=Math.PI/180*30,COLLISION_DISTANCE_AI_PLAYER_FACTOR=100,AI_TIME_CHANGE_DIR={min:2E3,max:5E3},AI_TIME_IGNORE_PLAYER=1E3,AI_WAIT_TIME_FOR_CHANGE_DIR={min:250,max:1E3},CAN_PLAYER_EATEN_ENEMY=!1,SHOW_COLLISION_SHAPE=!1,SHOW_FIELD_OF_VIEW=!1,SHOW_FOODS_ID=!1,SHOW_SECTION_SHAPE=!1,ALLOW_SPEED_UP=!1,HERO_START_X=
1511,HERO_START_Y=1024,HERO_ACCELLERATION,MAX_HERO_SPEED,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;TEXT_GAMEOVER="GAME OVER";TEXT_SCORE="SCORE";TEXT_BEST_SCORE="BEST SCORE";TEXT_HELP1_PC="Use arrow keys to drive your starship. Cross the screen from side to side to avoid blocks";TEXT_HELP1_MOBILE="TOUCH THE LEFT OR RIGHT SIDE TO MOVE THE STARSHIP. Cross the screen from side to side to avoid blocks";TEXT_PAUSE="PAUSE";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_DEVELOPED="DEVELOPED BY";TEXT_MOVE="MOVE";
TEXT_EAT="EAT";TEXT_AVOID="AVOID";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var b,c,a,f,d,e,g;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("logo","./sprites/logo.png");s_oSpriteLibrary.loadSprites();g=new createjs.Container;s_oStage.addChild(g)};this.unload=function(){g.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(e).to({alpha:1},
500).call(function(){a.unload();s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){CBackground(g);new CLogo(CANVAS_WIDTH_HALF,CANVAS_HEIGHT_HALF-150,g);var h=s_oSpriteLibrary.getSprite("progress_bar");f=createBitmap(h);f.x=CANVAS_WIDTH/2-h.width/2;f.y=CANVAS_HEIGHT-150;g.addChild(f);b=h.width;c=h.height;d=new createjs.Shape;d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,
f.y,1,c);g.addChild(d);f.mask=d;a=new createjs.Text("","30px "+FONT_GAME,"#fff");a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT-150;a.shadow=new createjs.Shadow("#000",2,2,2);a.textBaseline="alphabetic";a.textAlign="center";g.addChild(a);e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e.alpha=0;g.addChild(e)};this.refreshLoader=function(e){a.text=e+"%";d.graphics.clear();e=Math.floor(e*b/100);d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,f.y,e,c)};this._init()}
function CMain(b){var c,a=0,f=0,d=STATE_LOADING,e,g,h,k;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_oStage.preventSelection=!1;s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader;c=!0};this.soundLoaded=function(){a++;g.refreshLoader(Math.floor(a/f*100));if(a===f){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/snake_eating.ogg","snake_eating"),createjs.Sound.registerSound("./sounds/snake_follow.ogg","snake_follow"),createjs.Sound.registerSound("./sounds/scream.ogg","scream")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.mp3","click"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/snake_eating.mp3","snake_eating"),createjs.Sound.registerSound("./sounds/snake_follow.mp3","snake_follow"),createjs.Sound.registerSound("./sounds/scream.mp3","scream")),f+=6)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,
this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_restart",
"./sprites/but_restart.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("food_0","./sprites/food_0.png");s_oSpriteLibrary.addSprite("but_pause","./sprites/but_pause.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_not","./sprites/but_not.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("logo_ctl",
"./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("arrow_key","./sprites/arrow_key.png");s_oSpriteLibrary.addSprite("edge_side_lr","./sprites/edge_side_lr.png");s_oSpriteLibrary.addSprite("edge_side_ud","./sprites/edge_side_ud.png");s_oSpriteLibrary.addSprite("logo","./sprites/logo.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");for(var a=1;4>a;a++)for(var d=0;d<FRAMES_NUM_HELP[a];d++)s_oSpriteLibrary.addSprite("help_"+a+"_"+d,"./sprites/help_"+a+"/help_"+a+"_"+
d+".jpg");for(d=0;d<SNAKE_TYPES;d++)s_oSpriteLibrary.addSprite("snake_head_"+d,"./sprites/snake_head_"+d+".png"),s_oSpriteLibrary.addSprite("snake_parts_"+d,"./sprites/snake_parts_"+d+".png");f+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){a++;g.refreshLoader(Math.floor(a/f*100));if(a===f){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};
this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.preloaderReady=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)this._initSounds(),s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this._loadImages();c=!0};this.gotoMenu=function(){h=new CMenu;d=STATE_MENU};this.gotoGame=function(){k=new CGame(e);d=STATE_GAME};this.gotoHelp=function(){new CHelp;d=STATE_HELP};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};
this.startUpdate=function(){s_iPrevTime=(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=function(a){if(!1!==c){var e=(new Date).getTime();s_iTimeElaps=e-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=e;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);d===STATE_GAME?k.update():d===STATE_MENU&&h.update();s_oStage.update(a)}};s_oMain=this;e=b;ENABLE_CHECK_ORIENTATION=b.check_orientation;
this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iSpeedBlock,s_oDrawLayer,s_oStage,s_oScrollStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_bFullscreen=!1;
function CTextButton(b,c,a,f,d,e,g){var h,k,l;this._init=function(a,d,e,b,f,g,c){h=[];k=[];var m=createBitmap(e),p=Math.ceil(c/20),n=new createjs.Text(b,"bold "+c+"px "+f,"#000000");n.textAlign="center";n.textBaseline="alphabetic";var v=n.getBounds();n.x=e.width/2+p;n.y=Math.floor(e.height/2)+v.height/3+p;b=new createjs.Text(b,"bold "+c+"px "+f,g);b.textAlign="center";b.textBaseline="alphabetic";v=b.getBounds();b.x=e.width/2;b.y=Math.floor(e.height/2)+v.height/3;l=new createjs.Container;l.x=a;l.y=
d;l.regX=e.width/2;l.regY=e.height/2;l.addChild(m,n,b);s_bMobile||(l.cursor="pointer");s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,d,e){h[a]=d;k[a]=e};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;playSound("click",1,0);h[ON_MOUSE_UP]&&
h[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setPosition=function(a,d){l.x=a;l.y=d};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(b,c,a,f,d,e,g);return this}
function CToggle(b,c,a,f,d){var e,g,h,k,l;this._init=function(a,d,b,f,c){l=void 0!==c?c:s_oStage;g=[];h=[];c=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}});e=f;k=createSprite(c,"state_"+e,b.width/2/2,b.height/2,b.width/2,b.height);k.x=a;k.y=d;k.stop();s_bMobile||(k.cursor="pointer");l.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",
this.buttonRelease);l.removeChild(k)};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,d,e){g[a]=d;h[a]=e};this.setCursorType=function(a){k.cursor=a};this.setActive=function(a){e=a;k.gotoAndStop("state_"+e)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("click",1,0);e=!e;k.gotoAndStop("state_"+e);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(h[ON_MOUSE_UP],e)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=
.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=function(a,d){k.x=a;k.y=d};this._init(b,c,a,f,d)}
function CGfxButton(b,c,a,f){var d,e,g,h,k,l,p,m,n,q=!1,r;this._init=function(a,b,f){d=[];e=[];h=[];g=createBitmap(f);g.x=a;g.y=b;l=k=1;g.regX=f.width/2;g.regY=f.height/2;s_bMobile||(g.cursor="pointer");r.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",m);g.off("pressup",n);r.removeChild(g)};this.setVisible=function(a){g.visible=a};this.setCursorType=function(a){g.cursor=a};this._initListener=function(){m=g.on("mousedown",this.buttonDown);n=g.on("pressup",this.buttonRelease)};
this.addEventListener=function(a,b,f){d[a]=b;e[a]=f};this.addEventListenerWithParams=function(a,b,f,c){d[a]=b;e[a]=f;h[a]=c};this.buttonRelease=function(){q||(g.scaleX=0<k?1:-1,g.scaleY=1,playSound("click",1,0),d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(e[ON_MOUSE_UP],h[ON_MOUSE_UP]))};this.buttonDown=function(){q||(g.scaleX=0<k?.9:-.9,g.scaleY=.9,d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],h[ON_MOUSE_DOWN]))};this.rotation=function(a){g.rotation=a};this.getButton=function(){return g};this.setPosition=
function(a,d){g.x=a;g.y=d};this.setX=function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.block=function(a){q=a;g.scaleX=k;g.scaleY=l};this.setScaleX=function(a){k=g.scaleX=a};this.getX=function(){return g.x};this.getY=function(){return g.y};this.pulseAnimation=function(){createjs.Tween.get(g).to({scaleX:.9*k,scaleY:.9*l},850,createjs.Ease.quadOut).to({scaleX:k,scaleY:l},650,createjs.Ease.quadIn).call(function(){p.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(g).to({rotation:5},
75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){p.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(g)};r=void 0!==f?f:s_oStage;this._init(b,c,a);p=this;return this}
function CCreditsPanel(){var b,c,a,f;this._init=function(){b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.alpha=0;b.on("mousedown",function(){});s_oStage.addChild(b);createjs.Tween.get(b).to({alpha:.7},500);c=new createjs.Container;s_oStage.addChild(c);var d=s_oSpriteLibrary.getSprite("msg_box"),e=createBitmap(d);e.regX=d.width/2;e.regY=d.height/2;c.addChild(e);c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;c.alpha=0;createjs.Tween.get(c).to({alpha:1},500);e=
new createjs.Text(TEXT_DEVELOPED," 40px "+FONT_GAME,"#000");e.y=-d.height/2+130;e.textAlign="center";e.textBaseline="middle";e.lineWidth=500;e.outline=4;c.addChild(e);e=new createjs.Text(TEXT_DEVELOPED," 40px "+FONT_GAME,"#ff6c00");e.y=-d.height/2+130;e.textAlign="center";e.textBaseline="middle";e.lineWidth=500;c.addChild(e);d=new createjs.Text("WWW.CODETHISLAB.COM"," 40px "+FONT_GAME,"#000");d.y=100;d.textAlign="center";d.textBaseline="middle";d.lineWidth=500;d.outline=4;c.addChild(d);d=new createjs.Text("WWW.CODETHISLAB.COM",
" 40px "+FONT_GAME,"#ff6c00");d.y=100;d.textAlign="center";d.textBaseline="middle";d.lineWidth=500;c.addChild(d);d=s_oSpriteLibrary.getSprite("logo_ctl");f=createBitmap(d);f.on("mousedown",this._onLogoButRelease);f.regX=d.width/2;f.regY=d.height/2;c.addChild(f);d=s_oSpriteLibrary.getSprite("but_exit");a=new CGfxButton(315,-155,d,c);a.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){a.block(!0);createjs.Tween.get(b).to({alpha:0},500);createjs.Tween.get(c).to({alpha:0},500).call(function(){s_oStage.removeChild(b);
s_oStage.removeChild(c);a.unload()});b.off("mousedown",function(){});f.off("mousedown",this._onLogoButRelease)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._onMoreGamesReleased=function(){window.open("http://codecanyon.net/collections/5409142-games")};this._init()}
function CMenu(){var b,c,a,f,d,e,g,h,k,l,p,m,n,q,r,v=null,A=null;this._init=function(){CBackground(s_oStage);q=new createjs.Container;q.alpha=0;s_oStage.addChild(q);var t=s_oSpriteLibrary.getSprite("but_play");d=CANVAS_WIDTH/2;e=CANVAS_HEIGHT-200;k=new CGfxButton(d,e,t,q);k.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);k.pulseAnimation();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)t=s_oSpriteLibrary.getSprite("audio_icon"),g=CANVAS_WIDTH-t.height/2-10,h=t.height/2+10,m=new CToggle(g,
h,t,s_bAudioActive,q),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);t=s_oSpriteLibrary.getSprite("but_info");a=t.height/2+10;f=t.height/2+10;l=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-240,t,q);l.addEventListener(ON_MOUSE_UP,this._onCreditsBut,this);n=new CAnimMenu(s_oStage);s_oStage.addChild(q);var t=window.document,B=t.documentElement;v=B.requestFullscreen||B.mozRequestFullScreen||B.webkitRequestFullScreen||B.msRequestFullscreen;A=t.exitFullscreen||t.mozCancelFullScreen||t.webkitExitFullscreen||
t.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(v=!1);v&&!1===inIframe()&&(t=s_oSpriteLibrary.getSprite("but_fullscreen"),b=a+t.width/2+10,c=t.height/2+10,r=new CToggle(b,c,t,s_bFullscreen,q),r.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(p);createjs.Tween.get(p).to({alpha:0},MS_FADE_TIME,createjs.Ease.cubicOut).call(function(){p.visible=!1});this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.animContainerGUI=function(){createjs.Tween.get(q).to({alpha:1},500,createjs.Ease.cubicOut)};this.refreshButtonPos=function(d,e){l.setPosition(a+d,e+f);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(g-d,e+h);v&&!1===inIframe()&&r.setPosition(b+d,c+e)};this.unload=function(){k.unload();k=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;v&&!1===inIframe()&&r.unload();s_oStage.removeAllChildren();s_oMenu=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onCreditsBut=function(){new CCreditsPanel};this._onButPlayRelease=function(){p.visible=!0;createjs.Tween.get(p).to({alpha:1},MS_FADE_TIME,createjs.Ease.cubicOut).call(function(){s_oMenu.unload();s_oMain.gotoGame();$(s_oMain).trigger("start_session")})};this._onFullscreenRelease=function(){s_bFullscreen?(A.call(window.document),s_bFullscreen=!1):(v.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};this.update=function(){n.update()};s_oMenu=
this;this._init()}var s_oMenu=null;
function CGame(b){var c,a,f,d;function e(a){if(!1!==v)switch(a.keyCode){case 38:s_oGame.onKeyUpUp();break;case 37:case 39:A=!1}}function g(a){if(!1===v||A)return a.preventDefault(),!1;a||(a=window.event);switch(a.keyCode){case 37:s_oGame.onLeft();break;case 39:s_oGame.onRight();break;case 38:s_oGame.onKeyDownUp()}a.preventDefault();return!1}var h,k,l,p,m,n,q,r,v=!1,A=!1,t,B=STATE_INIT,y,E,C,x,z,u=LERP_RATE,D;this._init=function(){r=new createjs.Container;s_oScrollStage=new createjs.Container;s_oStage.addChild(s_oScrollStage);
new CBackground(s_oScrollStage);t=0;x=[];C=[];setVolume(s_oSoundTrack,.4);z=0;m=new CEdges(r);q=new CManageSections;p=new CManageFoods(s_oScrollStage);n=new CControlAiSnakes;y=HERO_SPEED;this.createPlayerSnake();t=E=START_QUEUE_SNAKES[PLAYER];this.resetCameraOnPlayer();c=SCROLL_LIMIT.xMax;a=SCROLL_LIMIT.xMin;f=SCROLL_LIMIT.yMax;d=SCROLL_LIMIT.yMin;this.addEnemySnakes();s_oScrollStage.addChild(r);!1===s_bMobile?(document.onkeydown=g,document.onkeyup=e):this.createControl();k=new CInterface;k.refreshScore(t);
k.refreshBestScore(E,!1);l=new createjs.Shape;l.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(l);createjs.Tween.get(l).to({alpha:0},MS_FADE_TIME,createjs.Ease.cubicOut).call(function(){l.visible=!1})};this.resetCameraOnPlayer=function(){s_oScrollStage.x+=h.getDir().getX()*HERO_SPEED+(PLAYER_CAMERA_OFFSET.x-h.getLocalPos().x);s_oScrollStage.y+=h.getDir().getY()*HERO_SPEED+(PLAYER_CAMERA_OFFSET.y-h.getLocalPos().y)};this.unload=function(){v=!1;s_bMobile&&(D.off("mousedown",
this.onPressStart),D.off("pressup",this.onPressRelease));s_oStage.removeAllChildren();createjs.Tween.removeAllTweens();s_oGame=null;k.unload()};this.createPlayerSnake=function(){var a=PLAYER,d=s_oSpriteLibrary.getSprite("snake_head_"+a);h=new CSnake(HERO_START_X,HERO_START_Y,d,a,START_QUEUE_SNAKES[a],null,s_oScrollStage);x.push(h)};this.addEnemySnakes=function(){for(var a=0,d=0;d<AI_SNAKES.length;d++){var e=AI_SNAKES[d].type,b=s_oSpriteLibrary.getSprite("snake_head_"+e),e=new CSnake(AI_SNAKES[d].x,
AI_SNAKES[d].y,b,e,START_QUEUE_SNAKES[e],a,s_oScrollStage);C.push(e);x.push(e);n.addSnakeToAI(e);a++}};this.createControl=function(){D=new createjs.Shape;D.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(D);D.on("mousedown",this.onPressStart);D.on("pressup",this.onPressRelease)};this.onPressStart=function(a){if(a.stageX<.5*CANVAS_WIDTH)s_oGame.onLeft();else if(a.stageX>.5*CANVAS_WIDTH)s_oGame.onRight()};this.onPressRelease=function(){s_oGame.onKeyReleased()};
this.onRestart=function(){z=0;this.unloadASnake(h);for(var a=0;a<C.length;a++)this.unloadASnake(C[a]),n.removeSnakeByID(a);x=[];C=[];n.reset();A=!1;this.createPlayerSnake();this.scrollStage(h,y);u=.1;createjs.Tween.get(this).wait(750).call(function(){u=LERP_RATE});this.addEnemySnakes();t=h.getLengthQueue();k.refreshScore(t);playExistingSound(s_oSoundTrack);s_oScrollStage.setChildIndex(r,s_oScrollStage.numChildren-1);p.restoresAllEatenFood();B=STATE_PLAY;s_oGame.unpause(!0)};this.unloadASnake=function(a){a.unloadQueue();
a.unload()};this.onKeyDownUp=function(){ALLOW_SPEED_UP&&(y=HERO_SPEED_UP)};this.onKeyUpUp=function(){y=HERO_SPEED};this.getPlayerSnake=function(){return h};this.getSnakesArray=function(){return x};this.onLeft=function(){h.getEaten()||(A=!0,playSound("spaceship_whoosh",.7,0),z=-HERO_ROT_SPEED)};this.onRight=function(){h.getEaten()||(A=!0,playSound("spaceship_whoosh",1,0),z=HERO_ROT_SPEED)};this.onKeyReleased=function(){A=!1};this.onExit=function(){l.visible=!0;createjs.Tween.get(l,{ignoreGlobalPause:!0}).to({alpha:1},
MS_FADE_TIME,createjs.Ease.cubicOut).call(function(){s_oGame.unpause(!0);s_oGame.unload();$(s_oMain).trigger("end_session");playExistingSound(s_oSoundTrack);setVolume(s_oSoundTrack,1);s_oMain.gotoMenu()})};this._onExitHelp=function(){k.onExitFromHelp();v=!0;B=STATE_PLAY;$(s_oMain).trigger("start_level",1)};this.updateScrollLimit=function(e,b){c=SCROLL_LIMIT.xMax+e;a=SCROLL_LIMIT.xMin-e;f=SCROLL_LIMIT.yMax+b;d=SCROLL_LIMIT.yMin-b};this.scrollStage=function(e){s_oScrollStage.x+=e.getDir().getX()*HERO_SPEED+
(PLAYER_CAMERA_OFFSET.x-e.getLocalPos().x)*u;s_oScrollStage.y+=e.getDir().getY()*HERO_SPEED+(PLAYER_CAMERA_OFFSET.y-e.getLocalPos().y)*u;s_oScrollStage.x<a?s_oScrollStage.x=a:s_oScrollStage.x>c&&(s_oScrollStage.x=c);s_oScrollStage.y<d?s_oScrollStage.y=d:s_oScrollStage.y>f&&(s_oScrollStage.y=f)};this.cutQueueAt=function(a,d){a.cutQueueAtPoint(d)};this.unpause=function(a){v=a;createjs.Ticker.paused=!a};this.snakeCloseMounthAnim=function(a){a.changeState("close");a.setIgnoreAnim(!0);a.onAnimationEnd()};
this.manageCollision=function(){this.snakeSection();this.snakeFoodsCollision();this.snakeEdgesCollision();this.snakesCollisions()};this.snakesCollisions=function(){for(var a=0;a<C.length;a++)this.snakesHeadHeadCollision(h,C[a]),this.snakesHeadQueueCollision(h,C[a])};this.snakesHeadHeadCollision=function(a,d){a.getEaten()||(this.snakeOpenMounth(a,d),this.circleToCircleCollision(a.getPos(),d.getPos(),a.getDim().h,d.getDim().h)&&(A=!1,a.die(),createjs.Tween.get(this).wait(MS_TIME_SHOW_WIN_PANEL).call(this.onDiePlayerSnake)))};
this.snakesHeadQueueCollision=function(a,d){if(d.getTarget().target===AI_PLAYER&&!a.getEaten())for(var e=a.getQueue(),b=e.length-2;0<b;b--)if(this.snakeOpenMounth(d,e[b]),this.circleToCircleCollision(e[b].getPos(),d.getPos(),e[b].getDim().h,d.getDim().w)){this.cutQueueAt(a,b);"damage_open"!==a.getCurrentAnimation()&&"remain_damage"!==a.getCurrentAnimation()&&a.changeState("damage_open");d.getSubAI().setFollowTime(d.getSubAI().getFollowTime()-MS_DECREASE_TIME_EATEN_QUEUE);a.screamingSound();this.snakeCloseMounthAnim(d);
t=a.getLengthQueue();k.refreshScore(t);break}};this.snakeSection=function(){for(var a=q.getSections(),d=0;d<x.length;d++)for(var e=0;e<a.length;e++)if(a[e].getRect().intersects(x[d].getRectangle())){x[d].setSectionID(a[e].getID());break}};this.snakeEdgesCollision=function(){for(var a=m.getRectangles(),d=0;d<x.length;d++)for(var e=0;e<a.length;e++)a[e].rect.intersects(x[d].getRectangle())&&x[d].bounce(a[e].normal)};this.snakeEatenFood=function(a,d){a.getType()===PLAYER&&(this.updateScoreFood(),a.eatingSound());
a.setTarget({result:!1});d.setEaten(!0);d.eatenAnim(a.getPos());a.eatenEffect();for(var e=0;e<C.length&&!(a.getType()===ENEMY_SNAKES[e]&&a.getLengthQueue()>=MAX_AI_QUEUE_LENGTH);e++);};this.snakeFoodsCollision=function(){for(var a=0;a<x.length;a++)for(var d=q.getSectionByID(x[a].getSectionID()).getFoodsSection(),e=0;e<d.length;e++)if(this.snakeOpenMounth(x[a],d[e]),!d[e].getEaten()){var b=x[a].getPos();b.y+=EATEN_OFFSET_DETECT*x[a].getDir().getY();b.x+=EATEN_OFFSET_DETECT*x[a].getDir().getX();this.circleToCircleCollision(b,
d[e].getPos(),SNAKES_TOKEN_RADIUS_FOOD_DETECT,d[e].getDim().w)&&this.snakeEatenFood(x[a],d[e])}};this.snakeOpenMounth=function(a,d){var e=!1;if(!d.getEaten()){var b=a.getPos();b.y+=MOUNTH_OFFSET_DETECT*a.getDir().getY();b.x+=MOUNTH_OFFSET_DETECT*a.getDir().getX();this.circleToCircleCollision(b,d.getPos(),a.getOpenMounthDim().h,d.getDim().w)&&(e=!0)}this.actionOpenMounth(a,e)};this.actionOpenMounth=function(a,d){d?"open"!==a.getCurrentAnimation()&&"remain_open"!==a.getCurrentAnimation()&&"damage_close"!==
a.getCurrentAnimation()&&("remain_damage"===a.getCurrentAnimation()?a.changeState("damage_close"):a.changeState("open")):"open"!==a.getCurrentAnimation()&&"remain_open"!==a.getCurrentAnimation()||a.changeState("close")};this.circleToCircleCollision=function(a,d,e,b){a=distance(a,d);return e+b>a?!0:!1};this.onDiePlayerSnake=function(){stopSound(s_oSoundTrack);k.createEndPanel(E)};this.onDieEnemySnake=function(a){C.splice(a,1);n.removeSnakeByID(a)};this.updateScoreFood=function(){t++;k.refreshScore(t);
t>E&&(E=t,k.refreshBestScore(E,!0))};this._updatePlay=function(){v&&(A&&h.rotation(z),h.update(y),this.scrollStage(h,y),p.update(),this.manageCollision(),n.update())};this.update=function(){switch(B){case STATE_INIT:null!==s_oHelp&&s_oHelp.update();break;case STATE_PLAY:this._updatePlay()}};s_oGame=this;HERO_ROT_SPEED=b.hero_rotation_speed;HERO_SPEED=b.hero_speed;HERO_SPEED_UP=b.hero_speed_up;FOOD_SCORE=b.food_score;SNAKES_AI_SPEED=b.snakes_AI_speed;ENABLE_FULLSCREEN=b.fullscreen;this._init()}var s_oGame;
function CInterface(){var b,c,a,f,d,e,g,h,k,l,p,m,n,q,r,v,A,t,B,y,E,C,x,z,u,D,G,F=null,H=null;this._init=function(){n=CANVAS_WIDTH/2-50;q=55;B=new createjs.Text(TEXT_SCORE+": 0","32px "+FONT_GAME,"#ffffff");B.x=n;B.y=q;B.textAlign="left";B.regY=.5*B.getBounds().height;s_oStage.addChild(B);p=CANVAS_WIDTH/2-550;m=55;y=new createjs.Text(TEXT_BEST_SCORE+": 0","32px "+FONT_GAME,"#ffffff");y.x=p;y.y=m;y.textAlign="left";y.regX=.5*y.getBounds().width;y.regY=.5*y.getBounds().height;s_oStage.addChild(y);var w=
s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-w.height/2-20;f=w.height/2+20;A=new CGfxButton(a,f,w,s_oStage);A.addEventListener(ON_MOUSE_UP,this._onExit,this);w=s_oSpriteLibrary.getSprite("but_pause");b=a-w.height-20;c=f;t=new CGfxButton(b,c,w,s_oStage);t.addEventListener(ON_MOUSE_UP,this._onPause,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(w=s_oSpriteLibrary.getSprite("audio_icon"),r=b-w.height-20,v=f,C=new CToggle(r,v,w,s_bAudioActive,s_oStage),C.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this),d=r-w.width/2-20,e=c):(d=b-w.height-20,e=f);var w=window.document,u=w.documentElement;F=u.requestFullscreen||u.mozRequestFullScreen||u.webkitRequestFullScreen||u.msRequestFullscreen;H=w.exitFullscreen||w.mozCancelFullScreen||w.webkitExitFullscreen||w.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(F=!1);F&&!1===inIframe()&&(w=s_oSpriteLibrary.getSprite("but_fullscreen"),G=new CToggle(d,e,w,s_bFullscreen,s_oStage),G.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));s_bMobile&&(k=.5*CANVAS_WIDTH-
430-EDGEBOARD_X,l=.5*CANVAS_HEIGHT+220+EDGEBOARD_Y,w=s_oSpriteLibrary.getSprite("arrow"),x=createBitmap(w),x.regX=.5*w.width,x.regY=.5*w.height,x.x=k,x.y=l,x.scaleX=-1,s_oStage.addChild(x),g=.5*CANVAS_WIDTH+430+EDGEBOARD_X,h=.5*CANVAS_HEIGHT+220+EDGEBOARD_Y,z=createBitmap(w),z.regX=.5*w.width,z.regY=.5*w.height,z.x=g,z.y=h,s_oStage.addChild(z));E=new CHelpPanel(0,0,s_oSpriteLibrary.getSprite("bg_help"));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(w,n){A.setPosition(a-
w,n+f);t.setPosition(b-w,n+c);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||C.setPosition(r-w,n+v);F&&!1===inIframe()&&G.setPosition(d-w,e+n);y.x=p+w;y.y=m+n;s_bMobile&&(x.x=k+w,x.y=l-n,z.x=g-w,z.y=h-n);B.y=q+n;s_oGame.updateScrollLimit(w,n)};this.unload=function(){A.unload();A=null;E.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)C.unload(),C=null;F&&!1===inIframe()&&G.unload();s_oInterface=null};this.refreshScore=function(a){B.text=TEXT_SCORE+": "+a};this.refreshBestScore=function(a,d){y.text=
TEXT_BEST_SCORE+": "+a;d&&(y.color="#ffff00",createjs.Tween.get(y,{override:!0}).to({scaleX:1.1,scaleY:1.1},500,createjs.Ease.cubicOut).to({scaleX:1,scaleY:1},500,createjs.Ease.cubicIn).set({color:"#fff"}))};this._onPause=function(){s_oGame.unpause(!1);this.createPauseInterface()};this.createPauseInterface=function(){u=new CPause};this.createEndPanel=function(a){D=new CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));D.show(a)};this.unloadPause=function(){u.unload();u=null};this.onExitFromHelp=function(){E.unload()};
this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){(new CAreYouSurePanel(s_oStage)).show()};this._onFullscreenRelease=function(){s_bFullscreen?(H.call(window.document),s_bFullscreen=!1):(F.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(b,c,a){var f,d,e,g,h,k;this._init=function(a,b,c){d=new createjs.Container;d.x=a;d.y=b;e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e.alpha=.5;d.addChild(e);f=createBitmap(c);f.x=CANVAS_WIDTH_HALF;f.y=CANVAS_HEIGHT_HALF;f.regX=.5*c.width;f.regY=.5*c.height;d.addChild(f);a=new createjs.Text(TEXT_MOVE,"60px "+FONT_GAME,"#000000");a.textAlign="center";a.lineWidth=300;a.lineHeight=44;a.textBaseline="middle";a.x=.5*CANVAS_WIDTH-150;a.y=
.5*CANVAS_HEIGHT-140;a.outline=4;d.addChild(a);b=new createjs.Text(TEXT_MOVE,"60px "+FONT_GAME,"#ff6c00");b.textAlign="center";b.textBaseline="middle";b.lineWidth=300;b.lineHeight=a.lineHeight;b.x=a.x;b.y=a.y;d.addChild(b);g=new CAnimHelp(1,CANVAS_WIDTH_HALF+220,a.y+50,d);b="arrow_key";a=.5;s_bMobile&&(b="arrow",a=.4);b=s_oSpriteLibrary.getSprite(b);c=createBitmap(b);c.x=CANVAS_WIDTH_HALF+50;c.y=CANVAS_HEIGHT_HALF-140;c.regX=.5*b.width;c.regY=.5*b.height;c.scaleX=-a;c.scaleY=a;d.addChild(c);var l=
createBitmap(b);l.x=CANVAS_WIDTH_HALF+190;l.y=c.y;l.regX=.5*b.width;l.regY=.5*b.height;l.scaleX=a;l.scaleY=a;d.addChild(l);a=new createjs.Text(TEXT_EAT,"60px "+FONT_GAME,"#000000");a.textAlign="center";a.lineWidth=300;a.lineHeight=44;a.textBaseline="middle";a.x=.5*CANVAS_WIDTH-150;a.y=.5*CANVAS_HEIGHT-20;a.outline=4;d.addChild(a);b=new createjs.Text(TEXT_EAT,"60px "+FONT_GAME,"#ff6c00");b.textAlign="center";b.textBaseline="middle";b.lineWidth=300;b.lineHeight=a.lineHeight;b.x=a.x;b.y=a.y;d.addChild(b);
h=new CAnimHelp(2,CANVAS_WIDTH_HALF+220,CANVAS_HEIGHT_HALF+37,d);a=new createjs.Text(TEXT_AVOID,"60px "+FONT_GAME,"#000000");a.textAlign="center";a.lineWidth=300;a.lineHeight=44;a.textBaseline="middle";a.x=.5*CANVAS_WIDTH-150;a.y=.5*CANVAS_HEIGHT+115;a.outline=4;d.addChild(a);b=new createjs.Text(TEXT_AVOID,"60px "+FONT_GAME,"#ff6c00");b.textAlign="center";b.textBaseline="middle";b.lineWidth=300;b.lineHeight=a.lineHeight;b.x=a.x;b.y=a.y;d.addChild(b);k=new CAnimHelp(3,CANVAS_WIDTH_HALF+220,a.y+50,
d);s_oStage.addChild(d);var m=this;d.on("pressup",function(){m._onExitHelp()})};this.unload=function(){s_oStage.removeChild(d);var a=this;d.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){this.unload();s_oGame._onExitHelp()};this.update=function(){g.animMonitor();h.animMonitor();k.animMonitor()};this._init(b,c,a);s_oHelp=this;return this}var s_oHelp;
function CEndPanel(b){var c,a,f,d,e,g,h,k,l;this._init=function(b){l=new createjs.Shape;l.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.alpha=.5;l.on("click",function(){});c=createBitmap(b);c.x=CANVAS_WIDTH_HALF;c.y=CANVAS_HEIGHT_HALF;c.regX=.5*b.width;c.regY=.5*b.height;e=new createjs.Text("","90px "+FONT_GAME,"#000");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-160;e.textAlign="center";e.outline=4;d=new createjs.Text("","90px "+FONT_GAME,"#ff6c00");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/
2-160;d.textAlign="center";a=new createjs.Text("","60px "+FONT_GAME,"#000");a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2-50;a.textAlign="center";a.outline=4;f=new createjs.Text("","60px "+FONT_GAME,"#ff6c00");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-50;f.textAlign="center";g=new createjs.Container;g.alpha=0;g.visible=!1;g.addChild(l,c,a,f,e,d);s_oStage.addChild(g)};this.show=function(b){playSound("game_over",1,0);e.text=TEXT_GAMEOVER;d.text=TEXT_GAMEOVER;a.text=TEXT_SCORE+": "+b;f.text=TEXT_SCORE+": "+b;
g.visible=!0;var c=s_oSpriteLibrary.getSprite("but_restart");h=new CGfxButton(.5*CANVAS_WIDTH+260,.5*CANVAS_HEIGHT+100,c,g);h.addEventListener(ON_MOUSE_DOWN,this._onRestart,this);c=s_oSpriteLibrary.getSprite("but_home");k=new CGfxButton(.5*CANVAS_WIDTH-260,.5*CANVAS_HEIGHT+100,c,g);k.addEventListener(ON_MOUSE_DOWN,this._onExit,this);createjs.Tween.get(g,{ignoreGlobalPause:!0}).to({alpha:1},1E3,createjs.Ease.cubicOut);$(s_oMain).trigger("save_score",b);$(s_oMain).trigger("share_event",b)};this._onExit=
function(){s_oStage.removeChild(g);this.unload();$(s_oMain).trigger("show_interlevel_ad");s_oGame.onExit()};this.unload=function(){k.unload();k=null;h.unload();h=null;l.removeAllEventListeners()};this._onRestart=function(){createjs.Tween.get(g,{ignoreGlobalPause:!0}).to({alpha:0},300).call(function(){!0===s_bMobile&&s_oGame.createControl(!1);s_oStage.removeChild(g)});s_oGame.onRestart();$(s_oMain).trigger("show_interlevel_ad")};this._init(b);return this}
function CSnake(b,c,a,f,d,e,g){var h,k,l,p,m,n,q,r,v,A,t,B=null,y,E,C,x,z,u,D=!1,G=!1,F=!1,H=!1;this._init=function(a,d,b,e,c){v=new createjs.Container;g.addChild(v);u=[];z=new CVector2(0,1);C=b;var f,h;4===b?(b=c.width/9,f=c.height/2,h={normal:0,open:[1,7,"remain_open"],remain_open:7,close:[8,12,"normal"],damage_open:[13,16,"remain_damage"],remain_damage:[16,16,"damage_close",.05],damage_close:{frames:[16,15,14,13],next:"normal"},die:17}):(b=c.width/7,f=c.height/2,h={normal:0,open:[1,7,"remain_open"],
remain_open:7,close:[8,12,"normal"]});c=new createjs.SpriteSheet({images:[c],frames:{width:b,height:f,regX:b/2,regY:f/2},animations:h});m=createSprite(c,"normal",b/2,f/2,b,f);m.gotoAndPlay("close");m.x=a;m.y=d;v.addChild(m);A={result:!1,target:null};y=.4*b;E=y+y;n={w:.5*b,h:.5*b};t={w:n.w*OPEN_MOUNTH_DISTANCE_RATE,h:n.h*OPEN_MOUNTH_DISTANCE_RATE};for(a=0;a<e;a++)this.createAQueque(m.x,m.y+DISTANCE_SINGLE_QUEUE*(u.length+1),!1);this.createCollision()};this.getCurrentAnimation=function(){return m.currentAnimation};
this.setSubAI=function(a){B=a};this.getSubAI=function(){return B};this.createCollision=function(){h=m.x-y;k=m.y-y;p=l=E;r=new createjs.Rectangle(h,k,l,p);SHOW_COLLISION_SHAPE&&(q=new createjs.Shape,q.graphics.beginFill("#00ff00").drawRect(r.x,r.y,r.width,r.height),q.alpha=.5,g.addChild(q))};this.bounce=function(a){m.x+=z.getX()*HERO_SPEED;m.y+=z.getY()*HERO_SPEED;z.setV(reflectVectorV2(z,a));m.rotation=Math.atan2(z.getY(),z.getX())*(180/Math.PI)-90};this.changeState=function(a){G||m.gotoAndPlay(a)};
this.onAnimationEnd=function(){var a=this;m.on("animationend",function(){a.setIgnoreAnim(!1)})};this.setIgnoreAnim=function(a){G=a};this.stopState=function(a){m.gotoAndStop(a)};this.createAQueque=function(a,d){var b=new CSingleQueue(a,d,m.rotation,f,v);if(0<u.length){var e=u.length-1;u[e].changeState("body");u[e].setRegY(u[e].getRegY()-REG_Y_OFFSET_QUEUE);v.swapChildren(m,b.getObj());v.setChildIndex(b.getObj(),1)}b.stopTimeline(0);u.push(b)};this.eatingSound=function(){if(!F){var a=playSound("snake_eating",
1,0);if(null!==a)a.on("complete",function(){F=!1});F=!0}};this.screamingSound=function(){if(!H){var a=playSound("scream",1,0);if(null!==a)a.on("complete",function(){H=!1});H=!0}};this.eatenEffect=function(){for(var a=EATEN_FOOD_SNAKE_INTERVAL,b=4;b<u.length;b++)u[b].eatenEffect(a),a+=EATEN_FOOD_SNAKE_INTERVAL;createjs.Tween.get(this).wait(a).call(function(){this.createAQueque(-5E3,-5E3)})};this.queuePosition=function(){u[0].setPosition(m.x,m.y);u[0].setRotation(m.rotation);for(var a=u.length-1;0<
a;a--)u[a].setPosition(u[a-1].getLastPos().x,u[a-1].getLastPos().y),u[a].setRotation(u[a-1].getRotation())};this.cutQueueAtPoint=function(a){for(var b=0,d=a;d<u.length-1;d++)u[d].unload(),b++;u.splice(a,b)};this.die=function(){D||(D=!0,z.set(0,0),this.stopState("die"))};this.getOpenMounthDim=function(){return t};this.unload=function(){createjs.Tween.removeTweens(m);createjs.Tween.removeTweens(this);g.removeChild(v)};this.unloadQueue=function(){for(var a=0;a<u.length;a++)u[a].unload();u=null};this.getLengthQueue=
function(){return u.length};this.getQueue=function(){return u};this.getDim=function(){return n};this.getEaten=function(){return D};this.getSectionID=function(){return x};this.setSectionID=function(a){x=a};this.setVisible=function(a){m.visible=a};this.getPos=function(){return{x:m.x,y:m.y}};this.getLocalPos=function(){return m.localToGlobal(0,0)};this.getX=function(){return m.x};this.getY=function(){return m.y};this.getSprite=function(){return m};this.setPosition=function(a,b){m.x=a;m.y=b};this.rotation=
function(a){m.rotation+=a;z.set(Math.sin(Math.PI/180*-m.rotation),Math.cos(Math.PI/180*-m.rotation))};this.rotate=function(a){m.rotation=a;z.set(Math.sin(Math.PI/180*-m.rotation),Math.cos(Math.PI/180*-m.rotation))};this.getType=function(){return C};this.getDir=function(){return z};this.getID=function(){return e};this.move=function(a){m.x-=z.getX()*a;m.y-=z.getY()*a;this.moveRect()};this.getTarget=function(){return A};this.setTarget=function(a){A.result=a.result;A.target=a.target};this.moveRect=function(){h=
m.x-y;k=m.y-y;p=l=E;r.setValues(h,k,l,p);SHOW_COLLISION_SHAPE&&(q&&(g.removeChild(q),q=null),q=new createjs.Shape,q.graphics.beginFill("#00ff00").drawRect(r.x,r.y,r.width,r.height),q.alpha=.5,g.addChild(q))};this.getRectangle=function(){return r};this.update=function(a){D||(this.queuePosition(),this.move(a))};this._init(b,c,f,d,a)}
function CSingleQueue(b,c,a,f,d){var e,g,h,k;this._init=function(a,b,c,f){c=s_oSpriteLibrary.getSprite("snake_parts_"+c);var l=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{body:0,queue:1}});e=createSprite(l,"queue",c.width/2/2,c.height/2,c.width/2,c.height);d.addChild(e);e.x=a;e.y=b;g={x:a,y:b};h={w:c.width/2,h:c.height};e.regY+=REG_Y_OFFSET_QUEUE;e.rotation=f;e.tickEnabled=!1;d.addChild(e);k=new createjs.Timeline;k.addTween(createjs.Tween.get(e).to({scaleX:1.2},
TIME_EATEN_EFFECT,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(e).to({scaleX:1},TIME_EATEN_EFFECT,createjs.Ease.cubicIn)}))};this.changeState=function(a){e.gotoAndStop(a)};this.getPos=function(){return{x:e.x,y:e.y}};this.setRegY=function(a){e.regY=a};this.getRegY=function(){return e.regY};this.unload=function(){d.removeChild(e);e=null};this.getLastPos=function(){return g};this.setLastPos=function(a,b){g.x=a;g.y=b};this.setRotation=function(a){e.rotation=a};this.getRotation=function(){return e.rotation};
this.getObj=function(){return e};this.getDim=function(){return h};this.getEaten=function(){return!1};this.unload=function(){createjs.Tween.removeTweens(e);createjs.Tween.get(e).to({scaleX:0,scaleY:0},500,createjs.Ease.cubicOut).call(function(){d.removeChild(e)})};this.spawnAnim=function(a){e.scaleX=e.scaleY=0;createjs.Tween.get(e).wait(a).to({scaleX:1,scaleY:1},TIME_SPAWN_QUEUE,createjs.Ease.cubicOut)};this.eatenEffect=function(a){createjs.Tween.get(this).wait(a).call(function(){k.gotoAndPlay(0)})};
this.setScale=function(a){e.scaleX=e.scaleY=a};this.stopTimeline=function(a){k.gotoAndStop(a)};this.setPosition=function(a,b){e.x=a;e.y=b;g.x=a;g.y=b};this._init(b,c,f,a);return this}
function CVector2(b,c){var a,f;this._init=function(b,e){a=b;f=e};this.add=function(b,e){a+=b;f+=e};this.addV=function(b){a+=b.getX();f+=b.getY()};this.scalarDivision=function(b){a/=b;f/=b};this.subtract=function(b){a-=b.getX();f-=b.getY()};this.scalarProduct=function(b){a*=b;f*=b};this.invert=function(){a*=-1;f*=-1};this.dotProduct=function(b){return a*b.getX()+f*b.getY()};this.set=function(b,e){a=b;f=e};this.setV=function(b){a=b.getX();f=b.getY()};this.length=function(){return Math.sqrt(a*a+f*f)};
this.length2=function(){return a*a+f*f};this.normalize=function(){var b=this.length();0<b&&(a/=b,f/=b)};this.angleBetweenVectors=function(a){a=Math.acos(this.dotProduct(a)/(this.length()*a.length()));return!0===isNaN(a)?0:a};this.getNormalize=function(b){this.length();b.set(a,f);b.normalize()};this.rot90CCW=function(){var b=a;a=-f;f=b};this.rot90CW=function(){var b=a;a=f;f=-b};this.getRotCCW=function(b){b.set(a,f);b.rot90CCW()};this.getRotCW=function(b){b.set(a,f);b.rot90CW()};this.ceil=function(){a=
Math.ceil(a);f=Math.ceil(f)};this.round=function(){a=Math.round(a);f=Math.round(f)};this.toString=function(){return"Vector2: "+a+", "+f};this.print=function(){trace("Vector2: "+a+", "+f+"")};this.getX=function(){return a};this.getY=function(){return f};this.rotate=function(b){var e=a,d=f;a=e*Math.cos(b)-d*Math.sin(b);f=e*Math.sin(b)+d*Math.cos(b)};this._init(b,c)}
function CEdges(b){var c,a,f;this._init=function(){f=new createjs.Container;b.addChild(f);c=[];a=[];var d=s_oSpriteLibrary.getSprite("edge_side_lr"),e=s_oSpriteLibrary.getSprite("edge_side_ud"),g=EDGES_PROPERTIES.x,h=EDGES_PROPERTIES.y,k=g+d.height*EDGES_PROPERTIES.w-d.width;SPAWN_FOODS_RANGE.xMax=k-.5*EDGEBOARD_X;EDGES_PROPERTIES.xMax=k;for(var l=0;l<EDGES_PROPERTIES.h;l++)c.push(new CEdge(g,h,{lr:!0,val:1},d,f)),c.push(new CEdge(k,h,{lr:!0,val:-1},d,f)),h+=d.height;SPAWN_FOODS_RANGE.yMax=h-.5*EDGEBOARD_Y;
EDGES_PROPERTIES.yMax=h;for(l=0;l<EDGES_PROPERTIES.w;l++)c.push(new CEdge(g,EDGES_PROPERTIES.y,{lr:!1,val:-1},e,f)),c.push(new CEdge(g,h-23,{lr:!1,val:1},e,f)),g+=e.width;this.createEdgesCollision(k,h,d)};this.createEdgesCollision=function(b,e,c){b=[{x:EDGES_PROPERTIES.x,y:EDGES_PROPERTIES.y,w:b+.5*c.height,h:c.width-17,normal:new CVector2(0,1)},{x:EDGES_PROPERTIES.x,y:EDGES_PROPERTIES.y+c.width,w:c.width-20,h:e+.5*c.height,normal:new CVector2(1,0)},{x:EDGES_PROPERTIES.x,y:e,w:b+.5*c.height,h:c.width,
normal:new CVector2(0,-1)},{x:b+22,y:EDGES_PROPERTIES.y+c.width,w:c.width,h:e+.5*c.height,normal:new CVector2(-1,0)}];for(e=0;e<b.length;e++)a.push({rect:new createjs.Rectangle(b[e].x,b[e].y,b[e].w,b[e].h),normal:b[e].normal}),SHOW_COLLISION_SHAPE&&(c=new createjs.Shape,c.graphics.beginFill("#00ff00").drawRect(b[e].x,b[e].y,b[e].w,b[e].h),c.alpha=.5,f.addChild(c))};this.getRectangles=function(){return a};this.unload=function(){b.removeChild(f);f=null};this.getObj=function(){return f};this.setPosition=
function(a,b){f.x=a;f.y=b};this._init();return this}function CEdge(b,c,a,f,d){var e;this._init=function(a,b,c,f){e=createBitmap(c);e.x=a;e.y=b;!0===f.lr?(e.scaleX=f.val,0>e.scaleX&&(e.regX=c.width)):(e.scaleY=f.val,0>e.scaleY&&(e.regY=c.height));e.tickEnabled=!1;d.addChild(e)};this.getPos=function(){return{x:e.x,y:e.y}};this.unload=function(){d.removeChild(e);e=null};this.getObj=function(){return e};this.setPosition=function(a,b){e.x=a;e.y=b};this._init(b,c,f,a);return this}
function CManageFoods(b){var c,a,f,d=INTERVAL_SPAWN_FOOD;this._init=function(){f=new createjs.Container;f.tickChildren=!1;b.addChild(f);c=[];a=[];this.updateOccurrence();this.foodsInSections()};this.foodsInSections=function(){for(var a=Math.floor(MAX_FOODS_INSTANCE/FIELD_SECTION_SUBDIVISION.tot),b=s_oManageSections.getSections(),d=0;d<b.length;d++)for(var c=0;c<a;c++)this._spawnRandomFoods(b[d])};this.updateOccurrence=function(){for(var b=0;b<FOODS_OCCURRENCE.length;b++)for(var d=0;d<FOODS_OCCURRENCE[b];d++)a.push(b)};
this.getFoods=function(){return c};this._spawnRandomFoods=function(b){for(var e=Math.floor(Math.random()*a.length),d,k,l=s_oSpriteLibrary.getSprite("food_"+a[e]),p=Math.floor(Math.random()*FOOD_STATE[a[e]]),m=l.width/4,n=2*m,q=2.2*l.height,r=!0,v=0;r;){d=Math.random()*(b.getRect().x+b.getRect().width-n-(b.getRect().x+n))+b.getRect().x+n;k=Math.random()*(b.getRect().y+b.getRect().height-q-(b.getRect().y+q))+b.getRect().y+q;for(var A=0;A<c.length&&!(r=this.checkCollisionFoodToObject(c[A],m,d,k));A++);
if(!r)for(var t=s_oGame.getSnakesArray(),B=0;B<t.length&&!(r=this.checkCollisionFoodToObject(t[A],t.getDim().h,d,k));B++);if(v===MAX_FOODS_INSTANCE||!r)break;v++}e=new CFood(d,k,0,a[e],b.getID(),l,f);e.changeState(p);c.push(e);b.addFood(e);SHOW_FOODS_ID&&e.createTextID(c.length)};this.checkCollisionFoodToObject=function(a,b,d,c){return s_oGame.circleToCircleCollision({x:d,y:c},a.getPos(),b,a.getDim().w)?!0:!1};this.unload=function(){b.removeChild(f);f=null};this.restoresEatenFood=function(){for(var a=
s_oManageSections.getSections(),b=s_oManageSections.getSectionIDShuffle(),d=0;d<b.length;d++)for(var f=a[b[d]].getFoodsSection(),l=0;l<f.length;l++)if(f[l].getEaten()){f[l].setEaten(!1);for(var p=!0,m=0,n,q,a=a[b[d]],b=2*f[l].getDim().w,d=2.2*f[l].getDim().h;p;){n=Math.random()*(a.getRect().x+a.getRect().width-b-(a.getRect().x+b))+a.getRect().x+b;q=Math.random()*(a.getRect().y+a.getRect().height-d-(a.getRect().y+d))+a.getRect().y+d;for(var r=0;r<c.length&&!(p=this.checkCollisionFoodToObject(c[r],
c[r].getDim().w,n,q));r++);if(!p)for(var r=s_oGame.getSnakesArray(),v=0;v<r.length&&!(p=this.checkCollisionFoodToObject(r[v],r[v].getDim().w,n,q));v++);if(m===MAX_FOODS_INSTANCE||!p)break;m++}p=Math.floor(Math.random()*FOOD_STATE[f[l].getType()]);f[l].setPosition(n,q);f[l].changeState(p);f[l].spawnAnim(Math.floor(Math.random()*MAXT_TIME_WAIT_FOOD_SPAWN_ANIM));f[l].setVisible(!0);return}};this.restoresAllEatenFood=function(){for(var a=0;a<c.length;a++)if(c[a].getEaten()){c[a].setEaten(!1);for(var b=
!0,d=0,f,l,p=s_oManageSections.getSectionByID(c[a].getSectionID()),m=2*c[a].getDim().w,n=2.2*c[a].getDim().h;b;){f=Math.random()*(p.getRect().x+p.getRect().width-m-(p.getRect().x+m))+p.getRect().x+m;l=Math.random()*(p.getRect().y+p.getRect().height-n-(p.getRect().y+n))+p.getRect().y+n;for(var q=0;q<c.length&&!(b=this.checkCollisionFoodToObject(c[q],c[q].getDim().w,f,l));q++);if(!b)for(var q=s_oGame.getSnakesArray(),r=0;r<q.length&&!(b=this.checkCollisionFoodToObject(q[r],q[r].getDim().w,f,l));r++);
if(d===MAX_FOODS_INSTANCE||!b)break;d++}c[a].setPosition(f,l);c[a].spawnAnim(Math.floor(Math.random()*MAXT_TIME_WAIT_FOOD_SPAWN_ANIM));c[a].setVisible(!0)}};this.getFood=function(a){return c[a]};this.updateVisibility=function(){for(var a=0;a<c.length;a++)if(!c[a].getEaten()){var b=c[a].getLocalPos();b.x>-c[a].getDim().w+s_iOffsetX&&b.x<CANVAS_WIDTH+c[a].getDim().w-s_iOffsetX&&b.y>-c[a].getDim().h+s_iOffsetY&&b.y<CANVAS_HEIGHT+c[a].getDim().h-s_iOffsetY?c[a].setVisible(!0):c[a].setVisible(!1)}};this.update=
function(){this.updateVisibility();0<d?d-=s_iTimeElaps:(d=INTERVAL_SPAWN_FOOD,this.restoresEatenFood())};this._init();s_oManageFoods=this;return this}var s_oManageFoods=null;
function CFood(b,c,a,f,d,e,g){var h,k,l,p,m=!1;this._init=function(a,b,d,c,e){var f=new createjs.SpriteSheet({images:[c],frames:{width:c.width/4,height:c.height,regX:c.width/4/2,regY:c.height/2},animations:{apple:0,orange:1,cherry:2,pear:3}});h=createSprite(f,0,c.width/4/2,c.height/2,c.width/4,c.height);h.stop();h.regX+=REG_FOOD_OFFSET[d].x;h.regY+=REG_FOOD_OFFSET[d].y;k={w:c.width/4+COLLISION_OFFSET_FOOD[d].x,h:c.height+COLLISION_OFFSET_FOOD[d].y};p=d;h.x=a;h.y=b;h.rotation=e;h.tickEnabled=!1;g.addChild(h)};
this.getPos=function(){return{x:h.x,y:h.y}};this.getY=function(){return h.y};this.getX=function(){return h.x};this.changeState=function(a){h.gotoAndStop(a)};this.getType=function(){return p};this.getLocalPos=function(){return h.localToGlobal(0,0)};this.getDim=function(){return k};this.getEaten=function(){return m};this.createTextID=function(a){l=new createjs.Text(a,"20px "+FONT_GAME,"#ffffff");l.textAlign="center";l.textBaseline="middle";l.x=h.x;l.y=h.y;g.addChild(l)};this.eatenAnim=function(a){createjs.Tween.get(h).to({x:a.x,
y:a.y,scaleX:1,scaleY:1},100,createjs.Ease.cubicIn).set({visible:!1,scaleX:1,scaleY:1})};this.getID=function(){return l.text};this.getSectionID=function(){return d};this.setEaten=function(a){m=a};this.setVisible=function(a){h.visible=a};this.isVisible=function(){return h.visible};this.unload=function(){g.removeChild(h);h=null};this.getObj=function(){return h};this.spawnAnim=function(a){h.scaleX=h.scaleY=0;createjs.Tween.get(h).wait(a).to({scaleX:1,scaleY:1},TIME_FOOD_SPAWN_ANIM,createjs.Ease.elasticOut)};
this.setPosition=function(a,b){h.x=a;h.y=b;SHOW_FOODS_ID&&(l.x=a,l.y=b)};this._init(b,c,f,e,a);return this}
function CControlAiSnakes(){var b,c;this._init=function(){this.reset()};this.addSnakeToAI=function(a){var f=new CSubAISnake(a,AI_SNAKES[a.getType()].time_follow);a.setSubAI(f);b.push({snake:a,subAI:f});if(SHOW_FIELD_OF_VIEW){a=new createjs.Shape;var f=new createjs.Shape,d=new createjs.Shape;c.push([]);c[c.length-1].push(a);c[c.length-1].push(f);c[c.length-1].push(d);s_oScrollStage.addChild(a,f,d)}};this.manageAI=function(a,b){var d=this.fieldOfViewFood(a.snake,a.subAI,b);if(d.result===AI_FOODS){var c=
this.getFoodCloser(a.snake,d.foods);a.subAI.setSoundFollow(!1);a.snake.getTarget().result||this.setDirectionSnake(a,d.foods[c],AI_FOODS)}else d.result!==AI_PLAYER||s_oGame.getPlayerSnake().getEaten()?(a.subAI.setSoundFollow(!1),a.subAI.update()):(this.setDirectionSnake(a,d,AI_PLAYER),a.subAI.followTime(),a.subAI.playSoundFollow());a.snake.update(SNAKES_AI_SPEED[a.snake.getType()])};this.getFoodCloser=function(a,b){for(var d=0,c=distanceWithoutSQRT(a.getPos(),b[0].food.getPos()),f=1;f<b.length;f++){var h=
distanceWithoutSQRT(a.getPos(),b[f].food.getPos());c>h&&(c=h,d=f)}return d};this.setDirectionSnake=function(a,b,d){b=Math.atan2(b.vect.getY(),b.vect.getX())*(180/Math.PI)-90;a.snake.rotate(b);a.snake.setTarget({result:!0,target:d})};this.fieldOfViewFood=function(a,b,d){var c=[],f=new CVector2(a.getDir().getX(),a.getDir().getY()),h=new CVector2(a.getDir().getX(),a.getDir().getY());f.rotate(AI_ANGLE_DETECT_FOODS);h.rotate(-AI_ANGLE_DETECT_FOODS);var k=new CVector2(a.getX()+DISTANCE_AI_DETECT_FOOD*f.getX()-
a.getX(),a.getY()+DISTANCE_AI_DETECT_FOOD*f.getY()-a.getY()),l=new CVector2(a.getX()+(DISTANCE_AI_DETECT_FOOD*h.getX()-a.getX()),a.getY()+DISTANCE_AI_DETECT_FOOD*h.getY()-a.getY()),p=k.length2();SHOW_FIELD_OF_VIEW&&(f=new CVector2(a.getX()-DISTANCE_AI_DETECT_FOOD*f.getX(),a.getY()-DISTANCE_AI_DETECT_FOOD*f.getY()),h=new CVector2(a.getX()-DISTANCE_AI_DETECT_FOOD*h.getX(),a.getY()-DISTANCE_AI_DETECT_FOOD*h.getY()),this.castFieldOfViewLine(d[0],a,f,"red"),this.castFieldOfViewLine(d[1],a,h,"black"));
d=k.angleBetweenVectors(l);h=new CVector2(0,0);if(!(b.ignorePlayer()||this.countFollowersAI()&&a.getTarget().target!==AI_PLAYER)){var m=s_oGame.getPlayerSnake();h.set(a.getX()-m.getX(),a.getY()-m.getY());b=Math.abs(l.angleBetweenVectors(h));f=Math.abs(k.angleBetweenVectors(h));if(f<d&&b<d&&p>h.length2()&&a.getLengthQueue()>m.getLengthQueue())return{vect:h,result:AI_PLAYER};a.setTarget({result:!1,target:null})}for(var m=s_oManageFoods.getFoods(),n=0;n<m.length;n++)m[n].isVisible()&&(h.set(a.getX()-
m[n].getX(),a.getY()-m[n].getY()),b=Math.abs(l.angleBetweenVectors(h)),f=Math.abs(k.angleBetweenVectors(h)),f<d&&b<d&&p>h.length2()&&c.push({id:n,vect:h,result:AI_FOODS,food:m[n]}));return{foods:c,result:null}};this.countFollowersAI=function(){for(var a=0,c=0;c<b.length;c++)b[c].snake.getTarget().target===AI_PLAYER&&a++;return a>MAX_AI_FOLLOW_PLAYER?!0:!1};this.castFieldOfViewLine=function(a,b,d,c){a.graphics.clear();a.graphics.beginStroke(c);a.graphics.setStrokeStyle(5);a.graphics.moveTo(b.getX(),
b.getY());a.graphics.lineTo(d.getX(),d.getY());a.graphics.closePath()};this.removeSnakeByID=function(a){b.splice(a,1);if(SHOW_FIELD_OF_VIEW)for(var f=0;f<c[a].length;f++)s_oScrollStage.removeChild(c[a][f])};this.reset=function(){b=[];c=[]};this.update=function(){for(var a=0;a<b.length;a++)this.manageAI(b[a],c[a])};this._init();return this}
function CSubAISnake(b,c){var a=0,f,d=c,e=AI_TIME_IGNORE_PLAYER,g=!1,h=!1;this._init=function(){f=Math.random()*(AI_WAIT_TIME_FOR_CHANGE_DIR.max-AI_WAIT_TIME_FOR_CHANGE_DIR.min)+AI_WAIT_TIME_FOR_CHANGE_DIR.min};this.setRandomDirection=function(){0>a?0<f?(b.rotation(HERO_ROT_SPEED),f-=s_iTimeElaps):(f=Math.random()*(AI_WAIT_TIME_FOR_CHANGE_DIR.max-AI_WAIT_TIME_FOR_CHANGE_DIR.min)+AI_WAIT_TIME_FOR_CHANGE_DIR.min,a=Math.random()*(AI_TIME_CHANGE_DIR.max-AI_TIME_CHANGE_DIR.min)+AI_TIME_CHANGE_DIR.min):
a-=s_iTimeElaps};this.followTime=function(){0>d?(g=!0,a=-1):d-=s_iTimeElaps};this.setFollowTime=function(a){d=a};this.getFollowTime=function(){return d};this.playSoundFollow=function(){h||(h=!0,playSound("snake_follow",1,0))};this.setSoundFollow=function(a){h=a};this.ignorePlayerTime=function(){g&&(0<e?e-=s_iTimeElaps:(g=!1,e=AI_TIME_IGNORE_PLAYER,d=AI_SNAKES[b.getType()].time_follow))};this.ignorePlayer=function(){return g};this.update=function(){this.setRandomDirection();this.ignorePlayerTime()};
this._init();return this}
function CManageSections(){var b,c;this._init=function(){b=[];c=[];this.createSection()};this.createSection=function(){for(var a=EDGES_PROPERTIES.x,f=EDGES_PROPERTIES.y,d=EDGES_PROPERTIES.xMax/FIELD_SECTION_SUBDIVISION.w,e=EDGES_PROPERTIES.yMax/FIELD_SECTION_SUBDIVISION.h,g=0,h=0;h<FIELD_SECTION_SUBDIVISION.h;h++){for(var k=0;k<FIELD_SECTION_SUBDIVISION.w;k++)b.push(new CSection(g,{x:a,y:f,w:d,h:e})),c.push(g),a+=d,g++;f+=e;a=EDGES_PROPERTIES.x}};this.getSections=function(){return b};this.getSectionIDShuffle=
function(){return shuffle(c)};this.getSectionByID=function(a){return b[a]};this._init();s_oManageSections=this;return this}var s_oManageSections=null;
function CSection(b,c){var a,f;this._init=function(b){f=[];a=new createjs.Rectangle(b.x,b.y,b.w,b.h);this.createDebugShape()};this.createDebugShape=function(){if(SHOW_SECTION_SHAPE){var b=new createjs.Shape;b.graphics.beginFill(getRandomColor()).drawRect(a.x,a.y,a.width,a.height);b.alpha=.5;s_oScrollStage.addChild(b)}};this.addFood=function(a){f.push(a)};this.getFoodsSection=function(){return f};this.getRect=function(){return a};this.getID=function(){return b};this._init(c);return this}
function CPause(){var b;this._init=function(){var c=new createjs.Container;c.alpha=0;b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.alpha=.5;var a=new createjs.Shape;a.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.hitArea=a;b.on("click",function(){});c.addChild(b);a=new createjs.Text(TEXT_PAUSE,"80px "+FONT_GAME,"#ff6c00");a.x=.5*CANVAS_WIDTH;a.y=.5*CANVAS_HEIGHT-130;a.textAlign="center";c.addChild(a);a=s_oSpriteLibrary.getSprite("but_continue");
(new CGfxButton(.5*CANVAS_WIDTH,.5*CANVAS_HEIGHT+70,a,c)).addEventListenerWithParams(ON_MOUSE_UP,this._onLeavePause,this,c);s_oStage.addChild(c);createjs.Tween.get(c,{ignoreGlobalPause:!0}).to({alpha:1},300,createjs.quartOut)};this.unload=function(){b.off("click",function(){});s_oStage.removeChild(void 0)};this._onLeavePause=function(b){createjs.Tween.get(b,{ignoreGlobalPause:!0}).to({alpha:0},300,createjs.quartIn).call(function(){s_oInterface.unloadPause();s_oGame.unpause(!0)})};this._init();return this}
function CAreYouSurePanel(b){var c,a,f,d,e,g,h,k;this._init=function(){g=new createjs.Container;g.alpha=0;h.addChild(g);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=.5;k.on("click",function(){});g.addChild(k);var b=s_oSpriteLibrary.getSprite("msg_box");c=createBitmap(b);c.x=CANVAS_WIDTH_HALF;c.y=CANVAS_HEIGHT_HALF;c.regX=.5*b.width;c.regY=.5*b.height;g.addChild(c);a=new createjs.Text(TEXT_ARE_SURE,"80px "+FONT_GAME,"#000");a.x=CANVAS_WIDTH/2;
a.y=CANVAS_HEIGHT_HALF-65;a.textAlign="center";a.textBaseline="middle";a.outline=5;g.addChild(a);f=new createjs.Text(TEXT_ARE_SURE,"80px "+FONT_GAME,"#ff6c00");f.x=CANVAS_WIDTH/2;f.y=a.y;f.textAlign="center";f.textBaseline="middle";g.addChild(f);d=new CGfxButton(CANVAS_WIDTH/2+260,.5*CANVAS_HEIGHT+100,s_oSpriteLibrary.getSprite("but_yes"),g);d.addEventListener(ON_MOUSE_UP,this._onButYes,this);e=new CGfxButton(CANVAS_WIDTH/2-260,.5*CANVAS_HEIGHT+100,s_oSpriteLibrary.getSprite("but_not"),g);e.addEventListener(ON_MOUSE_UP,
this._onButNo,this)};this.show=function(){s_oGame.unpause(!1);createjs.Tween.get(g,{ignoreGlobalPause:!0}).to({alpha:1},150,createjs.quartOut)};this.unload=function(){createjs.Tween.get(g,{ignoreGlobalPause:!0}).to({alpha:0},150,createjs.quartOut).call(function(){h.removeChild(g,k)})};this._onButYes=function(){this.unload();s_oGame.onExit();k.removeAllEventListeners()};this._onButNo=function(){s_oGame.unpause(!0);this.unload();g.visible=!1;k.removeAllEventListeners()};h=b;this._init()}
function CBackground(b){var c,a;this._init=function(){c=new createjs.Container;c.tickChildren=!1;b.addChild(c);var f=new createjs.Matrix2D;f.a=f.d=1;a=new createjs.Shape;a.graphics.beginBitmapFill(s_oSpriteLibrary.getSprite("bg_game"),"repeat",f).drawRect(0,0,3072,2048);a.y=0;a.alpha=1;a.tickEnabled=!1;c.addChild(a)};this._init();return this}
function CAnimMenu(b){var c,a=null,f,d,e=MENU_SNAKE_GOOD_ROTATION,g=MENU_SNAKE_BAD_ROTATION,h,k,l=!1,p=!1,m=.5*MENU_SNAKE_GOOD_TIME_ROTATION,n=.5*MENU_SNAKE_BAD_TIME_ROTATION,q=MENU_BAD_SNAKE_DELAY;this._init=function(){c=new createjs.Container;b.addChild(c);f=new CSnake(-100,CANVAS_HEIGHT_HALF,s_oSpriteLibrary.getSprite("snake_head_4"),4,15,0,c);f.rotate(90);h=s_oSpriteLibrary.getSprite("snake_parts_4").height*(15/(MENU_SNAKES_VELOCITY/20))+CANVAS_WIDTH-s_iOffsetX;var e=Math.floor(3*Math.random());
d=new CSnake(-100,CANVAS_HEIGHT_HALF,s_oSpriteLibrary.getSprite("snake_head_"+e),e,25,0,c);d.rotate(90);a=new CLogo(CANVAS_WIDTH_HALF,-.5*s_oSpriteLibrary.getSprite("logo").height,b);createjs.Tween.get(this).wait(1500).call(function(){a.animLogo();s_oMenu.animContainerGUI()});k=s_oSpriteLibrary.getSprite("snake_parts_"+e).height*(25/(MENU_SNAKES_VELOCITY/20))+CANVAS_WIDTH-s_iOffsetX};this.animSnakes=function(){l||(0>m?(e*=-1,m=MENU_SNAKE_GOOD_TIME_ROTATION):(m-=s_iTimeElaps,f.rotation(e)),f.update(MENU_SNAKES_VELOCITY),
f.getX()>h&&(l=!0,this.unloadSnake(f)));p||(0>n?(g*=-1,n=MENU_SNAKE_BAD_TIME_ROTATION):(n-=s_iTimeElaps,d.rotation(g)),0>q?(d.update(MENU_SNAKES_VELOCITY),d.getX()>k&&(p=!0,this.unloadSnake(d))):q-=s_iTimeElaps)};this.unloadSnake=function(a){a.unload()};this.update=function(){this.animSnakes()};this._init();return this}
function CLogo(b,c,a){var f;this._init=function(b,c){var d=s_oSpriteLibrary.getSprite("logo");f=createBitmap(d);f.regX=.5*d.width;f.regY=.5*d.height;f.x=b;f.y=c;a.addChild(f)};this.animLogo=function(){createjs.Tween.get(f).to({y:CANVAS_HEIGHT_HALF-100},1E3,createjs.Ease.bounceOut)};this._init(b,c);return this}
function CAnimHelp(b,c,a,f){var d,e=[],g,h=0,k,l=0;this._init=function(a,b,c){d={x:b,y:c};g=new createjs.Container;g.x=d.x;g.y=d.y;f.addChild(g);for(b=0;b<FRAMES_NUM_HELP[a];b++)e.push(createBitmap(s_oSpriteLibrary.getSprite("help_"+a+"_"+b))),e[b].visible=!1,g.addChild(e[b]);e[0].visible=!0;k=a;g.regX=s_oSpriteLibrary.getSprite("help_"+a+"_0").width;g.regY=s_oSpriteLibrary.getSprite("help_"+a+"_0").height};this.setPosition=function(a,b){g.x=a;g.y=b};this.getStartPos=function(){return d};this.setVisibleMonitor=
function(a){g.visible=a};this.viewMonitor=function(a,b){a[b].visible=!0};this.hideMonitor=function(a,b){a[b].visible=!1};this.animMonitor=function(){l+=s_iTimeElaps;l>BUFFER_ANIM_MONITOR[k]&&(this.hideMonitor(e,h),h+1<FRAMES_NUM_HELP[k]?(this.viewMonitor(e,h+1),h++):(l=h=0,this.viewMonitor(e,h)),l=0)};this._init(b,c,a);s_oAnimMonitor=this;return this}var s_oAnimMonitor=null;
