var s_iScaleFactor=1,s_iOffsetX,s_iOffsetY,s_bIsIphone=!1;
(function(b){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(b)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(b.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(b){console.log(b)}
function getSize(b){var d=b.toLowerCase(),a=window.document,c=a.documentElement;if(void 0===window["inner"+b])b=c["client"+b];else if(window["inner"+b]!=c["client"+b]){var e=a.createElement("body");e.id="vpw-test-b";e.style.cssText="overflow:scroll";var f=a.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+d+":"+c["client"+b]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";e.appendChild(f);c.insertBefore(e,a.head);
b=7==f["offset"+b]?c["client"+b]:window["inner"+b];c.removeChild(e)}else b=window["inner"+b];return b}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function isIOS(){for(var b="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");b.length;)if(navigator.platform===b.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var b=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<b?b:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var b;b=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width"),a=Math.min(b/CANVAS_HEIGHT,d/CANVAS_WIDTH),c=CANVAS_WIDTH*a,a=CANVAS_HEIGHT*a;s_bMobile&&!s_bIsIphone?($("#canvas").css("width",c+"px"),$("#canvas").css("height",a+"px")):(s_oStage.canvas.width=c,s_oStage.canvas.height=a,s_oStage.scaleX=s_oStage.scaleY=Math.min(c/CANVAS_WIDTH,a/CANVAS_HEIGHT));var e;a<b?(e=b-a,a+=e,c+=CANVAS_WIDTH/
CANVAS_HEIGHT*e):c<d&&(e=d-c,c+=e,a+=CANVAS_HEIGHT/CANVAS_WIDTH*e);e=b/2-a/2;var f=d/2-c/2,g=CANVAS_WIDTH/c;if(f*g<-EDGEBOARD_X||e*g<-EDGEBOARD_Y)a=Math.min(b/(CANVAS_HEIGHT-2*EDGEBOARD_Y),d/(CANVAS_WIDTH-2*EDGEBOARD_X)),c=CANVAS_WIDTH*a,a*=CANVAS_HEIGHT,e=(b-a)/2,f=(d-c)/2,g=CANVAS_WIDTH/c;s_iOffsetX=-1*f*g;s_iOffsetY=-1*e*g;0<=e&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);
$("#canvas").css("width",c+"px");$("#canvas").css("height",a+"px");0>e?$("#canvas").css("top",e+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",f+"px")}}function playSound(b,d,a){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(b,{loop:a,volume:d}):null}function stopSound(b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||b.stop()}function setVolume(b,d){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)b.volume=d}
function setMute(b,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||b.setMute(d)}function createBitmap(b,d,a){var c=new createjs.Bitmap(b),e=new createjs.Shape;d&&a?e.graphics.beginFill("#fff").drawRect(0,0,d,a):e.graphics.beginFill("#ff0").drawRect(0,0,b.width,b.height);c.hitArea=e;return c}function createSprite(b,d,a,c,e,f){b=null!==d?new createjs.Sprite(b,d):new createjs.Sprite(b);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-a,-c,e,f);b.hitArea=d;return b}
function pad(b,d,a){b+="";return b.length>=d?b:Array(d-b.length+1).join(a||"0")+b}function randomFloatBetween(b,d,a){"undefined"===typeof a&&(a=2);return parseFloat(Math.min(b+Math.random()*(d-b),d).toFixed(a))}function rotateVector2D(b,d){var a=d.getX()*Math.cos(b)+d.getY()*Math.sin(b),c=d.getX()*-Math.sin(b)+d.getY()*Math.cos(b);d.set(a,c)}function tweenVectorsOnX(b,d,a){return b+a*(d-b)}
function shuffle(b){for(var d=b.length,a,c;0!==d;)c=Math.floor(Math.random()*d),--d,a=b[d],b[d]=b[c],b[c]=a;return b}function bubbleSort(b){var d;do{d=!1;for(var a=0;a<b.length-1;a++)b[a]>b[a+1]&&(d=b[a],b[a]=b[a+1],b[a+1]=d,d=!0)}while(d)}function compare(b,d){return b.index>d.index?-1:b.index<d.index?1:0}function easeLinear(b,d,a,c){return a*b/c+d}function easeInQuad(b,d,a,c){return a*(b/=c)*b+d}function easeInSine(b,d,a,c){return-a*Math.cos(b/c*(Math.PI/2))+a+d}
function easeInCubic(b,d,a,c){return a*(b/=c)*b*b+d}function getTrajectoryPoint(b,d){var a=new createjs.Point,c=(1-b)*(1-b),e=b*b;a.x=c*d.start.x+2*(1-b)*b*d.traj.x+e*d.end.x;a.y=c*d.start.y+2*(1-b)*b*d.traj.y+e*d.end.y;return a}function formatTime(b){b/=1E3;var d=Math.floor(b/60);b=parseFloat(b-60*d).toFixed(1);var a="",a=10>d?a+("0"+d+":"):a+(d+":");return 10>b?a+("0"+b):a+b}function degreesToRadians(b){return b*Math.PI/180}
function checkRectCollision(b,d){var a,c;a=getBounds(b,.9);c=getBounds(d,.98);return calculateIntersection(a,c)}function calculateIntersection(b,d){var a,c,e,f,g,l,k,h;a=b.x+(e=b.width/2);c=b.y+(f=b.height/2);g=d.x+(l=d.width/2);k=d.y+(h=d.height/2);a=Math.abs(a-g)-(e+l);c=Math.abs(c-k)-(f+h);return 0>a&&0>c?(a=Math.min(Math.min(b.width,d.width),-a),c=Math.min(Math.min(b.height,d.height),-c),{x:Math.max(b.x,d.x),y:Math.max(b.y,d.y),width:a,height:c,rect1:b,rect2:d}):null}
function getBounds(b,d){var a={x:Infinity,y:Infinity,width:0,height:0};if(b instanceof createjs.Container){a.x2=-Infinity;a.y2=-Infinity;var c=b.children,e=c.length,f,g;for(g=0;g<e;g++)f=getBounds(c[g],1),f.x<a.x&&(a.x=f.x),f.y<a.y&&(a.y=f.y),f.x+f.width>a.x2&&(a.x2=f.x+f.width),f.y+f.height>a.y2&&(a.y2=f.y+f.height);Infinity==a.x&&(a.x=0);Infinity==a.y&&(a.y=0);Infinity==a.x2&&(a.x2=0);Infinity==a.y2&&(a.y2=0);a.width=a.x2-a.x;a.height=a.y2-a.y;delete a.x2;delete a.y2}else{var l,k;b instanceof createjs.Bitmap?
(e=b.sourceRect||b.image,g=e.width*d,l=e.height*d):b instanceof createjs.Sprite?b.spriteSheet._frames&&b.spriteSheet._frames[b.currentFrame]&&b.spriteSheet._frames[b.currentFrame].image?(e=b.spriteSheet.getFrame(b.currentFrame),g=e.rect.width,l=e.rect.height,c=e.regX,k=e.regY):(a.x=b.x||0,a.y=b.y||0):(a.x=b.x||0,a.y=b.y||0);c=c||0;g=g||0;k=k||0;l=l||0;a.regX=c;a.regY=k;e=b.localToGlobal(0-c,0-k);f=b.localToGlobal(g-c,l-k);g=b.localToGlobal(g-c,0-k);c=b.localToGlobal(0-c,l-k);a.x=Math.min(Math.min(Math.min(e.x,
f.x),g.x),c.x);a.y=Math.min(Math.min(Math.min(e.y,f.y),g.y),c.y);a.width=Math.max(Math.max(Math.max(e.x,f.x),g.x),c.x)-a.x;a.height=Math.max(Math.max(Math.max(e.y,f.y),g.y),c.y)-a.y}return a}function NoClickDelay(b){this.element=b;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(b){for(var d=b.length,a,c;0<d;)c=Math.floor(Math.random()*d),d--,a=b[d],b[d]=b[c],b[c]=a;return b}
NoClickDelay.prototype={handleEvent:function(b){switch(b.type){case "touchstart":this.onTouchStart(b);break;case "touchmove":this.onTouchMove(b);break;case "touchend":this.onTouchEnd(b)}},onTouchStart:function(b){b.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(b){this.moved=!0},onTouchEnd:function(b){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){b=document.elementFromPoint(b.changedTouches[0].clientX,b.changedTouches[0].clientY);3==b.nodeType&&(b=b.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);b.dispatchEvent(d)}}};
(function(){function b(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",b):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",b):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",b):(d="msHidden")in document?document.addEventListener("msvisibilitychange",b):"onfocusin"in document?document.onfocusin=document.onfocusout=b:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=b})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(b){for(var d=window.location.search.substring(1).split("&"),a=0;a<d.length;a++){var c=d[a].split("=");if(c[0]==b)return c[1]}}
function CSpriteLibrary(){var b,d,a,c,e,f;this.init=function(g,l,k){a=d=0;c=g;e=l;f=k;b={}};this.addSprite=function(a,c){b.hasOwnProperty(a)||(b[a]={szPath:c,oSprite:new Image},d++)};this.getSprite=function(a){return b.hasOwnProperty(a)?b[a].oSprite:null};this._onSpritesLoaded=function(){e.call(f)};this._onSpriteLoaded=function(){c.call(f);++a==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in b)b[a].oSprite.oSpriteLibrary=this,b[a].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
b[a].oSprite.src=b[a].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=640,CANVAS_HEIGHT=1024,EDGEBOARD_X=16,EDGEBOARD_Y=110,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="space_marine",SPACE_BAR=32,LEFT=37,RIGHT=39,UP=38,DOWN=40,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_CONTROLLER_END=8,ON_CONTROLLER_REMOVE=9,ON_CONTROLLER_ROLL=10,HORIZONTAL_SELECTION_STATE=0,VERTICAL_SELECTION_STATE=1,SHOT_SELECTION_STATE=2,NULL_TARGET_RIGHT=-3,
NULL_TARGET_LEFT=-2,NULL_TARGET_POLE=-1,RED_TARGET=0,YELLOW_TARGET=1,GREEN_TARGET=2,NUM_STAGES=5,BALL_FLYTIME=2500,BALL_MAX_ROTATION=30,SHOT_INDICATOR_SPEED,DECREASE_SHOT_INDICATOR_SPEED,SHOTS_PER_STAGE,RED_AREA_POINTS,YELLOW_AREA_POINTS,GREEN_AREA_POINTS,AD_SHOW_COUNTER,GOAL_AREA=[{x:0,y:-40,width:750,height:435},{x:-26,y:-94,width:750,height:420},{x:-18,y:-78,width:750,height:400},{x:16,y:-206,width:750,height:500},{x:-34,y:-202,width:750,height:500}],STAKE_POS=[[{x:-160,y:-260},{x:-165,y:190},
{x:165,y:190},{x:160,y:-260}],[{x:-185,y:-300},{x:-190,y:170},{x:140,y:150},{x:135,y:-350}],[{x:-170,y:-330},{x:-175,y:165},{x:140,y:180},{x:140,y:-280}],[{x:-120,y:-530},{x:-125,y:90},{x:155,y:135},{x:150,y:-400}],[{x:-145,y:-400},{x:-150,y:140},{x:80,y:90},{x:75,y:-540}]],POST_POS=[{x:0,y:66},{x:-26,y:20},{x:-18,y:34},{x:-4,y:-70},{x:12,y:-70}],TARGET_AREA_SPRITE_OFFSET=[{red:{x:0,y:0},yellow:{x:0,y:0},green:{x:0,y:0}},{red:{x:0,y:0},yellow:{x:4,y:-6},green:{x:5,y:-9}},{red:{x:0,y:0},yellow:{x:-3,
y:-6},green:{x:-4,y:-9}},{red:{x:0,y:0},yellow:{x:-6,y:-18},green:{x:-9,y:-27}},{red:{x:0,y:0},yellow:{x:6,y:-20},green:{x:8,y:-30}}],Y_BAR_OFFSET=[-150,-150,-150,-180,-180],GREEN_INDICATOR_RANGE=[{horiz:{left:-14,right:14},vert:{top:-29,bot:24}},{horiz:{left:-17,right:11},vert:{top:-25,bot:32}},{horiz:{left:-12,right:15},vert:{top:-25,bot:32}},{horiz:{left:-7,right:16},vert:{top:-23,bot:39}},{horiz:{left:-13,right:4},vert:{top:-11,bot:39}}];TEXT_GAMEOVER="CONGRATULATIONS!";TEXT_SCORE="SCORE";
TEXT_STAGE="STAGE";TEXT_TOTAL_SCORE="TOTAL SCORE";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_WIDE_RIGHT="WIDE RIGHT!";TEXT_WIDE_LEFT="WIDE LEFT!";TEXT_CENTER_NULL="POLE HIT!";TEXT_CENTER_RED="NOT BAD!";TEXT_CENTER_YELLOW="GOOD!";TEXT_CENTER_GREEN="SUPER!";TEXT_HELP1="PRESS SPACEBAR TO CHOOSE THE POINT WHERE KICKING THE BALL";TEXT_HELP1_MOB="TAP ON THE SCREEN TO CHOOSE THE POINT WHERE KICKING THE BALL";TEXT_HELP2="CENTER THE GREEN AREA TO GET THE TOP SCORE!";TEXT_SHARE_IMAGE="200x200.jpg";
TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var b,d,a,c,e,f,g;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();g=new createjs.Container;s_oStage.addChild(g)};this.unload=function(){g.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(f).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));g.addChild(l);l=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(l);c.x=CANVAS_WIDTH/2-l.width/2;c.y=CANVAS_HEIGHT-170;g.addChild(c);b=l.width;d=l.height;e=new createjs.Shape;e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,d);g.addChild(e);c.mask=
e;a=new createjs.Text("","30px Arial","#fff");a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT-125;a.shadow=new createjs.Shadow("#000",2,2,2);a.textBaseline="alphabetic";a.textAlign="center";g.addChild(a);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;g.addChild(f)};this.refreshLoader=function(f){a.text=f+"%";e.graphics.clear();f=Math.floor(f*b/100);e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,f,d)};this._init()}
function CMain(b){var d,a=0,c=0,e=STATE_LOADING,f,g,l;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oTweenController=new CTweenController;s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();d=!0};this.soundLoaded=function(){a++;g.refreshLoader(Math.floor(a/c*100));if(a===c){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&
(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/crowd.ogg","crowd"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/kick.ogg",
"kick"),createjs.Sound.registerSound("./sounds/goal.mp3","goal"),createjs.Sound.registerSound("./sounds/miss_goal.ogg","miss_goal"),createjs.Sound.registerSound("./sounds/red_area.ogg","red_area"),createjs.Sound.registerSound("./sounds/yellow_area.ogg","yellow_area"),createjs.Sound.registerSound("./sounds/green_area.ogg","green_area")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3",
"soundtrack"),createjs.Sound.registerSound("./sounds/crowd.mp3","crowd"),createjs.Sound.registerSound("./sounds/press_button.mp3","click"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/kick.mp3","kick"),createjs.Sound.registerSound("./sounds/goal.mp3","goal"),createjs.Sound.registerSound("./sounds/miss_goal.mp3","miss_goal"),createjs.Sound.registerSound("./sounds/red_area.mp3","red_area"),createjs.Sound.registerSound("./sounds/yellow_area.mp3",
"yellow_area"),createjs.Sound.registerSound("./sounds/green_area.mp3","green_area")),c+=10)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("logo","./sprites/logo.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");
s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("but_yes_big","./sprites/but_yes_big.png");s_oSpriteLibrary.addSprite("but_exit_big","./sprites/but_exit_big.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");for(var a=1;5>=a;a++)s_oSpriteLibrary.addSprite("bg_game_"+a,"./sprites/bg_game_"+a+"/bg_game_"+a+".jpg"),s_oSpriteLibrary.addSprite("post_"+
a,"./sprites/bg_game_"+a+"/post_"+a+".png"),s_oSpriteLibrary.addSprite("green_area_"+a,"./sprites/bg_game_"+a+"/green_area_"+a+".png"),s_oSpriteLibrary.addSprite("yellow_area_"+a,"./sprites/bg_game_"+a+"/yellow_area_"+a+".png"),s_oSpriteLibrary.addSprite("red_area_"+a,"./sprites/bg_game_"+a+"/red_area_"+a+".png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");
s_oSpriteLibrary.addSprite("arrow_bar","./sprites/arrow_bar.png");s_oSpriteLibrary.addSprite("top_bar","./sprites/top_bar.png");s_oSpriteLibrary.addSprite("right_bar","./sprites/right_bar.png");s_oSpriteLibrary.addSprite("ball","./sprites/ball.png");s_oSpriteLibrary.addSprite("ball_holder","./sprites/ball_holder.png");for(a=0;37>=a;a++)s_oSpriteLibrary.addSprite("player_"+a,"./sprites/player/player_"+a+".png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=
function(){a++;g.refreshLoader(Math.floor(a/c*100));if(a===c){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;e=STATE_MENU};this.gotoGame=function(){l=new CGame(f);e=STATE_GAME};this.gotoHelp=function(){new CHelp;e=STATE_HELP};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=
!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&l.update();s_oStage.update(a)}};s_oMain=this;f=b;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack,s_oCanvas,s_oTweenController;
function CTextButton(b,d,a,c,e,f,g){var l,k,h,m,p;this._init=function(a,b,c,e,d,f,g){l=[];k=[];var C=createBitmap(c),D=Math.ceil(g/20);p=new createjs.Text(e,"bold "+g+"px "+d,"#000000");p.textAlign="center";p.textBaseline="alphabetic";var t=p.getBounds();p.x=c.width/2+D;p.y=Math.floor(c.height/2)+t.height/3+D;m=new createjs.Text(e,"bold "+g+"px "+d,f);m.textAlign="center";m.textBaseline="alphabetic";t=m.getBounds();m.x=c.width/2;m.y=Math.floor(c.height/2)+t.height/3;h=new createjs.Container;h.x=a;
h.y=b;h.regX=c.width/2;h.regY=c.height/2;h.addChild(C,p,m);s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown");h.off("pressup");s_oStage.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){oParent=this;h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){l[a]=b;k[a]=c};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=
function(){h.scaleX=.9;h.scaleY=.9;l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setTextPosition=function(a){m.y=a;p.y=a+2};this.setPosition=function(a,b){h.x=a;h.y=b};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(b,d,a,c,e,f,g);return this}
function CToggle(b,d,a,c,e){var f,g,l,k;this._init=function(a,b,c,e,d){g=[];l=[];var q=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=e;k=createSprite(q,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);k.x=a;k.y=b;k.stop();d.addChild(k);this._initListener()};this.unload=function(){s_bMobile?k.off("mousedown",this.buttonDown):(k.off("mousedown",this.buttonDown),k.off("mouseover",this.buttonOver));
k.off("pressup",this.buttonRelease);e.removeChild(k)};this._initListener=function(){if(s_bMobile)k.on("mousedown",this.buttonDown);else k.on("mousedown",this.buttonDown),k.on("mouseover",this.buttonOver);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;l[a]=c};this.setActive=function(a){f=a;k.gotoAndStop("state_"+f)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");f=!f;k.gotoAndStop("state_"+
f);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(l[ON_MOUSE_UP],f)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.setPosition=function(a,b){k.x=a;k.y=b};this._init(b,d,a,c,e)}
function CGfxButton(b,d,a,c){var e,f,g,l,k,h;this._init=function(a,b,c,d){e=!1;f=1;g=[];l=[];k=createBitmap(c);k.x=a;k.y=b;k.scaleX=k.scaleY=f;k.regX=c.width/2;k.regY=c.height/2;d.addChild(k);this._initListener()};this.unload=function(){s_bMobile?k.off("mousedown",this.buttonDown):(k.off("mousedown",this.buttonDown),k.off("mouseover",this.buttonOver));k.off("pressup",this.buttonRelease);c.removeChild(k)};this.setVisible=function(a){k.visible=a};this.setClickable=function(a){e=!a};this._initListener=
function(){if(s_bMobile)k.on("mousedown",this.buttonDown);else k.on("mousedown",this.buttonDown),k.on("mouseover",this.buttonOver);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;l[a]=c};this.buttonRelease=function(){e||(k.scaleX=f,k.scaleY=f,g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(l[ON_MOUSE_UP]))};this.buttonDown=function(){e||(k.scaleX=.9*f,k.scaleY=.9*f,playSound("click",1,0),g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN]))};this.buttonOver=function(a){s_bMobile||
e||(a.target.cursor="pointer")};this.pulseAnimation=function(){createjs.Tween.get(k).to({scaleX:.9*f,scaleY:.9*f},850,createjs.Ease.quadOut).to({scaleX:f,scaleY:f},650,createjs.Ease.quadIn).call(function(){h.pulseAnimation()})};this.trembleAnimation=function(){createjs.Tween.get(k).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){h.trebleAnimation()})};this.setPosition=function(a,b){k.x=a;k.y=b};
this.setX=function(a){k.x=a};this.setY=function(a){k.y=a};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};h=this;this._init(b,d,a,c);return this}
function CRollingTextController(b,d,a,c,e){var f,g,l,k,h,m,p,n,r,q,u,y;this._init=function(a,b,c,e,d){n=[];r=[];h=e;this.setUpdateInfo(c);p=d;u=a;y=b;q=[]};this.unload=function(){clearInterval(m)};this.setUpdateInfo=function(a){l=parseFloat(b.text);k=a;f=0;g=Math.round(h/FPS);var c=this;m=setInterval(function(){c.update()},FPS_TIME)};this.addEventListener=function(a,b,c){n[a]=b;r[a]=c};this.addRollingListener=function(a,b,c){n[ON_CONTROLLER_ROLL]=a;r[ON_CONTROLLER_ROLL]=b;q=[];for(a=0;a<c.length;a++)q[a]=
{step:c[a],flag:!1}};this.increaseValue=function(a){};this.getTarget=function(){return u};this.update=function(){f++;if(f>g)f=0,u.text=k.toFixed(0),null!==y&&(y.text=k.toFixed(0)),clearInterval(m);else{var a;switch(p){case EASE_BACKIN:a=s_oTweenController.easeInBack(f,0,1,g);break;case EASE_BACKOUT:a=s_oTweenController.easeOutBack(f,0,1,g);break;case EASE_CUBIC_IN:a=s_oTweenController.easeInCubic(f,0,1,g);break;case EASE_CUBIC_OUT:a=s_oTweenController.easeOutCubic(f,0,1,g);break;case EASE_ELASTIC_OUT:a=
s_oTweenController.easeOutElastic(f,0,1,g);break;case EASE_LINEAR:a=s_oTweenController.easeLinear(f,0,1,g);break;case EASE_QUART_BACKIN:a=s_oTweenController.easeBackInQuart(f,0,1,g);break;default:a=s_oTweenController.easeLinear(f,0,1,g)}a=s_oTweenController.tweenValue(l,k,a);for(var b=0;b<q.length;b++)a>q[b].step&&!q[b].flag&&(q[b].flag=!0,null!==n[ON_CONTROLLER_ROLL]&&n[ON_CONTROLLER_ROLL].call(r[ON_CONTROLLER_ROLL],b));u.text=a.toFixed(0);null!==y&&(y.text=a.toFixed(0))}};this._init(b,d,a,c,e)}
var EASE_LINEAR=0,EASE_CUBIC_IN=1,EASE_QUART_BACKIN=2,EASE_BACKIN=3,EASE_SIN_IN=4,EASE_QUAD_IN=5,EASE_CUBIC_OUT=6,EASE_ELASTIC_OUT=7,EASE_BACKOUT=8,EASE_QUINT_OUT=9,EASE_CUBIC_INOUT=10;
function CTweenController(){this.tweenValue=function(b,d,a){return b+a*(d-b)};this.easeLinear=function(b,d,a,c){return a*b/c+d};this.easeInCubic=function(b,d,a,c){c=(b/=c)*b*b;return d+a*c};this.easeBackInQuart=function(b,d,a,c){c=(b/=c)*b;return d+a*(2*c*c+2*c*b+-3*c)};this.easeInBack=function(b,d,a,c){return a*(b/=c)*b*(2.70158*b-1.70158)+d};this.easeInSine=function(b,d,a,c){return-a*Math.cos(b/c*(Math.PI/2))+a+d};this.easeInQuad=function(b,d,a,c){return a*(b/=c)*b+d};this.easeOutCubic=function(b,
d,a,c){return a*((b=b/c-1)*b*b+1)+d};this.easeOutElastic=function(b,d,a,c){var e;if(0===b)return d;if(1===(b/=c))return d+a;e=.3*c;return a*Math.pow(2,-10*b)*Math.sin(2*(b*c-e/4)*Math.PI/e)+a+d};this.easeOutBack=function(b,d,a,c){return a*((b=b/c-1)*b*(2.70158*b+1.70158)+1)+d};this.easeInOutCubic=function(b,d,a,c){return 1>(b/=c/2)?a/2*b*b*b+d:a/2*((b-=2)*b*b+2)+d};this.easeOutQuint=function(b,d,a,c){return a*((b=b/c-1)*b*b*b*b+1)+d}}
function CMenu(){var b,d,a,c,e,f,g,l,k,h,m,p,n,r;this._init=function(){k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(k);l=g=10;var q=s_oSpriteLibrary.getSprite("logo");r=createBitmap(q);r.x=g;r.y=l;s_oStage.addChild(r);q=s_oSpriteLibrary.getSprite("but_play");e=CANVAS_WIDTH-q.height/2-50;f=CANVAS_HEIGHT-q.height/2-50;h=new CGfxButton(e,f,q,s_oStage);h.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=s_oSpriteLibrary.getSprite("audio_icon"),
b=CANVAS_WIDTH-q.height/2-10,d=q.height/2+10,p=new CToggle(b,d,q,s_bAudioActive,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);q=s_oSpriteLibrary.getSprite("but_info");a=CANVAS_WIDTH-q.width/2-80;c=q.height/2+10;n=new CGfxButton(a,c,q,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onCreditsBut,this);m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(m);createjs.Tween.get(m).to({alpha:0},1E3).call(function(){m.visible=!1});
this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){h.unload();h=null;m.visible=!1;n.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;s_oStage.removeAllChildren();s_oMenu=k=null};this.refreshButtonPos=function(k,m){n.setPosition(a-k,m+c);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(b-k,m+d);h.setPosition(e-k,f-m);r.x=g+k;r.y=l+m};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCreditsBut=
function(){new CCreditsPanel};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoGame()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(b){var d,a,c,e,f,g,l=null,k,h,m,p,n,r,q,u;this._init=function(){d=0;c=a=1;u=playSound("crowd",1,-1);n=new createjs.Container;n.x=CANVAS_WIDTH/2;n.y=CANVAS_HEIGHT/2;n.scaleX=n.scaleY=.5;s_oStage.addChild(n);var b=s_oSpriteLibrary.getSprite("bg_game_"+a);r=createBitmap(b);r.regX=b.width/2;r.regY=b.height/2;n.addChild(r);h=new CGoalArea(a-1,n);var b=s_oSpriteLibrary.getSprite("ball_holder"),e=createBitmap(b);e.regX=b.width/2;e.regY=b.height/2;e.x=78;e.y=764;n.addChild(e);m=new CBall(0,
600,n);q=new CPlayer(s_oStage);g=new CInterface;g.setControlPos(a-1);p=new createjs.Shape;p.graphics.beginFill("Black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);p.alpha=0;s_oStage.addChild(p);p.on("mousedown",function(){});new CHelpPanel};this._calculateScore=function(a,b,c){var e=0;switch(c){case GREEN_TARGET:e=GREEN_AREA_POINTS;break;case YELLOW_TARGET:e=YELLOW_AREA_POINTS;break;case RED_TARGET:e=RED_AREA_POINTS}d+=e;0<e&&setTimeout(function(){new CScoreText(e,a,b,n)},500);g.refreshScore(d)};this._shiftCamera=
function(a){320<Math.abs(a)&&(a=0<a?320:-320);(new createjs.Tween.get(n)).wait(500).to({scaleX:1,scaleY:1,regX:a},2E3,createjs.Ease.cubicOut);(new createjs.Tween.get(n)).wait(500).to({regY:-200},1300,createjs.Ease.cubicOut).to({regY:-150},1600,createjs.Ease.cubicIn)};this.playerShot=function(a,b){e=a;f=b;q.startPlay()};this.launchBall=function(){c++;g.refreshShot(c);var a=h.getAreaHit(e,f);this._shiftCamera(a.x);m.launch(a.x,a.y,a.areahit,e,a.stakehit)};this.ballTouchTheTarget=function(a,b,c){h.showArea(c);
this._calculateScore(a,b,c);switch(c){case GREEN_TARGET:playSound("goal",1,0);playSound("green_area",1,0);new CScoreText(TEXT_CENTER_GREEN,a,b,n,"#17294d");break;case YELLOW_TARGET:playSound("yellow_area",1,0);new CScoreText(TEXT_CENTER_YELLOW,a,b,n,"#17294d");break;case RED_TARGET:playSound("red_area",1,0);new CScoreText(TEXT_CENTER_RED,a,b,n,"#17294d");break;case NULL_TARGET_POLE:playSound("miss_goal",1,0);new CScoreText(TEXT_CENTER_NULL,a,b,n,"#ff0000");break;case NULL_TARGET_LEFT:playSound("miss_goal",
1,0);new CScoreText(TEXT_WIDE_LEFT,a,b,n,"#ff0000");break;case NULL_TARGET_RIGHT:playSound("miss_goal",1,0),new CScoreText(TEXT_WIDE_RIGHT,a,b,n,"#ff0000")}c!==NULL_TARGET_POLE&&n.swapChildren(m.getContainer(),h.getContainer())};this.ballArrived=function(b){c>SHOTS_PER_STAGE?($(s_oMain).trigger("end_level",a),c=1,a++,a>NUM_STAGES?k.gameOver():this._changeStage()):k._resetShot();b||n.swapChildren(h.getContainer(),m.getContainer())};this._changeStage=function(){playSound("game_over",1,0);$(s_oMain).trigger("start_level",
a);(new createjs.Tween.get(p)).to({alpha:1},1E3).call(function(){h.setGoalArea(a-1);h.setAreaSprite(a-1);k._levelSet();g.resetShotsIndicator();g.stopControl();g.setControlPos(a-1);r.image=s_oSpriteLibrary.getSprite("bg_game_"+a);(new createjs.Tween.get(p)).to({alpha:0},1E3).call(function(){g.resetControl(SHOT_INDICATOR_SPEED)})})};this._resetShot=function(){h.stopAnim();(new createjs.Tween.get(n)).to({scaleX:.5,scaleY:.5,regX:0,regY:0},1E3,createjs.Ease.cubicOut).call(function(){k._levelSet()})};
this._levelSet=function(){m.reset();n.scaleX=n.scaleY=.5;n.regX=n.regY=0;var b=SHOT_INDICATOR_SPEED-c*DECREASE_SHOT_INDICATOR_SPEED;b<DECREASE_SHOT_INDICATOR_SPEED&&(b=DECREASE_SHOT_INDICATOR_SPEED);g.refreshStage(a);g.resetControl(b)};this.getStage=function(){return a};this.endGoalAnim=function(){h.stopAnim()};this.unload=function(){g.unload();null!==l&&l.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren();p.off("mousedown")};this.onExit=function(){stopSound(u);$(s_oMain).trigger("show_interlevel_ad");
$(s_oMain).trigger("end_session");this.unload();s_oMain.gotoMenu();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(new createjs.Tween.get(s_oSoundtrack)).to({volume:1},1E3)};this._onExitHelp=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(new createjs.Tween.get(s_oSoundtrack)).to({volume:0},1500);$(s_oMain).trigger("start_level",1)};this.gameOver=function(){l=CEndPanel(d);l.show()};this.restartGame=function(){k.unload();k._init()};this.update=function(){q.update()};s_oGame=this;SHOT_INDICATOR_SPEED=
b.shot_indicator_spd;DECREASE_SHOT_INDICATOR_SPEED=b.decrease_shot_indicator_spd;SHOTS_PER_STAGE=b.shots_per_stage;RED_AREA_POINTS=b.red_area_points;YELLOW_AREA_POINTS=b.yellow_area_points;GREEN_AREA_POINTS=b.green_area_points;AD_SHOW_COUNTER=b.ad_show_counter;k=this;this._init()}var s_oGame;
function CInterface(){var b,d,a,c,e,f,g,l,k,h,m;function p(a){a||(a=window.event);switch(a.keyCode){case SPACE_BAR:return C._handleClick(),a.preventDefault(),!1;case LEFT:return a.preventDefault(),!1;case UP:return a.preventDefault(),!1;case RIGHT:return a.preventDefault(),!1;case DOWN:return a.preventDefault(),!1}}var n,r,q,u,y,z,A,C,D,t,x,B,E;this._init=function(){n=!0;r=HORIZONTAL_SELECTION_STATE;var v=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-v.height/2-10;c=v.height/2+10;y=new CGfxButton(a,
c,v,s_oStage);y.addEventListener(ON_MOUSE_UP,this._onExit,this);b=CANVAS_WIDTH-v.width/2-80;d=v.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)v=s_oSpriteLibrary.getSprite("audio_icon"),u=new CToggle(b,d,v,s_bAudioActive,s_oStage),u.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);x=new CShotIndicatorController(CANVAS_WIDTH/2,300,!1);B=new CShotIndicatorController(500,CANVAS_HEIGHT/2-20,!0);s_bMobile||(document.onkeydown=p);D=new createjs.Shape;D.graphics.beginFill("Black").drawRect(0,
160,CANVAS_WIDTH,CANVAS_HEIGHT-160);D.alpha=.01;s_oStage.addChild(D);D.on("mousedown",this._handleClick,this);this.controlState();k=62;t=new createjs.Text(TEXT_STAGE+": 1"," 22px "+PRIMARY_FONT,"#17294d");t.textAlign="left";t.textBaseline="alphabetic";t.lineWidth=400;t.x=10;t.y=k;s_oStage.addChild(t);g=10;l=32;z=new createjs.Text(TEXT_SCORE+":"," 22px "+PRIMARY_FONT,"#17294d");z.y=t.y+100;z.textAlign="left";z.textBaseline="alphabetic";z.lineWidth=400;z.x=g;z.y=l;s_oStage.addChild(z);e=138;f=32;A=
new createjs.Text(0," 22px "+PRIMARY_FONT,"#17294d");A.textAlign="left";A.textBaseline="alphabetic";A.lineWidth=400;A.x=e;A.y=f;s_oStage.addChild(A);h=CANVAS_WIDTH-30;m=CANVAS_HEIGHT-30;E=new createjs.Container;E.x=h;E.y=m;s_oStage.addChild(E);var v=s_oSpriteLibrary.getSprite("ball"),w=v.width/2,C=v.height/6,v=new createjs.SpriteSheet({images:[v],framerate:30,frames:{width:w,height:C,regX:w/2,regY:C/2},animations:{"static":[0]}});q=[];for(w=0;w<SHOTS_PER_STAGE;w++)q[w]=createSprite(v,"static",0,0,
0,0),q[w].gotoAndStop("static"),q[w].scaleX=q[w].scaleY=.15,q[w].rotation=30,q[w].x=26*-w,E.addChild(q[w]);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u.unload(),u=null;D.off("mousedown");y.unload();s_oInterface=null};this._handleClick=function(a){if(!0===n)switch(r){case HORIZONTAL_SELECTION_STATE:s_oGame.endGoalAnim();x.endAnimation();r++;C.controlState();break;case VERTICAL_SELECTION_STATE:!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
createjs.Sound.play("stop_indicator"),B.endAnimation(),r++,C.controlState()}};this.controlState=function(){switch(r){case HORIZONTAL_SELECTION_STATE:x.startAnimation();break;case VERTICAL_SELECTION_STATE:B.startAnimation();break;case SHOT_SELECTION_STATE:x.hide(),B.hide(),s_oGame.playerShot(x.getCursorPosition(),B.getCursorPosition())}};this.refreshButtonPos=function(q,n){y.setPosition(a-q,n+c);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||u.setPosition(b-q,n+d);t.y=k+n;z.x=g+q;z.y=l+n;A.x=e+q;A.y=f+
n;E.x=h-q;E.y=m-n};this.refreshScore=function(a){new CRollingTextController(A,null,a,1500,EASE_CUBIC_OUT)};this.refreshStage=function(a){t.text=TEXT_STAGE+": "+a};this.refreshShot=function(a){q[SHOTS_PER_STAGE-(a-1)].visible=!1};this.resetShotsIndicator=function(){for(var a=0;a<SHOTS_PER_STAGE;a++)q[a].visible=!0};this.setControlPos=function(a){x.setPos(CANVAS_WIDTH/2+GOAL_AREA[a].x/2,CANVAS_HEIGHT/2+GOAL_AREA[a].y/2+Y_BAR_OFFSET[a],GREEN_INDICATOR_RANGE[a]);B.setPos(CANVAS_WIDTH/2+GOAL_AREA[a].x/
2+200,CANVAS_HEIGHT/2+GOAL_AREA[a].y/2,GREEN_INDICATOR_RANGE[a])};this.stopControl=function(){x.hide();x.endAnimation();B.hide();B.endAnimation()};this.resetControl=function(a){r=0;x.reset(a);B.reset(a);x.show();B.show();x.startAnimation()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){new CAreYouSurePanel(s_oStage)};s_oInterface=this;this._init();C=this;return this}var s_oInterface=null;
function CHelpPanel(){var b,d,a,c,e,f,g,l;this._init=function(){g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=.7;g.on("mousedown",this._onExitHelp);s_oStage.addChild(g);l=new createjs.Container;s_oStage.addChild(l);var f=s_oSpriteLibrary.getSprite("msg_box"),h=createBitmap(f);h.regX=f.width/2;h.regY=f.height/2;l.addChild(h);l.x=CANVAS_WIDTH/2;l.y=CANVAS_HEIGHT+f.height/2;b=l.y;(new createjs.Tween.get(l)).to({y:CANVAS_HEIGHT/2},500,createjs.Ease.quartIn).call(function(){});
f=TEXT_HELP1;s_bMobile&&(f=TEXT_HELP1_MOB);a=new createjs.Text(f," 16px "+PRIMARY_FONT,"#000000");a.x=2;a.y=-98;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=400;d=new createjs.Text(f," 16px "+PRIMARY_FONT,"#ffffff");d.x=0;d.y=-100;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=400;f=new createjs.Container;f.x=0;f.y=0;l.addChild(f);var h=s_oSpriteLibrary.getSprite("top_bar"),m=createBitmap(h);m.regX=h.width/2;m.regY=h.height/2;f.addChild(m);h=s_oSpriteLibrary.getSprite("arrow_bar");
m=createBitmap(h);m.regX=h.width/2;m.regY=h.height;m.x=-20;f.addChild(m);h=s_oSpriteLibrary.getSprite("arrow");m=createBitmap(h);m.regX=h.width/2;m.regY=5;m.x=-25;f.addChild(m);h=s_oSpriteLibrary.getSprite("arrow");m=createBitmap(h);m.regX=h.width/2;m.regY=5;m.x=25;f.addChild(m);e=new createjs.Text(TEXT_HELP2," 16px "+PRIMARY_FONT,"#000000");e.x=-198;e.y=52;e.textAlign="left";e.textBaseline="alphabetic";e.lineWidth=300;c=new createjs.Text(TEXT_HELP2," 16px "+PRIMARY_FONT,"#ffffff");c.x=-200;c.y=50;
c.textAlign="left";c.textBaseline="alphabetic";c.lineWidth=300;f=s_oSpriteLibrary.getSprite("green_area_3");f=new createjs.SpriteSheet({images:[f],frames:{width:f.width/2,height:f.height,regX:f.width/2/2,regY:f.height/2},animations:{off:[0],on:[1]}});f=new createjs.Sprite(f);f.gotoAndStop("on");f.x=160;f.y=65;f.scaleX=f.scaleY=.8;l.addChild(f);l.addChild(d,c)};this.unload=function(){s_oStage.removeChild(l);g.off("mousedown");s_oStage.removeChild(g)};this._onExitHelp=function(){(new createjs.Tween.get(g)).to({alpha:0},
500);(new createjs.Tween.get(l)).to({y:b},400,createjs.Ease.backIn).call(function(){f.unload();s_oGame._onExitHelp()})};f=this;this._init()}
function CCreditsPanel(){var b,d,a,c,e;this._init=function(){d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;d.on("mousedown",function(){});s_oStage.addChild(d);(new createjs.Tween.get(d)).to({alpha:.7},500);a=new createjs.Container;s_oStage.addChild(a);var f=s_oSpriteLibrary.getSprite("msg_box"),g=createBitmap(f);g.regX=f.width/2;g.regY=f.height/2;a.addChild(g);a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT+f.height/2;b=a.y;(new createjs.Tween.get(a)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.quartIn);g=new createjs.Text("DEVELOPED BY"," 20px "+PRIMARY_FONT,"#ffffff");g.y=-f.height/2+60;g.textAlign="center";g.textBaseline="middle";g.lineWidth=300;a.addChild(g);f=new createjs.Text("www.codethislab.com"," 20px "+PRIMARY_FONT,"#ffffff");f.y=70;f.textAlign="center";f.textBaseline="middle";f.lineWidth=300;a.addChild(f);f=s_oSpriteLibrary.getSprite("ctl_logo");e=createBitmap(f);e.on("mousedown",this._onLogoButRelease);e.regX=f.width/2;e.regY=f.height/2;a.addChild(e);
f=s_oSpriteLibrary.getSprite("but_exit");c=new CGfxButton(193,-90,f,a);c.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){c.setClickable(!1);(new createjs.Tween.get(d)).to({alpha:0},500);(new createjs.Tween.get(a)).to({y:b},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(d);s_oStage.removeChild(a);c.unload()});d.off("mousedown",function(){});e.off("mousedown",this._onLogoButRelease)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};
this._onMoreGamesReleased=function(){window.open("http://codecanyon.net/collections/5409142-games")};this._init()}
function CAreYouSurePanel(){var b,d,a,c,e,f;this._init=function(){c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;c.on("mousedown",function(){});s_oStage.addChild(c);(new createjs.Tween.get(c)).to({alpha:.7},500);e=new createjs.Container;s_oStage.addChild(e);var f=s_oSpriteLibrary.getSprite("msg_box"),l=createBitmap(f);l.regX=f.width/2;l.regY=f.height/2;e.addChild(l);e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT+f.height/2;b=e.y;(new createjs.Tween.get(e)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.quartIn);l=new createjs.Text(TEXT_ARE_SURE,"bold 34px "+PRIMARY_FONT,"#ffffff");l.y=-f.height/2+60;l.textAlign="center";l.textBaseline="middle";l.lineWidth=400;e.addChild(l);d=new CGfxButton(110,60,s_oSpriteLibrary.getSprite("but_yes_big"),e);d.addEventListener(ON_MOUSE_UP,this._onButYes,this);a=new CGfxButton(-110,60,s_oSpriteLibrary.getSprite("but_exit_big"),e);a.addEventListener(ON_MOUSE_UP,this._onButNo,this);a.pulseAnimation()};this._onButYes=function(){a.setClickable(!1);
d.setClickable(!1);(new createjs.Tween.get(c)).to({alpha:0},500);(new createjs.Tween.get(e)).to({y:b},400,createjs.Ease.backIn).call(function(){f.unload();s_oGame.onExit()})};this._onButNo=function(){a.setClickable(!1);d.setClickable(!1);(new createjs.Tween.get(c)).to({alpha:0},500);(new createjs.Tween.get(e)).to({y:b},400,createjs.Ease.backIn).call(function(){f.unload()})};this.unload=function(){a.unload();d.unload();s_oStage.removeChild(c);s_oStage.removeChild(e);c.off("mousedown",function(){})};
f=this;this._init()}
function CEndPanel(b){var d,a,c,e,f,g;this._init=function(b){a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=0;a.on("mousedown",function(){});s_oStage.addChild(a);(new createjs.Tween.get(a)).to({alpha:.7},500);c=new createjs.Container;s_oStage.addChild(c);var g=s_oSpriteLibrary.getSprite("msg_box"),h=createBitmap(g);h.regX=g.width/2;h.regY=g.height/2;c.addChild(h);c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT+g.height/2;d=c.y;(new createjs.Tween.get(c)).to({y:CANVAS_HEIGHT/2},
500,createjs.Ease.quartIn);h=new createjs.Text(TEXT_GAMEOVER," 26px "+PRIMARY_FONT,"#ffffff");h.y=-g.height/2+50;h.textAlign="center";h.textBaseline="middle";h.lineWidth=400;c.addChild(h);$(s_oMain).trigger("save_score",b);$(s_oMain).trigger("share_event",b);b=new createjs.Text(TEXT_TOTAL_SCORE+" "+b," 20px "+PRIMARY_FONT,"#ffffff");b.y=h.y+40;b.textAlign="center";b.textBaseline="middle";b.lineWidth=500;c.addChild(b);g=s_oSpriteLibrary.getSprite("but_home");e=new CGfxButton(-120,60,g,c);e.addEventListener(ON_MOUSE_UP,
this._onExit,this);g=s_oSpriteLibrary.getSprite("but_restart");f=new CGfxButton(120,60,g,c);f.addEventListener(ON_MOUSE_UP,this._onRestart,this);f.pulseAnimation()};this.unload=function(){s_oStage.removeChild(c);a.off("mousedown",function(){});e.unload();f.unload()};this.show=function(a){playSound("game_over",1,0)};this._onExit=function(){a.off("mousedown",function(){});s_oStage.removeChild(c);s_oGame.onExit()};this._onRestart=function(){(new createjs.Tween.get(a)).to({alpha:0},500);(new createjs.Tween.get(c)).to({y:d},
400,createjs.Ease.backIn).call(function(){g.unload();s_oGame.restartGame()})};g=this;this._init(b);return this}
function CShotIndicatorController(b,d,a){var c,e,f=!0,g,l,k,h,m,p,n,r;this.init=function(a,b,d){h=new createjs.Container;h.x=a;h.y=b;s_oStage.addChild(h);g=d;!1===d?(a=s_oSpriteLibrary.getSprite("top_bar"),m=createBitmap(a),m.regX=a.width/2,m.regY=a.height/2,h.addChild(m),c=-a.width/2+4,e=a.width/2-4,k=e-c,a=s_oSpriteLibrary.getSprite("arrow_bar"),p=createBitmap(a),p.regX=a.width/2,p.regY=a.height/2+20,p.x=c,h.addChild(p),a=s_oSpriteLibrary.getSprite("arrow"),n=createBitmap(a),n.regX=a.width/2,n.regY=
5,h.addChild(n),a=s_oSpriteLibrary.getSprite("arrow"),r=createBitmap(a),r.regX=a.width/2,r.regY=5):(a=s_oSpriteLibrary.getSprite("right_bar"),m=createBitmap(a),m.regX=a.width/2,m.regY=a.height/2,h.addChild(m),c=-a.height/2+1,e=a.height/2-6,k=e-c,a=s_oSpriteLibrary.getSprite("arrow_bar"),p=createBitmap(a),p.regX=a.width/2,p.regY=a.height/2+20,p.y=c,p.rotation=90,h.addChild(p),a=s_oSpriteLibrary.getSprite("arrow"),n=createBitmap(a),n.regX=a.width/2,n.regY=4,n.rotation=90,h.addChild(n),a=s_oSpriteLibrary.getSprite("arrow"),
r=createBitmap(a),r.regX=a.width/2,r.regY=4,r.rotation=90);h.addChild(r);this.reset(SHOT_INDICATOR_SPEED)};this.reset=function(a){l=a;g?p.y=c:p.x=c};this.show=function(){f=!0;h.visible=f};this.hide=function(){f=!1;h.visible=f};this.getCursorPosition=function(){return g?(p.y-c)/(e-c)*2-1:(p.x-c)/(e-c)*2-1};this.startAnimation=function(){g?(new createjs.Tween.get(p,{loop:!0})).to({y:c+.5*k},l/2,createjs.Ease.cubicIn).to({y:e},.5*l,createjs.Ease.cubicOut).to({y:c+.5*k},l/2,createjs.Ease.cubicIn).to({y:c},
.5*l,createjs.Ease.cubicOut):(new createjs.Tween.get(p,{loop:!0})).to({x:c+.5*k},l/2,createjs.Ease.cubicIn).to({x:e},.5*l,createjs.Ease.cubicOut).to({x:c+.5*k},l/2,createjs.Ease.cubicIn).to({x:c},.5*l,createjs.Ease.cubicOut)};this.setPos=function(b,c,e){h.x=b;h.y=c;a?(n.y=e.vert.top,r.y=e.vert.bot):(n.x=e.horiz.left,r.x=e.horiz.right)};this.endAnimation=function(){new createjs.Tween.removeTweens(p)};this.init(b,d,a)}
function CVector2(b,d){var a,c;this._init=function(b,d){a=b;c=d};this.add=function(b,d){a+=b;c+=d};this.addV=function(b){a+=b.getX();c+=b.getY()};this.scalarDivision=function(b){a/=b;c/=b};this.subV=function(b){a-=b.getX();c-=b.getY()};this.scalarProduct=function(b){a*=b;c*=b};this.invert=function(){a*=-1;c*=-1};this.dotProduct=function(b){return a*b.getX()+c*b.getY()};this.set=function(b,d){a=b;c=d};this.setV=function(b){a=b.getX();c=b.getY()};this.length=function(){return Math.sqrt(a*a+c*c)};this.length2=
function(){return a*a+c*c};this.normalize=function(){var b=this.length();0<b&&(a/=b,c/=b)};this.getNormalize=function(b){this.length();b.set(a,c);b.normalize()};this.rot90CCW=function(){var b=a;a=-c;c=b};this.rot90CW=function(){var b=a;a=c;c=-b};this.getRotCCW=function(b){b.set(a,c);b.rot90CCW()};this.getRotCW=function(b){b.set(a,c);b.rot90CW()};this.ceil=function(){a=Math.ceil(a);c=Math.ceil(c)};this.round=function(){a=Math.round(a);c=Math.round(c)};this.toString=function(){return"Vector2: "+a+", "+
c};this.print=function(){trace("Vector2: "+a+", "+c+"")};this.getX=function(){return a};this.getY=function(){return c};this._init(b,d)}
function CGoalArea(b,d){var a,c,e,f,g,l,k,h,m,p,n,r;this._init=function(b,c){a=b;e=new createjs.Container;c.addChild(e);r=new createjs.Container;c.addChild(r);this.setGoalArea(a);this.setAreaSprite(a)};this.unload=function(){d.removeChild(e);d.removeChild(r)};this.setGoalArea=function(b){a=b;e.removeAllChildren();r.removeAllChildren();d.removeChild(n);e.x=GOAL_AREA[a].x;e.y=GOAL_AREA[a].y;f=new createjs.Shape;f.graphics.beginFill("rgba(0,255,255,0.5)").drawRect(-GOAL_AREA[a].width/2,-GOAL_AREA[a].height/
2,GOAL_AREA[a].width,GOAL_AREA[a].height)};this.setAreaSprite=function(){var b=a+1,c=s_oSpriteLibrary.getSprite("green_area_"+b),c={images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2+TARGET_AREA_SPRITE_OFFSET[a].green.x,regY:c.height/2+TARGET_AREA_SPRITE_OFFSET[a].green.y},animations:{off:[0],on:[1]}},c=new createjs.SpriteSheet(c);k=new createjs.Sprite(c);e.addChild(k);p=new createjs.Sprite(c);p.gotoAndStop("on");p.alpha=0;e.addChild(p);c=s_oSpriteLibrary.getSprite("yellow_area_"+
b);c={images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2+TARGET_AREA_SPRITE_OFFSET[a].yellow.x,regY:c.height/2+TARGET_AREA_SPRITE_OFFSET[a].yellow.y},animations:{off:[0],on:[1]}};c=new createjs.SpriteSheet(c);l=new createjs.Sprite(c);e.addChild(l);m=new createjs.Sprite(c);m.gotoAndStop("on");m.alpha=0;e.addChild(m);c=s_oSpriteLibrary.getSprite("red_area_"+b);c={images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{off:[0],on:[1]}};c=new createjs.SpriteSheet(c);
g=new createjs.Sprite(c);e.addChild(g);h=new createjs.Sprite(c);h.gotoAndStop("on");h.alpha=0;e.addChild(h);this._stakeArea();this.animateArea()};this._stakeArea=function(){var b=new createjs.Shape;b.graphics.setStrokeStyle(50);b.graphics.beginStroke("rgba(255,255,255,0.01)");b.graphics.moveTo(STAKE_POS[a][0].x,STAKE_POS[a][0].y);for(var c=1;c<STAKE_POS[a].length;c++)b.graphics.lineTo(STAKE_POS[a][c].x,STAKE_POS[a][c].y);r.addChild(b);b=s_oSpriteLibrary.getSprite("post_"+(a+1));n=createBitmap(b);
n.regX=b.width/2;n.regY=b.height/2;n.x=POST_POS[a].x-GOAL_AREA[a].x;n.y=POST_POS[a].y-GOAL_AREA[a].y;e.addChild(n)};this.getAreaHit=function(b,c){var d=GOAL_AREA[a].x+b*GOAL_AREA[a].width/2,e=GOAL_AREA[a].y+c*GOAL_AREA[a].height/2;if(r.hitTest(d,e))return{x:d,y:e,areahit:NULL_TARGET_POLE,stakehit:!0};var f=b*GOAL_AREA[a].width/2,h=c*GOAL_AREA[a].height/2,f=k.hitTest(f,h)?GREEN_TARGET:l.hitTest(f,h)?YELLOW_TARGET:g.hitTest(f,h)?RED_TARGET:0>b?NULL_TARGET_LEFT:NULL_TARGET_RIGHT;return{x:d,y:e,areahit:f,
stakehit:!1}};this.showArea=function(a){switch(a){case GREEN_TARGET:(new createjs.Tween.get(p)).to({alpha:.8},100).to({alpha:0},100).to({alpha:1},50);break;case YELLOW_TARGET:(new createjs.Tween.get(m)).to({alpha:.8},100).to({alpha:0},100).to({alpha:1},50);break;case RED_TARGET:(new createjs.Tween.get(h)).to({alpha:.8},100).to({alpha:0},100).to({alpha:1},50)}};this.getGlobalPos=function(){return d.localToGlobal(e.x,e.y)};this.animateArea=function(){this._anim3(1500)};this._anim=function(a){(new createjs.Tween.get(h)).to({alpha:1},
a).call(function(){(new createjs.Tween.get(m)).to({alpha:1},a);(new createjs.Tween.get(h)).to({alpha:0},a).call(function(){(new createjs.Tween.get(p)).to({alpha:1},a);(new createjs.Tween.get(m)).to({alpha:0},a).call(function(){(new createjs.Tween.get(p)).to({alpha:0},a);c._anim(a)})})})};this._anim2=function(a){(new createjs.Tween.get(h)).to({alpha:1},a).to({alpha:0},a);(new createjs.Tween.get(m)).wait(a/2).to({alpha:1},a).to({alpha:0},a);(new createjs.Tween.get(p)).wait(a).to({alpha:1},a).to({alpha:0},
a).call(function(){c._anim2(a)})};this._anim3=function(a){(new createjs.Tween.get(h)).to({alpha:1},a,createjs.Ease.cubicOut).to({alpha:0},a,createjs.Ease.cubicIn);(new createjs.Tween.get(m)).wait(a/2).to({alpha:1},a,createjs.Ease.cubicOut).to({alpha:0},a,createjs.Ease.cubicIn);(new createjs.Tween.get(p)).wait(a).to({alpha:1},a,createjs.Ease.cubicOut).to({alpha:0},a,createjs.Ease.cubicIn).call(function(){c._anim2(a)})};this.stopAnim=function(){(new createjs.Tween.get(h,{override:!0})).to({alpha:0},
800);(new createjs.Tween.get(m,{override:!0})).to({alpha:0},800);(new createjs.Tween.get(p,{override:!0})).to({alpha:0},800)};this.getContainer=function(){return e};c=this;this._init(b,d)}
function CBall(b,d,a){var c,e,f,g;this._init=function(a,b,d){c=2;e=new createjs.Container;e.x=a;e.y=b;d.addChild(e);a=s_oSpriteLibrary.getSprite("ball");b=a.width/2;d=a.height/6;a=new createjs.SpriteSheet({images:[a],framerate:30,frames:{width:b,height:d,regX:b/2,regY:d/2},animations:{launch:[0,11,"launch"]}});f=createSprite(a,"launch",0,0,0,0);f.gotoAndStop("launch");e.addChild(f)};this.unload=function(){a.removeChild(e)};this.launch=function(a,b,c,d,p){f.gotoAndPlay("launch");f.framerate=30;var n=
BALL_FLYTIME;d*=BALL_MAX_ROTATION;(new createjs.Tween.get(e)).to({rotation:d},n,createjs.Ease.cubicOut);(new createjs.Tween.get(e)).to({x:a},n,createjs.Ease.cubicOut);(new createjs.Tween.get(e)).to({y:b},.5*n,createjs.Ease.cubicOut).call(function(){p?(new createjs.Tween.removeTweens(e),f.framerate=10,s_oGame.ballTouchTheTarget(e.x,e.y,c),(new createjs.Tween.get(e)).to({y:b+400,alpha:0},.5*n,createjs.Ease.cubicIn),(new createjs.Tween.get(e)).to({scaleX:e.scaleX+.1,scaleY:e.scaleY+.1},.5*n).wait(1E3).call(function(){s_oGame.ballArrived(p);
new createjs.Tween.removeTweens(e);f.gotoAndStop("launch")})):((new createjs.Tween.get(e)).to({y:b+200,alpha:0},.5*n,createjs.Ease.cubicIn),s_oGame.ballTouchTheTarget(e.x,e.y,c),c>NULL_TARGET_POLE&&g._waveAnimation(e.x,e.y))});(new createjs.Tween.get(e)).to({scaleX:.02,scaleY:.02},n,createjs.Ease.cubicOut).wait(1E3).call(function(){s_oGame.ballArrived();new createjs.Tween.removeTweens(e);f.gotoAndStop("launch")})};this.reset=function(){e.alpha=1;e.scaleX=e.scaleY=1;e.rotation=0;e.x=b;e.y=d};this._waveAnimation=
function(a,b){0===c?c=2:(this.spawnWave(a,b),setTimeout(function(){g._waveAnimation(a,b)},200))};this.spawnWave=function(b,d){c--;var e=new createjs.Shape;e.graphics.setStrokeStyle(3);e.graphics.beginStroke("rgba(255,255,255,1)").drawCircle(b,d,1);a.addChild(e);(new createjs.Tween.get(e.graphics.command)).to({radius:50},1E3,createjs.Ease.cubicOut);(new createjs.Tween.get(e)).to({alpha:0},1E3,createjs.Ease.cubicOut).call(function(){a.removeChild(e)})};this.getContainer=function(){return e};g=this;
this._init(b,d,a)}
function CPlayer(b){var d,a,c,e,f;this._init=function(b){a=d=!1;c=0;f=new createjs.Container;f.y=CANVAS_HEIGHT;b.addChild(f);e=[];for(b=0;37>=b;b++){var l=s_oSpriteLibrary.getSprite("player_"+b);e[b]=createBitmap(l);e[b].regY=l.height;e[b].visible=!1;f.addChild(e[b])}};this.unload=function(){b.removeChild(f)};this.fade=function(){(new createjs.Tween.get(f)).to({alpha:0},800)};this.startPlay=function(){f.alpha=1;d=!0;a=!1};this._playShot=function(){0!==c&&(e[c-1].visible=!1);e[c].visible=!0;c++;12<=
c&&!a&&(a=!0,playSound("kick",1,0),s_oGame.launchBall(),this.fade());37<c&&(e[c-1].visible=!1,c=0,d=!1)};this.update=function(){d&&this._playShot()};this._init(b)}
function CScoreText(b,d,a,c,e){var f;this._init=function(a,b,c,d){f=new createjs.Text("00000"," 30px "+PRIMARY_FONT,"#17294d");f.textAlign="center";f.text=0<=a?"+"+a:a;f.color=e;f.x=b;f.y=c;f.alpha=0;f.shadow=new createjs.Shadow("#ffffff",2,2,2);d.addChild(f);var m=this;createjs.Tween.get(f).to({alpha:1},400,createjs.Ease.quadIn).call(function(){m.moveUp()})};this.moveUp=function(){var a=f.y-100,b=this;createjs.Tween.get(f).to({y:a},1E3,createjs.Ease.sineIn).call(function(){b.unload()});createjs.Tween.get(f).wait(500).to({alpha:0},
500)};this.unload=function(){c.removeChild(f)};this._init(b,d,a,c)};
