function CBlock(a,f,b){var c,e,d,g,k,h=!1;this._init=function(a,b,f){g=[];c=new createjs.Container;c.x=a;c.y=b;e=new CVerticalRect(CANVAS_WIDTH-WIDTH_OF_VERTICAL_RECT-EDGEBOARD_X+OFFSET_LEFT_VERTICAL_POS,0,c,VERTICAL_RECT_STYLE_BLOCK[f].right);d=new CVerticalRect(EDGEBOARD_X,0,c,VERTICAL_RECT_STYLE_BLOCK[f].left);for(a=0;a<SUB_COLUMN;a++)g[a]=new CHorizontalRect(EDGEBOARD_X+WIDTH_OF_VERTICAL_RECT+WIDTH_OF_HORIZONTAL_RECT*a,0,c,HORIZONTAL_RECT_STYLE_BLOCK[f][a]);SHOW_ID_BLOCK&&(f=new createjs.Text(f,
"40px "+FONT_GAME,"#ffffff"),f.x=EDGEBOARD_X+.5*WIDTH_OF_VERTICAL_RECT,f.y=10,f.textAlign="center",c.addChild(f));s_oStage.addChild(c);s_oStage.setChildIndex(c,5)};this.setY=function(a){c.y=a};this.getY=function(){return c.y};this.getCollisionOfAHorizontalRect=function(a){return g[a].getCollision()};this.setCollisionOfAHorizontalRect=function(a,b){g[a].setCollision(b);k=a};this.getPrevHorRectColFalse=function(){return k};this.resetPrevHorRectCollision=function(){g[k].setCollision(!0)};this.getPositionOfAHorizontalRect=
function(a){return g[a].getPosition()};this.getCollisionOfVericalRects=function(){return{left:d.getCollision(),right:e.getCollision()}};this.getPositionOfVerticalRects=function(){return{left:d.getPosition(),right:e.getPosition()}};this.unload=function(){s_oStage.removeChild(c);c=null};this.setCollisionOfVerticalRects=function(a){d.setCollision(a);e.setCollision(a)};this.getToken=function(){return h};this.setToken=function(a){h=a};this.getYContainer=function(){return c.y};this.update=function(){c.y+=
s_iSpeedBlock;e.update();d.update()};this._init(a,f,b)}
function CControlMobile(a,f){var b,c,e,d=!1;this._init=function(a){b=[];c=[];e=a;d=f;s_oStage.on("mousedown",this.onPressStart);s_oStage.on("pressup",this.onPressRelease)};this.unload=function(){s_oStage.removeAllEventListeners("mousedown");s_oStage.removeAllEventListeners("pressup")};this.addEventListener=function(a,d,e){b[a]=d;c[a]=e};this.onPressRelease=function(){b[ON_MOUSE_UP]&&b[ON_MOUSE_UP].call(c[ON_MOUSE_UP])};this.block=function(a){d=a};this.onPressStart=function(a){d||(!0===e?a.stageX<
.5*CANVAS_WIDTH&&b[ON_MOUSE_DOWN]&&b[ON_MOUSE_DOWN].call(c[ON_MOUSE_DOWN]):!1===e&&a.stageX>.5*CANVAS_WIDTH&&b[ON_MOUSE_DOWN]&&b[ON_MOUSE_DOWN].call(c[ON_MOUSE_DOWN]))};this._init(a);return this}
function CEndPanel(a){var f,b,c,e,d,g,k,h;this._init=function(a){f=createBitmap(a);d=new createjs.Text("","60px "+FONT_GAME,"#000");d.x=CANVAS_WIDTH/2+1;d.y=CANVAS_HEIGHT/2-160;d.textAlign="center";e=new createjs.Text("","60px "+FONT_GAME,"#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-162;e.textAlign="center";b=new createjs.Text("","40px "+FONT_GAME,"#000");b.x=CANVAS_WIDTH/2+1;b.y=CANVAS_HEIGHT/2-80;b.textAlign="center";c=new createjs.Text("","40px "+FONT_GAME,"#ffffff");c.x=CANVAS_WIDTH/2;c.y=
CANVAS_HEIGHT/2-78;c.textAlign="center";g=new createjs.Container;g.alpha=0;g.visible=!1;g.addChild(f,b,c,d,e);s_oStage.addChild(g)};this.show=function(a){playSound("game_over",1,0);d.text=TEXT_GAMEOVER;e.text=TEXT_GAMEOVER;b.text=TEXT_SCORE+": "+a;c.text=TEXT_SCORE+": "+a;g.visible=!0;var f=this;createjs.Tween.get(g).to({alpha:1},500).call(function(){var a=s_oSpriteLibrary.getSprite("but_restart");k=new CGfxButton(.5*CANVAS_WIDTH+100,.5*CANVAS_HEIGHT+75,a,!0);k.addEventListener(ON_MOUSE_DOWN,f._onRestart,
this);a=s_oSpriteLibrary.getSprite("but_home");h=new CGfxButton(.5*CANVAS_WIDTH-100,.5*CANVAS_HEIGHT+75,a,!0);h.addEventListener(ON_MOUSE_DOWN,f._onExit,this)});$(s_oMain).trigger("save_score",a);$(s_oMain).trigger("share_event",a)};this._onExit=function(){s_oStage.removeChild(g);s_oEndPanel.unload();$(s_oMain).trigger("show_interlevel_ad");s_oGame.onExit()};this.unload=function(){h.unload();h=null;k.unload();s_oEndPanel=h=null};this._onRestart=function(){createjs.Tween.get(g).to({alpha:0},300).call(function(){!0===
s_bMobile&&s_oGame.createControl(!1);s_oStage.removeChild(g)});s_oEndPanel.unload();s_oGame.onRestart();$(s_oMain).trigger("show_interlevel_ad")};this._init(a);s_oEndPanel=this;return this}var s_oEndPanel;
function CGame(a){function f(a){!1!==c&&(e=!1,h.stop())}function b(a){if(!1===c||e)return a.preventDefault(),!1;a||(a=window.event);switch(a.keyCode){case 37:e=!0;s_oGame.onLeft();break;case 39:e=!0,s_oGame.onRight()}a.preventDefault();return!1}var c=!1,e=!1,d,g,k,h,m,p,n,l,t,y=null,v,x,u,w,q,r;this._init=function(){d=0;setVolume(s_oSoundTrack,.4);g=new CScrollingMultipleBg([s_oSpriteLibrary.getSprite("parallax_1_1"),s_oSpriteLibrary.getSprite("parallax_1_2"),s_oSpriteLibrary.getSprite("parallax_1_3")]);
k=new CScrollingBg(s_oSpriteLibrary.getSprite("parallax_2"));n=.5*WIDTH_OF_HORIZONTAL_RECT;p=[];l=[];for(var a=w=0;a<SUB_COLUMN;a++)p[a]=new createjs.Point(WIDTH_OF_VERTICAL_RECT+EDGEBOARD_X+n+WIDTH_OF_HORIZONTAL_RECT*a,0),!0===SHOW_DEBUG_COLUMN&&this.createDebugColumn(a);s_iSpeedBlock=SPEED_BLOCKS;u=0;x=!1;this.createBlocks();a=s_oSpriteLibrary.getSprite("hero");h=new CHero(HERO_START_X,CANVAS_HEIGHT-300,a);m=new createjs.Shape;m.graphics.beginFill("red").drawRect(.5*-DISPLAY_SHOCK_X,.5*-DISPLAY_SHOCK_Y,
CANVAS_WIDTH+DISPLAY_SHOCK_X,CANVAS_HEIGHT+DISPLAY_SHOCK_Y);m.alpha=.1;m.visible=!1;v=0;s_oStage.addChild(m);t=new CInterface;!1===s_bMobile?(document.onkeydown=b,document.onkeyup=f):this.createControl(!1)};this.unload=function(){c=!1;r&&(r.unload(),r=null);q&&(q.unload(),q=null);s_oStage.removeAllChildren();h.unload();t.unload()};this.createControl=function(a){q=new CControlMobile(!0,a);q.addEventListener(ON_MOUSE_DOWN,this.onLeft,this);q.addEventListener(ON_MOUSE_UP,this.onKeyReleased,this);r=new CControlMobile(!1,
a);r.addEventListener(ON_MOUSE_DOWN,this.onRight,this);r.addEventListener(ON_MOUSE_UP,this.onKeyReleased,this)};this.onRestart=function(){for(var a=0;a<l.length;a++)l[a].unload();l=[];$(s_oMain).trigger("restart_level",1);u=0;x=!1;v=0;this.createBlocks();h.stop();h.setX(HERO_START_X);h.setVisible(!0);d=0;t.refreshScore(d);t.showArrowButs();c=!0;s_iSpeedBlock=SPEED_BLOCKS};this.createBlocks=function(){l[0]=new CBlock(0,-HEIGHT_OF_VERTICAL_RECT,0);var a=Math.floor(Math.random()*SUB_COLUMN);l[0].setCollisionOfAHorizontalRect(a,
!1);for(var b=1;b<BLOCK_FOR_SCREEN;b++){l[b]=new CBlock(0,-HEIGHT_OF_VERTICAL_RECT*(b+1),b);for(var d=l[b-1].getPrevHorRectColFalse(),c=d+2,e=d-2,a=Math.floor(Math.random()*(c-e))+e;a===d;)a=Math.floor(Math.random()*(c-e))+e;0>a?(l[b].setCollisionOfVerticalRects(!1),d===SUB_COLUMN-1?(c=SUB_COLUMN-1,e=SUB_COLUMN-2,a=Math.floor(Math.random()*(c-e))+e):a=SUB_COLUMN-1):a>SUB_COLUMN-1&&(l[b].setCollisionOfVerticalRects(!1),0===d?(c=1,e=0,a=Math.floor(Math.random()*(c-e))+e):a=0);l[b].setCollisionOfAHorizontalRect(a,
!1)}};this._lostLife=function(){m.visible=!0;var a=this;createjs.Tween.get(m).to({alpha:.6},400).call(function(){a._resetHurt()});this.displayShock();c=!1;h.gameOver()};this.gameOver=function(){$(s_oMain).trigger("end_level",1);y=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));y.show(d);s_bMobile&&(q.unload(),r.unload(),q=r=null)};this._resetHurt=function(){m.visible=!1;m.alpha=.5};this.onLeft=function(){h.moveLeft();playSound("spaceship_whoosh",.7,0)};this.onRight=function(){h.moveRight();playSound("spaceship_whoosh",
1,0)};this.onKeyReleased=function(){h.stop()};this.onExit=function(){this.unload();$(s_oMain).trigger("share_event",d);$(s_oMain).trigger("end_session");setVolume(s_oSoundTrack,1);s_oMain.gotoMenu()};this._onExitHelp=function(){t.onExitFromHelp();c=!0;$(s_oMain).trigger("start_level",1)};this._updateParallaxes=function(){g.update(PARALLAX1_SPEED);k.update(PARALLAX2_SPEED)};this.heroColumn=function(a){h.getX()>p[a].x-n&&h.getX()};this.displayShock=function(){var a=DISPLAY_SHOCK_X,b=DISPLAY_SHOCK_Y;
createjs.Tween.get(s_oStage).to({x:Math.round(Math.random()*a),y:Math.round(Math.random()*b)},40).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(Math.random()*a*.8),y:-Math.round(Math.random()*b*.8)},40).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(Math.random()*a*.6),y:Math.round(Math.random()*b*.6)},40).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(Math.random()*a*.4),y:-Math.round(Math.random()*b*.4)},40).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(Math.random()*
a*.2),y:Math.round(Math.random()*b*.2)},40).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(Math.random()*a),y:-Math.round(Math.random()*b)},40).call(function(){createjs.Tween.get(s_oStage).to({y:0,x:0},50).call(function(){})})})})})})})};this.blockPositionCheck=function(a){l[a].getY()>CANVAS_HEIGHT&&this.randomAperture(a)};this.randomAperture=function(a){for(var b=l[0].getY(),d=0;d<l.length;d++)b>l[d].getY()&&(b=l[d].getY());l[a].setY(b-HEIGHT_OF_VERTICAL_RECT);l[a].resetPrevHorRectCollision();
l[a].setCollisionOfVerticalRects(!0);for(var b=0>=a?l[BLOCK_FOR_SCREEN-1].getPrevHorRectColFalse():l[a-1].getPrevHorRectColFalse(),d=b+2,c=b-2,e=Math.floor(Math.random()*(d-c))+c;e===b;)e=Math.floor(Math.random()*(d-c))+c;0>e?(l[a].setCollisionOfVerticalRects(!1),b===SUB_COLUMN-1?(d=SUB_COLUMN-1,c=SUB_COLUMN-2,e=Math.floor(Math.random()*(d-c))+c):e=SUB_COLUMN-1):e>SUB_COLUMN-1&&(l[a].setCollisionOfVerticalRects(!1),0===b?(c=0,e=Math.floor(Math.random()*(1-c))+c):e=0);l[a].setCollisionOfAHorizontalRect(e,
!1);l[a].setToken(!1)};this.collisionBetweenHeroAndHorRect=function(a){for(var b=h.getPos(),c=h.getCollision(),e=c.height+HEIGHT_OF_HORIZONTAL_RECT,g=c.width+WIDTH_OF_HORIZONTAL_RECT,f=0;f<SUB_COLUMN;f++){var k=l[a].getPositionOfAHorizontalRect(f);if(b.x>k.x-c.width&&b.x<k.x+g&&b.y>l[a].getYContainer()-c.height&&b.y<l[a].getYContainer()+e)if(l[a].getCollisionOfAHorizontalRect(f)){this._lostLife();break}else if(!1===l[a].getToken()){d+=SCORE_HIT;t.refreshScore(d);l[a].setToken(!0);this.speedUp();w=
a;u=TIME_TRANSICTION;x=!0;break}}1===a&&t.hideArrowButs()};this.speedUp=function(){s_iSpeedBlock+=VELOCITY_INCREASE;s_iSpeedBlock>MAX_SPEED&&(s_iSpeedBlock=MAX_SPEED)};this.createDebugColumn=function(a){var b=new createjs.Shape;0===a%2?b.graphics.beginFill("#aa0000").drawRect(WIDTH_OF_VERTICAL_RECT+EDGEBOARD_X+WIDTH_OF_HORIZONTAL_RECT*a,0,WIDTH_OF_HORIZONTAL_RECT,CANVAS_HEIGHT):b.graphics.beginFill("#0000aa").drawRect(WIDTH_OF_VERTICAL_RECT+EDGEBOARD_X+WIDTH_OF_HORIZONTAL_RECT*a,0,WIDTH_OF_HORIZONTAL_RECT,
CANVAS_HEIGHT);s_oStage.addChild(b)};this.changeTransiction=function(){x=!1;w<BLOCK_FOR_SCREEN-1?v++:v=0};this.collisionBetweenHeroAndVertRect=function(a){var b=h.getPos(),c=h.getCollision(),d=l[a].getCollisionOfVericalRects(),d=!0===d.left&&!0===d.right?c.height+HEIGHT_OF_VERTICAL_RECT:c.height+MASK_VERTICAL_RECT_HEIGHT,e=c.width+WIDTH_OF_VERTICAL_RECT,g=l[a].getPositionOfVerticalRects(),f=g.left,g=g.right;b.x>f.x-c.width&&b.x<f.x+e&&b.y>l[a].getYContainer()-c.height&&b.y<l[a].getYContainer()+d?
this._lostLife():b.x>g.x-c.width&&b.x<g.x+e&&b.y>l[a].getYContainer()-c.height&&b.y<l[a].getYContainer()+d&&this._lostLife()};this.teleportToOtherHand=function(){h.getX()<TELEPORT_OFFSET_LEFT?h.setX(TELEPORT_OFFSET_RIGHT-2):h.getX()>TELEPORT_OFFSET_RIGHT&&h.setX(TELEPORT_OFFSET_LEFT+2)};this.update=function(){if(c){h.update();for(var a=0;a<p.length;a++)this.heroColumn(a);for(a=0;a<l.length;a++)this.blockPositionCheck(a),l[a].update();this.collisionBetweenHeroAndHorRect(v);this.collisionBetweenHeroAndVertRect(v);
this.teleportToOtherHand();this._updateParallaxes();0<u?u-=1/createjs.Ticker.framerate:x&&this.changeTransiction()}};s_oGame=this;HERO_ACCELLERATION=a.hero_accelleration;HERO_FRICTION=a.hero_friction;HERO_SPEED=a.hero_speed;SPEED_BLOCKS=a.starting_bg_speed;MAX_SPEED=a.max_bg_speed;SCORE_HIT=a.score_hit;POINT_DIFFICULT_INCREASE=a.point_to_next_difficult;VELOCITY_INCREASE=a.velocity_increase;this._init()}var s_oGame;
function CGfxButton(a,f,b){var c,e,d;this._init=function(a,b,f){c=[];e=[];d=createBitmap(f);d.x=a;d.y=b;d.regX=f.width/2;d.regY=f.height/2;s_bMobile||(d.cursor="pointer");s_oStage.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);s_oStage.removeChild(d)};this.setVisible=function(a){d.visible=a};this.setCursorType=function(a){d.cursor=a};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease)};
this.addEventListener=function(a,b,d){c[a]=b;e[a]=d};this.buttonRelease=function(){d.scaleX=1;d.scaleY=1;playSound("click",1,0);c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(e[ON_MOUSE_UP])};this.buttonDown=function(){d.scaleX=.9;d.scaleY=.9;c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN])};this.setPosition=function(a,b){d.x=a;d.y=b};this.setX=function(a){d.x=a};this.setY=function(a){d.y=a};this.getButtonImage=function(){return d};this.getX=function(){return d.x};this.getY=function(){return d.y};this._init(a,
f,b);return this}
function CHelpPanel(a,f,b){var c,e,d,g;this._init=function(a,b,f){d=createBitmap(f);f=s_bMobile?TEXT_HELP1_MOBILE:TEXT_HELP1_PC;e=new createjs.Text(f,"24px "+FONT_GAME,"#000000");e.textAlign="center";e.lineWidth=600;e.x=.5*CANVAS_WIDTH;e.y=.5*CANVAS_HEIGHT+50;c=new createjs.Text(f,"24px "+FONT_GAME,"#ffffff");c.textAlign="center";c.lineWidth=600;c.x=.5*CANVAS_WIDTH+2;c.y=.5*CANVAS_HEIGHT+52;g=new createjs.Container;g.x=a;g.y=b;g.addChild(d,e,c);s_oStage.addChild(g);var p=this;g.on("pressup",function(){p._onExitHelp()})};
this.unload=function(){s_oStage.removeChild(g);var a=this;g.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){this.unload();s_oGame._onExitHelp()};this._init(a,f,b)}
function CHero(a,f,b){var c,e=!1,d=!1,g,k,h,m,p,n,l,t;this._init=function(a,b,d){h=0;m=1;p=0;c=!1;d={images:[d],frames:{width:65,height:100,regX:32,regY:50},animations:{idle:[0],move_right:[1,5,"idle_right"],idle_right:[5],back_right:[6,10,"idle"],move_left:[11,15,"idle_left"],idle_left:[15],back_left:[16,20,"idle"]}};t={width:16,height:25};d=new createjs.SpriteSheet(d);n=createSprite(d,"idle",32,50,65,100);n.x=a;n.y=b;n.stop();s_oStage.addChild(n);g=32.5;k=50;d={images:[s_oSpriteLibrary.getSprite("explosion_hero")],
frames:{width:200,height:200,regX:100,regY:100},animations:{show:[0,19,"hide"],hide:[20,21]}};a=new createjs.SpriteSheet(d,"hide");l=createSprite(a,"hide",100,100,200,200);l.addEventListener("animationend",this.onAnimationEnd);l.stop();l.visible=!1;s_oStage.addChild(l)};this.unload=function(){createjs.Tween.removeTweens(n);l.removeEventListener("animationend",this.onAnimationEnd)};this.moveLeft=function(){n.gotoAndPlay("move_left");e=!0};this.moveRight=function(){n.gotoAndPlay("move_right");d=!0};
this.onAnimationEnd=function(){l.stop();s_oGame.gameOver()};this.getCollision=function(){return t};this.stop=function(){e?n.gotoAndPlay("back_left"):n.gotoAndPlay("back_right");d=e=!1};this.hurt=function(){m=1===m?0:1;p++;if(6>p){c=!0;var a=this;createjs.Tween.get(n).to({alpha:m},150,createjs.Ease.cubicOut).call(function(){a.hurt()})}else c=!1,p=0,m=1,createjs.Tween.get(n).to({alpha:m},150,createjs.Ease.cubicOut)};this.gameOver=function(){n.visible=!1;l.x=n.x;l.y=n.y;l.visible=!0;l.gotoAndPlay("show");
playSound("final_explosion",1,0)};this.setVisible=function(a){n.visible=a};this.getPos=function(){return{x:n.x,y:n.y}};this.getX=function(){return n.x};this.getHeadY=function(){return n.y-k};this.getRadius=function(){return g};this.isHurting=function(){return c};this.getBulletStartPoint=function(){return{x:n.x,y:this.getHeadY()}};this.getSprite=function(){return n};this.setX=function(a){n.x=a};this.update=function(){e&&(h-=HERO_ACCELLERATION);d&&(h+=HERO_ACCELLERATION);n.x+=h;h*=HERO_FRICTION;h>MAX_HERO_SPEED&&
(h=MAX_HERO_SPEED);h<-MAX_HERO_SPEED&&(h=-MAX_HERO_SPEED);.1>Math.abs(h)&&(h=0);n.x+g+h>CANVAS_WIDTH&&(n.x=CANVAS_WIDTH-g-h);0>n.x-g+h&&(n.x=g-h)};this._init(a,f,b)}
function CHorizontalRect(a,f,b,c){var e,d=!0;this._init=function(a,b,d,c){c=0===c?s_oSpriteLibrary.getSprite("horizontal_rect"):s_oSpriteLibrary.getSprite("horizontal_rect_2");e=createBitmap(c);e.x=a;e.y=b;d.addChild(e)};this.setCollision=function(a){a?(e.alpha=1,d=!0):(e.alpha=0,d=!1)};this.getCollision=function(){return d};this.getPosition=function(){return{x:e.x,y:e.y}};this._init(a,f,b,c)}
function CInterface(){var a,f,b,c,e,d,g,k,h,m,p,n;this._init=function(){b=CANVAS_WIDTH/2;c=30;k=new createjs.Text(TEXT_SCORE+": 0","40px "+FONT_GAME,"#ffffff");k.x=b;k.y=c;k.textAlign="center";s_oStage.addChild(k);h=new CHelpPanel(0,0,s_oSpriteLibrary.getSprite("bg_help"));var l=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-l.height/2-10;f=l.height/2+10;g=new CGfxButton(a,f,l,!0);g.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l=s_oSpriteLibrary.getSprite("audio_icon"),
e=a-l.height-10,d=f,m=new CToggle(e,d,l,s_bAudioActive),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);l=s_oSpriteLibrary.getSprite("arrow");p=createBitmap(l);p.regX=l.width;p.regY=l.height;p.x=.5*CANVAS_WIDTH-395;p.y=.5*CANVAS_HEIGHT+500;p.scaleX=-1;s_oStage.addChild(p);s_oStage.setChildIndex(p,10);n=createBitmap(l);n.regX=l.width;n.regY=l.height;n.x=.5*CANVAS_WIDTH+395;n.y=.5*CANVAS_HEIGHT+500;s_oStage.addChild(n);s_oStage.setChildIndex(n,10);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};
this.refreshButtonPos=function(b,h){g.setPosition(a-b,h+f);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(e-b,h+d);k.y=c+h};this.unload=function(){g.unload();g=null;h.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;s_oInterface=null};this.refreshScore=function(a){k.text=TEXT_SCORE+": "+a};this.showArrowButs=function(){n.alpha=1;p.alpha=1};this.hideArrowButs=function(){createjs.Tween.get(n).to({alpha:0},600);createjs.Tween.get(p).to({alpha:0},600)};this.onExitFromHelp=
function(){h.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};s_oInterface=this;this._init();return this}var s_oInterface=null;TEXT_GAMEOVER="GAME OVER";TEXT_SCORE="SCORE";TEXT_HELP1_PC="Use arrow keys to drive your starship. Cross the screen from side to side to avoid blocks";TEXT_HELP1_MOBILE="TOUCH THE LEFT OR RIGHT SIDE TO MOVE THE STARSHIP. Cross the screen from side to side to avoid blocks";
TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CMain(a){var f,b=0,c=0,e=STATE_LOADING,d,g,k;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_oStage.preventSelection=!1;s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader;f=!0};this.soundLoaded=function(){b++;g.refreshLoader(Math.floor(b/c*100));if(b===c){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.ogg","click"),createjs.Sound.registerSound("./sounds/final_explosion.ogg","final_explosion"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/spaceship_whoosh.ogg","spaceship_whoosh")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.mp3",
"click"),createjs.Sound.registerSound("./sounds/final_explosion.mp3","final_explosion"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/spaceship_whoosh.mp3","spaceship_whoosh")),c+=4)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu",
"./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("parallax_1_1","./sprites/parallax_1_1.jpg");s_oSpriteLibrary.addSprite("parallax_1_2","./sprites/parallax_1_2.jpg");s_oSpriteLibrary.addSprite("parallax_1_3","./sprites/parallax_1_3.jpg");s_oSpriteLibrary.addSprite("parallax_2","./sprites/parallax_2.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("hero","./sprites/hero.png");s_oSpriteLibrary.addSprite("explosion_hero",
"./sprites/explosion_hero.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("horizontal_rect","./sprites/horizontal_rect.png");s_oSpriteLibrary.addSprite("horizontal_rect_2","./sprites/horizontal_rect_2.png");s_oSpriteLibrary.addSprite("vertical_rect","./sprites/vertical_rect.png");s_oSpriteLibrary.addSprite("vertical_rect_2","./sprites/vertical_rect_2.png");s_oSpriteLibrary.addSprite("vertical_rect_electro","./sprites/vertical_rect_electro.png");
s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;g.refreshLoader(Math.floor(b/c*100));if(b===c){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};
this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.preloaderReady=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)this._initSounds(),s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this._loadImages();f=!0};this.gotoMenu=function(){new CMenu;e=STATE_MENU};this.gotoGame=function(){k=new CGame(d);e=STATE_GAME};this.gotoHelp=function(){new CHelp;e=STATE_HELP};this.stopUpdate=function(){f=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=
function(){s_iPrevTime=(new Date).getTime();f=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==f){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&k.update();s_oStage.update(a)}};s_oMain=this;d=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iSpeedBlock,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack;
function CMenu(){var a,f,b,c,e,d,g,k;this._init=function(){e=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(e);var h=s_oSpriteLibrary.getSprite("but_play");a=CANVAS_WIDTH/2;f=CANVAS_HEIGHT-230;d=new CGfxButton(a,f,h,FONT_GAME,"#ffffff",40);d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-h.height/2-10,c=h.height/2+10,k=new CToggle(b,c,h,s_bAudioActive),k.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(g);createjs.Tween.get(g).to({alpha:0},1E3).call(function(){g.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||k.setPosition(b-a,d+c)};this.unload=function(){d.unload();d=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null;s_oStage.removeAllChildren();s_oMenu=null};
this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoGame()};s_oMenu=this;this._init()}var s_oMenu=null;
function CPreloader(){var a,f,b,c,e,d,g;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();g=new createjs.Container;s_oStage.addChild(g)};this.unload=function(){g.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(d).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));g.addChild(k);k=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(k);c.x=CANVAS_WIDTH/2-k.width/2;c.y=CANVAS_HEIGHT-150;g.addChild(c);a=k.width;f=k.height;e=new createjs.Shape;e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,f);g.addChild(e);c.mask=
e;b=new createjs.Text("","30px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-150;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";g.addChild(b);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;g.addChild(d)};this.refreshLoader=function(d){b.text=d+"%";e.graphics.clear();d=Math.floor(d*a/100);e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,d,f)};this._init()}
function CScrollingBg(a){var f,b,c;this._init=function(a){c=a;b=[];for(var d=-a.height;d<CANVAS_HEIGHT;){var g=createBitmap(a);g.y=d;d+=a.height;b.push(g);s_oStage.addChild(g)}f=0};this.update=function(a){for(var d=0;d<b.length;d++)b[d].y>CANVAS_HEIGHT&&(b[d].y=b[f].y-c.height,f=d),b[d].y+=a};this._init(a)}
function CScrollingMultipleBg(a){var f,b,c;this._init=function(a){b=[];var d=-a[0].height;c=a[0].height;for(var g=0;d<2*CANVAS_HEIGHT;){var k=createBitmap(a[g]);k.y=d;d+=c;b.push(k);s_oStage.addChild(k);g++}f=0};this.update=function(a){for(var d=0;d<b.length;d++)b[d].y>CANVAS_HEIGHT&&(b[d].y=b[f].y-c,f=d),b[d].y+=a,b[d].visible=b[d].y>-c&&b[d].y<CANVAS_HEIGHT?!0:!1};this._init(a)}
function CTextButton(a,f,b,c,e,d,g){var k,h,m;this._init=function(a,b,d,c,e,f,g){k=[];h=[];var u=createBitmap(d),w=Math.ceil(g/20),q=new createjs.Text(c,"bold "+g+"px "+e,"#000000");q.textAlign="center";q.textBaseline="alphabetic";var r=q.getBounds();q.x=d.width/2+w;q.y=Math.floor(d.height/2)+r.height/3+w;c=new createjs.Text(c,"bold "+g+"px "+e,f);c.textAlign="center";c.textBaseline="alphabetic";r=c.getBounds();c.x=d.width/2;c.y=Math.floor(d.height/2)+r.height/3;m=new createjs.Container;m.x=a;m.y=
b;m.regX=d.width/2;m.regY=d.height/2;m.addChild(u,q,c);s_bMobile||(m.cursor="pointer");s_oStage.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown");m.off("pressup");s_oStage.removeChild(m)};this.setVisible=function(a){m.visible=a};this._initListener=function(){oParent=this;m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){k[a]=b;h[a]=d};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;playSound("click",1,0);k[ON_MOUSE_UP]&&
k[ON_MOUSE_UP].call(h[ON_MOUSE_UP])};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=function(a,b){m.x=a;m.y=b};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};this._init(a,f,b,c,e,d,g);return this}var s_iOffsetX=0,s_iOffsetY=0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}window.addEventListener("orientationchange",onOrientationChange);
function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(a){var f=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var e=b.createElement("body");e.id="vpw-test-b";e.style.cssText="overflow:scroll";var d=b.createElement("div");d.id="vpw-test-d";d.style.cssText="position:absolute;top:-1000px";d.innerHTML="<style>@media("+f+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+f+":7px!important}}</style>";e.appendChild(d);c.insertBefore(e,b.head);
a=7==d["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(e)}else a=window["inner"+a];return a}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var f=getSize("Width");s_iScaleFactor=Math.min(a/CANVAS_HEIGHT,f/CANVAS_WIDTH);var b=CANVAS_WIDTH*s_iScaleFactor,c=CANVAS_HEIGHT*s_iScaleFactor,e=0;c<a?(e=a-c,c+=e,b+=CANVAS_WIDTH/CANVAS_HEIGHT*e):b<f&&(e=f-b,b+=e,c+=CANVAS_HEIGHT/CANVAS_WIDTH*e);var e=a/2-c/2,d=f/2-b/2,g=CANVAS_WIDTH/b;if(d*g<-EDGEBOARD_X||e*g<-EDGEBOARD_Y)s_iScaleFactor=Math.min(a/
(CANVAS_HEIGHT-2*EDGEBOARD_Y),f/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=CANVAS_WIDTH*s_iScaleFactor,c=CANVAS_HEIGHT*s_iScaleFactor,e=(a-c)/2,d=(f-b)/2,g=CANVAS_WIDTH/b;s_iOffsetX=-1*d*g;s_iOffsetY=-1*e*g;0<=e&&(s_iOffsetY=0);0<=d&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",b+"px");$("#canvas").css("height",c+"px");0>e?$("#canvas").css("top",e+"px"):$("#canvas").css("top",
"0px");$("#canvas").css("left",d+"px")}}function createBitmap(a,f,b){var c=new createjs.Bitmap(a),e=new createjs.Shape;f&&b?e.graphics.beginFill("#fff").drawRect(0,0,f,b):e.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=e;return c}function createSprite(a,f,b,c,e,d){a=null!==f?new createjs.Sprite(a,f):new createjs.Sprite(a);f=new createjs.Shape;f.graphics.beginFill("#000000").drawRect(-b,-c,e,d);a.hitArea=f;return a}
function randomFloatBetween(a,f,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(f-a),f).toFixed(b))}function shuffle(a){for(var f=a.length,b,c;0!==f;)c=Math.floor(Math.random()*f),--f,b=a[f],a[f]=a[c],a[c]=b;return a}function formatTime(a){a/=1E3;var f=Math.floor(a/60);a=parseFloat(a-60*f).toFixed(1);var b="",b=10>f?b+("0"+f+":"):b+(f+":");return b=10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,f){var b,c;b=getBounds(a,.9);c=getBounds(f,.98);return calculateIntersection(b,c)}function calculateIntersection(a,f){var b,c,e,d,g,k,h,m;b=a.x+(e=a.width/2);c=a.y+(d=a.height/2);g=f.x+(k=f.width/2);h=f.y+(m=f.height/2);b=Math.abs(b-g)-(e+k);c=Math.abs(c-h)-(d+m);return 0>b&&0>c?(b=Math.min(Math.min(a.width,f.width),-b),c=Math.min(Math.min(a.height,f.height),-c),{x:Math.max(a.x,f.x),y:Math.max(a.y,f.y),width:b,height:c,rect1:a,rect2:f}):null}
function getBounds(a,f){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,e=c.length,d,g;for(g=0;g<e;g++)d=getBounds(c[g],1),d.x<b.x&&(b.x=d.x),d.y<b.y&&(b.y=d.y),d.x+d.width>b.x2&&(b.x2=d.x+d.width),d.y+d.height>b.y2&&(b.y2=d.y+d.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var k,h;a instanceof createjs.Bitmap?
(e=a.sourceRect||a.image,g=e.width*f,k=e.height*f):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(e=a.spriteSheet.getFrame(a.currentFrame),g=e.rect.width,k=e.rect.height,c=e.regX,h=e.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);c=c||0;g=g||0;h=h||0;k=k||0;b.regX=c;b.regY=h;e=a.localToGlobal(0-c,0-h);d=a.localToGlobal(g-c,k-h);g=a.localToGlobal(g-c,0-h);c=a.localToGlobal(0-c,k-h);b.x=Math.min(Math.min(Math.min(e.x,
d.x),g.x),c.x);b.y=Math.min(Math.min(Math.min(e.y,d.y),g.y),c.y);b.width=Math.max(Math.max(Math.max(e.x,d.x),g.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(e.y,d.y),g.y),c.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var f=document.createEvent("MouseEvents");f.initEvent("click",!0,!0);a.dispatchEvent(f)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[f]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var f="hidden";f in document?document.addEventListener("visibilitychange",a):(f="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(f="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(f="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function playSound(a,f,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:f}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}
function setVolume(a,f){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=f}function setMute(a,f){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(f)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var f=window.location.search.substring(1).split("&"),b=0;b<f.length;b++){var c=f[b].split("=");if(c[0]==a)return c[1]}}
function CToggle(a,f,b,c){var e,d,g,k;this._init=function(a,b,c,f){d=[];g=[];var l=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});e=f;k=createSprite(l,"state_"+e,c.width/2/2,c.height/2,c.width/2,c.height);k.x=a;k.y=b;k.stop();s_bMobile||(k.cursor="pointer");s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);
s_oStage.removeChild(k)};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){d[a]=b;g[a]=c};this.setCursorType=function(a){k.cursor=a};this.setActive=function(a){e=a;k.gotoAndStop("state_"+e)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("click",1,0);e=!e;k.gotoAndStop("state_"+e);d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(g[ON_MOUSE_UP],e)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;d[ON_MOUSE_DOWN]&&
d[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this.setPosition=function(a,b){k.x=a;k.y=b};this._init(a,f,b,c)}
function CVerticalRect(a,f,b,c){var e,d,g,k,h=!0,m,p,n=!1;this._init=function(a,b,c,f){var h;if(0===f)h=s_oSpriteLibrary.getSprite("vertical_rect");else if(1===f)h=s_oSpriteLibrary.getSprite("vertical_rect_2");else if(2===f){h=s_oSpriteLibrary.getSprite("vertical_rect_electro");var n=new createjs.SpriteSheet({images:[h],frames:{width:h.width/STYLE_BLOCK_VERTICAL_MASK[f].width,height:h.height/STYLE_BLOCK_VERTICAL_MASK[f].height,regX:17,regY:0},animations:{electro:[0,23,"electro",1],idle:[0]}});e=createSprite(n,
"idle",17,0,h.width/STYLE_BLOCK_VERTICAL_MASK[f].width,h.height/STYLE_BLOCK_VERTICAL_MASK[f].height);this.randomTime()}if(0===f||1===f)e=createBitmap(h);e.x=a;e.y=b;d=new createjs.Shape;g=h.height/STYLE_BLOCK_VERTICAL_MASK[f].height;k=h.width/STYLE_BLOCK_VERTICAL_MASK[f].width;d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(a,b,k,g);e.mask=d;m=f;c.addChild(e)};this.playState=function(a){2===m&&e.gotoAndPlay(a)};this.randomTime=function(){p=Math.floor(Math.random()*MAX_SECOND_FOR_ANIM_VERTICAL_RECT)};
this.setCollision=function(a){a?(d.graphics.clear(),d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,k,g),h=!0):(d.graphics.clear(),d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,k,MASK_VERTICAL_RECT_HEIGHT),h=!1)};this.getCollision=function(){return h};this.getPosition=function(){return{x:e.x,y:e.y}};this.update=function(){2===m&&!1===n&&(0<p?p-=1/createjs.Ticker.framerate:(n=!0,this.playState("electro")))};this._init(a,f,b,c)}
var CANVAS_WIDTH=968,CANVAS_HEIGHT=1224,EDGEBOARD_X=100,EDGEBOARD_Y=100,DISABLE_SOUND_MOBILE=!1,FONT_GAME="space_marinenominal",FPS_TIME=1E3/24,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,WIDTH_OF_HORIZONTAL_RECT=130,HEIGHT_OF_HORIZONTAL_RECT=50,WIDTH_OF_VERTICAL_RECT=60,HEIGHT_OF_VERTICAL_RECT=320,OFFSET_LEFT_VERTICAL_POS=2,TELEPORT_OFFSET_LEFT=130,TELEPORT_OFFSET_RIGHT=870,OFFSET_COUPLING=-50,MASK_VERTICAL_RECT_HEIGHT=
50,TIME_TRANSICTION=.5,SHOW_ID_BLOCK=!1,SHOW_DEBUG_COLUMN=!1,STYLE_BLOCK_VERTICAL_MASK,SUB_COLUMN=5,BLOCK_FOR_SCREEN=5,VERTICAL_RECT_STYLE_BLOCK,HORIZONTAL_RECT_STYLE_BLOCK,MAX_SECOND_FOR_ANIM_VERTICAL_RECT=10,DISPLAY_SHOCK_X=30,DISPLAY_SHOCK_Y=50;VERTICAL_RECT_STYLE_BLOCK=[];STYLE_BLOCK_VERTICAL_MASK=[];HORIZONTAL_RECT_STYLE_BLOCK=[];for(var i=0;i<SUB_COLUMN;i++)HORIZONTAL_RECT_STYLE_BLOCK[i]=[];STYLE_BLOCK_VERTICAL_MASK[0]={width:1,height:1};STYLE_BLOCK_VERTICAL_MASK[1]={width:1,height:1};
STYLE_BLOCK_VERTICAL_MASK[2]={width:12,height:2};VERTICAL_RECT_STYLE_BLOCK[0]={left:0,right:2};VERTICAL_RECT_STYLE_BLOCK[1]={left:2,right:0};VERTICAL_RECT_STYLE_BLOCK[2]={left:1,right:2};VERTICAL_RECT_STYLE_BLOCK[3]={left:0,right:1};VERTICAL_RECT_STYLE_BLOCK[4]={left:2,right:1};HORIZONTAL_RECT_STYLE_BLOCK[0][0]=1;HORIZONTAL_RECT_STYLE_BLOCK[0][1]=0;HORIZONTAL_RECT_STYLE_BLOCK[0][2]=1;HORIZONTAL_RECT_STYLE_BLOCK[0][3]=0;HORIZONTAL_RECT_STYLE_BLOCK[0][4]=1;HORIZONTAL_RECT_STYLE_BLOCK[1][0]=0;
HORIZONTAL_RECT_STYLE_BLOCK[1][1]=1;HORIZONTAL_RECT_STYLE_BLOCK[1][2]=0;HORIZONTAL_RECT_STYLE_BLOCK[1][3]=1;HORIZONTAL_RECT_STYLE_BLOCK[1][4]=0;HORIZONTAL_RECT_STYLE_BLOCK[2][0]=1;HORIZONTAL_RECT_STYLE_BLOCK[2][1]=1;HORIZONTAL_RECT_STYLE_BLOCK[2][2]=0;HORIZONTAL_RECT_STYLE_BLOCK[2][3]=1;HORIZONTAL_RECT_STYLE_BLOCK[2][4]=1;HORIZONTAL_RECT_STYLE_BLOCK[3][0]=1;HORIZONTAL_RECT_STYLE_BLOCK[3][1]=0;HORIZONTAL_RECT_STYLE_BLOCK[3][2]=0;HORIZONTAL_RECT_STYLE_BLOCK[3][3]=0;
HORIZONTAL_RECT_STYLE_BLOCK[3][4]=1;HORIZONTAL_RECT_STYLE_BLOCK[4][0]=0;HORIZONTAL_RECT_STYLE_BLOCK[4][1]=0;HORIZONTAL_RECT_STYLE_BLOCK[4][2]=1;HORIZONTAL_RECT_STYLE_BLOCK[4][3]=0;HORIZONTAL_RECT_STYLE_BLOCK[4][4]=0;var HERO_START_X=.5*CANVAS_WIDTH,HERO_ACCELLERATION,HERO_FRICTION,MAX_HERO_SPEED,SCORE_HIT,PARALLAX1_SPEED=1,PARALLAX2_SPEED=5,POINT_DIFFICULT_INCREASE,VELOCITY_INCREASE,MAX_SPEED;
function CSpriteLibrary(){var a,f,b,c,e,d;this.init=function(g,k,h){b=f=0;c=g;e=k;d=h;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},f++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){e.call(d)};this._onSpriteLoaded=function(){c.call(d);++b==f&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return f}};
