function CSpriteLibrary(){var a,e,b,c,f,h;this.init=function(g,d,k){b=e=0;c=g;f=d;h=k;a={}};this.addSprite=function(b,d){a.hasOwnProperty(b)||(a[b]={szPath:d,oSprite:new Image},e++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(h)};this._onSpriteLoaded=function(){c.call(h);++b==e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return e}}
var CANVAS_WIDTH=1600,CANVAS_HEIGHT=768,DISABLE_SOUND_MOBILE=!1,EDGEBOARD_X=270,EDGEBOARD_Y=60,FPS_TIME=1E3/30,FONT_GAME="arialbold",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_PRESS_MOVE=6,NUM_LANGUAGES=6,TIME_LEVEL,MAX_CHAR_VALUE,CELL_WIDTH=86,CELL_HEIGHT=86,MAX_WORD_LENGTH=8,MAX_WORDS_WRITTEN_VIEWABLE=22,SCORE_WORD_WRONG,NUM_ROWS=7,NUM_COLS=7,DEFAULT_LANG,LABEL_LANG_0=0,LABEL_LANG_1=1,LABEL_LANG_2=
2,LABEL_LANG_3=3,LABEL_LANG_4=4,LABEL_LANG_5=5;
function CToggle(a,e,b,c,f){var h,g,d,k,n=null;this._init=function(a,b,c,e,f){g=[];d=[];var n=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});h=e;k=createSprite(n,"state_"+h,c.width/2/2,c.height/2,c.width/2,c.height);k.x=a;k.y=b;k.stop();!1!==f&&s_oStage.addChild(k);k.cursor="pointer";this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);
s_oStage.removeChild(k)};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;d[a]=c};this.addEventListenerWithParams=function(a,b,c,e){g[a]=b;d[a]=c;n=e};this.setActive=function(a){h=a;k.gotoAndStop("state_"+h)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("click",1,0);h=!h;k.gotoAndStop("state_"+h);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(d[ON_MOUSE_UP],{active:h,params:n})};this.buttonDown=function(){k.scaleX=
.9;k.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(d[ON_MOUSE_DOWN])};this.setPosition=function(a,b){k.x=a;k.y=b};this.getSprite=function(){return k};this._init(a,e,b,c,f)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop,s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}window.addEventListener("orientationchange",onOrientationChange);
function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(a){var e=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var f=b.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var h=b.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+e+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+e+":7px!important}}</style>";f.appendChild(h);c.insertBefore(f,b.head);
a=7==h["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(f)}else a=window["inner"+a];return a}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var e=getSize("Width"),b=s_iScaleFactor=Math.min(a/CANVAS_HEIGHT,e/CANVAS_WIDTH),c=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,f;b<a?(f=a-b,b+=f,c+=CANVAS_WIDTH/CANVAS_HEIGHT*f):c<e&&(f=e-c,c+=f,b+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-b/2;var h=e/2-c/2,g=CANVAS_WIDTH/c;if(h*g<-EDGEBOARD_X||f*g<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),e/(CANVAS_WIDTH-
2*EDGEBOARD_X)),c=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,f=(a-b)/2,h=(e-c)/2,g=CANVAS_WIDTH/c;s_iOffsetX=-1*h*g;s_iOffsetY=-1*f*g;0<=f&&(s_iOffsetY=0);0<=h&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",c+"px");$("#canvas").css("height",b+"px");0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",h+"px");s_oCanvasLeft=$("#canvas").offset().left;
s_oCanvasTop=$("#canvas").offset().top}}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function createBitmap(a,e,b){var c=new createjs.Bitmap(a),f=new createjs.Shape;e&&b?f.graphics.beginFill("#fff").drawRect(0,0,e,b):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=f;return c}function createSprite(a,e,b,c,f,h){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-b,-c,f,h);a.hitArea=e;return a}
function randomFloatBetween(a,e,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(b))}function shuffle(a){for(var e=a.length,b,c;0!==e;)c=Math.floor(Math.random()*e),--e,b=a[e],a[e]=a[c],a[c]=b;return a}function formatTime(a){a/=1E3;var e=Math.floor(a/60);a=parseInt(a-60*e);var b="",b=10>e?b+("0"+e+":"):b+(e+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,e){var b,c;b=getBounds(a,.9);c=getBounds(e,.98);return calculateIntersection(b,c)}function calculateIntersection(a,e){var b,c,f,h,g,d,k,n;b=a.x+(f=a.width/2);c=a.y+(h=a.height/2);g=e.x+(d=e.width/2);k=e.y+(n=e.height/2);b=Math.abs(b-g)-(f+d);c=Math.abs(c-k)-(h+n);return 0>b&&0>c?(b=Math.min(Math.min(a.width,e.width),-b),c=Math.min(Math.min(a.height,e.height),-c),{x:Math.max(a.x,e.x),y:Math.max(a.y,e.y),width:b,height:c,rect1:a,rect2:e}):null}
function getBounds(a,e){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,f=c.length,h,g;for(g=0;g<f;g++)h=getBounds(c[g],1),h.x<b.x&&(b.x=h.x),h.y<b.y&&(b.y=h.y),h.x+h.width>b.x2&&(b.x2=h.x+h.width),h.y+h.height>b.y2&&(b.y2=h.y+h.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var d,k;a instanceof createjs.Bitmap?
(f=a.sourceRect||a.image,g=f.width*e,d=f.height*e):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(f=a.spriteSheet.getFrame(a.currentFrame),g=f.rect.width,d=f.rect.height,c=f.regX,k=f.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);c=c||0;g=g||0;k=k||0;d=d||0;b.regX=c;b.regY=k;f=a.localToGlobal(0-c,0-k);h=a.localToGlobal(g-c,d-k);g=a.localToGlobal(g-c,0-k);c=a.localToGlobal(0-c,d-k);b.x=Math.min(Math.min(Math.min(f.x,
h.x),g.x),c.x);b.y=Math.min(Math.min(Math.min(f.y,h.y),g.y),c.y);b.width=Math.max(Math.max(Math.max(f.x,h.x),g.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(f.y,h.y),g.y),c.y)-b.y}return b}function binarySearch(a,e,b,c){if(b>c)return-1;var f=Math.floor((b+c)/2);return a[f].toLowerCase()===e.toLowerCase()?f:a[f].toLowerCase()>e.toLowerCase()?binarySearch(a,e,b,f-1):binarySearch(a,e,f+1,c)}function between(a,e,b){var c=!1;a<b&&e>a&&e<b&&(c=!0);a>b&&e>b&&e<a&&(c=!0);if(e===a||e===b)c=!0;return c}
function pointInRectangle(a,e,b){var c=!1,f=b.y,h=b.height;between(b.x,a,b.width)&&between(f,e,h)&&(c=!0);return c}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[e]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var e="hidden";e in document?document.addEventListener("visibilitychange",a):(e="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(e="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(e="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function playSound(a,e,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:e}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}
function setVolume(a,e){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=e}function setMute(a,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(e)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var e=window.location.search.substring(1).split("&"),b=0;b<e.length;b++){var c=e[b].split("=");if(c[0]==a)return c[1]}}
function CTimeBar(a,e){var b,c,f;this._init=function(a,e){f=new createjs.Container;f.x=a;f.y=e;s_oStage.addChild(f);var d=s_oSpriteLibrary.getSprite("timebar_bg"),k=createBitmap(d);k.y=25;f.addChild(k);c=createBitmap(s_oSpriteLibrary.getSprite("timebar_fill"));c.y=k.y+d.height;c.regY=d.height;f.addChild(c);b=new createjs.Text("","20px "+FONT_GAME,"#55bcff");b.x=d.width/2;b.y=k.y+d.height+20;b.textAlign="center";b.textBaseline="alphabetic";f.addChild(b);var k=s_oSpriteLibrary.getSprite("time_icon"),
n=createBitmap(k);n.regX=k.width/2;n.regY=k.height/2;n.x=d.width/2;f.addChild(n)};this.refreshTime=function(a){b.text=formatTime(Math.floor(a));a=(a/TIME_LEVEL).toFixed(2);c.scaleY=a};this._init(a,e)}
function CTextButton(a,e,b,c,f,h,g,d){var k,n,l,m,q;this._init=function(a,b,c,d,e,f,g,h){k=[];n=[];var z=createBitmap(c),y=Math.ceil(g/30);m=new createjs.Text(d,g+"px "+e,"#000000");m.textAlign="center";m.textBaseline="middle";m.lineHeight=1;var x=m.getBounds();m.x=c.width/2+y;m.y=Math.floor(c.height/2)+x.height/3+y;q=new createjs.Text(d,g+"px "+e,f);q.textAlign="center";q.textBaseline="middle";q.lineHeight=1;x=q.getBounds();q.x=c.width/2;q.y=Math.floor(c.height/2)+x.height/3;l=new createjs.Container;
l.x=a;l.y=b;l.regX=c.width/2;l.regY=c.height/2;l.addChild(z,m,q);!1!==h&&s_oStage.addChild(l);l.cursor="pointer";this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.setText=function(a){m.text=a;q.text=a};this.addEventListener=function(a,b,c){k[a]=b;n[a]=c};this.buttonRelease=function(){playSound("click",
1,0);l.scaleX=1;l.scaleY=1;k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(n[ON_MOUSE_UP])};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN])};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this.getSprite=function(){return l};this._init(a,e,b,c,f,h,g,d);return this}
function CPreloader(){var a,e,b,c,f,h,g;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();g=new createjs.Container;s_oStage.addChild(g)};this.unload=function(){g.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(h).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var d=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));g.addChild(d);d=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(d);c.x=CANVAS_WIDTH/2-d.width/2;c.y=CANVAS_HEIGHT-150;g.addChild(c);a=d.width;e=d.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,e);g.addChild(f);c.mask=
f;b=new createjs.Text(" ","30px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-105;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";g.addChild(b);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=0;g.addChild(h)};this.refreshLoader=function(d){b.text=d+"%";f.graphics.clear();d=Math.floor(d*a/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,d,e)};this._init()}
function CMenu(){var a,e,b,c,f,h,g,d=null,k,n;this._init=function(){f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(f);var l=s_oSpriteLibrary.getSprite("but_play");h=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-160,l,s_oStage);h.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);d=new CLanguageSelection;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-l.height/2-10,c=l.height/2+10,k=new CToggle(b,c,l,s_bAudioActive,
!0),k.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);l=s_oSpriteLibrary.getSprite("but_credits");a=l.height/2+10;e=l.height/2+10;n=new CGfxButton(a,e,l,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onCredits,this);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(g);createjs.Tween.get(g).to({alpha:0},1E3).call(function(){g.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(g,f){!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||k.setPosition(b-g,c+f);n.setPosition(a+g,e+f);null!==d&&d.refreshButtonPos(g,f)};this.unload=function(){h.unload();h=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null;s_oStage.removeAllChildren();s_oMenu=f=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){$(s_oMain).trigger("start_session");d.show()};this._onCredits=function(){new CCreditsPanel};s_oMenu=this;this._init()}
var s_oMenu=null;
function CMain(a){var e,b=0,c=0,f=STATE_LOADING,h,g,d;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);s_oCanvas=a;s_bMobile=jQuery.browser.mobile;!1===s_bMobile?(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1})):createjs.Touch.enable(s_oStage);s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();e=!0};this.soundLoaded=function(){b++;g.refreshLoader(Math.floor(b/c*100));b===c&&(g.unload(),s_oSoundtrack=playSound("soundtrack",.5,-1),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=
["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.ogg","click"),createjs.Sound.registerSound("./sounds/gameover.ogg","gameover"),createjs.Sound.registerSound("./sounds/right.ogg","right"),createjs.Sound.registerSound("./sounds/wrong.ogg","wrong"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,
this)),createjs.Sound.registerSound("./sounds/click.mp3","click"),createjs.Sound.registerSound("./sounds/gameover.mp3","gameover"),createjs.Sound.registerSound("./sounds/right.mp3","right"),createjs.Sound.registerSound("./sounds/wrong.mp3","wrong"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack")),c+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_game",
"./sprites/but_game.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("gameover_bg","./sprites/gameover_bg.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("toggle_lang","./sprites/toggle_lang.png");s_oSpriteLibrary.addSprite("bg_language_selection","./sprites/bg_language_selection.jpg");
s_oSpriteLibrary.addSprite("cell_bg","./sprites/cell_bg.png");s_oSpriteLibrary.addSprite("cell_right","./sprites/cell_right.png");s_oSpriteLibrary.addSprite("cell_select_bg","./sprites/cell_select_bg.png");s_oSpriteLibrary.addSprite("cell_wrong","./sprites/cell_wrong.png");s_oSpriteLibrary.addSprite("hit_area_cell","./sprites/hit_area_cell.png");s_oSpriteLibrary.addSprite("timebar_bg","./sprites/timebar_bg.png");s_oSpriteLibrary.addSprite("timebar_fill","./sprites/timebar_fill.png");s_oSpriteLibrary.addSprite("help_bg",
"./sprites/help_bg.png");s_oSpriteLibrary.addSprite("time_icon","./sprites/time_icon.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("bg_credits","./sprites/bg_credits.png");s_oSpriteLibrary.addSprite("logo_credits","./sprites/logo_credits.png");s_oSpriteLibrary.addSprite("but_exit_big","./sprites/but_exit_big.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");
c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;g.refreshLoader(Math.floor(b/c*100));b===c&&(g.unload(),s_oSoundtrack=playSound("soundtrack",.5,-1),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.setLanguage=function(){switch(s_iLangSelected){case LABEL_LANG_0:s_oWordListSelected=new CEngWordlist;break;case LABEL_LANG_1:s_oWordListSelected=new CGerWordlist;break;case LABEL_LANG_2:s_oWordListSelected=
new CSpaWordlist;break;case LABEL_LANG_3:s_oWordListSelected=new CFraWordlist;break;case LABEL_LANG_4:s_oWordListSelected=new CItaWordlist;break;case LABEL_LANG_5:s_oWordListSelected=new CPorWordlist}this.gotoHelp()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(){d=new CGame(h);f=STATE_GAME};this.gotoHelp=function(){new CHelpPanel;f=STATE_HELP};this.stopUpdate=function(){e=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=
(new Date).getTime();e=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==e){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&d.update();s_oStage.update(a)}};s_oMain=this;h=a;s_iLangSelected=DEFAULT_LANG=a.default_lang;trace("init lang: "+s_iLangSelected);this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iLangSelected,s_oWordListSelected,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas;
function CLanguageSelection(){var a,e,b,c,f,h;this._init=function(){h=new createjs.Container;h.alpha=0;h.visible=!1;s_oStage.addChild(h);var g=createBitmap(s_oSpriteLibrary.getSprite("bg_language_selection"));h.addChild(g);g=s_oSpriteLibrary.getSprite("but_play");a=CANVAS_WIDTH-10-.5*g.width/2;e=CANVAS_HEIGHT-10-.5*g.height/2;c=new CGfxButton(a,e,g,h);c.setScale(.5);c.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);for(var g=182,d=0;d<NUM_LANGUAGES;d++){if(d===s_iLangSelected){var k=new CToggle(380,
g,s_oSpriteLibrary.getSprite("toggle_lang"),!0,!1);b=k}else k=new CToggle(380,g,s_oSpriteLibrary.getSprite("toggle_lang"),!1,!1);k.addEventListenerWithParams(ON_MOUSE_UP,this._onLangToggle,this,{index:d,but:k});h.addChild(k.getSprite());g+=79}f=new createjs.Text(TEXT_CHOOSE_LANG,"60px "+FONT_GAME,"#55bcff");f.x=CANVAS_WIDTH/2;f.y=116;f.textAlign="center";f.textBaseline="alphabetic";h.addChild(f)};this.show=function(){h.visible=!0;createjs.Tween.get(h).to({alpha:1},500)};this.refreshButtonPos=function(b,
d){c.setPosition(a-b,e-d)};this._onLangToggle=function(a){a=a.params;if(a.but===b)b.setActive(!0);else{var c=a.index;b.setActive(!1);s_iLangSelected=window["LABEL_LANG_"+c];b=a.but;changeLanguage();f.text=TEXT_CHOOSE_LANG}};this._onButPlayRelease=function(){changeLanguage();s_oMenu.unload();s_oMain.setLanguage()};this._init()}TEXT_LOSE="GAME OVER";TEXT_WIN="CONGRATULATIONS!!!";TEXT_SCORE="SCORE";TEXT_PLAY="PLAY";TEXT_EXIT="EXIT";TEXT_CHOOSE_LANG="CHOOSE A LANGUAGE";TEXT_TOT_SCORE="TOTAL SCORE";
TEXT_WORD_FOUND="WORDS FOUND";TEXT_LONGEST_WORD="LONGEST WORD";TEXT_BEST_WORD="BEST WORD";TEXT_HELP="COMPOSE AS MANY WORDS AS POSSIBLE DRAWING A LINE!";var TEXT_CREDITS_DEVELOPED="DEVELOPED BY",TEXT_LINK1="WWW.CODETHISLAB.COM";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function changeLanguage(){switch(s_iLangSelected){case LABEL_LANG_0:TEXT_LOSE="GAME OVER";TEXT_WIN="CONGRATULATIONS!!!";TEXT_SCORE="SCORE";TEXT_PLAY="PLAY";TEXT_EXIT="EXIT";TEXT_CHOOSE_LANG="CHOOSE A LANGUAGE";TEXT_TOT_SCORE="TOTAL SCORE";TEXT_WORD_FOUND="WORDS FOUND";TEXT_LONGEST_WORD="LONGEST WORD";TEXT_BEST_WORD="BEST WORD";TEXT_HELP="COMPOSE AS MANY WORDS AS POSSIBLE DRAWING A LINE!";break;case LABEL_LANG_1:TEXT_LOSE="GAME OVER";TEXT_WIN="GL\u00dcCKW\u00dcNSCHE!!!";TEXT_SCORE="ERGEBNIS";TEXT_PLAY=
"SPIELEN";TEXT_EXIT="EXIT";TEXT_CHOOSE_LANG="SPRACHE AUSW\u00c4HLEN";TEXT_TOT_SCORE="GESAMTPUNKTZAHL";TEXT_WORD_FOUND="W\u00d6RTER GEFUNDEN";TEXT_LONGEST_WORD="L\u00c4NGSTE WORT";TEXT_BEST_WORD="BESTE WORT";TEXT_HELP="KOMPIEREN SO VIELE W\u00d6RTER WIE M\u00d6GLICH!";break;case LABEL_LANG_2:TEXT_LOSE="FIN DEL JUEGO";TEXT_WIN="\u00a1FELICIDADES!";TEXT_SCORE="PUNTOS";TEXT_PLAY="JUGAR";TEXT_EXIT="SALIR";TEXT_CHOOSE_LANG="SELECCIONA UN IDIOMA";TEXT_TOT_SCORE="PUNTUACI\u00d3N TOTAL";TEXT_WORD_FOUND="PALABRAS HALLADAS";
TEXT_LONGEST_WORD="PALABRA M\u00c1S LARGA";TEXT_BEST_WORD="MEJOR PALABRA";TEXT_HELP="\u00a1COMPONGAS TODAS LAS PALABRAS POSIBLES!";break;case LABEL_LANG_3:TEXT_LOSE="FIN DU JEU ";TEXT_WIN="F\u00c9LICITATIONS!!!";TEXT_SCORE="SCORE";TEXT_PLAY="JOUER";TEXT_EXIT="SORTIR";TEXT_CHOOSE_LANG="CHOISISSEZ LA LANGUE";TEXT_TOT_SCORE="SCORE TOTAL";TEXT_WORD_FOUND="MOTS TROUV\u00c9S";TEXT_LONGEST_WORD="MOT LE PLUS LONG";TEXT_BEST_WORD="MEILLEUR MOT";TEXT_HELP="COMPOSER AUTANT DE MOTS QUE POSSIBLE!";break;case LABEL_LANG_4:TEXT_LOSE=
"GAME OVER";TEXT_WIN="COMPLIMENTI!!!";TEXT_SCORE="PUNTI";TEXT_PLAY="GIOCA";TEXT_EXIT="ESCI";TEXT_CHOOSE_LANG="SCEGLI UNA LINGUA";TEXT_TOT_SCORE="PUNTI TOTALI";TEXT_WORD_FOUND="PAROLE TROVATE";TEXT_LONGEST_WORD="PAROLA PI\u00d9 LUNGA";TEXT_BEST_WORD="MIGLIOR PAROLA";TEXT_HELP="COMPONI PI\u00d9 PAROLE CHE PUOI!";break;case LABEL_LANG_5:TEXT_LOSE="FIM DE JOGO",TEXT_WIN="PARAB\u00c9NS!!!!",TEXT_SCORE="ESCORE",TEXT_PLAY="JOGAR",TEXT_EXIT="SAIR",TEXT_CHOOSE_LANG="ESCOLHE UMA L\u00cdNGUA",TEXT_TOT_SCORE=
"PONTUA\u00c7\u00c3O TOTAL",TEXT_WORD_FOUND="PALAVRAS ENCONTRADAS",TEXT_LONGEST_WORD="PALAVRA MAIS LONGA",TEXT_BEST_WORD="MELHOR PALAVRA",TEXT_HELP="COMPONHA TANTAS PALAVRAS QUANTO POSS\u00cdVEL!"}}
function CInterface(){var a,e,b,c,f,h,g,d,k,n,l;this._init=function(){g=new createjs.Text("0","60px "+FONT_GAME,"#fff");g.x=1160;g.y=692;g.textAlign="center";g.textBaseline="alphabetic";s_oStage.addChild(g);f=[];for(var m=1023,q=0;q<MAX_WORD_LENGTH;q++){var r=new createjs.Text("","36px "+FONT_GAME,"#fff");r.x=m;r.y=99;r.textAlign="center";r.textBaseline="alphabetic";s_oStage.addChild(r);m+=41;f.push(r)}d=new createjs.Text("","20px "+FONT_GAME,"#6b6a69");d.x=1030;d.y=170;d.textAlign="left";d.textBaseline=
"alphabetic";d.lineHeight=20;s_oStage.addChild(d);k=new createjs.Text("","20px "+FONT_GAME,"#6b6a69");k.x=1140;k.y=170;k.textAlign="left";k.textBaseline="alphabetic";k.lineHeight=20;s_oStage.addChild(k);n=new CTimeBar(958,86);m=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-m.height/2-10;e=10+m.height/2;h=new CGfxButton(a,e,m,s_oStage);h.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m=s_oSpriteLibrary.getSprite("audio_icon"),b=h.getX()-m.height-
10,c=m.height/2+10,l=new CToggle(b,c,m,s_bAudioActive),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){h.unload();h=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;s_oInterface=null};this.refreshButtonPos=function(d,f){h.setPosition(a-d,e+f);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(b-d,c+f)};this.refreshScore=function(a){g.text=""+a};this.clearWordComposing=function(){for(var a=0;a<f.length;a++)f[a].text=
""};this.setWordComposing=function(a){for(var b=0;b<a.length;b++)f[b].text=a.charAt(b)};this.displayAnswer=function(a){this.refreshScore(a);for(a=0;a<MAX_WORD_LENGTH;a++)f[a].text=""};this.refreshWordWritten=function(a){d.text="";k.text="";var b=a.length-MAX_WORDS_WRITTEN_VIEWABLE;a=0<b?a.slice(b,a.length):a;for(b=0;b<a.length;b++)d.text+=a[b].word+"\n",k.text+="+"+a[b].score+"\n"};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};
this.updateTime=function(a){n.refreshTime(a)};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(){var a,e,b,c;this._init=function(){e=createBitmap(s_oSpriteLibrary.getSprite("help_bg"));a=new createjs.Text(TEXT_HELP,"50px "+FONT_GAME,"#fff");a.x=CANVAS_WIDTH/2;a.y=130;a.textAlign="center";a.textBaseline="alphabetic";a.lineHeight=46;a.lineWidth=600;var f=s_oSpriteLibrary.getSprite("but_play");b=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-145,f,s_oStage);b.setScale(.6);b.addEventListener(ON_MOUSE_UP,this._onExit,this);c=new createjs.Container;c.addChild(e,a,b.getSprite());
s_oStage.addChild(c)};this.unload=function(){b.unload();s_oStage.removeAllChildren()};this._onExit=function(){this.unload();s_oMain.gotoGame()};this._init()}
function CGfxButton(a,e,b,c){var f=1,h,g,d,k;this._init=function(a,b,c){h=[];g=[];d=createBitmap(c);d.x=a;d.y=b;d.regX=c.width/2;d.regY=c.height/2;k.addChild(d);d.cursor="pointer";this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);!1===s_bMobile&&d.off("mouseover",this.buttonOver);k.removeChild(d)};this.setVisible=function(a){d.visible=a};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease);
if(!1===s_bMobile)d.on("mouseover",this.buttonOver)};this.addEventListener=function(a,b,c){h[a]=b;g[a]=c};this.buttonRelease=function(){playSound("click",1,0);d.scaleX=f;d.scaleY=f;h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(g[ON_MOUSE_UP])};this.buttonDown=function(){d.scaleX=.9*f;d.scaleY=.9*f;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this.buttonOver=function(){h[ON_MOUSE_OVER]&&h[ON_MOUSE_OVER].call(g[ON_MOUSE_OVER])};this.setPosition=function(a,b){d.x=a;d.y=b};this.setX=function(a){d.x=
a};this.setY=function(a){d.y=a};this.setScale=function(a){f=a;d.scaleX=a;d.scaleY=a};this.getSprite=function(){return d};this.getX=function(){return d.x};this.getY=function(){return d.y};k=c;this._init(a,e,b);return this}
function CGame(a){var e,b,c,f,h,g,d,k,n,l,m,q,r,u,t,v,p,w=null;this._init=function(){c=0;v=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(v);t=new createjs.Container;t.x=310;t.y=74;s_oStage.addChild(t);p=new CInterface;k=s_oWordListSelected.getWordList();if(s_bMobile)if(window.navigator.msPointerEnabled)s_oCanvas.addEventListener("MSPointerUp",this._onStageRelease,!1);else s_oStage.on("pressup",this._onStageRelease);else s_oStage.on("pressup",this._onStageRelease);this._reset();
this._createMatrix();this._populateMatrix();e=!0;$(s_oMain).trigger("start_level",1)};this.unload=function(){s_bMobile?window.navigator.msPointerEnabled?s_oCanvas.removeEventListener("MSPointerUp",this._onStageRelease,!1):s_oStage.off("pressup",this._onStageRelease):s_oStage.off("pressup",this._onStageRelease);w&&w.unload();p.unload();s_oStage.removeAllChildren()};this._reset=function(){f=TIME_LEVEL;n=[];d="";b=!0;c=0;l=[]};this._createMatrix=function(){var a=0,b=0;m=[];for(var c=0;c<NUM_ROWS;c++){m[c]=
[];for(var d=0;d<NUM_COLS;d++){var e=new CCell(a,b,c,d,Math.floor(Math.random()*MAX_CHAR_VALUE)+1,t),a=a+(CELL_WIDTH+4);m[c][d]=e}a=0;b+=CELL_HEIGHT+4}};this._populateMatrix=function(){for(var a,b=s_oWordListSelected.getConsonants(),c=s_oWordListSelected.getVowel(),d=0,e=0;e<NUM_ROWS;e++)for(var f=0;f<NUM_COLS;f++)2===d?(d=0,a=Math.floor(Math.random()*c.length),m[e][f].setText(c[a])):(a=Math.floor(Math.random()*b.length),m[e][f].setText(b[a])),d++};this._gameOver=function(){e=!1;playSound("gameover",
1,0);var a="",b="",d;d=0;if(0<l.length){a=l[0].word;b=l[0].score;d=0;for(var f=1;f<l.length;f++)a.length<l[f].word.length&&(a=l[f].word),b<l[f].score&&(b=l[f].score,d=f);b=l[d].word;d=l[d].score}w=new CEndPanel;w.show(c,l.length,a,b,d);$(s_oMain).trigger("end_level",1)};this.onCellSelected=function(a,c,e){b&&(b=!1,n.push(a),a.select(),d+=a.getText(),p.setWordComposing(d),this.retrieveSelectableCells(c,e,a),r=new createjs.Graphics,r.setStrokeStyle(5),r.beginStroke("rgba(0,0,0,0.7)"),r.moveTo(a.getX()+
CELL_WIDTH/2,a.getY()+CELL_HEIGHT/2),u=new createjs.Shape(r),t.addChild(u),s_bMobile?window.navigator.msPointerEnabled?s_oCanvas.addEventListener("MSPointerMove",this._onMSStageMouseMove,!1):s_oStage.addEventListener("stagemousemove",this._onStageMouseMove):s_oStage.addEventListener("stagemousemove",this._onStageMouseMove))};this.onCellOver=function(a,c,e){if(!b)if(d.length===MAX_WORD_LENGTH)this._onStageRelease();else for(var f=0;f<q.length;f++)if(q[f]===a){n.push(a);a.select();d+=a.getText();p.setWordComposing(d);
this.retrieveSelectableCells(c,e,a);r.lineTo(a.getX()+CELL_WIDTH/2,a.getY()+CELL_HEIGHT/2);break}};this.retrieveSelectableCells=function(a,b,c){q=[];for(var d=a-1;d<a+2;d++)for(var e=b-1;e<b+2;e++)-1<d&&d<NUM_ROWS&&-1<e&&e<NUM_COLS&&!1===m[d][e].isActive()&&m[d][e]!==c&&q.push(m[d][e])};this._onStageRelease=function(){b||(s_bMobile?window.navigator.msPointerEnabled?s_oCanvas.removeEventListener("MSPointerMove",this._onStageMouseMove,!1):s_oCanvas.removeEventListener("touchmove",this._onStageMouseMove,
!1):s_oStage.removeEventListener("stagemousemove",s_oGame._onStageMouseMove),b=!0,u&&(r.clear(),s_oGame._onCheckWord()))};this._clearMatrix=function(){for(var a=0;a<NUM_ROWS;a++)for(var c=0;c<NUM_COLS;c++)m[a][c].deselect();n=[];b=!0;d="";p.clearWordComposing()};this._displayRightOnCell=function(){for(var a=0;a<n.length;a++)n[a].showRight();playSound("right",1,0)};this._displayWrongOnCell=function(){for(var a=0;a<n.length;a++)n[a].showWrong();playSound("wrong",1,0)};this._onCheckWord=function(){if(!(3>
d.length))if(-1===binarySearch(k,d.toLowerCase(),0,k.length))c+=SCORE_WORD_WRONG,0>c&&(c=0),this._displayWrongOnCell(),p.displayAnswer(c);else{for(var a=!1,b=0;b<l.length;b++)if(l[b].word===d){a=!0;break}if(a)c+=SCORE_WORD_WRONG,0>c&&(c=0),this._displayWrongOnCell(),p.displayAnswer(c);else{for(b=a=0;b<n.length;b++)a+=n[b].getValue();c+=d.length*a;this._displayRightOnCell();p.displayAnswer(c);l.push({word:d,score:d.length*a});p.refreshWordWritten(l)}}this._clearMatrix()};this.onExit=function(){this.unload();
$(s_oMain).trigger("share_event",c);$(s_oMain).trigger("end_session");s_oMain.gotoMenu()};this._onStageMouseMove=function(a){h=a.stageX;g=a.stageY;for(a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_COLS;b++)if(!1===m[a][b].isActive()&&pointInRectangle(h,g,m[a][b].getRectPos())){s_oGame.onCellOver(m[a][b],m[a][b].getRow(),m[a][b].getCol());break}};this._onMSStageMouseMove=function(a){if(!window.navigator.msPointerEnabled||a.isPrimary)for(a.preventDefault(),h=parseInt(((a.pageX||a.targetTouches[0].pageX)-s_oCanvasLeft)/
s_iScaleFactor),g=parseInt(((a.pageY||a.targetTouches[0].pageY)-s_oCanvasTop)/s_iScaleFactor),a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_COLS;b++)if(!1===m[a][b].isActive()&&pointInRectangle(h,g,m[a][b].getRectPos())){s_oGame.onCellOver(m[a][b],m[a][b].getRow(),m[a][b].getCol());break}};this.update=function(){!1!==e&&(f-=s_iTimeElaps,0<f?p.updateTime(f):this._gameOver())};s_oGame=this;TIME_LEVEL=a.time_level;MAX_CHAR_VALUE=a.max_char_value;SCORE_WORD_WRONG=a.score_wrong;this._init()}var s_oGame;
function CEndPanel(){var a,e,b,c,f,h,g;this._init=function(){g=new createjs.Container;g.alpha=0;g.visible=!1;s_oStage.addChild(g);var d=createBitmap(s_oSpriteLibrary.getSprite("gameover_bg"));g.addChild(d);d=new createjs.Text(TEXT_TOT_SCORE,"56px "+FONT_GAME,"#fff");d.x=CANVAS_WIDTH/2;d.y=140;d.textAlign="center";d.textBaseline="alphabetic";g.addChild(d);a=new createjs.Text("0","56px "+FONT_GAME,"#fff");a.x=CANVAS_WIDTH/2;a.y=200;a.textAlign="center";a.textBaseline="alphabetic";g.addChild(a);d=new createjs.Text(TEXT_WORD_FOUND,
"38px "+FONT_GAME,"#fff");d.x=CANVAS_WIDTH/2;d.y=270;d.textAlign="center";d.textBaseline="alphabetic";g.addChild(d);e=new createjs.Text("0","38px "+FONT_GAME,"#fff");e.x=CANVAS_WIDTH/2;e.y=310;e.textAlign="center";e.textBaseline="alphabetic";g.addChild(e);d=new createjs.Text(TEXT_LONGEST_WORD,"38px "+FONT_GAME,"#fff");d.x=CANVAS_WIDTH/2;d.y=370;d.textAlign="center";d.textBaseline="alphabetic";g.addChild(d);b=new createjs.Text("WORD","38px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=410;b.textAlign=
"center";b.textBaseline="alphabetic";g.addChild(b);d=new createjs.Text(TEXT_BEST_WORD,"38px "+FONT_GAME,"#fff");d.x=CANVAS_WIDTH/2;d.y=470;d.textAlign="center";d.textBaseline="alphabetic";g.addChild(d);c=new createjs.Text("","38px "+FONT_GAME,"#fff");c.x=CANVAS_WIDTH/2;c.y=510;c.textAlign="center";c.textBaseline="alphabetic";g.addChild(c);d=s_oSpriteLibrary.getSprite("but_home");f=new CGfxButton(CANVAS_WIDTH/2-215,CANVAS_HEIGHT-170,d,g);f.addEventListener(ON_MOUSE_UP,this._onExit,this);d=s_oSpriteLibrary.getSprite("but_restart");
h=new CGfxButton(CANVAS_WIDTH/2+215,CANVAS_HEIGHT-170,d,g);h.addEventListener(ON_MOUSE_UP,this._onRestart,this)};this.unload=function(){f.unload()};this.show=function(d,f,h,l,m){a.text=""+d;e.text=""+f;b.text=h;""!==l&&(c.text=l+" +"+m);g.visible=!0;createjs.Tween.get(g).to({alpha:1},500).call(function(){$(s_oMain).trigger("show_interlevel_ad")});$(s_oMain).trigger("save_score",[d,s_iLangSelected])};this._onExit=function(){s_oGame.onExit()};this._onRestart=function(){s_oGame._init()};this._init();
return this}
function CCreditsPanel(){var a,e,b,c,f,h,g,d;this._init=function(){d=new createjs.Container;s_oStage.addChild(d);var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));d.addChild(k);f=new createjs.Shape;f.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.addChild(f);k=s_oSpriteLibrary.getSprite("bg_credits");e=createBitmap(k);e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2;e.regX=k.width/2;e.regY=k.height/2;d.addChild(e);c=new createjs.Text(TEXT_CREDITS_DEVELOPED,"46px "+
FONT_GAME,"#ffffff");c.x=CANVAS_WIDTH/2;c.y=270;c.textAlign="center";d.addChild(c);var k=s_oSpriteLibrary.getSprite("logo_credits"),n=createBitmap(k);n.regX=k.width/2;n.regY=k.height/2;n.x=CANVAS_WIDTH/2;n.y=390;d.addChild(n);g=new createjs.Text(TEXT_LINK1,"40px "+FONT_GAME,"#ffffff");g.x=CANVAS_WIDTH/2;g.y=450;g.textAlign="center";d.addChild(g);h=new createjs.Shape;h.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=.01;h.on("click",this._onLogoButRelease);d.addChild(h);
k=s_oSpriteLibrary.getSprite("but_exit_big");a=CANVAS_WIDTH/2+290;b=new CGfxButton(a,180,k,d);b.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){h.off("click",this._onLogoButRelease);b.unload();b=null;s_oStage.removeChild(d)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()}
function CCell(a,e,b,c,f,h){var g,d,k,n,l,m,q,r,u,t,v,p;this._init=function(a,b,c,e,f,h){g=!1;d=c;k=e;n=f;p=new createjs.Container;p.x=a;p.y=b;h.addChild(p);c=s_oSpriteLibrary.getSprite("cell_bg");e=createBitmap(c);p.addChild(e);r=createBitmap(s_oSpriteLibrary.getSprite("cell_select_bg"));r.visible=!1;p.addChild(r);m=new createjs.Text("A","44px "+FONT_GAME,"#6b6a69");m.x=c.width/2;m.y=56;m.textAlign="center";m.textBaseline="alphabetic";p.addChild(m);q=new createjs.Text(f,"20px "+FONT_GAME,"#55bcff");
q.x=15;q.y=70;q.textAlign="center";q.textBaseline="alphabetic";p.addChild(q);u=createBitmap(s_oSpriteLibrary.getSprite("cell_right"));u.alpha=0;p.addChild(u);t=createBitmap(s_oSpriteLibrary.getSprite("cell_wrong"));t.alpha=0;p.addChild(t);c=s_oSpriteLibrary.getSprite("hit_area_cell");v=new CGfxButton(c.width/2,c.height/2,c,p);v.addEventListener(ON_MOUSE_DOWN,this._onCellClicked,this);l=new createjs.Rectangle(h.x+a,h.y+b,h.x+a+c.width-20,h.y+b+c.height-20)};this.select=function(){g=!0;r.visible=!0};
this.deselect=function(){g=!1;r.visible=!1};this.setText=function(a){m.text=a};this.showRight=function(){var a=this;createjs.Tween.get(u).to({alpha:1},300).call(function(){setTimeout(function(){a.hideRight()},300)})};this.hideRight=function(){createjs.Tween.get(u).to({alpha:0},300)};this.showWrong=function(){var a=this;createjs.Tween.get(t).to({alpha:1},300).call(function(){setTimeout(function(){a.hideWrong()},300)})};this.hideWrong=function(){createjs.Tween.get(t).to({alpha:0},300)};this._onCellClicked=
function(){s_oGame.onCellSelected(this,b,c)};this.getText=function(){return m.text};this.getX=function(){return p.x};this.getY=function(){return p.y};this.getRow=function(){return d};this.getCol=function(){return k};this.getRectPos=function(){return l};this.getValue=function(){return n};this.isActive=function(){return g};this.getContainer=function(){return p};this._init(a,e,b,c,f,h)};