var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}
function getSize(a){var e=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var f=b.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var h=b.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+e+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+e+":7px!important}}</style>";f.appendChild(h);c.insertBefore(f,b.head);
a=7==h["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(f)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var e=getSize("Width");_checkOrientation(e,a);s_iScaleFactor=Math.min(a/CANVAS_HEIGHT,e/CANVAS_WIDTH);var b=CANVAS_WIDTH*s_iScaleFactor,c=CANVAS_HEIGHT*s_iScaleFactor,f;c<a?(f=a-c,c+=f,b+=CANVAS_WIDTH/CANVAS_HEIGHT*f):b<e&&(f=e-b,b+=f,c+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-c/2;var h=e/2-b/2,k=CANVAS_WIDTH/b;if(h*k<-EDGEBOARD_X||f*k<-EDGEBOARD_Y)s_iScaleFactor=
Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),e/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=CANVAS_WIDTH*s_iScaleFactor,c=CANVAS_HEIGHT*s_iScaleFactor,f=(a-c)/2,h=(e-b)/2,k=CANVAS_WIDTH/b;s_iOffsetX=-1*h*k;s_iOffsetY=-1*f*k;0<=f&&(s_iOffsetY=0);0<=h&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",b+"px");$("#canvas").css("height",
c+"px");0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",h+"px");s_oCanvasLeft=$("#canvas").offset().left;s_oCanvasTop=$("#canvas").offset().top}}
function _checkOrientation(a,e){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>e?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function createBitmap(a,e,b){var c=new createjs.Bitmap(a),f=new createjs.Shape;e&&b?f.graphics.beginFill("#fff").drawRect(0,0,e,b):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=f;return c}function createSprite(a,e,b,c,f,h){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-b,-c,f,h);a.hitArea=e;return a}
function randomFloatBetween(a,e,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(b))}function rotateVector2D(a,e){var b=e.getX()*Math.cos(a)+e.getY()*Math.sin(a),c=e.getX()*-Math.sin(a)+e.getY()*Math.cos(a);e.set(b,c)}function tweenVectorsOnX(a,e,b){return a+b*(e-a)}function shuffle(a){for(var e=a.length,b,c;0!==e;)c=Math.floor(Math.random()*e),--e,b=a[e],a[e]=a[c],a[c]=b;return a}
function bubbleSort(a){var e;do{e=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(e=a[b],a[b]=a[b+1],a[b+1]=e,e=!0)}while(e)}function compare(a,e){return a.index>e.index?-1:a.index<e.index?1:0}function easeLinear(a,e,b,c){return b*a/c+e}function easeInQuad(a,e,b,c){return b*(a/=c)*a+e}function easeInSine(a,e,b,c){return-b*Math.cos(a/c*(Math.PI/2))+b+e}function easeInCubic(a,e,b,c){return b*(a/=c)*a*a+e}
function getTrajectoryPoint(a,e){var b=new createjs.Point,c=(1-a)*(1-a),f=a*a;b.x=c*e.start.x+2*(1-a)*a*e.traj.x+f*e.end.x;b.y=c*e.start.y+2*(1-a)*a*e.traj.y+f*e.end.y;return b}function formatTime(a){a/=1E3;var e=Math.floor(a/60);a=Math.floor(a-60*e);var b="",b=10>e?b+("0"+e+":"):b+(e+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,e){var b,c;b=getBounds(a,.9);c=getBounds(e,.98);return calculateIntersection(b,c)}
function calculateIntersection(a,e){var b,c,f,h,k,l,g,m;b=a.x+(f=a.width/2);c=a.y+(h=a.height/2);k=e.x+(l=e.width/2);g=e.y+(m=e.height/2);b=Math.abs(b-k)-(f+l);c=Math.abs(c-g)-(h+m);return 0>b&&0>c?(b=Math.min(Math.min(a.width,e.width),-b),c=Math.min(Math.min(a.height,e.height),-c),{x:Math.max(a.x,e.x),y:Math.max(a.y,e.y),width:b,height:c,rect1:a,rect2:e}):null}
function getBounds(a,e){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,f=c.length,h,k;for(k=0;k<f;k++)h=getBounds(c[k],1),h.x<b.x&&(b.x=h.x),h.y<b.y&&(b.y=h.y),h.x+h.width>b.x2&&(b.x2=h.x+h.width),h.y+h.height>b.y2&&(b.y2=h.y+h.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var l,g;a instanceof createjs.Bitmap?
(f=a.sourceRect||a.image,k=f.width*e,l=f.height*e):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(f=a.spriteSheet.getFrame(a.currentFrame),k=f.rect.width,l=f.rect.height,c=f.regX,g=f.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);c=c||0;k=k||0;g=g||0;l=l||0;b.regX=c;b.regY=g;f=a.localToGlobal(0-c,0-g);h=a.localToGlobal(k-c,l-g);k=a.localToGlobal(k-c,0-g);c=a.localToGlobal(0-c,l-g);b.x=Math.min(Math.min(Math.min(f.x,
h.x),k.x),c.x);b.y=Math.min(Math.min(Math.min(f.y,h.y),k.y),c.y);b.width=Math.max(Math.max(Math.max(f.x,h.x),k.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(f.y,h.y),k.y),c.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var e=a.length,b,c;0<e;)c=Math.floor(Math.random()*e),e--,b=a[e],a[e]=a[c],a[c]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[e]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var e="hidden";e in document?document.addEventListener("visibilitychange",a):(e="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(e="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(e="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var e=window.location.search.substring(1).split("&"),b=0;b<e.length;b++){var c=e[b].split("=");if(c[0]==a)return c[1]}}
function CSpriteLibrary(){var a,e,b,c,f,h;this.init=function(k,l,g){b=e=0;c=k;f=l;h=g;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},e++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(h)};this._onSpriteLoaded=function(){c.call(h);++b==e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return e}}
var CANVAS_WIDTH=640,CANVAS_HEIGHT=960,EDGEBOARD_X=20,EDGEBOARD_Y=80,FONT="walibi0615bold",SCROLLING_BG_WIDTH=640,SCROLLING_BG_HEIGHT=741,CELL_WIDTH=110,CELL_HEIGHT=110,PARTICLE_WIDTH=70,PARTICLE_HEIGHT=70,GRID_AREA_SIZE=600,START_X_GRID=parseInt((CANVAS_WIDTH-GRID_AREA_SIZE)/2),START_Y_GRID=parseInt((CANVAS_HEIGHT-GRID_AREA_SIZE)/2),FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=
4,ON_DRAG_END=5,ORANGE=0,GREEN=1,YELLOW=2,RED=3,BLUE=4,NONE=-1,DOWN=0,UP=1,LEFT=2,RIGHT=3,CHANGED=4,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;TEXT_SELECT_LEVEL="SELECT LEVEL";TEXT_LEVEL="LEVEL";TEXT_LEVEL_COMPLETED="LEVEL COMPLETED!";TEXT_WIN1="CONGRATULATIONS!";TEXT_WIN2="YOU HAVE COMPLETED ALL THE LEVELS!";TEXT_HELP="CONNECT MATCHING FLOWERS AND COVER THE ENTIRE BOARD TO SOLVE EACH LEVEL";TEXT_HELP_TITLE="HOW TO PLAY";TEXT_SCORE="YOUR SCORE IS: ";TEXT_MOVES="MOVES";TEXT_DEVELOPED="DEVELOPED BY";
TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var a,e,b,c,f,h,k;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();k=new createjs.Container;s_oStage.addChild(k)};this.unload=function(){k.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(h).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));k.addChild(l);l=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(l);c.x=CANVAS_WIDTH/2-l.width/2;c.y=CANVAS_HEIGHT-250;k.addChild(c);a=l.width;e=l.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,e);k.addChild(f);c.mask=
f;b=new createjs.Text("","30px "+FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-250;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";k.addChild(b);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=0;k.addChild(h)};this.refreshLoader=function(h){b.text=h+"%";f.graphics.clear();h=Math.floor(h*a/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,h,e)};this._init()}
function CMain(a){var e,b=0,c=0,f=STATE_LOADING,h,k,l;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(5),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;k=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();e=!0};this.soundLoaded=function(){b++;k.refreshLoader(Math.floor(b/c*100));b===c&&this._allResourcesLoaded()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/but_press.ogg","click"),createjs.Sound.registerSound("./sounds/flower_closed.ogg","flower_closed"),createjs.Sound.registerSound("./sounds/all_level_completed.ogg","all_level_completed"),createjs.Sound.registerSound("./sounds/flower_open.ogg","flower_open"),createjs.Sound.registerSound("./sounds/next_level.ogg","next_level"),createjs.Sound.registerSound("./sounds/particle.ogg",
"particle")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/but_press.mp3","click"),createjs.Sound.registerSound("./sounds/flower_closed.mp3","flower_closed"),createjs.Sound.registerSound("./sounds/all_level_completed.mp3","all_level_completed"),createjs.Sound.registerSound("./sounds/flower_open.mp3","flower_open"),
createjs.Sound.registerSound("./sounds/next_level.mp3","next_level"),createjs.Sound.registerSound("./sounds/particle.mp3","particle")),c+=7)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_play_small","./sprites/but_play_small.png");s_oSpriteLibrary.addSprite("level_sprite","./sprites/LevelSprite.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");
s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_win","./sprites/bg_win.png");s_oSpriteLibrary.addSprite("clouds_back","./sprites/clouds_back.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");
s_oSpriteLibrary.addSprite("but_next","./sprites/but_next.png");s_oSpriteLibrary.addSprite("but_restart_big","./sprites/but_restart_big.png");s_oSpriteLibrary.addSprite("grid_spritesheet","./sprites/grid_spritesheet.png");s_oSpriteLibrary.addSprite("particle","./sprites/particle_sprite.png");s_oSpriteLibrary.addSprite("background","./sprites/background.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("but_fullscreen",
"./sprites/but_fullscreen.png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;k.refreshLoader(Math.floor(b/c*100));b===c&&this._allResourcesLoaded()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._allResourcesLoaded=function(){k.unload();jQuery.getJSON("levels.json",this.onLoadedJSON)};this.onLoadedJSON=function(a){s_aLevelsData=[];for(var b=0;b<Object.keys(a).length;b++)s_aLevelsData[b]=
{dim:a[b].dim,maxMoves:a[b].maxMoves,points:a[b].points};s_oMain._onRemovePreloader()};this._onRemovePreloader=function(){isIOS()||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1}));s_oMain.gotoMenu()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoLevelMenu=function(){new CLevelMenu(h);f=STATE_MENU};this.gotoGame=function(a,b){l=new CGame(h,a,b);f=STATE_GAME};this.gotoHelp=function(a){new CHelp(a);f=STATE_HELP};this.stopUpdate=function(){e=
!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();e=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=function(a){!1!==e&&(a=(new Date).getTime(),s_iTimeElaps=a-s_iPrevTime,s_iCntTime+=s_iTimeElaps,s_iCntFps++,s_iPrevTime=a,1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0),!s_bMobile||s_bIsIphone?(f===
STATE_GAME&&l.update(),s_oStage.update()):f===STATE_GAME?l.update():s_oStage.update())};s_oMain=this;h=a;ENABLE_CHECK_ORIENTATION=a.check_orientation;ENABLE_FULLSCREEN=a.fullscreen;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iMode,s_szImage,s_iLevelReached=1,s_bIsIphone=!1,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack=null,s_oCanvas,s_aLevelsData,s_bFullscreen=!1;
function CTextButton(a,e,b,c,f,h,k){var l,g,m,p,r;this._init=function(a,b,c,e,f,h,k){l=[];g=[];var q=createBitmap(c),t=Math.ceil(k/20);r=new createjs.Text(e,k+"px "+f,"#000000");r.textAlign="center";r.textBaseline="alphabetic";var u=r.getBounds();r.x=c.width/2+t;r.y=Math.floor(c.height/2)+u.height/3+t;p=new createjs.Text(e,k+"px "+f,h);p.textAlign="center";p.textBaseline="alphabetic";u=p.getBounds();p.x=c.width/2;p.y=Math.floor(c.height/2)+u.height/3;m=new createjs.Container;m.x=a;m.y=b;m.regX=c.width/
2;m.regY=c.height/2;m.addChild(q,r,p);s_bMobile||(m.cursor="pointer");s_oStage.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown");m.off("pressup");s_oStage.removeChild(m)};this.setVisible=function(a){m.visible=a};this._initListener=function(){oParent=this;m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){l[a]=b;g[a]=c};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(g[ON_MOUSE_UP])};
this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this.setTextPosition=function(a){p.y=a;r.y=a+2};this.setPosition=function(a,b){m.x=a;m.y=b};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};this._init(a,e,b,c,f,h,k);return this}
function CToggle(a,e,b,c){var f,h,k,l=[],g;this._init=function(a,b,c,e){h=[];k=[];var m=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=e;g=createSprite(m,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);g.x=a;g.y=b;g.stop();s_bMobile||(g.cursor="pointer");s_oStage.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);
s_oStage.removeChild(g)};this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;k[a]=c};this.addEventListenerWithParams=function(a,b,c,e){h[a]=b;k[a]=c;l=e};this.setActive=function(a){f=a;g.gotoAndStop("state_"+f)};this.buttonRelease=function(){g.scaleX=1;g.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");f=!f;g.gotoAndStop("state_"+f);h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(k[ON_MOUSE_UP],
l)};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],l)};this.setPosition=function(a,b){g.x=a;g.y=b};this.setVisible=function(a){g.visible=a};this._init(a,e,b,c)}
function CGfxButton(a,e,b,c){var f,h,k,l=[],g;this._init=function(a,b,e){f=1;h=[];k=[];g=createBitmap(e);g.x=a;g.y=b;g.regX=e.width/2;g.regY=e.height/2;s_bMobile||(g.cursor="pointer");c.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);c.removeChild(g)};this.setVisible=function(a){g.visible=a};this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,
b,c){h[a]=b;k[a]=c};this.addEventListenerWithParams=function(a,b,c,e){h[a]=b;k[a]=c;l=e};this.buttonRelease=function(){g.scaleX=f;g.scaleY=f;h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(k[ON_MOUSE_UP],l)};this.buttonDown=function(){g.scaleX=.9*f;g.scaleY=.9*f;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],l)};this.setScale=function(a){f=a;g.scaleX=a;g.scaleY=a};this.setPosition=function(a,b){g.x=a;g.y=b};this.setX=function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};
this.getX=function(){return g.x};this.getY=function(){return g.y};this._init(a,e,b,c);return this}
function CMenu(){var a,e,b,c,f,h,k,l,g,m,p,r,t=null,q=null;this._init=function(){k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(k);var w=s_oSpriteLibrary.getSprite("but_play");l=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-350,w,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)w=s_oSpriteLibrary.getSprite("audio_icon"),f=CANVAS_WIDTH-w.height/2-10,h=w.height/2+10,m=new CToggle(f,h,w,s_bAudioActive),m.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);w=s_oSpriteLibrary.getSprite("but_credits");b=w.height/2+10;c=w.height/2+10;p=new CGfxButton(b,c,w,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onButInfoRelease,this);var w=window.document,u=w.documentElement;t=u.requestFullscreen||u.mozRequestFullScreen||u.webkitRequestFullScreen||u.msRequestFullscreen;q=w.exitFullscreen||w.mozCancelFullScreen||w.webkitExitFullscreen||w.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(t=!1);t&&!1===inIframe()&&(w=s_oSpriteLibrary.getSprite("but_fullscreen"),
a=b+w.width/2+10,e=w.height/2+10,r=new CToggle(a,e,w,s_bFullscreen,s_oStage),r.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(g);createjs.Tween.get(g).to({alpha:0},1E3).call(function(){g.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){l.unload();l=null;g.visible=!1;p.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;t&&
!1===inIframe()&&r.unload();s_oStage.removeAllChildren();s_oMenu=null};this.refreshButtonPos=function(g,k){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(f-g,k+h);t&&!1===inIframe()&&r.setPosition(a+g,e+k);p.setPosition(b+g,c+k)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");!isIOS()||null!==s_oSoundtrack||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
(s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1}));s_oMain.gotoLevelMenu(0)};this._onFullscreenRelease=function(){s_bFullscreen?(q.call(window.document),s_bFullscreen=!1):(t.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};this._onButInfoRelease=function(){new CCreditsPanel};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a,e,b){var c=e,f=b,h,k,l,g,m=NONE,p=0,r,t=0,q,w,u,y,B,v,x=[],C=[],z=[],D=[],E=[],F=[],G=[],H=[],I=[],J=[],N,M=null,O=!1,Q=!1,R=!1,S=!1,P=Array(2),A,n=[],T,K,L;this._init=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack.volume=.6;$(s_oMain).trigger("start_level",[c]);var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);P[0]=new CScrollingBg(s_oSpriteLibrary.getSprite("clouds_back"),0);P[1]=new CScrollingBg(s_oSpriteLibrary.getSprite("clouds_back"),
-SCROLLING_BG_WIDTH);r=A[c].dim;q=A[c].points.length;B=y=parseInt(GRID_AREA_SIZE/r);w=u=B/2;N=new CInterface(c,t,A[c].maxMoves);T=new createjs.Container;s_oStage.addChild(T);for(var a={images:[s_oSpriteLibrary.getSprite("grid_spritesheet")],framerate:35,frames:{width:CELL_WIDTH,height:CELL_HEIGHT,regX:CELL_WIDTH/2,regY:CELL_HEIGHT/2},animations:{orange0:[0],orangeGrowing:[0,9,"orange1"],orangeDwarfing:{frames:[9,8,7,6,5,4,3,2,1,0],next:"orange0"},orange1:[9],orange2:[10],orange3:[11],orange4:[12],
orange5:[9],green0:[13],greenGrowing:[13,22,"green1"],greenDwarfing:{frames:[22,21,20,19,18,17,16,15,14,13],next:"green0"},green1:[22],green2:[23],green3:[24],green4:[25],green5:[22],yellow0:[26],yellowGrowing:[26,35,"yellow1"],yellowDwarfing:{frames:[35,34,33,32,31,30,29,28,27,26],next:"yellow0"},yellow1:[35],yellow2:[36],yellow3:[37],yellow4:[38],yellow5:[35],red0:[39],redGrowing:[39,48,"red1"],redDwarfing:{frames:[48,47,46,45,44,43,42,41,40,39],next:"red0"},red1:[48],red2:[49],red3:[50],red4:[51],
red5:[48],blue0:[52],blueGrowing:[52,61,"blue1"],blueDwarfing:{frames:[61,60,59,58,57,56,55,54,53,52],next:"blue0"},blue1:[61],blue2:[62],blue3:[63],blue4:[64],blue5:[61],heavenly0:[65],heavenlyGrowing:[65,74,"heavenly1"],heavenlyDwarfing:{frames:[74,73,72,71,70,69,68,67,66,65],next:"heavenly0"},heavenly1:[74],heavenly2:[75],heavenly3:[76],heavenly4:[77],heavenly5:[74],violet0:[78],violetGrowing:[78,87,"violet1"],violetDwarfing:{frames:[87,86,84,83,82,81,80,79,78],next:"violet0"},violet1:[87],violet2:[88],
violet3:[89],violet4:[90],violet5:[87],pink0:[91],pinkGrowing:[91,100,"pink1"],pinkDwarfing:{frames:[100,99,98,97,96,95,94,93,92,91],next:"pink0"},pink1:[100],pink2:[101],pink3:[102],pink4:[103],pink5:[100],orangeyellow0:[104],orangeyellowGrowing:[104,113,"orangeyellow1"],orangeyellowDwarfing:{frames:[113,112,111,110,109,108,107,106,105,104],next:"orangeyellow0"},orangeyellow1:[113],orangeyellow2:[114],orangeyellow3:[115],orangeyellow4:[116],orangeyellow5:[113],purple0:[117],purpleGrowing:[117,126,
"purple1"],purpleDwarfing:{frames:[126,125,124,123,122,121,120,119,118,117],next:"purple0"},purple1:[126],purple2:[127],purple3:[128],purple4:[129],purple5:[126],hide:[130]}},a=new createjs.SpriteSheet(a),b=0;b<r;b++){n[b]=[];for(var d=0;d<r;d++)n[b][d]=new CCell(a,b,d,START_X_GRID+d*y+w,START_Y_GRID+b*B+u,T,"hide",GRID_AREA_SIZE/r/CELL_WIDTH)}for(a=0;a<q;a++)n[A[c].points[a].start_r][A[c].points[a].start_c].changeCellState(A[c].points[a].color,0,0,m,NONE,!0),n[A[c].points[a].end_r][A[c].points[a].end_c].changeCellState(A[c].points[a].color,
0,0,m,NONE,!0);R=!0;s_oStage.on("stagemousemove",this.onMouseMove,this);s_bMobile&&!s_bIsIphone&&s_oStage.update()};this.onCellClick=function(a,b,d){if(R){h=b;k=d;n[b][d].getX();n[b][d].getY();v=n[b][d].getValue();if(0===n[b][d].getState()||1===n[b][d].getState()||5===n[b][d].getState()){this._cancelThisLineColor(v);switch(v){case "orange":x.push({r:b,c:d});break;case "green":C.push({r:b,c:d});break;case "yellow":z.push({r:b,c:d});break;case "red":D.push({r:b,c:d});break;case "blue":E.push({r:b,c:d});
break;case "heavenly":F.push({r:b,c:d});break;case "violet":G.push({r:b,c:d});break;case "pink":H.push({r:b,c:d});break;case "orangeyellow":I.push({r:b,c:d});break;case "purple":J.push({r:b,c:d})}O=!0}else if(2===n[b][d].getState()||3===n[b][d].getState()||4===n[b][d].getState()){var c=this.getCellPositionInArray(b,d,n[b][d].getValue()),e;switch(v){case "orange":e=x;break;case "green":e=C;break;case "yellow":e=z;break;case "red":e=D;break;case "blue":e=E;break;case "heavenly":e=F;break;case "violet":e=
G;break;case "pink":e=H;break;case "orangeyellow":e=I;break;case "purple":e=J}c.arrayDim>c.index+1&&this._cancelNextLines(c.index+1,n[b][d].getValue(),e);a=e[c.index-1].r;e=e[c.index-1].c;if(1===n[a][e].getState())n[b][d].changeCellState(v,2,n[a][e].getRotation()-180,n[a][e].getDirection(),n[a][e].getDirection());else if(4===n[a][e].getState()){var f;switch(n[a][e].getDirectionNoChange()){case UP:f=90;break;case DOWN:f=-90;break;case LEFT:f=0;break;case RIGHT:f=180}n[b][d].changeCellState(v,2,f,n[a][e].getDirectionNoChange(),
n[a][e].getDirectionNoChange())}else n[b][d].changeCellState(v,2,n[a][e].getRotation(),n[a][e].getDirection(),n[a][e].getDirection());O=!0}s_bMobile&&!s_bIsIphone&&s_oStage.update()}};this.onMouseMove=function(a){O&&(l=s_oStage.mouseX,g=s_oStage.mouseY,S=!0)};this.releaseForm=function(a){S=Q=O=!1;s_bMobile&&!s_bIsIphone&&s_oStage.update()};this.getCellPositionInArray=function(a,b,d){switch(d){case "orange":for(d=0;d<x.length;d++)if(x[d].r===a&&x[d].c===b)return{index:d,arrayDim:x.length};break;case "green":for(d=
0;d<C.length;d++)if(C[d].r===a&&C[d].c===b)return{index:d,arrayDim:C.length};break;case "yellow":for(d=0;d<z.length;d++)if(z[d].r===a&&z[d].c===b)return{index:d,arrayDim:z.length};break;case "red":for(d=0;d<D.length;d++)if(D[d].r===a&&D[d].c===b)return{index:d,arrayDim:D.length};break;case "blue":for(d=0;d<E.length;d++)if(E[d].r===a&&E[d].c===b)return{index:d,arrayDim:E.length};break;case "heavenly":for(d=0;d<F.length;d++)if(F[d].r===a&&F[d].c===b)return{index:d,arrayDim:F.length};break;case "violet":for(d=
0;d<G.length;d++)if(G[d].r===a&&G[d].c===b)return{index:d,arrayDim:G.length};break;case "pink":for(d=0;d<H.length;d++)if(H[d].r===a&&H[d].c===b)return{index:d,arrayDim:H.length};break;case "orangeyellow":for(d=0;d<I.length;d++)if(I[d].r===a&&I[d].c===b)return{index:d,arrayDim:I.length};break;case "purple":for(d=0;d<J.length;d++)if(J[d].r===a&&J[d].c===b)return{index:d,arrayDim:J.length}}};this.updateColorArray=function(a,b,d){switch(a){case "orange":x.push({r:b,c:d});break;case "green":C.push({r:b,
c:d});break;case "yellow":z.push({r:b,c:d});break;case "red":D.push({r:b,c:d});break;case "blue":E.push({r:b,c:d});break;case "heavenly":F.push({r:b,c:d});break;case "violet":G.push({r:b,c:d});break;case "pink":H.push({r:b,c:d});break;case "orangeyellow":I.push({r:b,c:d});break;case "purple":J.push({r:b,c:d})}};this._cancelNextLines=function(a,b,d){d.length;for(var c=a;c<d.length;c++)5===n[d[c].r][d[c].c].getState()?(n[d[c].r][d[c].c].flowerDwarfing(0,0,NONE,NONE),p--):0<n[d[c].r][d[c].c].getState()&&
n[d[c].r][d[c].c].changeCellState("hide",null,0,NONE,NONE,!0);a===d.length?d.pop():d.splice(a,d.length-a);1===d.length&&this._cancelThisLineColor(b)};this.checkIfLevelCompleted=function(){for(var a=0;a<r;a++)for(var b=0;b<r;b++)if("hide"===n[a][b].getValue())return!1;return!0};this._cancelThisLineColor=function(a){switch(a){case "orange":x=[];break;case "green":C=[];break;case "yellow":z=[];break;case "red":D=[];break;case "blue":E=[];break;case "heavenly":F=[];break;case "violet":G=[];break;case "pink":H=
[];break;case "orangeyellow":I=[];break;case "purple":J=[]}for(var b=0;b<r;b++)for(var d=0;d<r;d++)n[b][d].getValue()===a&&5===n[b][d].getState()?(n[b][d].flowerDwarfing(0,0,NONE,NONE),p--):n[b][d].getValue()===a&&1<n[b][d].getState()?n[b][d].changeCellState("hide",null,0,NONE,!1):n[b][d].getValue()===a&&1===n[b][d].getState()&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("flower_closed"),n[b][d].flowerDwarfing(0,0,NONE,NONE))};this.checkIfNextIsGoal=function(a,b){return!1===this._checkIfNotOccupied(a,
b)&&n[h][k].getValue()===n[a][b].getValue()&&0===n[a][b].getState()?!0:!1};this._checkIfNear=function(a,b,d,c){return a<d&&b===c?(m=DOWN,{r:1,c:0}):a>d&&b===c?(m=UP,{r:-1,c:0}):a===d&&b>c?(m=LEFT,{r:0,c:-1}):a===d&&b<c?(m=RIGHT,{r:0,c:1}):null};this.checkIfThereIsAnotherLineNear=function(a,b){return 0<b&&n[a][b-1].getValue()===v&&5!==n[a][b-1].getState()?LEFT:0<a&&n[a-1][b].getValue()===v&&5!==n[a-1][b].getState()?UP:a<r-1&&n[a+1][b].getValue()===v&&5!==n[a+1][b].getState()?DOWN:b<r-1&&n[a][b+1].getValue()===
v&&5!==n[a][b+1].getState()?RIGHT:null};this._checkIfNotOccupied=function(a,b){return"hide"===n[a][b].getValue()&&h>=a-1&&h<=a+1&&k>=b-1&&k<=b+1?!0:!1};this._getTypeSprite=function(a,b){var d={typeOld:NONE,typeNew:NONE,rotationOld:0,rotationNew:0,changeSprite:!1};switch(b){case DOWN:switch(a){case LEFT:d.rotationOld=90;d.typeOld=4;d.rotationNew=0;d.typeNew=2;break;case RIGHT:d.rotationOld=180;d.typeOld=4;d.rotationNew=180;d.typeNew=2;break;case DOWN:d.rotationOld=270;d.typeOld=3;d.rotationNew=-90;
d.typeNew=2;break;case UP:d.rotationOld=90;d.typeOld=3;d.rotationNew=-90;d.typeNew=2;break;case NONE:d.rotationOld=0,d.typeOld=1,d.rotationNew=180,d.typeNew=2}break;case UP:switch(a){case LEFT:d.rotationOld=0;d.typeOld=4;d.rotationNew=0;d.typeNew=2;break;case RIGHT:d.rotationOld=270;d.typeOld=4;d.rotationNew=180;d.typeNew=2;break;case UP:d.rotationOld=90;d.typeOld=3;d.rotationNew=90;d.typeNew=2;break;case DOWN:d.rotationOld=270;d.typeOld=3;d.rotationNew=-90;d.typeNew=2;break;case NONE:d.rotationOld=
0,d.typeOld=1,d.rotationNew=180,d.typeNew=2}break;case LEFT:switch(a){case UP:d.rotationOld=180;d.typeOld=4;d.rotationNew=90;d.typeNew=2;break;case DOWN:d.rotationOld=270;d.typeOld=4;d.rotationNew=-90;d.typeNew=2;break;case LEFT:d.rotationOld=0;d.typeOld=3;d.rotationNew=0;d.typeNew=2;break;case RIGHT:d.rotationOld=180;d.typeOld=3;d.rotationNew=0;d.typeNew=2;break;case NONE:d.rotationOld=90,d.typeOld=1,d.rotationNew=-90,d.typeNew=2}break;case RIGHT:switch(a){case DOWN:d.rotationOld=0;d.typeOld=4;d.rotationNew=
-90;d.typeNew=2;break;case UP:d.rotationOld=90;d.typeOld=4;d.rotationNew=90;d.typeNew=2;break;case RIGHT:d.rotationOld=180;d.typeOld=3;d.rotationNew=180;d.typeNew=2;break;case LEFT:d.rotationOld=0;d.typeOld=3;d.rotationNew=0;d.typeNew=2;break;case NONE:d.rotationOld=90,d.typeOld=1,d.rotationNew=-90,d.typeNew=2}break;case NONE:switch(a){case LEFT:d.rotationOld=180;d.typeOld=1;d.rotationNew=0;d.typeNew=2;break;case RIGHT:d.rotationOld=0;d.typeOld=1;d.rotationNew=180;d.typeNew=2;break;case DOWN:d.rotationOld=
90;d.typeOld=1;d.rotationNew=-90;d.typeNew=2;break;case UP:d.rotationOld=-90,d.typeOld=1,d.rotationNew=90,d.typeNew=2}}return d};this.unload=function(){N.unload();for(var a=0;a<r;a++)for(var b=0;b<r;b++)n[a][b].unload();n=[];x=[];C=[];z=[];D=[];E=[];F=[];G=[];H=[];I=[];J=[];s_oStage.off("stagemousemove",this.onMouseMove,this);createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this.onRestart=function(){$(s_oMain).trigger("restart_level",
c);$(s_oMain).trigger("show_interlevel_ad");this._cancelThisLineColor("orange");this._cancelThisLineColor("green");this._cancelThisLineColor("yellow");this._cancelThisLineColor("red");this._cancelThisLineColor("blue");this._cancelThisLineColor("heavenly");this._cancelThisLineColor("violet");this._cancelThisLineColor("pink");this._cancelThisLineColor("orangeyellow");for(this._cancelThisLineColor("purple");0<t;t--)f=t>A[c].maxMoves-q?f-5:f-10};this.endPanel=function(){c++;R=!1;c<A.length?s_bMobile&&
!s_bIsIphone?setTimeout(function(){M=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"),c-1,f);s_iLevelReached<c+1&&(s_iLevelReached=c+1);M.nextLevel()},500):(M=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"),c-1,f),s_iLevelReached<c+1&&(s_iLevelReached=c+1),M.nextLevel()):s_bMobile&&!s_bIsIphone?setTimeout(function(){M=CEndPanel(s_oSpriteLibrary.getSprite("bg_win"),c-1,f);M.lastLevelCompleted()},500):(M=CEndPanel(s_oSpriteLibrary.getSprite("bg_win"),c-1,f),M.lastLevelCompleted())};this.nextLevel=function(){this.unload();
s_oMain.gotoGame(c,f)};this.update=function(){if(!s_bMobile||s_bIsIphone)P[0].move(),P[1].move();if(S){var a=h,b=k,d=n[a][b].getDirectionNoChange();if(l>START_X_GRID&&l<=START_X_GRID+GRID_AREA_SIZE&&g>START_Y_GRID&&g<=START_Y_GRID+GRID_AREA_SIZE){var e=Math.floor((g-START_Y_GRID)/y),u=Math.floor((l-START_X_GRID)/B);if(!(e!==a&&0<=e||u!==b&&0<=u))return;var r=this._checkIfNear(a,b,e,u),w=n[e][u].getValue();if(null!==r)if(this._checkIfNotOccupied(e,u)){if(null!==this.checkIfThereIsAnotherLineNear(e,
u)){d=this._getTypeSprite(m,d);if(!Q){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_bMobile&&!s_bIsIphone||createjs.Sound.play("particle");Q=!0}1===d.typeOld?n[a][b].flowerGrow(d.typeOld,d.rotationOld,m,m):n[a][b].changeCellState(v,d.typeOld,d.rotationOld,m,m,!1);a+=r.r;b+=r.c;n[a][b].changeCellState(v,d.typeNew,d.rotationNew,m,m,!0);h+=r.r;k+=r.c;this.updateColorArray(v,a,b);f=t<A[c].maxMoves-q?f+10:f-5;t++;N.refreshScore(t,A[c].maxMoves)}}else if(this.checkIfNextIsGoal(e,u))null!==this.checkIfThereIsAnotherLineNear(e,
u)&&(d=this._getTypeSprite(m,d),n[a][b].changeCellState(v,d.typeOld,d.rotationOld,m,m,!1),a+=r.r,b+=r.c,n[a][b].flowerGrow(5,d.rotationNew,m,m),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("flower_open"),this.updateColorArray(v,a,b),O=!1,p++,f=t<A[c].maxMoves-q?f+10:f-5,t++,N.refreshScore(t,A[c].maxMoves),p===q&&this.checkIfLevelCompleted()?this.endPanel():p!==q||this.checkIfLevelCompleted()||(K=new createjs.Text("YOU HAVE TO FILL ALL THE CELLS"," 50px "+FONT,"#730358"),K.x=CANVAS_WIDTH/
2,K.y=-100,K.textAlign="center",K.textBaseline="alphabetic",K.lineWidth=500,K.outline=4,s_oStage.addChild(K),L=new createjs.Text("YOU HAVE TO FILL ALL THE CELLS"," 50px "+FONT,"#ffffff"),L.x=CANVAS_WIDTH/2,L.y=-100,L.textAlign="center",L.textBaseline="alphabetic",L.lineWidth=500,s_oStage.addChild(L),createjs.Tween.get(K).to({y:CANVAS_HEIGHT/2},1E3,createjs.Ease.bounceOut).wait(500).call(function(){createjs.Tween.get(K).to({y:-100},1E3,createjs.Ease.backIn).wait(500).call(function(){s_oStage.removeChild(this)})}),
createjs.Tween.get(L).to({y:CANVAS_HEIGHT/2},1E3,createjs.Ease.bounceOut).wait(500).call(function(){createjs.Tween.get(L).to({y:-100},1E3,createjs.Ease.backIn).wait(500).call(function(){s_oStage.removeChild(this)})})));else if(1<n[e][u].getState()&&5>n[e][u].getState()&&w!==v&&null!==this.checkIfThereIsAnotherLineNear(e,u)){if(e=this.getCellPositionInArray(e,u,w)){switch(w){case "orange":this._cancelNextLines(e.index,w,x);break;case "green":this._cancelNextLines(e.index,w,C);break;case "yellow":this._cancelNextLines(e.index,
w,z);break;case "red":this._cancelNextLines(e.index,w,D);break;case "blue":this._cancelNextLines(e.index,w,E);break;case "heavenly":this._cancelNextLines(e.index,w,F);break;case "violet":this._cancelNextLines(e.index,w,G);break;case "pink":this._cancelNextLines(e.index,w,H);break;case "orangeyellow":this._cancelNextLines(e.index,w,I);break;case "purple":this._cancelNextLines(e.index,w,J)}d=this._getTypeSprite(m,d);1===d.typeOld&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("flower_open"));
n[a][b].changeCellState(v,d.typeOld,d.rotationOld,m,m,!1);a+=r.r;b+=r.c;n[a][b].changeCellState(v,d.typeNew,d.rotationNew,m,m,!0);h+=r.r;k+=r.c;this.updateColorArray(v,a,b)}f=t<A[c].maxMoves-q?f+10:f-5;t++;N.refreshScore(t,A[c].maxMoves)}}s_bMobile&&!s_bIsIphone&&s_oStage.update()}};s_oGame=this;A=s_aLevelsData;this._init()}var s_oGame;
function CInterface(a,e,b){var c,f,h,k,l,g,m,p,r,t,q,w,u,y,B,v,x,C=null;this._init=function(a,b,e){var z=s_oSpriteLibrary.getSprite("but_exit");r=CANVAS_WIDTH-z.height/2-10;t=z.height/2+10;w=new CGfxButton(r,t,z,s_oStage);w.addEventListener(ON_MOUSE_UP,this._onExit,this);c=CANVAS_WIDTH-z.width/2-70;f=z.height/2+10;z=s_oSpriteLibrary.getSprite("but_restart");u=new CGfxButton(c,f,z,s_oStage);u.addEventListener(ON_MOUSE_UP,this._onRestart,this);m=c-55;p=z.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===
s_bMobile)z=s_oSpriteLibrary.getSprite("audio_icon"),q=new CToggle(m,p,z,s_bAudioActive),q.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);l=CANVAS_WIDTH/2-150;g=70;y=new createjs.Text(TEXT_LEVEL+": "+(a+1)," 50px "+FONT,"#730358");y.x=l;y.y=g;y.textAlign="center";y.textBaseline="alphabetic";y.lineWidth=500;y.outline=4;s_oStage.addChild(y);B=new createjs.Text(TEXT_LEVEL+": "+(a+1)," 50px "+FONT,"#ffffff");B.x=l;B.y=g;B.textAlign="center";B.textBaseline="alphabetic";B.lineWidth=500;s_oStage.addChild(B);
h=CANVAS_WIDTH/2+100;k=CANVAS_HEIGHT-25;v=new createjs.Text(TEXT_MOVES+": "+b+"/"+e," 50px "+FONT,"#730358");v.x=h;v.y=k;v.textAlign="center";v.textBaseline="alphabetic";v.lineWidth=500;v.outline=4;s_oStage.addChild(v);x=new createjs.Text(TEXT_MOVES+": "+b+"/"+e," 50px "+FONT,"#ffffff");x.x=h;x.y=k;x.textAlign="center";x.textBaseline="alphabetic";x.lineWidth=500;s_oStage.addChild(x);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q.unload(),
q=null;w.unload();null!==C&&C.unload();s_oInterface=null};this.refreshButtonPos=function(a,b){w.setPosition(r-a,b+t);u.setPosition(c-a,b+f);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||q.setPosition(m-a,b+p);B.y=g+b;y.y=g+b;x.y=k-b;v.y=k-b};this.refreshScore=function(a){x.text=TEXT_MOVES+": "+a+"/"+b;v.text=TEXT_MOVES+": "+a+"/"+b};this._onButHelpRelease=function(){C=new CHelpPanel};this._onButRestartRelease=function(){s_oGame.restartGame()};this.onExitFromHelp=function(){C.unload()};this._onAudioToggle=
function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive;s_bMobile&&!s_bIsIphone&&s_oStage.update()};this._onExit=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oGame.onExit();$(s_oMain).trigger("end_level");$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};this._onRestart=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oGame.onRestart()};s_oInterface=this;this._init(a,e,b);
return this}var s_oInterface=null;
function CEndPanel(a,e,b){var c,f,h,k,l,g,m,p,r,t;this._init=function(a,b,e){$(s_oMain).trigger("end_level",[b]);c=createBitmap(a);c.x=0;c.y=0;f=new createjs.Container;if(!s_bMobile||s_bIsIphone)f.alpha=0,f.visible=!1;h=new createjs.Container;k=new createjs.Container;l=new createjs.Text(""," 40px "+FONT,"#730358");l.x=CANVAS_WIDTH/2;l.y=CANVAS_HEIGHT/2-120;l.textAlign="center";l.textBaseline="alphabetic";l.outline=4;l.lineWidth=500;g=new createjs.Text(""," 40px "+FONT,"#ffffff");g.x=CANVAS_WIDTH/
2;g.y=CANVAS_HEIGHT/2-120;g.textAlign="center";g.textBaseline="alphabetic";g.lineWidth=500;m=new createjs.Text(""," 40px "+FONT,"#730358");m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2-50;m.textAlign="center";m.textBaseline="alphabetic";m.outline=4;m.lineWidth=500;p=new createjs.Text(""," 40px "+FONT,"#ffffff");p.x=CANVAS_WIDTH/2;p.y=CANVAS_HEIGHT/2-50;p.textAlign="center";p.textBaseline="alphabetic";p.lineWidth=500;r=createBitmap(s_oSpriteLibrary.getSprite("but_next"));r.x=CANVAS_WIDTH/2+30;r.y=CANVAS_HEIGHT/
2;h.addChild(r);t=createBitmap(s_oSpriteLibrary.getSprite("but_restart_big"));t.x=CANVAS_WIDTH/2-140;t.y=CANVAS_HEIGHT/2;k.addChild(t);k.on("mousedown",this._onExit,this);f.addChild(c,l,g,m,p,k);s_oStage.addChild(f)};this._onNextLevel=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oStage.removeChild(f);$(s_oMain).trigger("show_interlevel_ad");h.off("mousedown",this._onNextLevel,this);s_oGame.nextLevel()};this.nextLevel=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==
s_bMobile||createjs.Sound.play("next_level");l.text=TEXT_LEVEL_COMPLETED;g.text=TEXT_LEVEL_COMPLETED;m.text=TEXT_SCORE+b;p.text=TEXT_SCORE+b;f.addChild(h);h.on("mousedown",this._onNextLevel,this);f.visible=!0;s_bMobile&&!s_bIsIphone||createjs.Tween.get(f).wait(400).to({alpha:1},500).call(function(){});$(s_oMain).trigger("save_score",[b]);$(s_oMain).trigger("share_event",[b]);s_bMobile&&!s_bIsIphone&&s_oStage.update()};this.lastLevelCompleted=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("all_level_completed");
l.font=" 30px "+FONT;g.font=" 30px "+FONT;l.text=TEXT_WIN1+"\n"+TEXT_WIN2;g.text=TEXT_WIN1+"\n"+TEXT_WIN2;t.x=CANVAS_WIDTH/2-50;t.y=CANVAS_HEIGHT/2+20;f.visible=!0;s_bMobile&&!s_bIsIphone||createjs.Tween.get(f).wait(400).to({alpha:1},500).call(function(){});var a="You reached level <strong>"+(e+1)+" </strong> with <strong>"+b+"</strong> points!<br><br>Share your score with your friends!",c="I've reached level "+(e+1)+" with "+b+" points! Can you do better?";$(s_oMain).trigger("save_score",[b]);$(s_oMain).trigger("share_event",
["200x200.jpg","Congratulations!",a,c]);s_bMobile&&!s_bIsIphone&&s_oStage.update()};this._onExit=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");f.off("mousedown",this._onExit);s_oStage.removeChild(f);s_oGame.onExit();$(s_oMain).trigger("end_level");$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};this._init(a,e,b);return this}
function CCell(a,e,b,c,f,h,k,l){var g,m=NONE,p=NONE,r,t,q;this._init=function(a,b,c,e,f,h,k,m){t=k;g=null;b=createBitmap(s_oSpriteLibrary.getSprite("background"));b.x=e;b.y=f;b.regX=CELL_WIDTH/2;b.regY=CELL_HEIGHT/2;b.scaleX=b.scaleY=l;h.addChild(b);q=createSprite(a,k,CELL_WIDTH/2*m,CELL_HEIGHT/2*m,CELL_WIDTH*m,CELL_HEIGHT*m);q.x=e;q.y=f;q.scaleX=q.scaleY=l;h.addChild(q);s_bMobile||(q.cursor="pointer");q.on("mousedown",this._onCellClick,this);q.on("pressup",this._releaseForm,this)};this.changeCellState=
function(a,b,e,h,v,x){if("hide"===a)q.alpha=1,!s_bMobile||s_bIsIphone?createjs.Tween.get(q,{override:!0}).to({alpha:0},150).call(function(){q.gotoAndStop(a);t=a;g=b;m=v;p=h;q.rotation=e}):(q.gotoAndStop(a),t=a,g=b,m=v,p=h,q.rotation=e);else if(x&&5!==b&&0!==b){if(q.gotoAndStop(a+b),!s_bMobile||s_bIsIphone){q.alpha=0;createjs.Tween.get(q,{override:!0}).to({alpha:1},500).call(function(){});r=s_oSpriteLibrary.getSprite("particle");x=new createjs.SpriteSheet({images:[r],framerate:35,frames:{width:PARTICLE_WIDTH,
height:PARTICLE_HEIGHT,regX:PARTICLE_WIDTH/2,regY:PARTICLE_HEIGHT/2},animations:{idle:[0,15]}});x=createSprite(x,k,PARTICLE_WIDTH/2,PARTICLE_HEIGHT/2,PARTICLE_WIDTH,PARTICLE_HEIGHT);switch(h){case UP:x.x=c;x.y=f+CELL_HEIGHT/2;break;case DOWN:x.x=c;x.y=f-CELL_HEIGHT/2;break;case LEFT:x.x=c+CELL_WIDTH/2;x.y=f;break;case RIGHT:x.x=c-CELL_WIDTH/2,x.y=f}x.gotoAndPlay("idle");x.scaleX=x.scaleY=l;s_oStage.addChild(x);createjs.Tween.get(x).to({alpha:0},500).call(function(){s_oStage.addChild(this)})}}else q.gotoAndStop(a+
b);"hide"!==a&&(t=a,g=b,m=v,p=h,q.rotation=e)};this.flowerGrow=function(a,b,c,e){!s_bMobile||s_bIsIphone?q.gotoAndPlay(t+"Growing"):q.gotoAndStop(t+"5");g=a;m=e;p=c;q.rotation=b};this.flowerDwarfing=function(a,b,c,e){!s_bMobile||s_bIsIphone?(q.gotoAndPlay(t+"Dwarfing"),createjs.Tween.get(q,{override:!0}).to({rotation:b},150).call(function(){})):(q.gotoAndStop(t+"0"),q.rotation=b);g=a;m=e;p=c};this._onCellClick=function(a){s_oGame.onCellClick(a,e,b)};this._releaseForm=function(a){s_oGame.releaseForm(a)};
this.getX=function(){return c};this.getY=function(){return f};this.getValue=function(){return t};this.getState=function(){return g};this.getDirection=function(){return m};this.getDirectionNoChange=function(){return p};this.getRotation=function(){return q.rotation};this.unload=function(){q.off("mousedown",this._onCellClick,this);q.off("pressup",this._releaseForm,this)};s_oCell=this;this._init(a,e,b,c,f,h,k,l)}
function CLevelMenu(a){var e,b,c,f,h,k,l,g=[],m,p,r,t,q=null,w=null;this._init=function(){m=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));m.x=0;m.y=0;s_oStage.addChild(m);m=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));s_oStage.addChild(m);l=new createjs.Text(TEXT_SELECT_LEVEL," 50px "+FONT,"#730358");l.x=CANVAS_WIDTH/2;l.y=360;l.textAlign="center";l.textBaseline="alphabetic";l.lineWidth=1E3;l.outline=4;s_oStage.addChild(l);l=new createjs.Text(TEXT_SELECT_LEVEL," 50px "+FONT,"#ffffff");
l.x=CANVAS_WIDTH/2;l.y=360;l.textAlign="center";l.textBaseline="alphabetic";l.lineWidth=1E3;s_oStage.addChild(l);for(var u=CANVAS_WIDTH/2,y=0,B=50,v=0;v<a.levels.length;v++,y+=100)400<y&&(y=0,B+=100),v<s_iLevelReached?g.push(new CLevelBut(u-200+y,375+B,s_oSpriteLibrary.getSprite("level_sprite"),!0,v+1)):g.push(new CLevelBut(u-200+y,375+B,s_oSpriteLibrary.getSprite("level_sprite"),!1,v+1)),0===v?g[v].addEventListenerWithParams(ON_MOUSE_UP,this._onClickHelp,this,v):g[v].addEventListenerWithParams(ON_MOUSE_UP,
this._onClick,this,v),s_bFirstTime=!0;u=s_oSpriteLibrary.getSprite("but_exit");h=CANVAS_WIDTH-u.height/2-10;k=u.height/2+10;p=new CGfxButton(h,k,u,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onExit,this);c=CANVAS_WIDTH-u.width/2-70;f=u.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u=s_oSpriteLibrary.getSprite("audio_icon"),r=new CToggle(c,f,u,s_bAudioActive),r.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);u=window.document;y=u.documentElement;q=y.requestFullscreen||y.mozRequestFullScreen||
y.webkitRequestFullScreen||y.msRequestFullscreen;w=u.exitFullscreen||u.mozCancelFullScreen||u.webkitExitFullscreen||u.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(q=!1);q&&!1===inIframe()&&(u=s_oSpriteLibrary.getSprite("but_fullscreen"),e=u.width/4+10,b=u.height/2+10,t=new CToggle(e,b,u,s_bFullscreen,s_oStage),t.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){for(var b=0;b<a.levels.length;b++)g[b].unload();q&&!1===inIframe()&&
t.unload();s_oLevelMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(a,g){p.setPosition(h-a,g+k);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.setPosition(c-a,g+f);q&&!1===inIframe()&&t.setPosition(e+a,b+g)};this._onNumModeToggle=function(a){a===NUM_ACTIVE?((void 0).setActive(!1),(void 0).setActive(!0)):((void 0).setActive(!0),(void 0).setActive(!1))};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onClick=function(a){!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");g[a].ifClickable()&&(s_oLevelMenu.unload(),s_oMain.gotoGame(a,0))};this._onClickHelp=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");g[a].ifClickable()&&(s_oLevelMenu.unload(),s_oMain.gotoHelp(a))};this._onExit=function(){s_oLevelMenu.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_level");$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};this._onFullscreenRelease=function(){s_bFullscreen?
(w.call(window.document),s_bFullscreen=!1):(q.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(a,e,b,c,f){var h,k,l,g=[],m=[],p;this._init=function(a,b,c,e){k=[];l=[];var m=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});h=e;p=createSprite(m,"state_"+h,c.width/2/2,c.height/2,c.width/2,c.height);p.mouseEnabled=e;p.x=a;p.y=b;p.stop();s_bMobile||(p.cursor="pointer");s_oStage.addChild(p);g.push(p);c=new createjs.Text(f,"40px "+FONT,"#79035c");c.x=a;c.y=b+15;c.textAlign=
"center";c.textBaseline="alphabetic";c.lineWidth=200;c.outline=4;s_oStage.addChild(c);c=new createjs.Text(f,"40px "+FONT,"#ffffff");c.x=a;c.y=b+15;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=200;s_oStage.addChild(c);this._initListener()};this.unload=function(){p.off("mousedown",this.buttonDown);p.off("pressup",this.buttonRelease);s_oStage.removeChild(p)};this._initListener=function(){p.on("mousedown",this.buttonDown);p.on("pressup",this.buttonRelease)};this.viewBut=function(a){s_oStage.addChild(a)};
this.addEventListener=function(a,b,c){k[a]=b;l[a]=c};this.addEventListenerWithParams=function(a,b,c,e){k[a]=b;l[a]=c;m=e};this.ifClickable=function(){return!0===p.mouseEnabled?1:0};this.setActive=function(a,b){h=b;g[a].gotoAndStop("state_"+h);g[a].mouseEnabled=!0};this.buttonRelease=function(){p.scaleX=1;p.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");h=!h;p.gotoAndStop("state_"+h);k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(l[ON_MOUSE_UP],m)};this.buttonDown=function(){p.scaleX=
.9;p.scaleY=.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],m)};this.setPosition=function(a,b){p.x=a;p.y=b};this.setVisible=function(a){p.visible=a};this._init(a,e,b,c)}
function CHelp(a){var e,b,c,f,h,k,l,g;this._init=function(a){e=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));e.x=0;e.y=0;c=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));c.x=0;c.y=0;f=new createjs.Text(TEXT_HELP_TITLE," 50px "+FONT,"#730358");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-230;f.textAlign="center";f.textBaseline="alphabetic";f.outline=6;f.lineWidth=470;h=new createjs.Text(TEXT_HELP_TITLE," 50px "+FONT,"#ffd800");h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2-230;h.textAlign="center";h.textBaseline=
"alphabetic";h.lineWidth=470;k=new createjs.Text(TEXT_HELP," 30px "+FONT,"#730358");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2+80;k.textAlign="center";k.textBaseline="alphabetic";k.outline=2;k.lineWidth=470;l=new createjs.Text(TEXT_HELP," 30px "+FONT,"#ffffff");l.x=CANVAS_WIDTH/2;l.y=CANVAS_HEIGHT/2+80;l.textAlign="center";l.textBaseline="alphabetic";l.lineWidth=470;b=new createjs.Container;b.addChild(e,c,f,h,l,k);a=s_oSpriteLibrary.getSprite("but_play_small");g=new CGfxButton(CANVAS_WIDTH/2+195,CANVAS_HEIGHT-
230,a,b);g.addEventListener(ON_MOUSE_UP,this._onExit,this);b.alpha=0;s_oStage.addChild(b);createjs.Tween.get(b).to({alpha:1},500).call(function(){})};this._onExit=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");g.unload();s_oStage.removeChild(b);s_oMain.gotoGame(a,0)};this._init(a);return this}
function CScrollingBg(a,e){var b,c;this._init=function(a,e){b=a;c=createBitmap(b);s_oStage.addChild(c);c.x=e;c.y=175;c.regX=0};this.move=function(){c.x++;c.x>CANVAS_WIDTH&&(c.x=-SCROLLING_BG_WIDTH)};this._init(a,e)}
function CCreditsPanel(){var a,e,b,c,f,h,k,l;this._init=function(){l=new createjs.Container;s_oStage.addChild(l);var g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));l.addChild(g);f=new createjs.Shape;f.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.addChild(f);g=s_oSpriteLibrary.getSprite("msg_box");e=createBitmap(g);e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2;e.regX=g.width/2;e.regY=g.height/2;l.addChild(e);h=new createjs.Shape;h.graphics.beginFill("#0f0f0f").drawRect(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=.01;h.on("click",this._onLogoButRelease);l.addChild(h);g=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH/2+220;b=new CGfxButton(a,334,g,l);b.addEventListener(ON_MOUSE_UP,this.unload,this);c=new createjs.Text(TEXT_DEVELOPED,"34px "+FONT,"#ffffff");c.x=CANVAS_WIDTH/2;c.y=400;c.textAlign="center";l.addChild(c);var g=s_oSpriteLibrary.getSprite("ctl_logo"),m=createBitmap(g);m.regX=g.width/2;m.regY=g.height/2;m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2;l.addChild(m);
k=new createjs.Text("www.codethislab.com","26px "+FONT,"#ffffff");k.x=CANVAS_WIDTH/2;k.y=526;k.textAlign="center";l.addChild(k)};this.unload=function(){h.off("click",this._onLogoButRelease);b.unload();b=null;s_oStage.removeChild(l)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()};
