var s_iScaleFactor=1,s_iOffsetX,s_iOffsetY,s_bIsIphone=!1;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var d=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var f=b.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var e=b.createElement("div");e.id="vpw-test-d";e.style.cssText="position:absolute;top:-1000px";e.innerHTML="<style>@media("+d+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";f.appendChild(e);c.insertBefore(f,b.head);
a=7==e["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(f)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH),c=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b;s_bMobile&&!s_bIsIphone?($("#canvas").css("width",c+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=c,s_oStage.canvas.height=b,s_oStage.scaleX=s_oStage.scaleY=Math.min(c/CANVAS_WIDTH,b/CANVAS_HEIGHT));var f;b<a?(f=a-b,b+=f,c+=CANVAS_WIDTH/
CANVAS_HEIGHT*f):c<d&&(f=d-c,c+=f,b+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-b/2;var e=d/2-c/2,g=CANVAS_WIDTH/c;if(e*g<-EDGEBOARD_X||f*g<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),d/(CANVAS_WIDTH-2*EDGEBOARD_X)),c=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,f=(a-b)/2,e=(d-c)/2,g=CANVAS_WIDTH/c;s_iOffsetX=-1*e*g;s_iOffsetY=-1*f*g;0<=f&&(s_iOffsetY=0);0<=e&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);
$("#canvas").css("width",c+"px");$("#canvas").css("height",b+"px");0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",e+"px")}}function playSound(a,d,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:d}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}function setVolume(a,d){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=d}
function setMute(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(d)}function fadeVolume(a,d,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(new createjs.Tween.get(a)).to({volume:d},b)}function createBitmap(a,d,b){var c=new createjs.Bitmap(a),f=new createjs.Shape;d&&b?f.graphics.beginFill("#fff").drawRect(0,0,d,b):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=f;return c}
function createSprite(a,d,b,c,f,e){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-b,-c,f,e);a.hitArea=d;return a}function pad(a,d,b){a+="";return a.length>=d?a:Array(d-a.length+1).join(b||"0")+a}function randomFloatBetween(a,d,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(b))}
function rotateVector2D(a,d){var b=d.getX()*Math.cos(a)+d.getY()*Math.sin(a),c=d.getX()*-Math.sin(a)+d.getY()*Math.cos(a);d.set(b,c)}function tweenVectorsOnX(a,d,b){return a+b*(d-a)}function shuffle(a){for(var d=a.length,b,c;0!==d;)c=Math.floor(Math.random()*d),--d,b=a[d],a[d]=a[c],a[c]=b;return a}function bubbleSort(a){var d;do{d=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(d=a[b],a[b]=a[b+1],a[b+1]=d,d=!0)}while(d)}function compare(a,d){return a.index>d.index?-1:a.index<d.index?1:0}
function easeLinear(a,d,b,c){return b*a/c+d}function easeInQuad(a,d,b,c){return b*(a/=c)*a+d}function easeInSine(a,d,b,c){return-b*Math.cos(a/c*(Math.PI/2))+b+d}function easeInCubic(a,d,b,c){return b*(a/=c)*a*a+d}function getTrajectoryPoint(a,d){var b=new createjs.Point,c=(1-a)*(1-a),f=a*a;b.x=c*d.start.x+2*(1-a)*a*d.traj.x+f*d.end.x;b.y=c*d.start.y+2*(1-a)*a*d.traj.y+f*d.end.y;return b}
function getTrajectoryPointZ(a,d){var b=new createjs.Point,c=(1-a)*(1-a),f=a*a;b.x=c*d.start.x+2*(1-a)*a*d.traj.x+f*d.end.x;b.y=c*d.start.y+2*(1-a)*a*d.traj.y+f*d.end.y;b.z=c*d.start.z+2*(1-a)*a*d.traj.z+f*d.end.z;return b}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var b="",b=10>d?b+("0"+d+":"):b+(d+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,d){var b,c;b=getBounds(a,.9);c=getBounds(d,.98);return calculateIntersection(b,c)}function calculateIntersection(a,d){var b,c,f,e,g,k,h,m;b=a.x+(f=a.width/2);c=a.y+(e=a.height/2);g=d.x+(k=d.width/2);h=d.y+(m=d.height/2);b=Math.abs(b-g)-(f+k);c=Math.abs(c-h)-(e+m);return 0>b&&0>c?(b=Math.min(Math.min(a.width,d.width),-b),c=Math.min(Math.min(a.height,d.height),-c),{x:Math.max(a.x,d.x),y:Math.max(a.y,d.y),width:b,height:c,rect1:a,rect2:d}):null}
function getBounds(a,d){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,f=c.length,e,g;for(g=0;g<f;g++)e=getBounds(c[g],1),e.x<b.x&&(b.x=e.x),e.y<b.y&&(b.y=e.y),e.x+e.width>b.x2&&(b.x2=e.x+e.width),e.y+e.height>b.y2&&(b.y2=e.y+e.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var k,h;a instanceof createjs.Bitmap?
(f=a.sourceRect||a.image,g=f.width*d,k=f.height*d):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(f=a.spriteSheet.getFrame(a.currentFrame),g=f.rect.width,k=f.rect.height,c=f.regX,h=f.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);c=c||0;g=g||0;h=h||0;k=k||0;b.regX=c;b.regY=h;f=a.localToGlobal(0-c,0-h);e=a.localToGlobal(g-c,k-h);g=a.localToGlobal(g-c,0-h);c=a.localToGlobal(0-c,k-h);b.x=Math.min(Math.min(Math.min(f.x,
e.x),g.x),c.x);b.y=Math.min(Math.min(Math.min(f.y,e.y),g.y),c.y);b.width=Math.max(Math.max(Math.max(f.x,e.x),g.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(f.y,e.y),g.y),c.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,b,c;0<d;)c=Math.floor(Math.random()*d),d--,b=a[d],a[d]=a[c],a[c]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),b=0;b<d.length;b++){var c=d[b].split("=");if(c[0]==a)return c[1]}}
function CSpriteLibrary(){var a,d,b,c,f,e;this.init=function(g,k,h){b=d=0;c=g;f=k;e=h;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(e)};this._onSpriteLoaded=function(){c.call(e);++b==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=1280,CANVAS_HEIGHT=768,EDGEBOARD_X=90,EDGEBOARD_Y=105,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="arialbold",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_CONTROLLER_END=8,ON_CONTROLLER_REMOVE=9,ON_CONTROLLER_ROLL=10,PLAYER_IDLE=0,PLAYER_AIM=1,PLAYER_RECHARGE=2,PLAYER_SHOOT=3,SKEET_AWAY=0,SKEET_LINEAR=1,SKEET_PARABOLIC=2,SKEET_GONE=0,SKEET_DESTROYED=1,MAX_NUM_AMMO=
2,SHOT_SINGLE=0,SHOT_DOUBLE=1,STANDARD_SPEED_FACTOR,MOBILE_SPEED_FACTOR,TRAJECTOR_RANGE_X=100,TRAJECTOR_RANGE_Y=50,SCOPE_ACCELERATION,SCOPE_FRICTION,MAX_SCOPE_SPEED,MAX_POINTS_EARN,AD_SHOW_COUNTER;TEXT_BADSCORE="YOU CAN DO BETTER!";TEXT_CONGRATULATIONS="CONGRATULATIONS!";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_TOTAL_SCORE="TOTAL SCORE:";TEXT_PREPARE="READY";TEXT_PULL="PULL";TEXT_DEVELOPED="DEVELOPED BY";TEXT_LINK="www.codethislab.com";TEXT_HELP1="USE ARROW BUTTONS OR KEYS TO MOVE THE SCOPE";
TEXT_HELP2="CLICK SPACEBAR TO SHOOT";TEXT_HELP3="YOU HAVE 2 BULLETS TO HIT THE SKEETS";TEXT_HELP_MOB1="TOUCH THE LEFT SIDE OF THE SCREEN TO MOVE THE SCOPE";TEXT_HELP_MOB2="TOUCH THE RIGHT SIDE OF THE SCREEN TO SHOOT";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var a,d,b,c,f,e,g;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();g=new createjs.Container;s_oStage.addChild(g)};this.unload=function(){g.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(e).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));g.addChild(k);k=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(k);c.x=CANVAS_WIDTH/2-k.width/2;c.y=CANVAS_HEIGHT-170;g.addChild(c);a=k.width;d=k.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,d);g.addChild(f);c.mask=
f;b=new createjs.Text("","30px Arial","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";g.addChild(b);e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e.alpha=0;g.addChild(e)};this.refreshLoader=function(e){b.text=e+"%";f.graphics.clear();e=Math.floor(e*a/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,e,d)};this._init()}
var EASE_LINEAR=0,EASE_CUBIC_IN=1,EASE_QUART_BACKIN=2,EASE_BACKIN=3,EASE_SIN_IN=4,EASE_QUAD_IN=5,EASE_CUBIC_OUT=6,EASE_ELASTIC_OUT=7,EASE_BACKOUT=8,EASE_QUINT_OUT=9,EASE_CUBIC_INOUT=10;
function CTweenController(){this.tweenValue=function(a,d,b){return a+b*(d-a)};this.easeLinear=function(a,d,b,c){return b*a/c+d};this.easeInCubic=function(a,d,b,c){c=(a/=c)*a*a;return d+b*c};this.easeBackInQuart=function(a,d,b,c){c=(a/=c)*a;return d+b*(2*c*c+2*c*a+-3*c)};this.easeInBack=function(a,d,b,c){return b*(a/=c)*a*(2.70158*a-1.70158)+d};this.easeInSine=function(a,d,b,c){return-b*Math.cos(a/c*(Math.PI/2))+b+d};this.easeInQuad=function(a,d,b,c){return b*(a/=c)*a+d};this.easeOutCubic=function(a,
d,b,c){return b*((a=a/c-1)*a*a+1)+d};this.easeOutElastic=function(a,d,b,c){var f;if(0===a)return d;if(1===(a/=c))return d+b;f=.3*c;return b*Math.pow(2,-10*a)*Math.sin(2*(a*c-f/4)*Math.PI/f)+b+d};this.easeOutBack=function(a,d,b,c){return b*((a=a/c-1)*a*(2.70158*a+1.70158)+1)+d};this.easeInOutCubic=function(a,d,b,c){return 1>(a/=c/2)?b/2*a*a*a+d:b/2*((a-=2)*a*a+2)+d};this.easeOutQuint=function(a,d,b,c){return b*((a=a/c-1)*a*a*a*a+1)+d}}
function CJoypad(a,d,b,c,f){var e,g,k,h,m,u,n=[],l,r;this._init=function(a,b,c,d,f){e=a.height/2;k=g=0;h=a.height/30;m=[];u=[];r=new createjs.Container;r.x=b;r.y=c;d.addChild(r);b=new createjs.SpriteSheet({images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{bg:[0],stick:[1]}});c=createSprite(b,"bg",a.width/2/2,a.height/2,a.width/2,a.height);l=createSprite(b,"stick",a.width/2/2,a.height/2,a.width/2,a.height);r.addChild(c,l);f||(r.visible=!1);d.on("mousedown",
this.onPressStart);d.on("pressmove",this.onPressMove);d.on("pressup",this.onPressRelease)};this.addFireButtonListener=function(a,b,c,d){m[a]=b;u[a]=c;n=d};this.unload=function(){c.off("mousedown",this.onStageStart);c.off("pressmove",this.onStageMove);c.off("pressup",this.onStageRelease);c.removeChild(r)};this.onPressStart=function(a){a.primary?a.stageX<CANVAS_WIDTH/2?f||(r.visible=!0,r.x=a.stageX,r.y=a.stageY,l.x=0,l.y=0):m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(u[ON_MOUSE_DOWN],n):m[ON_MOUSE_DOWN]&&
m[ON_MOUSE_DOWN].call(u[ON_MOUSE_DOWN],n)};this.onPressMove=function(a){a.primary&&r.visible&&(l.x=a.stageX-r.x,l.y=a.stageY-r.y,k=Math.atan2(l.y,l.x),g=Math.abs(l.x/Math.cos(k)),Math.pow(l.x,2)+Math.pow(l.y,2)>Math.pow(e,2)&&(l.x=e*Math.cos(k),l.y=e*Math.sin(k)))};this.onPressRelease=function(a){a.primary&&(f?(new createjs.Tween(l)).to({x:0,y:0},200).call(function(){k=g=0}):(r.visible=!1,k=g=0))};this.update=function(){return g>h?k:null};this._init(a,d,b,c,f)}
function CMain(a){var d,b=0,c=0,f=STATE_LOADING,e,g,k;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;s_oTweenController=new CTweenController;g=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();d=!0};this.soundLoaded=function(){b++;g.refreshLoader(Math.floor(b/c*100));if(b===c){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&
(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/ambience.ogg","ambience"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/shot.ogg",
"shot"),createjs.Sound.registerSound("./sounds/pull.ogg","pull"),createjs.Sound.registerSound("./sounds/disc_launch.ogg","disc_launch"),createjs.Sound.registerSound("./sounds/hitted_disc.ogg","hitted_disc"),createjs.Sound.registerSound("./sounds/reload.ogg","reload"),createjs.Sound.registerSound("./sounds/applauses.ogg","applauses")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3",
"soundtrack"),createjs.Sound.registerSound("./sounds/ambience.mp3","ambience"),createjs.Sound.registerSound("./sounds/press_button.mp3","click"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/shot.mp3","shot"),createjs.Sound.registerSound("./sounds/pull.mp3","pull"),createjs.Sound.registerSound("./sounds/disc_launch.mp3","disc_launch"),createjs.Sound.registerSound("./sounds/hitted_disc.mp3","hitted_disc"),createjs.Sound.registerSound("./sounds/reload.mp3",
"reload"),createjs.Sound.registerSound("./sounds/applauses.mp3","applauses")),c+=10)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");
s_oSpriteLibrary.addSprite("general_panel","./sprites/general_panel.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("skeet_icon","./sprites/skeet_icon.png");s_oSpriteLibrary.addSprite("bottom_panel","./sprites/bottom_panel.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("small_panel","./sprites/small_panel.png");s_oSpriteLibrary.addSprite("keys",
"./sprites/keys.png");s_oSpriteLibrary.addSprite("space_bar","./sprites/space_bar.png");s_oSpriteLibrary.addSprite("dividing_line","./sprites/dividing_line.png");s_oSpriteLibrary.addSprite("swift_hand","./sprites/swift_hand.png");s_oSpriteLibrary.addSprite("touch_hand","./sprites/touch_hand.png");s_oSpriteLibrary.addSprite("advice_panel","./sprites/advice_panel.png");s_oSpriteLibrary.addSprite("joypad","./sprites/joypad.png");s_oSpriteLibrary.addSprite("skeet","./sprites/skeet.png");s_oSpriteLibrary.addSprite("scope",
"./sprites/scope.png");s_oSpriteLibrary.addSprite("particle_skeet","./sprites/particle_skeet.png");s_oSpriteLibrary.addSprite("indicator","./sprites/indicator.png");for(var a=0;10>a;a++)s_oSpriteLibrary.addSprite("mss_goto_aim_"+a,"./sprites/mss_goto_aim/mss_goto_aim_"+a+".png");for(a=0;25>a;a++)s_oSpriteLibrary.addSprite("mss_recharge_"+a,"./sprites/mss_recharge/mss_recharge_"+a+".png");for(a=0;8>a;a++)s_oSpriteLibrary.addSprite("mss_turn0_"+a,"./sprites/mss_turn_0/mss_turn0_"+a+".png");for(a=0;8>
a;a++)s_oSpriteLibrary.addSprite("mss_turn1_"+a,"./sprites/mss_turn_1/mss_turn1_"+a+".png");for(a=0;8>a;a++)s_oSpriteLibrary.addSprite("mss_turn2_"+a,"./sprites/mss_turn_2/mss_turn2_"+a+".png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;g.refreshLoader(Math.floor(b/c*100));if(b===c){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=
function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(){k=new CGame(e);f=STATE_GAME};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==d){var b=
(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&k.update();s_oStage.update(a)}};s_oMain=this;e=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack,s_oCanvas,s_oTweenController;
function CCreditsPanel(){var a,d,b,c,f;this._init=function(){d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;d.on("mousedown",function(){});s_oStage.addChild(d);(new createjs.Tween.get(d)).to({alpha:.7},500);b=new createjs.Container;s_oStage.addChild(b);var e=s_oSpriteLibrary.getSprite("general_panel"),g=createBitmap(e);g.regX=e.width/2;g.regY=e.height/2;b.addChild(g);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT+e.height/2;a=b.y;(new createjs.Tween.get(b)).to({y:CANVAS_HEIGHT/
2},500,createjs.Ease.quartIn);g=new createjs.Text(TEXT_DEVELOPED," 34px "+PRIMARY_FONT,"#000000");g.y=-e.height/2+120;g.textAlign="center";g.textBaseline="middle";g.lineWidth=300;g.outline=5;b.addChild(g);e=new createjs.Text(TEXT_DEVELOPED," 34px "+PRIMARY_FONT,"#ffffff");e.y=g.y;e.textAlign="center";e.textBaseline="middle";e.lineWidth=300;b.addChild(e);e=new createjs.Text(TEXT_LINK," 34px "+PRIMARY_FONT,"#000000");e.y=70;e.textAlign="center";e.textBaseline="middle";e.lineWidth=300;e.outline=5;b.addChild(e);
g=new createjs.Text(TEXT_LINK," 34px "+PRIMARY_FONT,"#ffffff");g.y=e.y;g.textAlign="center";g.textBaseline="middle";g.lineWidth=300;b.addChild(g);e=s_oSpriteLibrary.getSprite("ctl_logo");f=createBitmap(e);f.on("mousedown",this._onLogoButRelease);f.regX=e.width/2;f.regY=e.height/2;b.addChild(f);e=s_oSpriteLibrary.getSprite("but_exit");c=new CGfxButton(245,-147,e,b);c.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){c.setClickable(!1);(new createjs.Tween.get(d)).to({alpha:0},500);
(new createjs.Tween.get(b)).to({y:a},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(d);s_oStage.removeChild(b);c.unload()});d.off("mousedown",function(){});f.off("mousedown",this._onLogoButRelease)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()}
function CAreYouSurePanel(){var a,d,b,c,f,e;this._init=function(){c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;c.on("mousedown",function(){});s_oStage.addChild(c);(new createjs.Tween.get(c)).to({alpha:.7},500);f=new createjs.Container;s_oStage.addChild(f);var e=s_oSpriteLibrary.getSprite("small_panel"),k=createBitmap(e);k.regX=e.width/2;k.regY=e.height/2;f.addChild(k);f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT+e.height/2;a=f.y;(new createjs.Tween.get(f)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.quartIn);k=new createjs.Text(TEXT_ARE_SURE," 34px "+PRIMARY_FONT,"#000000");k.y=-e.height/2+70;k.textAlign="center";k.textBaseline="middle";k.lineWidth=400;k.outline=5;f.addChild(k);e=new createjs.Text(TEXT_ARE_SURE," 34px "+PRIMARY_FONT,"#ffffff");e.y=k.y;e.textAlign="center";e.textBaseline="middle";e.lineWidth=400;f.addChild(e);d=new CGfxButton(100,60,s_oSpriteLibrary.getSprite("but_yes"),f);d.addEventListener(ON_MOUSE_UP,this._onButYes,this);b=new CGfxButton(-100,60,s_oSpriteLibrary.getSprite("but_exit"),
f);b.addEventListener(ON_MOUSE_UP,this._onButNo,this);b.pulseAnimation();s_oGame.stopUpdate()};this._onButYes=function(){b.setClickable(!1);d.setClickable(!1);(new createjs.Tween.get(c)).to({alpha:0},500);(new createjs.Tween.get(f)).to({y:a},400,createjs.Ease.backIn).call(function(){e.unload();s_oGame.onExit()})};this._onButNo=function(){b.setClickable(!1);d.setClickable(!1);(new createjs.Tween.get(c)).to({alpha:0},500);(new createjs.Tween.get(f)).to({y:a},400,createjs.Ease.backIn).call(function(){e.unload();
s_oGame.startUpdate()})};this.unload=function(){b.unload();d.unload();s_oStage.removeChild(c);s_oStage.removeChild(f);c.off("mousedown",function(){})};e=this;this._init()}
function CToggle(a,d,b,c,f){var e,g,k,h;this._init=function(a,b,c,d,f){g=[];k=[];var w=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});e=d;h=createSprite(w,"state_"+e,c.width/2/2,c.height/2,c.width/2,c.height);h.x=a;h.y=b;h.stop();f.addChild(h);this._initListener()};this.unload=function(){s_bMobile?h.off("mousedown",this.buttonDown):(h.off("mousedown",this.buttonDown),h.off("mouseover",this.buttonOver));
h.off("pressup",this.buttonRelease);f.removeChild(h)};this._initListener=function(){if(s_bMobile)h.on("mousedown",this.buttonDown);else h.on("mousedown",this.buttonDown),h.on("mouseover",this.buttonOver);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;k[a]=c};this.setActive=function(a){e=a;h.gotoAndStop("state_"+e)};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");e=!e;h.gotoAndStop("state_"+
e);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(k[ON_MOUSE_UP],e)};this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.setPosition=function(a,b){h.x=a;h.y=b};this._init(a,d,b,c,f)}
function CGfxButton(a,d,b,c){var f,e,g,k,h,m;this._init=function(a,b,c,d){f=!1;e=1;g=[];k=[];h=createBitmap(c);h.x=a;h.y=b;h.scaleX=h.scaleY=e;h.regX=c.width/2;h.regY=c.height/2;d.addChild(h);this._initListener()};this.unload=function(){s_bMobile?h.off("mousedown",this.buttonDown):(h.off("mousedown",this.buttonDown),h.off("mouseover",this.buttonOver));h.off("pressup",this.buttonRelease);c.removeChild(h)};this.setVisible=function(a){h.visible=a};this.setClickable=function(a){f=!a};this._initListener=
function(){if(s_bMobile)h.on("mousedown",this.buttonDown);else h.on("mousedown",this.buttonDown),h.on("mouseover",this.buttonOver);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;k[a]=c};this.buttonRelease=function(){f||(h.scaleX=e,h.scaleY=e,g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(k[ON_MOUSE_UP]))};this.buttonDown=function(){f||(h.scaleX=.9*e,h.scaleY=.9*e,playSound("click",1,0),g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN]))};this.buttonOver=function(a){s_bMobile||
f||(a.target.cursor="pointer")};this.pulseAnimation=function(){createjs.Tween.get(h).to({scaleX:.9*e,scaleY:.9*e},850,createjs.Ease.quadOut).to({scaleX:e,scaleY:e},650,createjs.Ease.quadIn).call(function(){m.pulseAnimation()})};this.trembleAnimation=function(){createjs.Tween.get(h).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){m.trebleAnimation()})};this.setPosition=function(a,b){h.x=a;h.y=b};
this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};m=this;this._init(a,d,b,c);return this}
function CMenu(){var a,d,b,c,f,e,g,k,h,m,u;this._init=function(){g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(g);var n=s_oSpriteLibrary.getSprite("but_play");a=CANVAS_WIDTH/2;d=CANVAS_HEIGHT-n.height/2-10;k=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-200,n,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);k.pulseAnimation();n=s_oSpriteLibrary.getSprite("but_credits");b=n.height/2+10;c=n.height/2+10;u=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-240,n,
s_oStage);u.addEventListener(ON_MOUSE_UP,this._onCreditsBut,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n=s_oSpriteLibrary.getSprite("audio_icon"),f=CANVAS_WIDTH-n.height/2-10,e=n.height/2+10,m=new CToggle(f,e,n,s_bAudioActive,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(h);createjs.Tween.get(h).to({alpha:0},1E3).call(function(){h.visible=!1});this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.unload=function(){k.unload();k=null;h.visible=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;s_oStage.removeChild(g);s_oMenu=g=null};this.refreshButtonPos=function(g,h){u.setPosition(b+g,h+c);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(f-g,h+e);k.setPosition(a-g,d-h)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCreditsBut=function(){new CCreditsPanel};this._onButPlayRelease=function(){this.unload();
$(s_oMain).trigger("start_session");s_oMain.gotoGame()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){function d(a){a.preventDefault();switch(a.keyCode){case 37:q.leftStop();break;case 38:q.upStop();break;case 39:q.rightStop();break;case 40:q.downStop()}}function b(a){a||(a=window.event);a.preventDefault();switch(a.keyCode){case 32:s_oGame._onShot();break;case 37:q.moveLeft();break;case 38:q.moveUp();break;case 39:q.moveRight();break;case 40:q.moveDown()}}var c,f,e,g,k,h,m,u,n,l,r,w,p,v,t,A=null,y,x,z,q,B;this._init=function(){c=!0;f=!1;e=Math.PI/8;g=0;k=MAX_NUM_AMMO;w=r=l=n=m=h=
0;playSound("ambience",1,-1);p=new createjs.Container;s_oStage.addChild(p);t=new CInterface;t.refreshScore(g);var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));p.addChild(a);v=new createjs.Container;p.addChild(v);q=new CScope(p);q.setVisible(!1);z=new CPlayer(p);z.playIdle();CHelpPanel()};this.checkController=function(a){null===a?q.resetAllDirection():a>=-e&&a<e?(q.moveRight(),q.downStop(),q.upStop(),q.leftStop()):a>=e&&a<3*e?(q.moveDown(),q.moveRight(),q.upStop(),q.leftStop()):a>=3*e&&a<
5*e?(q.moveDown(),q.upStop(),q.rightStop(),q.leftStop()):a>=5*e&&a<7*e?(q.moveDown(),q.moveLeft(),q.upStop(),q.rightStop()):a>=7*e||a<7*-e?(q.moveLeft(),q.downStop(),q.rightStop(),q.upStop()):a>=7*-e&&a<5*-e?(q.moveUp(),q.moveLeft(),q.downStop(),q.rightStop()):a>=5*-e&&a<3*-e?(q.moveUp(),q.downStop(),q.rightStop(),q.leftStop()):a>=3*-e&&a<-e&&(q.moveUp(),q.moveRight(),q.downStop(),q.leftStop())};this._onShot=function(){if(0!==k&&f){w++;playSound("shot",1,0);for(var a,b=0;b<x.length;b++)a=x[b].checkCollision(q.bullsEye().x,
q.bullsEye().y),a.hit&&(playSound("hitted_disc",1,0),r++,x[b].destroy(),this.setScore(a.hitdistance,a.collisionradius,q.bullsEye()));k--;p.x=q.bullsEye().x;p.y=q.bullsEye().y;p.regX=q.bullsEye().x;p.regY=q.bullsEye().y;(new createjs.Tween.get(p)).to({scaleX:1.1,scaleY:1.1},80).to({scaleX:1,scaleY:1},10);0===k&&(setTimeout(function(){z.playRecharge()},500),q.setVisible(!1))}};this.setScore=function(a,b,c){a=Math.floor(-(a-b)/b*MAX_POINTS_EARN);new CScoreText(a,c.x,c.y);g+=a;t.refreshScore(a)};this.beginNewRound=
function(){h<SHOT_MODE.length?z.playAimAnim():this.gameOver()};this.playerReadyToShot=function(){this._initStage()};this._getSkeetValue=function(a){var b=SHOT[a].startX,c=SHOT[a].endX,d=SHOT[a].startY,e=SHOT[a].endY;0<SHOT[m].startY?(d=SHOT[a].startY+randomFloatBetween(-TRAJECTOR_RANGE_Y,TRAJECTOR_RANGE_Y,1),e=SHOT[a].endY+randomFloatBetween(-TRAJECTOR_RANGE_Y,TRAJECTOR_RANGE_Y,1)):(b=SHOT[a].startX+randomFloatBetween(-TRAJECTOR_RANGE_X,TRAJECTOR_RANGE_X,1),c=SHOT[a].endX+randomFloatBetween(-TRAJECTOR_RANGE_X,
TRAJECTOR_RANGE_X,1));var f=Math.floor(SHOT[a].speed/STANDARD_SPEED_FACTOR);s_bMobile&&(f=Math.floor(SHOT[a].speed/MOBILE_SPEED_FACTOR/STANDARD_SPEED_FACTOR));return{startX:b,endX:c,startY:d,endY:e,speed:f}};this._initStage=function(){n=0;k=MAX_NUM_AMMO;q.setPos(CANVAS_WIDTH/2,CANVAS_HEIGHT/2);q.setFadeVisible(!0);q.stopMovement();l=0;var a;x=[];SHOT_MODE[h]===SHOT_SINGLE?(u=1,a=this._getSkeetValue(m),x[0]=new CSkeet(a.startX,a.startY,v,a.endX,a.endY,SHOT[m].type,a.speed,m)):(u=2,a=this._getSkeetValue(m),
x[0]=new CSkeet(a.startX,a.startY,v,a.endX,a.endY,SHOT[m].type,a.speed,m),m++,a=this._getSkeetValue(m),x[1]=new CSkeet(a.startX,a.startY,v,a.endX,a.endY,SHOT[m].type,a.speed,m));m++;h++;y=[];for(a=0;a<x.length;a++)y[a]=new CIndicator(x[a].getPos().x,x[a].getPos().y,a+1);t.startText()};this.startStage=function(){z.playShootDirection();f=!0};this.endStage=function(a,b){u--;t.setSkeetInfo(a,b);if(0===u){f=!1;setTimeout(function(){s_oGame.beginNewRound()},1500);for(var c=!0,d=0;d<x.length;d++)x[d].getDestroyed()&&
1!==x.length||(c=!1);c&&playSound("applauses",1,0);0<k&&(setTimeout(function(){z.playRecharge()},500),q.setVisible(!1))}};this.unload=function(){c=!1;t.unload();null!==A&&A.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){$(s_oMain).trigger("end_session");$(s_oMain).trigger("end_level",1);setVolume(s_oSoundtrack,1);this.unload();s_oMain.gotoMenu()};this._onExitHelp=function(){c=!0;$(s_oMain).trigger("start_level",1);fadeVolume(s_oSoundtrack,0,2E3);this.beginNewRound();
if(s_bMobile){var a=s_oSpriteLibrary.getSprite("joypad");B=new CJoypad(a,100,700,s_oStage,!1);B.addFireButtonListener(ON_MOUSE_DOWN,this._onShot,this)}else document.onkeydown=b,document.onkeyup=d};this.gameOver=function(){A=new CEndPanel(g,r,w)};this.startUpdate=function(){c=!0;t.setTweenPause(!1)};this.stopUpdate=function(){c=!1;t.setTweenPause(!0)};this.update=function(){if(c&&(B&&this.checkController(B.update()),z.update(q.bullsEye()),f)){for(var a=0;a<x.length;a++)x[a].update();q.update();n+=
s_iTimeElaps;2E3<n&&l<x.length&&(n=0,x[l].lauch(),y[l].remove(),l++)}};s_oGame=this;SCOPE_ACCELERATION=a.scope_accelleration;SCOPE_FRICTION=a.scope_friction;MAX_SCOPE_SPEED=a.max_scope_speed;MAX_POINTS_EARN=a.max_points_earned_per_skeet;STANDARD_SPEED_FACTOR=a.standard_skeet_speed;MOBILE_SPEED_FACTOR=a.mobile_skeet_speed_factor;this._init()}var s_oGame;
function CInterface(){var a,d,b,c,f,e,g,k,h,m,u,n,l,r,w;this._init=function(){var p=s_oSpriteLibrary.getSprite("but_exit");f=CANVAS_WIDTH-p.height/2-10;e=p.height/2+10;k=new CGfxButton(f,e,p,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onExit,this);b=CANVAS_WIDTH-p.width/2-90;c=p.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p=s_oSpriteLibrary.getSprite("audio_icon"),g=new CToggle(b,c,p,s_bAudioActive,s_oStage),g.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);h=new createjs.Container;
h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2-200;h.alpha=0;s_oStage.addChild(h);var p=s_oSpriteLibrary.getSprite("advice_panel"),v=createBitmap(p);v.regX=p.width/2;v.regY=p.height/2;h.addChild(v);m=new createjs.Text(TEXT_PREPARE," 34px "+PRIMARY_FONT,"#ffffff");m.textAlign="center";m.textBaseline="middle";m.lineWidth=400;h.addChild(m);a=400;d=743;l=new createjs.Container;l.x=a;l.y=d;s_oStage.addChild(l);p=s_oSpriteLibrary.getSprite("bottom_panel");p=createBitmap(p);p.x=-60;p.y=-20;l.addChild(p);p=s_oSpriteLibrary.getSprite("skeet_icon");
v=new createjs.SpriteSheet({images:[p],frames:{width:p.width/3,height:p.height,regX:p.width/3/2,regY:p.height/2},animations:{hit:[0],available:[1],nohit:[2]}});r=[];for(var t=0;25>t;t++)r.push(createSprite(v,"available",p.width/3/2,p.height/2,p.width/3,p.height)),r[t].x=p.width/3*t,l.addChild(r[t]);u=new createjs.Text("0"," 24px "+PRIMARY_FONT,"#000000");u.x=680;u.y=10;u.textAlign="right";u.textBaseline="alphabetic";u.lineWidth=200;l.addChild(u);n=new createjs.Text("0"," 24px "+PRIMARY_FONT,"#ffffff");
n.x=u.x-2;n.y=u.y-2;n.textAlign="right";n.textBaseline="alphabetic";n.lineWidth=200;l.addChild(n);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),g=null;k.unload();s_oInterface=null};this.refreshButtonPos=function(h,n){k.setPosition(f-h,n+e);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||g.setPosition(b-h,n+c);l.x=a;l.y=d-n};this.refreshScore=function(a){new CRollingTextController(n,u,a,500,EASE_CUBIC_OUT)};this.startText=function(){m.text=
TEXT_PREPARE;w=(new createjs.Tween.get(h)).to({alpha:1},500);w=(new createjs.Tween.get(m)).to({alpha:1},500).wait(500).to({alpha:0},500).call(function(){m.text=TEXT_PULL;m.alpha=1;s_oGame.startStage();playSound("pull",1,0);w=(new createjs.Tween.get(h)).wait(500).to({alpha:0},1E3)})};this.setTweenPause=function(a){w.setPaused(a)};this.setSkeetInfo=function(a,b){b===SKEET_DESTROYED?r[a].gotoAndStop("hit"):r[a].gotoAndStop("nohit")};this.onExitFromHelp=function(){null.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onExit=function(){new CAreYouSurePanel(s_oStage)};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(){var a,d,b,c,f,e,g,k,h,m,u,n,l,r,w;this._init=function(){d=!1;r=new createjs.Shape;r.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);r.alpha=0;r.on("mousedown",function(){});s_oStage.addChild(r);(new createjs.Tween.get(r)).to({alpha:.7},500);var p=s_oSpriteLibrary.getSprite("general_panel");m=new createjs.Container;s_oStage.addChild(m);m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT+p.height/2;a=m.y;(new createjs.Tween.get(m)).to({y:CANVAS_HEIGHT/2},500,createjs.Ease.quartIn);
h=createBitmap(p);h.regX=p.width/2;h.regY=p.height/2;m.addChild(h);c=new createjs.Text(""," 22px "+PRIMARY_FONT,"#000000");c.textAlign="left";c.lineWidth=260;c.textBaseline="middle";c.x=-268;c.y=-148;b=new createjs.Text(""," 22px "+PRIMARY_FONT,"#ffffff");b.textAlign="left";b.lineWidth=260;b.textBaseline="middle";b.x=-270;b.y=-150;u=createBitmap(s_oSpriteLibrary.getSprite("scope"));u.x=20;u.y=-170;n=createBitmap(s_oSpriteLibrary.getSprite("keys"));n.x=145;n.y=-160;e=new createjs.Text(""," 22px "+
PRIMARY_FONT,"#000000");e.textAlign="left";e.textBaseline="middle";e.lineWidth=300;e.x=-268;e.y=-28;f=new createjs.Text(""," 22px "+PRIMARY_FONT,"#ffffff");f.textAlign="left";f.lineWidth=300;f.textBaseline="middle";f.x=-270;f.y=-30;l=createBitmap(s_oSpriteLibrary.getSprite("space_bar"));l.x=85;l.y=-25;k=new createjs.Text(TEXT_HELP3," 22px "+PRIMARY_FONT,"#000000");k.textAlign="center";k.lineWidth=440;k.textBaseline="middle";k.x=2;k.y=107;g=new createjs.Text(TEXT_HELP3," 22px "+PRIMARY_FONT,"#ffffff");
g.textAlign="center";g.lineWidth=440;g.textBaseline="middle";g.x=0;g.y=105;if(s_bMobile){c.text=TEXT_HELP_MOB1;c.lineWidth=290;c.textAlign="center";c.x=-150;b.text=TEXT_HELP_MOB1;b.lineWidth=290;b.textAlign="center";b.x=c.x-2;e.text=TEXT_HELP_MOB2;e.x=150;e.y=c.y;e.lineWidth=290;e.textAlign="center";f.text=TEXT_HELP_MOB2;f.x=e.x-2;f.y=b.y;f.lineWidth=290;f.textAlign="center";b.scaleX=b.scaleY=c.scaleX=c.scaleY=f.scaleX=f.scaleY=e.scaleX=e.scaleY=.8;var p=s_oSpriteLibrary.getSprite("dividing_line"),
v=createBitmap(p);v.regX=p.width/2;v.y=-160;m.addChild(v);p=s_oSpriteLibrary.getSprite("joypad");v=new createjs.SpriteSheet({images:[p],frames:{width:p.width/2,height:p.height,regX:p.width/2/2,regY:p.height/2},animations:{bg:[0],stick:[1]}});u=createSprite(v,"bg",p.width/2/2,p.height/2,p.width/2,p.height);u.scaleX=u.scaleY=.5;u.x=-150;u.y=-20;v=c.x-40;p=s_oSpriteLibrary.getSprite("swift_hand");n.regY=p.height/2;n.x=v;n.y=10;n.image=p;createjs.Tween.get(n,{loop:!0}).to({x:n.x+50},1E3,createjs.Ease.cubicIn).to({x:v},
1E3,createjs.Ease.cubicIn);createjs.Tween.get(n,{loop:!0}).to({y:n.y+30},500,createjs.Ease.sinOut).to({y:10},500,createjs.Ease.sinIn);p=s_oSpriteLibrary.getSprite("touch_hand");l.regX=p.width/2;l.regY=p.height/2;l.x=e.x;l.y=0;l.image=p;k.textAlign="center";g.textAlign="center";k.x=0;g.x=0;k.y+=30;g.y+=30;createjs.Tween.get(l,{loop:!0}).to({scaleX:.9,scaleY:.9},250,createjs.Ease.cubicIn).to({scaleX:1,scaleY:1},250,createjs.Ease.cubicIn)}else c.text=TEXT_HELP1,b.text=TEXT_HELP1,e.text=TEXT_HELP2,f.text=
TEXT_HELP2;m.addChild(h,c,b,e,f,k,g,u,n,l);m.on("pressup",this._onExitHelp);m.on("mouseover",this._buttonOver)};this._buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.unload=function(){s_oStage.removeChild(m);m.off("pressup",this._onExitHelp);m.off("mouseover",this._buttonOver)};this._onExitHelp=function(){d||(d=!0,(new createjs.Tween.get(r)).to({alpha:0},500),(new createjs.Tween.get(m)).to({y:a},400,createjs.Ease.backIn).call(function(){w.unload();s_oGame._onExitHelp()}))};w=this;
this._init()}
function CEndPanel(a,d,b){var c,f,e,g,k;this._init=function(a,b,d){var g;15<b?(g=TEXT_CONGRATULATIONS,playSound("applauses",1,0)):(g=TEXT_BADSCORE,playSound("game_over",1,0));f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;f.on("mousedown",function(){});s_oStage.addChild(f);(new createjs.Tween.get(f)).to({alpha:.7},500);e=new createjs.Container;s_oStage.addChild(e);var l=s_oSpriteLibrary.getSprite("small_panel"),r=createBitmap(l);r.regX=l.width/
2;r.regY=l.height/2;e.addChild(r);e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT+l.height/2;c=e.y;(new createjs.Tween.get(e)).to({y:CANVAS_HEIGHT/2},500,createjs.Ease.quartIn);g=new createjs.Text(g," 34px "+PRIMARY_FONT,"#ffffff");g.y=-l.height/2+40;g.textAlign="center";g.textBaseline="middle";g.lineWidth=400;e.addChild(g);new CSkeet(-45,g.y+60,e,0,0,0,0,0);k=new createjs.Text(b+" / 25"," 24px "+PRIMARY_FONT,"#ffffff");k.x=-5;k.y=g.y+60;k.textAlign="left";k.textBaseline="middle";k.lineWidth=400;e.addChild(k);
l=s_oSpriteLibrary.getSprite("scope");r=createBitmap(l);r.regX=l.width/2;r.regY=l.height/2;r.scaleX=r.scaleY=.5;r.x=-45;r.y=g.y+110;e.addChild(r);l=(b/d*100).toFixed(1);0===b&&0===d&&(l=0);b=new createjs.Text(l+"%"," 24px "+PRIMARY_FONT,"#ffffff");b.x=-5;b.y=r.y;b.textAlign="left";b.textBaseline="middle";b.lineWidth=400;e.addChild(b);$(s_oMain).trigger("save_score",a,"standard");$(s_oMain).trigger("share_event",a);a=new createjs.Text(TEXT_TOTAL_SCORE+" "+a," 24px "+PRIMARY_FONT,"#ffffff");a.y=g.y+
180;a.textAlign="center";a.textBaseline="middle";a.lineWidth=500;e.addChild(a);e.on("pressup",this._onExit);e.on("mouseover",this._buttonOver)};this._buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.unload=function(){s_oStage.removeChild(e);f.off("mousedown",function(){});e.off("pressup",this._onExit);e.off("mouseover",this._buttonOver)};this._onExit=function(){$(s_oMain).trigger("show_interlevel_ad");(new createjs.Tween.get(f)).to({alpha:0},500);(new createjs.Tween.get(e)).to({y:c},
400,createjs.Ease.backIn).call(function(){g.unload();s_oGame.onExit()})};g=this;this._init(a,d,b);return this}
function CSkeet(a,d,b,c,f,e,g,k){var h,m,u,n,l,r,w,p,v,t,A,y,x,z,q;this._init=function(a,b,c,d,e,f,g,k){m=h=!1;u=k;n=0;l=g;r=500;w=f;t=new createjs.Container;t.x=a;t.y=b;c.addChild(t);f=s_oSpriteLibrary.getSprite("skeet");g={images:[f],frames:{width:f.width/2,height:f.height,regX:f.width/2/2,regY:f.height/2},animations:{flawless:[0],damaged:[1]}};g=new createjs.SpriteSheet(g);A=createSprite(g,"flawless",f.width/2/2,f.height/2,f.width/2,f.height);t.addChild(A);f=s_oSpriteLibrary.getSprite("particle_skeet");
g={framerate:20,images:[f],frames:{width:f.width/8,height:f.height/5,regX:f.width/8/2,regY:f.height/5/2},animations:{idle:[39],explosion:[0,39,"idle"]}};g=new createjs.SpriteSheet(g);y=createSprite(g,"idle",f.width/8/2,f.height/5/2,f.width/8,f.height/5);y.gotoAndStop("idle");c.addChild(y);v=[];z={x:a,y:b};q={x:d,y:e};this._calculateMid();p=Math.pow(50,2)};this.unload=function(){b.removeChild(t)};this._calculateMid=function(){var b;b=new createjs.Point(c-.2*(c-a),f-r/2);v={start:z,end:q,traj:b}};this._awayMovement=
function(){n++;if(n>l)n=0,h=!1,s_oGame.endStage(u,SKEET_GONE),x.unload();else{var b=s_oTweenController.easeOutCubic(n,0,1,l),b=s_oTweenController.tweenValue(a,c,b);t.x=b;b=s_oTweenController.easeOutCubic(n,0,1,l);b=s_oTweenController.tweenValue(d,f,b);t.y=b;b=s_oTweenController.easeOutCubic(n,0,1,l);b=s_oTweenController.tweenValue(1.5,.1,b);t.scaleX=t.scaleY=b}};this._linearMovement=function(){n++;if(n>l)n=0,h=!1,s_oGame.endStage(u,SKEET_GONE),x.unload();else{var b=s_oTweenController.easeOutCubic(n,
0,1,l),b=s_oTweenController.tweenValue(a,c,b);t.x=b;b=s_oTweenController.easeOutCubic(n,0,1,l);b=s_oTweenController.tweenValue(d,f,b);t.y=b;b=s_oTweenController.easeOutCubic(n,0,1,l);b=s_oTweenController.tweenValue(1,.8,b);t.scaleX=t.scaleY=b}};this._parabolicMovement=function(){n++;if(n>l)n=0,h=!1,s_oGame.endStage(u,SKEET_GONE),x.unload();else{var a=s_oTweenController.easeOutCubic(n,0,1,l),a=getTrajectoryPoint(a,v);t.x=a.x;t.y=a.y;a=s_oTweenController.easeLinear(n,0,1,l);a=s_oTweenController.tweenValue(1,
.01,a);t.scaleX=t.scaleY=a}};this.lauch=function(){h=!0;playSound("disc_launch",1,0)};this.checkCollision=function(a,b){var c=a-t.x,d=b-t.y,c=c*c+d*d,d=p*t.scaleX*t.scaleX;return{hit:c<d,hitdistance:c,collisionradius:d}};this.getPos=function(){return{x:t.x,y:t.y}};this.getIndex=function(){return u};this.getDestroyed=function(){return m};this.destroy=function(){m=!0;A.gotoAndStop("damaged");(new createjs.Tween.get(t,{loop:!0})).to({rotation:7},100).to({rotation:-7},100);y.x=t.x+10*t.scaleX;y.y=t.y-
20*t.scaleX;y.scaleX=y.scaleY=t.scaleX;y.gotoAndPlay("explosion");(new createjs.Tween.get(t)).to({alpha:0},800).call(function(){h=!1;s_oGame.endStage(u,SKEET_DESTROYED);x.unload()})};this.update=function(){if(h)switch(w){case SKEET_AWAY:this._awayMovement();break;case SKEET_LINEAR:this._linearMovement();break;case SKEET_PARABOLIC:this._parabolicMovement()}};x=this;this._init(a,d,b,c,f,e,g,k)}
function CPlayer(a){var d,b,c,f,e,g,k,h,m;this._init=function(a){c=PLAYER_IDLE;f=0;d=CANVAS_WIDTH/7.99;b=CANVAS_HEIGHT/2.99;h=new createjs.Container;h.x=0;h.y=CANVAS_HEIGHT;a.addChild(h);e=[];for(a=0;10>a;a++){var n=s_oSpriteLibrary.getSprite("mss_goto_aim_"+a),l=createBitmap(n);l.regY=n.height;l.visible=!1;e.push(l);h.addChild(l)}g=[];for(a=0;25>a;a++)n=s_oSpriteLibrary.getSprite("mss_recharge_"+a),l=createBitmap(n),l.regY=n.height,l.visible=!1,g.push(l),h.addChild(l);k=[];for(a=0;3>a;a++){k[a]=
[];for(var r=2-a,w=0;8>w;w++)n=s_oSpriteLibrary.getSprite("mss_turn"+r+"_"+w),l=createBitmap(n),l.regY=n.height,l.visible=!1,k[a][w]=l,h.addChild(l)}m=e[0]};this.resetAnim=function(){};this.playIdle=function(){c=PLAYER_IDLE;m.visible=!1;e[0].visible=!0;m=e[0]};this.playAimAnim=function(){c=PLAYER_AIM};this.playRecharge=function(){playSound("reload",1,0);c=PLAYER_RECHARGE};this.playShootDirection=function(){c=PLAYER_SHOOT};this._rechargeAnim=function(){m.visible=!1;f++;g[f].visible=!0;m=g[f];f===g.length-
1&&(f=0,this.playIdle())};this._aimAnim=function(){m.visible=!1;f++;e[f].visible=!0;m=e[f];f===e.length-1&&(f=0,c=PLAYER_IDLE,s_oGame.playerReadyToShot())};this._setShootDirection=function(a){m.visible=!1;var c=Math.floor(a.y/b);a=Math.floor(a.x/d);m.visible=!1;k[c][a].visible=!0;m=k[c][a]};this.update=function(a){switch(c){case PLAYER_AIM:this._aimAnim();break;case PLAYER_RECHARGE:this._rechargeAnim();break;case PLAYER_SHOOT:this._setShootDirection(a)}};this._init(a)}
function CScope(a){var d,b=!1,c=!1,f=!1,e=!1,g,k,h,m;this._init=function(a){k=g=0;var b=s_oSpriteLibrary.getSprite("scope");d=createBitmap(b);d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2;d.regX=b.width/2;d.regY=b.height/2;a.addChild(d);s_oSpriteLibrary.getSprite("tap_shot")};this.resetAllDirection=function(){e=f=c=b=!1};this.stopMovement=function(){k=g=0};this.onAnimationEnd=function(){};this.playShot=function(){(void 0).gotoAndPlay("show");playSound("shot",1,0)};this._checkBoundary=function(){d.x>CANVAS_WIDTH&&
(d.x=CANVAS_WIDTH);0>d.x&&(d.x=0);d.y>CANVAS_HEIGHT&&(d.y=CANVAS_HEIGHT);0>d.y&&(d.y=0)};this.bullsEye=function(){h=d.x;m=d.y;return{x:h,y:m}};this.upStop=function(){f=!1};this.downStop=function(){e=!1};this.leftStop=function(){b=!1};this.rightStop=function(){c=!1};this.moveLeft=function(){b=!0;c=!1};this.moveRight=function(){c=!0;b=!1};this.moveUp=function(){f=!0;e=!1};this.moveDown=function(){e=!0;f=!1};this.getSprite=function(){return d};this.setPos=function(a,b){d.x=a;d.y=b};this.setVisible=function(a){d.alpha=
a?1:0};this.setFadeVisible=function(a){a?(new createjs.Tween.get(d)).to({alpha:1},500):(new createjs.Tween.get(d)).to({alpha:0},500)};this.update=function(){c&&f?(g+=SCOPE_ACCELERATION,k-=SCOPE_ACCELERATION):c&&e?(g+=SCOPE_ACCELERATION,k+=SCOPE_ACCELERATION):b&&e?(g-=SCOPE_ACCELERATION,k+=SCOPE_ACCELERATION):b&&f?(g-=SCOPE_ACCELERATION,k-=SCOPE_ACCELERATION):b?g-=SCOPE_ACCELERATION:c?g+=SCOPE_ACCELERATION:f?k-=SCOPE_ACCELERATION:e&&(k+=SCOPE_ACCELERATION);d.x+=g;d.y+=k;g*=SCOPE_FRICTION;k*=SCOPE_FRICTION;
g>MAX_SCOPE_SPEED&&(g=MAX_SCOPE_SPEED);g<-MAX_SCOPE_SPEED&&(g=-MAX_SCOPE_SPEED);k>MAX_SCOPE_SPEED&&(k=MAX_SCOPE_SPEED);k<-MAX_SCOPE_SPEED&&(k=-MAX_SCOPE_SPEED);.2>Math.abs(g)&&(g=0);.2>Math.abs(k)&&(k=0);this._checkBoundary()};this._init(a)}var SHOT=[];SHOT[0]={startX:-50,startY:400,endX:1400,endY:200,type:SKEET_LINEAR,speed:150};SHOT[1]={startX:-500,startY:200,endX:1500,endY:500,type:SKEET_LINEAR,speed:150};SHOT[2]={startX:-50,startY:300,endX:1500,endY:350,type:SKEET_LINEAR,speed:150};
SHOT[3]={startX:1350,startY:500,endX:-150,endY:200,type:SKEET_LINEAR,speed:150};SHOT[4]={startX:1350,startY:400,endX:-50,endY:300,type:SKEET_PARABOLIC,speed:150};SHOT[5]={startX:-50,startY:400,endX:1400,endY:200,type:SKEET_LINEAR,speed:150};SHOT[6]={startX:-50,startY:200,endX:1300,endY:500,type:SKEET_PARABOLIC,speed:150};SHOT[7]={startX:1350,startY:300,endX:-100,endY:200,type:SKEET_LINEAR,speed:150};SHOT[8]={startX:1350,startY:500,endX:-150,endY:200,type:SKEET_PARABOLIC,speed:150};
SHOT[9]={startX:-50,startY:400,endX:1300,endY:300,type:SKEET_PARABOLIC,speed:120};SHOT[10]={startX:1350,startY:550,endX:-50,endY:550,type:SKEET_PARABOLIC,speed:150};SHOT[11]={startX:700,startY:-50,endX:1E3,endY:600,type:SKEET_AWAY,speed:200};SHOT[12]={startX:-50,startY:550,endX:1400,endY:500,type:SKEET_LINEAR,speed:120};SHOT[13]={startX:1350,startY:550,endX:-100,endY:500,type:SKEET_LINEAR,speed:120};SHOT[14]={startX:1350,startY:500,endX:-100,endY:550,type:SKEET_LINEAR,speed:120};
SHOT[15]={startX:1E3,startY:-30,endX:600,endY:600,type:SKEET_AWAY,speed:150};SHOT[16]={startX:400,startY:-30,endX:1100,endY:600,type:SKEET_AWAY,speed:150};SHOT[17]={startX:1350,startY:550,endX:-50,endY:200,type:SKEET_PARABOLIC,speed:120};SHOT[18]={startX:1350,startY:200,endX:-50,endY:550,type:SKEET_PARABOLIC,speed:120};SHOT[19]={startX:-50,startY:300,endX:1300,endY:300,type:SKEET_PARABOLIC,speed:120};SHOT[20]={startX:1E3,startY:-30,endX:600,endY:600,type:SKEET_AWAY,speed:120};
SHOT[21]={startX:1350,startY:200,endX:-50,endY:300,type:SKEET_PARABOLIC,speed:120};SHOT[22]={startX:-150,startY:-30,endX:1300,endY:550,type:SKEET_PARABOLIC,speed:120};SHOT[23]={startX:1350,startY:120,endX:-50,endY:300,type:SKEET_PARABOLIC,speed:120};SHOT[24]={startX:-150,startY:550,endX:1300,endY:500,type:SKEET_PARABOLIC,speed:100};var SHOT_MODE=[];SHOT_MODE[0]=SHOT_SINGLE;SHOT_MODE[1]=SHOT_SINGLE;SHOT_MODE[2]=SHOT_SINGLE;SHOT_MODE[3]=SHOT_DOUBLE;SHOT_MODE[4]=SHOT_SINGLE;SHOT_MODE[5]=SHOT_DOUBLE;
SHOT_MODE[6]=SHOT_DOUBLE;SHOT_MODE[7]=SHOT_DOUBLE;SHOT_MODE[8]=SHOT_SINGLE;SHOT_MODE[9]=SHOT_SINGLE;SHOT_MODE[10]=SHOT_SINGLE;SHOT_MODE[11]=SHOT_DOUBLE;SHOT_MODE[12]=SHOT_DOUBLE;SHOT_MODE[13]=SHOT_SINGLE;SHOT_MODE[14]=SHOT_DOUBLE;SHOT_MODE[15]=SHOT_DOUBLE;SHOT_MODE[16]=SHOT_SINGLE;
function CScoreText(a,d,b){var c;this._init=function(a,b,d){c=new createjs.Text("00000"," 30px "+PRIMARY_FONT,"#ffffff");c.textAlign="center";c.text="+"+a;c.x=b;c.y=d;c.alpha=0;c.shadow=new createjs.Shadow("#000000",2,2,2);s_oStage.addChild(c);var k=this;createjs.Tween.get(c).to({alpha:1},400,createjs.Ease.quadIn).call(function(){k.moveUp()})};this.moveUp=function(){var a=c.y-100,b=this;createjs.Tween.get(c).to({y:a},1E3,createjs.Ease.sineIn).call(function(){b.unload()});createjs.Tween.get(c).wait(500).to({alpha:0},
500)};this.unload=function(){s_oStage.removeChild(c)};this._init(a,d,b)}
function CIndicator(a,d,b){var c;this._init=function(a,b,d){c=new createjs.Container;var k=s_oSpriteLibrary.getSprite("indicator"),h=createBitmap(k);c.addChild(h);h=new createjs.Text(d," 24px "+PRIMARY_FONT,"#000000");h.y=30;h.x=18;h.textAlign="center";h.textBaseline="middle";h.lineWidth=200;c.addChild(h);d=new createjs.Text(d," 24px "+PRIMARY_FONT,"#ffffff");d.x=h.x-2;d.y=h.y-2;d.textAlign="center";d.textBaseline="middle";d.lineWidth=200;c.addChild(d);0>a?(c.scaleX=-1,h.scaleX=d.scaleX=-1,c.x=s_iOffsetX+
k.width):c.x=CANVAS_WIDTH-s_iOffsetX-k.width;0>b?(c.rotation=-90,h.rotation=d.rotation=90,c.y=s_iOffsetY+k.height,c.x=a):c.y=b;c.alpha=0;s_oStage.addChild(c);(new createjs.Tween.get(c)).to({alpha:1},1E3)};this.remove=function(){(new createjs.Tween.get(c)).to({alpha:0},500).call(function(){s_oStage.removeChild(c)})};this._init(a,d,b)}
function CRollingTextController(a,d,b,c,f){var e,g,k,h,m,u,n,l,r,w,p,v;this._init=function(a,b,c,d,e){l=[];r=[];m=d;this.setUpdateInfo(c);n=e;p=a;v=b;w=[]};this.unload=function(){clearInterval(u)};this.setUpdateInfo=function(b){k=parseFloat(a.text);h=k+b;e=0;g=Math.round(m/FPS);var c=this;u=setInterval(function(){c.update()},FPS_TIME)};this.addEventListener=function(a,b,c){l[a]=b;r[a]=c};this.addRollingListener=function(a,b,c){l[ON_CONTROLLER_ROLL]=a;r[ON_CONTROLLER_ROLL]=b;w=[];for(a=0;a<c.length;a++)w[a]=
{step:c[a],flag:!1}};this.increaseValue=function(a){};this.getTarget=function(){return p};this.update=function(){e++;if(e>g)e=0,p.text=h.toFixed(0),null!==v&&(v.text=h.toFixed(0)),clearInterval(u);else{var a;switch(n){case EASE_BACKIN:a=s_oTweenController.easeInBack(e,0,1,g);break;case EASE_BACKOUT:a=s_oTweenController.easeOutBack(e,0,1,g);break;case EASE_CUBIC_IN:a=s_oTweenController.easeInCubic(e,0,1,g);break;case EASE_CUBIC_OUT:a=s_oTweenController.easeOutCubic(e,0,1,g);break;case EASE_ELASTIC_OUT:a=
s_oTweenController.easeOutElastic(e,0,1,g);break;case EASE_LINEAR:a=s_oTweenController.easeLinear(e,0,1,g);break;case EASE_QUART_BACKIN:a=s_oTweenController.easeBackInQuart(e,0,1,g);break;default:a=s_oTweenController.easeLinear(e,0,1,g)}a=s_oTweenController.tweenValue(k,h,a);for(var b=0;b<w.length;b++)a>w[b].step&&!w[b].flag&&(w[b].flag=!0,null!==l[ON_CONTROLLER_ROLL]&&l[ON_CONTROLLER_ROLL].call(r[ON_CONTROLLER_ROLL],b));p.text=a.toFixed(0);null!==v&&(v.text=a.toFixed(0))}};this._init(a,d,b,c,f)}
;
