var s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return!0;return!1}
function getSize(a){var d=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var f=b.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var g=b.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+d+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";f.appendChild(g);c.insertBefore(f,b.head);
a=7==g["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(f)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH),c=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,f;b<a?(f=a-b,b+=f,c+=CANVAS_WIDTH/CANVAS_HEIGHT*f):c<d&&(f=d-c,c+=f,b+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-b/2;var g=d/2-c/2,m=CANVAS_WIDTH/c;if(g*m<-EDGEBOARD_X||f*m<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),d/(CANVAS_WIDTH-2*EDGEBOARD_X)),
c=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,f=(a-b)/2,g=(d-c)/2,m=CANVAS_WIDTH/c;s_iOffsetX=-1*g*m;s_iOffsetY=-1*f*m;0<=f&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",c+"px");$("#canvas").css("height",b+"px");0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",g+"px")}}
function createBitmap(a,d,b){var c=new createjs.Bitmap(a),f=new createjs.Shape;d&&b?f.graphics.beginFill("#fff").drawRect(0,0,d,b):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=f;return c}function createSprite(a,d,b,c,f,g){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-b,-c,f,g);a.hitArea=d;return a}
function randomFloatBetween(a,d,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(b))}function shuffle(a){for(var d=a.length,b,c;0!==d;)c=Math.floor(Math.random()*d),--d,b=a[d],a[d]=a[c],a[c]=b;return a}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var b="",b=10>d?b+("0"+d+":"):b+(d+":");return 10>a?b+("0"+a):b+a}
function rotateVector2D(a,d){var b=d.getX()*Math.cos(a)+d.getY()*Math.sin(a),c=d.getX()*-Math.sin(a)+d.getY()*Math.cos(a);d.set(b,c)}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};function getUrlVars(a){a=a.trim();var d=[];a=a.split("&");for(var b=0;b<a.length;b++){var c=a[b].split("=");d[c[0]]=c[1]}return d}
function tryCheckLogin(){var a=checkLogin();console.log(a);a=getUrlVars(a);"true"===a.res?(s_bLogged=!0,WHEEL_SETTINGS=a.bonus_prize.split("#"),s_oGameSettings.initSymbolWin(a.paytable),COIN_BET=a.coin_bet.split("#"),MAX_BET=parseFloat(COIN_BET[COIN_BET.length-1]),MIN_BET=parseFloat(COIN_BET[0]),$(s_oMain).trigger("start_session"),s_oMenu.exitFromMenu()):s_oMsgBox.show("can't login #"+a.desc)}
function tryCallSpin(a,d,b){a=callSpin(b,a,d);console.log(a);a=getUrlVars(a);if("true"===a.res)s_oGame.onSpinReceived(a);else s_oMsgBox.show(a.desc)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),b=0;b<d.length;b++){var c=d[b].split("=");if(c[0]==a)return c[1]}}
function playSound(a,d,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:d}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}function setVolume(a,d){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=d}function setMute(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(d)}
function CSpriteLibrary(){var a,d,b,c,f,g;this.init=function(m,h,n){b=d=0;c=m;f=h;g=n;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(g)};this._onSpriteLoaded=function(){c.call(g);++b===d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=1500,CANVAS_HEIGHT=640,EDGEBOARD_X=300,EDGEBOARD_Y=0,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!0,FONT_GAME="rugamikaregular",FONT_PAYTABLE="Arial",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,GAME_STATE_IDLE=0,GAME_STATE_SPINNING=1,GAME_STATE_SHOW_ALL_WIN=2,GAME_STATE_SHOW_WIN=3,GAME_STATE_BONUS=4,REEL_STATE_START=0,REEL_STATE_MOVING=1,REEL_STATE_STOP=2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,REEL_OFFSET_X=380,REEL_OFFSET_Y=
84,NUM_REELS=5,NUM_ROWS=3,NUM_SYMBOLS=10,WILD_SYMBOL=8,NUM_PAYLINES=20,SYMBOL_SIZE=140,SPACE_BETWEEN_SYMBOLS=10,MAX_FRAMES_REEL_EASE=16,MIN_REEL_LOOPS,REEL_DELAY,REEL_START_Y=REEL_OFFSET_Y-3*SYMBOL_SIZE,REEL_ARRIVAL_Y=REEL_OFFSET_Y+3*SYMBOL_SIZE,TIME_SHOW_WIN,TIME_SHOW_ALL_WINS,COIN_BET,MIN_BET,MAX_BET,TOTAL_MONEY,WIN_OCCURRENCE,SLOT_CASH,MIN_WIN,FREESPIN_OCCURRENCE,BONUS_OCCURRENCE,FREESPIN_SYMBOL_NUM_OCCURR,NUM_FREESPIN,BONUS_PRIZE,BONUS_PRIZE_OCCURR,BONUS_FREESPIN=1,BONUS_WHEEL=2,WHEEL_SETTINGS,
SEGMENT_ROT=18,TIME_ANIM_IDLE=1E4,MIN_FAKE_SPIN=3,WHEEL_SPIN_TIMESPEED=2600,ANIM_SPIN_TIMESPEED=50,TIME_ANIM_WIN=5E3,ANIM_WIN1_TIMESPEED=300,ANIM_WIN2_TIMESPEED=50,LED_SPIN=3,ANIM_IDLE1_TIMESPEED=2E3,ANIM_IDLE2_TIMESPEED=100,ANIM_IDLE3_TIMESPEED=150,STATE_BONUS_IDLE=0,STATE_BONUS_SPIN=1,STATE_BONUS_WIN=2,STATE_BONUS_LOSE=3,NUM_SPIN_FOR_ADS;
function CSlotSettings(){this._init=function(){this._initSymbolSpriteSheets();this._initPaylines();this._initSymbolAnims();this._initSymbolsOccurence()};this._initSymbolSpriteSheets=function(){s_aSymbolData=[];for(var a=1;a<NUM_SYMBOLS+1;a++){var d={images:[s_oSpriteLibrary.getSprite("symbol_"+a)],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],moving:[1,2]}};s_aSymbolData[a]=new createjs.SpriteSheet(d)}};this._initPaylines=function(){s_aPaylineCombo=[[{row:1,
col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:1,col:4}],[{row:0,col:0},{row:0,col:1},{row:0,col:2},{row:0,col:3},{row:0,col:4}],[{row:2,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:2,col:4}],[{row:0,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:0,col:4}],[{row:2,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:2,col:4}],[{row:1,col:0},{row:0,col:1},{row:0,col:2},{row:0,col:3},{row:1,col:4}],[{row:1,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:1,col:4}],[{row:0,
col:0},{row:0,col:1},{row:1,col:2},{row:2,col:3},{row:2,col:4}],[{row:2,col:0},{row:2,col:1},{row:1,col:2},{row:0,col:3},{row:0,col:4}],[{row:1,col:0},{row:2,col:1},{row:1,col:2},{row:0,col:3},{row:1,col:4}],[{row:2,col:0},{row:0,col:1},{row:1,col:2},{row:2,col:3},{row:1,col:4}],[{row:0,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:0,col:4}],[{row:2,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:2,col:4}],[{row:0,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:0,col:4}],[{row:2,
col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:2,col:4}],[{row:1,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:1,col:4}],[{row:1,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:1,col:4}],[{row:0,col:0},{row:0,col:1},{row:2,col:2},{row:0,col:3},{row:0,col:4}],[{row:2,col:0},{row:2,col:1},{row:0,col:2},{row:2,col:3},{row:2,col:4}],[{row:0,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:0,col:4}]]};this.initSymbolWin=function(a){a=a.split("#");s_aSymbolWin=[];for(var d=0;d<
a.length;d++){var b=a[d].split(",");s_aSymbolWin[d]=[];for(var c=0;c<b.length;c++)s_aSymbolWin[d][c]=parseFloat(b[c])}};this._initSymbolAnims=function(){s_aSymbolAnims=[];var a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_1_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[0]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_2_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,
regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[1]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_3_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[2]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_4_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[3]=
new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_5_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[4]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_6_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[5]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_7_anim")],
frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[6]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_8_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[7]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_9_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,
1],anim:[1,14]}};s_aSymbolAnims[8]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_10_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[9]=new createjs.SpriteSheet(a)};this._initSymbolsOccurence=function(){s_aRandSymbols=[];var a;for(a=0;1>a;a++)s_aRandSymbols.push(1);for(a=0;2>a;a++)s_aRandSymbols.push(2);for(a=0;3>a;a++)s_aRandSymbols.push(3);for(a=0;4>a;a++)s_aRandSymbols.push(4);for(a=
0;4>a;a++)s_aRandSymbols.push(5);for(a=0;6>a;a++)s_aRandSymbols.push(6);for(a=0;6>a;a++)s_aRandSymbols.push(7);for(a=0;1>a;a++)s_aRandSymbols.push(8);for(a=0;1>a;a++)s_aRandSymbols.push(9);for(a=0;1>a;a++)s_aRandSymbols.push(10)};this._init()}var s_aSymbolData,s_aPaylineCombo,s_aSymbolWin,s_aSymbolAnims,s_aRandSymbols;TEXT_GAMEOVER="GAME OVER";TEXT_CONGRATS="CONGRATULATIONS";TEXT_MONEY="MONEY";TEXT_PLAY="PLAY";TEXT_BET="BET";TEXT_COIN="COIN";TEXT_MAX_BET="MAX BET";TEXT_INFO="INFO";TEXT_LINES="LINES";
TEXT_SPIN="SPIN";TEXT_AUTOSPIN="AUTO\nSPIN";TEXT_WIN="WIN";TEXT_OK="OK";TEXT_STOP_AUTO="STOP\nAUTO";TEXT_HELP_WILD="THIS SIMBOL IS A JOLLY WHICH \nCAN REPLACE ANY OTHER \nSYMBOL TO MAKE UP A COMBO";TEXT_HELP_BONUS1="3 OR MORE ON ANY REELS, WILL TRIGGER WHEEL OF FORTUNE BONUS!!";TEXT_HELP_BONUS2="CLICK SPIN BUTTON TO GET YOUR PRIZE!!";TEXT_HELP_FREESPIN="GET 3 OR MORE FREESPIN SYMBOL ON ANY REEL TO TRIGGER FREESPINS";TEXT_CURRENCY="$";TEXT_BONUS_HELP="SPIN THE WHEEL!!";TEXT_NO_MAX_BET="NOT ENOUGH MONEY FOR MAX BET!!";
TEXT_CONNECTION_LOST="CONNECTION DOWN! PLEASE TRY AGAIN";TEXT_NOT_ENOUGH_MONEY="NOT ENOUGH MONEY FOR THE CURRENT BET!";TEXT_CONGRATULATIONS="Congratulations!";TEXT_MSG_SHARE1="You collected <strong>";TEXT_MSG_SHARE2=" points</strong>!<br><br>Share your score with your friends!";TEXT_MSG_SHARING1="My score is ";TEXT_MSG_SHARING2=" points! Can you do better?";
function CPreloader(){var a,d,b,c,f,g;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();g=new createjs.Container;s_oStage.addChild(g)};this.unload=function(){g.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var m=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));g.addChild(m);m=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(m);c.x=CANVAS_WIDTH/2-m.width/2;c.y=CANVAS_HEIGHT-170;g.addChild(c);a=m.width;d=m.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,d);g.addChild(f);c.mask=f;b=new createjs.Text("","30px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline=
"alphabetic";b.textAlign="center";g.addChild(b)};this.refreshLoader=function(g){b.text=g+"%";f.graphics.clear();g=Math.floor(g*a/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,g,d)};this._init()}
function CMain(a){var d,b=0,c=0,f=STATE_LOADING,g,m,h;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);s_oAttachSection=new createjs.Container;s_oStage.addChild(s_oAttachSection);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;m=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();d=!0};this.soundLoaded=function(){b++;if(b===c)this.onAllResourcesLoaded()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,
this)),createjs.Sound.registerSound("./sounds/press_but.ogg","press_but"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/reels.ogg","reels"),createjs.Sound.registerSound("./sounds/reel_stop.ogg","reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.ogg","start_reel",6),createjs.Sound.registerSound("./sounds/game_over_bonus.ogg","game_over_bonus"),createjs.Sound.registerSound("./sounds/reel_bonus.ogg","reel_bonus"),createjs.Sound.registerSound("./sounds/start_reel_bonus.ogg",
"start_reel_bonus"),createjs.Sound.registerSound("./sounds/win_bonus.ogg","win_bonus")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/reels.mp3","reels"),createjs.Sound.registerSound("./sounds/reel_stop.mp3","reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.mp3",
"start_reel",6),createjs.Sound.registerSound("./sounds/game_over_bonus.mp3","game_over_bonus"),createjs.Sound.registerSound("./sounds/reel_bonus.mp3","reel_bonus"),createjs.Sound.registerSound("./sounds/start_reel_bonus.mp3","start_reel_bonus"),createjs.Sound.registerSound("./sounds/win_bonus.mp3","win_bonus")),c+=9)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_bg","./sprites/but_play_bg.png");s_oSpriteLibrary.addSprite("but_exit",
"./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("paytable1","./sprites/paytable1.jpg");s_oSpriteLibrary.addSprite("paytable2","./sprites/paytable2.jpg");s_oSpriteLibrary.addSprite("paytable3","./sprites/paytable3.jpg");s_oSpriteLibrary.addSprite("mask_slot","./sprites/mask_slot.png");s_oSpriteLibrary.addSprite("spin_but","./sprites/but_spin_bg.png");s_oSpriteLibrary.addSprite("but_autospin",
"./sprites/but_autospin.png");s_oSpriteLibrary.addSprite("spin_bg","./sprites/spin_bg.png");s_oSpriteLibrary.addSprite("coin_but","./sprites/but_coin_bg.png");s_oSpriteLibrary.addSprite("info_but","./sprites/but_info_bg.png");s_oSpriteLibrary.addSprite("bet_but","./sprites/bet_but.png");s_oSpriteLibrary.addSprite("win_frame_anim","./sprites/win_frame_anim.png");s_oSpriteLibrary.addSprite("but_lines_bg","./sprites/but_lines_bg.png");s_oSpriteLibrary.addSprite("but_maxbet_bg","./sprites/but_maxbet_bg.png");
s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_arrow_next","./sprites/but_arrow_next.png");s_oSpriteLibrary.addSprite("but_arrow_prev","./sprites/but_arrow_prev.png");s_oSpriteLibrary.addSprite("freespin_panel","./sprites/freespin_panel.png");s_oSpriteLibrary.addSprite("logo","./sprites/logo.png");s_oSpriteLibrary.addSprite("logo_freespin","./sprites/logo_freespin.png");for(var a=1;a<
NUM_SYMBOLS+1;a++)s_oSpriteLibrary.addSprite("symbol_"+a,"./sprites/symbol_"+a+".png"),s_oSpriteLibrary.addSprite("symbol_"+a+"_anim","./sprites/symbol_"+a+"_anim.png");for(a=1;a<NUM_PAYLINES+1;a++)s_oSpriteLibrary.addSprite("payline_"+a,"./sprites/payline_"+a+".png");s_oSpriteLibrary.addSprite("bg_bonus","./sprites/bonus/bg_bonus.png");s_oSpriteLibrary.addSprite("but_spin_bonus","./sprites/bonus/but_spin_bonus.png");s_oSpriteLibrary.addSprite("leds","./sprites/bonus/leds.png");s_oSpriteLibrary.addSprite("wheel",
"./sprites/bonus/wheel.png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;m.refreshLoader(Math.floor(b/c*100));if(b===c)this.onAllResourcesLoaded()};this._onAllImagesLoaded=function(){};this.onAllResourcesLoaded=function(){s_oGameSettings=new CSlotSettings;s_oMsgBox=new CMsgBox;m.unload();WIN_OCCURRENCE=g.win_occurrence;MIN_REEL_LOOPS=g.min_reel_loop;REEL_DELAY=g.reel_delay;TIME_SHOW_WIN=g.time_show_win;TIME_SHOW_ALL_WINS=g.time_show_all_wins;
SLOT_CASH=g.slot_cash;TOTAL_MONEY=parseFloat(g.money);FREESPIN_OCCURRENCE=g.freespin_occurrence;BONUS_OCCURRENCE=g.bonus_occurrence;FREESPIN_SYMBOL_NUM_OCCURR=g.freespin_symbol_num_occur;NUM_FREESPIN=g.num_freespin;BONUS_PRIZE=g.bonus_prize;BONUS_PRIZE_OCCURR=g.bonus_prize_occur;COIN_BET=g.coin_bet;NUM_SPIN_FOR_ADS=a.num_spin_ads_showing;this.gotoMenu()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(){h=new CGame(g);f=STATE_GAME};this.gotoHelp=function(){new CHelp;f=STATE_HELP};
this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;g=
a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oAttachSection,s_oMain,s_oSpriteLibrary,s_bLogged=!1,s_oMsgBox,s_oGameSettings;
function CTextButton(a,d,b,c,f,g,m,h){var n,t,e,k,r,p,l,v,x;this._init=function(a,b,c,f,d,h,g,m){n=!1;k=[];r=[];x=createBitmap(c);t=c.width;e=c.height;var I=Math.ceil(g/20);l=new createjs.Text(f,"bold "+g+"px "+d,"#000000");l.textAlign="center";var q=l.getBounds();l.x=c.width/2+I;l.y=(c.height-q.height)/2+I;v=new createjs.Text(f,"bold "+g+"px "+d,h);v.textAlign="center";q=v.getBounds();v.x=c.width/2;v.y=(c.height-q.height)/2;p=new createjs.Container;p.x=a;p.y=b;p.regX=c.width/2;p.regY=c.height/2;
p.addChild(x,l,v);void 0===m?s_oAttachSection.addChild(p):m.addChild(p);this._initListener()};this.unload=function(){p.off("mousedown");p.off("pressup");s_oAttachSection.removeChild(p)};this.setVisible=function(a){p.visible=a};this.setText=function(a){v.text=a;l.text=a};this.enable=function(){n=!1;x.filters=[];x.cache(0,0,t,e)};this.disable=function(){n=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);x.filters=[new createjs.ColorMatrixFilter(a)];x.cache(0,0,t,e)};this._initListener=
function(){h=this;p.on("mousedown",this.buttonDown);p.on("pressup",this.buttonRelease)};this.addEventListener=function(a,e,b){k[a]=e;r[a]=b};this.buttonRelease=function(){n||(playSound("press_but",1,0),p.scaleX=1,p.scaleY=1,k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(r[ON_MOUSE_UP]))};this.buttonDown=function(){n||(p.scaleX=.9,p.scaleY=.9,k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(r[ON_MOUSE_DOWN]))};this.setPosition=function(a,e){p.x=a;p.y=e};this.changeText=function(a){v.text=a;l.text=a};this.setX=function(a){p.x=
a};this.setY=function(a){p.y=a};this.getButtonImage=function(){return p};this.getX=function(){return p.x};this.getY=function(){return p.y};this.getText=function(){return v.text};this._init(a,d,b,c,f,g,m,h);return this}
function CGfxButton(a,d,b,c){var f,g,m=[],h,n;this._init=function(a,e,b){f=[];g=[];h=createBitmap(b);h.x=a;h.y=e;h.regX=b.width/2;h.regY=b.height/2;n.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);n.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,e,b){f[a]=e;g[a]=b};this.addEventListenerWithParams=
function(a,e,b,c){f[a]=e;g[a]=b;m=c};this.buttonRelease=function(){playSound("press_but",1,0);h.scaleX=1;h.scaleY=1;f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(g[ON_MOUSE_UP],m)};this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],m)};this.setPosition=function(a,e){h.x=a;h.y=e};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};n=c;this._init(a,
d,b);return this}
function CToggle(a,d,b,c){var f,g,m,h;this._init=function(a,b,e,c){g=[];m=[];var d=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{state_true:[0],state_false:[1]}});f=c;h=createSprite(d,"state_"+f,e.width/2/2,e.height/2,e.width/2,e.height);h.x=a;h.y=b;h.stop();s_oAttachSection.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);s_oAttachSection.removeChild(h)};this._initListener=
function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,e){g[a]=b;m[a]=e};this.setActive=function(a){f=a;h.gotoAndStop("state_"+f)};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;playSound("press_but",1,0);f=!f;h.gotoAndStop("state_"+f);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(m[ON_MOUSE_UP],f)};this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN])};this.setPosition=function(a,b){h.x=
a;h.y=b};this._init(a,d,b,c)}
function CBetBut(a,d,b){var c,f,g,m=[],h;this._init=function(a,b,e){c=!1;f=[];g=[];e=s_oSpriteLibrary.getSprite("bet_but");var k=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:0,regY:0},animations:{on:[0,1],off:[1,2]}});h=createSprite(k,"on",0,0,e.width/2,e.height);h.stop();h.x=a;h.y=b;h.regX=e.width/2;h.regY=e.height/2;s_oAttachSection.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);
s_oAttachSection.removeChild(h)};this.disable=function(a){c=a};this.setVisible=function(a){h.visible=a};this.setOn=function(){h.gotoAndStop("on")};this.setOff=function(){h.gotoAndStop("off")};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,e){f[a]=b;g[a]=e};this.addEventListenerWithParams=function(a,b,e,c){f[a]=b;g[a]=e;m=c};this.buttonRelease=function(){f[ON_MOUSE_UP]&&!1===c&&(playSound("press_but",1,0),f[ON_MOUSE_UP].call(g[ON_MOUSE_UP],
m))};this.buttonDown=function(){f[ON_MOUSE_DOWN]&&!1===c&&f[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],m)};this.setPosition=function(a,b){h.x=a;h.y=b};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(a,d,b)}
function CMenu(){var a,d,b,c,f,g;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oAttachSection.addChild(b);var m=s_oSpriteLibrary.getSprite("but_bg");c=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-164,m,TEXT_PLAY,FONT_GAME,"#ffffff",40);c.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-m.width/4-10,d=m.height/2+10,f=new CToggle(a,d,m,s_bAudioActive),f.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oAttachSection.addChild(g);createjs.Tween.get(g).to({alpha:0},400).call(function(){g.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){c.unload();c=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f.unload(),f=null;s_oAttachSection.removeChild(b);b=null;s_oAttachSection.removeChild(g);s_oMenu=g=null};this.refreshButtonPos=function(b,c){!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||f.setPosition(a-b,c+d)};this._onButPlayRelease=function(){tryCheckLogin()};this.exitFromMenu=function(){this.unload();s_oMain.gotoGame()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var d=!1,b=!1,c,f,g,m,h,n,t,e,k,r,p,l,v,x,y,C,D,w,A,z,J,B,I,q,L,G,E,F,M,u,H=null,K;this._init=function(){f=GAME_STATE_IDLE;C=h=g=0;J=[0,1,2,3,4];m=J[0];n=NUM_PAYLINES;p=TOTAL_MONEY;k=MIN_BET;r=k*n;c=!1;D=x=v=0;s_oTweenController=new CTweenController;L=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oAttachSection.addChild(L);this._initReels();M=new createjs.Bitmap(s_oSpriteLibrary.getSprite("mask_slot"));s_oAttachSection.addChild(M);G=new createjs.Bitmap(s_oSpriteLibrary.getSprite("logo"));
G.x=590;G.y=0;s_oAttachSection.addChild(G);E=new createjs.Bitmap(s_oSpriteLibrary.getSprite("logo_freespin"));E.x=590;E.y=0;E.visible=!1;s_oAttachSection.addChild(E);F=new createjs.Bitmap(s_oSpriteLibrary.getSprite("freespin_panel"));F.x=940;F.y=3;F.visible=!1;s_oAttachSection.addChild(F);u=new CInterface(k,r,p);this._initStaticSymbols();H=new CPayTablePanel;p<r&&u.disableSpin(c);MIN_WIN=s_aSymbolWin[0][s_aSymbolWin[0].length-1];for(var a=0;a<s_aSymbolWin.length;a++)for(var e=s_aSymbolWin[a],b=0;b<
e.length;b++)0!==e[b]&&e[b]<MIN_WIN&&(MIN_WIN=e[b]);K=new CBonusPanel;d=!0};this.unload=function(){createjs.Sound.stop();u.unload();H.unload();for(var a=0;a<w.length;a++)w[a].unload();for(a=0;a<NUM_ROWS;a++)for(var e=0;e<NUM_REELS;e++)A[a][e].unload();s_oAttachSection.removeAllChildren()};this._initReels=function(){var a=REEL_OFFSET_X,e=REEL_OFFSET_Y,b=0;w=[];for(var c=0;c<NUM_REELS;c++)w[c]=new CReelColumn(c,a,e,b),w[c+NUM_REELS]=new CReelColumn(c+NUM_REELS,a,e+SYMBOL_SIZE*NUM_ROWS,b),a+=SYMBOL_SIZE+
SPACE_BETWEEN_SYMBOLS,b+=REEL_DELAY};this._initStaticSymbols=function(){var a=REEL_OFFSET_X,e=REEL_OFFSET_Y;A=[];for(var b=0;b<NUM_ROWS;b++){A[b]=[];for(var c=0;c<NUM_REELS;c++){var f=new CStaticSymbolCell(b,c,a,e);A[b][c]=f;a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS}a=REEL_OFFSET_X;e+=SYMBOL_SIZE}};this.generateLosingPattern=function(){for(var a=[],e=0;e<NUM_ROWS;e++){var c=Math.floor(Math.random()*(s_aRandSymbols.length-2)),c=s_aRandSymbols[c];a[e]=c}B=[];for(e=0;e<NUM_ROWS;e++){B[e]=[];for(var f=0;f<
NUM_REELS;f++)if(0===f)B[e][f]=a[e];else{do c=Math.floor(Math.random()*(s_aRandSymbols.length-2)),c=s_aRandSymbols[c];while(a[0]===c||a[1]===c||a[2]===c);B[e][f]=c}}z=[];b=!0};this._generateRandSymbols=function(){for(var a=[],e=0;e<NUM_ROWS;e++)a[e]=s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)];return a};this.reelArrived=function(a,e){if(g>MIN_REEL_LOOPS)if(m===e){if(!1===w[a].isReadyToStop()){var c=a;a<NUM_REELS?(c+=NUM_REELS,w[c].setReadyToStop(),w[a].restart([B[0][a],B[1][a],
B[2][a]],!0)):(c-=NUM_REELS,w[c].setReadyToStop(),w[a].restart([B[0][c],B[1][c],B[2][c]],!0))}}else w[a].restart(this._generateRandSymbols(),!1);else w[a].restart(this._generateRandSymbols(),!1),b&&0===a&&g++};this.stopNextReel=function(){h++;0===h%2&&(playSound("reel_stop",1,0),m=J[h/2],h===2*NUM_REELS&&this._endReelAnimation())};this._endReelAnimation=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||I.stop();b=!1;h=g=0;m=J[0];0<x&&(u.disableSpin(c),u.disableGuiButtons(!1));!1===F.visible&&
0===v||u.refreshFreeSpinNum(v);if(0<z.length){for(var a=0;a<z.length;a++){0<z[a].line&&(H.highlightCombo(z[a].value,z[a].num_win),u.showLine(z[a].line));for(var e=z[a].list,k=0;k<e.length;k++)A[e[k].row][e[k].col].show(e[k].value),w[e[k].col].setVisible(e[k].row,!1),w[e[k].col+NUM_REELS].setVisible(e[k].row,!1)}0<v?(G.visible=!1,E.visible=!0,F.visible=!0):(G.visible=!0,E.visible=!1,F.visible=!1,u.refreshFreeSpinNum(""));0<l&&u.refreshWinText(l);t=0;f=GAME_STATE_SHOW_ALL_WIN;if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)q=playSound("win",.3,0);x!==BONUS_WHEEL&&u.refreshMoney(p)}else 0<v?(G.visible=!1,E.visible=!0,F.visible=!0,u.disableSpin(c),this.onSpin()):(G.visible=!0,E.visible=!1,F.visible=!1,u.refreshFreeSpinNum(""),c?p<r&&0===v?(this.resetCoinBet(),c=!1,u.enableGuiButtons()):(u.enableAutoSpin(),this.onSpin()):f=GAME_STATE_IDLE);p<r&&0===v?(this.resetCoinBet(),c=!1,u.enableGuiButtons()):c||0!==v||0!==x||(u.enableGuiButtons(),u.disableBetBut(!1));D++;D===NUM_SPIN_FOR_ADS&&(D=0,$(s_oMain).trigger("show_interlevel_ad"));
$(s_oMain).trigger("save_score",p)};this.hidePayTable=function(){H.hide()};this._showWin=function(){var a;if(0<e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||q.stop();a=z[e-1].line;0<a&&u.hideLine(a);a=z[e-1].list;for(var b=0;b<a.length;b++)A[a[b].row][a[b].col].stopAnim(),w[a[b].col].setVisible(a[b].row,!0),w[a[b].col+NUM_REELS].setVisible(a[b].row,!0)}if(e===z.length){e=0;if(0<v){u.disableSpin(c);this.onSpin();return}if(x===BONUS_WHEEL)K.show(y),f=GAME_STATE_BONUS;else if(c){u.enableAutoSpin();this.onSpin();
return}}a=z[e].line;0<a&&u.showLine(a);a=z[e].list;for(b=0;b<a.length;b++)A[a[b].row][a[b].col].show(a[b].value),w[a[b].col].setVisible(a[b].row,!1),w[a[b].col+NUM_REELS].setVisible(a[b].row,!1);e++};this._hideAllWins=function(){for(var a=0;a<z.length;a++)for(var b=z[a].list,c=0;c<b.length;c++)A[b[c].row][b[c].col].stopAnim(),w[b[c].col].setVisible(b[c].row,!0),w[b[c].col+NUM_REELS].setVisible(b[c].row,!0);u.hideAllLines();e=t=0;t=TIME_SHOW_WIN;f=GAME_STATE_SHOW_WIN};this.activateLines=function(a){n=
a;this.removeWinShowing();r=a=k*n;u.refreshTotalBet(r);u.refreshNumLines(n);a>p?u.disableSpin(c):u.enableSpin()};this.addLine=function(){n===NUM_PAYLINES?n=1:n++;r=k*n;u.refreshTotalBet(r);u.refreshNumLines(n);u.enableSpin()};this.resetCoinBet=function(){C=0;var a=parseFloat(COIN_BET[C]),e=a*n;k=a;k=Math.floor(100*k)/100;r=e;u.refreshBet(k);u.refreshTotalBet(r);u.enableSpin()};this.changeCoinBet=function(){C++;C===COIN_BET.length&&(C=0);var a=parseFloat(COIN_BET[C]),e=a*n;k=a;k=Math.floor(100*k)/
100;r=e;u.refreshBet(k);u.refreshTotalBet(r);u.enableSpin()};this.onMaxBet=function(){if(p<MAX_BET*NUM_PAYLINES)s_oMsgBox.show(TEXT_NO_MAX_BET);else{var a=MAX_BET;n=NUM_PAYLINES;a*=n;k=MAX_BET;r=a;u.refreshBet(k);u.refreshTotalBet(r);u.refreshNumLines(n);a>p?u.disableSpin(c):(u.enableSpin(),this.onSpin())}};this.removeWinShowing=function(){H.resetHighlightCombo();u.resetWin();for(var a=0;a<NUM_ROWS;a++)for(var e=0;e<NUM_REELS;e++)A[a][e].hide(),w[e].setVisible(a,!0),w[e+NUM_REELS].setVisible(a,!0);
for(a=0;a<w.length;a++)w[a].activate();f=GAME_STATE_IDLE};this.onSpin=function(){if(p<r&&0===v)u.enableGuiButtons(),c=!1,s_oMsgBox.show(TEXT_NOT_ENOUGH_MONEY);else{if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q&&q.stop(),I=playSound("reels",1,0);u.disableBetBut(!0);this.removeWinShowing();!0===s_bLogged?(r=E.visible?0:k*n,tryCallSpin(k,r,n)):this.generateLosingPattern();u.hideAllLines();u.disableGuiButtons(c)}};this.onAutoSpin=function(){c=!0;this.onSpin()};this.onStopAutoSpin=function(){c=!1;f!==
GAME_STATE_SPINNING&&f!==GAME_STATE_BONUS&&u.enableGuiButtons()};this.generateLosingPattern=function(){for(var a=[],e=0;e<NUM_ROWS;e++){var c=Math.floor(Math.random()*(s_aRandSymbols.length-2)),c=s_aRandSymbols[c];a[e]=c}B=[];for(e=0;e<NUM_ROWS;e++){B[e]=[];for(var f=0;f<NUM_REELS;f++)if(0===f)B[e][f]=a[e];else{do c=Math.floor(Math.random()*(s_aRandSymbols.length-2)),c=s_aRandSymbols[c];while(a[0]===c||a[1]===c||a[2]===c);B[e][f]=c}}z=[];b=!0};this.onSpinReceived=function(a){p-=r;u.refreshMoney(p);
f=GAME_STATE_SPINNING;"true"===a.res?(v=parseInt(a.freespin),"true"===a.win?(B=JSON.parse(a.pattern),z=JSON.parse(a.win_lines),0<parseInt(a.freespin)?x=BONUS_FREESPIN:0<parseInt(a.bonus)?(x=BONUS_WHEEL,y=a.bonus_prize):x=0,l=parseFloat(a.tot_win)):(x=0,B=JSON.parse(a.pattern),z=[]),b=!0,p=parseFloat(a.money)):s_oGame.generateLosingPattern()};this.onInfoClicked=function(){f!==GAME_STATE_SPINNING&&(H.isVisible()?H.hide():H.show())};this.onConnectionLost=function(){s_oMsgBox.show(TEXT_CONNECTION_LOST);
u.enableGuiButtons()};this.exitFromBonus=function(){u.refreshMoney(p);c?(u.enableAutoSpin(),this.onSpin()):(u.enableGuiButtons(),u.disableBetBut(!1),u.enableSpin());$(s_oMain).trigger("save_score",p)};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",{img:"200x200.jpg",title:TEXT_CONGRATULATIONS,msg:TEXT_MSG_SHARE1+p+TEXT_MSG_SHARE2,msg_share:TEXT_MSG_SHARING1+p+TEXT_MSG_SHARING2})};this.getState=function(){return f};this.update=
function(){if(!1!==d)switch(f){case GAME_STATE_SPINNING:for(var a=0;a<w.length;a++)w[a].update();break;case GAME_STATE_SHOW_ALL_WIN:t+=s_iTimeElaps;t>TIME_SHOW_ALL_WINS&&this._hideAllWins();break;case GAME_STATE_SHOW_WIN:t+=s_iTimeElaps;t>TIME_SHOW_WIN&&(t=0,this._showWin());break;case GAME_STATE_BONUS:K.update()}};s_oGame=this;this._init()}var s_oGame,s_oTweenController;
function CReelColumn(a,d,b,c){var f,g,m,h,n,t,e,k,r,p,l,v,x,y;this._init=function(a,b,c,d){m=g=f=!1;e=0;h=a;t=d;n=h<NUM_REELS?h:h-NUM_REELS;r=0;p=MAX_FRAMES_REEL_EASE;k=REEL_STATE_START;l=c;v=l+SYMBOL_SIZE*NUM_ROWS;this.initContainer(b,c)};this.initContainer=function(a,e){y=new createjs.Container;y.x=a;y.y=e;var b=0;x=[];for(var c=0;c<NUM_ROWS;c++){var f=createSprite(s_aSymbolData[s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);f.stop();f.x=0;
f.y=b;y.addChild(f);x[c]=f;b+=SYMBOL_SIZE}s_oAttachSection.addChild(y)};this.unload=function(){s_oAttachSection.removeChild(y)};this.activate=function(){l=y.y;v=l+SYMBOL_SIZE*NUM_ROWS;f=!0};this._setSymbol=function(a){y.removeAllChildren();for(var e=0,b=0;b<a.length;b++){var c=new createjs.Sprite(s_aSymbolData[a[b]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);c.stop();c.x=0;c.y=e;y.addChild(c);x[b]=c;e+=SYMBOL_SIZE}};this.setVisible=function(a,e){x[a].visible=e};this.restart=function(a,e){y.y=l=REEL_START_Y;
v=l+SYMBOL_SIZE*NUM_ROWS;this._setSymbol(a);if(g=e){r=0;p=MAX_FRAMES_REEL_EASE;k=REEL_STATE_STOP;for(var b=0;b<NUM_ROWS;b++)x[b].gotoAndStop("static");m=!0}else for(b=0;b<NUM_ROWS;b++)x[b].gotoAndStop("moving")};this.setReadyToStop=function(){r=0;p=MAX_FRAMES_REEL_EASE;k=REEL_STATE_STOP};this.isReadyToStop=function(){return g};this._updateStart=function(){0===r&&h<NUM_REELS&&playSound("start_reel",1,0);r++;r>p&&(r=0,p/=2,k++,l=y.y,v=l+SYMBOL_SIZE*NUM_ROWS);var a=s_oTweenController.easeInBack(r,0,
1,p),a=s_oTweenController.tweenValue(l,v,a);y.y=a};this._updateMoving=function(){r++;r>p&&(r=0,l=y.y,v=l+SYMBOL_SIZE*NUM_ROWS);var a=s_oTweenController.easeLinear(r,0,1,p),a=s_oTweenController.tweenValue(l,v,a);y.y=a};this._updateStopping=function(){r++;if(r>=p)f=!1,r=0,p=MAX_FRAMES_REEL_EASE,k=REEL_STATE_START,e=0,g=!1,m&&(m=!1,y.y=REEL_OFFSET_Y),s_oGame.stopNextReel();else{var a=s_oTweenController.easeOutCubic(r,0,1,p),a=s_oTweenController.tweenValue(l,v,a);y.y=a}};this.update=function(){if(!1!==
f&&(e++,e>t))switch(!1===g&&y.y>REEL_ARRIVAL_Y&&s_oGame.reelArrived(h,n),k){case REEL_STATE_START:this._updateStart();break;case REEL_STATE_MOVING:this._updateMoving();break;case REEL_STATE_STOP:this._updateStopping()}};this._init(a,d,b,c)}
function CInterface(a,d,b){var c,f,g,m,h,n,t,e,k,r,p,l,v,x,y,C,D,w,A,z;this._init=function(a,b,d){var q=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH-q.width/2-2;f=q.height/2+2;t=new CGfxButton(c,f,q,s_oAttachSection);t.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=s_oSpriteLibrary.getSprite("audio_icon"),g=c-q.width/2-2,m=q.height/2+2,l=new CToggle(g,m,q,s_bAudioActive),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);q=createBitmap(s_oSpriteLibrary.getSprite("spin_bg"));
q.x=1040;q.y=551;s_oAttachSection.addChild(q);q=s_oSpriteLibrary.getSprite("but_autospin");k=new CTextButton(1030+q.width/2,595,q,TEXT_AUTOSPIN,FONT_GAME,"#ffffff",22);k.addEventListener(ON_MOUSE_UP,this._onAutoSpin,this);q=s_oSpriteLibrary.getSprite("spin_but");e=new CTextButton(1111+q.width/2,595,q,TEXT_SPIN,FONT_GAME,"#ffffff",26);e.addEventListener(ON_MOUSE_UP,this._onSpin,this);q=s_oSpriteLibrary.getSprite("info_but");r=new CTextButton(296+q.width/2,595,q,TEXT_INFO,FONT_GAME,"#ffffff",30);r.addEventListener(ON_MOUSE_UP,
this._onInfo,this);q=s_oSpriteLibrary.getSprite("but_lines_bg");p=new CTextButton(436+q.width/2,595,q,TEXT_LINES,FONT_GAME,"#ffffff",30);p.addEventListener(ON_MOUSE_UP,this._onAddLine,this);q=s_oSpriteLibrary.getSprite("coin_but");v=new CTextButton(620+q.width/2,595,q,TEXT_COIN,FONT_GAME,"#ffffff",30);v.addEventListener(ON_MOUSE_UP,this._onBet,this);q=s_oSpriteLibrary.getSprite("but_maxbet_bg");x=new CTextButton(805+q.width/2,595,q,TEXT_MAX_BET,FONT_GAME,"#ffffff",30);x.addEventListener(ON_MOUSE_UP,
this._onMaxBet,this);C=new createjs.Text(TEXT_MONEY+"\n"+d.toFixed(2),"bold 24px "+FONT_GAME,"#ffde00");C.x=408;C.y=20;C.textAlign="center";s_oAttachSection.addChild(C);w=new createjs.Text(NUM_PAYLINES,"bold 30px "+FONT_GAME,"#ffffff");w.x=530;w.y=CANVAS_HEIGHT-94;w.textAlign="center";w.textBaseline="alphabetic";w.shadow=new createjs.Shadow("#000000",1,1,2);s_oAttachSection.addChild(w);y=new createjs.Text(a.toFixed(2),"bold 30px "+FONT_GAME,"#ffffff");y.x=712;y.y=CANVAS_HEIGHT-94;y.textAlign="center";
y.textBaseline="alphabetic";y.shadow=new createjs.Shadow("#000000",1,1,2);s_oAttachSection.addChild(y);D=new createjs.Text(TEXT_BET+": "+b.toFixed(2),"bold 30px "+FONT_GAME,"#ffffff");D.x=918;D.y=CANVAS_HEIGHT-94;D.textAlign="center";D.textBaseline="alphabetic";D.shadow=new createjs.Shadow("#000000",1,1,2);s_oAttachSection.addChild(D);A=new createjs.Text("","bold 24px "+FONT_GAME,"#ffde00");A.x=1116;A.y=CANVAS_HEIGHT-94;A.textAlign="center";A.textBaseline="alphabetic";A.shadow=new createjs.Shadow("#000000",
1,1,2);s_oAttachSection.addChild(A);z=new createjs.Text("","bold 54px "+FONT_GAME,"#ffde00");z.x=974;z.y=59;z.textAlign="center";z.textBaseline="alphabetic";s_oAttachSection.addChild(z);q=s_oSpriteLibrary.getSprite("bet_but");h=[];a=q.height/2;b=84+a;d=new CBetBut(319+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,4);h[3]=d;b+=43;d=new CBetBut(319+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,2);h[1]=d;b+=43;d=new CBetBut(319+
q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,20);h[19]=d;b+=43;d=new CBetBut(319+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,16);h[15]=d;b+=43;d=new CBetBut(319+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,10);h[9]=d;b+=43;d=new CBetBut(319+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,1);h[0]=d;b+=44;d=new CBetBut(319+q.width/2,b,
q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,11);h[10]=d;b+=43;d=new CBetBut(319+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,17);h[16]=d;b+=43;d=new CBetBut(319+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,3);h[2]=d;d=new CBetBut(319+q.width/2,b+43,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,5);h[4]=d;b=84+a;d=new CBetBut(1130+q.width/2,b,!0);d.addEventListenerWithParams(ON_MOUSE_UP,
this._onBetLineClicked,this,14);h[13]=d;b+=43;d=new CBetBut(1130+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,12);h[11]=d;b+=43;d=new CBetBut(1130+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,9);h[8]=d;b+=43;d=new CBetBut(1130+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,18);h[17]=d;b+=43;d=new CBetBut(1130+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,
this,6);h[5]=d;b+=44;d=new CBetBut(1130+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,7);h[6]=d;b+=43;d=new CBetBut(1130+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,19);h[18]=d;b+=43;d=new CBetBut(1130+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,8);h[7]=d;b+=43;d=new CBetBut(1130+q.width/2,b,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,13);h[12]=
d;d=new CBetBut(1130+q.width/2,b+43,q,!0);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,15);h[14]=d;n=[];for(q=0;q<NUM_PAYLINES;q++)a=createBitmap(s_oSpriteLibrary.getSprite("payline_"+(q+1))),a.visible=!1,s_oAttachSection.addChild(a),n[q]=a;this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){t.unload();t=null;e.unload();e=null;k.unload();k=null;r.unload();r=null;p.unload();p=null;v.unload();v=null;x.unload();x=null;!1===DISABLE_SOUND_MOBILE&&(l.unload(),l=
null);for(var a=0;a<NUM_PAYLINES;a++)h[a].unload();s_oInterface=null};this.refreshButtonPos=function(a,b){t.setPosition(c-a,b+f);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(g-a,b+m)};this.refreshMoney=function(a){C.text=TEXT_MONEY+"\n"+a.toFixed(2)};this.refreshBet=function(a){y.text=a.toFixed(2)};this.refreshTotalBet=function(a){D.text=TEXT_BET+": "+a.toFixed(2)};this.refreshNumLines=function(a){w.text=a;for(var b=0;b<NUM_PAYLINES;b++)b<a?(h[b].setOn(),n[b].visible=!0):h[b].setOff();
setTimeout(function(){for(var a=0;a<NUM_PAYLINES;a++)n[a].visible=!1},1E3)};this.resetWin=function(){A.text=" "};this.refreshWinText=function(a){A.text=TEXT_WIN+" "+a.toFixed(2)};this.refreshFreeSpinNum=function(a){z.text=a};this.showLine=function(a){n[a-1].visible=!0};this.hideLine=function(a){n[a-1].visible=!1};this.hideAllLines=function(){for(var a=0;a<NUM_PAYLINES;a++)n[a].visible=!1};this.disableBetBut=function(a){for(var b=0;b<NUM_PAYLINES;b++)h[b].disable(a)};this.enableGuiButtons=function(){e.enable();
k.setText(TEXT_AUTOSPIN);k.enable();x.enable();v.enable();p.enable();r.enable()};this.enableSpin=function(){e.enable();k.setText(TEXT_AUTOSPIN);k.enable();x.enable()};this.enableAutoSpin=function(){k.enable()};this.disableSpin=function(a){e.disable();a?k.setText(TEXT_STOP_AUTO):k.disable();x.disable()};this.disableAutoSpin=function(){k.disable()};this.disableGuiButtons=function(a){e.disable();a?k.setText(TEXT_STOP_AUTO):k.disable();x.disable();v.disable();p.disable();r.disable()};this._onBetLineClicked=
function(a){this.refreshNumLines(a);s_oGame.activateLines(a)};this._onExit=function(){s_oGame.onExit()};this._onSpin=function(){s_oGame.onSpin()};this._onAutoSpin=function(){if(k.getText()===TEXT_AUTOSPIN)s_oGame.onAutoSpin();else k.disable(),k.setText(TEXT_AUTOSPIN),s_oGame.onStopAutoSpin()};this._onAddLine=function(){s_oGame.addLine()};this._onInfo=function(){s_oGame.onInfoClicked()};this._onBet=function(){s_oGame.changeCoinBet()};this._onMaxBet=function(){s_oGame.onMaxBet()};this._onAudioToggle=
function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oInterface=this;this._init(a,d,b);return this}var s_oInterface=null;
function CPayTablePanel(){var a,d,b,c,f,g,m,h,n,t;this._init=function(){a=0;c=[];t=new createjs.Container;t.visible=!1;s_oAttachSection.addChild(t);var e=new createjs.Container;t.addChild(e);var k=createBitmap(s_oSpriteLibrary.getSprite("paytable1"));e.addChild(k);d=[];var r=450,p=122;d[0]=[];for(k=0;3>k;k++){var l=new createjs.Text("X"+(5-k),"bold 26px "+FONT_PAYTABLE,"#ffffff");l.textAlign="center";l.x=r;l.y=p;l.textBaseline="alphabetic";e.addChild(l);d[0][k]=l;p+=49}r=450;p=302;d[1]=[];for(k=0;3>
k;k++)l=new createjs.Text("X"+(5-k),"bold 26px "+FONT_PAYTABLE,"#ffffff"),l.textAlign="center",l.x=r,l.y=p,l.textBaseline="alphabetic",e.addChild(l),d[1][k]=l,p+=49;r=450;p=486;d[2]=[];for(k=0;3>k;k++)l=new createjs.Text("X"+(5-k),"bold 26px "+FONT_PAYTABLE,"#ffffff"),l.textAlign="center",l.x=r,l.y=p,l.textBaseline="alphabetic",e.addChild(l),d[2][k]=l,p+=49;r=780;p=122;d[3]=[];for(k=0;3>k;k++)l=new createjs.Text("X"+(5-k),"bold 26px "+FONT_PAYTABLE,"#ffffff"),l.textAlign="center",l.x=r,l.y=p,l.textBaseline=
"alphabetic",e.addChild(l),d[3][k]=l,p+=49;r=780;p=302;d[4]=[];for(k=0;3>k;k++)l=new createjs.Text("X"+(5-k),"bold 26px "+FONT_PAYTABLE,"#ffffff"),l.textAlign="center",l.x=r,l.y=p,l.textBaseline="alphabetic",e.addChild(l),d[4][k]=l,p+=49;r=1100;p=122;d[5]=[];for(k=0;3>k;k++)l=new createjs.Text("X"+(5-k),"bold 26px "+FONT_PAYTABLE,"#ffffff"),l.textAlign="center",l.x=r,l.y=p,l.textBaseline="alphabetic",e.addChild(l),d[5][k]=l,p+=49;r=1100;p=302;d[6]=[];for(k=0;3>k;k++)l=new createjs.Text("X"+(5-k),
"bold 26px "+FONT_PAYTABLE,"#ffffff"),l.textAlign="center",l.x=r,l.y=p,l.textBaseline="alphabetic",e.addChild(l),d[6][k]=l,p+=49;b=[];r=510;p=122;b[0]=[];for(k=0;3>k;k++)l=new createjs.Text(s_aSymbolWin[0][4-k],"bold 26px "+FONT_PAYTABLE,"#ffff00"),l.textAlign="center",l.x=r,l.y=p,l.textBaseline="alphabetic",e.addChild(l),b[0][k]=l,p+=49;r=510;p=302;b[3]=[];for(k=0;3>k;k++)l=new createjs.Text(s_aSymbolWin[3][4-k],"bold 26px "+FONT_PAYTABLE,"#ffff00"),l.textAlign="center",l.x=r,l.y=p,l.textBaseline=
"alphabetic",e.addChild(l),b[3][k]=l,p+=49;r=510;p=486;b[6]=[];for(k=0;3>k;k++)l=new createjs.Text(s_aSymbolWin[6][4-k],"bold 26px "+FONT_PAYTABLE,"#ffff00"),l.textAlign="center",l.x=r,l.y=p,l.textBaseline="alphabetic",e.addChild(l),b[6][k]=l,p+=49;r=830;p=122;b[1]=[];for(k=0;3>k;k++)l=new createjs.Text(s_aSymbolWin[1][4-k],"bold 26px "+FONT_PAYTABLE,"#ffff00"),l.textAlign="center",l.x=r,l.y=p,l.textBaseline="alphabetic",e.addChild(l),b[1][k]=l,p+=49;r=830;p=302;b[4]=[];for(k=0;3>k;k++)l=new createjs.Text(s_aSymbolWin[4][4-
k],"bold 26px "+FONT_PAYTABLE,"#ffff00"),l.textAlign="center",l.x=r,l.y=p,l.textBaseline="alphabetic",e.addChild(l),b[4][k]=l,p+=49;r=1150;p=122;b[2]=[];for(k=0;3>k;k++)l=new createjs.Text(s_aSymbolWin[2][4-k],"bold 26px "+FONT_PAYTABLE,"#ffff00"),l.textAlign="center",l.x=r,l.y=p,l.textBaseline="alphabetic",e.addChild(l),b[2][k]=l,p+=49;r=1150;p=302;b[5]=[];for(k=0;3>k;k++)l=new createjs.Text(s_aSymbolWin[5][4-k],"bold 26px "+FONT_PAYTABLE,"#ffff00"),l.textAlign="center",l.x=r,l.y=p,l.textBaseline=
"alphabetic",e.addChild(l),b[5][k]=l,p+=49;m=new createjs.Text(TEXT_HELP_WILD,"bold 26px "+FONT_PAYTABLE,"#ffff00");m.textAlign="center";m.x=986;m.y=484;e.addChild(m);c[0]=e;e=new createjs.Container;e.visible=!1;t.addChild(e);k=createBitmap(s_oSpriteLibrary.getSprite("paytable2"));e.addChild(k);l=new createjs.Text(TEXT_HELP_BONUS1,"bold 26px "+FONT_PAYTABLE,"#fff");l.textAlign="center";l.x=986;l.y=124;l.lineWidth=400;e.addChild(l);k=new createjs.Text(TEXT_HELP_BONUS2,"bold 26px "+FONT_PAYTABLE,"#fff");
k.textAlign="center";k.x=506;k.y=304;k.lineWidth=400;e.addChild(k);c[1]=e;e=new createjs.Container;e.visible=!1;t.addChild(e);k=createBitmap(s_oSpriteLibrary.getSprite("paytable3"));e.addChild(k);l=new createjs.Text(TEXT_HELP_FREESPIN,"bold 32px "+FONT_PAYTABLE,"#ffff00");l.textAlign="center";l.x=CANVAS_WIDTH/2;l.y=328;l.lineWidth=400;e.addChild(l);c[2]=e;f=c[a];g=new createjs.Shape;g.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);var v=this;g.on("click",function(){v._onExit()});
t.addChild(g);h=new CGfxButton(CANVAS_WIDTH-300,50,s_oSpriteLibrary.getSprite("but_arrow_next"),t);h.addEventListener(ON_MOUSE_UP,this._onNext,this);n=new CGfxButton(300,50,s_oSpriteLibrary.getSprite("but_arrow_prev"),t);n.addEventListener(ON_MOUSE_UP,this._onPrev,this)};this.unload=function(){var a=this;g.off("click",function(){a._onExit()});s_oAttachSection.removeChild(t);for(var c=0;c<d.length;c++)t.removeChild(d[c]);for(c=0;c<b.length;c++)t.removeChild(b[c])};this._onNext=function(){a===c.length-
1?a=0:a++;f.visible=!1;c[a].visible=!0;f=c[a]};this._onPrev=function(){0===a?a=c.length-1:a--;f.visible=!1;c[a].visible=!0;f=c[a]};this.show=function(){a=0;f.visible=!1;c[a].visible=!0;f=c[a];t.visible=!0};this.hide=function(){t.visible=!1};this.resetHighlightCombo=function(){for(var a=0;a<d.length;a++)for(var c=0;c<d[a].length;c++)d[a][c].color="#ffffff",b[a][c].color="#ffff00",createjs.Tween.removeTweens(b[a][c]),b[a][c].alpha=1};this.highlightCombo=function(a,c){b[a-1][NUM_REELS-c].color="#ff0000";
this.tweenAlpha(b[a-1][NUM_REELS-c],0)};this.tweenAlpha=function(a,b){var c=this;createjs.Tween.get(a).to({alpha:b},200).call(function(){1===b?c.tweenAlpha(a,0):c.tweenAlpha(a,1)})};this._onExit=function(){s_oGame.hidePayTable()};this.isVisible=function(){return t.visible};this._init()}
function CStaticSymbolCell(a,d,b,c){var f=-1,g,m,h,n;this._init=function(a,b,c,d){n=new createjs.Container;n.visible=!1;m=[];for(a=0;a<NUM_SYMBOLS;a++)b=createSprite(s_aSymbolAnims[a],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE),b.stop(),b.x=c,b.y=d,b.on("animationend",this._onAnimEnded,null,!1,{index:a}),n.addChild(b),m[a]=b,m[a].visible=!1;a={framerate:60,images:[s_oSpriteLibrary.getSprite("win_frame_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,
19]}};a=new createjs.SpriteSheet(a);h=new createjs.Sprite(a,"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);h.stop();h.x=c;h.y=d;n.addChild(h);s_oAttachSection.addChild(n)};this.unload=function(){s_oAttachSection.removeChild(n)};this.hide=function(){-1<f&&(h.gotoAndStop("static"),h.visible=!1,m[f].gotoAndPlay("static"),n.visible=!1)};this.show=function(a){h.gotoAndPlay("anim");h.visible=!0;for(var b=0;b<NUM_SYMBOLS;b++)m[b].visible=b+1===a?!0:!1;m[a-1].gotoAndPlay("anim");f=a-1;g=m[a-1].spriteSheet.getNumFrames();
n.visible=!0};this._onAnimEnded=function(a,b){m[b.index].currentFrame!==g&&(m[b.index].stop(),setTimeout(function(){m[b.index].gotoAndPlay(1)},100))};this.stopAnim=function(){m[f].gotoAndStop("static");m[f].visible=!1;h.gotoAndStop("static");h.visible=!1};this._init(a,d,b,c)}
function CTweenController(){this.tweenValue=function(a,d,b){return a+b*(d-a)};this.easeLinear=function(a,d,b,c){return b*a/c+d};this.easeInCubic=function(a,d,b,c){c=(a/=c)*a*a;return d+b*c};this.easeBackInQuart=function(a,d,b,c){c=(a/=c)*a;return d+b*(2*c*c+2*c*a+-3*c)};this.easeInBack=function(a,d,b,c){return b*(a/=c)*a*(2.70158*a-1.70158)+d};this.easeOutCubic=function(a,d,b,c){return b*((a=a/c-1)*a*a+1)+d}}
function CMsgBox(){var a,d,b,c,f;this._init=function(){f=new createjs.Container;f.visible=!1;s_oStage.addChild(f);a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));f.addChild(a);b=new createjs.Text("","bold 24px "+FONT_GAME,"#000");b.x=CANVAS_WIDTH/2+2;b.y=CANVAS_HEIGHT/2-48;b.textAlign="center";f.addChild(b);d=new createjs.Text("","bold 24px "+FONT_GAME,"#ffffff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-50;d.textAlign="center";f.addChild(d);c=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-200,s_oSpriteLibrary.getSprite("but_bg"),
TEXT_OK,"walibi0615bold","#ffffff",40,f);c.addEventListener(ON_MOUSE_UP,this._onExit,this)};this.show=function(a){b.text=a;d.text=a;f.visible=!0};this.hide=function(){f.visible=!1};this._onExit=function(){this.hide()};this._init();return this}
function CVector2(a,d){var b,c;this._init=function(a,d){b=a;c=d};this.add=function(a,d){b+=a;c+=d};this.addV=function(a){b+=a.getX();c+=a.getY()};this.scalarDivision=function(a){b/=a;c/=a};this.subV=function(a){b-=a.getX();c-=a.getY()};this.scalarProduct=function(a){b*=a;c*=a};this.invert=function(){b*=-1;c*=-1};this.dotProduct=function(a){return b*a.getX()+c*a.getY()};this.set=function(a,d){b=a;c=d};this.setV=function(a){b=a.getX();c=a.getY()};this.length=function(){return Math.sqrt(b*b+c*c)};this.length2=
function(){return b*b+c*c};this.normalize=function(){var a=this.length();0<a&&(b/=a,c/=a)};this.getNormalize=function(a){this.length();a.set(b,c);a.normalize()};this.rot90CCW=function(){var a=b;b=-c;c=a};this.rot90CW=function(){var a=b;b=c;c=-a};this.getRotCCW=function(a){a.set(b,c);a.rot90CCW()};this.getRotCW=function(a){a.set(b,c);a.rot90CW()};this.ceil=function(){b=Math.ceil(b);c=Math.ceil(c)};this.round=function(){b=Math.round(b);c=Math.round(c)};this.toString=function(){return"Vector2: "+b+", "+
c};this.print=function(){trace("Vector2: "+b+", "+c+"")};this.getX=function(){return b};this.getY=function(){return c};this._init(a,d)}
function CFormatText(a,d,b,c){var f,g,m,h;this._init=function(a,b,c,d){f=0;h=new createjs.Container;h.x=a;h.y=b;d.addChild(h);a=56;b=a/20;for(d=0;d<c.length;d++){var r=a+"px";g=new createjs.Text;g.text=c[d];g.font="bold "+r+" "+FONT_GAME;g.color="#000000";g.textAlign="left";g.textBaseline="middle";g.x=f+2;g.y=2;h.addChild(g);m=new createjs.Text;m.text=c[d];m.font="bold "+r+" "+FONT_GAME;m.color="#ffffff";m.textAlign="left";m.textBaseline="middle";m.x=f;h.addChild(m);f+=g.getMeasuredWidth()+b;a-=9}};
this.unload=function(){c.removeChild(h)};this.rotateText=function(a){h.rotation=a};this._init(a,d,b,c)}
function CWheelBonus(a,d,b){var c,f,g,m,h,n,t;this._init=function(a,b){c=[];f=[];g=[];for(var d=0;d<WHEEL_SETTINGS.length;d++)g[d]=WHEEL_SETTINGS[d];this._initColors();d=s_oSpriteLibrary.getSprite("wheel");h=new createjs.Container;h.x=a;h.y=b;t.addChild(h);m=createBitmap(d);m.regX=d.width/2;m.regY=d.height/2;h.addChild(m);this.setText(1)};this.unload=function(){t.removeChild(h)};this._initColors=function(){for(var a=0;9>a;a++)f[0]="violet";for(a=351;360>=a;a++)f[a]="violet";for(var b=0;4>b;b++)for(a=
9+b*SEGMENT_ROT*5;a<27+b*SEGMENT_ROT*5;a++)f[a]="blue";for(b=0;4>b;b++)for(a=27+b*SEGMENT_ROT*5;a<45+b*SEGMENT_ROT*5;a++)f[a]="green";for(b=0;4>b;b++)for(a=45+b*SEGMENT_ROT*5;a<63+b*SEGMENT_ROT*5;a++)f[a]="yellow";for(b=0;4>b;b++)for(a=63+b*SEGMENT_ROT*5;a<81+b*SEGMENT_ROT*5;a++)f[a]="red";for(b=0;3>b;b++)for(a=81+b*SEGMENT_ROT*5;a<=99+b*SEGMENT_ROT*5;a++)f[a]="violet";for(a=315;333>=a;a++)f[a]="white"};this.setText=function(a){for(var b=new CVector2(-210,3),d=SEGMENT_ROT,f=Math.PI*SEGMENT_ROT/180,
l=0;l<g.length;l++)c[l]=new CFormatText(b.getX(),b.getY(),TEXT_CURRENCY+g[l]*a,h),c[l].rotateText(-d*l),rotateVector2D(f,b)};this.clearText=function(){for(var a=0;a<g.length;a++)c[a].unload()};this.spin=function(a,b){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)playSound("start_reel_bonus",1,0),n=playSound("reel_bonus",1,-1);createjs.Tween.get(h).to({rotation:h.rotation+a},WHEEL_SPIN_TIMESPEED*b,createjs.Ease.quartOut).call(function(){h.rotation%=360;s_oBonusPanel.wheelArrived();!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||n.stop()})};this.getDegree=function(){return h.rotation};this.getColor=function(){return f[Math.round(h.rotation)]};t=b;this._init(a,d)}
function CBonusPanel(){var a,d,b,c,f,g,m,h,n,t,e,k;this._init=function(){m=c=b=0;a=!1;f=STATE_BONUS_IDLE;k=new createjs.Container;k.visible=!1;s_oAttachSection.addChild(k);h=new CWheelBonus(890,320,k);var g=createBitmap(s_oSpriteLibrary.getSprite("bg_bonus"));k.addChild(g);n=new CLedsBonus(890,320,k);d=n.getState();g=s_oSpriteLibrary.getSprite("but_spin_bonus");t=new CTextButton(360+g.width/2,490,g,TEXT_SPIN,FONT_GAME,"#ffffff",40,k);t.addEventListener(ON_MOUSE_UP,this._onSpin,this);g=new createjs.Text(TEXT_BONUS_HELP,
"bold 56px "+FONT_GAME,"#000");g.x=490;g.y=132;g.textAlign="center";g.textBaseline="alphabetic";g.lineWidth=300;k.addChild(g);g=new createjs.Text(TEXT_BONUS_HELP,"bold 56px "+FONT_GAME,"white");g.x=488;g.y=130;g.textAlign="center";g.textBaseline="alphabetic";g.lineWidth=300;k.addChild(g);e=new createjs.Text(TEXT_CURRENCY+"0","bold 56px "+FONT_GAME,"yellow");e.x=464;e.y=340;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=400;e.alpha=m;k.addChild(e)};this.show=function(b){t.enable();e.text=
"";e.alpha=1;g=b;a=k.visible=!0};this._onSpin=function(){t.disable();f=STATE_BONUS_SPIN;c=0;var a=MIN_FAKE_SPIN+Math.floor(3*Math.random()),b=SEGMENT_ROT-3,b=-b/2+Math.random()*b,b=(360-h.getDegree()+g*SEGMENT_ROT+b)%360;h.spin(360*a+b,a)};this._animLedIdle=function(){b+=s_iTimeElaps;if(b>TIME_ANIM_IDLE){b=0;for(var a=Math.floor(Math.random()*n.getNumAnim());a===d;)a=Math.floor(Math.random()*n.getNumAnim());n.changeAnim(a);d=a}};this._animLedSpin=function(){n.changeAnim(LED_SPIN);f=-1};this._animLedWin=
function(){0===c?(n.changeAnim(4+Math.round(Math.random())),n.setWinColor(this.getCurColor())):c>TIME_ANIM_WIN&&(b=TIME_ANIM_IDLE,f=STATE_BONUS_IDLE,s_oBonusPanel.unload(),c=0);c+=s_iTimeElaps};this._animLedLose=function(){0===c?(n.changeAnim(6),n.setWinColor(this.getCurColor())):c>TIME_ANIM_LOSE&&(b=TIME_ANIM_IDLE,f=STATE_BONUS_IDLE,s_oBonusPanel.unload(),c=0);c+=s_iTimeElaps};this.getCurColor=function(){return h.getColor()};this.wheelArrived=function(){e.text=TEXT_CURRENCY+WHEEL_SETTINGS[g];this._animWinText();
0>=WHEEL_SETTINGS[g].prize?(f=STATE_BONUS_LOSE,playSound("game_over_bonus",1,0)):(f=STATE_BONUS_WIN,playSound("win_bonus",1,0))};this._animWinText=function(){m=1===m?0:1;createjs.Tween.get(e).to({alpha:m},150,createjs.Ease.cubicOut).call(function(){s_oBonusPanel._animWinText()})};this.unload=function(){a=!1;k.visible=!1;createjs.Tween.removeTweens(e);s_oGame.exitFromBonus()};this.update=function(){if(a)switch(n.update(),f){case STATE_BONUS_IDLE:this._animLedIdle();break;case STATE_BONUS_SPIN:this._animLedSpin();
break;case STATE_BONUS_WIN:this._animLedWin();break;case STATE_BONUS_LOSE:this._animLedLose()}};s_oBonusPanel=this;this._init()}var s_oBonusPanel=null;
function CLedsBonus(a,d,b){var c,f,g,m,h,n,t,e,k,r;this._init=function(a,b){h=3;g=Math.floor(Math.random()*h);m=0;e=[];k=new createjs.Container;k.x=a;k.y=b;r.addChild(k);for(var c={images:[s_oSpriteLibrary.getSprite("leds")],frames:{width:54,height:54,regX:27,regY:27},animations:{off:[0],white:[1],green:[2],blue:[3],violet:[4],red:[5],yellow:[6]}},c=new createjs.SpriteSheet(c),d=new CVector2(-255,0),f=360/WHEEL_SETTINGS.length*Math.PI/180,n=0;n<WHEEL_SETTINGS.length;n++)e[n]=createSprite(c,"off",
0,0,54,54),e[n].x=d.getX(),e[n].y=d.getY(),rotateVector2D(f,d),k.addChild(e[n]);e[0].visible=!1};this.unload=function(){r.removeChild(k)};this.setWinColor=function(a){c=a};this.getState=function(){return g};this.getNumAnim=function(){return h};this.changeAnim=function(a){m=0;g=a;for(a=0;a<e.length;a++)e[a].gotoAndStop("off")};this.animIdle0=function(){m+=s_iTimeElaps;if(0<=m&&m<ANIM_IDLE1_TIMESPEED/2)for(var a=0;a<e.length;a++)0===a%2?e[a].gotoAndStop("white"):e[a].gotoAndStop("off");else if(m>=ANIM_IDLE1_TIMESPEED/
2&&m<ANIM_IDLE1_TIMESPEED)for(a=0;a<e.length;a++)0===a%2?e[a].gotoAndStop("off"):e[a].gotoAndStop("white");else m=0};this.animIdle1=function(){0===m&&(n=0,e[n].gotoAndStop("white"),e[e.length/4].gotoAndStop("white"),e[e.length/2].gotoAndStop("white"),e[3*e.length/4].gotoAndStop("white"));m+=s_iTimeElaps;m>ANIM_IDLE2_TIMESPEED&&(n===e.length/4&&(n=0,m=1),0===n?(e[e.length-1].gotoAndStop("off"),e[0].gotoAndStop("white"),e[e.length/4-1].gotoAndStop("off"),e[e.length/4].gotoAndStop("white"),e[e.length/
2-1].gotoAndStop("off"),e[e.length/2].gotoAndStop("white"),e[3*e.length/4-1].gotoAndStop("off"),e[3*e.length/4].gotoAndStop("white")):(e[n-1].gotoAndStop("off"),e[n].gotoAndStop("white"),e[e.length/4+n-1].gotoAndStop("off"),e[e.length/4+n].gotoAndStop("white"),e[e.length/2+n-1].gotoAndStop("off"),e[e.length/2+n].gotoAndStop("white"),e[3*e.length/4+n-1].gotoAndStop("off"),e[3*e.length/4+n].gotoAndStop("white")),n++,m=1)};this.animIdle2=function(){0===m&&(n=0,t=e.length/2,e[n].gotoAndStop("white"),
e[t].gotoAndStop("white"));m+=s_iTimeElaps;m>ANIM_IDLE3_TIMESPEED&&(n===e.length/2&&(n=0,t=e.length/2,m=1),0===n?(e[e.length-1].gotoAndStop("off"),e[1].gotoAndStop("off"),e[0].gotoAndStop("white"),e[e.length/2+1].gotoAndStop("off"),e[e.length/2-1].gotoAndStop("off"),e[e.length/2].gotoAndStop("white")):(e[n-1].gotoAndStop("off"),e[n].gotoAndStop("white"),1!==n&&e[e.length-n+1].gotoAndStop("off"),e[e.length-n].gotoAndStop("white"),e[t+1].gotoAndStop("off"),e[t].gotoAndStop("white"),e[e.length-t-1].gotoAndStop("off"),
0!==t&&e[e.length-t].gotoAndStop("white")),n++,t--,m=1)};this.animSpin0=function(){0===m&&(n=Math.floor(Math.random()*e.length),e[n].gotoAndStop("white"));m+=s_iTimeElaps;m>ANIM_SPIN_TIMESPEED&&(0>n&&(n=e.length-1,m=1),n===e.length-1?(e[0].gotoAndStop("off"),e[e.length-1].gotoAndStop("white")):(e[n+1].gotoAndStop("off"),e[n].gotoAndStop("white")),n--,m=1)};this.animWin0=function(){m+=s_iTimeElaps;if(0<=m&&m<ANIM_WIN1_TIMESPEED/2)for(var a=0;a<e.length;a++)0===a%2?e[a].gotoAndStop(c):e[a].gotoAndStop("off");
else if(m>=ANIM_WIN1_TIMESPEED/2&&m<ANIM_WIN1_TIMESPEED)for(a=0;a<e.length;a++)0===a%2?e[a].gotoAndStop("off"):e[a].gotoAndStop(c);else m=0};this.animWin1=function(){0===m&&(n=0,t=e.length/2,f=c,e[n].gotoAndStop(f),e[t].gotoAndStop(f));m+=s_iTimeElaps;m>ANIM_WIN2_TIMESPEED&&(n>e.length/4&&(n=0,t=e.length/2,m=1,f=f===c?"off":c),0===n?(e[0].gotoAndStop(f),e[e.length/2].gotoAndStop(f)):n<=e.length/4&&(e[n].gotoAndStop(f),e[e.length-n].gotoAndStop(f),e[t].gotoAndStop(f),0!==t&&e[e.length-t].gotoAndStop(f)),
n++,t--,m=1)};this.animLose=function(){for(var a=0;a<e.length;a++)e[a].gotoAndStop(c);g=-1};this.update=function(){switch(g){case 0:this.animIdle0();break;case 1:this.animIdle1();break;case 2:this.animIdle2();break;case 3:this.animSpin0();break;case 4:this.animWin0();break;case 5:this.animWin1();break;case 6:this.animLose()}};r=b;this._init(a,d)}
var s_aSession=[],NUM_ROWS=3,NUM_REELS=5,_aFinalSymbols=[],_aRandSymbols=[],_aRandSymbols=_initSymbolsOccurence(),_aPaylineCombo=[],_aPaylineCombo=_initPaylines(),_aSymbolWin=[],_aSymbolWin=_initSymbolWin(),_iNumSymbolFreeSpin=0;s_aSession.bBonus=0;
function _initSettings(){s_aSession.iMoney=TOTAL_MONEY;s_aSession.iSlotCash=SLOT_CASH;s_aSession.win_occurrence=WIN_OCCURRENCE;s_aSession.freespin_occurrence=FREESPIN_OCCURRENCE;s_aSession.bonus_occurrence=BONUS_OCCURRENCE;s_aSession.freespin_symbol_num_occur=FREESPIN_SYMBOL_NUM_OCCURR;s_aSession.num_freespin=NUM_FREESPIN;s_aSession.bonus_prize=BONUS_PRIZE;s_aSession.bonus_prize_occur=BONUS_PRIZE_OCCURR;s_aSession.coin_bet=COIN_BET}
function checkLogin(){s_aSession.iTotFreeSpin=0;s_aSession.bFreeSpin=0;_initSettings();_setMinWin();return _tryToCheckLogin()}function callSpin(a,d,b){return _onSpin(a,d,b)}function _tryToCheckLogin(){for(var a=[],d=0;d<_aSymbolWin.length;d++)a[d]=_aSymbolWin[d].join(",");return"res=true&login=true&money="+s_aSession.iMoney+"&bonus_prize="+s_aSession.bonus_prize.join("#")+"&paytable="+a.join("#")+"&coin_bet="+s_aSession.coin_bet.join("#")}
function _setMinWin(){s_aSession.min_win=_aSymbolWin[0][_aSymbolWin[0].length-1];for(var a=0;a<_aSymbolWin.length;a++)for(var d=_aSymbolWin[a],b=0;b<d.length;b++)0!==d[b]&&d[b]<s_aSession.min_win&&(s_aSession.min_win=d[b])}
function _onSpin(a,d,b){if(b>s_aSession.iMoney)_dieError("INVALID BET: "+b+",money:"+s_aSession.iMoney);else{s_aSession.iMoney-=b;s_aSession.iSlotCash+=b;var c=s_aSession.bBonus=0,f=0;if(s_aSession.iSlotCash<s_aSession.min_win)return generLosingPattern(),1===s_aSession.bFreeSpin&&(--s_aSession.iTotFreeSpin,0>s_aSession.iTotFreeSpin&&(s_aSession.iTotFreeSpin=0,s_aSession.bFreeSpin=0)),"res=true&win=false&pattern="+JSON.stringify(_aFinalSymbols)+"&money="+s_aSession.iMoney+"&freespin="+s_aSession.iTotFreeSpin+
"&bonus=false&bonus_prize=-1&cash="+s_aSession.iSlotCash;if(Math.floor(101*Math.random())<s_aSession.win_occurrence){0===s_aSession.bFreeSpin&&0===s_aSession.bBonus&&(b=Math.floor(101*Math.random()),0===s_aSession.iTotFreeSpin&&b<s_aSession.freespin_occurrence+s_aSession.bonus_occurrence&&(b=Math.floor(Math.random()*(s_aSession.freespin_occurrence+s_aSession.bonus_occurrence)+1),b<=s_aSession.freespin_occurrence?c=1:f=1));do{generateRandomSymbols(c,f);b=checkWin(c,f,a);for(var g=0,m=0;m<b.length;m++)g+=
b[m].amount;g*=d}while(0===b.length||g>s_aSession.iSlotCash);s_aSession.iMoney+=g;s_aSession.iSlotCash-=g;a=-1;if(1===c&&2<_iNumSymbolFreeSpin)s_aSession.bFreeSpin=1,s_aSession.iTotFreeSpin=s_aSession.num_freespin[_iNumSymbolFreeSpin-3];else if(1===s_aSession.bFreeSpin)--s_aSession.iTotFreeSpin,0>s_aSession.iTotFreeSpin&&(s_aSession.iTotFreeSpin=0,s_aSession.bFreeSpin=0);else if(1===f){s_aSession.bBonus=1;a=[];for(d=0;d<s_aSession.bonus_prize_occur.length;d++)for(c=s_aSession.bonus_prize_occur[d],
f=0;f<c;f++)a.push(d);a=a[Math.floor(Math.random()*a.length)]}-1!==a&&(s_aSession.iMoney+=s_aSession.bonus_prize[a],s_aSession.iSlotCash-=s_aSession.bonus_prize[a]);return"res=true&win=true&pattern="+JSON.stringify(_aFinalSymbols)+"&win_lines="+JSON.stringify(b)+"&money="+s_aSession.iMoney+"&tot_win="+g+"&freespin="+s_aSession.iTotFreeSpin+"&bonus="+s_aSession.bBonus+"&bonus_prize="+a+"&cash="+s_aSession.iSlotCash}generLosingPattern();1===s_aSession.bFreeSpin&&(--s_aSession.iTotFreeSpin,0>s_aSession.iTotFreeSpin&&
(s_aSession.iTotFreeSpin=0,s_aSession.bFreeSpin=0));return"res=true&win=false&pattern="+JSON.stringify(_aFinalSymbols)+"&money="+s_aSession.iMoney+"&freespin="+s_aSession.iTotFreeSpin+"&bonus=false&bonus_prize=-1"}}
function _initPaylines(){_aPaylineCombo[0]=[{row:1,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:1,col:4}];_aPaylineCombo[1]=[{row:0,col:0},{row:0,col:1},{row:0,col:2},{row:0,col:3},{row:0,col:4}];_aPaylineCombo[2]=[{row:2,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:2,col:4}];_aPaylineCombo[3]=[{row:0,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:0,col:4}];_aPaylineCombo[4]=[{row:2,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:2,col:4}];_aPaylineCombo[5]=[{row:1,
col:0},{row:0,col:1},{row:0,col:2},{row:0,col:3},{row:1,col:4}];_aPaylineCombo[6]=[{row:1,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:1,col:4}];_aPaylineCombo[7]=[{row:0,col:0},{row:0,col:1},{row:1,col:2},{row:2,col:3},{row:2,col:4}];_aPaylineCombo[8]=[{row:2,col:0},{row:2,col:1},{row:1,col:2},{row:0,col:3},{row:0,col:4}];_aPaylineCombo[9]=[{row:1,col:0},{row:2,col:1},{row:1,col:2},{row:0,col:3},{row:1,col:4}];_aPaylineCombo[10]=[{row:2,col:0},{row:0,col:1},{row:1,col:2},{row:2,col:3},{row:1,
col:4}];_aPaylineCombo[11]=[{row:0,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:0,col:4}];_aPaylineCombo[12]=[{row:2,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:2,col:4}];_aPaylineCombo[13]=[{row:0,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:0,col:4}];_aPaylineCombo[14]=[{row:2,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:2,col:4}];_aPaylineCombo[15]=[{row:1,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:1,col:4}];_aPaylineCombo[16]=[{row:1,col:0},{row:1,
col:1},{row:2,col:2},{row:1,col:3},{row:1,col:4}];_aPaylineCombo[17]=[{row:0,col:0},{row:0,col:1},{row:2,col:2},{row:0,col:3},{row:0,col:4}];_aPaylineCombo[18]=[{row:2,col:0},{row:2,col:1},{row:0,col:2},{row:2,col:3},{row:2,col:4}];_aPaylineCombo[19]=[{row:0,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:0,col:4}];return _aPaylineCombo}
function _initSymbolsOccurence(){var a;for(a=0;1>a;a++)_aRandSymbols.push(1);for(a=0;2>a;a++)_aRandSymbols.push(2);for(a=0;3>a;a++)_aRandSymbols.push(3);for(a=0;4>a;a++)_aRandSymbols.push(4);for(a=0;5>a;a++)_aRandSymbols.push(5);for(a=0;6>a;a++)_aRandSymbols.push(6);for(a=0;7>a;a++)_aRandSymbols.push(7);for(a=0;1>a;a++)_aRandSymbols.push(8);for(a=0;2>a;a++)_aRandSymbols.push(9);for(a=0;2>a;a++)_aRandSymbols.push(10);return _aRandSymbols}
function _initSymbolWin(){_aSymbolWin[0]=[0,0,90,150,200];_aSymbolWin[1]=[0,0,80,110,160];_aSymbolWin[2]=[0,0,70,100,150];_aSymbolWin[3]=[0,0,50,80,110];_aSymbolWin[4]=[0,0,40,60,80];_aSymbolWin[5]=[0,0,30,50,70];_aSymbolWin[6]=[0,0,20,30,50];_aSymbolWin[7]=[0,0,0,0,0,50];_aSymbolWin[8]=[0,0,0,0,0,50];_aSymbolWin[9]=[0,0,0,0,0,50];return _aSymbolWin}
function generLosingPattern(){for(var a=[],d=0;d<NUM_ROWS;d++){do var b=Math.floor(Math.random()*_aRandSymbols.length);while(9===_aRandSymbols[b]||10===_aRandSymbols[b]||8===_aRandSymbols[b]);b=_aRandSymbols[b];a[d]=b}for(d=0;d<NUM_ROWS;d++){_aFinalSymbols[d]=[];for(var c=0;c<NUM_REELS;c++)if(0==c)_aFinalSymbols[d][c]=a[d];else{do b=Math.floor(Math.random()*_aRandSymbols.length),b=_aRandSymbols[b];while(a[0]===b||a[1]===b||a[2]===b||9===b||10===b||8===b);_aFinalSymbols[d][c]=b}}}
function generateRandomSymbols(a,d){for(var b=0;b<NUM_ROWS;b++){_aFinalSymbols[b]=[];for(var c=0;c<NUM_REELS;c++){do iRandSymbol=_aRandSymbols[Math.floor(Math.random()*_aRandSymbols.length)],_aFinalSymbols[b][c]=iRandSymbol;while(9===iRandSymbol||10===iRandSymbol)}}if(1===a){for(var f=[],b=0;b<s_aSession.freespin_symbol_num_occur.length;b++)for(c=0;c<s_aSession.freespin_symbol_num_occur[b];c++)f.push(b);_iNumSymbolFreeSpin=3+f[Math.floor(Math.random()*f.length)];b=[0,1,2,3,4];b=shuffle(b);for(c=0;c<
_iNumSymbolFreeSpin;c++)f=Math.floor(3*Math.random()),_aFinalSymbols[f][b[c]]=10}else if(1===d)for(var b=[0,1,2,3,4],b=shuffle(b),g=Math.floor(3*Math.random()+3),c=0;c<g;c++)f=Math.floor(3*Math.random()),_aFinalSymbols[f][b[c]]=9}
function checkWin(a,d,b){for(var c=[],f=0;f<b;f++){var g=_aPaylineCombo[f],m=[],h=_aFinalSymbols[g[0].row][g[0].col],n=1,t=1;for(m.push({row:g[0].row,col:g[0].col,value:_aFinalSymbols[g[0].row][g[0].col]});8===h&&t<NUM_REELS;)n++,h=_aFinalSymbols[g[t].row][g[t].col],m.push({row:g[t].row,col:g[t].col,value:_aFinalSymbols[g[t].row][g[t].col]}),t++;for(;t<g.length;t++)if(_aFinalSymbols[g[t].row][g[t].col]===h||8===_aFinalSymbols[g[t].row][g[t].col])n++,m.push({row:g[t].row,col:g[t].col,value:_aFinalSymbols[g[t].row][g[t].col]});
else break;0<_aSymbolWin[h-1][n-1]&&c.push({line:f+1,amount:_aSymbolWin[h-1][n-1],num_win:n,value:h,list:m})}if(1===a){m=[];for(a=0;a<NUM_ROWS;a++)for(d=0;d<NUM_REELS;d++)10===_aFinalSymbols[a][d]&&m.push({row:a,col:d,value:10});c.push({line:0,amount:0,num_win:m.length,value:10,list:m})}else if(1===d){m=[];for(a=0;a<NUM_ROWS;a++)for(d=0;d<NUM_REELS;d++)9===_aFinalSymbols[a][d]&&m.push({row:a,col:d,value:9});c.push({line:0,amount:0,num_win:m.length,value:9,list:m})}return c}
function shuffle(a){for(var d,b,c=a.length;c;d=Math.floor(Math.random()*c),b=a[--c],a[c]=a[d],a[d]=b);return a}function _dieError(a){return"res=false&desc="+a};
