var s_iOffsetX=0,s_iOffsetY=0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}window.addEventListener("orientationchange",onOrientationChange);
function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(a){var h=a.toLowerCase(),b=window.document,e=b.documentElement;if(void 0===window["inner"+a])a=e["client"+a];else if(window["inner"+a]!=e["client"+a]){var g=b.createElement("body");g.id="vpw-test-b";g.style.cssText="overflow:scroll";var f=b.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+h+":"+e["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+h+":7px!important}}</style>";g.appendChild(f);e.insertBefore(g,b.head);
a=7==f["offset"+a]?e["client"+a]:window["inner"+a];e.removeChild(g)}else a=window["inner"+a];return a}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var h=getSize("Width");s_iScaleFactor=Math.min(a/CANVAS_HEIGHT,h/CANVAS_WIDTH);var b=CANVAS_WIDTH*s_iScaleFactor,e=CANVAS_HEIGHT*s_iScaleFactor,g;e<a?(g=a-e,e+=g,b+=CANVAS_WIDTH/CANVAS_HEIGHT*g):b<h&&(g=h-b,b+=g,e+=CANVAS_HEIGHT/CANVAS_WIDTH*g);g=a/2-e/2;var f=h/2-b/2,d=CANVAS_WIDTH/b;if(f*d<-EDGEBOARD_X||g*d<-EDGEBOARD_Y)s_iScaleFactor=Math.min(a/
(CANVAS_HEIGHT-2*EDGEBOARD_Y),h/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=CANVAS_WIDTH*s_iScaleFactor,e=CANVAS_HEIGHT*s_iScaleFactor,g=(a-e)/2,f=(h-b)/2,d=CANVAS_WIDTH/b;s_iOffsetX=-1*f*d;s_iOffsetY=-1*g*d;0<=g&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",b+"px");$("#canvas").css("height",e+"px");0>g?$("#canvas").css("top",g+"px"):$("#canvas").css("top",
"0px");$("#canvas").css("left",f+"px")}}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function createBitmap(a,h,b){var e=new createjs.Bitmap(a),g=new createjs.Shape;h&&b?g.graphics.beginFill("#fff").drawRect(-h/2,-b/2,h,b):g.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);e.hitArea=g;return e}
function createSprite(a,h,b,e,g,f){a=null!==h?new createjs.Sprite(a,h):new createjs.Sprite(a);h=new createjs.Shape;h.graphics.beginFill("#000000").drawRect(-b,-e,g,f);a.hitArea=h;return a}function randomFloatBetween(a,h,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(h-a),h).toFixed(b))}function shuffle(a){for(var h=a.length,b,e;0!==h;)e=Math.floor(Math.random()*h),--h,b=a[h],a[h]=a[e],a[e]=b;return a}
function formatTime(a){a/=1E3;var h=Math.floor(a/60);a=parseFloat(a-60*h).toFixed(1);var b="",b=10>h?b+("0"+h+":"):b+(h+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,h){var b,e;b=getBounds(a,.9);e=getBounds(h,.98);return calculateIntersection(b,e)}
function calculateIntersection(a,h){var b,e,g,f,d,l,c,p;b=a.x+(g=a.width/2);e=a.y+(f=a.height/2);d=h.x+(l=h.width/2);c=h.y+(p=h.height/2);b=Math.abs(b-d)-(g+l);e=Math.abs(e-c)-(f+p);return 0>b&&0>e?(b=Math.min(Math.min(a.width,h.width),-b),e=Math.min(Math.min(a.height,h.height),-e),{x:Math.max(a.x,h.x),y:Math.max(a.y,h.y),width:b,height:e,rect1:a,rect2:h}):null}
function getBounds(a,h){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var e=a.children,g=e.length,f,d;for(d=0;d<g;d++)f=getBounds(e[d],1),f.x<b.x&&(b.x=f.x),f.y<b.y&&(b.y=f.y),f.x+f.width>b.x2&&(b.x2=f.x+f.width),f.y+f.height>b.y2&&(b.y2=f.y+f.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var l,c;a instanceof createjs.Bitmap?
(g=a.sourceRect||a.image,d=g.width*h,l=g.height*h):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(g=a.spriteSheet.getFrame(a.currentFrame),d=g.rect.width,l=g.rect.height,e=g.regX,c=g.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);e=e||0;d=d||0;c=c||0;l=l||0;b.regX=e;b.regY=c;g=a.localToGlobal(0-e,0-c);f=a.localToGlobal(d-e,l-c);d=a.localToGlobal(d-e,0-c);e=a.localToGlobal(0-e,l-c);b.x=Math.min(Math.min(Math.min(g.x,
f.x),d.x),e.x);b.y=Math.min(Math.min(Math.min(g.y,f.y),d.y),e.y);b.width=Math.max(Math.max(Math.max(g.x,f.x),d.x),e.x)-b.x;b.height=Math.max(Math.max(Math.max(g.y,f.y),d.y),e.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var h=document.createEvent("MouseEvents");h.initEvent("click",!0,!0);a.dispatchEvent(h)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[h]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var h="hidden";h in document?document.addEventListener("visibilitychange",a):(h="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(h="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(h="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function playSound(a,h,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:h}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}
function setVolume(a,h){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=h}function setMute(a,h){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(h)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var h=window.location.search.substring(1).split("&"),b=0;b<h.length;b++){var e=h[b].split("=");if(e[0]==a)return e[1]}}function distanceV2(a,h){var b=a.x-h.x,e=a.y-h.y;return b*b+e*e}
function collisionRect(a,h){return a.x<h.x+h.width&&a.x+a.width>h.x&&a.y<h.y+h.height&&a.y+a.height>h.y?!0:!1}function saveItem(a,h){s_bStorageAvailable&&localStorage.setItem(a,h)}function getItem(a){return s_bStorageAvailable?localStorage.getItem(a):null}function clearAllItem(){s_bStorageAvailable&&localStorage.clear()}
function CSpriteLibrary(){var a,h,b,e,g,f;this.init=function(d,l,c){b=h=0;e=d;g=l;f=c;a={}};this.addSprite=function(d,b){a.hasOwnProperty(d)||(a[d]={szPath:b,oSprite:new Image},h++)};this.getSprite=function(d){return a.hasOwnProperty(d)?a[d].oSprite:null};this._onSpritesLoaded=function(){g.call(f)};this._onSpriteLoaded=function(){e.call(f);++b==h&&this._onSpritesLoaded()};this.loadSprites=function(){for(var d in a)a[d].oSprite.oSpriteLibrary=this,a[d].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[d].oSprite.src=a[d].szPath};this.getNumSprites=function(){return h}}
var CANVAS_WIDTH=1360,CANVAS_HEIGHT=540,EDGEBOARD_X=300,EDGEBOARD_Y=100,FPS=30,DISABLE_SOUND_MOBILE=!1,FONT_GAME="rocks__gregular",TEXT_COLOR="#e6a900",CONFIRMATION_EXIT=0,CONFIRMATION_RESET=1,FPS_TIME=1E3/FPS,URL_LEVELS_SETTINGS="json/levels_settings.json",OFFSET_PLATFORM_COL_DIMENSION=[{x:6,y:8},{x:6,y:8}],OFFSET_PLATFORM_COL_POINT=[{x:2,y:6},{x:2,y:6}],OFFSET_HEIGHT_PLATFORM_CHRACTER=26,OFFSET_PLAYER_COL_DIMENSION={x:-55,y:-67},OFFSET_PLAYER_COL_POINT={x:70,y:50},TOLLERANCE_Y_FOR_ANIMATION=100,
PLATFORM_Y_START=120,LOGO_Y_POS=.5*CANVAS_HEIGHT-80,FIRST_PLATFORM_X=250,LAST_PLATFORM_X=.2*CANVAS_WIDTH,PARALLAXE_OBJ_X_RANDOMIZE=-150,PARALLAXE_OBJ_X_REPOS=CANVAS_WIDTH+150,MAX_POS_X_RANDOM_PARALLAXE=150,MAX_SCALE_PARALLAXE=1,MIN_SCALE_PARALLAXE=.6,PARALLAXE_Y_POS_ICE=440,PARALLAXE_Y_POS_VM=540,MAX_NUM_PARALLAXE=3,FALL_LIMIT_Y=CANVAS_HEIGHT+100,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,SEA_NUMBER=2,POSITION_Y_SEA=490,NUMBER_OF_STARS=3,STARS_POSITION=[{x:700,y:216},{x:754,y:216},{x:809,
y:216}],SHOW_COLLISION_SHAPE=!1,SCALE_STAR_FACTOR=1.2,OFFSET_RECT_ARRIVAL={x:10,y:150},OFFSET_ARRIVAL_POS={x:0,y:5},GAME_STATE_HELP=0,GAME_STATE_PLAY=1,GAME_STATE_FINISH=2,GAME_STATE_GAMEOVER=3,COLLISION_PLATFORM=0,COLLISION_WALL=1,COLLISION_NOTHING=2,COLLISION_ARRIVAL=3,PREVIEW_COLLISION=4,DECREASE_FACTOR_VOL_GAME_COMPLETED=.95,DECREASE_FACTOR_VOL_LEVEL_COMPLETED=.85,OFFSET_HEIGHT_COLLISION_PLATFORM=-2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_BUT_NO_DOWN=
6,ON_BUT_YES_DOWN=7,ON_CONTROLLER_END=8,ON_CONTROLLER_REMOVE=9,ON_CONTROLLER_ROLL=10,EASE_CUBIC_OUT=1,WEIGHT_ARRIVAL=92,ON_VISIBLE_X=CANVAS_WIDTH+20,PLATFORM_SPEED,NUM_LEVEL_FOR_ADS,PERCENTAGE_STARS,ENABLE_FULLSCREEN;TEXT_GAMEOVER="GAME OVER";TEXT_COMMANDS="CONTROLS";TEXT_ALL_COMPLETE="ALL LEVEL COMPLETE";TEXT_SELECT_A_LEVEL="SELECT A LEVEL";TEXT_CREDITS_DEVELOPED="Developed by";TEXT_LINK1="www.codethislab.com";TEXT_SCORES="SCORES";TEXT_TOTAL_SCORE="TOTAL SCORE";TEXT_CONGRATULATIONS="CONGRATULATIONS !";
TEXT_PAUSE="PAUSE";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_SCORE="SCORE";TEXT_LEVEL_COMPLETED="LEVEL COMPLETED!!!";TEXT_GAME_COMPLETED="GAME COMPLETED";TEXT_FINAL_SCORE="FINAL SCORE";TEXT_HELP_INPUT="JUMP";TEXT_HELP_COIN="COLLECT";TEXT_HELP_SPIKE="AVOID";TEXT_RESET="ARE YOU SURE? ALL YOUR PREVIOUS SCORES WILL BE DELETED!";TEXT_LEVEL="LEVEL";TEXT_ERR_LS="YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";
TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var a,h,b,e,g,f,d;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();d=new createjs.Container;s_oStage.addChild(d)};this.unload=function(){d.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(f).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));d.addChild(l);l=s_oSpriteLibrary.getSprite("progress_bar");e=createBitmap(l);e.x=CANVAS_WIDTH/2-l.width/2;e.y=CANVAS_HEIGHT-200;d.addChild(e);a=l.width;h=l.height;g=new createjs.Shape;g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,1,h);d.addChild(g);e.mask=
g;b=new createjs.Text("","30px "+FONT_GAME,TEXT_COLOR);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-200;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";d.addChild(b);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;d.addChild(f)};this.refreshLoader=function(d){b.text=d+"%";g.graphics.clear();d=Math.floor(d*a/100);g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,d,h)};this._init()}
function CMain(a){var h,b=0,e=0,g=STATE_LOADING,f,d,l;this.initContainer=function(){var c=document.getElementById("canvas");s_oStage=new createjs.Stage(c);createjs.Touch.enable(s_oStage);s_oStage.preventSelection=!1;c.opacity=.5;s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(c){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;s_oTweenController=new CTweenController;d=new CPreloader;h=!0};this.soundLoaded=function(){b++;d.refreshLoader(Math.floor(b/e*100));if(b===e)this.onPreloadingComplete()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),
createjs.Sound.registerSound("./sounds/click.ogg","click"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/broken_stone.ogg","broken_stone"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/coin.ogg","coin"),createjs.Sound.registerSound("./sounds/game_completed.ogg","game_completed"),createjs.Sound.registerSound("./sounds/hero_falling.ogg","hero_falling"),createjs.Sound.registerSound("./sounds/hit_axe.ogg",
"hit_axe"),createjs.Sound.registerSound("./sounds/jump.ogg","jump"),createjs.Sound.registerSound("./sounds/level_completed.ogg","level_completed"),createjs.Sound.registerSound("./sounds/splash.ogg","splash"),createjs.Sound.registerSound("./sounds/hero_spike.ogg","hero_spike"),createjs.Sound.registerSound("./sounds/star.ogg","star")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.mp3",
"click"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/broken_stone.mp3","broken_stone"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/coin.mp3","coin"),createjs.Sound.registerSound("./sounds/game_completed.mp3","game_completed"),createjs.Sound.registerSound("./sounds/hero_falling.mp3","hero_falling"),createjs.Sound.registerSound("./sounds/hit_axe.mp3","hit_axe"),createjs.Sound.registerSound("./sounds/jump.mp3",
"jump"),createjs.Sound.registerSound("./sounds/level_completed.mp3","level_completed"),createjs.Sound.registerSound("./sounds/splash.mp3","splash"),createjs.Sound.registerSound("./sounds/hero_spike.mp3","hero_spike"),createjs.Sound.registerSound("./sounds/star.mp3","star")),e+=13)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");
s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_restart_big","./sprites/but_restart_big.png");s_oSpriteLibrary.addSprite("but_exit_big","./sprites/but_exit_big.png");s_oSpriteLibrary.addSprite("but_pause","./sprites/but_pause.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_level","./sprites/but_level.png");s_oSpriteLibrary.addSprite("but_yes",
"./sprites/but_yes.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_ice","./sprites/bg_ice.jpg");s_oSpriteLibrary.addSprite("bg_mountain","./sprites/bg_mountain.jpg");s_oSpriteLibrary.addSprite("bg_volcano","./sprites/bg_volcano.jpg");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_restart",
"./sprites/but_restart.png");s_oSpriteLibrary.addSprite("player","./sprites/player.png");s_oSpriteLibrary.addSprite("game_completed_panel","./sprites/game_completed_panel.png");s_oSpriteLibrary.addSprite("level_completed_panel","./sprites/level_completed_panel.png");s_oSpriteLibrary.addSprite("game_over_panel","./sprites/game_over_panel.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("logo","./sprites/logo.png");s_oSpriteLibrary.addSprite("sea","./sprites/sea.png");
s_oSpriteLibrary.addSprite("help_mouse","./sprites/help_mouse.png");s_oSpriteLibrary.addSprite("help_touch","./sprites/help_touch.png");s_oSpriteLibrary.addSprite("star","./sprites/star.png");s_oSpriteLibrary.addSprite("object_0","./sprites/object_0.png");s_oSpriteLibrary.addSprite("object_1","./sprites/object_1.png");s_oSpriteLibrary.addSprite("parallaxe_ice_0","./sprites/parallaxe_ice_0.png");s_oSpriteLibrary.addSprite("parallaxe_mountain_0","./sprites/parallaxe_mountain_0.png");s_oSpriteLibrary.addSprite("parallaxe_volcano_0",
"./sprites/parallaxe_volcano_0.png");s_oSpriteLibrary.addSprite("parallaxe_volcano_1","./sprites/parallaxe_volcano_1.png");s_oSpriteLibrary.addSprite("arrival_0","./sprites/arrival_0.png");s_oSpriteLibrary.addSprite("arrival_1","./sprites/arrival_1.png");s_oSpriteLibrary.addSprite("platform_ice_0","./sprites/platform_ice_0.png");s_oSpriteLibrary.addSprite("platform_ice_1","./sprites/platform_ice_1.png");s_oSpriteLibrary.addSprite("platform_mountain_0","./sprites/platform_mountain_0.png");s_oSpriteLibrary.addSprite("platform_mountain_1",
"./sprites/platform_mountain_1.png");s_oSpriteLibrary.addSprite("platform_volcano_0","./sprites/platform_volcano_0.png");s_oSpriteLibrary.addSprite("platform_volcano_1","./sprites/platform_volcano_1.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;d.refreshLoader(Math.floor(b/e*100));if(b===e)this.onPreloadingComplete()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=
function(){this._loadImages()};this.preloaderReady=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)this._initSounds(),s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.loadJSON();this._loadImages();h=!0};this.onLoadedJSON=function(c){s_aLevelDiagram=c};this.loadJSON=function(){jQuery.getJSON(URL_LEVELS_SETTINGS,this.onLoadedJSON)};this.onPreloadingComplete=function(){try{saveItem("ls_available","ok")}catch(c){s_bStorageAvailable=!1}d.unload();if(!1===DISABLE_SOUND_MOBILE||!1===
s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()};this.gotoMenu=function(){new CMenu;g=STATE_MENU};this.gotoGame=function(c){l=new CGame(f,c);g=STATE_GAME;$(s_oMain).trigger("start_session")};this.gotoLevelMenu=function(){new CLevelMenu(f);g=STATE_MENU};this.gotoHelp=function(){new CHelp;g=STATE_HELP};this.gotoCongratulations=function(c,a){new CCongratulations(c,a);g=STATE_MENU};this.stopUpdate=function(){h=!1;createjs.Ticker.paused=!0;$("#block_game").css("display",
"block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();h=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=function(c){if(!1!==h){var a=(new Date).getTime();s_iTimeElaps=a-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=a;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);g===STATE_GAME&&l.update();s_oStage.update(c)}};s_oMain=this;f=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iAdsLevel=1,s_iLevelReached=1,s_aScores,s_aPercentage,s_aLevelDiagram,s_oTweenController,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_bFullscreen=!1,s_bStorageAvailable=!0;
function CTextButton(a,h,b,e,g,f,d,l){var c,p,k,m;this._init=function(a,d,b,f,e,l,g){c=[];p=[];var h=createBitmap(b),n=Math.ceil(g/20),q=new createjs.Text(f,"bold "+g+"px "+e,"#000000");q.textAlign="center";q.textBaseline="alphabetic";var r=q.getBounds();q.x=b.width/2+n;q.y=Math.floor(b.height/2)+r.height/3+n;f=new createjs.Text(f,"bold "+g+"px "+e,l);f.textAlign="center";f.textBaseline="alphabetic";r=f.getBounds();f.x=b.width/2;f.y=Math.floor(b.height/2)+r.height/3;k=new createjs.Container;k.x=a;
k.y=d;k.regX=b.width/2;k.regY=b.height/2;k.addChild(h,q,f);s_bMobile||(k.cursor="pointer");m.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown");k.off("pressup");m.removeChild(k)};this.setVisible=function(c){k.visible=c};this._initListener=function(){oParent=this;k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,d,b){c[a]=d;p[a]=b};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("click",1,0);c[ON_MOUSE_UP]&&
c[ON_MOUSE_UP].call(p[ON_MOUSE_UP])};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN])};this.setPosition=function(c,a){k.x=c;k.y=a};this.setX=function(c){k.x=c};this.setY=function(c){k.y=c};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};m=l;this._init(a,h,b,e,g,f,d);return this}
function CToggle(a,h,b,e,g){var f,d,l,c,p;this._init=function(a,b,e,g){d=[];l=[];var k=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{state_true:[0],state_false:[1]}});f=g;c=createSprite(k,"state_"+f,e.width/2/2,e.height/2,e.width/2,e.height);c.x=a;c.y=b;c.stop();s_bMobile||(c.cursor="pointer");p.addChild(c);this._initListener()};this.unload=function(){c.off("mousedown",this.buttonDown);c.off("pressup",this.buttonRelease);
p.removeChild(c)};this._initListener=function(){c.on("mousedown",this.buttonDown);c.on("pressup",this.buttonRelease)};this.addEventListener=function(c,a,b){d[c]=a;l[c]=b};this.setCursorType=function(a){c.cursor=a};this.setActive=function(a){f=a;c.gotoAndStop("state_"+f)};this.buttonRelease=function(){c.scaleX=1;c.scaleY=1;playSound("click",1,0);f=!f;c.gotoAndStop("state_"+f);d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(l[ON_MOUSE_UP],f)};this.buttonDown=function(){c.scaleX=.9;c.scaleY=.9;d[ON_MOUSE_DOWN]&&
d[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.setPosition=function(a,d){c.x=a;c.y=d};p=g;this._init(a,h,b,e)}
function CGfxButton(a,h,b,e){var g,f,d,l,c,p,k,m=!1,n;this._init=function(a,b,e){g=[];f=[];d=createBitmap(e);d.x=a;d.y=b;p=c=1;d.regX=e.width/2;d.regY=e.height/2;s_bMobile||(d.cursor="pointer");n.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);n.removeChild(d)};this.setVisible=function(c){d.visible=c};this.setCursorType=function(c){d.cursor=c};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",
this.buttonRelease)};this.addEventListener=function(c,a,d){g[c]=a;f[c]=d};this.addEventListenerWithParams=function(c,a,d,b){g[c]=a;f[c]=d;l=b};this.buttonRelease=function(){m||(d.scaleX=0<c?1:-1,d.scaleY=1,playSound("click",1,0),g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(f[ON_MOUSE_UP],l))};this.buttonDown=function(){m||(d.scaleX=0<c?.9:-.9,d.scaleY=.9,g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],l))};this.rotation=function(c){d.rotation=c};this.getButton=function(){return d};this.setPosition=
function(c,a){d.x=c;d.y=a};this.setX=function(c){d.x=c};this.setY=function(c){d.y=c};this.getButtonImage=function(){return d};this.block=function(a){m=a;d.scaleX=c;d.scaleY=p};this.setScaleX=function(a){c=d.scaleX=a};this.getX=function(){return d.x};this.getY=function(){return d.y};this.pulseAnimation=function(){createjs.Tween.get(d).to({scaleX:.9*c,scaleY:.9*p},850,createjs.Ease.quadOut).to({scaleX:c,scaleY:p},650,createjs.Ease.quadIn).call(function(){k.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(d).to({rotation:5},
75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){k.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(d)};n=e;this._init(a,h,b);k=this;return this}
function CMenu(){var a,h,b,e,g,f,d,l,c,p,k=null,m=null,n,r,t,x,u,q,w,v=null,y;this._init=function(){r=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(r);var v=s_oSpriteLibrary.getSprite("but_play");d=CANVAS_WIDTH/2;l=CANVAS_HEIGHT-90;t=new CGfxButton(d,l,v,s_oStage);t.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);null!==getItem("olaf_levelreached")?(s_iLevelReached=getItem("olaf_levelreached"),s_aScores=JSON.parse(getItem("olaf_scores")),s_aPercentage=JSON.parse(getItem("olaf_percentage")),
d=CANVAS_WIDTH/2-200,l=CANVAS_HEIGHT-90,t.setPosition(d,l),g=CANVAS_WIDTH/2+200,f=CANVAS_HEIGHT-90,v=s_oSpriteLibrary.getSprite("but_continue"),u=new CGfxButton(g,f,v,s_oStage),u.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this),u.pulseAnimation()):(t.pulseAnimation(),this.resetArrays());if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)v=s_oSpriteLibrary.getSprite("audio_icon"),c=CANVAS_WIDTH-v.height/2-10,p=v.height/2+10,y=new CToggle(c,p,v,s_bAudioActive,s_oStage),y.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);v=s_oSpriteLibrary.getSprite("but_info");b=v.width/2+10;e=v.height/2+10;x=new CGfxButton(b,e,v,s_oStage);x.addEventListener(ON_MOUSE_UP,this._onButInfoRelease,this);var v=window.document,z=v.documentElement;k=z.requestFullscreen||z.mozRequestFullScreen||z.webkitRequestFullScreen||z.msRequestFullscreen;m=v.exitFullscreen||v.mozCancelFullScreen||v.webkitExitFullscreen||v.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(k=!1);k&&!1===inIframe()&&(v=s_oSpriteLibrary.getSprite("but_fullscreen"),
a=b+v.width/2+10,h=v.height/2+10,n=new CToggle(a,h,v,s_bFullscreen,s_oStage),n.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));w=new createjs.Shape;w.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q=new CLogo(.5*CANVAS_WIDTH,-200);s_oStage.addChild(w);createjs.Tween.get(w).to({alpha:0},800).call(function(){w.visible=!1});q.playAnimation();s_bStorageAvailable||new CMsgBox(TEXT_ERR_LS,s_oStage);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(m,
q){t.setPosition(d,l-q);u&&u.setPosition(g,f-q);x.setPosition(b+m,e+q);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||y.setPosition(c-m,q+p);k&&!1===inIframe()&&n.setPosition(a+m,h+q)};this.unload=function(){t.unload();t=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)y.unload(),y=null;k&&!1===inIframe()&&n.unload();s_oStage.removeAllChildren();createjs.Tween.removeAllTweens();s_oMenu=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=
function(){s_bFullscreen?(m.call(window.document),s_bFullscreen=!1):(k.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};this._onButInfoRelease=function(){new CCreditsPanel};this._onButNo=function(){v.unload();v=null};this._onButYes=function(){clearAllItem();this.unload();s_iLevelReached=1;this.resetArrays();s_oMain.gotoLevelMenu()};this._onButContinueRelease=function(){this.unload();playSound("click",1,0);s_oMain.gotoLevelMenu()};this.resetArrays=function(){s_aScores=[];s_aPercentage=
[];for(var c=0;c<s_aLevelDiagram.length;c++)s_aScores[c]=0,s_aPercentage[c]=0};this._onButPlayRelease=function(){null===getItem("olaf_levelreached")?(this.unload(),playSound("click",1,0),s_oMain.gotoLevelMenu()):null===v&&(v=new CConfirmPanel(TEXT_RESET,CONFIRMATION_RESET),v.addEventListener(ON_BUT_NO_DOWN,this._onButNo,this),v.addEventListener(ON_BUT_YES_DOWN,this._onButYes,this))};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a,h){var b,e,g,f,d,l,c,p,k,m=null,n,r,t,x,u=null,q,w,v,y=!1,A=!1;this._init=function(){b=!1;c=p=g=f=e=0;d=h;l=GAME_STATE_HELP;for(var a=0;a<d;a++)e+=s_aScores[a];void 0===e&&(e=0);f=e;this.createLevel();a=s_oSpriteLibrary.getSprite("player");this._createPlayer(a,s_aLevelDiagram[d].playerX,s_aLevelDiagram[d].playerY,s_oStage);this.createSea();k=new CInterface;k.refreshScore(f);k.refreshLevelCounter(d+1);l=GAME_STATE_HELP;setVolume(s_oSoundTrack,.35)};this.createParallaxeObject=function(){x=
new CParallaxObject(0,0,s_oStage);var c=s_aLevelDiagram[d].material,a=0;if("ice"===c)a=PARALLAXE_Y_POS_ICE;else if("volcano"===c||"mountain"===c)a=PARALLAXE_Y_POS_VM;for(var b=0;b<MAX_NUM_PARALLAXE;b++){var f=Math.floor(Math.random()*CANVAS_WIDTH),e=0;"volcano"===c&&(e=Math.round(1*Math.random()));x.addObject(f,a,c,e)}x.setSpeed(PARALLAX_SPEED)};this._createPlayer=function(c,a,d,b){n=new CCharacter(a,d,c,b);n.stopAnimation()};this.createLevel=function(){var c=s_aLevelDiagram[d].platform,a=c.length,
b=c[0].length,f=s_aLevelDiagram[d].material;m?v!==f&&(m.image=s_oSpriteLibrary.getSprite("bg_"+f)):(m=createBitmap(s_oSpriteLibrary.getSprite("bg_"+f)),m.on("mousedown",this._onMouseDown),m.on("pressup",this._onPressUp),v=f,s_oStage.addChild(m));this.createParallaxeObject();r=new CLevelPlatforms(0,0,s_oStage);this.createLevelObject();for(var e=FIRST_PLATFORM_X,l,p=0,k=0;k<b;k++){l=PLATFORM_Y_START;for(var g=0;g<a;g++)l+=50,-1!==c[g][k]&&(r.addPlatform(e,l,p,f,c[g][k]),p++);e+=50}r.createArrival(s_aLevelDiagram[d].last_platform)};
this.createLevelObject=function(){var a=s_aLevelDiagram[d].objects;t=new CLevelObjects(0,0,s_oStage);for(var b=0,f=0;f<a.length;f++){var e=a[f].x+100,l=a[f].y,p=a[f].gid;0===p&&c++;t.addObject(e,l,b,p);b++}};this.createSea=function(){"ice"===s_aLevelDiagram[d].material&&(u=new CSea(0,0,s_oStage),u.setSpeed(PLATFORM_SPEED))};this._onMouseDown=function(){b&&!1!==n.getCollisionWithPlatform()&&l===GAME_STATE_PLAY&&(n.moveUp(),n.stayMouseDown(!0),n.collisionWithPlatform(!1),n.changeState("jump"),playSound("jump",
1,0))};this.win=function(){var c=f;f=e;s_iLevelReached<d+2&&(s_iLevelReached=d+2);g>s_aScores[d]&&(s_aScores[d]=g);var a=this.calculatePercentCoins();a>s_aPercentage[d]&&(s_aPercentage[d]=a);saveItem("olaf_levelreached",s_iLevelReached);saveItem("olaf_scores",JSON.stringify(s_aScores));saveItem("olaf_percentage",JSON.stringify(s_aPercentage));d>=s_aLevelDiagram.length-1?(k.createCongratulations(f,a,g,c),q=playSound("game_completed",1,-1),w=DECREASE_FACTOR_VOL_GAME_COMPLETED):(k.createWinPanel(f,a,
g,c,d),q=playSound("level_completed",1,-1),w=DECREASE_FACTOR_VOL_LEVEL_COMPLETED);setVolume(s_oSoundTrack,0);$(s_oMain).trigger("end_level",d);e=f};this.calculatePercentCoins=function(){return Math.floor(p/c*100)};this._onPressUp=function(){b&&l===GAME_STATE_PLAY&&n.stayMouseDown(!1)};this.unload=function(){b=!1;k.unload();n.unload();q&&(q.destroy(),q=null);s_oStage.removeAllChildren();createjs.Tween.removeAllTweens()};this.onExit=function(){this.unload();$(s_oMain).trigger("show_interlevel_ad");
$(s_oMain).trigger("end_session");setVolume(s_oSoundTrack,1);s_oMain.gotoMenu()};this._onExitHelp=function(){$(s_oMain).trigger("start_level",d);b=!0;n.playAnimation();l=GAME_STATE_PLAY};this.unpause=function(c){b=c;!0===c?n.playAnimation():n.stopAnimation()};this.changeState=function(c){l=c};this.nextLevel=function(){d++;q&&(q.destroy(),q=null);setVolume(s_oSoundTrack,.35);"ice"===v&&v!==s_aLevelDiagram[d].material&&u&&(u.unload(),u=null);$(s_oMain).trigger("start_level",d);k.refreshLevelCounter(d+
1);this.restartLevel()};this._onEnd=function(){this.unload();$(s_oMain).trigger("end_session");setVolume(s_oSoundTrack,1);s_oMain.gotoCongratulations(_aResults,e)};this.gameOver=function(){l=GAME_STATE_FINISH;b=!1;k.createLosePanel(e)};this.addScore=function(c){e+=c;g+=c;k.refreshScore(e)};this.restartLevel=function(){n.removeTweens();this.unloadLevel();e=f;p=c=g=0;k.refreshScore(e);n.setPosition(s_aLevelDiagram[d].playerX-10,s_aLevelDiagram[d].playerY);n.playerIDPlatform(0);n.changeState("run");
n.resetJump();this.createLevel();r.setSpeed(PLATFORM_SPEED);x.setSpeed(PARALLAX_SPEED);u&&u.setSpeed(PLATFORM_SPEED);t.setSpeed(PLATFORM_SPEED);q&&(q.destroy(),q=null);setVolume(s_oSoundTrack,.35);b=!0};this.unloadLevel=function(){r.unload();r=null;x.unload();x=null;t.unload();t=null};this.platformFinished=function(){l=GAME_STATE_FINISH;r.setSpeed(0);u&&u.setSpeed(-.5);y=r.getArrival().getY()-n.getY()>=TOLLERANCE_Y_FOR_ANIMATION?!0:!1;n.animationArrival(r.getArrival(),r.getPlatformByID(r.getArrival().getIDPlatform()),
y)};this.collisionPlatform=function(c){!1===c.collide&&!1===n.getCollisionWithPlatform()&&(n.collisionWithPlatform(!0),n.setPosition(n.getX(),c.y+OFFSET_HEIGHT_PLATFORM_CHRACTER),l===GAME_STATE_PLAY&&n.changeState("run"))};this.collisionWall=function(){r.setSpeed(0);x.setSpeed(0);u&&u.setSpeed(-.5);t.setSpeed(0);n.changeState("fall");n.collisionWithPlatform(!1)};this.fallLimit=function(){null!==u?n.getY()>POSITION_Y_SEA+50&&(n.playSeaAnimation(),y=!0,playSound("splash",1,0),l=GAME_STATE_GAMEOVER,
u.setSpeed(-.5)):n.getY()>FALL_LIMIT_Y&&(this.gameOver(),playSound("hero_falling",1,0),l=GAME_STATE_GAMEOVER)};this.spikeCollision=function(){u&&u.setSpeed(-.5);this.changeState(GAME_STATE_GAMEOVER);n.playDeadSpikeAnimation();playSound("hero_spike",1,0)};this.decreaseVolumeSoundLevelComplete=function(c){A=c};this.unloadObject=function(c){t.unloadObject(c)};this.addObtainCoin=function(){p++};this.update=function(){switch(l){case GAME_STATE_PLAY:if(b){var c={rect:n.getRectangle(),id:n.getIDPlatform()},
a=r.update(c);t.update(c);n.playerIDPlatform(a.id);a.collision===COLLISION_PLATFORM?this.collisionPlatform(a):a.collision===COLLISION_WALL?this.collisionWall():a.collision===COLLISION_NOTHING&&(n.collisionWithPlatform(!1),r.getPlatformByID(a.id).setCollideYet(!1));x.update();u&&u.update();this.fallLimit();n.update()}break;case GAME_STATE_FINISH:b&&!y&&!1===n.getCollisionWithPlatform()&&(c={rect:n.getRectangle(),id:n.getIDPlatform()},a=r.update(c),n.playerIDPlatform(a.id),a.collision===COLLISION_PLATFORM&&
(this.collisionPlatform(a),n.changeState("lands")),n.update());u&&u.update();A&&q&&(q.volume*=w);break;case GAME_STATE_GAMEOVER:u&&u.update()}};s_oGame=this;PLATFORM_SPEED=a.platform_velocity;HERO_DOWN_ACCELLERATION=a.hero_down_speed;DECELLERATION_MOUSE_DOWN=a.decelleration_mouse_down;DECELLERATION_NORMAL=a.decelleration_normal;NUM_LEVEL_FOR_ADS=a.num_levels_for_ads;JUMP_MULTIPLY=a.jump_multiplier;PARALLAX_SPEED=a.parallax_speed;COIN_SCORE=a.coin_score;PERCENTAGE_STARS=a.percentage_stars;ENABLE_FULLSCREEN=
a.fullscreen;this._init()}var s_oGame;
function CInterface(){var a,h,b,e,g,f,d,l,c,p,k,m=null,n=null,r,t,x,u,q=null,w,v,y,A,z,B,C,D;this._init=function(){var k=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-k.height/2-10;e=k.height/2+10;t=new CGfxButton(b,e,k,s_oStage);t.addEventListener(ON_MOUSE_UP,this._onExit,this);k=s_oSpriteLibrary.getSprite("but_pause");a=b-k.height-10;h=e;x=new CGfxButton(a,h,k,s_oStage);x.addEventListener(ON_MOUSE_UP,this._onPause,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k=s_oSpriteLibrary.getSprite("audio_icon"),
c=a-k.height-10,p=e,q=new CToggle(c,p,k,s_bAudioActive,s_oStage),q.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);var k=window.document,w=k.documentElement;m=w.requestFullscreen||w.mozRequestFullScreen||w.webkitRequestFullScreen||w.msRequestFullscreen;n=k.exitFullscreen||k.mozCancelFullScreen||k.webkitExitFullscreen||k.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(m=!1);m&&!1===inIframe()&&(k=s_oSpriteLibrary.getSprite("but_fullscreen"),null===q?(g=a-k.height-10,f=e):(g=c-k.width/2-10,f=k.height/
2+10),trace("_pStartPosFullscreen: "+g+","+f),r=new CToggle(g,f,k,s_bFullscreen,s_oStage),r.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));d=CANVAS_WIDTH/2-75;l=53;v=new createjs.Container;v.x=d;v.y=l;A=new createjs.Text(TEXT_SCORE+" 0","normal 36px "+FONT_GAME,"#000000");A.textAlign="left";A.textBaseline="alphabetic";A.x=0;A.y=0;A.outline=3;v.addChild(A);y=new createjs.Text(TEXT_SCORE+" 0","normal 36px "+FONT_GAME,TEXT_COLOR);y.textAlign="left";y.textBaseline="alphabetic";y.x=0;y.y=
0;v.addChild(y);this.createLevelCounter();D=new CAreYouSurePanel(s_oStage);s_oStage.addChild(v);u=new CHelpPanel(0,0,s_oSpriteLibrary.getSprite("msg_box"));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(d,n){t.setPosition(b-d,n+e);x.setPosition(a-d,n+h);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||q.setPosition(c-d,n+p);m&&!1===inIframe()&&r.setPosition(g-d,f+n);v.y=l+n;z.x=k.x+d;z.y=k.y+n};this.createLevelCounter=function(){k={x:10,y:53};z=new createjs.Container;z.x=k.x;
z.y=k.y;C=new createjs.Text(TEXT_LEVEL+" 0","normal 36px "+FONT_GAME,"#000000");C.textAlign="left";C.textBaseline="alphabetic";C.x=0;C.y=0;C.outline=3;z.addChild(C);B=new createjs.Text(TEXT_LEVEL+" 0","normal 36px "+FONT_GAME,TEXT_COLOR);B.textAlign="left";B.textBaseline="alphabetic";B.x=0;B.y=0;z.addChild(B);s_oStage.addChild(z)};this.unload=function(){t.unload();t=null;x.unload();x=null;D&&D.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q.unload(),q=null;m&&!1===inIframe()&&r.unload();s_oInterface=
null};this.createLosePanel=function(c){new CLosePanel(s_oSpriteLibrary.getSprite("game_over_panel"),c)};this.createWinPanel=function(c,a,d,b,f){new CWinPanel(s_oSpriteLibrary.getSprite("level_completed_panel"),c,a,d,b,f)};this.createCongratulations=function(c,a,d,b){new CCongratulations(s_oSpriteLibrary.getSprite("game_completed_panel"),c,a,d,b)};this.unloadHelpPanel=function(){u&&(u.unload(),u=null)};this.createPauseInterface=function(){w=new CPause};this.unloadPause=function(){w.unload();w=null};
this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){D.show()};this.refreshScore=function(c){y.text=TEXT_SCORE+" "+c;A.text=TEXT_SCORE+" "+c};this.refreshLevelCounter=function(c){B.text=TEXT_LEVEL+": "+c;C.text=B.text};this._onPause=function(){s_oGame.unpause(!1);this.createPauseInterface();createjs.Ticker.paused=!0};this._onFullscreenRelease=function(){s_bFullscreen?(n.call(window.document),s_bFullscreen=!1):(m.call(window.document.documentElement),
s_bFullscreen=!0);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(a,h,b){var e,g,f,d,l=!1;this._init=function(c,a,d){e=createBitmap(d);e.x=.5*CANVAS_WIDTH;e.y=.5*CANVAS_HEIGHT;e.regX=.5*d.width;e.regY=.5*d.height;g=new createjs.Container;g.x=c;g.y=a;f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=.5;g.addChild(f);g.addChild(e);s_oStage.addChild(g);this.page1();g.on("pressup",function(){s_oHelpPanel._onExitHelp()},null,!0);s_bMobile||(g.cursor="pointer")};this.page1=function(){var c;c=new createjs.Text(TEXT_HELP_INPUT,
"30px "+FONT_GAME,"#000000");c.textAlign="center";c.textBaseline="middle";c.x=.5*CANVAS_WIDTH;c.y=.5*CANVAS_HEIGHT-85;c.outline=3;g.addChild(c);var a;a=new createjs.Text(TEXT_HELP_INPUT,"30px "+FONT_GAME,TEXT_COLOR);a.textAlign="center";a.textBaseline="middle";a.lineWidth=600;a.x=c.x;a.y=c.y;g.addChild(a);var b=s_oSpriteLibrary.getSprite("player");(new CCharacter(a.x-90,c.y+40,b,g)).changeState("start_jump_help");a=s_bMobile?s_oSpriteLibrary.getSprite("help_touch"):s_oSpriteLibrary.getSprite("help_mouse");
b=createBitmap(a);b.x=c.x+90;b.y=c.y;b.regX=.5*a.width;b.regY=.5*a.height;g.addChild(b);c=new createjs.Text(TEXT_HELP_COIN,"30px "+FONT_GAME,"#000000");c.textAlign="center";c.textBaseline="middle";c.lineWidth=400;c.x=.5*CANVAS_WIDTH;c.y=.5*CANVAS_HEIGHT;c.outline=3;g.addChild(c);a=new createjs.Text(c.text,"30px "+FONT_GAME,TEXT_COLOR);a.textAlign="center";a.textBaseline="middle";a.lineWidth=c.lineWidth;a.x=c.x;a.y=c.y;g.addChild(a);a=s_oSpriteLibrary.getSprite("object_0");b=new createjs.SpriteSheet({images:[a],
frames:{width:a.width/5,height:a.height/4,regX:a.width/2/5,regY:a.height/2/4},animations:{normal:[0,19,"normal"]}});a=createSprite(b,"run",a.width/2/5,a.height/2/4,a.width/5,a.height/4);a.x=.5*CANVAS_WIDTH-100;a.y=c.y;g.addChild(a);c=new createjs.Text(TEXT_HELP_SPIKE,"30px "+FONT_GAME,"#000000");c.textAlign="center";c.textBaseline="middle";c.lineWidth=600;c.x=.5*CANVAS_WIDTH;c.y=.5*CANVAS_HEIGHT+85;c.outline=3;g.addChild(c);a=new createjs.Text(c.text,"30px "+FONT_GAME,TEXT_COLOR);a.textAlign="center";
a.textBaseline="middle";a.lineWidth=600;a.x=c.x;a.y=c.y;g.addChild(a);b=s_oSpriteLibrary.getSprite("object_1");a=createBitmap(b);a.x=.5*CANVAS_WIDTH-100;a.y=c.y;a.regX=b.width/2;a.regY=b.height/2;g.addChild(a);createjs.Tween.get(g).to({alpha:1},300,createjs.Ease.cubicOut);c=s_oSpriteLibrary.getSprite("but_continue");d=new CGfxButton(.5*CANVAS_WIDTH+210,.5*CANVAS_HEIGHT+80,c,g);d.addEventListener(ON_MOUSE_UP,this._onExitHelp,this);d.pulseAnimation();s_oStage.addChild(g)};this.unload=function(){s_oStage.removeChild(g);
s_oHelpPanel=null;g.off("click",function(){});d.unload();d=null};this._onExitHelp=function(){l||(l=!0,playSound("click",1,0),createjs.Tween.get(g).to({alpha:0},500).call(function(){s_oHelpPanel.unload();s_oGame._onExitHelp()}))};s_oHelpPanel=this;this._init(a,h,b)}var s_oHelpPanel=null;
function CLosePanel(a,h){var b,e,g,f,d,l,c;this._init=function(a,k){b=new createjs.Container;e=new createjs.Container;c=a.width;e.y=-c;g=createBitmap(a);g.x=.5*CANVAS_WIDTH;g.y=.5*CANVAS_HEIGHT;g.regX=.5*a.width;g.regY=.5*a.height;e.addChild(g);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;f.on("click",function(){});b.addChild(f);var h,p;p=new createjs.Text(TEXT_GAMEOVER,"44px "+FONT_GAME,"#000000");p.textAlign="center";p.textBaseline="middle";
p.x=.5*CANVAS_WIDTH;p.y=176;p.outline=4;e.addChild(p);h=new createjs.Text(TEXT_GAMEOVER,"44px "+FONT_GAME,TEXT_COLOR);h.textAlign="center";h.textBaseline="middle";h.x=.5*CANVAS_WIDTH;h.y=p.y;e.addChild(h);p=new createjs.Text(TEXT_SCORE+": "+k,"34px "+FONT_GAME,"#000000");p.textAlign="center";p.textBaseline="middle";p.x=.5*CANVAS_WIDTH;p.y=241;p.outline=4;e.addChild(p);h=new createjs.Text(TEXT_SCORE+": "+k,"34px "+FONT_GAME,TEXT_COLOR);h.textAlign="center";h.textBaseline="middle";h.x=.5*CANVAS_WIDTH;
h.y=p.y;e.addChild(h);b.addChild(e);b.x=0;b.y=0;s_oStage.addChild(b);h=s_oSpriteLibrary.getSprite("but_restart_big");p=s_oSpriteLibrary.getSprite("but_home");d=new CGfxButton(510,350,p,e);d.addEventListener(ON_MOUSE_UP,this._onExit,this);l=new CGfxButton(850,350,h,e);l.addEventListener(ON_MOUSE_UP,this._onRestart,this);l.pulseAnimation();createjs.Tween.get(f).to({alpha:.5},750,createjs.Ease.cubicOut);createjs.Tween.get(e).to({y:0},1500,createjs.Ease.bounceOut).call(function(){s_iAdsLevel===NUM_LEVEL_FOR_ADS?
($(s_oMain).trigger("show_interlevel_ad"),s_iAdsLevel=1):s_iAdsLevel++});$(s_oMain).trigger("save_score",k);$(s_oMain).trigger("share_event",k)};this.unload=function(){var a=this;createjs.Tween.get(e).to({y:CANVAS_HEIGHT+c},1500,createjs.Ease.cubicIn).call(function(){a.unloadButton()})};this.unloadButton=function(){d.unload();d=null;l.unload();l=null};this.blockAllBut=function(){l.block(!0);d.block(!0)};this._onRestart=function(){this.blockAllBut();this.unload();createjs.Tween.get(f).to({alpha:1},
1E3,createjs.Ease.cubicIn).call(function(){s_oGame.restartLevel();s_oGame.changeState(GAME_STATE_PLAY);s_oStage.removeChild(b)})};this._onExit=function(){this.unload();this.blockAllBut();s_oGame.onExit()};this._init(a,h);return this}
function CWinPanel(a,h,b,e,g,f){var d,l,c,p,k,m,n,r,t,x,u;this._init=function(a,b,f,e,h,g){u=[];d=new createjs.Container;l=new createjs.Container;x=a.width;l.y=-x;c=createBitmap(a);c.x=.5*CANVAS_WIDTH;c.y=.5*CANVAS_HEIGHT;c.regX=.5*a.width;c.regY=.5*a.height;l.addChild(c);p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);p.alpha=0;p.on("click",function(){});d.addChild(p);var q;q=new createjs.Text(TEXT_LEVEL_COMPLETED,"40px "+FONT_GAME,"#000000");q.textAlign=
"center";q.textBaseline="middle";q.x=.5*CANVAS_WIDTH+65;q.y=166;q.outline=4;l.addChild(q);a=new createjs.Text(TEXT_LEVEL_COMPLETED,"40px "+FONT_GAME,TEXT_COLOR);a.textAlign="center";a.textBaseline="middle";a.x=q.x;a.y=q.y;l.addChild(a);q=new createjs.Text(TEXT_SCORE+":","32px "+FONT_GAME,"#000000");q.textAlign="center";q.textBaseline="middle";q.x=717;q.y=270;q.outline=4;l.addChild(q);a=new createjs.Text(TEXT_SCORE+":","32px "+FONT_GAME,TEXT_COLOR);a.textAlign="center";a.textBaseline="middle";a.x=
q.x;a.y=q.y;l.addChild(a);var t;t=new createjs.Text(h,"32px "+FONT_GAME,"#000000");t.textAlign="left";t.textBaseline="middle";t.x=q.x+54;t.y=270;t.outline=4;l.addChild(t);var r;r=new createjs.Text(h,"32px "+FONT_GAME,TEXT_COLOR);r.textAlign="left";r.textBaseline="middle";r.x=t.x;r.y=t.y;l.addChild(r);var w;w=new createjs.Text("0","32px "+FONT_GAME,"#000000");w.textAlign="center";w.textBaseline="middle";w.x=840;w.y=242;w.outline=4;var v;v=new createjs.Text("0","32px "+FONT_GAME,"#000000");v.textAlign=
"center";v.textBaseline="middle";v.x=840;v.y=242;h=s_oSpriteLibrary.getSprite("star");for(a=0;a<NUMBER_OF_STARS;a++)u[a]=new CStar(STARS_POSITION[a].x,STARS_POSITION[a].y,h,!1,l);d.addChild(l);d.x=0;d.y=0;s_oStage.addChild(d);h=s_oSpriteLibrary.getSprite("but_restart_big");a=s_oSpriteLibrary.getSprite("but_home");q=s_oSpriteLibrary.getSprite("but_continue");k=new CGfxButton(635,350,a,l);k.addEventListener(ON_MOUSE_UP,this._onExit,this);m=new CGfxButton(759,350,h,l);m.addEventListenerWithParams(ON_MOUSE_UP,
this._onRestart,this,g);n=new CGfxButton(882,350,q,l);n.addEventListener(ON_MOUSE_UP,this._onContinue,this);n.pulseAnimation();createjs.Tween.get(p).to({alpha:.5},750,createjs.Ease.cubicOut);var y=this;createjs.Tween.get(l).to({y:0},1500,createjs.Ease.bounceOut).call(function(){s_iAdsLevel===NUM_LEVEL_FOR_ADS?($(s_oMain).trigger("show_interlevel_ad"),s_iAdsLevel=1):s_iAdsLevel++;y.checkPoint(r,t,e,y);y.checkStars(v,w,f,y)});$(s_oMain).trigger("save_score",b);$(s_oMain).trigger("share_event",b)};this.unload=
function(){this.blockAllBut();var a=this;createjs.Tween.get(l).to({y:CANVAS_HEIGHT+x},1E3,createjs.Ease.cubicIn).call(function(){a.unloadButton()});r.unload();t.unload()};this.blockAllBut=function(){m.block(!0);k.block(!0);n.block(!0)};this.unloadButton=function(){k.unload();k=null;m.unload();m=null;n.unload();n=null};this._onRestart=function(a){this.unload();createjs.Tween.get(p).to({alpha:1},1E3,createjs.Ease.cubicIn).call(function(){s_oGame.restartLevel();s_oGame.changeState(GAME_STATE_PLAY);s_oStage.removeChild(d)});
$(s_oMain).trigger("restart_level",a)};this.checkStars=function(a,c,d,b){t=new CRollingTextController(a,c,d,4E3,EASE_CUBIC_OUT);t.addEventListener(ON_CONTROLLER_END,b._onFinishRollingStars);t.addEventListener(ON_CONTROLLER_REMOVE,b._onFinishRollingStars);t.addRollingListener(b._onRollingText,b,PERCENTAGE_STARS)};this.checkPoint=function(a,c,d,b){r=new CRollingTextController(a,c,d,4E3,EASE_CUBIC_OUT);r.addEventListener(ON_CONTROLLER_END,b._onFinishRollingPoint);r.addEventListener(ON_CONTROLLER_REMOVE,
b._onFinishRollingPoint);r.addRollingListener(b._onRollingTextScore,b,PERCENTAGE_STARS)};this._onFinishRollingPoint=function(){r.unload()};this._onFinishRollingStars=function(){t.unload()};this._onContinue=function(){this.unload();s_oGame.decreaseVolumeSoundLevelComplete(!0);createjs.Tween.get(p).to({alpha:1},750,createjs.Ease.cubicIn).call(function(){s_oGame.nextLevel();s_oGame.changeState(GAME_STATE_PLAY);s_oStage.removeChild(d);s_oGame.decreaseVolumeSoundLevelComplete(!1)})};this._onRollingTextScore=
function(){};this._onRollingText=function(a){u[a].setActive(!0);u[a].pulseAnimation(500,SCALE_STAR_FACTOR);playSound("star",1,0)};this._onExit=function(){this.unload();s_oGame.onExit()};this._init(a,h,b,e,g,f);return this}
function CCharacter(a,h,b,e){var g,f,d,l,c,p,k,m=null,n,r,t=!1,x,u,q,w=!1,v=!1;this._init=function(a,b,e,h){p=h;h=new createjs.SpriteSheet({images:[e],frames:{width:e.width/10,height:e.height/6,regX:e.width/2/10,regY:e.height/6},animations:{run:[0,15,"run",1],jump:[16,19,"jump_stay"],lands_run:[20,23,"run"],lands:[20,26,"idle"],shot:[28,40,"shot_remain"],dance:[41,53,"dance"],fall:[54,58,"fall_stay"],ice:[59],idle:[26],jump_stay:[19],fall_stay:[58],shot_remain:[40],start_jump:{frames:[25,24,23,22,
21,20,19,18],next:"jump"},start_jump_help:{frames:[25,24,23,22,21,20,19],next:"jump_help",speed:.5},jump_help:[19,19,"lands_help",.1],lands_help:[20,26,"start_jump_help",.5]}});c=createSprite(h,"run",e.width/2/10,e.height/6,e.width/10,e.height/6);c.x=a;c.y=b;n=HERO_DOWN_ACCELLERATION;u=e.width/10;q=e.height/6;g=a-u+OFFSET_PLAYER_COL_POINT.x;f=b-q+OFFSET_PLAYER_COL_POINT.y;d=u+OFFSET_PLAYER_COL_DIMENSION.x;l=q+OFFSET_PLAYER_COL_DIMENSION.y;k=new createjs.Rectangle(g,f,d,l);SHOW_COLLISION_SHAPE&&(m=
new createjs.Shape,m.graphics.beginFill("#00ff00").drawRect(k.x,k.y,k.width,k.height),m.alpha=.5,p.addChild(m));x=r=0;p.addChild(c)};this.getX=function(){return c.x};this.getY=function(){return c.y};this.onPlatform=function(a){v=a};this.getOnPlatform=function(){return v};this.setPosition=function(a,b){null!==a&&(c.x=a);null!==b&&(c.y=b);this.rectMovement()};this.rotate=function(a){c.scaleX=a};this.setVisible=function(a){c.visible=a};this.changeState=function(a){c.gotoAndPlay(a)};this.stopAnimation=
function(){c.stop()};this.playAnimation=function(){c.play()};this._onFinishAnimation=function(){c.on("animationend",function(){})};this.collisionWithPlatform=function(a){!0===w&&c.gotoAndPlay("jump");w=a};this.getCollisionWithPlatform=function(){return w};this.getRectangle=function(){return k};this.moveUp=function(){r=-HERO_DOWN_ACCELLERATION*JUMP_MULTIPLY;n=-HERO_DOWN_ACCELLERATION};this.stayMouseDown=function(a){t=a};this.unload=function(){p.removeChild(c);s_oCharacter=null};this.playerIDPlatform=
function(a){x=a};this.getIDPlatform=function(){return x};this.resetJump=function(){n=HERO_DOWN_ACCELLERATION};this.rectMovement=function(){g=c.x-u+OFFSET_PLAYER_COL_POINT.x;f=c.y-q+OFFSET_PLAYER_COL_POINT.y;d=u+OFFSET_PLAYER_COL_DIMENSION.x;l=q+OFFSET_PLAYER_COL_DIMENSION.y;k.setValues(g,f,d,l);SHOW_COLLISION_SHAPE&&(m&&(p.removeChild(m),m=null),m=new createjs.Shape,m.graphics.beginFill("#00ff00").drawRect(k.x,k.y,k.width,k.height),m.alpha=.5,p.addChild(m))};this.animationArrival=function(a,b,d){createjs.Tween.removeTweens(c);
d?(c.gotoAndPlay("shot"),createjs.Tween.get(c).wait(300).call(function(){a.destroyEffect()}),createjs.Tween.get(c).to({y:b.getY()+30,x:a.getX()-10},500,createjs.Ease.quadIn).call(function(){c.gotoAndPlay("lands");c.on("animationend",function(){c.gotoAndStop("idle");c.removeAllEventListeners()});createjs.Tween.get(c).wait(1200).call(function(){c.gotoAndPlay("dance");c.on("animationend",function(){s_oGame.win();c.removeAllEventListeners()})})})):(w&&c.gotoAndPlay("idle"),createjs.Tween.get(c).wait(300).call(function(){c.gotoAndPlay("start_jump");
createjs.Tween.get(c).wait(180).call(function(){createjs.Tween.get(c).to({y:a.getY()-100,x:a.getX()-20},750,createjs.Ease.cubicOut).call(function(){c.gotoAndPlay("shot");createjs.Tween.get(c).wait(300).call(function(){a.destroyEffect()});createjs.Tween.get(c).to({y:b.getY()+30,x:a.getX()-10},500,createjs.Ease.circIn).call(function(){c.gotoAndPlay("lands");c.on("animationend",function(){c.gotoAndStop("idle");c.removeAllEventListeners()});createjs.Tween.get(c).wait(1200).call(function(){c.gotoAndPlay("dance");
c.on("animationend",function(){s_oGame.win();c.removeAllEventListeners()})})})})})}))};this.playSeaAnimation=function(){var a=this;createjs.Tween.get(c).wait(300).call(function(){c.gotoAndStop("ice")});createjs.Tween.get(c).to({y:POSITION_Y_SEA+150},1E3,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(c).to({y:POSITION_Y_SEA+40},1E3,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(c).to({y:POSITION_Y_SEA+70},700,createjs.Ease.cubicInOut).call(function(){a.loopBounceSea();createjs.Tween.get(c).wait(600).call(function(){s_oGame.gameOver()})})})})};
this.playDeadSpikeAnimation=function(){c.gotoAndPlay("fall");s_oGame.changeState(GAME_STATE_GAMEOVER);createjs.Tween.get(c).to({y:c.y-50,x:c.x+30},500,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(c).to({y:CANVAS_HEIGHT+q},750,createjs.Ease.cubicIn).call(function(){s_oGame.gameOver()})})};this.loopBounceSea=function(){var a=this,b=5*Math.random();createjs.Tween.get(c).to({y:POSITION_Y_SEA+50,rotation:b},1E3,createjs.Ease.quartInOut).call(function(){var b=-5*Math.random();createjs.Tween.get(c).to({y:POSITION_Y_SEA+
70,rotation:b},1E3,createjs.Ease.quartInOut).call(function(){a.loopBounceSea()})})};this.removeTweens=function(){createjs.Tween.removeTweens(c)};this.update=function(){n=t?n<HERO_DOWN_ACCELLERATION?n+DECELLERATION_MOUSE_DOWN:HERO_DOWN_ACCELLERATION:n<HERO_DOWN_ACCELLERATION?n+DECELLERATION_NORMAL:HERO_DOWN_ACCELLERATION;-100>c.y&&(c.y=-100);w?r=0:(r+=n,c.y+=r);this.rectMovement()};s_oCharacter=this;this._init(a,h,b,e)}var s_oCharacter;
function CCongratulations(a,h,b,e,g){var f,d,l,c,p,k,m,n,r;this._init=function(a,b,e,h,k){r=[];f=new createjs.Container;d=new createjs.Container;n=a.width;d.y=-n;l=createBitmap(a);l.x=.5*CANVAS_WIDTH;l.y=.5*CANVAS_HEIGHT;l.regX=.5*a.width;l.regY=.5*a.height;d.addChild(l);c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;c.on("click",function(){});f.addChild(c);var g;g=new createjs.Text(TEXT_CONGRATULATIONS,"42px "+FONT_GAME,"#000000");g.textAlign=
"center";g.textBaseline="middle";g.x=.5*CANVAS_WIDTH;g.y=166;g.outline=4;d.addChild(g);a=new createjs.Text(TEXT_CONGRATULATIONS,"42px "+FONT_GAME,"#ffdc00");a.textAlign="center";a.textBaseline="middle";a.x=.5*CANVAS_WIDTH;a.y=g.y;d.addChild(a);g=new createjs.Text(TEXT_GAME_COMPLETED,"30px "+FONT_GAME,"#000000");g.textAlign="center";g.textBaseline="middle";g.x=685;g.y=236;g.outline=4;d.addChild(g);a=new createjs.Text(TEXT_GAME_COMPLETED,"30px "+FONT_GAME,"#ffdc00");a.textAlign="center";a.textBaseline=
"middle";a.x=g.x;a.y=g.y;d.addChild(a);g=new createjs.Text(TEXT_SCORE+":","26px "+FONT_GAME,"#000000");g.textAlign="center";g.textBaseline="middle";g.x=640;g.y=350;g.outline=4;d.addChild(g);a=new createjs.Text(TEXT_SCORE+":","26px "+FONT_GAME,"#ffdc00");a.textAlign="center";a.textBaseline="middle";a.x=g.x;a.y=g.y;d.addChild(a);var m;m=new createjs.Text(k,"26px "+FONT_GAME,"#000000");m.textAlign="left";m.textBaseline="middle";m.x=g.x+50;m.y=g.y;m.outline=4;d.addChild(m);var q;q=new createjs.Text(k,
"26px "+FONT_GAME,"#ffdc00");q.textAlign="left";q.textBaseline="middle";q.x=m.x;q.y=m.y;d.addChild(q);var u;u=new createjs.Text("0","26px "+FONT_GAME,"#000000");u.textAlign="center";u.textBaseline="middle";u.x=840;u.y=242;u.outline=4;var w;w=new createjs.Text("0","26px "+FONT_GAME,"#000000");w.textAlign="center";w.textBaseline="middle";w.x=840;w.y=242;k=s_oSpriteLibrary.getSprite("star");for(a=0;a<NUMBER_OF_STARS;a++)r[a]=new CStar(STARS_POSITION[a].x-75,STARS_POSITION[a].y+75,k,!1,d);f.addChild(d);
f.x=0;f.y=0;s_oStage.addChild(f);k=s_oSpriteLibrary.getSprite("but_home");p=new CGfxButton(882,350,k,d);p.addEventListener(ON_MOUSE_UP,this._onExit,this);createjs.Tween.get(c).to({alpha:.5},750,createjs.Ease.cubicOut);var t=this;createjs.Tween.get(d).to({y:0},1500,createjs.Ease.bounceOut).call(function(){s_iAdsLevel===NUM_LEVEL_FOR_ADS?($(s_oMain).trigger("show_interlevel_ad"),s_iAdsLevel=1):s_iAdsLevel++;t.checkPoint(q,m,h,t);t.checkStars(w,u,e,t)});$(s_oMain).trigger("save_score",b);$(s_oMain).trigger("share_event",
b)};this.unload=function(){var a=this;createjs.Tween.get(d).to({y:CANVAS_HEIGHT+n},1500,createjs.Ease.cubicIn).call(function(){a.unloadButton()});k.unload();m.unload()};this.unloadButton=function(){p.unload();p=null};this.blockAllBut=function(){p.block(!0)};this._onExit=function(){this.blockAllBut();var a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=0;f.addChild(a);s_oGame.decreaseVolumeSoundLevelComplete(!0);var c=this;createjs.Tween.get(a).to({alpha:1},
2500,createjs.Ease.cubicIn).call(function(){s_oGame.onExit();c.unload()})};this._onRollingTextScore=function(){};this._onRollingText=function(a){r[a].setActive(!0);r[a].pulseAnimation(500,SCALE_STAR_FACTOR);playSound("star",1,0)};this.checkStars=function(a,c,b,d){m=new CRollingTextController(a,c,b,4E3,EASE_CUBIC_OUT);m.addEventListener(ON_CONTROLLER_END,d._onFinishRollingStars);m.addEventListener(ON_CONTROLLER_REMOVE,d._onFinishRollingStars);m.addRollingListener(d._onRollingText,d,PERCENTAGE_STARS)};
this.checkPoint=function(a,c,b,d){k=new CRollingTextController(a,c,b,4E3,EASE_CUBIC_OUT);k.addEventListener(ON_CONTROLLER_END,d._onFinishRollingPoint);k.addEventListener(ON_CONTROLLER_REMOVE,d._onFinishRollingPoint);k.addRollingListener(d._onRollingTextScore,d,PERCENTAGE_STARS)};this._onFinishRollingPoint=function(){k.unload()};this._onFinishRollingStars=function(){m.unload()};this._init(a,h,b,e,g);return this}
function CCreditsPanel(){var a,h,b,e,g,f,d,l,c;this._init=function(){c=new createjs.Container;s_oStage.addChild(c);var p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);p.alpha=.5;c.addChild(p);p=s_oSpriteLibrary.getSprite("msg_box");a=createBitmap(p);c.addChild(a);a.x=.5*CANVAS_WIDTH;a.y=.5*CANVAS_HEIGHT;a.regX=.5*p.width;a.regY=.5*p.height;f=new createjs.Shape;f.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=.01;f.on("click",
this._onLogoButRelease);s_bMobile||(f.cursor="pointer");c.addChild(f);p=s_oSpriteLibrary.getSprite("but_exit");b=new CGfxButton(900,170,p,c);b.addEventListener(ON_MOUSE_UP,this.unload,this);g=new createjs.Text(TEXT_CREDITS_DEVELOPED,"28px "+FONT_GAME,"#000");g.textAlign="center";g.textBaseline="alphabetic";g.x=CANVAS_WIDTH/2+25;g.y=180;g.outline=3;c.addChild(g);e=new createjs.Text(TEXT_CREDITS_DEVELOPED,"28px "+FONT_GAME,TEXT_COLOR);e.textAlign="center";e.textBaseline="alphabetic";e.x=CANVAS_WIDTH/
2+25;e.y=g.y;c.addChild(e);p=s_oSpriteLibrary.getSprite("logo_ctl");h=createBitmap(p);h.regX=p.width/2;h.regY=p.height/2;h.x=CANVAS_WIDTH/2+25;h.y=260;c.addChild(h);l=new createjs.Text(TEXT_LINK1,"32px "+FONT_GAME,"#000");l.textAlign="center";l.textBaseline="alphabetic";l.x=CANVAS_WIDTH/2+25;l.y=360;l.outline=3;c.addChild(l);d=new createjs.Text(TEXT_LINK1,"32px "+FONT_GAME,TEXT_COLOR);d.textAlign="center";d.textBaseline="alphabetic";d.x=CANVAS_WIDTH/2+25;d.y=l.y;c.addChild(d);this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.refreshButtonPos=function(a,c){};this.unload=function(){playSound("click",1,0);f.off("click",this._onLogoButRelease);b.unload();b=null;s_oStage.removeChild(c)};this._onLogoButRelease=function(){playSound("click",1,0);window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()}
function CPause(){var a;this._init=function(){var h=new createjs.Container;h.alpha=1;a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=.5;var b=new createjs.Shape;b.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.hitArea=b;a.on("click",function(){});h.addChild(a);b=new createjs.Text(TEXT_PAUSE,"50px "+FONT_GAME,"#000000");b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT-130;b.textAlign="center";b.outline=5;h.addChild(b);var e=new createjs.Text(TEXT_PAUSE,
"50px "+FONT_GAME,TEXT_COLOR);e.x=b.x;e.y=b.y;e.textAlign="center";h.addChild(e);b=s_oSpriteLibrary.getSprite("but_continue");(new CGfxButton(.5*CANVAS_WIDTH,.5*CANVAS_HEIGHT+70,b,h)).addEventListenerWithParams(ON_MOUSE_UP,this._onLeavePause,this,h);s_oStage.addChild(h)};this.unload=function(){a.off("click",function(){});s_oStage.removeChild(void 0)};this._onLeavePause=function(a){createjs.Ticker.paused=!1;createjs.Tween.get(a).to({alpha:0},300,createjs.quartIn).call(function(){s_oInterface.unloadPause();
s_oGame.unpause(!0)})};this._init();return this}
function CAreYouSurePanel(a){var h,b,e,g,f,d;this._init=function(){f=new createjs.Container;f.visible=!1;d.addChild(f);var a;a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=.5;a.on("click",function(){});f.addChild(a);a=s_oSpriteLibrary.getSprite("msg_box");var c=createBitmap(a);c.x=.5*CANVAS_WIDTH;c.y=.5*CANVAS_HEIGHT;c.regX=.5*a.width;c.regY=.5*a.height;f.addChild(c);h=new createjs.Text(TEXT_ARE_SURE,"40px "+FONT_GAME,"#000");h.x=CANVAS_WIDTH/2+
25;h.y=200;h.textAlign="center";h.textBaseline="middle";h.outline=5;f.addChild(h);b=new createjs.Text(h.text,"40px "+FONT_GAME,TEXT_COLOR);b.x=h.x;b.y=h.y;b.textAlign="center";b.textBaseline="middle";f.addChild(b);e=new CGfxButton(CANVAS_WIDTH/2+145,350,s_oSpriteLibrary.getSprite("but_yes"),f);e.addEventListener(ON_MOUSE_UP,this._onButYes,this);g=new CGfxButton(CANVAS_WIDTH/2-120,350,s_oSpriteLibrary.getSprite("but_exit_big"),f);g.addEventListener(ON_MOUSE_UP,this._onButNo,this)};this.show=function(){s_oGame.unpause(!1);
f.visible=!0};this._onButYes=function(){s_oGame.unpause(!0);s_oGame.onExit()};this._onButNo=function(){s_oGame.unpause(!0);f.visible=!1};this.unload=function(){e.unload();g.unload()};d=a;this._init()}
function CLevelPlatforms(a,h,b){var e,g,f,d,l;this._init=function(a,b,f){l=PLATFORM_SPEED;g=f;d=[];e=new createjs.Container;e.x=a;e.y=b;g.addChild(e);g.setChildIndex(e,2)};this.addPlatform=function(a,b,f,g,l){d[f]=new CPlatform(a,b,f,g,l,e);a>ON_VISIBLE_X&&d[f].setVisible(!1)};this.setSpeed=function(a){l=a};this.setPosition=function(a,b){e.x=a;e.y=b};this.unload=function(){g.removeChild(e);d=e=null;f.unload();f=null};this.unloadPlatform=function(){for(var a=0;a<d.length;a++)e.removeChild(d[a]);d=
null};this.repositionArrivalToLastPlatform=function(){var a=d[d.length-1];f.setPosition(a.getX()+.5*a.getWidth()+OFFSET_ARRIVAL_POS.x,a.getY()+OFFSET_ARRIVAL_POS.y)};this.getPlatformByID=function(a){return d[a]};this.moveArrival=function(){var a=f.getX()+l,b=f.getY();f.setPosition(a,b);a<ON_VISIBLE_X&&f.setVisible(!0)};this.managePlatform=function(){for(var a=0;a<d.length;a++){var b=d[a].getX()+l,f=d[a].getY();d[a].setPosition(b,f);b=d[a].getX();b<ON_VISIBLE_X&&b>-d[a].getWidth()?d[a].setVisible(!0):
d[a].setVisible(!1)}this.moveArrival()};this.createArrival=function(a){a=d.length-1+a;var c=d[a];f=new CArrival(c.getX()+.5*c.getWidth()+OFFSET_ARRIVAL_POS.x,c.getY()+OFFSET_ARRIVAL_POS.y);f.setVisible(!1);f.setIDPlatform(a)};this.collisionPlatforms=function(a){var c=a.rect,b=d[a.id].controlCollision(c);if(b.collision===COLLISION_NOTHING)for(var f=a.id;f<a.id+PREVIEW_COLLISION;f++)if(!(f>d.length-1)){var e=d[f].controlCollision(c);if(e.collision===COLLISION_PLATFORM||e.collision===COLLISION_WALL)return e.collide=
b.collide,e}return b};this.collisionArrival=function(a){!0===f.getVisible()&&f.controlCollision(a)===COLLISION_ARRIVAL&&s_oGame.platformFinished()};this.getArrival=function(){return f};this.update=function(a){this.managePlatform();var c=this.collisionPlatforms(a);this.collisionArrival(a.rect);return c};this._init(a,h,b);return this}
function CPlatform(a,h,b,e,g,f){var d,l,c,p,k,m,n,r=null,t,x,u,q=!1;this._init=function(a,b,f,e,g,h){k=h;u=f;f=s_oSpriteLibrary.getSprite("platform_"+e+"_"+g);m=createBitmap(f);m.x=a;m.y=b;t=f.width+OFFSET_PLATFORM_COL_DIMENSION[g].x;x=f.height+OFFSET_PLATFORM_COL_DIMENSION[g].y;m.regY=0;d=a+OFFSET_PLATFORM_COL_POINT[g].x;l=b+OFFSET_PLATFORM_COL_POINT[g].y;c=t;p=x;n=new createjs.Rectangle(a+OFFSET_PLATFORM_COL_POINT[g].x,b+OFFSET_PLATFORM_COL_POINT[g].y,t,x);SHOW_COLLISION_SHAPE&&(r=new createjs.Shape,
r.graphics.beginFill("#00ff00").drawRect(n.x,n.y,n.width,n.height),r.alpha=.5,k.addChild(r));k.addChild(m)};this.setPosition=function(a,c){m.x=a;m.y=c;this.rectMovement()};this.rectMovement=function(){d=m.x+OFFSET_PLATFORM_COL_POINT[g].x;l=m.y+OFFSET_PLATFORM_COL_POINT[g].y;c=t;p=x;n.setValues(d,l,c,p);SHOW_COLLISION_SHAPE&&(r&&(k.removeChild(r),r=null),r=new createjs.Shape,r.graphics.beginFill("#00ff00").drawRect(n.x,n.y,n.width,n.height),r.alpha=.5,k.addChild(r))};this.getX=function(){return m.x};
this.getY=function(){return m.y};this.getRectX=function(){return n.x};this.getWidth=function(){return t};this.setVisible=function(a){m.visible=a};this.collideYet=function(){return q};this.setCollideYet=function(a){q=a};this.unload=function(){k.removeChild(m)};this.getID=function(){return u};this.setID=function(a){u=a};this.controlCollision=function(a){if(n)return n.intersects(a)?a.x+.6*a.width>n.x&&n.y>=Math.floor(a.y)+OFFSET_HEIGHT_COLLISION_PLATFORM?(a={collision:COLLISION_PLATFORM,id:u,y:m.y,collide:q},
q=!0):a={collision:COLLISION_WALL,id:u,y:m.y}:(q=!1,a={collision:COLLISION_NOTHING,id:u,y:m.y,collide:q}),a};this._init(a,h,b,e,g,f);return this}
function CArrival(a,h){var b,e,g,f,d,l,c,p,k,m,n,r,t;this._init=function(a,h){c=new createjs.Container;c.x=a;var q=s_oSpriteLibrary.getSprite("arrival_1");k=createBitmap(q);k.regX=.5*q.width;k.regY=.5*q.height;k.x=.26*k.regX;k.y=0;c.addChild(k);q=s_oSpriteLibrary.getSprite("arrival_0");m=createBitmap(q);m.regX=.5*q.width;m.regY=.5*q.height;m.x=.26*-m.regX;m.y=0;c.y=h-.4*q.height;c.addChild(m);r=q.height+OFFSET_RECT_ARRIVAL.y;b=m.regX+OFFSET_RECT_ARRIVAL.x;e=m.regY+OFFSET_RECT_ARRIVAL.y;g=a-b;f=h-
e;d=WEIGHT_ARRIVAL;l=r;p=new createjs.Rectangle(a,h,d,l);SHOW_COLLISION_SHAPE&&(n&&(s_oStage.removeChild(n),n=null),n=new createjs.Shape,n.graphics.beginFill("#00ff00").drawRect(p.x,p.y,p.width,p.height),n.alpha=.5,s_oStage.addChild(n));s_oStage.addChild(c)};this.destroyEffect=function(){var a=this;playSound("broken_stone",1,0);playSound("hit_axe",1,0);createjs.Tween.get(k).to({y:-50},500,createjs.Ease.circOut).call(function(){createjs.Tween.get(k).to({y:CANVAS_HEIGHT},1E3,createjs.Ease.circIn)});
createjs.Tween.get(k).to({x:300,rotation:270},2500,createjs.Ease.circOut).call(function(){a.unload()});createjs.Tween.get(m).to({y:-50},500,createjs.Ease.circOut).call(function(){createjs.Tween.get(m).to({y:CANVAS_HEIGHT},1E3,createjs.Ease.circIn)});createjs.Tween.get(m).to({x:-300,rotation:-270},2500,createjs.Ease.circOut).call(function(){})};this.setVisible=function(a){c.visible=a};this.setPosition=function(a,b){c.x=a;c.y=b;this.positionRect()};this.positionRect=function(){g=c.x-b;f=c.y-e;d=WEIGHT_ARRIVAL;
l=r;p.setValues(g,f,d,l);SHOW_COLLISION_SHAPE&&(n&&(s_oStage.removeChild(n),n=null),n=new createjs.Shape,n.graphics.beginFill("#00ff00").drawRect(p.x,p.y,p.width,p.height),n.alpha=.5,s_oStage.addChild(n))};this.setIDPlatform=function(a){t=a};this.getIDPlatform=function(){return t};this.controlCollision=function(a){if(p)return p.intersects(a)?COLLISION_ARRIVAL:COLLISION_NOTHING};this.getVisible=function(){return c.visible};this.getX=function(){return c.x};this.getY=function(){return c.y};this.unload=
function(){s_oStage.removeChild(c);c=null};this._init(a,h)}function CLogo(a,h){var b;this._init=function(a,g){var f=s_oSpriteLibrary.getSprite("logo");b=createBitmap(f);b.regX=.5*f.width;b.regY=.5*f.height;b.x=a;b.y=g;s_oStage.addChild(b)};this.playAnimation=function(){createjs.Tween.get(b).to({y:LOGO_Y_POS},1E3,createjs.Ease.bounceOut)};this.unload=function(){s_oScrollStage.removeChild(b);b=null};this._init(a,h);return this}
function CParallaxObject(a,h,b){var e,g,f,d=0;this._init=function(a,c,b){f=[];e=b;g=new createjs.Container;g.x=a;g.y=c;e.addChild(g);e.setChildIndex(g,1)};this.addObject=function(a,c,b,d){var e=f.length;f.push(new CParallaxeObject(a,c,b,d,g));this.randomObjectScale(f[e]);this.randomFlipObject(f[e])};this.unload=function(){e.removeChild(g);g=null};this.unloadObject=function(){for(var a=0;a<f.length;a++)g.removeChild(f[a])};this.randomObjectScale=function(a){a.scale(Math.random()*-MIN_SCALE_PARALLAXE+
MAX_SCALE_PARALLAXE)};this.randomFlipObject=function(a){1===Math.round(1*Math.random())?a.flip(!0):a.flip(!1)};this.randomPosition=function(a){a.setPosition(Math.random()*MAX_POS_X_RANDOM_PARALLAXE+PARALLAXE_OBJ_X_REPOS,a.getY())};this.randomizeObject=function(a){this.randomPosition(a);this.randomObjectScale(a);this.randomFlipObject(a)};this.setSpeed=function(a){d=a};this.update=function(){for(var a=0;a<f.length;a++){var c=f[a].getX()+d,b=f[a].getY();f[a].setPosition(c,b);f[a].getX()<PARALLAXE_OBJ_X_RANDOMIZE&&
this.randomizeObject(f[a])}};this._init(a,h,b);return this}
function CParallaxeObject(a,h,b,e,g){var f,d,l=1;this._init=function(a,b,e,g,h){e=s_oSpriteLibrary.getSprite("parallaxe_"+e+"_"+g);d=h;f=createBitmap(e);f.regX=.5*e.width;f.regY=e.height;f.x=a;f.y=b;d.addChild(f)};this.flip=function(a){f.scaleX=a?-l:l};this.scale=function(a){l=a;f.scaleX=l;f.scaleY=l};this.setPosition=function(a,b){f.x=a;f.y=b};this.getX=function(){return f.x};this.getY=function(){return f.y};this.unload=function(){d.removeChild(f);f=null};this._init(a,h,b,e,g);return this}
function CSea(a,h,b){var e,g,f,d,l=0;this._init=function(a,b,h){f=[];e=h;g=new createjs.Container;g.x=a;g.y=b;a=s_oSpriteLibrary.getSprite("sea");d=a.width;b=0;h=POSITION_Y_SEA;for(var c=0;c<SEA_NUMBER;c++)f[c]=this.addSea(b,h,a),b+=d;e.addChild(g)};this.addSea=function(a,b,f){f=createBitmap(f);f.x=a;f.y=b;f.regX=d;g.addChild(f);return f};this.unload=function(){e.removeChild(g);g=null};this.setSpeed=function(a){l=a};this.update=function(){for(var a=0;a<f.length;a++)0>f[a].x&&(f[a].x=0===a?f[f.length-
1].x+d:f[a-1].x+d),f[a].x+=l};this._init(a,h,b);return this}
function CLevelObjects(a,h,b){var e,g,f,d;this._init=function(a,c,b){d=PLATFORM_SPEED;g=b;f=[];e=new createjs.Container;e.x=a;e.y=c;g.addChild(e);g.setChildIndex(e,3)};this.addObject=function(a,c,b,d){f[b]=new CObject(a,c,b,d,e);a>ON_VISIBLE_X&&f[b].setVisible(!1)};this.setSpeed=function(a){d=a};this.setPosition=function(a,c){e.x=a;e.y=c};this.unload=function(){g.removeChild(e);f=e=null};this.unloadObjects=function(){for(var a=0;a<f.length;a++)e.removeChild(f[a]);f=null};this.unloadObject=function(a){f[a].unload();
f.splice(a,1);for(a=0;a<f.length;a++)f[a].setID(a)};this.getObjectByID=function(a){return f[a]};this.manageObjects=function(){for(var a=0;a<f.length;a++){var c=f[a].getX()+d,b=f[a].getY();f[a].setPosition(c,b);c=f[a].getX();c<ON_VISIBLE_X&&c>-f[a].getWidth()?f[a].setVisible(!0):f[a].setVisible(!1)}};this.collisionObjects=function(a){a=a.rect;for(var c=0;c<f.length;c++)f[c].getVisible()&&f[c].controlCollision(a)};this.update=function(a){this.manageObjects();this.collisionObjects(a)};this._init(a,h,
b);return this}
function CObject(a,h,b,e,g){var f,d,l,c,p,k,m,n=null,r,t,x,u,q;this._init=function(a,b,e,g,h){p=h;u=e;q=g;e=s_oSpriteLibrary.getSprite("object_"+g);h=g=1;if(0===q){g=4;h=5;var w=new createjs.SpriteSheet({images:[e],frames:{width:e.width/h,height:e.height/g,regX:0,regY:e.height/2/g},animations:{normal:[0,19,"normal"]}});k=createSprite(w,"run",0,e.height/2/g,e.width/h,e.height/g)}else k=createBitmap(e),k.regX=0,k.regY=e.height/2;k.x=a;k.y=b;r=e.width/h;t=e.height/g;x=.5*t;f=a;d=b-x;l=r;c=t;m=new createjs.Rectangle(a,
b,r,t);SHOW_COLLISION_SHAPE&&(n=new createjs.Shape,n.graphics.beginFill("#00ff00").drawRect(m.x,m.y,m.width,m.height),n.alpha=.5,p.addChild(n));p.addChild(k)};this.setPosition=function(a,b){k.x=a;k.y=b;this.rectMovement()};this.rectMovement=function(){f=k.x;d=k.y-x;l=r;c=t;m.setValues(f,d,l,c);SHOW_COLLISION_SHAPE&&(n&&(p.removeChild(n),n=null),n=new createjs.Shape,n.graphics.beginFill("#00ff00").drawRect(m.x,m.y,m.width,m.height),n.alpha=.5,p.addChild(n))};this.getX=function(){return k.x};this.getY=
function(){return k.y};this.getRectX=function(){return m.x};this.getWidth=function(){return r};this.setVisible=function(a){k.visible=a};this.collideYet=function(){return!1};this.getVisible=function(){return k.visible};this.unload=function(){p.removeChild(k)};this.getID=function(){return u};this.setID=function(a){u=a};this.controlCollision=function(a){m&&m.intersects(a)&&(0===e?(s_oGame.addScore(COIN_SCORE),playSound("coin",1,0),s_oGame.addObtainCoin(),s_oGame.unloadObject(u)):1===e&&s_oGame.spikeCollision())};
this._init(a,h,b,e,g);return this}
function CLevelBut(a,h,b,e,g,f){var d,l,c,p=[],k=[],m,n;this._init=function(a,b,e,f){l=[];c=[];var h=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{state_true:[0],state_false:[1]}});d=f;m=createSprite(h,"state_"+d,e.width/2/2,e.height/2,e.width/2,e.height);m.mouseEnabled=f;m.x=a;m.y=b;m.stop();s_bMobile||(m.cursor="pointer");n.addChild(m);p.push(m);e=new createjs.Text(g,"bold 40px "+FONT_GAME,"#000000");e.x=a-2;e.y=b+13;e.textAlign=
"center";e.textBaseline="alphabetic";e.lineWidth=200;e.outline=6;n.addChild(e);a=new createjs.Text(g,"bold 40px "+FONT_GAME,TEXT_COLOR);a.x=e.x;a.y=e.y;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=200;n.addChild(a);this._initListener()};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);n.removeChild(m)};this._initListener=function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.viewBut=function(a){n.addChild(a)};
this.addEventListener=function(a,b,d){l[a]=b;c[a]=d};this.addEventListenerWithParams=function(a,b,d,e){l[a]=b;c[a]=d;k=e};this.ifClickable=function(){return!0===m.mouseEnabled?1:0};this.setActive=function(a,b){d=b;p[a].gotoAndStop("state_"+d);p[a].mouseEnabled=!0};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;playSound("click",1,0);d=!d;m.gotoAndStop("state_"+d);l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(c[ON_MOUSE_UP],k)};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(c[ON_MOUSE_DOWN],
k)};this.setPosition=function(a,b){m.x=a;m.y=b};this.setVisible=function(a){m.visible=a};n=f;this._init(a,h,b,e)}
function CLevelMenu(a){var h,b,e,g,f,d,l,c=[],p,k,m,n,r=null,t=null,x;this._init=function(){p=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));p.x=0;p.y=0;s_oStage.addChild(p);var a=s_oSpriteLibrary.getSprite("msg_box");p=createBitmap(a);p.x=.5*CANVAS_WIDTH;p.y=.5*CANVAS_HEIGHT;p.regX=.5*a.width;p.regY=.5*a.height;s_oStage.addChild(p);l=new createjs.Container;l.x=0;l.y=0;a=new createjs.Text(TEXT_SELECT_A_LEVEL," 40px "+FONT_GAME,TEXT_COLOR);a.x=CANVAS_WIDTH/2+25;a.y=176;a.textAlign="center";a.textBaseline=
"alphabetic";a.lineWidth=1E3;var q;q=new createjs.Text(TEXT_SELECT_A_LEVEL," 40px "+FONT_GAME,"#000000");q.x=a.x;q.y=176;q.textAlign="center";q.textBaseline="alphabetic";q.lineWidth=1E3;q.outline=3;l.addChild(q,a);s_oStage.addChild(l);for(var w=q=a=0;w<s_aLevelDiagram.length;w++,a+=85){350<a&&(a=0,q+=100);var v=535+a,y=240+q;w<s_iLevelReached?(c[w]=new CLevelBut(v,y,s_oSpriteLibrary.getSprite("but_level"),!0,w+1,s_oStage),c[w].addEventListenerWithParams(ON_MOUSE_DOWN,this._onClick,this,w),this.addStars(v,
y,w)):c[w]=new CLevelBut(535+a,240+q,s_oSpriteLibrary.getSprite("but_level"),!1,w+1,s_oStage);s_bFirstTime=!0}a=s_oSpriteLibrary.getSprite("but_exit");f=CANVAS_WIDTH-a.width/2-10;d=a.height/2+10;k=new CGfxButton(f,d,a,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=s_oSpriteLibrary.getSprite("audio_icon"),e=CANVAS_WIDTH-q.width/2-a.width/2-18,g=q.height/2+10,m=new CToggle(e,g,q,s_bAudioActive,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);a=window.document;q=a.documentElement;r=q.requestFullscreen||q.mozRequestFullScreen||q.webkitRequestFullScreen||q.msRequestFullscreen;t=a.exitFullscreen||a.mozCancelFullScreen||a.webkitExitFullscreen||a.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(r=!1);r&&!1===inIframe()&&(q=s_oSpriteLibrary.getSprite("but_fullscreen"),h=q.width/4+10,b=q.height/2+10,x=new CToggle(h,b,q,s_bFullscreen,s_oStage),x.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));n=new createjs.Shape;n.graphics.beginFill("black").drawRect(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(n);createjs.Tween.get(n).to({alpha:0},1E3).call(function(){s_oStage.removeChild(n)});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.addStars=function(a,b,c){var d=[];c=s_aPercentage[c];a-=26;b-=34;for(var e=s_oSpriteLibrary.getSprite("star"),f=0;f<NUMBER_OF_STARS;f++){var g=!1;c>PERCENTAGE_STARS[f]&&(g=!0);d[f]=new CStar(a,b,e,g,s_oStage);d[f].setScale(.5);a+=26}};this.unload=function(){for(var a=0;a<s_aLevelDiagram.length;a++)c[a].unload();k.unload();
!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.unload();r&&!1===inIframe()&&x.unload();s_oLevelMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(e-a,g+c);r&&!1===inIframe()&&x.setPosition(h+a,b+c);k.setPosition(f-a,d+c)};this._onNumModeToggle=function(a){a===NUM_ACTIVE?((void 0).setActive(!1),(void 0).setActive(!0)):((void 0).setActive(!0),(void 0).setActive(!1))};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?(t.call(window.document),s_bFullscreen=!1):(r.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};this._onClick=function(a){c[a].ifClickable()&&(s_oLevelMenu.unload(),s_oMain.gotoGame(a))};this._onExit=function(){playSound("click",1,0);s_oLevelMenu.unload();s_oMain.gotoMenu()};PERCENTAGE_STARS=a.percentage_stars;s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CConfirmPanel(a){var h=this,b=[],e=[],g=[],f,d,l=CANVAS_WIDTH/2,c=CANVAS_HEIGHT/2,p,k,m,n,r;this._init=function(){var b=s_oSpriteLibrary.getSprite("msg_box");d=new createjs.Container;d.x=l;d.y=-b.height;m=new createjs.Shape;m.graphics.beginFill("#000000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);m.alpha=0;m.on("mousedown",this._onClick);s_oStage.addChild(m);f=createBitmap(b);f.regX=b.width/2;f.regY=b.height/2;d.addChild(f);k=new createjs.Text(a," 30px "+FONT_GAME,"#000");k.x=0;k.y=-90;k.textAlign=
"center";k.textBaseline="alphabetic";k.lineWidth=400;k.outline=3;d.addChild(k);p=new createjs.Text(a," 30px "+FONT_GAME,TEXT_COLOR);p.x=0;p.y=-90;p.textAlign="center";p.textBaseline="alphabetic";p.lineWidth=400;d.addChild(p);n=new CGfxButton(-100,75,s_oSpriteLibrary.getSprite("but_exit_big"),d);n.pulseAnimation();r=new CGfxButton(100,75,s_oSpriteLibrary.getSprite("but_yes"),d);s_oStage.addChild(d);this.show()};this._initListener=function(){n.addEventListener(ON_MOUSE_DOWN,this.buttonNoDown,this);
r.addEventListener(ON_MOUSE_DOWN,this.buttonYesDown,this)};this.addEventListener=function(a,c,d){b[a]=c;e[a]=d};this.buttonNoDown=function(){b[ON_BUT_NO_DOWN]&&b[ON_BUT_NO_DOWN].call(e[ON_BUT_NO_DOWN],g)};this.buttonYesDown=function(){b[ON_BUT_YES_DOWN]&&b[ON_BUT_YES_DOWN].call(e[ON_BUT_YES_DOWN],g)};this._onClick=function(){};this.show=function(){createjs.Tween.get(m).to({alpha:.7},500);createjs.Tween.get(d).to({y:c},500,createjs.Ease.quadOut).call(function(){h._initListener()})};this.unload=function(){createjs.Tween.get(d).to({y:1.5*
CANVAS_HEIGHT},500).call(function(){s_oStage.removeChild(d)});createjs.Tween.get(m).to({alpha:0},500).call(function(){s_oStage.removeChild(m)})};this._init();s_oVariousHelp=this;return this}var s_oVariousHelp=null,EASE_LINEAR=0,EASE_CUBIC_IN=1,EASE_QUART_BACKIN=2,EASE_BACKIN=3,EASE_SIN_IN=4,EASE_QUAD_IN=5,EASE_CUBIC_OUT=6,EASE_ELASTIC_OUT=7,EASE_BACKOUT=8,EASE_QUINT_OUT=9,EASE_CUBIC_INOUT=10;
function CTweenController(){this.tweenValue=function(a,h,b){return a+b*(h-a)};this.easeLinear=function(a,h,b,e){return b*a/e+h};this.easeInCubic=function(a,h,b,e){e=(a/=e)*a*a;return h+b*e};this.easeBackInQuart=function(a,h,b,e){e=(a/=e)*a;return h+b*(2*e*e+2*e*a+-3*e)};this.easeInBack=function(a,h,b,e){return b*(a/=e)*a*(2.70158*a-1.70158)+h};this.easeInSine=function(a,h,b,e){return-b*Math.cos(a/e*(Math.PI/2))+b+h};this.easeInQuad=function(a,h,b,e){return b*(a/=e)*a+h};this.easeOutCubic=function(a,
h,b,e){return b*((a=a/e-1)*a*a+1)+h};this.easeOutElastic=function(a,h,b,e){var g;if(0===a)return h;if(1===(a/=e))return h+b;g=.3*e;return b*Math.pow(2,-10*a)*Math.sin(2*(a*e-g/4)*Math.PI/g)+b+h};this.easeOutBack=function(a,h,b,e){return b*((a=a/e-1)*a*(2.70158*a+1.70158)+1)+h};this.easeInOutCubic=function(a,h,b,e){return 1>(a/=e/2)?b/2*a*a*a+h:b/2*((a-=2)*a*a+2)+h};this.easeOutQuint=function(a,h,b,e){return b*((a=a/e-1)*a*a*a*a+1)+h}}
function CRollingTextController(a,h,b,e,g){var f,d,l,c,p,k,m,n,r,t,x,u,q;this._init=function(a,b,c,d,e){r=[];t=[];p=d;this.setUpdateInfo(c);n=e;u=a;q=b};this.unload=function(){clearInterval(m)};this.setUpdateInfo=function(b){l=parseFloat(a.text);c=l+b;f=0;d=Math.round(p/FPS);k=0;var e=this;m=setInterval(function(){e.update()},FPS_TIME)};this.addEventListener=function(a,b,c){r[a]=b;t[a]=c};this.addRollingListener=function(a,b,c){r[ON_CONTROLLER_ROLL]=a;t[ON_CONTROLLER_ROLL]=b;x=[];for(a=0;a<c.length;a++)x[a]=
{step:c[a],flag:!1}};this.increaseValue=function(a){k=a};this.getTarget=function(){return u};this.update=function(){f++;if(f>d)f=0,u.text=c.toFixed(0),null!==q&&(q.text=c.toFixed(0)),clearInterval(m),null!==r[ON_CONTROLLER_END]&&r[ON_CONTROLLER_END].call(t[ON_CONTROLLER_END],this),0<k?this.setUpdateInfo(k):r[ON_CONTROLLER_REMOVE].call(t[ON_CONTROLLER_REMOVE],this);else{var a;switch(n){case EASE_BACKIN:a=s_oTweenController.easeInBack(f,0,1,d);break;case EASE_BACKOUT:a=s_oTweenController.easeOutBack(f,
0,1,d);break;case EASE_CUBIC_IN:a=s_oTweenController.easeInCubic(f,0,1,d);break;case EASE_CUBIC_OUT:a=s_oTweenController.easeOutCubic(f,0,1,d);break;case EASE_ELASTIC_OUT:a=s_oTweenController.easeOutElastic(f,0,1,d);break;case EASE_LINEAR:a=s_oTweenController.easeLinear(f,0,1,d);break;case EASE_QUART_BACKIN:a=s_oTweenController.easeBackInQuart(f,0,1,d);break;default:a=s_oTweenController.easeLinear(f,0,1,d)}a=s_oTweenController.tweenValue(l,c,a);for(var b=0;b<x.length;b++)a>x[b].step&&!x[b].flag&&
(x[b].flag=!0,null!==r[ON_CONTROLLER_ROLL]&&r[ON_CONTROLLER_ROLL].call(t[ON_CONTROLLER_ROLL],b));u.text=a.toFixed(0);null!==q&&(q.text=a.toFixed(0))}};this._init(a,h,b,e,g)}
function CStar(a,h,b,e,g){var f,d,l=1,c=1,p;this._init=function(a,b,c,e){var g=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=e;d=createSprite(g,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);d.x=a;d.y=b;d.stop();p.addChild(d)};this.unload=function(){p.removeChild(d)};this.setActive=function(a){f=a;d.gotoAndStop("state_"+f)};this.setPosition=function(a,b){d.x=a;d.y=b};this.setScale=
function(a){c=l=a;d.scaleX=a;d.scaleY=a};this.pulseAnimation=function(a,b){createjs.Tween.get(d).to({scaleX:l*b,scaleY:c*b},a+200,createjs.Ease.quadOut).to({scaleX:l,scaleY:c},a,createjs.Ease.quadIn)};p=g;this._init(a,h,b,e)}
function CMsgBox(a,h){var b,e,g,f,d,l;this._init=function(a){d=new createjs.Container;l.addChild(d);var c;c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=.5;c.on("click",function(){});d.addChild(c);c=s_oSpriteLibrary.getSprite("msg_box");var f=createBitmap(c);f.x=.5*CANVAS_WIDTH;f.y=.5*CANVAS_HEIGHT;f.regX=.5*c.width;f.regY=.5*c.height;d.addChild(f);b=new createjs.Text(a,"24px "+FONT_GAME,"#000");b.x=CANVAS_WIDTH/2+25;b.y=160;b.textAlign="center";
b.textBaseline="middle";b.lineWidth=500;b.outline=2;d.addChild(b);e=new createjs.Text(b.text,"24px "+FONT_GAME,TEXT_COLOR);e.x=b.x;e.y=b.y;e.textAlign="center";e.textBaseline="middle";e.lineWidth=500;d.addChild(e);g=new CGfxButton(CANVAS_WIDTH/2,350,s_oSpriteLibrary.getSprite("but_yes"),d);g.addEventListener(ON_MOUSE_UP,this._onButOk,this)};this._onButOk=function(){f.unload()};this.unload=function(){g.unload();l.removeChild(d)};f=this;l=h;this._init(a)};
