var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(c){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(c)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(c.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(c){console.log(c)}function isIOS(){for(var c="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");c.length;)if(navigator.platform===c.pop())return!0;return!1}
function getSize(c){var m=c.toLowerCase(),a=window.document,e=a.documentElement;if(void 0===window["inner"+c])c=e["client"+c];else if(window["inner"+c]!=e["client"+c]){var d=a.createElement("body");d.id="vpw-test-b";d.style.cssText="overflow:scroll";var g=a.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+m+":"+e["client"+c]+"px){body#vpw-test-b div#vpw-test-d{"+m+":7px!important}}</style>";d.appendChild(g);e.insertBefore(d,a.head);
c=7==g["offset"+c]?e["client"+c]:window["inner"+c];e.removeChild(d)}else c=window["inner"+c];return c}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var c=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<c?c:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var c;c=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var m=getSize("Width");_checkOrientation(m,c);var a=Math.min(c/CANVAS_HEIGHT,m/CANVAS_WIDTH),e=CANVAS_WIDTH*a,a=CANVAS_HEIGHT*a,d;a<c?(d=c-a,a+=d,e+=CANVAS_WIDTH/CANVAS_HEIGHT*d):e<m&&(d=m-e,e+=d,a+=CANVAS_HEIGHT/CANVAS_WIDTH*d);d=c/2-a/2;var g=m/2-e/2,b=CANVAS_WIDTH/e;if(g*b<-EDGEBOARD_X||d*b<-EDGEBOARD_Y)a=Math.min(c/(CANVAS_HEIGHT-2*EDGEBOARD_Y),
m/(CANVAS_WIDTH-2*EDGEBOARD_X)),e=CANVAS_WIDTH*a,a*=CANVAS_HEIGHT,d=(c-a)/2,g=(m-e)/2,b=CANVAS_WIDTH/e;s_iOffsetX=-1*g*b;s_iOffsetY=-1*d*b;0<=d&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",e+"px");$("#canvas").css("height",a+"px");0>d?$("#canvas").css("top",d+"px"):$("#canvas").css("top",
"0px");$("#canvas").css("left",g+"px")}}function createBitmap(c,m,a){var e=new createjs.Bitmap(c),d=new createjs.Shape;m&&a?d.graphics.beginFill("#fff").drawRect(0,0,m,a):d.graphics.beginFill("#ff0").drawRect(0,0,c.width,c.height);e.hitArea=d;return e}
function _checkOrientation(c,m){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(c>m?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(c){return!0}}function createSprite(c,m,a,e,d,g){c=null!==m?new createjs.Sprite(c,m):new createjs.Sprite(c);m=new createjs.Shape;m.graphics.beginFill("#000000").drawRect(-a,-e,d,g);c.hitArea=m;return c}function randomFloatBetween(c,m,a){"undefined"===typeof a&&(a=2);return parseFloat(Math.min(c+Math.random()*(m-c),m).toFixed(a))}
function formatTime(c){c/=1E3;var m=Math.floor(c/60);c=Math.floor(c-60*m);var a="",a=10>m?a+("0"+m+":"):a+(m+":");return 10>c?a+("0"+c):a+c}function NoClickDelay(c){this.element=c;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(c){for(var m=c.length,a,e;0<m;)e=Math.floor(Math.random()*m),m--,a=c[m],c[m]=c[e],c[e]=a;return c}
NoClickDelay.prototype={handleEvent:function(c){switch(c.type){case "touchstart":this.onTouchStart(c);break;case "touchmove":this.onTouchMove(c);break;case "touchend":this.onTouchEnd(c)}},onTouchStart:function(c){c.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(c){this.moved=!0},onTouchEnd:function(c){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){c=document.elementFromPoint(c.changedTouches[0].clientX,c.changedTouches[0].clientY);3==c.nodeType&&(c=c.parentNode);var m=document.createEvent("MouseEvents");m.initEvent("click",!0,!0);c.dispatchEvent(m)}}};function toRadian(c){return Math.PI/180*c}function toDegree(c){return 180/Math.PI*c}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(c){for(var m=window.location.search.substring(1).split("&"),a=0;a<m.length;a++){var e=m[a].split("=");if(e[0]==c)return e[1]}}function playSound(c,m,a){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(c,{loop:a,volume:m}):null}function stopSound(c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||c.stop()}function setVolume(c,m){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c.volume=m}
function setMute(c,m){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||c.setMute(m)}
(function(){function c(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[m]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var m="hidden";m in document?document.addEventListener("visibilitychange",c):(m="mozHidden")in document?document.addEventListener("mozvisibilitychange",c):(m="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",c):(m="msHidden")in document?document.addEventListener("msvisibilitychange",c):"onfocusin"in document?document.onfocusin=document.onfocusout=c:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=c})();
function CSpriteLibrary(){var c,m,a,e,d,g;this.init=function(b,l,f){a=m=0;e=b;d=l;g=f;c={}};this.addSprite=function(b,a){c.hasOwnProperty(b)||(c[b]={szPath:a,oSprite:new Image},m++)};this.getSprite=function(b){return c.hasOwnProperty(b)?c[b].oSprite:null};this._onSpritesLoaded=function(){d.call(g)};this._onSpriteLoaded=function(){e.call(g);++a===m&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in c)c[b].oSprite.oSpriteLibrary=this,c[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
c[b].oSprite.src=c[b].szPath};this.getNumSprites=function(){return m}}
var CANVAS_WIDTH=840,CANVAS_HEIGHT=1024,EDGEBOARD_X=100,EDGEBOARD_Y=30,FPS_TIME=1E3/30,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="domdiagonal_btregular",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,MAX_BONUS_BOUNCE=5,TYPES_OF_BRICK=6,TYPES_OF_BONUS=10,MAX_BRICK_FOR_ROW=7,MAX_BALL_SPAWN=4,MAX_VELOCITY_LIMIT=1.5,MIN_VELOCITY_LIMIT=.5,MAX_TIME_SHOT_BONUS=100,BONUS_MULTI_BALL=0,TIME_BOUNCE_BALL=.01,BRICKS_LEVEL_POSITION,
COLOR_TEXT_LEVEL,HEIGHT_OF_PADDLE=CANVAS_HEIGHT/2+370,OFFSET_BALL_PAD_Y=15,BONUS_OCCURRENCE_PER_LEVEL,PADDLE_DIMENSION=[80,150,210],SPACE_BETWEEN_BRICKS=-3,TIME_REFLECT_IRON_BRICK=100,LAUNCH_BALL_POS=.1,EDGE_OFFSET=102,OFFSET_BRICK_Y_POS=-16,OFFSET_HEIGHT_BRICK=0,OFFSET_WIDTH_BRICK=0,OFFSET_X_BRICK=-1,OFFSET_Y_BRICK=0,OFFSET_RADIUS_BALL=0,OFFSET_DIAGRAM_CHECK=25,OFFSETEDGEDOWN=83,OFFSETEDGEUP=50,OFFSETEDGERIGHT=106,OFFSETEDGELEFT=106,OFFSETPOWERUPFLOOR=20,OFFSET_PAD_Y=15,OFFSET_PAD_MAGNETIC_Y=-1,
OFFSET_CENTER_X_DIAGRAM=-35,OFFSET_CENTER_Y_DIAGRAM=-55,OFFSET_BRICK_SECTION_X=70,OFFSET_BRICK_SECTION_Y=15,OFFSET_DETECTION_BRICK_SECTION_X=-50,OFFSET_DETECTION_BRICK_SECTION_Y=60,OFFSET_DIM_X_CANNONS=32,OFFSET_CANNONS_Y_POS=14,REG_X_OFFSET_PADDLE_MAGNETIC=0,REG_Y_OFFSET_PADDLE_MAGNETIC=460,SPAWN_BONUS_PROBABILITY;BRICKS_LEVEL_POSITION=[];SPAWN_BONUS_PROBABILITY=[];COLOR_TEXT_LEVEL=[];
BRICKS_LEVEL_POSITION[0]=[3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0];BRICKS_LEVEL_POSITION[1]=[1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1];
BRICKS_LEVEL_POSITION[2]=[1,1,1,1,1,-1,-1,0,0,0,0,-1,-1,-1,3,3,3,-1,-1,-1,-1,2,2,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,0,0,-1,-1,-1,-1,-1,3,3,3,-1,-1,-1,-1,2,2,2,2,-1,-1,-1,1,1,1,1,1,-1,-1,5,5,5,5,5,5,-1];BRICKS_LEVEL_POSITION[3]=[4,-1,-1,3,-1,-1,4,-1,-1,2,2,2,-1,-1,-1,1,1,1,1,1,-1,0,0,0,0,0,0,0,5,5,5,5,5,5,5,0,0,0,0,0,0,0,-1,1,1,1,1,1,1,-1,-1,2,2,2,-1,-1,4,-1,-1,3,-1,-1,4];
BRICKS_LEVEL_POSITION[4]=[4,4,-1,-1,-1,4,4,4,-1,-1,3,-1,-1,4,-1,-1,3,3,3,-1,-1,-1,3,3,3,3,3,-1,3,3,3,3,3,3,3,-1,5,5,5,5,5,-1,-1,5,5,5,5,5,-1,-1,5,2,5,2,5,-1,-1,5,5,5,5,5,-1,-1,5,5,1,5,5,-1,-1,5,5,1,5,5,-1,-1,0,0,0,0,0,-1];BRICKS_LEVEL_POSITION[5]=[1,-1,-1,3,-1,-1,1,1,-1,3,3,3,-1,1,1,3,3,3,3,3,1,1,-1,3,3,3,-1,1,1,1,0,0,0,1,1,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,-1,-1,-1,3,-1,-1,1,1,-1,1,1,-1,-1,2,2,2,2,2,-1,-1,4,4,4,4,4,-1];
BRICKS_LEVEL_POSITION[6]=[5,5,5,5,5,5,5,3,-1,-1,5,-1,-1,3,1,-1,-1,5,-1,-1,1,0,-1,-1,5,-1,-1,0,2,-1,-1,5,-1,-1,2,2,-1,-1,5,-1,-1,2,0,-1,-1,5,-1,-1,0,1,-1,-1,5,-1,-1,1,3,-1,-1,5,-1,-1,3,5,5,5,5,5,5,5,0,1,3,2,3,1,0,1,1,3,2,3,2,2,3,3,3,2,3,3,3];BRICKS_LEVEL_POSITION[7]=[3,3,3,-1,3,3,3,3,4,3,-1,3,4,3,3,3,3,-1,3,3,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,-1,-1,-1,-1,-1,0,0,0,-1,-1,-1,0,0,0,0,0,-1,-1,0,0,0,0,0,-1,-1,-1,0,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,1,-1,1,-1,-1,-1,1,-1,-1,-1,1,1,1,-1,-1];
BRICKS_LEVEL_POSITION[8]=[5,5,5,-1,5,5,5,5,2,5,-1,5,0,5,5,5,5,-1,5,5,5,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,5,5,5,-1,5,5,5,5,1,5,-1,5,3,5,5,5,5,-1,5,5,5,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,-1,4,-1,4,-1,4];BRICKS_LEVEL_POSITION[9]=[1,1,1,1,2,2,2,1,1,1,2,2,2,2,1,1,1,1,2,2,2,1,1,1,2,2,2,2,1,1,4,5,4,2,2,1,1,4,-1,4,2,2,3,3,4,-1,4,0,0,3,4,4,-1,4,4,0,3,4,4,-1,4,4,0,3,4,4,-1,4,4,0,4,4,4,-1,4,4,4,4,4,4,-1,4,4,4,4,4,4,-1,4,4,4];
BONUS_OCCURRENCE_PER_LEVEL=[[20,15,5,15,1,5,10,15,14,14],[15,3,10,15,2,10,15,20,15,7],[20,1,5,25,2,7,1,20,23,9],[20,1,10,20,4,5,1,20,23,10],[10,1,15,20,6,10,2,20,20,5],[5,1,15,20,6,10,5,15,27,10],[10,2,10,25,2,10,5,15,25,10],[18,3,15,10,2,5,4,10,20,25,9],[10,1,15,20,6,10,2,20,20,5],[23,1,10,7,1,2,7,20,20,23]];SPAWN_BONUS_PROBABILITY[0]=15;SPAWN_BONUS_PROBABILITY[1]=15;SPAWN_BONUS_PROBABILITY[2]=15;SPAWN_BONUS_PROBABILITY[3]=15;SPAWN_BONUS_PROBABILITY[4]=15;SPAWN_BONUS_PROBABILITY[5]=15;
SPAWN_BONUS_PROBABILITY[6]=15;SPAWN_BONUS_PROBABILITY[7]=15;SPAWN_BONUS_PROBABILITY[8]=10;SPAWN_BONUS_PROBABILITY[9]=10;COLOR_TEXT_LEVEL[0]="#00CA1B";COLOR_TEXT_LEVEL[1]="#EBD100";COLOR_TEXT_LEVEL[2]="#FF0013";COLOR_TEXT_LEVEL[3]="#00A1E0";var ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;TEXT_SCORE="SCORE";TEXT_SCORE_GAMEOVER="Total Score";TEXT_LEVEL="Level";TEXT_LEVEL_UPPERCASE="LEVEL";TEXT_COMPLETE="Complete";TEXT_CONGRATULATIONS="All levels completed... Congratulations!";TEXT_HELP_PAGE_1_PC="Move the paddle with your mouse to bounce the ball and destroy all the bricks! Grab any falling power-ups to get more points!";
TEXT_HELP_PAGE_1_MOBILE="Swipe the paddle to bounce the ball and destroy all the bricks! Grab any falling power-ups to get more points!";TEXT_DEVELOPED="DEVELOPED BY";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var c,m,a,e,d,g,b;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("time_bar_fill","./sprites/time_bar_fill.png");s_oSpriteLibrary.loadSprites();b=new createjs.Container;s_oStage.addChild(b)};this.unload=function(){b.removeAllChildren()};this.hide=function(){var b=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){b.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));b.addChild(l);l=s_oSpriteLibrary.getSprite("time_bar_fill");e=createBitmap(l);e.x=CANVAS_WIDTH/2-l.width/2;e.y=CANVAS_HEIGHT-140;b.addChild(e);c=l.width;m=l.height;d=new createjs.Shape;d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,1,m);b.addChild(d);e.mask=
d;a=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT-115;a.shadow=new createjs.Shadow("#000",2,2,2);a.textBaseline="alphabetic";a.textAlign="center";b.addChild(a);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;b.addChild(g)};this.refreshLoader=function(b){a.text=b+"%";d.graphics.clear();b=Math.floor(b*c/100);d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,b,m)};this._init()}
function CMain(c){var m,a=0,e=0,d=STATE_LOADING,g,b,l;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(b){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;b=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();m=!0};this.soundLoaded=function(){a++;b.refreshLoader(Math.floor(a/e*100));a===e&&this._onRemovePreloader()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/game_completed.ogg","game_completed"),createjs.Sound.registerSound("./sounds/ball_collision.ogg","boing"),createjs.Sound.registerSound("./sounds/ball_lose.ogg","ball_lose"),createjs.Sound.registerSound("./sounds/fireball.ogg","fireball"),createjs.Sound.registerSound("./sounds/brick_crack.ogg",
"brick_crack"),createjs.Sound.registerSound("./sounds/brick_explosion.ogg","brick_explosion"),createjs.Sound.registerSound("./sounds/brick_metal_collision.ogg","brick_metal"),createjs.Sound.registerSound("./sounds/power_up_bonus.ogg","power_up_bonus"),createjs.Sound.registerSound("./sounds/power_up_malus.ogg","power_up_malus"),createjs.Sound.registerSound("./sounds/stage_clear.ogg","stage_clear"),createjs.Sound.registerSound("./sounds/bullet.ogg","bullet"),createjs.Sound.registerSound("./sounds/but_press.ogg",
"click")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/game_completed.mp3","game_completed"),createjs.Sound.registerSound("./sounds/ball_collision.mp3","boing"),createjs.Sound.registerSound("./sounds/ball_lose.mp3","ball_lose"),createjs.Sound.registerSound("./sounds/fireball.mp3",
"fireball"),createjs.Sound.registerSound("./sounds/brick_crack.mp3","brick_crack"),createjs.Sound.registerSound("./sounds/brick_explosion.mp3","brick_explosion"),createjs.Sound.registerSound("./sounds/brick_metal_collision.mp3","brick_metal"),createjs.Sound.registerSound("./sounds/power_up_bonus.mp3","power_up_bonus"),createjs.Sound.registerSound("./sounds/power_up_malus.mp3","power_up_malus"),createjs.Sound.registerSound("./sounds/stage_clear.mp3","stage_clear"),createjs.Sound.registerSound("./sounds/bullet.mp3",
"bullet"),createjs.Sound.registerSound("./sounds/but_press.mp3","click")),e+=14)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_level_1","./sprites/bg_level_1.jpg");s_oSpriteLibrary.addSprite("paddle","./sprites/paddle.png");s_oSpriteLibrary.addSprite("paddle_magnet","./sprites/paddle_magnet.png");
s_oSpriteLibrary.addSprite("cannons","./sprites/cannons.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_pause","./sprites/but_pause.png");s_oSpriteLibrary.addSprite("icon_audio","./sprites/icon_audio.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_level",
"./sprites/but_level.png");s_oSpriteLibrary.addSprite("powerup_edge","./sprites/powerup_edge.png");s_oSpriteLibrary.addSprite("up_edges","./sprites/up_edges.png");s_oSpriteLibrary.addSprite("normal_ball","./sprites/normal_ball.png");s_oSpriteLibrary.addSprite("fire_ball","./sprites/fire_ball.png");s_oSpriteLibrary.addSprite("iron_ball","./sprites/iron_ball.png");s_oSpriteLibrary.addSprite("bullet","./sprites/bullet.png");s_oSpriteLibrary.addSprite("life","./sprites/life.png");s_oSpriteLibrary.addSprite("ctl_logo",
"./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");for(var b=0;b<TYPES_OF_BRICK;b++)s_oSpriteLibrary.addSprite("brick"+b,"./sprites/brick"+b+".png");for(b=0;b<TYPES_OF_BONUS;b++)s_oSpriteLibrary.addSprite("bonus"+b,"./sprites/bonus"+b+".png");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){a++;b.refreshLoader(Math.floor(a/e*100));
a===e&&this._onRemovePreloader()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._onRemovePreloader=function(){b.unload();isIOS()||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1}));this.gotoMenu()};this.gotoMenu=function(){new CMenu;d=STATE_MENU};this.gotoGame=function(b){l=new CGame(g,b);d=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoLevelMenu=function(){new CLevelMenu(g);d=STATE_MENU};
this.stopUpdate=function(){m=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();m=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=function(b){if(!1!==m){var h=(new Date).getTime();s_iTimeElaps=h-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=h;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=
0);d===STATE_GAME&&l.update();s_oStage.update(b)}};s_oMain=this;g=c;ENABLE_FULLSCREEN=c.fullscreen;ENABLE_CHECK_ORIENTATION=c.check_orientation;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iLevelReached=1,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null,s_oCanvas,s_iLanguageSelected,s_oSpriteSheetLora,s_aQuestions,s_bFullscreen=!1;
function CTextButton(c,m,a,e,d,g,b){var l,f,h,k,q;this._init=function(b,c,a,e,d,g,m){l=[];f=[];d=createBitmap(a);var p=Math.ceil(m/20);q=new createjs.Text(e,"bold "+m+"px "+PRIMARY_FONT,"#000000");q.textAlign="center";q.textBaseline="alphabetic";var n=q.getBounds();q.x=a.width/2+p;q.y=Math.floor(a.height/2)+n.height/3+p;k=new createjs.Text(e,"bold "+m+"px "+PRIMARY_FONT,g);k.textAlign="center";k.textBaseline="alphabetic";n=k.getBounds();k.x=a.width/2;k.y=Math.floor(a.height/2)+n.height/3;h=new createjs.Container;
h.x=b;h.y=c;h.regX=a.width/2;h.regY=a.height/2;h.addChild(d,q,k);s_bMobile||(h.cursor="pointer");s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown");h.off("pressup");s_oStage.removeChild(h)};this.setVisible=function(b){h.visible=b};this._initListener=function(){oParent=this;h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(b,h,a){l[b]=h;f[b]=a};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(f[ON_MOUSE_UP])};
this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN])};this.setTextPosition=function(b){k.y=b;q.y=b+2};this.setPosition=function(b,a){h.x=b;h.y=a};this.setX=function(b){h.x=b};this.setY=function(b){h.y=b};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(c,m,a,e,d,g,b);return this}
function CTextToggle(c,m,a,e,d,g,b,l,f){var h=1,k,q=!1,p,F,n,r,u,t;this._init=function(b,h,a,c,f,e,d,l,g){k=!1;p=[];F=[];t=createBitmap(a);var q=Math.ceil(d/20);u=new createjs.Text(c," "+d+"px "+f,"#000000");u.textAlign="center";u.textBaseline="alphabetic";var m=u.getBounds();u.x=a.width/2+q;u.y=Math.floor(a.height/2)+m.height/3+q-7;r=new createjs.Text(c," "+d+"px "+f,e);r.textAlign="center";r.textBaseline="alphabetic";m=r.getBounds();r.x=a.width/2;r.y=Math.floor(a.height/2)+m.height/3-7;n=new createjs.Container;
n.x=b;n.y=h;n.regX=a.width/2;n.regY=a.height/2;l||(b=new createjs.SpriteSheet({images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{state_true:[0],state_false:[1]}}),t=createSprite(b,"state_false",a.width/2/2,a.height/2,a.width/2,a.height),u.x=q,u.y=q+17,r.x=0,r.y=17,n.regX=0,n.regY=0);n.addChild(t,u,r);g.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown");n.off("pressup");f.removeChild(n)};this.setVisible=function(b){n.visible=b};
this._initListener=function(){oParent=this;n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(b,a,h){p[b]=a;F[b]=h};this.buttonRelease=function(){k||q||(n.scaleX=1*h,n.scaleY=1*h,p[ON_MOUSE_UP]&&p[ON_MOUSE_UP].call(F[ON_MOUSE_UP]))};this.buttonDown=function(){k||q||(n.scaleX=.9*h,n.scaleY=.9*h,p[ON_MOUSE_DOWN]&&p[ON_MOUSE_DOWN].call(F[ON_MOUSE_DOWN]))};this.enable=function(){k=!1;l||t.gotoAndStop("state_true")};this.disable=function(){k=!0;l||t.gotoAndStop("state_false")};
this.setTextPosition=function(a,h){var c=Math.ceil(b/20);u.x=a+c;u.y=h+c;r.x=a;r.y=h};this.setText=function(b){r.text=b;u.text=b};this.setPosition=function(b,a){n.x=b;n.y=a};this.setX=function(b){n.x=b};this.setY=function(b){n.y=b};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this.block=function(b){q=b};this.setScale=function(b){h=b;n.scaleX=b;n.scaleY=b};this.setScaleX=function(b){t.scaleX=b};this._init(c,m,a,e,d,g,b,l,f);return this}
function CToggle(c,m,a,e){var d,g,b,l=[],f;this._init=function(a,c,e,l){g=[];b=[];var h=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{state_true:[0],state_false:[1]}});d=l;f=createSprite(h,"state_"+d,e.width/2/2,e.height/2,e.width/2,e.height);f.mouseEnabled=!0;f.x=a;f.y=c;f.stop();s_bMobile||(f.cursor="pointer");s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",
this.buttonRelease);f.mouseEnabled=!1;s_oStage.removeChild(f)};this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,e){g[a]=c;b[a]=e};this.addEventListenerWithParams=function(a,c,e,f){g[a]=c;b[a]=e;l=f};this.setActive=function(b){d=b;f.gotoAndStop("state_"+d)};this.buttonRelease=function(){f.scaleX=1;f.scaleY=1;playSound("click",1,0);d=!d;f.gotoAndStop("state_"+d);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(b[ON_MOUSE_UP],l)};
this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(b[ON_MOUSE_DOWN],l)};this.setPosition=function(b,a){f.x=b;f.y=a};this.setVisible=function(b){f.visible=b};this._init(c,m,a,e)}
function CNumToggle(c,m,a,e){var d,g,b,l,f,h,k,q=[];this._init=function(a,c,e,q){g=!1;b=[];l=[];f=new createjs.Container;f.x=a;f.y=c;q.addChild(f);a=s_oSpriteLibrary.getSprite("num_button");c={images:[a],framerate:5,frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{state_true:[0],state_false:[1]}};c=new createjs.SpriteSheet(c);d=!1;h=createSprite(c,"state_"+d,a.width/2/2,a.height/2,a.width/2,a.height);h.stop();a=s_oSpriteLibrary.getSprite("ball");c={images:[a],
frames:{width:a.width/NUM_DIFFERENT_BALLS,height:a.height,regX:a.width/NUM_DIFFERENT_BALLS/2,regY:a.height/2},animations:{red:[0],green:[1],cyan:[0],violet:[1],blue:[1]}};c=new createjs.SpriteSheet(c);k=createSprite(c,"red",a.width/NUM_DIFFERENT_BALLS/2,a.height/2,a.width/NUM_DIFFERENT_BALLS,a.height);k.gotoAndStop(0);k.visible=!1;s_bMobile||(f.cursor="pointer");f.addChild(h,k);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);e.removeChild(f)};
this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,h){b[a]=c;l[a]=h};this.addEventListenerWithParams=function(a,c,h,e){b[a]=c;l[a]=h;q=e};this.setActive=function(b){d=b;h.gotoAndStop("state_"+d)};this.buttonRelease=function(){g||(playSound("click",1,0),d=!d,h.gotoAndStop("state_"+d),b[ON_MOUSE_UP]&&b[ON_MOUSE_UP].call(l[ON_MOUSE_UP],q))};this.buttonDown=function(){g||b[ON_MOUSE_DOWN]&&b[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],
q)};this.setPosition=function(b,a){f.x=b;f.y=a};this.getGlobalPosition=function(){return{x:f.localToGlobal(0,0).x,y:f.localToGlobal(0,0).y}};this.block=function(b){g=b};this.setExtracted=function(b,a){k.visible=b;k.gotoAndStop(a)};this.highlight=function(){h.gotoAndPlay(0)};this.stopHighlight=function(){h.gotoAndStop(1)};this._init(c,m,a,e)}
function CGfxButton(c,m,a){var e,d,g,b=[],l,f;this._init=function(b,a,c){e=1;d=[];g=[];l=createBitmap(c);l.x=b;l.y=a;l.regX=c.width/2;l.regY=c.height/2;s_bMobile||(l.cursor="pointer");s_oStage.addChild(l);f=!1;this._initListener()};this.unload=function(){l.off("mousedown",this.buttonDown);l.off("pressup",this.buttonRelease);s_oStage.removeChild(l)};this.setVisible=function(b){l.visible=b};this._initListener=function(){l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=
function(b,a,c){d[b]=a;g[b]=c};this.addEventListenerWithParams=function(a,c,e,f){d[a]=c;g[a]=e;b=f};this.buttonRelease=function(){f||(l.scaleX=e,l.scaleY=e,d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(g[ON_MOUSE_UP],b))};this.buttonDown=function(){f||(l.scaleX=.9*e,l.scaleY=.9*e,d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],b))};this.setScale=function(b){e=b;l.scaleX=b;l.scaleY=b};this.setPosition=function(b,a){l.x=b;l.y=a};this.setX=function(b){l.x=b};this.setY=function(b){l.y=b};this.getButtonImage=
function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this.block=function(b){f=b};this._init(c,m,a);return this}
function CMenu(){var c,m,a,e,d,g,b,l,f,h,k,q,p=null,F=null;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(b);var n=s_oSpriteLibrary.getSprite("but_play");l=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+250,n);l.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n=s_oSpriteLibrary.getSprite("icon_audio"),d=CANVAS_WIDTH-n.width/2+15,g=n.height/2+20,h=new CToggle(d,g,n,s_bAudioActive),h.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);n=s_oSpriteLibrary.getSprite("but_credits");a=n.width/2+20;e=n.height/2+20;k=new CGfxButton(a,e,n,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onCreditsBut,this);var n=window.document,r=n.documentElement;p=r.requestFullscreen||r.mozRequestFullScreen||r.webkitRequestFullScreen||r.msRequestFullscreen;F=n.exitFullscreen||n.mozCancelFullScreen||n.webkitExitFullscreen||n.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(p=!1);p&&!1===inIframe()&&(n=s_oSpriteLibrary.getSprite("but_fullscreen"),
c=a+n.width/2+10,m=e,q=new CToggle(c,m,n,s_bFullscreen,!0),q.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(f);createjs.Tween.get(f).to({alpha:0},1E3).call(function(){s_oStage.removeChild(f)});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){l.unload();l=null;s_oStage.removeChild(b);b=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h.unload(),h=null;p&&
!1===inIframe()&&q.unload();k.unload();s_oMenu=null};this.refreshButtonPos=function(b,f){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||h.setPosition(d-b,g+f);p&&!1===inIframe()&&q.setPosition(c+b,m+f);k.setPosition(a+b,e+f)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();if(isIOS()&&null===s_oSoundTrack){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1})}else playSound("click",
1,0);s_oMain.gotoLevelMenu()};this._onCreditsBut=function(){new CCreditsPanel};this._onFullscreenRelease=function(){s_bFullscreen?(F.call(window.document),s_bFullscreen=!1):(p.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(c,m){var a,e,d,g,b,l,f,h,k={},q,p,F=0,n,r,u,t,z,v,G,N,D,A,I,X,B,w,y,S,aa,T,Q,Aa,fa,E,U,ga,ba,pa,qa,ra,V,Y,ka,O,K,P,J,W,R,la,L,ca,C,ma,da,ha,M,Ba,Ca,Da,Ea,sa,ia,ja,ta,ua,va,wa,xa,x,Z,na,ea,oa;this._init=function(){g=!1;var c=s_oSpriteLibrary.getSprite("normal_ball");U=0;G=CANVAS_WIDTH/2;b=[];l=[];E=[];ga=SPACE_BETWEEN_BRICKS;I=p=0;var f=s_oSpriteLibrary.getSprite("brick0");N=f.width/2;D=f.height/2;M=1;q=c.height/2+OFFSET_RADIUS_BALL;d=m;ea=C=0;ma=MAX_TIME_SHOT_BONUS;ca=LIFE;Aa=new CSettingsLevel;
t=[];u=[];r=[];n=[];z=[];v=[];this.createPadding(CANVAS_WIDTH/2);Y=R=W=J=P=K=O=!1;oa=V=0;f=OFFSETEDGELEFT+q;Ba=CANVAS_WIDTH+(-OFFSETEDGERIGHT-q);Ca=f;a=createBitmap(s_oSpriteLibrary.getSprite("bg_level_1"));s_oStage.addChild(a);a.addEventListener("click",this.launchBall);s_oStage.setChildIndex(a,0);fa=[];w=D+q+OFFSET_HEIGHT_BRICK;y=N+q+OFFSET_WIDTH_BRICK;S=w+OFFSET_Y_BRICK;aa=y+OFFSET_X_BRICK;Q=EDGE_OFFSET+k.x;T=CANVAS_WIDTH-EDGE_OFFSET-k.x;Q=EDGE_OFFSET+k.x;Da=2*D+OFFSET_BRICK_Y_POS;Ea=2*N;sa=OFFSET_BRICK_SECTION_X+
OFFSET_DETECTION_BRICK_SECTION_X;ka=TIME_REFLECT_IRON_BRICK;e=new CInterface;this.createABall(0,h.x,h.y-q-k.y,c,!0);this.createLevel();1>d?e.help(d):e.showNumLevel(d+1);e.numLevel(d);ha=!0;ba=!1;da=0;setVolume(s_oSoundTrack,.3)};this.launchBall=function(){!1===ba&&!1===g?(h.x>G?(h.x-=G,Z=-(h.x/G)):Z=h.x/G,b[0].setPosition(null,b[0].getY()-3),b[0].setDirection(Z,-1),b[0].setInfoData("OnPad",!1),ba=!0):!0===J&&s_oGame.launchUnmagneticBall()};this.createLevel=function(){this.setLevelBrick();$(s_oMain).trigger("start_level",
d);fa=Aa.createBonusOccurance(d)};this.createABall=function(a,c,e,f,h,d,l){b[a]=new CBall(c,e,f,d,l,M,K,q);b[a].setInfoData("ID",a);b[a].setInfoData("OnPad",h);b[a].setInfoData("Collision",0);b[a].changeRotation();!0===P&&b[a].downFloor(!0);!0===h&&(ba=!1)};this.generateABonus=function(b,a){var c=Math.floor(Math.random()*fa.length),H=s_oSpriteLibrary.getSprite("bonus"+fa[c]);E.push(new CBonus(b,a,H,fa[c]));E[U].setInfoData("ID",U);U++};this.createPadding=function(b){h&&s_oStage.removeChild();var a=
s_oSpriteLibrary.getSprite("paddle"),c=new createjs.SpriteSheet({images:[a],frames:{width:a.width/7,height:a.height/2,regX:a.width/2/7,regY:a.height/2/7},animations:{small:{frames:[0]},normal:{frames:[6]},big:{frames:[12]},StoN:{frames:[1,2,3,4,5,6]},NtoB:{frames:[7,8,9,10,11,12]},BtoN:{frames:[11,10,9,8,7,6]},NtoS:{frames:[5,4,3,2,1,0]}}});h=createSprite(c,"normal",a.width/2/7,a.height/2/2,a.width/7,a.height/2);h.x=b;h.y=HEIGHT_OF_PADDLE;s_oStage.addChild(h);s_oStage.setChildIndex(h,3);k={x:PADDLE_DIMENSION[1]/
2,y:a.height/2/2-OFFSET_PAD_Y}};this.setLevelBrick=function(){var b=BRICKS_LEVEL_POSITION[d],a=0,c=0;X=b.length/MAX_BRICK_FOR_ROW;for(var e=0;e<X;e++)for(var f=0;f<MAX_BRICK_FOR_ROW;f++){if(-1!==b[a]){var h=s_oSpriteLibrary.getSprite("brick"+b[a]);l[c]=new CBrick(CANVAS_WIDTH/2-250-ga+(Ea+ga)*f,CANVAS_HEIGHT/2-310+(Da+ga)*e,h,BRICKS_RESISTANCE[b[a]],BRICKS_DESTRUCTIBLE[b[a]]);l[c].setInfoData("resistance",BRICKS_RESISTANCE[b[a]]);l[c].setInfoData("score",BRICKS_SCORE[b[a]]);l[c].setInfoData("destructible",
BRICKS_DESTRUCTIBLE[b[a]]);l[c].setChildIndex(4);!0===BRICKS_DESTRUCTIBLE[b[a]]&&I++;c++}a++}p=l[c-1].getY()+OFFSET_DIAGRAM_CHECK+D;this.createBricksSections()};this.loseBall=function(a){this.unloadBall(a);1>b.length&&(ca--,e.refreshBallLife(ca),!0===O?this.deactiveLargePad():!0===R&&this.deactiveSmallPad(),!0===W?V=0:!0===J&&this.deactiveMagnetic(),!0===P&&this.deactiveFloor(),!0===K&&this.stopFireSound(),J=P=K=O=!1,M=1,this.checkOtherActiveBonus(),0<ca?(ba=!1,a=s_oSpriteLibrary.getSprite("normal_ball"),
this.createABall(0,h.x,h.y-q-k.y,a,!0)):e.gameOver(C));playSound("ball_lose",1,0,void 0)};this.setPause=function(b){g=b};this.createBricksSections=function(){var b=0,a=0,c=0,e=0,f=0,h=0;A=1===X%2?l[Math.floor(l.length/2)].getY()+2*D+OFFSET_CENTER_Y_DIAGRAM:l[Math.floor(l.length/2)].getY()-D+OFFSET_CENTER_Y_DIAGRAM;B=G+w+Math.floor(ga/2)+OFFSET_CENTER_X_DIAGRAM;ia=B+sa;ja=B-sa;ta=B+OFFSET_BRICK_SECTION_X;ua=B-OFFSET_BRICK_SECTION_X;va=A+OFFSET_BRICK_SECTION_Y;wa=A+OFFSET_DETECTION_BRICK_SECTION_Y;
xa=A-OFFSET_DETECTION_BRICK_SECTION_Y;for(var d=0;d<l.length;d++)if(l[d].getX()<=B-OFFSET_BRICK_SECTION_X&&l[d].getY()<A-OFFSET_BRICK_SECTION_Y)r[a]=l[d],a++;else if(l[d].getX()>=B+OFFSET_BRICK_SECTION_X&&l[d].getY()<A-OFFSET_BRICK_SECTION_Y)n[b]=l[d],b++;else if(l[d].getX()<=B-OFFSET_BRICK_SECTION_X&&l[d].getY()>A+OFFSET_BRICK_SECTION_Y)t[e]=l[d],e++;else if(l[d].getX()>=B+OFFSET_BRICK_SECTION_X&&l[d].getY()>A+OFFSET_BRICK_SECTION_Y)u[c]=l[d],c++;else if(l[d].getX()<=B+OFFSET_BRICK_SECTION_X&&l[d].getX()>=
B-OFFSET_BRICK_SECTION_X)z[f]=l[d],f++;else if(l[d].getY()<=A+OFFSET_BRICK_SECTION_Y&&l[d].getY()>=A-OFFSET_BRICK_SECTION_Y&&l[d]&&l[d].getX()>=B+OFFSET_BRICK_SECTION_X||l[d].getX()<=B-OFFSET_BRICK_SECTION_X)v[h]=l[d],h++};this.onExit=function(){s_oGame.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_level",d);$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");setVolume(s_oSoundTrack,1)};this.bonusLargePad=function(){C+=BONUS_SCORE.s0;e.refreshScore(C);!0===R?this.deactiveSmallPad():
(!0===J?this.deactiveMagnetic():x&&(V=0,x.gotoAndPlay("go"),x.on("animationend",function(){s_oStage.removeChild(x);x=null})),this.audioPowerUpBonus(),O||(k.x=PADDLE_DIMENSION[2]/2,h.gotoAndPlay("NtoB"),h.on("animationend",function(){h.gotoAndStop("big")}),O=!0,T=CANVAS_WIDTH-EDGE_OFFSET-k.x,Q=EDGE_OFFSET+k.x))};this.bonusSmallPad=function(){C+=BONUS_SCORE.s9;e.refreshScore(C);this.audioPowerUpMalus();!0===O?this.deactiveLargePad():(!0===J?this.deactiveMagnetic():x&&(V=0,x.gotoAndPlay("go"),x.on("animationend",
function(){s_oStage.removeChild(x);x=null})),R||(k.x=PADDLE_DIMENSION[0]/2,h.gotoAndPlay("NtoS"),h.on("animationend",function(){h.gotoAndStop("small")}),R=!0,T=CANVAS_WIDTH-EDGE_OFFSET-k.x,Q=EDGE_OFFSET+k.x))};this.bonusMultiBall=function(){C+=BONUS_SCORE.s5;e.refreshScore(C);if(!(b.length>=MAX_BALL_SPAWN)){this.audioPowerUpBonus();var a,c=0,d;a=b.length+BONUS_MULTI_BALL;var f=b.length;d=!1===K&&!1===J?s_oSpriteLibrary.getSprite("normal_ball"):!0===K?s_oSpriteLibrary.getSprite("fire_ball"):s_oSpriteLibrary.getSprite("iron_ball");
for(var h=f;h<f+a;h++)0===c%2?this.createABall(h,b[c].getX(),b[c].getY(),d,!1,1,-1):this.createABall(h,b[c].getX(),b[c].getY(),d,!1,-1,1),c++}};this.bonusFireBall=function(){C+=BONUS_SCORE.s1;e.refreshScore(C);pa=BONUS_TIME.t1;if(!0!==K){for(var a=s_oSpriteLibrary.getSprite("fire_ball"),c=0;c<b.length;c++)b[c].changeSprite(a,"fire");K=!0;!0===J&&(s_oStage.removeChild(h),this.createPadding(h.x),this.launchUnmagneticBall(),J=!1);Y=!0;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile&&null===na)na=createjs.Sound.play("fireball",
{loop:-1});this.audioPowerUpBonus()}};this.createFloor=function(){var b=s_oSpriteLibrary.getSprite("powerup_edge");L=createBitmap(b);L.x=G;L.y=CANVAS_HEIGHT+b.height/2;L.regX=b.width/2;L.regY=b.height/2;s_oStage.addChild(L);s_oStage.setChildIndex(L,s_oStage.numChildren-1);createjs.Tween.get(L).to({y:940},800,createjs.Ease.backOut)};this.bonusMagnetic=function(){C+=BONUS_SCORE.s3;e.refreshScore(C);ra=BONUS_TIME.t3;this.audioPowerUpBonus();if(!0!==J){for(var a=s_oSpriteLibrary.getSprite("iron_ball"),
c=0;c<b.length;c++)b[c].changeSprite(a,"magnetic");!0===O?(h.gotoAndPlay("BtoN"),h.on("animationend",function(){s_oStage.removeChild(h);s_oGame.createMagneticPad(h.x)}),O=!1):!0===R?(h.gotoAndPlay("StoN"),h.on("animationend",function(){s_oStage.removeChild(h);s_oGame.createMagneticPad(h.x)}),R=!1):x?(V=0,x.gotoAndPlay("go"),x.on("animationend",function(){s_oStage.removeChild(x);x=null;s_oStage.removeChild(h);s_oGame.createMagneticPad(h.x)})):this.createMagneticPad(h.x);!0===K&&(K=!1,this.stopFireSound());
Y=J=!0}};this.createMagneticPad=function(b){s_oStage.removeChild(h);var a=s_oSpriteLibrary.getSprite("paddle_magnet"),c=new createjs.SpriteSheet({images:[a],frames:{width:a.width/5,height:a.height/2,regX:(a.width+REG_X_OFFSET_PADDLE_MAGNETIC)/2/5,regY:(a.height+REG_Y_OFFSET_PADDLE_MAGNETIC)/2/7},animations:{magnetic:[0,9,"magnetic",.5]}});h=createSprite(c,"magnetic",(a.width+REG_X_OFFSET_PADDLE_MAGNETIC)/2/5,(a.height+REG_Y_OFFSET_PADDLE_MAGNETIC)/2/2,a.width/5,a.height/2);h.x=b;h.y=HEIGHT_OF_PADDLE;
s_oStage.addChild(h);k.x=PADDLE_DIMENSION[1]/2;T=CANVAS_WIDTH-EDGE_OFFSET-k.x;Q=EDGE_OFFSET+k.x};this.bonusLife=function(){C+=BONUS_SCORE.s4;e.refreshScore(C);e.refreshBallLife(ca);ca++;this.audioPowerUpBonus()};this.bonusSlowBall=function(){C+=BONUS_SCORE.s7;e.refreshScore(C);for(var a=0;a<b.length;a++)b[a].setVelocityRate(M);1>M?this.audioPowerUpMalus():this.audioPowerUpBonus();M>MIN_VELOCITY_LIMIT&&(M-=SPEED_DOWN_BALL);M<MIN_VELOCITY_LIMIT&&(M=MIN_VELOCITY_LIMIT)};this.bonusFastBall=function(){C+=
BONUS_SCORE.s8;e.refreshScore(C);if(M<MAX_VELOCITY_LIMIT){M+=SPEED_UP_BALL;for(var a=0;a<b.length;a++)b[a].setVelocityRate(M);1<M?this.audioPowerUpMalus():this.audioPowerUpBonus()}};this.bonusShot=function(){C+=BONUS_SCORE.s6;e.refreshScore(C);this.audioPowerUpBonus();V=BONUS_TIME.t6;!1===W&&(W=!0,la=s_oSpriteLibrary.getSprite("bullet"),f=[],!0===O?(h.gotoAndPlay("BtoN"),h.on("animationend",function(){h.gotoAndStop("normal")}),O=!1):!0===R?(h.gotoAndPlay("StoN"),h.on("animationend",function(){h.gotoAndStop("normal")}),
R=!1):!0===J&&this.deactiveMagnetic(),x?(x.gotoAndPlay("come"),x.on("animationend",function(){x.gotoAndStop(5)})):this.createCannons());Y=!0};this.bonusFloor=function(){C+=BONUS_SCORE.s2;e.refreshScore(C);qa=BONUS_TIME.t2;if(!0!==P){L||this.createFloor();for(var a=0;a<b.length;a++)b[a].downFloor(!0)}Y=P=!0;this.audioPowerUpBonus()};this.createCannons=function(){var a=s_oSpriteLibrary.getSprite("cannons"),b=new createjs.SpriteSheet({images:[a],frames:{width:a.width/3,height:a.height/2,regX:a.width/
2/3,regY:a.height/2/2},animations:{come:{frames:[0,1,2,3,4,5],speed:.5},go:{frames:[5,4,3,2,1,0],speed:.5}}});x=createSprite(b,"come",a.width/2/3,a.height/2/2,a.width/3,a.height/2);x.x=h.x;x.y=h.y+OFFSET_CANNONS_Y_POS;s_oStage.addChild(x);x.on("animationend",function(){x.gotoAndStop(5)});s_oStage.setChildIndex(x,5);k.x=(PADDLE_DIMENSION[1]+OFFSET_DIM_X_CANNONS)/2;T=CANVAS_WIDTH-EDGE_OFFSET-k.x;Q=EDGE_OFFSET+k.x};this.launchUnmagneticBall=function(){for(var a=0;a<b.length;a++)if(!0===b[a].getInfoData("OnPad")){var c=
b[a].getInfoData("Collision")/k.x,c=Math.sin(c);b[a].setPosition(null,b[a].getY()-2);b[a].changeDirection(-c,-1,!1,"launch");b[a].setInfoData("OnPad",!1);b[a].changeRotation()}};this.unload=function(){e.unload();for(var a=0;a<b.length;a++)b[a].unload();for(a=0;a<E.length;a++)E[a].unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.__updatePhysics=function(a){var c=1/createjs.Ticker.framerate/ya;h.x=s_oStage.mouseX;h.x<Q&&(h.x=Q);h.x>T&&(h.x=T);x&&(x.x=h.x);for(var d=0;d<b.length;d++)if(!1===
b[d].getInfoData("OnPad")){var f=b[d].getX(),e=b[d].getY();b[d].update(a);if(f>h.x-k.x&&f<h.x+k.x&&e>h.y-k.y-q&&e<h.y+k.y+q){if(!1===J){if(0===Z){var g=h.x-f,g=g/k.x;b[d].setPosition(null,e-1);Z=Math.sin(g);b[d].changeDirection(-Z,-1,!0);b[d].changeRotation()}Z=0}else{g=h.x-b[d].getX();b[d].setInfoData("Collision",g);!1===b[d].getInfoData("OnPad")&&(b[d].setPosition(null,h.y-k.y-q),b[d].setInfoData("OnPad",!0));break}this.audioBoing()}if(e<p){if(f<ia&&e>va)for(g=0;g<t.length;g++){if(f>t[g].getX()-
y&&f<t[g].getX()+y&&e>t[g].getY()-w&&e<t[g].getY()+w){var H=t[g].getX(),m=t[g].getY();this.gestureBricks(t,g,H,m);this.ballBounce(d,f,e,H,m);break}}else if(f>ja&&e>va)for(g=0;g<u.length;g++){if(f>u[g].getX()-y&&f<u[g].getX()+y&&e>u[g].getY()-w&&e<u[g].getY()+w){H=u[g].getX();m=u[g].getY();this.gestureBricks(u,g,H,m);this.ballBounce(d,f,e,H,m);break}}else if(f<ia&&e<A)for(g=0;g<r.length;g++)f>r[g].getX()-y&&f<r[g].getX()+y&&e>r[g].getY()-w&&e<r[g].getY()+w&&(H=r[g].getX(),m=r[g].getY(),this.gestureBricks(r,
g,H,m),this.ballBounce(d,f,e,H,m));else if(f>ja&&e<A)for(g=0;g<n.length;g++)if(f>n[g].getX()-y&&f<n[g].getX()+y&&e>n[g].getY()-w&&e<n[g].getY()+w){H=n[g].getX();m=n[g].getY();this.gestureBricks(n,g,H,m);this.ballBounce(d,f,e,H,m);break}if(f>ua&&f<ta)for(g=0;g<z.length;g++)if(f>z[g].getX()-y&&f<z[g].getX()+y&&e>z[g].getY()-w&&e<z[g].getY()+w){H=z[g].getX();m=z[g].getY();this.gestureBricks(z,g,H,m);this.ballBounce(d,f,e,H,m);break}if(e<wa&&e>xa)for(g=0;g<v.length;g++)if(f>v[g].getX()-y&&f<v[g].getX()+
y&&e>v[g].getY()-w&&e<v[g].getY()+w){H=v[g].getX();m=v[g].getY();this.gestureBricks(v,g,H,m);this.ballBounce(d,f,e,H,m);break}}}else b[d].setPosition(h.x-b[d].getInfoData("Collision"),null),b[d].getX()>Ba?b[d].setInfoData("Collision",b[d].getInfoData("Collision")+1):b[d].getX()<Ca&&b[d].setInfoData("Collision",b[d].getInfoData("Collision")-1);this.timeBonus(c);if(0<ka)ka-=c;else for(d=0;d<l.length;d++)!1===l[d].getInfoData("destructible")&&(l[d].reflectBrick(),l[d].setInfoData("Reflect",!0)),ka=TIME_REFLECT_IRON_BRICK;
0<ea&&(ea-=c);0!==U&&this.bonusGesture()};this.allBrickDestroyed=function(){0<I||(this.setPause(!0),e.levelComplete(d,C),oa++,oa===NUM_LEVELS_FOR_ADS&&(oa=0,$(s_oMain).trigger("show_interlevel_ad")),$(s_oMain).trigger("end_level",d),s_iLevelReached<d+2&&(s_iLevelReached=d+2),!0===K&&this.stopFireSound())};this.stopFireSound=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)na.destroy(),na=null};this.timeBonus=function(a){!0===Y&&(!0===K?0<pa?pa-=a:(this.deactiveFireBall(),this.checkOtherActiveBonus()):
!0===J&&(0<ra?ra-=a:(this.deactiveMagnetic(),this.checkOtherActiveBonus())),!0===P&&(0<qa?qa-=a:(this.deactiveFloor(),this.checkOtherActiveBonus())),!0===W&&(0<V&&(V-=a,--ma,0>ma&&(!0===ha?(f.push(new CBullet(h.x-k.x,h.y-k.y,la)),ha=!1):(f.push(new CBullet(h.x+k.x,h.y-k.y,la)),ha=!0),f[da].setIndex(da),ma=MAX_TIME_SHOT_BONUS,da++,this.audioBullet())),1>f.length&&.1>V?(this.deactiveShot(),this.checkOtherActiveBonus()):this.detectiveCollisionBullet()))};this.nextLevel=function(){this.unloadLevel();
d++;this.createLevel();var a=s_oSpriteLibrary.getSprite("normal_ball");M=1;this.createABall(0,h.x,h.y-q-k.y,a,!0);ha=!0;ba=!1;da=0;e.showNumLevel(d+1);e.numLevel(d)};this.audioBrickExplosion=function(){playSound("brick_explosion",1,0)};this.audioPowerUpBonus=function(){playSound("power_up_bonus",1,0)};this.audioPowerUpMalus=function(){playSound("power_up_malus",1,0)};this.audioBrickMetal=function(){playSound("brick_metal",1,0)};this.audioBullet=function(){playSound("bullet",1,0)};this.audioBoing=
function(){playSound("boing",1,0)};this.ballBounce=function(a,c,d,f,e){!0===K||0<ea||(c>f+aa||c<f-aa&&d>e-S&&d<e+S?(c>f?(b[a].changeDirection(-1,1,!1,"side"),b[a].setPosition(b[a].getX()+3,null)):(b[a].changeDirection(-1,1,!1,"side"),b[a].setPosition(b[a].getX()-3,null)),ea=TIME_BOUNCE_BALL):c>f-y&&c<f+y&&d>e-w&&d<e+w&&(d>e?(b[a].changeDirection(1,1,!1,"base"),b[a].setPosition(null,b[a].getY()+3)):(b[a].changeDirection(1,-1,!1,"base"),b[a].setPosition(null,b[a].getY()-3)),ea=TIME_BOUNCE_BALL,b[a].changeRotation()),
this.audioBoing())};this.gestureBricks=function(a,b,c,d){!0===a[b].getInfoData("destructible")||!0===K?0===a[b].getInfoData("resistance")?(C+=a[b].getInfoData("score"),e.refreshScore(C),!0===a[b].getInfoData("destructible")&&(I--,this.allBrickDestroyed()),!1===a[b].getInfoData("Effect")?a[b].unload():(a[b].animBrick("destroyed"),this.audioBrickExplosion()),this.randomBonus(c,d),a.splice(b,1)):(a[b].setInfoData("resistance",a[b].getInfoData("resistance")-1),a[b].damageBrick(a[b].getInfoData("resistance")),
playSound("brick_crack",1,0,void 0)):(a[b].reflectBrick(),a[b].setInfoData("Reflect",!0),this.audioBrickMetal())};this.detectiveCollisionBullet=function(){for(var a=0;a<f.length;a++){var b=f[a].getX(),c=f[a].getY();f[a].update();if(c<p){if(b<ia&&c>A)for(var d=0;d<t.length;d++){if(b>t[d].getX()-y&&b<t[d].getX()+y&&c>t[d].getY()-w&&c<t[d].getY()+w){var e=t[d].getX(),g=t[d].getY();this.gestureBricks(t,d,e,g);this.unloadBullet(f[a].getIndex());break}}else if(b>ja&&c>A)for(d=0;d<u.length;d++){if(b>u[d].getX()-
y&&b<u[d].getX()+y&&c>u[d].getY()-w&&c<u[d].getY()+w){e=u[d].getX();g=u[d].getY();this.gestureBricks(u,d,e,g);this.unloadBullet(f[a].getIndex());break}}else if(b<ia&&c<A)for(d=0;d<r.length;d++)b>r[d].getX()-y&&b<r[d].getX()+y&&c>r[d].getY()-w&&c<r[d].getY()+w&&(e=r[d].getX(),g=r[d].getY(),this.gestureBricks(r,d,e,g),this.unloadBullet(f[a].getIndex()));else if(b>ja&&c<A)for(d=0;d<n.length;d++)if(b>n[d].getX()-y&&b<n[d].getX()+y&&c>n[d].getY()-w&&c<n[d].getY()+w){e=n[d].getX();g=n[d].getY();this.gestureBricks(n,
d,e,g);this.unloadBullet(f[a].getIndex());break}if(b>ua&&b<ta)for(d=0;d<z.length;d++)if(b>z[d].getX()-y&&b<z[d].getX()+y&&c>z[d].getY()-w&&c<z[d].getY()+w){e=z[d].getX();g=z[d].getY();this.gestureBricks(z,d,e,g);this.unloadBullet(f[a].getIndex());break}if(c<wa&&c>xa)for(d=0;d<v.length;d++)if(b>v[d].getX()-y&&b<v[d].getX()+y&&c>v[d].getY()-w&&c<v[d].getY()+w){e=v[d].getX();g=v[d].getY();this.gestureBricks(v,d,e,g);this.unloadBullet(f[a].getIndex());break}}}};this.deactiveFireBall=function(){for(var a=
s_oSpriteLibrary.getSprite("normal_ball"),d=0;d<b.length;d++)b[d].changeSprite(a,"normal");K=!1;this.stopFireSound()};this.deactiveLargePad=function(){h.gotoAndPlay("BtoN");h.on("animationend",function(){h.gotoAndStop("normal")});k.x=PADDLE_DIMENSION[1]/2;T=CANVAS_WIDTH-102-k.x;Q=102+k.x;O=!1};this.deactiveSmallPad=function(){h.gotoAndPlay("StoN");h.on("animationend",function(){h.gotoAndStop("normal")});k.x=PADDLE_DIMENSION[1]/2;T=CANVAS_WIDTH-102-k.x;Q=102+k.x;R=!1};this.deactiveFloor=function(){var a=
s_oSpriteLibrary.getSprite("powerup_edge");createjs.Tween.get(L).to({y:CANVAS_HEIGHT+a.height/2},800,createjs.Ease.backIn).call(function(){!1===P?(s_oStage.removeChild(L),L=null):createjs.Tween.get(L).to({y:940},800,createjs.Ease.backOut)});for(a=0;a<b.length;a++)b[a].downFloor(!1);P=!1};this.deactiveMagnetic=function(){for(var a=s_oSpriteLibrary.getSprite("normal_ball"),d=0;d<b.length;d++)b[d].changeSprite(a,"normal");s_oStage.removeChild(h);this.createPadding(h.x);this.launchUnmagneticBall();J=
!1};this.deactiveShot=function(){la=null;W=!1;x&&(x.gotoAndPlay("go"),x.on("animationend",function(){!1===W&&(s_oStage.removeChild(x),x=null)}));k.x=PADDLE_DIMENSION[1]/2;T=CANVAS_WIDTH-EDGE_OFFSET-k.x;Q=EDGE_OFFSET+k.x};this.checkOtherActiveBonus=function(){!1===K&&!0===P&&!1===J&&!1===W&&(Y=!1)};this.bonusGesture=function(){for(var a=0;a<U;a++)if(E[a].update(),void 0!==E[a]&&E[a].getX()>h.x-k.x-E[a].getInfoData("offsetX")&&E[a].getX()<h.x+k.x+E[a].getInfoData("offsetX")&&E[a].getY()>h.y-k.y-E[a].getInfoData("offsetY")&&
E[a].getY()<h.y+k.y+E[a].getInfoData("offsetY")){switch(E[a].getInfoData("Type")){case 0:this.bonusLargePad();break;case 1:this.bonusFireBall();break;case 2:this.bonusFloor();break;case 3:this.bonusMagnetic();break;case 4:this.bonusLife();break;case 5:this.bonusMultiBall();break;case 6:this.bonusShot();break;case 7:this.bonusSlowBall();break;case 8:this.bonusFastBall();break;case 9:this.bonusSmallPad()}this.unloadBonus(a);break}};this.unloadBonus=function(a){E[a].unload();E.splice(a,1);0<U&&U--;for(a=
0;a<U;a++)E[a].resetTheIndex(a)};this.unloadBall=function(a){b[a].unload();b.splice(a,1);for(a=0;a<b.length;a++)b[a].resetTheIndex(a)};this.unloadBullet=function(a){f[a].unload();f.splice(a,1);da--;for(a=0;a<f.length;a++)f[a].setIndex(a)};this.randomBonus=function(a,b){Math.floor(100*Math.random())<SPAWN_BONUS_PROBABILITY[d]&&0<I&&this.generateABonus(a,b)};this.unloadLevel=function(){for(var a=0;a<b.length;a++)b[a].unload(),b[a]=null;for(a=0;a<E.length;a++)E[a].unload(),E[a]=null;if(void 0!==f)for(a=
0;a<f.length;a++)f[a].unload(),f[a]=null;!0===O?this.deactiveLargePad():!0===R&&this.deactiveSmallPad();!0===W&&(V=0,s_oStage.removeChild(x),x=null);!0===P&&(s_oStage.removeChild(L),L=null);!0===J&&(s_oStage.removeChild(h),this.createPadding(h.x));Y=K=J=P=O=W=!1;for(a=0;a<l.length;a++)l[a].unload(),l[a]=null;U=0;b=f=E=n=r=u=t=v=z=l=null;l=[];z=[];v=[];t=[];u=[];r=[];n=[];E=[];f=[];b=[]};this.update=function(){if(!1===g){F+=s_iTimeElaps;var a=parseInt(F/ya);F-=ya*a;for(var b=0;b<a;b++)for(var d=0;d<
za;d++)this.__updatePhysics()}};s_oGame=this;var ya=16,za=10;BALL_SPEED=c.ball_speed/za;BRICKS_SCORE=c.bricks_score;BRICKS_RESISTANCE=c.bricks_resistance;BRICKS_DESTRUCTIBLE=c.bricks_destructible;BONUS_SPEED=c.bonus_speed/za;BONUS_TIME=c.bonus_time;BONUS_SCORE=c.bonus_score;BULLET_SPEED=c.bullet_speed;LIFE=c.life;SPEED_DOWN_BALL=c.speed_down_ball;SPEED_UP_BALL=c.speed_up_ball;NUM_LEVELS_FOR_ADS=c.num_levels_for_ads;this._init()}var s_oGame;
function CSettingsLevel(){this.createBonusOccurance=function(c){c=BONUS_OCCURRENCE_PER_LEVEL[c];for(var m=[],a=0;a<c.length;a++)for(var e=0;e<c[a];e++)m.push(a);return m};this.unload=function(){s_oAlienSettings=null};s_oAliensSettings=this}var s_oAliensSettings;
function CInterface(){var c,m,a,e,d,g,b,l,f,h,k,q,p,F,n,r,u,t,z,v,G,N,D,A,I,X,B,w,y,S=null,aa=null;this._init=function(){var k=s_oSpriteLibrary.getSprite("icon_audio"),p=CANVAS_WIDTH-k.width/2-130;F=createBitmap(s_oSpriteLibrary.getSprite("up_edges"));s_oStage.addChild(F);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(d=p,g=k.height/2+10,f=new CToggle(d,g,k,s_bAudioActive),f.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),c=d-k.width/2-10,m=g):(c=p,m=k.height/2+10);p=window.document;k=p.documentElement;
S=k.requestFullscreen||k.mozRequestFullScreen||k.webkitRequestFullScreen||k.msRequestFullscreen;aa=p.exitFullscreen||p.mozCancelFullScreen||p.webkitExitFullscreen||p.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(S=!1);S&&!1===inIframe()&&(k=s_oSpriteLibrary.getSprite("but_fullscreen"),y=new CToggle(c,m,k,s_bFullscreen,!0),y.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));u=new createjs.Text(TEXT_SCORE+"\n0","normal 40px "+PRIMARY_FONT,"#ffffff");u.textAlign="center";u.textBaseline="alphabetic";
u.x=CANVAS_WIDTH/2-70;u.y=CANVAS_HEIGHT/2-400;s_oStage.addChild(u);w=new createjs.Text(TEXT_LEVEL_UPPERCASE,"normal 40px "+PRIMARY_FONT,"#ffffff");w.textAlign="center";w.textBaseline="alphabetic";w.x=CANVAS_WIDTH/2-240;w.y=CANVAS_HEIGHT/2-400;s_oStage.addChild(w);k=s_oSpriteLibrary.getSprite("but_exit");p=CANVAS_WIDTH-k.width/2-100;a=p+85;e=k.height/2+10;q=new CGfxButton(a,e,k);q.addEventListener(ON_MOUSE_UP,this._onExit,this);k=s_oSpriteLibrary.getSprite("but_pause");b=p=CANVAS_WIDTH-k.width/2-90;
l=k.height/2+10;h=new CGfxButton(b,l,k);h.addEventListener(ON_MOUSE_UP,this._onButPauseRelease,this);p=s_oSpriteLibrary.getSprite("life");n=createBitmap(p);n.x=.5*CANVAS_WIDTH+60;n.y=120;n.regX=.5*p.width;n.regY=.5*p.width;s_oStage.addChild(n);r=new createjs.Text("x"+LIFE,"normal 40px "+PRIMARY_FONT,"#ffffff");r.textAlign="center";r.textBaseline="alphabetic";r.x=.5*CANVAS_WIDTH+100;r.y=125;s_oStage.addChild(r);s_oGame.setPause(!0);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=
function(k,p){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||f.setPosition(d-k,g+p);S&&!1===inIframe()&&y.setPosition(c-k,m+p);h.setPosition(b-k,l+p);q.setPosition(a-k,e+p)};this.rereshNumLevel=function(){};this.refreshBallLife=function(a){r.text="x"+ +a};this.gameOver=function(a){s_oGame.setPause(!0);h.block(!0);t=new createjs.Shape;t.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);t.alpha=0;s_oStage.addChild(t);v=new createjs.Text(TEXT_SCORE_GAMEOVER+"\n\n"+a,"normal 90px "+PRIMARY_FONT,
"#ffff00");v.textAlign="center";v.textBaseline="alphabetic";v.x=CANVAS_WIDTH/2;v.y=-120;s_oStage.addChild(v);createjs.Tween.get(t).to({alpha:.5},1E3,createjs.Ease.backOut).call(function(){createjs.Tween.get(v).to({y:CANVAS_HEIGHT/2-200},1E3,createjs.Ease.bounceOut).call(function(){var a=s_oSpriteLibrary.getSprite("but_restart");z=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+200,a);z.addEventListener(ON_MOUSE_UP,s_oInterface._onButReturnToMenuRelease,this)})});$(s_oMain).trigger("share_event",a);
$(s_oMain).trigger("save_score",a);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var b;b=createjs.Sound.play("game_over");s_oSoundTrack.volume=.04;b.on("complete",function(){s_oSoundTrack.volume=1;b=null})}};this.levelComplete=function(a,b){var d=a+1;d<BRICKS_LEVEL_POSITION.length?(t=createBitmap(s_oSpriteLibrary.getSprite("msg_box")),t.alpha=0,s_oStage.addChild(t),s_oStage.setChildIndex(t,s_oStage.numChildren-1),h.block(!0),D=new createjs.Text(TEXT_LEVEL+" "+d+" "+TEXT_COMPLETE,"normal 90px "+PRIMARY_FONT,
"#ffff00"),D.textAlign="center",D.textBaseline="alphabetic",D.x=CANVAS_WIDTH/2,D.y=-140,s_oStage.addChild(D),A=new createjs.Text(TEXT_SCORE+"\n\n"+b,"normal 90px "+PRIMARY_FONT,"#ffff00"),A.textAlign="center",A.textBaseline="alphabetic",A.x=CANVAS_WIDTH/2,A.y=CANVAS_HEIGHT/2-40,A.alpha=0,s_oStage.addChild(A),createjs.Tween.get(t).to({alpha:1},1E3,createjs.Ease.backOut),createjs.Tween.get(A).to({alpha:1},1E3,createjs.Ease.bounceOut).call(function(){var a=s_oSpriteLibrary.getSprite("but_continue");
N=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+300,a);N.addEventListener(ON_MOUSE_UP,s_oInterface._onButNextLevelRelease,this)}),createjs.Tween.get(D).to({y:CANVAS_HEIGHT/2-300},1E3,createjs.Ease.bounceOut)):this.finishGame(b)};this.finishGame=function(a){s_oGame.setPause(!0);h.block(!0);t=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));t.alpha=0;s_oStage.addChild(t);s_oStage.setChildIndex(t,s_oStage.numChildren-1);I=new createjs.Text(TEXT_CONGRATULATIONS,"normal 70px "+PRIMARY_FONT,"#ffff00");
I.textAlign="center";I.textBaseline="alphabetic";I.lineWidth=500;I.lineHeight=60;I.x=CANVAS_WIDTH/2;I.y=-120;s_oStage.addChild(I);v=new createjs.Text(TEXT_SCORE_GAMEOVER+"\n\n"+a,"normal 80px "+PRIMARY_FONT,"#ffff00");v.textAlign="center";v.textBaseline="alphabetic";v.x=CANVAS_WIDTH/2;v.y=CANVAS_HEIGHT/2-50;v.alpha=0;s_oStage.addChild(v);createjs.Tween.get(t).to({alpha:1},1E3,createjs.Ease.backOut);createjs.Tween.get(I).to({y:CANVAS_HEIGHT/2-310},1200,createjs.Ease.bounceOut);createjs.Tween.get(v).to({alpha:1},
1E3,createjs.Ease.bounceOut).call(function(){var a=s_oSpriteLibrary.getSprite("but_restart");z=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+300,a);z.addEventListener(ON_MOUSE_UP,s_oInterface._onButReturnToMenuRelease,this)});if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var b;b=createjs.Sound.play("game_completed");s_oSoundTrack.volume=.04;b.on("complete",function(){s_oSoundTrack.volume=1;b=null})}$(s_oMain).trigger("save_score",a);$(s_oMain).trigger("share_event",a)};this._onButNextLevelRelease=
function(){s_oStage.removeChild(D,A,t);A=t=D=null;N.unload();N=null;h.block(!1);s_oGame.nextLevel()};this._onButReturnToMenuRelease=function(){s_oGame.onExit()};this.refreshScore=function(a){u.text="SCORE\n"+a};this._onButPauseRelease=function(){playSound("click",1,0,void 0);s_oGame.setPause(!0);G=new createjs.Shape;G.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);G.alpha=.5;s_oStage.addChild(G);k=new createjs.Text("Pause","normal 70px "+PRIMARY_FONT,"#ffffff");k.textAlign="center";
k.textBaseline="alphabetic";k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2-250;s_oStage.addChild(k);h.block(!0);q.block(!0);createjs.Ticker.paused=!0;var a=s_oSpriteLibrary.getSprite("but_continue");p=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2,a);p.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this)};this._onButContinueRelease=function(){playSound("click",1,0,void 0);p.unload();p=null;s_oStage.removeChild(k,G);G=!1;k=null;h.block(!1);q.block(!1);createjs.Ticker.paused=!1;s_oGame.setPause(!1)};
this.help=function(a){var b=a+1;a=s_oSpriteLibrary.getSprite("msg_box");X=createBitmap(a);X.on("click",function(){s_oInterface.unloadHelp(b)},null,!0);s_oStage.addChild(X);B?B.text=!0===s_bMobile?TEXT_HELP_PAGE_1_MOBILE:TEXT_HELP_PAGE_1_PC:(B=new createjs.Text(TEXT_HELP_PAGE_1_PC,"normal 60px "+PRIMARY_FONT,"#ffff00"),B.textAlign="center",B.textBaseline="alphabetic",B.lineWidth=500,B.lineHeight=50,B.x=CANVAS_WIDTH/2,B.y=CANVAS_HEIGHT/2-100,s_oStage.addChild(B))};this.unloadHelp=function(a){createjs.Tween.get(X).to({alpha:0},
1E3,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(X)});createjs.Tween.get(B).to({alpha:0},1E3,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(B);s_oInterface.showNumLevel(a)})};this.numLevel=function(a){w.text=TEXT_LEVEL_UPPERCASE+"\n"+(a+1)};this.showNumLevel=function(a){var b,d;b=new createjs.Text(TEXT_LEVEL_UPPERCASE+" "+a,"normal 100px "+PRIMARY_FONT,COLOR_TEXT_LEVEL[Math.floor(4*Math.random())]);b.textAlign="center";b.textBaseline="alphabetic";b.x=0;b.y=0;a=new createjs.Text(TEXT_LEVEL_UPPERCASE+
" "+a,"normal 100px "+PRIMARY_FONT,"#000000");a.textAlign="center";a.textBaseline="alphabetic";a.x=0;a.y=0;a.outline=5;d=new createjs.Container;d.addChild(a,b);d.x=-100;d.y=.5*CANVAS_HEIGHT;s_oStage.addChild(d);createjs.Tween.get(d).to({x:.5*CANVAS_WIDTH},600,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(d).wait(500).to({x:CANVAS_WIDTH+100},600,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(d);s_oGame.setPause(!1)})})};this.unload=function(){s_oStage.removeChild(v,z,t);t=
z=v=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f.unload(),f=null;S&&!1===inIframe()&&y.unload();s_oInterface=null};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?(aa.call(window.document),s_bFullscreen=!1):(S.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CBall(c,m,a,e,d,g,b,l){var f,h={},k,q,p,F,n,r,u,t,z,v,G,N,D=0;this._init=function(){if(b){var h=new createjs.SpriteSheet({images:[a],frames:{width:a.width/8,height:a.height,regX:a.width/2/8,regY:a.height/2},animations:{fire:[0,7,"fire",.5]}});f=createSprite(h,"fire",a.width/2/8,a.height/2,a.width/8,a.height)}else f=createBitmap(a);f.x=c;f.y=m;p=l+OFFSET_RADIUS_BALL;v=!1;k=new CVector2(e,d);q=new CVector2(0,-1);f.regX=p;f.regY=p;var h=OFFSETEDGELEFT+p,I=-OFFSETEDGEDOWN-p,D=OFFSETEDGEUP+p;
F=CANVAS_WIDTH+(-OFFSETEDGERIGHT-p);n=h;u=CANVAS_HEIGHT+I-p;r=D+p;z=CANVAS_HEIGHT+p;t=CANVAS_HEIGHT+I-p+OFFSETPOWERUPFLOOR;N=g;G=BALL_SPEED*N;s_oStage.addChild(f);s_oStage.setChildIndex(f,1)};this.changeDirection=function(a,b,d,c){!0===d?k.set(a,k.getY()*b):"base"===c?k.set(k.getX()*a,b):"side"===c?k.set(k.getX()*a,k.getY()*b):"launch"===c&&k.set(a,b)};this.changeSprite=function(a,b){var d=f.x,c=f.y;if("fire"===b){s_oStage.removeChild(f);f=null;var e=new createjs.SpriteSheet({images:[a],frames:{width:a.width/
8,height:a.height,regX:a.width/2/8,regY:a.height/2},animations:{fire:[0,7,"fire",.5]}});f=createSprite(e,"fire",a.width/2/8,a.height/2,a.width/8,a.height);f.x=d;f.y=c}else s_oStage.removeChild(f),f=createBitmap(a),f.x=d,f.y=c,f.regX=p,f.regY=p;s_oStage.addChild(f);this.changeRotation();s_oStage.setChildIndex(f,1)};this.downFloor=function(a){v=a};this.getDirectionY=function(){return k.getY()};this.getX=function(){return f.x};this.getY=function(){return f.y};this.setDirection=function(a,b){k.normalize();
k.set(a,b);this.changeRotation()};this.changeRotation=function(){D=Math.round(toDegree(k.angleBetweenVectors(q)));0<k.getY()?(D*=-1,0<=k.getX()&&(D*=-1)):0>=k.getX()&&(D*=-1);f.rotation=D};this.setPosition=function(a,b){null!==a&&(f.x=a);null!==b&&(f.y=b)};this.setInfoData=function(a,b){h[a]=b};this.getInfoData=function(a){return h[a]};this.resetTheIndex=function(a){h.ID=a};this.unload=function(){s_oStage.removeChild(f);s_oBall=null};this.setVelocityRate=function(a){N=a;G=BALL_SPEED*N};this.update=
function(){f.x+=G*k.getX();f.y+=G*k.getY();f.x>=F?(k.set(-1*k.getX(),k.getY()),this.changeRotation(),--f.x,playSound("boing",1,0)):f.x<=n?(k.set(-1*k.getX(),k.getY()),this.changeRotation(),f.x+=1,playSound("boing",1,0)):f.y>=u&&!0===v&&f.y<t?(k.set(k.getX(),-1*k.getY()),this.changeRotation(),playSound("boing",1,0)):f.y<=r?(k.set(k.getX(),-1*k.getY()),this.changeRotation(),playSound("boing",1,0)):f.y>z?s_oGame.loseBall(h.ID):f.x<=n-1?f.x+=2:f.x>=F+1?f.x-=2:f.y<=r-1&&(f.y+=2)};s_oBall=this;this._init()}
var s_oBall;
function CBrick(c,m,a,e,d){var g,b={};this._init=function(){if(1>e&&!0===d)g=createBitmap(a),g.regX=a.width/2,g.regY=a.height/2,b.Effect=!1;else if(!0===d){var l={images:[a],frames:{width:a.width/4,height:a.height/2,regX:a.width/2/4,regY:a.height/2/2},animations:{normal:[1],destoyed:[2,7,"destroyed",.5]}},l=new createjs.SpriteSheet(l);g=createSprite(l,"normal",a.width/2/4,a.height/2/2,a.width/4,a.height/2);b.Effect=!0}else l={images:[a],frames:{width:a.width/8,height:a.height/2,regX:a.width/2/8,regY:a.height/
2/2},animations:{reflect:[0,15,"reflect",.5]}},l=new createjs.SpriteSheet(l),g=createSprite(l,0,a.width/2/8,a.height/2/2,a.width/8,a.height/2),b.Effect=!1,b.Reflect=!1;g.x=c;g.y=m;s_oStage.addChild(g)};this.getX=function(){return g.x};this.getY=function(){return g.y};this.setInfoData=function(a,d){b[a]=d};this.getInfoData=function(a){return b[a]};this.animBrick=function(a){g.gotoAndPlay(a);g.on("animationend",function(){s_oStage.removeChild(g)})};this.reflectBrick=function(){!0!==b.Reflect&&(g.gotoAndPlay("reflect"),
g.on("animationend",function(){g.gotoAndStop("reflect");b.Reflect=!1}))};this.setPosition=function(a,b){g.x=a;g.y=b};this.setChildIndex=function(a){s_oStage.setChildIndex(g,a)};this.damageBrick=function(a){g.gotoAndStop(a)};this.unload=function(){s_oStage.removeChild(g);s_oBrick=null};this.update=function(){};s_oBrick=this;this._init()}var s_oBrick;
function CBonus(c,m,a,e,d){var g,b={},l,f;this._init=function(a,d,c,e,m){b.Type=e;b.ID=m;0===e||7===e||9===e?(e={images:[c],frames:{width:c.width/5,height:c.height/2,regX:c.width/2/5,regY:c.height/2/2},animations:{normal:[0,9,"normal",1]}},e=new createjs.SpriteSheet(e),g=createSprite(e,"normal",c.width/2/5,c.height/2/2,c.width/5,c.height/2),b.offsetX=c.width/5/2):1===e||2===e||4===e||5===e||8===e?(e={images:[c],frames:{width:c.width/4,height:c.height/2,regX:c.width/2/4,regY:c.height/2/2},animations:{normal:[0,
7,"normal",1]}},e=new createjs.SpriteSheet(e),g=createSprite(e,"normal",c.width/2/4,c.height/2/2,c.width/4,c.height/2),b.offsetX=c.width/4/2):(e={images:[c],frames:{width:c.width/6,height:c.height/2,regX:c.width/2/6,regY:c.height/2/2},animations:{normal:[0,11,"normal",1]}},e=new createjs.SpriteSheet(e),g=createSprite(e,"normal",c.width/2/6,c.height/2/2,c.width/6,c.height/2),b.offsetX=c.width/6/2);b.offsetY=c.height/2/2;l=BONUS_SPEED;g.x=a;g.y=d;s_oStage.addChild(g);f=CANVAS_HEIGHT+b.offsetX};this.getX=
function(){return g.x};this.getY=function(){return g.y};this.setInfoData=function(a,d){b[a]=d};this.getInfoData=function(a){return b[a]};this.resetTheIndex=function(a){b.ID=a};this.unload=function(){s_oStage.removeChild(g)};this.update=function(){g.y+=l;g.y<f||s_oGame.unloadBonus(b.ID)};s_oBonus=this;this._init(c,m,a,e,d)}var s_oBonus;
function CBullet(c,m,a){var e,d,g;this._init=function(){var b=a.height/2;e=createBitmap(a);e.x=c;e.y=m;e.regX=a.width/2;e.regY=b;s_oStage.addChild(e);d=30+b+b};this.getX=function(){return e.x};this.getY=function(){return e.y};this.setPosition=function(a,d){null!==a&&(e.x=a);null!==d&&(e.y=d)};this.unload=function(){s_oStage.removeChild(e);s_oBullet=null};this.setIndex=function(a){g=a};this.getIndex=function(){return g};this.update=function(){e.y-=BULLET_SPEED;e.y<d&&(s_oGame.unloadBullet(g),playSound("brick_metal",
1,0))};s_oBullet=this;this._init()}var s_oBullet;
function CVector2(c,m){var a,e;this._init=function(d,c){a=d;e=c};this.add=function(d,c){a+=d;e+=c};this.addV=function(d){a+=d.getX();e+=d.getY()};this.scalarDivision=function(d){a/=d;e/=d};this.subV=function(d){a-=d.getX();e-=d.getY()};this.scalarProduct=function(d){a*=d;e*=d};this.invert=function(){a*=-1;e*=-1};this.dotProduct=function(d){return a*d.getX()+e*d.getY()};this.set=function(d,c){a=d;e=c};this.setV=function(d){a=d.getX();e=d.getY()};this.length=function(){return Math.sqrt(a*a+e*e)};this.length2=
function(){return a*a+e*e};this.normalize=function(){var d=this.length();0<d&&(a/=d,e/=d)};this.angleBetweenVectors=function(a){a=Math.acos(this.dotProduct(a)/(this.length()*a.length()));return!0===isNaN(a)?0:a};this.getNormalize=function(c){this.length();c.set(a,e);c.normalize()};this.rot90CCW=function(){var c=a;a=-e;e=c};this.rot90CW=function(){var c=a;a=e;e=-c};this.getRotCCW=function(c){c.set(a,e);c.rot90CCW()};this.getRotCW=function(c){c.set(a,e);c.rot90CW()};this.ceil=function(){a=Math.ceil(a);
e=Math.ceil(e)};this.round=function(){a=Math.round(a);e=Math.round(e)};this.toString=function(){return"Vector2: "+a+", "+e};this.print=function(){trace("Vector2: "+a+", "+e+"")};this.getX=function(){return a};this.getY=function(){return e};this._init(c,m)}
function CLevelMenu(c){var m,a,e,d,g,b=[],l,f,h,k;this._init=function(){l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));l.x=0;l.y=0;s_oStage.addChild(l);l=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));s_oStage.addChild(l);g=new createjs.Text(TEXT_LEVEL_UPPERCASE," 50px "+PRIMARY_FONT,"#ffffff");g.x=CANVAS_WIDTH/2;g.y=400;g.textAlign="center";g.textBaseline="alphabetic";g.lineWidth=1E3;s_oStage.addChild(g);for(var c=.5*CANVAS_WIDTH-20,p=0,F=50,n=0;n<BRICKS_LEVEL_POSITION.length;n++,p+=
110)440<p&&(p=0,F+=100),n<s_iLevelReached?(b[n]=new CLevelBut(c-200+p,425+F,s_oSpriteLibrary.getSprite("but_level"),!0,n+1),b[n].addEventListenerWithParams(ON_MOUSE_DOWN,this._onClick,this,n)):b[n]=new CLevelBut(c-200+p,425+F,s_oSpriteLibrary.getSprite("but_level"),!1,n+1),s_bFirstTime=!0;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p=s_oSpriteLibrary.getSprite("icon_audio"),m=c=CANVAS_WIDTH-p.width/2-60,a=p.height/2+10,h=new CToggle(m,a,p,s_bAudioActive),h.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);p=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH-p.width/2-100;e=c+85;d=p.height/2+10;f=new CGfxButton(e,d,p);f.addEventListener(ON_MOUSE_UP,this._onExit,this);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(k);createjs.Tween.get(k).to({alpha:0},1E3).call(function(){s_oStage.removeChild(k)});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){for(var a=0;a<BRICKS_LEVEL_POSITION.length;a++)b[a].unload();s_oLevelMenu=
null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(b,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||h.setPosition(m-b,a+c);f.setPosition(e-b,d+c)};this._onNumModeToggle=function(a){a===NUM_ACTIVE?((void 0).setActive(!1),(void 0).setActive(!0)):((void 0).setActive(!0),(void 0).setActive(!1))};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onClick=function(a){playSound("click",1,0);b[a].ifClickable()&&(s_oLevelMenu.unload(),
$(s_oMain).trigger("start_session"),s_oMain.gotoGame(a))};this._onExit=function(){s_oLevelMenu.unload();s_oMain.gotoMenu()};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(c,m,a,e,d){var g,b,l,f=[],h=[],k;this._init=function(a,c,e,h){b=[];l=[];var m=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{state_true:[0],state_false:[1]}});g=h;k=createSprite(m,"state_"+g,e.width/2/2,e.height/2,e.width/2,e.height);k.mouseEnabled=h;k.x=a;k.y=c;k.stop();s_bMobile||(k.cursor="pointer");s_oStage.addChild(k);f.push(k);e=new createjs.Text(d,"bold 50px "+PRIMARY_FONT,"#ffff00");e.x=a;e.y=c+
15;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=200;s_oStage.addChild(e);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);s_oStage.removeChild(k)};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.viewBut=function(a){s_oStage.addChild(a)};this.addEventListener=function(a,c,d){b[a]=c;l[a]=d};this.addEventListenerWithParams=function(a,c,d,e){b[a]=c;l[a]=d;h=e};this.ifClickable=
function(){return!0===k.mouseEnabled?1:0};this.setActive=function(a,b){g=b;f[a].gotoAndStop("state_"+g);f[a].mouseEnabled=!0};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("click",1,0);g=!g;k.gotoAndStop("state_"+g);b[ON_MOUSE_UP]&&b[ON_MOUSE_UP].call(l[ON_MOUSE_UP],h)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;b[ON_MOUSE_DOWN]&&b[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],h)};this.setPosition=function(a,b){k.x=a;k.y=b};this.setVisible=function(a){k.visible=a};this._init(c,m,a,
e)}
function CCreditsPanel(){var c,m,a,e,d,g,b,l;this._init=function(){l=new createjs.Container;s_oStage.addChild(l);var f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));l.addChild(f);d=new createjs.Shape;d.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.addChild(d);f=s_oSpriteLibrary.getSprite("msg_box");m=createBitmap(f);m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2;m.regX=f.width/2;m.regY=f.height/2;l.addChild(m);g=new createjs.Shape;g.graphics.beginFill("#0f0f0f").drawRect(0,0,
CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=.01;g.on("click",this._onLogoButRelease);l.addChild(g);f=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH/2+264;a=new CGfxButton(c,394,f,l);a.addEventListener(ON_MOUSE_UP,this.unload,this);e=new createjs.Text(TEXT_DEVELOPED,"46px "+PRIMARY_FONT,"#ffffff");e.x=CANVAS_WIDTH/2;e.y=420;e.textAlign="center";l.addChild(e);var f=s_oSpriteLibrary.getSprite("ctl_logo"),h=createBitmap(f);h.regX=f.width/2;h.regY=f.height/2;h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2;l.addChild(h);
b=new createjs.Text("www.codethislab.com","46px "+PRIMARY_FONT,"#ffffff");b.x=CANVAS_WIDTH/2;b.y=570;b.textAlign="center";l.addChild(b)};this.unload=function(){g.off("click",this._onLogoButRelease);a.unload();a=null;s_oStage.removeChild(l)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()};
