var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(b){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(b)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(b.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(b){console.log(b)}function isIOS(){for(var b="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");b.length;)if(navigator.platform===b.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}
function getSize(b){var f=b.toLowerCase(),e=window.document,d=e.documentElement;if(void 0===window["inner"+b])b=d["client"+b];else if(window["inner"+b]!=d["client"+b]){var c=e.createElement("body");c.id="vpw-test-b";c.style.cssText="overflow:scroll";var k=e.createElement("div");k.id="vpw-test-d";k.style.cssText="position:absolute;top:-1000px";k.innerHTML="<style>@media("+f+":"+d["client"+b]+"px){body#vpw-test-b div#vpw-test-d{"+f+":7px!important}}</style>";c.appendChild(k);d.insertBefore(c,e.head);
b=7==k["offset"+b]?d["client"+b]:window["inner"+b];d.removeChild(c)}else b=window["inner"+b];return b}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var b=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<b?b:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var b;b=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var f=getSize("Width");_checkOrientation(f,b);var e=Math.min(b/CANVAS_HEIGHT,f/CANVAS_WIDTH),d=CANVAS_WIDTH*e,e=CANVAS_HEIGHT*e,c;e<b?(c=b-e,e+=c,d+=CANVAS_WIDTH/CANVAS_HEIGHT*c):d<f&&(c=f-d,d+=c,e+=CANVAS_HEIGHT/CANVAS_WIDTH*c);c=b/2-e/2;var k=f/2-d/2,a=CANVAS_WIDTH/d;if(k*a<-EDGEBOARD_X||c*a<-EDGEBOARD_Y)e=Math.min(b/(CANVAS_HEIGHT-2*EDGEBOARD_Y),
f/(CANVAS_WIDTH-2*EDGEBOARD_X)),d=CANVAS_WIDTH*e,e*=CANVAS_HEIGHT,c=(b-e)/2,k=(f-d)/2,a=CANVAS_WIDTH/d;s_iOffsetX=-1*k*a;s_iOffsetY=-1*c*a;0<=c&&(s_iOffsetY=0);0<=k&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oLanguageMenu&&s_oLanguageMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile?($("#canvas").css("width",d+"px"),$("#canvas").css("height",e+"px")):(s_oStage.canvas.width=
d,s_oStage.canvas.height=e,s_oStage.scaleX=s_oStage.scaleY=Math.min(d/CANVAS_WIDTH,e/CANVAS_HEIGHT));0>c?$("#canvas").css("top",c+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",k+"px")}}
function _checkOrientation(b,f){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(b>f?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(b){return!0}}function createBitmap(b,f,e){var d=new createjs.Bitmap(b),c=new createjs.Shape;f&&e?c.graphics.beginFill("#fff").drawRect(0,0,f,e):c.graphics.beginFill("#ff0").drawRect(0,0,b.width,b.height);d.hitArea=c;return d}function createSprite(b,f,e,d,c,k){b=null!==f?new createjs.Sprite(b,f):new createjs.Sprite(b);f=new createjs.Shape;f.graphics.beginFill("#000000").drawRect(-e,-d,c,k);b.hitArea=f;return b}
function randomFloatBetween(b,f,e){"undefined"===typeof e&&(e=2);return parseFloat(Math.min(b+Math.random()*(f-b),f).toFixed(e))}function formatTime(b){b/=1E3;var f=Math.floor(b/60);b=Math.floor(b-60*f);var e="",e=10>f?e+("0"+f+":"):e+(f+":");return 10>b?e+("0"+b):e+b}function NoClickDelay(b){this.element=b;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(b){for(var f=b.length,e,d;0<f;)d=Math.floor(Math.random()*f),f--,e=b[f],b[f]=b[d],b[d]=e;return b}
NoClickDelay.prototype={handleEvent:function(b){switch(b.type){case "touchstart":this.onTouchStart(b);break;case "touchmove":this.onTouchMove(b);break;case "touchend":this.onTouchEnd(b)}},onTouchStart:function(b){b.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(b){this.moved=!0},onTouchEnd:function(b){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){b=document.elementFromPoint(b.changedTouches[0].clientX,b.changedTouches[0].clientY);3==b.nodeType&&(b=b.parentNode);var f=document.createEvent("MouseEvents");f.initEvent("click",!0,!0);b.dispatchEvent(f)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(b){for(var f=window.location.search.substring(1).split("&"),e=0;e<f.length;e++){var d=f[e].split("=");if(d[0]==b)return d[1]}}
(function(){function b(b){var e={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};b=b||window.event;b.type in e?document.body.className=e[b.type]:(document.body.className=this[f]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var f="hidden";f in document?document.addEventListener("visibilitychange",b):(f="mozHidden")in document?document.addEventListener("mozvisibilitychange",b):(f="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",b):(f="msHidden")in document?document.addEventListener("msvisibilitychange",b):"onfocusin"in document?document.onfocusin=document.onfocusout=b:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=b})();
function CSpriteLibrary(){var b,f,e,d,c,k;this.init=function(a,h,m){e=f=0;d=a;c=h;k=m;b={}};this.addSprite=function(a,c){b.hasOwnProperty(a)||(b[a]={szPath:c,oSprite:new Image},f++)};this.getSprite=function(a){return b.hasOwnProperty(a)?b[a].oSprite:null};this._onSpritesLoaded=function(){c.call(k)};this._onSpriteLoaded=function(){d.call(k);++e===f&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in b)b[a].oSprite.oSpriteLibrary=this,b[a].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
b[a].oSprite.src=b[a].szPath};this.getNumSprites=function(){return f}}
var CANVAS_WIDTH=1280,CANVAS_HEIGHT=1920,EDGEBOARD_X=120,EDGEBOARD_Y=170,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="ArialRoundedMTBold",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_LANGUAGE=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,LANGUAGE_EN=0,LANGUAGE_FR=1,LANGUAGE_IT=2,LANGUAGE_ES=3,LANGUAGE_GER=4,LANGUAGE_POR=5,PADDING=40,GAME_ELEMENT_HEIGHT=-150,NUMBER_OF_WORDS=21,NUMBER_QUEST_IMAGE=4,BONUS_TIME=!0,ALPHABET=[],ALPHABET=
["AAABCDEEEFGHHIIJKLMNNOOOPQRSSTTTUVWXYZ".split(""),"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),"AAABCDEEEFGHIIIJKLLMNNOOPQRSTTUVWLXYZ".split(""),"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("")],SHOW_CREDITS=!0,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;
function CPreloader(){var b,f,e,d,c,k,a;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.png");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();a=new createjs.Container;s_oStage.addChild(a)};this.unload=function(){a.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(k).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));a.addChild(h);h=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(h);d.x=CANVAS_WIDTH/2-h.width/2;d.y=CANVAS_HEIGHT-370;a.addChild(d);b=h.width;f=h.height;c=new createjs.Shape;c.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,f);a.addChild(c);d.mask=
c;e=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT-325;e.shadow=new createjs.Shadow("#000",2,2,2);e.textBaseline="alphabetic";e.textAlign="center";a.addChild(e);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=0;a.addChild(k)};this.refreshLoader=function(a){e.text=a+"%";c.graphics.clear();a=Math.floor(a*b/100);c.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,a,f)};this._init()}
function CMain(b){var f,e=0,d=0,c=STATE_LOADING,k,a,h,m;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile;s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;m="json/QUIZLogic.json";a=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this.loadJSON();this._loadImages();f=!0};this.onLoadedJSON=function(a){s_aQuestions=a};this.loadJSON=function(){jQuery.getJSON(m,this.onLoadedJSON)};this.soundLoaded=function(){e++;a.refreshLoader(Math.floor(e/d*100));e===d&&this._onRemovePreloader()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&
(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","gameover"),createjs.Sound.registerSound("./sounds/guessed.ogg","guessed"),createjs.Sound.registerSound("./sounds/wrong.ogg",
"wrong")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.mp3","click"),createjs.Sound.registerSound("./sounds/game_over.mp3","gameover"),createjs.Sound.registerSound("./sounds/guessed.mp3","guessed"),createjs.Sound.registerSound("./sounds/wrong.mp3","wrong")),d+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,
this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_gameover","./sprites/bg_gameover.png");s_oSpriteLibrary.addSprite("load_level","./sprites/load_level.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("curtain_dx",
"./sprites/curtain_dx.jpg");s_oSpriteLibrary.addSprite("curtain_sx","./sprites/curtain_sx.jpg");s_oSpriteLibrary.addSprite("logo","./sprites/logo.png");s_oSpriteLibrary.addSprite("logo_small","./sprites/logo_small.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("letterbox","./sprites/letterbox.png");s_oSpriteLibrary.addSprite("letter","./sprites/letter.png");s_oSpriteLibrary.addSprite("money_panel","./sprites/money_panel.png");s_oSpriteLibrary.addSprite("level_panel",
"./sprites/level_panel.png");s_oSpriteLibrary.addSprite("success","./sprites/success.png");s_oSpriteLibrary.addSprite("mistake","./sprites/mistake.png");s_oSpriteLibrary.addSprite("but_next","./sprites/but_next.png");s_oSpriteLibrary.addSprite("text_copyright","./sprites/text_copyright.png");s_oSpriteLibrary.addSprite("but_flag_it","./sprites/but_flag_it.png");s_oSpriteLibrary.addSprite("but_flag_en","./sprites/but_flag_en.png");s_oSpriteLibrary.addSprite("but_flag_fr","./sprites/but_flag_fr.png");
s_oSpriteLibrary.addSprite("but_flag_es","./sprites/but_flag_es.png");s_oSpriteLibrary.addSprite("but_flag_ger","./sprites/but_flag_ger.png");s_oSpriteLibrary.addSprite("but_flag_por","./sprites/but_flag_por.png");s_oSpriteLibrary.addSprite("but_add_a_letter","./sprites/but_add_a_letter.png");s_oSpriteLibrary.addSprite("but_remove_letters","./sprites/but_remove_letters.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");
s_oSpriteLibrary.addSprite("imghome1","./sprites/imghome1.png");s_oSpriteLibrary.addSprite("imghome2","./sprites/imghome2.jpg");s_oSpriteLibrary.addSprite("imghome3","./sprites/imghome3.jpg");s_oSpriteLibrary.addSprite("imghome4","./sprites/imghome4.jpg");s_oSpriteLibrary.addSprite("imgcat1","./sprites/imgcat1.jpg");s_oSpriteLibrary.addSprite("imgcat2","./sprites/imgcat2.jpg");s_oSpriteLibrary.addSprite("imgcat3","./sprites/imgcat3.jpg");s_oSpriteLibrary.addSprite("imgcat4","./sprites/imgcat4.jpg");
s_oSpriteLibrary.addSprite("imghappy1","./sprites/imghappy1.jpg");s_oSpriteLibrary.addSprite("imghappy2","./sprites/imghappy2.jpg");s_oSpriteLibrary.addSprite("imghappy3","./sprites/imghappy3.jpg");s_oSpriteLibrary.addSprite("imghappy4","./sprites/imghappy4.jpg");s_oSpriteLibrary.addSprite("imgdrink1","./sprites/imgdrink1.jpg");s_oSpriteLibrary.addSprite("imgdrink2","./sprites/imgdrink2.jpg");s_oSpriteLibrary.addSprite("imgdrink3","./sprites/imgdrink3.jpg");s_oSpriteLibrary.addSprite("imgdrink4",
"./sprites/imgdrink4.jpg");s_oSpriteLibrary.addSprite("imgminute1","./sprites/imgminute1.jpg");s_oSpriteLibrary.addSprite("imgminute2","./sprites/imgminute2.jpg");s_oSpriteLibrary.addSprite("imgminute3","./sprites/imgminute3.jpg");s_oSpriteLibrary.addSprite("imgminute4","./sprites/imgminute4.jpg");s_oSpriteLibrary.addSprite("imgsound1","./sprites/imgsound1.jpg");s_oSpriteLibrary.addSprite("imgsound2","./sprites/imgsound2.jpg");s_oSpriteLibrary.addSprite("imgsound3","./sprites/imgsound3.jpg");s_oSpriteLibrary.addSprite("imgsound4",
"./sprites/imgsound4.jpg");s_oSpriteLibrary.addSprite("imgcacao1","./sprites/imgcacao1.jpg");s_oSpriteLibrary.addSprite("imgcacao2","./sprites/imgcacao2.jpg");s_oSpriteLibrary.addSprite("imgcacao3","./sprites/imgcacao3.jpg");s_oSpriteLibrary.addSprite("imgcacao4","./sprites/imgcacao4.jpg");s_oSpriteLibrary.addSprite("imgfull1","./sprites/imgfull1.jpg");s_oSpriteLibrary.addSprite("imgfull2","./sprites/imgfull2.jpg");s_oSpriteLibrary.addSprite("imgfull3","./sprites/imgfull3.jpg");s_oSpriteLibrary.addSprite("imgfull4",
"./sprites/imgfull4.jpg");s_oSpriteLibrary.addSprite("imgcold1","./sprites/imgcold1.jpg");s_oSpriteLibrary.addSprite("imgcold2","./sprites/imgcold2.jpg");s_oSpriteLibrary.addSprite("imgcold3","./sprites/imgcold3.jpg");s_oSpriteLibrary.addSprite("imgcold4","./sprites/imgcold4.jpg");s_oSpriteLibrary.addSprite("imgviolet1","./sprites/imgviolet1.jpg");s_oSpriteLibrary.addSprite("imgviolet2","./sprites/imgviolet2.jpg");s_oSpriteLibrary.addSprite("imgviolet3","./sprites/imgviolet3.jpg");s_oSpriteLibrary.addSprite("imgviolet4",
"./sprites/imgviolet4.jpg");s_oSpriteLibrary.addSprite("imgchord1","./sprites/imgchord1.jpg");s_oSpriteLibrary.addSprite("imgchord2","./sprites/imgchord2.jpg");s_oSpriteLibrary.addSprite("imgchord3","./sprites/imgchord3.jpg");s_oSpriteLibrary.addSprite("imgchord4","./sprites/imgchord4.jpg");s_oSpriteLibrary.addSprite("imgcolors1","./sprites/imgcolors1.jpg");s_oSpriteLibrary.addSprite("imgcolors2","./sprites/imgcolors2.jpg");s_oSpriteLibrary.addSprite("imgcolors3","./sprites/imgcolors3.jpg");s_oSpriteLibrary.addSprite("imgcolors4",
"./sprites/imgcolors4.jpg");s_oSpriteLibrary.addSprite("imgrubber1","./sprites/imgrubber1.jpg");s_oSpriteLibrary.addSprite("imgrubber2","./sprites/imgrubber2.jpg");s_oSpriteLibrary.addSprite("imgrubber3","./sprites/imgrubber3.jpg");s_oSpriteLibrary.addSprite("imgrubber4","./sprites/imgrubber4.jpg");s_oSpriteLibrary.addSprite("imgdelete1","./sprites/imgdelete1.jpg");s_oSpriteLibrary.addSprite("imgdelete2","./sprites/imgdelete2.jpg");s_oSpriteLibrary.addSprite("imgdelete3","./sprites/imgdelete3.jpg");
s_oSpriteLibrary.addSprite("imgdelete4","./sprites/imgdelete4.jpg");s_oSpriteLibrary.addSprite("imgclimb1","./sprites/imgclimb1.jpg");s_oSpriteLibrary.addSprite("imgclimb2","./sprites/imgclimb2.jpg");s_oSpriteLibrary.addSprite("imgclimb3","./sprites/imgclimb3.jpg");s_oSpriteLibrary.addSprite("imgclimb4","./sprites/imgclimb4.jpg");s_oSpriteLibrary.addSprite("imgorange1","./sprites/imgorange1.jpg");s_oSpriteLibrary.addSprite("imgorange2","./sprites/imgorange2.jpg");s_oSpriteLibrary.addSprite("imgorange3",
"./sprites/imgorange3.jpg");s_oSpriteLibrary.addSprite("imgorange4","./sprites/imgorange4.jpg");s_oSpriteLibrary.addSprite("imgbed1","./sprites/imgbed1.jpg");s_oSpriteLibrary.addSprite("imgbed2","./sprites/imgbed2.jpg");s_oSpriteLibrary.addSprite("imgbed3","./sprites/imgbed3.jpg");s_oSpriteLibrary.addSprite("imgbed4","./sprites/imgbed4.jpg");s_oSpriteLibrary.addSprite("imgisland1","./sprites/imgisland1.jpg");s_oSpriteLibrary.addSprite("imgisland2","./sprites/imgisland2.jpg");s_oSpriteLibrary.addSprite("imgisland3",
"./sprites/imgisland3.jpg");s_oSpriteLibrary.addSprite("imgisland4","./sprites/imgisland4.jpg");s_oSpriteLibrary.addSprite("imgwine1","./sprites/imgwine1.jpg");s_oSpriteLibrary.addSprite("imgwine2","./sprites/imgwine2.jpg");s_oSpriteLibrary.addSprite("imgwine3","./sprites/imgwine3.jpg");s_oSpriteLibrary.addSprite("imgwine4","./sprites/imgwine4.jpg");s_oSpriteLibrary.addSprite("imground1","./sprites/imground1.jpg");s_oSpriteLibrary.addSprite("imground2","./sprites/imground2.jpg");s_oSpriteLibrary.addSprite("imground3",
"./sprites/imground3.jpg");s_oSpriteLibrary.addSprite("imground4","./sprites/imground4.jpg");s_oSpriteLibrary.addSprite("imgiron1","./sprites/imgiron1.jpg");s_oSpriteLibrary.addSprite("imgiron2","./sprites/imgiron2.jpg");s_oSpriteLibrary.addSprite("imgiron3","./sprites/imgiron3.jpg");s_oSpriteLibrary.addSprite("imgiron4","./sprites/imgiron4.jpg");s_oSpriteLibrary.addSprite("but_menu","./sprites/but_menu.png");s_oSpriteLibrary.addSprite("shadow","./sprites/shadow_of_images.png");s_oSpriteLibrary.addSprite("but_fullscreen",
"./sprites/but_fullscreen.png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){e++;a.refreshLoader(Math.floor(e/d*100));e===d&&this._onRemovePreloader()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._onRemovePreloader=function(){a.unload();isIOS()||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1}));this.gotoMenu()};this.gotoMenu=function(){new CMenu;
c=STATE_MENU};this.gotoGame=function(a){h=new CGame(a,k);c=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoGameOver=function(a){new CGameOver(a)};this.gotoLanguage=function(){new CLanguageMenu};this.stopUpdate=function(){f=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();f=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};
this._update=function(a){if(!1!==f){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);c===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;k=b;ENABLE_CHECK_ORIENTATION=b.check_orientation;ENABLE_FULLSCREEN=b.fullscreen;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack=null,s_oCanvas,s_iLanguageSelected,s_oSpriteSheetLora,s_aQuestions,s_bFullscreen=!1;
function CTextButton(b,f,e,d,c,k,a,h){var m,g,p,t,q,r,n,u,v,l,y,x,z,w={};this._init=function(a,b,c,e,d,f,r){m=!1;g=1;z=!1;u=[];v=[];var A=createBitmap(c),n=Math.ceil(r/20);x=new createjs.Text(e,"bold "+r+"px "+d,"#000000");x.textAlign="center";x.textBaseline="alphabetic";var k=x.getBounds();x.x=c.width/2+n;x.y=Math.floor(c.height/2+k.height/3+n)+h;x.alpha=.5;y=new createjs.Text(e,"bold "+r+"px "+d,f);y.textAlign="center";y.textBaseline="alphabetic";k=y.getBounds();y.x=c.width/2;y.y=Math.floor(c.height/
2+k.height/3)+h;l=new createjs.Container;l.x=a;l.y=b;l.regX=c.width/2;l.regY=c.height/2;l.addChild(A,x,y);s_oStage.addChild(l);l.cursor="pointer";this._initListener()};this.setExtraData=function(a,b){w[a]=b};this.getExtraData=function(a){return w[a]};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setUsed=function(a){z=a};this.getUsed=function(){return z};this.getID=function(){return n};this.setCursorType=function(a){l.cursor=a};this.setTextCenterX=function(a){y+=
a;y+=a};this.changeChildIndex=function(a){s_oStage.setChildIndex(l,a)};this.setVisible=function(a){l.visible=a};this.getVisible=function(){return l.visible};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){u[a]=b;v[a]=c};this.addEventListenerWithParams=function(a,b,c,e,d,g,f,m){u[a]=b;v[a]=c;p=e;t=f;q=d;r=g;n=m};this.buttonRelease=function(){m||(l.scaleX=1*g,l.scaleY=1*g,u[ON_MOUSE_UP]&&u[ON_MOUSE_UP].call(v[ON_MOUSE_UP],
p,q,r,t,n))};this.buttonDown=function(){m||(l.scaleX=.9*g,l.scaleY=.9*g,u[ON_MOUSE_DOWN]&&u[ON_MOUSE_DOWN].call(v[ON_MOUSE_DOWN],p,q,r,t,n))};this.setTextPosition=function(a){y.y=a;x.y=a+2};this.getText=function(){return y.text};this.setText=function(a){y.text=a;x.text=a};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this.block=function(a){m=
a};this.setScale=function(a){g=a;l.scaleX=a;l.scaleY=a};this._init(b,f,e,d,c,k,a);return this}
function CTextToggle(b,f,e,d,c,k,a,h,m){var g=1,p,t=!1,q,r,n,u,v,l;this._init=function(a,b,c,e,d,g,f,m,k){p=!1;q=[];r=[];l=createBitmap(c);var A=Math.ceil(f/20);v=new createjs.Text(e," "+f+"px "+d,"#000000");v.textAlign="center";v.textBaseline="alphabetic";var h=v.getBounds();v.x=c.width/2+A;v.y=Math.floor(c.height/2)+h.height/3+A-7;u=new createjs.Text(e," "+f+"px "+d,g);u.textAlign="center";u.textBaseline="alphabetic";h=u.getBounds();u.x=c.width/2;u.y=Math.floor(c.height/2)+h.height/3-7;n=new createjs.Container;
n.x=a;n.y=b;n.regX=c.width/2;n.regY=c.height/2;m||(a=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}}),l=createSprite(a,"state_false",c.width/2/2,c.height/2,c.width/2,c.height),v.x=A,v.y=A+17,u.x=0,u.y=17,n.regX=0,n.regY=0);n.addChild(l,v,u);k.addChild(n);n.cursor="pointer";this._initListener()};this.unload=function(){n.off("mousedown");n.off("pressup");m.removeChild(n)};this.setVisible=function(a){n.visible=
a};this._initListener=function(){oParent=this;n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){q[a]=b;r[a]=c};this.buttonRelease=function(){p||t||(n.scaleX=1*g,n.scaleY=1*g,q[ON_MOUSE_UP]&&q[ON_MOUSE_UP].call(r[ON_MOUSE_UP]))};this.buttonDown=function(){p||t||(n.scaleX=.9*g,n.scaleY=.9*g,q[ON_MOUSE_DOWN]&&q[ON_MOUSE_DOWN].call(r[ON_MOUSE_DOWN]))};this.enable=function(){p=!1;h||l.gotoAndStop("state_true")};this.disable=function(){p=!0;h||l.gotoAndStop("state_false")};
this.setTextPosition=function(b,c){var e=Math.ceil(a/20);v.x=b+e;v.y=c+e;u.x=b;u.y=c};this.setText=function(a){u.text=a;v.text=a};this.setPosition=function(a,b){n.x=a;n.y=b};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this.block=function(a){t=a};this.setScale=function(a){g=a;n.scaleX=a;n.scaleY=a};this.setScaleX=function(a){l.scaleX=a};this._init(b,f,e,d,c,k,a,h,m);return this}
function CToggle(b,f,e,d){var c,k,a,h;this._init=function(b,e,d,f){k=[];a=[];var g=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}});c=f;h=createSprite(g,"state_"+c,d.width/2/2,d.height/2,d.width/2,d.height);h.x=b;h.y=e;h.stop();s_oStage.addChild(h);h.cursor="pointer";this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);s_oStage.removeChild(h)};
this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(b,c,e){k[b]=c;a[b]=e};this.setActive=function(a){c=a;h.gotoAndStop("state_"+c)};this.setCursorType=function(a){h.cursor=a};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");c=!c;h.gotoAndStop("state_"+c);k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(a[ON_MOUSE_UP],c)};this.buttonDown=function(){h.scaleX=.9;
h.scaleY=.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(a[ON_MOUSE_DOWN])};this.setPosition=function(a,b){h.x=a;h.y=b};this._init(b,f,e,d)}
function CGfxButton(b,f,e){var d,c,k,a,h,m,g,p,t,q;this._init=function(b,e,f){d=!1;q=1;c=[];k=[];a=createBitmap(f);a.x=b;a.y=e;a.regX=f.width/2;a.regY=f.height/2;s_oStage.addChild(a);a.cursor="pointer";this._initListener()};this.changeChildIndex=function(b){s_oStage.setChildIndex(a,b)};this.unload=function(){a.off("mousedown",this.buttonDown);a.off("pressup",this.buttonRelease);s_oStage.removeChild(a)};this.setVisible=function(b){a.visible=b};this.getVisible=function(){return a.visible};this._initListener=
function(){a.on("mousedown",this.buttonDown);a.on("pressup",this.buttonRelease)};this.setCursorType=function(b){a.cursor=b};this.setAlpha=function(b){a.alpha=b};this.addEventListener=function(a,b,e){c[a]=b;k[a]=e};this.addEventListenerWithParams=function(a,b,e,d,f,q,x,z){c[a]=b;k[a]=e;h=d;m=x;g=f;p=q;t=z};this.buttonRelease=function(){d||(a.scaleX=1*q,a.scaleY=1*q,c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(k[ON_MOUSE_UP],h,g,p,m,t))};this.buttonDown=function(){d||(a.scaleX=.95*q,a.scaleY=.95*q,c[ON_MOUSE_DOWN]&&
c[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],h,g,p,m,t))};this.getScale=function(){return q};this.setPosition=function(b,c){a.x=b;a.y=c};this.setX=function(b){a.x=b};this.setY=function(b){a.y=b};this.getButtonImage=function(){return a};this.getX=function(){return a.x};this.getY=function(){return a.y};this.block=function(a){d=a};this.setScale=function(b){q=b;a.scaleX=b;a.scaleY=b};this._init(b,f,e);return this}
function CMenu(){var b,f,e,d,c,k,a,h,m,g,p,t=null,q,r=null,n=null;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(a);var t=s_oSpriteLibrary.getSprite("but_play");h=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+560,t);h.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);t=s_oSpriteLibrary.getSprite("audio_icon");!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(c=CANVAS_WIDTH-t.height/2-PADDING,k=t.height/2+PADDING,g=new CToggle(c,k,t,s_bAudioActive),g.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this),b=c-t.width/2-10,f=k):(b=CANVAS_WIDTH-t.height/2-PADDING,f=t.height/2+PADDING);SHOW_CREDITS&&(p=new CGfxButton(b,f,s_oSpriteLibrary.getSprite("but_credits"),!0),p.addEventListener(ON_MOUSE_UP,this._onCredits,this));!1===s_bMobile&&(g.setCursorType("pointer"),h.setCursorType("pointer"));var t=window.document,v=t.documentElement;r=v.requestFullscreen||v.mozRequestFullScreen||v.webkitRequestFullScreen||v.msRequestFullscreen;n=t.exitFullscreen||t.mozCancelFullScreen||t.webkitExitFullscreen||
t.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(r=!1);r&&!1===inIframe()&&(t=s_oSpriteLibrary.getSprite("but_fullscreen"),e=t.width/4+10,d=f,q=new CToggle(e,d,t,s_bFullscreen,s_oStage),q.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(m);createjs.Tween.get(m).to({alpha:0},1E3).call(function(){s_oStage.removeChild(m);m=null});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=
function(){h.unload();h=null;SHOW_CREDITS&&p.unload();s_oStage.removeChild(a);a=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),g=null;r&&!1===inIframe()&&q.unload();s_oMenu=null};this.exitFromCredits=function(){t=null};this.refreshButtonPos=function(a,h){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||g.setPosition(c-a,h+k);SHOW_CREDITS&&p.setPosition(b-a,h+f);null!==t&&t.refreshButtonPos(a,h);r&&!1===inIframe()&&q.setPosition(e+a,d+h)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onCredits=function(){t=new CCreditsPanel};this._onButPlayRelease=function(){this.unload();if(isIOS()&&null===s_oSoundtrack){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1})}else!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoLanguage()};this._onFullscreenRelease=function(){s_bFullscreen?(n.call(window.document),s_bFullscreen=!1):(r.call(window.document.documentElement),s_bFullscreen=
!0);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(b,f){var e,d,c,k,a,h,m,g,p;this._init=function(){N_MAX_WORDS_TO_GUESS>NUMBER_OF_WORDS&&(N_MAX_WORDS_TO_GUESS=NUMBER_OF_WORDS);c=0;a=START_MONEY;p=0;d=new CGameSettings(b,c);d.loadQuest();d.showPicture();d.placeLetters();d.shuffleLetters();e=new CInterface(a);e.refreshNuMLevel(c);e.refreshMoney(a);$(s_oMain).trigger("start_level",{ilevel:c});k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);var f=s_oSpriteLibrary.getSprite("curtain_dx");m=createBitmap(f);
m.x=CANVAS_WIDTH;m.visible=!1;s_oStage.addChild(m);f=s_oSpriteLibrary.getSprite("curtain_sx");g=createBitmap(f);g.x=0;g.regX=f.width;g.visible=!1;s_oStage.addChild(g);g.addEventListener("click",function(){});m.addEventListener("click",function(){});s_oStage.addChild(k);createjs.Tween.get(k).to({alpha:0},1E3).call(function(){k.visible=!1})};this.wordGuessed=function(){c++;c<N_MAX_WORDS_TO_GUESS?(s_oStage.setChildIndex(m,s_oStage.getNumChildren()-1),s_oStage.setChildIndex(g,s_oStage.getNumChildren()-
1),m.visible=!0,g.visible=!0,createjs.Tween.get(g,{override:!0}).to({x:CANVAS_WIDTH/2},700,createjs.Ease.cubicOut),createjs.Tween.get(m,{override:!0}).to({x:CANVAS_WIDTH/2},700,createjs.Ease.cubicOut).call(function(){s_oGame.goToNextLevel(c,a)})):($(s_oMain).trigger("share_event",a),this.unload(),s_oMain.gotoGameOver(a))};this.goToNextLevel=function(a,b){d.setLevel(a);d.unloadQuest(c-1);d.loadQuest();d.showPicture();d.placeLetters();d.shuffleLetters();e.refreshNuMLevel(a);e.refreshMoney(b);e.resetCounter();
s_oStage.setChildIndex(m,s_oStage.getNumChildren()-1);s_oStage.setChildIndex(g,s_oStage.getNumChildren()-1);var f=s_oSpriteLibrary.getSprite("logo"),h=createBitmap(f);h.x=CANVAS_WIDTH/2;h.y=0;h.regX=f.width/2;h.regY=f.height/2;s_oStage.addChild(h);createjs.Tween.get(h,{override:!0}).to({y:CANVAS_HEIGHT/2},1300,createjs.Ease.elasticOut).call(function(){p++;p===NUM_QUIZ_FOR_ADS&&(p=0,$(s_oMain).trigger("show_interlevel_ad"));createjs.Tween.get(g,{override:!0}).wait(200).to({x:0},700,createjs.Ease.cubicOut);
createjs.Tween.get(m,{override:!0}).wait(200).to({x:CANVAS_WIDTH},700,createjs.Ease.cubicOut).call(function(){g.visible=!1;m.visible=!1;$(s_oMain).trigger("start_level",{ilevel:a});!0===BONUS_TIME&&s_oGame.stoppedTime(!1)});createjs.Tween.get(h,{override:!0}).wait(100).to({y:-f.height},700,createjs.Ease.backIn).call(function(){s_oStage.removeChild(h);h=null})})};this.animEarnedMoney=function(b){h=b+e.getCount();a+=h;e.addedMoneyAnim(h,2E3,"#00ff00");e.refreshMoney(a)};this.animSpentMoney=function(a){this.manageMoney(a);
e.addedMoneyAnim(a,2E3,"#ff0000")};this.manageMoney=function(b){a+=b;e.refreshMoney(a)};this.getMoney=function(){return a};this.restartGame=function(){this.unload();this._init()};this.stoppedTime=function(a){e.setStoppedTime(a)};this.unload=function(){e.unload();d.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("restart")};this.update=
function(){!0===BONUS_TIME&&e.update()};s_oGame=this;N_MAX_WORDS_TO_GUESS=f.words_to_guess;NUM_OF_SPAWN_LETTER=f.spawn_letters;START_MONEY=f.start_money;COST_OF_A_LETTER=f.cost_of_a_letter;COST_FOR_REMOVE_LETTERS=f.cost_for_remove_letters;TIME_FOR_EVERY_WORD=f.time_for_every_quest;NUM_QUIZ_FOR_ADS=f.num_quiz_before_ads;this._init()}var s_oGame;
function CGameSettings(b,f){var e,d,c=[],k=[],a,h,m,g,p,t,q,r,n,u,v,l,y,x,z,w;this._init=function(){e=b;l=f;t=0;h=[];m=[];g=[];y=[];z=[];x=0;w=!0;4<NUMBER_QUEST_IMAGE&&(NUMBER_QUEST_IMAGE=4);for(a=0;a<N_MAX_WORDS_TO_GUESS;a++)c[a]=Array(NUMBER_QUEST_IMAGE),k[a]=Array(NUMBER_QUEST_IMAGE);for(var d=0;d<NUMBER_OF_WORDS;d++)z[d]=d;z=shuffle(z);d=s_oSpriteLibrary.getSprite("success");n=createBitmap(d);n.x=CANVAS_WIDTH/2;n.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+50;n.regX=d.width/2;n.regY=d.height/2;n.visible=
!1;s_oStage.addChild(n);d=s_oSpriteLibrary.getSprite("mistake");r=createBitmap(d);r.x=CANVAS_WIDTH/2;r.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+50;r.regX=d.width/2;r.regY=d.height/2;r.visible=!1;s_oStage.addChild(r);d=s_oSpriteLibrary.getSprite("but_next");q=new CGfxButton(CANVAS_WIDTH/2+430,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+700,d);q.addEventListener(ON_MOUSE_UP,this._onNextLevel,this);q.setVisible(!1);q.setCursorType("pointer");d=s_oSpriteLibrary.getSprite("but_remove_letters");u=new CGfxButton(CANVAS_WIDTH/
2-100,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+940,d);u.addEventListener(ON_MOUSE_UP,this.removeSomeLetters,this);u.setCursorType("pointer");d=s_oSpriteLibrary.getSprite("but_add_a_letter");v=new CGfxButton(CANVAS_WIDTH/2+100,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+940,d);v.addEventListener(ON_MOUSE_UP,this.addALetter,this);v.setCursorType("pointer")};this.loadQuest=function(){d=s_aQuestions[z[l]].answer[e];for(var a=0;a<NUMBER_QUEST_IMAGE;a++){var b=s_oSpriteLibrary.getSprite(s_aQuestions[z[l]].img[0].file[a]);
c[l][a]=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT,b);b=s_oSpriteLibrary.getSprite("text_copyright");k[l][a]=new CText(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+320,b,s_aQuestions[z[l]].img[0].copyright[a],PRIMARY_FONT,"#ffffff",25,0);k[l][a].setVisible(!1)}};this.unloadQuest=function(b){for(var d=0;4>d;d++)c[b][d].unload(),c[b][d]=null,k[b][d].unload(),k[b][d]=null;for(a=0;a<p;a++)h[a].unload(),h[a]=null;for(a=0;a<NUM_OF_SPAWN_LETTER;a++)g[a].unload(),g[a]=null};
this.unload=function(){v.unload();v=null;s_oStage.removeChild(r);r=null;s_oStage.removeChild(n);n=null;u.unload();u=null;this.unloadQuest(l);s_oGameSettings=null};this.removeSomeLetters=function(){if(!(s_oGame.getMoney()<COST_FOR_REMOVE_LETTERS-1)){for(var a=[],b=0;b<NUM_OF_SPAWN_LETTER;b++)g[b].getVisible()&&a.push(g[b]);for(var c=3,e=!1,b=0;b<a.length;b++){for(var f=!0,h=0;h<p;h++)if(a[b].getText()===d.charAt(h)){f=!1;break}if(!0===f&&(a[b].setVisible(!1),m[a[b].getExtraData("boxposition")]=!1,
a[b].setExtraData("boxposition",null),c--,e=!0,0===c))break}!0===e&&s_oGame.animSpentMoney(-COST_FOR_REMOVE_LETTERS)}};this.addALetter=function(){var b=!0,c=0;if(!(s_oGame.getMoney()<COST_OF_A_LETTER-1)&&x<p&&s_oGame.getMoney()>COST_OF_A_LETTER-1)for(;!0===b;){var e=Math.floor(Math.random()*p);if(!0===m[e])c===p&&(b=!1),c++;else for(a=0;a<NUM_OF_SPAWN_LETTER;a++)if(g[a].getText()===d.charAt(e)&&!1===g[a].getUsed()){g[a].setPosition(h[e].getX(),h[e].getY());g[a].block(!0);g[a].setUsed(!0);y[e]=d.charAt(e);
g[a].setExtraData("boxposition",e);m[g[a].getExtraData("boxposition")]=!0;s_oGame.animSpentMoney(-COST_OF_A_LETTER);b=!1;x++;this.checkVictory();break}}};this._onNextLevel=function(){createjs.Tween.get(n).to({alpha:0},1E3,createjs.Ease.cubicOut).call(function(){n.visible=!1});q.setVisible(!1);x=t=0;s_oGame.wordGuessed()};this.placeLetters=function(){var b=0,c=s_oSpriteLibrary.getSprite("letter");for(a=0;a<NUM_OF_SPAWN_LETTER;a++){var f=Math.floor(Math.random()*ALPHABET[e].length);a<p?(0===a%2?g[a]=
new CTextButton(CANVAS_WIDTH/2-120*b+24*NUM_OF_SPAWN_LETTER,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+750,c,d.charAt(a),PRIMARY_FONT,"#382074",66,-10):(g[a]=new CTextButton(CANVAS_WIDTH/2-120*b+24*NUM_OF_SPAWN_LETTER,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+630,c,d.charAt(a),PRIMARY_FONT,"#382074",66,-10),b++),g[a].addEventListenerWithParams(ON_MOUSE_UP,this._onChooseWord,this,d.charAt(a),a)):(0===a%2?g[a]=new CTextButton(CANVAS_WIDTH/2-120*b+24*NUM_OF_SPAWN_LETTER,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+750,c,
ALPHABET[e][f],PRIMARY_FONT,"#382074",66,-10):(g[a]=new CTextButton(CANVAS_WIDTH/2-120*b+24*NUM_OF_SPAWN_LETTER,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+630,c,ALPHABET[e][f],PRIMARY_FONT,"#382074",66,-10),b++),g[a].addEventListenerWithParams(ON_MOUSE_UP,this._onChooseWord,this,ALPHABET[e][f],a));!1===s_bMobile&&g[a].setCursorType("pointer")}v.block(!1);u.block(!1)};this.returnPosition=function(b,c,d,e,f){g[d].setPosition(b,c);g[d].addEventListenerWithParams(ON_MOUSE_UP,this._onChooseWord,this,e,d);g[d].setUsed(!1);
y[f]=null;w=!0;createjs.Sound.play("click");!0===r.visible&&createjs.Tween.get(r).to({alpha:0},500,createjs.Ease.cubicOut).call(function(){r.visible=!1});m[f]=!1;a=0;for(b=!1;a<p&&!1===b;)!1===m[a]&&(t=a,b=!0),a++};this.shuffleLetters=function(){for(a=0;a<NUM_OF_SPAWN_LETTER;a++){var b=Math.floor(Math.random()*NUM_OF_SPAWN_LETTER),c=g[a].getX(),d=g[a].getY();g[a].setPosition(g[b].getX(),g[b].getY());g[b].setPosition(c,d)}};this._onChooseWord=function(a,b){if(t<p){for(var c=0,d=!1;c<p&&!1===d;)!1===
m[c]?(g[b].addEventListenerWithParams(ON_MOUSE_UP,this.returnPosition,this,g[b].getX(),g[b].getY(),b,g[b].getText(),c),g[b].setPosition(h[c].getX(),h[c].getY()),y[c]=a,m[c]=!0,g[b].setExtraData("boxposition",c),g[b].setUsed(!0),d=!0):t++,c++;t=c}createjs.Sound.play("click");this.checkVictory()};this.checkVictory=function(){var b=0;for(a=0;a<p;a++)!0===m[a]&&b++;if(!(b<p)&&b===p){b=!0;for(a=0;a<p;a++)y[a]!==d.charAt(a)&&(b=!1);if(!0===b){n.alpha=0;n.visible=!0;s_oStage.setChildIndex(n,s_oStage.getNumChildren()-
1);createjs.Tween.get(n).to({alpha:1},700,createjs.Ease.cubicOut);q.setVisible(!0);s_oGame.stoppedTime(!0);createjs.Sound.play("guessed");s_oGame.animEarnedMoney(p);for(a=0;a<NUM_OF_SPAWN_LETTER;a++)g[a].block(!0);for(b=0;b<NUMBER_QUEST_IMAGE;b++)c[l][b].block(!0);$(s_oMain).trigger("end_level",{ilevel:l});v.block(!0);u.block(!0)}else r.alpha=0,r.visible=!0,s_oStage.setChildIndex(r,s_oStage.getNumChildren()-1),createjs.Tween.get(r).to({alpha:1},700,createjs.Ease.cubicOut),!0===w&&(createjs.Sound.play("wrong"),
w=!1)}};this.setLevel=function(a){l=a};this.showPicture=function(){c[l][0].setPosition(CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-100);!1===s_bMobile&&c[l][0].setCursorType("pointer");switch(NUMBER_QUEST_IMAGE){case 2:c[l][1].setPosition(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-100);c[l][1].setCursorType("pointer");break;case 3:c[l][1].setPosition(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-100);c[l][2].setPosition(CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+
200);!1===s_bMobile&&(c[l][1].setCursorType("pointer"),c[l][2].setCursorType("pointer"));break;case 4:c[l][1].setPosition(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-100),c[l][2].setPosition(CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+200),c[l][3].setPosition(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+200),!1===s_bMobile&&(c[l][1].setCursorType("pointer"),c[l][2].setCursorType("pointer"),c[l][3].setCursorType("pointer"))}for(a=0;4>a;a++)this.addEventForImage(a,0);
p=d.length;var b=s_oSpriteLibrary.getSprite("letterbox");for(a=0;a<p;a++)h[a]=new CGfxButton(CANVAS_WIDTH/2+115*a-50*p,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+470,b,!0),h[a].block(!0),m[a]=!1};this.addEventForImage=function(a,b,d,e,f){0===b&&c[l][a].addEventListenerWithParams(ON_MOUSE_UP,this.zoomImage,this,c[l][a].getX(),c[l][a].getY(),c[l][a].getScale(),a);1===b&&(c[l][a].setPosition(d,e),c[l][a].setScale(f),c[l][a].addEventListenerWithParams(ON_MOUSE_UP,this.zoomImage,this,d,e,f,a),k[l][a].setVisible(!1))};
this.zoomImage=function(a,b,d,e){c[l][e].setPosition(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+50);c[l][e].setScale(2);c[l][e].changeChildIndex(s_oStage.getNumChildren()-5);c[l][e].addEventListenerWithParams(ON_MOUSE_UP,this.addEventForImage,this,e,1,a,b,d);k[l][e].setVisible(!0);k[l][e].changeChildIndex(s_oStage.getNumChildren()-4)};s_oGameSettings=this;this._init()}var s_oGameSettings;
function CGameOver(b){var f,e,d,c,k,a,h,m,g,p,t,q;this._init=function(){var r;q=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(q);$(s_oMain).trigger("save_score",s_oGame.getMoney());r=createBitmap(s_oSpriteLibrary.getSprite("bg_gameover"));s_oStage.addChild(r);r=s_oSpriteLibrary.getSprite("money_panel");k=new CTextButton(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2,r,b,PRIMARY_FONT,"#ffffff",50,-8);k.block(!0);k.setScale(1);r=s_oSpriteLibrary.getSprite("but_menu");d=new CGfxButton(CANVAS_WIDTH/
2,CANVAS_HEIGHT/2+270,r);d.addEventListener(ON_MOUSE_UP,this._onButToMenuRelease,this);h=new createjs.Text(TEXT_GAMEOVER,"bold 136px "+PRIMARY_FONT,"#ff21fe");h.textAlign="center";h.textBaseline="alphabetic";h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2-170;s_oStage.addChild(h);m=new createjs.Text(TEXT_GAMEOVER,"bold 136px "+PRIMARY_FONT,"#ffffff");m.textAlign="center";m.textBaseline="alphabetic";m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2-170;m.outline=4;s_oStage.addChild(m);r=CANVAS_WIDTH/2-180;var n=CANVAS_HEIGHT/
2+25;g=new createjs.Text(TEXT_SCORE,"bold 96px "+PRIMARY_FONT,"#ff21fe");g.textAlign="center";g.textBaseline="alphabetic";g.x=r;g.y=n;s_oStage.addChild(g);p=new createjs.Text(TEXT_SCORE,"bold 96px "+PRIMARY_FONT,"#ffffff");p.textAlign="center";p.textBaseline="alphabetic";p.x=r;p.y=n;p.outline=4;s_oStage.addChild(p);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n=s_oSpriteLibrary.getSprite("audio_icon"),r=CANVAS_WIDTH-n.width/2-100,f=r-15,e=n.height/2+110,a=new CToggle(f,e,n,s_bAudioActive),a.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(c);createjs.Tween.get(c).to({alpha:0},1E3).call(function(){c.visible=!1})};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.unload(),a=null;k.unload();k=null;d.unload();d=null;s_oStage.removeChild(t,q,m,m,g,p);s_oGameOver=p=g=m=h=q=t=null};this._onButToMenuRelease=function(){$(s_oMain).trigger("show_interlevel_ad");this.unload();!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoMenu()};s_oGameOver=this;this._init()}var s_oGameOver;
function CLanguageMenu(){var b,f,e,d,c,k,a,h,m,g,p,t,q,r,n,u,v,l,y,x=null,z=null;this._init=function(){v=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(v);var w=s_oSpriteLibrary.getSprite("logo_small");b=CANVAS_WIDTH/2-540+PADDING;f=CANVAS_HEIGHT/2-840+PADDING;l=createBitmap(w);l.x=b;l.y=f;l.regX=w.width/2;l.regY=w.height/2;s_oStage.addChild(l);n=new createjs.Text(TEXT_SELECT_LANG,"bold 104px "+PRIMARY_FONT,"#ff21fe");n.textAlign="center";n.textBaseline="alphabetic";n.x=CANVAS_WIDTH/
2;n.y=CANVAS_HEIGHT/2-300;s_oStage.addChild(n);u=new createjs.Text(TEXT_SELECT_LANG,"bold 104px "+PRIMARY_FONT,"#ffffff");u.textAlign="center";u.textBaseline="alphabetic";u.x=CANVAS_WIDTH/2;u.y=CANVAS_HEIGHT/2-300;u.outline=4;s_oStage.addChild(u);w=s_oSpriteLibrary.getSprite("but_flag_it");m=new CGfxButton(CANVAS_WIDTH/2+350,CANVAS_HEIGHT/2-100,w);m.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,2);m.regX=128;m.regY=90;w=s_oSpriteLibrary.getSprite("but_flag_en");g=new CGfxButton(CANVAS_WIDTH/
2-350,CANVAS_HEIGHT/2-100,w);g.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,0);g.regX=128;g.regY=90;w=s_oSpriteLibrary.getSprite("but_flag_fr");p=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2-100,w);p.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,1);p.regX=128;p.regY=90;w=s_oSpriteLibrary.getSprite("but_flag_es");t=new CGfxButton(CANVAS_WIDTH/2+350,CANVAS_HEIGHT/2+150,w);t.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,3);t.regX=128;t.regY=
90;w=s_oSpriteLibrary.getSprite("but_flag_ger");q=new CGfxButton(CANVAS_WIDTH/2-350,CANVAS_HEIGHT/2+150,w);q.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,4);q.regX=128;q.regY=90;w=s_oSpriteLibrary.getSprite("but_flag_por");r=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+150,w);r.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,5);r.regX=128;r.regY=90;w=s_oSpriteLibrary.getSprite("audio_icon");!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(c=CANVAS_WIDTH-w.height/
2-PADDING,k=w.height/2+PADDING,h=new CToggle(c,k,w,s_bAudioActive),h.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),e=c-w.width/2-10,d=k):(e=CANVAS_WIDTH-w.height/2-PADDING,d=w.height/2+PADDING);var w=window.document,A=w.documentElement;x=A.requestFullscreen||A.mozRequestFullScreen||A.webkitRequestFullScreen||A.msRequestFullscreen;z=w.exitFullscreen||w.mozCancelFullScreen||w.webkitExitFullscreen||w.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(x=!1);x&&!1===inIframe()&&(w=s_oSpriteLibrary.getSprite("but_fullscreen"),
y=new CToggle(e,d,w,s_bFullscreen,s_oStage),y.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(a);createjs.Tween.get(a).to({alpha:0},1E3).call(function(){s_oStage.removeChild(a);a=null});!1===s_bMobile&&(h.setCursorType("pointer"),g.setCursorType("pointer"),t.setCursorType("pointer"),p.setCursorType("pointer"),q.setCursorType("pointer"),m.setCursorType("pointer"),r.setCursorType("pointer"));
this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){m.unload();m=null;g.unload();g=null;p.unload();p=null;t.unload();t=null;q.unload();q=null;r.unload();r=null;s_oStage.removeChild(u,n,l);l=n=u=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h.unload(),h=null;x&&!1===inIframe()&&y.unload();s_oLanguageMenu=null};this.refreshButtonPos=function(a,g){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||h.setPosition(c-a,g+k);x&&!1===inIframe()&&y.setPosition(e-a,d+g);l.x=b+a;l.y=f+g};this._onAudioToggle=
function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(a){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");$(s_oMain).trigger("start_session");s_oMain.gotoGame(a)};this._onFullscreenRelease=function(){s_bFullscreen?(z.call(window.document),s_bFullscreen=!1):(x.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oLanguageMenu=this;this._init()}var s_oLanguageMenu=null;
function CInterface(b){var f,e,d,c,k,a,h,m,g,p,t,q,r,n,u,v,l,y,x,z,w,A,E,C,B,F,D,G,H,J,I=null,K=null;this._init=function(){var g;x=TIME_FOR_EVERY_WORD;z=!0;g=s_oSpriteLibrary.getSprite("logo_small");d=CANVAS_WIDTH/2-540+PADDING;c=CANVAS_HEIGHT/2-840+PADDING;F=createBitmap(g);F.x=d;F.y=c;F.regX=g.width/2;F.regY=g.height/2;s_oStage.addChild(F);var q=s_oSpriteLibrary.getSprite("but_exit");h=CANVAS_WIDTH-q.height/2-PADDING;m=q.height/2+PADDING;t=new CGfxButton(h,m,q,!0);t.addEventListener(ON_MOUSE_UP,
this._onExit,this);g=CANVAS_WIDTH-q.width/2-10;!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(k=g-165-PADDING,a=q.height/2+PADDING,q=s_oSpriteLibrary.getSprite("audio_icon"),p=new CToggle(k,a,q,s_bAudioActive),p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),f=k-q.width/2-10,e=a):(f=g-165-PADDING,e=q.height/2+PADDING);g=window.document;q=g.documentElement;I=q.requestFullscreen||q.mozRequestFullScreen||q.webkitRequestFullScreen||q.msRequestFullscreen;K=g.exitFullscreen||g.mozCancelFullScreen||
g.webkitExitFullscreen||g.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(I=!1);I&&!1===inIframe()&&(q=s_oSpriteLibrary.getSprite("but_fullscreen"),J=new CToggle(f,e,q,s_bFullscreen,s_oStage),J.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));g=s_oSpriteLibrary.getSprite("shadow");E=createBitmap(g);E.x=CANVAS_WIDTH/2;E.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+50;E.regX=g.width/2;E.regY=g.height/2;s_oStage.addChild(E);r=new createjs.Text(TEXT_LEVEL+"/n1","bold 60px "+PRIMARY_FONT,"#ff21fe");r.textAlign=
"center";r.textBaseline="alphabetic";r.y=-15;n=new createjs.Text(TEXT_LEVEL+"/n1","bold 60px "+PRIMARY_FONT,"#ffffff");n.textAlign="center";n.textBaseline="alphabetic";n.outline=6;n.y=-15;g=s_oSpriteLibrary.getSprite("level_panel");u=createBitmap(g);u.regX=g.width/2;u.regY=g.height/2;v=new createjs.Container;v.x=CANVAS_WIDTH/2;v.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-370;v.addChild(u,n,r);s_oStage.addChild(v);g=s_oSpriteLibrary.getSprite("money_panel");l=new CText(CANVAS_WIDTH/2-300,CANVAS_HEIGHT/
2+GAME_ELEMENT_HEIGHT-340,g,b+TEXT_PT,PRIMARY_FONT,"#ffffff",66,-10);s_oStage.addChild(w);!0===BONUS_TIME?(y=new CText(CANVAS_WIDTH/2+300,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-340,g,x+"s",PRIMARY_FONT,"#ffffff",66,-10),s_oStage.addChild(A)):x=0;this.helpPanel();this.refreshButtonPos(s_iOffsetX,s_iOffsetY);!1===s_bMobile&&(t.setCursorType("pointer"),p.setCursorType("pointer"))};this.helpPanel=function(){var a=s_oSpriteLibrary.getSprite("bg_gameover");q=createBitmap(a);q.addEventListener("click",function(){});
s_oStage.addChild(q);C=new createjs.Text(TEXT_HELP,"bold 70px "+PRIMARY_FONT,"#ff21fe");C.textAlign="left";C.textBaseline="alphabetic";C.lineWidth=600;C.x=CANVAS_WIDTH/2-260;C.y=CANVAS_HEIGHT/2-150;s_oStage.addChild(C);B=new createjs.Text(TEXT_HELP,"bold 70px "+PRIMARY_FONT,"#ffffff");B.textAlign="left";B.textBaseline="alphabetic";B.lineWidth=600;B.x=CANVAS_WIDTH/2-260;B.y=CANVAS_HEIGHT/2-150;B.outline=3;s_oStage.addChild(B);a=s_oSpriteLibrary.getSprite("but_next");D=new CGfxButton(CANVAS_WIDTH/2+
460,CANVAS_HEIGHT/2,a);D.addEventListener(ON_MOUSE_UP,this._onNextHelp2,this);0==s_bMobile&&D.setCursorType("pointer")};this._onNextHelp2=function(){D.unload();D=null;this.helpPanel2()};this.helpPanel2=function(){var a=s_oSpriteLibrary.getSprite("but_next");D=new CGfxButton(CANVAS_WIDTH/2+460,CANVAS_HEIGHT/2,a);D.addEventListener(ON_MOUSE_UP,this._onStartGame,this);0==s_bMobile&&D.setCursorType("pointer");a=s_oSpriteLibrary.getSprite("but_remove_letters");H=createBitmap(a);H.x=CANVAS_WIDTH/2-340;
H.y=CANVAS_HEIGHT/2+240;H.regX=a.width/2;H.regY=a.height/2;s_oStage.addChild(H);a=s_oSpriteLibrary.getSprite("but_add_a_letter");G=createBitmap(a);G.x=CANVAS_WIDTH/2-340;G.y=CANVAS_HEIGHT/2-145;G.regX=a.width/2;G.regY=a.height/2;s_oStage.addChild(G);C.text=TEXT_HELP2+COST_FOR_REMOVE_LETTERS+TEXT_PT+"."+TEXT_HELP3+COST_OF_A_LETTER+TEXT_PT+".";C.x=CANVAS_WIDTH/2-190;C.y=CANVAS_HEIGHT/2-230;B.text=TEXT_HELP2+COST_FOR_REMOVE_LETTERS+TEXT_PT+"."+TEXT_HELP3+COST_OF_A_LETTER+TEXT_PT+".";B.x=CANVAS_WIDTH/
2-190;B.y=CANVAS_HEIGHT/2-230};this._onStartGame=function(){s_oStage.removeChild(B,C,q,G,H);D.unload();C=q=B=D=null;z=!1;H=G=null};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;I&&!1===inIframe()&&J.unload();s_oStage.removeChild(E);E=null;t.unload();t=null;s_oStage.removeChild(v);v=null;s_oStage.removeChild(r);r=null;l.unload();l=null;s_oStage.removeChild(w);w=null;s_oStage.removeChild(A);A=null;y.unload();y=null;s_oStage.removeChild(g);g=null;null!==q&&q.unload();
s_oInterface=null};this.addedMoneyAnim=function(a,b,c){var d;0<a?(c=new createjs.Text("+"+a,"bold 66px "+PRIMARY_FONT,c),a=new createjs.Text("+"+a,"bold 66px "+PRIMARY_FONT,"#ffffff")):(c=new createjs.Text(a,"bold 66px "+PRIMARY_FONT,c),a=new createjs.Text(a,"bold 66px "+PRIMARY_FONT,"#ffffff"));c.textAlign="center";c.textBaseline="alphabetic";a.textAlign="center";a.textBaseline="alphabetic";a.outline=4;d=new createjs.Container;d.x=CANVAS_WIDTH/2-150;d.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-330;d.addChild(c,
a);s_oStage.addChild(d);createjs.Tween.get(d).to({y:CANVAS_HEIGHT/2-500},b);createjs.Tween.get(d).to({alpha:0},b).call(function(){s_oStage.removeChild(d);d=null})};this.setStoppedTime=function(a){z=a};this.resetCounter=function(){x=TIME_FOR_EVERY_WORD;y.setText(x+"s")};this.refreshButtonPos=function(b,g){t.setPosition(h-b,g+m);F.x=d+b;F.y=c+g;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(k-b,g+a);I&&!1===inIframe()&&J.setPosition(f-b,e+g)};this.refreshMoney=function(a){l.setText(a+"PT")};
this.refreshNuMLevel=function(a){a+=1;r.text=TEXT_LEVEL+"\n"+a;n.text=TEXT_LEVEL+"\n"+a};this.getCount=function(){return Math.round(x)};this.update=function(){if(0<x&&!1===z){var a=createjs.Ticker.getFPS();x-=1/a;y.setText(Math.round(x)+"s")}};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?(K.call(window.document),s_bFullscreen=!1):(I.call(window.document.documentElement),
s_bFullscreen=!0);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CText(b,f,e,d,c,k,a,h){var m,g,p;this._init=function(a,b,c,d,e,f,l){var k=createBitmap(c),n=Math.ceil(l/20);p=new createjs.Text(d,"bold "+l+"px "+e,"#000000");p.textAlign="center";p.textBaseline="alphabetic";var q=p.getBounds();p.x=c.width/2+n;p.y=Math.floor(c.height/2+q.height/3+n)+h;p.alpha=.5;g=new createjs.Text(d,"bold "+l+"px "+e,f);g.textAlign="center";g.textBaseline="alphabetic";q=g.getBounds();g.x=c.width/2;g.y=Math.floor(c.height/2+q.height/3)+h;m=new createjs.Container;m.x=a;m.y=
b;m.regX=c.width/2;m.regY=c.height/2;m.addChild(k,p,g);s_oStage.addChild(m);this._initListener()};this._initListener=function(){oParent=this};this.setText=function(a){g.text=a;p.text=a};this.changeChildIndex=function(a){null!==e?s_oStage.setChildIndex(m,a):s_oStage.setChildIndex(g,a)};this.setVisible=function(a){m.visible=a};this.unload=function(){s_oStage.removeChild(m)};this._init(b,f,e,d,c,k,a);return this}TEXT_GAMEOVER="GAME OVER";TEXT_SCORE="SCORE";TEXT_LEVEL="LEVEL";TEXT_PT="PT";TEXT_HELP="Guess the word that links the 4 pics as fast as possible!If you use a help, yourscore will decrease!";
TEXT_HELP2="Add a random\nletters to the\nsolution. This help\nwill cost you ";TEXT_HELP3="Remove some letters from the display. It will cost you ";TEXT_SELECT_LANG="SELECT LANGUAGE";TEXT_CONGRATULATIONS="Congratulations!";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CCreditsPanel(){var b,f,e,d,c,k,a,h;this._init=function(){e=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(e);a=new createjs.Shape;a.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=.01;a.on("click",this._onLogoButRelease);s_oStage.addChild(a);var m=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-m.height/2-PADDING;f=m.height/2+PADDING;c=new CGfxButton(b,f,m,s_oStage);c.addEventListener(ON_MOUSE_UP,this.unload,this);k=new createjs.Text(TEXT_CREDITS_DEVELOPED,
"60px "+PRIMARY_FONT,"#ff21fe");k.textAlign="center";k.textBaseline="alphabetic";k.x=CANVAS_WIDTH/2;k.y=700;s_oStage.addChild(k);m=s_oSpriteLibrary.getSprite("logo_ctl");d=createBitmap(m);d.regX=m.width/2;d.regY=m.height/2;d.x=CANVAS_WIDTH/2;d.y=820;s_oStage.addChild(d);h=new createjs.Text("www.codethislab.com","60px "+PRIMARY_FONT,"#ff21fe");h.textAlign="center";h.textBaseline="alphabetic";h.x=CANVAS_WIDTH/2;h.y=950;s_oStage.addChild(h);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=
function(a,d){c.setPosition(b-a,d+f)};this.unload=function(){a.off("click",this._onLogoButRelease);c.unload();c=null;s_oStage.removeChild(e);s_oStage.removeChild(d);s_oStage.removeChild(a);s_oStage.removeChild(h);s_oStage.removeChild(k);s_oMenu.exitFromCredits()};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()};
