function CCell(d,f,c,b,k,g){var h,a,m;this._init=function(c,b,e,d,g,f){a=s_oSpriteLibrary.getSprite("cubes_sprite");c=new createjs.SpriteSheet({images:[a],frames:{width:CELL_WIDTH,height:CELL_HEIGHT,regX:CELL_WIDTH/2,regY:CELL_HEIGHT/2},animations:{background:[0],form0:[1],form1:[2],form2:[3],form3:[4],form4:[5],form5:[6],form6:[7],form7:[8],form8:[9],hide:[10]}});b=createSprite(c,"background",0,0,CELL_WIDTH,CELL_HEIGHT);b.x=e;b.y=d;g.addChild(b);m=createSprite(c,"hide",0,0,CELL_WIDTH,CELL_HEIGHT);
m.x=e;m.y=d;h=f;g.addChild(m)};this.changeCellState=function(a){m.gotoAndStop(a);h=a};this.changeScaleandState=function(){createjs.Tween.get(m).to({scaleX:1.2,scaleY:1.2},300,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(m).to({scaleX:.1,scaleY:.1,alpha:.3},300,createjs.Ease.cubicIn).call(function(){this.gotoAndStop("hide");this.alpha=this.scaleY=this.scaleX=1;h=0;s_oGame._setScore();s_oGame.decreaseCellToDeleteCounter()})})};this.getValue=function(){return h};s_oCell=this;this._init(d,
f,c,b,k,g)}
function CEndPanel(d){var f,c,b,k;this._init=function(d){f=createBitmap(d);f.x=0;f.y=0;b=new createjs.Text(""," 60px "+FONT,"#ffffff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2-150;b.textAlign="center";b.textBaseline="alphabetic";b.lineWidth=500;k=new createjs.Text(""," 60px "+FONT,"#ffffff");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2+40;k.textAlign="center";k.textBaseline="alphabetic";k.lineWidth=500;c=new createjs.Container;c.alpha=0;c.visible=!1;c.addChild(f,k,b);s_oStage.addChild(c)};this.unload=function(){c.off("mousedown",
this._onExit)};this._initListener=function(){c.on("mousedown",this._onExit)};this.show=function(d){b.text=TEXT_GAMEOVER;k.text=TEXT_SCORE+d;c.visible=!0;var h=this;createjs.Tween.get(c).to({alpha:1},500).call(function(){h._initListener()});$(s_oMain).trigger("share_event",d);$(s_oMain).trigger("save_score",d)};this._onExit=function(){c.off("mousedown",this._onExit);s_oStage.removeChild(c);s_oGame.onExit()};this._init(d);return this}
function CForms(d,f){var c=[{x:0,y:0,sprite:0},{x:0,y:0,sprite:0},{x:0,y:0,sprite:0},{x:0,y:0,sprite:0},{x:0,y:0,sprite:0},{x:0,y:0,sprite:0},{x:0,y:0,sprite:0},{x:0,y:0,sprite:0},{x:0,y:0,sprite:0}],b=[],k,g,h={x:0,y:0};this._init=function(a,d){var f={images:[s_oSpriteLibrary.getSprite("cubes_sprite")],frames:{width:CELL_WIDTH,height:CELL_HEIGHT,regX:0,regY:0},animations:{background:[0],form0:[1],form1:[2],form2:[3],form3:[4],form4:[5],form5:[6],form6:[7],form7:[8],form8:[9]}};switch(a){case 0:h.x=
50-CELL_WIDTH/2;break;case 1:h.x=265-CELL_WIDTH/2;break;case 2:h.x=475-CELL_WIDTH/2}g=new createjs.Container;switch(d){case 0:h.y=CANVAS_HEIGHT-180;g.x=h.x;g.y=h.y;var l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0-CELL_WIDTH,0-CELL_HEIGHT,7*CELL_WIDTH+7*OFFSET_X,3*CELL_HEIGHT+3*OFFSET_Y);g.addChild(l);for(a=0;5>a;a++)c[a].x=a,c[a].sprite=4,l=new createjs.SpriteSheet(f),b.push(createSprite(l,4,0,0,CELL_WIDTH,CELL_HEIGHT)),b[a].x=CELL_WIDTH*a+OFFSET_X*a,b[a].gotoAndStop(4),
g.addChild(b[a]);break;case 1:h.x+=60;h.y=CANVAS_HEIGHT-280;g.x=h.x;g.y=h.y;l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0-CELL_WIDTH,0-CELL_HEIGHT,3*CELL_WIDTH+3*OFFSET_X,7*CELL_HEIGHT+7*OFFSET_Y);g.addChild(l);for(a=0;5>a;a++)c[a].y=a,c[a].sprite=4,l=new createjs.SpriteSheet(f),b.push(createSprite(l,4,0,0,CELL_WIDTH,CELL_HEIGHT)),b[a].y=CELL_HEIGHT*a+OFFSET_Y*a,b[a].gotoAndStop(4),g.addChild(b[a]);break;case 2:h.x+=15;h.y=CANVAS_HEIGHT-180;g.x=h.x;g.y=h.y;l=new createjs.Shape;
l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0-CELL_WIDTH,0-CELL_HEIGHT,6*CELL_WIDTH+6*OFFSET_X,3*CELL_HEIGHT+3*OFFSET_Y);g.addChild(l);for(a=0;4>a;a++)c[a].x=a,c[a].sprite=3,l=new createjs.SpriteSheet(f),b.push(createSprite(l,3,0,0,CELL_WIDTH,CELL_HEIGHT)),b[a].x=CELL_WIDTH*a+OFFSET_X*a,b[a].gotoAndStop(3),g.addChild(b[a]);break;case 3:h.x+=60;h.y=CANVAS_HEIGHT-250;g.x=h.x;g.y=h.y;l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0-CELL_WIDTH,0-CELL_HEIGHT,3*
CELL_WIDTH+3*OFFSET_X,6*CELL_HEIGHT+6*OFFSET_Y);g.addChild(l);for(a=0;4>a;a++)c[a].y=a,c[a].sprite=3,l=new createjs.SpriteSheet(f),b.push(createSprite(l,3,0,0,CELL_WIDTH,CELL_HEIGHT)),b[a].y=CELL_HEIGHT*a+OFFSET_Y*a,b[a].gotoAndStop(3),g.addChild(b[a]);break;case 4:h.x+=25;h.y=CANVAS_HEIGHT-180;g.x=h.x;g.y=h.y;l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0-CELL_WIDTH,0-CELL_HEIGHT,5*CELL_WIDTH+5*OFFSET_X,3*CELL_HEIGHT+3*OFFSET_Y);g.addChild(l);for(a=0;3>a;a++)c[a].x=
a,c[a].sprite=2,l=new createjs.SpriteSheet(f),b.push(createSprite(l,2,0,0,CELL_WIDTH,CELL_HEIGHT)),b[a].x=CELL_WIDTH*a+OFFSET_X*a,b[a].gotoAndStop(2),g.addChild(b[a]);break;case 5:h.x+=60;h.y=CANVAS_HEIGHT-230;g.x=h.x;g.y=h.y;l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0-CELL_WIDTH,0-CELL_HEIGHT,3*CELL_WIDTH+3*OFFSET_X,5*CELL_HEIGHT+5*OFFSET_Y);g.addChild(l);for(a=0;3>a;a++)c[a].y=a,c[a].sprite=2,l=new createjs.SpriteSheet(f),b.push(createSprite(l,2,0,0,CELL_WIDTH,
CELL_HEIGHT)),b[a].y=CELL_HEIGHT*a+OFFSET_Y*a,b[a].gotoAndStop(2),g.addChild(b[a]);break;case 6:h.x+=40;h.y=CANVAS_HEIGHT-180;g.x=h.x;g.y=h.y;l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0-CELL_WIDTH,0-CELL_HEIGHT,4*CELL_WIDTH+4*OFFSET_X,3*CELL_HEIGHT+3*OFFSET_Y);g.addChild(l);for(a=0;2>a;a++)c[a].x=a,c[a].sprite=1,l=new createjs.SpriteSheet(f),b.push(createSprite(l,1,0,0,CELL_WIDTH,CELL_HEIGHT)),b[a].x=CELL_WIDTH*a+OFFSET_X*a,b[a].gotoAndStop(1),g.addChild(b[a]);break;
case 7:h.x+=60;h.y=CANVAS_HEIGHT-205;g.x=h.x;g.y=h.y;l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0-CELL_WIDTH,0-CELL_HEIGHT,3*CELL_WIDTH+3*OFFSET_X,4*CELL_HEIGHT+4*OFFSET_Y);g.addChild(l);for(a=0;2>a;a++)c[a].y=a,c[a].sprite=1,l=new createjs.SpriteSheet(f),b.push(createSprite(l,1,0,0,CELL_WIDTH,CELL_HEIGHT)),b[a].y=CELL_HEIGHT*a+OFFSET_Y*a,b[a].gotoAndStop(1),g.addChild(b[a]);break;case 8:h.x+=50;h.y=CANVAS_HEIGHT-205;g.x=h.x;g.y=h.y;l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0-
CELL_WIDTH,0-CELL_HEIGHT,4*CELL_WIDTH+4*OFFSET_X,4*CELL_HEIGHT+4*OFFSET_Y);g.addChild(l);for(a=0;2>a;a++)for(var e=0;2>e;e++)c[2*a+e].x=a,c[2*a+e].y=e,c[2*a+e].sprite=7,l=new createjs.SpriteSheet(f),b.push(createSprite(l,7,0,0,CELL_WIDTH,CELL_HEIGHT)),b[2*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[2*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[2*a+e].gotoAndStop(7),g.addChild(b[2*a+e]);break;case 9:h.x+=30;h.y=CANVAS_HEIGHT-230;g.x=h.x;g.y=h.y;l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0-
CELL_WIDTH,0-CELL_HEIGHT,5*CELL_WIDTH+5*OFFSET_X,5*CELL_HEIGHT+5*OFFSET_Y);g.addChild(l);k=Math.floor(4*Math.random());switch(k){case 0:for(a=0;3>a;a++)for(e=0;3>e;e++)0===a&&(1===e||2===e)||1===a&&(1===e||2===e)?(c[3*a+e].x=a,c[3*a+e].y=e,c[3*a+e].sprite=0,b.push(new createjs.Shape),b[3*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[3*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[3*a+e].graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,0,2*CELL_WIDTH+2*OFFSET_X,2*CELL_HEIGHT+2*OFFSET_Y)):(c[3*a+e].x=a,c[3*a+e].y=e,
c[3*a+e].sprite=6,l=new createjs.SpriteSheet(f),b.push(createSprite(l,6,0,0,CELL_WIDTH,CELL_HEIGHT)),b[3*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[3*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[3*a+e].gotoAndStop(6)),g.addChild(b[3*a+e]);break;case 1:for(a=0;3>a;a++)for(e=0;3>e;e++)1===a&&(1===e||2===e)||2===a&&(1===e||2===e)?(c[3*a+e].x=a,c[3*a+e].y=e,c[3*a+e].sprite=0,b.push(new createjs.Shape),b[3*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[3*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[3*a+e].graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,
0,2*CELL_WIDTH+2*OFFSET_X,2*CELL_HEIGHT+2*OFFSET_Y)):(c[3*a+e].x=a,c[3*a+e].y=e,c[3*a+e].sprite=6,l=new createjs.SpriteSheet(f),b.push(createSprite(l,6,0,0,CELL_WIDTH,CELL_HEIGHT)),b[3*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[3*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[3*a+e].gotoAndStop(6)),g.addChild(b[3*a+e]);break;case 2:for(a=0;3>a;a++)for(e=0;3>e;e++)1===a&&(0===e||1===e)||2===a&&(0===e||1===e)?(c[3*a+e].x=a,c[3*a+e].y=e,c[3*a+e].sprite=0,b.push(new createjs.Shape),b[3*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[3*a+
e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[3*a+e].graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,0,2*CELL_WIDTH+2*OFFSET_X,2*CELL_HEIGHT+2*OFFSET_Y)):(c[3*a+e].x=a,c[3*a+e].y=e,c[3*a+e].sprite=6,l=new createjs.SpriteSheet(f),b.push(createSprite(l,6,0,0,CELL_WIDTH,CELL_HEIGHT)),b[3*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[3*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[3*a+e].gotoAndStop(6)),g.addChild(b[3*a+e]);break;case 3:for(a=0;3>a;a++)for(e=0;3>e;e++)0===a&&(0===e||1===e)||1===a&&(0===e||1===e)?(c[3*a+e].x=a,c[3*
a+e].y=e,c[3*a+e].sprite=0,b.push(new createjs.Shape),b[3*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[3*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[3*a+e].graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,0,2*CELL_WIDTH+2*OFFSET_X,2*CELL_HEIGHT+2*OFFSET_Y)):(c[3*a+e].x=a,c[3*a+e].y=e,c[3*a+e].sprite=6,l=new createjs.SpriteSheet(f),b.push(createSprite(l,6,0,0,CELL_WIDTH,CELL_HEIGHT)),b[3*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[3*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[3*a+e].gotoAndStop(6)),g.addChild(b[3*a+e])}break;case 10:h.x+=
45;h.y=CANVAS_HEIGHT-205;g.x=h.x;g.y=h.y;l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0-CELL_WIDTH,0-CELL_HEIGHT,4*CELL_WIDTH+4*OFFSET_X,4*CELL_HEIGHT+4*OFFSET_Y);g.addChild(l);k=Math.floor(4*Math.random());switch(k){case 0:for(a=0;2>a;a++)for(e=0;2>e;e++)0===a&&1===e?(c[2*a+e].x=a,c[2*a+e].y=e,c[2*a+e].sprite=0,b.push(new createjs.Shape),b[2*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[2*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[2*a+e].graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,
0,2*CELL_WIDTH+2*OFFSET_X,2*CELL_HEIGHT+2*OFFSET_Y)):(c[2*a+e].x=a,c[2*a+e].y=e,c[2*a+e].sprite=8,l=new createjs.SpriteSheet(f),b.push(createSprite(l,8,0,0,CELL_WIDTH,CELL_HEIGHT)),b[2*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[2*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[2*a+e].gotoAndStop(8)),g.addChild(b[2*a+e]);break;case 1:for(a=0;2>a;a++)for(e=0;2>e;e++)1===a&&1===e?(c[2*a+e].x=a,c[2*a+e].y=e,c[2*a+e].sprite=0,b.push(new createjs.Shape),b[2*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[2*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[2*
a+e].graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,0,2*CELL_WIDTH+2*OFFSET_X,2*CELL_HEIGHT+2*OFFSET_Y)):(c[2*a+e].x=a,c[2*a+e].y=e,c[2*a+e].sprite=8,l=new createjs.SpriteSheet(f),b.push(createSprite(l,8,0,0,CELL_WIDTH,CELL_HEIGHT)),b[2*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[2*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[2*a+e].gotoAndStop(8)),g.addChild(b[2*a+e]);break;case 2:for(a=0;2>a;a++)for(e=0;2>e;e++)1===a&&0===e?(c[2*a+e].x=a,c[2*a+e].y=e,c[2*a+e].sprite=0,b.push(new createjs.Shape),b[2*a+e].x=CELL_WIDTH*
a+OFFSET_X*a,b[2*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[2*a+e].graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,0,2*CELL_WIDTH+2*OFFSET_X,2*CELL_HEIGHT+2*OFFSET_Y)):(c[2*a+e].x=a,c[2*a+e].y=e,c[2*a+e].sprite=8,l=new createjs.SpriteSheet(f),b.push(createSprite(l,8,0,0,CELL_WIDTH,CELL_HEIGHT)),b[2*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[2*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[2*a+e].gotoAndStop(8)),g.addChild(b[2*a+e]);break;case 3:for(a=0;2>a;a++)for(e=0;2>e;e++)0===a&&0===e?(c[2*a+e].x=a,c[2*a+e].y=e,c[2*
a+e].sprite=0,b.push(new createjs.Shape),b[2*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[2*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[2*a+e].graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,0,2*CELL_WIDTH+2*OFFSET_X,2*CELL_HEIGHT+2*OFFSET_Y)):(c[2*a+e].x=a,c[2*a+e].y=e,c[2*a+e].sprite=8,l=new createjs.SpriteSheet(f),b.push(createSprite(l,8,0,0,CELL_WIDTH,CELL_HEIGHT)),b[2*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[2*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[2*a+e].gotoAndStop(8)),g.addChild(b[2*a+e])}break;case 11:h.x+=55;h.y=
CANVAS_HEIGHT-180;g.x=h.x;g.y=h.y;l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0-CELL_WIDTH,0-CELL_HEIGHT,3*CELL_WIDTH+3*OFFSET_X,3*CELL_HEIGHT+3*OFFSET_Y);g.addChild(l);for(a=0;1>a;a++)c[a].x=a,c[a].y=a,c[a].sprite=5,l=new createjs.SpriteSheet(f),b.push(createSprite(l,5,0,0,CELL_WIDTH,CELL_HEIGHT)),b[a].y=CELL_HEIGHT*a+OFFSET_Y*a,b[a].gotoAndStop(5),g.addChild(b[a]);break;case 12:for(h.x+=30,h.y=CANVAS_HEIGHT-230,g.x=h.x,g.y=h.y,l=new createjs.Shape,l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0-
CELL_WIDTH,0-CELL_HEIGHT,5*CELL_WIDTH+5*OFFSET_X,5*CELL_HEIGHT+5*OFFSET_Y),g.addChild(l),a=0;3>a;a++)for(e=0;3>e;e++)c[3*a+e].x=a,c[3*a+e].y=e,c[3*a+e].sprite=9,l=new createjs.SpriteSheet(f),b.push(createSprite(l,9,0,0,CELL_WIDTH,CELL_HEIGHT)),b[3*a+e].x=CELL_WIDTH*a+OFFSET_X*a,b[3*a+e].y=CELL_HEIGHT*e+OFFSET_Y*e,b[3*a+e].gotoAndStop(9),g.addChild(b[3*a+e])}s_oStage.addChild(g);createjs.Touch.enable(g);g.on("mousedown",this._onFormContainerClick,this);g.on("pressup",this._releaseForm,this);g.on("pressmove",
this._dragForm,this);g.scaleX=.7;g.scaleY=.7};this._onFormContainerClick=function(a){s_oGame.onFormContainerClick(a,g,d)};this._dragForm=function(a){s_oGame.dragForm(a,g,d)};this._releaseForm=function(a){s_oGame.releaseForm(a,g,h,d)};this.slideContainer=function(){var a=h.x;g.x=1200;createjs.Tween.get(g).to({x:a},600,createjs.Ease.cubicOut).call(function(){s_bUpdate=!0})};this.setPos=function(a,b){g.x=a;g.y=b};this.getPosX=function(){return g.x};this.getPosY=function(){return g.y};this.getFormArray=
function(){return c};this.getForm=function(){return f};this.getType=function(){return k};this.deleteForm=function(){g.off("mousedown",this._onFormContainerClick,this);g.off("pressmove",this._dragForm,this);g.off("pressup",this._releaseForm,this);s_oStage.removeChild(g)};this._init(d,f)}
function CGame(d){var f,c,b,k,g=0,h=0,a=0,m=0,n=0,l=[!1,!1,!1],e,r,x=!1,w,z,y=Array(2),t,v=[],u=[],p=[];this._init=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack.volume=.4;var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);y[0]=new CScrollingBg(s_oSpriteLibrary.getSprite("clouds_back"),0);y[1]=new CScrollingBg(s_oSpriteLibrary.getSprite("clouds_back"),-SCROLLING_BG_WIDTH);a=createBitmap(s_oSpriteLibrary.getSprite("cloud_mask"));s_oStage.addChild(a);
e=new CInterface;z=new createjs.Container;s_oStage.addChild(z);for(var a=START_X_GRID,b=START_Y_GRID,c=0;c<NUM_ROWS;c++)v[c]=10,u[c]=10;t=[];for(c=0;c<NUM_ROWS;c++){b+=CELL_HEIGHT+OFFSET_Y;t[c]=[];for(var d=0;d<NUM_COLS;d++)a+=CELL_WIDTH+OFFSET_X,t[c][d]=new CCell(c,d,a,b,z,0);a=START_X_GRID}w=!1;new CHelpPanel(s_oSpriteLibrary.getSprite("msg_box"))};this.setUpdateOn=function(){w=!0};this._createForm=function(){for(var a=0;3>a;a++)p.push(new CForms(a,Math.floor(Math.random()*(MAX_FORMS+1)))),h++,
p[a].slideContainer()};this.onFormContainerClick=function(a,e,d){createjs.Tween.get(e).to({y:e.y-150,scaleX:1,scaleY:1},150,createjs.Ease.sineInOut).call(function(){});b=e.x;k=e.y;f=a.stageX-b;c=a.stageY-k;l[d]=!0};this.dragForm=function(a,b,e){l[e]&&p[e]&&p[e].setPos(a.stageX-f,a.stageY-c-150,b)};this.releaseForm=function(a,c,b,d){a=!0;var f=p[d].getPosX(),k=p[d].getPosY(),m=Math.floor((f-START_X_GRID)/(CELL_WIDTH+OFFSET_X)),r=Math.floor((k-START_Y_GRID)/(CELL_HEIGHT+OFFSET_Y)),q=p[d].getFormArray(),
w=!1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("position");p[d].getForm();if(f>=START_X_GRID&&f<START_X_GRID+10*(CELL_WIDTH+OFFSET_X)&&k>=START_Y_GRID&&k<START_Y_GRID+10*(CELL_HEIGHT+OFFSET_Y)+CELL_HEIGHT/2+OFFSET_Y){if(!0===this.checkPieceIfFitInPos(q,r,m))for(c=0;c<q.length;c++){if(0!==q[c].sprite){t[q[c].y+r][q[c].x+m].changeCellState(q[c].sprite);v[m+q[c].x]--;u[r+q[c].y]--;g+=SCORE_OBJECT_PLACED;if(0===u[r+q[c].y]){a=!1;n++;for(b=0;b<NUM_COLS;b++)0===v[b]&&(n++,v[b]=10,this.deleteCol(r+
q[c].y,b));u[r+q[c].y]=10;this.deleteRow(r+q[c].y,m+q[c].x)}if(0===v[m+q[c].x]){a=!1;n++;for(b=0;b<NUM_ROWS;b++)0===u[b]&&(n++,u[b]=10,this.deleteRow(b,m+q[c].x));v[m+q[c].x]=10;this.deleteCol(r+q[c].y,m+q[c].x)}w=!0;e.viewScore(g)}}else createjs.Tween.get(c).to({x:b.x,y:b.y,scaleX:.7,scaleY:.7},200,createjs.Ease.cubicOut).call(function(){});!0===w&&(p[d].deleteForm(),p[d]=0,h--);!0===a&&this.isGameOver()&&(x=!0)}else createjs.Tween.get(c).to({x:b.x,y:b.y,scaleX:.7,scaleY:.7},200,createjs.Ease.cubicOut).call(function(){});
l[d]=!1};this.checkPieceIfFitInPos=function(a,c,b){for(var e=!0,d=0;d<a.length;d++)if(0!==a[d].sprite){if(a[d].y+c>=NUM_COLS||a[d].x+b>=NUM_ROWS){e=!1;break}if(0!==t[a[d].y+c][a[d].x+b].getValue()){e=!1;break}}return e};this.checkPieceIfFitInMatrix=function(a){a=a.getFormArray();for(var c=0;c<NUM_ROWS;c++)for(var b=0;b<NUM_COLS;b++)if(this.checkPieceIfFitInPos(a,c,b))return!0;return!1};this.isGameOver=function(){var c=!0;a=0;if(!p||0===p[0]&&0===p[1]&&0===p[2])return!1;for(var b=0;b<p.length;b++)if(0!==
p[b]&&this.checkPieceIfFitInMatrix(p[b])){c=!1;break}return c};this.deleteRow=function(a,c){for(var b=0;b<NUM_ROWS;b++)0<=c-1-b&&(t[a][c-1-b].changeScaleandState(),m++),c+b<NUM_ROWS&&(t[a][c+b].changeScaleandState(),m++),v[b]++;1<n?!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("combo"):!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("combo_plus")};this.deleteCol=function(a,c){for(var b=0;b<NUM_ROWS;b++)0<=a-1-b&&(t[a-1-b][c].changeScaleandState(0),m++),a+b<NUM_ROWS&&
(t[a+b][c].changeScaleandState(0),m++),u[b]++;1<n?!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("combo"):!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("combo_plus")};this.decreaseCellToDeleteCounter=function(){m--;0===m&&this.isGameOver()&&this.gameOverText()};this._setScore=function(a){g+=SCORE_ROW_COL_DELETED*n*n;e.viewScore(g);n=0};this.unload=function(){e.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();
s_oMain.gotoMenu();$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};this.gameOverText=function(){var a=new createjs.Text("GAME OVER"," 60px "+FONT,"#7fc6d8");a.x=CANVAS_WIDTH/2;a.y=0;a.textAlign="center";a.textBaseline="alphabetic";a.outline=3;a.lineWidth=500;s_oStage.addChild(a);var b=new createjs.Text("GAME OVER"," 60px "+FONT,"#ffffff");b.x=CANVAS_WIDTH/2;b.y=0;b.textAlign="center";b.textBaseline="alphabetic";b.lineWidth=500;s_oStage.addChild(b);
createjs.Tween.get(a).to({y:CANVAS_HEIGHT/2,alpha:1},2E3,createjs.Ease.bounceOut).call(function(){});createjs.Tween.get(b).to({y:CANVAS_HEIGHT/2,alpha:1},2E3,createjs.Ease.bounceOut).call(function(){s_oGame.gameOver()});if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack.volume=0,a=createjs.Sound.play("game_over"),a.volume=.4};this.gameOver=function(){r=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));r.show(g)};this.increaseConunterForCheckGameOver=function(){a++;a>=10*(n+1)&&this.isGameOver()&&
this.gameOverText()};this.update=function(){w&&(0===h&&(p=[],this._createForm(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("swish")),s_bUpdate&&(this.isGameOver()&&(x=!0),s_bUpdate=!1),!0===x&&(this.gameOverText(),x=!1),y[0].move(),y[1].move())};s_oGame=this;SCORE_OBJECT_PLACED=d.score_object_placed;SCORE_ROW_COL_DELETED=d.score_row_col_deleted;this._init()}var s_oGame;
function CGfxButton(d,f,c){var b,k,g,h=[],a;this._init=function(c,d,f){b=1;k=[];g=[];a=createBitmap(f);a.x=c;a.y=d;a.regX=f.width/2;a.regY=f.height/2;s_oStage.addChild(a);this._initListener()};this.unload=function(){a.off("mousedown",this.buttonDown);a.off("pressup",this.buttonRelease);s_oStage.removeChild(a)};this.setVisible=function(b){a.visible=b};this._initListener=function(){a.on("mousedown",this.buttonDown);a.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){k[a]=b;g[a]=
c};this.addEventListenerWithParams=function(a,b,c,e){k[a]=b;g[a]=c;h=e};this.buttonRelease=function(){a.scaleX=b;a.scaleY=b;k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(g[ON_MOUSE_UP],h)};this.buttonDown=function(){a.scaleX=.9*b;a.scaleY=.9*b;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],h)};this.setScale=function(c){b=c;a.scaleX=c;a.scaleY=c};this.setPosition=function(b,c){a.x=b;a.y=c};this.setX=function(b){a.x=b};this.setY=function(b){a.y=b};this.getButtonImage=function(){return a};this.getX=
function(){return a.x};this.getY=function(){return a.y};this._init(d,f,c);return this}
function CHelpPanel(d){var f,c,b,k;this._init=function(d){f=createBitmap(d);f.x=0;f.y=0;b=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));b.x=CANVAS_WIDTH/2-100;b.y=CANVAS_HEIGHT/2-290;k=new createjs.Text(TEXT_HELP," 30px "+FONT,"#ffffff");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2;k.textAlign="center";k.textBaseline="alphabetic";k.lineWidth=470;c=new createjs.Container;c.addChild(f,b,void 0,k);c.alpha=0;s_oStage.addChild(c);var h=this;createjs.Tween.get(c).to({alpha:1},500).call(function(){h._initListener()})};
this.unload=function(){c.off("mousedown",this._onExit)};this._initListener=function(){c.on("mousedown",this._onExit)};this._onExit=function(){c.off("mousedown",this._onExit);s_oStage.removeChild(c);s_oGame.setUpdateOn();$(s_oMain).trigger("start_level")};this._init(d);return this}
function CInterface(){var d,f,c,b,k,g,h,a;this._init=function(){var m=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH-m.height/2-10;b=m.height/2+10;g=new CGfxButton(c,b,m,s_oStage);g.addEventListener(ON_MOUSE_UP,this._onExit,this);d=CANVAS_WIDTH-m.width/2-90;f=m.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m=s_oSpriteLibrary.getSprite("audio_icon"),k=new CToggle(d,f,m,s_bAudioActive),k.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);h=new createjs.Text("0 pt"," 40px "+FONT,
"#8836b6");h.x=CANVAS_WIDTH/2;h.y=CANVAS_WIDTH/2-180;h.textAlign="center";h.textBaseline="middle";h.lineWidth=500;h.outline=5;a=new createjs.Text("0 pt"," 40px "+FONT,"#fd83d3");a.x=CANVAS_WIDTH/2;a.y=CANVAS_WIDTH/2-180;a.textAlign="center";a.textBaseline="middle";a.lineWidth=500;s_oStage.addChild(h,a);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null;s_oInterface=null};this.refreshButtonPos=function(a,h){g.setPosition(c-
a,h+b);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||k.setPosition(d-a,h+f)};this.viewScore=function(b){h.text=b+" pt";a.text=b+" pt";createjs.Tween.get(h).to({scaleX:1.2,scaleY:1.2},200,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(h).to({scaleX:1,scaleY:1},200,createjs.Ease.cubicIn).call(function(){})});createjs.Tween.get(a).to({scaleX:1.2,scaleY:1.2},200,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(a).to({scaleX:1,scaleY:1},200,createjs.Ease.cubicIn).call(function(){})})};
this._onButHelpRelease=function(){_oHelpPanel=new CHelpPanel};this.onExitFromHelp=function(){_oHelpPanel.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};s_oInterface=this;this._init();return this}var s_oInterface=null;TEXT_GAMEOVER="GAME OVER";TEXT_SCORE="YOUR SCORE IS:\n\n";TEXT_PAUSE="PAUSE";TEXT_PANEL="CONGRATULATIONS!\n\nYOU OBTAINED";TEXT_PANEL_POINT=" POINTS";TEXT_HELP="DRAG THE BLOCKS INTO THE GRID TO FILL AND CLEAR ROWS AND COLUMNS.THE GAME ENDS WHEN YOU DON'T HAVE ENOUGH SPACE TO PUT TILES INTO THE BOARD.";
TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CMain(d){var f,c=0,b=0,k=STATE_LOADING,g,h,a;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();f=!0};this.soundLoaded=function(){c++;h.refreshLoader(Math.floor(c/b*100));if(c===b){h.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<
navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/but_press.ogg","click"),createjs.Sound.registerSound("./sounds/combo.ogg","combo"),createjs.Sound.registerSound("./sounds/combo_plus.ogg","combo_plus"),createjs.Sound.registerSound("./sounds/position.ogg","position"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/swish.ogg",
"swish"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/but_press.mp3","click"),createjs.Sound.registerSound("./sounds/combo.mp3","combo"),createjs.Sound.registerSound("./sounds/combo_plus.mp3","combo_plus"),createjs.Sound.registerSound("./sounds/position.mp3","position"),createjs.Sound.registerSound("./sounds/soundtrack.mp3",
"soundtrack"),createjs.Sound.registerSound("./sounds/swish.mp3","swish"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over")),b+=7)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");
s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("cubes_sprite","./sprites/cubes_sprite.png");s_oSpriteLibrary.addSprite("clouds_back","./sprites/clouds_back.png");s_oSpriteLibrary.addSprite("cloud_mask","./sprites/cloud_mask.png");b+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;
h.refreshLoader(Math.floor(c/b*100));if(c===b){h.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;k=STATE_MENU};this.gotoGame=function(){a=new CGame(g);k=STATE_GAME};this.gotoHelp=function(){new CHelp;k=STATE_HELP};this.stopUpdate=function(){f=!1;createjs.Ticker.paused=!0;$("#block_game").css("display",
"block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();f=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(b){if(!1!==f){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);k===STATE_GAME&&a.update();s_oStage.update(b)}};s_oMain=this;g=d;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_bUpdate=!1,s_oDrawLayer,s_oStage,s_oMain,s_oCell,s_oSpriteLibrary,s_oSoundtrack,s_oBgSound,s_oCanvas;
function CMenu(){var d,f,c,b,k,g;this._init=function(){c=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(c);var h=s_oSpriteLibrary.getSprite("but_play");b=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-325,h);b.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h=s_oSpriteLibrary.getSprite("audio_icon"),d=CANVAS_WIDTH-h.height/2-10,f=h.height/2+10,g=new CToggle(d,f,h,s_bAudioActive),g.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(k);createjs.Tween.get(k).to({alpha:0},1E3).call(function(){k.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){b.unload();b=null;k.visible=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),g=null;s_oStage.removeChild(c);s_oMenu=c=null};this.refreshButtonPos=function(b,a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||g.setPosition(d-b,a+f)};this._onAudioToggle=
function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoGame();$(s_oMain).trigger("start_session")};s_oMenu=this;this._init()}var s_oMenu=null;
function CPreloader(){var d,f,c,b,k,g,h;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();h=new createjs.Container;s_oStage.addChild(h)};this.unload=function(){h.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var a=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));h.addChild(a);a=s_oSpriteLibrary.getSprite("progress_bar");b=createBitmap(a);b.x=CANVAS_WIDTH/2-a.width/2;b.y=CANVAS_HEIGHT-250;h.addChild(b);d=a.width;f=a.height;k=new createjs.Shape;k.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(b.x,b.y,1,f);h.addChild(k);b.mask=
k;c=new createjs.Text("","30px Arial","#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT-250;c.shadow=new createjs.Shadow("#000",2,2,2);c.textBaseline="alphabetic";c.textAlign="center";h.addChild(c);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;h.addChild(g)};this.refreshLoader=function(a){c.text=a+"%";k.graphics.clear();a=Math.floor(a*d/100);k.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(b.x,b.y,a,f)};this._init()}
function CScrollingBg(d,f){var c,b;this._init=function(d,f){c=d;b=createBitmap(c);s_oStage.addChild(b);b.x=f;b.y=175;b.regX=0};this.move=function(){b.x++;b.x>CANVAS_WIDTH&&(b.x=-SCROLLING_BG_WIDTH)};this._init(d,f)}
function CTextButton(d,f,c,b,k,g,h){var a,m,n,l,e;this._init=function(b,c,d,f,g,h,k){a=[];m=[];var u=createBitmap(d),p=Math.ceil(k/20);e=new createjs.Text(f,"bold "+k+"px "+g,"#000000");e.textAlign="center";e.textBaseline="alphabetic";var A=e.getBounds();e.x=d.width/2+p;e.y=Math.floor(d.height/2)+A.height/3+p;l=new createjs.Text(f,"bold "+k+"px "+g,h);l.textAlign="center";l.textBaseline="alphabetic";A=l.getBounds();l.x=d.width/2;l.y=Math.floor(d.height/2)+A.height/3;n=new createjs.Container;n.x=b;
n.y=c;n.regX=d.width/2;n.regY=d.height/2;n.addChild(u,e,l);s_oStage.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown");n.off("pressup");s_oStage.removeChild(n)};this.setVisible=function(a){n.visible=a};this._initListener=function(){oParent=this;n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(b,c,d){a[b]=c;m[b]=d};this.buttonRelease=function(){n.scaleX=1;n.scaleY=1;a[ON_MOUSE_UP]&&a[ON_MOUSE_UP].call(m[ON_MOUSE_UP])};this.buttonDown=
function(){n.scaleX=.9;n.scaleY=.9;a[ON_MOUSE_DOWN]&&a[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN])};this.setTextPosition=function(a){l.y=a;e.y=a+2};this.setPosition=function(a,b){n.x=a;n.y=b};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this._init(d,f,c,b,k,g,h);return this}
(function(d){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(d)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(d.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);function trace(d){console.log(d)}function isIOS(){for(var d="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");d.length;)if(navigator.platform===d.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}$(window).resize(function(){sizeHandler()});
function getSize(d){var f=d.toLowerCase(),c=window.document,b=c.documentElement;if(void 0===window["inner"+d])d=b["client"+d];else if(window["inner"+d]!=b["client"+d]){var k=c.createElement("body");k.id="vpw-test-b";k.style.cssText="overflow:scroll";var g=c.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+f+":"+b["client"+d]+"px){body#vpw-test-b div#vpw-test-d{"+f+":7px!important}}</style>";k.appendChild(g);b.insertBefore(k,c.head);
d=7==g["offset"+d]?b["client"+d]:window["inner"+d];b.removeChild(k)}else d=window["inner"+d];return d}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var d=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<d?d:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var d;d=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var f=getSize("Width"),c=Math.min(d/CANVAS_HEIGHT,f/CANVAS_WIDTH),b=CANVAS_WIDTH*c,c=CANVAS_HEIGHT*c,k=0;c<d?(k=d-c,c+=k,b+=CANVAS_WIDTH/CANVAS_HEIGHT*k):b<f&&(k=f-b,b+=k,c+=CANVAS_HEIGHT/CANVAS_WIDTH*k);var k=d/2-c/2,g=f/2-b/2,h=CANVAS_WIDTH/b;if(g*h<-EDGEBOARD_X||k*h<-EDGEBOARD_Y)c=Math.min(d/(CANVAS_HEIGHT-2*EDGEBOARD_Y),f/(CANVAS_WIDTH-2*
EDGEBOARD_X)),b=CANVAS_WIDTH*c,c*=CANVAS_HEIGHT,k=(d-c)/2,g=(f-b)/2,h=CANVAS_WIDTH/b;s_iOffsetX=-1*g*h;s_iOffsetY=-1*k*h;0<=k&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",b+"px");$("#canvas").css("height",c+"px");0>k?$("#canvas").css("top",k+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",g+"px")}}
function createBitmap(d,f,c){var b=new createjs.Bitmap(d),k=new createjs.Shape;f&&c?k.graphics.beginFill("#fff").drawRect(0,0,f,c):k.graphics.beginFill("#ff0").drawRect(0,0,d.width,d.height);b.hitArea=k;return b}function createSprite(d,f,c,b,k,g){d=null!==f?new createjs.Sprite(d,f):new createjs.Sprite(d);f=new createjs.Shape;f.graphics.beginFill("#000000").drawRect(-c,-b,k,g);d.hitArea=f;return d}
function randomFloatBetween(d,f,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(d+Math.random()*(f-d),f).toFixed(c))}function rotateVector2D(d,f){var c=f.getX()*Math.cos(d)+f.getY()*Math.sin(d),b=f.getX()*-Math.sin(d)+f.getY()*Math.cos(d);f.set(c,b)}function tweenVectorsOnX(d,f,c){return d+c*(f-d)}function shuffle(d){for(var f=d.length,c,b;0!==f;)b=Math.floor(Math.random()*f),--f,c=d[f],d[f]=d[b],d[b]=c;return d}
function bubbleSort(d){var f;do{f=!1;for(var c=0;c<d.length-1;c++)d[c]>d[c+1]&&(f=d[c],d[c]=d[c+1],d[c+1]=f,f=!0)}while(f)}function compare(d,f){return d.index>f.index?-1:d.index<f.index?1:0}function easeLinear(d,f,c,b){return c*d/b+f}function easeInQuad(d,f,c,b){return c*(d/=b)*d+f}function easeInSine(d,f,c,b){return-c*Math.cos(d/b*(Math.PI/2))+c+f}function easeInCubic(d,f,c,b){return c*(d/=b)*d*d+f}
function getTrajectoryPoint(d,f){var c=new createjs.Point,b=(1-d)*(1-d),k=d*d;c.x=b*f.start.x+2*(1-d)*d*f.traj.x+k*f.end.x;c.y=b*f.start.y+2*(1-d)*d*f.traj.y+k*f.end.y;return c}function formatTime(d){d/=1E3;var f=Math.floor(d/60);d=Math.floor(d-60*f);var c="",c=10>f?c+("0"+f+":"):c+(f+":");return 10>d?c+("0"+d):c+d}function degreesToRadians(d){return d*Math.PI/180}function checkRectCollision(d,f){var c,b;c=getBounds(d,.9);b=getBounds(f,.98);return calculateIntersection(c,b)}
function calculateIntersection(d,f){var c,b,k,g,h,a,m,n;c=d.x+(k=d.width/2);b=d.y+(g=d.height/2);h=f.x+(a=f.width/2);m=f.y+(n=f.height/2);c=Math.abs(c-h)-(k+a);b=Math.abs(b-m)-(g+n);return 0>c&&0>b?(c=Math.min(Math.min(d.width,f.width),-c),b=Math.min(Math.min(d.height,f.height),-b),{x:Math.max(d.x,f.x),y:Math.max(d.y,f.y),width:c,height:b,rect1:d,rect2:f}):null}
function getBounds(d,f){var c={x:Infinity,y:Infinity,width:0,height:0};if(d instanceof createjs.Container){c.x2=-Infinity;c.y2=-Infinity;var b=d.children,k=b.length,g,h;for(h=0;h<k;h++)g=getBounds(b[h],1),g.x<c.x&&(c.x=g.x),g.y<c.y&&(c.y=g.y),g.x+g.width>c.x2&&(c.x2=g.x+g.width),g.y+g.height>c.y2&&(c.y2=g.y+g.height);Infinity==c.x&&(c.x=0);Infinity==c.y&&(c.y=0);Infinity==c.x2&&(c.x2=0);Infinity==c.y2&&(c.y2=0);c.width=c.x2-c.x;c.height=c.y2-c.y;delete c.x2;delete c.y2}else{var a,m;d instanceof createjs.Bitmap?
(k=d.sourceRect||d.image,h=k.width*f,a=k.height*f):d instanceof createjs.Sprite?d.spriteSheet._frames&&d.spriteSheet._frames[d.currentFrame]&&d.spriteSheet._frames[d.currentFrame].image?(k=d.spriteSheet.getFrame(d.currentFrame),h=k.rect.width,a=k.rect.height,b=k.regX,m=k.regY):(c.x=d.x||0,c.y=d.y||0):(c.x=d.x||0,c.y=d.y||0);b=b||0;h=h||0;m=m||0;a=a||0;c.regX=b;c.regY=m;k=d.localToGlobal(0-b,0-m);g=d.localToGlobal(h-b,a-m);h=d.localToGlobal(h-b,0-m);b=d.localToGlobal(0-b,a-m);c.x=Math.min(Math.min(Math.min(k.x,
g.x),h.x),b.x);c.y=Math.min(Math.min(Math.min(k.y,g.y),h.y),b.y);c.width=Math.max(Math.max(Math.max(k.x,g.x),h.x),b.x)-c.x;c.height=Math.max(Math.max(Math.max(k.y,g.y),h.y),b.y)-c.y}return c}function NoClickDelay(d){this.element=d;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(d){for(var f=d.length,c,b;0<f;)b=Math.floor(Math.random()*f),f--,c=d[f],d[f]=d[b],d[b]=c;return d}
NoClickDelay.prototype={handleEvent:function(d){switch(d.type){case "touchstart":this.onTouchStart(d);break;case "touchmove":this.onTouchMove(d);break;case "touchend":this.onTouchEnd(d)}},onTouchStart:function(d){d.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(d){this.moved=!0},onTouchEnd:function(d){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){d=document.elementFromPoint(d.changedTouches[0].clientX,d.changedTouches[0].clientY);3==d.nodeType&&(d=d.parentNode);var f=document.createEvent("MouseEvents");f.initEvent("click",!0,!0);d.dispatchEvent(f)}}};
(function(){function d(c){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};c=c||window.event;c.type in b?document.body.className=b[c.type]:(document.body.className=this[f]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var f="hidden";f in document?document.addEventListener("visibilitychange",d):(f="mozHidden")in document?document.addEventListener("mozvisibilitychange",d):(f="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",d):(f="msHidden")in document?document.addEventListener("msvisibilitychange",d):"onfocusin"in document?document.onfocusin=document.onfocusout=d:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=d})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(d){for(var f=window.location.search.substring(1).split("&"),c=0;c<f.length;c++){var b=f[c].split("=");if(b[0]==d)return b[1]}}
function CToggle(d,f,c,b){var k,g,h,a=[],m;this._init=function(a,b,c,d){g=[];h=[];var f=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});k=d;m=createSprite(f,"state_"+k,c.width/2/2,c.height/2,c.width/2,c.height);m.x=a;m.y=b;m.stop();s_oStage.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);s_oStage.removeChild(m)};
this._initListener=function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;h[a]=c};this.addEventListenerWithParams=function(b,c,d,f){g[b]=c;h[b]=d;a=f};this.setActive=function(a){k=a;m.gotoAndStop("state_"+k)};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");k=!k;m.gotoAndStop("state_"+k);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(h[ON_MOUSE_UP],a)};this.buttonDown=
function(){m.scaleX=.9;m.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN],a)};this.setPosition=function(a,b){m.x=a;m.y=b};this.setVisible=function(a){m.visible=a};this._init(d,f,c,b)}
var CANVAS_WIDTH=640,CANVAS_HEIGHT=960,FONT="bubblegumregular",EDGEBOARD_X=20,EDGEBOARD_Y=100,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,SCORE_OBJECT_PLACED,SCORE_ROW_COL_DELETED,SCROLLING_BG_WIDTH=640,SCROLLING_BG_HEIGHT=741,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,NUM_ROWS=10,NUM_COLS=10,CELL_WIDTH=48,CELL_HEIGHT=53,PARTICLE_HEIGHT=115,PARTICLE_WIDTH=140,OFFSET_X=0,OFFSET_Y=-4,START_X_GRID=CANVAS_WIDTH/2-11*(CELL_WIDTH+OFFSET_X)/2,START_Y_GRID=150,MAX_FORMS=12,ON_MOUSE_DOWN=0,ON_MOUSE_UP=
1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5;
function CSpriteLibrary(){var d,f,c,b,k,g;this.init=function(h,a,m){c=f=0;b=h;k=a;g=m;d={}};this.addSprite=function(b,a){d.hasOwnProperty(b)||(d[b]={szPath:a,oSprite:new Image},f++)};this.getSprite=function(b){return d.hasOwnProperty(b)?d[b].oSprite:null};this._onSpritesLoaded=function(){k.call(g)};this._onSpriteLoaded=function(){b.call(g);++c==f&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in d)d[b].oSprite.oSpriteLibrary=this,d[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
d[b].oSprite.src=d[b].szPath};this.getNumSprites=function(){return f}};
