function CGfxButton(a,c,b){var d,e,g,f=[],h;this._init=function(a,b,c){d=1;e=[];g=[];h=createBitmap(c);h.x=a;h.y=b;h.regX=c.width/2;h.regY=c.height/2;s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);s_oStage.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){e[a]=b;g[a]=
c};this.addEventListenerWithParams=function(a,b,c,d){e[a]=b;g[a]=c;f=d};this.buttonRelease=function(){h.scaleX=d;h.scaleY=d;e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(g[ON_MOUSE_UP],f)};this.buttonDown=function(){h.scaleX=.9*d;h.scaleY=.9*d;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],f)};this.setScale=function(a){d=a;h.scaleX=a;h.scaleY=a};this.setPosition=function(a,b){h.x=a;h.y=b};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=
function(){return h.x};this.getY=function(){return h.y};this._init(a,c,b);return this}
function CGame(a){var c=0,b=0,d,e=0,g=0,f=0,h=.5,k,l,m,n=0,y=new CVector2(0,CANVAS_HEIGHT),M=new CVector2(SKIER_X_START,SKIER_Y_START),F=new CVector2(CANVAS_WIDTH/2,CANVAS_HEIGHT/2),x=[],B=[],C=[],D=[],z=[],r=[],q=[],v=[],w=[],u=[],J,p,A,G=0,t=[null,null],E=[null,null],N=!1,O=!1,R=!0,K=!1,H=!1,I=!1,P=!1,Q,S,L=null;this._init=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack.volume=.6,s_oSkiingAudio=createjs.Sound.play("skiing_idle",{loop:-1});d=0;k=OBSTACLES_SPD;NUM_ROW=Math.floor((CANVAS_HEIGHT+
MAX_OBSTACLE_HEIGHT)/HEIGHT_BETWEEN_OBSTACLES);l=SKIER_Y_START+MAX_OBSTACLE_HEIGHT+SKIER_HEIGHT/2;m=CANVAS_HEIGHT+MAX_OBSTACLE_HEIGHT;S=new CScrollingBg;this.createLine(SKIER_X_START,c);Q=new createjs.Container;s_oStage.addChild(Q);p=new CSkier(Q);for(var a=0;a<MAX_OBJECT_FOR_TYPE;a++)a<MAX_OBJECT_FOR_TYPE/2&&(x.push(new CObstacle(-MAX_OBSTACLE_WIDTH,-MAX_OBSTACLE_HEIGHT,"tree")),B.push(new CObstacle(-MAX_OBSTACLE_WIDTH,-MAX_OBSTACLE_HEIGHT,"tree2"))),C.push(new CObstacle(-MAX_OBSTACLE_WIDTH,-MAX_OBSTACLE_HEIGHT,
"rock")),D.push(new CObstacle(-MAX_OBSTACLE_WIDTH,-MAX_OBSTACLE_HEIGHT,"fence")),z.push(new CObstacle(-MAX_OBSTACLE_WIDTH,-MAX_OBSTACLE_HEIGHT,"bonus"));this._controlIfAllReady();J=new CInterface};this._controlIfAllReady=function(){x.length===MAX_OBJECT_FOR_TYPE/2&&(f+=x.length);B.length===MAX_OBJECT_FOR_TYPE/2&&(f+=B.length);C.length===MAX_OBJECT_FOR_TYPE&&(f+=C.length);D.length===MAX_OBJECT_FOR_TYPE&&(f+=D.length);z.length===MAX_OBJECT_FOR_TYPE&&(f+=z.length);if(f>=MAX_OBJECT_FOR_TYPE*(NUM_ELEMENTS-
1))for(var a=m,b=0;b<NUM_ROW;b++,a+=HEIGHT_BETWEEN_OBSTACLES)this._createRow(a);f=0};this._createRow=function(a){for(var b=Math.round(Math.random()*(MAX_OBJECT_ROW-MIN_OBJECT_ROW)+MIN_OBJECT_ROW),c=0,e,f=[],h=0;h<b;h++)f.push(h);for(var h=(CANVAS_WIDTH-2*s_iOffsetX)/b,g=0;g<b;g++)switch(c=Math.floor(Math.random()*f.length),e=f[c],f.splice(c,1),c=Math.floor(Math.random()*(h*(e+1)-50-s_iOffsetX-(h*e+50)+s_iOffsetX)+h*e+50+s_iOffsetX),e=Math.floor(Math.random()*NUM_ELEMENTS),e){case TREE:r.push(this.getFirstAvailableObstacle(e));
e=r.length-1;null!==r[e]?r[e].changeStatusOn(c,a):r.pop();break;case TREE2:q.push(this.getFirstAvailableObstacle(e));e=q.length-1;null!==q[e]?q[e].changeStatusOn(c,a):q.pop();break;case ROCK:v.push(this.getFirstAvailableObstacle(e));e=v.length-1;null!==v[e]?v[e].changeStatusOn(c,a):v.pop();break;case FENCE:w.push(this.getFirstAvailableObstacle(e));e=w.length-1;null!==w[e]?w[e].changeStatusOn(c,a):w.pop();break;case BONUS:u.push(this.getFirstAvailableObstacle(e)),e=u.length-1,null!==u[e]?u[e].changeStatusOn(c,
a):u.pop()}d=NUM_ROW};this.getFirstAvailableObstacle=function(a){switch(a){case TREE:return 0<x.length?(a=x.length-1,a=x[a],x.pop(),a):null;case TREE2:return 0<B.length?(a=B.length-1,a=B[a],B.pop(),a):null;case ROCK:return 0<C.length?(a=C.length-1,a=C[a],C.pop(),a):null;case FENCE:return 0<D.length?(a=D.length-1,a=D[a],D.pop(),a):null;case BONUS:return 0<z.length?(a=z.length-1,a=z[a],z.pop(),a):null}};this._mouseMove=function(){s_oStage.on("stagemousemove",function(a){0<a.stageX&&a.stageX<CANVAS_WIDTH&&
F.set(Math.floor(a.stageX),CANVAS_HEIGHT/2)})};this._moveSkier=function(){p.getRotation()<=-TOLLERANCE||p.getRotation()>=TOLLERANCE?(p.getX()<=F.getX()?(h<SKIER_SPD&&(h=0>h?h+CHANGE_DIRECTION_FASTER:h+DECELERATION,h>SKIER_SPD&&(h=SKIER_SPD)),p.getX()+h<CANVAS_WIDTH&&p.addPos(h)):p.getX()>F.getX()-SKIER_SPD&&(h>-SKIER_SPD&&(h=0<h?h-CHANGE_DIRECTION_FASTER:h-DECELERATION,h<-SKIER_SPD&&(h=-SKIER_SPD)),0<p.getX()+h&&p.addPos(h)),p.refreshRectangle()):h=.5};this.createLine=function(a){t[b]=new CLineStroke(a-
7);E[b]=new CLineStroke(a+7)};this._setRotation=function(){var a=new CVector2(F.getX(),-F.getY());M.set(p.getX(),-p.getY());M.subV(a);c=angleBetweenVectors(y,M);c=toDegree(c);this._changeVelocityObstacles();p.getX()<=F.getX()&&(c*=-1);"idle"!==p.returnState()&&c<TOLLERANCE&&c>-TOLLERANCE&&(p.changeFrameStateIdle(),I=H=!1);c<-TOLLERANCE?(p.changeFrameStateRight(Math.floor(-c/6)+10),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!1!==H||(0===G?(createjs.Sound.play("skiing_direction"),H=!0,I=!1):0===G.position&&
(createjs.Sound.play("skiing_direction"),H=!0,I=!1))):c>TOLLERANCE&&(p.changeFrameStateLeft(Math.floor(c/6)),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!1!==I||(0===G?(G=createjs.Sound.play("skiing_direction"),H=!1,I=!0):0===G.position&&(G=createjs.Sound.play("skiing_direction"),H=!1,I=!0)));p.setRotation(c)};this._changeVelocityObstacles=function(){c>TOLLERANCE||c<-TOLLERANCE?k=(-9*(c-0)+90)/100+MODIFIER:k<OBSTACLES_SPD&&(k+=ACCELERATION)};this._moveObstacles=function(){for(var a,b=0;b<r.length;b++)r[b].move(k+
n),r[b].getY()<l&&(r[b].refreshRectangle(),A=p.getRectangle(),r[b].controlCollision(A,b),a=this._controlIfObstaclesIsOverCanvas(TREE,b),null!==a&&(x.push(a),b--));for(b=0;b<q.length;b++)q[b].move(k+n),q[b].getY()<l&&(q[b].refreshRectangle(),A=p.getRectangle(),q[b].controlCollision(A,b),a=this._controlIfObstaclesIsOverCanvas(TREE2,b),null!==a&&(B.push(a),b--));for(b=0;b<v.length;b++)v[b].move(k+n),v[b].getY()<l&&(v[b].refreshRectangle(),A=p.getRectangle(),v[b].controlCollision(A,b),a=this._controlIfObstaclesIsOverCanvas(ROCK,
b),null!==a&&(C.push(a),b--));for(b=0;b<w.length;b++)w[b].move(k+n),w[b].getY()<l&&(w[b].refreshRectangle(),A=p.getRectangle(),w[b].controlCollision(A,b),a=this._controlIfObstaclesIsOverCanvas(FENCE,b),null!==a&&(D.push(a),b--));for(b=0;b<u.length;b++)u[b].move(k+n),u[b].getY()<l&&(u[b].refreshRectangle(),A=p.getRectangle(),u[b].controlCollision(A,b),a=this._controlIfObstaclesIsOverCanvas(BONUS,b),null!==a&&(z.push(a),b--));d<NUM_ROW&&this._createRow(m)};this.collisionFound=function(a){K||(!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("falling"),a===ROCK||a===FENCE?(p.falling(),O=!0,R=!1):createjs.Tween.get(s_oStage).to({x:Math.round(10*Math.random()),y:Math.round(30*Math.random())},50).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(8*Math.random()),y:-Math.round(24*Math.random())},50).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(6*Math.random()),y:Math.round(18*Math.random())},50).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(4*Math.random()),
y:-Math.round(12*Math.random())},50).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(2*Math.random()),y:Math.round(6*Math.random())},50).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(10*Math.random()),y:-Math.round(30*Math.random())},50).call(function(){createjs.Tween.get(s_oStage).to({y:0,x:0},50).call(function(){})})})})})})}),this.gameOver())};this.bonusHitted=function(a){if(!K&&!P){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("bonus");P=!0;u[a].setInvisible();
var b=createBitmap(s_oSpriteLibrary.getSprite("bonus_hitted"));b.x=u[a].getX();b.y=u[a].getY();b.regX=BONUS_WIDTH/2;b.regY=BONUS_HEIGHT;s_oStage.addChild(b);var c=this;createjs.Tween.get(b).to({x:b.x/2+25,y:(CANVAS_HEIGHT-50)/2},350,createjs.Ease.linear).call(function(){c.setBonusTakenFalse();createjs.Tween.get(b).to({x:50,y:CANVAS_HEIGHT-50},650,createjs.Ease.backOut).call(function(){c.setScore(SCORE_BONUS);s_oStage.removeChild(this)})})}};this.setBonusTakenFalse=function(){P=!1};this._controlIfObstaclesIsOverCanvas=
function(a,b){var c;switch(a){case TREE:return 0>r[b].getY()?(r[b].changeStatusOff(),c=r[b],r.splice(b,1),d--,c):null;case TREE2:return 0>q[b].getY()?(q[b].changeStatusOff(),c=q[b],q.splice(b,1),d--,c):null;case ROCK:return 0>v[b].getY()?(v[b].changeStatusOff(),c=v[b],v.splice(b,1),d--,c):null;case FENCE:return 0>w[b].getY()?(w[b].changeStatusOff(),c=w[b],w.splice(b,1),d--,c):null;case BONUS:return 0>u[b].getY()?(u[b].changeStatusOff(),c=u[b],u.splice(b,1),d--,c):null}};this._controlLineIfOverCanvas=
function(){0>t[b].getY()&&!0===t[b].getState()&&(t[b].changeState(),E[b].changeState(),0===b?b++:1===b&&b--,this.createLine(p.getX(),c));t[0].getY()<-SKIER_Y_START&&!1===t[0].getState()&&(0===b?(t[1].unload(),E[1].unload()):1===b&&(t[0].unload(),E[0].unload()));null!==t[1]&&t[1].getY()<-SKIER_Y_START&&!1===t[1].getState()&&(0===b?(t[1].unload(),E[1].unload()):1===b&&(t[0].unload(),E[0].unload()))};this.setScore=function(b){e+=b;g+=b;if(0<=g-SCORE_FOR_INCREASE_SPD&&n<=7*SPEED_INCREASE){var a=createBitmap(s_oSpriteLibrary.getSprite("speed_up"));
a.x=-800;a.y=CANVAS_HEIGHT/2;a.regX=324;a.regY=53;s_oStage.addChild(a);createjs.Tween.get(a).to({x:CANVAS_WIDTH/2},500).wait(100).call(function(){createjs.Tween.get(a).to({x:CANVAS_WIDTH+600},500).call(function(){s_oStage.removeChild(a)})});n+=SPEED_INCREASE;g=0}J.refreshScore(e);b>SCORE_TO_ADD&&J.bonusTaken()};this.gameOver=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSkiingAudio.volume=0,s_oSoundtrack.volume=0;K||(L=CEndPanel(s_oSpriteLibrary.getSprite("msg_box")),L.show(e+1,O),K=
!0)};this.unload=function(){J.unload();null!==L&&L.unload();x=[];B=[];C=[];D=[];r=[];q=[];v=[];w=[];createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};this.onHelpExit=function(){J.onExitFromHelp()};this.setUpdateFalse=function(){N=!1};this.setUpdateTrue=function(){N=!0};this.restartGame=function(){s_oStage.removeAllChildren();
s_oMain.gotoGame();$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("show_interlevel_ad")};this.update=function(){!1!==N&&(this._mouseMove(),R&&(this._moveSkier(),this._setRotation(),this.setScore(SCORE_TO_ADD)),this._moveObstacles(),!0===t[0].getUpdate()&&(t[0].update(p.getX()-7,k+n),E[0].update(p.getX()+7,k+n)),null!==t[1]&&!0===t[1].getUpdate()&&(t[1].update(p.getX()-7,k+n),E[1].update(p.getX()+7,k+n)),S.move(k+n),this._controlLineIfOverCanvas(),!0===O&&(13===p.getFrame()&&p.setUltimateFrame(),
0<k-.5&&(k-=DECELERATION_HITTED)))};s_oGame=this;SKIER_SPD=a.skier_spd;OBSTACLES_SPD=a.obstacles_spd;SCORE_TO_ADD=a.score_to_add;SCORE_BONUS=a.score_bonus;MAX_OBJECT_FOR_TYPE=a.max_object_for_type;MIN_OBJECT_ROW=a.min_object_row;MAX_OBJECT_ROW=a.max_object_row;SCORE_FOR_INCREASE_SPD=a.speed_increase_score;SPEED_INCREASE=a.speed_increase;this._init()}var s_oGame;
function CEndPanel(a){var c,b,d,e,g,f,h,k,l,m,n,y;this._init=function(a){g=createBitmap(a);g.x=0;g.y=0;k=new createjs.Text(""," 80px "+FONT,"#0f40ba");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2-100;k.textAlign="center";k.textBaseline="alphabetic";k.lineWidth=500;k.outline=3;h=new createjs.Text(""," 80px "+FONT,"#ffffff");h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2-100;h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=500;m=new createjs.Text(""," 50px "+FONT,"#0f40ba");m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/
2-30;m.textAlign="center";m.textBaseline="alphabetic";m.lineWidth=500;m.outline=3;l=new createjs.Text(""," 50px "+FONT,"#ffffff");l.x=CANVAS_WIDTH/2;l.y=CANVAS_HEIGHT/2-30;l.textAlign="center";l.textBaseline="alphabetic";l.lineWidth=500;f=new createjs.Container;f.alpha=0;f.visible=!1;f.addChild(g,m,l,k,h);s_oStage.addChild(f)};this.unload=function(){s_oStage.removeChild(f);n.unload();y.unload()};this.show=function(a,g){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.play("game_over").volume=
.6;k.text=TEXT_GAMEOVER;h.text=TEXT_GAMEOVER;m.text=TEXT_SCORE+a;l.text=TEXT_SCORE+a;f.visible=!0;!1===g&&s_oGame.setUpdateFalse();createjs.Tween.get(f).to({alpha:1},1200).call(function(){s_oGame.setUpdateFalse()});var x=s_oSpriteLibrary.getSprite("but_exit");d=CANVAS_WIDTH-170;e=CANVAS_HEIGHT/2-215;n=new CGfxButton(d,e,x,f);n.addEventListener(ON_MOUSE_UP,this._onExit,this);x=s_oSpriteLibrary.getSprite("but_restart");c=CANVAS_WIDTH-200;b=CANVAS_HEIGHT/2+160;y=new CGfxButton(c,b,x,f);y.addEventListener(ON_MOUSE_UP,
this._onRestart,this);$(s_oMain).trigger("share_event",a);$(s_oMain).trigger("save_score",[a])};this._onExit=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oGame.onExit()};this._onRestart=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oGame.restartGame();s_oStage.removeChild(f);n.unload();y.unload()};this._init(a);return this}
function CSpriteLibrary(){var a,c,b,d,e,g;this.init=function(f,h,k){b=c=0;d=f;e=h;g=k;a={}};this.addSprite=function(b,e){a.hasOwnProperty(b)||(a[b]={szPath:e,oSprite:new Image},c++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){e.call(g)};this._onSpriteLoaded=function(){d.call(g);++b==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=790,CANVAS_HEIGHT=960,EDGEBOARD_X=140,EDGEBOARD_Y=0,FONT="gotham_boldregular",FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,SKIER_X_START=CANVAS_WIDTH/2,SKIER_Y_START=150,SKIER_WIDTH=145,SKIER_HEIGHT=89,SKIER_FALLING_WIDTH=93,SKIER_FALLING_HEIGHT=180,TOLLERANCE=1.5,DECELERATION=.5,DECELERATION_HITTED=.3,CHANGE_DIRECTION_FASTER=1,MODIFIER=10,ACCELERATION=.5,NUM_ROW,HEIGHT_BETWEEN_OBSTACLES=250,NUM_ELEMENTS=5,TREE_WIDTH=169,TREE_HEIGHT=221,TREE2_WIDTH=198,TREE2_HEIGHT=252,ROCK_WIDTH=120,
ROCK_HEIGHT=92,FENCE_WIDTH=126,FENCE_HEIGHT=47,BONUS_WIDTH=59,BONUS_HEIGHT=89,MAX_OBSTACLE_WIDTH=TREE_WIDTH,MAX_OBSTACLE_HEIGHT=TREE_HEIGHT,SKIER_RECTANGLE_WIDTH=30,SKIER_RECTANGLE_HEIGHT=20,TREE_RECTANGLE_WIDTH=20,TREE_RECTANGLE_HEIGHT=20,TREE2_RECTANGLE_WIDTH=10,TREE2_RECTANGLE_HEIGHT=20,ROCK_RECTANGLE_WIDTH=40,ROCK_RECTANGLE_HEIGHT=30,FENCE_RECTANGLE_WIDTH=55,FENCE_RECTANGLE_HEIGHT=5,BONUS_RECTANGLE_WIDTH=59,BONUS_RECTANGLE_HEIGHT=49,SKIER_SPD,OBSTACLES_SPD,SCORE_TO_ADD,SCORE_BONUS,MAX_OBJECT_FOR_TYPE,
MIN_OBJECT_ROW,MAX_OBJECT_ROW,SCORE_FOR_INCREASE_SPD,SPEED_INCREASE,TREE=0,TREE2=1,ROCK=2,FENCE=3,BONUS=4,BG_GAME_INDEX=0,BG_GAME2_INDEX=1,LINE_INDEX=2,SKIER_INDEX=3,OBSACLE_INDEX=4,SCORE_INDEX=5,BUTTON_INDEX=6,SKIER_FALLING_INDEX=7,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5;
function CVector2(a,c){var b,d;this._init=function(a,c){b=a;d=c};this.add=function(a,c){b+=a;d+=c};this.addV=function(a){b+=a.getX();d+=a.getY()};this.scalarDivision=function(a){b/=a;d/=a};this.subV=function(a){b-=a.getX();d-=a.getY()};this.scalarProduct=function(a){b*=a;d*=a};this.invert=function(){b*=-1;d*=-1};this.dotProduct=function(a){return b*a.getX()+d*a.getY()};this.set=function(a,c){b=a;d=c};this.setV=function(a){b=a.getX();d=a.getY()};this.length=function(){return Math.sqrt(b*b+d*d)};this.length2=
function(){return b*b+d*d};this.normalize=function(){var a=this.length();0<a&&(b/=a,d/=a)};this.getNormalize=function(a){this.length();a.set(b,d);a.normalize()};this.rot90CCW=function(){var a=b;b=-d;d=a};this.rot90CW=function(){var a=b;b=d;d=-a};this.getRotCCW=function(a){a.set(b,d);a.rot90CCW()};this.getRotCW=function(a){a.set(b,d);a.rot90CW()};this.ceil=function(){b=Math.ceil(b);d=Math.ceil(d)};this.round=function(){b=Math.round(b);d=Math.round(d)};this.toString=function(){return"Vector2: "+b+", "+
d};this.print=function(){trace("Vector2: "+b+", "+d+"")};this.getX=function(){return b};this.getY=function(){return d};this._init(a,c)}
function CToggle(a,c,b,d){var e,g,f,h=[],k;this._init=function(a,b,c,d){g=[];f=[];var h=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});e=d;k=createSprite(h,"state_"+e,c.width/2/2,c.height/2,c.width/2,c.height);k.x=a;k.y=b;k.stop();s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);s_oStage.removeChild(k)};
this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;f[a]=c};this.addEventListenerWithParams=function(a,b,c,d){g[a]=b;f[a]=c;h=d};this.setActive=function(a){e=a;k.gotoAndStop("state_"+e)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");e=!e;k.gotoAndStop("state_"+e);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(f[ON_MOUSE_UP],h)};this.buttonDown=
function(){k.scaleX=.9;k.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],h)};this.setPosition=function(a,b){k.x=a;k.y=b};this.setVisible=function(a){k.visible=a};this._init(a,c,b,d)}
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return!0;return!1}
function getSize(a){var c=a.toLowerCase(),b=window.document,d=b.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var e=b.createElement("body");e.id="vpw-test-b";e.style.cssText="overflow:scroll";var g=b.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+c+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";e.appendChild(g);d.insertBefore(e,b.head);
a=7==g["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(e)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),d=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,e=0;b<a?(e=a-b,b+=e,d+=CANVAS_WIDTH/CANVAS_HEIGHT*e):d<c&&(e=c-d,d+=e,b+=CANVAS_HEIGHT/CANVAS_WIDTH*e);var e=a/2-b/2,g=c/2-d/2,f=CANVAS_WIDTH/d;if(g*f<-EDGEBOARD_X||e*f<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*
EDGEBOARD_X)),d=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,e=(a-b)/2,g=(c-d)/2,f=CANVAS_WIDTH/d;s_iOffsetX=-1*g*f;s_iOffsetY=-1*e*f;0<=e&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",d+"px");$("#canvas").css("height",b+"px");0>e?$("#canvas").css("top",e+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",g+"px")}}
function createBitmap(a,c,b){var d=new createjs.Bitmap(a),e=new createjs.Shape;c&&b?e.graphics.beginFill("#fff").drawRect(0,0,c,b):e.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=e;return d}function createSprite(a,c,b,d,e,g){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-d,e,g);a.hitArea=c;return a}
function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function rotateVector2D(a,c){var b=c.getX()*Math.cos(a)+c.getY()*Math.sin(a),d=c.getX()*-Math.sin(a)+c.getY()*Math.cos(a);c.set(b,d)}function tweenVectorsOnX(a,c,b){return a+b*(c-a)}function shuffle(a){for(var c=a.length,b,d;0!==c;)d=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[d],a[d]=b;return a}
function bubbleSort(a){var c;do{c=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(c=a[b],a[b]=a[b+1],a[b+1]=c,c=!0)}while(c)}function compare(a,c){return a.index>c.index?-1:a.index<c.index?1:0}function easeLinear(a,c,b,d){return b*a/d+c}function easeInQuad(a,c,b,d){return b*(a/=d)*a+c}function easeInSine(a,c,b,d){return-b*Math.cos(a/d*(Math.PI/2))+b+c}function easeInCubic(a,c,b,d){return b*(a/=d)*a*a+c}
function getTrajectoryPoint(a,c){var b=new createjs.Point,d=(1-a)*(1-a),e=a*a;b.x=d*c.start.x+2*(1-a)*a*c.traj.x+e*c.end.x;b.y=d*c.start.y+2*(1-a)*a*c.traj.y+e*c.end.y;return b}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=Math.floor(a-60*c);var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,c){var b,d;b=getBounds(a,.9);d=getBounds(c,.98);return calculateIntersection(b,d)}
function calculateIntersection(a,c){var b,d,e,g,f,h,k,l;b=a.x+(e=a.width/2);d=a.y+(g=a.height/2);f=c.x+(h=c.width/2);k=c.y+(l=c.height/2);b=Math.abs(b-f)-(e+h);d=Math.abs(d-k)-(g+l);return 0>b&&0>d?(b=Math.min(Math.min(a.width,c.width),-b),d=Math.min(Math.min(a.height,c.height),-d),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:b,height:d,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var d=a.children,e=d.length,g,f;for(f=0;f<e;f++)g=getBounds(d[f],1),g.x<b.x&&(b.x=g.x),g.y<b.y&&(b.y=g.y),g.x+g.width>b.x2&&(b.x2=g.x+g.width),g.y+g.height>b.y2&&(b.y2=g.y+g.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var h,k;a instanceof createjs.Bitmap?
(e=a.sourceRect||a.image,f=e.width*c,h=e.height*c):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(e=a.spriteSheet.getFrame(a.currentFrame),f=e.rect.width,h=e.rect.height,d=e.regX,k=e.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);d=d||0;f=f||0;k=k||0;h=h||0;b.regX=d;b.regY=k;e=a.localToGlobal(0-d,0-k);g=a.localToGlobal(f-d,h-k);f=a.localToGlobal(f-d,0-k);d=a.localToGlobal(0-d,h-k);b.x=Math.min(Math.min(Math.min(e.x,
g.x),f.x),d.x);b.y=Math.min(Math.min(Math.min(e.y,g.y),f.y),d.y);b.width=Math.max(Math.max(Math.max(e.x,g.x),f.x),d.x)-b.x;b.height=Math.max(Math.max(Math.max(e.y,g.y),f.y),d.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var c=a.length,b,d;0<c;)d=Math.floor(Math.random()*c),c--,b=a[c],a[c]=a[d],a[d]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(a){var d={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in d?document.body.className=d[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var d=c[b].split("=");if(d[0]==a)return d[1]}}
function CTextButton(a,c,b,d,e,g,f){var h,k,l,m,n;this._init=function(a,b,c,d,e,f,g){h=[];k=[];var z=createBitmap(c),r=Math.ceil(g/20);n=new createjs.Text(d,"bold "+g+"px "+e,"#000000");n.textAlign="center";n.textBaseline="alphabetic";var q=n.getBounds();n.x=c.width/2+r;n.y=Math.floor(c.height/2)+q.height/3+r;m=new createjs.Text(d,"bold "+g+"px "+e,f);m.textAlign="center";m.textBaseline="alphabetic";q=m.getBounds();m.x=c.width/2;m.y=Math.floor(c.height/2)+q.height/3;l=new createjs.Container;l.x=a;
l.y=b;l.regX=c.width/2;l.regY=c.height/2;l.addChild(z,n,m);s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;k[a]=c};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=
function(){l.scaleX=.9;l.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setTextPosition=function(a){m.y=a;n.y=a+2};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(a,c,b,d,e,g,f);return this}
function CSkier(a){var c,b,d,e,g;this._init=function(a){var h={images:[s_oSpriteLibrary.getSprite("skier_sprite")],framerate:30,frames:{width:SKIER_WIDTH,height:SKIER_HEIGHT,regX:SKIER_WIDTH/2,regY:SKIER_HEIGHT/2},animations:{idle:[0],left1:[1],left2:[2],left3:[3],left4:[4],left5:[5],left6:[6],left7:[7],left8:[8],left9:[9],right1:[10],right2:[11],right3:[12],right4:[13],right5:[14],right6:[15],right7:[16],right8:[17],right9:[18]}};b=new createjs.SpriteSheet(h);c=createSprite(b,"idle",0,0,SKIER_WIDTH,
SKIER_HEIGHT);c.x=SKIER_X_START;c.y=SKIER_Y_START;c.rotation=0;a.addChild(c);d=new createjs.Rectangle(c.x,c.y+20,SKIER_RECTANGLE_WIDTH,SKIER_RECTANGLE_HEIGHT);e="idle";s_oStage.setChildIndex(a,SKIER_INDEX)};this.falling=function(){s_oStage.setChildIndex(a,SKIER_FALLING_INDEX);var d={images:[s_oSpriteLibrary.getSprite("skier_falling")],framerate:20,frames:{width:SKIER_FALLING_WIDTH,height:SKIER_FALLING_HEIGHT,regX:SKIER_FALLING_WIDTH/2,regY:SKIER_FALLING_HEIGHT/2},animations:{idle:[2,13,"idle"]}};
b=new createjs.SpriteSheet(d);c.spriteSheet=b;c.gotoAndPlay("idle")};this.refreshRectangle=function(){d.setValues(c.x,c.y+20,SKIER_RECTANGLE_WIDTH,SKIER_RECTANGLE_HEIGHT)};this.getFrame=function(){return c.currentFrame};this.setUltimateFrame=function(){c.stop()};this.changeFrameStateLeft=function(a){c.gotoAndStop(a);e="left"};this.changeFrameStateRight=function(a){c.gotoAndStop(a);e="right"};this.changeFrameStateIdle=function(){c.gotoAndStop(0);e="idle"};this.returnState=function(){return e};this.getRectangle=
function(){return d};this.getSprite=function(){return c};this.addPos=function(a){c.x+=a};this.setPos=function(a){c.x+=a};this.getX=function(){return c.x};this.getY=function(){return c.y};this.setRotation=function(a){g=a};this.getRotation=function(){return g};this._init(a)}
function CScrollingBg(){var a=null,c=null;this._init=function(){var b=s_oSpriteLibrary.getSprite("bg_scroll_1");a=createBitmap(b);s_oStage.addChild(a);b=s_oSpriteLibrary.getSprite("bg_scroll_2");c=createBitmap(b);c.y=CANVAS_HEIGHT;s_oStage.addChild(c);s_oStage.setChildIndex(a,BG_GAME_INDEX);s_oStage.setChildIndex(c,BG_GAME2_INDEX)};this.move=function(b){a.y<=-CANVAS_HEIGHT&&(a.y=c.y+CANVAS_HEIGHT);c.y<=-CANVAS_HEIGHT&&(c.y=a.y+CANVAS_HEIGHT);a.y-=b;c.y-=b};this._init()}
function CPreloader(){var a,c,b,d,e,g,f;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();f=new createjs.Container;s_oStage.addChild(f)};this.unload=function(){f.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));f.addChild(h);h=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(h);d.x=CANVAS_WIDTH/2-h.width/2;d.y=CANVAS_HEIGHT-250;f.addChild(d);a=h.width;c=h.height;e=new createjs.Shape;e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,c);f.addChild(e);d.mask=
e;b=new createjs.Text("","30px "+FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-250;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";f.addChild(b);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;f.addChild(g)};this.refreshLoader=function(h){b.text=h+"%";e.graphics.clear();h=Math.floor(h*a/100);e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,h,c)};this._init()}
function CPausePanel(a){var c,b,d;this._init=function(a){c=createBitmap(a);c.x=0;c.y=0;d=new createjs.Text(""," 100px blackplotan","#008df0");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=500;b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(c,d);s_oStage.addChild(b);this.show()};this.unload=function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(){!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("game_over");d.text=TEXT_PAUSE;b.visible=!0;var a=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){a._initListener()})};this._onExit=function(){b.off("mousedown",this._onExit);s_oStage.removeChild(b);s_oGame.onPauseExit()};this._init(a);return this}
function CObstacle(a,c,b){var d,e,g,f;this._init=function(a,b,c){"tree"===c?d=TREE:"tree2"===c?d=TREE2:"rock"===c?d=ROCK:"fence"===c?d=FENCE:"bonus"===c&&(d=BONUS);g=new createjs.Container;s_oStage.addChild(g);d===BONUS?(c={images:[s_oSpriteLibrary.getSprite("bonus")],framerate:10,frames:{width:BONUS_WIDTH,height:BONUS_HEIGHT,regX:BONUS_WIDTH/2,regY:BONUS_HEIGHT},animations:{idle:[0,19,"idle"]}},c=new createjs.SpriteSheet(c),e=new createjs.Sprite(c,"idle"),e.stop()):e=createBitmap(s_oSpriteLibrary.getSprite(c));
e.x=a;e.y=b;switch(d){case TREE:e.regX=TREE_WIDTH/2;e.regY=TREE_HEIGHT;f=new createjs.Rectangle(e.x+TREE_RECTANGLE_WIDTH/2,e.y-TREE_RECTANGLE_HEIGHT,TREE_RECTANGLE_WIDTH,TREE_RECTANGLE_HEIGHT);break;case TREE2:e.regX=TREE2_WIDTH/2;e.regY=TREE2_HEIGHT;f=new createjs.Rectangle(e.x+TREE2_RECTANGLE_WIDTH/2+20,e.y-TREE2_RECTANGLE_HEIGHT,TREE2_RECTANGLE_WIDTH,TREE2_RECTANGLE_HEIGHT);break;case ROCK:e.regX=ROCK_WIDTH/2;e.regY=ROCK_HEIGHT;f=new createjs.Rectangle(e.x-ROCK_RECTANGLE_WIDTH/2+15,e.y-ROCK_RECTANGLE_HEIGHT,
ROCK_RECTANGLE_WIDTH,ROCK_RECTANGLE_HEIGHT);break;case FENCE:e.regX=FENCE_WIDTH/2;e.regY=FENCE_HEIGHT;f=new createjs.Rectangle(e.x,e.y,FENCE_RECTANGLE_WIDTH,FENCE_RECTANGLE_HEIGHT);break;case BONUS:f=new createjs.Rectangle(e.x,e.y,BONUS_RECTANGLE_WIDTH,BONUS_RECTANGLE_HEIGHT)}e.rotation=0;g.addChild(e);g.addChild(void 0)};this.refreshRectangle=function(){switch(d){case TREE:f.setValues(e.x+TREE_RECTANGLE_WIDTH/2,e.y-TREE_RECTANGLE_HEIGHT,TREE_RECTANGLE_WIDTH,TREE_RECTANGLE_HEIGHT);break;case TREE2:f.setValues(e.x+
TREE2_RECTANGLE_WIDTH/2+20,e.y-TREE2_RECTANGLE_HEIGHT,TREE2_RECTANGLE_WIDTH,TREE2_RECTANGLE_HEIGHT);break;case ROCK:f.setValues(e.x-ROCK_RECTANGLE_WIDTH/2,e.y-ROCK_RECTANGLE_HEIGHT,ROCK_RECTANGLE_WIDTH,ROCK_RECTANGLE_HEIGHT);break;case FENCE:f.setValues(e.x,e.y,FENCE_RECTANGLE_WIDTH,FENCE_RECTANGLE_HEIGHT);break;case BONUS:f.setValues(e.x,e.y-BONUS_RECTANGLE_HEIGHT,BONUS_RECTANGLE_WIDTH,BONUS_RECTANGLE_HEIGHT)}};this.getRectangle=function(){return f};this.changeStatusOn=function(a,b){e.x=a;e.y=b;
e.visible=!0;d===BONUS&&e.play()};this.changeStatusOff=function(){e.x=-150;e.y=-150;d===BONUS&&e.stop()};this.controlCollision=function(a,b){d===BONUS?null!==f.intersection(a)&&s_oGame.bonusHitted(b):null!==f.intersection(a)&&s_oGame.collisionFound(d)};this.setInvisible=function(){e.visible=!1};this.move=function(a){e.y-=a};this.getY=function(){return e.y};this.getX=function(){return e.x};this._init(a,c,b)}
function CMenu(){var a,c,b,d,e,g;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(b);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack.volume=1;var f=s_oSpriteLibrary.getSprite("but_play");d=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-120,f);d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-f.height/2-10,c=f.height/2+10,g=new CToggle(a,
c,f,s_bAudioActive),g.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(e);createjs.Tween.get(e).to({alpha:0},1E3).call(function(){e.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){d.unload();d=null;e.visible=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),g=null;s_oStage.removeChild(b);s_oMenu=b=null};this.refreshButtonPos=function(b,d){g.setPosition(a-
b,d+c)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoGame();$(s_oMain).trigger("start_session")};s_oMenu=this;this._init()}var s_oMenu=null;function toRadian(a){return Math.PI/180*a}function toDegree(a){return 180/Math.PI*a}function randRange(a,c){return Math.floor(Math.random()*(c-a+1))+a}
function angleBetweenVectors(a,c){var b=Math.acos(dotProductV2(a,c)/(a.length()*c.length()));return!0===isNaN(b)?0:b}function rotateVector2D(a,c){var b=c.getX()*Math.cos(a)+c.getY()*Math.sin(a),d=c.getX()*-Math.sin(a)+c.getY()*Math.cos(a);c.set(b,d)}function reflectVectorV2(a,c){var b=new CVector2,d=dotProductV2(a,c);b.set(a.getX()-2*d*c.getX(),a.getY()-2*d*c.getY());return b}function dotProductV2(a,c){return a.getX()*c.getX()+a.getY()*c.getY()}
function pointInRect(a,c){return a.getX()>c.x&&a.getX()<c.x+c.width&&a.getY()>c.y&&a.getY()<c.y+c.height}function distance2(a,c){return(c.getX()-a.getX())*(c.getX()-a.getX())+(c.getY()-a.getY())*(c.getY()-a.getY())}
function CMain(a){var c,b=0,d=0,e=STATE_LOADING,g,f,h;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;f=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();c=!0};this.soundLoaded=function(){b++;f.refreshLoader(Math.floor(b/d*100));if(b===d){f.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<
navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/falling.ogg","falling"),createjs.Sound.registerSound("./sounds/skiing_direction.ogg","skiing_direction"),
createjs.Sound.registerSound("./sounds/bonus.ogg","bonus"),createjs.Sound.registerSound("./sounds/skiing_idle.ogg","skiing_idle")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.mp3","click"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/falling.mp3",
"falling"),createjs.Sound.registerSound("./sounds/skiing_direction.mp3","skiing_direction"),createjs.Sound.registerSound("./sounds/bonus.mp3","bonus"),createjs.Sound.registerSound("./sounds/skiing_idle.mp3","skiing_idle")),d+=7)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");
s_oSpriteLibrary.addSprite("help_desktop","./sprites/help_desktop.png");s_oSpriteLibrary.addSprite("help_mobile","./sprites/help_mobile.png");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_scroll_1","./sprites/bg_scroll_1.jpg");s_oSpriteLibrary.addSprite("bg_scroll_2","./sprites/bg_scroll_2.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_restart",
"./sprites/but_restart.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("skier_sprite","./sprites/skier_sprite.png");s_oSpriteLibrary.addSprite("skier_falling","./sprites/skier_falling.png");s_oSpriteLibrary.addSprite("tree","./sprites/tree.png");s_oSpriteLibrary.addSprite("tree2","./sprites/tree_2.png");s_oSpriteLibrary.addSprite("rock","./sprites/rock.png");s_oSpriteLibrary.addSprite("fence","./sprites/fence.png");s_oSpriteLibrary.addSprite("bonus",
"./sprites/bonus.png");s_oSpriteLibrary.addSprite("bonus_hitted","./sprites/bonus_hitted.png");s_oSpriteLibrary.addSprite("speed_up","./sprites/speed_up.png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;f.refreshLoader(Math.floor(b/d*100));if(b===d){f.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=
function(){this._loadImages()};this.gotoMenu=function(){new CMenu;e=STATE_MENU};this.gotoGame=function(a,b,c){s_iMode=a;s_szImage=b;s_bNumActive=c;h=new CGame(g);e=STATE_GAME};this.gotoHelp=function(){new CHelp;e=STATE_HELP};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==c){var b=(new Date).getTime();
s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;g=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iMode,s_szImage,s_bNumActive,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack,s_oSkiingAudio,s_oCanvas;
function CLineStroke(a,c){var b,d=0,e=!0,g=!0;this._init=function(a){b=new createjs.Shape;b.y=SKIER_Y_START+10;s_oStage.addChild(b);s_oStage.setChildIndex(b,LINE_INDEX);b.graphics.beginStroke("black");b.graphics.moveTo(a,0)};this.update=function(a,c){!0===g&&(b.y-=c,!0===e&&(d+=c,b.graphics.lineTo(a,d)))};this.getY=function(){return b.y};this.getState=function(){return e};this.getUpdate=function(){return g};this.changeState=function(){e=!e;b.graphics.endStroke()};this.unload=function(){g=!1;s_oStage.removeChild(b)};
this._init(a,c)}TEXT_GAMEOVER="YOU LOST";TEXT_SCORE="YOUR SCORE IS: ";TEXT_PAUSE="PAUSE";TEXT_DESKTOP="Use your mouse to move the skier from side to side and avoid obstacles";TEXT_MOBILE="Swipe from side to side to move the skier and avoid obstacles";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CInterface(){var a,c,b,d,e,g,f,h,k=null,l,m;this._init=function(){var n=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-n.height/2-10;g=n.height/2+10;h=new CGfxButton(e,g,n,s_oStage);h.addEventListener(ON_MOUSE_UP,this._onExit,this);b=CANVAS_WIDTH-n.width/2-120;d=n.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n=s_oSpriteLibrary.getSprite("audio_icon"),f=new CToggle(b,d,n,s_bAudioActive),f.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),s_oStage.setChildIndex(f,BUTTON_INDEX);
a=50;c=CANVAS_HEIGHT-50;m=new createjs.Text("0pt","bold 50px "+FONT,"#ffffff");m.x=a;m.y=c;m.textAlign="left";m.textBaseline="alphabetic";m.outline=5;s_oStage.addChild(m);l=new createjs.Text("0pt","bold 50px "+FONT,"#0f40ba");l.x=a;l.y=c;l.textAlign="left";l.textBaseline="alphabetic";s_oStage.addChild(l);s_oStage.setChildIndex(h,BUTTON_INDEX);this.refreshButtonPos(s_iOffsetX,s_iOffsetY);k=new CHelp(s_oSpriteLibrary.getSprite("bg_help"))};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f.unload(),
f=null;h.unload();null!==k&&k.unload();s_oInterface=null};this.refreshButtonPos=function(c,k){h.setPosition(e-c,k+g);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||f.setPosition(b-c,k+d);m.x=a+c;l.x=a+c};this._onButRestartRelease=function(){s_oGame.restartGame()};this.onExitFromHelp=function(){k.unload();s_oGame.setUpdateTrue()};this.refreshScore=function(a){l.text=a+"pt";m.text=a+"pt"};this.bonusTaken=function(){createjs.Tween.get(l).to({scaleX:1.2,scaleY:1.2},200,createjs.Ease.backOut).call(function(){createjs.Tween.get(l).to({scaleX:1,
scaleY:1},200,createjs.Ease.backIn).call(function(){})});createjs.Tween.get(m).to({scaleX:1.2,scaleY:1.2},200,createjs.Ease.backOut).call(function(){createjs.Tween.get(m).to({scaleX:1,scaleY:1},200,createjs.Ease.backIn).call(function(){})})};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oGame.onExit()};s_oInterface=this;this._init();return this}
var s_oInterface=null;
function CHelp(a){var c,b,d,e,g,f,h,k,l,m,n,y;this._init=function(a){e=new createjs.Container;e.alpha=0;e.visible=!1;g=new createjs.Container;g.visible=!1;d=createBitmap(a);s_oStage.addChild(d);f=new createjs.Text(""," 40px "+FONT,"#ffffff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/3+20;f.textAlign="center";f.textBaseline="alphabetic";f.lineWidth=500;e.addChild(f);!1===s_bMobile?(f.text=TEXT_DESKTOP,f.text=TEXT_DESKTOP,l=createBitmap(s_oSpriteLibrary.getSprite("help_desktop")),l.x=CANVAS_WIDTH/2-120,
l.y=CANVAS_HEIGHT/2+20):(f.text=TEXT_MOBILE,f.text=TEXT_MOBILE,l=createBitmap(s_oSpriteLibrary.getSprite("help_mobile")),l.x=CANVAS_WIDTH/2-120,l.y=CANVAS_HEIGHT/2-15);e.addChild(l);s_oStage.addChild(e);h=new createjs.Text("AVOID OBSTACLES"," 40px "+FONT,"#ffffff");h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/3+30;h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=500;g.addChild(h);a=createBitmap(s_oSpriteLibrary.getSprite("tree"));a.x=CANVAS_WIDTH/2-240;a.y=CANVAS_HEIGHT/2-130;g.addChild(a);a=
createBitmap(s_oSpriteLibrary.getSprite("tree2"));a.x=CANVAS_WIDTH/2-130;a.y=CANVAS_HEIGHT/2-130;g.addChild(a);a=createBitmap(s_oSpriteLibrary.getSprite("rock"));a.x=CANVAS_WIDTH/2+100;a.y=CANVAS_HEIGHT/2-100;g.addChild(a);a=createBitmap(s_oSpriteLibrary.getSprite("fence"));a.x=CANVAS_WIDTH/2+80;a.y=CANVAS_HEIGHT/2;g.addChild(a);k=new createjs.Text("COLLECT"," 40px "+FONT,"#ffffff");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2+120;k.textAlign="center";k.textBaseline="alphabetic";k.lineWidth=500;g.addChild(k);
a=createBitmap(s_oSpriteLibrary.getSprite("bonus_hitted"));a.x=CANVAS_WIDTH/2-25;a.y=CANVAS_HEIGHT/2+120;g.addChild(a);a=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH-170;b=CANVAS_HEIGHT/2-215;y=new CGfxButton(c,b,a,s_oStage);y.addEventListener(ON_MOUSE_UP,this._onExit,this);s_oStage.addChild(g);m=createBitmap(s_oSpriteLibrary.getSprite("arrow"));m.x=CANVAS_WIDTH/2-270;m.y=CANVAS_HEIGHT/2;m.regX=30;m.regY=43;m.rotation=180;s_oStage.addChild(m);n=createBitmap(s_oSpriteLibrary.getSprite("arrow"));
n.x=CANVAS_WIDTH/2+270;n.y=CANVAS_HEIGHT/2;n.regX=30;n.regY=43;s_oStage.addChild(n);m.visible=!1;n.visible=!0;this.show()};this._initListener=function(){m.addEventListener("click",this._previousPage);n.addEventListener("click",this._nextPage)};this._previousPage=function(){e.visible=!0;g.visible=!1;m.visible=!1;n.visible=!0};this._nextPage=function(){e.visible=!1;g.visible=!0;m.visible=!0;n.visible=!1};this.show=function(){e.visible=!0;var a=this;createjs.Tween.get(e).to({alpha:1},500).call(function(){a._initListener()})};
this._onExit=function(){s_oGame.onHelpExit();$(s_oMain).trigger("start_level",1)};this.unload=function(){m.removeAllEventListeners("click");n.removeAllEventListeners("click");s_oStage.removeChild(e);s_oStage.removeChild(g);s_oStage.removeChild(n);s_oStage.removeChild(m);y.unload();s_oStage.removeChild(d)};this._init(a);return this};