function CBatter(a,c){var b=[],d=[];this._init=function(a,c){for(var f=0;f<NUM_SPRITE_BATTING;f++)b.push(createBitmap(s_oSpriteLibrary.getSprite("batter_batting_"+c+"_"+f))),b[f].x=BATTER_X,b[f].y=BATTER_Y,b[f].rotation=0,b[f].visible=!1,a.addChild(b[f]);for(f=0;f<NUM_SPRITE_PLAYERS;f++)d.push(createBitmap(s_oSpriteLibrary.getSprite("batter_idle_"+c+"_"+f))),d[f].x=BATTER_X,d[f].y=BATTER_Y,d[f].rotation=0,d[f].visible=!1,a.addChild(d[f]);d[0].visible=!0};this.viewBatter=function(a,c){c?b[a].visible=
!0:d[a].visible=!0};this.hideBatter=function(a,c){c?b[a].visible=!1:d[a].visible=!1};s_oBatter=this;this._init(a,c)}s_oBatter=null;
function CBallTarget(a,c,b,d){var e;this._init=function(a,b,c){var l=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[1],state_false:[0]}});e=createSprite(l,"state_false",c.width/2/2,c.height/2,c.width/2,c.height);e.x=a;e.y=b;e.stop();d.addChild(e)};this.unload=function(){d.removeChild(e)};this.changeState=function(a){e.gotoAndStop("state_"+a)};this.setPosition=function(a,b){e.x=a;e.y=b};this.setVisible=function(a){e.visible=
a};this._init(a,c,b);return this}
function CBall(a){var c=0,b=MAX_FRAMES_THROWN,d=0,e=0,g,f,k,l,m=!1,p,n,t,h,r,u={x:0,y:0},q={x:0,y:0},x;this._init=function(a){var b=s_oSpriteLibrary.getSprite("ball"),d=new createjs.SpriteSheet({images:[b],frames:{width:b.width/7,height:b.height/3,regX:b.width/2/7,regY:b.height/2/3},animations:{rotate:[0,20]}});h=createSprite(d,"normal",b.width/2/7,b.height/2/3,b.width/7,b.height/3);h.stop();f=g=STEP_SPEED_BALL;a.addChild(h)};this.reset=function(a){h.x=BALL_X;h.y=BALL_Y;h.regX=NaN;h.regY=NaN;h.scaleX=
.4;h.scaleY=.4;h.rotation=0;t=n=p=m=l=h.visible=!1;b=MAX_FRAMES_THROWN;this.changeTrajectory(a)};this.changeTrajectory=function(a){u.x=h.x;u.y=h.y;q.x=a.x;q.y=a.y;g=f;this._calculateMid(u,q)};this.addVelocity=function(){g<MAX_BALL_VELOCITY?f=g+=BALL_VELOCITY_ADDED:g=MAX_BALL_VELOCITY};this.viewBall=function(){h.visible=!0;this._calculateMid(u,q);k=!0};this.hideBall=function(){h.visible=!1};this._calculateMid=function(a,b){var d;d=Math.floor(50*Math.random())+1;d=!0===l?p?new createjs.Point(Math.floor(100*
Math.random())+CANVAS_WIDTH/2-100,TRAJECTORY_Y_BALL_CAUGHT-d):b.x<CANVAS_WIDTH/2?b.y>CANVAS_HEIGHT/2?new createjs.Point(Math.floor(CANVAS_WIDTH/2*Math.random())-100,TRAJECTORY_Y_BALL_CAUGHT-d):new createjs.Point(Math.floor(CANVAS_WIDTH/2*Math.random())-100,TRAJECTORY_Y_BALL_CAUGHT+d):b.x>CANVAS_WIDTH/2?b.y>CANVAS_HEIGHT/2?new createjs.Point(Math.floor(CANVAS_WIDTH/2*Math.random()+125)+250,TRAJECTORY_Y_BALL_CAUGHT-d):new createjs.Point(Math.floor(Math.random()*(q.x-u.x)+CANVAS_WIDTH/2+d),TRAJECTORY_Y_BALL_CAUGHT+
d):b.x>CANVAS_WIDTH/2?new createjs.Point(CANVAS_WIDTH/2-50,Math.floor(200*Math.random())+100):new createjs.Point(CANVAS_WIDTH/2+50,Math.floor(200*Math.random())+100):m?new createjs.Point(CANVAS_WIDTH_HALF+(END_POINT_X_MISSED_BALL-h.x),CANVAS_HEIGHT_HALF+(END_POINT_Y_MISSED_BALL-h.y)):.5>Math.random()?new createjs.Point(CANVAS_WIDTH/2-50,Math.floor(CANVAS_HEIGHT/2*Math.random()-100)+100):new createjs.Point(CANVAS_WIDTH/2+50,Math.floor(CANVAS_HEIGHT/2*Math.random()-100)+100);x={start:a,end:b,traj:d}};
this._updateBall=function(){c+=g;c>b&&(!m||l?!0===l?s_oGame._ballHitted(r):(m=!0,this.changeTrajectory({x:END_POINT_X_MISSED_BALL,y:END_POINT_Y_MISSED_BALL})):(s_oGame._ballMissed(),k=h.visible=!1),s_oGame.changeStateTarget(!0),playSound("drop_bounce_grass",1,0),c=0);var a;a=easeLinear(c,0,1,b);this.rolls();a=getTrajectoryPoint(a,x);h.x=a.x;h.y=a.y;!0===l?(0<=h.scaleX&&(h.scaleX-=.03,h.scaleY-=.03),g-=.035):1>h.scaleX?(h.scaleX+=.03,h.scaleY+=.03):g+=.2};this.getValue=function(){return h};this.hitControl=
function(){var a=!1;h.y>=PERFECT_HIT_Y-OFFSET_FOR_PERFECT_HIT&&h.y<=PERFECT_HIT_Y+OFFSET_FOR_PERFECT_HIT?a=p=!0:h.y>=ALMOST_MINUS&&h.y<=PERFECT_HIT_Y?a=t=!0:h.y<=ALMOST_PLUS&&h.y>=PERFECT_HIT_Y&&(a=n=!0);a&&(r=h.y-PERFECT_HIT_Y,0>r&&(r*=-1));k=!0};this.hitBall=function(){p?this.perfectHit():t?this.miniusHit():n&&this.plusHit();if(p||t||n)l=!0,u.x=h.x,u.y=h.y,g=STEP_SPEED_BALL+BEAT_FORCE,playSound("hit_ball",1,0),this._calculateMid(u,q),s_oGame.setScore(SCORE_HIT-r)};this.perfectHit=function(){x.traj.x<
CANVAS_WIDTH/2?(c=0,q.x=END_POINT_X_PERFECT_LEFT):(c=0,q.x=END_POINT_X_PERFECT_RIGHT);q.y=END_POINT_Y_PERFECT};this.miniusHit=function(){x.traj.x<CANVAS_WIDTH/2?(c=0,q.x=END_POINT_X_ALMOST_MINUS_RIGHT):(c=0,q.x=END_POINT_X_ALMOST_MINUS_LEFT);q.y=END_POINT_Y_ALMOST_MINUS};this.plusHit=function(){x.traj.x<CANVAS_WIDTH/2?(c=0,q.x=END_POINT_X_ALMOST_PLUS_RIGHT):(c=0,q.x=END_POINT_X_ALMOST_PLUS_LEFT);q.y=END_POINT_Y_ALMOST_PLUS};this.rolls=function(){2<g?h.rotation+=10:1<g?(d++,2===d&&(h.rotation+=8,d=
0)):.5<g&&(d++,3===d&&(h.rotation+=4,d=0));var a=this._goToPrevFrame;u.y>q.y&&(a=this._goToNextFrame);1.5<g?a():1<g?(d++,1<d&&(a(),d=0)):.5<g&&(d++,2<d&&(a(),d=0))};this._goToPrevFrame=function(){0===e?e=20:e--;h.gotoAndStop(e)};this._goToNextFrame=function(){21===e?e=1:e++;h.gotoAndStop(e)};this.setPosition=function(a,b){h.x=a;h.y=b};this.changeState=function(a){h.gotoAndStop(a)};this.update=function(){k&&this._updateBall()};this._init(a);return this}
function CAreYouSurePanel(a){var c,b,d,e,g,f,k;this._init=function(){g=new createjs.Container;g.alpha=0;f.addChild(g);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=.5;k.on("click",function(){});g.addChild(k);var a=s_oSpriteLibrary.getSprite("msg_box");c=createBitmap(a);c.x=CANVAS_WIDTH_HALF;c.y=CANVAS_HEIGHT_HALF;c.regX=.5*a.width;c.regY=.5*a.height;g.addChild(c);b=new createjs.Text(TEXT_ARE_SURE,"70px "+FONT2,"#ffffff");b.x=CANVAS_WIDTH/2+10;
b.y=CANVAS_HEIGHT_HALF-120;b.textAlign="center";b.textBaseline="middle";b.lineWidth=450;g.addChild(b);d=new CGfxButton(CANVAS_WIDTH/2+160,.5*CANVAS_HEIGHT+150,s_oSpriteLibrary.getSprite("but_yes"),g);d.addEventListener(ON_MOUSE_UP,this._onButYes,this);e=new CGfxButton(CANVAS_WIDTH/2-160,.5*CANVAS_HEIGHT+150,s_oSpriteLibrary.getSprite("but_no"),g);e.addEventListener(ON_MOUSE_UP,this._onButNo,this)};this.show=function(){createjs.Tween.get(g).to({alpha:1},150,createjs.quartOut).call(function(){s_oGame.pause(!0)})};
this.unload=function(){createjs.Tween.get(g).to({alpha:0},150,createjs.quartOut).call(function(){f.removeChild(g,k)})};this._onButYes=function(){createjs.Ticker.paused=!1;this.unload();s_oGame.onExit();k.removeAllEventListeners()};this._onButNo=function(){s_oGame.pause(!1);this.unload();k.removeAllEventListeners()};f=a;this._init()}
function CSpriteLibrary(){var a={},c,b,d,e,g,f;this.init=function(a,l,m){c={};d=b=0;e=a;g=l;f=m};this.addSprite=function(d,e){a.hasOwnProperty(d)||(a[d]=c[d]={szPath:e,oSprite:new Image,bLoaded:!1},b++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){b=0;g.call(f)};this._onSpriteLoaded=function(a){e.call(f,a);++d===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in c)c[a].oSprite.oSpriteLibrary=this,c[a].oSprite.szKey=a,
c[a].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},c[a].oSprite.src=c[a].szPath};this.setLoaded=function(b){a[b].bLoaded=!0};this.isLoaded=function(b){return a[b].bLoaded};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=790,CANVAS_HEIGHT=960,CANVAS_WIDTH_HALF=.5*CANVAS_WIDTH,CANVAS_HEIGHT_HALF=.5*CANVAS_HEIGHT,FONT="pixel_lcd7regular",FONT2="arialbold",EDGEBOARD_X=150,EDGEBOARD_Y=0,FPS=30,FPS_TIME=1/FPS,ROLL_BALL_RATE=60/FPS,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,BATTER_MODE=0,BOWLER_MODE=1,TOT_TEAMS=6,POINT_TEXT_EXCELLENT,POINT_TEXT_GREAT=85,TEXT_EXCELLENT_COLOR=["#fff","#5d96fe"],PLAYER_SELECTION_FLAG_START_POS={x:CANVAS_WIDTH_HALF-180,y:CANVAS_HEIGHT_HALF-
85},OPPONENT_SELECTION_FLAG_START_POS={x:CANVAS_WIDTH_HALF+72,y:CANVAS_HEIGHT_HALF-85},MAX_COL_FLAG=2,FLAG_OFFSET={x:110,y:75},TRAJECTORY_Y_BALL_CAUGHT=-250,BATTER_X=CANVAS_WIDTH/2-140,BATTER_Y=CANVAS_HEIGHT-620,BOWLER_X=CANVAS_WIDTH/2-50,BOWLER_Y=CANVAS_HEIGHT/2-475,BALL_X=BOWLER_X+86,BALL_Y=BOWLER_Y+50,BALL_TO_THROW,STEP_SPEED_BALL,BEAT_FORCE=.5,STEP_SPEED_STADIUM,TARGET_PREV_LUM_OFFSET={min:-12,max:-5},LAUNCH_DIR_OFFSET_RANGE=[{min:-90,max:-50},{min:-5,max:5},{min:50,max:90}],POLE_POSITION={x:CANVAS_WIDTH_HALF,
y:CANVAS_HEIGHT-200},OFFSET_FOR_HIT,OFFSET_FOR_PERFECT_HIT,PERFECT_HIT_X=BALL_X-36,PERFECT_HIT_Y=CANVAS_HEIGHT-410,ALMOST_MINUS,ALMOST_PLUS,END_POINT_X_THROWN=PERFECT_HIT_X,END_POINT_Y_THROWN=PERFECT_HIT_Y,END_POINT_X_MISSED_BALL=POLE_POSITION.x,END_POINT_Y_MISSED_BALL=POLE_POSITION.y,END_POINT_X_ALMOST_MINUS_LEFT=CANVAS_WIDTH/2-200,END_POINT_X_ALMOST_MINUS_RIGHT=CANVAS_WIDTH/2+200,END_POINT_Y_ALMOST_MINUS=50,END_POINT_X_ALMOST_PLUS_LEFT=CANVAS_WIDTH/2-300,END_POINT_X_ALMOST_PLUS_RIGHT=CANVAS_WIDTH/
2+300,END_POINT_Y_ALMOST_PLUS=50,END_POINT_X_PERFECT_LEFT=CANVAS_WIDTH/2-100,END_POINT_X_PERFECT_RIGHT=CANVAS_WIDTH/2+100,END_POINT_Y_PERFECT=0,MAX_FRAMES_THROWN=40,START_POINT_STADIUM_X=CANVAS_WIDTH/2,START_POINT_STADIUM_Y=CANVAS_HEIGHT/2+250,NUM_SPRITE_PLAYERS=40,NUM_SPRITE_BATTING=36,NUM_SPRITE_BOWLER=56,NUM_SPRITE_BATTER_BOWLER_MODE=81,STEP_RATE=1.5,PHYSICS_ACCURACY=3,MOBILE_OFFSET_GLOVES_X=-45,MOBILE_OFFSET_GLOVES_Y=-38,BALL_VELOCITY_MULTIPLIER=1,PHYSICS_STEP=1/FPS,BALL_MASS=.16,BALL_RADIUS=
.6,BALL_LINEAR_DAMPING=.2,OFFSET_BALL_POS_X=10,OBJECT,TEXT_SIZE=[50,65,80],TIME_TRY_TO_SHOT_BALL_OPPONENT=.7,MIN_BALL_VEL_ROTATION=.1,TIME_RESET_AFTER_GOAL=1,TIME_RESET_AFTER_KEEPER_SAVED=2,TIME_RESET_AFTER_PERFECT_KEEPER_SAVED=3,TIME_BALL_IN_HAND=1E3,FOV=35,INTERVAL_SHOOT=1,HAND_KEEPER_ANGLE_RATE=.15,LIMIT_HAND_RANGE_POS={x:8.8,zMax:5.1,zMin:-8.5},POSITION_BALL={x:60,y:220,z:0},LINE_GOAL_SIZE={width:17.5,depth:1,height:15.5},GOAL_LINE_POS={x:0,y:10,z:-2.7},GLOVE_SIZE={width:1.4,depth:1,height:1.7},
LEFT_GLOVE_POSITION={x:-1.5,y:40,z:0},RIGHT_GLOVE_POSITION={x:1.5,y:40,z:0},LAUNCH_BALL_IMPULSE={x:-4.47,y:0,z:1},LEFT_GLOVE=0,RIGHT_GLOVE=1,GLOVE_REG=[{x:3,y:-5},{x:-3,y:-5}],SHOW_3D_RENDER=!1,CAMERA_TEST=!1,MOUSE_SENSIBILTY=.03,OFFSET_MOUSE_X=-75,SCORE_ERROR_MULTIPLIER=20,INTENSITY_DISPLAY_SHOCK=[{x:30,y:20,time:75},{x:50,y:25,time:75},{x:70,y:30,time:75},{x:90,y:40,time:75}],CAMERA_POSITION={x:0,y:0,z:100},NEAR=10,FAR=2E3,STATE_INIT=0,STATE_PLAY=1,STATE_FINISH=2,STATE_PAUSE=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=
1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,HIT_LEFT=0,HIT_CENTER=1,HIT_RIGHT=2;
function CToggle(a,c,b,d){var e,g,f,k=[],l;this._init=function(a,b,d,c){g=[];f=[];var h=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}});e=c;l=createSprite(h,"state_"+e,d.width/2/2,d.height/2,d.width/2,d.height);l.x=a;l.y=b;l.cursor="pointer";l.stop();s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown",this.buttonDown);l.off("pressup",this.buttonRelease);s_oStage.removeChild(l)};
this._initListener=function(){l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){g[a]=b;f[a]=d};this.addEventListenerWithParams=function(a,b,d,c){g[a]=b;f[a]=d;k=c};this.setActive=function(a){e=a;l.gotoAndStop("state_"+e)};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");e=!e;l.gotoAndStop("state_"+e);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(f[ON_MOUSE_UP],k)};this.buttonDown=
function(){l.scaleX=.9;l.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],k);playSound("click",1,0)};this.setPosition=function(a,b){l.x=a;l.y=b};this.setVisible=function(a){l.visible=a};this._init(a,c,b,d)}var s_fInverseScaling=0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}$(window).resize(function(){sizeHandler()});
function getSize(a){var c=a.toLowerCase(),b=window.document,d=b.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var e=b.createElement("body");e.id="vpw-test-b";e.style.cssText="overflow:scroll";var g=b.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+c+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";e.appendChild(g);d.insertBefore(e,b.head);
a=7==g["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(e)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),d=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,e;b<a?(e=a-b,b+=e,d+=CANVAS_WIDTH/CANVAS_HEIGHT*e):d<c&&(e=c-d,d+=e,b+=CANVAS_HEIGHT/CANVAS_WIDTH*e);e=a/2-b/2;var g=c/2-d/2,f=CANVAS_WIDTH/d;if(g*f<-EDGEBOARD_X||e*f<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*EDGEBOARD_X)),
d=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,e=(a-b)/2,g=(c-d)/2,f=CANVAS_WIDTH/d;s_fInverseScaling=f;s_iOffsetX=-1*g*f;s_iOffsetY=-1*e*f;0<=e&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oTeamChoose&&s_oTeamChoose.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",d+"px");$("#canvas").css("height",b+"px");0>e?($("#canvas").css("top",e+"px"),s_iCanvasOffsetHeight=
e):($("#canvas").css("top","0px"),s_iCanvasOffsetHeight=0);$("#canvas").css("left",g+"px");resizeCanvas3D();s_iCanvasResizeWidth=d;s_iCanvasResizeHeight=b;s_iCanvasOffsetWidth=g}}function createBitmap(a,c,b){var d=new createjs.Bitmap(a),e=new createjs.Shape;c&&b?e.graphics.beginFill("#fff").drawRect(0,0,c,b):e.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=e;return d}
function createSprite(a,c,b,d,e,g){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-d,e,g);a.hitArea=c;return a}function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function rotateVector2D(a,c){var b=c.getX()*Math.cos(a)+c.getY()*Math.sin(a),d=c.getX()*-Math.sin(a)+c.getY()*Math.cos(a);c.set(b,d)}function tweenVectorsOnX(a,c,b){return a+b*(c-a)}
function shuffle(a){for(var c=a.length,b,d;0!==c;)d=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[d],a[d]=b;return a}function bubbleSort(a){var c;do{c=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(c=a[b],a[b]=a[b+1],a[b+1]=c,c=!0)}while(c)}function compare(a,c){return a.index>c.index?-1:a.index<c.index?1:0}function easeLinear(a,c,b,d){return b*a/d+c}function easeInQuad(a,c,b,d){return b*(a/=d)*a+c}function easeInSine(a,c,b,d){return-b*Math.cos(a/d*(Math.PI/2))+b+c}
function easeInCubic(a,c,b,d){return b*(a/=d)*a*a+c}function easeOutCubic(a,c,b,d){return b*((a=a/d-1)*a*a+1)+c}function getTrajectoryPoint(a,c){var b=new createjs.Point,d=(1-a)*(1-a),e=a*a;b.x=d*c.start.x+2*(1-a)*a*c.traj.x+e*c.end.x;b.y=d*c.start.y+2*(1-a)*a*c.traj.y+e*c.end.y;return b}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=Math.floor(a-60*c);var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,c){var b,d;b=getBounds(a,.9);d=getBounds(c,.98);return calculateIntersection(b,d)}function calculateIntersection(a,c){var b,d,e,g,f,k,l,m;b=a.x+(e=a.width/2);d=a.y+(g=a.height/2);f=c.x+(k=c.width/2);l=c.y+(m=c.height/2);b=Math.abs(b-f)-(e+k);d=Math.abs(d-l)-(g+m);return 0>b&&0>d?(b=Math.min(Math.min(a.width,c.width),-b),d=Math.min(Math.min(a.height,c.height),-d),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:b,height:d,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var d=a.children,e=d.length,g,f;for(f=0;f<e;f++)g=getBounds(d[f],1),g.x<b.x&&(b.x=g.x),g.y<b.y&&(b.y=g.y),g.x+g.width>b.x2&&(b.x2=g.x+g.width),g.y+g.height>b.y2&&(b.y2=g.y+g.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var k,l;a instanceof createjs.Bitmap?
(e=a.sourceRect||a.image,f=e.width*c,k=e.height*c):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(e=a.spriteSheet.getFrame(a.currentFrame),f=e.rect.width,k=e.rect.height,d=e.regX,l=e.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);d=d||0;f=f||0;l=l||0;k=k||0;b.regX=d;b.regY=l;e=a.localToGlobal(0-d,0-l);g=a.localToGlobal(f-d,k-l);f=a.localToGlobal(f-d,0-l);d=a.localToGlobal(0-d,k-l);b.x=Math.min(Math.min(Math.min(e.x,
g.x),f.x),d.x);b.y=Math.min(Math.min(Math.min(e.y,g.y),f.y),d.y);b.width=Math.max(Math.max(Math.max(e.x,g.x),f.x),d.x)-b.x;b.height=Math.max(Math.max(Math.max(e.y,g.y),f.y),d.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var c=a.length,b,d;0<c;)d=Math.floor(Math.random()*c),c--,b=a[c],a[c]=a[d],a[d]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(a){var d={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in d?document.body.className=d[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var d=c[b].split("=");if(d[0]==a)return d[1]}}function playSound(a,c,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:c}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}function setVolume(a,c){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=c}
function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(c)}function destroySound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.destroy()}function resizeCanvas3D(){$("canvas").each(function(){"#canvas"!=$(this).attr("id")&&($(this).css("width",$("#canvas").css("width")),$(this).css("height",$("#canvas").css("height")),$(this).css("position",$("#canvas").css("position")),$(this).css("left",$("#canvas").css("left")),$(this).css("top",$("#canvas").css("top")))})}
function createOrthoGraphicCamera(){var a=new THREE.PerspectiveCamera(FOV,CANVAS_WIDTH/CANVAS_HEIGHT,NEAR,FAR);a.rotation.x=Math.PI/180*90;a.position.set(0,0,0);a.updateProjectionMatrix();a.updateMatrixWorld();return a}Math.radians=function(a){return a*Math.PI/180};Math.degrees=function(a){return 180*a/Math.PI};
function CTextButton(a,c,b,d,e,g,f,k){var l,m,p,n,t,h,r=!1;this._init=function(a,b,d,c,e,f,g,k){l=[];m=[];p=[];var r=createBitmap(d);h=new createjs.Text(c,k+"px "+e,g);h.textAlign="center";h.textBaseline="middle";h.x=d.width/2;h.y=d.height/2;h.outline=3;t=new createjs.Text(c,k+"px "+e,f);t.textAlign="center";t.textBaseline="middle";t.x=h.x;t.y=h.y;n=new createjs.Container;n.x=a;n.y=b;n.regX=d.width/2;n.regY=d.height/2;n.addChild(r,h,t);s_bMobile||(n.cursor="pointer");s_oStage.addChild(n);this._initListener()};
this.unload=function(){n.off("mousedown");n.off("pressup");s_oStage.removeChild(n)};this.setVisible=function(a){n.visible=a};this._initListener=function(){n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){l[a]=b;m[a]=d};this.addEventListenerWithParams=function(a,b,d,c){l[a]=b;m[a]=d;p=c};this.buttonRelease=function(){r||(n.scaleX=1,n.scaleY=1,l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(m[ON_MOUSE_UP],p))};this.buttonDown=function(){r||(n.scaleX=.9,
n.scaleY=.9,l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN],p))};this.block=function(a){r=a;n.scaleX=1;n.scaleY=1};this.setTextPosition=function(a){t.y=a;h.y=a+2};this.setPosition=function(a,b){n.x=a;n.y=b};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this._init(a,c,b,d,e,g,f,k);return this}
function CTeamChoose(){var a,c,b,d,e,g,f,k,l,m,p,n,t,h,r,u,q,x,B,v,C,w,z,D,A;this._init=function(){f=createBitmap(s_oSpriteLibrary.getSprite("bg_select_team"));s_oStage.addChild(f);B=new createjs.Container;D=0;A=TEXT_TEAM.length-1;w=this.createFlagSelection(PLAYER_SELECTION_FLAG_START_POS.x,PLAYER_SELECTION_FLAG_START_POS.y,1500,this._onButPlayerTeamChoose);z=this.createFlagSelection(OPPONENT_SELECTION_FLAG_START_POS.x,OPPONENT_SELECTION_FLAG_START_POS.y,1500,this._onButOppTeamChoose);var h=s_oSpriteLibrary.getSprite("flag_selection");
q=createBitmap(h);q.x=w[0].getX();q.y=w[0].getY();q.regX=.5*h.width;q.regY=.5*h.height;x=createBitmap(h);x.x=z[TEXT_TEAM.length-1].getX();x.y=z[TEXT_TEAM.length-1].getY();x.regX=.5*h.width;x.regY=.5*h.height;s_oStage.addChild(B);B.y=12;m=this.createText(TEXT_SELECT_OPPONENT_TEAM,22,200).container;m.x=CANVAS_WIDTH_HALF+130;m.y=304;s_oStage.addChild(m);l=this.createText(TEXT_SELECT_YOUR_TEAM,22,200).container;l.x=CANVAS_WIDTH_HALF-120;l.y=304;s_oStage.addChild(l);h=this.createText(TEXT_TEAM[0],30,500);
p=h.container;p.x=CANVAS_WIDTH_HALF-120;p.y=CANVAS_HEIGHT_HALF+132;v=h.text;s_oStage.addChild(p);h=this.createText(TEXT_TEAM[TEXT_TEAM.length-1],30,500);n=h.container;n.x=CANVAS_WIDTH_HALF+120;n.y=CANVAS_HEIGHT_HALF+132;C=h.text;s_oStage.addChild(n);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h=s_oSpriteLibrary.getSprite("audio_icon"),e=CANVAS_WIDTH-h.width/2-60,g=h.height/2+20,r=new CToggle(e,g,h,s_bAudioActive,s_oStage),r.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);a=.5*CANVAS_WIDTH+
300;c=.5*CANVAS_HEIGHT+400;h=s_oSpriteLibrary.getSprite("but_continue");k=new CGfxButton(a,c,h,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this);k.pulseAnimation();h=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-h.width/2-15;d=h.height/2+20;u=new CGfxButton(b,d,h,s_oStage);u.addEventListener(ON_MOUSE_UP,this._onExit,this);t=new createjs.Shape;t.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(t);createjs.Tween.get(t).to({alpha:0},
1E3).call(function(){t.visible=!1;B.addChild(q,x)});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this._createFlag=function(a,b,d,c,e,f,h){var g=s_oSpriteLibrary.getSprite("flag_"+a);b=new CGfxButton(b,d,g,h);b.addEventListenerWithParams(ON_MOUSE_UP,f,this,a);a=b.getButton();a.scaleX=0;a.scaleY=0;createjs.Tween.get(a).wait(c).to({scaleY:1,scaleX:1},e,createjs.Ease.elasticOut);return b};this.createFlagSelection=function(a,b,d,c){for(var e=[],f=a,h=0;h<TOT_TEAMS;h++)e[h]=this._createFlag(h,f,b,Math.floor(500*
Math.random()),d,c,B),0===h%MAX_COL_FLAG-1?(f=a,b+=FLAG_OFFSET.y):f+=FLAG_OFFSET.x;return e};this.createText=function(a,b,d){var c=new createjs.Container;a=new createjs.Text(a,b+"px "+FONT2,"#ffffff");a.textAlign="center";a.lineWidth=d;a.x=0;a.y=0;c.addChild(a);return{container:c,text:a}};this.refreshButtonPos=function(f,h){u.setPosition(b-f,h+d);k.setPosition(a-f,c-h);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.setPosition(e-f,h+g)};this._onButPlayerTeamChoose=function(a){D!==a&&A!==a&&(q.x=w[a].getX(),
q.y=w[a].getY(),v.text=TEXT_TEAM[a],D=a)};this._onButOppTeamChoose=function(a){A!==a&&D!==a&&(x.x=z[a].getX(),x.y=z[a].getY(),C.text=TEXT_TEAM[a],A=a)};this.unload=function(){for(var a=0;a<w.length;a++)w[a].unload(),w[a]=null;for(a=0;a<z.length;a++)z[a].unload(),z[a]=null;u.unload();u=null;k.unload();k=null;h.unload();h=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r.unload(),r=null;s_oStage.removeAllChildren();createjs.Tween.removeAllTweens();s_oTeamChoose=null};this.loadingScreen=function(){var a=
new createjs.Container;a.alpha=0;h=new CLoadingScreen(a,this);createjs.Tween.get(a).to({alpha:1},250,createjs.Ease.cubicOut)};this._onExit=function(){this.unload();s_oMain.gotoMenu()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButContinueRelease=function(){k.block(!0);this.loadingScreen();s_oMain._loadChoosedTeam(D,A)};s_oTeamChoose=this;this._init()}var s_oTeamChoose=null;
function CPreloader(){var a,c,b,d,e,g,f;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.loadSprites();f=new createjs.Container;s_oStage.addChild(f)};this.unload=function(){f.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},
500).call(function(){a.unload();s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));f.addChild(k);k=createBitmap(s_oSpriteLibrary.getSprite("logo_menu"));k.x=200;k.y=90;f.addChild(k);k=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(k);d.x=CANVAS_WIDTH/2-k.width/2;d.y=CANVAS_HEIGHT-250;f.addChild(d);a=k.width;
c=k.height;e=new createjs.Shape;e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,c);f.addChild(e);d.mask=e;b=new createjs.Text("","30px Arial","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-250;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";f.addChild(b);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;f.addChild(g)};this.refreshLoader=function(f){b.text=f+"%";e.graphics.clear();f=Math.floor(f*
a/100);e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,f,c)};this._init()}function CPole(a,c,b,d){var e;this._init=function(a,b,c){e=createBitmap(c);e.x=a;e.y=b;e.regX=.5*c.width;e.regY=.5*c.height;d.addChild(e)};this.getValue=function(){return e};this.unload=function(){d.removeChild(e)};this._init(a,c,b);return this}
function CPause(){var a,c;this._init=function(){var b=new createjs.Container;b.alpha=1;a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=.5;var d=new createjs.Shape;d.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.hitArea=d;a.on("click",function(){});b.addChild(a);var d=s_oSpriteLibrary.getSprite("msg_box"),e=createBitmap(d);e.x=CANVAS_WIDTH_HALF;e.y=CANVAS_HEIGHT_HALF;e.regX=.5*d.width;e.regY=.5*d.height;b.addChild(e);d=
new createjs.Text(TEXT_PAUSE,"80px "+FONT2,"#ffffff");d.x=.5*CANVAS_WIDTH;d.y=.5*CANVAS_HEIGHT-200;d.textAlign="center";d.lineWidth=600;b.addChild(d);d=s_oSpriteLibrary.getSprite("but_continue");c=new CGfxButton(.5*CANVAS_WIDTH,.5*CANVAS_HEIGHT+70,d,b);c.addEventListenerWithParams(ON_MOUSE_UP,this._onLeavePause,this,b);c.pulseAnimation();s_oStage.addChild(b);s_oGame.pause(!0)};this.unload=function(){a.removeAllEventListeners();c.unload();c=null;s_oStage.removeChild(void 0)};this._onLeavePause=function(a){s_oGame.pause(!1);
createjs.Tween.get(a).to({alpha:0},100,createjs.quartIn).call(function(){s_oInterface.unloadPause()})};this._init();return this}
function CMenu(){var a,c,b,d,e,g,f,k,l,m;this._init=function(){e=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(e);g=createBitmap(s_oSpriteLibrary.getSprite("logo_menu"));g.x=200;g.y=90;s_oStage.addChild(g);var p=s_oSpriteLibrary.getSprite("but_play");f=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-225,p);f.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-p.height/2-
10,d=p.height/2+10,l=new CToggle(b,d,p,s_bAudioActive),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);p=s_oSpriteLibrary.getSprite("but_credits");a=p.height/2+10;c=p.height/2+10;m=new CGfxButton(a,c,p,s_oStage);m.addEventListener(ON_MOUSE_UP,this._onCredits,this);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(k);createjs.Tween.get(k).to({alpha:0},1E3).call(function(){k.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};
this.unload=function(){f.unload();f=null;k.visible=!1;m.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;s_oStage.removeAllChildren();s_oMenu=null};this.refreshButtonPos=function(e,f){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(b-e,f+d);m.setPosition(a+e,f+c)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCredits=function(){new CCreditsPanel};this._onButPlayRelease=function(){this.unload();s_oMain.gotoTeamChoose()};
s_oMenu=this;this._init()}var s_oMenu=null;
function CMain(a){var c,b=0,d=0,e=STATE_LOADING,g,f,k,l,m=[];this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_oStage.preventSelection=!1;s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;this.setLoadedArray();f=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();c=!0};this.soundLoaded=function(a){b++;f.refreshLoader(Math.floor(b/d*100));b===d&&(f.unload(),s_oSoundTrack=playSound("soundtrack",1,-1),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?
(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/buzzer.ogg","buzzer"),createjs.Sound.registerSound("./sounds/countdown_1.ogg","countdown1"),createjs.Sound.registerSound("./sounds/countdown_2.ogg","countdown2"),createjs.Sound.registerSound("./sounds/drop_bounce_grass.ogg","drop_bounce_grass"),createjs.Sound.registerSound("./sounds/hit_ball.ogg",
"hit_ball"),createjs.Sound.registerSound("./sounds/crowd_cheering.ogg","crowd_cheering"),createjs.Sound.registerSound("./sounds/applauses.ogg","applauses"),createjs.Sound.registerSound("./sounds/crowd_ohhh.ogg","crowd_ohhh"),createjs.Sound.registerSound("./sounds/click.ogg","click")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/buzzer.mp3",
"buzzer"),createjs.Sound.registerSound("./sounds/countdown_1.mp3","countdown1"),createjs.Sound.registerSound("./sounds/countdown_2.mp3","countdown2"),createjs.Sound.registerSound("./sounds/drop_bounce_grass.mp3","drop_bounce_grass"),createjs.Sound.registerSound("./sounds/hit_ball.mp3","hit_ball"),createjs.Sound.registerSound("./sounds/crowd_cheering.mp3","crowd_cheering"),createjs.Sound.registerSound("./sounds/applauses.mp3","applauses"),createjs.Sound.registerSound("./sounds/crowd_ohhh.mp3","crowd_ohhh"),
createjs.Sound.registerSound("./sounds/click.mp3","click")),d+=10)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("preloader_anim",
"./sprites/preloader_anim.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("score_panel","./sprites/score_panel.png");s_oSpriteLibrary.addSprite("ball","./sprites/ball.png");s_oSpriteLibrary.addSprite("1","./sprites/1.png");s_oSpriteLibrary.addSprite("2","./sprites/2.png");s_oSpriteLibrary.addSprite("3","./sprites/3.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("logo_credits","./sprites/logo_credits.png");
s_oSpriteLibrary.addSprite("ball_target","./sprites/ball_target.png");s_oSpriteLibrary.addSprite("bg_select_team","./sprites/bg_select_team.jpg");s_oSpriteLibrary.addSprite("bg_select_mode","./sprites/bg_select_mode.jpg");s_oSpriteLibrary.addSprite("flag_selection","./sprites/flag_selection.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("pole_0","./sprites/pole_0.png");s_oSpriteLibrary.addSprite("pole_1","./sprites/pole_1.png");s_oSpriteLibrary.addSprite("but_pause",
"./sprites/but_pause.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("bg_text","./sprites/bg_text.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("key_up","./sprites/key_up.png");s_oSpriteLibrary.addSprite("key_left",
"./sprites/key_left.png");s_oSpriteLibrary.addSprite("key_right","./sprites/key_right.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");for(var a=0;a<TOT_TEAMS;a++)s_oSpriteLibrary.addSprite("flag_"+a,"./sprites/flag_"+a+".png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;f.refreshLoader(Math.floor(b/d*100));b===d&&(f.unload(),s_oSoundTrack=playSound("soundtrack",1,-1),this.gotoMenu())};this._loadChoosedTeam=function(a,
c){s_iPlayerTeam=a;s_iOpponentTeam=c;d=b=0;if(m[a]&&m[c])this.gotoGame(s_iPlayerTeam,s_iOpponentTeam);else{s_oSpriteLibrary.init(this._onTeamsLoaded,this._onAllImagesLoaded,this);for(var e=0;e<NUM_SPRITE_BATTING;e++)!1===m[a]&&s_oSpriteLibrary.addSprite("batter_batting_"+a+"_"+e,"./sprites/batter_hit_"+a+"/batter_batting_"+a+"_"+e+".png"),!1===m[c]&&s_oSpriteLibrary.addSprite("batter_batting_"+c+"_"+e,"./sprites/batter_hit_"+c+"/batter_batting_"+c+"_"+e+".png");for(e=0;e<NUM_SPRITE_PLAYERS;e++)!1===
m[a]&&s_oSpriteLibrary.addSprite("batter_idle_"+a+"_"+e,"./sprites/batter_idle_"+a+"/batter_idle_"+a+"_"+e+".png"),!1===m[c]&&s_oSpriteLibrary.addSprite("batter_idle_"+c+"_"+e,"./sprites/batter_idle_"+c+"/batter_idle_"+c+"_"+e+".png");for(e=0;e<NUM_SPRITE_BOWLER;e++)!1===m[a]&&s_oSpriteLibrary.addSprite("bowler_"+a+"_"+e,"./sprites/bowler_"+a+"/bowler_"+a+"_"+e+".png"),!1===m[c]&&s_oSpriteLibrary.addSprite("bowler_"+c+"_"+e,"./sprites/bowler_"+c+"/bowler_"+c+"_"+e+".png");d+=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()}};this._onTeamsLoaded=function(){b++;b===d&&this.gotoGame(s_iPlayerTeam,s_iOpponentTeam)};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.setLoadedArray=function(){for(var a=0;a<TOT_TEAMS;a++)m[a]=!1};this.gotoMenu=function(){new CMenu;e=STATE_MENU};this.gotoGame=function(a,b){l.unload();m[s_iOpponentTeam]=!0;m[s_iPlayerTeam]=!0;k=new CGame(g,a,b);e=STATE_GAME};this.gotoTeamChoose=function(){l=new CTeamChoose;
e=STATE_MENU};this.stopUpdate=function(){c=!1};this.startUpdate=function(){c=!0};this._update=function(a){if(!1!==c){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&k.update();s_oStage.update(a)}};s_oMain=this;g=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iPlayerTeam,s_iOpponentTeam,s_iMode,s_iAdsLevel=1,s_bBounce=!0,s_oDrawLayer,s_oStage,s_oMain,s_oStadium,s_oBall,s_oSpriteLibrary,s_oSoundTrack,s_oBgSound,s_oCanvas,s_iCanvasResizeHeight,s_iCanvasResizeWidth,s_iCanvasOffsetHeight,s_iCanvasOffsetWidth;
function CLoadingScreen(a,c){var b=null,d;this._init=function(){b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.on("click",function(){});a.addChild(b);var e=c.createText(TEXT_LOADING,36).container;e.x=CANVAS_WIDTH_HALF;e.y=CANVAS_HEIGHT_HALF-30;a.addChild(e);e=s_oSpriteLibrary.getSprite("preloader_anim");d=createBitmap(e);d.x=CANVAS_WIDTH_HALF;d.y=CANVAS_HEIGHT_HALF+30;d.regX=.5*e.width;d.regY=.5*e.height;a.addChild(d);s_oStage.addChild(a);this.animLoad()};
this.animLoad=function(){var a=this;createjs.Tween.get(d).to({rotation:d.rotation+360},1E3).call(function(){a.animLoad()})};this.unload=function(){b.removeAllEventListeners();s_oStage.removeChild(a)};this._init();return this}TEXT_TEAM="Australia;England;India;Pakistan;South Africa;Sri Lanka".split(";");TEXT_GAMEOVER="YOU RAN OUT OF BALLS.";TEXT_SCORE="FINAL SCORE\n";TEXT_PAUSE="PAUSE";TEXT_PANEL="CONGRATULATIONS! YOU GOT";TEXT_PANEL_POINT=" POINTS";TEXT_BOWLED="BOWLED!";SCORE_TEXT="PTS: ";
TEXT_START="START";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";TEXT_SELECT_YOUR_TEAM="SELECT YOUR TEAM";TEXT_SELECT_OPPONENT_TEAM="SELECT CPU TEAM";TEXT_LINK="www.codethislab.com";TEXT_HIT="HIT";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_CONGRATULATION=["GOOD!","GREAT!","EXCELLENT!!!"];TEXT_LOADING="LOADING";TEXT_SELECT_MODE="SELECT MODE";TEXT_BATTER="BATTER";TEXT_BOWLER="BOWLER";TEXT_HOW_TO_PLAY="HOW TO PLAY";TEXT_HELP1_PC_BATTER="PRESS THE CORRESPONDING KEY WHEN THE BALL TARGET BECOMES GREEN";
TEXT_HELP1_MOBILE_BATTER="TOUCH THE CORRESPONDING ARROW WHEN THE BALL TARGET BECOMES GREEN";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CInterface(){var a,c,b,d,e,g,f,k,l,m,p,n,t,h,r,u,q,x,B,v,C,w=null,z,D=null,A=null,E;this._init=function(){var y=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-y.height/2-10;g=y.height/2+10;r=new CGfxButton(e,g,y);r.addEventListener(ON_MOUSE_UP,this._onExit,this);y=s_oSpriteLibrary.getSprite("but_pause");a=e-y.height-10;c=g;u=new CGfxButton(a,c,y);u.addEventListener(ON_MOUSE_UP,this.onButPauseRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)y=s_oSpriteLibrary.getSprite("audio_icon"),
b=a-y.height-10,d=g,h=new CToggle(b,d,y,s_bAudioActive),h.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);y=s_oSpriteLibrary.getSprite("score_panel");n=CANVAS_WIDTH/2-260;t=35;C=createBitmap(y);C.x=n;C.y=t;C.regX=.5*y.width;C.regY=.5*y.height;s_oStage.addChild(C);l=CANVAS_WIDTH/2-315;x=new createjs.Text(SCORE_TEXT,"30px "+FONT,"#ffffff");x.x=l;x.y=47;x.textAlign="center";x.textBaseline="alphabetic";s_oStage.addChild(x);k=CANVAS_WIDTH/2-150;B=new createjs.Text("0","30px "+FONT,"#ffffff");B.x=
k;B.y=47;B.textAlign="right";B.textBaseline="alphabetic";s_oStage.addChild(B);q=new CBall(s_oStage);m=CANVAS_WIDTH/2-370;p=80;q.setPosition(m,p);q.changeState(15);f=CANVAS_WIDTH/2-350;v=new createjs.Text("x "+LIVES,"30px "+FONT2,"#fff");v.x=f;v.y=88;v.textAlign="left";v.textBaseline="alphabetic";s_oStage.addChild(v);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h.unload(),h=null;r.unload();s_bMobile&&(A.removeAllEventListeners(),
w.unload());s_oInterface=null};this.refreshButtonPos=function(y,F){r.setPosition(e-y,F+g);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||h.setPosition(b-y,F+d);C.x=n+y;C.y=t+F;q.setPosition(m+y,F+p);u.setPosition(a-y,F+c);x.x=l+y;B.x=k+y;v.x=f+y;if(null!==w){var G=w.getStartPositionControlLeft();w.setPositionControlLeft(G.x+y,G.y-F);G=w.getStartPositionControlRight();w.setPositionControlRight(G.x-y,G.y-F)}};this.createController=function(){w=new CController};this.createHitArea=function(){A=new createjs.Shape;
A.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);A.alpha=.01;A.on("click",function(){});s_oStage.addChild(A)};this.setHitAreaVisible=function(a){null!==A&&(A.visible=a)};this.createAnimText=function(a,b,d,c,e,f){var h=new createjs.Container;h.scaleX=0;h.scaleY=0;var g=new createjs.Text(a,b+"px "+FONT2,"#000");g.x=0;g.y=0;g.textAlign="center";g.textBaseline="middle";g.outline=4;h.addChild(g);var k=new createjs.Text(a,b+"px "+FONT2,"#ffffff");k.x=0;k.y=0;k.textAlign="center";
k.textBaseline="middle";h.addChild(k);h.x=CANVAS_WIDTH_HALF;h.y=CANVAS_HEIGHT_HALF;d&&(E=0,s_oInterface.strobeText(k,c));s_oStage.addChild(h);createjs.Tween.get(h).to({scaleX:1,scaleY:1},e,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(h).wait(300).to({scaleX:0,scaleY:0},e,createjs.Ease.cubicOut).call(function(){d&&createjs.Tween.removeTweens(k);f();s_oStage.removeChild(h)})})};this.strobeText=function(a,b){createjs.Tween.get(a).wait(30).call(function(){E<b.length-1?E++:E=0;a.color=b[E];
s_oInterface.strobeText(a,b)})};this.animBallHit=function(){var a=s_oSpriteLibrary.getSprite("hit_msg"),b=createBitmap(a);b.x=CANVAS_WIDTH_HALF;b.y=CANVAS_HEIGHT_HALF;b.regX=.5*a.width;b.regY=.5*a.height;b.scaleX=0;b.scaleY=0;s_oStage.addChild(b);createjs.Tween.get(b).to({scaleX:1,scaleY:1},500,createjs.Ease.cubicOut).wait(800).call(function(){s_oGame.afterBallHit();s_oStage.removeChild(b)})};this.viewScore=function(a){B.text=a};this.refreshLivesText=function(a){v.text="x "+a};this.createHelpPanel=
function(){D=new CHelpPanel(0,0,s_oSpriteLibrary.getSprite("bg_help"))};this._onButRestartRelease=function(){s_oGame.restartGame()};this.onExitFromHelp=function(){null!==D&&D.unload()};this.unloadPause=function(){z.unload();z=null};this.onButPauseRelease=function(){z=new CPause};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){(new CAreYouSurePanel(s_oStage)).show()};s_oInterface=this;this._init();return this}
var s_oInterface=null;
function CHelpPanel(a,c,b){var d,e,g,f,k,l,m,p=!1;this._init=function(a,b,c){k=new createjs.Container;k.x=a;k.y=b;s_oStage.addChild(k);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=.5;k.addChild(f);g=createBitmap(c);g.x=CANVAS_WIDTH_HALF;g.y=CANVAS_HEIGHT_HALF;g.regX=.5*c.width;g.regY=.5*c.height;k.addChild(g);d=new createjs.Text(TEXT_HOW_TO_PLAY,"bold 50px "+FONT2,"#ffffff");d.textAlign="center";d.lineWidth=500;d.x=.5*CANVAS_WIDTH;d.y=.5*CANVAS_HEIGHT-
240;k.addChild(d);e=new createjs.Text(s_bMobile?TEXT_HELP1_MOBILE_BATTER:TEXT_HELP1_PC_BATTER,"28px "+FONT2,"#ffffff");e.textAlign="center";e.lineWidth=450;e.x=.5*CANVAS_WIDTH;e.y=.5*CANVAS_HEIGHT-170;k.addChild(e);m=new createjs.Container;c=s_oSpriteLibrary.getSprite("ball_target");a=new CBallTarget(CANVAS_WIDTH_HALF-150,CANVAS_HEIGHT_HALF-30,c,m);b=new CBallTarget(CANVAS_WIDTH_HALF,CANVAS_HEIGHT_HALF-30,c,m);c=new CBallTarget(CANVAS_WIDTH_HALF+150,CANVAS_HEIGHT_HALF-30,c,m);var r,u,q;s_bMobile?
(r=s_oSpriteLibrary.getSprite("arrow"),u=s_oSpriteLibrary.getSprite("arrow"),q=s_oSpriteLibrary.getSprite("arrow")):(r=s_oSpriteLibrary.getSprite("key_left"),u=s_oSpriteLibrary.getSprite("key_up"),q=s_oSpriteLibrary.getSprite("key_right"));r=this.createKey(CANVAS_WIDTH_HALF-150,CANVAS_HEIGHT_HALF+60,r);u=this.createKey(CANVAS_WIDTH_HALF,CANVAS_HEIGHT_HALF+60,u);q=this.createKey(CANVAS_WIDTH_HALF+150,CANVAS_HEIGHT_HALF+60,q);var p=.8;s_bMobile&&(r.scaleX=-1,p=-.8,u.rotation=270);m.addChild(r,u,q);
k.addChild(m);var B=this;this.animKeyTarget(r,a,u,b,q,c,250,250,r.scaleX,p);a=s_oSpriteLibrary.getSprite("but_continue");l=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT_HALF+180,a,k);l.addEventListener(ON_MOUSE_UP,this._onExitHelp,this);l.pulseAnimation();k.on("pressup",function(){B._onExitHelp()})};this.animKeyTarget=function(a,b,d,c,e,f,g,k,l,m){var p=this;createjs.Tween.get(a).wait(g).call(function(){p.changeAnimArrayTarget(a,b,m,.8,!0);createjs.Tween.get(a).wait(k).call(function(){p.changeAnimArrayTarget(a,
b,l,1,!1);createjs.Tween.get(d).wait(g).call(function(){p.changeAnimArrayTarget(d,c,.8,.8,!0);createjs.Tween.get(d).wait(k).call(function(){p.changeAnimArrayTarget(d,c,1,1,!1);createjs.Tween.get(e).wait(g).call(function(){p.changeAnimArrayTarget(e,f,.8,.8,!0);createjs.Tween.get(e).wait(k).call(function(){p.changeAnimArrayTarget(e,f,1,1,!1);p.animKeyTarget(a,b,d,c,e,f,g,k,l,m)})})})})})})};this.changeAnimArrayTarget=function(a,b,d,c,e){a.scaleX=d;a.scaleY=c;b.changeState(e)};this.createKey=function(a,
b,d){var c;c=createBitmap(d);c.x=a;c.y=b;c.regX=.5*d.width;c.regY=.5*d.height;return c};this.unload=function(){createjs.Tween.removeAllTweens();createjs.Tween.get(k).to({alpha:0},500,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(k)});var a=this;k.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){p||(p=!0,this.unload(),s_oGame._onExitHelpPanel())};this._init(a,c,b);return this}
function CGfxButton(a,c,b,d){var e,g,f,k,l,m,p,n=!1,t;this._init=function(a,b,d){e=[];g=[];f=createBitmap(d);f.x=a;f.y=b;m=l=1;f.regX=d.width/2;f.regY=d.height/2;s_bMobile||(f.cursor="pointer");t.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);t.removeChild(f)};this.setVisible=function(a){f.visible=a};this.setCursorType=function(a){f.cursor=a};this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",
this.buttonRelease)};this.addEventListener=function(a,b,d){e[a]=b;g[a]=d};this.addEventListenerWithParams=function(a,b,d,c){e[a]=b;g[a]=d;k=c};this.buttonRelease=function(){n||(f.scaleX=0<l?1:-1,f.scaleY=1,e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(g[ON_MOUSE_UP],k))};this.buttonDown=function(){n||(f.scaleX=0<l?.9:-.9,f.scaleY=.9,playSound("click",1,0),e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],k))};this.rotation=function(a){f.rotation=a};this.getButton=function(){return f};this.setPosition=
function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};this.block=function(a){n=a;f.scaleX=l;f.scaleY=m};this.setScaleX=function(a){l=f.scaleX=a};this.getX=function(){return f.x};this.getY=function(){return f.y};this.pulseAnimation=function(){createjs.Tween.get(f).to({scaleX:.9*l,scaleY:.9*m},850,createjs.Ease.quadOut).to({scaleX:l,scaleY:m},650,createjs.Ease.quadIn).call(function(){p.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(f).to({rotation:5},
75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){p.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(f)};t=void 0===d?s_oStage:d;this._init(a,c,b);p=this;return this}
function CGame(a,c,b){function d(a){!0===q&&(x||(37===a.keyCode?s_oGame.hitLeft():38===a.keyCode?s_oGame.hitCenter():39===a.keyCode&&s_oGame.hitRight()));a.preventDefault();return!1}var e=0,g=0,f=0,k=0,l=0,m=0,p=-1,n,t,h=!1,r=!1,u=!1,q=!0,x=!1,B,v,C=null,w,z,D,A,E;this._init=function(a,b){$(s_oMain).trigger("start_session");setVolume(s_oSoundTrack,.35);E=playSound("crowd_cheering",1,-1);var c=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(c);w=new createjs.Container;s_oStage.addChild(w);
v=new CInterface;D=new CBowler(w,b);c=s_oSpriteLibrary.getSprite("pole_1");new CPole(CANVAS_WIDTH_HALF-8,CANVAS_HEIGHT-812,c,w);c=s_oSpriteLibrary.getSprite("ball_target");A=new CBallTarget(-100,-100,c,w);A.setVisible(!1);s_oBall=new CBall(w);this.ballResetPos();n=LIVES;z=new CBatter(w,a);c=s_oSpriteLibrary.getSprite("pole_0");new CPole(CANVAS_WIDTH_HALF,CANVAS_HEIGHT-193,c,w);!1===s_bMobile?document.onkeydown=d:(v.createController(),v.refreshButtonPos(s_iOffsetX,s_iOffsetY),v.createHitArea());B=
!0;v.createHelpPanel()};this.launchCountdown=function(){var a=createBitmap(s_oSpriteLibrary.getSprite("3"));a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;a.regX=40;a.regY=84;w.addChild(a);playSound("countdown1",1,0);createjs.Tween.get(a).to({scaleX:1.3,scaleY:1.3},500,createjs.Ease.cubicOut).wait(500).call(function(){this.visible=!1;var a=createBitmap(s_oSpriteLibrary.getSprite("2"));a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;a.regX=40;a.regY=84;a.scaleX=.7;a.scaleY=.7;w.addChild(a);playSound("countdown1",1,
0);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("countdown1");createjs.Tween.get(a).to({scaleX:1.3,scaleY:1.3},500,createjs.Ease.cubicOut).wait(500).call(function(){w.removeChild(this);var a=createBitmap(s_oSpriteLibrary.getSprite("1"));a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;a.regX=40;a.regY=84;a.scaleX=.7;a.scaleY=.7;w.addChild(a);playSound("countdown1",1,0);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("countdown1");createjs.Tween.get(a).to({scaleX:1.3,scaleY:1.3},
500,createjs.Ease.cubicOut).wait(500).call(function(){w.removeChild(this);v.createAnimText(TEXT_START,48,!1,null,300,function(){w.removeChild(this);t=!0;v.setHitAreaVisible(!1)});playSound("countdown2",1,0)})})})};this._onExitHelpPanel=function(){v.onExitFromHelp();this.launchCountdown();$(s_oMain).trigger("start_level",1)};this.hitLeft=function(){p=HIT_LEFT;s_oGame._strike();s_oGame.beatDirection()};this.hitCenter=function(){p=HIT_CENTER;s_oGame._strike();s_oGame.beatDirection()};this.hitRight=function(){p=
HIT_RIGHT;s_oGame._strike();s_oGame.beatDirection()};this._strike=function(){h?(z.hideBatter(g,h),g=0):(z.hideBatter(e,h),e=0);h=!h;x=!0;v.setHitAreaVisible(!0)};this._ballMissed=function(){t=!1;u=!0;playSound("crowd_ohhh",1,0);v.createAnimText(TEXT_BOWLED,48,!1,null,300,this.afterBallMissed);A.setVisible(!1);n--;v.refreshLivesText(n)};this.afterBallMissed=function(){z.hideBatter(e,h);e=0;h&&s_oGame._strike();s_oGame.changeStateTarget(!1);t=!0;x=!1;v.setHitAreaVisible(!1)};this.getMissed=function(){return u};
this.setScore=function(a){k+=Math.floor(a);v.viewScore(k)};this.unload=function(){!1===s_bMobile&&(document.onkeydown=null);v.unload();null!==C&&C.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu();setVolume(s_oSoundTrack,1);destroySound(E);$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};this.gameOver=function(){q=t=!1;C=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));
C.show(k)};this._ballHitted=function(a){t=!1;s_oBall.hideBall();var b=!1;playSound("applauses",1,0);a=SCORE_HIT-a;var d=TEXT_CONGRATULATION[0];a>=POINT_TEXT_EXCELLENT?(d=TEXT_CONGRATULATION[2],b=!0):a>POINT_TEXT_GREAT&&(d=TEXT_CONGRATULATION[1]);v.createAnimText(d,48,b,TEXT_EXCELLENT_COLOR,300,this.afterBallHit)};this.afterBallHit=function(){s_oGame._restart();s_oBall.addVelocity();t=!0};this.changeStateTarget=function(a){A.changeState(a)};this.randomDir=function(){m=Math.floor(Math.random()*LAUNCH_DIR_OFFSET_RANGE.length)};
this.ballResetPos=function(){this.randomDir();var a={x:END_POINT_X_THROWN+(Math.random()*(LAUNCH_DIR_OFFSET_RANGE[m].max-LAUNCH_DIR_OFFSET_RANGE[m].min)+LAUNCH_DIR_OFFSET_RANGE[m].min),y:END_POINT_Y_THROWN};PERFECT_HIT_X=a.x;A.setPosition(a.x,a.y);s_oBall.reset(a)};this.pause=function(a){B=!a;createjs.Ticker.paused=a};this._restart=function(){0>=n?this.gameOver():(this.ballResetPos(),A.setVisible(!1),s_oGame.changeStateTarget(!1),s_bBounce=!0,u=r=!1,this._strike(),x=!1,v.setHitAreaVisible(!1))};this.resetGame=
function(){n=LIVES;v.refreshLivesText(n);k=0;v.viewScore(k);q=h=t=!0;x=!1;this._restart();$(s_oMain).trigger("restart_level",1)};this.ballMissedRestart=function(){0>=n?this.gameOver():(this.ballResetPos(),r=!1,0<g&&this._strike(),x=u=!1,v.setHitAreaVisible(!1))};this.beatDirection=function(){p===m&&s_oBall.hitControl()};this.update=function(){if(t&&B){h?(z.hideBatter(g,h),g+1<NUM_SPRITE_BATTING?(z.viewBatter(g+1,h),g++):z.viewBatter(g,h),8===g&&s_oBall.hitBall()):(z.hideBatter(e,h),e+1<NUM_SPRITE_BATTING?
(z.viewBatter(e+1,h),e++):(e=0,z.viewBatter(e,h)));!0===u&&this.ballMissedRestart();if(!r||f+1<NUM_SPRITE_BOWLER)D.hideBowler(f),f+1<NUM_SPRITE_BOWLER?(D.viewBowler(f+1),f++):f=0,28===f&&(l++,s_oBall.viewBall(),A.setVisible(!0),r=!0);r&&s_oBall.update()}};s_oGame=this;LIVES=a.lives;OFFSET_FOR_HIT=a.offset_hit;OFFSET_FOR_PERFECT_HIT=a.offset_perfect_hit;STEP_SPEED_BALL=a.start_speed_ball;BALL_VELOCITY_ADDED=a.ball_velocity_added;MAX_BALL_VELOCITY=a.max_ball_velocity;SCORE_HIT=a.score_ball_hit;NUM_LEVEL_FOR_ADS=
a.num_levels_for_ads;ALMOST_MINUS=PERFECT_HIT_Y-OFFSET_FOR_HIT;ALMOST_PLUS=PERFECT_HIT_Y+OFFSET_FOR_HIT;POINT_TEXT_EXCELLENT=SCORE_HIT-OFFSET_FOR_PERFECT_HIT;this._init(c,b)}var s_oGame;
function CEndPanel(a){var c,b,d,e,g,f;this._init=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("baseball_buzzer");c=createBitmap(a);c.on("click",function(){});d=new createjs.Text(""," 44px "+FONT2,"#fff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-190;d.textAlign="center";d.textBaseline="alphabetic";d.lineHeight=60;d.lineWidth=450;e=new createjs.Text(""," 40px "+FONT2,"#fff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2;e.textAlign="center";e.textBaseline="alphabetic";e.lineHeight=
60;e.lineWidth=470;b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(c,e,d);a=s_oSpriteLibrary.getSprite("but_restart");g=new CGfxButton(CANVAS_WIDTH/2+170,CANVAS_HEIGHT_HALF+160,a,b);a=s_oSpriteLibrary.getSprite("but_home");f=new CGfxButton(CANVAS_WIDTH/2-170,CANVAS_HEIGHT_HALF+160,a,b);s_oStage.addChild(b)};this.unload=function(){c.off("click",function(){});createjs.Tween.get(b).to({alpha:0},500).call(function(){f.unload();g.unload();s_oStage.removeChild(b)})};this._initListener=function(){f.addEventListener(ON_MOUSE_UP,
this._onExit,this);g.addEventListener(ON_MOUSE_UP,this._onRestart,this)};this.show=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");d.text=TEXT_GAMEOVER;e.text=TEXT_SCORE+a;b.visible=!0;var c=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){c._initListener();s_iAdsLevel===NUM_LEVEL_FOR_ADS?($(s_oMain).trigger("show_interlevel_ad"),s_iAdsLevel=1):s_iAdsLevel++});$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("share_event",a);$(s_oMain).trigger("save_score",
a)};this._onRestart=function(){this.unload();s_oGame.resetGame()};this._onExit=function(){this.unload();s_oGame.onExit()};this._init(a);return this}
function CCreditsPanel(){var a,c,b,d,e,g,f,k;this._init=function(){k=new createjs.Container;s_oStage.addChild(k);var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));k.addChild(l);e=new createjs.Shape;e.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.addChild(e);l=s_oSpriteLibrary.getSprite("msg_box");c=createBitmap(l);c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;c.regX=l.width/2;c.regY=l.height/2;k.addChild(c);g=new createjs.Shape;g.graphics.beginFill("#0f0f0f").drawRect(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=.01;g.cursor="pointer";g.on("click",this._onLogoButRelease);k.addChild(g);l=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH/2+204;b=new CGfxButton(a,264,l,k);b.addEventListener(ON_MOUSE_UP,this.unload,this);d=new createjs.Text(TEXT_CREDITS_DEVELOPED,"48px "+FONT2,"#ffffff");d.x=CANVAS_WIDTH/2;d.y=350;d.textAlign="center";k.addChild(d);var l=s_oSpriteLibrary.getSprite("logo_credits"),m=createBitmap(l);m.regX=l.width/2;m.regY=l.height/2;m.x=CANVAS_WIDTH/2;
m.y=470;k.addChild(m);f=new createjs.Text(TEXT_LINK,"42px "+FONT2,"#ffffff");f.x=CANVAS_WIDTH/2;f.y=530;f.textAlign="center";k.addChild(f)};this.unload=function(){g.off("click",this._onLogoButRelease);b.unload();b=null;s_oStage.removeChild(k)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()}
function CController(){var a,c,b,d,e,g;this._init=function(){a={x:.5*CANVAS_WIDTH+320,y:CANVAS_HEIGHT-120};c={x:.5*CANVAS_WIDTH-320,y:CANVAS_HEIGHT-120};b={x:.5*CANVAS_WIDTH,y:CANVAS_HEIGHT-120};var f=s_oSpriteLibrary.getSprite("arrow");d=new CGfxButton(c.x,c.y,f,s_oStage);d.addEventListener(ON_MOUSE_DOWN,s_oGame.hitLeft,this);d.setScaleX(-1);e=new CGfxButton(a.x,a.y,f,s_oStage);e.addEventListener(ON_MOUSE_DOWN,s_oGame.hitRight,this);g=new CGfxButton(b.x,b.y,f,s_oStage);g.addEventListener(ON_MOUSE_DOWN,
s_oGame.hitCenter,this);g.rotation(-90)};this.getStartPositionControlRight=function(){return a};this.getStartPositionControlLeft=function(){return c};this.getStartPositionControlUp=function(){return b};this.setPositionControlRight=function(a,b){e.setPosition(a,b)};this.setPositionControlLeft=function(a,b){d.setPosition(a,b)};this.setPositionControlUp=function(a,b){g.setPosition(a,b)};this.unload=function(){d.unload();d=null;e.unload();e=null;g.unload();g=null};this._init();return this}
function CBowler(a,c){var b=[];this._init=function(a,c){for(var g=0;g<NUM_SPRITE_BOWLER;g++)b.push(createBitmap(s_oSpriteLibrary.getSprite("bowler_"+c+"_"+g))),b[g].x=BOWLER_X,b[g].y=BOWLER_Y,b[g].rotation=0,b[g].visible=!1,a.addChild(b[g]);b[0].visible=!0};this.viewBowler=function(a){b[a].visible=!0};this.hideBowler=function(a){b[a].visible=!1};s_oPticher=this;this._init(a,c)}s_oPticher=null;