function CVector2(a,d){var b,c;this._init=function(a,d){b=a;c=d};this.add=function(a,d){b+=a;c+=d};this.addV=function(a){b+=a.getX();c+=a.getY()};this.scalarDivision=function(a){b/=a;c/=a};this.subV=function(a){b-=a.getX();c-=a.getY()};this.scalarProduct=function(a){b*=a;c*=a};this.invert=function(){b*=-1;c*=-1};this.dotProduct=function(a){return b*a.getX()+c*a.getY()};this.set=function(a,d){b=a;c=d};this.setV=function(a){b=a.getX();c=a.getY()};this.length=function(){return Math.sqrt(b*b+c*c)};this.length2=
function(){return b*b+c*c};this.normalize=function(){var a=this.length();0<a&&(b/=a,c/=a)};this.getNormalize=function(a){this.length();a.set(b,c);a.normalize()};this.rot90CCW=function(){var a=b;b=-c;c=a};this.rot90CW=function(){var a=b;b=c;c=-a};this.getRotCCW=function(a){a.set(b,c);a.rot90CCW()};this.getRotCW=function(a){a.set(b,c);a.rot90CW()};this.ceil=function(){b=Math.ceil(b);c=Math.ceil(c)};this.round=function(){b=Math.round(b);c=Math.round(c)};this.toString=function(){return"Vector2: "+b+", "+
c};this.print=function(){trace("Vector2: "+b+", "+c+"")};this.getX=function(){return b};this.getY=function(){return c};this._init(a,d)}
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);function trace(a){console.log(a)}function centerBetweenPointsV2(a,d){var b=new CVector2;b.set((a.x+d.x)/2,(a.y+d.y)/2);return b}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function playSound(a,d,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:d}):null}
function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}function setSoundAsPlayed(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.play()}function setVolume(a,d){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=d}function setMute(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(d)}$(window).resize(function(){sizeHandler()});
function getSize(a){var d=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var g=b.createElement("body");g.id="vpw-test-b";g.style.cssText="overflow:scroll";var f=b.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+d+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";g.appendChild(f);c.insertBefore(g,b.head);
a=7==f["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(g)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH),c=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,g=0;b<a?(g=a-b,b+=g,c+=CANVAS_WIDTH/CANVAS_HEIGHT*g):c<d&&(g=d-c,c+=g,b+=CANVAS_HEIGHT/CANVAS_WIDTH*g);var g=a/2-b/2,f=d/2-c/2,h=CANVAS_WIDTH/c;if(f*h<-EDGEBOARD_X||g*h<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),d/(CANVAS_WIDTH-2*
EDGEBOARD_X)),c=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,g=(a-b)/2,f=(d-c)/2,h=CANVAS_WIDTH/c;s_iOffsetX=-1*f*h;s_iOffsetY=-1*g*h;0<=g&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile&&!s_bIsIphone?($("#canvas").css("width",c+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=c,s_oStage.canvas.height=b,s_oStage.scaleX=s_oStage.scaleY=Math.min(c/CANVAS_WIDTH,b/
CANVAS_HEIGHT));0>g?$("#canvas").css("top",g+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",f+"px")}}function createBitmap(a,d,b){var c=new createjs.Bitmap(a),g=new createjs.Shape;d&&b?g.graphics.beginFill("#fff").drawRect(0,0,d,b):g.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=g;return c}
function createSprite(a,d,b,c,g,f){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-b,-c,g,f);a.hitArea=d;return a}function randomFloatBetween(a,d,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(b))}function rotateVector2D(a,d){var b=d.getX()*Math.cos(a)+d.getY()*Math.sin(a),c=d.getX()*-Math.sin(a)+d.getY()*Math.cos(a);d.set(b,c)}function tweenVectorsOnX(a,d,b){return a+b*(d-a)}
function shuffle(a){for(var d=a.length,b,c;0!==d;)c=Math.floor(Math.random()*d),--d,b=a[d],a[d]=a[c],a[c]=b;return a}function bubbleSort(a){var d;do{d=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(d=a[b],a[b]=a[b+1],a[b+1]=d,d=!0)}while(d)}function compare(a,d){return a.index>d.index?-1:a.index<d.index?1:0}function easeLinear(a,d,b,c){return b*a/c+d}function easeInQuad(a,d,b,c){return b*(a/=c)*a+d}function easeInSine(a,d,b,c){return-b*Math.cos(a/c*(Math.PI/2))+b+d}
function easeInCubic(a,d,b,c){return b*(a/=c)*a*a+d}function getTrajectoryPoint(a,d){var b=new createjs.Point,c=(1-a)*(1-a),g=a*a;b.x=c*d.start.x+2*(1-a)*a*d.traj.x+g*d.end.x;b.y=c*d.start.y+2*(1-a)*a*d.traj.y+g*d.end.y;return b}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=Math.floor(a-60*d);var b="",b=10>d?b+("0"+d+":"):b+(d+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,d){var b,c;b=getBounds(a,.9);c=getBounds(d,.98);return calculateIntersection(b,c)}function calculateIntersection(a,d){var b,c,g,f,h,k,e,l;b=a.x+(g=a.width/2);c=a.y+(f=a.height/2);h=d.x+(k=d.width/2);e=d.y+(l=d.height/2);b=Math.abs(b-h)-(g+k);c=Math.abs(c-e)-(f+l);return 0>b&&0>c?(b=Math.min(Math.min(a.width,d.width),-b),c=Math.min(Math.min(a.height,d.height),-c),{x:Math.max(a.x,d.x),y:Math.max(a.y,d.y),width:b,height:c,rect1:a,rect2:d}):null}
function getBounds(a,d){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,g=c.length,f,h;for(h=0;h<g;h++)f=getBounds(c[h],1),f.x<b.x&&(b.x=f.x),f.y<b.y&&(b.y=f.y),f.x+f.width>b.x2&&(b.x2=f.x+f.width),f.y+f.height>b.y2&&(b.y2=f.y+f.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var k,e;a instanceof createjs.Bitmap?
(g=a.sourceRect||a.image,h=g.width*d,k=g.height*d):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(g=a.spriteSheet.getFrame(a.currentFrame),h=g.rect.width,k=g.rect.height,c=g.regX,e=g.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);c=c||0;h=h||0;e=e||0;k=k||0;b.regX=c;b.regY=e;g=a.localToGlobal(0-c,0-e);f=a.localToGlobal(h-c,k-e);h=a.localToGlobal(h-c,0-e);c=a.localToGlobal(0-c,k-e);b.x=Math.min(Math.min(Math.min(g.x,
f.x),h.x),c.x);b.y=Math.min(Math.min(Math.min(g.y,f.y),h.y),c.y);b.width=Math.max(Math.max(Math.max(g.x,f.x),h.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(g.y,f.y),h.y),c.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,b,c;0<d;)c=Math.floor(Math.random()*d),d--,b=a[d],a[d]=a[c],a[c]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),b=0;b<d.length;b++){var c=d[b].split("=");if(c[0]==a)return c[1]}}
function CSpriteLibrary(){var a,d,b,c,g,f;this.init=function(h,k,e){b=d=0;c=h;g=k;f=e;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){g.call(f)};this._onSpriteLoaded=function(){c.call(f);++b==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=640,CANVAS_HALF_WIDTH=CANVAS_WIDTH/2,CANVAS_HEIGHT=960,FONT="rocks__gregular",EDGEBOARD_X=20,EDGEBOARD_Y=95,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,PLAYER_X_START=CANVAS_WIDTH/2-25,PLAYER_Y_START=356,PLAYER_WIDTH=127,PLAYER_HEIGHT=124,PLAYER_CHAINED_WIDTH=215,PLAYER_CHAINED_HEIGHT=152,PLAYER_HAMMER_WIDTH=156,PLAYER_HAMMER_HEIGHT=219,PLAYER_GHOST_WIDTH=130,PLAYER_GHOST_HEIGHT=192,MAX_PLATFORM_FOR_TYPE=26,PLATFORM_WIDTH=350,PLATFORM_HEIGHT=200,PLATFORM_START_WIDTH=380,PLATFORM_START_HEIGHT=
49,SLOW_WIDTH=120,SLOW_HEIGHT=126,DESTROY_WIDTH=105,DESTROY_HEIGHT=132,TORCH_WIDTH=342,TORCH_HEIGHT=320,ROTATORY_SAW_WIDTH=120,ROTATORY_SAW_HEIGHT=66,CEILING_WIDTH=640,CEILING_HEIGHT=173,ROTATORY_SAW_DESTROYED_WIDTH=200,ROTATORY_SAW_DESTROYED_HEIGHT=150,NUM_ELEMENTS=2,PLATFORM=1,THORNS=2,OBSTACLE=3,ROTARY_SAW=0,PLAYER_SPD_MAX,PLAYER_SPD_FALLING,PLAYER_MAX_SPD_FALLING,PLAYER_ACCELERATION,PLAYER_DECELERATION,OBJECT_SPD,OBJECT_SPD_ADDER,SCORE_TO_REACH_FOR_INCREMENT_SPEED,OBJECT_SPD_ORIZZONTAL,ACCELERATION,
DECELERATION,GAMMA_RANGE_ACCEPTED,CANVAS_WIDTH_RANGE_ACCEPTED,DECELERATION_BG_GAME_OVER,HEIGHT_BETWEEN_OBJECT,TIME_TO_SPAWN_THORNS,TIME_TO_HIDE_THORNS,BONUS_OCCUR,TIME_SLOW_DOWN_POWERUP,SCORE_BREAKED_PLATFORM,SCORE_TO_CHANGE_OCCURRENCE,SPAWN_DELAY_PLATFORM_OBSTACLES,SLOW=0,DESTROY=1,BG_INDEX=1,GOING_RIGHT=0,GOING_LEFT=1,LEFT_DIR=37,UP_DIR=38,RIGHT_DIR=39,DOWN_DIR=40,SPACEBAR=32,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=
4,ON_DRAG_END=5;TEXT_GAMEOVER="GAME OVER";TEXT_SCORE="YOUR SCORE IS: ";TEXT_CREDITS_DEVELOPED="Developed by";TEXT_LINK1="www.codethislab.com";TEXT_DESKTOP="RUN ALONG THE PLATFORMS TO ESCAPE FROM THE DOUNGEON! USE LEFT AND RIGHT KEYS TO MOVE YOUR HERO.";TEXT_MOBILE="RUN ALONG THE PLATFORMS TO ESCAPE FROM THE DOUNGEON! USE LEFT AND RIGHT BUTTONS TO MOVE YOUR HERO.";TEXT_SLOW_DOWN="SLOW DOWN PLATFORM!";TEXT_HAMMER="DESTROY PLATFORM WITH YOUR HAMMER!";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";
TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var a,d,b,c,g,f,h;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();h=new createjs.Container;s_oStage.addChild(h)};this.unload=function(){h.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(f).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));h.addChild(k);k=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(k);c.x=CANVAS_WIDTH/2-k.width/2;c.y=CANVAS_HEIGHT-150;h.addChild(c);a=k.width;d=k.height;g=new createjs.Shape;g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,d);h.addChild(g);c.mask=
g;b=new createjs.Text("","30px "+FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-150;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";h.addChild(b);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;h.addChild(f)};this.refreshLoader=function(f){b.text=f+"%";g.graphics.clear();f=Math.floor(f*a/100);g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,f,d)};this._init()}
function CMain(a){var d,b=0,c=0,g=STATE_LOADING,f,h,k;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();d=!0};this.soundLoaded=function(){b++;h.refreshLoader(Math.floor(b/c*100));b===c&&(h.unload(),s_oSoundtrack=playSound("soundtrack",1,-1),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=
["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/ceiling.ogg","ceiling"),createjs.Sound.registerSound("./sounds/death.ogg","death"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/platform_broken.ogg","platform_broken"),createjs.Sound.registerSound("./sounds/power_up_slow.ogg","power_up_slow"),createjs.Sound.registerSound("./sounds/press_but.ogg","press_button"),
createjs.Sound.registerSound("./sounds/soundtrack.ogg","power_up"),createjs.Sound.registerSound("./sounds/soundtrack_loop.ogg","soundtrack_loop"),createjs.Sound.registerSound("./sounds/spikes.ogg","spikes"),createjs.Sound.registerSound("./sounds/wothan_broken_chains.ogg","wothan_broken_chains"),createjs.Sound.registerSound("./sounds/wothan_hammer.ogg","wothan_hammer"),createjs.Sound.registerSound("./sounds/wothan_landing.ogg","wothan_landing")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/ceiling.mp3","ceiling"),createjs.Sound.registerSound("./sounds/death.mp3","death"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/platform_broken.mp3","platform_broken"),createjs.Sound.registerSound("./sounds/power_up_slow.mp3","power_up_slow"),createjs.Sound.registerSound("./sounds/press_but.mp3","press_button"),createjs.Sound.registerSound("./sounds/soundtrack.mp3",
"soundtrack"),createjs.Sound.registerSound("./sounds/soundtrack_loop.mp3","soundtrack_loop"),createjs.Sound.registerSound("./sounds/spikes.mp3","spikes"),createjs.Sound.registerSound("./sounds/wothan_broken_chains.mp3","wothan_broken_chains"),createjs.Sound.registerSound("./sounds/wothan_hammer.mp3","wothan_hammer"),createjs.Sound.registerSound("./sounds/wothan_landing.mp3","wothan_landing")),c+=12)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);
s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_scroll_1","./sprites/bg_scroll_1.jpg");s_oSpriteLibrary.addSprite("bg_scroll_2","./sprites/bg_scroll_2.jpg");s_oSpriteLibrary.addSprite("bg_scroll_3",
"./sprites/bg_scroll_3.jpg");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("but_next","./sprites/but_next.png");s_oSpriteLibrary.addSprite("but_skip","./sprites/but_skip.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("credits_panel","./sprites/credits_panel.png");s_oSpriteLibrary.addSprite("logo_credits","./sprites/logo_credits.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon",
"./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("player_left","./sprites/wothan_idle_walk_falling_left_sprite.png");s_oSpriteLibrary.addSprite("player_right","./sprites/wothan_idle_walk_falling_right_sprite.png");s_oSpriteLibrary.addSprite("player_hammer_left","./sprites/wothan_hammer_left_sprite.png");s_oSpriteLibrary.addSprite("player_hammer_right","./sprites/wothan_hammer_right_sprite.png");s_oSpriteLibrary.addSprite("player_start","./sprites/wothan_broken_chain_sprite.png");s_oSpriteLibrary.addSprite("player_dead",
"./sprites/wothan_dead_sprite.png");s_oSpriteLibrary.addSprite("ghost","./sprites/ghost_sprite.png");s_oSpriteLibrary.addSprite("floor_start","./sprites/floor.png");s_oSpriteLibrary.addSprite("torch","./sprites/torch_sprite.png");s_oSpriteLibrary.addSprite("ceiling","./sprites/ceiling_sprite.png");s_oSpriteLibrary.addSprite("platforms","./sprites/platforms_sprite.png");s_oSpriteLibrary.addSprite("slow_bonus","./sprites/power_up_slow_sprite.png");s_oSpriteLibrary.addSprite("destroy_bonus","./sprites/power_up_hammer_sprite.png");
s_oSpriteLibrary.addSprite("rotary_saw","./sprites/wheel_rotation_sprite.png");s_oSpriteLibrary.addSprite("rotary_saw_destroyed","./sprites/wheel_explosion_sprite.png");s_oSpriteLibrary.addSprite("arrow_keys","./sprites/arrow_keys.png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;h.refreshLoader(Math.floor(b/c*100));if(b===c){h.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});
this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;g=STATE_MENU};this.gotoGame=function(a){k=new CGame(f,a);g=STATE_GAME};this.gotoHelp=function(){new CHelp;g=STATE_HELP};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};
this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);g===STATE_GAME&&k.update();s_oStage.update(a)}};s_oMain=this;f=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack,s_oSoundtrackGame,s_oCanvas;
function CTextButton(a,d,b,c,g,f,h){var k,e,l,p,m;this._init=function(a,b,c,d,f,g,h){k=[];e=[];var z=createBitmap(c),y=Math.ceil(h/20);m=new createjs.Text(d,"bold "+h+"px "+f,"#000000");m.textAlign="center";m.textBaseline="alphabetic";var x=m.getBounds();m.x=c.width/2+y;m.y=Math.floor(c.height/2)+x.height/3+y;p=new createjs.Text(d,"bold "+h+"px "+f,g);p.textAlign="center";p.textBaseline="alphabetic";x=p.getBounds();p.x=c.width/2;p.y=Math.floor(c.height/2)+x.height/3;l=new createjs.Container;l.x=a;
l.y=b;l.regX=c.width/2;l.regY=c.height/2;l.addChild(z,m,p);s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){k[a]=b;e[a]=c};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(e[ON_MOUSE_UP])};this.buttonDown=
function(){l.scaleX=.9;l.scaleY=.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN])};this.setTextPosition=function(a){p.y=a;m.y=a+2};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(a,d,b,c,g,f,h);return this}
function CToggle(a,d,b,c){var g,f,h,k=[],e;this._init=function(a,b,c,d){f=[];h=[];var k=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});g=d;e=createSprite(k,"state_"+g,c.width/2/2,c.height/2,c.width/2,c.height);e.x=a;e.y=b;e.stop();e.cursor="pointer";s_oStage.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",this.buttonDown);e.off("pressup",this.buttonRelease);s_oStage.removeChild(e)};
this._initListener=function(){e.on("mousedown",this.buttonDown);e.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;h[a]=c};this.addEventListenerWithParams=function(a,b,c,e){f[a]=b;h[a]=c;k=e};this.setActive=function(a){g=a;e.gotoAndStop("state_"+g)};this.buttonRelease=function(){e.scaleX=1;e.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");g=!g;e.gotoAndStop("state_"+g);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(h[ON_MOUSE_UP],k)};this.buttonDown=
function(){e.scaleX=.9;e.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN],k)};this.setPosition=function(a,b){e.x=a;e.y=b};this.setVisible=function(a){e.visible=a};this._init(a,d,b,c)}
function CGfxButton(a,d,b){var c,g,f,h=[],k;this._init=function(a,b,d){c=1;g=[];f=[];k=createBitmap(d);k.x=a;k.y=b;k.regX=d.width/2;k.regY=d.height/2;k.cursor="pointer";s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);s_oStage.removeChild(k)};this.setVisible=function(a){k.visible=a};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,
b,c){g[a]=b;f[a]=c};this.addEventListenerWithParams=function(a,b,c,d){g[a]=b;f[a]=c;h=d};this.buttonRelease=function(){k.scaleX=c;k.scaleY=c;g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(f[ON_MOUSE_UP],h)};this.buttonDown=function(){k.scaleX=.9*c;k.scaleY=.9*c;playSound("press_button",1,0);g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],h)};this.setScale=function(a){c=a;k.scaleX=a;k.scaleY=a};this.setPosition=function(a,b){k.x=a;k.y=b};this.setX=function(a){k.x=a};this.setY=function(a){k.y=a};this.getButtonImage=
function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this._init(a,d,b);return this}
function CMenu(){var a,d,b,c,g,f,h,k,e;this._init=function(){s_oSoundtrack?setSoundAsPlayed(s_oSoundtrack):s_oSoundtrack=playSound("soundtrack",1,-1);g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(g);var l=s_oSpriteLibrary.getSprite("but_play");f=new CGfxButton(CANVAS_WIDTH/2+20,CANVAS_HEIGHT-180,l);f.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);l=s_oSpriteLibrary.getSprite("but_info");a=CANVAS_WIDTH-l.height/2-10;d=l.height/2+10;h=new CGfxButton(a,d,l);h.addEventListener(ON_MOUSE_UP,
this._onCredits,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-l.height/2-100,c=l.height/2+10,e=new CToggle(b,c,l,s_bAudioActive),e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(k);createjs.Tween.get(k).to({alpha:0},1E3).call(function(){k.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){f.unload();
f=null;k.visible=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),e=null;s_oStage.removeChild(g);s_oMenu=g=null};this.refreshButtonPos=function(f,g){e.setPosition(b-f,g+c);h.setPosition(a-f,g+d)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoHelp()};this._onCredits=function(){new CCreditsPanel};s_oMenu=this;this._init()}var s_oMenu=null;
function CHelp(){var a=this,d,b,c,g=!0,f,h,k,e,l,p,m,r,u,q,w;this._init=function(){d=createBitmap(s_oSpriteLibrary.getSprite("bg_scroll_1"));s_oStage.addChild(d);b=new createjs.Container;b.alpha=0;c=new createjs.Container;c.alpha=0;d=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));s_oStage.addChild(d);f=new createjs.Text(""," 25px "+FONT,"#410701");f.x=CANVAS_WIDTH/2+1;f.y=CANVAS_HEIGHT/2+71;f.textAlign="center";f.textBaseline="alphabetic";f.lineWidth=400;b.addChild(f);h=new createjs.Text("",
" 25px "+FONT,"#ffb400");h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2+70;h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=400;b.addChild(h);if(s_bMobile){f.text=TEXT_MOBILE;h.text=TEXT_MOBILE;f.y-=15;h.y-=15;var a=s_oSpriteLibrary.getSprite("arrow");m=createBitmap(a);m.x=CANVAS_WIDTH/2-50;m.y=CANVAS_HEIGHT/2-100;m.scaleX=-1;b.addChild(m);r=createBitmap(a);r.x=CANVAS_WIDTH/2+50;r.y=CANVAS_HEIGHT/2-100;b.addChild(r)}else f.text=TEXT_DESKTOP,h.text=TEXT_DESKTOP,m=createBitmap(s_oSpriteLibrary.getSprite("arrow_keys")),
m.x=CANVAS_WIDTH/2-100,m.y=CANVAS_HEIGHT/2-100,b.addChild(m);a=s_oSpriteLibrary.getSprite("slow_bonus");a={images:[a],frames:{width:SLOW_WIDTH,height:SLOW_HEIGHT,regX:SLOW_WIDTH/2,regY:SLOW_HEIGHT/2},animations:{idle:[0,29,"idle"]}};a=new createjs.SpriteSheet(a);a=createSprite(a,"idle",0,0,SLOW_WIDTH/2,SLOW_HEIGHT/2);a.x=CANVAS_WIDTH/2-120;a.y=420;c.addChild(a);a=s_oSpriteLibrary.getSprite("destroy_bonus");a={images:[a],frames:{width:DESTROY_WIDTH,height:DESTROY_HEIGHT,regX:DESTROY_WIDTH/2,regY:DESTROY_HEIGHT/
2},animations:{idle:[0,17,"idle"]}};a=new createjs.SpriteSheet(a);a=createSprite(a,"idle",0,0,DESTROY_WIDTH/2,DESTROY_HEIGHT/2);a.x=CANVAS_WIDTH/2-120;a.y=580;c.addChild(a);k=new createjs.Text(TEXT_SLOW_DOWN," 25px "+FONT,"#410701");k.x=CANVAS_WIDTH/2+51;k.y=CANVAS_HEIGHT/2-59;k.textAlign="center";k.textBaseline="alphabetic";k.lineWidth=300;c.addChild(k);e=new createjs.Text(TEXT_SLOW_DOWN," 25px "+FONT,"#ffb400");e.x=CANVAS_WIDTH/2+50;e.y=CANVAS_HEIGHT/2-60;e.textAlign="center";e.textBaseline="alphabetic";
e.lineWidth=300;c.addChild(e);l=new createjs.Text(TEXT_HAMMER," 25px "+FONT,"#410701");l.x=CANVAS_WIDTH/2+51;l.y=CANVAS_HEIGHT/2+101;l.textAlign="center";l.textBaseline="alphabetic";l.lineWidth=300;c.addChild(l);p=new createjs.Text(TEXT_HAMMER," 25px "+FONT,"#ffb400");p.x=CANVAS_WIDTH/2+50;p.y=CANVAS_HEIGHT/2+100;p.textAlign="center";p.textBaseline="alphabetic";p.lineWidth=300;c.addChild(p);s_oStage.addChild(b);s_oStage.addChild(c);u=createBitmap(s_oSpriteLibrary.getSprite("but_skip"));u.x=CANVAS_WIDTH/
2-220;u.y=CANVAS_HEIGHT/2-10;u.regX=30;u.regY=43;u.scaleX=-.8;u.cursor="pointer";s_oStage.addChild(u);q=createBitmap(s_oSpriteLibrary.getSprite("but_skip"));q.x=CANVAS_WIDTH/2+220;q.y=CANVAS_HEIGHT/2-10;q.regX=30;q.regY=43;q.scaleX=.8;q.cursor="pointer";s_oStage.addChild(q);w=createBitmap(s_oSpriteLibrary.getSprite("but_next"));w.x=CANVAS_WIDTH/2-45;w.y=CANVAS_HEIGHT/2+160;w.cursor="pointer";s_oStage.addChild(w);u.alpha=0;q.alpha=1;this.show()};this._initListener=function(){u.addEventListener("click",
this._previousPage);q.addEventListener("click",this._nextPage);w.addEventListener("click",this._onExit)};this._previousPage=function(){g||(playSound("press_button",1,0),createjs.Tween.get(b).to({alpha:1},1E3).call(function(){}),createjs.Tween.get(c).to({alpha:0},500).call(function(){}),createjs.Tween.get(q).to({alpha:1},1E3).call(function(){}),createjs.Tween.get(u).to({alpha:0},500).call(function(){}),g=!0)};this._nextPage=function(){g&&(playSound("press_button",1,0),createjs.Tween.get(b).to({alpha:0},
500).call(function(){}),createjs.Tween.get(c).to({alpha:1},1E3).call(function(){}),createjs.Tween.get(q).to({alpha:0},500).call(function(){}),createjs.Tween.get(u).to({alpha:1},1E3).call(function(){}),g=!1)};this.show=function(){createjs.Tween.get(b).to({alpha:1},500).call(function(){a._initListener()})};this._onExit=function(){stopSound(s_oSoundtrack);playSound("press_button",1,0);a.unload();s_oMain.gotoGame()};this.unload=function(){u.removeAllEventListeners("click");q.removeAllEventListeners("click");
createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this._init();return this}
function CGame(a){var d=0,b=0,c,g=0,f,h=0,k=0,e,l=0,p=0,m=0,r=0,u=0,q,w,A,n,v=null,z=[[0],[0,0,0,0,1,1,2]],y=[],x=[],B=[],t=[],C=!0,D=!1,F=!1,I=!1,J=!0,G=!1,E=!1,K=!1,L,H=null,M,N;this._init=function(){s_oSoundtrackGame?setSoundAsPlayed(s_oSoundtrackGame):s_oSoundtrackGame=playSound("soundtrack_loop",1,-1);N=playSound("ceiling",.3,-1);f=CANVAS_HEIGHT/2;e=OBJECT_SPD;l=Math.round(e/7);c=HEIGHT_BETWEEN_OBJECT;$(s_oMain).trigger("start_level",1);k=Math.floor((CANVAS_HEIGHT+c)/c);w=new createjs.Container;
s_oStage.addChild(w);M=new CScrollingBg(w);n=new createjs.Container;w.addChild(n);t.push(new CPlatform(0,440,3,n));for(var a=0;a<MAX_PLATFORM_FOR_TYPE;a++)y.push(new CPlatform(-150,CANVAS_HEIGHT+150,0,n)),x.push(new CPlatform(-150,CANVAS_HEIGHT+150,1,n)),B.push(new CPlatform(-150,CANVAS_HEIGHT+150,2,n));this._controlIfAllReady();A=new createjs.Container;w.addChild(A);q=new CPlayer(A);L=new CInterface;this.setUpdateTrue();this._initMovementControl()};this._controlIfAllReady=function(){y.length===MAX_PLATFORM_FOR_TYPE&&
(h+=y.length);x.length===MAX_PLATFORM_FOR_TYPE&&(h+=x.length);B.length===MAX_PLATFORM_FOR_TYPE&&(h+=B.length);if(h>=MAX_PLATFORM_FOR_TYPE*(NUM_ELEMENTS-1))for(var a=0;a<k;a++)this._createRow();h=0};this._createRow=function(){var a;a=0;f+=c;d>=SCORE_TO_CHANGE_OCCURRENCE&&(a=1);var b=Math.random()*(CANVAS_WIDTH-PLATFORM_WIDTH),e=f;a=z[a][Math.floor(Math.random()*z[a].length)];(1===a||2===a)&&g<SPAWN_DELAY_PLATFORM_OBSTACLES?(g++,a=0):(1===a||2===a)&&g>=SPAWN_DELAY_PLATFORM_OBSTACLES&&(g=0);t.push(this.getFirstAvailableObstacle(a));
a=t.length-1;null!==t[a]?t[a].changeStatusOn(b,e):t.pop();b=Math.round(100*Math.random());b<=BONUS_OCCUR&&!v&&200<d&&!E&&(b={x:t[a].getX(),y:t[a].getY()},a={x:t[a-1].getX(),y:t[a-1].getY()},a=centerBetweenPointsV2(b,a),b=Math.round(Math.random()),v=0===b?new CBonus(a.getX(),a.getY(),SLOW,n):new CBonus(a.getX(),a.getY(),DESTROY,n))};this.getFirstAvailableObstacle=function(a){switch(a){case 0:return 0<y.length?(a=y.length-1,a=y[a],y.pop(),a):null;case 1:return 0<x.length?(a=x.length-1,a=x[a],x.pop(),
a):null;case 2:return 0<B.length?(a=B.length-1,a=B[a],B.pop(),a):null}};this._initMovementControl=function(){document.onkeydown=this.onKeyDown;document.onkeyup=this.onKeyUp;p=PLAYER_ACCELERATION};this.onKeyDown=function(a){a||(a=window.event);if(a.keyCode===LEFT_DIR)return q.moveLeft(!0),a.preventDefault(),!1;if(a.keyCode===RIGHT_DIR)return q.moveRight(!0),a.preventDefault(),!1;if(a.keyCode===SPACEBAR||a.keyCode===UP_DIR||a.keyCode===DOWN_DIR)return a.preventDefault(),!1};this.onKeyUp=function(a){a||
(a=window.event);if(a.keyCode===LEFT_DIR)return q.moveLeft(!1),a.preventDefault(),!1;if(a.keyCode===RIGHT_DIR)return q.moveRight(!1),a.preventDefault(),!1;if(a.keyCode===SPACEBAR||a.keyCode===UP_DIR||a.keyCode===DOWN_DIR)return a.preventDefault(),!1};this.onButtonDown=function(a){a===LEFT_DIR?q.moveLeft(!0):a===RIGHT_DIR&&q.moveRight(!0)};this.onButtonUp=function(a){a===LEFT_DIR?q.moveLeft(!1):a===RIGHT_DIR&&q.moveRight(!1)};this.setUpdateTrue=function(){D||F||(q.startGame(),D=!0)};this.letGameStart=
function(){I=!0};this.spawnThorns=function(){for(var a=!1,b=0;b<t.length;b++)1===t[b].getType()&&(t[b].spawnThorns(),a=!0);a&&playSound("spikes",1,0)};this.playAlmostThornsOnAnimation=function(){for(var a=0;a<t.length;a++)1===t[a].getType()&&t[a].playAlmostThornsOnAnimation()};this.hideThorns=function(){for(var a=0;a<t.length;a++)1===t[a].getType()&&t[a].hideThorns()};this.moveObject=function(){var a=0,a=null;M.move(e);for(var b=0;b<t.length;b++)if(t[b].move(e),a=t[b].controlCollision(q.getRectangle()),
a===PLATFORM?E?(t[b].startAnimationDestroyed(),d+=SCORE_BREAKED_PLATFORM,this.applyTrembling()):(J=!1,m=b):a===THORNS?E?(t[b].startAnimationDestroyed(),d+=SCORE_BREAKED_PLATFORM+5,this.applyTrembling()):(this.gameOver(),F=!0,D=!1):a===OBSTACLE&&(E?(t[b].startAnimationDestroyed(),d+=SCORE_BREAKED_PLATFORM+10,this.applyTrembling()):(this.gameOver(),F=!0,D=!1)),a=t[m].controlCollision(q.getRectangle()),0>a&&(J=!0,m=0),a=this._controlIfPlatformOverCanvas(b),null!==a){switch(a.getType()){case 0:y.push(a);
break;case 1:x.push(a);break;case 2:B.push(a)}b--}v&&(v.move(e),v.controlCollision(q.getRectangle())?(v.getType()===SLOW?this._slowDownPowerUpOn():this._destroyPowerUpOn(),v.unload(),v=null):v.checkIfOverCanvas()&&(v.unload(),v=null))};this.applyTrembling=function(){playSound("platform_broken",1,0);K||(K=!0,createjs.Tween.get(s_oStage).to({x:Math.round(10*Math.random()),y:Math.round(30*Math.random())},50).call(function(){createjs.Tween.get(s_oStage).to({x:Math.round(8*Math.random()),y:-Math.round(24*
Math.random())},50).call(function(){createjs.Tween.get(s_oStage).to({y:0,x:0},50).call(function(){K=!1})})}))};this._slowDownPowerUpOn=function(){playSound("power_up_slow",1,0);G=!0;e/=2};this._slowDownPowerUpOff=function(){G=!1;e*=2};this._destroyPowerUpOn=function(){playSound("wothan_hammer",1,0);E=G=!0;e*=2;q.playerWithHammerOn()};this._destroyPowerUpOff=function(){E=G=!1;e/=2;q.playerWithHammerOff()};this._controlIfPlatformOverCanvas=function(a){var c;return-100>=t[a].getY()&&a<t.length-1?(t[a].changeStatusOff(),
c=t[a],t.splice(a,1),3!==t[a].getType&&(b--,this._createRow()),c):null};this.handlePlayerMovement=function(){q.movePlayer(p);E||(J?q.playerFalling():q.followPlatform(e))};this.handlePowerUp=function(){G&&(u+=s_iTimeElaps,u>=TIME_SLOW_DOWN_POWERUP&&(E?this._destroyPowerUpOff():this._slowDownPowerUpOff(),u=0))};this.handleThorns=function(){C?(r+=s_iTimeElaps,r>=TIME_TO_SPAWN_THORNS?(this.spawnThorns(),C=!C,r=0):r>=TIME_TO_SPAWN_THORNS/2&&r<TIME_TO_SPAWN_THORNS&&this.playAlmostThornsOnAnimation()):(r+=
s_iTimeElaps,r>=TIME_TO_HIDE_THORNS&&(this.hideThorns(),C=!C,r=0))};this.setScore=function(){!F&&0<d+Math.abs(Math.floor(l))&&(d+=Math.abs(Math.floor(l)),L.refreshScore(d),0!==d%SCORE_TO_REACH_FOR_INCREMENT_SPEED||G||(e+=OBJECT_SPD_ADDER,l=Math.round(e/7)))};this.controlIfGameOver=function(){return 150>q.getY()||q.getY()>CANVAS_HEIGHT?!0:!1};this.unload=function(){L.unload();null!==H&&(H.unload(),H=null);t=[];y=[];x=[];B=[];stopSound(s_oSoundtrackGame);createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};
this.onExit=function(){this.unload();s_oMain.gotoMenu();stopSound(s_oSoundtrackGame);$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};this.onRestart=function(){this.unload();$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("show_interlevel_ad");s_oMain.gotoGame()};this.gameOver=function(){H=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));q.playDeadTween();playSound("death",1,0);setTimeout(function(){stopSound(N);H&&H.show(d)},2500)};
this.update=function(){D&&I&&(this.handleThorns(),this.handlePowerUp(),this.handlePlayerMovement(),this.moveObject(),f=t[t.length-1].getY(),this.setScore(),this.controlIfGameOver()&&!F&&(this.gameOver(),F=!0,I=D=!1))};s_oGame=this;PLAYER_SPD_MAX=a.player_spd;PLAYER_SPD_FALLING=a.player_spd_falling;PLAYER_MAX_SPD_FALLING=a.player_max_spd_falling;PLAYER_ACCELERATION=a.player_acceleration;PLAYER_DECELERATION=a.player_deceleration;OBJECT_SPD=a.object_spd;OBJECT_SPD_ADDER=a.object_spd_adder;SCORE_TO_REACH_FOR_INCREMENT_SPEED=
a.score_to_reach_for_increment_speed;OBJECT_SPD_ORIZZONTAL=a.object_spd_orizzontal;GAMMA_RANGE_ACCEPTED=a.gamma_range_accepted;CANVAS_WIDTH_RANGE_ACCEPTED=a.canvas_half_width_range_accepted;HEIGHT_BETWEEN_OBJECT=a.height_between_object;TIME_TO_SPAWN_THORNS=a.time_to_spawn_thorns;TIME_TO_HIDE_THORNS=a.time_to_hide_thorns;BONUS_OCCUR=a.bonus_occur;TIME_SLOW_DOWN_POWERUP=a.time_slow_down_powerup;SCORE_BREAKED_PLATFORM=a.score_breaked_platform;SCORE_TO_CHANGE_OCCURRENCE=a.score_to_change_occurrence;SPAWN_DELAY_PLATFORM_OBSTACLES=
a.spawn_delay_platform_obstacles;this._init()}var s_oGame;
function CInterface(){var a,d,b,c,g,f,h=null,k,e,l,p=CANVAS_WIDTH-100,m,r,u;this._init=function(){if(s_bMobile){var h=s_oSpriteLibrary.getSprite("arrow");l=createBitmap(h);l.x=100;l.y=835;l.scaleX=-1;s_oStage.addChild(l);k=new createjs.Shape;k.graphics.beginFill("#ffffff").drawRect(0,0,CANVAS_WIDTH/2,CANVAS_HEIGHT);k.alpha=.01;s_oStage.addChild(k);k.on("mousedown",this.buttonPressLeft);k.on("pressup",this.buttonUpLeft);h=s_oSpriteLibrary.getSprite("arrow");m=createBitmap(h);m.x=p;m.y=835;s_oStage.addChild(m);
e=new createjs.Shape;e.graphics.beginFill("#ffffff").drawRect(CANVAS_WIDTH/2,0,CANVAS_WIDTH/2,CANVAS_HEIGHT);e.alpha=.01;s_oStage.addChild(e);e.on("mousedown",this.buttonPressRight);e.on("pressup",this.buttonUpRight)}new CCeiling(0,0,s_oSpriteLibrary.getSprite("ceiling"),s_oStage);h=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-h.height/2-10;c=h.height/2+10;f=new CGfxButton(b,c,h,s_oStage);f.addEventListener(ON_MOUSE_UP,this._onExit,this);a=CANVAS_WIDTH-h.width/2-100;d=h.height/2+10;if(!1===
DISABLE_SOUND_MOBILE||!1===s_bMobile)h=s_oSpriteLibrary.getSprite("audio_icon"),g=new CToggle(a,d,h,s_bAudioActive),g.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);r=new createjs.Text("SCORE: 0"," 40px "+FONT,"#410701");r.x=27;r.y=62;r.textAlign="left";r.textBaseline="alphabetic";r.lineWidth=400;s_oStage.addChild(r);u=new createjs.Text("SCORE: 0"," 40px "+FONT,"#ffb400");u.x=25;u.y=60;u.textAlign="left";u.textBaseline="alphabetic";u.lineWidth=400;s_oStage.addChild(u);this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.buttonPressLeft=function(a){s_oGame.onButtonDown(LEFT_DIR)};this.buttonPressRight=function(a){s_oGame.onButtonDown(RIGHT_DIR)};this.buttonUpLeft=function(){s_oGame.onButtonUp(LEFT_DIR)};this.buttonUpRight=function(){s_oGame.onButtonUp(RIGHT_DIR)};this.refreshScore=function(a){r.text="SCORE: "+a;u.text="SCORE: "+a};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),g=null;f.unload();s_bMobile&&(s_oStage.off("mousedown",this.buttonPress),s_oStage.off("pressup",
this.buttonUp));null!==h&&h.unload();s_oInterface=null};this.refreshButtonPos=function(e,h){f.setPosition(b-e,h+c);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||g.setPosition(a-e,h+d);s_bMobile&&(l.y=835-h,m.y=835-h);r.y=60+h;u.y=60+h};this._onButHelpRelease=function(){h=new CHelpPanel};this.onExitFromHelp=function(){h.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};this._onRestart=function(){s_oGame.onRestart()};
s_oInterface=this;this._init();return this}var s_oInterface=null;
function CEndPanel(a){var d,b,c,g,f,h,k,e,l,p=this,m;this._init=function(a){d=setTimeout(function(){m=playSound("game_over",1,0);stopSound(s_oSoundtrackGame)},1E3);b=createBitmap(a);b.x=0;b.y=0;g=new createjs.Text(""," 70px "+FONT,"#410701");g.x=CANVAS_WIDTH/2+2;g.y=CANVAS_HEIGHT/2+65;g.textAlign="center";g.textBaseline="alphabetic";g.lineWidth=500;f=new createjs.Text(""," 70px "+FONT,"#ffb400");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2+65;f.textAlign="center";f.textBaseline="alphabetic";f.lineWidth=
500;h=new createjs.Text(""," 40px "+FONT,"#410701");h.x=CANVAS_WIDTH/2+2;h.y=CANVAS_HEIGHT/2+132;h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=500;k=new createjs.Text(""," 40px "+FONT,"#ffb400");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2+132;k.textAlign="center";k.textBaseline="alphabetic";k.lineWidth=500;e=createBitmap(s_oSpriteLibrary.getSprite("but_restart"));e.x=CANVAS_WIDTH/2+15;e.y=CANVAS_HEIGHT/2+160;e.cursor="pointer";l=createBitmap(s_oSpriteLibrary.getSprite("but_home"));l.x=CANVAS_WIDTH/
2-105;l.y=CANVAS_HEIGHT/2+160;l.cursor="pointer";c=new createjs.Container;c.alpha=0;c.visible=!1;c.addChild(b,h,k,g,f,e,l);s_oStage.addChild(c)};this.unload=function(){l&&(l.off("mousedown",this._onExit),e.off("mousedown",this._onRestart));clearTimeout(d);m&&stopSound(m)};this._initListener=function(){l.on("mousedown",this._onExit);e.on("mousedown",this._onRestart)};this.show=function(a){stopSound(s_oSoundtrack);g.text=TEXT_GAMEOVER;f.text=TEXT_GAMEOVER;h.text=TEXT_SCORE+a;k.text=TEXT_SCORE+a;c.visible=
!0;createjs.Tween.get(c).to({alpha:1},500).call(function(){setTimeout(function(){setSoundAsPlayed(s_oSoundtrackGame)},3500);p._initListener()});$(s_oMain).trigger("share_event",[a]);$(s_oMain).trigger("save_score",[a])};this._onExit=function(){p.unload();playSound("press_button",1,0);s_oStage.removeChild(c);s_oGame.onExit()};this._onRestart=function(){p.unload();playSound("press_button",1,0);s_oStage.removeChild(c);stopSound(m);stopSound(s_oSoundtrackGame);s_oGame.onRestart()};this._init(a);return this}
function CPlayer(a){var d,b,c,g,f=0,h=PLAYER_SPD_FALLING,k=-1,e,l,p,m,r,u,q,w,A,n=!1,v=!1,z=!1,y=!1,x,B=!1,t=!1,C=!1;this._init=function(){var f=s_oSpriteLibrary.getSprite("player_left"),f={images:[f],framerate:30,frames:{width:PLAYER_WIDTH,height:PLAYER_HEIGHT,regX:PLAYER_WIDTH/2,regY:PLAYER_HEIGHT/2},animations:{idle:[0,14,"idle"],moving:[15,31,"moving"],start_falling:[32,35,"falling"],falling:[34,35,"falling"],landed:[36,43,"idle"]}};p=new createjs.SpriteSheet(f);f=s_oSpriteLibrary.getSprite("player_right");
f={images:[f],framerate:30,frames:{width:PLAYER_WIDTH,height:PLAYER_HEIGHT,regX:PLAYER_WIDTH/2,regY:PLAYER_HEIGHT/2},animations:{idle:[0,14,"idle"],moving:[15,31,"moving"],start_falling:[32,35,"falling"],falling:[34,35,"falling"],landed:[36,43,"idle"]}};m=new createjs.SpriteSheet(f);f=s_oSpriteLibrary.getSprite("player_hammer_left");f={images:[f],framerate:30,frames:{width:PLAYER_HAMMER_WIDTH,height:PLAYER_HAMMER_HEIGHT,regX:PLAYER_HAMMER_WIDTH/2,regY:PLAYER_HAMMER_HEIGHT/2},animations:{taking_hammer:[0,
8,"hammer_idle"],hammer_idle:[9,13,"hammer_idle"]}};r=new createjs.SpriteSheet(f);f=s_oSpriteLibrary.getSprite("player_hammer_right");f={images:[f],framerate:30,frames:{width:PLAYER_HAMMER_WIDTH,height:PLAYER_HAMMER_HEIGHT,regX:PLAYER_HAMMER_WIDTH/2,regY:PLAYER_HAMMER_HEIGHT/2},animations:{taking_hammer:[0,8,"hammer_idle"],hammer_idle:[9,13,"hammer_idle"]}};u=new createjs.SpriteSheet(f);f=s_oSpriteLibrary.getSprite("player_start");f={images:[f],framerate:30,frames:{width:PLAYER_CHAINED_WIDTH,height:PLAYER_CHAINED_HEIGHT,
regX:PLAYER_CHAINED_WIDTH/2,regY:PLAYER_CHAINED_HEIGHT/2},animations:{idle:[0],breaking_chains:[1,47]}};l=new createjs.SpriteSheet(f);e=createSprite(l,"idle",0,0,PLAYER_WIDTH,PLAYER_HEIGHT);e.x=PLAYER_X_START;e.y=PLAYER_Y_START;a.addChild(e);e.on("animationend",this.letGameStart);d=e.x-e.regX-20;b=e.y+40;c=PLAYER_CHAINED_WIDTH/2-45;g=PLAYER_CHAINED_HEIGHT-PLAYER_CHAINED_HEIGHT/2-40;w=new createjs.Rectangle(d,b,c,g)};this.letGameStart=function(){C||(e.off("animationend",this.letGameStart),e.spriteSheet=
p,D.playIdleAnimation(),s_oGame.letGameStart(),C=!0)};this.startGame=function(){playSound("wothan_broken_chains",.5,0);e.gotoAndPlay("breaking_chains");A="breaking_chains"};this.flipSprite=function(a){a===GOING_RIGHT?y?(k=GOING_RIGHT,e.spriteSheet=u):(k=GOING_RIGHT,e.spriteSheet=m):a===GOING_LEFT&&(y?(k=GOING_LEFT,e.spriteSheet=r):(k=GOING_LEFT,e.spriteSheet=p))};this.playDeadTween=function(){e.visible=!1;var b=s_oSpriteLibrary.getSprite("player_dead");q=createBitmap(b);q.x=e.x;q.y=e.y;q.regX=b.width/
2;q.regY=b.height/2;a.addChild(q);createjs.Tween.get(q).to({y:q.y-100},300,createjs.Ease.CubicIn).call(function(){createjs.Tween.get(q).to({y:CANVAS_HEIGHT+200},700,createjs.Ease.CubicOut).call(function(){})});this.spawnGhost()};this.spawnGhost=function(){var a={images:[s_oSpriteLibrary.getSprite("ghost")],framerate:30,frames:{width:PLAYER_GHOST_WIDTH,height:PLAYER_GHOST_HEIGHT,regX:PLAYER_GHOST_WIDTH/2,regY:PLAYER_GHOST_HEIGHT/2},animations:{idle:[0,29,"idle"]}},a=new createjs.SpriteSheet(a),b=createSprite(a,
"idle",0,0,PLAYER_GHOST_WIDTH,PLAYER_GHOST_HEIGHT);b.x=this.getX();b.y=CANVAS_HEIGHT+200;s_oStage.addChild(b);createjs.Tween.get(b).wait(1500).to({y:CANVAS_HEIGHT/2-80},1500).call(function(){});b.x>CANVAS_WIDTH/2?createjs.Tween.get(b).wait(1500).to({x:b.x-Math.abs(b.x-CANVAS_WIDTH/2)/2},500).call(function(){createjs.Tween.get(b).to({x:b.x+Math.abs(b.x-CANVAS_WIDTH/2)/2},500).call(function(){createjs.Tween.get(b).to({x:b.x-Math.abs(b.x-CANVAS_WIDTH/2)},500).call(function(){})})}):createjs.Tween.get(b).wait(1500).to({x:b.x+
Math.abs(CANVAS_WIDTH/2-b.x)/2},500).call(function(){createjs.Tween.get(b).to({x:b.x-Math.abs(CANVAS_WIDTH/2-b.x)/2},500).call(function(){createjs.Tween.get(b).to({x:b.x+Math.abs(CANVAS_WIDTH/2-b.x)},500).call(function(){})})})};this.playFallingAnimation=function(){n||(e.gotoAndPlay("start_falling"),A="falling",n=!0,v=z=!1)};this.playIdleAnimation=function(){z||(h=PLAYER_SPD_FALLING,e.gotoAndPlay("idle"),A="idle",n&&playSound("wothan_landing",1,0),n=!1,z=!0,v=!1)};this.playMovingAnimation=function(){v||
(e.gotoAndPlay("moving"),A="moving",z=n=!1,v=!0)};this.playerWithHammerOn=function(){k===GOING_RIGHT?e.spriteSheet=u:k===GOING_LEFT&&(e.spriteSheet=r);e.gotoAndPlay("taking_hammer");A="taking_hammer";y=!0};this.playerWithHammerOff=function(){k===GOING_RIGHT?e.spriteSheet=m:k===GOING_LEFT&&(e.spriteSheet=p);e.gotoAndPlay("falling");A="falling";y=!1};this.refreshRectangle=function(){d=e.x-e.regX-30;b=e.y+50;c=PLAYER_WIDTH-65;g=PLAYER_HEIGHT-PLAYER_HEIGHT/2-50;w.setValues(d,b,c,g)};this.playerFalling=
function(){n||this.playFallingAnimation();h+=.2;h>=PLAYER_MAX_SPD_FALLING&&(h=PLAYER_MAX_SPD_FALLING);e.y+=h;this.refreshRectangle()};this.followPlatform=function(a){0!==f?this.playMovingAnimation():this.playIdleAnimation();e.y+=a;this.refreshRectangle()};this.moveLeft=function(a){a&&(t=!1);B=a};this.moveRight=function(a){a&&(B=!1);t=a};this.movePlayer=function(a){t?(f+=a,f>=PLAYER_SPD_MAX&&(f=PLAYER_SPD_MAX),x&&(x=!1,this.flipSprite(GOING_LEFT))):B?(f-=a,f<=-PLAYER_SPD_MAX&&(f=-PLAYER_SPD_MAX),x||
(x=!0,this.flipSprite(GOING_RIGHT))):(f=0,n||this.playIdleAnimation());this.addSpeedToPlayer(f);this.getX()>CANVAS_WIDTH?this.setPos(0):0>this.getX()&&this.setPos(CANVAS_WIDTH)};this.addSpeedToPlayer=function(a){e.x+=a;this.refreshRectangle()};this.addPos=function(){e.x+=f;this.refreshRectangle()};this.setPos=function(a){e.x=a;this.refreshRectangle()};this.returnState=function(){return A};this.getRectangle=function(){return w};this.getSprite=function(){return e};this.getX=function(){return e.x};this.getY=
function(){return e.y};var D=this;this._init()}
function CPlatform(a,d,b,c){var g,f,h,k,e,l,p,m,r,u,q=!0,w=!1,A=!1,n,v,z;this._init=function(){e=a;l=d;var q={images:[s_oSpriteLibrary.getSprite("platforms")],framerate:30,frames:{width:PLATFORM_WIDTH,height:PLATFORM_HEIGHT,regX:0,regY:0},animations:{normal:[0],binary:[1],thorns_off:[2],thorns_almost_on:[3,4,"thorns_almost_on"],thorns_on:[5],platform_destroyed:[6,12,"end"],end:[13]}},q=new createjs.SpriteSheet(q);0===b&&(n=createSprite(q,"normal",0,0,PLATFORM_WIDTH,PLATFORM_HEIGHT),n.x=e+PLATFORM_WIDTH/
2,n.y=l,u="normal");1===b&&(n=createSprite(q,"thorns_off",0,0,PLATFORM_WIDTH,PLATFORM_HEIGHT),n.x=e,n.y=l,u="thorns_off");2===b&&(n=createSprite(q,"binary",0,0,PLATFORM_WIDTH,PLATFORM_HEIGHT),n.x=e,n.y=l,u="binary",w=!0,z=new CObstacle(e,l-n.regY,ROTARY_SAW,c));3===b&&(p=PLATFORM_START_WIDTH,m=PLATFORM_START_HEIGHT,n=createBitmap(s_oSpriteLibrary.getSprite("floor_start")),n.x=e,n.y=l,n.regY=m/2);c.addChild(n);w&&z.addOnStage();3===b?(n.visible=!0,g=n.x,f=n.y+10-n.regY,h=p,k=m):(n.visible=!1,g=n.x+
60,f=n.y+50,h=PLATFORM_WIDTH-150,k=PLATFORM_HEIGHT-100);v=new createjs.Rectangle(g,f,h,k)};this.controlCollision=function(a){if(q)if(0===b){if(v.intersects(a))return PLATFORM}else if(1===b){if(v.intersects(a))return"thorns_on"===r?THORNS:PLATFORM}else if(2===b){if(z.getRectangle().intersects(a))return OBSTACLE;if(v.intersects(a))return PLATFORM}else if(3===b&&v.intersects(a))return PLATFORM;return-1};this.setInvisible=function(){n.visible=!1};this.move=function(a){n.y+=a;w&&z.move(a,n.x+PLATFORM_WIDTH/
2);this.refreshRectangle()};this.refreshRectangle=function(){3===b?(g=n.x,f=n.y+10-n.regY,h=p,k=m-30):(g=n.x+60,f=n.y+60,h=PLATFORM_WIDTH-150,k=PLATFORM_HEIGHT-185);v.setValues(g,f,h,k)};this.startAnimationDestroyed=function(){n.gotoAndPlay("platform_destroyed");q=!1;w&&z.startAnimationDestroyed()};this.changeStatusOn=function(a,b){n.x=a;n.y=b;n.visible=!0;n.alpha=1;q=!0;n.gotoAndStop(u);w&&z.setVisibleTrue(a+PLATFORM_WIDTH/2,b)};this.changeStatusOff=function(){n.x=-150;n.y=CANVAS_HEIGHT+150;n.visible=
!1};this.spawnThorns=function(){q&&(n.gotoAndStop("thorns_on"),r="thorns_on")};this.playAlmostThornsOnAnimation=function(){q&&!A&&(n.gotoAndPlay("thorns_almost_on"),r="thorns_almost_on",A=!0)};this.hideThorns=function(){q&&(n.gotoAndStop("thorns_off"),r="thorns_off",A=!1)};this.getRectangle=function(){return v};this.getType=function(){return b};this.getY=function(){return n.y};this.getX=function(){return n.x};this.unload=function(){c.removeChild(n);_oBonus=n=null};this._init()}
function CScrollingBg(a){var d=null,b=null,c=null,g=null,f=null;this._init=function(){var h=s_oSpriteLibrary.getSprite("bg_scroll_1");d=createBitmap(h);a.addChild(d);a.setChildIndex(d,BG_INDEX);h={images:[s_oSpriteLibrary.getSprite("torch")],framerate:15,frames:{width:TORCH_WIDTH,height:TORCH_HEIGHT,regX:0,regY:0},animations:{idle:[0,12,"idle"]}};h=new createjs.SpriteSheet(h);g=createSprite(h,"idle",0,0,0,0);g.y=50;a.addChild(g);a.setChildIndex(g,BG_INDEX);f=createSprite(h,"idle",0,0,0,0);f.x=CANVAS_WIDTH-
TORCH_WIDTH-45;f.y=50;a.addChild(f);a.setChildIndex(f,BG_INDEX);h=s_oSpriteLibrary.getSprite("bg_scroll_2");b=createBitmap(h);b.y=CANVAS_HEIGHT;a.addChild(b);a.setChildIndex(b,BG_INDEX);h=s_oSpriteLibrary.getSprite("bg_scroll_3");c=createBitmap(h);c.y=2*CANVAS_HEIGHT;a.addChild(c);a.setChildIndex(c,BG_INDEX)};this.move=function(a){b.y<=-CANVAS_HEIGHT&&(b.y=c.y+CANVAS_HEIGHT);c.y<=-CANVAS_HEIGHT&&(c.y=b.y+CANVAS_HEIGHT);0>=d.y&&(d.y+=a,g.y+=a,f.y+=a);b.y+=a;c.y+=a};this._init()}
function CBonus(a,d,b,c){var g,f,h,k,e,l,p;this._init=function(){if(b===SLOW){var m=s_oSpriteLibrary.getSprite("slow_bonus"),m={images:[m],frames:{width:SLOW_WIDTH,height:SLOW_HEIGHT,regX:SLOW_WIDTH/2,regY:SLOW_HEIGHT/2},animations:{idle:[0,29,"idle"]}},m=new createjs.SpriteSheet(m);e=createSprite(m,"idle",0,0,SLOW_WIDTH/2,SLOW_HEIGHT/2);var m=Math.floor(100*Math.random()),r=Math.random();0===r&&(m*=-1);e.x=a+m;e.y=d+SLOW_HEIGHT/2;c.addChild(e)}else b===DESTROY&&(m=s_oSpriteLibrary.getSprite("destroy_bonus"),
m={images:[m],frames:{width:DESTROY_WIDTH,height:DESTROY_HEIGHT,regX:DESTROY_WIDTH/2,regY:DESTROY_HEIGHT/2},animations:{idle:[0,17,"idle"]}},m=new createjs.SpriteSheet(m),e=createSprite(m,"idle",0,0,DESTROY_WIDTH/2,DESTROY_HEIGHT/2),m=Math.floor(100*Math.random()),r=Math.random(),0===r&&(m*=-1),e.x=a+m,e.y=d+DESTROY_HEIGHT/2,c.addChild(e));g=e.x-e.regX;f=e.regY-DESTROY_HEIGHT/2;h=DESTROY_WIDTH;k=DESTROY_HEIGHT;l=new createjs.Rectangle(g,f,h,k);p=new createjs.Shape;p.graphics.beginFill("#0f0f0f").drawRect(g,
f,h,k);p.alpha=.5;c.addChild(p)};this.controlCollision=function(a){return null!==l.intersection(a)?(playSound("spring",1,0),!0):!1};this.checkIfOverCanvas=function(){return 0>e.y?!0:!1};this.move=function(a){e.y+=a;this.refreshRectangle()};this.refreshRectangle=function(){b===SLOW?(g=e.x-SLOW_WIDTH/2,f=e.y-SLOW_HEIGHT/2,h=SLOW_WIDTH,k=SLOW_HEIGHT+SLOW_HEIGHT/2):b===DESTROY&&(g=e.x-DESTROY_WIDTH/2,f=e.y-DESTROY_HEIGHT/2,h=DESTROY_WIDTH,k=DESTROY_HEIGHT+DESTROY_HEIGHT/2);l.setValues(g,f,h,k);c.removeChild(p)};
this.moveOrizzontal=function(a){e.x+=a};this.getRectangle=function(){return l};this.getY=function(){return e.y};this.getX=function(){return e.x};this.getType=function(){return b};this.unload=function(){c.removeChild(e);c.removeChild(p)};this._init()}
function CObstacle(a,d,b,c){var g,f,h,k,e,l,p=!1,m,r;this._init=function(){if(b===ROTARY_SAW){var c={images:[s_oSpriteLibrary.getSprite("rotary_saw_destroyed")],framerate:30,frames:{width:ROTATORY_SAW_DESTROYED_WIDTH,height:ROTATORY_SAW_DESTROYED_HEIGHT,regX:ROTATORY_SAW_DESTROYED_WIDTH/2,regY:ROTATORY_SAW_DESTROYED_HEIGHT/2},animations:{idle_breaking:[0,7,"end"],end:[8]}};l=new createjs.SpriteSheet(c);c={images:[s_oSpriteLibrary.getSprite("rotary_saw")],framerate:30,frames:{width:ROTATORY_SAW_WIDTH,
height:ROTATORY_SAW_HEIGHT,regX:ROTATORY_SAW_WIDTH/2,regY:0},animations:{idle:[0,19,"idle"]}};e=new createjs.SpriteSheet(c);m=createSprite(e,"idle",0,0,ROTATORY_SAW_WIDTH/2,0);m.x=a;m.y=d-ROTATORY_SAW_HEIGHT/2}g=m.x-ROTATORY_SAW_WIDTH/2;f=m.y;h=ROTATORY_SAW_WIDTH;k=ROTATORY_SAW_HEIGHT;r=new createjs.Rectangle(g,f,h,k)};this.startAnimationDestroyed=function(){m.spriteSheet=l;m.gotoAndPlay("idle_breaking")};this.addOnStage=function(){c.addChild(m)};this.controlCollision=function(a){return null!==r.intersection(a)?
(playSound("spring",1,0),!0):!1};this.checkIfOverCanvas=function(){return 0>m.y?!0:!1};this.setVisibleFalse=function(){m.visible=!1};this.setVisibleTrue=function(a,b){m.visible=!0;m.spriteSheet=e;m.gotoAndPlay("idle");m.x=a;m.y=b+5};this.move=function(a,b){m.y+=a;this.moveOrizzontal(a,b);this.refreshRectangle()};this.moveOrizzontal=function(a,b){a/=2;m.x>b-50&&!p?m.x+=a:m.x<=b-50&&(p=!0);m.x<b+50&&p?m.x-=a:m.x>=b+50&&(p=!1)};this.refreshRectangle=function(){g=m.x-ROTATORY_SAW_WIDTH/2;f=m.y+10;h=ROTATORY_SAW_WIDTH;
k=ROTATORY_SAW_HEIGHT+40;r.setValues(g,f,h,k)};this.getRectangle=function(){return r};this.getY=function(){return m.y};this.getX=function(){return m.x};this.getType=function(){return b};this.unload=function(){c.removeChild(m)};this._init()}
function CCeiling(a,d,b,c){var g;this._init=function(){var f=new createjs.SpriteSheet({images:[b],frames:{width:CEILING_WIDTH,height:CEILING_HEIGHT,regX:0,regY:0},animations:{idle:[0,15,"idle"]}});g=createSprite(f,"idle",0,0,0,0);g.x=a;g.y=d;c.addChild(g)};this.getY=function(){return g.y};this.getX=function(){return g.x};this.setPos=function(a,b){g.x=a;g.y=b};this.unload=function(){c.removeChild(g);c.removeChild(void 0)};this._init()}
function CCreditsPanel(){var a,d,b,c,g,f,h;this._init=function(){d=createBitmap(s_oSpriteLibrary.getSprite("credits_panel"));s_oStage.addChild(d);f=new createjs.Shape;f.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=.01;f.on("click",this._onLogoButRelease);s_oStage.addChild(f);var k=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-k.height/2-100;c=new CGfxButton(a,300,k,s_oStage);c.addEventListener(ON_MOUSE_UP,this.unload,this);g=new CFormatText(CANVAS_WIDTH/2,
430,TEXT_CREDITS_DEVELOPED,"#ffb400",s_oStage,"#410701",40);k=s_oSpriteLibrary.getSprite("logo_credits");b=createBitmap(k);b.regX=k.width/2;b.regY=k.height/2;b.x=CANVAS_WIDTH/2;b.y=560;s_oStage.addChild(b);h=new CFormatText(CANVAS_WIDTH/2,690,TEXT_LINK1,"#ffb400",s_oStage,"#410701",40)};this.unload=function(){f.off("click",this._onLogoButRelease);c.unload();c=null;g.unload();h.unload();s_oStage.removeChild(d);s_oStage.removeChild(b);s_oStage.removeChild(f)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};
this._init()}
function CFormatText(a,d,b,c,g,f,h){var k,e,l,p,m,r;this._init=function(a,b,c,d,f,g,h){k=c;p=new createjs.Container;p.x=a;p.y=b;f.addChild(p);a=h+"px";e=new createjs.Text;e.text=k;e.font="bold "+a+" "+FONT;e.color=g;e.textAlign="center";e.textBaseline="middle";e.lineWidth=600;e.outline=4;p.addChild(e);l=new createjs.Text;l.text=k;l.font="bold "+a+" "+FONT;l.color=d;l.textAlign="center";l.textBaseline="middle";l.lineWidth=600;p.addChild(l)};this.unload=function(){g.removeChild(p)};this.disableOutline=function(){p.removeChild(e)};
this.setVisible=function(a){p.visible=a};this.isVisible=function(){return p.visible};this.setOutline=function(a){e.outline=a};this.setShadow=function(a){e.shadow=a?new createjs.Shadow("#333333",2,2,6):null};this.setAlign=function(a){e.textAlign=a;l.textAlign=a};this.setWidth=function(a){e.lineWidth=a;l.lineWidth=a};this.setText=function(a){l.text=a;e.text=a};this.setColor=function(a,b){l.color=a;e.color=b};this.setFont=function(a){var b=h+"px";l.font="bold "+b+" "+a;e.font="bold "+b+" "+a};this.getText=
function(){return p};this.setPos=function(a){p.y=a};this.getPos=function(){return{x:p.x,y:p.y}};this.playText=function(){m="";this.setText("");this._slideText(0)};this._slideText=function(a){m+=b[a];this.setText(m);a<b.length-1&&setTimeout(function(){r._slideText(a+1)},40)};this.setPosition=function(a,b){p.x=a;p.y=b};r=this;this._init(a,d,b,c,g,f,h)};
