var s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var b=a.toLowerCase(),d=window.document,c=d.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var f=d.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var e=d.createElement("div");e.id="vpw-test-d";e.style.cssText="position:absolute;top:-1000px";e.innerHTML="<style>@media("+b+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+b+":7px!important}}</style>";f.appendChild(e);c.insertBefore(f,d.head);
a=7==e["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(f)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return!0;return!1}
function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var b=getSize("Width");_checkOrientation(b,a);var d=Math.min(a/CANVAS_HEIGHT,b/CANVAS_WIDTH),c=CANVAS_WIDTH*d,d=CANVAS_HEIGHT*d,f;d<a?(f=a-d,d+=f,c+=CANVAS_WIDTH/CANVAS_HEIGHT*f):c<b&&(f=b-c,c+=f,d+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-d/2;var e=b/2-c/2,g=CANVAS_WIDTH/c;if(e*g<-EDGEBOARD_X||f*g<-EDGEBOARD_Y)d=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),
b/(CANVAS_WIDTH-2*EDGEBOARD_X)),c=CANVAS_WIDTH*d,d*=CANVAS_HEIGHT,f=(a-d)/2,e=(b-c)/2,g=CANVAS_WIDTH/c;s_iOffsetX=-1*e*g;s_iOffsetY=-1*f*g;0<=f&&(s_iOffsetY=0);0<=e&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile?($("#canvas").css("width",c+"px"),$("#canvas").css("height",d+"px")):(s_oStage.canvas.width=c,s_oStage.canvas.height=d,s_oStage.scaleX=s_oStage.scaleY=Math.min(c/CANVAS_WIDTH,
d/CANVAS_HEIGHT));0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",e+"px")}}
function _checkOrientation(a,b){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>b?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function createBitmap(a,b,d){var c=new createjs.Bitmap(a),f=new createjs.Shape;b&&d?f.graphics.beginFill("#fff").drawRect(0,0,b,d):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=f;return c}function createSprite(a,b,d,c,f,e){a=null!==b?new createjs.Sprite(a,b):new createjs.Sprite(a);b=new createjs.Shape;b.graphics.beginFill("#000000").drawRect(-d,-c,f,e);a.hitArea=b;return a}
function randomFloatBetween(a,b,d){"undefined"===typeof d&&(d=2);return parseFloat(Math.min(a+Math.random()*(b-a),b).toFixed(d))}function shuffle(a){for(var b=a.length,d,c;0!==b;)c=Math.floor(Math.random()*b),--b,d=a[b],a[b]=a[c],a[c]=d;return a}function formatTime(a){a/=1E3;var b=Math.floor(a/60);a=parseFloat(a-60*b).toFixed(1);var d="",d=10>b?d+("0"+b+":"):d+(b+":");return 10>a?d+("0"+a):d+a}
Array.prototype.sortOn=function(){var a=this.slice();if(!arguments.length)return a.sort();var b=Array.prototype.slice.call(arguments);return a.sort(function(a,c){for(var d=b.slice(),e=d.shift();a[e]==c[e]&&d.length;)e=d.shift();return a[e]==c[e]?0:a[e]>c[e]?1:-1})};function roundDecimal(a,b){var d=Math.pow(10,b);return Math.round(d*a)/d}function tweenVectors(a,b,d,c){c.set(a.getX()+d*(b.getX()-a.getX()),a.getY()+d*(b.getY()-a.getY()));return c}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var b=document.createEvent("MouseEvents");b.initEvent("click",!0,!0);a.dispatchEvent(b)}}};function playSound(a,b,d){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:d,volume:b}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}
function setVolume(a,b){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=b}function setMute(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(b)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var b=window.location.search.substring(1).split("&"),d=0;d<b.length;d++){var c=b[d].split("=");if(c[0]==a)return c[1]}}
function CSpriteLibrary(){var a,b,d,c,f,e;this.init=function(g,k,n){d=b=0;c=g;f=k;e=n;a={}};this.addSprite=function(c,d){a.hasOwnProperty(c)||(a[c]={szPath:d,oSprite:new Image},b++)};this.getSprite=function(c){return a.hasOwnProperty(c)?a[c].oSprite:null};this._onSpritesLoaded=function(){f.call(e)};this._onSpriteLoaded=function(){c.call(e);++d===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var c in a)a[c].oSprite.oSpriteLibrary=this,a[c].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[c].oSprite.src=a[c].szPath};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=1700,CANVAS_HEIGHT=768,EDGEBOARD_X=250,EDGEBOARD_Y=0,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,FONT_GAME_1="arialbold",FONT_GAME_2="Digital-7",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_GAME_WAITING_FOR_BET=0,STATE_GAME_DEALING=1,STATE_GAME_PLAYER_TURN=2,STATE_GAME_SHOWDOWN=3,STATE_GAME_DISTRIBUTE_FICHES=4,STATE_GAME_SHOW_WINNER=5,STATE_CARD_DEALING=0,STATE_CARD_REMOVING=1,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ASSIGN_FICHES=
"ASSIGN_FICHES",END_HAND="END_HAND",ON_CARD_SHOWN="ON_CARD_SHOWN",ON_CARD_ANIMATION_ENDING="ON_CARD_ANIMATION_ENDING",ON_CARD_TO_REMOVE="ON_CARD_TO_REMOVE",NUM_FICHES=6,CARD_WIDTH=66,CARD_HEIGHT=102,MIN_BET,MAX_BET,TOTAL_MONEY,FICHE_WIDTH,WIN_OCCURRENCE,BET_OCCURRENCE,TIME_FICHES_MOV=600,TIME_CARD_DEALING=250,TIME_CARD_REMOVE=1E3,TIME_SHOW_FINAL_CARDS=4E3,TIME_END_HAND,BET_TIME=1E4,AD_SHOW_COUNTER,NUM_DECKS=4,PAYOUT_MULT,ROYAL_FLUSH=0,STRAIGHT_FLUSH=1,FOUR_OF_A_KIND=2,FULL_HOUSE=3,FLUSH=4,STRAIGHT=
5,THREE_OF_A_KIND=6,TWO_PAIR=7,ONE_PAIR=8,HIGH_CARD=9,NO_HAND=10,CARD_TWO=2,CARD_THREE=3,CARD_FOUR=4,CARD_FIVE=5,CARD_SIX=6,CARD_SEVEN=7,CARD_EIGHT=8,CARD_NINE=9,CARD_TEN=10,CARD_JACK=11,CARD_QUEEN=12,CARD_KING=13,CARD_ACE=14,BET_ANTE=0,BET_RAISE=1,POS_BET=[],MULTIPLIERS=[],ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,TEXT_DEAL="DEAL",TEXT_MIN_BET="MIN BET",TEXT_MAX_BET="MAX BET",TEXT_RECHARGE="RECHARGE",TEXT_EXIT="EXIT",TEXT_MONEY="MONEY",TEXT_CURRENCY="$",TEXT_RAISE="RAISE",TEXT_FOLD="FOLD",TEXT_DISPLAY_MSG_WAITING_BET=
"WAITING FOR YOUR BET",TEXT_DISPLAY_MSG_PLAYER_LOSE="PLAYER LOSES THIS HAND!",TEXT_DISPLAY_MSG_STANDOFF="STAND OFF",TEXT_DISPLAY_MSG_PLAYER_WIN="PLAYER WINS",TEXT_DISPLAY_MSG_USER_TURN="PLAYER TURN. RAISE OR FOLD?",TEXT_DISPLAY_MSG_SHOWDOWN="SHOWDOWN!",TEXT_DISPLAY_MSG_DEALING="DEALING...",TEXT_NO_MONEY="YOU DON'T HAVE ENOUGH MONEY!!!",TEXT_HAND_WON_PLAYER="HAND WON BY THE PLAYER",TEXT_HAND_WON_DEALER="HAND WON BY THE DEALER",TEXT_ERROR_MIN_BET="YOUR BET IS LOWER THAN MINIMUM BET!!",TEXT_ERROR_MAX_BET=
"YOUR BET IS HIGHER THAN MAXIMUM BET!!",TEXT_EVALUATOR="ROYAL FLUSH;STRAIGHT FLUSH;FOUR OF A KIND;FULL HOUSE;FLUSH;STRAIGHT;THREE OF A KIND;TWO PAIR;ONE PAIR;HIGH CARD;NO HAND".split(";"),TEXT_SHARE_IMAGE="200x200.jpg",TEXT_SHARE_TITLE="Congratulations!",TEXT_SHARE_MSG1="You collected <strong>",TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!",TEXT_SHARE_SHARE1="My score is ",TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var a,b,d,c,f;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_preloader","./sprites/bg_preloader.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();f=new createjs.Container;s_oStage.addChild(f)};this.unload=function(){f.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var e=createBitmap(s_oSpriteLibrary.getSprite("bg_preloader"));f.addChild(e);d=createBitmap(s_oSpriteLibrary.getSprite("progress_bar"));d.x=599;d.y=CANVAS_HEIGHT-50;f.addChild(d);a=476;c=new createjs.Shape;c.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(599,CANVAS_HEIGHT-50,1,30);f.addChild(c);d.mask=c;b=new createjs.Text("0%","30px "+FONT_GAME_1,"#fff");b.x=638;b.y=CANVAS_HEIGHT-56;b.textAlign="center";b.textBaseline="middle";f.addChild(b)};this.refreshLoader=function(d){b.text=
d+"%";d=Math.floor(d*a/100);c.graphics.clear();c.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(599,CANVAS_HEIGHT-50,d,30)};this._init()}
function CMain(a){var b,d=0,c=0,f=STATE_LOADING,e,g,k;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader;
s_oGameSettings=new CGameSettings;b=!0};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds()};this.soundLoaded=function(){d++;g.refreshLoader(Math.floor(d/c*100));d===c&&(g.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,
this)),createjs.Sound.registerSound("./sounds/card.ogg","card"),createjs.Sound.registerSound("./sounds/chip.ogg","chip"),createjs.Sound.registerSound("./sounds/fiche_collect.ogg","fiche_collect"),createjs.Sound.registerSound("./sounds/press_but.ogg","press_but"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/lose.ogg","lose")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),
createjs.Sound.registerSound("./sounds/card.mp3","card",4),createjs.Sound.registerSound("./sounds/chip.mp3","chip",4),createjs.Sound.registerSound("./sounds/fiche_collect.mp3","fiche_collect"),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/lose.mp3","lose")),c+=6)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_menu_bg",
"./sprites/but_menu_bg.png");s_oSpriteLibrary.addSprite("but_game_bg","./sprites/but_game_bg.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("card_spritesheet","./sprites/card_spritesheet.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("display_bg",
"./sprites/display_bg.png");s_oSpriteLibrary.addSprite("fiche_highlight","./sprites/fiche_highlight.png");s_oSpriteLibrary.addSprite("win_bg","./sprites/win_bg.png");s_oSpriteLibrary.addSprite("but_clear","./sprites/but_clear.png");s_oSpriteLibrary.addSprite("but_generic","./sprites/but_generic.png");s_oSpriteLibrary.addSprite("but_rebet","./sprites/but_rebet.png");s_oSpriteLibrary.addSprite("gui_bg","./sprites/gui_bg.png");s_oSpriteLibrary.addSprite("bet_ante","./sprites/bet_ante.png");s_oSpriteLibrary.addSprite("bet_raise",
"./sprites/bet_raise.png");s_oSpriteLibrary.addSprite("paytable_bg","./sprites/paytable_bg.png");s_oSpriteLibrary.addSprite("help_cursor","./sprites/help_cursor.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");for(var a=0;a<NUM_FICHES;a++)s_oSpriteLibrary.addSprite("fiche_"+a,"./sprites/fiche_"+a+".png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){d++;g.refreshLoader(Math.floor(d/c*100));d===c&&(g.unload(),this.gotoMenu())};
this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(){k=new CGame(e);f=STATE_GAME};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){b=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();b=!0;createjs.Ticker.paused=!1;$("#block_game").css("display",
"none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=function(a){if(b){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&k.update();s_oStage.update(a)}};s_oMain=this;e=a;ENABLE_CHECK_ORIENTATION=e.check_orientation;ENABLE_FULLSCREEN=e.fullscreen;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_bFullscreen=!1,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oGameSettings;
function CTextButton(a,b,d,c,f,e,g,k){var n,m,h,l,u,v,p,A;this._init=function(a,c,b,d,f,e,g,k){n=!1;m=[];h=[];A=k;u=createBitmap(b);k=Math.ceil(g/20);v=new createjs.Text(d,g+"px "+f,"#000000");var w=v.getBounds();v.textAlign="center";v.textBaseline="alphabetic";v.x=b.width/2+k;v.y=Math.floor(b.height/2)+w.height/3+k;p=new createjs.Text(d,g+"px "+f,e);p.textAlign="center";p.textBaseline="alphabetic";p.x=b.width/2;p.y=Math.floor(b.height/2)+w.height/3;l=new createjs.Container;l.x=a;l.y=c;l.regX=b.width/
2;l.regY=b.height/2;l.cursor="pointer";l.addChild(u,p);A.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");A.removeChild(l)};this.setVisible=function(a){l.visible=a};this.enable=function(){n=!1;p.color="#fff"};this.disable=function(){n=!0;p.color="#a39b9d"};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){m[a]=c;h[a]=b};this.buttonRelease=function(){n||(!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||playSound("press_but",1,0),l.scaleX=1,l.scaleY=1,m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(h[ON_MOUSE_UP]))};this.buttonDown=function(){n||(l.scaleX=.9,l.scaleY=.9,m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN]))};this.setPosition=function(a,c){l.x=a;l.y=c};this.changeText=function(a){p.text=a;v.text=a};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};
this._init(a,b,d,c,f,e,g,k);return this}
function CGfxButton(a,b,d,c){var f,e,g,k,n,m=[],h,l;this._init=function(a,c,b){f=!1;k=[];n=[];e=b.width;g=b.height;h=createBitmap(b);h.x=a;h.y=c;h.regX=b.width/2;h.regY=b.height/2;h.cursor="pointer";l.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);l.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=
function(a,c,b){k[a]=c;n[a]=b};this.addEventListenerWithParams=function(a,c,b,d){k[a]=c;n[a]=b;m=d};this.buttonRelease=function(){f||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||playSound("press_but",1,0),k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(n[ON_MOUSE_UP],m))};this.buttonDown=function(){f||k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN],m)};this.setPosition=function(a,c){h.x=a;h.y=c};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.enable=function(){f=!1;h.filters=[];h.cache(0,
0,e,g)};this.disable=function(){f=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);h.filters=[new createjs.ColorMatrixFilter(a)];h.cache(0,0,e,g)};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};l=c;this._init(a,b,d);return this}
function CToggle(a,b,d,c,f){var e,g,k,n,m=[],h;this._init=function(a,c,b,d,f){k=[];n=[];var l=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}});e=d;g=f;h=createSprite(l,"state_"+e,b.width/2/2,b.height/2,b.width/2,b.height);h.x=a;h.y=c;h.cursor="pointer";h.stop();s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);
s_oStage.removeChild(h)};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){k[a]=c;n[a]=b};this.addEventListenerWithParams=function(a,c,b,d){k[a]=c;n[a]=b;m=d};this.setActive=function(a){e=a;h.gotoAndStop("state_"+e)};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;playSound("press_button",1,0);g&&(e=!e,h.gotoAndStop("state_"+e));k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(n[ON_MOUSE_UP],m)};this.buttonDown=function(){h.scaleX=
.9;h.scaleY=.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN],m)};this.setPosition=function(a,c){h.x=a;h.y=c};this.setVisible=function(a){h.visible=a};this.getY=function(){return h.y};this._init(a,b,d,c,f)}
function CMenu(){var a,b,d,c,f,e,g,k,n=null,m=null,h;this._init=function(){f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(f);var l=s_oSpriteLibrary.getSprite("but_menu_bg");e=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-164,l,s_oStage);e.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l=s_oSpriteLibrary.getSprite("audio_icon"),d=CANVAS_WIDTH-l.width/4-10,c=l.height/2+10,g=new CToggle(d,c,l),g.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);var l=window.document,u=l.documentElement;n=u.requestFullscreen||u.mozRequestFullScreen||u.webkitRequestFullScreen||u.msRequestFullscreen;m=l.exitFullscreen||l.mozCancelFullScreen||l.webkitExitFullscreen||l.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(n=!1);n&&!1===inIframe()&&(l=s_oSpriteLibrary.getSprite("but_fullscreen"),a=l.width/4+10,b=l.height/2+10,k=new CToggle(a,b,l,s_bFullscreen,!0),k.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));h=new createjs.Shape;
h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(h);createjs.Tween.get(h).to({alpha:0},400).call(function(){h.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(f,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||g.setPosition(d-f,e+c);n&&!1===inIframe()&&k.setPosition(a+f,b+e)};this.unload=function(){e.unload();e=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),g=null;n&&!1===inIframe()&&k.unload();s_oStage.removeAllChildren();
s_oMenu=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame();$(s_oMain).trigger("start_session")};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._onFullscreenRelease=function(){s_bFullscreen?(m.call(window.document),s_bFullscreen=!1):(n.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var b=!1,d,c,f,e,g,k,n,m,h,l,u,v,p,A,w,G,z,F,E,D,C,K,I,H,B,J,x,r,L,y,O,t,q,M,N;this._init=function(){f=MAX_BET;e=-1;g=v=c=0;s_oTweenController=new CTweenController;O=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(O);t=new CInterface(TOTAL_MONEY);r=new createjs.Container;s_oStage.addChild(r);L=new CHandEvaluator;q=new CSeat;q.setCredit(TOTAL_MONEY);y=new CHelpCursor(520,416,s_oSpriteLibrary.getSprite("help_cursor"),s_oStage);this.reset(!1);I=new CVector2;I.set(1214,
228);H=new CVector2;H.set(CANVAS_WIDTH/2-199,230);B=new CVector2;B.set(418,820);J=new CVector2;J.set(0,-CANVAS_HEIGHT);x=new CVector2(454,230);E=[q.getCardOffset(),H];N=new CGameOver;q.getCredit()<s_oGameSettings.getFichesValueAt(0)?(this._gameOver(),this.changeState(-1)):b=!0;K=new CVector2(I.getX(),I.getY());M=new CMsgBox;this.changeState(STATE_GAME_WAITING_FOR_BET)};this.unload=function(){b=!1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.stop();for(var a=0;a<w.length;a++)w[a].unload();
t.unload();N.unload();M.unload();s_oStage.removeAllChildren()};this.reset=function(a){k=g=c=0;q.reset();w=[];w.splice(0);G=[];F=[];t.reset();t.enableBetFiches(a);this.shuffleCard()};this.shuffleCard=function(){z=[];z=s_oGameSettings.getShuffledCardDeck()};this.changeState=function(a){e=a;switch(a){case STATE_GAME_WAITING_FOR_BET:t.displayMsg(TEXT_DISPLAY_MSG_WAITING_BET,TEXT_MIN_BET+": "+MIN_BET+"\n"+TEXT_MAX_BET+": "+MAX_BET);break;case STATE_GAME_DEALING:t.disableButtons(),t.displayMsg(TEXT_DISPLAY_MSG_DEALING),
this._dealing()}};this.cardFromDealerArrived=function(a,c,b){(!1===c||c&&9===b)&&a.showCard();10>b&&s_oGame._dealing()};this._showWin=function(){var a=0;d?this._playerLose():l===NO_HAND&&"dealer"!==p?(a=2*q.getBetAnte()+q.getBetRaise(),this._playerWin(a)):"player"===p?(a=2*q.getBetAnte()+q.getBetRaise()*PAYOUT_MULT[u],this._playerWin(a)):"dealer"===p&&l!==NO_HAND?this._playerLose():(a=q.getBetAnte()+q.getBetRaise(),this._standOff(a));"player"===p?playSound("win",1,0):playSound("lose",1,0);this.changeState(STATE_GAME_DISTRIBUTE_FICHES);
t.refreshCredit(q.getCredit());setTimeout(function(){q.resetBet();s_oGame.changeState(STATE_GAME_WAITING_FOR_BET);t.enableBetFiches(!0)},3*TIME_CARD_REMOVE)};this._playerWin=function(a){q.increaseCredit(a);n-=a;t.displayMsg(TEXT_DISPLAY_MSG_SHOWDOWN,TEXT_DISPLAY_MSG_PLAYER_WIN+" "+a+TEXT_CURRENCY);q.initMovement(0,B.getX(),B.getY());q.initMovement(1,B.getX(),B.getY());t.showResultText(TEXT_HAND_WON_PLAYER)};this._playerLose=function(a){t.displayMsg(TEXT_DISPLAY_MSG_SHOWDOWN,TEXT_DISPLAY_MSG_PLAYER_LOSE);
q.initMovement(0,J.getX(),J.getY());a||q.initMovement(1,J.getX(),J.getY());t.showResultText(TEXT_HAND_WON_DEALER)};this._standOff=function(a){q.increaseCredit(a);n-=a;t.displayMsg(TEXT_DISPLAY_MSG_SHOWDOWN,TEXT_DISPLAY_MSG_STANDOFF);q.initMovement(0,B.getX(),B.getY());q.initMovement(1,B.getX(),B.getY());t.showResultText(TEXT_DISPLAY_MSG_STANDOFF)};this._dealing=function(){if(10>k){var a=new CCard(I.getX(),I.getY(),r),c;if(1===k%E.length){c=new CVector2(H.getX()+(CARD_WIDTH/2+7)*k,H.getY());var b=
C.splice(0,1),d=b[0].fotogram,b=b[0].rank;a.setInfo(K,c,d,b,!0,k);a.addEventListener(ON_CARD_SHOWN,this._onCardShown);G.push(a)}else b=D.splice(0,1),d=b[0].fotogram,b=b[0].rank,a.setInfo(K,q.getAttachCardOffset(),d,b,!1,k),q.newCardDealed(),F.push(a);w.push(a);k++;a.addEventListener(ON_CARD_ANIMATION_ENDING,this.cardFromDealerArrived);playSound("card",1,0)}else setTimeout(function(){s_oGame.changeState(STATE_GAME_PLAYER_TURN);t.displayMsg(TEXT_DISPLAY_MSG_USER_TURN);t.enable(!1,!0,!0)},1E3)};this._onEndHand=
function(){for(var a=new CVector2(x.getX(),x.getY()),b=0;b<w.length;b++)w[b].initRemoving(a),w[b].hideCard();t.clearCardValueText();c=0;s_oGame.changeState(STATE_GAME_SHOW_WINNER);playSound("fiche_collect",1,0);v++;v===AD_SHOW_COUNTER&&(v=0,$(s_oMain).trigger("show_interlevel_ad"));$(s_oMain).trigger("save_score",[q.getCredit()])};this._onCardShown=function(){e===STATE_GAME_PLAYER_TURN&&(4===h?(t.showHandValue(l,u),e=STATE_GAME_SHOWDOWN,s_oGame._showWin()):s_oGame._showNextDealerCard())};this.setBet=
function(a,b){if(t.isResultPanelvisible())t.disableBetFiches(),q.clearBet(),A=this.setBet,this._onEndHand();else{var d=s_oGameSettings.getFichesValues()[b],e;a===BET_ANTE?(c=0,y.hide(),e=q.getBetAnte()+d):e=2*q.getBetAnte();e>f?M.show(TEXT_ERROR_MAX_BET):d>q.getCredit()?t.displayMsg(TEXT_NO_MONEY):(a===BET_ANTE?(q.decreaseCredit(d),n+=d,q.betAnte(d),t.enable(!0,!1,!1)):(q.decreaseCredit(e),n+=e,q.betRaise()),t.refreshCredit(q.getCredit()))}};this._gameOver=function(){N.show()};this.onRebet=function(){t.isResultPanelvisible()&&
(A=this.rebet,this._onEndHand())};this.onDeal=function(){m=q.getBetAnte()*PAYOUT_MULT[0];if(q.getBetAnte()<MIN_BET)M.show(TEXT_ERROR_MIN_BET),t.enableBetFiches(!1),t.enable(!1,!1,!1);else{r.removeAllChildren();if((n<m?WIN_OCCURRENCE+1:Math.floor(101*Math.random()))>WIN_OCCURRENCE){do{D=this._generateRandPlayerCards();C=this._generateRandDealerCards();var a=L.evaluate(C),c=L.evaluate(D);l=a.ret;u=c.ret;p=L.getWinnerComparingHands(c.sort_hand,a.sort_hand,u,l)}while(l===NO_HAND||"player"===p)}else{do D=
this._generateRandPlayerCards(),C=this._generateRandDealerCards(),a=L.evaluate(C),c=L.evaluate(D),l=a.ret,u=c.ret,p=L.getWinnerComparingHands(c.sort_hand,a.sort_hand,u,l);while("dealer"===p)}q.setPrevBet();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("card");d=!1;this.changeState(STATE_GAME_DEALING)}};this.onFold=function(){d=!0;p="dealer";h=0;this._showNextDealerCard()};this.onRaise=function(){e!==STATE_GAME_DISTRIBUTE_FICHES&&(this.setBet(BET_RAISE,t.getFicheSelected()),h=0,this._showNextDealerCard())};
this._showNextDealerCard=function(){G[h].showCard();h++};this._generateRandDealerCards=function(){for(var a=[],c=0;5>c;c++)a.push({fotogram:z[g].fotogram,rank:z[g].rank,suit:z[g].suit}),g++,this._checkDeckLength();return a};this._generateRandPlayerCards=function(){for(var a=[],c=0;5>c;c++)a.push({fotogram:z[g].fotogram,rank:z[g].rank,suit:z[g].suit}),g++,this._checkDeckLength();return a};this._checkDeckLength=function(){g>=z.length&&(z=s_oGameSettings.getShuffledCardDeck(),g=0)};this.clearBets=function(){if(e===
STATE_GAME_WAITING_FOR_BET){t.enable(!1,!1,!1);var a=q.getStartingBet();0<a&&(q.clearBet(),q.increaseCredit(a),n-=a,t.refreshCredit(q.getCredit()),a=q.checkIfRebetIsPossible(),t.enableBetFiches(a))}};this.rebet=function(){this.clearBets();var a=q.rebet();n-=a;t.enable(!0,!1,!1);t.refreshCredit(q.getCredit());c=BET_TIME};this.onExit=function(){this.unload();$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",q.getCredit());s_oMain.gotoMenu()};this.getState=function(){return e};this._updateDealing=
function(){for(var a=0;a<w.length;a++)w[a].update()};this._updateFiches=function(){q.updateFichesController()};this._updateShowWinner=function(){for(var a=0;a<w.length;a++)w[a].update();c+=s_iTimeElaps;c>TIME_END_HAND&&(c=0,a=q.checkIfRebetIsPossible(),this.reset(a),t.reset(),q.getCredit()<s_oGameSettings.getFichesValueAt(0)?(this._gameOver(),this.changeState(-1)):q.getCredit()<s_oGameSettings.getFichesValueAt(0)?(this._gameOver(),this.changeState(-1)):(this.changeState(STATE_GAME_WAITING_FOR_BET),
A.call(this,0,t.getFicheSelected())))};this.update=function(){if(!1!==b)switch(e){case STATE_GAME_WAITING_FOR_BET:c+=s_iTimeElaps;6E3<c&&(c=0,y.isVisible()||0!==q.getBetAnte()||y.show(1));break;case STATE_GAME_DEALING:this._updateDealing();break;case STATE_GAME_DISTRIBUTE_FICHES:this._updateFiches();break;case STATE_GAME_SHOW_WINNER:this._updateShowWinner()}};s_oGame=this;TOTAL_MONEY=a.money;MIN_BET=a.min_bet;MAX_BET=a.max_bet;MULTIPLIERS=a.multiplier;BET_TIME=a.bet_time;BLACKJACK_PAYOUT=a.blackjack_payout;
WIN_OCCURRENCE=a.win_occurrence;BET_OCCURRENCE=a.bet_occurrence;n=a.game_cash;PAYOUT_MULT=a.payout;TIME_END_HAND=a.time_show_hand;AD_SHOW_COUNTER=a.ad_show_counter;this._init()}var s_oGame,s_oTweenController;
function CInterface(a){var b,d,c,f,e,g,k,n,m,h,l,u,v,p,A,w=null,G,z,F,E,D,C,K,I,H,B=null,J=null;this._init=function(a){var r=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH-r.width/2-10;f=r.height/2+10;m=new CGfxButton(c,f,r,s_oStage);m.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e=m.getX()-r.width-10,g=r.height/2+10,w=new CToggle(e,g,s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive),w.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);
var r=window.document,x=r.documentElement;B=x.requestFullscreen||x.mozRequestFullScreen||x.webkitRequestFullScreen||x.msRequestFullscreen;J=r.exitFullscreen||r.mozCancelFullScreen||r.webkitExitFullscreen||r.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(B=!1);B&&!1===inIframe()&&(r=s_oSpriteLibrary.getSprite("but_fullscreen"),b=null===w?m.getX()-r.width/2-10:e-r.width/2-10,d=r.height/2+10,H=new CToggle(b,d,r,s_bFullscreen,!0),H.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));r=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));
r.x=290;r.y=6;s_oStage.addChild(r);r=s_oSpriteLibrary.getSprite("gui_bg");x=createBitmap(r);x.y=CANVAS_HEIGHT-r.height;s_oStage.addChild(x);r=s_oSpriteLibrary.getSprite("but_clear");h=new CGfxButton(830,CANVAS_HEIGHT-r.height/2,r,s_oStage);h.addEventListener(ON_MOUSE_UP,this._onButClearRelease,this);r=s_oSpriteLibrary.getSprite("but_rebet");l=new CGfxButton(890,CANVAS_HEIGHT-r.height/2,r,s_oStage);l.disable();l.addEventListener(ON_MOUSE_UP,this._onButRebetRelease,this);r=s_oSpriteLibrary.getSprite("but_generic");
v=new CTextButton(1012,CANVAS_HEIGHT-r.height/2,r,TEXT_DEAL,FONT_GAME_1,"#ffffff",30,s_oStage);v.addEventListener(ON_MOUSE_UP,this._onButDealRelease,this);r=s_oSpriteLibrary.getSprite("but_generic");p=new CTextButton(1196,CANVAS_HEIGHT-r.height/2,r,TEXT_RAISE,FONT_GAME_1,"#ffffff",30,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onButRaiseRelease,this);r=s_oSpriteLibrary.getSprite("but_generic");A=new CTextButton(1380,CANVAS_HEIGHT-r.height/2,r,TEXT_FOLD,FONT_GAME_1,"#ffffff",30,s_oStage);A.addEventListener(ON_MOUSE_UP,
this._onButFoldRelease,this);POS_BET[BET_ANTE]={x:CANVAS_WIDTH/2-100,y:440};POS_BET[BET_RAISE]={x:CANVAS_WIDTH/2+100,y:440};u=new CGfxButton(POS_BET[BET_ANTE].x,POS_BET[BET_ANTE].y,s_oSpriteLibrary.getSprite("bet_ante"),s_oStage);u.addEventListener(ON_MOUSE_UP,this._onButAnteRelease,this);var x=s_oSpriteLibrary.getSprite("bet_raise"),y=createBitmap(x);y.x=POS_BET[BET_RAISE].x;y.y=POS_BET[BET_RAISE].y;y.regX=x.width/2;y.regY=x.height/2;s_oStage.addChild(y);E=new createjs.Text("","24px "+FONT_GAME_2,
"#ffde00");E.x=412;E.y=16;E.lineWidth=150;E.textAlign="left";E.lineHeight=20;s_oStage.addChild(E);D=new createjs.Text("","19px "+FONT_GAME_2,"#ffde00");D.x=412;D.y=66;E.lineWidth=180;D.textAlign="left";D.lineHeight=18;s_oStage.addChild(D);z=new createjs.Text("","21px "+FONT_GAME_1,"#fff");z.x=CANVAS_WIDTH/2;z.y=290;z.textAlign="center";s_oStage.addChild(z);F=new createjs.Text("","21px "+FONT_GAME_1,"#fff");F.x=CANVAS_WIDTH/2;F.y=650;F.textAlign="center";s_oStage.addChild(F);x=new createjs.Text(TEXT_MONEY+
":","30px "+FONT_GAME_2,"#ffde00");x.x=320;x.y=CANVAS_HEIGHT-84;x.textAlign="left";s_oStage.addChild(x);G=new createjs.Text(TEXT_CURRENCY+a.toFixed(3),"30px "+FONT_GAME_2,"#ffde00");G.x=410;G.y=CANVAS_HEIGHT-84;G.textAlign="left";s_oStage.addChild(G);a=[{x:337,y:CANVAS_HEIGHT-24},{x:417,y:CANVAS_HEIGHT-24},{x:497,y:CANVAS_HEIGHT-24},{x:577,y:CANVAS_HEIGHT-24},{x:657,y:CANVAS_HEIGHT-24},{x:737,y:CANVAS_HEIGHT-24}];n=[];x=s_oGameSettings.getFichesValues();for(y=0;y<NUM_FICHES;y++)r=s_oSpriteLibrary.getSprite("fiche_"+
y),n[y]=new CGfxButton(a[y].x,a[y].y,r,s_oStage),n[y].addEventListenerWithParams(ON_MOUSE_UP,this._onFicheClicked,this,[x[y],y]);a=s_oSpriteLibrary.getSprite("fiche_highlight");C=createBitmap(a);C.regX=a.width/2;C.regY=a.height/2;C.x=n[0].getX();C.y=n[0].getY();s_oStage.addChild(C);k=0;FICHE_WIDTH=r.width;K=new CAnimText(CANVAS_WIDTH,CANVAS_HEIGHT,s_oStage);I=new CPaytablePanel(CANVAS_WIDTH-303,450,s_oStage);this.disableButtons();this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){m.unload();
m=null;!1===DISABLE_SOUND_MOBILE&&(w.unload(),w=null);B&&!1===inIframe()&&H.unload();h.unload();v.unload();l.unload();s_oInterface=null};this.refreshButtonPos=function(a,h){m.setPosition(c-a,h+f);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||w.setPosition(e-a,h+g);B&&!1===inIframe()&&H.setPosition(b-a,d+h);I.refreshButtonPos(a,h)};this.reset=function(){this.disableButtons()};this.enableBetFiches=function(a){for(var c=0;c<NUM_FICHES;c++)n[c].enable();h.enable();u.enable();a&&l.enable()};this.disableBetFiches=
function(){for(var a=0;a<NUM_FICHES;a++)n[a].disable();h.disable();l.disable();u.disable()};this.disableButtons=function(){v.disable();A.disable();p.disable()};this.enable=function(a,c,b){a?v.enable():v.disable();c?p.enable():p.disable();b?A.enable():A.disable()};this.refreshCredit=function(a){G.text=TEXT_CURRENCY+a.toFixed(3)};this.refreshCardValue=function(a,c){z.text=""+a;F.text=""+c};this.displayMsg=function(a,c){E.text=a;D.text=c};this.clearCardValueText=function(){z.text="";F.text="";K.hide()};
this._onFicheClicked=function(a){C.x=n[a[1]].getX();C.y=n[a[1]].getY();k=a[1]};this.showResultText=function(a){K.show({x:-200,y:CANVAS_HEIGHT/2+160},{x:CANVAS_WIDTH/2-450,y:CANVAS_HEIGHT/2+160},a)};this.showHandValue=function(a,c){z.text=TEXT_EVALUATOR[a];F.text=TEXT_EVALUATOR[c]};this._onButClearRelease=function(){s_oGame.clearBets()};this._onButRebetRelease=function(){l.disable();s_oGame.onRebet()};this._onButAnteRelease=function(){s_oGame.setBet(BET_ANTE,k)};this._onButDealRelease=function(){this.disableBetFiches();
this.disableButtons();s_oGame.onDeal()};this._onButRaiseRelease=function(){this.disableBetFiches();this.disableButtons();s_oGame.onRaise()};this._onButFoldRelease=function(){this.disableBetFiches();this.disableButtons();s_oGame.onFold()};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._onFullscreenRelease=function(){s_bFullscreen?(J.call(window.document),s_bFullscreen=!1):(B.call(window.document.documentElement),s_bFullscreen=
!0);sizeHandler()};this.getFicheSelected=function(){return k};this.isResultPanelvisible=function(){return K.isVisible()};s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CTweenController(){this.tweenValue=function(a,b,d){return a+d*(b-a)};this.easeLinear=function(a,b,d,c){return d*a/c+b};this.easeInCubic=function(a,b,d,c){c=(a/=c)*a*a;return b+d*c};this.easeBackInQuart=function(a,b,d,c){c=(a/=c)*a;return b+d*(2*c*c+2*c*a+-3*c)};this.easeInBack=function(a,b,d,c){return d*(a/=c)*a*(2.70158*a-1.70158)+b};this.easeOutCubic=function(a,b,d,c){return d*((a=a/c-1)*a*a+1)+b}}
function CSeat(){var a,b,d,c,f,e,g,k,n,m;this._init=function(){k=new createjs.Container;k.x=CANVAS_WIDTH/2-160;k.y=586;s_oStage.addChild(k);m=[];for(var c=0;2>c;c++)m[c]=new CFichesController;b=a=f=0;this.reset();n=new CVector2;n.set(0,0);g=new CVector2(n.getX(),n.getY())};this.unload=function(){s_oStage.removeChild(k)};this.addEventListener=function(a,c,b){};this.reset=function(){for(var a=c=0;a<m.length;a++)m[a].reset();e=[];for(a=0;3>a;a++)e[a]=[]};this.clearBet=function(){b=a=0;e=[];for(var c=
0;c<m.length;c++)m[c].reset(),e[c]=[]};this.resetBet=function(){b=a=0};this.setCredit=function(a){f=a};this.increaseCredit=function(a){f+=a};this.betAnte=function(c){a+=c;m[0].createFichesPile(a,POS_BET[0].x,POS_BET[0].y)};this.betRaise=function(){b=2*a;m[1].createFichesPile(b,POS_BET[1].x,POS_BET[1].y)};this.setPrevBet=function(){d=a};this.decreaseCredit=function(a){f-=a};this.refreshFiches=function(a,c,b,d,f){e[f].push({value:a,index:c});m[f].refreshFiches(e[f],b,d)};this.initMovement=function(a,
c,b){m[a].initMovement(c,b)};this.newCardDealed=function(){c++};this.rebet=function(){b=0;a=d;this.decreaseCredit(d);m[BET_ANTE].createFichesPile(d,POS_BET[BET_ANTE].x,POS_BET[BET_ANTE].y);return d};this.checkIfRebetIsPossible=function(){for(var a=0,c=0;c<m.length;c++)var b=parseFloat(m[c].getPrevBet().toFixed(2)),a=a+b;return a>f?!1:!0};this.updateFichesController=function(){for(var a=0;a<m.length;a++)m[a].update()};this.getAttachCardOffset=function(){g.set(k.x+n.getX()+(CARD_WIDTH+14)*c,k.y+n.getY());
return g};this.getBetAnte=function(){return a};this.getBetRaise=function(){return b};this.getCredit=function(){return f};this.getCardOffset=function(){return n};this.getPotentialWin=function(a){return(void 0)[a]};this.getStartingBet=function(){for(var a=0,c=0;c<m.length;c++)a+=m[c].getValue();return a};this._init()}
function CFichesController(){var a,b,d,c,f,e,g,k,n,m;this._init=function(){k=new createjs.Container;s_oStage.addChild(k);f=new CVector2;f.set(k.x,k.y);n=new createjs.Container;s_oStage.addChild(n);m=new createjs.Text("","28px "+FONT_GAME_1,"#fff");m.textAlign="center";n.addChild(m);d=c=b=0;a=!1};this.addEventListener=function(a,c,b){};this.reset=function(){a=!1;d=0;k.removeAllChildren();k.x=f.getX();k.y=f.getY();m.text=""};this.setPrevValue=function(a){c=a};this.refreshFiches=function(a,c,b){a=a.sortOn("value",
"index");for(var f=c,e=b+10,g=d=0,h=0;h<a.length;h++){var l=s_oSpriteLibrary.getSprite("fiche_"+a[h].index),l=createBitmap(l);l.scaleX=.7;l.scaleY=.7;k.addChild(l);l.x=f-12;l.y=e;e-=5;g++;9<g&&(g=0,f+=FICHE_WIDTH,e=b);d+=a[h].value}playSound("chip",1,0);m.x=c;m.y=b+35;m.text=d.toFixed(2)+TEXT_CURRENCY};this.createFichesPile=function(a,c,b){this.reset();var d=s_oGameSettings.getFichesValues(),f=[];do{for(var e=d[d.length-1],g=d.length-1;e>a;)g--,e=d[g];for(var g=Math.floor(a/e),k=0;k<g;k++)f.push({value:e,
index:s_oGameSettings.getIndexForFiches(e)});e=Math.floor(a/e)===a/e?0:a%e;a=e.toFixed(2)}while(0<e);this.refreshFiches(f,c,b)};this.initMovement=function(b,f){c=d;e=new CVector2(k.x,k.y);g=new CVector2(b,f);m.text="";a=!0};this.getValue=function(){return d};this.getPrevBet=function(){return c};this.update=function(){if(a)if(b+=s_iTimeElaps,b>TIME_FICHES_MOV)b=0,a=!1;else{var c=easeInOutCubic(b,0,1,TIME_FICHES_MOV),d=new CVector2,d=tweenVectors(e,g,c,d);k.x=d.getX();k.y=d.getY()}};this._init()}
function CVector2(a,b){var d,c;this._init=function(a,b){d=a;c=b};this.add=function(a,b){d+=a;c+=b};this.addV=function(a){d+=a.getX();c+=a.getY()};this.scalarDivision=function(a){d/=a;c/=a};this.subV=function(a){d-=a.getX();c-=a.getY()};this.scalarProduct=function(a){d*=a;c*=a};this.invert=function(){d*=-1;c*=-1};this.dotProduct=function(a){return d*a.getX()+c*a.getY()};this.set=function(a,b){d=a;c=b};this.setV=function(a){d=a.getX();c=a.getY()};this.length=function(){return Math.sqrt(d*d+c*c)};this.length2=
function(){return d*d+c*c};this.normalize=function(){var a=this.length();0<a&&(d/=a,c/=a)};this.getNormalize=function(a){this.length();a.set(d,c);a.normalize()};this.rot90CCW=function(){var a=d;d=-c;c=a};this.rot90CW=function(){var a=d;d=c;c=-a};this.getRotCCW=function(a){a.set(d,c);a.rot90CCW()};this.getRotCW=function(a){a.set(d,c);a.rot90CW()};this.ceil=function(){d=Math.ceil(d);c=Math.ceil(c)};this.round=function(){d=Math.round(d);c=Math.round(c)};this.toString=function(){return"Vector2: "+d+", "+
c};this.print=function(){trace("Vector2: "+d+", "+c+"")};this.getX=function(){return d};this.getY=function(){return c};this._init(a,b)}
function CGameSettings(){var a,b,d;this._init=function(){var c=-1;a=[];for(var b=0;52>b;b++){var e=(b+1)%13;1===e?(e=14,c++):0===e&&(e=13);a.push({fotogram:b,rank:e,suit:c})}d=[.1,1,5,10,25,100]};this.getFichesValues=function(){return d};this.getFichesValueAt=function(a){return d[a]};this.getIndexForFiches=function(a){for(var c=0,b=0;b<d.length;b++)d[b]===a&&(c=b);return c};this.generateFichesPile=function(a){var c=[],b,g=d.length-1,k=d[g];do{b=a%k;b=CMath.roundDecimal(b,1);a=Math.floor(a/k);for(var n=
0;n<a;n++)c.push(k);g--;k=d[g];a=b}while(0<b&&-1<g);return c};this.timeToString=function(a){a=Math.round(a/1E3);var c=Math.floor(a/60);a-=60*c;var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a};this.getShuffledCardDeck=function(){for(var c=[],d=0;d<a.length;d++)c[d]=a[d];for(b=[];0<c.length;)b.push(c.splice(Math.round(Math.random()*(c.length-1)),1)[0]);return b};this.getCardDeck=function(){return a};this._init()}
var TYPE_LINEAR=0,TYPE_OUT_CUBIC=1,TYPE_IN_CUBIC=2,TYPE_OUT_BACK=3,TYPE_IN_BACK=4;function ease(a,b,d,c,f,e){var g;switch(a){case TYPE_LINEAR:g=easeLinear(b,d,c,f,e);break;case TYPE_IN_CUBIC:g=easeInCubic(b,d,c,f,e);break;case TYPE_OUT_CUBIC:g=easeOutCubic(b,d,c,f,e);break;case TYPE_IN_BACK:g=easeInBack(b,d,c,f,e);break;case TYPE_OUT_BACK:g=easeInBack(b,d,c,f,e)}return g}
function easeOutBounce(a,b,d,c){return(a/=c)<1/2.75?7.5625*d*a*a+b:a<2/2.75?d*(7.5625*(a-=1.5/2.75)*a+.75)+b:a<2.5/2.75?d*(7.5625*(a-=2.25/2.75)*a+.9375)+b:d*(7.5625*(a-=2.625/2.75)*a+.984375)+b}function easeInBounce(a,b,d,c){return d-easeOutBounce(c-a,0,d,c)+b}function easeInOutBounce(a,b,d,c){return a<c/2?.5*easeInBounce(2*a,0,d,c)+b:.5*easeOutBounce(2*a-c,0,d,c)+.5*d+b}function easeInCirc(a,b,d,c){return-d*(Math.sqrt(1-(a/=c)*a)-1)+b}
function easeOutCirc(a,b,d,c){return d*Math.sqrt(1-(a=a/c-1)*a)+b}function easeInOutCirc(a,b,d,c){return 1>(a/=c/2)?-d/2*(Math.sqrt(1-a*a)-1)+b:d/2*(Math.sqrt(1-(a-=2)*a)+1)+b}function easeInCubic(a,b,d,c,f){return d*(a/=c)*a*a+b}function easeOutCubic(a,b,d,c,f){return d*((a=a/c-1)*a*a+1)+b}function easeInOutCubic(a,b,d,c,f){return 1>(a/=c/2)?d/2*a*a*a+b:d/2*((a-=2)*a*a+2)+b}
function easeInElastic(a,b,d,c,f,e,g){if(0==a)return b;if(1==(a/=c))return b+d;g||(g=.3*c);!e||e<Math.abs(d)?(e=d,f=g/4):f=g/(2*Math.PI)*Math.asin(d/e);return-(e*Math.pow(2,10*--a)*Math.sin(2*(a*c-f)*Math.PI/g))+b}function easeOutElastic(a,b,d,c,f,e,g){if(0==a)return b;if(1==(a/=c))return b+d;g||(g=.3*c);!e||e<Math.abs(d)?(e=d,f=g/4):f=g/(2*Math.PI)*Math.asin(d/e);return e*Math.pow(2,-10*a)*Math.sin(2*(a*c-f)*Math.PI/g)+d+b}
function easeInOutElastic(a,b,d,c,f,e,g){if(0==a)return b;if(1==(a/=c))return b+d;g||(g=.3*c);!e||e<Math.abs(d)?(e=d,f=g/4):f=g/(2*Math.PI)*Math.asin(d/e);return 1>a?-.5*e*Math.pow(2,10*--a)*Math.sin(2*(a*c-f)*Math.PI/g)+b:e*Math.pow(2,-10*--a)*Math.sin(2*(a*c-f)*Math.PI/g)*.5+d+b}function easeInExpo(a,b,d,c){return 0==a?b:d*Math.pow(2,10*(a/c-1))+b}function easeOutExpo(a,b,d,c){return a==c?b+d:d*(-Math.pow(2,-10*a/c)+1)+b}
function easeInOutExpo(a,b,d,c){return 0==a?b:a==c?b+d:1>(a/=c/2)?d/2*Math.pow(2,10*(a-1))+b:d/2*(-Math.pow(2,-10*--a)+2)+b}function easeLinear(a,b,d,c){return d*a/c+b}function easeInQuad(a,b,d,c){return d*(a/=c)*a+b}function easeOutQuad(a,b,d,c){return-d*(a/=c)*(a-2)+b}function easeInOutQuad(a,b,d,c){return 1>(a/=c/2)?d/2*a*a+b:-d/2*(--a*(a-2)-1)+b}function easeInQuart(a,b,d,c){return d*(a/=c)*a*a*a+b}function easeOutQuart(a,b,d,c){return-d*((a=a/c-1)*a*a*a-1)+b}
function easeInOutQuart(a,b,d,c){return 1>(a/=c/2)?d/2*a*a*a*a+b:-d/2*((a-=2)*a*a*a-2)+b}function easeInQuint(a,b,d,c){return d*(a/=c)*a*a*a*a+b}function easeOutQuint(a,b,d,c){return d*((a=a/c-1)*a*a*a*a+1)+b}function easeInOutQuint(a,b,d,c){return 1>(a/=c/2)?d/2*a*a*a*a*a+b:d/2*((a-=2)*a*a*a*a+2)+b}function easeInSine(a,b,d,c){return-d*Math.cos(a/c*(Math.PI/2))+d+b}function easeOutSine(a,b,d,c){return d*Math.sin(a/c*(Math.PI/2))+b}
function easeInOutSine(a,b,d,c){return-d/2*(Math.cos(Math.PI*a/c)-1)+b}function easeInBack(a,b,d,c){return d*(a/=c)*a*(2.70158*a-1.70158)+b}function easeOutBack(a,b,d,c){return d*((a=a/c-1)*a*(2.70158*a+1.70158)+1)+b}
function CCard(a,b,d){var c,f,e=-1,g,k,n,m,h,l,u,v,p,A;this._init=function(a,c,b){A=b;b={images:[s_oSpriteLibrary.getSprite("card_spritesheet")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_1_1:[0],card_1_2:[1],card_1_3:[2],card_1_4:[3],card_1_5:[4],card_1_6:[5],card_1_7:[6],card_1_8:[7],card_1_9:[8],card_1_10:[9],card_1_J:[10],card_1_Q:[11],card_1_K:[12],card_2_1:[13],card_2_2:[14],card_2_3:[15],card_2_4:[16],card_2_5:[17],card_2_6:[18],card_2_7:[19],
card_2_8:[20],card_2_9:[21],card_2_10:[22],card_2_J:[23],card_2_Q:[24],card_2_K:[25],card_3_1:[26],card_3_2:[27],card_3_3:[28],card_3_4:[29],card_3_5:[30],card_3_6:[31],card_3_7:[32],card_3_8:[33],card_3_9:[34],card_3_10:[35],card_3_J:[36],card_3_Q:[37],card_3_K:[38],card_4_1:[39],card_4_2:[40],card_4_3:[41],card_4_4:[42],card_4_5:[43],card_4_6:[44],card_4_7:[45],card_4_8:[46],card_4_9:[47],card_4_10:[48],card_4_J:[49],card_4_Q:[50],card_4_K:[51],back:[52]}};b=new createjs.SpriteSheet(b);p=createSprite(b,
"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);p.x=a;p.y=c;p.rotation=120;p.stop();A.addChild(p);u=[];v=[]};this.unload=function(){l=h=null;A.removeChild(p)};this.addEventListener=function(a,c,b){u[a]=c;v[a]=b};this.setInfo=function(a,b,d,p,u,v){f=!1;m=0;g=d;k=p;h=a;l=b;n=v;c=u;e=STATE_CARD_DEALING};this.initRemoving=function(a){h=new CVector2(p.x,p.y);l=a;m=0;e=STATE_CARD_REMOVING};this.setValue=function(){p.gotoAndStop(g);var a=this;createjs.Tween.get(p).to({scaleX:1},100).call(function(){a.cardShown()})};
this.showCard=function(){var a=this;createjs.Tween.get(p).to({scaleX:.1},100).call(function(){a.setValue()})};this.hideCard=function(){var a=this;createjs.Tween.get(p).to({scaleX:.1},100).call(function(){a.setBack()})};this.setBack=function(){p.gotoAndStop("back");var a=this;createjs.Tween.get(p).to({scaleX:1},100).call(function(){a.cardHidden()})};this.cardShown=function(){u[ON_CARD_SHOWN]&&u[ON_CARD_SHOWN].call(v[ON_CARD_SHOWN])};this.cardHidden=function(){f=!0};this.getValue=function(){return k};
this.getFotogram=function(){return g};this._updateDealing=function(){m+=s_iTimeElaps;if(m>TIME_CARD_DEALING)e=-1,m=0,p.x=l.getX(),p.y=l.getY(),p.rotation=360,u[ON_CARD_ANIMATION_ENDING]&&u[ON_CARD_ANIMATION_ENDING].call(v[ON_CARD_ANIMATION_ENDING],this,c,n);else{this.visible=!0;var a=easeInOutCubic(m,0,1,TIME_CARD_DEALING),b=new CVector2,b=tweenVectors(h,l,a,b);p.x=b.getX();p.y=b.getY();p.rotation=120+24E3*a/100}};this._updateRemoving=function(){m+=s_iTimeElaps;if(m>TIME_CARD_REMOVE)m=0,f=!1,e=-1,
this.unload();else{var a=easeInOutCubic(m,0,1,TIME_CARD_REMOVE),b=new CVector2,b=tweenVectors(h,l,a,b);p.x=b.getX();p.y=b.getY();p.rotation=4500*a/100}};this.update=function(){switch(e){case STATE_CARD_DEALING:this._updateDealing();break;case STATE_CARD_REMOVING:!0===f&&this._updateRemoving()}};s_oCard=this;this._init(a,b,d)}var s_oCard;
function CGameOver(){var a,b,d,c;this._init=function(){c=new createjs.Container;s_oStage.addChild(c);c.on("click",function(){});var f=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));c.addChild(f);a=new createjs.Text(TEXT_NO_MONEY,"32px "+FONT_GAME_1,"#fff");a.textAlign="center";a.x=CANVAS_WIDTH/2;a.y=290;a.lineWidth=300;a.shadow=new createjs.Shadow("#000000",2,2,2);c.addChild(a);b=new CTextButton(CANVAS_WIDTH/2-100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_RECHARGE,FONT_GAME_1,"#fff",
14,c);b.addEventListener(ON_MOUSE_UP,this._onRecharge,this);d=new CTextButton(CANVAS_WIDTH/2+100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_EXIT,FONT_GAME_1,"#fff",14,c);d.addEventListener(ON_MOUSE_UP,this._onExit,this);this.hide()};this.unload=function(){b.unload();d.unload();c.off("click",function(){})};this.show=function(){c.visible=!0;$(s_oMain).trigger("end_session")};this.hide=function(){c.visible=!1};this._onRecharge=function(){$(s_oMain).trigger("recharge")};this._onExit=function(){s_oGame.onExit()};
this._init()}
function CMsgBox(){var a,b,d,c;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));d=new createjs.Text("","34px "+FONT_GAME_1,"#000");d.x=CANVAS_WIDTH/2+2;d.y=CANVAS_HEIGHT/2-28;d.textAlign="center";d.lineWidth=400;d.textBaseline="middle";b=new createjs.Text("","34px "+FONT_GAME_1,"#ffffff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2-30;b.textAlign="center";b.lineWidth=400;b.textBaseline="middle";c=new createjs.Container;c.alpha=0;c.visible=!1;c.addChild(a,d,b);s_oStage.addChild(c)};this.unload=
function(){c.off("mousedown",this._onExit)};this._initListener=function(){c.on("mousedown",this._onExit)};this.show=function(a){d.text=a;b.text=a;c.visible=!0;var e=this;createjs.Tween.get(c).to({alpha:1},500).call(function(){e._initListener()});setTimeout(function(){e._onExit()},3E3)};this._onExit=function(){c.visible&&(c.off("mousedown"),c.visible=!1)};this._init();return this}
function CHandEvaluator(){var a,b,d;this.evaluate=function(c){b=[];a=[];for(var f=0;f<c.length;f++)b[f]={rank:c[f].rank,suit:c[f].suit},a[f]={rank:c[f].rank,suit:c[f].suit};b.sort(this.compareRank);a.sort(this.compareRank);d=[0,1,2,3,4];return{ret:this.rankHand(),sort_hand:a}};this.rankHand=function(){return this._checkForRoyalFlush()?ROYAL_FLUSH:this._checkForStraightFlush()?STRAIGHT_FLUSH:this._checkForFourOfAKind()?FOUR_OF_A_KIND:this._checkForFullHouse()?FULL_HOUSE:this._checkForFlush()?FLUSH:
this._checkForStraight()?STRAIGHT:this._checkForThreeOfAKind()?THREE_OF_A_KIND:this._checkForTwoPair()?TWO_PAIR:this._checkForOnePair()?ONE_PAIR:this._checkHighCard()?HIGH_CARD:NO_HAND};this._checkForRoyalFlush=function(){return this._isRoyalStraight()&&this._isFlush()?!0:!1};this._checkForStraightFlush=function(){return this._isStraight()&&this._isFlush()?!0:!1};this._checkForFourOfAKind=function(){return b[0].rank===b[3].rank?(b.splice(4,1),d.splice(4,1),!0):b[1].rank===b[4].rank?(b.splice(0,1),
d.splice(0,1),!0):!1};this._checkForFullHouse=function(){return b[0].rank===b[1].rank&&b[2].rank===b[4].rank||b[0].rank===b[2].rank&&b[3].rank===b[4].rank?!0:!1};this._checkForFlush=function(){return this._isFlush()?!0:!1};this._checkForStraight=function(){return this._isStraight()?!0:!1};this._checkForThreeOfAKind=function(){return b[0].rank===b[1].rank&&b[0].rank===b[2].rank?(b.splice(3,1),b.splice(3,1),d.splice(3,1),d.splice(3,1),!0):b[1].rank===b[2].rank&&b[1].rank===b[3].rank?(b.splice(0,1),
b.splice(3,1),d.splice(0,1),d.splice(3,1),!0):b[2].rank===b[3].rank&&b[2].rank===b[4].rank?(b.splice(0,1),b.splice(0,1),d.splice(0,1),d.splice(0,1),!0):!1};this._checkForTwoPair=function(){return b[0].rank===b[1].rank&&b[2].rank===b[3].rank?(b.splice(4,1),d.splice(4,1),!0):b[1].rank===b[2].rank&&b[3].rank===b[4].rank?(b.splice(0,1),d.splice(0,1),!0):b[0].rank===b[1].rank&&b[3].rank===b[4].rank?(b.splice(2,1),d.splice(2,1),!0):!1};this._checkForOnePair=function(){for(var a=0;4>a;a++)if(b[a].rank===
b[a+1].rank){var f=b[a],e=b[a+1];b=[];b.push(f);b.push(e);d=[a,a+1];return!0}return!1};this._checkHighCard=function(){for(var a=!1,d=!1,e=0;5>e;e++)b[e].rank===CARD_ACE&&(a=!0),b[e].rank===CARD_KING&&(d=!0);return a&&d?!0:!1};this._isFlush=function(){return b[0].suit===b[1].suit&&b[0].suit===b[2].suit&&b[0].suit===b[3].suit&&b[0].suit===b[4].suit?!0:!1};this._isRoyalStraight=function(){return b[0].rank===CARD_TEN&&b[1].rank===CARD_JACK&&b[2].rank===CARD_QUEEN&&b[3].rank===CARD_KING&&b[4].rank===CARD_ACE?
!0:!1};this._isStraight=function(){var a=b[0].rank+1===b[1].rank&&b[1].rank+1===b[2].rank&&b[2].rank+1===b[3].rank;return a&&b[0].rank===CARD_TWO&&b[4].rank===CARD_ACE?!0:a&&b[3].rank+1===b[4].rank?!0:!1};this.compareRank=function(a,b){return a.rank<b.rank?-1:a.rank>b.rank?1:0};this.getWinnerComparingHands=function(a,b,d,g){if(d===g)switch(d){case STRAIGHT_FLUSH:return a[0].suit>b[0].suit?"dealer":a[0].suit<b[0].suit?"player":"standoff";case FOUR_OF_A_KIND:return a[1].rank>b[1].rank?"player":a[1].rank<
b[1].rank?"dealer":"standoff";case FULL_HOUSE:return a[4].rank>b[4].rank?"player":a[4].rank<b[4].rank?"dealer":"standoff";case FLUSH:return a[0].suit>b[0].suit?"dealer":a[0].suit<b[0].suit?"player":"standoff";case STRAIGHT:return a[4].rank>b[4].rank?"player":a[4].rank<b[4].rank?"dealer":"standoff";case THREE_OF_A_KIND:return a[2].rank>b[2].rank?"player":a[2].rank<b[2].rank?"dealer":"standoff";case TWO_PAIR:d=0;for(g=a.length-1;0<g;g--)if(a[g].rank===a[g-1].rank){d=a[g].rank;break}a=0;for(g=b.length-
1;0<g;g--)if(b[g].rank===b[g-1].rank){a=b[g].rank;break}return d>a?"player":d<a?"dealer":"standoff";case ONE_PAIR:for(g=d=0;g<a.length-1;g++)if(a[g].rank===a[g+1].rank){d=a[g].rank;break}for(g=a=0;g<b.length-1;g++)if(b[g].rank===b[g+1].rank){a=b[g].rank;break}return d>a?"player":d<a?"dealer":"standoff";default:return"standoff"}else return d>g?"dealer":"player"}}
function CAnimText(a,b,d){var c,f,e,g;this._init=function(a,b){e=new createjs.Container;e.visible=!1;e.x=a;e.y=b;g.addChild(e);var c=s_oSpriteLibrary.getSprite("win_bg"),d=createBitmap(c);e.addChild(d);f=new createjs.Text("","28px "+FONT_GAME_1,"#fff");f.x=c.width/2;f.y=0;f.alphabetic="middle";f.textAlign="center";f.lineWidth=c.width;e.addChild(f)};this.show=function(a,b,d){c=a;f.text=d;e.x=a.x;e.y=a.y;e.visible=!0;createjs.Tween.get(e).to({x:b.x,y:b.y},1E3,createjs.Ease.elasticOut)};this.hide=function(){e.visible=
!1;e.x=c.x;e.y=c.y};this.isVisible=function(){return e.visible};g=d;this._init(a,b)}
function CPaytablePanel(a,b,d){var c,f,e,g,k,n;this._init=function(a,b){c=a;f=b;k=new createjs.Container;k.x=c;k.y=f;n.addChild(k);var d=s_oSpriteLibrary.getSprite("paytable_bg"),h=createBitmap(d);k.addChild(h);for(var m=h="",p=0;p<PAYOUT_MULT.length;p++)h+=TEXT_EVALUATOR[p]+"\n",m+=PAYOUT_MULT[p]+":1\n";e=new createjs.Text(h,"20px "+FONT_GAME_1,"#ffde00");e.x=10;e.y=10;e.textAlign="left";e.lineHeight=20;k.addChild(e);g=new createjs.Text(m,"20px "+FONT_GAME_1,"#ffde00");g.x=d.width-10;g.y=10;g.textAlign=
"right";g.lineHeight=20;k.addChild(g)};this.refreshButtonPos=function(a,b){k.x=c-a};n=d;this._init(a,b)}
function CHelpCursor(a,b,d,c){var f,e,g;this._init=function(a,b,d){f=a;e=createBitmap(d);e.visible=!1;e.x=a;e.y=b;c.addChild(e)};this.show=function(a){0>a&&(e.scaleX*=-1);this._move(a,f+30*a,600);e.visible=!0};this.hide=function(){createjs.Tween.removeTweens(e);e.x=f;e.visible=!1};this._move=function(a,b,c){var d;d=0<a?createjs.Ease.cubicIn:createjs.Ease.cubicOut;createjs.Tween.get(e).to({x:b},c,d).call(function(){a*=-1;g._move(a,b+15*a,400)})};this.isVisible=function(){return e.visible};g=this;this._init(a,
b,d)};
