var s_iScaleFactor=1,s_iOffsetX,s_iOffsetY,s_bIsIphone=!1;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var c=a.toLowerCase(),b=window.document,e=b.documentElement;if(void 0===window["inner"+a])a=e["client"+a];else if(window["inner"+a]!=e["client"+a]){var h=b.createElement("body");h.id="vpw-test-b";h.style.cssText="overflow:scroll";var g=b.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+c+":"+e["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";h.appendChild(g);e.insertBefore(h,b.head);
a=7==g["offset"+a]?e["client"+a]:window["inner"+a];e.removeChild(h)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),e=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b;s_bMobile&&!s_bIsIphone?($("#canvas").css("width",e+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=e,s_oStage.canvas.height=b,s_oStage.scaleX=s_oStage.scaleY=Math.min(e/CANVAS_WIDTH,b/CANVAS_HEIGHT));var h;b<a?(h=a-b,b+=h,e+=CANVAS_WIDTH/
CANVAS_HEIGHT*h):e<c&&(h=c-e,e+=h,b+=CANVAS_HEIGHT/CANVAS_WIDTH*h);h=a/2-b/2;var g=c/2-e/2,f=CANVAS_WIDTH/e;if(g*f<-EDGEBOARD_X||h*f<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*EDGEBOARD_X)),e=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,h=(a-b)/2,g=(c-e)/2,f=CANVAS_WIDTH/e;s_iOffsetX=-1*g*f;s_iOffsetY=-1*h*f;0<=h&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);
null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",e+"px");$("#canvas").css("height",b+"px");0>h?$("#canvas").css("top",h+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",g+"px")}}function playSound(a,c,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:c}):null}function continueSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.play()}
function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}function setVolume(a,c){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=c}function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(c)}function createBitmap(a,c,b){var e=new createjs.Bitmap(a),h=new createjs.Shape;c&&b?h.graphics.beginFill("#fff").drawRect(0,0,c,b):h.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);e.hitArea=h;return e}
function createSprite(a,c,b,e,h,g){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-e,h,g);a.hitArea=c;return a}function pad(a,c,b){a+="";return a.length>=c?a:Array(c-a.length+1).join(b||"0")+a}function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}
function angleBetweenVectors(a,c){var b=Math.acos(dotProductV2(a,c)/(a.length()*c.length()));return 1==isNaN(b)?0:b}function rotateVector2D(a,c){var b=c.getX()*Math.cos(a)+c.getY()*Math.sin(a),e=c.getX()*-Math.sin(a)+c.getY()*Math.cos(a);c.set(b,e)}function dotProductV2(a,c){return a.getX()*c.getX()+a.getY()*c.getY()}function reflectVectorV2(a,c){var b=new CVector2(0,0),e=dotProductV2(a,c);b.set(a.getX()-2*e*c.getX(),a.getY()-2*e*c.getY());return b}function tweenValue(a,c,b){return a+b*(c-a)}
function shuffle(a){for(var c=a.length,b,e;0!==c;)e=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[e],a[e]=b;return a}function bubbleSort(a){var c;do{c=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(c=a[b],a[b]=a[b+1],a[b+1]=c,c=!0)}while(c)}function compare(a,c){return a.index>c.index?-1:a.index<c.index?1:0}function easeLinear(a,c,b,e){return b*a/e+c}function easeInQuad(a,c,b,e){return b*(a/=e)*a+c}function easeInSine(a,c,b,e){return-b*Math.cos(a/e*(Math.PI/2))+b+c}
function easeInCubic(a,c,b,e){return b*(a/=e)*a*a+c}function easeOutCubic(a,c,b,e){return b*((a=a/e-1)*a*a+1)+c}function easeInOutCubic(a,c,b,e){return 1>(a/=e/2)?b/2*a*a*a+c:b/2*((a-=2)*a*a+2)+c}function getTrajectoryPoint(a,c){var b=new createjs.Point,e=(1-a)*(1-a),h=a*a;b.x=e*c.start.x+2*(1-a)*a*c.traj.x+h*c.end.x;b.y=e*c.start.y+2*(1-a)*a*c.traj.y+h*c.end.y;return b}
function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=parseFloat(a-60*c).toFixed(1);var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function radiansToDegree(a){return 180/Math.PI*a}function checkRectCollision(a,c){var b,e;b=getBounds(a,.9);e=getBounds(c,.98);return calculateIntersection(b,e)}
function calculateIntersection(a,c){var b,e,h,g,f,k,d,l;b=a.x+(h=a.width/2);e=a.y+(g=a.height/2);f=c.x+(k=c.width/2);d=c.y+(l=c.height/2);b=Math.abs(b-f)-(h+k);e=Math.abs(e-d)-(g+l);return 0>b&&0>e?(b=Math.min(Math.min(a.width,c.width),-b),e=Math.min(Math.min(a.height,c.height),-e),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:b,height:e,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var e=a.children,h=e.length,g,f;for(f=0;f<h;f++)g=getBounds(e[f],1),g.x<b.x&&(b.x=g.x),g.y<b.y&&(b.y=g.y),g.x+g.width>b.x2&&(b.x2=g.x+g.width),g.y+g.height>b.y2&&(b.y2=g.y+g.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var k,d;a instanceof createjs.Bitmap?
(h=a.sourceRect||a.image,f=h.width*c,k=h.height*c):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(h=a.spriteSheet.getFrame(a.currentFrame),f=h.rect.width,k=h.rect.height,e=h.regX,d=h.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);e=e||0;f=f||0;d=d||0;k=k||0;b.regX=e;b.regY=d;h=a.localToGlobal(0-e,0-d);g=a.localToGlobal(f-e,k-d);f=a.localToGlobal(f-e,0-d);e=a.localToGlobal(0-e,k-d);b.x=Math.min(Math.min(Math.min(h.x,
g.x),f.x),e.x);b.y=Math.min(Math.min(Math.min(h.y,g.y),f.y),e.y);b.width=Math.max(Math.max(Math.max(h.x,g.x),f.x),e.x)-b.x;b.height=Math.max(Math.max(Math.max(h.y,g.y),f.y),e.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var c=a.length,b,e;0<c;)e=Math.floor(Math.random()*c),c--,b=a[c],a[c]=a[e],a[e]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(b){var a={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};b=b||window.event;b.type in a?document.body.className=a[b.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var e=c[b].split("=");if(e[0]==a)return e[1]}}var EASE_LINEAR=0,EASE_CUBIC_IN=1,EASE_QUART_BACKIN=2,EASE_BACKIN=3,EASE_SIN_IN=4,EASE_QUAD_IN=5,EASE_CUBIC_OUT=6,EASE_ELASTIC_OUT=7,EASE_BACKOUT=8,EASE_QUINT_OUT=9,EASE_CUBIC_INOUT=10;
function CTweenController(){this.tweenValue=function(a,c,b){return a+b*(c-a)};this.easeLinear=function(a,c,b,e){return b*a/e+c};this.easeInCubic=function(a,c,b,e){e=(a/=e)*a*a;return c+b*e};this.easeBackInQuart=function(a,c,b,e){e=(a/=e)*a;return c+b*(2*e*e+2*e*a+-3*e)};this.easeInBack=function(a,c,b,e){return b*(a/=e)*a*(2.70158*a-1.70158)+c};this.easeInSine=function(a,c,b,e){return-b*Math.cos(a/e*(Math.PI/2))+b+c};this.easeInQuad=function(a,c,b,e){return b*(a/=e)*a+c};this.easeOutCubic=function(a,
c,b,e){return b*((a=a/e-1)*a*a+1)+c};this.easeOutElastic=function(a,c,b,e){var h;if(0===a)return c;if(1===(a/=e))return c+b;h=.3*e;return b*Math.pow(2,-10*a)*Math.sin(2*(a*e-h/4)*Math.PI/h)+b+c};this.easeOutBack=function(a,c,b,e){return b*((a=a/e-1)*a*(2.70158*a+1.70158)+1)+c};this.easeInOutCubic=function(a,c,b,e){return 1>(a/=e/2)?b/2*a*a*a+c:b/2*((a-=2)*a*a+2)+c};this.easeOutQuint=function(a,c,b,e){return b*((a=a/e-1)*a*a*a*a+1)+c}}
function CRollingTextController(a,c,b,e,h){var g,f,k,d,l,m,n,r,u,p,t,q,w;this._init=function(b,a,d,e,f){u=[];p=[];l=e;this.setUpdateInfo(d);r=f;q=b;w=a};this.unload=function(){clearInterval(n)};this.setUpdateInfo=function(b){k=parseFloat(a.text);d=k+b;g=0;f=Math.round(l/FPS);m=0;var e=this;n=setInterval(function(){e.update()},FPS_TIME)};this.addEventListener=function(b,a,d){u[b]=a;p[b]=d};this.addRollingListener=function(b,a,d){u[ON_CONTROLLER_ROLL]=b;p[ON_CONTROLLER_ROLL]=a;t=[];for(b=0;b<d.length;b++)t[b]=
{step:d[b],flag:!1}};this.increaseValue=function(b){m=b};this.getTarget=function(){return q};this.update=function(){g++;if(g>f)g=0,q.text=d.toFixed(0),null!==w&&(w.text=d.toFixed(0)),clearInterval(n),null!==u[ON_CONTROLLER_END]&&u[ON_CONTROLLER_END].call(p[ON_CONTROLLER_END],this),0<m?this.setUpdateInfo(m):u[ON_CONTROLLER_REMOVE].call(p[ON_CONTROLLER_REMOVE],this);else{var b;switch(r){case EASE_BACKIN:b=s_oTweenController.easeInBack(g,0,1,f);break;case EASE_BACKOUT:b=s_oTweenController.easeOutBack(g,
0,1,f);break;case EASE_CUBIC_IN:b=s_oTweenController.easeInCubic(g,0,1,f);break;case EASE_CUBIC_OUT:b=s_oTweenController.easeOutCubic(g,0,1,f);break;case EASE_ELASTIC_OUT:b=s_oTweenController.easeOutElastic(g,0,1,f);break;case EASE_LINEAR:b=s_oTweenController.easeLinear(g,0,1,f);break;case EASE_QUART_BACKIN:b=s_oTweenController.easeBackInQuart(g,0,1,f);break;default:b=s_oTweenController.easeLinear(g,0,1,f)}b=s_oTweenController.tweenValue(k,d,b);for(var a=0;a<t.length;a++)b>t[a].step&&!t[a].flag&&
(t[a].flag=!0,null!==u[ON_CONTROLLER_ROLL]&&u[ON_CONTROLLER_ROLL].call(p[ON_CONTROLLER_ROLL],a));q.text=b.toFixed(0);null!==w&&(w.text=b.toFixed(0))}};this._init(a,c,b,e,h)}
function CVector2(a,c){var b,e;this._init=function(a,c){b=a;e=c};this.add=function(a,c){b+=a;e+=c};this.addV=function(a){b+=a.getX();e+=a.getY()};this.scalarDivision=function(a){b/=a;e/=a};this.subV=function(a){b-=a.getX();e-=a.getY()};this.scalarProduct=function(a){b*=a;e*=a};this.invert=function(){b*=-1;e*=-1};this.dotProduct=function(a){return b*a.getX()+e*a.getY()};this.set=function(a,c){b=a;e=c};this.setV=function(a){b=a.getX();e=a.getY()};this.length=function(){return Math.sqrt(b*b+e*e)};this.length2=
function(){return b*b+e*e};this.normalize=function(){var a=this.length();0<a&&(b/=a,e/=a)};this.getNormalize=function(a){this.length();a.set(b,e);a.normalize()};this.rot90CCW=function(){var a=b;b=-e;e=a};this.rot90CW=function(){var a=b;b=e;e=-a};this.getRotCCW=function(a){a.set(b,e);a.rot90CCW()};this.getRotCW=function(a){a.set(b,e);a.rot90CW()};this.ceil=function(){b=Math.ceil(b);e=Math.ceil(e)};this.round=function(){b=Math.round(b);e=Math.round(e)};this.toString=function(){return"Vector2: "+b+", "+
e};this.print=function(){trace("Vector2: "+b+", "+e+"")};this.getX=function(){return b};this.getY=function(){return e};this._init(a,c)}
function CSpriteLibrary(){var a,c,b,e,h,g;this.init=function(f,k,d){b=c=0;e=f;h=k;g=d;a={}};this.addSprite=function(b,e){a.hasOwnProperty(b)||(a[b]={szPath:e,oSprite:new Image},c++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){h.call(g)};this._onSpriteLoaded=function(){e.call(g);++b==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=640,CANVAS_HEIGHT=1024,EDGEBOARD_X=16,EDGEBOARD_Y=110,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="walibi",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_CONTROLLER_END=8,ON_CONTROLLER_REMOVE=9,ON_CONTROLLER_ROLL=10,LEFT_DIRECTION=0,UP_DIRECTION=1,RIGHT_DIRECTION=2,DOWN_DIRECTION=3,MOVEMENT_STOP=-1,MOVEMENT_RANDOM=0,MOVEMENT_LINEAR=1,MOVEMENT_DISCRETE=2,MOVEMENT_CIRCULAR=
3,STAGE_PER_WORLD=3,STAGE_ANIM_COLOR=["#ec297b","#ec1c24","#c1e401","#f9ec31"],BORDER_LINE_DIM=3,BORDER_WIDTH=600,BORDER_HEIGHT=600,BORDER_HEIGHT_OFFSET=50,HERO_SPEED=[6,8,10],SPAWN_START_TIME=9E3,SPAWN_TIMER=4E4,BOSS_MOVEMENT=[],BOSS_MOVEMENT=[MOVEMENT_LINEAR,MOVEMENT_RANDOM,MOVEMENT_DISCRETE,MOVEMENT_CIRCULAR],SELECTED_SPEED,HERO_LIFE,WIN_QUOTE,VIRUS_SPEED=[],MAX_NUM_VIRUS_MINIONS=[],MINION_SCORE,SCORE_FIRST_STAR,SCORE_SECOND_STAR,SCORE_THIRD_STAR,AD_SHOW_COUNTER;TEXT_GAMEOVER="GAME OVER";
TEXT_SCORE="SCORE";TEXT_TOTAL_SCORE="TOTAL SCORE:";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_DEVELOPED="DEVELOPED BY";TEXT_LINK="www.codethislab.com";TEXT_SELECT_WORLD="SELECT THE WORLD YOU WANT TO PLAY";TEXT_SELECT_STAGE="SELECT THE STAGE";TEXT_VIRUS_TYPE="VIRUS TYPE";TEXT_STAGE="STAGE";TEXT_CONGRATULATION="CONGRATULATIONS!";TEXT_DEFEATED="YOU DEFEATED VIRUS";TEXT_INSTAGE="IN STAGE";TEXT_DEFEATED_ALL="YOU DEFEATED ALL VIRUS!";TEXT_HELP1_MOB="SWIFT ON THE SCREEN TO MOVE YOUR HERO AND WEAVE A LINE";
TEXT_HELP2_MOB="TAP ON THE SCREEN TO STOP HERO MOVEMENT";TEXT_HELP1="USE ARROW KEYS TO MOVE YOUR HERO ALONG THE SIDES OF THE SCREEN";TEXT_HELP2="PRESS AND HOLD THE SPACE BAR TO WEAVE A LINE";TEXT_HELP3="CLAIM THE % OF SCREEN SHOWN IN THE BOX TO PASS THE LEVEL";TEXT_HELP4="WHILE WEAVING, DON'T LET THE VIRUSES CATCHING YOU AND YOUR LINES!";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var a,c,b,e,h,g,f;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();f=new createjs.Container;s_oStage.addChild(f)};this.unload=function(){f.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));f.addChild(k);k=s_oSpriteLibrary.getSprite("progress_bar");e=createBitmap(k);e.x=CANVAS_WIDTH/2-k.width/2;e.y=CANVAS_HEIGHT-170;f.addChild(e);a=k.width;c=k.height;h=new createjs.Shape;h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,1,c);f.addChild(h);e.mask=
h;b=new createjs.Text("","30px Arial","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";f.addChild(b);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;f.addChild(g)};this.refreshLoader=function(f){b.text=f+"%";h.graphics.clear();f=Math.floor(f*a/100);h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,f,c)};this._init()}
function CMain(a){var c,b=0,e=0,h=STATE_LOADING,g,f,k;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;s_oTweenController=new CTweenController;f=new CPreloader;s_oLocalStorage=new CLocalStorage("virus_attack")};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();c=!0};this.soundLoaded=function(){b++;f.refreshLoader(Math.floor(b/e*100));b===e&&(f.unload(),s_oSoundtrack=playSound("soundtrack",1,-1),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&
(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/boss_idle.ogg","boss_idle",8),createjs.Sound.registerSound("./sounds/minion_anim.ogg","minion_anim",8),createjs.Sound.registerSound("./sounds/hero_dead.ogg","hero_dead"),createjs.Sound.registerSound("./sounds/weaving.ogg","weaving"),createjs.Sound.registerSound("./sounds/close_mask.ogg",
"close_mask"),createjs.Sound.registerSound("./sounds/boss_dead.ogg","boss_dead"),createjs.Sound.registerSound("./sounds/virus_dead_0.ogg","virus_dead_0"),createjs.Sound.registerSound("./sounds/virus_dead_1.ogg","virus_dead_1"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/star.ogg",
"star",3)):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/boss_idle.mp3","boss_idle",8),createjs.Sound.registerSound("./sounds/minion_anim.mp3","minion_anim",8),createjs.Sound.registerSound("./sounds/hero_dead.mp3","hero_dead"),createjs.Sound.registerSound("./sounds/weaving.mp3","weaving"),createjs.Sound.registerSound("./sounds/close_mask.mp3","close_mask"),createjs.Sound.registerSound("./sounds/boss_dead.mp3",
"boss_dead"),createjs.Sound.registerSound("./sounds/virus_dead_0.mp3","virus_dead_0"),createjs.Sound.registerSound("./sounds/virus_dead_1.mp3","virus_dead_1"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.mp3","click"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/star.mp3","star",3)),e+=13)};this._loadImages=
function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("keys","./sprites/keys.png");s_oSpriteLibrary.addSprite("space_bar","./sprites/space_bar.png");s_oSpriteLibrary.addSprite("swift_hand","./sprites/swift_hand.png");s_oSpriteLibrary.addSprite("touch_hand",
"./sprites/touch_hand.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_yes_big","./sprites/but_yes_big.png");s_oSpriteLibrary.addSprite("but_exit_big","./sprites/but_exit_big.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("game_over_box","./sprites/game_over_box.png");s_oSpriteLibrary.addSprite("intro_level_box","./sprites/intro_level_box.png");
s_oSpriteLibrary.addSprite("next_level_box","./sprites/next_level_box.png");s_oSpriteLibrary.addSprite("credits_panel","./sprites/credits_panel.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("star","./sprites/star.png");s_oSpriteLibrary.addSprite("but_next","./sprites/but_next.png");s_oSpriteLibrary.addSprite("but_back","./sprites/but_back.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_level",
"./sprites/but_level.png");s_oSpriteLibrary.addSprite("hero","./sprites/hero.png");s_oSpriteLibrary.addSprite("life","./sprites/life.png");s_oSpriteLibrary.addSprite("percentage_box","./sprites/percentage_box.png");s_oSpriteLibrary.addSprite("indicator","./sprites/indicator.png");s_oSpriteLibrary.addSprite("pill","./sprites/pill.png");s_oSpriteLibrary.addSprite("boss0","./sprites/boss0.png");s_oSpriteLibrary.addSprite("boss1","./sprites/boss1.png");s_oSpriteLibrary.addSprite("boss2","./sprites/boss2.png");
s_oSpriteLibrary.addSprite("boss3","./sprites/boss3.png");s_oSpriteLibrary.addSprite("virus0","./sprites/virus0.png");s_oSpriteLibrary.addSprite("virus1","./sprites/virus1.png");s_oSpriteLibrary.addSprite("virus2","./sprites/virus2.png");s_oSpriteLibrary.addSprite("virus3","./sprites/virus3.png");s_oSpriteLibrary.addSprite("frame_cover","./sprites/frame_cover.png");for(var a=0;4>a;a++)s_oSpriteLibrary.addSprite("percentage_fill_"+a,"./sprites/percentage_fill_"+a+".png"),s_oSpriteLibrary.addSprite("image_"+
a,"./sprites/image_"+a+".jpg"),s_oSpriteLibrary.addSprite("cover_"+a,"./sprites/cover_"+a+".jpg");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;f.refreshLoader(Math.floor(b/e*100));b===e&&(f.unload(),s_oSoundtrack=playSound("soundtrack",1,-1),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;h=STATE_MENU};this.gotoLevelMenu=function(){new CLevelMenu;
h=STATE_MENU};this.gotoGame=function(a,b){k=new CGame(g,a,b);h=STATE_GAME};this.gotoHelp=function(){new CHelp;h=STATE_HELP};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==c){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=
s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);h===STATE_GAME&&k.update();s_oStage.update(a)}};s_oMain=this;g=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oCanvas,s_oTweenController,s_oLocalStorage;
function CToggle(a,c,b,e,h){var g,f,k,d;this._init=function(a,b,e,c,h){f=[];k=[];var p=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{state_true:[0],state_false:[1]}});g=c;d=createSprite(p,"state_"+g,e.width/2/2,e.height/2,e.width/2,e.height);d.x=a;d.y=b;d.stop();h.addChild(d);this._initListener()};this.unload=function(){s_bMobile?d.off("mousedown",this.buttonDown):(d.off("mousedown",this.buttonDown),d.off("mouseover",this.buttonOver));
d.off("pressup",this.buttonRelease);h.removeChild(d)};this._initListener=function(){if(s_bMobile)d.on("mousedown",this.buttonDown);else d.on("mousedown",this.buttonDown),d.on("mouseover",this.buttonOver);d.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){f[a]=b;k[a]=d};this.setActive=function(a){g=a;d.gotoAndStop("state_"+g)};this.buttonRelease=function(){d.scaleX=1;d.scaleY=1;playSound("click",1,0);g=!g;d.gotoAndStop("state_"+g);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(k[ON_MOUSE_UP],
g)};this.buttonDown=function(){d.scaleX=.9;d.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.setPosition=function(a,b){d.x=a;d.y=b};this._init(a,c,b,e,h)}
function CGfxButton(a,c,b,e){var h,g,f,k,d,l;this._init=function(a,b,e,c){h=!1;g=1;f=[];k=[];d=createBitmap(e);d.x=a;d.y=b;d.scaleX=d.scaleY=g;d.regX=e.width/2;d.regY=e.height/2;c.addChild(d);this._initListener()};this.unload=function(){s_bMobile?d.off("mousedown",this.buttonDown):(d.off("mousedown",this.buttonDown),d.off("mouseover",this.buttonOver));d.off("pressup",this.buttonRelease);e.removeChild(d)};this.setVisible=function(a){d.visible=a};this.setClickable=function(a){h=!a};this._initListener=
function(){if(s_bMobile)d.on("mousedown",this.buttonDown);else d.on("mousedown",this.buttonDown),d.on("mouseover",this.buttonOver);d.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){f[a]=b;k[a]=d};this.buttonRelease=function(){h||(d.scaleX=g,d.scaleY=g,f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(k[ON_MOUSE_UP]))};this.buttonDown=function(){h||(d.scaleX=.9*g,d.scaleY=.9*g,playSound("click",1,0),f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN]))};this.buttonOver=function(a){s_bMobile||
h||(a.target.cursor="pointer")};this.pulseAnimation=function(){createjs.Tween.get(d).to({scaleX:.9*g,scaleY:.9*g},850,createjs.Ease.quadOut).to({scaleX:g,scaleY:g},650,createjs.Ease.quadIn).call(function(){l.pulseAnimation()})};this.trembleAnimation=function(){createjs.Tween.get(d).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){l.trebleAnimation()})};this.setPosition=function(a,b){d.x=a;d.y=b};
this.setX=function(a){d.x=a};this.setY=function(a){d.y=a};this.getButtonImage=function(){return d};this.getX=function(){return d.x};this.getY=function(){return d.y};l=this;this._init(a,c,b,e);return this}
function CLevelButton(a,c,b,e,h,g){var f,k,d,l,m=[],n,r,u,p=null,t=null,q,w,x;this._init=function(a,b,e,c,g,p){f=!1;k=1;d=[];l=[];n=new createjs.Container;n.x=a;n.y=b;n.scaleX=n.scaleY=k;p.addChild(n);r=new createjs.Container;r.x=a;r.y=b;r.scaleX=n.scaleY=k;p.addChild(r);a=new createjs.Shape;a.graphics.beginFill("black").drawRoundRect(-65,-65,130,130,20);n.addChild(a);q=createBitmap(c);q.regX=c.width/2;q.regY=c.height/2;q.scaleX=q.scaleY=.25;q.compositeOperation="source-in";q.mask=a;n.addChild(q);
c=e.width/2;a=e.height;e=new createjs.SpriteSheet({images:[e],frames:{width:c,height:a,regX:c/2,regY:a/2},animations:{on:[0],off:[1]}});u=createSprite(e,"on",c/2,a/2,c,a);n.addChild(u);this._initListener()};this.unload=function(){s_bMobile?n.off("mousedown",this.buttonDown):(n.off("mousedown",this.buttonDown),n.off("mouseover",this.buttonOver));n.off("pressup",this.buttonRelease);g.removeChild(n)};this.setVisible=function(a){n.visible=a};this.enable=function(){u.gotoAndStop("on");q.image=h;f=!1;null!==
t&&(p.color="#000000",t.color="#c1e401")};this.disable=function(){f=!0;q.image=e;u.gotoAndStop("off");null!==t&&(p.color="#000000",t.color="#8c874e")};this.setClickable=function(a){f=!a};this.addStar=function(a){var d=s_oSpriteLibrary.getSprite("star");w=new CAchievementStars(d,0,-b.height/2+45,r);w.getContainer().scaleX=w.getContainer().scaleY=.3;w.startLitStar(a)};this.addScore=function(a){var d=new createjs.Text(TEXT_SCORE+": "+a,"bold 14px "+PRIMARY_FONT,"#000000");d.y=b.height/2-50;d.textAlign=
"center";d.textBaseline="middle";d.lineWidth=200;d.outline=4;r.addChild(d);a=new createjs.Text(TEXT_SCORE+": "+a,"bold 14px "+PRIMARY_FONT,"#c1e401");a.y=d.y;a.textAlign="center";a.textBaseline="middle";a.lineWidth=200;r.addChild(a)};this.addLevelText=function(a){p=new createjs.Text(a,"bold 80px "+PRIMARY_FONT,"#000000");p.textAlign="center";p.textBaseline="middle";p.lineWidth=200;p.outline=8;n.addChild(p);t=new createjs.Text(a,"bold 80px "+PRIMARY_FONT,"#c1e401");t.textAlign="center";t.textBaseline=
"middle";t.lineWidth=200;n.addChild(t)};this._initListener=function(){if(s_bMobile)n.on("mousedown",this.buttonDown);else n.on("mousedown",this.buttonDown),n.on("mouseover",this.buttonOver);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,e){d[a]=b;l[a]=e};this.addEventListenerWithParams=function(a,b,e,c){d[a]=b;l[a]=e;m=c};this.buttonRelease=function(){f||(n.scaleX=k,n.scaleY=k,d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(l[ON_MOUSE_UP],m))};this.buttonDown=function(){f||(playSound("click",
1,0),n.scaleX=.9*k,n.scaleY=.9*k,d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],m))};this.buttonOver=function(a){s_bMobile||f||(a.target.cursor="pointer")};this.pulseAnimation=function(){createjs.Tween.get(n).to({scaleX:.9*k,scaleY:.9*k},850,createjs.Ease.quadOut).to({scaleX:k,scaleY:k},650,createjs.Ease.quadIn).call(function(){x.pulseAnimation()})};this.trembleAnimation=function(){createjs.Tween.get(n).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},
75,createjs.Ease.quadIn).wait(750).call(function(){x.trebleAnimation()})};this.setPosition=function(a,b){n.x=a;n.y=b};this.setScale=function(a){k=a;n.scaleX=n.scaleY=a};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};x=this;this._init(a,c,b,e,h,g);return this}
function CMenu(){var a,c,b,e,h,g,f,k,d;this._init=function(){h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(h);var l=s_oSpriteLibrary.getSprite("but_play");g=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-240,l,s_oStage);g.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);g.pulseAnimation();l=s_oSpriteLibrary.getSprite("but_info");a=l.height/2+10;c=l.height/2+10;d=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-240,l,s_oStage);d.addEventListener(ON_MOUSE_UP,this._onCreditsBut,
this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-l.height/2-10,e=l.height/2+10,k=new CToggle(b,e,l,s_bAudioActive,s_oStage),k.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(f);createjs.Tween.get(f).to({alpha:0},1E3).call(function(){f.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){g.unload();
g=null;d.unload();f.visible=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null;s_oStage.removeChild(h);s_oMenu=h=null};this.refreshButtonPos=function(f,g){d.setPosition(a+f,g+c);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||k.setPosition(b-f,g+e)};this._onCreditsBut=function(){new CCreditsPanel};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoLevelMenu()};
s_oMenu=this;this._init()}var s_oMenu=null;
function CLevelMenu(){var a,c,b,e,h,g;this._init=function(){h=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(h);var f=new createjs.Text(TEXT_SELECT_WORLD,"bold 34px "+PRIMARY_FONT,"#000000");f.x=CANVAS_WIDTH/2;f.y=200;f.textAlign="center";f.textBaseline="middle";f.lineWidth=500;f.outline=5;s_oStage.addChild(f);var k=new createjs.Text(TEXT_SELECT_WORLD,"bold 34px "+PRIMARY_FONT,"#c1e401");k.x=f.x;k.y=f.y;k.textAlign="center";k.textBaseline="middle";k.lineWidth=500;s_oStage.addChild(k);
b=s_oLocalStorage.getItemJson(LOCALSTORAGE_SCORE);e=[];k=s_oSpriteLibrary.getSprite("but_level");for(f=0;4>f;f++){var d=CANVAS_WIDTH/2-120+f%2*240,l=s_oSpriteLibrary.getSprite("image_"+f),m=s_oSpriteLibrary.getSprite("cover_"+f);e[f]=new CLevelButton(d,400+200*Math.floor(f/2),k,m,l,s_oStage);e[f].addEventListenerWithParams(ON_MOUSE_UP,this._onLevelBut,this,f);e[f].disable()}this._setLevelActive();f=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-f.height/2-10;c=f.height/2+10;g=new CGfxButton(a,
c,f,s_oStage);g.addEventListener(ON_MOUSE_UP,this._onExit,this);for(f=k=0;f<b.length;f++)k+=b[f];f=new createjs.Text(TEXT_TOTAL_SCORE+" "+k,"bold 24px "+PRIMARY_FONT,"#000000");f.x=CANVAS_WIDTH/2;f.y=740;f.textAlign="center";f.textBaseline="middle";f.lineWidth=500;f.outline=5;s_oStage.addChild(f);k=new createjs.Text(TEXT_TOTAL_SCORE+" "+k,"bold 24px "+PRIMARY_FONT,"#c1e401");k.x=f.x;k.y=f.y;k.textAlign="center";k.textBaseline="middle";k.lineWidth=500;s_oStage.addChild(k);this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.refreshButtonPos=function(b,e){g.setPosition(a-b,e+c)};this.unload=function(){for(var a=0;a<e.length;a++)e[a].unload();s_oLevelMenu=null;s_oStage.removeAllChildren()};this._setLevelActive=function(){for(var a=0,c=0;c<b.length;c++)0<b[c]&&(a=c+1);if(a===STAGE_PER_WORLD*e.length)for(c=0;c<e.length;c++)e[c].enable();else{a=Math.floor(a/STAGE_PER_WORLD);for(c=0;c<a+1;c++)e[c].enable();e[a].pulseAnimation()}};this._onLevelBut=function(a){var e=a*STAGE_PER_WORLD;new CStageMenu(a,[b[e],
b[e+1],b[e+2]])};this._onExit=function(){$(s_oMain).trigger("end_session");this.unload();s_oMain.gotoMenu()};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CStageMenu(a,c){var b,e,h,g,f;this._init=function(a,d){h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=0;h.on("mousedown",function(){});s_oStage.addChild(h);(new createjs.Tween.get(h)).to({alpha:.7},500);f=new createjs.Container;s_oStage.addChild(f);var c=s_oSpriteLibrary.getSprite("next_level_box"),m=createBitmap(c);m.regX=c.width/2;m.regY=c.height/2;f.addChild(m);m=new createjs.Text(TEXT_SELECT_STAGE,"bold 34px "+PRIMARY_FONT,"#000000");
m.y=-c.height/2+50;m.textAlign="center";m.textBaseline="middle";m.lineWidth=400;m.outline=5;f.addChild(m);var n=new createjs.Text(TEXT_SELECT_STAGE,"bold 34px "+PRIMARY_FONT,"#c1e401");n.y=m.y;n.textAlign="center";n.textBaseline="middle";n.lineWidth=400;f.addChild(n);f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT+c.height/2;b=f.y;(new createjs.Tween.get(f)).to({y:CANVAS_HEIGHT/2},500,createjs.Ease.quartIn).call(function(){});c=s_oSpriteLibrary.getSprite("but_level");m=s_oSpriteLibrary.getSprite("image_"+a);
n=s_oSpriteLibrary.getSprite("cover_"+a);e=[];for(var r=0;r<STAGE_PER_WORLD;r++){var u=r+1;e[r]=new CLevelButton(-130+130*r,-100,c,n,m,f);e[r].addEventListenerWithParams(ON_MOUSE_UP,this._onStageBut,this,r);e[r].setScale(.6);e[r].addLevelText(u);e[r].disable();e[r].addStar(0)}this._setStageInfo();c=s_oSpriteLibrary.getSprite("but_back");g=new CGfxButton(-120,190,c,f);g.addEventListener(ON_MOUSE_UP,this._onBack,this)};this.unload=function(){for(var a=0;a<STAGE_PER_WORLD;a++)e[a].unload();h.off("mousedown",
function(){});s_oStage.removeChild(h);s_oStage.removeChild(f)};this._setStageInfo=function(){for(var a=0,b=0;b<c.length;b++)0<c[b]&&(a=b+1);a<STAGE_PER_WORLD&&(e[a].enable(),e[a].addScore(0),e[a].pulseAnimation());for(b=0;b<a;b++)e[b].enable(),0<c[b]&&c[b]<SCORE_SECOND_STAR?e[b].addStar(1):c[b]>=SCORE_SECOND_STAR&&c[b]<SCORE_THIRD_STAR?e[b].addStar(2):e[b].addStar(3),e[b].addScore(c[b])};this._onStageBut=function(b){this.unload();s_oLevelMenu.unload();s_oMain.gotoGame(a,b)};this._onBack=function(){for(var a=
0;3>a;a++)e[a].setClickable();g.setClickable();var d=this;(new createjs.Tween.get(h)).to({alpha:0},500);(new createjs.Tween.get(f)).to({y:b},400,createjs.Ease.backIn).call(function(){d.unload()})};this._init(a,c)}
function CGame(a,c,b){var e,h,g,f,k,d,l=0,m=0,n=0,r,u,p,t,q,w,x,z=0,D,B,I=null,y,E,A,G,F,v,H,C,J;this._init=function(a,b){g=e=!1;t=w=q=0;p=HERO_LIFE;x=0;m=a;n=b;l=m*STAGE_PER_WORLD+n;var d=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(d);B=new CInterface(a);new CVirusSettings;d=createBitmap(s_oSpriteLibrary.getSprite("frame_cover"));d.x=0;d.y=242;s_oStage.addChild(d);G=new CBorder(a);v=new createjs.Container;s_oStage.addChild(v);J=new createjs.Container;s_oStage.addChild(J);
C=new CScoreAnim(J,B.getNumScorePos());A=new CHero(CANVAS_WIDTH/2+BORDER_WIDTH/2,CANVAS_HEIGHT/2-BORDER_HEIGHT/2+BORDER_HEIGHT_OFFSET+BORDER_HEIGHT);E=new CController(A,G);H=new CAnimation(v);setMute(s_oSoundtrack,!1);0===l?new CHelpPanel:this._setLevel();$(s_oMain).trigger("start_level",l)};this._setLevel=function(){d=[];var a=VIRUS_SPEED[l];k=[];k[0]=new CVirus(CANVAS_WIDTH/2,G.getBorderRect().y+G.getBorderRect().height/2,m,BOSS_MOVEMENT[m],a,v);F=k[0];h=!0;F.enableSeekMode();H.playLevelInfo(m+
1,n+1);H.playStartScene(F,m);u=setTimeout(function(){y._spawnVirus();y._setSpawnInterval();y._setSeekMode()},SPAWN_START_TIME)};this._setSpawnInterval=function(){r=setInterval(function(){y._spawnVirus();y._setSeekMode()},SPAWN_TIMER)};this.getBorderRect=function(){return G.getBorderRect()};this.getHeroPos=function(){return{x:A.getPos().x,y:A.getPos().y}};this.callTremble=function(){f||(f=!0,D=setInterval(function(){y.tremble()},10))};this.tremble=function(){if(g=!g){var a;a=.5>Math.random()?-2:2;
var b;b=.5>Math.random()?-2:2;s_oStage.x+=a;s_oStage.y+=b}else s_oStage.x=0,s_oStage.y=0;z++;50===z&&(z=0,f=!1,clearInterval(D))};this.nextLevel=function(){n++;if(2<n&&(n=0,m++,4===m)){new CCongratulationPanel;return}this.unload();this._init(m,n)};this.restartGame=function(){$(s_oMain).trigger("restart_level",l);this.unload();this._init(m,n)};this.unload=function(){e=!1;B.unload();null!==I&&I.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){$(s_oMain).trigger("show_interlevel_ad");
$(s_oMain).trigger("end_level",l);$(s_oMain).trigger("end_session");this.unload();s_oMain.gotoMenu()};this._onExitHelp=function(){this._setLevel()};this.gameOver=function(){$(s_oMain).trigger("end_level",l);I=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));I.show(t)};this.loseLife=function(){p--;s_oInterface.refreshLife(p);this.checkLoseGame()};this.checkLoseGame=function(){0===p&&(e=!1,this.gameOver())};this.checkWinGame=function(){x--;0!==x||e||($(s_oMain).trigger("show_interlevel_ad"),new CNextLevelPanel(m,
n,t))};this.checkClosedElements=function(a,b){this.checkMonsterToKill();this._calculateWeaveScore(a,b);if(a>=WIN_QUOTE[m]){$(s_oMain).trigger("end_level",l);setMute(s_oSoundtrack,!0);playSound("boss_dead",1,0);s_oGame.stopGame();clearInterval(r);clearInterval(u);F.gotoDeadAnim();x++;H.playEndScene(F.getSprite(),m+4);for(var d=1;d<k.length;d++)k[d].dead()}};this._calculateWeaveScore=function(a,b){var d=a-q;q=a;d=Math.round(b*HERO_SPEED[SELECTED_SPEED]/100*Math.round(10*d));0!==d&&(x++,C.play(d,A.getPos()))};
this.refreshScore=function(a){t+=a;B.refreshScore(t)};this._setSeekMode=function(){h?F.disableSeekMode():F.enableSeekMode();h=!h};this._spawnVirus=function(){if(k.length-1!==MAX_NUM_VIRUS_MINIONS[l]){F.callTremble();var a;a=2===n?BOSS_MOVEMENT[m]:MOVEMENT_LINEAR;for(var b=k.length-1;b<MAX_NUM_VIRUS_MINIONS[l];b++)k.push(new CVirus(F.getPos().x,F.getPos().y,m+4,a,VIRUS_SPEED[l]/2,v))}};this.checkBossToKill=function(a){return a.hitTest(F.getPos().x,F.getPos().y)?!0:!1};this.checkMonsterToKill=function(){for(var a=
!1,b=1;b<k.length;b++)G.hitMask(k[b].getPos().x,k[b].getPos().y)||k[b].isDying()||(a=!0,k[b].dead(),w++,x++,C.play(MINION_SCORE,k[b].getPos()));a&&(.5>Math.random()?playSound("virus_dead_0",1,0):playSound("virus_dead_1",1,0))};this._savePreviousPos=function(a){d[a]=k[a].getPos()};this._clearVirus=function(){for(var a=k.length-1;0<=a;a--)k[a].isDead()&&(k[a].unload(),k.splice(a,1))};this._checkCollision=function(){for(var a=0;a<k.length;a++){for(var b=A.getWeavePoint(),e=0;e<b.length;e++)if(k[a].checkCollision(b[e].x,
b[e].y)){A.dead();this.callTremble();this.loseLife();break}b=G.getBorderPoints();for(e=0;e<b.length;e++)if(k[a].checkCollision(b[e].x,b[e].y)){k[a].setPos(d[a].x,d[a].y);k[a].changeDirection(G.getPlaneDirection(e));break}}};this._setPermittedSpeed=function(a){--a;return a=2<a?2:Math.floor(a)};this.startGame=function(){e=!0};this.stopGame=function(){e=!1};this.update=function(){if(e){this._clearVirus();for(var a=0;a<k.length;a++)this._savePreviousPos(a),k[a].update();this._checkCollision();A.isDead()||
E.update()}};s_oGame=this;SELECTED_SPEED=this._setPermittedSpeed(a.hero_speed);HERO_LIFE=a.hero_starting_life;WIN_QUOTE=a.win_quote;VIRUS_SPEED=a.virus_speed;MAX_NUM_VIRUS_MINIONS=a.max_num_minions_spawn;MINION_SCORE=a.minion_killed_score;SCORE_FIRST_STAR=a.score_star_earned[0];SCORE_SECOND_STAR=a.score_star_earned[1];SCORE_THIRD_STAR=a.score_star_earned[2];y=this;this._init(c,b)}var s_oGame;
function CInterface(a){var c,b,e,h,g,f,k=null,d,l,m,n,r,u,p,t,q,w,x,z,D,B;this._init=function(a){var k=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-k.height/2-10;h=k.height/2+10;f=new CGfxButton(e,h,k,s_oStage);f.addEventListener(ON_MOUSE_UP,this._onExit,this);c=CANVAS_WIDTH-k.width/2-100;b=k.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k=s_oSpriteLibrary.getSprite("audio_icon"),g=new CToggle(c,b,k,s_bAudioActive,s_oStage),g.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);
d=new createjs.Text(TEXT_SCORE,"bold 24px "+PRIMARY_FONT,"#000000");d.x=20;d.y=130;d.textAlign="left";d.textBaseline="middle";d.lineWidth=200;d.outline=5;s_oStage.addChild(d);l=new createjs.Text(TEXT_SCORE,"bold 24px "+PRIMARY_FONT,"#c1e401");l.x=20;l.y=d.y;l.textAlign="left";l.textBaseline="middle";l.lineWidth=200;s_oStage.addChild(l);m=new createjs.Text(0,"bold 24px "+PRIMARY_FONT,"#000000");m.x=l.x+132;m.y=l.y;m.textAlign="left";m.textBaseline="middle";m.lineWidth=200;m.outline=5;s_oStage.addChild(m);
n=new createjs.Text(0,"bold 24px "+PRIMARY_FONT,"#c1e401");n.x=m.x;n.y=l.y;n.textAlign="left";n.textBaseline="middle";n.lineWidth=200;s_oStage.addChild(n);k=s_oSpriteLibrary.getSprite("life");r=createBitmap(k);r.regX=k.width/2;r.regY=k.height/2;r.x=35;r.y=180;s_oStage.addChild(r);u=new createjs.Text("X"+HERO_LIFE,"bold 24px "+PRIMARY_FONT,"#000000");u.x=r.x+30;u.y=r.y;u.textAlign="left";u.textBaseline="middle";u.lineWidth=200;u.outline=5;s_oStage.addChild(u);p=new createjs.Text("X"+HERO_LIFE,"bold 24px "+
PRIMARY_FONT,"#c1e401");p.x=r.x+30;p.y=r.y;p.textAlign="left";p.textBaseline="middle";p.lineWidth=200;s_oStage.addChild(p);t=new createjs.Container;t.x=250;t.y=r.y;s_oStage.addChild(t);k=s_oSpriteLibrary.getSprite("percentage_fill_"+a);w=createBitmap(k);w.regX=k.width/2;w.regY=k.height/2;t.addChild(w);var k=s_oSpriteLibrary.getSprite("percentage_box"),E=k.width,A=k.height;q=createBitmap(k);q.regX=k.width/2;q.regY=k.height/2;k=s_oSpriteLibrary.getSprite("percentage_fill_"+a);x=new createjs.Shape;x.x=
w.x-k.width/2;x.y=w.y-k.height/2;x.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(0,0,k.width,k.height);t.addChild(x);w.compositeOperation="source-in";w.mask=x;x.scaleX=0;z=new createjs.Text("0%","bold 24px "+PRIMARY_FONT,"#000000");z.textAlign="center";z.textBaseline="middle";z.lineWidth=200;z.outline=5;t.addChild(z);D=new createjs.Text("0%","bold 24px "+PRIMARY_FONT,"#c1e401");D.textAlign="center";D.textBaseline="middle";D.lineWidth=200;t.addChild(D);k=s_oSpriteLibrary.getSprite("indicator");
B=createBitmap(k);B.regX=k.width/2;B.regY=k.height;B.x=WIN_QUOTE[a]*E/100-E/2;B.y=A/2;t.addChild(B);t.addChild(q);k=new createjs.Text(WIN_QUOTE[a]+"%","bold 16px "+PRIMARY_FONT,"#000000");k.x=B.x;k.y=B.y+10;k.textAlign="center";k.textBaseline="middle";k.lineWidth=200;k.outline=3;t.addChild(k);a=new createjs.Text(WIN_QUOTE[a]+"%","bold 16px "+PRIMARY_FONT,"#ffd000");a.x=B.x;a.y=B.y+10;a.textAlign="center";a.textBaseline="middle";a.lineWidth=200;t.addChild(a);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};
this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),g=null;f.unload();null!==k&&k.unload();s_oInterface=null};this.refreshButtonPos=function(a,d){f.setPosition(e-a,d+h);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||g.setPosition(c-a,d+b)};this.refreshScore=function(a){n.text=a;m.text=n.text;(new createjs.Tween.get(n,{override:!0})).to({scaleX:1.1,scaleY:1.1},100).to({scaleX:1,scaleY:1},100);(new createjs.Tween.get(m,{override:!0})).to({scaleX:1.1,scaleY:1.1},100).to({scaleX:1,
scaleY:1},100)};this.refreshLife=function(a){p.text="X"+a;u.text=p.text};this.refreshPercentage=function(a){var b=Number(a.toString().match(/^\d+(?:\.\d{0,1})?/));D.text=b+"%";z.text=D.text;a/=100;createjs.Tween.get(x).to({scaleX:a},400,createjs.Ease.cubicOut)};this.getNumScorePos=function(){return{x:n.x,y:n.y}};this._onButHelpRelease=function(){k=new CHelpPanel};this._onButRestartRelease=function(){s_oGame.restartGame()};this.onExitFromHelp=function(){k.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onExit=function(){new CAreYouSurePanel(s_oStage)};s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CCreditsPanel(){var a,c,b,e,h;this._init=function(){c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;c.on("mousedown",function(){});s_oStage.addChild(c);(new createjs.Tween.get(c)).to({alpha:.7},500);b=new createjs.Container;s_oStage.addChild(b);var g=s_oSpriteLibrary.getSprite("credits_panel"),f=createBitmap(g);f.regX=g.width/2;f.regY=g.height/2;b.addChild(f);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT+g.height/2;a=b.y;(new createjs.Tween.get(b)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.quartIn);f=new createjs.Text(TEXT_DEVELOPED,"bold 24px "+PRIMARY_FONT,"#000000");f.y=-g.height/2+120;f.textAlign="center";f.textBaseline="middle";f.lineWidth=300;f.outline=5;b.addChild(f);g=new createjs.Text(TEXT_DEVELOPED,"bold 24px "+PRIMARY_FONT,"#c1e401");g.y=f.y;g.textAlign="center";g.textBaseline="middle";g.lineWidth=300;b.addChild(g);g=new createjs.Text(TEXT_LINK,"bold 24px "+PRIMARY_FONT,"#000000");g.y=80;g.textAlign="center";g.textBaseline="middle";g.lineWidth=300;
g.outline=5;b.addChild(g);f=new createjs.Text(TEXT_LINK,"bold 24px "+PRIMARY_FONT,"#c1e401");f.y=g.y;f.textAlign="center";f.textBaseline="middle";f.lineWidth=300;b.addChild(f);g=s_oSpriteLibrary.getSprite("ctl_logo");h=createBitmap(g);h.on("mousedown",this._onLogoButRelease);h.regX=g.width/2;h.regY=g.height/2;b.addChild(h);g=s_oSpriteLibrary.getSprite("but_exit");e=new CGfxButton(250,-150,g,b);e.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){e.setClickable(!1);(new createjs.Tween.get(c)).to({alpha:0},
500);(new createjs.Tween.get(b)).to({y:a},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(c);s_oStage.removeChild(b);e.unload()});c.off("mousedown",function(){});h.off("mousedown",this._onLogoButRelease)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._onMoreGamesReleased=function(){window.open("http://codecanyon.net/collections/5409142-games")};this._init()}
function CHelpPanel(){var a,c,b,e,h,g,f;this._init=function(){var f,d;h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=.7;h.on("mousedown",this._onExitHelp);s_oStage.addChild(h);g=new createjs.Container;s_oStage.addChild(g);var l=s_oSpriteLibrary.getSprite("intro_level_box");d=createBitmap(l);d.regX=l.width/2;d.regY=l.height/2;g.addChild(d);g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT+l.height/2;a=g.y;(new createjs.Tween.get(g)).to({y:CANVAS_HEIGHT/2},500,
createjs.Ease.quartIn).call(function(){});s_bMobile?(f=40,d=-170,l=s_oSpriteLibrary.getSprite("swift_hand"),b=createBitmap(l),b.regY=l.height/2,b.x=f,b.y=d,b.image=l,createjs.Tween.get(b,{loop:!0}).to({x:b.x+100},1E3,createjs.Ease.cubicOut).to({x:f},1E3,createjs.Ease.cubicOut),g.addChild(b),l=new createjs.Text(TEXT_HELP1_MOB,"bold 14px "+PRIMARY_FONT,"#000000"),l.x=-80,l.y=d-12,l.textAlign="center",l.textBaseline="middle",l.lineWidth=250,l.outline=4,g.addChild(l),f=new createjs.Text(TEXT_HELP1_MOB,
"bold 14px "+PRIMARY_FONT,"#c1e401"),f.x=l.x,f.y=l.y,f.textAlign="center",f.textBaseline="middle",f.lineWidth=250,g.addChild(f),f=-130,d=-70,l=s_oSpriteLibrary.getSprite("touch_hand"),e=createBitmap(l),e.regY=l.height/2,e.x=f,e.y=d,e.image=l,createjs.Tween.get(e,{loop:!0}).to({scaleX:.9,scaleY:.9},500,createjs.Ease.cubicOut).to({scaleX:1,scaleY:1},500,createjs.Ease.cubicOut),g.addChild(e),l=new createjs.Text(TEXT_HELP2_MOB,"bold 14px "+PRIMARY_FONT,"#000000"),l.x=80,l.y=d-12,l.textAlign="center",
l.textBaseline="middle",l.lineWidth=250,l.outline=4,g.addChild(l),d=new createjs.Text(TEXT_HELP2_MOB,"bold 14px "+PRIMARY_FONT,"#c1e401"),d.x=l.x,d.y=l.y,d.textAlign="center",d.textBaseline="middle",d.lineWidth=250):(f=130,d=-170,l=s_oSpriteLibrary.getSprite("keys"),b=createBitmap(l),b.regX=l.width/2,b.regY=l.height/2,b.x=f,b.y=d,g.addChild(b),l=new createjs.Text(TEXT_HELP1,"bold 14px "+PRIMARY_FONT,"#000000"),l.x=-80,l.y=d-12,l.textAlign="center",l.textBaseline="middle",l.lineWidth=250,l.outline=
4,g.addChild(l),f=new createjs.Text(TEXT_HELP1,"bold 14px "+PRIMARY_FONT,"#c1e401"),f.x=l.x,f.y=l.y,f.textAlign="center",f.textBaseline="middle",f.lineWidth=250,g.addChild(f),l=s_oSpriteLibrary.getSprite("space_bar"),e=createBitmap(l),e.regX=l.width/2,e.regY=l.height/2,e.x=-95,e.y=d+100,g.addChild(e),l=new createjs.Text(TEXT_HELP2,"bold 14px "+PRIMARY_FONT,"#000000"),l.x=100,l.y=e.y-12,l.textAlign="center",l.textBaseline="middle",l.lineWidth=200,l.outline=4,g.addChild(l),d=new createjs.Text(TEXT_HELP2,
"bold 14px "+PRIMARY_FONT,"#c1e401"),d.x=l.x,d.y=l.y,d.textAlign="center",d.textBaseline="middle",d.lineWidth=200);g.addChild(d);this._setPercentageBox(100,30);d=new createjs.Text(TEXT_HELP3,"bold 14px "+PRIMARY_FONT,"#000000");d.x=-100;d.y=0;d.textAlign="center";d.textBaseline="middle";d.lineWidth=180;d.outline=4;g.addChild(d);l=new createjs.Text(TEXT_HELP3,"bold 14px "+PRIMARY_FONT,"#c1e401");l.x=d.x;l.y=d.y;l.textAlign="center";l.textBaseline="middle";l.lineWidth=180;g.addChild(l);c=[];for(d=0;3>
d;d++)c[d]=createSprite(s_aVirusSpriteSheet[6],"idle",0,0,0,0),c[d].x=-150+40*d,c[d].y=130,g.addChild(c[d]),(new createjs.Tween.get(c[d],{loop:!0})).wait(100*Math.random()).to({y:170},500,createjs.Ease.cubicIn).to({y:130},500,createjs.Ease.cubicOut);d=new createjs.Text(TEXT_HELP4,"bold 14px "+PRIMARY_FONT,"#000000");d.x=80;d.y=140;d.textAlign="center";d.textBaseline="middle";d.lineWidth=250;d.outline=4;g.addChild(d);l=new createjs.Text(TEXT_HELP4,"bold 14px "+PRIMARY_FONT,"#c1e401");l.x=d.x;l.y=d.y;
l.textAlign="center";l.textBaseline="middle";l.lineWidth=250;g.addChild(l)};this.unload=function(){s_oStage.removeChild(g);s_oStage.removeChild(h);for(var a=0;3>a;a++)createjs.Tween.removeTweens(c[a]);h.off("mousedown",this._onExitHelp)};this._setPercentageBox=function(a,b){var e=new createjs.Container;e.x=a;e.y=b;g.addChild(e);var c=s_oSpriteLibrary.getSprite("percentage_fill_0"),f=createBitmap(c);f.regX=c.width/2;f.regY=c.height/2;e.addChild(f);var c=s_oSpriteLibrary.getSprite("percentage_box"),
h=c.width,u=c.height,p=createBitmap(c);p.regX=c.width/2;p.regY=c.height/2;var c=s_oSpriteLibrary.getSprite("percentage_fill_0"),t=new createjs.Shape;t.x=f.x-c.width/2;t.y=f.y-c.height/2;t.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(0,0,c.width,c.height);e.addChild(t);f.mask=t;t.scaleX=.79;c=new createjs.Text("79%","bold 24px "+PRIMARY_FONT,"#000000");c.textAlign="center";c.textBaseline="middle";c.lineWidth=200;c.outline=5;e.addChild(c);c=new createjs.Text("79%","bold 24px "+PRIMARY_FONT,"#c1e401");
c.textAlign="center";c.textBaseline="middle";c.lineWidth=200;e.addChild(c);c=s_oSpriteLibrary.getSprite("indicator");f=createBitmap(c);f.regX=c.width/2;f.regY=c.height;f.x=WIN_QUOTE[0]*h/100-h/2;f.y=u/2;e.addChild(f);e.addChild(p);h=new createjs.Text("75%","bold 16px "+PRIMARY_FONT,"#000000");h.x=f.x;h.y=f.y+10;h.textAlign="center";h.textBaseline="middle";h.lineWidth=200;h.outline=3;e.addChild(h);h=new createjs.Text("75%","bold 16px "+PRIMARY_FONT,"#ffd000");h.x=f.x;h.y=f.y+10;h.textAlign="center";
h.textBaseline="middle";h.lineWidth=200;e.addChild(h)};this._onExitHelp=function(){playSound("click",1,0);(new createjs.Tween.get(h)).to({alpha:0},500);(new createjs.Tween.get(g)).to({y:a},400,createjs.Ease.backIn).call(function(){f.unload();s_oGame._onExitHelp()})};f=this;this._init()}
function CEndPanel(){var a,c,b,e,h,g;this._init=function(){setMute(s_oSoundtrack,!0);c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;c.on("mousedown",function(){});s_oStage.addChild(c);(new createjs.Tween.get(c)).to({alpha:.7},500);b=new createjs.Container;s_oStage.addChild(b);var f=s_oSpriteLibrary.getSprite("game_over_box"),g=createBitmap(f);g.regX=f.width/2;g.regY=f.height/2;b.addChild(g);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT+f.height/2;a=b.y;
(new createjs.Tween.get(b)).to({y:CANVAS_HEIGHT/2},500,createjs.Ease.quartIn);g=new createjs.Text(TEXT_GAMEOVER,"bold 34px "+PRIMARY_FONT,"#000000");g.y=-f.height/2+50;g.textAlign="center";g.textBaseline="middle";g.lineWidth=400;g.outline=5;b.addChild(g);f=new createjs.Text(TEXT_GAMEOVER,"bold 34px "+PRIMARY_FONT,"#ef000b");f.y=g.y;f.textAlign="center";f.textBaseline="middle";f.lineWidth=400;b.addChild(f);for(var d=s_oLocalStorage.getItemJson(LOCALSTORAGE_SCORE),l=f=0;l<d.length;l++)f+=d[l];$(s_oMain).trigger("save_score",
f);$(s_oMain).trigger("share_event",f);d=new createjs.Text(TEXT_TOTAL_SCORE+" "+f,"bold 24px "+PRIMARY_FONT,"#000000");d.y=g.y+40;d.textAlign="center";d.textBaseline="middle";d.lineWidth=500;d.outline=5;b.addChild(d);g=new createjs.Text(TEXT_TOTAL_SCORE+" "+f,"bold 24px "+PRIMARY_FONT,"#ef000b");g.y=d.y;g.textAlign="center";g.textBaseline="middle";g.lineWidth=500;b.addChild(g);f=s_oSpriteLibrary.getSprite("but_exit_big");e=new CGfxButton(120,190,f,b);e.addEventListener(ON_MOUSE_UP,this._onExit,this);
f=s_oSpriteLibrary.getSprite("but_restart");h=new CGfxButton(-120,190,f,b);h.addEventListener(ON_MOUSE_UP,this._onRestart,this);h.pulseAnimation()};this.unload=function(){s_oStage.removeChild(b);c.off("mousedown",function(){});e.unload();h.unload()};this.show=function(a){playSound("game_over",1,0)};this._onExit=function(){setMute(s_oSoundtrack,!1);c.off("mousedown",function(){});s_oStage.removeChild(b);s_oGame.onExit()};this._onRestart=function(){(new createjs.Tween.get(c)).to({alpha:0},500);(new createjs.Tween.get(b)).to({y:a},
400,createjs.Ease.backIn).call(function(){g.unload();s_oGame.restartGame()})};g=this;this._init();return this}
function CController(a,c){var b,e,h,g;function f(a){a.preventDefault();switch(a.keyCode){case 32:q.fireUp();break;case 37:q.stopLeft();break;case 38:q.stopUp();break;case 39:q.stopRight();break;case 40:q.stopDown()}}function k(a){a||(a=window.event);switch(a.keyCode){case 32:q.fireDown();break;case 37:q.moveLeft();break;case 38:q.moveUp();break;case 39:q.moveRight();break;case 40:q.moveDown()}a.preventDefault();return!1}var d,l,m,n,r,u,p,t,q,w;this._init=function(a,b){p=a;t=b;u=[];s_bMobile?this._initHammer():
(document.onkeydown=k,document.onkeyup=f)};this.unload=function(){s_bMobile&&(w.off("swipeleft",function(){q.stopAllDirection();q.fireDown();q.moveLeft()}),w.off("swiperight",function(){q.stopAllDirection();q.fireDown();q.moveRight()}),w.off("swipeup",function(){q.stopAllDirection();q.fireDown();q.moveUp()}),w.off("swipedown",function(){q.stopAllDirection();q.fireDown();q.moveDown()}),w.off("tap",function(){q.stopAllDirection();q.fireUp()}));s_oController=null};this._initHammer=function(){w=new Hammer(s_oCanvas);
w.get("swipe").set({direction:Hammer.DIRECTION_ALL});w.get("swipe").set({velocity:.05});w.get("swipe").set({threshold:1});w.on("swipeleft",function(){q.stopAllDirection();q.fireDown();q.moveLeft()});w.on("swiperight",function(){q.stopAllDirection();q.fireDown();q.moveRight()});w.on("swipeup",function(){q.stopAllDirection();q.fireDown();q.moveUp()});w.on("swipedown",function(){q.stopAllDirection();q.fireDown();q.moveDown()});w.get("tap").set({enable:!0});w.on("tap",function(){q.stopAllDirection();
q.fireUp()})};this._detectDirection=function(){switch(u[u.length-1]){case LEFT_DIRECTION:h=p.getPos().x-HERO_SPEED[SELECTED_SPEED]/2;g=p.getPos().y;b=p.getPos().x-HERO_SPEED[SELECTED_SPEED];e=p.getPos().y;break;case UP_DIRECTION:h=p.getPos().x;g=p.getPos().y-HERO_SPEED[SELECTED_SPEED]/2;b=p.getPos().x;e=p.getPos().y-HERO_SPEED[SELECTED_SPEED];break;case RIGHT_DIRECTION:h=p.getPos().x+HERO_SPEED[SELECTED_SPEED]/2;g=p.getPos().y;b=p.getPos().x+HERO_SPEED[SELECTED_SPEED];e=p.getPos().y;break;case DOWN_DIRECTION:h=
p.getPos().x,g=p.getPos().y+HERO_SPEED[SELECTED_SPEED]/2,b=p.getPos().x,e=p.getPos().y+HERO_SPEED[SELECTED_SPEED]}d?t.hitBorder(b,e)?p.closingSquare(b,e)||(p.isWeaving()?(p.move(b,e),t.rebuild(p.getWeavePoint()),p.stopWeave(),p.removeAllWeave(),p.startIdle()):t.checkNearPoints(p.getPos().x,p.getPos().y,b,e)?p.move(b,e):t.hitMask(h,g)&&(p.startWeave(),p.move(b,e),t.rebuild(p.getWeavePoint()),p.stopWeave(),p.removeAllWeave(),p.startIdle())):t.hitMask(b,e)&&(s_bMobile?t.hitBorder(p.getPos().x,p.getPos().y)||
(p.startWeave(),p.move(b,e)):(p.startWeave(),p.move(b,e))):t.hitBorder(h,g)&&p.move(b,e)};this._removeDirection=function(a){for(var b=0;b<u.length;b++)u[b]===a&&u.splice(b,1)};this.stopAllDirection=function(){this.stopLeft();this.stopUp();this.stopRight();this.stopDown()};this.stopLeft=function(){l=!1;this._removeDirection(LEFT_DIRECTION)};this.stopUp=function(){m=!1;this._removeDirection(UP_DIRECTION)};this.stopRight=function(){n=!1;this._removeDirection(RIGHT_DIRECTION)};this.stopDown=function(){r=
!1;this._removeDirection(DOWN_DIRECTION)};this.moveLeft=function(){l||(l=!0,u.push(LEFT_DIRECTION),s_bMobile&&t.hitMask(p.getPos().x-HERO_SPEED[SELECTED_SPEED],p.getPos().y)&&(p.startWeave(),p.move(p.getPos().x-HERO_SPEED[SELECTED_SPEED],p.getPos().y)))};this.moveUp=function(){m||(m=!0,u.push(UP_DIRECTION),s_bMobile&&t.hitMask(p.getPos().x,p.getPos().y-HERO_SPEED[SELECTED_SPEED])&&(p.startWeave(),p.move(p.getPos().x,p.getPos().y-HERO_SPEED[SELECTED_SPEED])))};this.moveRight=function(){n||(n=!0,u.push(RIGHT_DIRECTION),
s_bMobile&&t.hitMask(p.getPos().x+HERO_SPEED[SELECTED_SPEED],p.getPos().y)&&(p.startWeave(),p.move(p.getPos().x+HERO_SPEED[SELECTED_SPEED],p.getPos().y)))};this.moveDown=function(){r||(r=!0,u.push(DOWN_DIRECTION),s_bMobile&&t.hitMask(p.getPos().x,p.getPos().y+HERO_SPEED[SELECTED_SPEED])&&(p.startWeave(),p.move(p.getPos().x,p.getPos().y+HERO_SPEED[SELECTED_SPEED])))};this.fireDown=function(){trace("_oHero.isReversing(): "+p.isReversing());p.isReversing()&&p.startWeave();d=!0};this.fireUp=function(){p.stopWeave();
p.reverseWeave();d=!1};this.update=function(){0<u.length&&this._detectDirection()};q=this;s_oController=this;this._init(a,c)}var s_oController=null;
function CHero(a,c){var b,e,h,g,f,k,d,l,m,n,r;this._init=function(a,c){h=e=b=!1;g=BORDER_LINE_DIM;l=new createjs.Shape;l.graphics.setStrokeStyle(g,"round","round");l.graphics.beginStroke("#ffffff");l.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(l);f=[];var k=s_oSpriteLibrary.getSprite("pill"),q=k.width/11,w=k.height/5;r={width:q,height:w};k=new createjs.SpriteSheet({images:[k],frames:{width:q,height:w,regX:30,regY:52},animations:{idle:[0,19],move:[20,40],dead:[41,54]}});d=createSprite(k,
"idle",0,0,0,0);d.x=a;d.y=c;s_oStage.addChild(d);d.addEventListener("animationend",this._onCompleteDead);n={x:a,y:c};m=playSound("weaving",1,-1);stopSound(m)};this.move=function(a,c){h||(1<f.length&&a===f[f.length-2].x&&c===f[f.length-2].y?this._eatWeave(a,c):this.weaveCollision(a,c)||(d.x=a,d.y=c,b&&(l.graphics.lineTo(d.x,d.y),l.updateCache(),f.push({x:d.x,y:d.y}))))};this.weaveCollision=function(a,b){for(var d=0;d<f.length;d++)if(f[d].x===a&&f[d].y===b)return!0;return!1};this.closingSquare=function(a,
b){if(2<f.length&&f[0].x===a&&f[0].y===b)return!0};this.removeAllWeave=function(){f=[];l.graphics.clear();l.updateCache()};this._eatWeave=function(a,b){f.splice(f.length-1,1);k._drawLineFromMultiplePoint();d.x=a;d.y=b};this._drawLineFromMultiplePoint=function(){l.graphics.clear();l.graphics.setStrokeStyle(g,"square","square");l.graphics.beginStroke("#ffffff");l.graphics.moveTo(f[0].x,f[0].y);for(var a=1;a<f.length;a++)l.graphics.lineTo(f[a].x,f[a].y);l.updateCache()};this.getPos=function(){return{x:d.x,
y:d.y}};this.getDim=function(){return r};this.getWeavePoint=function(){return f};this.isDead=function(){return h};this.isWeaving=function(){return b};this.isReversing=function(){return e};this.startWeave=function(){b||h||(b=!0,e=!1,d.gotoAndPlay("move"),continueSound(m),f.push({x:d.x,y:d.y}),this._drawLineFromMultiplePoint(),l.alpha=1,(new createjs.Tween.get(l,{loop:!0,override:!0})).to({alpha:.5},200).to({alpha:1},400))};this.stopWeave=function(){b=!1};this.reverseWeave=function(){h||(0<f.length&&
!b?(e=!0,d.x=f[f.length-1].x,d.y=f[f.length-1].y,k._drawLineFromMultiplePoint(),f.splice(f.length-1,1),setTimeout(function(){k.reverseWeave()},30)):(e=!1,0===f.length&&(d.gotoAndPlay("idle"),stopSound(m))))};this.startIdle=function(){d.gotoAndPlay("idle");stopSound(m)};this.dead=function(){h||(playSound("hero_dead",1,0),h=!0,n=f[0],s_bMobile&&s_oController.stopAllDirection(),this.removeAllWeave(),d.gotoAndPlay("dead"))};this._onCompleteDead=function(){"dead"===d.currentAnimation&&(d.x=n.x,d.y=n.y,
d.gotoAndPlay("idle"),stopSound(m),k.stopWeave(),k.reverseWeave(),h=!1)};k=this;this._init(a,c)}
function CBorder(a){var c,b,e,h,g,f,k,d,l,m,n,r,u;this._init=function(a){e="#c1e401";h=BORDER_LINE_DIM;l={x:CANVAS_WIDTH/2-BORDER_WIDTH/2,y:CANVAS_HEIGHT/2-BORDER_HEIGHT/2+BORDER_HEIGHT_OFFSET};c=l.x+BORDER_WIDTH;b=l.y+BORDER_HEIGHT;r=createBitmap(s_oSpriteLibrary.getSprite("image_"+a));r.x=l.x;r.y=l.y;s_oStage.addChild(r);u=createBitmap(s_oSpriteLibrary.getSprite("cover_"+a));u.x=l.x;u.y=l.y;u.compositeOperation="source-in";u.mask=n;s_oStage.addChild(u);this._buildStarterBoard();n=new createjs.Shape;
n=this._drawMask(d);this._setMaskOnBorder(n);s_oStage.addChild(n);g=BORDER_WIDTH*BORDER_HEIGHT};this._calculateArea=function(a){for(var b=0,d=0;d<a.length-1;d++)b+=a[d].x*a[d+1].y-a[d+1].x*a[d].y;b+=a[a.length-1].x*a[0].y-a[0].x*a[a.length-1].y;return b/2};this.calculateQuote=function(){k=100-100*f/g;s_oInterface.refreshPercentage(k)};this._drawBorder=function(){m.graphics.clear();m.graphics.setStrokeStyle(h,"round","round");m.graphics.beginStroke(e);m.graphics.moveTo(d[0].x,d[0].y);for(var a=1;a<
d.length;a++)m.graphics.lineTo(d[a].x,d[a].y);m.graphics.lineTo(d[0].x,d[0].y)};this._drawMask=function(a){var b=new createjs.Shape;b.alpha=.01;b.graphics.setStrokeStyle(h,"round","round");b.graphics.beginFill("#FFFFFF");b.graphics.moveTo(a[0].x,a[0].y);for(var d=1;d<a.length;d++)b.graphics.lineTo(a[d].x,a[d].y);b.graphics.lineTo(a[0].x,a[0].y);return b};this._setMaskOnBorder=function(a){n=a;u.compositeOperation="source-in";u.mask=n};this._buildStarterBoard=function(){d=[];for(var a=l.x;a<c;a+=HERO_SPEED[SELECTED_SPEED])d.push({x:a,
y:l.y});for(a=l.y;a<b;a+=HERO_SPEED[SELECTED_SPEED])d.push({x:c,y:a});for(a=c;a>l.x;a-=HERO_SPEED[SELECTED_SPEED])d.push({x:a,y:b});for(a=b;a>l.y;a-=HERO_SPEED[SELECTED_SPEED])d.push({x:l.x,y:a});m=new createjs.Shape;this._drawBorder();s_oStage.addChild(m)};this.checkNearPoints=function(a,b,c,e){for(var f,g=0;g<d.length;g++)if(d[g].x===a&&d[g].y===b){f=g;break}return 0===f?d[d.length-1].x===c&&d[d.length-1].y===e||d[f+1].x===c&&d[f+1].y===e?!0:!1:f===d.length-1?d[f-1].x===c&&d[f-1].y===e||d[0].x===
c&&d[0].y===e?!0:!1:d[f-1].x===c&&d[f-1].y===e||d[f+1].x===c&&d[f+1].y===e?!0:!1};this.rebuild=function(a){if(!(1>=a.length)){for(var b=-1,c=0,e=0,g=-1,h=0;h<d.length;h++)if(d[h].x===a[0].x&&d[h].y===a[0].y||d[h].x===a[a.length-1].x&&d[h].y===a[a.length-1].y)0>b?(b=h,c=d[h].x,e=d[h].y):g=h;for(var l=[],h=b;h<=g;h++)l.push(d[h]);if(a[0].x===c&&a[0].y===e)for(h=0;h<a.length-2;h++)l.push(a[a.length-h-2]);else for(h=1;h<a.length-1;h++)l.push(a[h]);for(var m=[],h=0;h<=b;h++)m.push(d[h]);if(a[0].x===c&&
a[0].y===e)for(h=1;h<a.length-1;h++)m.push(a[h]);else for(h=0;h<a.length-2;h++)m.push(a[a.length-h-2]);for(h=g;h<d.length;h++)m.push(d[h]);b=this._drawMask(l);d=[];if(s_oGame.checkBossToKill(b)){for(h=0;h<l.length;h++)d.push(l[h]);this._setMaskOnBorder(b)}else{for(h=0;h<m.length;h++)d.push(m[h]);h=this._drawMask(m);this._setMaskOnBorder(h)}this._drawBorder();f=this._calculateArea(d);this.calculateQuote();s_oGame.checkClosedElements(k,a.length);playSound("close_mask",1,0)}};this._debugCheckSamePoints=
function(){for(var a=0;a<d.length-1;a++)for(var b=d[a],c=a+1;c<d.length;c++)b.x===d[c].x&&b.y===d[c].y&&(trace(d[c]),trace(d[a]))};this.hitBorder=function(a,b){return m.hitTest(a,b)};this.hitMask=function(a,b){return n.hitTest(a,b)};this.getBorderShape=function(){return m};this.getBorderPoints=function(){return d};this.getBorderRect=function(){return{x:l.x,y:l.y,width:BORDER_WIDTH,height:BORDER_HEIGHT}};this.getStartPoint=function(){return l};this.getPlaneDirection=function(a){var b=d[a].x,c=d[a].y;
0===a?d[d.length-1].x===b?(a=(d[d.length-1].y+c)/2,b=n.hitTest(b+1,a)?new CVector2(1,0):new CVector2(-1,0)):(a=(d[d.length-1].x+b)/2,b=n.hitTest(a,c+1)?new CVector2(0,1):new CVector2(0,-1)):d[a-1].x===b?(a=(d[d.length-1].y+c)/2,b=n.hitTest(b+1,a)?new CVector2(1,0):new CVector2(-1,0)):(a=(d[d.length-1].x+b)/2,b=n.hitTest(a,c+1)?new CVector2(0,1):new CVector2(0,-1));return b};this._init(a)}
function CVirus(a,c,b,e,h,g){var f,k,d,l,m,n,r,u,p,t,q,w,x,z,D,B,I,y,E,A,G,F,v,H,C,J;this._init=function(a,b,c,e,f,g){z=x=t=p=!1;y=0;E;F=0;D=f;A=e;v=createSprite(s_aVirusSpriteSheet[c],"idle",0,0,0,0);v.x=a;v.y=b;v.addEventListener("animationend",this._onCompleteDead);g.addChildAt(v,0);B=s_aColliderRadius[c];I=Math.pow(B,2);C=new CVector2(-1+2*Math.random(),-1+2*Math.random());C.normalize();C.scalarProduct(D);J=new CVector2(0,0);r=v.x;u=v.y;m=v.x;n=v.y;d=v.x;l=v.y;this._setDirection()};this.unload=
function(){g.removeChild(v)};this.checkCollision=function(a,b){var d=a-v.x,c=b-v.y;return d*d+c*c<I};this.getSprite=function(){return v};this.getPos=function(){return{x:v.x,y:v.y}};this.callTremble=function(){A=MOVEMENT_STOP;f=v.x;k=v.y;w||(w=!0,G=setInterval(function(){H.tremble()},10))};this.tremble=function(){if(q=!q){var a;a=.5>Math.random()?-2:2;var b;b=.5>Math.random()?-2:2;v.x+=a;v.y+=b}else v.x=f,v.y=k;F++;100===F&&(F=0,w=!1,clearInterval(G),A=e)};this.enableSeekMode=function(){x=!0};this.disableSeekMode=
function(){x=!1};this.setPos=function(a,b){v.x=a;v.y=b};this.isDead=function(){return p};this.isDying=function(){return t};this.gotoDeadAnim=function(){v.gotoAndStop("dead")};this.dead=function(){t||(v.gotoAndPlay("dead"),t=!0)};this._onCompleteDead=function(){"dissolve"===v.currentAnimation&&(p=!0,v.gotoAndStop("stop"))};this._setDirection=function(){if(x&&e!==MOVEMENT_LINEAR)this._setHeroDirection();else switch(e){case MOVEMENT_RANDOM:this._setRandomDirection();break;case MOVEMENT_LINEAR:this._setReflectDirection();
break;case MOVEMENT_DISCRETE:this._setDiscreteDirection();break;case MOVEMENT_CIRCULAR:this._setDiscreteDirection();break;default:this._setReflectDirection()}};this._setRandomDirection=function(){A=MOVEMENT_RANDOM;C=new CVector2(-1+2*Math.random(),-1+2*Math.random());C.normalize();C.scalarProduct(D)};this._setReflectDirection=function(){C=reflectVectorV2(C,J)};this._setDiscreteDirection=function(){e===MOVEMENT_DISCRETE?A=MOVEMENT_DISCRETE:e===MOVEMENT_CIRCULAR&&(z=.5>Math.random()?!0:!1,A=MOVEMENT_CIRCULAR);
y=0;m=v.x;n=v.y;var a;do d=s_oGame.getBorderRect().x+Math.random()*s_oGame.getBorderRect().width,l=s_oGame.getBorderRect().y+Math.random()*s_oGame.getBorderRect().height,a=Math.pow(d-m,2)+Math.pow(l-n,2);while(1E4>a);E=Math.sqrt(a)/D};this._setStopDirection=function(){setTimeout(function(){H._setDirection()},10)};this._setHeroDirection=function(){y=0;m=v.x;n=v.y;d=s_oGame.getHeroPos().x;l=s_oGame.getHeroPos().y;E=Math.sqrt(Math.pow(d-m,2)+Math.pow(l-n,2))/D;C=new CVector2(d,l);var a=new CVector2(m,
n);C.subV(a);C.normalize();C.scalarProduct(D);A=e};this._frictionMovement=function(){y++;if(y>E)y=0,A=MOVEMENT_STOP,this._setStopDirection();else{var a=s_oTweenController.easeInOutCubic(y,0,1,E),a=s_oTweenController.tweenValue(n,l,a);v.y=a;a=s_oTweenController.easeInOutCubic(y,0,1,E);a=s_oTweenController.tweenValue(m,d,a);v.x=a}};this._circularMovement=function(){y++;if(y>E)y=0,A=MOVEMENT_STOP,this._setStopDirection();else{if(z)a=s_oTweenController.easeOutBack(y,0,1,E),a=s_oTweenController.tweenValue(n,
l,a),v.y=a,a=s_oTweenController.easeInOutCubic(y,0,1,E);else{var a=s_oTweenController.easeInOutCubic(y,0,1,E),a=s_oTweenController.tweenValue(n,l,a);v.y=a;a=s_oTweenController.easeOutBack(y,0,1,E)}a=s_oTweenController.tweenValue(m,d,a);v.x=a}};this.changeDirection=function(a){new createjs.Tween.removeTweens(v);J=new CVector2(a.getX(),a.getY());if(r===v.x&&u===v.y)switch(e){case MOVEMENT_DISCRETE:this._setDiscreteDirection();break;case MOVEMENT_CIRCULAR:this._setDiscreteDirection();break;default:this._setRandomDirection()}else this._setDirection();
r=v.x;u=v.y};this.update=function(){if(!t)switch(A){case MOVEMENT_DISCRETE:this._frictionMovement();break;case MOVEMENT_CIRCULAR:this._circularMovement();break;case MOVEMENT_STOP:break;default:v.x+=C.getX(),v.y+=C.getY()}};H=this;this._init(a,c,b,e,h,g)}
function CVirusSettings(){var a=s_oSpriteLibrary.getSprite("boss0"),c=a.width/7,b=a.height/4,a={images:[a],frames:{width:c,height:b,regX:c/2-6,regY:b/2-8},animations:{idle:[0,19],dead:[22,22],scared:[23,27,"scared"]}};s_aVirusSpriteSheet[0]=new createjs.SpriteSheet(a);s_aColliderRadius[0]=28;a=s_oSpriteLibrary.getSprite("boss1");c=a.width/7;b=a.height/4;a={images:[a],frames:{width:c,height:b,regX:c/2-5,regY:b/2-5},animations:{idle:[0,19],dead:[24,24],scared:[24,27,"scared"]}};s_aVirusSpriteSheet[1]=
new createjs.SpriteSheet(a);s_aColliderRadius[1]=26;a=s_oSpriteLibrary.getSprite("boss2");c=a.width/7;b=a.height/4;a={images:[a],frames:{width:c,height:b,regX:c/2-6,regY:b/2-8},animations:{idle:[0,19],dead:[22,22],scared:[24,27,"scared"]}};s_aVirusSpriteSheet[2]=new createjs.SpriteSheet(a);s_aColliderRadius[2]=26;a=s_oSpriteLibrary.getSprite("boss3");c=a.width/7;b=a.height/4;a={images:[a],frames:{width:c,height:b,regX:c/2-2,regY:b/2-2},animations:{idle:[0,19],dead:[20,20],scared:[21,27,"scared"]}};
s_aVirusSpriteSheet[3]=new createjs.SpriteSheet(a);s_aColliderRadius[3]=25;a=s_oSpriteLibrary.getSprite("virus0");c=a.width/9;b=a.height/4;a={images:[a],frames:{width:c,height:b,regX:c/2-2,regY:b/2-2},animations:{idle:[0,19],dead:[22,22,"dissolve",1/30],dissolve:[21,35,"stop",.5],stop:[36]}};s_aVirusSpriteSheet[4]=new createjs.SpriteSheet(a);s_aColliderRadius[4]=15;a=s_oSpriteLibrary.getSprite("virus1");c=a.width/9;b=a.height/4;a={images:[a],frames:{width:c,height:b,regX:c/2-3,regY:b/2-4},animations:{idle:[0,
19],dead:[20,20,"dissolve",1/30],dissolve:[21,35,"stop",.5],stop:[36]}};s_aVirusSpriteSheet[5]=new createjs.SpriteSheet(a);s_aColliderRadius[5]=13;a=s_oSpriteLibrary.getSprite("virus2");c=a.width/9;b=a.height/4;a={images:[a],frames:{width:c,height:b,regX:c/2-2,regY:b/2-2},animations:{idle:[0,19],dead:[20,20,"dissolve",1/30],dissolve:[21,35,"stop",.5],stop:[36]}};s_aVirusSpriteSheet[6]=new createjs.SpriteSheet(a);s_aColliderRadius[6]=13;a=s_oSpriteLibrary.getSprite("virus3");c=a.width/9;b=a.height/
4;a={images:[a],frames:{width:c,height:b,regX:c/2-3,regY:b/2-2},animations:{idle:[0,19],dead:[20,20,"dissolve",1/30],dissolve:[21,35,"stop",.5],stop:[36]}};s_aVirusSpriteSheet[7]=new createjs.SpriteSheet(a);s_aColliderRadius[7]=13}var s_aVirusSpriteSheet=[],s_aColliderRadius=[];
function CAnimation(a){var c,b,e,h,g,f,k,d,l,m,n,r;this._init=function(a){c=!1;b=100;g=8;f=0;n=a};this.playLevelInfo=function(a,b){var d=0,c;switch(a){case 1:c=STAGE_ANIM_COLOR[0];break;case 2:c=STAGE_ANIM_COLOR[1];break;case 3:d=1E3;c=STAGE_ANIM_COLOR[2];break;case 4:c=STAGE_ANIM_COLOR[3]}var e=new createjs.Text(TEXT_VIRUS_TYPE+": "+a,"bold 34px "+PRIMARY_FONT,"#000000");e.x=CANVAS_WIDTH/2;e.y=300;e.alpha=0;e.textAlign="center";e.textBaseline="middle";e.lineWidth=500;e.outline=5;s_oStage.addChild(e);
var f=new createjs.Text(TEXT_VIRUS_TYPE+": "+a,"bold 34px "+PRIMARY_FONT,c);f.x=e.x;f.y=e.y;f.alpha=0;f.textAlign="center";f.textBaseline="middle";f.lineWidth=500;s_oStage.addChild(f);var g=new createjs.Text(TEXT_STAGE+": "+b,"bold 34px "+PRIMARY_FONT,"#000000");g.x=e.x;g.y=e.y+50;g.alpha=0;g.textAlign="center";g.textBaseline="middle";g.lineWidth=500;g.outline=5;s_oStage.addChild(g);var h=new createjs.Text(TEXT_STAGE+": "+b,"bold 34px "+PRIMARY_FONT,c);h.x=e.x;h.y=g.y;h.alpha=0;h.textAlign="center";
h.textBaseline="middle";h.lineWidth=500;s_oStage.addChild(h);(new createjs.Tween.get(e)).wait(d).to({alpha:1},1E3).wait(1E3).to({alpha:0},1E3);(new createjs.Tween.get(f)).wait(d).to({alpha:1},1E3).wait(1E3).to({alpha:0},1E3);(new createjs.Tween.get(g)).wait(d).to({alpha:1},1E3).wait(1E3).to({alpha:0},1E3);(new createjs.Tween.get(h)).wait(d).to({alpha:1},1E3).wait(1E3).to({alpha:0},1E3).call(function(){s_oStage.removeChild(e);s_oStage.removeChild(f);s_oStage.removeChild(g);s_oStage.removeChild(h)})};
this.playStartScene=function(a,c){e=c;h=e+4;m=a.getSprite();m.scaleX=m.scaleY=0;var f=new CVector2(0,-1);f.scalarProduct(b);l=[];d=[];for(var r=0;r<g;r++){d[r]=createSprite(s_aVirusSpriteSheet[h],"idle",0,0,0,0);d[r].x=m.x+f.getX();d[r].y=m.y+f.getY();n.addChildAt(d[r],0);var w=degreesToRadians(360/g);rotateVector2D(w,f);l[r]=new CVector2(f.getX(),f.getY())}k=[];k=[this._startScene0,this._startScene2,this._startScene3,this._startScene1];k[e]()};this.unload=function(){for(var a=0;a<d.length;a++)n.removeChild(d[a])};
this._startScene0=function(){for(var a=[],b=0;b<d.length;b++)a[b]=b;shuffle(a);for(b=0;b<d.length;b++)l[b].normalize(),l[b].scalarProduct(200),d[b].x=m.x+l[b].getX(),d[b].y=m.y+l[b].getY(),d[b].alpha=0;for(b=0;b<d.length;b++)(new createjs.Tween.get(d[a[b]])).wait(100*b).to({alpha:1},500).to({alpha:.2},500),(new createjs.Tween.get(d[a[b]])).wait(100*b).to({x:m.x,y:m.y},1E3).call(function(){playSound("minion_anim",1,0)});setTimeout(function(){r._growBoss()},1E3)};this._startScene1=function(){for(var a=
0;a<d.length;a++)d[a].scaleX=d[a].scaleY=0,(new createjs.Tween.get(d[a])).wait(300*a).to({scaleX:1,scaleY:1},700,createjs.Ease.quartIn);r._circularAnim()};this._startScene2=function(){for(var a=0;a<d.length;a++){d[a].x=m.x-250+500*a/(d.length-1);d[a].y=400-100*Math.random();d[a].alpha=0;(new createjs.Tween.get(d[a])).to({alpha:m.alpha},300);(new createjs.Tween.get(d[a])).to({y:m.y},1500,createjs.Ease.bounceOut);(new createjs.Tween.get(d[a])).wait(1500).to({x:m.x},1500,createjs.Ease.cubicIn);var b;
b=a<d.length/2?360-25*a:-(360-d.length/2+20*a);(new createjs.Tween.get(d[a])).wait(1500).to({rotation:b},1500,createjs.Ease.cubicIn)}setTimeout(function(){r._growBoss()},2500)};this._startScene3=function(){for(var a=0;a<d.length;a++)d[a].x=m.x-100,d[a].y=m.y-30*(d.length-1)+30*a,d[a].alpha=0,(new createjs.Tween.get(d[a])).to({alpha:m.alpha},300),(new createjs.Tween.get(d[a])).wait(300*a).to({x:m.x},1500-40*a),(new createjs.Tween.get(d[a])).wait(300*a).to({y:d[a].y-50},750,createjs.Ease.cubicOut).to({y:m.y},
750-40*a,createjs.Ease.cubicIn).call(function(){r._inflateBoss();playSound("minion_anim",1,0)})};this._circularAnim=function(){for(var a=0;a<d.length;a++){b-=.1;d[a].alpha=b/100+.5;if(0>b)return;10>b&&r._growBoss();rotateVector2D(degreesToRadians(2),l[a]);d[a].x=m.x+l[a].getX();d[a].y=m.y+l[a].getY();l[a].normalize();l[a].scalarProduct(b)}setTimeout(function(){r._circularAnim()},FPS_TIME)};this._endStartScene=function(){s_oGame.startGame();this.unload()};this._endFinalScene=function(){f++;f===d.length&&
(this.unload(),s_oGame.checkWinGame())};this.playEndScene=function(a,b){e=b;m=a;l=[];d=[];for(var c=0;c<g;c++)d[c]=createSprite(s_aVirusSpriteSheet[h],"idle",0,0,0,0),d[c].x=m.x,d[c].y=m.y,d[c].gotoAndStop("dead"),d[c].alpha=0,n.addChildAt(d[c],0);setTimeout(function(){r._endScene0()},1E3)};this._endScene0=function(){for(var a,b,c=0;c<d.length;c++)a=-100+200*Math.random(),b=200*c,d[c].alpha=1,createjs.Tween.get(d[c]).wait(b).to({x:d[c].x+a},1E3),createjs.Tween.get(d[c]).wait(b).to({y:CANVAS_HEIGHT+
50},1E3,createjs.Ease.backIn).call(function(){r._endFinalScene()});this._shrinkBoss()};this._growBoss=function(){c||(playSound("boss_idle",1,0),c=!0,(new createjs.Tween.get(m)).to({scaleX:1,scaleY:1},700,createjs.Ease.bounceIn).wait(500).call(function(){r._endStartScene()}))};this._shrinkBoss=function(){(new createjs.Tween.get(m)).to({scaleX:0,scaleY:0},1500,createjs.Ease.cubicIn);(new createjs.Tween.get(m)).to({alpha:0},1500,createjs.Ease.cubicIn);m.gotoAndPlay("scared")};this._inflateBoss=function(){m.scaleX=
1;(new createjs.Tween.get(m)).to({scaleY:m.scaleY+1/d.length},300).call(function(){r._endInflate()})};this._endInflate=function(){g--;0===g&&(playSound("boss_idle",1,0),m.scaleY=1,r._endStartScene(),g=8)};r=this;this._init(a)}
function CScoreAnim(a,c){var b,e;this._init=function(a,c){b=a;e=c};this.play=function(a,c){var f=new createjs.Text(0,"bold 24px "+PRIMARY_FONT,"#000000");f.textAlign="left";f.textBaseline="middle";f.lineWidth=200;f.outline=5;b.addChild(f);var k=new createjs.Text(0,"bold 24px "+PRIMARY_FONT,"#c1e401");k.textAlign="left";k.textBaseline="middle";k.lineWidth=200;b.addChild(k);f.text=k.text="+"+a;f.x=k.x=c.x-k.getBounds().width/2;f.y=k.y=c.y;createjs.Tween.get(k).to({y:k.y-40},500,createjs.Ease.cubicOut);
createjs.Tween.get(f).to({y:f.y-40},500,createjs.Ease.cubicOut).wait(0).call(function(){createjs.Tween.get(k).to({x:e.x,y:e.y},1500,createjs.Ease.quartIn);createjs.Tween.get(f).to({x:e.x,y:e.y},1500,createjs.Ease.quartIn).call(function(){s_oGame.refreshScore(a);s_oGame.checkWinGame();b.removeChild(f);b.removeChild(k)})})};this._init(a,c)}
function CNextLevelPanel(a,c,b){var e,h,g,f,k,d,l,m,n;this._init=function(a,b,c){f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;f.on("mousedown",function(){});s_oStage.addChild(f);(new createjs.Tween.get(f)).to({alpha:.7},500);g=new createjs.Container;s_oStage.addChild(g);var h=s_oSpriteLibrary.getSprite("next_level_box"),q=createBitmap(h);q.regX=h.width/2;q.regY=h.height/2;g.addChild(q);q=new createjs.Text(TEXT_CONGRATULATION,"bold 34px "+PRIMARY_FONT,
"#000000");q.y=-h.height/2+50;q.textAlign="center";q.textBaseline="middle";q.lineWidth=200;q.outline=5;g.addChild(q);var w=new createjs.Text(TEXT_CONGRATULATION,"bold 34px "+PRIMARY_FONT,"#c1e401");w.y=q.y;w.textAlign="center";w.textBaseline="middle";w.lineWidth=200;g.addChild(w);q=a+1;a=new createjs.Text(TEXT_DEFEATED+" "+q,"bold 24px "+PRIMARY_FONT,"#000000");a.y=-180;a.textAlign="center";a.textBaseline="middle";a.lineWidth=400;a.outline=5;g.addChild(a);q=new createjs.Text(TEXT_DEFEATED+" "+q,"bold 24px "+
PRIMARY_FONT,"#c1e401");q.y=a.y;q.textAlign="center";q.textBaseline="middle";q.lineWidth=400;g.addChild(q);a=b+1;b=new createjs.Text(TEXT_INSTAGE+" "+a,"bold 24px "+PRIMARY_FONT,"#000000");b.y=-150;b.textAlign="center";b.textBaseline="middle";b.lineWidth=400;b.outline=5;g.addChild(b);a=new createjs.Text(TEXT_INSTAGE+" "+a,"bold 24px "+PRIMARY_FONT,"#c1e401");a.y=b.y;a.textAlign="center";a.textBaseline="middle";a.lineWidth=400;g.addChild(a);var x=new createjs.Text(0,"bold 50px "+PRIMARY_FONT,"#000000");
x.y=60;x.textAlign="center";x.textBaseline="middle";x.lineWidth=200;x.outline=5;g.addChild(x);var z=new createjs.Text(0,"bold 50px "+PRIMARY_FONT,"#c1e401");z.y=x.y;z.textAlign="center";z.textBaseline="middle";z.lineWidth=200;g.addChild(z);g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT+h.height/2;e=g.y;(new createjs.Tween.get(g)).to({y:CANVAS_HEIGHT/2},500,createjs.Ease.quartIn).call(function(){var a=s_oSpriteLibrary.getSprite("star");d=new CAchievementStars(a,0,-40,g,"star");l=new CRollingTextController(z,
x,c,4E3,EASE_CUBIC_OUT);l.addEventListener(ON_CONTROLLER_END,k._onFinishRolling);l.addEventListener(ON_CONTROLLER_REMOVE,k._onFinishRolling);l.addRollingListener(k._onRollingText,k,[SCORE_FIRST_STAR,SCORE_SECOND_STAR,SCORE_THIRD_STAR])});h=s_oSpriteLibrary.getSprite("but_next");m=new CGfxButton(120,190,h,g);m.addEventListener(ON_MOUSE_UP,this._onContinue,this);m.pulseAnimation();h=s_oSpriteLibrary.getSprite("but_restart");n=new CGfxButton(-120,190,h,g);n.addEventListener(ON_MOUSE_UP,this._onRestart,
this);this._sendScore();playSound("win",1,0)};this.unload=function(){d.unload();l.unload();f.off("mousedown",function(){});s_oStage.removeChild(f);g.removeAllChildren(f);m.unload();n.unload()};this._sendScore=function(){var d=s_oLocalStorage.getItemJson(LOCALSTORAGE_SCORE),e=a*STAGE_PER_WORLD+c;d[e]<b&&(d[e]=b,s_oLocalStorage.setItemJson(LOCALSTORAGE_SCORE,d));for(e=h=0;e<d.length;e++)h+=d[e];$(s_oMain).trigger("save_score",h)};this._onContinue=function(){(new createjs.Tween.get(f)).to({alpha:0},
500);(new createjs.Tween.get(g)).to({y:e},400,createjs.Ease.backIn).call(function(){k.unload();s_oGame.nextLevel()})};this._onRestart=function(){(new createjs.Tween.get(f)).to({alpha:0},500);(new createjs.Tween.get(g)).to({y:e},400,createjs.Ease.backIn).call(function(){k.unload();s_oGame.restartGame()})};this._onFinishRolling=function(){};this._onRollingRemoved=function(){};this._onRollingText=function(a){d.playManualMode(a,STAR_EFFECT_SCALE)};k=this;this._init(a,c,b)}
var STAR_EFFECT_ALPHA=0,STAR_EFFECT_SCALE=1;
function CAchievementStars(a,c,b,e,h){var g,f,k,d,l;this._init=function(a,b,c,e,h){g=3;d=new createjs.Container;d.x=b;d.y=c;e.addChild(d);b=a.width/2;c=a.height;a=new createjs.SpriteSheet({images:[a],frames:{width:b,height:c,regX:b/2,regY:c/2},animations:{lit:[0],unlit:[1]}});f=[];for(c=0;c<g;c++)f[c]=createSprite(a,"unlit",0,0,0,0),f[c].x=-((g-1)*(b+0))/2+c*(b+0),d.addChild(f[c]);k=[];for(c=0;c<g;c++)k[c]=createSprite(a,"lit",0,0,0,0),k[c].x=-((g-1)*(b+0))/2+c*(b+0),k[c].scaleX=k[c].scaleY=0,k[c].alpha=
0,d.addChild(k[c]);k[1].y=-10;k[0].y=10;k[2].y=10;f[1].y=-10;f[0].y=10;f[2].y=10};this.unload=function(){for(var a=0;a<g;a++)new createjs.Tween.removeTweens(k[a]);e.removeChild(d)};this.getContainer=function(){return d};this.startLitStar=function(a){for(var b=0;b<a;b++)k[b].scaleX=k[b].scaleY=1,k[b].alpha=1};this.playSequentialMode=function(a,b,c){b/=a-1;switch(c){case STAR_EFFECT_SCALE:for(c=0;c<g;c++)k[c].alpha=1;for(c=0;c<a;c++)(new createjs.Tween.get(k[c])).wait(c*b).call(function(){l._playSound()}).to({scaleX:1,
scaleY:1},1500,createjs.Ease.elasticOut);break;case STAR_EFFECT_ALPHA:for(c=0;c<g;c++)k[c].scaleX=k[c].scaleY=1;for(c=0;c<a;c++)(new createjs.Tween.get(k[c])).wait(c*b).call(function(){l._playSound()}).to({alpha:1},750)}};this.playManualMode=function(a,b){switch(b){case STAR_EFFECT_SCALE:k[a].alpha=1;(new createjs.Tween.get(k[a])).to({scaleX:1,scaleY:1},1500,createjs.Ease.elasticOut);break;case STAR_EFFECT_ALPHA:k[a].scaleX=k[a].scaleY=1,(new createjs.Tween.get(k[a])).to({alpha:1},750)}this._playSound()};
this._playSound=function(){playSound(h,1,0)};l=this;this._init(a,c,b,e,h)}var LOCALSTORAGE_SCORE="score";
function CLocalStorage(a){this._init=function(a){var b=window.localStorage.getItem(a);if(null===b||void 0===b){window.localStorage.setItem(a,!0);a=[];for(b=0;12>b;b++)a[b]=0;this.setItemJson(LOCALSTORAGE_SCORE,a)}};this.setItem=function(c,b){window.localStorage.setItem(a+"_"+c,b)};this.getItem=function(c){return window.localStorage.getItem(a+"_"+c)};this.setItemJson=function(c,b){localStorage.setItem(a+"_"+c,JSON.stringify(b))};this.getItemJson=function(c){return JSON.parse(localStorage.getItem(a+
"_"+c))};this._init(a)}
function CCongratulationPanel(){var a,c,b,e;this._init=function(){c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;c.on("mousedown",function(){});s_oStage.addChild(c);(new createjs.Tween.get(c)).to({alpha:.7},500);b=new createjs.Container;s_oStage.addChild(b);var h=s_oSpriteLibrary.getSprite("credits_panel"),g=createBitmap(h);g.regX=h.width/2;g.regY=h.height/2;b.addChild(g);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT+h.height/2;a=b.y;(new createjs.Tween.get(b)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.quartIn);g=new createjs.Text(TEXT_CONGRATULATION,"bold 34px "+PRIMARY_FONT,"#000000");g.y=-h.height/2+120;g.textAlign="center";g.textBaseline="middle";g.lineWidth=400;g.outline=5;b.addChild(g);h=new createjs.Text(TEXT_CONGRATULATION,"bold 34px "+PRIMARY_FONT,"#ffd000");h.y=g.y;h.textAlign="center";h.textBaseline="middle";h.lineWidth=400;b.addChild(h);h=new createjs.Text(TEXT_DEFEATED_ALL,"bold 24px "+PRIMARY_FONT,"#000000");h.y=-20;h.textAlign="center";h.textBaseline="middle";
h.lineWidth=400;h.outline=5;b.addChild(h);g=new createjs.Text(TEXT_DEFEATED_ALL,"bold 24px "+PRIMARY_FONT,"#ffd000");g.y=h.y;g.textAlign="center";g.textBaseline="middle";g.lineWidth=400;b.addChild(g);for(var g=s_oLocalStorage.getItemJson(LOCALSTORAGE_SCORE),f=h=0;f<g.length;f++)h+=g[f];$(s_oMain).trigger("save_score",h);$(s_oMain).trigger("share_event",h);g=new createjs.Text(TEXT_TOTAL_SCORE+" "+h,"bold 24px "+PRIMARY_FONT,"#000000");g.y=100;g.textAlign="center";g.textBaseline="middle";g.lineWidth=
500;g.outline=5;b.addChild(g);h=new createjs.Text(TEXT_TOTAL_SCORE+" "+h,"bold 24px "+PRIMARY_FONT,"#ffd000");h.y=g.y;h.textAlign="center";h.textBaseline="middle";h.lineWidth=500;b.addChild(h);h=s_oSpriteLibrary.getSprite("but_exit");e=new CGfxButton(250,-150,h,b);e.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){e.setClickable(!1);(new createjs.Tween.get(c)).to({alpha:0},500);(new createjs.Tween.get(b)).to({y:a},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(c);
s_oStage.removeChild(b);e.unload();s_oGame.onExit()});c.off("mousedown",function(){})};this._init()}
function CAreYouSurePanel(){var a,c,b,e,h,g;this._init=function(){e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e.alpha=0;e.on("mousedown",function(){});s_oStage.addChild(e);(new createjs.Tween.get(e)).to({alpha:.7},500);h=new createjs.Container;s_oStage.addChild(h);var f=s_oSpriteLibrary.getSprite("credits_panel"),g=createBitmap(f);g.regX=f.width/2;g.regY=f.height/2;h.addChild(g);h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT+f.height/2;a=h.y;(new createjs.Tween.get(h)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.quartIn);g=new createjs.Text(TEXT_ARE_SURE,"bold 34px "+PRIMARY_FONT,"#000000");g.y=-f.height/2+120;g.textAlign="center";g.textBaseline="middle";g.lineWidth=400;g.outline=5;h.addChild(g);f=new createjs.Text(TEXT_ARE_SURE,"bold 34px "+PRIMARY_FONT,"#c1e401");f.y=g.y;f.textAlign="center";f.textBaseline="middle";f.lineWidth=400;h.addChild(f);c=new CGfxButton(110,80,s_oSpriteLibrary.getSprite("but_yes_big"),h);c.addEventListener(ON_MOUSE_UP,this._onButYes,this);b=new CGfxButton(-110,
80,s_oSpriteLibrary.getSprite("but_exit_big"),h);b.addEventListener(ON_MOUSE_UP,this._onButNo,this);b.pulseAnimation()};this._onButYes=function(){b.setClickable(!1);c.setClickable(!1);(new createjs.Tween.get(e)).to({alpha:0},500);(new createjs.Tween.get(h)).to({y:a},400,createjs.Ease.backIn).call(function(){g.unload();s_oGame.onExit()})};this._onButNo=function(){b.setClickable(!1);c.setClickable(!1);(new createjs.Tween.get(e)).to({alpha:0},500);(new createjs.Tween.get(h)).to({y:a},400,createjs.Ease.backIn).call(function(){g.unload()})};
this.unload=function(){b.unload();c.unload();s_oStage.removeChild(e);s_oStage.removeChild(h);e.off("mousedown",function(){})};g=this;this._init()};
