function CHelpPanel(a,e,b){var c,f,d;this._init=function(a,b,e){f=createBitmap(e);c=new createjs.Text(TEXT_HELP,"bold 40px "+FONT_GAME,"#ffffff");c.textAlign="left";c.x=140;c.y=470;c.lineWidth=300;c.shadow=new createjs.Shadow("#000000",2,2,2);d=new createjs.Container;d.x=a;d.y=b;d.addChild(f,c);s_oStage.addChild(d)};this.unload=function(){s_oStage.removeChild(d)};this._onExitHelp=function(){this.unload();s_oGame._onExitHelp()};this._init(a,e,b)}
function CGfxButton(a,e,b){var c,f,d;this._init=function(a,b,e){c=[];f=[];d=createBitmap(e);d.x=a;d.y=b;d.regX=e.width/2;d.regY=e.height/2;s_oStage.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);s_oStage.removeChild(d)};this.setVisible=function(a){d.visible=a};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){c[a]=b;f[a]=d};this.buttonRelease=
function(){d.scaleX=1;d.scaleY=1;c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(f[ON_MOUSE_UP])};this.buttonDown=function(){d.scaleX=.9;d.scaleY=.9;c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN])};this.setPosition=function(a,b){d.x=a;d.y=b};this.setX=function(a){d.x=a};this.setY=function(a){d.y=a};this.getButtonImage=function(){return d};this.getX=function(){return d.x};this.getY=function(){return d.y};this._init(a,e,b);return this}
function CGame(a){var e,b=-1,c,f,d,g,h,k,q,l,m,n;this._init=function(){f=c=0;e=!0;b=-1;var a=new createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);h=new CScrollingBg(s_oSpriteLibrary.getSprite("bg_scroll"));a=s_oSpriteLibrary.getSprite("floor");l=createBitmap(a);l.y=CANVAS_HEIGHT-a.height;s_oStage.addChild(l);g=HERO_START_Y=l.y;q=new CObstacle(s_oSpriteLibrary.getSprite("obstacle"));k=new CHero(HERO_START_X,g);m=new CInterface;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||setVolume(s_oSoundTrackSnd,
.4);$(s_oMain).trigger("start_level",1);b=GAME_STATE_BEFORE_START};this.unload=function(){s_oStage.removeChild(h);q.unload();k.unload();m.unload()};this.tapScreen=function(){b!==GAME_STATE_GAME_OVER&&(e?(e=!1,k.start(),d=0,b=GAME_STATE_TRAINING):k.moveLeft())};this._resetLevel=function(){this.unload();this._init()};this.collisionFound=function(){k.dead();b=GAME_STATE_GAME_OVER};this.increaseScore=function(){c++;m.refreshScore(c);k.laugh()};this.gameOver=function(){b=-1;c>f&&(f=c);n=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));
n.show(c,f)};this.onRestartGame=function(){$(s_oMain).trigger("restart_level",1);this._resetLevel()};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",f)};this.update=function(){switch(b){case GAME_STATE_TRAINING:d+=s_iTimeElaps;d>TIME_TRAINING?(d=0,b=GAME_STATE_START):k.update();break;case GAME_STATE_START:k.update(),q.update(k.getSprite(),BG_SPEED),h.update(BG_SPEED),l.y<CANVAS_HEIGHT&&(l.y+=
BG_SPEED)}};s_oGame=this;HERO_START_X=a.hero_x;HERO_RIGHT_ACCELLERATION=a.hero_right_speed;BG_SPEED=a.bg_speed;TIME_TRAINING=a.time_training;DIST_AMONG_OBSTACLES=a.dist_among_obst;OBSTACLE_WIDTH_DIST=a.obst_width_dist;this._init()}var s_oGame;
function CEndPanel(a){var e,b,c,f,d,g,h;this._init=function(a){e=createBitmap(a);f=new createjs.Text("","bold 70px "+FONT_GAME,"#ffffff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-152;f.textAlign="center";f.shadow=new createjs.Shadow("#000000",2,2,2);b=new createjs.Text("","bold 52px "+FONT_GAME,"#ffffff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2-20;b.textAlign="center";b.shadow=new createjs.Shadow("#000000",2,2,2);c=new createjs.Text("","bold 42px "+FONT_GAME,"#ffffff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/
2+100;c.textAlign="center";c.shadow=new createjs.Shadow("#000000",2,2,2);a=s_oSpriteLibrary.getSprite("but_play");d=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-350,a,TEXT_PLAY_AGAIN,FONT_GAME,"#ffffff",40,!1);d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);a=s_oSpriteLibrary.getSprite("but_play");g=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-250,a,TEXT_EXIT,FONT_GAME,"#ffffff",40,!1);g.addEventListener(ON_MOUSE_UP,this._onExit,this);h=new createjs.Container;h.alpha=0;h.visible=!1;h.addChild(e,
b,c,f,d.getButtonImage(),g.getButtonImage());s_oStage.addChild(h)};this.show=function(a,d){f.text=TEXT_GAMEOVER;b.text=TEXT_SCORE+": "+a;c.text=TEXT_BEST_SCORE+": "+d;h.visible=!0;createjs.Tween.get(h).to({alpha:1},500).call(function(){$(s_oMain).trigger("show_interlevel_ad")});$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("save_score",a)};this._onButPlayRelease=function(){d.unload();s_oStage.removeChild(h);s_oGame.onRestartGame()};this._onExit=function(){d.unload();s_oStage.removeChild(h);
s_oMain.gotoMenu()};this._init(a);return this}
function CSpriteLibrary(){var a,e,b,c,f,d;this.init=function(g,h,k){b=e=0;c=g;f=h;d=k;a={}};this.addSprite=function(b,d){a.hasOwnProperty(b)||(a[b]={szPath:d,oSprite:new Image},e++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(d)};this._onSpriteLoaded=function(){c.call(d);++b==e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return e}}
var CANVAS_WIDTH=768,CANVAS_HEIGHT=1200,EDGEBOARD_X=40,EDGEBOARD_Y=120,DISABLE_SOUND_MOBILE=!1,FONT_GAME="Arial",FPS_TIME=1E3/24,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,GAME_STATE_BEFORE_START=0,GAME_STATE_TRAINING=1,GAME_STATE_START=2,GAME_STATE_GAME_OVER=3,HERO_START_X,HERO_START_Y,HERO_RIGHT_ACCELLERATION,BG_SPEED,TIME_TRAINING,DIST_AMONG_OBSTACLES,OBSTACLE_WIDTH_DIST,TOLERANCE_NEXT_OBST_WIDTH=
100,TIME_ROT_HAMMER=2E3;
function CToggle(a,e,b,c){var f,d,g,h;this._init=function(a,b,c,e){d=[];g=[];var n=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_false:[0,1],state_true:[1,2]}});f=e;h=createSprite(n,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);h.x=a;h.y=b;h.stop();s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);s_oStage.removeChild(h)};
this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.setPosition=function(a,b){h.x=a;h.y=b};this.addEventListener=function(a,b,c){d[a]=b;g[a]=c};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;f=!f;h.gotoAndStop("state_"+f);d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(g[ON_MOUSE_UP],f)};this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this._init(a,e,b,c)}var s_iOffsetX=s_iOffsetY=0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}window.addEventListener("orientationchange",onOrientationChange);
function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(a){var e=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var f=b.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var d=b.createElement("div");d.id="vpw-test-d";d.style.cssText="position:absolute;top:-1000px";d.innerHTML="<style>@media("+e+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+e+":7px!important}}</style>";f.appendChild(d);c.insertBefore(f,b.head);
a=7==d["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(f)}else a=window["inner"+a];return a}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var e=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,e/CANVAS_WIDTH),c=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,f=0;b<a?(f=a-b,b+=f,c+=CANVAS_WIDTH/CANVAS_HEIGHT*f):c<e&&(f=e-c,c+=f,b+=CANVAS_HEIGHT/CANVAS_WIDTH*f);var f=a/2-b/2,d=e/2-c/2,g=CANVAS_WIDTH/c;if(d*g<-EDGEBOARD_X||f*g<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),e/(CANVAS_WIDTH-2*
EDGEBOARD_X)),c=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,f=(a-b)/2,d=(e-c)/2,g=CANVAS_WIDTH/c;s_iOffsetX=-1*d*g;s_iOffsetY=-1*f*g;0<=f&&(s_iOffsetY=0);0<=d&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",c+"px");$("#canvas").css("height",b+"px");0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",d+"px")}}
function createBitmap(a,e,b){var c=new createjs.Bitmap(a),f=new createjs.Shape;e&&b?f.graphics.beginFill("#fff").drawRect(0,0,e,b):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=f;return c}function createSprite(a,e,b,c,f,d){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-b,-c,f,d);a.hitArea=e;return a}
function randomFloatBetween(a,e,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(b))}function shuffle(a){for(var e=a.length,b,c;0!==e;)c=Math.floor(Math.random()*e),--e,b=a[e],a[e]=a[c],a[c]=b;return a}function formatTime(a){a/=1E3;var e=Math.floor(a/60);a=parseFloat(a-60*e).toFixed(1);var b="",b=10>e?b+("0"+e+":"):b+(e+":");return b=10>a?b+("0"+a):b+a}
function checkRectCollision(a,e){var b,c;b=getBounds(a,.9);c=getBounds(e,.98);return calculateIntersection(b,c)}function calculateIntersection(a,e){var b,c,f,d,g,h,k,q;b=a.x+(f=a.width/2);c=a.y+(d=a.height/2);g=e.x+(h=e.width/2);k=e.y+(q=e.height/2);b=Math.abs(b-g)-(f+h);c=Math.abs(c-k)-(d+q);return 0>b&&0>c?(b=Math.min(Math.min(a.width,e.width),-b),c=Math.min(Math.min(a.height,e.height),-c),{x:Math.max(a.x,e.x),y:Math.max(a.y,e.y),width:b,height:c,rect1:a,rect2:e}):null}
function getBounds(a,e){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,f=c.length,d,g;for(g=0;g<f;g++)d=getBounds(c[g],1),d.x<b.x&&(b.x=d.x),d.y<b.y&&(b.y=d.y),d.x+d.width>b.x2&&(b.x2=d.x+d.width),d.y+d.height>b.y2&&(b.y2=d.y+d.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var h,k;a instanceof createjs.Bitmap?
(f=a.sourceRect||a.image,g=f.width*e,h=f.height*e):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(f=a.spriteSheet.getFrame(a.currentFrame),g=f.rect.width,h=f.rect.height,c=f.regX,k=f.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);c=c||0;g=g||0;k=k||0;h=h||0;b.regX=c;b.regY=k;f=a.localToGlobal(0-c,0-k);d=a.localToGlobal(g-c,h-k);g=a.localToGlobal(g-c,0-k);c=a.localToGlobal(0-c,h-k);b.x=Math.min(Math.min(Math.min(f.x,
d.x),g.x),c.x);b.y=Math.min(Math.min(Math.min(f.y,d.y),g.y),c.y);b.width=Math.max(Math.max(Math.max(f.x,d.x),g.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(f.y,d.y),g.y),c.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};function playSound(a,e,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:e}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}
function setVolume(a,e){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=e}function setMute(a,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(e)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var e=window.location.search.substring(1).split("&"),b=0;b<e.length;b++){var c=e[b].split("=");if(c[0]==a)return c[1]}}
function CTextButton(a,e,b,c,f,d,g,h){var k,q,l;this._init=function(a,b,c,d,f,e,g,h){k=[];q=[];var v=createBitmap(c),u=Math.ceil(g/20),r=new createjs.Text(d,"bold "+g+"px "+f,"#000000");r.textAlign="center";var t=r.getBounds();r.x=c.width/2+u;r.y=(c.height-t.height)/2+u;d=new createjs.Text(d,"bold "+g+"px "+f,e);d.textAlign="center";t=d.getBounds();d.x=c.width/2;d.y=(c.height-t.height)/2;l=new createjs.Container;l.x=a;l.y=b;l.regX=c.width/2;l.regY=c.height/2;l.addChild(v,r,d);!1!==h&&s_oStage.addChild(l);
this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){k[a]=b;q[a]=c};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(q[ON_MOUSE_UP])};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(q[ON_MOUSE_DOWN])};
this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(a,e,b,c,f,d,g,h);return this}
function CScrollingBg(a){var e,b,c;this._init=function(a){c=a;b=[];for(var d=-a.height;d<CANVAS_HEIGHT;){var g=createBitmap(a);g.y=d;d+=a.height;b.push(g);s_oStage.addChild(g)}e=0};this.update=function(a){for(var d=0;d<b.length;d++)b[d].y>CANVAS_HEIGHT&&(b[d].y=b[e].y-c.height,e=d),b[d].y+=a};this._init(a)}
function CPreloader(){var a,e,b,c,f,d,g;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();g=new createjs.Container;s_oStage.addChild(g)};this.unload=function(){g.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(d).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));g.addChild(h);h=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(h);c.x=CANVAS_WIDTH/2-h.width/2;c.y=CANVAS_HEIGHT-250;g.addChild(c);a=h.width;e=h.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,e);g.addChild(f);c.mask=
f;b=new createjs.Text("","30px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-250;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";g.addChild(b);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;g.addChild(d)};this.refreshLoader=function(d){b.text=d+"%";f.graphics.clear();d=Math.floor(d*a/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,d,e)};this._init()}
function CObstacle(a){var e,b,c,f,d,g,h,k;this._init=function(a){e=-Math.floor(a.width/3);b=-Math.floor(a.width/10);c=a.height/2;this._initLevel()};this.unload=function(){for(var a=0;a<g;a++)s_oStage.addChild(g[a])};this._initLevel=function(){var c=s_oSpriteLibrary.getSprite("hammer"),l=100,m=Math.floor(randomFloatBetween(e,b));g=[];k=[];for(h=[];l>-(2*CANVAS_HEIGHT+a.height);){var n=new createjs.Container;n.x=m;n.y=l;s_oStage.addChild(n);var p=createBitmap(a);p.regX=a.width/2;p.regY=a.height/2;n.addChild(p);
h.push(p);p=createBitmap(c);p.x=a.width/2-30;p.y=a.height/2-30;p.regX=c.width/2;p.regY=0;n.addChild(p);k.push(p);this.rotateHammer(k.length-1,30,TIME_ROT_HAMMER/2);g.push(n);n=new createjs.Container;n.x=m+a.width+OBSTACLE_WIDTH_DIST;n.y=l;s_oStage.addChild(n);p=createBitmap(a);p.regX=a.width/2;p.regY=a.height/2;n.addChild(p);h.push(p);p=createBitmap(c);p.x=-a.width/2+30;p.y=a.height/2-30;p.regX=c.width/2;p.regY=0;n.addChild(p);k.push(p);this.rotateHammer(k.length-1,30,TIME_ROT_HAMMER/2);g.push(n);
l-=DIST_AMONG_OBSTACLES;m=this.assignNextWidth(m)}f=g.length-1;d=-1};this.restartLevel=function(){for(var c=CANVAS_HEIGHT+a.height,h=Math.floor(randomFloatBetween(e,b)),m=0;m<g.length;m+=2)g[m].x=h,g[m].y=c,g[m+1].x=h+a.width+OBSTACLE_WIDTH_DIST,g[m+1].y=c,k[m].rotation=0,k[m+1].rotation=0,c+=DIST_AMONG_OBSTACLES,h=this.assignNextWidth(h);f=g.length-1;d=-1};this.rotateHammer=function(a,b,c){var d=this;createjs.Tween.get(k[a]).to({rotation:b},c,createjs.Ease.cubicInOut).call(function(){b*=-1;d.rotateHammer(a,
b,TIME_ROT_HAMMER)})};this.assignNextWidth=function(a){var c=a-TOLERANCE_NEXT_OBST_WIDTH;c<e&&(c=e);a+=TOLERANCE_NEXT_OBST_WIDTH;a>b&&(a=b);return Math.floor(randomFloatBetween(c,a))};this.update=function(b,e){for(var m=0;m<g.length;m+=2){g[m].y>CANVAS_HEIGHT+c&&(g[m].y=g[f].y-c-DIST_AMONG_OBSTACLES,g[m+1].y=g[f].y-c-DIST_AMONG_OBSTACLES,g[m].x=this.assignNextWidth(g[f].x),g[m+1].x=g[m].x+a.width+OBSTACLE_WIDTH_DIST,f=m);g[m].y+=e;g[m+1].y+=e;if(ndgmr.checkPixelCollision(b,h[m],0)||ndgmr.checkPixelCollision(b,
h[m+1],0)){s_oGame.collisionFound();break}if(ndgmr.checkPixelCollision(b,k[m],0)||ndgmr.checkPixelCollision(b,k[m+1],0)){s_oGame.collisionFound();break}d!==m&&g[m].y>HERO_START_Y&&(d=m,s_oGame.increaseScore())}};this._init(a)}
function CMenu(){var a,e,b,c,f,d;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(b);var g=s_oSpriteLibrary.getSprite("but_play");c=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-250,g,TEXT_PLAY,FONT_GAME,"#ffffff",50);c.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-g.height/2-10,e=g.height/2+10,f=new CToggle(a,e,g,s_bAudioActive),f.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this),setVolume(s_oSoundTrackSnd,.8);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(d);createjs.Tween.get(d).to({alpha:0},1E3).call(function(){d.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(b,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||f.setPosition(a-b,c+e)};this.unload=function(){c.unload();c=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f.unload(),f=null;s_oStage.removeAllChildren();
s_oMenu=b=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame();$(s_oMain).trigger("start_session")};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oMenu=this;this._init()}var s_oMenu=null;
function CMain(a){var e=!1,b=0,c=0,f=STATE_LOADING,d,g,h;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;d=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();e=!0};this.soundLoaded=function(){b++;d.refreshLoader(Math.floor(b/c*100));if(b===c){d.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrackSnd=playSound("soundtrack",.8,-1);this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?
(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/jetpack.ogg","jetpack"),createjs.Sound.registerSound("./sounds/laugh.ogg","laugh")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,
this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/jetpack.mp3","jetpack"),createjs.Sound.registerSound("./sounds/laugh.mp3","laugh")),c+=4)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");
s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("hero","./sprites/hero.png");s_oSpriteLibrary.addSprite("floor","./sprites/floor.png");s_oSpriteLibrary.addSprite("bg_scroll","./sprites/bg_scroll.png");s_oSpriteLibrary.addSprite("bg_game",
"./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("obstacle","./sprites/obstacle.png");s_oSpriteLibrary.addSprite("hammer","./sprites/hammer.png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;d.refreshLoader(Math.floor(b/c*100));if(b===c){d.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrackSnd=playSound("soundtrack",.8,-1);this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};
this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(){g=new CGame(h);f=STATE_GAME};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){e=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();e=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(e){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;
s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&g.update();s_oStage.update(a)}};s_oMain=this;h=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oSoundTrackSnd,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary;TEXT_GAMEOVER="GAME OVER";TEXT_CONGRATS="CONGRATULATIONS";TEXT_SCORE="SCORE";TEXT_BEST_SCORE="BEST SCORE";TEXT_TIME="TIME";TEXT_EXIT="EXIT";TEXT_PLAY="PLAY";
TEXT_PLAY_AGAIN="PLAY AGAIN";TEXT_HELP="TAP THE SCREEN TO SWING THE JETPACK AND AVOID THE OBSTACLES";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CInterface(){var a,e,b,c,f,d,g,h,k,q,l;this._init=function(){var m=this;a=CANVAS_WIDTH/2;e=35;q=new createjs.Text(TEXT_SCORE+": 0","bold 42px "+FONT_GAME,"#FFFF00");q.shadow=new createjs.Shadow("#000000",2,2,2);q.x=a;q.y=e;q.textAlign="center";s_oStage.addChild(q);l=new CHelpPanel(0,0,s_oSpriteLibrary.getSprite("bg_help"));k=new createjs.Shape;k.graphics.beginFill("white").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=.01;s_oStage.addChild(k);k.on("pressup",function(){m._onTapScreen()});
var n=s_oSpriteLibrary.getSprite("but_exit");f=CANVAS_WIDTH-n.height/2-10;d=n.height/2+10;g=new CGfxButton(f,d,n,!0);g.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-n.width/2-90,c=n.height/2+10,h=new CToggle(b,c,n,s_bAudioActive),h.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(a,k){g.setPosition(f-a,k+d);!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||h.setPosition(b-a,k+c);q.y=e+k};this.unload=function(){g.unload();g=null;s_oStage.removeChild(q);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h.unload(),h=null;var a=this;k.off("pressup",function(){a._onTapScreen()});s_oStage.removeChild(k);l.unload();s_oInterface=null};this.refreshScore=function(a){q.text=TEXT_SCORE+": "+a};this._onTapScreen=function(){l.unload();s_oGame.tapScreen()};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHero(a,e){var b,c,f,d,g,h,k,q=null;this._init=function(a,e){g=f=0;var k=s_oSpriteLibrary.getSprite("hero"),p=new createjs.SpriteSheet({framerate:24,images:[k],frames:{width:100,height:100,regX:50,regY:50},animations:{start:[0],idle:[1,20,"idle"],dead:[21]}});h=createSprite(p,"start",50,50,100,100);h.x=b=a;h.y=c=e;s_oStage.addChild(h);d=k.height/2};this.unload=function(){s_oStage.removeChild(h)};this.reset=function(){g=f=0;h.x=b;h.y=c};this.start=function(){createjs.Tween.removeTweens(h);
h.gotoAndPlay("idle");if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k=playSound("jetpack",1,-1);this.moveLeft()};this.dead=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)stopSound(k),q=playSound("game_over",1,0);h.gotoAndPlay("dead");createjs.Tween.get(h).to({y:CANVAS_HEIGHT+200},1E3,createjs.Ease.backIn).call(function(){s_oGame.gameOver()})};this.laugh=function(){null===q&&.25>Math.random()&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||playSound("laugh",1,0))};this.moveLeft=function(){f=10*
HERO_RIGHT_ACCELLERATION;HERO_RIGHT_ACCELLERATION*=-1;h.scaleX*=-1};this.getBottom=function(){return h.y+d};this.getX=function(){return h.x};this.getY=function(){return h.y};this.getRadius=function(){return h.width/2};this.getSprite=function(){return h};this.update=function(){f+=HERO_RIGHT_ACCELLERATION;h.x>=CANVAS_WIDTH?(h.x=CANVAS_WIDTH,s_oGame.collisionFound()):0>=h.x?(h.x=0,s_oGame.collisionFound()):(h.x+=f,0<f?(g+=2,20<g&&(g=20)):(g-=2,-20>g&&(g=-20)),h.rotation=g)};this._init(a,e)};