function CInterface(a){var g,k,b,d,e,l,c,h,f,p,r,q,v,n,u,x,C,J,y,D,H,z,t,A,V,W,S,Q,X,Z,K,P,T,M,N,O,I,F,E,U,R,Y,w,B,G,m,L,ba,aa;this._init=function(m){var a;I=createBitmap(s_oSpriteLibrary.getSprite("frame"));s_oStage.addChild(I);s_oStage.setChildIndex(I,s_oStage.numChildren-1);var L=s_oSpriteLibrary.getSprite("but_exit");f=a=CANVAS_WIDTH-(L.width/2+20);p=L.height/2+20;q=new CGfxButton(f,p,L);q.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)L=s_oSpriteLibrary.getSprite("icon_audio"),
c=a=CANVAS_WIDTH-L.width/2-50,h=L.height/2+20,r=new CToggle(c,h,L,s_bAudioActive),r.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);a=s_oSpriteLibrary.getSprite("fan");L=new createjs.SpriteSheet({images:[a],frames:{width:a.width/3,height:a.height,regX:a.width/2/3,regY:a.height/2},animations:{move:[0,2,"move",.5]}});T=createSprite(L,"move",a.width/2/2,a.height/2,a.width/3,a.height);T.x=CANVAS_WIDTH/2;T.y=CANVAS_HEIGHT/2-45;s_oStage.addChild(T);s_oStage.setChildIndex(T,1);Y=new createjs.Container;
U=new createjs.Text("0"+m,"bold 72px "+PRIMARY_FONT,"#02724e");U.textAlign="center";U.textBaseline="alphabetic";U.x=-220;U.y=70;R=new createjs.Text("0"+m,"bold 72px "+PRIMARY_FONT,"#02724e");R.textAlign="center";R.textBaseline="alphabetic";R.x=220;R.y=70;Y.addChild(U,R);Y.x=CANVAS_WIDTH/2;Y.y=CANVAS_HEIGHT/2;s_oStage.addChild(Y);s_oStage.setChildIndex(Y,1);a=s_oSpriteLibrary.getSprite("panel_score");m=createBitmap(a);m.regX=a.width/2;m.regY=a.height/2;u=new createjs.Text("0","bold 40px "+PRIMARY_FONT,
"#ffffff");u.textAlign="left";u.textBaseline="alphabetic";u.x=-80;u.y=13;x=new createjs.Text("0","bold 40px "+PRIMARY_FONT,"#000000");x.textAlign="left";x.textBaseline="alphabetic";x.x=-80;x.y=13;x.outline=.2;M=new createjs.Container;M.addChild(m,u,x);e=CANVAS_WIDTH/2-300;l=CANVAS_HEIGHT/2-230;M.x=e;M.y=l;s_oStage.addChild(M);a=s_oSpriteLibrary.getSprite("panel_hearth");m=createBitmap(a);m.regX=a.width/2;m.regY=a.height/2;C=new createjs.Text("X3","bold 36px "+PRIMARY_FONT,"#ffffff");C.textAlign="left";
C.textBaseline="alphabetic";C.x=0;C.y=13;J=new createjs.Text("X3","bold 36px "+PRIMARY_FONT,"#000000");J.textAlign="left";J.textBaseline="alphabetic";J.x=0;J.y=13;J.outline=.2;N=new createjs.Container;N.addChild(m,C,J);b=CANVAS_WIDTH/2-90;d=CANVAS_HEIGHT/2-230;N.x=b;N.y=d;s_oStage.addChild(N);a=s_oSpriteLibrary.getSprite("panel_time");m=createBitmap(a);m.regX=a.width/2;m.regY=a.height/2;y=new createjs.Text(TIME_LEVEL[0],"bold 36px "+PRIMARY_FONT,"#ffffff");y.textAlign="left";y.textBaseline="alphabetic";
y.x=-4;y.y=13;D=new createjs.Text(TIME_LEVEL[0],"bold 36px "+PRIMARY_FONT,"#000000");D.textAlign="left";D.textBaseline="alphabetic";D.x=-4;D.y=13;D.outline=.2;O=new createjs.Container;O.addChild(m,y,D);g=CANVAS_WIDTH/2+40;k=CANVAS_HEIGHT/2-230;O.x=CANVAS_WIDTH/2+80;O.y=CANVAS_HEIGHT/2-180;s_oStage.addChild(O);ba=!1;this.createContrast();this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(m,a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.setPosition(c-m,h+a);q.setPosition(f-
m,p+a);M.x=e+m;M.y=l+a;N.x=b+m;N.y=d+a;O.x=g+m;O.y=k+a};this.createContrast=function(){aa=new createjs.Shape;aa.graphics.beginFill("black").drawRect(80,85,800,370);aa.alpha=0;s_oStage.addChild(aa);s_oStage.setChildIndex(aa,3)};this.refreshLife=function(m){C.text="X"+m;J.text="X"+m};this.refreshLevel=function(m){m+=1;9<m?(U.text=m,R.text=m):(U.text="0"+m,R.text="0"+m)};this.showLevelNum=function(m){var a=m+1,c;m=new createjs.Text(TEXT_LEVEL+" "+a,"bold 60px "+PRIMARY_FONT,"#ffffff");m.textAlign="left";
m.textBaseline="alphabetic";m.x=-90;m.y=0;a=new createjs.Text(TEXT_LEVEL+" "+a,"bold 60px "+PRIMARY_FONT,"#000000");a.textAlign="left";a.textBaseline="alphabetic";a.x=-90;a.y=0;a.outline=.6;c=new createjs.Container;c.addChild(m,a);c.scaleX=0;c.scaleY=0;c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;s_oStage.addChild(c);this.animContrast(.5);createjs.Tween.get(c).to({scaleX:1,scaleY:1},1E3,createjs.Ease.elasticOut).call(function(){createjs.Tween.get(c).wait(500).to({scaleX:0,scaleY:0},1E3,createjs.Ease.elasticIn).call(function(){s_oStage.removeChild(c);
s_oGame.canInput(!0);s_oGame.setPause(!1);!0===s_bMobile&&s_oGame.blockJoypad(!1)})})};this.showTimeIsUp=function(){var m,a;m=new createjs.Text(TEXT_TIME_IS_UP,"bold 60px "+PRIMARY_FONT,"#ffffff");m.textAlign="center";m.textBaseline="alphabetic";m.x=0;m.y=0;a=new createjs.Text(TEXT_TIME_IS_UP,"bold 60px "+PRIMARY_FONT,"#000000");a.textAlign="center";a.textBaseline="alphabetic";a.x=0;a.y=0;a.outline=.6;E=new createjs.Container;E.addChild(m,a);E.scaleX=0;E.scaleY=0;E.x=CANVAS_WIDTH/2;E.y=CANVAS_HEIGHT/
2;s_oStage.addChild(E);createjs.Tween.get(E).to({scaleX:1,scaleY:1},1E3,createjs.Ease.elasticOut).call(function(){createjs.Tween.get(E).wait(500).to({scaleX:0,scaleY:0},1E3,createjs.Ease.elasticIn).call(function(){s_oStage.removeChild(E);s_oGame.restartLevel()})})};this.gameOver=function(m){s_oGame.setPause(!0);q.block(!0);var a=s_oSpriteLibrary.getSprite("game_over_bg");z=createBitmap(a);z.alpha=0;s_oStage.addChild(z);a=s_oSpriteLibrary.getSprite("game_over_panel");L=createBitmap(a);L.x=CANVAS_WIDTH/
2;L.y=-a.height/2;L.regX=a.width/2;L.regY=a.height/2;s_oStage.addChild(L);F=new createjs.Container;V=new createjs.Text(TEXT_GAMEOVER,"bold 40px "+PRIMARY_FONT,"#ffffff");V.textAlign="center";V.textBaseline="alphabetic";V.x=0;V.y=40;W=new createjs.Text(TEXT_GAMEOVER,"bold 40px "+PRIMARY_FONT,"#000000");W.textAlign="center";W.textBaseline="alphabetic";W.x=0;W.y=40;W.outline=.5;S=new createjs.Text(m,"bold 40px "+PRIMARY_FONT,"#ffffff");S.textAlign="center";S.textBaseline="alphabetic";S.x=0;S.y=90;Q=
new createjs.Text(m,"bold 40px "+PRIMARY_FONT,"#000000");Q.textAlign="center";Q.textBaseline="alphabetic";Q.x=0;Q.y=90;Q.outline=.5;F.addChild(V,W,S,Q);F.x=CANVAS_WIDTH/2;F.y=-200;s_oStage.addChild(F);createjs.Tween.get(L).to({y:190},1E3,createjs.Ease.backOut);createjs.Tween.get(z).to({alpha:1},1E3,createjs.Ease.backOut).call(function(){createjs.Tween.get(F).to({y:CANVAS_HEIGHT/2-130},1E3,createjs.Ease.bounceOut).call(function(){var m=s_oSpriteLibrary.getSprite("but_restart"),a=s_oSpriteLibrary.getSprite("but_exit_big");
t=new CGfxButton(CANVAS_WIDTH/2+100,CANVAS_HEIGHT/2+130,a);t.addEventListener(ON_MOUSE_UP,s_oInterface._onButReturnToMenuRelease,this);A=new CGfxButton(CANVAS_WIDTH/2-100,CANVAS_HEIGHT/2+130,m);A.addEventListener(ON_MOUSE_UP,s_oInterface._onButRestartLevelRelease,this)})});$(s_oMain).trigger("share_event",m);$(s_oMain).trigger("save_score",m);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var c;c=createjs.Sound.play("game_over");s_oSoundTrack.volume=.2;c.on("complete",function(){s_oSoundTrack.volume=
1;c=null})}};this._onButRestartLevelRelease=function(){s_oStage.removeChild(F,z,L);A.unload();t.unload();L=F=z=t=A=null;$(s_oMain).trigger("show_interlevel_ad");s_oGame.restartLevelFromGameOver();q.block(!1)};this.levelComplete=function(m,a){var c=m+1;c<BRICKS_LEVEL_POSITION.length?(H=createBitmap(s_oSpriteLibrary.getSprite("bg_level_complete")),H.alpha=0,s_oStage.addChild(H),s_oStage.setChildIndex(H,s_oStage.numChildren-1),_oButPause.block(!0),K=new createjs.Text(TEXT_LEVEL+" "+c+" "+TEXT_COMPLETE,
"bold 90px "+PRIMARY_FONT,"#ffff00"),K.textAlign="center",K.textBaseline="alphabetic",K.x=CANVAS_WIDTH/2,K.y=-120,s_oStage.addChild(K),P=new createjs.Text(TEXT_SCORE+"\n\n"+a,"bold 90px "+PRIMARY_FONT,"#ffff00"),P.textAlign="center",P.textBaseline="alphabetic",P.x=CANVAS_WIDTH/2,P.y=-120,s_oStage.addChild(P),createjs.Tween.get(H).to({alpha:.5},1E3,createjs.Ease.backOut).call(function(){createjs.Tween.get(K).to({y:CANVAS_HEIGHT/2-300},1E3,createjs.Ease.bounceOut).call(function(){createjs.Tween.get(P).to({y:CANVAS_HEIGHT/
2-100},1E3,createjs.Ease.bounceOut).call(function(){var m=s_oSpriteLibrary.getSprite("but_continue");Z=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+200,m);Z.addEventListener(ON_MOUSE_UP,s_oInterface._onButNextLevelRelease,this)})})})):this.finishGame(a)};this.finishGame=function(m){s_oGame.setPause(!0);!0===s_bMobile&&s_oGame.blockJoypad(!0);q.block(!0);var a=new createjs.Container,c=new createjs.Container;H=new createjs.Shape;H.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);
H.alpha=0;s_oStage.addChild(H);var f,b,d=50;f=new createjs.Text(TEXT_CONGRATULATIONS,"bold "+d+"px "+PRIMARY_FONT,"#ffffff");f.textAlign="center";f.textBaseline="alphabetic";f.x=0;f.y=0;f.lineWidth=700;f.lineHeight=d;b=new createjs.Text(TEXT_CONGRATULATIONS,"bold "+d+"px "+PRIMARY_FONT,"#000000");b.textAlign="center";b.textBaseline="alphabetic";b.x=0;b.y=0;b.lineWidth=700;b.outline=.4;b.lineHeight=d;a.addChild(f,b);a.x=CANVAS_WIDTH/2;a.y=-200;var h,d=50;f=new createjs.Text(TEXT_TOTAL_SCORE,"bold "+
d+"px "+PRIMARY_FONT,"#ffffff");f.textAlign="center";f.textBaseline="alphabetic";f.x=0;f.y=0;b=new createjs.Text(TEXT_TOTAL_SCORE,"bold "+d+"px "+PRIMARY_FONT,"#000000");b.textAlign="center";b.textBaseline="alphabetic";b.x=0;b.y=0;b.outline=.4;h=new createjs.Text(m,"bold "+d+"px "+PRIMARY_FONT,"#ffffff");h.textAlign="center";h.textBaseline="alphabetic";h.x=0;h.y=40;d=new createjs.Text(m,"bold "+d+"px "+PRIMARY_FONT,"#000000");d.textAlign="center";d.textBaseline="alphabetic";d.x=0;d.y=40;d.outline=
.4;c.addChild(f,b,h,d);c.x=CANVAS_WIDTH/2;c.y=-200;s_oStage.addChild(a);s_oStage.addChild(c);createjs.Tween.get(H).to({alpha:.5},1E3,createjs.Ease.backOut).call(function(){createjs.Tween.get(a).to({y:CANVAS_HEIGHT/2-150},1E3,createjs.Ease.backOut).call(function(){createjs.Tween.get(c).wait(500).to({y:CANVAS_HEIGHT/2},1E3,createjs.Ease.bounceOut).call(function(){var m=s_oSpriteLibrary.getSprite("but_play");t=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+150,m);t.setScale(.8);t.addEventListener(ON_MOUSE_UP,
s_oInterface._onButReturnToMenuRelease,this)})})});$(s_oMain).trigger("share_event",m);$(s_oMain).trigger("save_score",m)};this._onButNextLevelRelease=function(){s_oStage.removeChild(K,P,H);P=H=K=null;Z.unload();Z=null;_oButPause.block(!1);s_oGame.nextLevel()};this._onButReturnToMenuRelease=function(){s_oGame.onExit()};this.refreshScore=function(m){u.text=m;x.text=m};this.colorTime=function(m){y.color=m};this.refreshTime=function(m){y.text=m;D.text=m};this._onButPauseRelease=function(){!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("click");s_oGame.setPause(!0);X=new createjs.Shape;X.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);X.alpha=.5;s_oStage.addChild(X);v=new createjs.Text("Pause","bold 48px "+PRIMARY_FONT,"#ffffff");v.textAlign="center";v.textBaseline="alphabetic";v.x=CANVAS_WIDTH/2;v.y=CANVAS_HEIGHT/2-250;s_oStage.addChild(v);_oButPause.block(!0);var m=s_oSpriteLibrary.getSprite("but_continue");n=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2,m);n.addEventListener(ON_MOUSE_UP,
this._onButContinueRelease,this)};this._onButContinueRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");n.unload();n=null;s_oStage.removeChild(v,X);X=!1;v=null;_oButPause.block(!1);s_oGame.setPause(!1)};this.onButNextPrevPage=function(a){switch(a.page){case 1:this.helpPage1(a.level);G.block(!0);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");break;case 2:this.helpPage2(a.level);m.block(!0);G.block(!0);!1!==DISABLE_SOUND_MOBILE&&!1!==
s_bMobile||createjs.Sound.play("click");break;case 3:this.helpPage3(a.level),m.block(!0),G.block(!0),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click")}};this.helpPage1=function(a){var c,f;B&&s_oStage.removeChild(B);w||(c=s_oSpriteLibrary.getSprite("help_panel"),w=createBitmap(c),w.on("click",function(){s_oInterface.finishHelp(a);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click")},null,!0),s_oStage.addChild(w));G?(m.unload(),m=null):(c=s_oSpriteLibrary.getSprite("but_arrow"),
G=new CGfxButton(CANVAS_WIDTH/2+267,CANVAS_HEIGHT/2,c));G.addEventListenerWithParams(ON_MOUSE_UP,this.onButNextPrevPage,this,{level:a,page:2});B=new createjs.Container;c=new createjs.Text(TEXT_HELP_PAGE_1,"bold 36px "+PRIMARY_FONT,"#ffffff");c.textAlign="center";c.textBaseline="alphabetic";c.x=0;c.y=0;c.lineWidth=300;c.lineHeight=36;f=new createjs.Text(TEXT_HELP_PAGE_1,"bold 36px "+PRIMARY_FONT,"#000000");f.textAlign="center";f.textBaseline="alphabetic";f.x=0;f.y=0;f.lineWidth=300;f.outline=.6;f.lineHeight=
36;B.addChild(c,f);B.x=CANVAS_WIDTH/2+80;B.y=CANVAS_HEIGHT/2-90;B.alpha=0;createjs.Tween.get(B).to({alpha:1},500).call(function(){m&&m.block(!1);G&&G.block(!1)});s_oStage.addChild(B)};this.helpPage2=function(a){var c;s_oStage.removeChild(B);c=s_oSpriteLibrary.getSprite("but_arrow");G.addEventListenerWithParams(ON_MOUSE_UP,this.onButNextPrevPage,this,{level:a,page:3});m||(m=new CGfxButton(CANVAS_WIDTH/2-267,CANVAS_HEIGHT/2,c));m.addEventListenerWithParams(ON_MOUSE_UP,this.onButNextPrevPage,this,{level:a,
page:1});m.setScale(-1);B=new createjs.Container;a=new createjs.Text("","bold 33px "+PRIMARY_FONT,"#ffffff");a.textAlign="center";a.textBaseline="alphabetic";a.x=0;a.y=0;a.lineWidth=300;a.lineHeight=33;c=new createjs.Text("","bold 33px "+PRIMARY_FONT,"#000000");c.textAlign="center";c.textBaseline="alphabetic";c.x=0;c.y=0;c.lineWidth=300;c.outline=.3;c.lineHeight=33;!0===s_bMobile?(a.text=TEXT_HELP_PAGE_2_MOBILE,c.text=TEXT_HELP_PAGE_2_MOBILE):(a.text=TEXT_HELP_PAGE_2_PC,c.text=TEXT_HELP_PAGE_2_PC);
B.addChild(a,c);B.x=CANVAS_WIDTH/2+80;B.y=CANVAS_HEIGHT/2-100;B.alpha=0;createjs.Tween.get(B).to({alpha:1},500).call(function(){m&&m.block(!1);G&&G.block(!1)});s_oStage.addChild(B)};this.helpPage3=function(a){var c;s_oStage.removeChild(B);G.addEventListenerWithParams(ON_MOUSE_UP,this.finishHelp,this,a);m.addEventListenerWithParams(ON_MOUSE_UP,this.onButNextPrevPage,this,{level:a,page:2});B=new createjs.Container;a=new createjs.Text(TEXT_HELP_PAGE_3_PART1+" "+EXTRA_POINT+" "+TEXT_HELP_PAGE_3_PART2,
"bold 36px "+PRIMARY_FONT,"#ffffff");a.textAlign="center";a.textBaseline="alphabetic";a.x=0;a.y=0;a.lineWidth=300;a.lineHeight=36;c=new createjs.Text(TEXT_HELP_PAGE_3_PART1+" "+EXTRA_POINT+" "+TEXT_HELP_PAGE_3_PART2,"bold 36px "+PRIMARY_FONT,"#000000");c.textAlign="center";c.textBaseline="alphabetic";c.x=0;c.y=0;c.lineWidth=300;c.outline=.3;c.lineHeight=36;B.addChild(a,c);B.x=CANVAS_WIDTH/2+80;B.y=CANVAS_HEIGHT/2-90;B.alpha=0;w.off("click");createjs.Tween.get(B).to({alpha:1},500).call(function(){m.block(!1);
G.block(!1)});s_oStage.addChild(B)};this.finishHelp=function(a){s_oStage.removeChild(B);B=null;G&&(G.unload(),G=null);m&&(m.unload(),m=null);createjs.Tween.get(w).to({alpha:0},500,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(w);w=null;!1===ba&&(s_oInterface.showLevelNum(a),ba=!0)})};this.animContrast=function(m){createjs.Tween.get(aa).to({alpha:m},2E3,createjs.Ease.cubicOut)};this.unload=function(){s_oStage.removeChild(V,t,H);H=t=V=null;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!r||
(r.unload(),r=null);s_oInterface=null};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CGfxButton(a,g,k){var b,d,e,l=[],c,h;this._init=function(a,k,l){b=1;d=[];e=[];c=createBitmap(l);c.x=a;c.y=k;c.regX=l.width/2;c.regY=l.height/2;s_oStage.addChild(c);h=!1;this._initListener()};this.unload=function(){c.off("mousedown",this.buttonDown);c.off("pressup",this.buttonRelease);s_oStage.removeChild(c)};this.setVisible=function(a){c.visible=a};this._initListener=function(){c.on("mousedown",this.buttonDown);c.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){d[a]=
c;e[a]=b};this.addEventListenerWithParams=function(a,c,b,h){d[a]=c;e[a]=b;l=h};this.buttonRelease=function(){h||(c.scaleX=b,c.scaleY=b,d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(e[ON_MOUSE_UP],l))};this.buttonDown=function(){h||(c.scaleX=.9*b,c.scaleY=.9*b,d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],l))};this.setScale=function(a){b=a;c.scaleX=a;c.scaleY=a};this.setPosition=function(a,b){c.x=a;c.y=b};this.setX=function(a){c.x=a};this.setY=function(a){c.y=a};this.getButtonImage=function(){return c};
this.getX=function(){return c.x};this.getY=function(){return c.y};this.block=function(a){h=a};this._init(a,g,k);return this}
function CGame(a){function g(a){!0===P&&(32===a.keyCode&&A.length<MAX_ROPE&&s_oGame.shoot(),y||(37===a.keyCode?s_oGame.moveLeft():39===a.keyCode&&s_oGame.moveRight()));a.preventDefault();return!1}function k(a){y&&!0===P&&(37===a.keyCode&&(y=!1,z=0,D=!1,!0===P&&t.changeState("idle")),39===a.keyCode&&(y=!1,z=0,H=!1,!0===P&&t.changeState("idle")),32===a.keyCode&&(!0===D?(z=-1,t.changeState("run")):!0===H?(z=1,t.changeState("run")):!1===D&&!1===H&&(y=!1)));a.preventDefault();return!1}var b,d,e,l,c,h,
f,p,r,q=0,v,n,u,x,C,J,y,D,H,z,t,A,V,W,S,Q,X,Z,K,P,T,M,N,O,I,F,E,U,R,Y,w;this._init=function(){l=!1;v=CANVAS_WIDTH/2;n=CANVAS_HEIGHT/2;c=[];A=[];I=[];w=[];var a=s_oSpriteLibrary.getSprite("platform");p=a.width/2;r=a.height/2;J=1;C=x=u=e=0;O=CHARACTER_LIVES;Y=0;K=TIME_LEVEL[e];y=!1;R=TIME_RESTART;b=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(b);s_oStage.setChildIndex(b,0);d=new CInterface(e+1);d.refreshLife(O);d.refreshTime(K);d.refreshLevel(e);this.createLevel();this.createLevelPlatform();
$(s_oMain).trigger("start_level",e);U=!1;a=s_oSpriteLibrary.getSprite("character");h=(a.width-200)/2/6;f=(a.height-60)/2;t=new CCharacter(v,a,1);a=s_oSpriteLibrary.getSprite("rope");W=a.width/2;V=a.height;this.createDoor(v,n+50);z=0;!0===s_bMobile?this.createJoypad():(document.onkeydown=g,document.onkeyup=k);d.helpPage1(e)};this.createJoypad=function(){var a=s_oSpriteLibrary.getSprite("joypad");F=new CJoypad(a,100,700,s_oStage,!1);F.addFireButtonListener(ON_MOUSE_DOWN,this.shootMobile,this);this.blockJoypad(!0);
E=Math.PI/8};this.instanceBall=function(a){for(var c=0;c<MAX_BALL_INSTANCE;c++){var b=s_oSpriteLibrary.getSprite("ball"+a+"_3");w.push(new CBall(-50+-50*a,-50+-50*c,b,0,J,3,a,!1))}};this.createLevel=function(){for(var a=BALLS_LEVEL[e],b=!1,d=!1,f=!1,h=0;h<a.length;h++){var q=a[h].color;0===q?b=!0:1===q?d=!0:2===q&&(f=!0)}!0===b&&this.instanceBall(0);!0===d&&this.instanceBall(1);!0===f&&this.instanceBall(2);for(h=b=0;h<a.length;h++)for(var d=a[h].x,f=a[h].y,k=a[h].type,l=a[h].XDir,q=a[h].color,p=0;p<
w.length;p++)if(w[p].getInfoData("Color")===q&&!1===w[p].getActive()){c[b]=w[p];c[b].setPosition(d,f);c[b].changeDirection(l);c[b].changeType(k);c[b].setActive(!0);c[b].setInfoData("ID",b);b++;break}this.setPause(!0);this.canInput(!1)};this.createLevelPlatform=function(){for(var a=BRICKS_LEVEL[e],c=s_oSpriteLibrary.getSprite("platform"),b=0;b<a.length;b++)this.createAPlatform(b,a[b].x,a[b].y,c)};this.createABall=function(a,b,d,f,h,e,q){c.push(new CBall(b,d,f,h,J,e,q,!1));c[a].setInfoData("ID",a)};
this.createAPlatform=function(a,c,b,d){I[a]=createBitmap(d);I[a].x=c;I[a].y=b;I[a].regY=d.height/2;I[a].regX=d.width/2;s_oStage.addChild(I[a]);s_oStage.setChildIndex(I[a],5)};this.createDoor=function(a,c){var b=s_oSpriteLibrary.getSprite("door");Z=new CDoor(a,c,b);Z.changeState("open",!1)};this.onExit=function(){s_oGame.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_level",e);$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad")};this.unload=function(){d.unload();for(var a=
0;a<c.length;a++)c[a].unload();for(a=0;a<A.length;a++)A[a].unload();!0===s_bMobile&&F&&(F.unload(),F=null);createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.blockJoypad=function(a){F&&F.block(a)};this.shoot=function(){z=0;t.changeState("shoot");s_oGame.createARope(A.length)};this.moveLeft=function(){D=y=!0;z=-1;t.changeState("run");t.rotate(-1)};this.moveRight=function(){H=y=!0;z=1;t.changeState("run");t.rotate(1)};this.createARope=function(a){var c=s_oSpriteLibrary.getSprite("rope");
A.push(new CRope(t.getX(),t.getY(),c,1));A[a].setInfoData("ID",a)};this.combo=function(a,c,b){var d;if(!0===b&&0<N){var f,h,e;d=a>CANVAS_WIDTH/2?-50:50;f=new createjs.Text(COMBO_SCORE[N],"bold 40px "+PRIMARY_FONT,"#ffffff");f.textAlign="left";f.textBaseline="alphabetic";f.x=d;f.y=0;h=new createjs.Text(COMBO_SCORE[N],"bold 40px "+PRIMARY_FONT,"#000000");h.textAlign="left";h.textBaseline="alphabetic";h.x=d;h.y=0;h.outline=.2;e=new createjs.Container;e.addChild(f,h);e.scaleX=0;e.scaleY=0;e.x=a;e.y=c;
s_oStage.addChild(e);createjs.Tween.get(e).to({scaleX:1,scaleY:1},500,createjs.Ease.backOut).call(function(){createjs.Tween.get(e).to({scaleX:0,scaleY:0},500,createjs.Ease.backIn).call(function(){s_oStage.removeChild(e)})});this.addScore(COMBO_SCORE[N])}else N=0;4>N&&!0===b&&N++};this.__updatePhysics=function(a){y&&t.update(z);if(0===A.length)S=Q=-1;else for(var b=0;b<A.length;b++)A[b].update();for(var e=0;e<c.length;e++)if(!0===c[e].getActive()){var q=c[e].getX(),k=c[e].getY(),l=c[e].getInfoData("Radius");
c[e].update(a);for(var g=0;g<I.length;g++){var D=I[g].x,n=I[g].y;q>D-p-l&&q<D+p+l&&k>n-r-l&&k<n+r+l&&(k>n?c[e].bounceDown():c[e].bounceUp())}if(0!==A.length)for(b=0;b<A.length;b++){S=A[b].getX();Q=A[b].getY();X=b;for(g=0;g<I.length;g++)D=I[g].x,n=I[g].y,S>D-p&&S<D+p&&Q>n-r&&Q<n+r&&A[X].aggance(!0);if(q>S-W-l&&q<S+W+l&&k>Q-l&&k<Q+V+l){this.addScore(c[e].getInfoData("Score"));c[e].addExplosion();switch(c[e].getInfoData("Type")){case 0:this.unloadBall(e);break;case 1:c[e].changeType(0);c[e].changeDirection(-1);
c[e].resetSpeed();for(g=0;g<w.length;g++)if(w[g].getInfoData("Color")===c[e].getInfoData("Color")&&!1===w[g].getActive()){this.activeABallChached(0,g,q,k);break}break;case 2:c[e].changeType(1);c[e].changeDirection(-1);c[e].resetSpeed();for(g=0;g<w.length;g++)if(w[g].getInfoData("Color")===c[e].getInfoData("Color")&&!1===w[g].getActive()){this.activeABallChached(1,g,q,k);break}break;case 3:for(c[e].changeType(2),c[e].changeDirection(-1),c[e].resetSpeed(),g=0;g<w.length;g++)if(w[g].getInfoData("Color")===
c[e].getInfoData("Color")&&!1===w[g].getActive()){this.activeABallChached(2,g,q,k);break}}A[X].setInfoData("Unloaded",!1);this.unloadRope(X);this.combo(q,k,!0);this.ballFinished();break}}b=t.getX();g=t.getY();q>b-h-l&&q<b+h+l&&k>g-f-l&&k<g+f+l&&(c[e].addExplosion(),c[e].setActive(!1),c[e].setPosition(-100,-100),this.setPause(!0),this.canInput(!1),!0===s_bMobile&&(this.blockJoypad(!0),F.resetJoy()),t.changeState("death"),u=x,d.refreshScore(u),U=!0,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("dead"))}x>
u&&(u+=5,d.refreshScore(u))};this.activeABallChached=function(a,b,d,f){w[b].changeType(a);w[b].changeDirection(1);w[b].setPosition(d,f);w[b].setActive(!0);c.push(w[b])};this.restartLevelFromGameOver=function(){O=CHARACTER_LIVES+1;x=u=0;d.refreshScore(u);$(s_oMain).trigger("restart_level",e);this.restartLevel()};this.restartLevel=function(){if(0<O){s_oGame.addLife(-1);for(var a=0,b=0;b<c.length;b++)c[b].unload(),a++;c.splice(0,a);for(b=a=0;b<A.length;b++)A[b].unload(),a++;A.splice(0,a);for(b=a=0;b<
w.length;b++)w[b].unload(),a++;w.splice(0,a);createjs.Tween.removeAllTweens();d.showLevelNum(e);t.changeState("idle");t.setPosition(v,null);z=N=0;this.resetTime();this.createLevel()}else u=x,d.refreshScore(u),d.gameOver(u)};this.resetTime=function(){K=TIME_LEVEL[e];d.refreshTime(K)};this.addLife=function(a){var c,b,f;b=new createjs.Text(TEXT_EXTRA_LIFE,"bold 60px "+PRIMARY_FONT,"#ffffff");b.textAlign="center";b.textBaseline="alphabetic";b.x=0;b.y=-100;f=new createjs.Text(TEXT_EXTRA_LIFE,"bold 60px "+
PRIMARY_FONT,"#000000");f.textAlign="center";f.textBaseline="alphabetic";f.x=0;f.y=-100;f.outline=.6;null!==a?(O+=a,d.refreshLife(O)):(b.text=TEXT_ADDED+" "+EXTRA_POINT+" "+TEXT_SCORE,f.text=TEXT_ADDED+" "+EXTRA_POINT+" "+TEXT_SCORE);c=new createjs.Container;c.addChild(b,f);c.scaleX=0;c.scaleY=0;c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;s_oStage.addChild(c);createjs.Tween.get(c).to({scaleX:1,scaleY:1},1E3,createjs.Ease.elasticOut).call(function(){createjs.Tween.get(c).wait(300).to({scaleX:0,scaleY:0},
1E3,createjs.Ease.elasticIn).call(function(){s_oStage.removeChild(c)})})};this.canInput=function(a){P=a};this.ballFinished=function(){if(0===c.length){this.setPause(!0);this.canInput(!1);y=!1;z=0;!0===s_bMobile&&(F.unload(),this.blockJoypad(!0),F.resetJoy(),F=null);Z.openDoorAndRemain();var a=s_oSpriteLibrary.getSprite("rays"),b=new createjs.SpriteSheet({images:[a],frames:{width:a.width/3,height:a.height,regX:a.width/2/3,regY:a.height/2},animations:{cast:[0,2,"cast",.4]}});T=createSprite(b,"cast",
a.width/2/2,a.height/2,a.width/3,a.height);T.x=CANVAS_WIDTH/2;T.y=CANVAS_HEIGHT/2+53;s_oStage.addChild(T);s_oStage.setChildIndex(T,2);Z.childIndex(4);Y++;Y===NUM_LEVELS_FOR_ADS&&(Y=0,$(s_oMain).trigger("show_interlevel_ad"));e+1<BALLS_LEVEL.length?(this.createButNextLevel(),d.animContrast(0)):(u=x,d.finishGame(u));$(s_oMain).trigger("end_level",e);t.changeState("idle");u=x;d.refreshScore(u);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var f;f=createjs.Sound.play("game_completed");s_oSoundTrack.volume=
.2;f.on("complete",function(){s_oSoundTrack.volume=1;f=null})}}};this.createButNextLevel=function(){var a=s_oSpriteLibrary.getSprite("next_level"),c=new createjs.SpriteSheet({images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height},animations:{blink:[0,1,"blink",.3]}});M=createSprite(c,"blink",a.width/2/2,a.height,a.width/2,a.height);M.x=CANVAS_WIDTH/2;M.y=CANVAS_HEIGHT/2+115;M.on("mousedown",this.nextLevel);s_oStage.addChild(M);s_oStage.setChildIndex(M,s_oStage.numChildren-
1)};this.nextLevel=function(){s_oGame.resetLevel();e++;d.refreshLevel(e);s_oGame.resetTime(TIME_LEVEL[e]);!0===s_bMobile&&(s_oGame.createJoypad(),s_oGame.blockJoypad(!0));t.setPosition(v,null);s_oGame.createLevel();s_oGame.createLevelPlatform();d.showLevelNum(e);$(s_oMain).trigger("start_level",e)};this.setPause=function(a){l=a};this.addScore=function(a){x+=a;this.extraLife(a)};this.extraLife=function(a){C<EXTRA_LIFE?C+=a:(C=0,9>O?this.addLife(1):(this.addLife(null),this.addScore(EXTRA_POINT)))};
this.unloadBall=function(a){c[a].unload();c.splice(a,1);for(a=0;a<c.length;a++)c[a].resetTheIndex(a);var b=0;for(a=0;a<w.length;a++)if(void 0===w){b=a;break}w.splice(b,1)};this.unloadRope=function(a){A[a].unload();A.splice(a,1);for(a=0;a<A.length;a++)A[a].resetTheIndex(a)};this.resetLevel=function(){s_oStage.removeChild(T,M);M=T=null;for(var a=0;a<A.length;a++)A[a].unload();for(var c=0,a=0;a<I.length;a++)s_oStage.removeChild(I[a]),c++;I.splice(0,c);for(a=c=0;a<w.length;a++)w[a].unload(),c++;w.splice(0,
c);Z.changeState("open",!1)};this.shootMobile=function(){A.length<MAX_ROPE&&(z=0,t.changeState("shoot"),s_oGame.createARope(A.length),y=!1)};this.checkController=function(a){null===a?0!==z&&(z=0,t.changeState("idle"),y=!1):a>=-E&&a<E?1!==z&&(z=1,t.changeState("run"),t.rotate(1),y=!0):a>=7*E||a<7*-E?-1!==z&&(y=!0,z=-1,t.changeState("run"),t.rotate(-1)):a>=7*-E&&a<5*-E?-1!==z&&(y=!0,z=-1,t.changeState("run"),t.rotate(-1)):a>=3*-E&&a<-E?1!==z&&(z=1,t.changeState("run"),t.rotate(1),y=!0):a>=E&&a<3*E?
1!==z&&(z=1,t.changeState("run"),t.rotate(1),y=!0):a>=5*E&&a<7*E&&-1!==z&&(y=!0,z=-1,t.changeState("run"),t.rotate(-1))};this.update=function(){if(!1===l){F&&this.checkController(F.update());q+=s_iTimeElaps;var a=parseInt(q/B);q-=B*a;for(var c=0;c<a;c++)for(var b=0;b<G;b++)this.__updatePhysics();1<K?(K-=1/createjs.Ticker.framerate,d.refreshTime(Math.floor(K)),10<K?d.colorTime("#fff"):d.colorTime("#f00")):(this.setPause(!0),d.showTimeIsUp(),this.canInput(!1),t.changeState("idle"))}!0===U&&(R-=1/createjs.Ticker.framerate,
0>=R&&(s_oGame.restartLevel(),R=TIME_RESTART,U=!1))};s_oGame=this;var B=16,G=10;BALL_SPEED=a.ball_speed/G;BALL_DOWN_ACCELLERATION=a.ball_down_accelleration/G;BALL_SCORE=a.ball_score;CHARACTER_SPEED=a.character_speed/G;ROPE_SPEED=a.speed_rope/G;TIME_ROPE=a.time_rope;TIME_LEVEL=a.time_level;COMBO_SCORE=a.combo_score;CHARACTER_LIVES=a.character_lives;EXTRA_LIFE=a.extra_life_at_point;EXTRA_POINT=a.extra_point;NUM_LEVELS_FOR_ADS=a.num_levels_for_ads;this._init()}var s_oGame;
function CDoor(a,g,k){var b,d={};this._init=function(){var d=new createjs.SpriteSheet({images:[k],frames:{width:k.width/3,height:k.height,regX:k.width/2/3,regY:k.height/2},animations:{open:[0,2,"open",.2],close:[2,0,"close",.2]}});b=createSprite(d,"open",k.width/2/2,k.height/2,k.width/3,k.height);b.x=a;b.y=g;s_oStage.addChild(b);s_oStage.setChildIndex(b,1)};this.getX=function(){return b.x};this.getY=function(){return b.y};this.childIndex=function(a){s_oStage.setChildIndex(b,a)};this.setPosition=function(a,
d){null!==a&&(b.x=a);null!==d&&(b.y=d)};this.setInfoData=function(a,b){d[a]=b};this.getInfoData=function(a){return d[a]};this.resetTheIndex=function(a){d.ID=a};this.unload=function(){s_oStage.removeChild(b);s_oDoor=null};this.changeState=function(a,d){!0===d?b.gotoAndPlay(a):b.gotoAndStop(a)};this.openDoorAndRemain=function(){b.gotoAndPlay("open");b.on("animationend",function(){b.gotoAndStop(2)})};this.update=function(){};s_oDoor=this;this._init()}var s_oDoor;
function CCharacter(a,g,k){var b,d={},e,l,c,h,f;this._init=function(){var d=new createjs.SpriteSheet({images:[g],frames:{width:g.width/6,height:g.height,regX:g.width/2/6,regY:g.height/2},animations:{run:[0,3,"run",.5],shoot:[4],death:[5],idle:[0]}});b=createSprite(d,"idle",g.width/2/6,g.height/2,g.width/2,g.height);d=CANVAS_HEIGHT-EDGEBOARD_X-g.height/2-4;b.x=a;b.y=d;c=g.width/6;d=EDGEBOARD_Y+c;e=CANVAS_WIDTH+-(EDGEBOARD_Y+c);l=d;f=k;h=CHARACTER_SPEED*f;s_oStage.addChild(b);s_oStage.setChildIndex(b,
4)};this.getX=function(){return b.x};this.getY=function(){return b.y};this.setPosition=function(a,c){null!==a&&(b.x=a);null!==c&&(b.y=c)};this.rotate=function(a){b.scaleX=a};this.changeState=function(a){"run"===a?b.gotoAndPlay(a):b.gotoAndStop(a)};this.setInfoData=function(a,c){d[a]=c};this.getInfoData=function(a){return d[a]};this.unload=function(){s_oStage.removeChild(b);s_oCharacter=null};this.update=function(a){b.x+=h*a;b.x>=e?b.x=e:b.x<=l&&(b.x=l)};s_oCharacter=this;this._init()}var s_oCharacter;
function CBall(a,g,k,b,d,e,l,c){var h,f={},p,r,q,v,n,u,x,C,J,y;this._init=function(){h=createBitmap(k);h.x=a;h.y=g;J=0;f.Radius=k.height/2;f.Type=e;f.Score=BALL_SCORE[e];f.Color=l;f.Active=c;p=b;r=1;h.regX=f.Radius;h.regY=f.Radius;var D=76+f.Radius,H=f.Radius+EDGEBOARD_X,z=f.Radius+EDGEBOARD_X;q=CANVAS_WIDTH+(-76-f.Radius);v=D;u=CANVAS_HEIGHT-H;n=z;C=d;x=BALL_SPEED*C;y=-(BALL_DOWN_ACCELLERATION*MAX_FORCE_UP_RATE)*FORCE_RATE_BALL[e];s_oStage.addChild(h);s_oStage.setChildIndex(h,5)};this.edgeOffset=
function(){var a=EDGEBOARD_Y+21+f.Radius,c=f.Radius+EDGEBOARD_X,b=f.Radius+EDGEBOARD_X;q=CANVAS_WIDTH+(-EDGEBOARD_Y-21-f.Radius);v=a;u=CANVAS_HEIGHT-c;n=b};this.changeDirection=function(a){p=a};this.downFloor=function(a){};this.getDirectionY=function(){return r};this.getX=function(){return h.x};this.getY=function(){return h.y};this.setPosition=function(a,c){null!==a&&(h.x=a);null!==c&&(h.y=c)};this.setVisible=function(a){h.visible=a};this.getActive=function(){return f.Active};this.setActive=function(a){f.Active=
a};this.setInfoData=function(a,c){f[a]=c};this.getInfoData=function(a){return f[a]};this.resetTheIndex=function(a){f.ID=a};this.unload=function(){s_oStage.removeChild(h);s_oBall=null};this.resetSpeed=function(){J=0};this.setVelocityRate=function(a){C=a;x=BALL_SPEED*C};this.bounceUp=function(){J=y};this.bounceDown=function(){J=-y-.4};this.changeType=function(a){f.Type!==a&&(f.Type=a,f.Score=BALL_SCORE[a],y=-(BALL_DOWN_ACCELLERATION*MAX_FORCE_UP_RATE)*FORCE_RATE_BALL[a],a=s_oSpriteLibrary.getSprite("ball"+
f.Color+"_"+f.Type),h.image=a,f.Radius=a.width/2,this.edgeOffset(),h.regX=f.Radius,h.regY=f.Radius)};this.addExplosion=function(){var a,c=s_oSpriteLibrary.getSprite("explosion"+f.Color+"_"+f.Type);a=createBitmap(c);a.x=h.x;a.y=h.y;a.regX=c.width/2;a.regY=c.height/2;a.scaleX=0;a.scaleY=0;s_oStage.addChild(a);s_oStage.setChildIndex(a,5);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("ball_explosion");createjs.Tween.get(a).to({scaleX:2,scaleY:2},300).call(function(){s_oStage.removeChild(a)})};
this.update=function(a){h.x+=x*p;J+=BALL_DOWN_ACCELLERATION;h.y+=J;h.x>=q?(p*=-1,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("boing")):h.x<=v&&(p*=-1,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("boing"));h.y>=u?(this.bounceUp(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("boing")):h.y<=n&&this.bounceDown()};s_oBall=this;this._init()}var s_oBall;
function CSpriteLibrary(){var a,g,k,b,d,e;this.init=function(l,c,h){k=g=0;b=l;d=c;e=h;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},g++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){d.call(e)};this._onSpriteLoaded=function(){b.call(e);++k===g&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return g}}
for(var CANVAS_WIDTH=960,CANVAS_HEIGHT=540,EDGEBOARD_X=80,EDGEBOARD_Y=55,FPS_TIME=1E3/30,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="aldo_the_apacheregular",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,TYPES_OF_BALL=4,TYPES_OF_EXPLOSION=4,COLORS_OF_BALLS=3,TOT_LEVELS=10,TIME_RESTART=4,MAX_FORCE_UP_RATE=700,MAX_ROPE=2,MAX_BALL_INSTANCE=20,FORCE_RATE_BALL=[],BALLS_LEVEL=[],BRICKS_LEVEL=[],i=0;i<TOT_LEVELS;i++)BALLS_LEVEL[i]=
[],BRICKS_LEVEL[i]=[];BALLS_LEVEL[0][0]={x:CANVAS_WIDTH/2-200,y:CANVAS_HEIGHT/2-100,type:3,XDir:1,color:0};BALLS_LEVEL[1][0]={x:CANVAS_WIDTH/2-200,y:CANVAS_HEIGHT/2-100,type:3,XDir:1,color:0};BALLS_LEVEL[1][0]={x:CANVAS_WIDTH/2+200,y:CANVAS_HEIGHT/2-130,type:3,XDir:1,color:0};BRICKS_LEVEL[1][0]={x:CANVAS_WIDTH/2-200,y:CANVAS_HEIGHT/2};BALLS_LEVEL[2][0]={x:CANVAS_WIDTH/2-300,y:CANVAS_HEIGHT/2-100,type:1,XDir:1,color:0};BALLS_LEVEL[2][1]={x:CANVAS_WIDTH/2+100,y:CANVAS_HEIGHT/2-130,type:3,XDir:-1,color:1};
BALLS_LEVEL[2][2]={x:CANVAS_WIDTH/2+300,y:CANVAS_HEIGHT/2-150,type:2,XDir:1,color:0};BALLS_LEVEL[3][0]={x:CANVAS_WIDTH/2-300,y:CANVAS_HEIGHT/2-60,type:1,XDir:1,color:1};BALLS_LEVEL[3][1]={x:CANVAS_WIDTH/2+100,y:CANVAS_HEIGHT/2-130,type:3,XDir:-1,color:1};BRICKS_LEVEL[3][0]={x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2-50};BALLS_LEVEL[4][0]={x:CANVAS_WIDTH/2-300,y:CANVAS_HEIGHT/2-130,type:3,XDir:1,color:2};BALLS_LEVEL[4][1]={x:CANVAS_WIDTH/2+300,y:CANVAS_HEIGHT/2-130,type:3,XDir:-1,color:0};
BRICKS_LEVEL[4][0]={x:CANVAS_WIDTH/2+200,y:CANVAS_HEIGHT/2+50};BRICKS_LEVEL[4][1]={x:CANVAS_WIDTH/2-200,y:CANVAS_HEIGHT/2+50};BALLS_LEVEL[5][0]={x:CANVAS_WIDTH/2-300,y:CANVAS_HEIGHT/2+20,type:2,XDir:-1,color:1};BALLS_LEVEL[5][1]={x:CANVAS_WIDTH/2+300,y:CANVAS_HEIGHT/2-130,type:3,XDir:1,color:0};BALLS_LEVEL[5][2]={x:CANVAS_WIDTH/2+100,y:CANVAS_HEIGHT/2-20,type:2,XDir:1,color:1};BRICKS_LEVEL[5][0]={x:CANVAS_WIDTH/2+200,y:CANVAS_HEIGHT/2+70};
BALLS_LEVEL[6][0]={x:CANVAS_WIDTH/2-300,y:CANVAS_HEIGHT/2+130,type:1,XDir:-1,color:1};BALLS_LEVEL[6][1]={x:CANVAS_WIDTH/2+300,y:CANVAS_HEIGHT/2-130,type:2,XDir:-1,color:1};BALLS_LEVEL[6][2]={x:CANVAS_WIDTH/2-250,y:CANVAS_HEIGHT/2-130,type:2,XDir:-1,color:2};BALLS_LEVEL[6][3]={x:CANVAS_WIDTH/2+250,y:CANVAS_HEIGHT/2+130,type:1,XDir:-1,color:2};BRICKS_LEVEL[6][0]={x:CANVAS_WIDTH/2+250,y:CANVAS_HEIGHT/2+90};BRICKS_LEVEL[6][1]={x:CANVAS_WIDTH/2-250,y:CANVAS_HEIGHT/2+90};
BALLS_LEVEL[7][0]={x:CANVAS_WIDTH/2-300,y:CANVAS_HEIGHT/2+130,type:3,XDir:1,color:2};BALLS_LEVEL[7][1]={x:CANVAS_WIDTH/2+300,y:CANVAS_HEIGHT/2-130,type:3,XDir:-1,color:2};BALLS_LEVEL[7][2]={x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2-130,type:3,XDir:1,color:2};BRICKS_LEVEL[7][0]={x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2-50};BRICKS_LEVEL[7][1]={x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2+77};BALLS_LEVEL[8][0]={x:CANVAS_WIDTH/2+250,y:CANVAS_HEIGHT/2-45,type:3,XDir:-1,color:0};
BALLS_LEVEL[8][1]={x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2-100,type:2,XDir:-1,color:1};BALLS_LEVEL[8][2]={x:CANVAS_WIDTH/2-250,y:CANVAS_HEIGHT/2-45,type:3,XDir:1,color:2};BRICKS_LEVEL[8][0]={x:CANVAS_WIDTH/2+200,y:CANVAS_HEIGHT/2+10};BRICKS_LEVEL[8][1]={x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2-40};BRICKS_LEVEL[8][2]={x:CANVAS_WIDTH/2-200,y:CANVAS_HEIGHT/2+10};BALLS_LEVEL[9][0]={x:CANVAS_WIDTH/2+240,y:CANVAS_HEIGHT/2-120,type:1,XDir:-1,color:0};
BALLS_LEVEL[9][1]={x:CANVAS_WIDTH/2+140,y:CANVAS_HEIGHT/2-110,type:1,XDir:-1,color:0};BALLS_LEVEL[9][2]={x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2-110,type:1,XDir:-1,color:1};BALLS_LEVEL[9][3]={x:CANVAS_WIDTH/2-140,y:CANVAS_HEIGHT/2-110,type:1,XDir:-1,color:2};BALLS_LEVEL[9][4]={x:CANVAS_WIDTH/2-240,y:CANVAS_HEIGHT/2-120,type:1,XDir:1,color:2};BALLS_LEVEL[9][5]={x:CANVAS_WIDTH/2-250,y:CANVAS_HEIGHT/2+10,type:3,XDir:-1,color:0};BALLS_LEVEL[9][0]={x:CANVAS_WIDTH/2+250,y:CANVAS_HEIGHT/2,type:3,XDir:1,color:0};
BRICKS_LEVEL[9][0]={x:CANVAS_WIDTH/2+222,y:CANVAS_HEIGHT/2-80};BRICKS_LEVEL[9][1]={x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2-80};BRICKS_LEVEL[9][2]={x:CANVAS_WIDTH/2-222,y:CANVAS_HEIGHT/2-80};BRICKS_LEVEL[9][3]={x:CANVAS_WIDTH/2+390,y:CANVAS_HEIGHT/2+110};BRICKS_LEVEL[9][4]={x:CANVAS_WIDTH/2-390,y:CANVAS_HEIGHT/2+100};FORCE_RATE_BALL=[.7,.8,.9,1];
function CToggle(a,g,k,b){var d,e,l,c=[],h;this._init=function(a,c,b,q){e=[];l=[];var g=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}});d=q;h=createSprite(g,"state_"+d,b.width/2/2,b.height/2,b.width/2,b.height);h.mouseEnabled=!0;h.x=a;h.y=c;h.stop();s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);h.mouseEnabled=
!1;s_oStage.removeChild(h)};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){e[a]=c;l[a]=b};this.addEventListenerWithParams=function(a,b,d,h){e[a]=b;l[a]=d;c=h};this.setActive=function(a){d=a;h.gotoAndStop("state_"+d)};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");d=!d;h.gotoAndStop("state_"+d);e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(l[ON_MOUSE_UP],
c)};this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],c)};this.setPosition=function(a,c){h.x=a;h.y=c};this.setVisible=function(a){h.visible=a};this._init(a,g,k,b)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return!0;return!1}
function getSize(a){var g=a.toLowerCase(),k=window.document,b=k.documentElement;if(void 0===window["inner"+a])a=b["client"+a];else if(window["inner"+a]!=b["client"+a]){var d=k.createElement("body");d.id="vpw-test-b";d.style.cssText="overflow:scroll";var e=k.createElement("div");e.id="vpw-test-d";e.style.cssText="position:absolute;top:-1000px";e.innerHTML="<style>@media("+g+":"+b["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+g+":7px!important}}</style>";d.appendChild(e);b.insertBefore(d,k.head);
a=7==e["offset"+a]?b["client"+a]:window["inner"+a];b.removeChild(d)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var g=getSize("Width"),k=Math.min(a/CANVAS_HEIGHT,g/CANVAS_WIDTH),b=CANVAS_WIDTH*k,k=CANVAS_HEIGHT*k,d=0;k<a?(d=a-k,k+=d,b+=CANVAS_WIDTH/CANVAS_HEIGHT*d):b<g&&(d=g-b,b+=d,k+=CANVAS_HEIGHT/CANVAS_WIDTH*d);var d=a/2-k/2,e=g/2-b/2,l=CANVAS_WIDTH/b;if(e*l<-EDGEBOARD_X||d*l<-EDGEBOARD_Y)k=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),g/(CANVAS_WIDTH-2*
EDGEBOARD_X)),b=CANVAS_WIDTH*k,k*=CANVAS_HEIGHT,d=(a-k)/2,e=(g-b)/2,l=CANVAS_WIDTH/b;s_iOffsetX=-1*e*l;s_iOffsetY=-1*d*l;0<=d&&(s_iOffsetY=0);0<=e&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",b+"px");$("#canvas").css("height",k+"px");0>d?$("#canvas").css("top",d+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",e+"px")}}
function createBitmap(a,g,k){var b=new createjs.Bitmap(a),d=new createjs.Shape;g&&k?d.graphics.beginFill("#fff").drawRect(0,0,g,k):d.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);b.hitArea=d;return b}function createSprite(a,g,k,b,d,e){a=null!==g?new createjs.Sprite(a,g):new createjs.Sprite(a);g=new createjs.Shape;g.graphics.beginFill("#000000").drawRect(-k,-b,d,e);a.hitArea=g;return a}
function randomFloatBetween(a,g,k){"undefined"===typeof k&&(k=2);return parseFloat(Math.min(a+Math.random()*(g-a),g).toFixed(k))}function formatTime(a){a/=1E3;var g=Math.floor(a/60);a=Math.floor(a-60*g);var k="",k=10>g?k+("0"+g+":"):k+(g+":");return 10>a?k+("0"+a):k+a}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var g=a.length,k,b;0<g;)b=Math.floor(Math.random()*g),g--,k=a[g],a[g]=a[b],a[b]=k;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var g=document.createEvent("MouseEvents");g.initEvent("click",!0,!0);a.dispatchEvent(g)}}};function getParamValue(a){for(var g=window.location.search.substring(1).split("&"),k=0;k<g.length;k++){var b=g[k].split("=");if(b[0]==a)return b[1]}}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}
function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function CTextToggle(a,g,k,b,d,e,l,c,h){var f=1,p,r=!1,q,v,n,u,x,C;this._init=function(a,c,b,d,f,h,e,g,k){p=!1;q=[];v=[];C=createBitmap(b);var l=Math.ceil(e/20);x=new createjs.Text(d," "+e+"px "+f,"#000000");x.textAlign="center";x.textBaseline="alphabetic";var r=x.getBounds();x.x=b.width/2+l;x.y=Math.floor(b.height/2)+r.height/3+l-7;u=new createjs.Text(d," "+e+"px "+f,h);u.textAlign="center";u.textBaseline="alphabetic";r=u.getBounds();u.x=b.width/2;u.y=Math.floor(b.height/2)+r.height/3-7;n=new createjs.Container;
n.x=a;n.y=c;n.regX=b.width/2;n.regY=b.height/2;g||(a=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}}),C=createSprite(a,"state_false",b.width/2/2,b.height/2,b.width/2,b.height),x.x=l,x.y=l+17,u.x=0,u.y=17,n.regX=0,n.regY=0);n.addChild(C,x,u);k.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown");n.off("pressup");h.removeChild(n)};this.setVisible=function(a){n.visible=a};
this._initListener=function(){oParent=this;n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){q[a]=b;v[a]=c};this.buttonRelease=function(){p||r||(n.scaleX=1*f,n.scaleY=1*f,q[ON_MOUSE_UP]&&q[ON_MOUSE_UP].call(v[ON_MOUSE_UP]))};this.buttonDown=function(){p||r||(n.scaleX=.9*f,n.scaleY=.9*f,q[ON_MOUSE_DOWN]&&q[ON_MOUSE_DOWN].call(v[ON_MOUSE_DOWN]))};this.enable=function(){p=!1;c||C.gotoAndStop("state_true")};this.disable=function(){p=!0;c||C.gotoAndStop("state_false")};
this.setTextPosition=function(a,b){var c=Math.ceil(l/20);x.x=a+c;x.y=b+c;u.x=a;u.y=b};this.setText=function(a){u.text=a;x.text=a};this.setPosition=function(a,b){n.x=a;n.y=b};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this.block=function(a){r=a};this.setScale=function(a){f=a;n.scaleX=a;n.scaleY=a};this.setScaleX=function(a){C.scaleX=a};this._init(a,g,k,b,d,e,l,c,h);return this}
function CTextButton(a,g,k,b,d,e,l){var c,h,f,p,r;this._init=function(a,b,d,e,g,k,l){c=[];h=[];g=createBitmap(d);var y=Math.ceil(l/20);r=new createjs.Text(e,"bold "+l+"px "+PRIMARY_FONT,"#000000");r.textAlign="center";r.textBaseline="alphabetic";var D=r.getBounds();r.x=d.width/2+y;r.y=Math.floor(d.height/2)+D.height/3+y;p=new createjs.Text(e,"bold "+l+"px "+PRIMARY_FONT,k);p.textAlign="center";p.textBaseline="alphabetic";D=p.getBounds();p.x=d.width/2;p.y=Math.floor(d.height/2)+D.height/3;f=new createjs.Container;
f.x=a;f.y=b;f.regX=d.width/2;f.regY=d.height/2;f.addChild(g,r,p);s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown");f.off("pressup");s_oStage.removeChild(f)};this.setVisible=function(a){f.visible=a};this._initListener=function(){oParent=this;f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){c[a]=b;h[a]=d};this.buttonRelease=function(){f.scaleX=1;f.scaleY=1;c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(h[ON_MOUSE_UP])};
this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setTextPosition=function(a){p.y=a;r.y=a+2};this.setPosition=function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};this.getX=function(){return f.x};this.getY=function(){return f.y};this._init(a,g,k,b,d,e,l);return this}
function CRope(a,g,k,b){var d,e={},l,c,h,f,p,r;this._init=function(){var q=new createjs.SpriteSheet({images:[k],frames:{width:k.width/2,height:k.height,regX:k.width/2/2,regY:0},animations:{move:[0],ancorate:[1]}});d=createSprite(q,"move",k.width/2/2,0,k.width/2,k.height);d.x=a;d.y=g;r=TIME_ROPE;c=b;p=!1;e.Unloaded=!0;h=!1;l=ROPE_SPEED*c;f=EDGEBOARD_X+1;s_oStage.addChild(d);s_oStage.setChildIndex(d,5);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("rope_launch")};this.getX=function(){return d.x};
this.getY=function(){return d.y};this.setPosition=function(a,b){null!==a&&(d.x=a);null!==b&&(d.y=b)};this.setInfoData=function(a,b){e[a]=b};this.getInfoData=function(a){return e[a]};this.resetTheIndex=function(a){e.ID=a};this.unload=function(){s_oStage.removeChild(d);s_oRope=null};this.setVelocityRate=function(a){c=a;l=BALL_SPEED*c};this.aggance=function(a){p=a;r+=300};this.isAgganced=function(){return p};this.update=function(){d.y>f&&!1===p?d.y-=l:!1===h&&(d.gotoAndStop("ancorate"),h=!0,!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("rope_hoocked"),createjs.Tween.get(d).to({alpha:0},r).call(function(){!0===e.Unloaded&&(s_oGame.unloadRope(e.ID),s_oGame.combo(0,0,!1))}))};s_oRope=this;this._init()}var s_oRope;
function CPreloader(){var a,g,k,b,d,e,l;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("time_bar_fill","./sprites/time_bar_fill.png");s_oSpriteLibrary.loadSprites();l=new createjs.Container;s_oStage.addChild(l)};this.unload=function(){l.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(e).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var c=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));l.addChild(c);c=s_oSpriteLibrary.getSprite("time_bar_fill");b=createBitmap(c);b.x=CANVAS_WIDTH/2-c.width/2;b.y=CANVAS_HEIGHT-140;l.addChild(b);a=c.width;g=c.height;d=new createjs.Shape;d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(b.x,b.y,1,g);l.addChild(d);b.mask=
d;k=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT-115;k.shadow=new createjs.Shadow("#000",2,2,2);k.textBaseline="alphabetic";k.textAlign="center";l.addChild(k);e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e.alpha=0;l.addChild(e)};this.refreshLoader=function(c){k.text=c+"%";d.graphics.clear();c=Math.floor(c*a/100);d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(b.x,b.y,c,g)};this._init()}
function CNumToggle(a,g,k,b){var d,e,l,c,h,f,p,r=[];this._init=function(a,b,g,k){e=!1;l=[];c=[];h=new createjs.Container;h.x=a;h.y=b;k.addChild(h);a=s_oSpriteLibrary.getSprite("num_button");b={images:[a],framerate:5,frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{state_true:[0],state_false:[1]}};b=new createjs.SpriteSheet(b);d=!1;f=createSprite(b,"state_"+d,a.width/2/2,a.height/2,a.width/2,a.height);f.stop();a=s_oSpriteLibrary.getSprite("ball");b={images:[a],
frames:{width:a.width/NUM_DIFFERENT_BALLS,height:a.height,regX:a.width/NUM_DIFFERENT_BALLS/2,regY:a.height/2},animations:{red:[0],green:[1],cyan:[0],violet:[1],blue:[1]}};b=new createjs.SpriteSheet(b);p=createSprite(b,"red",a.width/NUM_DIFFERENT_BALLS/2,a.height/2,a.width/NUM_DIFFERENT_BALLS,a.height);p.gotoAndStop(0);p.visible=!1;h.addChild(f,p);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);b.removeChild(h)};this._initListener=
function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){l[a]=b;c[a]=d};this.addEventListenerWithParams=function(a,b,d,f){l[a]=b;c[a]=d;r=f};this.setActive=function(a){d=a;f.gotoAndStop("state_"+d)};this.buttonRelease=function(){e||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click"),d=!d,f.gotoAndStop("state_"+d),l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(c[ON_MOUSE_UP],r))};this.buttonDown=function(){e||l[ON_MOUSE_DOWN]&&
l[ON_MOUSE_DOWN].call(c[ON_MOUSE_DOWN],r)};this.setPosition=function(a,b){h.x=a;h.y=b};this.getGlobalPosition=function(){return{x:h.localToGlobal(0,0).x,y:h.localToGlobal(0,0).y}};this.block=function(a){e=a};this.setExtracted=function(a,b){p.visible=a;p.gotoAndStop(b)};this.highlight=function(){f.gotoAndPlay(0)};this.stopHighlight=function(){f.gotoAndStop(1)};this._init(a,g,k,b)}
function CMenu(){var a,g,k,b,d,e,l,c;this._init=function(){k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(k);var c=s_oSpriteLibrary.getSprite("but_play");d=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+150,c);d.setScale(.8);d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);c=s_oSpriteLibrary.getSprite("title");b=createBitmap(c);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2-120;b.regX=c.width/2;b.regY=c.height/2;s_oStage.addChild(b);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c=
s_oSpriteLibrary.getSprite("icon_audio"),a=CANVAS_WIDTH-c.height/2-20,g=c.height/2+20,l=new CToggle(a,g,c,s_bAudioActive),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this.createSleepChar(CANVAS_WIDTH/2+325,CANVAS_HEIGHT/2+100);e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(e);createjs.Tween.get(e).to({alpha:0},1E3).call(function(){e.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){d.unload();
d=null;e.visible=!1;s_oStage.removeChild(k,b,c);c=b=k=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;s_oMenu=null};this.refreshButtonPos=function(b,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(a-b,g+c)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.createSleepChar=function(a,b){var d,e;d=s_oSpriteLibrary.getSprite("sleep");e={images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/
2},animations:{sleep:[0,1,"sleep",.05]}};e=new createjs.SpriteSheet(e);d=createSprite(e,"sleep",d.width/2/2,d.height/2,d.width/2,d.height);d.x=0;d.y=0;var g=s_oSpriteLibrary.getSprite("snot");e={images:[g],frames:{width:g.width/8,height:g.height/2,regX:g.width/2/8,regY:g.height/2/2},animations:{normal:[0,14,"normal",.2]}};e=new createjs.SpriteSheet(e);e=createSprite(e,"normal",g.width/2/8,g.height/2/2,g.width/8,g.height/2);e.x=36;e.y=0;c=new createjs.Container;c.addChild(d,e);c.x=a;c.y=b;s_oStage.addChild(c)};
this._onButPlayRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");$(s_oMain).trigger("start_session");s_oMain.gotoGame()};s_oMenu=this;this._init()}var s_oMenu=null;
function CMain(a){var g,k=0,b=0,d=STATE_LOADING,e,l,c;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;l=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();g=!0};this.soundLoaded=function(){k++;l.refreshLoader(Math.floor(k/b*100));k===b&&(l.unload(),!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1}))};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||
0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/game_completed.ogg","game_completed"),createjs.Sound.registerSound("./sounds/ball_explosion.ogg",
"ball_explosion"),createjs.Sound.registerSound("./sounds/dead.ogg","dead"),createjs.Sound.registerSound("./sounds/rope_hoocked.ogg","rope_hoocked"),createjs.Sound.registerSound("./sounds/rope_launch.ogg","rope_launch"),createjs.Sound.registerSound("./sounds/boing.ogg","boing")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.mp3",
"click"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/game_completed.mp3","game_completed"),createjs.Sound.registerSound("./sounds/ball_explosion.mp3","ball_explosion"),createjs.Sound.registerSound("./sounds/dead.mp3","dead"),createjs.Sound.registerSound("./sounds/rope_hoocked.mp3","rope_hoocked"),createjs.Sound.registerSound("./sounds/rope_launch.mp3","rope_launch"),createjs.Sound.registerSound("./sounds/boing.mp3","boing")),b+=9)};this._loadImages=
function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("frame","./sprites/frame.png");s_oSpriteLibrary.addSprite("rays","./sprites/rays.jpg");s_oSpriteLibrary.addSprite("title","./sprites/title.png");s_oSpriteLibrary.addSprite("character","./sprites/character.png");s_oSpriteLibrary.addSprite("sleep","./sprites/sleep.png");
s_oSpriteLibrary.addSprite("snot","./sprites/snot.png");s_oSpriteLibrary.addSprite("door","./sprites/door.png");s_oSpriteLibrary.addSprite("fan","./sprites/fan.png");s_oSpriteLibrary.addSprite("icon_audio","./sprites/icon_audio.png");s_oSpriteLibrary.addSprite("game_over_bg","./sprites/game_over_bg.png");s_oSpriteLibrary.addSprite("game_over_panel","./sprites/game_over_panel.png");s_oSpriteLibrary.addSprite("help_panel","./sprites/help_panel.png");s_oSpriteLibrary.addSprite("next_level","./sprites/next_level.png");
s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_play_small","./sprites/but_play_small.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_exit_big","./sprites/but_exit_big.png");s_oSpriteLibrary.addSprite("but_arrow","./sprites/but_arrow.png");s_oSpriteLibrary.addSprite("panel_hearth","./sprites/panel_hearth.png");s_oSpriteLibrary.addSprite("panel_score",
"./sprites/panel_score.png");s_oSpriteLibrary.addSprite("panel_time","./sprites/panel_time.png");s_oSpriteLibrary.addSprite("platform","./sprites/platform.jpg");s_oSpriteLibrary.addSprite("rope","./sprites/rope.png");s_oSpriteLibrary.addSprite("joypad","./sprites/joypad.png");for(var a=0;a<COLORS_OF_BALLS;a++)for(var c=0;c<TYPES_OF_BALL;c++)s_oSpriteLibrary.addSprite("ball"+a+"_"+c,"./sprites/ball"+a+"_"+c+".png");for(a=0;a<COLORS_OF_BALLS;a++)for(c=0;c<TYPES_OF_EXPLOSION;c++)s_oSpriteLibrary.addSprite("explosion"+
a+"_"+c,"./sprites/explosion"+a+"_"+c+".png");b+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){k++;l.refreshLoader(Math.floor(k/b*100))};this._onAllImagesLoaded=function(){l.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;d=STATE_MENU};this.gotoGame=function(){c=new CGame(e);
d=STATE_GAME;$(s_oMain).trigger("game_start")};this.stopUpdate=function(){g=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();g=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==g){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);d===STATE_GAME&&
c.update();s_oStage.update(a)}};s_oMain=this;e=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas,s_iLanguageSelected,s_oSpriteSheetLora,s_aQuestions;TEXT_SCORE="SCORE";TEXT_GAMEOVER="GAME OVER";TEXT_LEVEL="Level";TEXT_COMPLETE="Complete";TEXT_CONGRATULATIONS="all levels completed... Congratulations!";TEXT_TOTAL_SCORE="Total score";TEXT_TIME_IS_UP="Time Is Up";
TEXT_HELP_PAGE_1="Hit all the balls, but be careful! From each sphere two smaller will come out!";TEXT_HELP_PAGE_2_MOBILE="The left side of the screen is your joystick, touch it to move the hero. Tap the right one to shoot.";TEXT_HELP_PAGE_2_PC="USE ARROW KEY TO MOVE THE CHARACTER, SHOOT PRESSING SPACEBAR";TEXT_HELP_PAGE_3_PART1="FOR EVERY";TEXT_HELP_PAGE_3_PART2="POINTS SCORED, YOU'LL GET AN EXTRA LIFE";TEXT_EXTRA_LIFE="EXTRA LIFE";TEXT_ADDED="ADDED";TEXT_SHARE_IMAGE="200x200.jpg";
TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CJoypad(a,g,k,b,d){var e,l,c,h,f,p,r=[],q,v,n;this._init=function(a,b,d,g,k){e=a.height/2;c=l=0;h=a.height/30;f=[];p=[];n=new createjs.Container;n.x=b;n.y=d;g.addChild(n);b=new createjs.SpriteSheet({images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{bg:[0],stick:[1]}});d=createSprite(b,"bg",a.width/2/2,a.height/2,a.width/2,a.height);v=createSprite(b,"stick",a.width/2/2,a.height/2,a.width/2,a.height);n.addChild(d,v);k||(n.visible=!1);g.on("mousedown",
this.onPressStart);g.on("pressmove",this.onPressMove);g.on("pressup",this.onPressRelease);q=!1};this.addFireButtonListener=function(a,b,c,d){f[a]=b;p[a]=c;r=d};this.unload=function(){b.off("mousedown",this.onStageStart);b.off("pressmove",this.onStageMove);b.off("pressup",this.onStageRelease);b.removeChild(n)};this.onPressStart=function(a){q||(a.primary?a.stageX<CANVAS_WIDTH/2?d||(n.visible=!0,n.x=a.stageX,n.y=a.stageY,v.x=0,v.y=0):f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN],r):f[ON_MOUSE_DOWN]&&
f[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN],r))};this.onPressMove=function(a){!q&&a.primary&&n.visible&&(v.x=a.stageX-n.x,v.y=a.stageY-n.y,c=Math.atan2(v.y,v.x),l=Math.abs(v.x/Math.cos(c)),Math.pow(v.x,2)+Math.pow(v.y,2)>Math.pow(e,2)&&(v.x=e*Math.cos(c),v.y=e*Math.sin(c)))};this.onPressRelease=function(a){!q&&a.primary&&(d?(new createjs.Tween(v)).to({x:0,y:0},200).call(function(){c=l=0}):(n.visible=!1,c=l=0))};this.block=function(a){q=a};this.resetJoy=function(){c=null;n.visible=!1};this.update=function(){return l>
h?c:null};this._init(a,g,k,b,d)};