function CSpriteLibrary(){var a,c,b,g,f,e;this.init=function(d,h,k){b=c=0;g=d;f=h;e=k;a={}};this.addSprite=function(b,e){a.hasOwnProperty(b)||(a[b]={szPath:e,oSprite:new Image},c++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(e)};this._onSpriteLoaded=function(){g.call(e);++b==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=1280,CANVAS_HEIGHT=768,CANVAS_WIDTH_HALF=.5*CANVAS_WIDTH,CANVAS_HEIGHT_HALF=.5*CANVAS_HEIGHT,EDGEBOARD_X=90,EDGEBOARD_Y=95,DISABLE_SOUND_MOBILE=!1,FONT_GAME="Arial",SECONDARY_FONT="blackplotanregular",FPS=30,FPS_DESKTOP=60,FPS_TIME=1/FPS,ROLL_BALL_RATE=60/FPS,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_TWEEN_ENDED=6,ON_BUT_NO_DOWN=7,ON_BUT_YES_DOWN=8,STEP_RATE=1.5,TEXT_SIZE=[80,
100,130],TEXT_EXCELLENT_COLOR=["#fff","#5d96fe"],TEXT_COLOR="#ffffff",TEXT_COLOR_STROKE="#000000",TIME_INTERVAL_STROBE=.2,PHYSICS_ACCURACY=3,MOBILE_OFFSET_GLOVES_X=-100,BALL_VELOCITY_MULTIPLIER=1,PHYSICS_STEP=1/(FPS*STEP_RATE),STATE_INIT=0,STATE_PLAY=1,STATE_FINISH=2,STATE_PAUSE=3,BALL_MASS=.5,BALL_RADIUS=1,BALL_LINEAR_DAMPING=.2,OFFSET_BALL_POS_X=10,OBJECT,TIME_TRY_TO_SHOT_BALL_OPPONENT=.7,START_POS_FLAG={x:277,y:268},FLAG_ADDED_POS={x:61,y:69},FLAG_LIMIT_POS_X=690,TOT_TEAM=32,MIN_BALL_VEL_ROTATION=
.1,TIME_RESET_AFTER_GOAL=1,TIME_RESET_AFTER_KEEPER_SAVED=2,TIME_RESET_AFTER_PERFECT_KEEPER_SAVED=3,TIME_BALL_IN_HAND=1E3,FOV=45,INTERVAL_SHOOT=1,HAND_KEEPER_ANGLE_RATE=.15,LIMIT_HAND_RANGE_POS={x:16.8,zMax:3.1,zMin:-8.5},BACK_WALL_GOAL_SIZE={width:17.5,depth:.1,height:7.5},LEFT_RIGHT_WALL_GOAL_SIZE={width:.1,depth:25,height:7.5},UP_WALL_GOAL_SIZE={width:17.5,depth:25,height:.1},BACK_WALL_GOAL_POSITION={x:0,y:8,z:-2.7},POSITION_BALL={x:0,y:125,z:-9},GOAL_LINE_POS={x:0,y:31,z:-2.7},HAND_KEEPER_SIZE=
{width:1.8,depth:.5,height:1.5},HAND_KEEPER_POSITION={x:0,y:36,z:0},POLE_UP_SIZE={radius_top:.5,radius_bottom:.5,height:35,segments:10},POLE_RIGHT_LEFT_SIZE={radius_top:.5,radius_bottom:.5,height:15,segments:10},GOAL_POSITION={x:0,y:33,z:-2.7},OFFSET_FIELD_Y=35,OFFSET_FIELD_X=35,HIT_BALL_MAX_FORCE=100,HIT_BALL_MIN_FORCE=.01,FIELD_POSITION,SHOW_3D_RENDER=!1,CAMERA_TEST=!1,MOUSE_SENSIBILTY=.03,BALL_Z_FORCE_RANGE={min:3,max:10},INTENSITY_DISPLAY_SHOCK=[{x:30,y:20,time:75},{x:50,y:25,time:75},{x:70,y:30,
time:75},{x:90,y:40,time:75}],CAMERA_POSITION={x:0,y:0,z:100},NEAR=10,FAR=2E3;
function CWinPanel(a,c){var b,g,f,e,d,h,k,l,n,p,m;this._init=function(a,c){m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);m.alpha=0;s_oStage.addChild(m);l=new createjs.Container;l.alpha=1;l.visible=!1;l.y=CANVAS_HEIGHT;b=createBitmap(a);b.x=CANVAS_WIDTH_HALF;b.y=CANVAS_HEIGHT_HALF;b.regX=.5*a.width;b.regY=.5*a.height;l.addChild(b);f=new createjs.Text("","bold 50px "+FONT_GAME,"#ffffff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT_HALF-230;f.textAlign="center";
l.addChild(f);g=new createjs.Text("","bold 34px "+FONT_GAME,"#ffffff");g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2-120;g.textAlign="center";g.textBaseline="middle";l.addChild(g);e=new createjs.Text("","34px "+FONT_GAME,"#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-70;e.textAlign="center";l.addChild(e);d=new createjs.Text("","34px "+FONT_GAME,"#ffffff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-10;d.textAlign="center";l.addChild(d);h=new createjs.Text("","34px "+FONT_GAME,"#ffffff");h.x=CANVAS_WIDTH/2;
h.y=CANVAS_HEIGHT/2+50;h.textAlign="center";l.addChild(h);k=new createjs.Text("","bold 34px "+FONT_GAME,"#ffffff");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2+170;k.textAlign="center";l.addChild(k);var v=s_oSpriteLibrary.getSprite("but_continue");p=new CGfxButton(.5*CANVAS_WIDTH+360,.5*CANVAS_HEIGHT+180,v,l);p.pulseAnimation();!1===c?(v=s_oSpriteLibrary.getSprite("but_home"),n=new CGfxButton(.5*CANVAS_WIDTH-360,.5*CANVAS_HEIGHT+180,v,l),n.addEventListener(ON_MOUSE_DOWN,this._onExit,this),p.addEventListener(ON_MOUSE_DOWN,
this._onContinue,this)):p.addEventListener(ON_MOUSE_DOWN,this._onEnd,this);s_oStage.addChild(l)};this.unload=function(){s_oStage.removeChild(l);n&&(n.unload(),n=null);p&&(p.unload(),p=null)};this.show=function(a,b,c,n){f.text=TEXT_WIN;g.text=TEXT_WIN_RESULT+" "+a+" "+TEXT_OF+" "+c+" "+TEXT_BALLS;e.text=TEXT_SCORE_BALL_SAVED+": "+n.ball_saved;d.text=TEXT_SCORE_BALL_SAVED_PERFECT+": "+n.ball_saved_perfect;h.text=TEXT_GOAL_OPPONENT+": "+n.opponent_goal;k.text=TEXT_TOTAL_SCORE+": "+n.new_score;l.visible=
!0;createjs.Tween.get(m).to({alpha:.5},500,createjs.Ease.cubicOut);createjs.Tween.get(l).wait(250).to({y:0},1250,createjs.Ease.bounceOut).call(function(){s_iAdsLevel===NUM_LEVEL_FOR_ADS?($(s_oMain).trigger("show_interlevel_ad"),s_iAdsLevel=1):s_iAdsLevel++});$(s_oMain).trigger("save_score",n.new_score);$(s_oMain).trigger("share_event",n.new_score)};this._onContinue=function(){var a=this;createjs.Tween.get(l).to({y:CANVAS_HEIGHT},750,createjs.Ease.quartIn).call(function(){a.unload()});createjs.Tween.get(m).to({alpha:0},
400,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(m);m.removeAllEventListeners()});p.block(!0);n.block(!0);s_oGame.onContinue(s_oStage.getChildIndex(l))};this._onEnd=function(){this.unload();s_oGame._onEnd()};this._onExit=function(){this.unload();m.off("click",function(){});s_oGame.onExit()};this._init(a,c);return this}
function CToggle(a,c,b,g,f){var e,d,h,k,l;this._init=function(a,b,c,f,g){l=void 0!==g?g:s_oStage;d=[];h=[];g=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});e=f;k=createSprite(g,"state_"+e,c.width/2/2,c.height/2,c.width/2,c.height);k.x=a;k.y=b;k.stop();s_bMobile||(k.cursor="pointer");l.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",
this.buttonRelease);l.removeChild(k)};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){d[a]=b;h[a]=c};this.setCursorType=function(a){k.cursor=a};this.setActive=function(a){e=a;k.gotoAndStop("state_"+e)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("click",1,0);e=!e;k.gotoAndStop("state_"+e);d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(h[ON_MOUSE_UP],e)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=
.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=function(a,b){k.x=a;k.y=b};this._init(a,c,b,g,f)}var s_iOffsetX=0,s_iOffsetY=0,s_fInverseScaling=0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}window.addEventListener("orientationchange",onOrientationChange);
function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(a){var c=a.toLowerCase(),b=window.document,g=b.documentElement;if(void 0===window["inner"+a])a=g["client"+a];else if(window["inner"+a]!=g["client"+a]){var f=b.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var e=b.createElement("div");e.id="vpw-test-d";e.style.cssText="position:absolute;top:-1000px";e.innerHTML="<style>@media("+c+":"+g["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";f.appendChild(e);g.insertBefore(f,b.head);
a=7==e["offset"+a]?g["client"+a]:window["inner"+a];g.removeChild(f)}else a=window["inner"+a];return a}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width");s_iScaleFactor=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH);var b=CANVAS_WIDTH*s_iScaleFactor,g=CANVAS_HEIGHT*s_iScaleFactor,f;g<a?(f=a-g,g+=f,b+=CANVAS_WIDTH/CANVAS_HEIGHT*f):b<c&&(f=c-b,b+=f,g+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-g/2;var e=c/2-b/2,d=CANVAS_WIDTH/b;if(e*d<-EDGEBOARD_X||f*d<-EDGEBOARD_Y)s_iScaleFactor=Math.min(a/
(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=CANVAS_WIDTH*s_iScaleFactor,g=CANVAS_HEIGHT*s_iScaleFactor,f=(a-g)/2,e=(c-b)/2,d=CANVAS_WIDTH/b;s_fInverseScaling=d;s_iOffsetX=-1*e*d;s_iOffsetY=-1*f*d;0<=f&&(s_iOffsetY=0);0<=e&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",b+"px");
$("#canvas").css("height",g+"px");0>f?($("#canvas").css("top",f+"px"),s_iCanvasOffsetHeight=f):($("#canvas").css("top","0px"),s_iCanvasOffsetHeight=0);$("#canvas").css("left",e+"px");resizeCanvas3D();s_iCanvasResizeWidth=b;s_iCanvasResizeHeight=g;s_iCanvasOffsetWidth=e}}function createBitmap(a,c,b){var g=new createjs.Bitmap(a),f=new createjs.Shape;c&&b?f.graphics.beginFill("#fff").drawRect(-c/2,-b/2,c,b):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);g.hitArea=f;return g}
function createSprite(a,c,b,g,f,e){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-g,f,e);a.hitArea=c;return a}function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function shuffle(a){for(var c=a.length,b,g;0!==c;)g=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[g],a[g]=b;return a}
function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=parseFloat(a-60*c).toFixed(1);var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,c){var b,g;b=getBounds(a,.9);g=getBounds(c,.98);return calculateIntersection(b,g)}
function calculateIntersection(a,c){var b,g,f,e,d,h,k,l;b=a.x+(f=a.width/2);g=a.y+(e=a.height/2);d=c.x+(h=c.width/2);k=c.y+(l=c.height/2);b=Math.abs(b-d)-(f+h);g=Math.abs(g-k)-(e+l);return 0>b&&0>g?(b=Math.min(Math.min(a.width,c.width),-b),g=Math.min(Math.min(a.height,c.height),-g),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:b,height:g,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var g=a.children,f=g.length,e,d;for(d=0;d<f;d++)e=getBounds(g[d],1),e.x<b.x&&(b.x=e.x),e.y<b.y&&(b.y=e.y),e.x+e.width>b.x2&&(b.x2=e.x+e.width),e.y+e.height>b.y2&&(b.y2=e.y+e.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var h,k;a instanceof createjs.Bitmap?
(f=a.sourceRect||a.image,d=f.width*c,h=f.height*c):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(f=a.spriteSheet.getFrame(a.currentFrame),d=f.rect.width,h=f.rect.height,g=f.regX,k=f.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);g=g||0;d=d||0;k=k||0;h=h||0;b.regX=g;b.regY=k;f=a.localToGlobal(0-g,0-k);e=a.localToGlobal(d-g,h-k);d=a.localToGlobal(d-g,0-k);g=a.localToGlobal(0-g,h-k);b.x=Math.min(Math.min(Math.min(f.x,
e.x),d.x),g.x);b.y=Math.min(Math.min(Math.min(f.y,e.y),d.y),g.y);b.width=Math.max(Math.max(Math.max(f.x,e.x),d.x),g.x)-b.x;b.height=Math.max(Math.max(Math.max(f.y,e.y),d.y),g.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(a){var g={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in g?document.body.className=g[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function playSound(a,c,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:c}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}
function setVolume(a,c){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=c}function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(c)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var g=c[b].split("=");if(g[0]==a)return g[1]}}
function rotateVector2D(a,c){return{x:c.x*Math.cos(a)+c.y*Math.sin(a),y:c.x*-Math.sin(a)+c.y*Math.cos(a)}}function normalize(a,c){0<c&&(a.x/=c,a.y/=c);return a}function length(a){return Math.sqrt(a.x*a.x+a.y*a.y)}function findNearestIntersectingObject(a,c,b,g){var f=CANVAS_RESIZE_WIDTH+2*OFFSET_WIDTH,e=CANVAS_RESIZE_HEIGHT+2*OFFSET_HEIGHT,d=new THREE.Raycaster,h=new THREE.Vector3;h.x=a/f*2-1;h.y=2*-(c/e)+1;h.z=.5;d.setFromCamera(h,b);a=d.intersectObjects(g,!0);c=!1;0<a.length&&(c=a[0]);return c}
function distance(a,c,b,g){a-=b;c-=g;return Math.sqrt(a*a+c*c)}function distance2(a,c,b,g){a-=b;c-=g;return a*a+c*c}function resizeCanvas3D(){$("canvas").each(function(){"#canvas"!=$(this).attr("id")&&($(this).css("width",$("#canvas").css("width")),$(this).css("height",$("#canvas").css("height")),$(this).css("position",$("#canvas").css("position")),$(this).css("left",$("#canvas").css("left")),$(this).css("top",$("#canvas").css("top")))})}
function createOrthoGraphicCamera(){var a=new THREE.PerspectiveCamera(FOV,CANVAS_WIDTH/CANVAS_HEIGHT,NEAR,FAR);a.rotation.x=Math.PI/180*90;a.position.set(0,0,0);a.updateProjectionMatrix();a.updateMatrixWorld();return a}function rotateVector2D(a,c){return{x:c.x*Math.cos(a)+c.y*Math.sin(a),y:c.x*-Math.sin(a)+c.y*Math.cos(a),z:0}}Math.radians=function(a){return a*Math.PI/180};Math.degrees=function(a){return 180*a/Math.PI};
function distanceV3(a,c,b,g,f,e){a-=g;c-=f;b-=e;return Math.sqrt(a*a+c*c+b*b)}function distanceV2(a,c){var b=a.x-c.x,g=a.y-c.y;return Math.sqrt(b*b+g*g)}function saveItem(a,c){localStorage.setItem(a,c)}function getItem(a){return localStorage.getItem(a)}function clearAllItem(){localStorage.clear()}
function CTextButton(a,c,b,g,f,e,d){var h,k,l;this._init=function(a,b,c,d,e,f,g){h=[];k=[];var x=createBitmap(c),y=Math.ceil(g/20),w=new createjs.Text(d,"bold "+g+"px "+e,"#000000");w.textAlign="center";w.textBaseline="alphabetic";var t=w.getBounds();w.x=c.width/2+y;w.y=Math.floor(c.height/2)+t.height/3+y;d=new createjs.Text(d,"bold "+g+"px "+e,f);d.textAlign="center";d.textBaseline="alphabetic";t=d.getBounds();d.x=c.width/2;d.y=Math.floor(c.height/2)+t.height/3;l=new createjs.Container;l.x=a;l.y=
b;l.regX=c.width/2;l.regY=c.height/2;l.addChild(x,w,d);s_bMobile||(l.cursor="pointer");s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;k[a]=c};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;playSound("click",1,0);h[ON_MOUSE_UP]&&
h[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(a,c,b,g,f,e,d);return this}
function CScenario(){var a,c,b,g,f,e,d,h,k,l,n,p,m,r,u,v,q,x,y,w,t,A;if(SHOW_3D_RENDER)var C=new CANNON.Demo;this.getDemo=function(){return C};this._init=function(){a=SHOW_3D_RENDER?C.getWorld():new CANNON.World;a.gravity.set(0,0,-9.81);a.broadphase=new CANNON.NaiveBroadphase;a.solver.iterations=50;a.solver.tolerance=1E-5;c=new CANNON.Material;b=new CANNON.Material;g=new CANNON.Material;f=new CANNON.Material;var d=new CANNON.ContactMaterial(b,g,{friction:.1,restitution:.5}),e=new CANNON.ContactMaterial(b,
c,{friction:.2,restitution:.3}),k=new CANNON.ContactMaterial(b,f,{friction:.5,restitution:.1});a.addContactMaterial(d);a.addContactMaterial(e);a.addContactMaterial(k);s_oScenario._createBallBody();s_oScenario._createFieldBody();s_oScenario._createGoal();s_oScenario.createBackGoalWall();s_oScenario.createLineOfGoal();s_oScenario.createHandGoalKeeper()};this._createFieldBody=function(){k=new CANNON.Plane;l=new CANNON.Body({mass:0,material:c});l.addShape(k);l.position.z=-10;l.addEventListener("collide",
function(a){s_oScenario.fieldCollision()});a.addBody(l);SHOW_3D_RENDER&&C.addVisual(l)};this._createGoal=function(){n=new CANNON.Cylinder(POLE_RIGHT_LEFT_SIZE.radius_top,POLE_RIGHT_LEFT_SIZE.radius_bottom,POLE_RIGHT_LEFT_SIZE.height,POLE_RIGHT_LEFT_SIZE.segments);m=new CANNON.Body({mass:0});p=new CANNON.Cylinder(POLE_UP_SIZE.radius_top,POLE_UP_SIZE.radius_bottom,POLE_UP_SIZE.height,POLE_UP_SIZE.segments);var b=new CANNON.Quaternion;b.setFromAxisAngle(new CANNON.Vec3(0,1,0),Math.PI/2);p.transformAllPoints(new CANNON.Vec3,
b);m.addShape(n,new CANNON.Vec3(.5*POLE_UP_SIZE.height,0,0));m.addShape(n,new CANNON.Vec3(.5*-POLE_UP_SIZE.height,0,0));m.addShape(p,new CANNON.Vec3(0,0,.5*POLE_RIGHT_LEFT_SIZE.height));m.position.set(GOAL_POSITION.x,GOAL_POSITION.y,GOAL_POSITION.z);m.addEventListener("collide",function(a){s_oScenario.poleCollision()});a.addBody(m);SHOW_3D_RENDER&&C.addVisual(m)};this.createBackGoalWall=function(){r=new CANNON.Box(new CANNON.Vec3(BACK_WALL_GOAL_SIZE.width,BACK_WALL_GOAL_SIZE.depth,BACK_WALL_GOAL_SIZE.height));
u=new CANNON.Box(new CANNON.Vec3(LEFT_RIGHT_WALL_GOAL_SIZE.width,LEFT_RIGHT_WALL_GOAL_SIZE.depth,LEFT_RIGHT_WALL_GOAL_SIZE.height));v=new CANNON.Box(new CANNON.Vec3(UP_WALL_GOAL_SIZE.width,UP_WALL_GOAL_SIZE.depth,UP_WALL_GOAL_SIZE.height));q=new CANNON.Body({mass:0,material:g});q.addShape(r);q.addShape(u,new CANNON.Vec3(BACK_WALL_GOAL_SIZE.width,0,0));q.addShape(u,new CANNON.Vec3(-BACK_WALL_GOAL_SIZE.width,0,0));q.addShape(v,new CANNON.Vec3(0,0,BACK_WALL_GOAL_SIZE.height));q.addEventListener("collide",
function(a){s_oScenario.goalCollision(a)});q.position.set(BACK_WALL_GOAL_POSITION.x,BACK_WALL_GOAL_POSITION.y,BACK_WALL_GOAL_POSITION.z);a.addBody(q);SHOW_3D_RENDER&&C.addVisual(q)};this.createLineOfGoal=function(){x=new CANNON.Box(new CANNON.Vec3(BACK_WALL_GOAL_SIZE.width,BACK_WALL_GOAL_SIZE.depth,BACK_WALL_GOAL_SIZE.height));y=new CANNON.Body({mass:0});y.addShape(x);y.position.set(GOAL_LINE_POS.x,GOAL_LINE_POS.y,GOAL_LINE_POS.z);y.collisionResponse=0;y.addEventListener("collide",function(a){s_oScenario.lineGoalCollision()});
a.addBody(y)};this.createHandGoalKeeper=function(){w=new CANNON.Box(new CANNON.Vec3(HAND_KEEPER_SIZE.width,HAND_KEEPER_SIZE.depth,HAND_KEEPER_SIZE.height));t=new CANNON.Body({mass:0,material:f});t.addShape(w);t.position.set(HAND_KEEPER_POSITION.x,HAND_KEEPER_POSITION.y,HAND_KEEPER_POSITION.z);t.addEventListener("collide",function(a){s_oScenario.handCollision(a)});a.addBody(t);SHOW_3D_RENDER&&(A=C.addVisual(t))};this._createBallBody=function(){e=new CANNON.Sphere(BALL_RADIUS);d=new CANNON.Body({mass:BALL_MASS,
material:b,linearDamping:BALL_LINEAR_DAMPING,angularDamping:2*BALL_LINEAR_DAMPING});var c=new CANNON.Vec3(POSITION_BALL.x,POSITION_BALL.y,POSITION_BALL.z);d.position.copy(c);d.addShape(e);a.add(d);SHOW_3D_RENDER&&(h=C.addVisual(d))};this.addImpulse=function(a,b){var c=new CANNON.Vec3(0,0,BALL_RADIUS),d=new CANNON.Vec3(b.x,b.y,b.z);a.applyImpulse(d,c)};this.addForce=function(a,b){var c=new CANNON.Vec3(0,0,0),d=new CANNON.Vec3(b.x,b.y,b.z);a.applyForce(d,c)};this.getBodyVelocity=function(a){return a.velocity};
this.ballBody=function(){return d};this.ballMesh=function(){return h};this.getCamera=function(){return C.camera()};this.fieldCollision=function(){s_oGame.ballFadeForReset();playSound("drop_bounce_grass",1,0)};this.collisionWithBall=function(){s_oGame.lineGoalCollision()};this.setElementAngularVelocity=function(a,b){a.angularVelocity.set(b.x,b.y,b.z)};this.setElementVelocity=function(a,b){var c=new CANNON.Vec3(b.x,b.y,b.z);a.velocity=c};this.setElementLinearDamping=function(a,b){a.linearDamping=b};
this.getFieldBody=function(){return l};this.lineGoalCollision=function(){s_oGame.goal()};this.handCollision=function(a){s_oGame.keeperSave(a.contact.rj)};this.update=function(){a.step(PHYSICS_STEP)};this.getHandKeeperBody=function(){return t};this.getHandKeeperMesh=function(){return A};this.getGoalBody=function(){return m};this.goalCollision=function(a){s_oGame.goalAnimation(a.body.velocity.x*a.body.velocity.x+a.body.velocity.y*a.body.velocity.y)};this.poleCollision=function(){playSound("kick",1,
0)};this.destroyWorld=function(){for(var b=a.bodies,c=0;c<b.length;c++)a.remove(b[c]);a=null};s_oScenario=this;SHOW_3D_RENDER?(C.addScene("Test",this._init),C.start()):this._init()}var s_oScenario;
function CPreloader(){var a,c,b,g,f,e,d,h;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();h=new createjs.Container;s_oStage.addChild(h)};this.unload=function(){h.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(d).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));h.addChild(k);k=s_oSpriteLibrary.getSprite("progress_bar");f=createBitmap(k);f.x=CANVAS_WIDTH/2-k.width/2;f.y=CANVAS_HEIGHT-200;h.addChild(f);a=k.width;c=k.height;e=new createjs.Shape;e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,f.y,1,c);h.addChild(e);f.mask=
e;b=new createjs.Text("","30px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-200;b.textBaseline="alphabetic";b.textAlign="center";h.addChild(b);g=new createjs.Text("","30px "+SECONDARY_FONT,"#fff");g.x=CANVAS_WIDTH+200;g.y=CANVAS_HEIGHT+200;g.textBaseline="alphabetic";g.textAlign="center";h.addChild(g);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;h.addChild(d)};this.refreshLoader=function(d){b.text=d+"%";g.text=d+"%";e.graphics.clear();
d=Math.floor(d*a/100);e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,f.y,d,c)};this._init()}
function CPause(){var a,c;this._init=function(){a=new createjs.Container;a.alpha=0;c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=.5;c.on("click",function(){});a.addChild(c);var b=new createjs.Text(TEXT_PAUSE,"bold 70px "+FONT_GAME,TEXT_COLOR);b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT-100;b.textAlign="center";a.addChild(b);b=s_oSpriteLibrary.getSprite("but_continue");(new CGfxButton(.5*CANVAS_WIDTH,.5*CANVAS_HEIGHT+90,b,a)).addEventListener(ON_MOUSE_UP,
this._onLeavePause,this);s_oStage.addChild(a);var g=this;createjs.Tween.get(a).to({alpha:1},150,createjs.quartOut).call(function(){g.onPause(!0)})};this.onPause=function(a){s_oGame.pause(a)};this.unload=function(){c.off("click",function(){});s_oStage.removeChild(a)};this._onLeavePause=function(){playSound("click",1,0);createjs.Ticker.paused=!1;createjs.Tween.removeTweens(a);var b=this;createjs.Tween.get(a).to({alpha:0},150,createjs.quartIn).call(function(){b.onPause(!1);s_oInterface.unloadPause()})};
this._init();return this}
function COpponent(a,c,b,g){var f,e;this._init=function(a,b,c,g){e=g;g=new createjs.SpriteSheet({images:[c],frames:{width:c.width/10,height:c.height/8,regX:c.width/2/10,regY:c.height/8},animations:{shot:[0,44,"stay",30/FPS],stay:[45,79,"remain",30/FPS],remain:[79]}});f=createSprite(g,"shot",c.width/2/10,c.height/8,c.width/10,c.height/8);f.x=a;f.y=b;f.alpha=0;e.addChild(f)};this.getX=function(){return f.x};this.getY=function(){return f.y};this.setPosition=function(a,b){null!==a&&(f.x=a);null!==b&&
(f.y=b)};this.rotate=function(a){f.scaleX=a};this.setVisible=function(a){f.visible=a};this.changeState=function(a){f.gotoAndPlay(a)};this.stopAnimation=function(){f.stop()};this.playAnimation=function(){f.play()};this.onFinishAnimation=function(){var a=this;f.on("animationend",function(){s_oGame.addImpulseToBall();playSound("kick",.3,0);f.removeAllEventListeners();a.fadeAnimation(0)})};this.fadeAnimation=function(a){createjs.Tween.get(f).to({alpha:a},500)};this.removeTweens=function(){createjs.Tween.removeTweens(f)};
this._init(a,c,b,g);return this}
function CMenu(a){var c,b,g,f,e,d,h,k,l,n,p,m,r=null,u;this._init=function(){h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(h);var a=s_oSpriteLibrary.getSprite("but_play");g=CANVAS_WIDTH/2;f=CANVAS_HEIGHT-230;k=new CGfxButton(g,f,a);k.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(null!==getItem("LevelReached")){s_iLastLevel=getItem("LevelReached");s_aScores=JSON.parse(getItem("Scores"));k.setPosition(CANVAS_WIDTH/2-200,CANVAS_HEIGHT-230);var r=s_oSpriteLibrary.getSprite("but_continue_big");
n=new CGfxButton(CANVAS_WIDTH/2+200,CANVAS_HEIGHT-230,r);n.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this);n.pulseAnimation()}else k.setPosition(CANVAS_WIDTH/2,584),k.pulseAnimation(),this.resetArrayScores();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a=s_oSpriteLibrary.getSprite("audio_icon"),e=CANVAS_WIDTH-a.height/2-10,d=a.height/2+10,m=new CToggle(e,d,a,s_bAudioActive),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);r=s_oSpriteLibrary.getSprite("but_info");c=a.height/2+
10;b=a.height/2+10;l=new CGfxButton(c,b,r,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onButInfoRelease,this);p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(p);createjs.Tween.get(p).to({alpha:0},1E3).call(function(){p.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(a,f){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(e-a,f+d);l.setPosition(c+a,b+f)};this.unload=function(){k.unload();
k=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;s_oStage.removeAllChildren();s_oMenu=null};this._onButPlayRelease=function(){null===getItem("LevelReached")?(this.unload(),playSound("click",1,0),s_oMain.gotoLevelMenu()):null===r&&(r=new CConfirmPanel(TEXT_RESET,0),r.addEventListener(ON_BUT_NO_DOWN,this._onButNo,this),r.addEventListener(ON_BUT_YES_DOWN,this._onButYes,this))};this._onButContinueRelease=function(){this.unload();playSound("click",1,0);s_oMain.gotoLevelMenu()};this._onButNo=
function(){r.unload();r=null};this._onButYes=function(){clearAllItem();this.unload();s_iLastLevel=1;this.resetArrayScores();s_oMain.gotoLevelMenu()};this.resetArrayScores=function(){s_aScores=[];for(var a=0;a<u;a++)s_aScores[a]=0};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButInfoRelease=function(){new CCreditsPanel};s_oMenu=this;u=a;this._init()}var s_oMenu=null;
function CMain(a){var c,b=0,g=0,f=STATE_LOADING,e,d,h;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_oStage.preventSelection=!1;s_bMobile=jQuery.browser.mobile;!1===s_bMobile?(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}),FPS=FPS_DESKTOP,FPS_TIME=1/FPS,PHYSICS_STEP=1/(FPS*STEP_RATE),ROLL_BALL_RATE=60/FPS):BALL_VELOCITY_MULTIPLIER=.8;s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",
this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;d=new CPreloader;c=!0};this.soundLoaded=function(){b++;d.refreshLoader(Math.floor(b/g*100));if(b===g){d.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?
(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.ogg","click"),createjs.Sound.registerSound("./sounds/drop_bounce_grass.ogg","drop_bounce_grass"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/goal.ogg","goal"),createjs.Sound.registerSound("./sounds/keep_ball.ogg","keep_ball"),createjs.Sound.registerSound("./sounds/kick.ogg",
"kick"),createjs.Sound.registerSound("./sounds/win.ogg","win")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.mp3","click"),createjs.Sound.registerSound("./sounds/drop_bounce_grass.mp3","drop_bounce_grass"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/goal.mp3","goal"),createjs.Sound.registerSound("./sounds/keep_ball.mp3",
"keep_ball"),createjs.Sound.registerSound("./sounds/kick.mp3","kick"),createjs.Sound.registerSound("./sounds/win.mp3","win")),g+=7)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_restart_small","./sprites/but_restart_small.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");
s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("msg_box_small","./sprites/msg_box_small.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_continue_big","./sprites/but_continue_big.png");s_oSpriteLibrary.addSprite("ball",
"./sprites/ball.png");s_oSpriteLibrary.addSprite("but_level","./sprites/but_level.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("gloves","./sprites/gloves.png");s_oSpriteLibrary.addSprite("goal","./sprites/goal.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");
s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("but_pause","./sprites/but_pause.png");s_oSpriteLibrary.addSprite("arrow_right","./sprites/arrow_right.png");s_oSpriteLibrary.addSprite("arrow_left","./sprites/arrow_left.png");s_oSpriteLibrary.addSprite("opponent","./sprites/opponent.png");s_oSpriteLibrary.addSprite("ball_shadow","./sprites/ball_shadow.png");s_oSpriteLibrary.addSprite("gui_panel","./sprites/gui_panel.png");s_oSpriteLibrary.addSprite("help_mouse",
"./sprites/help_mouse.png");s_oSpriteLibrary.addSprite("help_touch","./sprites/help_touch.png");g+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;d.refreshLoader(Math.floor(b/g*100));if(b===g){d.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.preloaderReady=function(){if(!1===
DISABLE_SOUND_MOBILE||!1===s_bMobile)this._initSounds(),s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this._loadImages();c=!0};this.gotoMenu=function(){new CMenu(a.ball_to_saved.length);f=STATE_MENU};this.gotoGame=function(a){h=new CGame(e,a);f=STATE_GAME};this.gotoLevelMenu=function(){new CLevelMenu(a.ball_to_saved.length);f=STATE_MENU};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=
function(){s_iPrevTime=(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==c){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;e=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oPhysicsController,s_iLevelReached=18,s_iCanvasResizeHeight,s_iCanvasResizeWidth,s_iCanvasOffsetHeight,s_iCanvasOffsetWidth,s_iAdsLevel=1,s_iLastLevel=1,s_aScores=[],s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack;
function CLosePanel(a){var c,b,g,f,e=null,d,h,k=!1;this._init=function(a){h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=0;s_oStage.addChild(h);f=new createjs.Container;f.alpha=1;f.visible=!1;f.y=CANVAS_HEIGHT;c=createBitmap(a);c.x=CANVAS_WIDTH_HALF;c.y=CANVAS_HEIGHT_HALF;c.regX=.5*a.width;c.regY=.5*a.height;f.addChild(c);b=new createjs.Text("","45px "+FONT_GAME,"#ffffff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT_HALF;b.textAlign="center";b.textBaseline=
"middle";f.addChild(b);g=new createjs.Text("","bold 100px "+FONT_GAME,"#ffffff");g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT_HALF-210;g.textAlign="center";f.addChild(g);s_oStage.addChild(f);a=s_oSpriteLibrary.getSprite("but_home");e=new CGfxButton(.5*CANVAS_WIDTH-360,.5*CANVAS_HEIGHT+180,a,f);e.addEventListener(ON_MOUSE_DOWN,this._onExit,this);a=s_oSpriteLibrary.getSprite("but_restart");d=new CGfxButton(.5*CANVAS_WIDTH+360,.5*CANVAS_HEIGHT+180,a,f);d.addEventListener(ON_MOUSE_DOWN,this._onRestart,this);
d.pulseAnimation()};this.unload=function(){createjs.Tween.get(f).to({alpha:0},500,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(f);null!==e&&(e.unload(),e=null);h.removeAllEventListeners();d.unload();d=null})};this.show=function(a,c){b.text=TEXT_LOSE_RESULT+" "+a+" "+TEXT_OF+" "+c+" "+TEXT_BALLS;g.text=TEXT_LOSE;f.visible=!0;createjs.Tween.get(h).to({alpha:.5},500,createjs.Ease.cubicOut);h.on("click",function(){});createjs.Tween.get(f).wait(250).to({y:0},1250,createjs.Ease.elasticOut).call(function(){s_iAdsLevel===
NUM_LEVEL_FOR_ADS?($(s_oMain).trigger("show_interlevel_ad"),s_iAdsLevel=1):s_iAdsLevel++})};this._onRestart=function(){k||(k=!0,this.unload(),createjs.Tween.get(h).to({alpha:0},400,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(h)}),s_oGame.restartLevel())};this._onExit=function(){k||(k=!0,this.unload(),s_oGame.onExit())};this._init(a);return this}var NUM_ROWS_PAGE_LEVEL=2,NUM_COLS_PAGE_LEVEL=5;
function CLevelMenu(a){var c,b,g,f,e,d,h,k,l,n,p,m,r,u,v,q,x=null,y=null,w,t,A;this._init=function(){n=0;t=new createjs.Container;s_oStage.addChild(t);var m=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));t.addChild(m);m=s_oSpriteLibrary.getSprite("goal");new CGoal(0,0,m,null,t);var m=s_oSpriteLibrary.getSprite("msg_box"),B=createBitmap(m);B.x=CANVAS_WIDTH_HALF;B.y=CANVAS_HEIGHT_HALF;B.regX=.5*m.width;B.regY=.5*m.height;t.addChild(B);k=CANVAS_WIDTH/2;l=CANVAS_HEIGHT_HALF-210;w=new createjs.Text(TEXT_SELECT_A_LEVEL,
"bold 60px "+FONT_GAME,TEXT_COLOR);w.x=k;w.y=l;w.textAlign="center";s_oStage.addChild(w);m=s_oSpriteLibrary.getSprite("but_exit");d=CANVAS_WIDTH-m.height/2-10;h=m.height/2+10;v=new CGfxButton(d,h,m,s_oStage);v.addEventListener(ON_MOUSE_UP,this._onExit,this);p=m.height;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=v.getX()-m.width-10,e=m.height/2+10,q=new CToggle(f,e,s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive),q.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this._checkBoundLimits();
r=[];for(var m=Math.floor((CANVAS_WIDTH+EDGEBOARD_X)/NUM_COLS_PAGE_LEVEL)/2,B=.7*-EDGEBOARD_X,D=0;D<NUM_COLS_PAGE_LEVEL;D++)r.push(B),B+=m;u=[];this._createNewLevelPage(0,a);if(1<u.length){for(m=1;m<u.length;m++)u[m].visible=!1;b=CANVAS_WIDTH-180;g=CANVAS_HEIGHT_HALF;x=new CGfxButton(b,g,s_oSpriteLibrary.getSprite("arrow_right"),s_oStage);x.addEventListener(ON_MOUSE_UP,this._onRight,this);c=CANVAS_HEIGHT_HALF;y=new CGfxButton(180,c,s_oSpriteLibrary.getSprite("arrow_left"),s_oStage);y.addEventListener(ON_MOUSE_UP,
this._onLeft,this)}A=new createjs.Shape;A.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(A);createjs.Tween.get(A).to({alpha:0},1E3).call(function(){s_oStage.removeChild(A);A=null});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){for(var a=0;a<m.length;a++)m[a].unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q.unload(),q=null;v.unload();v=null;null!==y&&(y.unload(),x.unload());s_oLevelMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=
function(a,b){v.setPosition(d-a,h+b);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||q.setPosition(f-a,b+e)};this._checkBoundLimits=function(){for(var a=s_oSpriteLibrary.getSprite("but_level"),b=0,c=CANVAS_HEIGHT-2*EDGEBOARD_Y-2*p,d=0;b<c;)b+=a.height+20,d++;NUM_ROWS_PAGE_LEVEL>d&&(NUM_ROWS_PAGE_LEVEL=d);c=b=0;d=CANVAS_WIDTH-2*EDGEBOARD_X;for(a=s_oSpriteLibrary.getSprite("but_level");c<d;)c+=a.width/2+5,b++;NUM_COLS_PAGE_LEVEL>b&&(NUM_COLS_PAGE_LEVEL=b)};this._createNewLevelPage=function(a,b){var c=new createjs.Container;
t.addChild(c);u.push(c);m=[];for(var d=0,e=-230,f=1,g=!1,h=s_oSpriteLibrary.getSprite("but_level"),k=a;k<b;k++){var l=new CLevelBut(r[d]+h.width/2,e+h.height/2,k+1,h,k+1>s_iLastLevel?!1:!0,c);l.addEventListenerWithParams(ON_MOUSE_UP,this._onButLevelRelease,this,k);m.push(l);d++;if(d===r.length&&(d=0,e+=h.height+20,f++,f>NUM_ROWS_PAGE_LEVEL&&k<b-1)){g=!0;break}}c.x=CANVAS_WIDTH/2;c.y=520;c.regX=c.getBounds().width/2;g&&this._createNewLevelPage(k+1,b)};this._onRight=function(){u[n].visible=!1;n++;n>=
u.length&&(n=0);u[n].visible=!0};this._onLeft=function(){u[n].visible=!1;n--;0>n&&(n=u.length-1);u[n].visible=!0};this._onButLevelRelease=function(a){this.unload();s_oMain.gotoGame(a)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){this.unload();s_oMain.gotoMenu()};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(a,c,b,g,f,e){var d,h,k,l=[],n=[],p,m,r,u,v,q;this._init=function(a,b,c,e,f){h=[];k=[];r=new createjs.Container;u.addChild(r);var g=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{state_true:[0],state_false:[1]}});d=f;m=createSprite(g,"state_"+d,e.width/2/2,e.height/2,e.width/2,e.height);m.mouseEnabled=f;m.x=a;m.y=b;m.stop();s_bMobile||(r.cursor="pointer");r.addChild(m);l.push(m);p=new createjs.Text(c,"bold 60px "+
FONT_GAME,TEXT_COLOR);p.x=a;p.y=b+20;p.textAlign="center";p.textBaseline="alphabetic";p.lineWidth=200;r.addChild(p);f||(p.color="#b4b4b4");this._initListener()};this.unload=function(){r.off("mousedown",v);r.off("pressup",q);r.removeChild(m)};this._initListener=function(){v=r.on("mousedown",this.buttonDown);q=r.on("pressup",this.buttonRelease)};this.viewBut=function(a){r.addChild(a)};this.addEventListener=function(a,b,c){h[a]=b;k[a]=c};this.addEventListenerWithParams=function(a,b,c,d){h[a]=b;k[a]=
c;n=d};this.ifClickable=function(){return!0===r.mouseEnabled?1:0};this.setActive=function(a,b){d=b;l[a].gotoAndStop("state_"+d);l[a].mouseEnabled=!0;p.color=d?"#69b8d5":"#b4b4b4"};this.buttonRelease=function(){d&&h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(k[ON_MOUSE_UP],n)};this.buttonDown=function(){h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],n)};this.setPosition=function(a,b){r.x=a;r.y=b};this.setVisible=function(a){r.visible=a};u=e;this._init(a,c,b,g,f,e)}TEXT_GAMEOVER="GAME OVER";
TEXT_OF="/";TEXT_HELP1_PC="MOVE THE MOUSE TO CONTROL THE KEEPER GLOVES TO DEFEND THE GOAL";TEXT_HELP1_MOBILE="MOVE THE FINGER TO CONTROL THE KEEPER GLOVES TO DEFEND THE GOAL";TEXT_COMPLETE="COMPLETE";TEXT_SELECT_A_LEVEL="SELECT A LEVEL";TEXT_TOTAL_SCORE="TOTAL SCORE";TEXT_WIN="YOU WON";TEXT_LOSE="YOU LOST";TEXT_BALLS="BALLS";TEXT_GOAL_OPPONENT="GOALS";TEXT_LAUNCH="KICK";TEXT_SCORE_BALL_SAVED="SAVINGS";TEXT_SCORE_BALL_SAVED_PERFECT="PERFECT SAVINGS";TEXT_MATCH_SCORE="MATCH SCORE";TEXT_GOAL="GOAL!";
TEXT_ARE_SURE="ARE YOU SURE?";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";TEXT_LINK1="WWW.CODETHISLAB.COM";TEXT_WIN_RESULT=TEXT_LOSE_RESULT="YOU SAVED";TEXT_RESET="ARE YOU SURE? ALL YOUR PREVIOUS SAVINGS WILL BE DELETED!";TEXT_MATCH="MATCH";TEXT_PAUSE="PAUSE";TEXT_HOW_TO_PLAY="HOW TO PLAY";TEXT_CONGRATULATION=["GOOD!","GREAT!","EXCELLENT!!!"];TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CInterface(){var a,c,b,g,f,e,d,h,k,l,n,p,m,r,u,v,q,x=null,y,w,t,A=null,C=null,B,D;this._init=function(){f=0;y=createBitmap(s_oSpriteLibrary.getSprite("gui_panel"));s_oStage.addChild(y);v=new createjs.Text(TEXT_SCORE_BALL_SAVED+"\n0","bold 32px "+FONT_GAME,"#ffffff");v.textAlign="center";v.x=.5*CANVAS_WIDTH;v.y=.5*v.getBounds().height;l=v.x;n=v.y;s_oStage.addChild(v);q=new createjs.Text(TEXT_LAUNCH+"\n0","bold 32px "+FONT_GAME,"#ffffff");q.textAlign="center";q.x=.5*CANVAS_WIDTH-290;q.y=.5*
q.getBounds().height;h=q.x;k=q.y;s_oStage.addChild(q);t=new createjs.Text(TEXT_MATCH+"\n0","bold 32px "+FONT_GAME,"#ffffff");t.textAlign="center";t.x=.5*CANVAS_WIDTH-570;t.y=.5*t.getBounds().height;e=t.x;d=t.y;s_oStage.addChild(t);var z=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-z.height/2-10;g=z.height/2+10;r=new CGfxButton(b,g,z);r.addEventListener(ON_MOUSE_UP,this._onExit,this);z=s_oSpriteLibrary.getSprite("but_pause");a=b-z.height-10;c=g;u=new CGfxButton(a,c,z);u.addEventListener(ON_MOUSE_UP,
this.onButPauseRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)z=s_oSpriteLibrary.getSprite("audio_icon"),p=a-z.height-10,m=g,w=new CToggle(p,m,z,s_bAudioActive),w.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(z,x){r.setPosition(b-z,x+g);u.setPosition(a-z,x+c);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||w.setPosition(p-z,x+m);y.y=f+x;v.x=l+z;v.y=n+x;q.x=h+z;q.y=k+x;t.x=e+z;t.y=d+x};this.unload=function(){r.unload();
r=null;this.onExitFromHelp();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)w.unload(),w=null;s_oInterface=null};this.refreshBallSaved=function(a,b){v.text=TEXT_SCORE_BALL_SAVED+"\n"+a+" "+TEXT_OF+" "+b};this.refreshLaunch=function(a,b){q.text=TEXT_LAUNCH+"\n"+a+" "+TEXT_OF+" "+b};this.onExitFromHelp=function(){null!==x&&(x.unload(),x=null)};this.createLosePanel=function(a,b){C=new CLosePanel(s_oSpriteLibrary.getSprite("msg_box"));C.show(a,b)};this.createWinPanel=function(a,b,c,d,e){A=new CWinPanel(s_oSpriteLibrary.getSprite("msg_box"),
e);A.show(a,b,c,d)};this.createHelpPanel=function(){createjs.Ticker.paused=!1;x=new CHelpPanel(0,0,s_oSpriteLibrary.getSprite("msg_box"))};this.createAnimText=function(a,b,c){var d=new createjs.Container,e=new createjs.Text(a,b+"px "+SECONDARY_FONT,"#000000");e.x=0;e.y=0;e.textAlign="center";e.outline=3;d.addChild(e);var f=new createjs.Text(e.text,b+"px "+SECONDARY_FONT,"#ffffff");f.x=0;f.y=0;f.textAlign="center";d.addChild(f);d.x=CANVAS_WIDTH_HALF;d.y=-e.getBounds().height;c&&s_oInterface.strobeText(f);
s_oStage.addChild(d);createjs.Tween.get(d).to({y:CANVAS_HEIGHT_HALF},500,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(d).wait(250).to({y:CANVAS_HEIGHT+e.getBounds().height},500,createjs.Ease.cubicIn).call(function(){c&&createjs.Tween.removeTweens(f);s_oStage.removeChild(d)})})};this.strobeText=function(a){createjs.Tween.get(a).wait(30).call(function(){D<TEXT_EXCELLENT_COLOR.length-1?D++:D=0;a.color=TEXT_EXCELLENT_COLOR[D];s_oInterface.strobeText(a)})};this.createExtendedTimeText=function(){var a=
new createjs.Container,b=new createjs.Text(TEXT_TIE,"50px "+FONT_GAME,"#000000");b.x=0;b.y=0;b.textAlign="center";b.outline=5;a.addChild(b);var c=new createjs.Text(b.text,"50px "+FONT_GAME,"#ffffff");c.x=0;c.y=0;c.textAlign="center";a.addChild(c);a.x=-b.getBounds().width;a.y=.5*CANVAS_HEIGHT;s_oStage.addChild(a);createjs.Tween.get(a).to({x:.5*CANVAS_WIDTH},750,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(a).to({x:CANVAS_WIDTH+b.getBounds().width},750,createjs.Ease.cubicIn).call(function(){s_oGame.extendLaunch();
s_oStage.removeChild(a)})})};this.refreshMatchNum=function(a){t.text=TEXT_MATCH+"\n"+a};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){(new CAreYouSurePanel(s_oStage)).show()};this.unloadPause=function(){B.unload();B=null};this.onButPauseRelease=function(){playSound("click",1,0);B=new CPause};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(a,c,b){var g,f,e,d,h,k,l,n,p=!1,m;this._init=function(a,b,c){h=new createjs.Container;h.x=a;h.y=b;s_oStage.addChild(h);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=.5;h.addChild(d);e=createBitmap(c);e.x=CANVAS_WIDTH_HALF;e.y=CANVAS_HEIGHT_HALF;e.regX=.5*c.width;e.regY=.5*c.height;h.addChild(e);g=new createjs.Text(TEXT_HOW_TO_PLAY,"bold 50px "+FONT_GAME,TEXT_COLOR);g.textAlign="center";g.lineWidth=500;g.x=.5*CANVAS_WIDTH;g.y=
.5*CANVAS_HEIGHT-240;h.addChild(g);n=new createjs.Container;a=s_oSpriteLibrary.getSprite("gloves");l=new CGloves(CANVAS_WIDTH_HALF,306,a,null,n);l.changeState("perfect");s_bMobile?(a=TEXT_HELP1_MOBILE,b="help_touch"):(a=TEXT_HELP1_PC,b="help_mouse");b=s_oSpriteLibrary.getSprite(b);m=createBitmap(b);m.x=CANVAS_WIDTH_HALF+6;m.y=320;m.regX=.5*b.width;m.regY=.5*b.height;n.addChild(m);h.addChild(n);this.animGloves();f=new createjs.Text(a,"32px "+FONT_GAME,TEXT_COLOR);f.textAlign="center";f.lineWidth=700;
f.x=.5*CANVAS_WIDTH;f.y=.5*CANVAS_HEIGHT+34;h.addChild(f);a=s_oSpriteLibrary.getSprite("but_continue");k=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT_HALF+180,a,h);k.addEventListener(ON_MOUSE_UP,this._onExitHelp,this);k.pulseAnimation();var q=this;h.on("pressup",function(){q._onExitHelp()})};this.animGloves=function(){var a=this;createjs.Tween.get(n).to({x:100},1E3,createjs.Ease.cubicInOut).call(function(){createjs.Tween.get(n).to({x:-100},1E3,createjs.Ease.cubicInOut).call(function(){a.animGloves()})})};
this.unload=function(){createjs.Tween.get(h).to({alpha:0},500,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(h)});var a=this;createjs.Tween.removeTweens(n);h.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){p||(p=!0,this.unload(),s_oGame.onExitHelp())};this._init(a,c,b)}
function CGoal(a,c,b,g,f){var e,d,h;this._init=function(a,b,c){e=createBitmap(c);this.setPosition(a,b);h.addChild(e)};this.unload=function(){h.removeChild(e)};this.setPosition=function(a,b){e.x=a;e.y=b};this.getObject=function(){return e};this.getDepthPos=function(){return d.position.y};this.getPhysics=function(){return d};this.getX=function(){return e.x};this.getY=function(){return e.y};d=g;h=f;this._init(a,c,b);return this}
function CGloves(a,c,b,g,f){var e,d,h;this._init=function(a,b,c){var f=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{normal:[0],perfect:[1]}});e=createSprite(f,"normal",c.width/2/2,c.height/2,c.width/2,c.height);this.setPosition(a,b);d.addChild(e)};this.unload=function(){d.removeChild(e)};this.setPosition=function(a,b){e.x=a;e.y=b};this.getObject=function(){return e};this.getDepthPos=function(){return h.position.y};this.getX=
function(){return e.x};this.getY=function(){return e.y};this.changeState=function(a){e.gotoAndStop(a)};this.getPhysics=function(){return h};this.setRotation=function(a){e.rotation=a};h=g;d=f;this._init(a,c,b);return this}
function CGfxButton(a,c,b,g){var f,e,d,h,k,l,n,p=!1,m;this._init=function(a,b,c){f=[];e=[];h=[];d=createBitmap(c);d.x=a;d.y=b;l=k=1;d.regX=c.width/2;d.regY=c.height/2;s_bMobile||(d.cursor="pointer");m.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);m.removeChild(d)};this.setVisible=function(a){d.visible=a};this.setCursorType=function(a){d.cursor=a};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",
this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;e[a]=c};this.addEventListenerWithParams=function(a,b,c,d){f[a]=b;e[a]=c;h[a]=d};this.buttonRelease=function(){p||(d.scaleX=0<k?1:-1,d.scaleY=1,playSound("click",1,0),f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(e[ON_MOUSE_UP],h[ON_MOUSE_UP]))};this.buttonDown=function(){p||(d.scaleX=0<k?.9:-.9,d.scaleY=.9,f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],h[ON_MOUSE_DOWN]))};this.rotation=function(a){d.rotation=a};this.getButton=function(){return d};
this.setPosition=function(a,b){d.x=a;d.y=b};this.setX=function(a){d.x=a};this.setY=function(a){d.y=a};this.getButtonImage=function(){return d};this.block=function(a){p=a;d.scaleX=k;d.scaleY=l};this.setScaleX=function(a){k=d.scaleX=a};this.getX=function(){return d.x};this.getY=function(){return d.y};this.pulseAnimation=function(){createjs.Tween.get(d).to({scaleX:.9*k,scaleY:.9*l},850,createjs.Ease.quadOut).to({scaleX:k,scaleY:l},650,createjs.Ease.quadIn).call(function(){n.pulseAnimation()})};this.trebleAnimation=
function(){createjs.Tween.get(d).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){n.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(d)};m=void 0!==g?g:s_oStage;this._init(a,c,b);n=this;return this}
function CGame(a,c){var b,g,f,e,d,h=null,k,l=null,n,p=!1,m=!1,r=!1,u=!1,v=!1,q,x,y,w=0,t=0,A=0,C=0,B=0,D,z,F=STATE_INIT,E=null;this._init=function(){this.pause(!0);y=x=0;z=[];q=c;for(var a=0;a<q;a++)x+=s_aScores[a];n=new createjs.Container;s_oStage.addChild(n);s_bMobile&&this.velocityBall();g=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));n.addChild(g);f=new CScenario(q);E=SHOW_3D_RENDER?camera:createOrthoGraphicCamera();a=s_oSpriteLibrary.getSprite("opponent");h=new COpponent(600,480,a,n);a=
s_oSpriteLibrary.getSprite("ball");d=new CBall(0,0,a,f.ballBody(),n);z.push(d);this.ballPosition();resizeCanvas3D();setVolume(s_oSoundTrack,.35);b=new CInterface;a=s_oSpriteLibrary.getSprite("gloves");e=new CGloves(CANVAS_WIDTH_HALF,CANVAS_HEIGHT_HALF,a,f.getHandKeeperBody(),n);z.push(e);a=s_oSpriteLibrary.getSprite("goal");k=new CGoal(0,0,a,f.getGoalBody(),n);z.push(k);b.refreshBallSaved(w,BALL_TO_SAVED[q]);b.refreshMatchNum(q+1);b.refreshLaunch(A,MATCH_LAUNCH[q]);if(SHOW_3D_RENDER)this.onExitHelp();
else b.createHelpPanel()};this.velocityBall=function(){for(var a=0;a<BALL_FORCE_Y.length;a++)BALL_FORCE_Y[a]*=BALL_VELOCITY_MULTIPLIER,BALL_FORCE_Z[a].min/=BALL_VELOCITY_MULTIPLIER+.1,BALL_FORCE_Z[a].max*=BALL_VELOCITY_MULTIPLIER+.1,BALL_FORCE_X[a]*=BALL_VELOCITY_MULTIPLIER};this.sortDepth=function(a,b){null!==a&&null!==b&&(a.getDepthPos()>b.getDepthPos()?n.getChildIndex(a.getObject())>n.getChildIndex(b.getObject())&&n.swapChildren(a.getObject(),b.getObject()):a.getDepthPos()<b.getDepthPos()&&n.getChildIndex(b.getObject())>
n.getChildIndex(a.getObject())&&n.swapChildren(b.getObject(),a.getObject()))};this.onExitHelp=function(){this.activeEventListeners();this.pause(!1);this.startOpponentShot();b.onExitFromHelp()};this.activeEventListeners=function(){SHOW_3D_RENDER?(window.addEventListener("mousedown",this.addImpulseToBall),window.addEventListener("mousemove",this.onHandKeeper)):null===l&&(l=s_oStage.on("stagemousemove",this.onHandKeeper))};this.deactiveEventListeners=function(){SHOW_3D_RENDER?(window.removeEventListener("mousedown",
this.addImpulseToBall),window.removeEventListener("mousemove",this.onHandKeeper)):(s_oStage.off("stagemousemove",l),l=null)};this.ballPosition=function(){var a=f.ballBody(),b=this.convert3dPosTo2dScreen(a.position,E),c=d.getStartScale()-b.z;this.shadowBall(a,c);d.scale(c);d.setPosition(b.x,b.y)};this.getLevel=function(){return q};this.shadowBall=function(a,b){var c=f.getFieldBody(),e=this.convert3dPosTo2dScreen({x:a.position.x,y:a.position.y,z:c.position.z},E);d.scaleShadow(b/(a.position.z-c.position.z));
d.setAlphaByHeight(.1*(-a.position.z-.1*c.position.z));d.setPositionShadow(e.x,e.y)};this.unload=function(){s_oStage.removeAllChildren();b.unload();f.destroyWorld();f=null;this.deactiveEventListeners()};this.onContinue=function(){this.nextLevel();F=STATE_PLAY;this.resetValues();this.activeEventListeners()};this.resetValues=function(){A=y=C=w=t=0;b.refreshBallSaved(w,BALL_TO_SAVED[q]);b.refreshLaunch(A,MATCH_LAUNCH[q])};this.nextLevel=function(){q++;b.refreshMatchNum(q+1);this.resetScene();$(s_oMain).trigger("start_level",
q);this.startOpponentShot()};this.wallSoundCollision=function(){playSound("ball_collision",1,0)};this.goal=function(){p||(p=!0,D=TIME_RESET_AFTER_GOAL,b.createAnimText(TEXT_GOAL,80),playSound("goal",1,0),B=0)};this.keeperSave=function(a){p||m||(a.x>-BALL_SAVED_POINT.x&&a.x<BALL_SAVED_POINT.x&&a.z>-BALL_SAVED_POINT.z&&a.z<BALL_SAVED_POINT.z?(r=!0,d.getPhysics().mass=0,D=TIME_RESET_AFTER_PERFECT_KEEPER_SAVED,C++,e.changeState("perfect"),createjs.Tween.get(n).wait(TIME_BALL_IN_HAND).call(function(){r=
!1;d.getPhysics().mass=BALL_MASS;e.changeState("normal")})):(r=!1,D=TIME_RESET_AFTER_KEEPER_SAVED),createjs.Tween.get(n).wait(300).call(function(){p||s_oGame.textSave()}),m=!0,playSound("kick",.65,0),playSound("keep_ball",1,0))};this.addImpulseToBall=function(){if(!u&&F===STATE_PLAY){var a={x:Math.random()*(BALL_FORCE_X[q]+BALL_FORCE_X[q])-BALL_FORCE_X[q],y:-BALL_FORCE_Y[q],z:Math.random()*(BALL_FORCE_Z[q].max-BALL_FORCE_Z[q].min)+BALL_FORCE_Z[q].min},b=f.ballBody();f.addImpulse(b,a);f.setElementAngularVelocity(b,
{x:0,y:0,z:0});u=!0}};this.pause=function(a){a?(F=STATE_PAUSE,null!==h&&h.stopAnimation(),this.deactiveEventListeners()):(F=STATE_PLAY,null!==h&&h.playAnimation(),this.activeEventListeners());createjs.Ticker.paused=a};this.startOpponentShot=function(){h.changeState("shot");h.fadeAnimation(1);h.onFinishAnimation()};this.onExit=function(){this.unload();$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session");setVolume(s_oSoundTrack,1);s_oMain.gotoMenu()};this.restartLevel=function(){this.resetValues();
this.resetScene();this.activeEventListeners();F=STATE_PLAY;this.startOpponentShot();$(s_oMain).trigger("restart_level",q)};this.resetBallPosition=function(){var a=f.ballBody();a.position.set(POSITION_BALL.x,POSITION_BALL.y,POSITION_BALL.z);f.setElementVelocity(a,{x:0,y:0,z:0});f.setElementAngularVelocity(a,{x:0,y:0,z:0});d.fadeAnimation(1,500,0)};this.ballFadeForReset=function(){if(p||m){var a=1E3;p&&(a=100);v||(d.fadeAnimation(0,300,a),v=!0)}};this._updateInit=function(){f.update();this._updateBall2DPosition();
F=STATE_PLAY};this.onHandKeeper=function(a){var b=f.getHandKeeperBody();a=SHOW_3D_RENDER?{x:a.clientX-s_iCanvasOffsetWidth,y:a.clientY-s_iCanvasOffsetHeight}:{x:a.stageX/s_fInverseScaling,y:a.stageY/s_fInverseScaling};s_bMobile&&(a.x+=MOBILE_OFFSET_GLOVES_X);a=s_oGame.convert2dScreenPosTo3d(a,b);b.position.x=a.x<LIMIT_HAND_RANGE_POS.x&&a.x>-LIMIT_HAND_RANGE_POS.x?a.x:a.x<LIMIT_HAND_RANGE_POS.x?-LIMIT_HAND_RANGE_POS.x:LIMIT_HAND_RANGE_POS.x;b.position.z=a.z>LIMIT_HAND_RANGE_POS.zMin&&a.z<LIMIT_HAND_RANGE_POS.zMax?
a.z:a.z>LIMIT_HAND_RANGE_POS.zMin?LIMIT_HAND_RANGE_POS.zMax:LIMIT_HAND_RANGE_POS.zMin;a=s_oGame.convert3dPosTo2dScreen(b.position,E);e.setPosition(a.x,a.y);r&&s_oGame.ballInHand(b.position)};this.ballInHand=function(a){var b=f.ballBody();b.position.x=a.x;b.position.y=a.y+.7*BALL_RADIUS;b.position.z=a.z;a=this.convert3dPosTo2dScreen(b.position,E);var c=d.getStartScale()-a.z;this.shadowBall(b,c);d.scale(d.getStartScale()-a.z);d.setPosition(a.x,a.y)};this.convert2dScreenPosTo3d=function(a){a=new THREE.Vector3(a.x/
s_iCanvasResizeWidth*2-1,2*-(a.y/s_iCanvasResizeHeight)+1,-1);a.unproject(E);a.sub(E.position);a.normalize();a.multiply(new THREE.Vector3(34,1,34));return a};this.convert3dPosTo2dScreen=function(a,b){var c=(new THREE.Vector3(a.x,a.y,a.z)).project(b),d=.5*Math.floor(s_iCanvasResizeWidth),e=.5*Math.floor(s_iCanvasResizeHeight);c.x=(c.x*d+d)*s_fInverseScaling;c.y=(-(c.y*e)+e)*s_fInverseScaling;return c};this.timeReset=function(){0<D?D-=FPS_TIME:(p?t++:(w++,b.refreshBallSaved(w,BALL_TO_SAVED[q])),A++,
b.refreshLaunch(A,MATCH_LAUNCH[q]),A<MATCH_LAUNCH[q]?(this.resetScene(),v=!1,this.startOpponentShot()):(this.matchResult(),F=STATE_FINISH,$(s_oMain).trigger("end_level",q),this.deactiveEventListeners()),u=!1)};this.textSave=function(){if(B<TEXT_CONGRATULATION.length){var a=!1;B>=TEXT_CONGRATULATION.length-1&&(a=!0);b.createAnimText(TEXT_CONGRATULATION[B],TEXT_SIZE[B],a);B++}else{var a=!1,c=Math.floor(Math.random()*(TEXT_CONGRATULATION.length-1))+1;c>=TEXT_CONGRATULATION.length-1&&(a=!0);b.createAnimText(TEXT_CONGRATULATION[c],
TEXT_SIZE[c],a)}};this.matchResult=function(){w>=BALL_TO_SAVED[q]?this.wonMatch():this.lostMatch()};this.goalAnimation=function(a){500<a&&1E3>a?this.displayShock(INTENSITY_DISPLAY_SHOCK[0].time,INTENSITY_DISPLAY_SHOCK[0].x,INTENSITY_DISPLAY_SHOCK[0].y):999<a&&2E3>a?this.displayShock(INTENSITY_DISPLAY_SHOCK[1].time,INTENSITY_DISPLAY_SHOCK[1].x,INTENSITY_DISPLAY_SHOCK[1].y):1999<a&&3E3>a?this.displayShock(INTENSITY_DISPLAY_SHOCK[2].time,INTENSITY_DISPLAY_SHOCK[2].x,INTENSITY_DISPLAY_SHOCK[2].y):2999<
a&&this.displayShock(INTENSITY_DISPLAY_SHOCK[3].time,INTENSITY_DISPLAY_SHOCK[3].x,INTENSITY_DISPLAY_SHOCK[3].y)};this.displayShock=function(a,b,c){createjs.Tween.get(n).to({x:Math.round(Math.random()*b),y:Math.round(Math.random()*c)},a).call(function(){createjs.Tween.get(n).to({x:Math.round(Math.random()*b*.8),y:-Math.round(Math.random()*c*.8)},a).call(function(){createjs.Tween.get(n).to({x:Math.round(Math.random()*b*.6),y:Math.round(Math.random()*c*.6)},a).call(function(){createjs.Tween.get(n).to({x:Math.round(Math.random()*
b*.4),y:-Math.round(Math.random()*c*.4)},a).call(function(){createjs.Tween.get(n).to({x:Math.round(Math.random()*b*.2),y:Math.round(Math.random()*c*.2)},a).call(function(){createjs.Tween.get(n).to({y:0,x:0},a).call(function(){})})})})})})};this.wonMatch=function(){var a=!1;q>=MATCH_LAUNCH.length-1&&(a=!0);var c=this.calculateNewScore();x=c.new_score;this.saveProgress();b.createWinPanel(w,C,BALL_TO_SAVED[q],c,a);playSound("win",1,0)};this.lostMatch=function(){b.createLosePanel(w,BALL_TO_SAVED[q]);
playSound("goal",1,0)};this.calculateNewScore=function(){var a={score:x,ball_saved:0,ball_saved_perfect:0,opponent_goal:0,new_score:0};a.ball_saved=w*SCORE_BALL_SAVED;a.ball_saved_perfect=C*SCORE_PERFECT_BALL_SAVED;a.opponent_goal=t*SCORE_GOAL_OPPONENT;y=a.ball_saved+a.opponent_goal+a.ball_saved_perfect;a.new_score=a.score+y;0>a.new_score&&(a.new_score=0);return a};this.saveProgress=function(){s_iLastLevel<q+2&&(s_iLastLevel=q+2);y>s_aScores[q]&&(s_aScores[q]=y);saveItem("LevelReached",s_iLastLevel);
saveItem("Scores",JSON.stringify(s_aScores))};this.resetScene=function(){m=p=!1;this.resetBallPosition()};this._onEnd=function(){this.onExit()};this.swapChildrenIndex=function(){for(var a=0;a<z.length-1;a++)for(var b=a+1;b<z.length;b++)this.sortDepth(z[a],z[b])};this.rotateGuantes=function(){var a=(e.getX()-CANVAS_WIDTH_HALF)*HAND_KEEPER_ANGLE_RATE;e.setRotation(a)};this._updatePlay=function(){for(var a=0;a<PHYSICS_ACCURACY;a++)f.update();this._updateBall2DPosition();(m||p)&&this.timeReset();this.rotateGuantes();
this.swapChildrenIndex()};this.update=function(){switch(F){case STATE_INIT:this._updateInit();break;case STATE_PLAY:this._updatePlay()}};this._updateBall2DPosition=function(){r||(this.ballPosition(),d.rolls());E.updateProjectionMatrix();E.updateMatrixWorld()};s_oGame=this;BALL_TO_SAVED=a.ball_to_saved;BALL_FORCE_X=a.ball_force_left_right;BALL_FORCE_Z=a.ball_force_up;BALL_FORCE_Y=a.ball_force_velocity;MATCH_LAUNCH=a.max_launch;SCORE_PERFECT_BALL_SAVED=a.score_perfect_ball_saved;SCORE_BALL_SAVED=a.score_ball_saved;
SCORE_GOAL_OPPONENT=a.score_goal_opponent;BALL_SAVED_POINT=a.perfect_ball_saved_point;NUM_LEVEL_FOR_ADS=a.num_levels_for_ads;this._init()}var s_oGame;
function CCreditsPanel(){var a,c,b,g,f,e,d,h;this._init=function(){h=new createjs.Container;s_oStage.addChild(h);var k=s_oSpriteLibrary.getSprite("msg_box");e=new createjs.Shape;e.graphics.beginFill("#000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e.alpha=.5;e.on("click",this._onLogoButRelease);e.cursor="pointer";h.addChild(e);c=createBitmap(k);c.x=CANVAS_WIDTH_HALF;c.y=CANVAS_HEIGHT_HALF;c.regX=.5*k.width;c.regY=.5*k.height;h.addChild(c);k=s_oSpriteLibrary.getSprite("but_exit");a=.5*CANVAS_WIDTH+
380;g=new CGfxButton(a,180,k,h);g.addEventListener(ON_MOUSE_UP,this.unload,this);f=new createjs.Text(TEXT_CREDITS_DEVELOPED,"bold 50px "+FONT_GAME,"#ffffff");f.textAlign="center";f.textBaseline="alphabetic";f.x=CANVAS_WIDTH/2;f.y=280;h.addChild(f);k=s_oSpriteLibrary.getSprite("logo_ctl");b=createBitmap(k);b.regX=k.width/2;b.regY=k.height/2;b.x=CANVAS_WIDTH/2;b.y=380;h.addChild(b);d=new createjs.Text(TEXT_LINK1,"bold 50px "+FONT_GAME,"#ffffff");d.textAlign="center";d.textBaseline="alphabetic";d.x=
CANVAS_WIDTH/2;d.y=520;h.addChild(d)};this.unload=function(){e.off("click",this._onLogoButRelease);g.unload();g=null;s_oStage.removeChild(h)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()}
function CConfirmPanel(a){var c=this,b=[],g=[],f=[],e,d,h=CANVAS_WIDTH/2,k=CANVAS_HEIGHT/2+50,l,n,p,m;this._init=function(){var b=s_oSpriteLibrary.getSprite("msg_box_small");d=new createjs.Container;d.x=h;d.y=CANVAS_HEIGHT+.5*b.width;n=new createjs.Shape;n.graphics.beginFill("#000000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);n.alpha=0;n.on("mousedown",this._onClick);s_oStage.addChild(n);e=createBitmap(b);e.regX=b.width/2;e.regY=b.height/2;d.addChild(e);l=new createjs.Text(a,"bold 35px "+FONT_GAME,
TEXT_COLOR);l.x=0;l.y=-95;l.textAlign="center";l.textBaseline="alphabetic";l.lineWidth=520;d.addChild(l);p=new CGfxButton(-180,70,s_oSpriteLibrary.getSprite("but_no"),d);p.pulseAnimation();m=new CGfxButton(180,70,s_oSpriteLibrary.getSprite("but_yes"),d);s_oStage.addChild(d);this.show()};this._initListener=function(){p.addEventListener(ON_MOUSE_DOWN,this.buttonNoDown,this);m.addEventListener(ON_MOUSE_DOWN,this.buttonYesDown,this)};this.addEventListener=function(a,c,d){b[a]=c;g[a]=d};this.buttonNoDown=
function(){playSound("click",1,0);b[ON_BUT_NO_DOWN]&&b[ON_BUT_NO_DOWN].call(g[ON_BUT_NO_DOWN],f)};this.buttonYesDown=function(){playSound("click",1,0);b[ON_BUT_YES_DOWN]&&b[ON_BUT_YES_DOWN].call(g[ON_BUT_YES_DOWN],f)};this._onClick=function(){};this.show=function(){createjs.Tween.get(n).to({alpha:.9},500,createjs.Ease.quadOut);createjs.Tween.get(d).to({y:k},500,createjs.Ease.quadOut).call(function(){c._initListener()})};this.unload=function(){createjs.Tween.get(d).to({y:1.5*CANVAS_HEIGHT},500).call(function(){s_oStage.removeChild(d)});
createjs.Tween.get(n).to({alpha:0},500,createjs.Ease.quadIn).call(function(){s_oStage.removeChild(n)})};this._init();s_oVariousHelp=this;return this}var s_oVariousHelp=null;
function CBall(a,c,b,g,f){var e,d,h,k,l,n=null,p=0,m=0,r=null,u;this._init=function(a,b,c){l=new createjs.Container;d.addChild(l);var f=new createjs.SpriteSheet({images:[c],frames:{width:c.width/7,height:c.height,regX:c.width/2/7,regY:c.height/2}});e=createSprite(f,0,c.width/2/7,c.height/2,c.width/7,c.height/2);e.stop();this.scale(.93);c=s_oSpriteLibrary.getSprite("ball_shadow");k=createBitmap(c);k.x=a;k.y=b;k.regX=.5*c.width;k.regY=.5*c.height;this.scaleShadow(.93);l.addChild(k,e)};this.rolls=function(){e.rotation=
Math.degrees(Math.sin(.15*h.velocity.x));var a=Math.abs(h.angularVelocity.x),b=this._goToPrevFrame;0>h.angularVelocity.x&&(b=this._goToNextFrame);7<a?b():3<a?(p++,p>2/ROLL_BALL_RATE&&(b(),p=0)):1<a?(p++,p>3/ROLL_BALL_RATE&&(b(),p=0)):a>MIN_BALL_VEL_ROTATION&&(p++,p>4/ROLL_BALL_RATE&&(b(),p=0))};this._goToPrevFrame=function(){0===m?m=6:m--;e.gotoAndStop(m)};this._goToNextFrame=function(){7===m?m=1:m++;e.gotoAndStop(m)};this.unload=function(){e.removeAllEventListeners();d.removeChild(e)};this.setVisible=
function(a){e.visible=a};this.getStartScale=function(){return.93};this.startPosShadowY=function(a){n=a};this.getStartShadowYPos=function(){return n};this.fadeAnimation=function(a,b,c){a!==u&&(null!==r&&createjs.Tween.removeTweens(l),this.tweenFade(a,b,c),u=a)};this.tweenFade=function(a,b,c){r=createjs.Tween.get(l).wait(c).to({alpha:a},b).call(function(){r=null})};this.setPositionShadow=function(a,b){k.x=a;k.y=b};this.setPosition=function(a,b){e.x=a;e.y=b};this.getPhysics=function(){return h};this.setAngle=
function(a){e.rotation=a};this.getX=function(){return e.x};this.getY=function(){return e.y};this.getStartScale=function(){return.93};this.scale=function(a){e.scaleX=a;e.scaleY=a};this.scaleShadow=function(a){.08<a?(k.scaleX=a,k.scaleY=a):(k.scaleX=.08,k.scaleY=.08)};this.setAlphaByHeight=function(a){k.alpha=a};this.getScale=function(){return e.scaleX};this.getObject=function(){return e};this.getDepthPos=function(){return h.position.y};h=g;d=f;this._init(a,c,b);return this}
function CAreYouSurePanel(a){var c,b,g,f,e,d,h;this._init=function(){e=new createjs.Container;e.alpha=0;d.addChild(e);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=.5;h.on("click",function(){});e.addChild(h);var a=s_oSpriteLibrary.getSprite("msg_box_small");c=createBitmap(a);c.x=CANVAS_WIDTH_HALF;c.y=CANVAS_HEIGHT_HALF+50;c.regX=.5*a.width;c.regY=.5*a.height;e.addChild(c);b=new createjs.Text(TEXT_ARE_SURE,"bold 60px "+FONT_GAME,"#ffffff");b.x=
CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT_HALF-50;b.textAlign="center";b.textBaseline="middle";e.addChild(b);g=new CGfxButton(CANVAS_WIDTH/2+180,.5*CANVAS_HEIGHT+120,s_oSpriteLibrary.getSprite("but_yes"),e);g.addEventListener(ON_MOUSE_UP,this._onButYes,this);f=new CGfxButton(CANVAS_WIDTH/2-180,.5*CANVAS_HEIGHT+120,s_oSpriteLibrary.getSprite("but_no"),e);f.addEventListener(ON_MOUSE_UP,this._onButNo,this)};this.show=function(){createjs.Tween.get(e).to({alpha:1},150,createjs.quartOut).call(function(){s_oGame.pause(!0)})};
this.unload=function(){createjs.Tween.get(e).to({alpha:0},150,createjs.quartOut).call(function(){d.removeChild(e,h)})};this._onButYes=function(){createjs.Ticker.paused=!1;this.unload();s_oGame.onExit();h.removeAllEventListeners()};this._onButNo=function(){s_oGame.pause(!1);this.unload();e.visible=!1;h.removeAllEventListeners()};d=a;this._init()};