var s_iScaleFactor=1,s_iOffsetX,s_iOffsetY,s_bIsIphone=!1;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var d=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var k=b.createElement("body");k.id="vpw-test-b";k.style.cssText="overflow:scroll";var f=b.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+d+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";k.appendChild(f);c.insertBefore(k,b.head);
a=7==f["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(k)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function inIframe(){try{return window.self!==window.top}catch(a){return!0}}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH),c=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b;s_bMobile&&!s_bIsIphone?($("#canvas").css("width",c+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=c,s_oStage.canvas.height=b,s_oStage.scaleX=s_oStage.scaleY=Math.min(c/CANVAS_WIDTH,b/CANVAS_HEIGHT));var k;b<a?(k=a-b,b+=k,c+=CANVAS_WIDTH/
CANVAS_HEIGHT*k):c<d&&(k=d-c,c+=k,b+=CANVAS_HEIGHT/CANVAS_WIDTH*k);k=a/2-b/2;var f=d/2-c/2,g=CANVAS_WIDTH/c;if(f*g<-EDGEBOARD_X||k*g<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),d/(CANVAS_WIDTH-2*EDGEBOARD_X)),c=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,k=(a-b)/2,f=(d-c)/2,g=CANVAS_WIDTH/c;s_iOffsetX=-1*f*g;s_iOffsetY=-1*k*g;0<=k&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);
$("#canvas").css("width",c+"px");$("#canvas").css("height",b+"px");0>k?$("#canvas").css("top",k+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",f+"px")}}function playSound(a,d,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(d),0>b?s_aSounds[a].loop(!0):s_aSounds[a].loop(!1),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}
function setVolume(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.volume(d)}function setMute(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.mute(d)}function fadeSound(a,d,b,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.fade(d,b,c)}function createBitmap(a,d,b){var c=new createjs.Bitmap(a),k=new createjs.Shape;d&&b?k.graphics.beginFill("#fff").drawRect(0,0,d,b):k.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=k;return c}
function createSprite(a,d,b,c,k,f){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-b,-c,k,f);a.hitArea=d;return a}function pad(a,d,b){a+="";return a.length>=d?a:Array(d-a.length+1).join(b||"0")+a}function randomFloatBetween(a,d,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(b))}
function rotateVector2D(a,d){var b=d.getX()*Math.cos(a)+d.getY()*Math.sin(a),c=d.getX()*-Math.sin(a)+d.getY()*Math.cos(a);d.set(b,c)}function tweenVectorsOnX(a,d,b){return a+b*(d-a)}function shuffle(a){for(var d=a.length,b,c;0!==d;)c=Math.floor(Math.random()*d),--d,b=a[d],a[d]=a[c],a[c]=b;return a}function bubbleSort(a){var d;do{d=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(d=a[b],a[b]=a[b+1],a[b+1]=d,d=!0)}while(d)}function compare(a,d){return a.index>d.index?-1:a.index<d.index?1:0}
function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var b="",b=10>d?b+("0"+d+":"):b+(d+":");return 10>a?b+("0"+a):b+a}function pixelsToMeters(a){return a*PIXEL_TO_METER_RATIO}function kMetersHToPixelsF(a){return 1E3*a*METER_TO_PIXEL_RATIO/3600/FPS}function framesToMilliSeconds(a){return(a*FPS_TIME).toFixed(0)}function milliSecondsToFrames(a){return(.001*a*FPS).toFixed(0)}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,d){var b,c;b=getBounds(a,.9);c=getBounds(d,.98);return calculateIntersection(b,c)}function calculateIntersection(a,d){var b,c,k,f,g,e,h,n;b=a.x+(k=a.width/2);c=a.y+(f=a.height/2);g=d.x+(e=d.width/2);h=d.y+(n=d.height/2);b=Math.abs(b-g)-(k+e);c=Math.abs(c-h)-(f+n);return 0>b&&0>c?(b=Math.min(Math.min(a.width,d.width),-b),c=Math.min(Math.min(a.height,d.height),-c),{x:Math.max(a.x,d.x),y:Math.max(a.y,d.y),width:b,height:c,rect1:a,rect2:d}):null}
function getBounds(a,d){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,k=c.length,f,g;for(g=0;g<k;g++)f=getBounds(c[g],1),f.x<b.x&&(b.x=f.x),f.y<b.y&&(b.y=f.y),f.x+f.width>b.x2&&(b.x2=f.x+f.width),f.y+f.height>b.y2&&(b.y2=f.y+f.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var e,h;a instanceof createjs.Bitmap?
(k=a.sourceRect||a.image,g=k.width*d,e=k.height*d):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(k=a.spriteSheet.getFrame(a.currentFrame),g=k.rect.width,e=k.rect.height,c=k.regX,h=k.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);c=c||0;g=g||0;h=h||0;e=e||0;b.regX=c;b.regY=h;k=a.localToGlobal(0-c,0-h);f=a.localToGlobal(g-c,e-h);g=a.localToGlobal(g-c,0-h);c=a.localToGlobal(0-c,e-h);b.x=Math.min(Math.min(Math.min(k.x,
f.x),g.x),c.x);b.y=Math.min(Math.min(Math.min(k.y,f.y),g.y),c.y);b.width=Math.max(Math.max(Math.max(k.x,f.x),g.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(k.y,f.y),g.y),c.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,b,c;0<d;)c=Math.floor(Math.random()*d),d--,b=a[d],a[d]=a[c],a[c]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),b=0;b<d.length;b++){var c=d[b].split("=");if(c[0]==a)return c[1]}}
function CSpriteLibrary(){var a,d,b,c,k,f;this.init=function(g,e,h){b=d=0;c=g;k=e;f=h;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){k.call(f)};this._onSpriteLoaded=function(){c.call(f);++b==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=1280,CANVAS_HEIGHT=768,EDGEBOARD_X=90,EDGEBOARD_Y=105,PRIMARY_FONT="ArialBold",FPS=60,FPH=3600*FPS,FPS_TIME=1E3/FPS,CAR_REAL_LENGTH=4.5,CAR_PIXEL_LENGTH=370,PIXEL_TO_METER_RATIO=CAR_REAL_LENGTH/CAR_PIXEL_LENGTH,METER_TO_PIXEL_RATIO=CAR_PIXEL_LENGTH/CAR_REAL_LENGTH,PARALLAX_BG_RATIO=.05,PARALLAX_1_RATIO=.2,PARALLAX_2_RATIO=1.2,LAMP_WIDTH,LAMP_OFFSET=570,DISABLE_SOUND_MOBILE=!1,ENABLE_FULLSCREEN=!0,STATE_LOADING=0,STATE_MENU=1,STATE_MODEMENU=2,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=
0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,STATE_HELP_PANEL=-1,STATE_START_BATTLE=0,STATE_RACE_RUN=1,STATE_RACE_FINISH=2,GEAR_N=0,NULL_AREA=-1,GREEN_AREA=0,EARLY_AREA=1,LATE_AREA=2,STATE_HUD_NULL=-1,STATE_HUD_STALL=0,STATE_HUD_UPDATE=1,STATE_HUD_REPOSITIONING=2,STATE_ENGINE_STALL=0,STATE_ENGINE_UPDATE=1,STATE_ENGINE_BREAK=2,ENGINE_NORMAL_RPM_ACCELERATION=1,ENGINE_NITRO_RPM_ACCELERATION=3,NITRO_INFO,NITRO_DURATION=0,BREAK_DURATION=4E3,START_COUNTDOWN=3E3,HUD_DOWNSHIFT_GEAR_DURATION=
500,HUD_RPM_INTERVAL=[{min:-90,max:80},{min:-90,max:70},{min:-50,max:65},{min:-40,max:60},{min:-40,max:65},{min:-30,max:75},{min:-10,max:85}],WRONG_GEAR_DURATION_INFO,WRONG_GEAR_CHANGE_STALL_DURATION=0,GEAR_START_GREEN_WIDTH,GEAR_INRACE_GREEN_WIDTH,START_ACCELERATION_INDICATOR_SPEED=2,GEAR_START_AREA={center:45,greenangle:0,earlyangle:0,lateangle:0},GEAR_IN_RACE_AREA={greenangle:0,earlyangle:20,lateangle:20},GEAR_NULL_AREA={greenangle:0,earlyangle:0,lateangle:0},NUM_TRACK=10,START_LINE_X=600,STAGE_METER_LENGTH=
[],STAGE_WIN_REWARDS,BONUS_REWARD_TRACKLENGTH_MULTIPLIER,BONUS_REWARD_OVERTAKING_MULTIPLIER,BONUS_REWARD_DIFFICULTY_MULTIPLIER;TEXT_GAMEOVER="CONGRATULATIONS, YOU WON ALL THE RACES!";TEXT_LOSE="RACE LOST";TEXT_WIN="RACE WIN";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_KMH="mph";TEXT_M="m";TEXT_GEAR_N="N";TEXT_CURRENCY="$";TEXT_VS="Vs";TEXT_PERFECT="PERFECT";TEXT_SHOP="SHOP";TEXT_SELECT_STAGE="SELECT STAGE";TEXT_TOTAL_SCORE="TOTAL SCORE";TEXT_FIRST_WIN="FIRST WIN";TEXT_PRIZE="PRIZE";TEXT_BONUS="BONUS";
TEXT_BONUS_TRACK_LENGTH="TRACK LENGTH";TEXT_BONUS_OVERTAKING="OVERTAKING DISTANCE";TEXT_BONUS_DIFFICULTY="LEVEL DIFFICULTY";TEXT_HELP1="PRESS AND HOLD ACCELERATOR TO KEEP THE REV NEEDLE IN THE GREEN AREA AND MAKE A PERFECT START";TEXT_HELP2="PRESS THE GEAR AT THE RIGHT TIME FOR AN EXCELLENT GEAR SHIFT";TEXT_SAVE_REMOVE="THIS WILL REMOVE ALL YOUR ACHIEVEMENTS! DO YOU WANT TO PROCEED?";TEXT_IOS_PRIVATE='Your web browser does not support storing settings locally. In Safari, the most common cause of this is using "Private Browsing Mode". Some info may not save or some features may not work properly';
TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You completed the race in <strong>";TEXT_SHARE_MSG2=" seconds</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My time is ";TEXT_SHARE_SHARE2=" seconds! Can you do better";
function CCurtain(a){var d,b,c;this._init=function(a){c=new createjs.Container;a.addChild(c);d=new createjs.Container;d.y=0;d.on("mousedown",function(){});c.addChild(d);a=s_oSpriteLibrary.getSprite("curtain_top");a=createBitmap(a);d.addChild(a);b=new createjs.Container;b.y=CANVAS_HEIGHT/2;b.on("mousedown",function(){});c.addChild(b);a=s_oSpriteLibrary.getSprite("curtain_bot");a=createBitmap(a);b.addChild(a)};this.unload=function(){a.removeChild(c)};this.openAnim=function(){d.y=0;b.y=CANVAS_HEIGHT/
2;(new createjs.Tween.get(d,{override:!0})).to({y:-CANVAS_HEIGHT/2},1E3,createjs.Ease.cubicOut);(new createjs.Tween.get(b,{override:!0})).to({y:CANVAS_HEIGHT},1E3,createjs.Ease.cubicOut)};this.closeAnim=function(a){d.y=-CANVAS_HEIGHT/2;b.y=CANVAS_HEIGHT;(new createjs.Tween.get(d,{override:!0})).to({y:0},1E3,createjs.Ease.cubicOut);(new createjs.Tween.get(b,{override:!0})).to({y:CANVAS_HEIGHT/2},1E3,createjs.Ease.cubicOut).call(function(){a&&a()})};this._init(a)}
function CPreloader(){var a,d,b,c,k,f,g;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("curtain_bot","./sprites/preloader_bottom.jpg");s_oSpriteLibrary.addSprite("curtain_top","./sprites/preloader_top.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();g=new createjs.Container;s_oStage.addChild(g)};this.unload=function(){g.removeAllChildren()};this.hide=function(){var a=
this;setTimeout(function(){createjs.Tween.get(f).to({alpha:1},500).call(function(){a.unload();s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){new CCurtain(g);var e=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(e);c.x=CANVAS_WIDTH/2-e.width/2;c.y=CANVAS_HEIGHT-170;g.addChild(c);a=e.width;d=e.height;k=new createjs.Shape;k.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,
c.y,1,d);g.addChild(k);c.mask=k;b=new createjs.Text("","30px"+PRIMARY_FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";g.addChild(b);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;g.addChild(f)};this.refreshLoader=function(e){b.text=e+"%";k.graphics.clear();e=Math.floor(e*a/100);k.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,e,d)};
this._init()}var LOCALSTORAGE_TIMES="times",LOCALSTORAGE_COINS="coins",LOCALSTORAGE_GEARPOWER_LEVEL="startpower",LOCALSTORAGE_SPEEDPOWER_LEVEL="speedpower",LOCALSTORAGE_NITROPOWER_LEVEL="nitropower";
function CLocalStorage(a){var d=!0,b=[];this._init=function(a){a=window.localStorage.getItem(a);null!==a&&void 0!==a||this.resetAllData();this.loadData()};this.setItem=function(c,k){d?window.localStorage.setItem(a+"_"+c,k):b[c]=k};this.getItem=function(c){return d?window.localStorage.getItem(a+"_"+c):b[c]};this.setItemJson=function(c,k){d?localStorage.setItem(a+"_"+c,JSON.stringify(k)):b[c]=JSON.stringify(k)};this.getItemJson=function(c){return d?JSON.parse(localStorage.getItem(a+"_"+c)):JSON.parse(b[c])};
this.isDirty=function(){for(var a=s_oLocalStorage.getItemJson(LOCALSTORAGE_TIMES),b=0;b<a.length;b++)if(0<a[b])return!0;return!1};this.isUsed=function(){return d};this.resetAllData=function(){try{window.localStorage.setItem(a,!0)}catch(f){d=!1}for(var b=[],k=0;k<NUM_TRACK;k++)b[k]=0;this.setItemJson(LOCALSTORAGE_TIMES,b);this.setItem(LOCALSTORAGE_COINS,0);this.setItem(LOCALSTORAGE_GEARPOWER_LEVEL,0);this.setItem(LOCALSTORAGE_SPEEDPOWER_LEVEL,0);this.setItem(LOCALSTORAGE_NITROPOWER_LEVEL,0)};this.loadData=
function(){var a=parseInt(this.getItem(LOCALSTORAGE_GEARPOWER_LEVEL));GEAR_START_AREA.greenangle=GEAR_START_GREEN_WIDTH[a];GEAR_IN_RACE_AREA.greenangle=GEAR_INRACE_GREEN_WIDTH[a];WRONG_GEAR_CHANGE_STALL_DURATION=WRONG_GEAR_DURATION_INFO[a];a=parseInt(this.getItem(LOCALSTORAGE_NITROPOWER_LEVEL));NITRO_DURATION=NITRO_INFO[a];a=parseInt(this.getItem(LOCALSTORAGE_SPEEDPOWER_LEVEL));PLAYER_ENGINE_GEAR=PLAYER_ENGINE_INFO[a]};this._init(a)}
function CMain(a){var d,b=!1,c=!1,k=0,f=0,g=STATE_LOADING,e,h,n;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!0;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(FPS),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&
(c=DISABLE_SOUND_MOBILE=!0);this._initData();s_oSpriteLibrary=new CSpriteLibrary;s_oTweenController=new CTweenController;s_oLocalStorage=new CLocalStorage("car");h=new CPreloader};this._initData=function(){GEAR_START_GREEN_WIDTH=a.start_green_width;GEAR_INRACE_GREEN_WIDTH=a.in_race_green_width;WRONG_GEAR_DURATION_INFO=a.wrong_change_gear_duration;PLAYER_ENGINE_INFO=a.player_engine;NITRO_INFO=a.nitro_duration;OPPONENT_ENGINE_GEAR=a.opponent_engine;SKILL=a.opponent_skills;STAGE_METER_LENGTH=a.track_meter_length;
STAGE_WIN_REWARDS=a.track_rewards;BONUS_REWARD_TRACKLENGTH_MULTIPLIER=a.bonus_multiplier_length_reward;BONUS_REWARD_OVERTAKING_MULTIPLIER=a.bonus_multiplier_overtaking_reward;BONUS_REWARD_DIFFICULTY_MULTIPLIER=a.bonus_multiplier_difficulty};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();d=!0};this.soundLoaded=function(){k++;h.refreshLoader(Math.floor(k/f*100));k===f&&(c=!0,this.allResourcesLoaded())};this._initSounds=function(){var a=
[];a.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});a.push({path:"./sounds/",filename:"upgrade_car",loop:!1,volume:1,ingamename:"upgrade_car"});a.push({path:"./sounds/",filename:"press_button",loop:!1,volume:1,ingamename:"click"});a.push({path:"./sounds/",filename:"1",loop:!1,volume:1,ingamename:"1"});a.push({path:"./sounds/",filename:"2",loop:!1,volume:1,ingamename:"2"});a.push({path:"./sounds/",filename:"3",loop:!1,volume:1,ingamename:"3"});a.push({path:"./sounds/",
filename:"go",loop:!1,volume:1,ingamename:"go"});a.push({path:"./sounds/",filename:"arrive_lose",loop:!1,volume:1,ingamename:"arrive_lose"});a.push({path:"./sounds/",filename:"arrive_win",loop:!1,volume:1,ingamename:"arrive_win"});a.push({path:"./sounds/",filename:"ignition",loop:!1,volume:1,ingamename:"ignition"});a.push({path:"./sounds/",filename:"sprint_start",loop:!1,volume:1,ingamename:"sprint_start"});a.push({path:"./sounds/",filename:"fire_wheel",loop:!0,volume:1,ingamename:"fire_wheel"});
a.push({path:"./sounds/",filename:"nitro",loop:!1,volume:1,ingamename:"nitro"});a.push({path:"./sounds/",filename:"change_gear",loop:!1,volume:1,ingamename:"change_gear"});a.push({path:"./sounds/",filename:"wrong_gear",loop:!1,volume:1,ingamename:"wrong_gear"});a.push({path:"./sounds/",filename:"stall",loop:!0,volume:1,ingamename:"stall"});a.push({path:"./sounds/",filename:"acceleration",loop:!1,volume:1,ingamename:"acceleration"});a.push({path:"./sounds/",filename:"engine",loop:!1,volume:1,ingamename:"engine"});
a.push({path:"./sounds/",filename:"gear_player",loop:!1,volume:1,ingamename:"gear_player"});f+=a.length;s_aSounds=[];for(var b=0;b<a.length;b++)s_aSounds[a[b].ingamename]=new Howl({src:[a[b].path+a[b].filename+".mp3",a[b].path+a[b].filename+".ogg"],autoplay:!1,preload:!0,loop:a[b].loop,volume:a[b].volume,onload:s_oMain.soundLoaded()})};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("curtain_bot","./sprites/preloader_bottom.jpg");
s_oSpriteLibrary.addSprite("curtain_top","./sprites/preloader_top.jpg");s_oSpriteLibrary.addSprite("logo","./sprites/logo.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_continue_menu","./sprites/but_continue_menu.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("but_yes_big",
"./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_exit_big","./sprites/but_not.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_continue_small","./sprites/but_continue_small.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("but_level","./sprites/but_level.png");
s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_shop","./sprites/but_shop.png");s_oSpriteLibrary.addSprite("upgrade_gear","./sprites/upgrade_gear.png");s_oSpriteLibrary.addSprite("upgrade_speed","./sprites/upgrade_speed.png");s_oSpriteLibrary.addSprite("upgrade_nitro","./sprites/upgrade_nitro.png");s_oSpriteLibrary.addSprite("but_nitro",
"./sprites/but_nitro.png");s_oSpriteLibrary.addSprite("accelerator","./sprites/accelerator.png");s_oSpriteLibrary.addSprite("but_gear","./sprites/but_gear.png");s_oSpriteLibrary.addSprite("gear_handle","./sprites/gear_handle.png");s_oSpriteLibrary.addSprite("map_track","./sprites/map_track.png");s_oSpriteLibrary.addSprite("car_track_0","./sprites/car_track_0.png");s_oSpriteLibrary.addSprite("car_track_1","./sprites/car_track_1.png");s_oSpriteLibrary.addSprite("tachometer","./sprites/tachometer.png");
s_oSpriteLibrary.addSprite("indicator","./sprites/indicator.png");s_oSpriteLibrary.addSprite("smoke","./sprites/smoke.png");s_oSpriteLibrary.addSprite("woman_starting","./sprites/woman_starting.png");s_oSpriteLibrary.addSprite("parallaxe_1","./sprites/parallaxe_1.png");s_oSpriteLibrary.addSprite("street_piece","./sprites/street_piece.png");s_oSpriteLibrary.addSprite("parallaxe_2","./sprites/parallaxe_2.png");s_oSpriteLibrary.addSprite("lamp","./sprites/lamp.png");s_oSpriteLibrary.addSprite("arrive",
"./sprites/arrive.png");s_oSpriteLibrary.addSprite("fireline","./sprites/fireline.png");s_oSpriteLibrary.addSprite("firewheel","./sprites/firewheel.png");for(var a=0;10>=a;a++)s_oSpriteLibrary.addSprite("car_"+a,"./sprites/cars/car_"+a+".png"),s_oSpriteLibrary.addSprite("shadow_"+a,"./sprites/cars/car_"+a+"_shadow.png"),s_oSpriteLibrary.addSprite("wheel_"+a,"./sprites/cars/car_"+a+"_wheel.png");f+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){k++;
h.refreshLoader(Math.floor(k/f*100));k===f&&(b=!0,this.allResourcesLoaded())};this.allResourcesLoaded=function(){b&&c&&(h.unload(),s_oSoundtrack=playSound("soundtrack",1,-1),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;g=STATE_MENU};this.gotoModeMenu=function(){new CModeMenu;g=STATE_MODEMENU};this.gotoGame=function(a){n=new CGame(e,a);g=STATE_GAME};this.gotoHelp=function(){new CHelp;g=STATE_HELP};
this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&Howler.mute(!1)};this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);g===STATE_GAME?
n.update():g===STATE_MENU&&s_oMenu.update();s_oStage.update(a)}};s_oMain=this;e=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_bFullscreen=!1,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack,s_oCanvas,s_oTweenController,s_oLocalStorage,s_aSounds;
function CTextButton(a,d,b,c,k,f,g){var e,h,n,q,p;this._init=function(a,b,c,g,f,d,k){e=[];h=[];var m=createBitmap(c),t=Math.ceil(k/20);p=new createjs.Text(g," "+k+"px "+f,"#000000");p.textAlign="center";p.textBaseline="alphabetic";var l=p.getBounds();p.x=c.width/2+t;p.y=Math.floor(c.height/2)+l.height/3+t;q=new createjs.Text(g," "+k+"px "+f,d);q.textAlign="center";q.textBaseline="alphabetic";l=q.getBounds();q.x=c.width/2;q.y=Math.floor(c.height/2)+l.height/3;n=new createjs.Container;n.x=a;n.y=b;n.regX=
c.width/2;n.regY=c.height/2;n.addChild(m,p,q);s_oStage.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown");n.off("pressup");s_oStage.removeChild(n)};this.setVisible=function(a){n.visible=a};this._initListener=function(){oParent=this;n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){e[a]=b;h[a]=c};this.buttonRelease=function(){n.scaleX=1;n.scaleY=1;e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(h[ON_MOUSE_UP])};this.buttonDown=
function(){n.scaleX=.9;n.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setTextPosition=function(a){q.y=a;p.y=a+2};this.setPosition=function(a,b){n.x=a;n.y=b};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this._init(a,d,b,c,k,f,g);return this}
function CToggle(a,d,b,c,k){var f,g,e,h;this._init=function(a,b,c,d,k){g=[];e=[];var q=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=d;h=createSprite(q,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);h.x=a;h.y=b;h.stop();k.addChild(h);this._initListener()};this.unload=function(){s_bMobile?h.off("mousedown",this.buttonDown):(h.off("mousedown",this.buttonDown),h.off("mouseover",this.buttonOver));
h.off("pressup",this.buttonRelease);k.removeChild(h)};this._initListener=function(){if(s_bMobile)h.on("mousedown",this.buttonDown);else h.on("mousedown",this.buttonDown),h.on("mouseover",this.buttonOver);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;e[a]=c};this.setActive=function(a){f=a;h.gotoAndStop("state_"+f)};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");f=!f;h.gotoAndStop("state_"+
f);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(e[ON_MOUSE_UP],f)};this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN])};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.setPosition=function(a,b){h.x=a;h.y=b};this._init(a,d,b,c,k)}
function CGfxButton(a,d,b,c){var k,f,g,e,h,n;this._init=function(a,b,c,d){k=!1;f=1;g=[];e=[];h=createBitmap(c);h.x=a;h.y=b;h.scaleX=h.scaleY=f;h.regX=c.width/2;h.regY=c.height/2;d.addChild(h);this._initListener()};this.unload=function(){s_bMobile?h.off("mousedown",this.buttonDown):(h.off("mousedown",this.buttonDown),h.off("mouseover",this.buttonOver));h.off("pressup",this.buttonRelease);c.removeChild(h)};this.setVisible=function(a){h.visible=a};this.setClickable=function(a){k=!a};this._initListener=
function(){if(s_bMobile)h.on("mousedown",this.buttonDown);else h.on("mousedown",this.buttonDown),h.on("mouseover",this.buttonOver);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;e[a]=c};this.buttonRelease=function(){k||(h.scaleX=f,h.scaleY=f,g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(e[ON_MOUSE_UP]))};this.buttonDown=function(){k||(h.scaleX=.9*f,h.scaleY=.9*f,playSound("click",1,0),g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN]))};this.buttonOver=function(a){s_bMobile||
k||(a.target.cursor="pointer")};this.pulseAnimation=function(){createjs.Tween.get(h).to({scaleX:.9*f,scaleY:.9*f},850,createjs.Ease.quadOut).to({scaleX:f,scaleY:f},650,createjs.Ease.quadIn).call(function(){n.pulseAnimation()})};this.trembleAnimation=function(){createjs.Tween.get(h).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){n.trebleAnimation()})};this.setPosition=function(a,b){h.x=a;h.y=b};
this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};n=this;this._init(a,d,b,c);return this}var EASE_LINEAR=0,EASE_CUBIC_IN=1,EASE_QUART_BACKIN=2,EASE_BACKIN=3,EASE_SIN_IN=4,EASE_QUAD_IN=5,EASE_CUBIC_OUT=6,EASE_ELASTIC_OUT=7,EASE_BACKOUT=8,EASE_QUINT_OUT=9,EASE_CUBIC_INOUT=10;
function CTweenController(){this.tweenValue=function(a,d,b){return a+b*(d-a)};this.easeLinear=function(a,d,b,c){return b*a/c+d};this.easeInCubic=function(a,d,b,c){c=(a/=c)*a*a;return d+b*c};this.easeBackInQuart=function(a,d,b,c){c=(a/=c)*a;return d+b*(2*c*c+2*c*a+-3*c)};this.easeInBack=function(a,d,b,c){return b*(a/=c)*a*(2.70158*a-1.70158)+d};this.easeInSine=function(a,d,b,c){return-b*Math.cos(a/c*(Math.PI/2))+b+d};this.easeInQuad=function(a,d,b,c){return b*(a/=c)*a+d};this.easeInQuint=function(a,
d,b,c){a/=c;return b*a*a*a*a*a+d};this.easeOutCubic=function(a,d,b,c){return b*((a=a/c-1)*a*a+1)+d};this.easeOutElastic=function(a,d,b,c){var k;if(0===a)return d;if(1===(a/=c))return d+b;k=.3*c;return b*Math.pow(2,-10*a)*Math.sin(2*(a*c-k/4)*Math.PI/k)+b+d};this.easeOutBack=function(a,d,b,c){return b*((a=a/c-1)*a*(2.70158*a+1.70158)+1)+d};this.easeInOutCubic=function(a,d,b,c){return 1>(a/=c/2)?b/2*a*a*a+d:b/2*((a-=2)*a*a+2)+d};this.easeOutQuint=function(a,d,b,c){return b*((a=a/c-1)*a*a*a*a+1)+d}}
function CMenu(){var a,d,b,c,k,f,g,e,h,n,q,p,l,m,r,t,u,y,w,v,z;this._init=function(){k=randomFloatBetween(.02,.07);f=randomFloatBetween(.02,.07);e=g=0;y=new createjs.Container;s_oStage.addChild(y);w=new createjs.Container;s_oStage.addChild(w);h=new CBackground(y);n=new CStreet(0,y,w);n.setArrive(-400);z=new CCar(-randomFloatBetween(200,1E3),400,y,Math.floor(5*Math.random()),!1,OPPONENT_ENGINE_GEAR[0],0);z.setScale(.85);v=new CCar(-randomFloatBetween(200,1E3),500,y,Math.floor(5*Math.random()),!1,OPPONENT_ENGINE_GEAR[0],
0);var t=s_oSpriteLibrary.getSprite("logo"),x=createBitmap(t);x.regX=t.width/2;x.regY=t.height/2;x.x=-1E3;x.y=CANVAS_HEIGHT/2-160;s_oStage.addChild(x);(new createjs.Tween.get(x)).to({x:CANVAS_WIDTH/2},1500,createjs.Ease.cubicOut);s_oLocalStorage.isDirty()?(t=s_oSpriteLibrary.getSprite("but_play"),q=new CGfxButton(CANVAS_WIDTH/2-1070,CANVAS_HEIGHT-180,t,s_oStage),q.addEventListener(ON_MOUSE_UP,this._onButReset,this),(new createjs.Tween.get(q.getButtonImage())).wait(500).to({x:CANVAS_WIDTH/2-170},1500,
createjs.Ease.cubicOut),t=s_oSpriteLibrary.getSprite("but_continue_menu"),p=new CGfxButton(CANVAS_WIDTH/2-780,CANVAS_HEIGHT-180,t,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this),(new createjs.Tween.get(p.getButtonImage())).wait(1E3).to({x:CANVAS_WIDTH/2+120},1E3,createjs.Ease.cubicOut).call(function(){p.pulseAnimation()})):(t=s_oSpriteLibrary.getSprite("but_play"),q=new CGfxButton(CANVAS_WIDTH/2-780,CANVAS_HEIGHT-180,t,s_oStage),q.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,
this),(new createjs.Tween.get(q.getButtonImage())).wait(500).to({x:CANVAS_WIDTH/2},1500,createjs.Ease.cubicOut).call(function(){q.pulseAnimation()}));t=s_oSpriteLibrary.getSprite("but_info");b=t.height/2+10;c=t.height/2+10;r=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-240,t,s_oStage);r.addEventListener(ON_MOUSE_UP,this._onCreditsBut,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)t=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-t.height/2-10,d=t.height/2+10,m=new CToggle(a,d,t,s_bAudioActive,
s_oStage),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);l=new createjs.Shape;l.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(l);createjs.Tween.get(l).to({alpha:0},1E3).call(function(){l.visible=!1});u=new CCurtain(s_oStage);u.openAnim();this.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_oLocalStorage.isUsed()||new CMsgBox(TEXT_IOS_PRIVATE)};this.unload=function(){q.unload();q=null;l.visible=!1;r.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),
m=null;s_oStage.removeChild(h);s_oMenu=h=null;u.unload();v.unload();z.unload()};this.refreshButtonPos=function(g,e){r.setPosition(b+g,e+c);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(a-g,e+d)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCreditsBut=function(){new CCreditsPanel};this._onButPlayRelease=function(){s_oLocalStorage.isDirty()?(q.setClickable(!1),p.setClickable(!1)):q.setClickable(!1);u.closeAnim(t._onCurtainClose)};this._onButReset=
function(){(new CAreYouSurePanel(s_oMenu.removeDataAndContinue)).changeMessage(TEXT_SAVE_REMOVE,40)};this.removeDataAndContinue=function(){s_oLocalStorage.resetAllData();s_oLocalStorage.loadData();s_oMenu._onButPlayRelease()};this._onCurtainClose=function(){t.unload();$(s_oMain).trigger("start_session");s_oMain.gotoModeMenu()};this.resetAnim=function(){v.unload();v.unload();k=randomFloatBetween(.02,.07);f=randomFloatBetween(.02,.07);e=g=0;z=new CCar(-randomFloatBetween(200,1E3),400,y,Math.floor(5*
Math.random()),!1,OPPONENT_ENGINE_GEAR[0],0);z.setScale(.85);v=new CCar(-randomFloatBetween(200,1E3),500,y,Math.floor(5*Math.random()),!1,OPPONENT_ENGINE_GEAR[0],0)};this.update=function(){n.menuMovement(25);g-=k;e-=f;v.move(g);z.move(e);v.getCar().x>2*CANVAS_WIDTH&&z.getCar().x>2*CANVAS_WIDTH&&this.resetAnim()};s_oMenu=this;t=this;this._init()}var s_oMenu=null;
function CModeMenu(){var a,d,b,c,k,f,g,e,h,n=[],q,p,l,m,r,t,u;this._init=function(){g=0;new CBackground(s_oStage);p=new CStreet(0,s_oStage,s_oStage);p.setArrive(-400);t=new createjs.Shape;t.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);t.alpha=.7;s_oStage.addChild(t);h=new createjs.Container;h.x=0;h.y=0;var e=new createjs.Text(TEXT_SELECT_STAGE," 70px "+PRIMARY_FONT,"#3e240b");e.x=CANVAS_WIDTH/2;e.y=180;e.outline=10;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=
1E3;var w=new createjs.Text(TEXT_SELECT_STAGE," 70px "+PRIMARY_FONT,"#ffffff");w.x=CANVAS_WIDTH/2;w.y=180;w.textAlign="center";w.textBaseline="alphabetic";w.lineWidth=1E3;h.addChild(e,w);s_oStage.addChild(h);var e=.5*CANVAS_WIDTH-20,w=-200,v=-100;q=[];q=s_oLocalStorage.getItemJson(LOCALSTORAGE_TIMES);for(var z=0;z<q.length;z++)0<q[z]&&g++;for(z=0;z<NUM_TRACK;z++,w+=170)600<w&&(w=-200,v+=200),z<=g?(n[z]=new CLevelBut(e-120+w,425+v,s_oSpriteLibrary.getSprite("but_level"),!0,z+1,s_oStage),n[z].addEventListenerWithParams(ON_MOUSE_UP,
this._onClick,this,z),n[z].enable()):(n[z]=new CLevelBut(e-120+w,425+v,s_oSpriteLibrary.getSprite("but_level"),!1,z+1,s_oStage),n[z].disable()),n[z].addLevelText(z+1),n[z].disable(),s_bFirstTime=!0;this._setLevelInfo();e=s_oSpriteLibrary.getSprite("but_exit");k=CANVAS_WIDTH-e.height/2-10;f=e.height/2+17;l=new CGfxButton(k,f,e,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onExit,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(e=s_oSpriteLibrary.getSprite("audio_icon"),b=k-e.height-10,c=f,m=new CToggle(b,
c,e,s_bAudioActive,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),e=s_oSpriteLibrary.getSprite("but_shop"),a=b-e.height-10,d=c):(e=s_oSpriteLibrary.getSprite("but_shop"),a=k-e.height-10,d=f);r=new CGfxButton(a,d,e,s_oStage);r.addEventListener(ON_MOUSE_UP,this._onShop,this);t=new createjs.Shape;t.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(t);(new createjs.Tween.get(t)).to({alpha:0},1E3);u=new CCurtain(s_oStage);u.openAnim();this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.unload=function(){for(var a=0;a<NUM_TRACK;a++)n[a].unload();t.off("mousedown");s_oLevelMenu=null;s_oStage.removeAllChildren();u.unload()};this.refreshButtonPos=function(e,g){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(b-e,c+g);l.setPosition(k-e,f+g);r.setPosition(a-e,d+g)};this._setLevelInfo=function(){g<NUM_TRACK&&(n[g].enable(),n[g].pulseAnimation());for(var a=0;a<g;a++)n[a].enable(),n[a].addScore(q[a])};this._onNumModeToggle=function(a){a===NUM_ACTIVE?((void 0).setActive(!1),
(void 0).setActive(!0)):((void 0).setActive(!0),(void 0).setActive(!1))};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onClick=function(a){e=a;t.on("mousedown",function(){});createjs.Tween.get(t,{override:!0}).to({alpha:1},500);u.closeAnim(this._onCurtainClose)};this._onCurtainClose=function(){s_oLevelMenu.unload();s_oMain.gotoGame(e)};this._onExit=function(){$(s_oMain).trigger("end_session");u.closeAnim(this._onExitCurtainClose)};this._onExitCurtainClose=
function(){s_oLevelMenu.unload();s_oMain.gotoMenu()};this._onShop=function(){new CShopPanel};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(a,d,b,c,k,f){var g,e,h,n,q=[],p,l,m,r,t=null,u=null,y,w;this._init=function(a,b,f,d){g=!1;e=1;h=[];n=[];p=new createjs.Container;p.x=a;p.y=b;p.scaleX=p.scaleY=e;d.addChild(p);l=new createjs.Container;l.x=a;l.y=b;l.scaleX=p.scaleY=e;d.addChild(l);a=f.width/2;b=f.height;f=new createjs.SpriteSheet({images:[f],frames:{width:a,height:b,regX:a/2,regY:b/2},animations:{on:[0],off:[1]}});y=createSprite(f,"on",a/2,b/2,a,b);p.addChild(y);c?y.gotoAndStop("on"):y.gotoAndStop("off");this._initListener();
this.addInfo(STAGE_METER_LENGTH[k-1]+TEXT_M)};this.unload=function(){s_bMobile?p.off("mousedown",this.buttonDown):(p.off("mousedown",this.buttonDown),p.off("mouseover",this.buttonOver));p.off("pressup",this.buttonRelease);f.removeChild(p)};this.setVisible=function(a){p.visible=a};this.enable=function(){y.gotoAndStop("on");g=!1;null!==u&&(t.color="#3e240b",u.color="#ffffff");null!==r&&(m.color="#3e240b",r.color="#ffffff")};this.disable=function(){g=!0;y.gotoAndStop("off");null!==u&&(t.color="#000000",
u.color="#a8a8a8");null!==r&&(m.color="#000000",r.color="#a8a8a8")};this.setClickable=function(a){g=!a};this.addInfo=function(a){m=new createjs.Text(a," 24px "+PRIMARY_FONT,"#3e240b");m.x=b.height/2-24;m.y=-b.height/2+10;m.textAlign="center";m.textBaseline="middle";m.lineWidth=200;m.outline=4;m.rotation=30;p.addChild(m);r=new createjs.Text(a," 24px "+PRIMARY_FONT,"#ffffff");r.x=m.x;r.y=m.y;r.textAlign="center";r.textBaseline="middle";r.lineWidth=200;r.rotation=m.rotation;p.addChild(r)};this.addScore=
function(a){var c=new createjs.Text(formatTime(a)," 20px "+PRIMARY_FONT,"#3e240b");c.y=b.height/2+10;c.textAlign="center";c.textBaseline="middle";c.lineWidth=200;c.outline=4;l.addChild(c);a=new createjs.Text(formatTime(a)," 20px "+PRIMARY_FONT,"#ffffff");a.y=c.y;a.textAlign="center";a.textBaseline="middle";a.lineWidth=200;l.addChild(a)};this.addLevelText=function(a){t=new createjs.Text(a," 60px "+PRIMARY_FONT,"#3e240b");t.y=5;t.textAlign="center";t.textBaseline="middle";t.lineWidth=200;t.outline=
8;p.addChild(t);u=new createjs.Text(a," 60px "+PRIMARY_FONT,"#ffd800");u.y=5;u.textAlign="center";u.textBaseline="middle";u.lineWidth=200;p.addChild(u)};this._initListener=function(){if(s_bMobile)p.on("mousedown",this.buttonDown);else p.on("mousedown",this.buttonDown),p.on("mouseover",this.buttonOver);p.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;n[a]=c};this.addEventListenerWithParams=function(a,b,c,e){h[a]=b;n[a]=c;q=e};this.buttonRelease=function(){g||(p.scaleX=
e,p.scaleY=e,h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(n[ON_MOUSE_UP],q))};this.buttonDown=function(){g||(playSound("click",1,0),p.scaleX=.9*e,p.scaleY=.9*e,h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN],q))};this.buttonOver=function(a){s_bMobile||g||(a.target.cursor="pointer")};this.pulseAnimation=function(){createjs.Tween.get(p).to({scaleX:.9*e,scaleY:.9*e},850,createjs.Ease.quadOut).to({scaleX:e,scaleY:e},650,createjs.Ease.quadIn).call(function(){w.pulseAnimation()})};this.trembleAnimation=
function(){createjs.Tween.get(p).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){w.trebleAnimation()})};this.setPosition=function(a,b){p.x=a;p.y=b};this.setScale=function(a){e=a;p.scaleX=p.scaleY=a};this.setX=function(a){p.x=a};this.setY=function(a){p.y=a};this.getButtonImage=function(){return p};this.getX=function(){return p.x};this.getY=function(){return p.y};w=this;this._init(a,d,b,f);return this}
function CGame(a,d){var b,c,k,f,g,e,h,n,q,p,l=null,m,r,t,u,y,w,v,z,B,x,A;this._init=function(a,b){e=b;f=START_COUNTDOWN;k=STATE_HELP_PANEL;g=0;v=new createjs.Container;s_oStage.addChild(v);z=new createjs.Container;s_oStage.addChild(z);r=new CBackground(v);t=new CStreet(0,v,z);t.setArrive(STAGE_METER_LENGTH[e]);A=new CCar(START_LINE_X,400,v,e+1,!1,OPPONENT_ENGINE_GEAR[e],e);A.setScale(.85);var c=s_oSpriteLibrary.getSprite("woman_starting"),d=c.width/9,h=c.height/2;a={images:[c],framerate:30,frames:{width:d,
height:h,regX:d/2,regY:h},animations:{play:[0,17,"stop"],rev:[16,1,"play"],stop:[17]}};c=new createjs.SpriteSheet(a);w=createSprite(c,"play",d/2,h/2,d,h);w.x=700;w.y=450;w.gotoAndStop("play");v.addChild(w);x=new CCar(START_LINE_X,500,v,0,!0,PLAYER_ENGINE_GEAR,e);u=new CAI(A,e);p=new CInterface;s_oHUD.setGearArea(GEAR_START_AREA.center,GEAR_START_AREA);y=new createjs.Shape;y.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);y.on("mousedown",function(){});s_oStage.addChild(y);new CVsPanel(e);
$(s_oMain).trigger("start_level",e);B=new CCurtain(s_oStage);B.openAnim()};this.startAcceleration=function(a){s_oHUD.startAccelerate(a);a&&x.pitchStartAnim()};this.changeGear=function(){switch(s_oHUD.getIndicatorResult()){case GREEN_AREA:x.changeGear();s_oHUD.downShiftGear(x.getGear(),STATE_HUD_UPDATE,0);s_oHUD.scaleGear();new CScoreText(TEXT_PERFECT,100,-30,s_oHUD.getContainer());break;case EARLY_AREA:x.changeGear();this._wrongGearChange();s_oHUD.scaleGear();break;case LATE_AREA:x.changeGear(),this._wrongGearChange(),
s_oHUD.scaleGear()}x.getGear()<PLAYER_ENGINE_GEAR.length-1?s_oHUD.setGearArea(HUD_RPM_INTERVAL[x.getGear()].max-GEAR_IN_RACE_AREA.greenangle-5,GEAR_IN_RACE_AREA):s_oHUD.setGearArea(0,GEAR_NULL_AREA)};this._wrongGearChange=function(){playSound("wrong_gear",1,0);var a;a=b?WRONG_GEAR_CHANGE_STALL_DURATION/ENGINE_NITRO_RPM_ACCELERATION:WRONG_GEAR_CHANGE_STALL_DURATION;s_oHUD.downShiftGear(x.getGear(),STATE_HUD_STALL,a);x.delayEngine(a)};this.shotNitro=function(){b=!0;x.activateNitro(NITRO_DURATION);new CTremble(s_oStage,
NITRO_DURATION,5,1)};this.endNitro=function(){b=!1};this.playerHighlight=function(){x.highlight()};this.opponentHighlight=function(){A.highlight()};this.getPlayerMeterSpeed=function(){return x.getMeterSpeed()};this.getStage=function(){return e};this.nextLevel=function(){e++;e===NUM_TRACK?this.gameOver():(B.closeAnim(this._onCurtainClose),(new createjs.Tween.get(y)).to({alpha:1},500));fadeSound(s_oSoundtrack,0,1,2E3)};this.restartGame=function(){$(s_oMain).trigger("restart_level",e);$(s_oMain).trigger("show_interlevel_ad");
B.closeAnim(this._onCurtainClose);(new createjs.Tween.get(y)).to({alpha:1},500);fadeSound(s_oSoundtrack,0,1,2E3)};this._onCurtainClose=function(){m.unload();m._init(a,e)};this.unload=function(){p.unload();null!==l&&l.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren();B.unload();x.stopSound();q&&stopSound(q)};this.onExit=function(){$(s_oMain).trigger("end_session");$(s_oMain).trigger("end_level",e);$(s_oMain).trigger("show_interlevel_ad");B.closeAnim(m._onExitCurtain);(new createjs.Tween.get(y)).to({alpha:1},
500);fadeSound(s_oSoundtrack,0,1,2E3)};this._onExitCurtain=function(){s_oGame.unload();s_oMain.gotoMenu()};this._onExitVersusPanel=function(){(new createjs.Tween.get(y)).to({alpha:0},500).call(function(){0===e?new CHelpPanel:(n=playSound("ignition",1,0),k=STATE_START_BATTLE,fadeSound(s_oSoundtrack,1,0,2E3))})};this._onExitHelp=function(){n=playSound("ignition",1,0);k=STATE_START_BATTLE;fadeSound(s_oSoundtrack,1,0,2E3)};this._checkWinner=function(a,b){stopSound(q);x.stopSound();var c=a-b;$(s_oMain).trigger("end_level",
e);a>b?new CNextLevelPanel(e,g,c):new CRetryPanel};this.gameOver=function(){l=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));l.show(e,g)};this.update=function(){switch(k){case STATE_START_BATTLE:s_oHUD.updateIndicatorForStartBattle();f-=s_iTimeElaps;0>=f&&(f=0,p.removeCountdown(),k=STATE_RACE_RUN,x.ignition(),A.ignition(),s_oHUD.getIndicatorResult()!==GREEN_AREA?this._wrongGearChange():(s_oHUD.downShiftGear(x.getGear(),STATE_HUD_UPDATE,0),new CScoreText(TEXT_PERFECT,100,-30,s_oHUD.getContainer())),
s_oHUD.scaleGear(),s_oHUD.acceleratorButtonVisible(!1),s_oHUD.setGearArea(HUD_RPM_INTERVAL[x.getGear()].max-GEAR_IN_RACE_AREA.greenangle-5,GEAR_IN_RACE_AREA),0!==parseInt(s_oLocalStorage.getItem(LOCALSTORAGE_NITROPOWER_LEVEL))&&s_oHUD.nitroButtonVisible(!0),s_oHUD.gearButtonVisible(!0),w.gotoAndPlay("play"),playSound("sprint_start",1,0),fadeSound(n,1,0,2E3),q=playSound("engine",1,-1));p.refreshCountdown(f);break;case STATE_RACE_RUN:x.move();c=x.getSpeed();w.x-=c;h=x.getMeterPos();h>STAGE_METER_LENGTH[e]?
(k=STATE_RACE_FINISH,this._checkWinner(h,A.getMeterPos())):g+=s_iTimeElaps;t.move(c,x.getPixelPos(),A.getPixelPos());r.move(c*PARALLAX_BG_RATIO);A.move(c);s_oHUD.updateTachometer(x.getMeterSpeed(),x.getGear());break;case STATE_RACE_FINISH:x.move(),c=x.getSpeed(),t.move(c,x.getPixelPos(),A.getPixelPos()),r.move(c*PARALLAX_BG_RATIO),A.move(c),s_oHUD.updateTachometer(x.getMeterSpeed(),x.getGear())}u.update(k,A.getMeterPos());p.refreshMap(x.getMeterPos(),A.getMeterPos(),g)};s_oGame=this;m=this;this._init(a,
d)}var s_oGame;
function CInterface(){var a,d,b,c,k,f,g,e,h,n,q,p,l=null,m,r,t,u,y,w,v=null,z=null;this._init=function(){var l=s_oSpriteLibrary.getSprite("but_exit");h=CANVAS_WIDTH-l.height/2-10;n=l.height/2+10;p=new CGfxButton(h,n,l,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onExit,this);g=CANVAS_WIDTH-l.width/2-80;e=l.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l=s_oSpriteLibrary.getSprite("audio_icon"),q=new CToggle(h-l.height-10,e,l,s_bAudioActive,s_oStage),q.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);var l=window.document,x=l.documentElement;v=x.requestFullscreen||x.mozRequestFullScreen||x.webkitRequestFullScreen||x.msRequestFullscreen;z=l.exitFullscreen||l.mozCancelFullScreen||l.webkitExitFullscreen||l.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(v=!1);v&&!inIframe()&&(l=s_oSpriteLibrary.getSprite("but_fullscreen"),a=l.width/4+10,d=l.height/2+10,y=new CToggle(a,d,l,s_bAudioActive,s_oStage),y.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));r=new createjs.Text(""," 300px "+PRIMARY_FONT,
"#3e240b");r.x=CANVAS_WIDTH/2;r.y=CANVAS_HEIGHT/2;r.textAlign="center";r.textBaseline="middle";r.lineWidth=200;r.outline=20;s_oStage.addChild(r);t=new createjs.Text(""," 300px "+PRIMARY_FONT,"rgba(255,224,0,1)");t.x=CANVAS_WIDTH/2;t.y=CANVAS_HEIGHT/2;t.textAlign="center";t.textBaseline="middle";t.lineWidth=200;s_oStage.addChild(t);w=[];for(l=0;3>=l;l++)w[l]=!1;k=CANVAS_WIDTH/2;f=720;m=new CHUD(s_oStage);b=CANVAS_WIDTH/2-100;c=46;u=new CMapTrack(b,c,s_oStage,s_oGame.getStage());this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q.unload(),q=null;p.unload();v&&!inIframe()&&y.unload();s_oInterface=null};this.refreshButtonPos=function(t,l){p.setPosition(h-t,l+n);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||q.setPosition(g-t,l+e);v&&!inIframe()&&y.setPosition(a+t,d+l);m.setPos(k,f-l);u.setPos(b,c+l)};this.refreshMap=function(a,b,c){u.refreshMap(a,b,c)};this.refreshCountdown=function(a){var b=Math.ceil(a/1E3),c=(1E3*b-a)/1E3;t.alpha=1-c;t.scaleX=t.scaleY=
c;t.text=Math.ceil(a/1E3);r.alpha=t.alpha;r.scaleX=r.scaleY=c;r.text=t.text;3!==b||w[3]?2!==b||w[2]?1!==b||w[1]?0===b&&(w[0]=!0,playSound("go",1,0)):(w[1]=!0,playSound("1",1,0)):(w[2]=!0,playSound("2",1,0)):(w[3]=!0,playSound("3",1,0))};this.removeCountdown=function(){t.visible=!1};this._onFullscreen=function(){s_bFullscreen?(z.call(window.document),s_bFullscreen=!1):(v.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};this._onButHelpRelease=function(){l=new CHelpPanel};this._onButRestartRelease=
function(){s_oGame.restartGame()};this.onExitFromHelp=function(){l.unload()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){new CAreYouSurePanel(s_oGame.onExit)};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CMapTrack(a,d,b,c){var k,f,g,e,h,n,q,p,l,m,r,t,u;this._init=function(a,b,c,d){e=g=!1;h=d;p=new createjs.Container;c.addChild(p);a=s_oSpriteLibrary.getSprite("map_track");b=createBitmap(a);b.regX=a.width/2;b.regY=a.height/2;p.addChild(b);r=new createjs.Text("00:00.0"," 30px "+PRIMARY_FONT,"#3e240b");r.x=430;r.textAlign="center";r.textBaseline="middle";r.lineWidth=200;r.outline=3;p.addChild(r);t=new createjs.Text("00:00.0"," 30px "+PRIMARY_FONT,"#ffffff");t.x=r.x;t.textAlign="center";t.textBaseline=
"middle";t.lineWidth=200;p.addChild(t);u=new createjs.Text(STAGE_METER_LENGTH[d]+TEXT_M," 30px "+PRIMARY_FONT,"#ffffff");u.textAlign="center";u.textBaseline="middle";u.lineWidth=200;k=-a.width/2+24;f=a.width/2-10;a=s_oSpriteLibrary.getSprite("car_track_0");m=createBitmap(a);m.regX=a.width/2;m.regY=a.height/2;m.x=k;m.y=-15;p.addChild(m);a=s_oSpriteLibrary.getSprite("car_track_1");l=createBitmap(a);l.regX=a.width/2;l.regY=a.height/2;l.x=k;l.y=15;p.addChild(l);n=pixelsToMeters(START_LINE_X);q=(f-k)/
(STAGE_METER_LENGTH[h]-n)};this.setPos=function(a,b){p.x=a;p.y=b};this._fadeOutIndicator=function(a){(new createjs.Tween.get(a)).to({alpha:0},500)};this.refreshMap=function(a,b,c){l.x=(a-n)*q+k;m.x=(b-n)*q+k;t.text=formatTime(c);r.text=formatTime(c);!g&&l.x>f&&(g=!0,this._fadeOutIndicator(l));!e&&m.x>f&&(e=!0,this._fadeOutIndicator(m))};this._init(a,d,b,c)}
function CVsPanel(a){var d,b,c,k,f,g,e,h,n,q,p,l;this._init=function(a){d=!1;k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=0;k.on("mousedown",function(){g._onExit()});s_oStage.addChild(k);(new createjs.Tween.get(k)).to({alpha:.7},500);f=new createjs.Container;f.on("pressup",function(){g._onExit()});s_oStage.addChild(f);var m=s_oSpriteLibrary.getSprite("msg_box");b=m.width;c=m.height;m=createBitmap(m);m.regX=b/2;m.regY=c/2;f.addChild(m);f.x=CANVAS_WIDTH/
2;f.y=CANVAS_HEIGHT/2;(new createjs.Tween.get(f)).to({y:CANVAS_HEIGHT/2},500,createjs.Ease.cubicIn);h=new CCar(CANVAS_WIDTH/2,135,f,0,!0,OPPONENT_ENGINE_GEAR[a],a);h.getCar().scaleX=-1;e=new CCar(-CANVAS_WIDTH/2,-45,f,a+1,!1,OPPONENT_ENGINE_GEAR[a],a);n=new createjs.Text(TEXT_VS," 100px "+PRIMARY_FONT,"#3e240b");n.textAlign="center";n.textBaseline="middle";n.lineWidth=400;n.outline=5;n.alpha=0;n.scaleX=n.scaleY=4;n.y=15;f.addChild(n);q=new createjs.Text(n.text," 100px "+PRIMARY_FONT,"rgba(255,224,0,1)");
q.textAlign="center";q.textBaseline="middle";q.lineWidth=400;q.alpha=0;q.scaleX=q.scaleY=4;q.y=n.y;f.addChild(q);for(var m=0,t=s_oLocalStorage.getItemJson(LOCALSTORAGE_TIMES),u=0;u<t.length;u++)0<t[u]&&m++;t=0;u="";a>=m&&(t=STAGE_WIN_REWARDS[a],u=TEXT_CURRENCY+t);t=STAGE_WIN_REWARDS[a];p=new createjs.Text(TEXT_PRIZE+": "+u," 40px "+PRIMARY_FONT,"#3e240b");p.x=-302;p.y=160;p.textAlign="left";p.textBaseline="middle";p.lineWidth=400;p.outline=5;p.alpha=0;p.scaleX=p.scaleY=4;f.addChild(p);l=new createjs.Text(p.text,
" 40px "+PRIMARY_FONT,"rgba(255,224,0,1)");l.x=p.x;l.y=p.y;l.textAlign="left";l.textBaseline="middle";l.lineWidth=400;l.alpha=0;l.scaleX=l.scaleY=4;f.addChild(l);this._introAnim()};this.unload=function(){s_oStage.removeChild(k);s_oStage.removeChild(f);f.off("pressup",function(){g._onExit()});k.off("pressup",function(){g._onExit()});h.unload();e.unload()};this._introAnim=function(){(new createjs.Tween.get(e.getCar())).to({x:-200},2E3,createjs.Ease.cubicOut);(new createjs.Tween.get(e.getWheels().right)).to({rotation:1500},
2E3,createjs.Ease.cubicOut);(new createjs.Tween.get(e.getWheels().left)).to({rotation:1500},2E3,createjs.Ease.cubicOut);(new createjs.Tween.get(h.getCar())).to({x:200},2E3,createjs.Ease.cubicOut);(new createjs.Tween.get(h.getWheels().right)).to({rotation:1500},2E3,createjs.Ease.cubicOut);(new createjs.Tween.get(h.getWheels().left)).to({rotation:1500},2E3,createjs.Ease.cubicOut);(new createjs.Tween.get(q)).wait(500).to({alpha:1,scaleX:1,scaleY:1},1E3,createjs.Ease.cubicIn);(new createjs.Tween.get(n)).wait(500).to({alpha:1,
scaleX:1,scaleY:1},1E3,createjs.Ease.cubicIn);(new createjs.Tween.get(l)).wait(750).to({alpha:1,scaleX:1,scaleY:1},1E3,createjs.Ease.cubicIn);(new createjs.Tween.get(p)).wait(750).to({alpha:1,scaleX:1,scaleY:1},1E3,createjs.Ease.cubicIn)};this._outroAnim=function(){setTimeout(function(){e.highlight();h.highlight()},300);playSound("acceleration",1,0);(new createjs.Tween.get(e.getCar(),{override:!0})).to({x:CANVAS_WIDTH/2},1E3,createjs.Ease.cubicIn);(new createjs.Tween.get(e.getWheels().right,{override:!0})).to({rotation:3E3},
1E3,createjs.Ease.cubicIn);(new createjs.Tween.get(e.getWheels().left,{override:!0})).to({rotation:3E3},1E3,createjs.Ease.cubicIn);(new createjs.Tween.get(h.getCar(),{override:!0})).to({x:-CANVAS_WIDTH/2},1E3,createjs.Ease.cubicIn);(new createjs.Tween.get(h.getWheels().right,{override:!0})).to({rotation:3E3},1E3,createjs.Ease.cubicIn);(new createjs.Tween.get(h.getWheels().left,{override:!0})).to({rotation:3E3},1E3,createjs.Ease.cubicIn)};this._onExit=function(){d||(d=!0,g._outroAnim(),(new createjs.Tween.get(k)).to({alpha:0},
1E3),(new createjs.Tween.get(f)).to({alpha:0},1E3).call(function(){s_oGame._onExitVersusPanel();g.unload()}))};g=this;this._init(a)}
function CHelpPanel(){var a,d,b,c,k,f,g,e,h,n;this._init=function(){g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;g.on("mousedown",function(){h._onExitHelp()});s_oStage.addChild(g);(new createjs.Tween.get(g)).to({alpha:.7},500);e=new createjs.Container;e.on("pressup",function(){h._onExitHelp()});s_oStage.addChild(e);var d=s_oSpriteLibrary.getSprite("msg_box"),p=createBitmap(d);p.regX=d.width/2;p.regY=d.height/2;e.addChild(p);e.x=CANVAS_WIDTH/
2;e.y=CANVAS_HEIGHT+d.height/2;a=e.y;(new createjs.Tween.get(e)).to({y:CANVAS_HEIGHT/2-40},500,createjs.Ease.cubicOut);c=new createjs.Text(TEXT_HELP1," 24px "+PRIMARY_FONT,"#3e240b");c.x=-280;c.y=-150;c.textAlign="left";c.textBaseline="alphabetic";c.lineWidth=400;c.outline=4;e.addChild(c);b=new createjs.Text(TEXT_HELP1," 24px "+PRIMARY_FONT,"#ffffff");b.x=-280;b.y=-150;b.textAlign="left";b.textBaseline="alphabetic";b.lineWidth=400;e.addChild(b);d=s_oSpriteLibrary.getSprite("accelerator");p=createBitmap(d);
p.regX=d.width/2;p.regY=d.height/2;p.x=200;p.y=-100;p.scaleX=p.scaleY=.7;e.addChild(p);f=new createjs.Text(TEXT_HELP2," 24px "+PRIMARY_FONT,"#3e240b");f.x=-280;f.y=70;f.textAlign="left";f.textBaseline="alphabetic";f.lineWidth=350;f.outline=4;e.addChild(f);k=new createjs.Text(TEXT_HELP2," 24px "+PRIMARY_FONT,"#ffffff");k.x=-280;k.y=70;k.textAlign="left";k.textBaseline="alphabetic";k.lineWidth=350;e.addChild(k);d=s_oSpriteLibrary.getSprite("but_gear");n=new CGearButton(200,80,d,e);n.setClickable(!1)};
this.unload=function(){s_oStage.removeChild(g);s_oStage.removeChild(e);e.off("pressup",function(){h._onExitHelp()});g.off("pressup",function(){h._onExitHelp()});n.unload()};this._onExitHelp=function(){d||(d=!0,(new createjs.Tween.get(g)).to({alpha:0},500),(new createjs.Tween.get(e)).to({y:a},400,createjs.Ease.backIn).call(function(){h.unload();s_oGame._onExitHelp()}))};h=this;this._init()}
function CCreditsPanel(){var a,d,b,c,k;this._init=function(){d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;d.on("mousedown",function(){});s_oStage.addChild(d);(new createjs.Tween.get(d)).to({alpha:.7},500);b=new createjs.Container;s_oStage.addChild(b);var f=s_oSpriteLibrary.getSprite("msg_box"),g=createBitmap(f);g.regX=f.width/2;g.regY=f.height/2;b.addChild(g);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT+f.height/2;a=b.y;(new createjs.Tween.get(b)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.cubicOut);g=new createjs.Text("DEVELOPED BY"," 40px "+PRIMARY_FONT,"#3e240b");g.y=-f.height/2+110;g.textAlign="center";g.textBaseline="middle";g.lineWidth=500;g.outline=5;b.addChild(g);f=new createjs.Text("DEVELOPED BY"," 40px "+PRIMARY_FONT,"#ffffff");f.y=g.y;f.textAlign="center";f.textBaseline="middle";f.lineWidth=500;b.addChild(f);f=new createjs.Text("www.codethislab.com"," 40px "+PRIMARY_FONT,"#3e240b");f.y=90;f.textAlign="center";f.textBaseline="middle";f.lineWidth=600;
f.outline=5;b.addChild(f);g=new createjs.Text("www.codethislab.com"," 40px "+PRIMARY_FONT,"#ffffff");g.y=f.y;g.textAlign="center";g.textBaseline="middle";g.lineWidth=600;b.addChild(g);f=s_oSpriteLibrary.getSprite("ctl_logo");k=createBitmap(f);k.on("mousedown",this._onLogoButRelease);k.regX=f.width/2;k.regY=f.height/2;b.addChild(k);f=s_oSpriteLibrary.getSprite("but_exit");c=new CGfxButton(282,-155,f,b);c.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){c.setClickable(!1);(new createjs.Tween.get(d)).to({alpha:0},
500);(new createjs.Tween.get(b)).to({y:a},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(d);s_oStage.removeChild(b);c.unload()});d.off("mousedown",function(){});k.off("mousedown",this._onLogoButRelease)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._onMoreGamesReleased=function(){window.open("http://codecanyon.net/collections/5409142-games")};this._init()}
function CMsgBox(a,d){var b,c,k,f,g,e,h;this._init=function(a,d){g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;g.on("mousedown",function(){});s_oStage.addChild(g);(new createjs.Tween.get(g)).to({alpha:.7},500);e=new createjs.Container;s_oStage.addChild(e);var h=s_oSpriteLibrary.getSprite("msg_box"),l=createBitmap(h);l.regX=h.width/2;l.regY=h.height/2;e.addChild(l);e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT+h.height/2;b=e.y;(new createjs.Tween.get(e)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.quartIn);c=new createjs.Text(a," 26px "+PRIMARY_FONT,"#000000");c.y=-h.height/2+60;c.textAlign="center";c.textBaseline="middle";c.lineWidth=550;c.outline=5;e.addChild(c);k=new createjs.Text(a," 26px "+PRIMARY_FONT,"#ffffff");k.y=c.y;k.textAlign="center";k.textBaseline="middle";k.lineWidth=550;e.addChild(k);f=new CGfxButton(0,80,s_oSpriteLibrary.getSprite("but_yes_big"),e);f.addEventListener(ON_MOUSE_UP,this._onButYes,this);f.pulseAnimation()};this._onButYes=function(){f.setClickable(!1);
(new createjs.Tween.get(g)).to({alpha:0},500);(new createjs.Tween.get(e)).to({y:b},400,createjs.Ease.backIn).call(function(){h.unload();d&&d()})};this.changeMessage=function(a){c.text=a;k.text=a};this.unload=function(){f.unload();s_oStage.removeChild(g);s_oStage.removeChild(e);g.off("mousedown",function(){})};h=this;this._init(a,d)}
function CAreYouSurePanel(a){var d,b,c,k,f,g,e,h;this._init=function(a){g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;g.on("mousedown",function(){});s_oStage.addChild(g);(new createjs.Tween.get(g)).to({alpha:.7},500);e=new createjs.Container;s_oStage.addChild(e);a=s_oSpriteLibrary.getSprite("msg_box");var h=createBitmap(a);h.regX=a.width/2;h.regY=a.height/2;e.addChild(h);e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT+a.height/2;d=e.y;(new createjs.Tween.get(e)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.cubicOut);b=new createjs.Text(TEXT_ARE_SURE," 50px "+PRIMARY_FONT,"#000000");b.y=-a.height/2+120;b.textAlign="center";b.textBaseline="middle";b.lineWidth=600;b.outline=5;e.addChild(b);c=new createjs.Text(TEXT_ARE_SURE," 50px "+PRIMARY_FONT,"#ffffff");c.y=b.y;c.textAlign="center";c.textBaseline="middle";c.lineWidth=600;e.addChild(c);k=new CGfxButton(110,80,s_oSpriteLibrary.getSprite("but_yes_big"),e);k.addEventListener(ON_MOUSE_UP,this._onButYes,this);f=new CGfxButton(-110,
80,s_oSpriteLibrary.getSprite("but_exit_big"),e);f.addEventListener(ON_MOUSE_UP,this._onButNo,this);f.pulseAnimation()};this._onButYes=function(){f.setClickable(!1);k.setClickable(!1);(new createjs.Tween.get(g)).to({alpha:0},500);(new createjs.Tween.get(e)).to({y:d},400,createjs.Ease.backIn).call(function(){h.unload();a()})};this._onButNo=function(){f.setClickable(!1);k.setClickable(!1);(new createjs.Tween.get(g)).to({alpha:0},500);(new createjs.Tween.get(e)).to({y:d},400,createjs.Ease.backIn).call(function(){h.unload()})};
this.changeMessage=function(a,e){b.text=a;c.text=a;e&&(b.font=" "+e+"px "+PRIMARY_FONT,c.font=" "+e+"px "+PRIMARY_FONT)};this.unload=function(){f.unload();k.unload();s_oStage.removeChild(g);s_oStage.removeChild(e);g.off("mousedown",function(){})};h=this;this._init(a)}
function CNextLevelPanel(a,d,b){var c,k,f,g,e,h,n,q,p;this._init=function(a,b,d){playSound("arrive_win",1,0);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;g.on("mousedown",function(){});s_oStage.addChild(g);(new createjs.Tween.get(g)).to({alpha:.7},500);e=new createjs.Container;s_oStage.addChild(e);var h=s_oSpriteLibrary.getSprite("msg_box"),m=createBitmap(h);m.regX=h.width/2;m.regY=h.height/2;e.addChild(m);e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT+
h.height/2;c=e.y;(new createjs.Tween.get(e)).wait(1E3).to({y:CANVAS_HEIGHT/2-40},500,createjs.Ease.cubicOut);m=new createjs.Text(TEXT_WIN," 50px "+PRIMARY_FONT,"#3e240b");m.y=-h.height/2+60;m.textAlign="center";m.textBaseline="alphabetic";m.lineWidth=400;m.outline=5;e.addChild(m);var l=new createjs.Text(TEXT_WIN," 50px "+PRIMARY_FONT,"#ffffff");l.y=m.y;l.textAlign="center";l.textBaseline="alphabetic";l.lineWidth=400;e.addChild(l);for(var l=0,m=s_oLocalStorage.getItemJson(LOCALSTORAGE_TIMES),r=0;r<
m.length;r++)0<m[r]&&l++;m=0;r=TEXT_FIRST_WIN+": -";a>=l&&(m=STAGE_WIN_REWARDS[a],r=TEXT_FIRST_WIN+": "+TEXT_CURRENCY+STAGE_WIN_REWARDS[a]);l=new createjs.Text(r," 30px "+PRIMARY_FONT,"#3e240b");l.y=-h.height/2+100;l.textAlign="center";l.textBaseline="alphabetic";l.lineWidth=400;l.outline=5;e.addChild(l);r=new createjs.Text(r," 30px "+PRIMARY_FONT,"#ffffff");r.y=l.y;r.textAlign="center";r.textBaseline="alphabetic";r.lineWidth=400;e.addChild(r);l=new createjs.Text(TEXT_BONUS," 26px "+PRIMARY_FONT,
"#3e240b");l.x=-250;l.y=-h.height/2+150;l.textAlign="left";l.textBaseline="alphabetic";l.lineWidth=400;l.outline=5;e.addChild(l);r=new createjs.Text(TEXT_BONUS," 26px "+PRIMARY_FONT,"#ffffff");r.x=l.x;r.y=l.y;r.textAlign="left";r.textBaseline="alphabetic";r.lineWidth=400;e.addChild(r);l=Math.floor(.01*STAGE_METER_LENGTH[a]*BONUS_REWARD_TRACKLENGTH_MULTIPLIER);r=new createjs.Text(TEXT_BONUS_TRACK_LENGTH+": "+TEXT_CURRENCY+l," 18px "+PRIMARY_FONT,"#3e240b");r.x=-250;r.y=-h.height/2+180;r.textAlign=
"left";r.textBaseline="alphabetic";r.lineWidth=400;r.outline=5;e.addChild(r);var v=new createjs.Text(r.text," 18px "+PRIMARY_FONT,"#ffffff");v.x=r.x;v.y=r.y;v.textAlign="left";v.textBaseline="alphabetic";v.lineWidth=400;e.addChild(v);d=Math.floor(.1*d*BONUS_REWARD_OVERTAKING_MULTIPLIER);r=new createjs.Text(TEXT_BONUS_OVERTAKING+": "+TEXT_CURRENCY+d," 18px "+PRIMARY_FONT,"#3e240b");r.x=-250;r.y=-h.height/2+205;r.textAlign="left";r.textBaseline="alphabetic";r.lineWidth=400;r.outline=5;e.addChild(r);
v=new createjs.Text(r.text," 18px "+PRIMARY_FONT,"#ffffff");v.x=r.x;v.y=r.y;v.textAlign="left";v.textBaseline="alphabetic";v.lineWidth=400;e.addChild(v);r=(a+1)*BONUS_REWARD_DIFFICULTY_MULTIPLIER;v=new createjs.Text(TEXT_BONUS_DIFFICULTY+": "+TEXT_CURRENCY+r," 18px "+PRIMARY_FONT,"#3e240b");v.x=-250;v.y=-h.height/2+230;v.textAlign="left";v.textBaseline="alphabetic";v.lineWidth=400;v.outline=5;e.addChild(v);h=new createjs.Text(v.text," 18px "+PRIMARY_FONT,"#ffffff");h.x=v.x;h.y=v.y;h.textAlign="left";
h.textBaseline="alphabetic";h.lineWidth=400;e.addChild(h);k=new CGfxButton(245,120,s_oSpriteLibrary.getSprite("but_continue"),e);k.addEventListener(ON_MOUSE_UP,this._showShop,this);k.pulseAnimation();f=new CGfxButton(-245,120,s_oSpriteLibrary.getSprite("but_restart"),e);f.addEventListener(ON_MOUSE_UP,this._onButRestart,this);this._sendBestTime(a,b);a=parseInt(s_oLocalStorage.getItem(LOCALSTORAGE_COINS));b=a+m+l+d+r;s_oLocalStorage.setItem(LOCALSTORAGE_COINS,b);p=new createjs.Text(TEXT_CURRENCY+a,
" 40px "+PRIMARY_FONT,"#3e240b");p.x=250;p.y=h.y;p.textAlign="right";p.textBaseline="alphabetic";p.lineWidth=400;p.outline=5;e.addChild(p);q=new createjs.Text(TEXT_CURRENCY+a," 40px "+PRIMARY_FONT,"#ffffff");q.x=p.x;q.y=p.y;q.textAlign="right";q.textBaseline="alphabetic";q.lineWidth=400;e.addChild(q);n={value:a};(new createjs.Tween.get(n,{override:!0})).to({value:b},3E3,createjs.Ease.cubicOut).addEventListener("change",this._refreshCoins)};this._refreshCoins=function(){var a=n.value.toFixed(0);p.text=
TEXT_CURRENCY+a;q.text=TEXT_CURRENCY+a};this._sendBestTime=function(a,b){var c=s_oLocalStorage.getItemJson(LOCALSTORAGE_TIMES);if(c[a]>b||0===c[a])c[a]=b,s_oLocalStorage.setItemJson(LOCALSTORAGE_TIMES,c);$(s_oMain).trigger("share_event",b);$(s_oMain).trigger("save_score",b,a)};this._showShop=function(){new CShopPanel(this._onButContinue)};this._onButContinue=function(){f.setClickable(!1);k.setClickable(!1);(new createjs.Tween.get(g)).to({alpha:0},500);(new createjs.Tween.get(e)).to({y:c},400,createjs.Ease.backIn).call(function(){h.unload();
s_oGame.nextLevel()})};this._onButRestart=function(){f.setClickable(!1);k.setClickable(!1);(new createjs.Tween.get(g)).to({alpha:0},500);(new createjs.Tween.get(e)).to({y:c},400,createjs.Ease.backIn).call(function(){h.unload();s_oGame.restartGame()})};this.unload=function(){$(s_oMain).trigger("show_interlevel_ad");f.unload();k.unload();s_oStage.removeChild(g);s_oStage.removeChild(e);g.off("mousedown",function(){})};h=this;this._init(a,d,b)}
function CRetryPanel(){var a,d,b,c,k,f;this._init=function(){playSound("arrive_lose",1,0);c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;c.on("mousedown",function(){});s_oStage.addChild(c);(new createjs.Tween.get(c)).to({alpha:.7},500);k=new createjs.Container;s_oStage.addChild(k);var g=s_oSpriteLibrary.getSprite("msg_box"),e=createBitmap(g);e.regX=g.width/2;e.regY=g.height/2;k.addChild(e);k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT+g.height/2;a=k.y;
(new createjs.Tween.get(k)).to({y:CANVAS_HEIGHT/2-40},500,createjs.Ease.quartIn);e=new createjs.Text(TEXT_LOSE," 50px "+PRIMARY_FONT,"#000000");e.y=-g.height/2+120;e.textAlign="center";e.textBaseline="middle";e.lineWidth=500;e.outline=5;k.addChild(e);g=new createjs.Text(TEXT_LOSE," 50px "+PRIMARY_FONT,"#ffffff");g.y=e.y;g.textAlign="center";g.textBaseline="middle";g.lineWidth=500;k.addChild(g);b=new CGfxButton(110,80,s_oSpriteLibrary.getSprite("but_restart"),k);b.addEventListener(ON_MOUSE_UP,this._onButRestart,
this);b.pulseAnimation();d=new CGfxButton(-110,80,s_oSpriteLibrary.getSprite("but_home"),k);d.addEventListener(ON_MOUSE_UP,this._onButHome,this)};this._showShop=function(){new CShopPanel(this._onButContinue)};this._onButHome=function(){b.setClickable(!1);d.setClickable(!1);(new createjs.Tween.get(c)).to({alpha:0},500);(new createjs.Tween.get(k)).to({y:a},400,createjs.Ease.backIn).call(function(){f.unload();s_oGame.onExit()})};this._onButRestart=function(){b.setClickable(!1);d.setClickable(!1);(new createjs.Tween.get(c)).to({alpha:0},
500);(new createjs.Tween.get(k)).to({y:a},400,createjs.Ease.backIn).call(function(){f.unload();s_oGame.restartGame();$(s_oMain).trigger("show_interlevel_ad")})};this.unload=function(){b.unload();d.unload();s_oStage.removeChild(c);s_oStage.removeChild(k);c.off("mousedown",function(){})};f=this;this._init()}
function CEndPanel(a){var d,b,c,k,f,g,e,h,n;this._init=function(a){playSound("arrive_win",1,0);d=!1;h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=0;h.on("mousedown",this._onExit);s_oStage.addChild(h);(new createjs.Tween.get(h)).to({alpha:.7},500);b=createBitmap(a);b.x=0;b.y=0;k=new createjs.Text(""," 60px "+PRIMARY_FONT,"#3e240b");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2;k.textAlign="center";k.textBaseline="alphabetic";k.outline=8;k.lineWidth=500;
f=new createjs.Text(""," 60px "+PRIMARY_FONT,"#ffffff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2;f.textAlign="center";f.textBaseline="alphabetic";f.lineWidth=500;g=new createjs.Text(""," 40px "+PRIMARY_FONT,"#000");g.x=CANVAS_WIDTH/2+1;g.y=CANVAS_HEIGHT/2+50;g.textAlign="center";g.textBaseline="alphabetic";g.lineWidth=500;e=new createjs.Text(""," 40px "+PRIMARY_FONT,"#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+52;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=500;c=new createjs.Container;
c.alpha=0;c.visible=!1;c.addChild(g,e,k,f);s_oStage.addChild(c)};this.unload=function(){h.off("mousedown",this._onExit);c.off("mousedown",this._onExit)};this._initListener=function(){c.on("mousedown",this._onExit)};this.show=function(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");k.text=TEXT_GAMEOVER;f.text=TEXT_GAMEOVER;c.visible=!0;var e=this;createjs.Tween.get(c).to({alpha:1},500).call(function(){e._initListener()})};this._onExit=function(){d||(d=!0,(new createjs.Tween.get(h)).to({alpha:0},
500),n.unload(),s_oStage.removeChild(c),s_oGame.onExit())};n=this;this._init(a);return this}
function CShopPanel(a){var d,b,c,k,f,g,e,h,n,q,p,l,m,r,t;this._init=function(a){m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);m.alpha=0;m.on("mousedown",function(){});s_oStage.addChild(m);(new createjs.Tween.get(m)).to({alpha:.7},500);r=new createjs.Container;s_oStage.addChild(r);a=s_oSpriteLibrary.getSprite("msg_box");var t=createBitmap(a);t.regX=a.width/2;t.regY=a.height/2;r.addChild(t);r.x=CANVAS_WIDTH/2;r.y=CANVAS_HEIGHT+a.height/2;d=r.y;(new createjs.Tween.get(r)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.cubicOut);t=new createjs.Text(TEXT_SHOP," 50px "+PRIMARY_FONT,"#3e240b");t.y=-a.height/2+50;t.textAlign="center";t.textBaseline="middle";t.lineWidth=400;t.outline=5;r.addChild(t);a=new createjs.Text(TEXT_SHOP," 50px "+PRIMARY_FONT,"#ffffff");a.y=t.y;a.textAlign="center";a.textBaseline="middle";a.lineWidth=400;r.addChild(a);f=parseInt(s_oLocalStorage.getItem(LOCALSTORAGE_COINS));g={value:f};h=new createjs.Text(TEXT_CURRENCY+g.value," 40px "+PRIMARY_FONT,"#3e240b");h.y=120;h.textAlign=
"center";h.textBaseline="middle";h.lineWidth=400;h.outline=5;r.addChild(h);e=new createjs.Text(TEXT_CURRENCY+g.value," 40px "+PRIMARY_FONT,"#ffffff");e.y=h.y;e.textAlign="center";e.textBaseline="middle";e.lineWidth=400;r.addChild(e);a=s_oSpriteLibrary.getSprite("but_continue_small");n=new CGfxButton(282,155,a,r);n.addEventListener(ON_MOUSE_UP,this._onExit,this);b=parseInt(s_oLocalStorage.getItem(LOCALSTORAGE_GEARPOWER_LEVEL));q=new CUpgradeButton(-210,-34,s_oSpriteLibrary.getSprite("upgrade_gear"),
r,[100,300,900]);q.addEventListener(ON_MOUSE_UP,this._onButGear,this);q.setUpgrade(b);c=parseInt(s_oLocalStorage.getItem(LOCALSTORAGE_SPEEDPOWER_LEVEL));p=new CUpgradeButton(-8,-30,s_oSpriteLibrary.getSprite("upgrade_speed"),r,[250,500,1E3]);p.addEventListener(ON_MOUSE_UP,this._onButSpeed,this);p.setUpgrade(c);p.setTextPos(8);p.setSegmentPos(8);k=parseInt(s_oLocalStorage.getItem(LOCALSTORAGE_NITROPOWER_LEVEL));l=new CUpgradeButton(210,-30,s_oSpriteLibrary.getSprite("upgrade_nitro"),r,[300,600,1200]);
l.addEventListener(ON_MOUSE_UP,this._onButNitro,this);l.setUpgrade(k);this._checkAvailability()};this._refreshCoins=function(){var a=g.value.toFixed(0);h.text=TEXT_CURRENCY+a;e.text=TEXT_CURRENCY+a};this._onButGear=function(){b++;s_oLocalStorage.setItem(LOCALSTORAGE_GEARPOWER_LEVEL,b);GEAR_START_AREA.greenangle=GEAR_START_GREEN_WIDTH[b];GEAR_IN_RACE_AREA.greenangle=GEAR_INRACE_GREEN_WIDTH[b];WRONG_GEAR_CHANGE_STALL_DURATION=WRONG_GEAR_DURATION_INFO[b];f-=q.getPrice();s_oLocalStorage.setItem(LOCALSTORAGE_COINS,
f);(new createjs.Tween.get(g,{override:!0})).to({value:f},2E3,createjs.Ease.cubicOut).addEventListener("change",this._refreshCoins);q.increaseUpgrade();this._checkAvailability()};this._onButSpeed=function(){c++;s_oLocalStorage.setItem(LOCALSTORAGE_SPEEDPOWER_LEVEL,c);PLAYER_ENGINE_GEAR=PLAYER_ENGINE_INFO[c];f-=p.getPrice();s_oLocalStorage.setItem(LOCALSTORAGE_COINS,f);(new createjs.Tween.get(g,{override:!0})).to({value:f},2E3,createjs.Ease.cubicOut).addEventListener("change",this._refreshCoins);p.increaseUpgrade();
this._checkAvailability()};this._onButNitro=function(){k++;s_oLocalStorage.setItem(LOCALSTORAGE_NITROPOWER_LEVEL,k);NITRO_DURATION=NITRO_INFO[k];f-=l.getPrice();s_oLocalStorage.setItem(LOCALSTORAGE_COINS,f);(new createjs.Tween.get(g,{override:!0})).to({value:f},2E3,createjs.Ease.cubicOut).addEventListener("change",this._refreshCoins);l.increaseUpgrade();this._checkAvailability()};this._checkAvailability=function(){f<q.getPrice()&&q.disable(!0);f<p.getPrice()&&p.disable(!0);f<l.getPrice()&&l.disable(!0)};
this._onExit=function(){q.setClickable(!1);p.setClickable(!1);l.setClickable(!1);n.setClickable(!1);(new createjs.Tween.get(m)).to({alpha:0},500);(new createjs.Tween.get(r)).to({y:d},400,createjs.Ease.backIn).call(function(){t.unload();a&&a()})};this.unload=function(){q.unload();p.unload();l.unload();n.unload();s_oStage.removeChild(m);s_oStage.removeChild(r);m.off("mousedown",function(){})};t=this;this._init(a)}
function CUpgradeButton(a,d,b,c,k){var f,g,e,h,n,q,p,l,m,r,t,u,y,w;this._init=function(a,b,c,d,k){f=!1;e=1;g=0;n=[];q=[];y=new createjs.Container;y.x=a;y.y=b;d.addChild(y);m=new createjs.Container;y.addChild(m);a=c.width/2;b=c.height;d=new createjs.SpriteSheet({images:[c],frames:{width:a,height:b,regX:a/2,regY:b/2},animations:{on:[0],off:[1]}});l=createSprite(d,"on",a/2,b/2,a,b);m.addChild(l);r=new createjs.Text(TEXT_CURRENCY+k[0]," 26px "+PRIMARY_FONT,"#3e240b");r.y=b/2-18;r.textAlign="center";r.textBaseline=
"middle";r.lineWidth=200;r.outline=4;m.addChild(r);t=new createjs.Text(TEXT_CURRENCY+k[0]," 26px "+PRIMARY_FONT,"#ffffff");t.y=r.y;t.textAlign="center";t.textBaseline="middle";t.lineWidth=200;m.addChild(t);w=new createjs.Container;m.addChild(w);h=c.width/k.length/2;p=[];a=[];for(b=0;b<k.length;b++)p[b]=new createjs.Shape,p[b].graphics.beginFill("rgba(0,0,0,1)").drawRect(0,0,h,c.height/8),p[b].x=-((h+5)*k.length/2)+b*(h+5),p[b].y=c.height/2+5,w.addChild(p[b]),a[b]=new createjs.Shape,a[b].graphics.beginStroke("rgba(255,224,0,1)").drawRect(0,
0,h,c.height/8),a[b].x=-((h+5)*k.length/2)+b*(h+5),a[b].y=c.height/2+5,w.addChild(a[b]);this._initListener()};this.unload=function(){this.removeListener();c.removeChild(m)};this.setVisible=function(a){m.visible=a};this.disable=function(a){(f=a)?l.gotoAndStop("off"):l.gotoAndStop("on")};this.setClickable=function(a){f=!a};this._initListener=function(){if(s_bMobile)m.on("mousedown",this.buttonDown);else m.on("mousedown",this.buttonDown),m.on("mouseover",this.buttonOver);m.on("pressup",this.buttonRelease)};
this.removeListener=function(){s_bMobile?m.off("mousedown",this.buttonDown):(m.off("mousedown",this.buttonDown),m.off("mouseover",this.buttonOver));m.off("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){n[a]=b;q[a]=c};this.increaseUpgrade=function(){p[g].graphics.beginFill("rgba(255,255,255,1)").drawRect(0,0,h,b.height/8);g++;g===k.length?(this.disable(!0),g--,r.text="",t.text=""):this.setPrice(k[g])};this.setUpgrade=function(a){for(var b=0;b<a;b++)this.increaseUpgrade()};this.setPrice=
function(a){r.text=TEXT_CURRENCY+a;t.text=TEXT_CURRENCY+a};this.getPrice=function(){return k[g]};this.buttonRelease=function(){f||(m.scaleX=e,m.scaleY=e,n[ON_MOUSE_UP]&&n[ON_MOUSE_UP].call(q[ON_MOUSE_UP]))};this.buttonDown=function(){f||(m.scaleX=.9*e,m.scaleY=.9*e,playSound("upgrade_car",1,0),n[ON_MOUSE_DOWN]&&n[ON_MOUSE_DOWN].call(q[ON_MOUSE_DOWN]))};this.buttonOver=function(a){s_bMobile||f||(a.target.cursor="pointer")};this.pulseAnimation=function(){createjs.Tween.get(m).to({scaleX:.9*e,scaleY:.9*
e},850,createjs.Ease.quadOut).to({scaleX:e,scaleY:e},650,createjs.Ease.quadIn).call(function(){u.pulseAnimation()})};this.trembleAnimation=function(){createjs.Tween.get(m).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){u.trebleAnimation()})};this.setTextPos=function(a,b){a&&(r.x=a,t.x=a);b&&(r.y=b,t.y=b)};this.setSegmentPos=function(a,b){a&&(w.x=a);b&&(w.y=b)};this.setPosition=function(a,b){m.x=
a;m.y=b};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};u=this;this._init(a,d,b,c,k);return this}
function CHUD(a){var d,b,c,k,f,g,e,h,n,q,p,l,m,r;this._init=function(a){k=STATE_HUD_UPDATE;g=0;d=HUD_RPM_INTERVAL[0].min;b=HUD_RPM_INTERVAL[0].max;e=new createjs.Container;a.addChild(e);a=s_oSpriteLibrary.getSprite("tachometer");var c=createBitmap(a);c.regX=a.width/2;c.regY=a.height/2;e.addChild(c);l=new createjs.Text("0 "+TEXT_KMH," 24px "+PRIMARY_FONT,"#749fc3");l.textAlign="center";l.textBaseline="alphabetic";l.lineWidth=300;l.outline=3;l.y=10;e.addChild(l);n=new createjs.Text("0 "+TEXT_KMH," 24px "+
PRIMARY_FONT,"#ffffff");n.textAlign="center";n.textBaseline="alphabetic";n.lineWidth=300;n.y=10;e.addChild(n);q=new CGearAreaView(41,e);a=s_oSpriteLibrary.getSprite("indicator");h=createBitmap(a);h.regX=a.width/2;h.regY=122;h.y=41;h.rotation=d;e.addChild(h);a=s_oSpriteLibrary.getSprite("but_nitro");p=new CGfxButton(-250,200,a,e);p.addEventListener(ON_MOUSE_DOWN,this._onNitro,this);p.setVisible(!1);a=s_oSpriteLibrary.getSprite("accelerator");r=new CGfxButton(250,0,a,e);r.addEventListener(ON_MOUSE_DOWN,
this.accelerate,this);r.addEventListener(ON_MOUSE_UP,this.decelerate,this);a=s_oSpriteLibrary.getSprite("but_gear");m=new CGearButton(250,200,a,e);m.addEventListener(ON_MOUSE_DOWN,this._onGear,this);m.setVisible(!1)};this.unload=function(){s_oHUD=null;a.removeChild(e);p&&p.unload();m&&m.unload();r&&r.unload()};this.setGearArea=function(a,b){q.setAreas(b);q.moveAreas(a)};this.setPos=function(a,b){e.x=a;e.y=b};this._refreshSpeed=function(a){a=Math.round(a);n.text=a+" "+TEXT_KMH;l.text=a+" "+TEXT_KMH};
this._refreshIndicator=function(a,c){Math.round(a)===PLAYER_ENGINE_GEAR[c].speed?k=STATE_HUD_STALL:(new createjs.Tween.removeTweens(h),h.rotation=(a-g)/(PLAYER_ENGINE_GEAR[c].speed-g)*(b-d)+d)};this.updateTachometer=function(a,b){this._refreshSpeed(a);switch(k){case STATE_HUD_UPDATE:this._refreshIndicator(a,b);break;case STATE_HUD_STALL:this.stallAnim();break;case STATE_HUD_REPOSITIONING:this.downShiftGear()}};this.stallAnim=function(){k=STATE_HUD_NULL;(new createjs.Tween.get(h,{loop:!0,override:!0})).to({rotation:h.rotation+
.5},50).to({rotation:h.rotation},50).to({rotation:h.rotation-.5},50).to({rotation:h.rotation},50)};this.downShiftGear=function(a,c,e){k=STATE_HUD_NULL;d=HUD_RPM_INTERVAL[a].min;b=HUD_RPM_INTERVAL[a].max;(new createjs.Tween.get(h,{override:!0})).to({rotation:d},HUD_DOWNSHIFT_GEAR_DURATION,createjs.Ease.cubicOut).call(function(){g=s_oGame.getPlayerMeterSpeed();k=c;c===STATE_HUD_STALL&&setTimeout(function(){g=s_oGame.getPlayerMeterSpeed();k=STATE_HUD_UPDATE},e)})};this.startAccelerate=function(a){c=
a;f=0};this.updateIndicatorForStartBattle=function(){c?(f+=.1,h.rotation+=START_ACCELERATION_INDICATOR_SPEED+f,h.rotation>HUD_RPM_INTERVAL[0].max&&(f=0,(new createjs.Tween.get(h,{loop:!0})).to({rotation:b+3},50).to({rotation:b},50).to({rotation:b-3},50).to({rotation:b},50))):(new createjs.Tween.removeTweens(h),f=(h.rotation-HUD_RPM_INTERVAL[0].min)/(HUD_RPM_INTERVAL[0].max-HUD_RPM_INTERVAL[0].min)*(-START_ACCELERATION_INDICATOR_SPEED+.1)+START_ACCELERATION_INDICATOR_SPEED-.1,h.rotation-=START_ACCELERATION_INDICATOR_SPEED-
f,h.rotation<HUD_RPM_INTERVAL[0].min&&(h.rotation=HUD_RPM_INTERVAL[0].min))};this.getIndicatorResult=function(){return q.getIndicatorResult(h.rotation)};this._onNitro=function(){this.nitroButtonVisible(!1);s_oGame.shotNitro()};this._onGear=function(){s_oGame.changeGear()};this.scaleGear=function(){m.scaleGear()};this.gearButtonVisible=function(a){a?(m.setVisible(a),(new createjs.Tween(m.getButtonImage())).to({y:-30},500,createjs.Ease.cubicOut)):(m.setClickable(!1),(new createjs.Tween(m.getButtonImage())).to({y:200},
500,createjs.Ease.cubicOut))};this.accelerate=function(){s_oGame.startAcceleration(!0)};this.decelerate=function(){s_oGame.startAcceleration(!1)};this.acceleratorButtonVisible=function(a){a||(r.setClickable(!1),(new createjs.Tween(r.getButtonImage())).to({y:300},500,createjs.Ease.cubicOut))};this.nitroButtonVisible=function(a){a?(p.setVisible(a),(new createjs.Tween(p.getButtonImage())).to({y:-30},500,createjs.Ease.cubicOut)):(p.setClickable(!1),(new createjs.Tween(p.getButtonImage())).to({y:200},
500,createjs.Ease.cubicOut))};this.getContainer=function(){return e};this._init(a);s_oHUD=this}var s_oHUD;
function CGearAreaView(a,d){var b,c,k,f,g,e,h,n,q,p,l,m;this._init=function(a,b){g=200;m=new createjs.Container;m.x=0;m.y=a;b.addChild(m);this._setGreenSpot();this._setBlueSpot();this._setRedSpot()};this._setGreenSpot=function(){e=new createjs.Shape;e.graphics.rf(["rgba(0,255,0,0.01)","rgba(0,255,0,0.4)"],[0,1],0,0,60,0,0,126).drawCircle(0,0,126);m.addChild(e);h=new createjs.Shape;h.graphics.beginFill("rgba(255,255,255,0.01)");m.addChild(h)};this._setBlueSpot=function(){n=new createjs.Shape;n.graphics.rf(["rgba(0,0,255,0.01)",
"rgba(0,0,255,0.4)"],[0,1],0,0,60,0,0,126).drawCircle(0,0,126);m.addChild(n);q=new createjs.Shape;q.graphics.beginFill("rgba(255,255,255,0.01)");m.addChild(q)};this._setRedSpot=function(){p=new createjs.Shape;p.graphics.rf(["rgba(255,0,0,0.01)","rgba(255,0,0,0.4)"],[0,1],0,0,60,0,0,126).drawCircle(0,0,126);m.addChild(p);l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)");m.addChild(l)};this.setAreas=function(a){b=0;c=a.greenangle;k=a.earlyangle;f=a.lateangle;var d=a.greenangle/2*Math.PI/
180,d=g*Math.tan(d);h.graphics.beginFill("rgba(255,255,255,0.001)");h.graphics.moveTo(0,0);h.graphics.lineTo(-d,-g);h.graphics.lineTo(d,-g);h.graphics.lineTo(0,0);e.mask=h;d=a.earlyangle/2*Math.PI/180;d=g*Math.tan(d);q.graphics.beginFill("rgba(255,255,255,0.001)");q.graphics.moveTo(0,0);q.graphics.lineTo(-d,-g);q.graphics.lineTo(d,-g);q.graphics.lineTo(0,0);q.rotation=-(a.earlyangle/2+a.greenangle/2);n.mask=q;d=a.lateangle/2*Math.PI/180;d=g*Math.tan(d);l.graphics.beginFill("rgba(255,255,255,0.001)");
l.graphics.moveTo(0,0);l.graphics.lineTo(-d,-g);l.graphics.lineTo(d,-g);l.graphics.lineTo(0,0);l.rotation=a.lateangle/2+a.greenangle/2;p.mask=l};this.moveAreas=function(a){b=a;(new createjs.Tween.get(m)).to({rotation:a},1E3,createjs.Ease.cubicOut)};this.getIndicatorResult=function(a){return a<b+c/2&&a>b-c/2?GREEN_AREA:a>b+c/2&&a<b+c/2+f?LATE_AREA:a<b-c/2&&a>b-c/2-k?EARLY_AREA:NULL_AREA};this._init(a,d)}
function CBackground(a){var d,b,c,k,f,g,e,h;this._init=function(a){f=k=0;g=1;h=new createjs.Container;h.y=-150;a.addChild(h);c=0;d=2;e=[];a=s_oSpriteLibrary.getSprite("bg_game");b=a.width;for(var n=0;n<d;n++)e[n]=createBitmap(a),e[n].x=n*b,h.addChild(e[n]),c+=b};this._swapBgPiece=function(){g++;e[f].x=c;c+=b;f++;f===d&&(f=0)};this.move=function(a){k+=a;h.x=-k;k>=b*g&&this._swapBgPiece()};this._init(a)}
function CStreet(a,d,b){var c,k,f,g,e,h,n,q,p,l,m,r,t,u,y,w,v,z,B,x,A,C;this._init=function(a,b,d){k=c=!1;n=h=e=0;t=r=m=1;B=new createjs.Container;B.y=110;b.addChild(B);x=new createjs.Container;x.y=290;b.addChild(x);A=new createjs.Container;A.y=CANVAS_HEIGHT;d.addChild(A);f=2;q=0;u=[];a=s_oSpriteLibrary.getSprite("parallaxe_1");g=a.width;for(b=0;b<f;b++)u[b]=createBitmap(a),u[b].x=b*g,B.addChild(u[b]),q+=g;p=0;y=[];a=s_oSpriteLibrary.getSprite("street_piece");g=a.width;for(b=0;b<f;b++)y[b]=createBitmap(a),
y[b].x=b*g,x.addChild(y[b]),p+=g;a=s_oSpriteLibrary.getSprite("arrive");v=createBitmap(a);v.y=62;x.addChild(v);a=s_oSpriteLibrary.getSprite("lamp");z=createBitmap(a);LAMP_WIDTH=a.width;z.x=880;z.y=-180;x.addChild(z);a=s_oSpriteLibrary.getSprite("lamp");C=createBitmap(a);C.x=1200;C.y=-540;C.scaleX=C.scaleY=1.5;A.addChild(C);l=0;w=[];a=s_oSpriteLibrary.getSprite("parallaxe_2");for(b=0;b<f;b++)w[b]=createBitmap(a),w[b].x=b*g,w[b].regY=a.height,A.addChild(w[b]),l+=g};this.setArrive=function(a){v.x=a*
METER_TO_PIXEL_RATIO};this._swapBgPiece=function(){m++;u[m%f].x=q;q+=g};this._swapRoadPiece=function(){r++;y[r%f].x=p;0===r%8&&(z.x=p+LAMP_OFFSET,k=!1);p+=g};this._swapFgPiece=function(){t++;w[t%f].x=l;0===t%5&&(C.x=l+LAMP_OFFSET,c=!1);l+=g};this.move=function(a,b,c){e+=a*PARALLAX_1_RATIO;B.x=-e;e>=g*m&&this._swapBgPiece();h+=a;x.x=-h;h>=g*r&&this._swapRoadPiece();n+=a*PARALLAX_2_RATIO;A.x=-n;n>=g*t&&this._swapFgPiece();this._checkHighlighting(b,c)};this.menuMovement=function(a){e+=a*PARALLAX_1_RATIO;
B.x=-e;e>=g*m&&this._swapBgPiece();h+=a;x.x=-h;h>=g*r&&this._swapRoadPiece();n+=a*PARALLAX_2_RATIO;A.x=-n;n>=g*t&&this._swapFgPiece()};this._checkHighlighting=function(a,b){A.x+C.x<START_LINE_X&&!c&&(c=!0,s_oGame.playerHighlight());z.x<b&&!k&&(k=!0,s_oGame.opponentHighlight())};this.getMeterCovered=function(){return pixelsToMeters(h)};this._init(a,d,b)}
var WHEEL_POS=[[{x:108,y:-22},{x:-122,y:-22}],[{x:104,y:-24},{x:-98,y:-24}],[{x:108,y:-18},{x:-124,y:-20}],[{x:114,y:-20},{x:-114,y:-20}],[{x:113,y:-14},{x:-118,y:-14}],[{x:98,y:-22},{x:-108,y:-22}],[{x:114,y:-18},{x:-124,y:-18}],[{x:117,y:-20},{x:-106,y:-22}],[{x:101,y:-20},{x:-131,y:-20}],[{x:114,y:-20},{x:-120,y:-24}],[{x:100,y:-20},{x:-126,y:-24}]],SHADOW_POS=[-7,-2,-12,-8,-16,-8,-12,-10,-10,-8,-8],PLAYER_ENGINE_INFO=[],PLAYER_ENGINE_GEAR=PLAYER_ENGINE_INFO[0],OPPONENT_ENGINE_GEAR=[],SKILL=[];
function CCar(a,d,b,c,k,f,g){var e,h,n,q,p,l,m,r,t,u,y,w,v;this._init=function(a,b,c,d,g,f,k){e=!1;h=g;q=0;m=new createjs.Container;n=a;m.x=a;m.y=b;c.addChild(m);c=s_oSpriteLibrary.getSprite("fireline");a=c.width/2;b=c.height/30;c={images:[c],framerate:30,frames:{width:a,height:b,regX:a,regY:b},animations:{play:[0,59,"stop"],stop:[60,60]}};c=new createjs.SpriteSheet(c);w=createSprite(c,"stop",a/2,b/2,a,b);w.x=WHEEL_POS[d][1].x;w.y=WHEEL_POS[d][1].y+36;m.addChild(w);c=s_oSpriteLibrary.getSprite("car_"+
d);p=8;a=c.width/4;b=c.height/2;c={images:[c],framerate:30,frames:{width:a,height:b,regX:a/2,regY:b},animations:{"static":[0],highlight:[1,7,"static"]}};c=new createjs.SpriteSheet(c);r=createSprite(c,"static",a/2,b/2,a,b);m.addChild(r);c=s_oSpriteLibrary.getSprite("shadow_"+d);b=createBitmap(c);b.regY=c.height/2+SHADOW_POS[d];b.regX=a/2;m.addChild(b);l=[];c=s_oSpriteLibrary.getSprite("wheel_"+d);l[0]=createBitmap(c);l[0].regX=c.width/2;l[0].regY=c.height/2;l[0].x=WHEEL_POS[d][0].x;l[0].y=WHEEL_POS[d][0].y;
l[0].rotation=360*Math.random();m.addChild(l[0]);l[1]=createBitmap(c);l[1].regX=c.width/2;l[1].regY=c.height/2;l[1].x=WHEEL_POS[d][1].x;l[1].y=WHEEL_POS[d][1].y;l[1].rotation=360*Math.random();m.addChild(l[1]);c=s_oSpriteLibrary.getSprite("firewheel");a=c.width/7;b=c.height/2;c={images:[c],framerate:60,frames:{width:a,height:b,regX:a/2,regY:b/2},animations:{play:[0,12,"play"],stop:[13,13]}};c=new createjs.SpriteSheet(c);u=createSprite(c,"stop",a/2,b/2,a,b);u.x=WHEEL_POS[d][1].x;u.y=WHEEL_POS[d][1].y-
3;m.addChild(u);y=createSprite(c,"stop",a/2,b/2,a,b);y.x=WHEEL_POS[d][0].x;y.y=WHEEL_POS[d][0].y-3;m.addChild(y);c=s_oSpriteLibrary.getSprite("smoke");a=c.width/5;b=c.height/10;c={images:[c],framerate:30,frames:{width:a,height:b,regX:a/2,regY:b/2},animations:{play:[0,49,"stop"],stop:[50]}};c=new createjs.SpriteSheet(c);v=createSprite(c,"stop",a/2,b/2,a,b);v.x=WHEEL_POS[d][1].x-90;v.y=WHEEL_POS[d][1].y-30;m.addChild(v);t=new CEngine(this,f)};this.unload=function(){b.removeChild(m)};this.getCar=function(){return m};
this.getWheels=function(){return{right:l[0],left:l[1]}};this.getType=function(){return c};this.setScale=function(a){m.scaleX=m.scaleY=a};this.setSpeed=function(a){q=a};this.getSpeed=function(){return q};this.getMeterSpeed=function(){return t.getMeterSpeed()};this.getMaxSpeedPerGearReached=function(){return t.getMaxSpeedPerGearReached()};this.getMeterPos=function(){return pixelsToMeters(n)};this.getPixelPos=function(){return n};this.getGear=function(){return t.getGear()};this.ignition=function(){v.gotoAndPlay("play");
t.start();this.changeGear()};this.stopSound=function(){t.stopSound()};this.highlight=function(){r.framerate=p/(LAMP_WIDTH/q/FPS);r.gotoAndPlay("highlight")};this.pitchStartAnim=function(){playSound("acceleration",1,0);(new createjs.Tween.get(r,{override:!0})).to({rotation:.5},100).to({rotation:0},750);(new createjs.Tween.get(m,{override:!0})).to({x:a+1},100).to({x:a},750)};this.changeGear=function(){0!==t.getGear()&&t.getGear()<f.length-1&&!e&&(new createjs.Tween.get(r,{override:!0})).to({rotation:.5},
100,createjs.Ease.cubicOut).to({rotation:0},750,createjs.Ease.cubicIn);t.changeGear()};this.delayEngine=function(a){t.delayAcceleration(a)};this.activateNitro=function(a){0<a&&(u.gotoAndPlay("play"),y.gotoAndPlay("play"),w.gotoAndPlay("play"),(new createjs.Tween.get(u)).wait(a/2).to({alpha:0},a/2,createjs.Ease.cubicIn),(new createjs.Tween.get(y)).wait(a/2).to({alpha:0},a/2,createjs.Ease.cubicIn),e=!0,t.activateNitro(!0));setTimeout(function(){t.fadeNitroSound(a/2)},a/2-400);(new createjs.Tween.get(r)).to({rotation:-2},
400,createjs.Ease.cubicOut).wait(a/2-400).to({rotation:0},a/2,createjs.Ease.cubicIn).call(function(){e=!1;t.activateNitro(!1)})};this["break"]=function(){t["break"]()};this.move=function(a){n+=q;t.update();for(var b=0;2>b;b++)l[b].rotation=1>q?l[b].rotation+(20-20*q):l[b].rotation+q;h||(m.x+=q-a)};this._init(a,d,b,c,k,f,g)}
function CEngine(a,d){var b,c,k,f,g,e,h,n,q,p,l,m,r,t,u;this._init=function(a,d){k=c=b=!1;e=STATE_ENGINE_UPDATE;l=1;f=0;n=h=1;q=GEAR_N;u="gear_player"};this.start=function(){b=!0};this.activateNitro=function(a){if(a){if(l=ENGINE_NITRO_RPM_ACCELERATION,!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r=s_aSounds.fire_wheel.play(),t=s_aSounds.nitro.play()}else l=ENGINE_NORMAL_RPM_ACCELERATION};this.changeGear=function(){q<d.length-1&&(q++,k=!1,h=n,f=0,g=milliSecondsToFrames(d[q].time))};this["break"]=function(){e=
STATE_ENGINE_BREAK;h=n;f=0;g=milliSecondsToFrames(BREAK_DURATION)};this.delayAcceleration=function(a){e=STATE_ENGINE_STALL;h=n;f=0;g=milliSecondsToFrames(a);p=h};this.stall=function(){0===f&&0===a.getType()&&this.setStallSound();f++;if(f>g)h=n,f=0,g=milliSecondsToFrames(d[q].time),e=STATE_ENGINE_UPDATE;else{var b=s_oTweenController.easeInSine(f,0,1,g);n=s_oTweenController.tweenValue(h,p,b);this._setSpeed()}};this.decelerate=function(){f+=l;if(!(f>g)){var a=s_oTweenController.easeInSine(f,0,1,g);n=
s_oTweenController.tweenValue(h,0,a);this._setSpeed()}};this.rotate=function(){0===f&&0===a.getType()&&this._setEngineSound();f+=l;if(f>g)k=!0,c||0!==a.getType()||this.setStallSound();else{var b=s_oTweenController.easeInSine(f,0,1,g);n=s_oTweenController.tweenValue(h,d[q].speed,b);this._setSpeed()}};this._setEngineSound=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_aSounds[u].stop(),s_aSounds.stall.stop(),m=6E3/PLAYER_ENGINE_GEAR[q].time.toFixed(1),4<m&&(m=4),.5>m&&(m=.5),s_aSounds[u].play(),
s_aSounds[u].rate(m)};this.stopSound=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c=!0,s_aSounds[u].stop(),s_aSounds.stall.stop(),s_aSounds.fire_wheel.stop(),s_aSounds.nitro.stop()};this.setStallSound=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_aSounds.stall.stop(),s_aSounds.stall.play()};this.stopStallSound=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds.stall.stop()};this.fadeNitroSound=function(a){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_aSounds.fire_wheel.fade(1,
0,a,r),s_aSounds.nitro.fade(1,0,a,t)};this.update=function(){if(b)switch(e){case STATE_ENGINE_UPDATE:this.rotate();break;case STATE_ENGINE_STALL:this.stall();break;case STATE_ENGINE_BREAK:this.decelerate()}};this.getMeterSpeed=function(){return n};this._setSpeed=function(){var b=kMetersHToPixelsF(n);a.setSpeed(b)};this.getGear=function(){return q};this.getMaxSpeedPerGearReached=function(){return k};this._init(a,d)}
function CAI(a,d){var b,c,k,f;this._init=function(a,d){b=!1;a.getType();c=a.getGear();k=400+500*Math.random();f=(SKILL[d].normalizednitroshottime-.05+.1*Math.random())*STAGE_METER_LENGTH[d];0>f&&(f=0)};this.update=function(g,e){switch(g){case STATE_START_BATTLE:k-=s_iTimeElaps;0>k&&(k=400+500*Math.random(),a.pitchStartAnim());break;case STATE_RACE_RUN:e>f&&!b&&(b=!0,a.activateNitro(SKILL[d].nitroduration)),a.getMaxSpeedPerGearReached()&&c<OPPONENT_ENGINE_GEAR[d].length-1&&(a.changeGear(),c=a.getGear(),
Math.random()<SKILL[d].wronggearchangeratio&&a.delayEngine(SKILL[d].wrongearduration))}};this._init(a,d)}
function CGearButton(a,d,b,c){var k,f,g,e,h,n,q,p,l;this._init=function(a,b,c,d){k=!1;f=1;e=[];h=[];q=new createjs.Container;q.x=a;q.y=b;q.scaleX=q.scaleY=f;d.addChild(q);a=createBitmap(c);a.regX=c.width/2;a.regY=c.height/2;q.addChild(a);g=0;n=[];c=-20;for(a=1;a<PLAYER_ENGINE_GEAR.length;a++)n[a]=new createjs.Text(a," 18px "+PRIMARY_FONT,"#000000"),n[a].x=c,0===a%2?(n[a].y=32,c+=20):n[a].y=-32,n[a].textAlign="center",n[a].textBaseline="middle",n[a].lineWidth=200,q.addChild(n[a]);c=s_oSpriteLibrary.getSprite("gear_handle");
l=createBitmap(c);l.regX=c.width/2;l.regY=c.height/2;q.addChild(l);this._initListener()};this.unload=function(){s_bMobile?q.off("mousedown",this.buttonDown):(q.off("mousedown",this.buttonDown),q.off("mouseover",this.buttonOver));q.off("pressup",this.buttonRelease);c.removeChild(q)};this.setVisible=function(a){q.visible=a};this.setClickable=function(a){k=!a};this._initListener=function(){if(s_bMobile)q.on("mousedown",this.buttonDown);else q.on("mousedown",this.buttonDown),q.on("mouseover",this.buttonOver);
q.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){e[a]=b;h[a]=c};this.buttonRelease=function(){k||e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(h[ON_MOUSE_UP])};this.buttonDown=function(){k||e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.buttonOver=function(a){s_bMobile||k||(a.target.cursor="pointer")};this.pulseAnimation=function(){createjs.Tween.get(q).to({scaleX:.9*f,scaleY:.9*f},850,createjs.Ease.quadOut).to({scaleX:f,scaleY:f},650,createjs.Ease.quadIn).call(function(){p.pulseAnimation()})};
this.trembleAnimation=function(){createjs.Tween.get(q).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){p.trebleAnimation()})};this.setPosition=function(a,b){q.x=a;q.y=b};this.setX=function(a){q.x=a};this.setY=function(a){q.y=a};this.getButtonImage=function(){return q};this.getX=function(){return q.x};this.getY=function(){return q.y};this.scaleGear=function(){g++;g>=PLAYER_ENGINE_GEAR.length&&(g=
PLAYER_ENGINE_GEAR.length-1);for(var a=1;a<PLAYER_ENGINE_GEAR.length;a++)n[a].color="#000000";(new createjs.Tween.get(q)).to({scaleX:.9,scaleY:.9},200,createjs.Ease.cubicOut).to({scaleX:1,scaleY:1},200,createjs.Ease.cubicIn);playSound("change_gear",1,0);switch(g){case 1:(new createjs.Tween.get(l,{override:!0})).to({x:-20},200,createjs.Ease.cubicOut).wait(100).to({y:-18},200,createjs.Ease.cubicOut).call(function(){n[g].color="#ffffff"});break;case 3:(new createjs.Tween.get(l,{override:!0})).to({y:0},
100,createjs.Ease.cubicOut).wait(100).to({x:0},100,createjs.Ease.cubicOut).wait(100).to({y:-18},100,createjs.Ease.cubicOut).call(function(){n[g].color="#ffffff"});break;case 5:(new createjs.Tween.get(l,{override:!0})).to({y:0},100,createjs.Ease.cubicOut).wait(100).to({x:20},100,createjs.Ease.cubicOut).wait(100).to({y:-18},100,createjs.Ease.cubicOut).call(function(){n[g].color="#ffffff"});break;default:(new createjs.Tween.get(l,{override:!0})).to({y:0},200,createjs.Ease.cubicOut).wait(100).to({y:16},
200,createjs.Ease.cubicOut).call(function(){n[g].color="#ffffff"})}};p=this;this._init(a,d,b,c);return this}
function CTremble(a,d,b,c){var k,f,g,e,h,n,q,p;this._init=function(a,b,c,d){e=g=!1;n=0;this._calculateDuration();k=a.x;f=a.y;g||(g=!0,h=setInterval(function(){p._tremble()},c))};this._tremble=function(){if(e=!e){var l;l=.5>Math.random()?-c:c;var m;m=.5>Math.random()?-c:c;a.x+=l;a.y+=m}else a.x=k,a.y=f;n++;n>q&&(n=0,g=!1,0===d?h=setInterval(function(){p._tremble()},b):clearInterval(h))};this._calculateDuration=function(){q=d/b};this.stopTremble=function(){clearInterval(h)};p=this;this._init(a,d,b,
c)}
function CScoreText(a,d,b,c){var k;this._init=function(a,b,d){k=new createjs.Text("00000","bold 30px "+PRIMARY_FONT,"#ffffff");k.textAlign="center";k.textBaseline="middle";k.text=a;k.x=b;k.y=d;k.alpha=0;k.shadow=new createjs.Shadow("#3e240b",2,2,2);c.addChild(k);var e=this;createjs.Tween.get(k).to({alpha:1},400,createjs.Ease.quadIn).call(function(){e.moveUp()})};this.moveUp=function(){var a=k.y-100,b=this;createjs.Tween.get(k).to({alpha:0},1E3);createjs.Tween.get(k).to({y:a},1E3,createjs.Ease.sineIn).call(function(){b.unload()})};this.unload=
function(){c.removeChild(k)};this._init(a,d,b)};
