function CVector2(a,c){var b,d;this._init=function(a,c){b=a;d=c};this.add=function(a,c){b+=a;d+=c};this.addV=function(a){b+=a.getX();d+=a.getY()};this.scalarDivision=function(a){b/=a;d/=a};this.subV=function(a){b-=a.getX();d-=a.getY()};this.scalarProduct=function(a){b*=a;d*=a};this.invert=function(){b*=-1;d*=-1};this.dotProduct=function(a){return b*a.getX()+d*a.getY()};this.set=function(a,c){b=a;d=c};this.setV=function(a){b=a.getX();d=a.getY()};this.length=function(){return Math.sqrt(b*b+d*d)};this.length2=
function(){return b*b+d*d};this.normalize=function(){var a=this.length();0<a&&(b/=a,d/=a)};this.getNormalize=function(a){this.length();a.set(b,d);a.normalize()};this.rot90CCW=function(){var a=b;b=-d;d=a};this.rot90CW=function(){var a=b;b=d;d=-a};this.getRotCCW=function(a){a.set(b,d);a.rot90CCW()};this.getRotCW=function(a){a.set(b,d);a.rot90CW()};this.ceil=function(){b=Math.ceil(b);d=Math.ceil(d)};this.round=function(){b=Math.round(b);d=Math.round(d)};this.toString=function(){return"Vector2: "+b+", "+
d};this.print=function(){trace("Vector2: "+b+", "+d+"")};this.getX=function(){return b};this.getY=function(){return d};this._init(a,c)}
function CCollisionRectangle(a,c,b,d,e,f){var g;this.init=function(){g=new CRectangle;var h=[];h.push(new createjs.Point(c,b));h.push(new createjs.Point(-d+2,-e+3));h.push(new createjs.Point(a.width-d-2,-e+3));h.push(new createjs.Point(a.width-d-2,a.height-e-3));h.push(new createjs.Point(-d+2,a.height-e-3));g.prepareBox(h);g.addAngle(f)};this.move=function(a,b){g.move(a,b)};this.applySteering=function(a){g.addAngle(a)};this.getBox=function(){return g};this.refresh=function(a,b){var c=g.getNorm(),
d=a.getNorm(),k=this.prepareVector(g),e=this.getMinMax(k,c[1]),f=this.getMinMax(b,c[1]),h=this.getMinMax(k,c[0]),r=this.getMinMax(b,c[0]),c=this.getMinMax(k,d[1]),A=this.getMinMax(b,d[1]),k=this.getMinMax(k,d[0]),d=this.getMinMax(b,d[0]),h=h.max_proj<r.min_proj||r.max_proj<h.min_proj,c=c.max_proj<A.min_proj||A.max_proj<c.min_proj,A=k.max_proj<d.min_proj||d.max_proj<k.min_proj;return e.max_proj<f.min_proj||f.max_proj<e.min_proj||h||c||A};this.prepareVector=function(a){for(var b=[],c=0;5>c;c++){var d=
a.getDot(c);b.push(new CVector2(d.x,d.y))}return b};this.getMinMax=function(a,b){for(var c=a[1].dotProduct(b),d=a[1].dotProduct(b),k=2;k<a.length;k++){var e=a[k].dotProduct(b);c>e&&(c=e);e>d&&(d=e)}return{min_proj:c,max_proj:d}};this.init()}
function CRectangle(){var a;this.init=function(){a=[]};this.prepareBox=function(c){a.push(new createjs.Shape);a[0].graphics.beginFill("#ff0000").drawCircle(0,0,10);a[0].x=c[0].x;a[0].y=c[0].y;for(var b=1;b<c.length;b++)a.push(new createjs.Shape),a[b].graphics.beginFill("#ff0000").drawCircle(0,0,5),a[b].x=c[0].x+c[b].x,a[b].y=c[0].y+c[b].y};this.addAngle=function(c){var b=Math.cos(c*Math.PI/180);c=Math.sin(c*Math.PI/180);for(var d=1;d<a.length;d++){var e=a[d].x-a[0].x,f=a[d].y-a[0].y;a[d].x=e*b-f*
c;a[d].y=e*c+f*b;a[d].x+=a[0].x;a[d].y+=a[0].y}this.drawBox()};this.move=function(c,b){for(var d=0;d<a.length;d++)a[d].x+=c,a[d].y+=b};this.getDot=function(c){return{x:a[c].x,y:a[c].y}};this.drawBox=function(){for(var c=0;c<a.length;c++)a[c].alpha=.5,a[c].fillColor=0};this.getNorm=function(){for(var c=[],b=1;b<a.length-1;b++){var d=new CVector2(a[b+1].x-a[b].x,a[b+1].y-a[b].y);c.push(d)}b=new CVector2(a[1].x-a[a.length-1].x,a[1].y-a[a.length-1].y);c.push(b);return c};this.init()}
function toRadian(a){return Math.PI/180*a}function toDegree(a){return 180/Math.PI*a}function randRange(a,c){return Math.floor(Math.random()*(c-a+1))+a}function angleBetweenVectors(a,c){var b=Math.acos(dotProductV2(a,c)/(a.length()*c.length()));return!0===isNaN(b)?0:b}function rotateVector2D(a,c){var b=c.getX()*Math.cos(a)+c.getY()*Math.sin(a),d=c.getX()*-Math.sin(a)+c.getY()*Math.cos(a);c.set(b,d)}
function reflectVectorV2(a,c){var b=new CVector2,d=dotProductV2(a,c);b.set(a.getX()-2*d*c.getX(),a.getY()-2*d*c.getY());return b}function dotProductV2(a,c){return a.getX()*c.getX()+a.getY()*c.getY()}function pointInRect(a,c){return a.getX()>c.x&&a.getX()<c.x+c.width&&a.getY()>c.y&&a.getY()<c.y+c.height}function distance2(a,c){return(c.getX()-a.getX())*(c.getX()-a.getX())+(c.getY()-a.getY())*(c.getY()-a.getY())}var s_iOffsetX=0,s_iOffsetY=0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);function trace(a){console.log(a)}$(window).resize(function(){sizeHandler()});function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function playSound(a,c,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:c}):null}
function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}function setVolume(a,c){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=c}function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(c)}function isTablet(){var a=navigator.userAgent.toLowerCase();return-1!==a.indexOf("ipad")?!0:-1<a.indexOf("android")&&-1===a.indexOf("mobile")?!0:!1}
function getSize(a){var c=a.toLowerCase(),b=window.document,d=b.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var e=b.createElement("body");e.id="vpw-test-b";e.style.cssText="overflow:scroll";var f=b.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+c+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";e.appendChild(f);d.insertBefore(e,b.head);
a=7==f["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(e)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width");_checkOrientation(c,a);var b=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),d=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,e;b<a?(e=a-b,b+=e,d+=CANVAS_WIDTH/CANVAS_HEIGHT*e):d<c&&(e=c-d,d+=e,b+=CANVAS_HEIGHT/CANVAS_WIDTH*e);e=a/2-b/2;var f=c/2-d/2,g=CANVAS_WIDTH/d;if(f*g<-EDGEBOARD_X||e*g<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),
c/(CANVAS_WIDTH-2*EDGEBOARD_X)),d=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,e=(a-b)/2,f=(c-d)/2,g=CANVAS_WIDTH/d;s_iOffsetX=-1*f*g;s_iOffsetY=-1*e*g;0<=e&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile&&!s_bIsIphone?($("#canvas").css("width",d+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=d,s_oStage.canvas.height=b,s_oStage.scaleX=s_oStage.scaleY=Math.min(d/
CANVAS_WIDTH,b/CANVAS_HEIGHT));0>e?$("#canvas").css("top",e+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",f+"px")}}
function _checkOrientation(a,c){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>c?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function createBitmap(a,c,b){var d=new createjs.Bitmap(a),e=new createjs.Shape;c&&b?e.graphics.beginFill("#fff").drawRect(0,0,c,b):e.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=e;return d}function createSprite(a,c,b,d,e,f){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-d,e,f);a.hitArea=c;return a}
function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function rotateVector2D(a,c){var b=c.getX()*Math.cos(a)+c.getY()*Math.sin(a),d=c.getX()*-Math.sin(a)+c.getY()*Math.cos(a);c.set(b,d)}function tweenVectorsOnX(a,c,b){return a+b*(c-a)}function shuffle(a){for(var c=a.length,b,d;0!==c;)d=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[d],a[d]=b;return a}
function bubbleSort(a){var c;do{c=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(c=a[b],a[b]=a[b+1],a[b+1]=c,c=!0)}while(c)}function compare(a,c){return a.index>c.index?-1:a.index<c.index?1:0}function easeLinear(a,c,b,d){return b*a/d+c}function easeInQuad(a,c,b,d){return b*(a/=d)*a+c}function easeInSine(a,c,b,d){return-b*Math.cos(a/d*(Math.PI/2))+b+c}function easeInCubic(a,c,b,d){return b*(a/=d)*a*a+c}function easeOutCubic(a,c,b,d,e){return b*((a=a/d-1)*a*a+1)+c}
function getTrajectoryPoint(a,c){var b=new createjs.Point,d=(1-a)*(1-a),e=a*a;b.x=d*c.start.x+2*(1-a)*a*c.traj.x+e*c.end.x;b.y=d*c.start.y+2*(1-a)*a*c.traj.y+e*c.end.y;return b}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=Math.floor(a-60*c);var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,c){var b,d;b=getBounds(a,.9);d=getBounds(c,.98);return calculateIntersection(b,d)}
function calculateIntersection(a,c){var b,d,e,f,g,h,k,l;b=a.x+(e=a.width/2);d=a.y+(f=a.height/2);g=c.x+(h=c.width/2);k=c.y+(l=c.height/2);b=Math.abs(b-g)-(e+h);d=Math.abs(d-k)-(f+l);return 0>b&&0>d?(b=Math.min(Math.min(a.width,c.width),-b),d=Math.min(Math.min(a.height,c.height),-d),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:b,height:d,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var d=a.children,e=d.length,f,g;for(g=0;g<e;g++)f=getBounds(d[g],1),f.x<b.x&&(b.x=f.x),f.y<b.y&&(b.y=f.y),f.x+f.width>b.x2&&(b.x2=f.x+f.width),f.y+f.height>b.y2&&(b.y2=f.y+f.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var h,k;a instanceof createjs.Bitmap?
(e=a.sourceRect||a.image,g=e.width*c,h=e.height*c):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(e=a.spriteSheet.getFrame(a.currentFrame),g=e.rect.width,h=e.rect.height,d=e.regX,k=e.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);d=d||0;g=g||0;k=k||0;h=h||0;b.regX=d;b.regY=k;e=a.localToGlobal(0-d,0-k);f=a.localToGlobal(g-d,h-k);g=a.localToGlobal(g-d,0-k);d=a.localToGlobal(0-d,h-k);b.x=Math.min(Math.min(Math.min(e.x,
f.x),g.x),d.x);b.y=Math.min(Math.min(Math.min(e.y,f.y),g.y),d.y);b.width=Math.max(Math.max(Math.max(e.x,f.x),g.x),d.x)-b.x;b.height=Math.max(Math.max(Math.max(e.y,f.y),g.y),d.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var c=a.length,b,d;0<c;)d=Math.floor(Math.random()*c),c--,b=a[c],a[c]=a[d],a[d]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var d=c[b].split("=");if(d[0]==a)return d[1]}}
function CSpriteLibrary(){var a,c,b,d,e,f;this.init=function(g,h,k){b=c=0;d=g;e=h;f=k;a={}};this.addSprite=function(b,d){a.hasOwnProperty(b)||(a[b]={szPath:d,oSprite:new Image},c++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){e.call(f)};this._onSpriteLoaded=function(){d.call(f);++b==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return c}}var CANVAS_WIDTH=1360,CANVAS_HEIGHT=540,EDGEBOARD_X=330,EDGEBOARD_Y=0,FONT="gotham_boldregular",NUM_LEVELS=10,NUM_CARS=18,NUM_CONTAINERS=8,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,LEVEL_TIME,MIN_SPEED_OFFSET,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,LEFT_DIR=37,UP_DIR=38,RIGHT_DIR=39,DOWN_DIR=40,SPACEBAR=32,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;
TEXT_ALL_LEVELS_COMPLETED="CONGRATULATIONS! ALL LEVELS HAVE BEEN COMPLETED!";TEXT_SCORE="LEVEL SCORE: ";TEXT_NEXT_LEVEL="CONGRATULATIONS!";TEXT_LEVEL="SELECT LEVEL";TEXT_GAME_OVER="YOU CRASHED YOUR CAR!";TEXT_TOTAL_SCORE="TOTAL SCORE: ";TEXT_CREDITS_DEVELOPED="Developed by";TEXT_MOVE_DESKTOP="USE ARROW KEYS TO STEER AND DRIVE YOUR CAR";TEXT_MOVE_MOBILE="STEER";TEXT_MOVE_MOBILE1="BREAK/\nREVERSE";TEXT_MOVE_MOBILE2="ACCELERATOR";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";
TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var a,c,b,d,e,f,g;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_preloader.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();g=new createjs.Container;s_oStage.addChild(g)};this.unload=function(){g.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(f).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));g.addChild(h);h=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(h);d.x=CANVAS_WIDTH/2-h.width/2;d.y=CANVAS_HEIGHT-100;g.addChild(d);a=h.width;c=h.height;e=new createjs.Shape;e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,c);g.addChild(e);d.mask=
e;b=new createjs.Text("","30px Arial","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-100;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";g.addChild(b);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;g.addChild(f)};this.refreshLoader=function(f){b.text=f+"%";e.graphics.clear();f=Math.floor(f*a/100);e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,f,c)};this._init()}
function CMain(a){var c,b=0,d=0,e=STATE_LOADING,f,g,h;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;s_bTablet=isTablet();!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);
navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();c=!0};this.soundLoaded=function(){b++;g.refreshLoader(Math.floor(b/d*100));b===d&&this._onRemovePreloader()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=
["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/but_press.ogg","but_press"),createjs.Sound.registerSound("./sounds/car_parked.ogg","car_parked"),createjs.Sound.registerSound("./sounds/crash.ogg","crash"),createjs.Sound.registerSound("./sounds/select_car.ogg","select_car"),createjs.Sound.registerSound("./sounds/arrival_lose.ogg","arrival_lose"),createjs.Sound.registerSound("./sounds/arrival_win.ogg",
"arrival_win")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/but_press.mp3","but_press"),createjs.Sound.registerSound("./sounds/car_parked.mp3","car_parked"),createjs.Sound.registerSound("./sounds/crash.mp3","crash"),createjs.Sound.registerSound("./sounds/select_car.mp3","select_car"),createjs.Sound.registerSound("./sounds/arrival_lose.mp3",
"arrival_lose"),createjs.Sound.registerSound("./sounds/arrival_win.mp3","arrival_win")),d+=7)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("asphalt","./sprites/asphalt.jpg");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.png");
s_oSpriteLibrary.addSprite("logo","./sprites/logo.png");s_oSpriteLibrary.addSprite("baloon_mc","./sprites/baloon_mc.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_preloader.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("steering_wheel","./sprites/steering_wheel.png");s_oSpriteLibrary.addSprite("wheel_bar","./sprites/wheel_bar.png");s_oSpriteLibrary.addSprite("accelerator","./sprites/accelerator.png");s_oSpriteLibrary.addSprite("breacker",
"./sprites/breacker.png");s_oSpriteLibrary.addSprite("wheel","./sprites/wheel.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");for(var a=0;a<NUM_LEVELS;a++)s_oSpriteLibrary.addSprite("bg_game"+a,"./sprites/levels/level"+a+"/bg_game.jpg"),s_oSpriteLibrary.addSprite("fg_game"+a,"./sprites/levels/level"+a+"/fg_game.png"),s_oSpriteLibrary.addSprite("lights"+
a,"./sprites/levels/level"+a+"/lights.png");for(a=1;a<=NUM_CARS;a++)s_oSpriteLibrary.addSprite("car_"+a,"./sprites/cars/car"+a+"_mc.png");for(a=1;a<=NUM_CONTAINERS;a++)s_oSpriteLibrary.addSprite("container"+a,"./sprites/container/container"+a+".png");for(a=1;4>=a;a++)s_oSpriteLibrary.addSprite("bar"+a,"./sprites/bar/bar"+a+".png");for(a=1;3>=a;a++)s_oSpriteLibrary.addSprite("divider"+a,"./sprites/divider/divider"+a+".png");for(a=1;3>a;a++)s_oSpriteLibrary.addSprite("flowers"+a,"./sprites/flowers/flowers"+
a+".png");for(a=1;3>=a;a++)s_oSpriteLibrary.addSprite("garbage_bin"+a,"./sprites/garbage_bin/garbage_bin"+a+".png");for(a=1;5>=a;a++)s_oSpriteLibrary.addSprite("house"+a,"./sprites/house/house"+a+".png");for(a=1;3>a;a++)s_oSpriteLibrary.addSprite("box"+a,"./sprites/box/box"+a+".png");for(a=1;4>=a;a++)s_oSpriteLibrary.addSprite("select_car_"+a,"./sprites/select_car/select_car_"+a+".png");for(a=1;6>=a;a++)s_oSpriteLibrary.addSprite("sidewalk_"+a,"./sprites/sidewalk/sidewalk_"+a+".png");for(a=1;2>=a;a++)s_oSpriteLibrary.addSprite("trash"+
a,"./sprites/trash/trash"+a+".png");for(a=1;4>=a;a++)s_oSpriteLibrary.addSprite("drop_area_"+a,"./sprites/drop_area/drop_area_"+a+".png");s_oSpriteLibrary.addSprite("rear_light","./sprites/rear_light.png");s_oSpriteLibrary.addSprite("healt","./sprites/healt.png");s_oSpriteLibrary.addSprite("energy_bar","./sprites/energy_bar.png");s_oSpriteLibrary.addSprite("arrow_keys","./sprites/arrow_keys.png");s_oSpriteLibrary.addSprite("help_touch","./sprites/help_touch.png");s_oSpriteLibrary.addSprite("but_exit",
"./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("time","./sprites/time.png");s_oSpriteLibrary.addSprite("level_sprite","./sprites/LevelSprite.png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;g.refreshLoader(Math.floor(b/d*100));b===d&&this._onRemovePreloader()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._onRemovePreloader=
function(){g.unload();this.gotoMenu();isIOS()||(s_oSoundtrack=playSound("soundtrack",1,-1))};this.gotoMenu=function(){new CMenu;e=STATE_MENU};this.gotoLevelMenu=function(){new CLevelMenu;e=STATE_MENU};this.gotoGame=function(a,b){h=new CGame(f,a,b);e=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;e=STATE_HELP};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=
(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=function(a){if(!1!==c){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;f=a;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;this.initContainer()}
var s_bMobile,s_bTablet,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iLevelReached=1,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack=null,s_oCanvas,s_bIsIphone=!1,s_bFullscreen=!1;
function CTextButton(a,c,b,d,e,f,g){var h,k,l,m,q;this._init=function(a,b,c,d,e,f,g){h=[];k=[];var n=createBitmap(c),u=Math.ceil(g/20);q=new createjs.Text(d,"bold "+g+"px "+e,"#000000");q.textAlign="center";q.textBaseline="alphabetic";var r=q.getBounds();q.x=c.width/2+u;q.y=Math.floor(c.height/2)+r.height/3+u;m=new createjs.Text(d,"bold "+g+"px "+e,f);m.textAlign="center";m.textBaseline="alphabetic";r=m.getBounds();m.x=c.width/2;m.y=Math.floor(c.height/2)+r.height/3;l=new createjs.Container;l.x=a;
l.y=b;l.regX=c.width/2;l.regY=c.height/2;s_bMobile||(l.cursor="pointer");l.addChild(n,q,m);s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;k[a]=c};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};
this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setTextPosition=function(a){m.y=a;q.y=a+2};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(a,c,b,d,e,f,g);return this}
function CToggle(a,c,b,d){var e,f,g,h=[],k,l=1;this._init=function(a,b,c,d){f=[];g=[];var n=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});e=d;k=createSprite(n,"state_"+e,c.width/2/2,c.height/2,c.width/2,c.height);k.x=a;k.y=b;k.stop();s_bMobile||(k.cursor="pointer");s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);
s_oStage.removeChild(k)};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;g[a]=c};this.addEventListenerWithParams=function(a,b,c,d){f[a]=b;g[a]=c;h=d};this.setActive=function(a){e=a;k.gotoAndStop("state_"+e)};this.setScale=function(a){l=a;k.scaleX=l;k.scaleY=l};this.buttonRelease=function(){k.scaleX=l;k.scaleY=l;playSound("but_press",1,0);e=!e;k.gotoAndStop("state_"+e);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(g[ON_MOUSE_UP],
h)};this.buttonDown=function(){k.scaleX=l-.1;k.scaleY=l-.1;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],h)};this.setPosition=function(a,b){k.x=a;k.y=b};this.setVisible=function(a){k.visible=a};this._init(a,c,b,d)}
function CGfxButton(a,c,b){var d,e,f,g=[],h;this._init=function(a,b,c){d=1;e=[];f=[];h=createBitmap(c);h.x=a;h.y=b;h.regX=c.width/2;h.regY=c.height/2;s_bMobile||(h.cursor="pointer");s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);s_oStage.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=
function(a,b,c){e[a]=b;f[a]=c};this.addEventListenerWithParams=function(a,b,c,d){e[a]=b;f[a]=c;g=d};this.buttonRelease=function(){h.scaleX=d;h.scaleY=d;e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(f[ON_MOUSE_UP],g)};this.buttonDown=function(){h.scaleX=.9*d;h.scaleY=.9*d;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],g)};this.setScale=function(a){d=a;h.scaleX=a;h.scaleY=a};this.setPosition=function(a,b){h.x=a;h.y=b};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};
this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(a,c,b);return this}
function CMenu(){var a,c,b,d,e,f,g,h,k,l,m,q,n,u=null,z=null;this._init=function(){g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(g);h=createBitmap(s_oSpriteLibrary.getSprite("logo"));h.x=CANVAS_WIDTH/2-350;h.y=40;s_oStage.addChild(h);var r=s_oSpriteLibrary.getSprite("but_play");k=new CGfxButton(CANVAS_WIDTH/2+220,CANVAS_HEIGHT/2+80,r);k.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r=s_oSpriteLibrary.getSprite("audio_icon"),
e=CANVAS_WIDTH-r.height/2-10,f=r.height/2+10,m=new CToggle(e,f,r,s_bAudioActive),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);r=s_oSpriteLibrary.getSprite("but_credits");b=r.height/2+10;d=r.height/2+10;q=new CGfxButton(b,d,r,s_oStage);q.addEventListener(ON_MOUSE_UP,this._onButInfoRelease,this);var r=window.document,A=r.documentElement;u=A.requestFullscreen||A.mozRequestFullScreen||A.webkitRequestFullScreen||A.msRequestFullscreen;z=r.exitFullscreen||r.mozCancelFullScreen||r.webkitExitFullscreen||
r.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(u=!1);u&&!1===inIframe()&&(r=s_oSpriteLibrary.getSprite("but_fullscreen"),a=b+r.width/2-10,c=r.height/2+10,n=new CToggle(a,c,r,s_bFullscreen,!0),n.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));l=new createjs.Shape;l.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(l);createjs.Tween.get(l).to({alpha:0},1E3).call(function(){l.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){k.unload();
k=null;l.visible=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;u&&!1===inIframe()&&n.unload();q.unload();s_oStage.removeAllChildren();s_oMenu=null};this.refreshButtonPos=function(g,h){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(e-g,h+f);u&&!1===inIframe()&&n.setPosition(a+g,c+h);q.setPosition(b+g,d+h)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();isIOS()&&null===
s_oSoundtrack?s_oSoundtrack=playSound("soundtrack",1,-1):playSound("but_press",1,0);s_oMain.gotoLevelMenu();$(s_oMain).trigger("start_session")};this._onButInfoRelease=function(){new CCreditsPanel};this._onFullscreenRelease=function(){s_bFullscreen?(z.call(window.document),s_bFullscreen=!1):(u.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a,c,b){function d(a){a||(a=window.event);if(!0===u){if(a.keyCode===LEFT_DIR)return m.moveLeft(!0),a.preventDefault(),!1;if(a.keyCode===UP_DIR)return m.moveUp(!0),a.preventDefault(),!1;if(a.keyCode===RIGHT_DIR)return m.moveRight(!0),a.preventDefault(),!1;if(a.keyCode===DOWN_DIR)return m.moveDown(!0),a.preventDefault(),!1;if(a.keyCode===SPACEBAR)return a.preventDefault(),!1}}function e(a){a||(a=window.event);if(!0===u){if(a.keyCode===LEFT_DIR)return m.moveLeft(!1),a.preventDefault(),
!1;if(a.keyCode===UP_DIR)return m.moveUp(!1),a.preventDefault(),!1;if(a.keyCode===RIGHT_DIR)return m.moveRight(!1),a.preventDefault(),!1;if(a.keyCode===DOWN_DIR)return m.moveDown(!1),a.preventDefault(),!1;if(a.keyCode===SPACEBAR)return a.preventDefault(),!1}}var f=c,g=0,h=b,k=0,l,m,q,n,u=!1,z=!1,r,A=[],v=[],w=[],C=[],B,t,x,G=null,P=null;this._init=function(){l=LEVEL_TIME;P=new createjs.Shape;s_oStage.addChild(P);P.x=0;P.y=0;P.graphics.beginBitmapFill(s_oSpriteLibrary.getSprite("asphalt"),"repeat").drawRect(0,
0,canvas.width,canvas.height);$(s_oMain).trigger("start_level",f);var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"+f));a.x=330;a.y=40;s_oStage.addChild(a);B=new CLevelSettings;r=B.getLevelObjects(f);this._placeDropArea();for(a=0;a<r.length;a++){A.push();var b=s_oSpriteLibrary.getSprite(r[a].mc),c=createBitmap(b);c.x=r[a].x+b.width/2;c.y=r[a].y+b.height/2;c.regX=b.width/2;c.regY=b.height/2;r[a].visible&&s_oStage.addChild(c);b=new CCollisionRectangle(b,c.x,c.y,b.width/2,b.height/2,0);w.push(b.getBox());
C.push(b.prepareVector(w[w.length-1]))}this._placeCars();a=createBitmap(s_oSpriteLibrary.getSprite("fg_game"+f));a.x=275;a.y=-20;s_oStage.addChild(a);a=createBitmap(s_oSpriteLibrary.getSprite("lights"+f));a.x=300;a.y=15;s_oStage.addChild(a);x=new CInterface;x.refreshScore(h);s_bMobile?x.spawnGraphicControl():(document.onkeydown=d,document.onkeyup=e);z=u=!0;a=s_oSpriteLibrary.getSprite("baloon_mc");t=createBitmap(a);t.regX=a.width/2;t.regY=a.height/2;t.visible=!1;s_oStage.addChild(t)};this._placeDropArea=
function(){n=B.getDropArea(f);var a=s_oSpriteLibrary.getSprite("drop_area_"+n.mc);a.x=n.x;a.y=n.y;a=new createjs.SpriteSheet({images:[a],framerate:30,frames:{width:n.width,height:n.height,regX:0,regY:0},animations:{idle:[0,39,"idle"]}});q=createSprite(a,"idle",0,0,n.width,n.height);q.x=n.x;q.y=n.y;s_oStage.addChild(q)};this._placeCars=function(){var a,b;v=[];var c=B.getCarInfos(f),d;if(null!==c)for(var e=0;e<c.length;e++)d=new CCar(c[e].type,!1),a=B.getCarX(f,e),b=B.getCarY(f,e),d.initInfo(a,b,c[e].rot,
!1),v.push(d.getBitmap()),w.push(d.getRectangle()),C.push(d.getVector(w[w.length-1]));c=B.getMyCarInfos(f);d=new CCar(c.type,!0);a=B.getMyCarX(f);b=B.getMyCarY(f);d.initInfo(a,b,c.rot);this.carSelected(d);d.getBitmap()};this.carSelected=function(a){playSound("select_car",1,0);m=a;m.select()};this.checkDropArea=function(){m.check(q)};this.carParked=function(){playSound("car_parked",1,0);0<l&&(k+=Math.floor(l/1E3));c++;s_iLevelReached=c+1;h+=Math.ceil(k+g/10);z=!1;f<B.getNumLevels()-1?(G=CEndPanel(s_oSpriteLibrary.getSprite("msg_box")),
G.show(k,h,m,q,n.mc)):(G=CEndPanel(s_oSpriteLibrary.getSprite("msg_box")),G.endGame(k,h,m,q,n.mc))};this.gameOver=function(){G=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));G.gameOver(h,m)};this.onLeftSteeringWheelDown=function(){m.moveLeft(!0)};this.onLeftSteeringWheelUp=function(){m.moveLeft(!1)};this.onRightSteeringWheelDown=function(){m.moveRight(!0)};this.onRightSteeringWheelUp=function(){m.moveRight(!1)};this.onAcceleratorPress=function(){m.moveUp(!0)};this.onAcceleratorRelease=function(){m.moveUp(!1)};
this.onReversePress=function(){m.moveDown(!0)};this.onReverseRelease=function(){m.moveDown(!1)};this.unload=function(){w=[];v=[];r=[];C=[];x.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();setVolume(s_oSoundtrack,1);s_oMain.gotoMenu();var a=B.getNumLevels();f<a&&$(s_oMain).trigger("end_level",f);$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};this.onRestart=function(){this.unload();$(s_oMain).trigger("restart_level",
f);$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_level",f);s_oMain.gotoGame(f,h)};this.onNextLevel=function(){this.unload();$(s_oMain).trigger("end_level",f);s_oMain.gotoGame(f+1,h);$(s_oMain).trigger("show_interlevel_ad")};this.setCanMoveTrue=function(){u=!0};this.update=function(){if(z&&(m.update(),l-=s_iTimeElaps,0<l&&x.refreshTime(formatTime(l)),0<w.length))for(var a=0;a<w.length;a++)if(!m.checkCollision(w[a],C[a])){u=!1;m.moveLeft(!1);m.moveUp(!1);m.moveRight(!1);m.moveDown(!1);
m.isCrashing();t.visible=!0;t.x=m.getX();t.y=m.getY();playSound("crash",1,0);createjs.Tween.get(t).to({x:t.x+Math.round(10*Math.random()),y:t.y+Math.round(30*Math.random())},50).call(function(){createjs.Tween.get(t).to({x:t.x+Math.round(8*Math.random()),y:t.y+-Math.round(24*Math.random())},50).call(function(){createjs.Tween.get(t).to({x:t.x+Math.round(6*Math.random()),y:t.y+Math.round(18*Math.random())},50).call(function(){createjs.Tween.get(t).to({x:t.x+Math.round(4*Math.random()),y:t.y+-Math.round(12*
Math.random())},50).call(function(){createjs.Tween.get(t).to({y:t.y,x:t.x},150).call(function(){t.visible=!1})})})})});var b=m.getEnergyPercLost();x.refreshMask(b);g=m.getEnergy();0>=g&&this.gameOver()}};s_oGame=this;LEVEL_TIME=a.level_time;MIN_SPEED_OFFSET=a.min_speed_offset;_oParent=this;this._init()}var s_oGame;
function CInterface(){var a,c,b,d,e,f,g,h,k,l,m,q,n=100,u,z,r,A=null,v,w,C,B,t,x,G,P=CANVAS_HEIGHT-146,S=CANVAS_HEIGHT-70,K,U,T,O,L=CANVAS_WIDTH/2-265,D,E,M=CANVAS_WIDTH/2-205,N,J,F=CANVAS_WIDTH/2,p=CANVAS_HEIGHT-10,Q,H=null,I=null;this._init=function(){var a,b=s_oSpriteLibrary.getSprite("but_exit");m=CANVAS_WIDTH-b.height/2-10;q=b.height/2+10;z=new CGfxButton(m,q,b,s_oStage);z.addEventListener(ON_MOUSE_UP,this._onExit,this);k=a=CANVAS_WIDTH-b.width/2-70;l=b.height/2+10;!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile?(b=s_oSpriteLibrary.getSprite("audio_icon"),u=new CToggle(k,l,b,s_bAudioActive),u.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),e=k-b.width/2+10,f=l):(e=a,f=b.height/2+10);a=window.document;var c=a.documentElement;H=c.requestFullscreen||c.mozRequestFullScreen||c.webkitRequestFullScreen||c.msRequestFullscreen;I=a.exitFullscreen||a.mozCancelFullScreen||a.webkitExitFullscreen||a.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(H=!1);H&&!1===inIframe()&&(b=s_oSpriteLibrary.getSprite("but_fullscreen"),
Q=new CToggle(e,f,b,s_bFullscreen,!0),Q.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));g=40;h=b.height/2+10;b=s_oSpriteLibrary.getSprite("but_restart");r=new CGfxButton(g,h,b,s_oStage);r.addEventListener(ON_MOUSE_UP,this._onRestart,this);J=new createjs.Text("SCORE: 0","bold 40px "+FONT,"#600101");J.x=F;J.y=p;J.textAlign="center";J.textBaseline="alphabetic";J.outline=4;s_oStage.addChild(J);N=new createjs.Text("SCORE: 0","bold 40px "+FONT,"#ffffff");N.x=F;N.y=p;N.textAlign="center";N.textBaseline=
"alphabetic";s_oStage.addChild(N);E=new createjs.Text("00:00","bold 40px "+FONT,"#600101");E.x=M;E.y=50;E.textAlign="left";E.textBaseline="alphabetic";E.outline=4;s_oStage.addChild(E);D=new createjs.Text("00:00","bold 40px "+FONT,"#ffffff");D.x=M;D.y=50;D.textAlign="left";D.textBaseline="alphabetic";s_oStage.addChild(D);O=createBitmap(s_oSpriteLibrary.getSprite("time"));O.x=L;O.y=5;s_oStage.addChild(O);b=s_oSpriteLibrary.getSprite("energy_bar");G=createBitmap(b);G.x=260;G.y=S;G.regY=b.height;s_oStage.addChild(G);
b=s_oSpriteLibrary.getSprite("healt");x=createBitmap(b);U=b.width-6;T=b.height;x.x=264;x.y=P;x.regY=b.height;x.alpha=.9;s_oStage.addChild(x);K=new createjs.Shape;K.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(x.x+3,x.y,U,-T+3);K.regY=x.regY-T;s_oStage.addChild(K);x.mask=K;this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshTime=function(a){E.text=a;D.text=a};this.refreshScore=function(a){J.text="SCORE: "+a;N.text="SCORE: "+a};this.spawnGraphicControl=function(){C={x:125,y:450};w=new CSteeringWheel(C,
s_oStage);b=CANVAS_WIDTH-50;d=450;var e=s_oSpriteLibrary.getSprite("accelerator");B=new CToggle(b,d,e,!0);B.addEventListener(ON_MOUSE_DOWN,this._onAcceleratorPress,this);B.addEventListener(ON_MOUSE_UP,this._onAcceleratorRelease,this);a=CANVAS_WIDTH-175;c=450;e=s_oSpriteLibrary.getSprite("breacker");t=new CToggle(a,c,e,!0);t.addEventListener(ON_MOUSE_DOWN,this._onReversePress,this);t.addEventListener(ON_MOUSE_UP,this._onReverseRelease,this);v=!0;s_bTablet&&(w.setScale(.9),b=CANVAS_WIDTH-55,d=470,B.setPosition(b,
d),B.setScale(.7),a=CANVAS_WIDTH-115,c=470,t.setPosition(a,c),t.setScale(.7));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this._onReversePress=function(){s_oGame.onReversePress();t.setActive(!1)};this._onReverseRelease=function(){s_oGame.onReverseRelease();t.setActive(!0)};this._onAcceleratorPress=function(){s_oGame.onAcceleratorPress();B.setActive(!1)};this._onAcceleratorRelease=function(){s_oGame.onAcceleratorRelease();B.setActive(!0)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===
s_bMobile)u.unload(),u=null;H&&!1===inIframe()&&Q.unload();z.unload();r.unload();null!==A&&A.unload();s_oInterface=null};this.refreshMask=function(a){n=a;K.graphics.clear();a=Math.floor(n*T/100);K.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(x.x+3,x.y,U,-a+3)};this.refreshButtonPos=function(p,y){z.setPosition(m-p,y+q);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||u.setPosition(k-p,y+l);H&&!1===inIframe()&&Q.setPosition(e-p,f+y);r.setPosition(g+p,y+h);336>264+p?(x.x=264+p,G.x=260+p):(x.x=336,
G.x=332);this.refreshMask(n);v&&(w.setPosition(C.x+p,C.y),B.setPosition(b-p,d),t.setPosition(a-p,c))};this._onButHelpRelease=function(){A=new CHelpPanel};this.onExitFromHelp=function(){A.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){playSound("but_press",1,0);s_oGame.onExit()};this._onRestart=function(){playSound("but_press",1,0);s_oGame.onRestart()};this._onFullscreenRelease=function(){s_bFullscreen?(I.call(window.document),
s_bFullscreen=!1):(H.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CEndPanel(a){var c,b,d,e,f,g,h,k;this._init=function(a){c=createBitmap(a);c.x=0;c.y=0;e=new createjs.Text(""," 45px "+FONT,"#600101");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-122;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=500;e.outline=4;d=new createjs.Text(""," 45px "+FONT,"#ffffff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-122;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=500;g=new createjs.Text(""," 40px "+FONT,"#600101");g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/
2+15;g.textAlign="center";g.textBaseline="alphabetic";g.lineWidth=500;g.outline=4;f=new createjs.Text(""," 40px "+FONT,"#ffffff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2+15;f.textAlign="center";f.textBaseline="alphabetic";f.lineWidth=500;k=new createjs.Text(""," 40px "+FONT,"#600101");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2+102;k.textAlign="center";k.textBaseline="alphabetic";k.lineWidth=500;k.outline=4;h=new createjs.Text(""," 40px "+FONT,"#ffffff");h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2+102;h.textAlign=
"center";h.textBaseline="alphabetic";h.lineWidth=500;b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(c,g,f,e,d,k,h);s_oStage.addChild(b)};this._initListener=function(){b.on("mousedown",this._onExit)};this._initListenerEnd=function(){b.on("mousedown",this._onEndGame)};this.show=function(a,c,q,n,u){playSound("arrival_win",1,0);setVolume(s_oSoundtrack,.5);e.text=TEXT_NEXT_LEVEL;d.text=TEXT_NEXT_LEVEL;var l=Math.abs(n.x-q.getX()),m=Math.abs(n.y-q.getY()),A=0,v=0,w=CANVAS_WIDTH/2,C=CANVAS_HEIGHT/
2-60;b.addChild(n);switch(u){case 1:n.x=w-l;n.y=C-m+10;break;case 2:n.x=w-l;n.y=C-m+10;break;case 3:A=-20;v=30;n.x=w-l+A;n.y=C-m+v;break;case 4:n.x=w-l,n.y=C-m}q.seeOnStage(w+A,C+v,b);g.text=TEXT_SCORE+a;g.font=" 30px "+FONT;g.y+=60;f.text=TEXT_SCORE+a;f.font=" 30px "+FONT;f.y+=60;k.text=TEXT_TOTAL_SCORE+c;k.y=CANVAS_HEIGHT/2+132;h.text=TEXT_TOTAL_SCORE+c;h.y=CANVAS_HEIGHT/2+132;b.visible=!0;var B=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){B._initListener()});$(s_oMain).trigger("share_event",
c);$(s_oMain).trigger("save_score",c)};this.endGame=function(a,c,q,n,u){playSound("arrival_win",1,0);setVolume(s_oSoundtrack,.5);var l=Math.abs(n.x-q.getX()),m=Math.abs(n.y-q.getY());e.text=TEXT_ALL_LEVELS_COMPLETED;e.font=" 30px "+FONT;e.y=CANVAS_HEIGHT/2-122;d.text=TEXT_ALL_LEVELS_COMPLETED;d.font=" 30px "+FONT;d.y=CANVAS_HEIGHT/2-122;var l=Math.abs(n.x-q.getX()),m=Math.abs(n.y-q.getY()),A=CANVAS_WIDTH/2-30,v=CANVAS_HEIGHT/2;b.addChild(n);switch(u){case 1:n.x=A-l;n.y=v-m+10;break;case 2:n.x=A-l;
n.y=v-m+10;break;case 3:n.x=A-l;n.y=v-m;break;case 4:n.x=A-l,n.y=v-m}q.seeOnStage(A,v,b);g.text=TEXT_SCORE+a;g.font=" 30px "+FONT;g.y=CANVAS_HEIGHT/2+70;f.text=TEXT_SCORE+a;f.font=" 30px "+FONT;f.y=CANVAS_HEIGHT/2+70;k.text=TEXT_TOTAL_SCORE+c;k.y=CANVAS_HEIGHT/2+132;h.text=TEXT_TOTAL_SCORE+c;h.y=CANVAS_HEIGHT/2+132;b.visible=!0;var w=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){w._initListenerEnd()});$(s_oMain).trigger("share_event",c);$(s_oMain).trigger("save_score",c)};this.gameOver=
function(a,c){playSound("arrival_lose",1,0);setVolume(s_oSoundtrack,.5);e.text=TEXT_GAME_OVER;d.text=TEXT_GAME_OVER;var f=CANVAS_WIDTH/2-30,n=CANVAS_HEIGHT/2+20;c.seeOnStageGameOver(f,n,b);var g=s_oSpriteLibrary.getSprite("baloon_mc"),l=createBitmap(s_oSpriteLibrary.getSprite("baloon_mc"));l.x=f+50;l.y=n-50;l.regX=g.width/2;l.regY=g.height/2;b.addChild(l);k.text=TEXT_TOTAL_SCORE+a;k.y+=30;h.text=TEXT_TOTAL_SCORE+a;h.y+=30;b.visible=!0;var m=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){m._initListenerEnd()});
$(s_oMain).trigger("share_event",a);$(s_oMain).trigger("save_score",a)};this._onExit=function(){b.off("mousedown",this._onExit);s_oStage.removeChild(b);s_oGame.onNextLevel()};this._onEndGame=function(){b.off("mousedown",this._onEndGame);s_oStage.removeChild(b);s_oGame.onExit()};this._init(a);return this}
function CLevelSettings(){var a=[],c=[],b=[],d=[];this._init=function(){this._initLevelObjects();this._initCarInfos();this._initDropAreas()};this._initLevelObjects=function(){b.push([{x:331,y:-175,width:46,height:500,mc:"sidewalk_5",visible:!1},{x:369,y:40,width:656,height:46,mc:"sidewalk_1",visible:!1},{x:984,y:50,width:46,height:500,mc:"sidewalk_3",visible:!1},{x:332,y:493,width:656,height:46,mc:"sidewalk_4",visible:!1},{x:310,y:215,width:146,height:110,mc:"house3",visible:!0},{x:425,y:330,width:20,
height:160,mc:"bar3",visible:!0},{x:750,y:450,width:73,height:44,mc:"garbage_bin1",visible:!0},{x:830,y:450,width:73,height:44,mc:"garbage_bin1",visible:!0}]);b.push([{x:401,y:-175,width:46,height:500,mc:"sidewalk_5",visible:!1},{x:399,y:40,width:656,height:46,mc:"sidewalk_1",visible:!1},{x:984,y:50,width:46,height:500,mc:"sidewalk_3",visible:!1},{x:328,y:493,width:656,height:46,mc:"sidewalk_4",visible:!1},{x:310,y:220,width:146,height:110,mc:"house3",visible:!0},{x:425,y:335,width:20,height:160,
mc:"bar3",visible:!0},{x:750,y:450,width:73,height:44,mc:"garbage_bin1",visible:!0},{x:830,y:450,width:73,height:44,mc:"garbage_bin1",visible:!0},{x:910,y:450,width:73,height:44,mc:"garbage_bin1",visible:!0}]);b.push([{x:330,y:40,width:46,height:500,mc:"sidewalk_5",visible:!1},{x:361,y:40,width:656,height:46,mc:"sidewalk_1",visible:!1},{x:985,y:-180,width:46,height:500,mc:"sidewalk_3",visible:!1},{x:331,y:495,width:656,height:46,mc:"sidewalk_4",visible:!1},{x:883,y:220,width:146,height:110,mc:"house4",
visible:!0},{x:893,y:335,width:20,height:160,mc:"bar3",visible:!0},{x:900,y:175,width:73,height:44,mc:"garbage_bin1",visible:!0},{x:910,y:90,width:32,height:32,mc:"trash1",visible:!0},{x:944,y:90,width:32,height:32,mc:"trash1",visible:!0}]);b.push([{x:825,y:40,width:656,height:46,mc:"sidewalk_1",visible:!1},{x:985,y:40,width:46,height:500,mc:"sidewalk_3",visible:!1},{x:361,y:495,width:656,height:46,mc:"sidewalk_4",visible:!1},{x:330,y:40,width:46,height:500,mc:"sidewalk_5",visible:!1},{x:572,y:40,
width:110,height:146,mc:"house5",visible:!0},{x:685,y:155,width:160,height:20,mc:"bar4",visible:!0},{x:390,y:310,width:44,height:73,mc:"garbage_bin2",visible:!0},{x:590,y:193,width:75,height:34,mc:"flowers1",visible:!0},{x:850,y:90,width:34,height:75,mc:"flowers2",visible:!0},{x:420,y:120,width:34,height:75,mc:"flowers1",visible:!0},{x:535,y:120,width:32,height:32,mc:"trash2",visible:!0},{x:535,y:155,width:32,height:32,mc:"trash2",visible:!0}]);b.push([{x:331,y:40,width:656,height:46,mc:"sidewalk_1",
visible:!1},{x:985,y:40,width:46,height:500,mc:"sidewalk_3",visible:!1},{x:361,y:495,width:656,height:46,mc:"sidewalk_4",visible:!1},{x:330,y:40,width:46,height:500,mc:"sidewalk_2",visible:!1},{x:520,y:318,width:339,height:31,mc:"divider3",visible:!0},{x:885,y:220,width:146,height:110,mc:"house4",visible:!0},{x:890,y:335,width:20,height:160,mc:"bar3",visible:!0},{x:935,y:120,width:44,height:73,mc:"garbage_bin3",visible:!0}]);b.push([{x:588,y:40,width:656,height:46,mc:"sidewalk_1",visible:!1},{x:985,
y:40,width:46,height:500,mc:"sidewalk_3",visible:!1},{x:361,y:495,width:656,height:46,mc:"sidewalk_4",visible:!1},{x:330,y:40,width:46,height:500,mc:"sidewalk_2",visible:!1},{x:543,y:40,width:110,height:146,mc:"house1",visible:!0},{x:380,y:61,width:160,height:20,mc:"bar1",visible:!0},{x:936,y:296,width:44,height:73,mc:"garbage_bin3",visible:!0},{x:570,y:190,width:32,height:32,mc:"trash1",visible:!0},{x:610,y:190,width:32,height:32,mc:"trash1",visible:!0},{x:570,y:285,width:34,height:75,mc:"flowers2",
visible:!0},{x:675,y:170,width:34,height:75,mc:"flowers2",visible:!0},{x:815,y:90,width:34,height:75,mc:"flowers2",visible:!0},{x:815,y:170,width:34,height:75,mc:"flowers2",visible:!0},{x:675,y:415,width:34,height:75,mc:"flowers2",visible:!0},{x:675,y:370,width:75,height:34,mc:"flowers1",visible:!0}]);b.push([{x:351,y:40,width:656,height:46,mc:"sidewalk_1",visible:!1},{x:985,y:40,width:46,height:500,mc:"sidewalk_3",visible:!1},{x:809,y:495,width:656,height:46,mc:"sidewalk_4",visible:!1},{x:-72,y:495,
width:656,height:46,mc:"sidewalk_4",visible:!1},{x:330,y:40,width:46,height:500,mc:"sidewalk_2",visible:!1},{x:750,y:395,width:110,height:146,mc:"house1",visible:!0},{x:580,y:395,width:160,height:20,mc:"bar1",visible:!0},{x:880,y:440,width:73,height:44,mc:"garbage_bin1",visible:!0},{x:510,y:450,width:32,height:32,mc:"trash2",visible:!0},{x:770,y:355,width:75,height:34,mc:"flowers1",visible:!0}]);b.push([{x:350,y:40,width:656,height:46,mc:"sidewalk_1",visible:!1},{x:985,y:40,width:46,height:500,mc:"sidewalk_3",
visible:!1},{x:355,y:495,width:656,height:46,mc:"sidewalk_4",visible:!1},{x:330,y:-303,width:46,height:500,mc:"sidewalk_2",visible:!1},{x:330,y:360,width:46,height:500,mc:"sidewalk_2",visible:!1},{x:375,y:200,width:20,height:160,mc:"bar3",visible:!0},{x:400,y:195,width:75,height:34,mc:"flowers1",visible:!0},{x:825,y:195,width:75,height:34,mc:"flowers1",visible:!0},{x:480,y:197,width:339,height:31,mc:"divider3",visible:!0},{x:480,y:350,width:339,height:31,mc:"divider3",visible:!0}]);b.push([{x:352,
y:3,width:656,height:46,mc:"sidewalk_1",visible:!1},{x:1017,y:3,width:46,height:500,mc:"sidewalk_3",visible:!1},{x:630,y:527,width:656,height:46,mc:"sidewalk_4",visible:!1},{x:-200,y:527,width:656,height:46,mc:"sidewalk_4",visible:!1},{x:-9,y:249,width:46,height:500,mc:"sidewalk_2",visible:!1},{x:460,y:521,width:160,height:20,mc:"bar1",visible:!0}]);b.push([{x:356,y:40,width:656,height:46,mc:"sidewalk_1",visible:!1},{x:995,y:40,width:46,height:500,mc:"sidewalk_3",visible:!1},{x:538,y:510,width:656,
height:46,mc:"sidewalk_4",visible:!1},{x:320,y:40,width:46,height:500,mc:"sidewalk_2",visible:!1},{x:655,y:80,width:172,height:70,mc:"container1",visible:!0},{x:685,y:320,width:172,height:70,mc:"container1",visible:!0},{x:825,y:80,width:172,height:70,mc:"container3",visible:!0},{x:610,y:335,width:70,height:172,mc:"container6",visible:!0},{x:360,y:505,width:160,height:20,mc:"bar4",visible:!0},{x:618,y:273,width:73,height:44,mc:"garbage_bin1",visible:!0},{x:698,y:273,width:73,height:44,mc:"garbage_bin1",
visible:!0}])};this._initCarInfos=function(){a=[];a.push(null);a.push([{x:917,y:151,type:9,rot:25},{x:655,y:154,type:10,rot:25}]);a.push([{x:511,y:155,type:15,rot:-155},{x:576,y:154,type:8,rot:-155},{x:700,y:160,type:9,rot:-155},{x:830,y:160,type:3,rot:-155},{x:788,y:297,type:4,rot:-90}]);a.push([{x:955,y:347,type:5,rot:0},{x:650,y:425,type:7,rot:0},{x:475,y:345,type:2,rot:-90}]);a.push([{x:829,y:134,type:1,rot:0},{x:772,y:133,type:5,rot:0},{x:568,y:131,type:3,rot:0},{x:690,y:285,type:6,rot:-90},
{x:409,y:398,type:4,rot:0}]);a.push([{x:410,y:330,type:12,rot:0},{x:616,y:252,type:10,rot:90},{x:798,y:386,type:2,rot:0},{x:860,y:426,type:13,rot:0},{x:892,y:138,type:14,rot:0}]);a.push([{x:594,y:130,type:2,rot:0},{x:819,y:130,type:9,rot:0},{x:875,y:130,type:5,rot:0},{x:620,y:250,type:12,rot:-90},{x:525,y:376,type:3,rot:0}]);a.push([{x:870,y:277,type:16,rot:0},{x:940,y:435,type:17,rot:56}]);a.push([{x:428,y:122,type:8,rot:180},{x:598,y:120,type:9,rot:-175},{x:708,y:110,type:15,rot:-7.5},{x:827,y:93,
type:1,rot:0},{x:972,y:110,type:12,rot:0},{x:427,y:250,type:10,rot:0},{x:672,y:280,type:13,rot:0},{x:765,y:260,type:2,rot:0},{x:825,y:275,type:11,rot:0},{x:944,y:280,type:16,rot:0},{x:484,y:365,type:5,rot:0},{x:538,y:403,type:17,rot:180},{x:596,y:380,type:4,rot:0},{x:766,y:407,type:3,rot:180},{x:935,y:375,type:7,rot:0}]);a.push([{x:614,y:115,type:7,rot:60},{x:580,y:445,type:6,rot:180},{x:465,y:135,type:12,rot:48}]);c=[];c.push({x:570,y:440,type:2,rot:90});c.push({x:520,y:415,type:1,rot:90});c.push({x:820,
y:422,type:5,rot:-90});c.push({x:743,y:250,type:9,rot:180});c.push({x:815,y:419,type:8,rot:-90});c.push({x:461,y:155,type:8,rot:166});c.push({x:680,y:337,type:10,rot:40});c.push({x:473,y:280,type:15,rot:90});c.push({x:400,y:430,type:14,rot:24});c.push({x:450,y:340,type:18,rot:0})};this._initDropAreas=function(){d=[];d.push({mc:1,width:55,height:133,x:701,y:85});d.push({mc:2,width:124,height:124,x:725,y:87});d.push({mc:2,width:124,height:124,x:708,y:87});d.push({mc:3,width:133,height:55,x:388,y:433});
d.push({mc:1,width:55,height:133,x:632,y:87});d.push({mc:1,width:55,height:133,x:925,y:87});d.push({mc:1,width:55,height:133,x:508,y:87});d.push({mc:3,width:133,height:55,x:408,y:107});d.push({mc:1,width:55,height:133,x:511,y:200});d.push({mc:4,width:203,height:77,x:683,y:423})};this.getCarInfos=function(b){return a[b]};this.getMyCarInfos=function(a){return c[a]};this.getLevelObjects=function(a){return b[a]};this.getDropArea=function(a){return d[a]};this.getCarX=function(b,c){return a[b][c].x};this.getCarY=
function(b,c){return a[b][c].y};this.getMyCarX=function(a){return c[a].x};this.getMyCarY=function(a){return c[a].y};this.getNumLevels=function(a){return c.length};this._init();return this}
function CLevelBut(a,c,b,d,e){var f,g,h,k=[],l=[],m;this._init=function(a,b,c,d){g=[];h=[];var n=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=d;m=createSprite(n,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);m.mouseEnabled=d;m.x=a;m.y=b;m.stop();s_bMobile||(m.cursor="pointer");s_oStage.addChild(m);k.push(m);c=new createjs.Text(e,"bold 40px "+FONT,"#79035c");c.x=a;c.y=b+15;c.textAlign=
"center";c.textBaseline="alphabetic";c.lineWidth=200;c.outline=4;s_oStage.addChild(c);c=new createjs.Text(e,"bold 40px "+FONT,"#ffffff");c.x=a;c.y=b+15;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=200;s_oStage.addChild(c);this._initListener()};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);s_oStage.removeChild(m)};this._initListener=function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.viewBut=function(a){s_oStage.addChild(a)};
this.addEventListener=function(a,b,c){g[a]=b;h[a]=c};this.addEventListenerWithParams=function(a,b,c,d){g[a]=b;h[a]=c;l=d};this.ifClickable=function(){return!0===m.mouseEnabled?1:0};this.setActive=function(a,b){f=b;k[a].gotoAndStop("state_"+f);k[a].mouseEnabled=!0};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;playSound("but_press",1,0);f=!f;m.gotoAndStop("state_"+f);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(h[ON_MOUSE_UP],l)};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN],
l)};this.setPosition=function(a,b){m.x=a;m.y=b};this.setVisible=function(a){m.visible=a};this._init(a,c,b,d)}
function CLevelMenu(){var a,c,b,d,e,f=[],g,h,k,l,m;this._init=function(){k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(k);g=new CLevelSettings;h=g.getNumLevels();k=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));s_oStage.addChild(k);e=new createjs.Text(TEXT_LEVEL," 50px "+FONT,"#730358");e.x=CANVAS_WIDTH/2;e.y=160;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=1E3;e.outline=4;s_oStage.addChild(e);e=new createjs.Text(TEXT_LEVEL," 50px "+FONT,"#ffffff");e.x=
CANVAS_WIDTH/2;e.y=160;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=1E3;s_oStage.addChild(e);for(var q=CANVAS_WIDTH/2,n=0,u=50,z=0;z<h;z++,n+=100)400<n&&(n=0,u+=100),z<s_iLevelReached?f.push(new CLevelBut(q-200+n,175+u,s_oSpriteLibrary.getSprite("level_sprite"),!0,z+1)):f.push(new CLevelBut(q-200+n,175+u,s_oSpriteLibrary.getSprite("level_sprite"),!1,z+1)),0===z?f[z].addEventListenerWithParams(ON_MOUSE_UP,this._onClickHelp,this,z):f[z].addEventListenerWithParams(ON_MOUSE_UP,this._onClick,
this,z),s_bFirstTime=!0;q=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-q.height/2-10;d=q.height/2+10;l=new CGfxButton(b,d,q,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onExit,this);a=CANVAS_WIDTH-q.width/2-70;c=q.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=s_oSpriteLibrary.getSprite("audio_icon"),m=new CToggle(a,c,q,s_bAudioActive),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){for(var a=0;a<
h;a++)f[a].unload();s_oLevelMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(e,f){l.setPosition(b-e,f+d);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(a-e,f+c)};this._onNumModeToggle=function(a){a===NUM_ACTIVE?((void 0).setActive(!1),(void 0).setActive(!0)):((void 0).setActive(!0),(void 0).setActive(!1))};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onClick=function(a){playSound("but_press",1,0);f[a].ifClickable()&&
(s_oLevelMenu.unload(),s_oMain.gotoGame(a,0))};this._onClickHelp=function(a){playSound("but_press",1,0);f[a].ifClickable()&&(s_oLevelMenu.unload(),s_oMain.gotoHelp())};this._onExit=function(){s_oLevelMenu.unload();playSound("but_press",1,0);s_oMain.gotoMenu();$(s_oMain).trigger("end_level");$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CCar(a,c){var b,d=!1,e=!1,f=!1,g=!1,h=!1,k=!1,l=!1,m=!1,q=!1,n=0,u=0,z=0,r=0,A=.95,v=0,w=0,C=0,B=0,t=0,x=0,G=0,P=100,S=0,K=0,U=0,T=0,O=0,L,D,E,M,N,J,F,p,Q,H=s_oSpriteLibrary.getSprite("wheel"),I=s_oSpriteLibrary.getSprite("car_"+a),R,y;this.init=function(a,b){p=new createjs.Container;s_oStage.addChild(p);N=createBitmap(s_oSpriteLibrary.getSprite("rear_light"));N.x=I.width/4;N.y=I.height-2;p.addChild(N);J=createBitmap(s_oSpriteLibrary.getSprite("rear_light"));J.x=I.width-I.width/4-2;J.y=I.height-
2;p.addChild(J);N.visible=!1;J.visible=!1;b&&(L=createBitmap(H),L.x=5,L.y=20,L.regX=H.width/2,L.regY=H.height/2,p.addChild(L),D=createBitmap(H),D.x=I.width-5,D.y=20,D.regX=H.width/2,D.regY=H.height/2,p.addChild(D),E=createBitmap(H),E.x=5,E.y=I.height-20,E.regX=H.width/2,E.regY=H.height/2,p.addChild(E),M=createBitmap(H),M.x=I.width-5,M.y=I.height-20,M.regX=H.width/2,M.regY=H.height/2,p.addChild(M));F=createBitmap(I);p.addChild(F);p.regX=I.width/2;p.regY=35;S=P;p.visible=!0;switch(a){case 1:case 7:case 13:this.Car1init();
break;case 2:case 8:case 14:p.addChild(y);this.Car2init();break;case 3:case 9:case 15:this.Car3init();break;case 4:case 10:case 16:this.Car4init();break;case 5:case 11:case 17:this.Car5init();p.regY=40;break;case 6:case 12:case 18:this.Car6init(),p.regY=60,b&&(L.x=6,L.y=22,D.x=I.width-6,D.y=22,E.x=6,E.y=I.height-22,M.x=I.width-6,M.y=I.height-22)}p.rotation=G;d=!0};this.check=function(a){var b=p.localToGlobal(L.x,L.y),c=p.localToGlobal(D.x,D.y),d=p.localToGlobal(E.x,E.y),e=p.localToGlobal(M.x,M.y),
b=a.globalToLocal(b.x,b.y),c=a.globalToLocal(c.x,c.y),d=a.globalToLocal(d.x,d.y),e=a.globalToLocal(e.x,e.y);a=a.getBounds();a.contains(b.x,b.y)&&a.contains(c.x,c.y)&&a.contains(d.x,d.y)&&a.contains(e.x,e.y)&&(s_oGame.carParked(),m=!0)};this.Car1init=function(){u=28;z=-3;r=.45;w=2;C=.1;B=.98;O=15;K=40};this.Car2init=function(){u=8;z=-3;r=.25;w=2;C=.1;B=.98;O=10;K=40};this.Car3init=function(){u=8;z=-3;r=.25;w=2;C=.1;B=.98;O=10;K=40};this.Car4init=function(){u=28;z=-3;r=.45;w=2;C=.1;B=.98;O=15;K=40};
this.Car5init=function(){u=28;z=-3;r=.45;w=2;C=.1;B=.98;O=15;K=40};this.Car6init=function(){u=8;z=-3;r=.15;w=2;C=.1;B=.98;O=15;K=40};this.unload=function(){this.unload()};this.initInfo=function(a,b,c){p.x=U=a;p.y=T=b;p.rotation=G=c;Q=new CCollisionRectangle(I,p.x,p.y,p.regX,p.regY,p.rotation)};this._reset=function(){k=h=g=f=!1;x=t=v=n=0;A=.95;b=!1};this.resetPos=function(){this._reset();p.x=U;p.y=T;p.rotation=G;P=100;S=0};this.select=function(){l=!0;switch(a){case 1:case 7:case 13:case 2:case 8:case 14:case 3:case 9:case 15:R=
s_oSpriteLibrary.getSprite("select_car_1");var b={images:[R],framerate:20,frames:{width:76,height:130,regX:38,regY:50},animations:{idle:[0,19,"idle"]}},b=new createjs.SpriteSheet(b);y=createSprite(b,"idle",0,0,76,130);y.x=p.x;y.y=p.y;s_oStage.addChild(y);break;case 4:case 10:case 16:R=s_oSpriteLibrary.getSprite("select_car_2");b={images:[R],framerate:20,frames:{width:76,height:110,regX:38,regY:48},animations:{idle:[0,19,"idle"]}};b=new createjs.SpriteSheet(b);y=createSprite(b,"idle",0,0,76,110);y.x=
p.x;y.y=p.y;s_oStage.addChild(y);break;case 5:case 11:case 17:R=s_oSpriteLibrary.getSprite("select_car_4");b={images:[R],framerate:20,frames:{width:66,height:130,regX:33,regY:53},animations:{idle:[0,19,"idle"]}};b=new createjs.SpriteSheet(b);y=createSprite(b,"idle",0,0,66,130);y.x=p.x;y.y=p.y;s_oStage.addChild(y);break;case 6:case 12:case 18:R=s_oSpriteLibrary.getSprite("select_car_3"),b={images:[R],framerate:20,frames:{width:89,height:210,regX:44,regY:70},animations:{idle:[0,19,"idle"]}},b=new createjs.SpriteSheet(b),
y=createSprite(b,"idle",0,0,89,210),y.x=p.x,y.y=p.y,s_oStage.addChild(y)}y.rotation=G};this.moveLeft=function(a){a&&(k=!1);h=a};this.getX=function(){return y.x};this.getY=function(){return y.y};this.getRegX=function(){return p.regX};this.getRegY=function(){return p.regY};this.moveRight=function(a){a&&(h=!1);k=a};this.moveUp=function(a){a&&(g=!1);f=a};this.moveDown=function(a){a&&(f=!1);g=a};this.seeOnStage=function(a,b,c){c.addChild(F);F.x=a;F.y=b;F.regX=p.regX;F.regY=p.regY;F.rotation=p.rotation;
L.visible=!1;D.visible=!1;E.visible=!1;M.visible=!1};this.seeOnStageGameOver=function(b,c,d){d.addChild(F);F.regX=p.regX;F.regY=p.regY;6===a||12===a||18===a?(F.x=b+60,F.y=c+10,F.rotation=90):(F.x=b,F.y=c,F.rotation=p.rotation);L.visible=!1;D.visible=!1;E.visible=!1;M.visible=!1};this.getBitmap=function(){return F};this.getSpeed=function(){return n};this.getEnergy=function(){return S};this.isCrashing=function(){e||(S-=O*Math.abs(n),e=!0)};this.isDestroying=function(){return b};this.getEnergyPercLost=
function(){return S*P/100};this.isReady=function(){return d};this.getRectangle=function(){return Q.getBox()};this.getVector=function(a){return Q.prepareVector(a)};this.checkCollision=function(a,b){return Q.refresh(a,b)};this.update=function(){if(null!==J&&l){f&&n<u&&(n+=r,n>u&&(n=u));g&&n>z&&(n-=r,n<z&&(n=z));h&&(v-=C,v>w&&(v=w));k&&(v+=C,v<-w&&(v=-w));n*=A;n>-MIN_SPEED_OFFSET&&n<MIN_SPEED_OFFSET?(n=0,y.visible=!0):y.visible=!1;e&&(q||(n=-n,A-=.2,q=!0),n>-MIN_SPEED_OFFSET&&n<MIN_SPEED_OFFSET&&(n=
0,q=e=!1,A+=.2,s_oGame.setCanMoveTrue()));t=Math.sin(p.rotation*Math.PI/180)*n;x=Math.cos(p.rotation*Math.PI/180)*-n;0===n||-.09<t&&.09>t||(p.x+=t,y.x+=t);0===n||-.09<x&&.09>x||(p.y+=x,y.y+=x);.09>t&&-.09<t&&.09>x&&-.09<x&&!m&&s_oGame.checkDropArea();0>n?(J.visible=!0,N.visible=!0):(J.visible=!1,N.visible=!1);0<v?.05>v&&(v=0):0>v&&-.05<v&&(v=0);v*=B;v-=.1*v;var a=v*n;p.rotation+=a;y.rotation+=a;(0===n||-.09<t&&.09>t)&&(0===n||-.09<x&&.09>x)||(Q.move(t,x),Q.applySteering(a));a=K*v;L.rotation=a;D.rotation=
a}};this.init(a,c)}
function CSteeringWheel(a,c){var b,d,e,f,g;this._init=function(){b=a.x;d=a.y;var h=s_oSpriteLibrary.getSprite("steering_wheel");e=createBitmap(h);e.x=b;e.y=d;e.regX=h.width/2;e.regY=h.height/2;c.addChild(e);f=new createjs.Shape;f.graphics.beginFill("#ff0000").drawRect(0,0,100,130);f.x=b-100;f.y=d-65;f.alpha=.01;c.addChild(f);f.on("mousedown",this.onLeftSteeringWheelDown);f.on("pressup",this.onLeftSteeringWheelUp);g=new createjs.Shape;g.graphics.beginFill("#ff00ff").drawRect(0,0,100,130);g.x=b;g.y=
d-65;g.alpha=.01;c.addChild(g);g.on("mousedown",this.onRightSteeringWheelDown);g.on("pressup",this.onRightSteeringWheelUp)};this.setPosition=function(a,b){e.x=a;f.x=a-100;g.x=a};this.setScale=function(a){e.scaleX=a;e.scaleY=a};this.onLeftSteeringWheelDown=function(){createjs.Tween.get(e,{override:!0}).to({rotation:-90},500).call(function(){});s_oGame.onLeftSteeringWheelDown()};this.onLeftSteeringWheelUp=function(){createjs.Tween.get(e,{override:!0}).to({rotation:0},500).call(function(){});s_oGame.onLeftSteeringWheelUp()};
this.onRightSteeringWheelDown=function(){createjs.Tween.get(e,{override:!0}).to({rotation:90},500).call(function(){});s_oGame.onRightSteeringWheelDown()};this.onRightSteeringWheelUp=function(){createjs.Tween.get(e,{override:!0}).to({rotation:0},500).call(function(){});s_oGame.onRightSteeringWheelUp()};this.unload=function(){c.removeChildren(e,f,g);f.off("mousedown",this.onLeftSteeringWheelDown);f.off("pressup",this.onLeftSteeringWheelUp);g.off("mousedown",this.onRightSteeringWheelDown);g.off("pressup",
this.onRightSteeringWheelUp)};this._init()}
function CHelp(){var a=this,c,b,d,e,f,g,h,k,l,m,q;this._init=function(){c=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(c);b=new createjs.Container;b.alpha=0;c=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));s_oStage.addChild(c);d=new createjs.Text(""," 25px "+FONT,"#730358");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2+70;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=400;d.outline=3;b.addChild(d);e=new createjs.Text(""," 25px "+FONT,"#ffffff");e.x=CANVAS_WIDTH/
2;e.y=CANVAS_HEIGHT/2+70;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=400;b.addChild(e);if(s_bMobile){d.text=TEXT_MOVE_MOBILE;d.x-=200;d.y+=40;e.text=TEXT_MOVE_MOBILE;e.x-=200;e.y+=40;var a=s_oSpriteLibrary.getSprite("steering_wheel");f=createBitmap(a);f.x=CANVAS_WIDTH/2-200;f.y=CANVAS_HEIGHT/2-40;f.regX=a.width/2;f.regY=a.height/2;g=createBitmap(s_oSpriteLibrary.getSprite("help_touch"));g.x=CANVAS_WIDTH/2-230;g.y=CANVAS_HEIGHT/2-40;b.addChild(f,g);this.moveCursorRight();a=new createjs.Text(TEXT_MOVE_MOBILE2,
" 25px "+FONT,"#730358");a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2+110;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=400;a.outline=3;b.addChild(a);a=new createjs.Text(TEXT_MOVE_MOBILE2," 25px "+FONT,"#ffffff");a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2+110;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=400;b.addChild(a);a=s_oSpriteLibrary.getSprite("accelerator");k=new CToggle(CANVAS_WIDTH/2,CANVAS_HEIGHT/2-50,a,!0);l=createBitmap(s_oSpriteLibrary.getSprite("help_touch"));l.x=
CANVAS_WIDTH/2-30;l.y=CANVAS_HEIGHT/2-80;b.addChild(l);this.pressAccelerator();a=new createjs.Text(TEXT_MOVE_MOBILE1," 25px "+FONT,"#730358");a.x=CANVAS_WIDTH/2+200;a.y=CANVAS_HEIGHT/2+100;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=400;a.outline=3;b.addChild(a);a=new createjs.Text(TEXT_MOVE_MOBILE1," 25px "+FONT,"#ffffff");a.x=CANVAS_WIDTH/2+200;a.y=CANVAS_HEIGHT/2+100;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=400;b.addChild(a);a=s_oSpriteLibrary.getSprite("breacker");
m=new CToggle(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2-50,a,!0);q=createBitmap(s_oSpriteLibrary.getSprite("help_touch"));q.x=CANVAS_WIDTH/2+170;q.y=CANVAS_HEIGHT/2-80;b.addChild(q);this.pressReverse()}else d.text=TEXT_MOVE_DESKTOP,e.text=TEXT_MOVE_DESKTOP,f=createBitmap(s_oSpriteLibrary.getSprite("arrow_keys")),f.x=CANVAS_WIDTH/2-100,f.y=CANVAS_HEIGHT/2-130,b.addChild(f);a=s_oSpriteLibrary.getSprite("but_play");h=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+180,a);h.setScale(.5);s_oStage.addChild(b);this.show()};
this._initListener=function(){h.addEventListener(ON_MOUSE_UP,this._onExit,this)};this.moveCursorRight=function(){var a=this;g.scaleX=1;g.scaleY=1;createjs.Tween.get(f).to({rotation:0},1E3).call(function(){});createjs.Tween.get(g).to({x:CANVAS_WIDTH/2-180},1E3).call(function(){g.scaleX=.9;g.scaleY=.9;createjs.Tween.get(f).to({rotation:90},1E3).call(function(){a.moveCursorLeft()})})};this.moveCursorLeft=function(){var a=this;g.scaleX=1;g.scaleY=1;createjs.Tween.get(f).to({rotation:0},1E3).call(function(){});
createjs.Tween.get(g).to({x:CANVAS_WIDTH/2-270},1E3).call(function(){g.scaleX=.9;g.scaleY=.9;createjs.Tween.get(f).to({rotation:-90},1E3).call(function(){a.moveCursorRight()})})};this.pressAccelerator=function(){var a=this;createjs.Tween.get(l).to({scaleX:.9,scaleY:.9},1E3).call(function(){k.setActive(!1);setTimeout(function(){a.releaseAccelerator()},1E3)})};this.releaseAccelerator=function(){var a=this;k.setActive(!0);createjs.Tween.get(l).to({scaleX:1,scaleY:1},1E3).call(function(){a.pressAccelerator()})};
this.pressReverse=function(){var a=this;createjs.Tween.get(q).to({scaleX:.9,scaleY:.9},1E3).call(function(){m.setActive(!1);setTimeout(function(){a.releaseReverse()},1E3)})};this.releaseReverse=function(){var a=this;m.setActive(!0);createjs.Tween.get(q).to({scaleX:1,scaleY:1},1E3).call(function(){a.pressReverse()})};this.show=function(){createjs.Tween.get(b).to({alpha:1},500).call(function(){a._initListener()})};this._onExit=function(){playSound("press_button",1,0);a.unload();s_oMain.gotoGame(0,0)};
this.unload=function(){createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this._init();return this}
function CCreditsPanel(){var a,c,b,d,e,f,g,h,k;this._init=function(){k=new createjs.Container;s_oStage.addChild(k);var l=new createjs.Shape;l.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.alpha=.5;k.addChild(l);l=s_oSpriteLibrary.getSprite("msg_box");a=createBitmap(l);k.addChild(a);a.x=.5*CANVAS_WIDTH;a.y=.5*CANVAS_HEIGHT;a.regX=.5*l.width;a.regY=.5*l.height;f=new createjs.Shape;f.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=.01;f.on("click",
this._onLogoButRelease);s_bMobile||(f.cursor="pointer");k.addChild(f);l=s_oSpriteLibrary.getSprite("but_exit");b=new CGfxButton(970,110,l,k);b.addEventListener(ON_MOUSE_UP,this.unload,this);e=new createjs.Text(TEXT_CREDITS_DEVELOPED,"28px "+FONT,"#000");e.textAlign="center";e.textBaseline="alphabetic";e.x=CANVAS_WIDTH/2;e.y=220;e.outline=3;k.addChild(e);d=new createjs.Text(TEXT_CREDITS_DEVELOPED,"28px "+FONT,"#600101");d.textAlign="center";d.textBaseline="alphabetic";d.x=CANVAS_WIDTH/2;d.y=e.y;k.addChild(d);
l=s_oSpriteLibrary.getSprite("logo_ctl");c=createBitmap(l);c.regX=l.width/2;c.regY=l.height/2;c.x=CANVAS_WIDTH/2;c.y=280;k.addChild(c);h=new createjs.Text("www.codethislab.com","32px "+FONT,"#000");h.textAlign="center";h.textBaseline="alphabetic";h.x=CANVAS_WIDTH/2;h.y=360;h.outline=3;k.addChild(h);g=new createjs.Text("www.codethislab.com","32px "+FONT,"#600101");g.textAlign="center";g.textBaseline="alphabetic";g.x=CANVAS_WIDTH/2;g.y=h.y;k.addChild(g);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};
this.refreshButtonPos=function(a,b){};this.unload=function(){playSound("click",1,0);f.off("click",this._onLogoButRelease);b.unload();b=null;s_oStage.removeChild(k)};this._onLogoButRelease=function(){playSound("click",1,0);window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()};
