var s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var b=a.toLowerCase(),d=window.document,c=d.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var e=d.createElement("body");e.id="vpw-test-b";e.style.cssText="overflow:scroll";var f=d.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+b+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+b+":7px!important}}</style>";e.appendChild(f);c.insertBefore(e,d.head);
a=7==f["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(e)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return!0;return!1}
function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var b=getSize("Width");_checkOrientation(b,a);var d=Math.min(a/CANVAS_HEIGHT,b/CANVAS_WIDTH),c=CANVAS_WIDTH*d,d=CANVAS_HEIGHT*d,e;d<a?(e=a-d,d+=e,c+=CANVAS_WIDTH/CANVAS_HEIGHT*e):c<b&&(e=b-c,c+=e,d+=CANVAS_HEIGHT/CANVAS_WIDTH*e);e=a/2-d/2;var f=b/2-c/2,g=CANVAS_WIDTH/c;if(f*g<-EDGEBOARD_X||e*g<-EDGEBOARD_Y)d=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),
b/(CANVAS_WIDTH-2*EDGEBOARD_X)),c=CANVAS_WIDTH*d,d*=CANVAS_HEIGHT,e=(a-d)/2,f=(b-c)/2,g=CANVAS_WIDTH/c;s_iOffsetX=-1*f*g;s_iOffsetY=-1*e*g;0<=e&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile?($("#canvas").css("width",c+"px"),$("#canvas").css("height",d+"px")):(s_oStage.canvas.width=c,s_oStage.canvas.height=d,s_oStage.scaleX=s_oStage.scaleY=Math.min(c/CANVAS_WIDTH,
d/CANVAS_HEIGHT));0>e?$("#canvas").css("top",e+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",f+"px")}}
function _checkOrientation(a,b){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>b?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function createBitmap(a,b,d){var c=new createjs.Bitmap(a),e=new createjs.Shape;b&&d?e.graphics.beginFill("#fff").drawRect(0,0,b,d):e.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=e;return c}function createSprite(a,b,d,c,e,f){a=null!==b?new createjs.Sprite(a,b):new createjs.Sprite(a);b=new createjs.Shape;b.graphics.beginFill("#000000").drawRect(-d,-c,e,f);a.hitArea=b;return a}
function randomFloatBetween(a,b,d){"undefined"===typeof d&&(d=2);return parseFloat(Math.min(a+Math.random()*(b-a),b).toFixed(d))}function shuffle(a){for(var b=a.length,d,c;0!==b;)c=Math.floor(Math.random()*b),--b,d=a[b],a[b]=a[c],a[c]=d;return a}function formatTime(a){a/=1E3;var b=Math.floor(a/60);a=parseFloat(a-60*b).toFixed(1);var d="",d=10>b?d+("0"+b+":"):d+(b+":");return 10>a?d+("0"+a):d+a}
Array.prototype.sortOn=function(){var a=this.slice();if(!arguments.length)return a.sort();var b=Array.prototype.slice.call(arguments);return a.sort(function(a,c){for(var d=b.slice(),f=d.shift();a[f]==c[f]&&d.length;)f=d.shift();return a[f]==c[f]?0:a[f]>c[f]?1:-1})};function roundDecimal(a,b){var d=Math.pow(10,b);return Math.round(d*a)/d}function tweenVectors(a,b,d,c){c.set(a.getX()+d*(b.getX()-a.getX()),a.getY()+d*(b.getY()-a.getY()));return c}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var b=document.createEvent("MouseEvents");b.initEvent("click",!0,!0);a.dispatchEvent(b)}}};function playSound(a,b,d){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:d,volume:b}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}
function setVolume(a,b){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=b}function setMute(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(b)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var b=window.location.search.substring(1).split("&"),d=0;d<b.length;d++){var c=b[d].split("=");if(c[0]==a)return c[1]}}
function CSpriteLibrary(){var a,b,d,c,e,f;this.init=function(g,m,n){d=b=0;c=g;e=m;f=n;a={}};this.addSprite=function(c,d){a.hasOwnProperty(c)||(a[c]={szPath:d,oSprite:new Image},b++)};this.getSprite=function(c){return a.hasOwnProperty(c)?a[c].oSprite:null};this._onSpritesLoaded=function(){e.call(f)};this._onSpriteLoaded=function(){c.call(f);++d===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var c in a)a[c].oSprite.oSpriteLibrary=this,a[c].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[c].oSprite.src=a[c].szPath};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=1700,CANVAS_HEIGHT=768,EDGEBOARD_X=250,EDGEBOARD_Y=0,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,FONT_GAME_1="arialbold",FONT_GAME_2="Digital-7",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_GAME_WAITING_FOR_BET=0,STATE_GAME_DEALING=1,STATE_GAME_PLAYER_TURN=2,STATE_GAME_SPLIT_HAND=3,STATE_GAME_SHOWDOWN=4,STATE_GAME_DISTRIBUTE_FICHES=5,STATE_GAME_SHOW_WINNER=6,STATE_CARD_DEALING=0,STATE_CARD_WAIT_USER=1,STATE_CARD_SPLITTING=2,STATE_CARD_REMOVING=3,ON_MOUSE_DOWN=
0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ASSIGN_FICHES="ASSIGN_FICHES",END_HAND="END_HAND",ON_CARD_SHOWN="ON_CARD_SHOWN",ON_CARD_ANIMATION_ENDING="ON_CARD_ANIMATION_ENDING",ON_CARD_TO_REMOVE="ON_CARD_TO_REMOVE",SPLIT_CARD_END_ANIM="SPLIT_CARD_END_ANIM",NUM_FICHES=6,CARD_WIDTH=66,CARD_HEIGHT=102,MIN_BET,MAX_BET,TOTAL_MONEY,FICHE_WIDTH,WIN_OCCURRENCE,BET_OCCURRENCE,TIME_FICHES_MOV=600,TIME_CARD_DEALING=250,TIME_CARD_REMOVE=1E3,TIME_CARD_SPLIT=500,TIME_SHOW_FINAL_CARDS=
4E3,TIME_END_HAND,BET_TIME=1E4,AD_SHOW_COUNTER,NUM_DECKS=4,PAYOUT_MULT,ROYAL_FLUSH=0,STRAIGHT_FLUSH=1,FOUR_OF_A_KIND=2,FULL_HOUSE=3,FLUSH=4,STRAIGHT=5,THREE_OF_A_KIND=6,TWO_PAIR=7,ONE_PAIR=8,HIGH_CARD=9,NO_HAND=10,CARD_TWO=2,CARD_THREE=3,CARD_FOUR=4,CARD_FIVE=5,CARD_SIX=6,CARD_SEVEN=7,CARD_EIGHT=8,CARD_NINE=9,CARD_TEN=10,CARD_JACK=11,CARD_QUEEN=12,CARD_KING=13,CARD_ACE=14,POS_BET,MULTIPLIERS=[],ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,TEXT_DEAL="DEAL",TEXT_MIN_BET="MIN BET",TEXT_MAX_BET="MAX BET",
TEXT_RECHARGE="RECHARGE",TEXT_EXIT="EXIT",TEXT_MONEY="MONEY",TEXT_CURRENCY="$",TEXT_FOLD="FOLD",TEXT_HIGH_HAND="HIGH HAND",TEXT_LOW_HAND="LOW HAND",TEXT_HOUSE_WAY="HOUSE WAY",TEXT_DISPLAY_MSG_WAITING_BET="WAITING FOR YOUR BET",TEXT_DISPLAY_MSG_PLAYER_LOSE="PLAYER LOSES THIS HAND!",TEXT_DISPLAY_MSG_STANDOFF="PUSH",TEXT_DISPLAY_MSG_PLAYER_WIN="PLAYER WINS",TEXT_DISPLAY_MSG_USER_TURN="SELECT 5 CARDS FOR HIGH HAND OR USE AUTOMATIC HOUSE WAY!",TEXT_DISPLAY_MSG_SHOWDOWN="SHOWDOWN!",TEXT_DISPLAY_MSG_DEALING=
"DEALING...",TEXT_NO_MONEY="YOU DON'T HAVE ENOUGH MONEY!!!",TEXT_HAND_WON_PLAYER="HAND WON BY THE PLAYER",TEXT_HAND_WON_DEALER="HAND WON BY THE DEALER",TEXT_ERROR_MIN_BET="YOUR BET IS LOWER THAN MINIMUM BET!!",TEXT_ERROR_MAX_BET="YOUR BET IS HIGHER THAN MAXIMUM BET!!",TEXT_EVALUATOR="ROYAL FLUSH;STRAIGHT FLUSH;FOUR OF A KIND;FULL HOUSE;FLUSH;STRAIGHT;THREE OF A KIND;TWO PAIR;ONE PAIR;HIGH CARD;NO HAND".split(";"),TEXT_SHARE_IMAGE="200x200.jpg",TEXT_SHARE_TITLE="Congratulations!",TEXT_SHARE_MSG1="You collected <strong>",
TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!",TEXT_SHARE_SHARE1="My score is ",TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var a,b,d,c,e;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_preloader","./sprites/bg_preloader.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();e=new createjs.Container;s_oStage.addChild(e)};this.unload=function(){e.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var f=createBitmap(s_oSpriteLibrary.getSprite("bg_preloader"));e.addChild(f);d=createBitmap(s_oSpriteLibrary.getSprite("progress_bar"));d.x=599;d.y=CANVAS_HEIGHT-50;e.addChild(d);a=476;c=new createjs.Shape;c.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(599,CANVAS_HEIGHT-50,1,30);e.addChild(c);d.mask=c;b=new createjs.Text("0%","30px "+FONT_GAME_1,"#fff");b.x=638;b.y=CANVAS_HEIGHT-56;b.textAlign="center";b.textBaseline="middle";e.addChild(b)};this.refreshLoader=function(d){b.text=
d+"%";d=Math.floor(d*a/100);c.graphics.clear();c.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(599,CANVAS_HEIGHT-50,d,30)};this._init()}
function CMain(a){var b,d=0,c=0,e=STATE_LOADING,f,g,m;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(FPS);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader;
s_oGameSettings=new CGameSettings;b=!0};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds()};this.soundLoaded=function(){d++;g.refreshLoader(Math.floor(d/c*100));d===c&&(g.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,
this)),createjs.Sound.registerSound("./sounds/card.ogg","card"),createjs.Sound.registerSound("./sounds/chip.ogg","chip"),createjs.Sound.registerSound("./sounds/fiche_collect.ogg","fiche_collect"),createjs.Sound.registerSound("./sounds/press_but.ogg","press_but"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/lose.ogg","lose")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),
createjs.Sound.registerSound("./sounds/card.mp3","card",4),createjs.Sound.registerSound("./sounds/chip.mp3","chip",4),createjs.Sound.registerSound("./sounds/fiche_collect.mp3","fiche_collect"),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/lose.mp3","lose")),c+=6)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_menu_bg",
"./sprites/but_menu_bg.png");s_oSpriteLibrary.addSprite("but_game_bg","./sprites/but_game_bg.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("card_spritesheet","./sprites/card_spritesheet.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("display_bg",
"./sprites/display_bg.png");s_oSpriteLibrary.addSprite("fiche_highlight","./sprites/fiche_highlight.png");s_oSpriteLibrary.addSprite("win_bg","./sprites/win_bg.png");s_oSpriteLibrary.addSprite("but_clear","./sprites/but_clear.png");s_oSpriteLibrary.addSprite("but_generic","./sprites/but_generic.png");s_oSpriteLibrary.addSprite("but_rebet","./sprites/but_rebet.png");s_oSpriteLibrary.addSprite("gui_bg","./sprites/gui_bg.png");s_oSpriteLibrary.addSprite("bet_ante","./sprites/bet_ante.png");s_oSpriteLibrary.addSprite("help_cursor",
"./sprites/help_cursor.png");s_oSpriteLibrary.addSprite("but_split","./sprites/but_split.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");for(var a=0;a<NUM_FICHES;a++)s_oSpriteLibrary.addSprite("fiche_"+a,"./sprites/fiche_"+a+".png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){d++;g.refreshLoader(Math.floor(d/c*100));d===c&&(g.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=
function(){this._loadImages()};this.gotoMenu=function(){new CMenu;e=STATE_MENU};this.gotoGame=function(){m=new CGame(f);e=STATE_GAME};this.gotoHelp=function(){new CHelp;e=STATE_HELP};this.stopUpdate=function(){b=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();b=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=function(a){if(b){var c=
(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&m.update();s_oStage.update(a)}};s_oMain=this;f=a;ENABLE_CHECK_ORIENTATION=a.check_orientation;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_bFullscreen=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oGameSettings;
function CTextButton(a,b,d,c,e,f,g,m){var n,k,h,l,x,v,w,z;this._init=function(a,c,b,d,e,f,g,m){n=!1;k=[];h=[];z=m;x=createBitmap(b);m=Math.ceil(g/20);v=new createjs.Text(d,g+"px "+e,"#000000");var p=v.getBounds();v.textAlign="center";v.textBaseline="alphabetic";v.x=b.width/2+m;v.y=Math.floor(b.height/2)+p.height/3+m;w=new createjs.Text(d,g+"px "+e,f);w.textAlign="center";w.textBaseline="alphabetic";w.x=b.width/2;w.y=Math.floor(b.height/2)+p.height/3;l=new createjs.Container;l.x=a;l.y=c;l.regX=b.width/
2;l.regY=b.height/2;l.cursor="pointer";l.addChild(x,w);z.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");z.removeChild(l)};this.setVisible=function(a){l.visible=a};this.enable=function(){n=!1;w.color="#fff"};this.disable=function(){n=!0;w.color="#a39b9d"};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){k[a]=c;h[a]=b};this.buttonRelease=function(){n||(!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||playSound("press_but",1,0),l.scaleX=1,l.scaleY=1,k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(h[ON_MOUSE_UP]))};this.buttonDown=function(){n||(l.scaleX=.9,l.scaleY=.9,k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN]))};this.setPosition=function(a,c){l.x=a;l.y=c};this.changeText=function(a){w.text=a;v.text=a};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};
this._init(a,b,d,c,e,f,g,m);return this}
function CGfxButton(a,b,d,c){var e,f,g,m,n,k=[],h,l;this._init=function(a,c,b){e=!1;m=[];n=[];f=b.width;g=b.height;h=createBitmap(b);h.x=a;h.y=c;h.regX=b.width/2;h.regY=b.height/2;h.cursor="pointer";l.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);l.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=
function(a,c,b){m[a]=c;n[a]=b};this.addEventListenerWithParams=function(a,c,b,d){m[a]=c;n[a]=b;k=d};this.buttonRelease=function(){e||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||playSound("press_but",1,0),m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(n[ON_MOUSE_UP],k))};this.buttonDown=function(){e||m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN],k)};this.setPosition=function(a,c){h.x=a;h.y=c};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.enable=function(){e=!1;h.filters=[];h.cache(0,
0,f,g)};this.disable=function(){e=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100);h.filters=[new createjs.ColorMatrixFilter(a)];h.cache(0,0,f,g)};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};l=c;this._init(a,b,d);return this}
function CToggle(a,b,d,c,e){var f,g,m,n,k=[],h;this._init=function(a,c,b,d,e){m=[];n=[];var l=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}});f=d;g=e;h=createSprite(l,"state_"+f,b.width/2/2,b.height/2,b.width/2,b.height);h.x=a;h.y=c;h.cursor="pointer";h.stop();s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);
s_oStage.removeChild(h)};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){m[a]=c;n[a]=b};this.addEventListenerWithParams=function(a,c,b,d){m[a]=c;n[a]=b;k=d};this.setActive=function(a){f=a;h.gotoAndStop("state_"+f)};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;playSound("press_button",1,0);g&&(f=!f,h.gotoAndStop("state_"+f));m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(n[ON_MOUSE_UP],k)};this.buttonDown=function(){h.scaleX=
.9;h.scaleY=.9;m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN],k)};this.setPosition=function(a,c){h.x=a;h.y=c};this.setVisible=function(a){h.visible=a};this.getY=function(){return h.y};this._init(a,b,d,c,e)}
function CMenu(){var a,b,d,c,e,f,g,m,n,k=null,h=null;this._init=function(){e=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(e);var l=s_oSpriteLibrary.getSprite("but_menu_bg");f=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-164,l,s_oStage);f.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l=s_oSpriteLibrary.getSprite("audio_icon"),d=CANVAS_WIDTH-l.width/4-10,c=l.height/2+10,g=new CToggle(d,c,l,s_bAudioActive,!0),g.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);var l=window.document,x=l.documentElement;k=x.requestFullscreen||x.mozRequestFullScreen||x.webkitRequestFullScreen||x.msRequestFullscreen;h=l.exitFullscreen||l.mozCancelFullScreen||l.webkitExitFullscreen||l.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(k=!1);k&&!1===inIframe()&&(l=s_oSpriteLibrary.getSprite("but_fullscreen"),a=l.width/4+10,b=l.height/2+10,n=new CToggle(a,b,l,s_bFullscreen,!0),n.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));m=new createjs.Shape;
m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(m);createjs.Tween.get(m).to({alpha:0},400).call(function(){m.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(e,f){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||g.setPosition(d-e,f+c);k&&!1===inIframe()&&n.setPosition(a+e,b+f)};this.unload=function(){f.unload();f=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),g=null;k&&!1===inIframe()&&n.unload();s_oStage.removeAllChildren();
s_oMenu=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame();$(s_oMain).trigger("start_session")};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?(h.call(window.document),s_bFullscreen=!1):(k.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var b=!1,d,c,e,f,g,m,n,k,h,l,x,v,w,z,p,D,G,A,B,F,H,K,y,I,J,E,N,C,u,r,O,M,P,T,U,V,R,L,Q,X,t,q,S,W;this._init=function(){e=MAX_BET;f=-1;g=x=c=0;s_oTweenController=new CTweenController;X=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(X);t=new CInterface(TOTAL_MONEY);R=new createjs.Container;s_oStage.addChild(R);L=new CHandEvaluator;q=new CSeat;q.setCredit(TOTAL_MONEY);Q=new CHelpCursor(620,390,s_oSpriteLibrary.getSprite("help_cursor"),s_oStage);this.reset(!1);
r=new CVector2;r.set(1214,228);O=new CVector2(CANVAS_WIDTH/2-115,250);U=new CVector2(O.getX()-65,O.getY());V=new CVector2(O.getX()+215,O.getY());M=new CVector2;M.set(418,820);P=new CVector2;P.set(0,-CANVAS_HEIGHT);T=new CVector2(454,230);W=new CGameOver;q.getCredit()<s_oGameSettings.getFichesValueAt(0)?(this._gameOver(),this.changeState(-1)):b=!0;u=new CVector2(r.getX(),r.getY());S=new CMsgBox;this.changeState(STATE_GAME_WAITING_FOR_BET)};this.unload=function(){b=!1;!1!==DISABLE_SOUND_MOBILE&&!1!==
s_bMobile||createjs.Sound.stop();for(var a=0;a<y.length;a++)y[a].unload();t.unload();W.unload();S.unload();s_oStage.removeAllChildren()};this.reset=function(a){l=n=g=c=0;q.reset();y=[];y.splice(0);I=[];E=[];t.reset();t.enableBetFiches(a);this.shuffleCard()};this.shuffleCard=function(){J=[];J=s_oGameSettings.getShuffledCardDeck()};this.changeState=function(a){f=a;switch(a){case STATE_GAME_WAITING_FOR_BET:t.displayMsg(TEXT_DISPLAY_MSG_WAITING_BET,TEXT_MIN_BET+": "+MIN_BET+TEXT_CURRENCY+"\n"+TEXT_MAX_BET+
": "+MAX_BET+TEXT_CURRENCY);break;case STATE_GAME_DEALING:t.disableButtons();t.displayMsg(TEXT_DISPLAY_MSG_DEALING);this._dealing();break;case STATE_GAME_SHOWDOWN:this._showHandEvaluation()}};this.cardFromDealerArrived=function(a,c,b){!1===c&&a.showCard();14>b&&s_oGame._dealing()};this._cardSplitted=function(a,c){12===c?(h=0,I[0].showCard()):13===c&&s_oGame.changeState(STATE_GAME_SHOWDOWN)};this._showHandEvaluation=function(){t.refreshHandValueText(TEXT_EVALUATOR[v],TEXT_EVALUATOR[z],TEXT_EVALUATOR[w],
TEXT_EVALUATOR[p]);this._showWin()};this._showWin=function(){var a=0;"player"===D?(playSound("win",1,0),d?(a=2*q.getBetAnte()-.05*q.getBetAnte(),this._playerWin(a)):(a=q.getBetAnte(),this._standOff(a))):"dealer"===D&&(playSound("lose",1,0),d?(a=q.getBetAnte(),this._standOff(a)):this._playerLose());this.changeState(STATE_GAME_DISTRIBUTE_FICHES);t.refreshCredit(q.getCredit());setTimeout(function(){q.resetBet();s_oGame.changeState(STATE_GAME_WAITING_FOR_BET);t.enableBetFiches(!0)},3*TIME_CARD_REMOVE)};
this._playerWin=function(a){q.increaseCredit(a);k-=a;t.displayMsg(TEXT_DISPLAY_MSG_SHOWDOWN,TEXT_DISPLAY_MSG_PLAYER_WIN+" "+a+TEXT_CURRENCY);q.initMovement(0,M.getX(),M.getY());q.initMovement(1,M.getX(),M.getY());t.showResultText(TEXT_HAND_WON_PLAYER)};this._playerLose=function(){t.displayMsg(TEXT_DISPLAY_MSG_SHOWDOWN,TEXT_DISPLAY_MSG_PLAYER_LOSE);q.initMovement(0,P.getX(),P.getY());q.initMovement(1,P.getX(),P.getY());t.showResultText(TEXT_HAND_WON_DEALER)};this._standOff=function(a){q.increaseCredit(a);
k-=a;t.displayMsg(TEXT_DISPLAY_MSG_SHOWDOWN,TEXT_DISPLAY_MSG_STANDOFF);q.initMovement(0,M.getX(),M.getY());q.initMovement(1,M.getX(),M.getY());t.showResultText("\n"+TEXT_DISPLAY_MSG_STANDOFF)};this._dealing=function(){if(14>n){var a=new CCard(r.getX(),r.getY(),R),c;if(1===n%2){c=new CVector2(O.getX()+CARD_WIDTH/4*n,O.getY());var b=C.splice(0,1),d=b[0].fotogram,e=b[0].rank,b=b[0].suit;a.setInfo(u,c,d,e,b,!0,n);a.addEventListener(ON_CARD_SHOWN,this._onCardShown);I.push(a)}else b=N.splice(0,1),d=b[0].fotogram,
e=b[0].rank,b=b[0].suit,a.setInfo(u,q.getAttachCardOffset(),d,e,b,!1,n),q.newCardDealed(),E.push(a);y.push(a);n++;a.addEventListener(ON_CARD_ANIMATION_ENDING,this.cardFromDealerArrived);a.addEventListener(SPLIT_CARD_END_ANIM,this._cardSplitted);playSound("card",1,0)}else setTimeout(function(){s_oGame.changeState(STATE_GAME_PLAYER_TURN);t.displayMsg(TEXT_DISPLAY_MSG_USER_TURN);t.disableDeal(!0)},1E3)};this._onEndHand=function(){for(var a=new CVector2(T.getX(),T.getY()),b=0;b<y.length;b++)y[b].initRemoving(a),
y[b].hideCard();t.clearCardValueText();t.clearHandValueText();c=0;s_oGame.changeState(STATE_GAME_SHOW_WINNER);playSound("fiche_collect",1,0);x++;x===AD_SHOW_COUNTER&&(x=0,$(s_oMain).trigger("show_interlevel_ad"));$(s_oMain).trigger("save_score",[q.getCredit()])};this._onCardShown=function(){if(7===h){for(var a=U.getX(),c=U.getY(),b=I[0].getChildIndex(),d=0;d<H.length;d++)I[H[d].index].initSplit(a,c,b),a+=CARD_WIDTH/2,b++;a=V.getX();c=V.getY();for(d=0;d<B.length;d++)I[B[d].index].initSplit(a,c,b),
a+=CARD_WIDTH/2,b++;s_oGame.changeState(STATE_GAME_SPLIT_HAND)}else s_oGame._showNextDealerCard()};this.setBet=function(a){if(t.isResultPanelvisible())t.disableBetFiches(),q.clearBet(),K=this.setBet,this._onEndHand();else{a=s_oGameSettings.getFichesValues()[a];var b;c=0;Q.hide();b=q.getBetAnte()+a;b>e?S.show(TEXT_ERROR_MAX_BET):b>q.getCredit()?t.displayMsg(TEXT_NO_MONEY):(q.decreaseCredit(a),k+=a,q.betAnte(a),t.enable(!0,!1,!1),t.refreshCredit(q.getCredit()))}};this.cardSelected=function(a){a?l++:
l--;5===l?t.enableSplit(!0):t.enableSplit(!1)};this._gameOver=function(){W.show()};this.onRebet=function(){t.isResultPanelvisible()&&(K=this.rebet,this._onEndHand(),Q.hide())};this.onDeal=function(){if(q.getBetAnte()<MIN_BET)S.show(TEXT_ERROR_MIN_BET),t.enableBetFiches(!1),t.enable(!1,!1,!1);else{R.removeAllChildren();m=2*q.getBetAnte();if((k<m?WIN_OCCURRENCE+1:Math.floor(101*Math.random()))>WIN_OCCURRENCE){do this._generateRandomCards();while("player"===D&&d)}else{do this._generateRandomCards();
while("player"!==D||!d)}q.setPrevBet();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("card");this.changeState(STATE_GAME_DEALING)}};this._generateRandomCards=function(){N=this._generateRandCards();G=[];this._findHandCombinations(N,5,0,[]);var a=this.getBestHand();F=a.hand;v=a.res;a=this._split7Hand(v,F,N);A=a.low_hand;F=a.high_hand;C=this._generateRandCards();G=[];this._findHandCombinations(C,5,0,[]);a=this.getBestHand();H=a.hand;w=a.res;a=this._split7Hand(w,H,C);B=a.low_hand;H=a.high_hand;
d=this._compareLowHands();a=L.getWinnerComparingHands(F,H);D=a.res;v=a.player_value;w=a.dealer_value};this.getBestHand=function(){for(var a=NO_HAND,c=G[0],b=0;b<G.length;b++){var d=L.evaluate(G[b]);d.ret<a&&(a=d.ret,c=d.sort_hand)}return{res:a,hand:c}};this._findHandCombinations=function(a,c,b,d){if(0===c){a=[];for(c=0;c<d.length;c++)a[c]=d[c];G.push(a)}else for(;b<=a.length-c;b++)d[Math.abs(c-5)]=a[b],this._findHandCombinations(a,c-1,b+1,d)};this._compareLowHands=function(){A=L.sortCards(A);B=L.sortCards(B);
if(A[0].rank===A[1].rank){z=ONE_PAIR;if(B[0].rank===B[1].rank)return p=ONE_PAIR,A[0].rank>B[0].rank?!0:!1;p=HIGH_CARD;return!0}z=HIGH_CARD;if(B[0].rank===B[1].rank)return p=ONE_PAIR,!1;p=HIGH_CARD;return A[1].rank>B[1].rank?!0:!1};this._split7Hand=function(a,c,b){var d=[],e=[];switch(a){case ROYAL_FLUSH:case STRAIGHT_FLUSH:case STRAIGHT:case FLUSH:for(a=0;a<c.length;a++)d.push(c[a]);b=this._fillHandWithRemaining(b,d,e);d=b.high;e=b.low;break;case FOUR_OF_A_KIND:7>c[1].rank?(c[1].rank===c[0].rank?
(d.push(c[0]),d.push(c[1]),d.push(c[2]),d.push(c[3])):(d.push(c[1]),d.push(c[2]),d.push(c[3]),d.push(c[4])),c=this.getRemainingCards(b,d,e),c=L.sortCards(c),e.push(c[c.length-1])):(c[1].rank===c[0].rank?(d.push(c[0]),d.push(c[1]),e.push(c[2]),e.push(c[3])):(d.push(c[1]),d.push(c[2]),e.push(c[3]),e.push(c[4])),c=this.getRemainingCards(b,d,e),c=L.sortCards(c),d.push(c[c.length-1]));b=this._fillHandWithRemaining(b,d,e);d=b.high;e=b.low;break;case FULL_HOUSE:c[2].rank>c[1].rank?(d.push(c[2]),d.push(c[3]),
d.push(c[4]),e.push(c[0]),e.push(c[1])):(d.push(c[0]),d.push(c[1]),d.push(c[2]),e.push(c[3]),e.push(c[4]));b=this._fillHandWithRemaining(b,d,e);d=b.high;e=b.low;break;case THREE_OF_A_KIND:a=[];c[2].rank===c[1].rank&&c[0].rank===c[1].rank?(a.push(c[0]),a.push(c[1]),a.push(c[2])):c[2].rank===c[1].rank&&c[2].rank===c[3].rank?(a.push(c[1]),a.push(c[2]),a.push(c[3])):(a.push(c[2]),a.push(c[3]),a.push(c[4]));a[0].rank===CARD_ACE?(d.push(a[0]),d.push(a[1]),e.push(a[2])):(d.push(a[0]),d.push(a[1]),d.push(a[2]));
b=this._fillHandWithRemaining(b,d,e);d=b.high;e=b.low;break;case TWO_PAIR:var f=a=0,h=2,g=[],m=[];c[0].rank===c[1].rank?(a=c[0].rank,g.push(c[0]),g.push(c[1])):c[1].rank===c[2].rank&&(a=c[1].rank,g.push(c[1]),g.push(c[2]),h=c[0].rank);c[2].rank===c[3].rank?(f=c[2].rank,h=c[4].rank,m.push(c[2]),m.push(c[3])):c[3].rank===c[4].rank&&(f=c[3].rank,c[0].rank===c[1].rank&&(h=c[2].rank),m.push(c[3]),m.push(c[4]));7>a&&7>f||11>a&&11>f&&14===h||(10<a&&6>f||6>a&&10<f)&&14===h?(d.push(g[0]),d.push(g[1]),d.push(m[0]),
d.push(m[1]),c=this.getRemainingCards(b,d,e),c=L.sortCards(c),e.push(c[c.length-1])):(e.push(g[0]),e.push(g[1]),d.push(m[0]),d.push(m[1]));b=this._fillHandWithRemaining(b,d,e);d=b.high;e=b.low;break;case ONE_PAIR:f=[];for(a=0;a<c.length-1;a++)if(c[a].rank===c[a+1].rank){f.push(c[a]);f.push(c[a+1]);break}d.push(f[0]);d.push(f[1]);c=this.getRemainingCards(b,d,e);c=L.sortCards(c);e.push(c[c.length-1]);e.push(c[c.length-2]);b=this._fillHandWithRemaining(b,d,e);d=b.high;e=b.low;break;default:c=L.sortCards(b);
for(a=0;a<c.length;a++)c[a].index=a;e.push(c[c.length-2]);e.push(c[c.length-3]);b=this._fillHandWithRemaining(b,d,e);d=b.high;e=b.low}return{high_hand:d,low_hand:e}};this.getRemainingCards=function(a,c,b){for(var d=[],e=0;e<a.length;e++){for(var f=!1,h=a[e],g=0;g<c.length;g++)if(c[g].rank===h.rank&&c[g].suit===h.suit){f=!0;break}for(g=0;g<b.length;g++)if(b[g].rank===h.rank&&b[g].suit===h.suit){f=!0;break}f||d.push(h)}return d};this._fillHandWithRemaining=function(a,c,b){a=this.getRemainingCards(a,
c,b);for(var d=0;5>c.length;)c.push(a[d]),d++;for(;2>b.length;)b.push(a[d]),d++;return{high:c,low:b}};this.onHouseWay=function(){t.disableButtons();for(var a=q.getHighHandAttach().getX(),c=q.getHighHandAttach().getY(),b=E[0].getChildIndex(),d=0;d<F.length;d++)E[F[d].index].initSplit(a,c,b),a+=CARD_WIDTH/2,b++;a=q.getLowHandAttach().getX();c=q.getLowHandAttach().getY();for(d=0;d<A.length;d++)E[A[d].index].initSplit(a,c,b),a+=CARD_WIDTH/2,b++;this.changeState(STATE_GAME_SPLIT_HAND)};this.onSplitHand=
function(){F=[];A=[];for(var a=0;a<E.length;a++)E[a].isSelected()?F.push({rank:E[a].getValue(),suit:E[a].getSuit(),index:a}):A.push({rank:E[a].getValue(),suit:E[a].getSuit(),index:a});d=this._compareLowHands();a=L.getWinnerComparingHands(F,H);D=a.res;v=a.player_value;w=a.dealer_value;this.onHouseWay()};this._showNextDealerCard=function(){I[h].showCard();h++};this._generateRandCards=function(){for(var a=[],c=0;7>c;c++)a.push({fotogram:J[g].fotogram,rank:J[g].rank,suit:J[g].suit,index:c}),g++,this._checkDeckLength();
return a};this._checkDeckLength=function(){g>=J.length&&(J=s_oGameSettings.getShuffledCardDeck(),g=0)};this.clearBets=function(){if(f===STATE_GAME_WAITING_FOR_BET){t.enable(!1,!1,!1);var a=q.getStartingBet();0<a&&(q.clearBet(),q.increaseCredit(a),k-=a,t.refreshCredit(q.getCredit()),a=q.checkIfRebetIsPossible(),t.enableBetFiches(a))}};this.rebet=function(){this.clearBets();var a=q.rebet();k-=a;t.enable(!0,!1,!1);t.refreshCredit(q.getCredit());c=BET_TIME};this.onExit=function(){this.unload();$(s_oMain).trigger("end_session");
$(s_oMain).trigger("share_event",q.getCredit());s_oMain.gotoMenu()};this.getState=function(){return f};this._updateCards=function(){for(var a=0;a<y.length;a++)y[a].update()};this._updateFiches=function(){q.updateFichesController()};this._updateShowWinner=function(){for(var a=0;a<y.length;a++)y[a].update();c+=s_iTimeElaps;c>TIME_END_HAND&&(c=0,a=q.checkIfRebetIsPossible(),this.reset(a),t.reset(),q.getCredit()<s_oGameSettings.getFichesValueAt(0)?(this._gameOver(),this.changeState(-1)):q.getCredit()<
s_oGameSettings.getFichesValueAt(0)?(this._gameOver(),this.changeState(-1)):(this.changeState(STATE_GAME_WAITING_FOR_BET),K.call(this,t.getFicheSelected())))};this.update=function(){if(!1!==b)switch(f){case STATE_GAME_WAITING_FOR_BET:c+=s_iTimeElaps;6E3<c&&(c=0,Q.isVisible()||0!==q.getBetAnte()||Q.show(1));break;case STATE_GAME_DEALING:this._updateCards();break;case STATE_GAME_SPLIT_HAND:this._updateCards();break;case STATE_GAME_DISTRIBUTE_FICHES:this._updateFiches();break;case STATE_GAME_SHOW_WINNER:this._updateShowWinner()}};
s_oGame=this;TOTAL_MONEY=a.money;MIN_BET=a.min_bet;MAX_BET=a.max_bet;BET_TIME=a.bet_time;WIN_OCCURRENCE=a.win_occurrence;k=a.game_cash;TIME_END_HAND=a.time_show_hand;ENABLE_FULLSCREEN=a.fullscreen;AD_SHOW_COUNTER=a.ad_show_counter;this._init()}var s_oGame,s_oTweenController;
function CInterface(a){var b,d,c,e,f,g,m,n,k,h,l,x,v,w,z,p,D,G,A,B,F,H,K,y,I,J,E=null,N=null;this._init=function(a){var u=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH-u.width/2-10;e=u.height/2+10;k=new CGfxButton(c,e,u,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onExit,this);var r=s_oSpriteLibrary.getSprite("but_fullscreen");!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(f=k.getX()-u.width-10,g=u.height/2+10,p=new CToggle(f,g,s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive,!0),p.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this),b=f-r.width/2-10):b=c-r.width/2-10;d=r.height/2+10;var u=window.document,C=u.documentElement;E=C.requestFullscreen||C.mozRequestFullScreen||C.webkitRequestFullScreen||C.msRequestFullscreen;N=u.exitFullscreen||u.mozCancelFullScreen||u.webkitExitFullscreen||u.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(E=!1);E&&!1===inIframe()&&(J=new CToggle(b,d,r,s_bFullscreen,!0),J.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));u=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));
u.x=290;u.y=6;s_oStage.addChild(u);u=s_oSpriteLibrary.getSprite("gui_bg");r=createBitmap(u);r.y=CANVAS_HEIGHT-u.height;s_oStage.addChild(r);u=s_oSpriteLibrary.getSprite("but_clear");h=new CGfxButton(830,CANVAS_HEIGHT-u.height/2,u,s_oStage);h.addEventListener(ON_MOUSE_UP,this._onButClearRelease,this);u=s_oSpriteLibrary.getSprite("but_rebet");l=new CGfxButton(890,CANVAS_HEIGHT-u.height/2,u,s_oStage);l.disable();l.addEventListener(ON_MOUSE_UP,this._onButRebetRelease,this);u=s_oSpriteLibrary.getSprite("but_generic");
v=new CTextButton(1012,CANVAS_HEIGHT-u.height/2,u,TEXT_DEAL,FONT_GAME_1,"#ffffff",30,s_oStage);v.addEventListener(ON_MOUSE_UP,this._onButDealRelease,this);z=new CTextButton(1202,CANVAS_HEIGHT-u.height/2,u,TEXT_HOUSE_WAY,FONT_GAME_1,"#ffffff",27,s_oStage);z.addEventListener(ON_MOUSE_UP,this._onButHouseWayRelease,this);w=new CGfxButton(1060,570,s_oSpriteLibrary.getSprite("but_split"),s_oStage);w.setVisible(!1);w.addEventListener(ON_MOUSE_UP,this._onButSplitRelease,this);POS_BET={x:CANVAS_WIDTH/2,y:415};
x=new CGfxButton(POS_BET.x,POS_BET.y,s_oSpriteLibrary.getSprite("bet_ante"),s_oStage);x.addEventListener(ON_MOUSE_UP,this._onButAnteRelease,this);r=new createjs.Text(TEXT_HIGH_HAND,"17px "+FONT_GAME_1,"#ffde00");r.x=734;r.y=165;r.textAlign="center";s_oStage.addChild(r);r=new createjs.Text(TEXT_LOW_HAND,"17px "+FONT_GAME_1,"#ffde00");r.x=968;r.y=165;r.textAlign="center";s_oStage.addChild(r);r=new createjs.Text(TEXT_HIGH_HAND,"17px "+FONT_GAME_1,"#ffde00");r.x=734;r.y=635;r.textAlign="center";s_oStage.addChild(r);
r=new createjs.Text(TEXT_LOW_HAND,"17px "+FONT_GAME_1,"#ffde00");r.x=968;r.y=635;r.textAlign="center";s_oStage.addChild(r);B=new createjs.Text("","17px "+FONT_GAME_1,"#fff");B.x=740;B.y=490;B.textAlign="center";s_oStage.addChild(B);F=new createjs.Text("","17px "+FONT_GAME_1,"#fff");F.x=970;F.y=490;F.textAlign="center";s_oStage.addChild(F);H=new createjs.Text("","17px "+FONT_GAME_1,"#fff");H.x=740;H.y=310;H.textAlign="center";s_oStage.addChild(H);K=new createjs.Text("","17px "+FONT_GAME_1,"#fff");
K.x=970;K.y=310;K.textAlign="center";s_oStage.addChild(K);G=new createjs.Text("","24px "+FONT_GAME_2,"#ffde00");G.x=412;G.y=16;G.lineWidth=150;G.textAlign="left";G.lineHeight=20;s_oStage.addChild(G);A=new createjs.Text("","19px "+FONT_GAME_2,"#ffde00");A.x=412;A.y=66;G.lineWidth=180;A.textAlign="left";A.lineHeight=18;s_oStage.addChild(A);r=new createjs.Text(TEXT_MONEY+":","30px "+FONT_GAME_2,"#ffde00");r.x=320;r.y=CANVAS_HEIGHT-84;r.textAlign="left";s_oStage.addChild(r);D=new createjs.Text(TEXT_CURRENCY+
a.toFixed(3),"30px "+FONT_GAME_2,"#ffde00");D.x=410;D.y=CANVAS_HEIGHT-84;D.textAlign="left";s_oStage.addChild(D);a=[{x:337,y:CANVAS_HEIGHT-24},{x:417,y:CANVAS_HEIGHT-24},{x:497,y:CANVAS_HEIGHT-24},{x:577,y:CANVAS_HEIGHT-24},{x:657,y:CANVAS_HEIGHT-24},{x:737,y:CANVAS_HEIGHT-24}];n=[];r=s_oGameSettings.getFichesValues();for(C=0;C<NUM_FICHES;C++)u=s_oSpriteLibrary.getSprite("fiche_"+C),n[C]=new CGfxButton(a[C].x,a[C].y,u,s_oStage),n[C].addEventListenerWithParams(ON_MOUSE_UP,this._onFicheClicked,this,
[r[C],C]);a=s_oSpriteLibrary.getSprite("fiche_highlight");y=createBitmap(a);y.regX=a.width/2;y.regY=a.height/2;y.x=n[0].getX();y.y=n[0].getY();s_oStage.addChild(y);m=0;FICHE_WIDTH=u.width;I=new CAnimText(CANVAS_WIDTH,CANVAS_HEIGHT,s_oStage);this.disableButtons();this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){k.unload();k=null;!1===DISABLE_SOUND_MOBILE&&(p.unload(),p=null);E&&!1===inIframe()&&J.unload();h.unload();v.unload();l.unload();s_oInterface=null};this.refreshButtonPos=
function(a,h){k.setPosition(c-a,h+e);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(f-a,h+g);E&&!1===inIframe()&&J.setPosition(b-a,d+h)};this.reset=function(){this.disableButtons()};this.enableBetFiches=function(a){for(var c=0;c<NUM_FICHES;c++)n[c].enable();h.enable();x.enable();a&&l.enable()};this.disableBetFiches=function(){for(var a=0;a<NUM_FICHES;a++)n[a].disable();h.disable();l.disable();x.disable()};this.disableButtons=function(){v.disable();z.disable();w.setVisible(!1)};this.disableDeal=
function(a){a?(v.disable(),z.enable()):(v.enable(),z.disable())};this.enable=function(a){a?v.enable():v.disable()};this.enableSplit=function(a){w.setVisible(a)};this.refreshCredit=function(a){D.text=TEXT_CURRENCY+a.toFixed(3)};this.refreshHandValueText=function(a,c,b,d){B.text=a;F.text=c;H.text=b;K.text=d};this.clearHandValueText=function(){B.text="";F.text="";H.text="";K.text=""};this.displayMsg=function(a,c){G.text=a;A.text=c};this.clearCardValueText=function(){I.hide()};this._onFicheClicked=function(a){y.x=
n[a[1]].getX();y.y=n[a[1]].getY();m=a[1]};this.showResultText=function(a){I.show({x:-200,y:CANVAS_HEIGHT/2+140},{x:CANVAS_WIDTH/2-450,y:CANVAS_HEIGHT/2+140},a)};this._onButClearRelease=function(){s_oGame.clearBets()};this._onButRebetRelease=function(){l.disable();s_oGame.onRebet()};this._onButAnteRelease=function(){s_oGame.setBet(m)};this._onButDealRelease=function(){this.disableBetFiches();this.disableDeal(!0);s_oGame.onDeal()};this._onButHouseWayRelease=function(){this.disableBetFiches();this.disableButtons();
s_oGame.onHouseWay()};this._onButSplitRelease=function(){s_oGame.onSplitHand()};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?(N.call(window.document),s_bFullscreen=!1):(E.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};this.getFicheSelected=function(){return m};this.isResultPanelvisible=function(){return I.isVisible()};s_oInterface=
this;this._init(a);return this}var s_oInterface=null;function CTweenController(){this.tweenValue=function(a,b,d){return a+d*(b-a)};this.easeLinear=function(a,b,d,c){return d*a/c+b};this.easeInCubic=function(a,b,d,c){c=(a/=c)*a*a;return b+d*c};this.easeBackInQuart=function(a,b,d,c){c=(a/=c)*a;return b+d*(2*c*c+2*c*a+-3*c)};this.easeInBack=function(a,b,d,c){return d*(a/=c)*a*(2.70158*a-1.70158)+b};this.easeOutCubic=function(a,b,d,c){return d*((a=a/c-1)*a*a+1)+b}}
function CSeat(){var a,b,d,c,e,f,g,m,n,k;this._init=function(){g=new createjs.Container;g.x=CANVAS_WIDTH/2-100;g.y=570;s_oStage.addChild(g);k=[];for(var b=0;2>b;b++)k[b]=new CFichesController;a=c=0;this.reset();m=new CVector2(g.x-80,g.y);n=new CVector2(g.x+200,g.y);f=new CVector2};this.unload=function(){s_oStage.removeChild(g)};this.addEventListener=function(a,c,b){};this.reset=function(){for(var a=d=0;a<k.length;a++)k[a].reset();e=[];for(a=0;3>a;a++)e[a]=[]};this.clearBet=function(){a=0;e=[];for(var c=
0;c<k.length;c++)k[c].reset(),e[c]=[]};this.resetBet=function(){a=0};this.setCredit=function(a){c=a};this.increaseCredit=function(a){c+=a};this.betAnte=function(c){a+=c;k[0].createFichesPile(a,POS_BET.x,POS_BET.y)};this.setPrevBet=function(){b=a};this.decreaseCredit=function(a){c-=a};this.refreshFiches=function(a,c,b,d,f){e[f].push({value:a,index:c});k[f].refreshFiches(e[f],b,d)};this.initMovement=function(a,c,b){k[a].initMovement(c,b)};this.newCardDealed=function(){d++};this.rebet=function(){a=b;
this.decreaseCredit(b);k[0].createFichesPile(b,POS_BET.x,POS_BET.y);return b};this.checkIfRebetIsPossible=function(){for(var a=0,b=0;b<k.length;b++)var d=parseFloat(k[b].getPrevBet().toFixed(2)),a=a+d;return a>c?!1:!0};this.updateFichesController=function(){for(var a=0;a<k.length;a++)k[a].update()};this.getAttachCardOffset=function(){f.set(g.x+CARD_WIDTH/2*d,g.y);return f};this.getHighHandAttach=function(){return m};this.getLowHandAttach=function(){return n};this.getBetAnte=function(){return a};this.getCredit=
function(){return c};this.getPotentialWin=function(a){return(void 0)[a]};this.getStartingBet=function(){for(var a=0,c=0;c<k.length;c++)a+=k[c].getValue();return a};this._init()}
function CFichesController(){var a,b,d,c,e,f,g,m,n,k;this._init=function(){m=new createjs.Container;s_oStage.addChild(m);e=new CVector2;e.set(m.x,m.y);n=new createjs.Container;s_oStage.addChild(n);k=new createjs.Text("","28px "+FONT_GAME_1,"#fff");k.textAlign="center";k.shadow=new createjs.Shadow("#000000",2,2,2);n.addChild(k);d=c=b=0;a=!1};this.addEventListener=function(a,c,b){};this.reset=function(){a=!1;d=0;m.removeAllChildren();m.x=e.getX();m.y=e.getY();k.text=""};this.setPrevValue=function(a){c=
a};this.refreshFiches=function(a,c,b){a=a.sortOn("value","index");for(var e=c,f=b+10,g=d=0,h=0;h<a.length;h++){var l=s_oSpriteLibrary.getSprite("fiche_"+a[h].index),l=createBitmap(l);l.scaleX=.7;l.scaleY=.7;m.addChild(l);l.x=e-16;l.y=f;f-=5;g++;9<g&&(g=0,e+=FICHE_WIDTH,f=b);d+=a[h].value}playSound("chip",1,0);k.x=c;k.y=b+40;k.text=d.toFixed(2)+TEXT_CURRENCY};this.createFichesPile=function(a,c,b){this.reset();var d=s_oGameSettings.getFichesValues(),e=[];do{for(var f=d[d.length-1],g=d.length-1;f>a;)g--,
f=d[g];for(var g=Math.floor(a/f),m=0;m<g;m++)e.push({value:f,index:s_oGameSettings.getIndexForFiches(f)});a=f=(a%f).toFixed(1)}while(0<f);this.refreshFiches(e,c,b)};this.initMovement=function(b,e){c=d;f=new CVector2(m.x,m.y);g=new CVector2(b,e);k.text="";a=!0};this.getValue=function(){return d};this.getPrevBet=function(){return c};this.update=function(){if(a)if(b+=s_iTimeElaps,b>TIME_FICHES_MOV)b=0,a=!1;else{var c=easeInOutCubic(b,0,1,TIME_FICHES_MOV),d=new CVector2,d=tweenVectors(f,g,c,d);m.x=d.getX();
m.y=d.getY()}};this._init()}
function CVector2(a,b){var d,c;this._init=function(a,b){d=a;c=b};this.add=function(a,b){d+=a;c+=b};this.addV=function(a){d+=a.getX();c+=a.getY()};this.scalarDivision=function(a){d/=a;c/=a};this.subV=function(a){d-=a.getX();c-=a.getY()};this.scalarProduct=function(a){d*=a;c*=a};this.invert=function(){d*=-1;c*=-1};this.dotProduct=function(a){return d*a.getX()+c*a.getY()};this.set=function(a,b){d=a;c=b};this.setV=function(a){d=a.getX();c=a.getY()};this.length=function(){return Math.sqrt(d*d+c*c)};this.length2=
function(){return d*d+c*c};this.normalize=function(){var a=this.length();0<a&&(d/=a,c/=a)};this.getNormalize=function(a){this.length();a.set(d,c);a.normalize()};this.rot90CCW=function(){var a=d;d=-c;c=a};this.rot90CW=function(){var a=d;d=c;c=-a};this.getRotCCW=function(a){a.set(d,c);a.rot90CCW()};this.getRotCW=function(a){a.set(d,c);a.rot90CW()};this.ceil=function(){d=Math.ceil(d);c=Math.ceil(c)};this.round=function(){d=Math.round(d);c=Math.round(c)};this.toString=function(){return"Vector2: "+d+", "+
c};this.print=function(){trace("Vector2: "+d+", "+c+"")};this.getX=function(){return d};this.getY=function(){return c};this._init(a,b)}
function CGameSettings(){var a,b,d;this._init=function(){var c=-1;a=[];for(var b=0;52>b;b++){var f=(b+1)%13;1===f?(f=14,c++):0===f&&(f=13);a.push({fotogram:b,rank:f,suit:c})}d=[1,5,10,25,50,100]};this.getFichesValues=function(){return d};this.getFichesValueAt=function(a){return d[a]};this.getIndexForFiches=function(a){for(var c=0,b=0;b<d.length;b++)d[b]===a&&(c=b);return c};this.generateFichesPile=function(a){var c=[],b,g=d.length-1,m=d[g];do{b=a%m;b=CMath.roundDecimal(b,1);a=Math.floor(a/m);for(var n=
0;n<a;n++)c.push(m);g--;m=d[g];a=b}while(0<b&&-1<g);return c};this.timeToString=function(a){a=Math.round(a/1E3);var c=Math.floor(a/60);a-=60*c;var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a};this.getShuffledCardDeck=function(){for(var c=[],d=0;d<a.length;d++)c[d]=a[d];for(b=[];0<c.length;)b.push(c.splice(Math.round(Math.random()*(c.length-1)),1)[0]);return b};this.getCardDeck=function(){return a};this._init()}
var TYPE_LINEAR=0,TYPE_OUT_CUBIC=1,TYPE_IN_CUBIC=2,TYPE_OUT_BACK=3,TYPE_IN_BACK=4;function ease(a,b,d,c,e,f){var g;switch(a){case TYPE_LINEAR:g=easeLinear(b,d,c,e,f);break;case TYPE_IN_CUBIC:g=easeInCubic(b,d,c,e,f);break;case TYPE_OUT_CUBIC:g=easeOutCubic(b,d,c,e,f);break;case TYPE_IN_BACK:g=easeInBack(b,d,c,e,f);break;case TYPE_OUT_BACK:g=easeInBack(b,d,c,e,f)}return g}
function easeOutBounce(a,b,d,c){return(a/=c)<1/2.75?7.5625*d*a*a+b:a<2/2.75?d*(7.5625*(a-=1.5/2.75)*a+.75)+b:a<2.5/2.75?d*(7.5625*(a-=2.25/2.75)*a+.9375)+b:d*(7.5625*(a-=2.625/2.75)*a+.984375)+b}function easeInBounce(a,b,d,c){return d-easeOutBounce(c-a,0,d,c)+b}function easeInOutBounce(a,b,d,c){return a<c/2?.5*easeInBounce(2*a,0,d,c)+b:.5*easeOutBounce(2*a-c,0,d,c)+.5*d+b}function easeInCirc(a,b,d,c){return-d*(Math.sqrt(1-(a/=c)*a)-1)+b}
function easeOutCirc(a,b,d,c){return d*Math.sqrt(1-(a=a/c-1)*a)+b}function easeInOutCirc(a,b,d,c){return 1>(a/=c/2)?-d/2*(Math.sqrt(1-a*a)-1)+b:d/2*(Math.sqrt(1-(a-=2)*a)+1)+b}function easeInCubic(a,b,d,c,e){return d*(a/=c)*a*a+b}function easeOutCubic(a,b,d,c,e){return d*((a=a/c-1)*a*a+1)+b}function easeInOutCubic(a,b,d,c,e){return 1>(a/=c/2)?d/2*a*a*a+b:d/2*((a-=2)*a*a+2)+b}
function easeInElastic(a,b,d,c,e,f,g){if(0==a)return b;if(1==(a/=c))return b+d;g||(g=.3*c);!f||f<Math.abs(d)?(f=d,e=g/4):e=g/(2*Math.PI)*Math.asin(d/f);return-(f*Math.pow(2,10*--a)*Math.sin(2*(a*c-e)*Math.PI/g))+b}function easeOutElastic(a,b,d,c,e,f,g){if(0==a)return b;if(1==(a/=c))return b+d;g||(g=.3*c);!f||f<Math.abs(d)?(f=d,e=g/4):e=g/(2*Math.PI)*Math.asin(d/f);return f*Math.pow(2,-10*a)*Math.sin(2*(a*c-e)*Math.PI/g)+d+b}
function easeInOutElastic(a,b,d,c,e,f,g){if(0==a)return b;if(1==(a/=c))return b+d;g||(g=.3*c);!f||f<Math.abs(d)?(f=d,e=g/4):e=g/(2*Math.PI)*Math.asin(d/f);return 1>a?-.5*f*Math.pow(2,10*--a)*Math.sin(2*(a*c-e)*Math.PI/g)+b:f*Math.pow(2,-10*--a)*Math.sin(2*(a*c-e)*Math.PI/g)*.5+d+b}function easeInExpo(a,b,d,c){return 0==a?b:d*Math.pow(2,10*(a/c-1))+b}function easeOutExpo(a,b,d,c){return a==c?b+d:d*(-Math.pow(2,-10*a/c)+1)+b}
function easeInOutExpo(a,b,d,c){return 0==a?b:a==c?b+d:1>(a/=c/2)?d/2*Math.pow(2,10*(a-1))+b:d/2*(-Math.pow(2,-10*--a)+2)+b}function easeLinear(a,b,d,c){return d*a/c+b}function easeInQuad(a,b,d,c){return d*(a/=c)*a+b}function easeOutQuad(a,b,d,c){return-d*(a/=c)*(a-2)+b}function easeInOutQuad(a,b,d,c){return 1>(a/=c/2)?d/2*a*a+b:-d/2*(--a*(a-2)-1)+b}function easeInQuart(a,b,d,c){return d*(a/=c)*a*a*a+b}function easeOutQuart(a,b,d,c){return-d*((a=a/c-1)*a*a*a-1)+b}
function easeInOutQuart(a,b,d,c){return 1>(a/=c/2)?d/2*a*a*a*a+b:-d/2*((a-=2)*a*a*a-2)+b}function easeInQuint(a,b,d,c){return d*(a/=c)*a*a*a*a+b}function easeOutQuint(a,b,d,c){return d*((a=a/c-1)*a*a*a*a+1)+b}function easeInOutQuint(a,b,d,c){return 1>(a/=c/2)?d/2*a*a*a*a*a+b:d/2*((a-=2)*a*a*a*a+2)+b}function easeInSine(a,b,d,c){return-d*Math.cos(a/c*(Math.PI/2))+d+b}function easeOutSine(a,b,d,c){return d*Math.sin(a/c*(Math.PI/2))+b}
function easeInOutSine(a,b,d,c){return-d/2*(Math.cos(Math.PI*a/c)-1)+b}function easeInBack(a,b,d,c){return d*(a/=c)*a*(2.70158*a-1.70158)+b}function easeOutBack(a,b,d,c){return d*((a=a/c-1)*a*(2.70158*a+1.70158)+1)+b}
function CCard(a,b,d){var c,e,f,g=-1,m,n,k,h,l,x,v,w,z,p,D;this._init=function(a,c,b){f=!1;D=b;b={images:[s_oSpriteLibrary.getSprite("card_spritesheet")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_1_1:[0],card_1_2:[1],card_1_3:[2],card_1_4:[3],card_1_5:[4],card_1_6:[5],card_1_7:[6],card_1_8:[7],card_1_9:[8],card_1_10:[9],card_1_J:[10],card_1_Q:[11],card_1_K:[12],card_2_1:[13],card_2_2:[14],card_2_3:[15],card_2_4:[16],card_2_5:[17],card_2_6:[18],
card_2_7:[19],card_2_8:[20],card_2_9:[21],card_2_10:[22],card_2_J:[23],card_2_Q:[24],card_2_K:[25],card_3_1:[26],card_3_2:[27],card_3_3:[28],card_3_4:[29],card_3_5:[30],card_3_6:[31],card_3_7:[32],card_3_8:[33],card_3_9:[34],card_3_10:[35],card_3_J:[36],card_3_Q:[37],card_3_K:[38],card_4_1:[39],card_4_2:[40],card_4_3:[41],card_4_4:[42],card_4_5:[43],card_4_6:[44],card_4_7:[45],card_4_8:[46],card_4_9:[47],card_4_10:[48],card_4_J:[49],card_4_Q:[50],card_4_K:[51],back:[52]}};b=new createjs.SpriteSheet(b);
p=createSprite(b,"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);p.x=a;p.y=c;p.rotation=120;p.stop();D.addChild(p);p.on("click",this._onCardRelease);w=[];z=[]};this.unload=function(){p.off("click",this._onCardRelease);v=x=null;D.removeChild(p)};this.addEventListener=function(a,c,b){w[a]=c;z[a]=b};this.setInfo=function(a,b,d,f,w,z,y){e=!1;l=0;m=d;n=f;k=w;x=a;v=b;h=y;c=z;c||(p.cursor="pointer");g=STATE_CARD_DEALING};this.initRemoving=function(a){x=new CVector2(p.x,p.y);v=a;l=0;g=STATE_CARD_REMOVING};
this.initSplit=function(a,c,b){d.setChildIndex(p,b);x=new CVector2(p.x,p.y);v=new CVector2(a,c);l=0;g=STATE_CARD_SPLITTING};this.setValue=function(){p.gotoAndStop(m);var a=this;createjs.Tween.get(p).to({scaleX:1},100).call(function(){a.cardShown()})};this.showCard=function(){var a=this;createjs.Tween.get(p).to({scaleX:.1},100).call(function(){a.setValue()})};this.hideCard=function(){var a=this;createjs.Tween.get(p).to({scaleX:.1},100).call(function(){a.setBack()})};this.setBack=function(){p.gotoAndStop("back");
var a=this;createjs.Tween.get(p).to({scaleX:1},100).call(function(){a.cardHidden()})};this.cardShown=function(){w[ON_CARD_SHOWN]&&w[ON_CARD_SHOWN].call(z[ON_CARD_SHOWN])};this.cardHidden=function(){e=!0};this._onCardRelease=function(){c||(g===STATE_CARD_WAIT_USER&&((f=!f)?createjs.Tween.get(p).to({y:p.y-20},300):createjs.Tween.get(p).to({y:p.y+20},300)),s_oGame.cardSelected(f))};this.getValue=function(){return n};this.getSuit=function(){return k};this.getChildIndex=function(){return D.getChildIndex(p)};
this.getFotogram=function(){return m};this.isSelected=function(){return f};this._updateDealing=function(){l+=s_iTimeElaps;if(l>TIME_CARD_DEALING)g=STATE_CARD_WAIT_USER,l=0,p.x=v.getX(),p.y=v.getY(),p.rotation=360,w[ON_CARD_ANIMATION_ENDING]&&w[ON_CARD_ANIMATION_ENDING].call(z[ON_CARD_ANIMATION_ENDING],this,c,h);else{this.visible=!0;var a=easeInOutCubic(l,0,1,TIME_CARD_DEALING),b=new CVector2,b=tweenVectors(x,v,a,b);p.x=b.getX();p.y=b.getY();p.rotation=120+24E3*a/100}};this._updateRemoving=function(){l+=
s_iTimeElaps;if(l>TIME_CARD_REMOVE)l=0,e=!1,g=-1,this.unload();else{var a=easeInOutCubic(l,0,1,TIME_CARD_REMOVE),c=new CVector2,c=tweenVectors(x,v,a,c);p.x=c.getX();p.y=c.getY();p.rotation=4500*a/100}};this._updateSplit=function(){l+=s_iTimeElaps;if(l>TIME_CARD_SPLIT)l=0,w[SPLIT_CARD_END_ANIM]&&w[SPLIT_CARD_END_ANIM].call(z[SPLIT_CARD_END_ANIM],this,h),g=-1;else{var a=easeInOutCubic(l,0,1,TIME_CARD_SPLIT),c=new CVector2,c=tweenVectors(x,v,a,c);p.x=c.getX();p.y=c.getY()}};this.update=function(){switch(g){case STATE_CARD_DEALING:this._updateDealing();
break;case STATE_CARD_SPLITTING:this._updateSplit();break;case STATE_CARD_REMOVING:!0===e&&this._updateRemoving()}};s_oCard=this;this._init(a,b,d)}var s_oCard;
function CGameOver(){var a,b,d,c;this._init=function(){c=new createjs.Container;s_oStage.addChild(c);c.on("click",function(){});var e=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));c.addChild(e);a=new createjs.Text(TEXT_NO_MONEY,"32px "+FONT_GAME_1,"#fff");a.textAlign="center";a.x=CANVAS_WIDTH/2;a.y=290;a.lineWidth=300;a.shadow=new createjs.Shadow("#000000",2,2,2);c.addChild(a);b=new CTextButton(CANVAS_WIDTH/2-100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_RECHARGE,FONT_GAME_1,"#fff",
14,c);b.addEventListener(ON_MOUSE_UP,this._onRecharge,this);d=new CTextButton(CANVAS_WIDTH/2+100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_EXIT,FONT_GAME_1,"#fff",14,c);d.addEventListener(ON_MOUSE_UP,this._onExit,this);this.hide()};this.unload=function(){b.unload();d.unload();c.off("click",function(){})};this.show=function(){c.visible=!0;$(s_oMain).trigger("end_session")};this.hide=function(){c.visible=!1};this._onRecharge=function(){$(s_oMain).trigger("recharge")};this._onExit=function(){s_oGame.onExit()};
this._init()}
function CMsgBox(){var a,b,d,c;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));d=new createjs.Text("","34px "+FONT_GAME_1,"#000");d.x=CANVAS_WIDTH/2+2;d.y=CANVAS_HEIGHT/2-28;d.textAlign="center";d.lineWidth=400;d.textBaseline="middle";b=new createjs.Text("","34px "+FONT_GAME_1,"#ffffff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2-30;b.textAlign="center";b.lineWidth=400;b.textBaseline="middle";c=new createjs.Container;c.alpha=0;c.visible=!1;c.addChild(a,d,b);s_oStage.addChild(c)};this.unload=
function(){c.off("mousedown",this._onExit)};this._initListener=function(){c.on("mousedown",this._onExit)};this.show=function(a){d.text=a;b.text=a;c.visible=!0;var e=this;createjs.Tween.get(c).to({alpha:1},500).call(function(){e._initListener()});setTimeout(function(){e._onExit()},3E3)};this._onExit=function(){c.visible&&(c.off("mousedown"),c.visible=!1)};this._init();return this}
function CHandEvaluator(){var a,b,d;this.evaluate=function(c){b=[];a=[];for(var e=0;e<c.length;e++)b[e]={rank:c[e].rank,suit:c[e].suit,index:c[e].index},a[e]={rank:c[e].rank,suit:c[e].suit,index:c[e].index};b.sort(this.compareRank);a.sort(this.compareRank);d=[0,1,2,3,4];return{ret:this.rankHand(),sort_hand:a}};this.rankHand=function(){return this._checkForRoyalFlush()?ROYAL_FLUSH:this._checkForStraightFlush()?STRAIGHT_FLUSH:this._checkForFourOfAKind()?FOUR_OF_A_KIND:this._checkForFullHouse()?FULL_HOUSE:
this._checkForFlush()?FLUSH:this._checkForStraight()?STRAIGHT:this._checkForThreeOfAKind()?THREE_OF_A_KIND:this._checkForTwoPair()?TWO_PAIR:this._checkForOnePair()?ONE_PAIR:this._checkHighCard()?HIGH_CARD:NO_HAND};this._checkForRoyalFlush=function(){return this._isRoyalStraight()&&this._isFlush()?!0:!1};this._checkForStraightFlush=function(){return this._isStraight()&&this._isFlush()?!0:!1};this._checkForFourOfAKind=function(){return b[0].rank===b[3].rank?(b.splice(4,1),d.splice(4,1),!0):b[1].rank===
b[4].rank?(b.splice(0,1),d.splice(0,1),!0):!1};this._checkForFullHouse=function(){return b[0].rank===b[1].rank&&b[2].rank===b[4].rank||b[0].rank===b[2].rank&&b[3].rank===b[4].rank?!0:!1};this._checkForFlush=function(){return this._isFlush()?!0:!1};this._checkForStraight=function(){return this._isStraight()?!0:!1};this._checkForThreeOfAKind=function(){return b[0].rank===b[1].rank&&b[0].rank===b[2].rank?(b.splice(3,1),b.splice(3,1),d.splice(3,1),d.splice(3,1),!0):b[1].rank===b[2].rank&&b[1].rank===
b[3].rank?(b.splice(0,1),b.splice(3,1),d.splice(0,1),d.splice(3,1),!0):b[2].rank===b[3].rank&&b[2].rank===b[4].rank?(b.splice(0,1),b.splice(0,1),d.splice(0,1),d.splice(0,1),!0):!1};this._checkForTwoPair=function(){return b[0].rank===b[1].rank&&b[2].rank===b[3].rank?(b.splice(4,1),d.splice(4,1),!0):b[1].rank===b[2].rank&&b[3].rank===b[4].rank?(b.splice(0,1),d.splice(0,1),!0):b[0].rank===b[1].rank&&b[3].rank===b[4].rank?(b.splice(2,1),d.splice(2,1),!0):!1};this._checkForOnePair=function(){for(var a=
0;4>a;a++)if(b[a].rank===b[a+1].rank){var e=b[a],f=b[a+1];b=[];b.push(e);b.push(f);d=[a,a+1];return!0}return!1};this._checkHighCard=function(){for(var a=!1,d=!1,f=0;5>f;f++)b[f].rank===CARD_ACE&&(a=!0),b[f].rank===CARD_KING&&(d=!0);return a&&d?!0:!1};this._isFlush=function(){return b[0].suit===b[1].suit&&b[0].suit===b[2].suit&&b[0].suit===b[3].suit&&b[0].suit===b[4].suit?!0:!1};this._isRoyalStraight=function(){return b[0].rank===CARD_TEN&&b[1].rank===CARD_JACK&&b[2].rank===CARD_QUEEN&&b[3].rank===
CARD_KING&&b[4].rank===CARD_ACE?!0:!1};this._isStraight=function(){var a=b[0].rank+1===b[1].rank&&b[1].rank+1===b[2].rank&&b[2].rank+1===b[3].rank;return a&&b[0].rank===CARD_TWO&&b[4].rank===CARD_ACE?!0:a&&b[3].rank+1===b[4].rank?!0:!1};this.compareRank=function(a,b){return a.rank<b.rank?-1:a.rank>b.rank?1:0};this.sortCards=function(a){return a=a.sort(this.compareRank)};this.getWinnerComparingHands=function(a,b){var c=this.evaluate(a).ret,d=this.evaluate(b).ret,e="dealer";if(c===d){switch(c){case STRAIGHT_FLUSH:a[0].suit>=
b[0].suit?e="dealer":a[0].suit<b[0].suit&&(e="player");break;case FOUR_OF_A_KIND:a[1].rank>b[1].rank?e="player":a[1].rank<=b[1].rank&&(e="dealer");break;case FULL_HOUSE:a[4].rank>b[4].rank?e="player":a[4].rank<=b[4].rank&&(e="dealer");break;case FLUSH:a[0].suit>=b[0].suit?e="dealer":a[0].suit<b[0].suit&&(e="player");break;case STRAIGHT:a[4].rank>b[4].rank?e="player":a[4].rank<=b[4].rank&&(e="dealer");break;case THREE_OF_A_KIND:a[2].rank>b[2].rank?e="player":a[2].rank<=b[2].rank&&(e="dealer");break;
case TWO_PAIR:for(var n=0,k=a.length-1;1<k;k--)if(a[k].rank===a[k-1].rank){n=a[k].rank;break}for(var h=0,k=b.length-1;1<k;k--)if(b[k].rank===b[k-1].rank){h=b[k].rank;break}n>h?e="player":n<=h&&(e="dealer");break;case ONE_PAIR:for(k=n=0;k<a.length-1;k++)if(a[k].rank===a[k+1].rank){n=a[k].rank;break}for(k=h=0;k<b.length-1;k++)if(b[k].rank===b[k+1].rank){h=b[k].rank;break}e=n>h?"player":"dealer";break;case HIGH_CARD:e=b[b.length-1]>=a[a.length-1]?"dealer":"player"}return{res:e,player_value:c,dealer_value:d}}return{res:c>
d?"dealer":"player",player_value:c,dealer_value:d}}}
function CAnimText(a,b,d){var c,e,f,g;this._init=function(a,c){f=new createjs.Container;f.visible=!1;f.x=a;f.y=c;g.addChild(f);var b=s_oSpriteLibrary.getSprite("win_bg"),d=createBitmap(b);f.addChild(d);e=new createjs.Text("","28px "+FONT_GAME_1,"#fff");e.x=b.width/2;e.y=0;e.alphabetic="middle";e.textAlign="center";e.lineWidth=b.width;f.addChild(e)};this.show=function(a,b,d){c=a;e.text=d;f.x=a.x;f.y=a.y;f.visible=!0;createjs.Tween.get(f).to({x:b.x,y:b.y},1E3,createjs.Ease.elasticOut)};this.hide=function(){f.visible=
!1;f.x=c.x;f.y=c.y};this.isVisible=function(){return f.visible};g=d;this._init(a,b)}
function CHelpCursor(a,b,d,c){var e,f,g;this._init=function(a,b,d){e=a;f=createBitmap(d);f.visible=!1;f.x=a;f.y=b;c.addChild(f)};this.show=function(a){0>a&&(f.scaleX*=-1);this._move(a,e+30*a,600);f.visible=!0};this.hide=function(){createjs.Tween.removeTweens(f);f.x=e;f.visible=!1};this._move=function(a,b,c){var d;d=0<a?createjs.Ease.cubicIn:createjs.Ease.cubicOut;createjs.Tween.get(f).to({x:b},c,d).call(function(){a*=-1;g._move(a,b+15*a,400)})};this.isVisible=function(){return f.visible};g=this;this._init(a,
b,d)};
