var s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return!0;return!1}
function getSize(a){var e=a.toLowerCase(),c=window.document,b=c.documentElement;if(void 0===window["inner"+a])a=b["client"+a];else if(window["inner"+a]!=b["client"+a]){var f=c.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var h=c.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+e+":"+b["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+e+":7px!important}}</style>";f.appendChild(h);b.insertBefore(f,c.head);
a=7==h["offset"+a]?b["client"+a]:window["inner"+a];b.removeChild(f)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){var a=window.document,a=a.exitFullscreen||a.mozCancelFullScreen||a.webkitExitFullscreen||a.msExitFullscreen;void 0!=a&&null!=a&&a.call(window.document);sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var e=getSize("Width"),c=Math.min(a/CANVAS_HEIGHT,e/CANVAS_WIDTH),b=CANVAS_WIDTH*c,c=CANVAS_HEIGHT*c,f;c<a?(f=a-c,c+=f,b+=CANVAS_WIDTH/CANVAS_HEIGHT*f):b<e&&(f=e-b,b+=f,c+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-c/2;var h=e/2-b/2,k=CANVAS_WIDTH/b;if(h*k<-EDGEBOARD_X||f*k<-EDGEBOARD_Y)c=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),e/(CANVAS_WIDTH-2*EDGEBOARD_X)),
b=CANVAS_WIDTH*c,c*=CANVAS_HEIGHT,f=(a-c)/2,h=(e-b)/2,k=CANVAS_WIDTH/b;s_iOffsetX=-1*h*k;s_iOffsetY=-1*f*k;0<=f&&(s_iOffsetY=0);0<=h&&(s_iOffsetX=0);null!==s_oGame&&s_oGame.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile?($("#canvas").css("width",b+"px"),$("#canvas").css("height",c+"px")):(s_oStage.canvas.width=b,s_oStage.canvas.height=c,s_oStage.scaleX=s_oStage.scaleY=Math.min(b/CANVAS_WIDTH,c/CANVAS_HEIGHT));0>f?$("#canvas").css("top",
f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",h+"px")}}function createBitmap(a,e,c){var b=new createjs.Bitmap(a),f=new createjs.Shape;e&&c?f.graphics.beginFill("#fff").drawRect(0,0,e,c):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);b.hitArea=f;return b}function createSprite(a,e,c,b,f,h){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-c,-b,f,h);a.hitArea=e;return a}
function randomFloatBetween(a,e,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(c))}function shuffle(a){for(var e=a.length,c,b;0!==e;)b=Math.floor(Math.random()*e),--e,c=a[e],a[e]=a[b],a[b]=c;return a}function formatTime(a){a/=1E3;var e=Math.floor(a/60);a=parseFloat(a-60*e).toFixed(1);var c="",c=10>e?c+("0"+e+":"):c+(e+":");return 10>a?c+("0"+a):c+a}
function rotateVector2D(a,e){var c=e.getX()*Math.cos(a)+e.getY()*Math.sin(a),b=e.getX()*-Math.sin(a)+e.getY()*Math.cos(a);e.set(c,b)}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};function getUrlVars(a){a=a.trim();var e=[];a=a.split("&");for(var c=0;c<a.length;c++){var b=a[c].split("=");e[b[0]]=b[1]}return e}
function tryCheckLogin(){var a=checkLogin(),a=getUrlVars(a);"true"===a.res?(s_bLogged=!0,WHEEL_SETTINGS=a.bonus_prize.split("#"),s_oGameSettings.initSymbolWin(a.paytable),COIN_BET=a.coin_bet.split("#"),MAX_BET=parseFloat(COIN_BET[COIN_BET.length-1]),MIN_BET=parseFloat(COIN_BET[0]),$(s_oMain).trigger("start_session"),s_oMenu.exitFromMenu()):s_oMsgBox.show("can't login #"+a.desc)}
function tryCallSpin(a,e,c){a=callSpin(c,a,e);a=getUrlVars(a);if("true"===a.res)s_oGame.onSpinReceived(a);else s_oMsgBox.show(a.desc)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var e=window.location.search.substring(1).split("&"),c=0;c<e.length;c++){var b=e[c].split("=");if(b[0]==a)return b[1]}}
function playSound(a,e,c){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:c,volume:e}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||void 0===a||a.stop()}function setVolume(a,e){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=e}function setMute(a,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(e)}
function CSpriteLibrary(){var a={},e,c,b,f,h,k;this.init=function(a,u,r){e={};b=c=0;f=a;h=u;k=r};this.addSprite=function(b,f){a.hasOwnProperty(b)||(a[b]=e[b]={szPath:f,oSprite:new Image,bLoaded:!1},c++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){c=0;h.call(k)};this._onSpriteLoaded=function(a){f.call(k,a);++b===c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in e)e[a].oSprite.oSpriteLibrary=this,e[a].oSprite.szKey=a,
e[a].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},e[a].oSprite.src=e[a].szPath};this.setLoaded=function(b){a[b].bLoaded=!0};this.isLoaded=function(b){return a[b].bLoaded};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=1500,CANVAS_HEIGHT=768,EDGEBOARD_X=200,EDGEBOARD_Y=70,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,FONT_GAME_1="odin_roundedbold",FONT_GAME_2="Digital-7",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,GAME_STATE_IDLE=0,GAME_STATE_SPINNING=1,GAME_STATE_SHOW_ALL_WIN=2,GAME_STATE_SHOW_WIN=3,GAME_STATE_BONUS=4,REEL_STATE_START=0,REEL_STATE_MOVING=1,REEL_STATE_STOP=2,SPIN_BUT_STATE_SPIN="spin",SPIN_BUT_STATE_STOP="stop",SPIN_BUT_STATE_AUTOSPIN="autospin",SPIN_BUT_STATE_DISABLE=
"disable",SPIN_BUT_STATE_FREESPIN="freespin",SPIN_BUT_STATE_SKIP="skip",ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,BONUS_BUTTON_1="up_left",BONUS_BUTTON_2="center_left",BONUS_BUTTON_3="down_left",BONUS_BUTTON_4="up_right",BONUS_BUTTON_5="center_right",BONUS_BUTTON_6="down_right",REEL_OFFSET_X=290,REEL_OFFSET_Y=97,NUM_REELS=5,NUM_ROWS=3,NUM_SYMBOLS=13,WILD_SYMBOL=12,BONUS_SYMBOL=13,FREESPIN_SYMBOL=1,NUM_PAYLINES=20,SYMBOL_WIDTH=171,SYMBOL_HEIGHT=164,
SYMBOL_ANIM_WIDTH=340,SYMBOL_ANIM_HEIGHT=326,SPACE_BETWEEN_SYMBOLS=17,SPACE_HEIGHT_BETWEEN_SYMBOLS=4,MAX_FRAMES_REEL_EASE=16,MIN_REEL_LOOPS,REEL_DELAY,REEL_START_Y=REEL_OFFSET_Y-3*(SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS),REEL_ARRIVAL_Y=REEL_OFFSET_Y+3*(SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS),TIME_SHOW_WIN,TIME_SHOW_ALL_WINS,TIME_SPIN_BUT_CHANGE=1E3,TIME_HOLD_AUTOSPIN=1E3,COIN_BET,MIN_BET,MAX_BET,TOTAL_MONEY,WIN_OCCURRENCE,SLOT_CASH,MIN_WIN,FREESPIN_OCCURRENCE,BONUS_OCCURRENCE,FREESPIN_SYMBOL_NUM_OCCURR,
NUM_FREESPIN,BONUS_PRIZE,BONUS_PRIZE_OCCURR,BONUS_FREESPIN=1,BONUS_GOALKEEPER=2,WHEEL_SETTINGS,SEGMENT_ROT=18,TIME_ANIM_IDLE=1E4,MIN_FAKE_SPIN=3,WHEEL_SPIN_TIMESPEED=2600,ANIM_SPIN_TIMESPEED=50,TIME_ANIM_WIN=5E3,ANIM_WIN1_TIMESPEED=300,ANIM_WIN2_TIMESPEED=50,LED_SPIN=3,ANIM_IDLE1_TIMESPEED=2E3,ANIM_IDLE2_TIMESPEED=100,ANIM_IDLE3_TIMESPEED=150,STATE_BONUS_IDLE=0,STATE_BONUS_KICK=1,STATE_BONUS_WIN=2,STATE_BONUS_LOSE=3,NUM_SPIN_FOR_ADS;
function CSlotSettings(){this._init=function(){this._initSymbolSpriteSheets();this._initSymbolAnims();this._initSymbolsOccurence()};this._initSymbolSpriteSheets=function(){s_aSymbolData=[];for(var a=1;a<NUM_SYMBOLS+1;a++){var e={images:[s_oSpriteLibrary.getSprite("symbol_"+a)],frames:{width:SYMBOL_WIDTH,height:SYMBOL_HEIGHT,regX:0,regY:0},animations:{"static":[0,1],moving:[1,2]}};s_aSymbolData[a]=new createjs.SpriteSheet(e)}};this.initSymbolWin=function(a){a=a.split("#");s_aSymbolWin=[];for(var e=
0;e<a.length;e++){var c=a[e].split(",");s_aSymbolWin[e]=[];for(var b=0;b<c.length;b++)s_aSymbolWin[e][b]=parseFloat(c[b])}};this._initSymbolsOccurence=function(){s_aRandSymbols=[];var a;for(a=0;1>a;a++)s_aRandSymbols.push(1);for(a=0;2>a;a++)s_aRandSymbols.push(2);for(a=0;3>a;a++)s_aRandSymbols.push(3);for(a=0;4>a;a++)s_aRandSymbols.push(4);for(a=0;4>a;a++)s_aRandSymbols.push(5);for(a=0;6>a;a++)s_aRandSymbols.push(6);for(a=0;6>a;a++)s_aRandSymbols.push(7);for(a=0;6>a;a++)s_aRandSymbols.push(8);for(a=
0;6>a;a++)s_aRandSymbols.push(9);for(a=0;6>a;a++)s_aRandSymbols.push(10);for(a=0;6>a;a++)s_aRandSymbols.push(11);for(a=0;1>a;a++)s_aRandSymbols.push(12);for(a=0;1>a;a++)s_aRandSymbols.push(13)};this._initSymbolAnims=function(){s_aSymbolAnims=[];for(var a=Math.floor(FPS/2),e=0;e<NUM_SYMBOLS;e++){var c={framerate:a,images:[s_oSpriteLibrary.getSprite("symbol_"+(e+1)+"_anim")],frames:{width:SYMBOL_ANIM_WIDTH,height:SYMBOL_ANIM_HEIGHT},animations:{"static":[0],anim:[0,23]}};s_aSymbolAnims[e]=new createjs.SpriteSheet(c)}s_oAnimRegPoint=
[{x:85,y:82},{x:85,y:82},{x:85,y:82},{x:85,y:82},{x:85,y:82},{x:85,y:82},{x:85,y:82},{x:85,y:82},{x:85,y:82},{x:85,y:82},{x:85,y:82},{x:85,y:82},,{x:85,y:82}]};this._init()}
var s_aSymbolData,s_aPaylineCombo,s_aSymbolWin,s_aSymbolAnims,s_aRandSymbols,s_oAnimRegPoint=[],TEXT_MONEY="MONEY",TEXT_BET="BET",TEXT_COIN="COIN",TEXT_MAX_BET="MAX BET",TEXT_LINES="LINES",TEXT_PAYTABLE="PAYTABLE",TEXT_WIN="WIN",TEXT_HELP_BONUS1="3 OR MORE ON ANY REELS, WILL TRIGGER PENALTY KICK BONUS!!",TEXT_HELP_BONUS2="CHOOSE WHERE TO KICK THE BALL TO GET A PRIZE!!",TEXT_HELP_FREESPIN="GET 3 OR MORE FREESPIN SYMBOL ON ANY REEL TO TRIGGER FREESPINS",TEXT_CURRENCY="$",TEXT_CONGRATS="CONGRATULATIONS!!",
TEXT_YOU_WIN="YOU WON",TEXT_FREESPINS="FREESPINS",TEXT_DEVELOPED="DEVELOPED BY",TEXT_NO_MAX_BET="NOT ENOUGH MONEY FOR MAX BET!!",TEXT_NOT_ENOUGH_MONEY="NOT ENOUGH MONEY FOR THE CURRENT BET!",TEXT_CONGRATULATIONS="Congratulations!",TEXT_MSG_SHARE1="You collected <strong>",TEXT_MSG_SHARE2=" points</strong>!<br><br>Share your score with your friends!",TEXT_MSG_SHARING1="My score is ",TEXT_MSG_SHARING2=" points! Can you do better?";
function CPreloader(){var a,e,c,b,f,h,k;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_loading","./sprites/bg_loading.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();k=new createjs.Container;s_oStage.addChild(k)};this.unload=function(){k.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var n=createBitmap(s_oSpriteLibrary.getSprite("bg_loading"));k.addChild(n);n=s_oSpriteLibrary.getSprite("progress_bar");f=createBitmap(n);f.x=CANVAS_WIDTH/2-n.width/2;f.y=CANVAS_HEIGHT-170;k.addChild(f);a=n.width;e=n.height;h=new createjs.Shape;h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,f.y,1,e);k.addChild(h);f.mask=h;c=new createjs.Text("","30px "+FONT_GAME_1,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT-125;c.shadow=new createjs.Shadow("#000",2,2,2);
c.textBaseline="alphabetic";c.textAlign="center";k.addChild(c);b=new createjs.Text("","30px "+FONT_GAME_2,"#fff");b.x=CANVAS_WIDTH;b.y=CANVAS_HEIGHT+125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";k.addChild(b)};this.refreshLoader=function(k){c.text=k+"%";b.text=k+"%";h.graphics.clear();k=Math.floor(k*a/100);h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,f.y,k,e)};this._init()}
function CMain(a){var e,c=0,b=0,f=STATE_LOADING,h,k,n;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);s_oAttachSection=new createjs.Container;s_oStage.addChild(s_oAttachSection);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(FPS);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;k=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();e=!0};this.soundLoaded=function(){c++;k.refreshLoader(Math.floor(c/b*100));if(c===b)this.onAllResourcesLoaded()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/crowd.ogg","crowd"),createjs.Sound.registerSound("./sounds/press_but.ogg","press_but"),createjs.Sound.registerSound("./sounds/reel_stop.ogg","reel_stop",6),createjs.Sound.registerSound("./sounds/reel_stop_bonus.ogg","reel_stop_bonus",6),createjs.Sound.registerSound("./sounds/reel_stop_freespin.ogg","reel_stop_freespin",6),createjs.Sound.registerSound("./sounds/start_reel.ogg",
"start_reel",6),createjs.Sound.registerSound("./sounds/spin_but.ogg","spin_but"),createjs.Sound.registerSound("./sounds/kick.ogg","kick"),createjs.Sound.registerSound("./sounds/symbol_1.ogg","symbol_1"),createjs.Sound.registerSound("./sounds/symbol2.ogg","symbol2"),createjs.Sound.registerSound("./sounds/symbol3.ogg","symbol3"),createjs.Sound.registerSound("./sounds/symbol4.ogg","symbol4"),createjs.Sound.registerSound("./sounds/symbol5.ogg","symbol5"),createjs.Sound.registerSound("./sounds/symbol6.ogg",
"symbol6"),createjs.Sound.registerSound("./sounds/symbol7.ogg","symbol7"),createjs.Sound.registerSound("./sounds/symbol8.ogg","symbol8"),createjs.Sound.registerSound("./sounds/symbol9_10_11.ogg","symbol9_10_11"),createjs.Sound.registerSound("./sounds/symbol12.ogg","symbol12"),createjs.Sound.registerSound("./sounds/symbol13.ogg","symbol13"),createjs.Sound.registerSound("./sounds/bonus_win.ogg","bonus_win"),createjs.Sound.registerSound("./sounds/avatar_win.ogg","avatar_win")):(createjs.Sound.alternateExtensions=
["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/crowd.mp3","crowd"),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/reel_stop.mp3","reel_stop",6),createjs.Sound.registerSound("./sounds/reel_stop_bonus.mp3","reel_stop_bonus",6),createjs.Sound.registerSound("./sounds/reel_stop_freespin.mp3","reel_stop_freespin",
6),createjs.Sound.registerSound("./sounds/start_reel.mp3","start_reel",6),createjs.Sound.registerSound("./sounds/spin_but.mp3","spin_but"),createjs.Sound.registerSound("./sounds/kick.mp3","kick"),createjs.Sound.registerSound("./sounds/symbol1.mp3","symbol1"),createjs.Sound.registerSound("./sounds/symbol2.mp3","symbol2"),createjs.Sound.registerSound("./sounds/symbol3.mp3","symbol3"),createjs.Sound.registerSound("./sounds/symbol4.mp3","symbol4"),createjs.Sound.registerSound("./sounds/symbol5.mp3","symbol5"),
createjs.Sound.registerSound("./sounds/symbol6.mp3","symbol6"),createjs.Sound.registerSound("./sounds/symbol7.mp3","symbol7"),createjs.Sound.registerSound("./sounds/symbol8.mp3","symbol8"),createjs.Sound.registerSound("./sounds/symbol9_10_11.mp3","symbol9_10_11"),createjs.Sound.registerSound("./sounds/symbol12.mp3","symbol12"),createjs.Sound.registerSound("./sounds/symbol13.mp3","symbol13"),createjs.Sound.registerSound("./sounds/bonus_win.mp3","bonus_win"),createjs.Sound.registerSound("./sounds/avatar_win.mp3",
"avatar_win")),b+=22)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("but_bg","./sprites/but_play_bg.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("paytable1","./sprites/paytable1.jpg");s_oSpriteLibrary.addSprite("paytable2","./sprites/paytable2.jpg");
s_oSpriteLibrary.addSprite("paytable3","./sprites/paytable3.jpg");s_oSpriteLibrary.addSprite("paytable4","./sprites/paytable4.jpg");s_oSpriteLibrary.addSprite("mask_slot","./sprites/mask_slot.png");s_oSpriteLibrary.addSprite("coin_but","./sprites/but_coin_bg.png");s_oSpriteLibrary.addSprite("info_but","./sprites/but_info_bg.png");s_oSpriteLibrary.addSprite("win_frame_anim","./sprites/win_frame_anim.png");s_oSpriteLibrary.addSprite("but_lines_bg","./sprites/but_lines_bg.png");s_oSpriteLibrary.addSprite("but_maxbet_bg",
"./sprites/but_maxbet_bg.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_arrow_next","./sprites/but_arrow_next.png");s_oSpriteLibrary.addSprite("but_arrow_prev","./sprites/but_arrow_prev.png");s_oSpriteLibrary.addSprite("logo","./sprites/logo.png");s_oSpriteLibrary.addSprite("but_spin","./sprites/but_spin.png");s_oSpriteLibrary.addSprite("bg_loading_bonus","./sprites/bg_loading_bonus.jpg");
s_oSpriteLibrary.addSprite("bg_loading","./sprites/bg_loading.jpg");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("but_exit_info","./sprites/but_exit_info.png");s_oSpriteLibrary.addSprite("amount_win_bg","./sprites/amount_win_bg.png");for(var a=1;a<NUM_SYMBOLS+1;a++)s_oSpriteLibrary.addSprite("symbol_"+a,"./sprites/symbol_"+
a+".png"),s_oSpriteLibrary.addSprite("symbol_"+a+"_anim","./sprites/symbol_"+a+"_anim.jpg");for(a=1;a<NUM_PAYLINES+1;a++)s_oSpriteLibrary.addSprite("payline_"+a,"./sprites/paylines/payline_"+a+".png"),s_oSpriteLibrary.addSprite("bet_but"+a,"./sprites/paylines/bet_but"+a+".png");for(a=0;30>a;a++)s_oSpriteLibrary.addSprite("avatar_idle_"+a,"./sprites/avatar/avatar_idle/avatar_idle_"+a+".png");for(a=0;38>a;a++)s_oSpriteLibrary.addSprite("avatar_win_"+a,"./sprites/avatar/avatar_win/avatar_win_"+a+".png");
b+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;k.refreshLoader(Math.floor(c/b*100));if(c===b)this.onAllResourcesLoaded()};this._onAllImagesLoaded=function(){};this.onAllResourcesLoaded=function(){s_oGameSettings=new CSlotSettings;s_oMsgBox=new CMsgBox;k.unload();WIN_OCCURRENCE=h.win_occurrence;MIN_REEL_LOOPS=h.min_reel_loop;REEL_DELAY=h.reel_delay;TIME_SHOW_WIN=h.time_show_win;TIME_SHOW_ALL_WINS=h.time_show_all_wins;SLOT_CASH=h.slot_cash;TOTAL_MONEY=
parseFloat(h.money);FREESPIN_OCCURRENCE=h.freespin_occurrence;BONUS_OCCURRENCE=h.bonus_occurrence;FREESPIN_SYMBOL_NUM_OCCURR=h.freespin_symbol_num_occur;NUM_FREESPIN=h.num_freespin;BONUS_PRIZE=h.bonus_prize;BONUS_PRIZE_OCCURR=h.bonus_prize_occur;COIN_BET=h.coin_bet;NUM_SPIN_FOR_ADS=a.num_spin_ads_showing;this.gotoMenu()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(){n=new CGame(h);f=STATE_GAME};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){e=
!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();e=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==e){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&n.update();s_oStage.update(a)}};s_oMain=this;h=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_bFullscreen=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oAttachSection,s_oMain,s_oSpriteLibrary,s_bLogged=!1,s_oMsgBox,s_oGameSettings;
function CTextButton(a,e,c,b,f,h,k,n){var u,r,q,t,l,d,p,m,g,x;this._init=function(a,b,c,f,e,h,k,n){u=!1;t=[];l=[];x=n;p=createBitmap(c);r=c.width;q=c.height;n=Math.ceil(k/20);m=new createjs.Text(f,k+"px "+e,"#000000");var w=m.getBounds();m.textAlign="center";m.textBaseline="alphabetic";m.x=c.width/2+n;m.y=Math.floor(c.height/2)+w.height/3+n;g=new createjs.Text(f,k+"px "+e,h);g.textAlign="center";g.textBaseline="alphabetic";g.x=c.width/2;g.y=Math.floor(c.height/2)+w.height/3;d=new createjs.Container;
d.x=a;d.y=b;d.regX=c.width/2;d.regY=c.height/2;d.cursor="pointer";d.addChild(p,m,g);x.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown");d.off("pressup");x.removeChild(d)};this.setVisible=function(a){d.visible=a};this.enable=function(){u=!1;p.filters=[];p.cache(0,0,r,q);g.color="#fff"};this.disable=function(){u=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);p.filters=[new createjs.ColorMatrixFilter(a)];p.cache(0,0,r,q);g.color="#a39b9d"};this.setText=
function(a){g.text=a;m.text=a};this._initListener=function(){oParent=this;d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){t[a]=b;l[a]=d};this.buttonRelease=function(){u||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||playSound("press_but",1,0),d.scaleX=1,d.scaleY=1,t[ON_MOUSE_UP]&&t[ON_MOUSE_UP].call(l[ON_MOUSE_UP]))};this.buttonDown=function(){u||(d.scaleX=.9,d.scaleY=.9,t[ON_MOUSE_DOWN]&&t[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN]))};this.setPosition=
function(a,b){d.x=a;d.y=b};this.changeText=function(a){g.text=a;m.text=a};this.setX=function(a){d.x=a};this.setY=function(a){d.y=a};this.getButtonImage=function(){return d};this.getX=function(){return d.x};this.getY=function(){return d.y};this._init(a,e,c,b,f,h,k,n);return this}
function CGfxButton(a,e,c,b){var f,h,k,n,u,r=[],q,t;this._init=function(a,b,c){f=!1;h=c.width;k=c.height;n=[];u=[];q=createBitmap(c);q.x=a;q.y=b;q.regX=c.width/2;q.regY=c.height/2;q.cursor="pointer";t.addChild(q);this._initListener()};this.unload=function(){q.off("mousedown",this.buttonDown);q.off("pressup",this.buttonRelease);t.removeChild(q)};this.enable=function(){f=!1;q.filters=[];q.cache(0,0,h,k)};this.disable=function(){f=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);
q.filters=[new createjs.ColorMatrixFilter(a)];q.cache(0,0,h,k)};this.setVisible=function(a){q.visible=a};this._initListener=function(){q.on("mousedown",this.buttonDown);q.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){n[a]=b;u[a]=c};this.addEventListenerWithParams=function(a,b,c,f){n[a]=b;u[a]=c;r=f};this.buttonRelease=function(){f||(playSound("press_but",1,0),q.scaleX=1,q.scaleY=1,n[ON_MOUSE_UP]&&n[ON_MOUSE_UP].call(u[ON_MOUSE_UP],r))};this.buttonDown=function(){f||(q.scaleX=
.9,q.scaleY=.9,n[ON_MOUSE_DOWN]&&n[ON_MOUSE_DOWN].call(u[ON_MOUSE_DOWN],r))};this.setPosition=function(a,b){q.x=a;q.y=b};this.setX=function(a){q.x=a};this.setY=function(a){q.y=a};this.getButtonImage=function(){return q};this.getX=function(){return q.x};this.getY=function(){return q.y};t=b;this._init(a,e,c);return this}
function CToggle(a,e,c,b){var f,h,k,n;this._init=function(a,b,c,e){h=[];k=[];var l=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=e;n=createSprite(l,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);n.x=a;n.y=b;n.stop();n.cursor="pointer";s_oAttachSection.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown",this.buttonDown);n.off("pressup",this.buttonRelease);s_oAttachSection.removeChild(n)};
this._initListener=function(){n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;k[a]=c};this.setActive=function(a){f=a;n.gotoAndStop("state_"+f)};this.buttonRelease=function(){n.scaleX=1;n.scaleY=1;playSound("press_but",1,0);f=!f;n.gotoAndStop("state_"+f);h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(k[ON_MOUSE_UP],f)};this.buttonDown=function(){n.scaleX=.9;n.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setPosition=
function(a,b){n.x=a;n.y=b};this._init(a,e,c,b)}
function CBetBut(a,e,c,b,f,h,k,n){var u,r,q,t=[],l,d,p;this._init=function(a,b,c,f,e,h,k){u=!1;r=[];q=[];d=new createjs.Container;d.x=a;d.y=b;p.addChild(d);a=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height},animations:{on:[0,1],off:[1,2]}});l=createSprite(a,"on",0,0,c.width/2,c.height);l.stop();l.cursor="pointer";d.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown",this.buttonDown);l.off("pressup",this.buttonRelease);p.removeChild(l)};this.disable=
function(a){u=a};this.setVisible=function(a){l.visible=a};this.setOn=function(){l.gotoAndStop("on")};this.setOff=function(){l.gotoAndStop("off")};this._initListener=function(){l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){r[a]=b;q[a]=c};this.addEventListenerWithParams=function(a,b,c,d){r[a]=b;q[a]=c;t=d};this.buttonRelease=function(){r[ON_MOUSE_UP]&&!1===u&&(playSound("press_but",1,0),r[ON_MOUSE_UP].call(q[ON_MOUSE_UP],t))};this.buttonDown=
function(){r[ON_MOUSE_DOWN]&&!1===u&&r[ON_MOUSE_DOWN].call(q[ON_MOUSE_DOWN],t)};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};p=n;this._init(a,e,c,b,f,h,k)}
function CMenu(){var a,e,c,b,f,h,k;this._init=function(){c=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oAttachSection.addChild(c);var n=s_oSpriteLibrary.getSprite("but_bg");b=new CGfxButton(CANVAS_WIDTH/2+420,CANVAS_HEIGHT-164,n,s_oStage);b.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-n.width/4-10,e=n.height/2+10,f=new CToggle(a,e,n,s_bAudioActive),f.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oAttachSection.addChild(h);createjs.Tween.get(h).to({alpha:0},400).call(function(){h.visible=!1});k=playSound("soundtrack",1,-1);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){b.unload();b=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f.unload(),f=null;s_oAttachSection.removeChild(c);c=null;s_oAttachSection.removeChild(h);s_oMenu=h=null;stopSound(k)};this.refreshButtonPos=
function(b,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||f.setPosition(a-b,c+e)};this._onButPlayRelease=function(){tryCheckLogin()};this.exitFromMenu=function(){this.unload();s_oMain.gotoGame()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(){var a,e,c=!1,b=!1,f,h,k,n,u,r,q,t,l,d,p,m,g,x,y,A,D,J,z,G,B,E,w,K,M,H,N,L,v,F=null,I,O;this._init=function(){k=GAME_STATE_IDLE;t=D=r=n=0;E=[0,1,2,3,4];u=E[0];q=NUM_PAYLINES;m=TOTAL_MONEY;d=MIN_BET;p=d*q;f=!1;J=y=x=0;s_oTweenController=new CTweenController;M=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oAttachSection.addChild(M);this._initReels();N=new createjs.Bitmap(s_oSpriteLibrary.getSprite("mask_slot"));s_oAttachSection.addChild(N);var a={images:[s_oSpriteLibrary.getSprite("logo")],
frames:{width:230,height:86,regX:165,regY:0},animations:{normal:[0],freespin:[1,55]}};v=new CInterface(d,p,m);this._initStaticSymbols();O=new CAvatar(s_oAttachSection);O.show(0);a=new createjs.SpriteSheet(a);H=createSprite(a,"normal",165,0,230,86);H.stop();s_oAttachSection.addChild(H);F=new CPayTablePanel;m<p&&v.disableSpin();MIN_WIN=s_aSymbolWin[0][s_aSymbolWin[0].length-1];for(a=0;a<s_aSymbolWin.length;a++)for(var b=s_aSymbolWin[a],g=0;g<b.length;g++)0!==b[g]&&b[g]<MIN_WIN&&(MIN_WIN=b[g]);I=new CBonusPanel;
L=new CFreespinPanel(s_oStage);this.refreshButtonPos(s_iOffsetX,s_iOffsetY);playSound("crowd",1,-1);c=!0};this.unload=function(){createjs.Sound.stop();v.unload();F.unload();for(var a=0;a<z.length;a++)z[a].unload();for(a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)G[a][b].unload();s_oAttachSection.removeAllChildren();s_oGame=null};this.refreshButtonPos=function(b,c){v.refreshButtonPos(b,c);F.refreshButtonPos(b,c);40>s_iOffsetY?(a=800,e=-2):(a=1432,e=80);H.x=a;H.y=e+c;O.refreshButtonPos(b,c)};this._initReels=
function(){var a=REEL_OFFSET_X,b=REEL_OFFSET_Y,c=0;z=[];for(var d=0;d<NUM_REELS;d++)z[d]=new CReelColumn(d,a,b,c),z[d+NUM_REELS]=new CReelColumn(d+NUM_REELS,a,b+(SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS)*NUM_ROWS,c),a+=SYMBOL_WIDTH+SPACE_BETWEEN_SYMBOLS,c+=REEL_DELAY};this._initStaticSymbols=function(){var a=REEL_OFFSET_X,b=REEL_OFFSET_Y;G=[];for(var c=0;c<NUM_ROWS;c++){G[c]=[];for(var d=0;d<NUM_REELS;d++){var f=new CStaticSymbolCell(c,d,a,b);G[c][d]=f;a+=SYMBOL_WIDTH+SPACE_BETWEEN_SYMBOLS}a=REEL_OFFSET_X;
b+=SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS}};this.generateLosingPattern=function(){for(var a=[],c=0;c<NUM_ROWS;c++){var d=Math.floor(Math.random()*(s_aRandSymbols.length-2)),d=s_aRandSymbols[d];a[c]=d}w=[];for(c=0;c<NUM_ROWS;c++){w[c]=[];for(var f=0;f<NUM_REELS;f++)if(0===f)w[c][f]=a[c];else{do d=Math.floor(Math.random()*(s_aRandSymbols.length-2)),d=s_aRandSymbols[d];while(a[0]===d||a[1]===d||a[2]===d);w[c][f]=d}}B=[];b=!0};this._generateRandSymbols=function(){for(var a=[],b=0;b<NUM_ROWS;b++)a[b]=
s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)];return a};this.reelArrived=function(a,c){if(n>MIN_REEL_LOOPS)if(u===c){if(!1===z[a].isReadyToStop()){var d=a;a<NUM_REELS?(d+=NUM_REELS,z[d].setReadyToStop(),z[a].restart([w[0][a],w[1][a],w[2][a]],!0)):(d-=NUM_REELS,z[d].setReadyToStop(),z[a].restart([w[0][d],w[1][d],w[2][d]],!0))}}else z[a].restart(this._generateRandSymbols(),!1);else z[a].restart(this._generateRandSymbols(),!1),b&&0===a&&n++};this.stopNextReel=function(a,b){r++;0===
r%2?(u=E[r/2],r===2*NUM_REELS&&this._endReelAnimation()):b?playSound("reel_stop_bonus",1,0):a?playSound("reel_stop_freespin",1,0):playSound("reel_stop",1,0)};this._endReelAnimation=function(){b=!1;l=r=n=0;u=E[0];0<y&&(v.disableGuiButtons(),v.disableSpin());"freespin"===H.currentAnimation&&!1===h&&v.refreshFreeSpinNum(x);if(0<B.length){O.show(1);for(var a=0;a<B.length;a++){0<B[a].line&&(F.highlightCombo(B[a].value,B[a].num_win),v.showLine(B[a].line));for(var c=B[a].list,d=0;d<c.length;d++)G[c[d].row][c[d].col].showWinFrame()}"freespin"===
H.currentAnimation&&0===x&&(H.gotoAndStop("normal"),v.refreshFreeSpinNum(""),v.setSpinState(SPIN_BUT_STATE_SPIN));0<g&&v.refreshWinText(g);t=0;k=GAME_STATE_SHOW_ALL_WIN;K=playSound("avatar_win",1,0);y!==BONUS_GOALKEEPER&&v.refreshMoney(m)}else if(0<x)v.disableSpin(),this.onSpin();else if("freespin"===H.currentAnimation&&(H.gotoAndStop("normal"),v.refreshFreeSpinNum(""),v.setSpinState(SPIN_BUT_STATE_SPIN)),f)if(m<p&&0===x)this.resetCoinBet(),f=!1,v.enableGuiButtons();else this.onSpin();else k=GAME_STATE_IDLE;
m<p&&0===x?(this.resetCoinBet(),f=!1,v.enableGuiButtons()):f||0!==x||0!==y||(v.enableGuiButtons(),v.disableBetBut(!1));J++;J===NUM_SPIN_FOR_ADS&&(J=0,$(s_oMain).trigger("show_interlevel_ad"));$(s_oMain).trigger("save_score",m)};this.hidePayTable=function(){F.hide()};this.showWin=function(){var a;if(0<l){stopSound(K);a=B[l-1].line;0<a&&v.hideLine(a);var b=B[l-1].list;for(a=0;a<b.length;a++)z[b[a].col].setVisible(b[a].row,!0),z[b[a].col+NUM_REELS].setVisible(b[a].row,!0)}if(l===B.length)if(l=0,h)h=
!1,L.show(x);else if(0<x)v.disableSpin(),this.onSpin();else if(y===BONUS_GOALKEEPER)I.isVisible()||(this._hideAllWins(),I.show(BONUS_PRIZE[A]),k=GAME_STATE_BONUS);else if(f)this.onSpin();else v.enableGuiButtons(),v.disableBetBut(!1),k=GAME_STATE_IDLE;else{var c;a=B[l].line;b=B[l].list;if(0===a)c=Math.floor(b.length/2),a=b[c].row,c=b[c].col;else{v.showLine(a);c=2;var d=!1;3>b.length?B[l].value===FREESPIN_SYMBOL?(c=b[0].col,a=b[0].row,d=!0):(c=b.length-1,a=b[c].row):a=b[c].row;for(;!d&&w[a][c]===WILD_SYMBOL;)if(c--,
0>c){c=0;a=b[c].row;break}else a=b[c].row}b={x:0,y:0};0===a?0===c?d={x:0,y:0}:4===c?(d={x:SYMBOL_ANIM_WIDTH,y:0},b={x:SYMBOL_WIDTH,y:0}):(d={x:SYMBOL_ANIM_WIDTH/2,y:0},b={x:SYMBOL_WIDTH/2,y:0}):1===a?0===c?(d={x:0,y:SYMBOL_ANIM_HEIGHT/2},b={x:0,y:SYMBOL_HEIGHT/2}):4===c?(d={x:SYMBOL_ANIM_WIDTH,y:SYMBOL_ANIM_HEIGHT/2},b={x:SYMBOL_WIDTH,y:SYMBOL_HEIGHT/2}):(d={x:SYMBOL_ANIM_WIDTH/2,y:SYMBOL_ANIM_HEIGHT/2},b={x:SYMBOL_WIDTH/2,y:SYMBOL_HEIGHT/2}):0===c?(d={x:0,y:SYMBOL_ANIM_HEIGHT},b={x:0,y:SYMBOL_HEIGHT}):
4===c?(d={x:SYMBOL_ANIM_WIDTH,y:SYMBOL_ANIM_HEIGHT},b={x:SYMBOL_WIDTH,y:SYMBOL_HEIGHT}):(d={x:SYMBOL_ANIM_WIDTH/2,y:SYMBOL_ANIM_HEIGHT},b={x:SYMBOL_WIDTH/2,y:SYMBOL_HEIGHT});G[a][c].show(B[l].value,B[l].amount,b,d,f||!1===h&&0<x?1:3);l++}};this._hideAllWins=function(){for(var a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)G[a][b].hideWinFrame();v.hideAllLines()};this._prepareForWinsShowing=function(){this._hideAllWins();l=t=0;t=TIME_SHOW_WIN;k=GAME_STATE_SHOW_WIN;this.showWin();0===x&&v.setSpinState(SPIN_BUT_STATE_SKIP)};
this.activateLines=function(a){q=a;this.removeWinShowing();p=a=d*q;v.refreshTotalBet(p);v.refreshNumLines(q);a>m?v.disableSpin():v.enableSpin()};this.addLine=function(){q===NUM_PAYLINES?q=1:q++;p=d*q;v.refreshTotalBet(p);v.refreshNumLines(q);v.enableSpin()};this.resetCoinBet=function(){D=0;var a=parseFloat(COIN_BET[D]),b=a*q;d=a;d=Math.floor(100*d)/100;p=b;v.refreshBet(d);v.refreshTotalBet(p);v.enableSpin()};this.changeCoinBet=function(){D++;D===COIN_BET.length&&(D=0);var a=parseFloat(COIN_BET[D]),
b=a*q;d=a;d=Math.floor(100*d)/100;p=b;v.refreshBet(d);v.refreshTotalBet(p);v.enableSpin()};this.onMaxBet=function(){if(m<MAX_BET*NUM_PAYLINES)s_oMsgBox.show(TEXT_NO_MAX_BET);else{var a=MAX_BET;q=NUM_PAYLINES;a*=q;d=MAX_BET;p=a;v.refreshBet(d);v.refreshTotalBet(p);v.refreshNumLines(q);a>m?v.disableSpin():(v.enableSpin(),this.onSpin())}};this.removeWinShowing=function(){F.resetHighlightCombo();v.resetWin();for(var a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)G[a][b].hide(),z[b].setVisible(a,!0),z[b+
NUM_REELS].setVisible(a,!0);for(a=0;a<z.length;a++)z[a].activate();k=GAME_STATE_IDLE};this.forceStopReel=function(){0===x&&(f=!1);k=GAME_STATE_IDLE;for(var a=0;a<NUM_REELS;a++)z[a].forceStop([w[0][a],w[1][a],w[2][a]],REEL_OFFSET_Y),z[a+NUM_REELS].forceStop(null,REEL_OFFSET_Y+(SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS)*NUM_ROWS);this._endReelAnimation()};this.onSpin=function(){m<p&&0===x?(v.enableGuiButtons(),f=!1,s_oMsgBox.show(TEXT_NOT_ENOUGH_MONEY)):(stopSound(K),playSound("spin_but",1,0),v.disableBetBut(!0),
this.removeWinShowing(),!0===s_bLogged?(p="freespin"===H.currentAnimation?0:d*q,tryCallSpin(d,p,q)):this.generateLosingPattern(),this._hideAllWins(),v.disableGuiButtons())};this.onSkip=function(){if(0<y)this._hideAllWins(),I.show(BONUS_PRIZE[A]),k=GAME_STATE_BONUS;else this.onSpin()};this.onAutoSpin=function(){f=!0;this.onSpin()};this.onStopAutoSpin=function(){f=!1;k!==GAME_STATE_SPINNING&&k!==GAME_STATE_BONUS&&v.enableGuiButtons()};this.generateLosingPattern=function(){for(var a=[],c=0;c<NUM_ROWS;c++){var d=
Math.floor(Math.random()*(s_aRandSymbols.length-2)),d=s_aRandSymbols[d];a[c]=d}w=[];for(c=0;c<NUM_ROWS;c++){w[c]=[];for(var f=0;f<NUM_REELS;f++)if(0===f)w[c][f]=a[c];else{do d=Math.floor(Math.random()*(s_aRandSymbols.length-2)),d=s_aRandSymbols[d];while(a[0]===d||a[1]===d||a[2]===d);w[c][f]=d}}B=[];b=!0};this.onSpinReceived=function(a){m-=p;v.refreshMoney(m);"true"===a.res?(x=parseInt(a.num_freespin),"true"===a.win?(w=JSON.parse(a.pattern),B=JSON.parse(a.win_lines),h=!1,1===parseInt(a.freespin)?(y=
BONUS_FREESPIN,f=!1,h=!0):0<parseInt(a.bonus)?(y=BONUS_GOALKEEPER,f=!1,A=a.bonus_prize):y=0,g=parseFloat(a.tot_win)):(y=0,w=JSON.parse(a.pattern),B=[]),b=!0,m=parseFloat(a.money)):s_oGame.generateLosingPattern();k=GAME_STATE_SPINNING};this.onInfoClicked=function(){k!==GAME_STATE_SPINNING&&(F.isVisible()?F.hide():F.show())};this.exitFromFreespinPanel=function(){v.refreshFreeSpinNum(x);H.gotoAndPlay("freespin");v.setSpinState(SPIN_BUT_STATE_FREESPIN);v.disableSpin();this.onSpin()};this.exitFromBonus=
function(){v.refreshMoney(m);if(f)this.onSpin();else this.removeWinShowing(),v.enableGuiButtons(),v.disableBetBut(!1),v.enableSpin();$(s_oMain).trigger("save_score",m)};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",{img:"200x200.jpg",title:TEXT_CONGRATULATIONS,msg:TEXT_MSG_SHARE1+m+TEXT_MSG_SHARE2,msg_share:TEXT_MSG_SHARING1+m+TEXT_MSG_SHARING2})};this.getState=function(){return k};this.update=function(){if(!1!==c){switch(k){case GAME_STATE_IDLE:if(f)return;
0===x&&(t+=s_iTimeElaps,t>TIME_SPIN_BUT_CHANGE&&(t=0,v.toggleAutoSpinImage()));v.update();break;case GAME_STATE_SPINNING:for(var a=0;a<z.length;a++)z[a].update();break;case GAME_STATE_SHOW_ALL_WIN:t+=s_iTimeElaps;t>TIME_SHOW_ALL_WINS&&this._prepareForWinsShowing();break;case GAME_STATE_BONUS:I.update()}O.update()}};s_oGame=this;this._init()}var s_oGame=null,s_oTweenController;
function CReelColumn(a,e,c,b){var f,h,k,n,u,r,q,t,l,d,p,m,g,x,y;this._init=function(a,b,c,g){k=h=f=!1;q=0;n=a;r=g;u=n<NUM_REELS?n:n-NUM_REELS;l=0;d=MAX_FRAMES_REEL_EASE;t=REEL_STATE_START;p=c;m=p+(SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS)*NUM_ROWS;this.initContainer(b,c)};this.initContainer=function(a,b){y=new createjs.Container;y.x=a;y.y=b;var c=0;g=[];x=[];for(var d=0;d<NUM_ROWS;d++){var f=s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)],e=createSprite(s_aSymbolData[f],"static",
0,0,SYMBOL_WIDTH,SYMBOL_HEIGHT);e.stop();e.x=0;e.y=c;y.addChild(e);g[d]=e;x[d]=f;c+=SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS}s_oAttachSection.addChild(y)};this.unload=function(){s_oAttachSection.removeChild(y)};this.activate=function(){p=y.y;m=p+(SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS)*NUM_ROWS;f=!0};this._setSymbol=function(a){y.removeAllChildren();for(var b=0,c=0;c<a.length;c++){var d=new createjs.Sprite(s_aSymbolData[a[c]],"static",0,0,SYMBOL_WIDTH,SYMBOL_HEIGHT);d.stop();d.x=0;d.y=b;y.addChild(d);
g[c]=d;x[c]=a[c];b+=SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS}};this.forceStop=function(a,b){null!==a&&this._setSymbol(a);y.y=b;f=!1;l=0;d=MAX_FRAMES_REEL_EASE;t=REEL_STATE_START;q=0;k=h=!1};this.setVisible=function(a,b){g[a].visible=b};this.restart=function(a,b){y.y=p=REEL_START_Y;m=p+(SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS)*NUM_ROWS;this._setSymbol(a);if(h=b){l=0;d=MAX_FRAMES_REEL_EASE;t=REEL_STATE_STOP;for(var c=0;c<NUM_ROWS;c++)g[c].gotoAndStop("static");k=!0}else for(c=0;c<NUM_ROWS;c++)g[c].gotoAndStop("moving")};
this.setReadyToStop=function(){l=0;d=MAX_FRAMES_REEL_EASE;t=REEL_STATE_STOP};this.isReadyToStop=function(){return h};this.getPosUpLeft=function(a){return{x:y.x,y:y.y+(SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS)*a}};this.getY=function(){return y.y};this._updateStart=function(){0===l&&n<NUM_REELS&&playSound("start_reel",1,0);l++;l>d&&(l=0,d/=2,t++,p=y.y,m=p+(SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS)*NUM_ROWS);var a=s_oTweenController.easeInBack(l,0,1,d),a=s_oTweenController.tweenValue(p,m,a);y.y=
a};this._updateMoving=function(){l++;l>d&&(l=0,p=y.y,m=p+(SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS)*NUM_ROWS);var a=s_oTweenController.easeLinear(l,0,1,d),a=s_oTweenController.tweenValue(p,m,a);y.y=a};this._updateStopping=function(){l++;if(l>=d)f=!1,l=0,d=MAX_FRAMES_REEL_EASE,t=REEL_STATE_START,q=0,h=!1,k&&(k=!1,y.y=REEL_OFFSET_Y),s_oGame.stopNextReel(x[0]===FREESPIN_SYMBOL||x[1]===FREESPIN_SYMBOL||x[2]===FREESPIN_SYMBOL?!0:!1,x[0]===BONUS_SYMBOL||x[1]===BONUS_SYMBOL||x[2]===BONUS_SYMBOL?!0:!1);
else{var a=s_oTweenController.easeOutCubic(l,0,1,d),a=s_oTweenController.tweenValue(p,m,a);y.y=a}};this.update=function(){if(!1!==f&&(q++,q>r))switch(!1===h&&y.y>REEL_ARRIVAL_Y&&s_oGame.reelArrived(n,u),t){case REEL_STATE_START:this._updateStart();break;case REEL_STATE_MOVING:this._updateMoving();break;case REEL_STATE_STOP:this._updateStopping()}};this._init(a,e,c,b)}
function CInterface(a,e,c){var b,f,h,k,n,u,r,q,t,l,d,p,m,g,x,y,A,D,J,z,G,B,E,w,K,M,H=null,N=null,L,v,F,I;this._init=function(a,c,e){var C=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-C.width/2-2;f=C.height/2+2;J=new CGfxButton(b,f,C,s_oAttachSection);J.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)C=s_oSpriteLibrary.getSprite("audio_icon"),x=b-C.width/2-2,y=C.height/2+2,E=new CToggle(x,y,C,s_bAudioActive),E.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);var C=window.document,A=C.documentElement;H=A.requestFullscreen||A.mozRequestFullScreen||A.webkitRequestFullScreen||A.msRequestFullscreen;N=C.exitFullscreen||C.mozCancelFullScreen||C.webkitExitFullscreen||C.msExitFullscreen;H&&(C=s_oSpriteLibrary.getSprite("but_fullscreen"),n=C.width/4+2,u=C.height/2+2,M=new CToggle(n,u,C,s_bFullscreen),M.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));this._initPaylines();C=s_oSpriteLibrary.getSprite("info_but");t=CANVAS_HEIGHT-C.height/2-80;
G=new CTextButton(420,t,C,TEXT_PAYTABLE,FONT_GAME_1,"#ffffff",24,s_oAttachSection);G.addEventListener(ON_MOUSE_UP,this._onInfo,this);C=s_oSpriteLibrary.getSprite("but_lines_bg");l=CANVAS_HEIGHT-C.height/2-80;B=new CTextButton(640,l,C,TEXT_LINES+" "+NUM_PAYLINES,FONT_GAME_1,"#ffffff",24,s_oAttachSection);B.addEventListener(ON_MOUSE_UP,this._onAddLine,this);C=s_oSpriteLibrary.getSprite("coin_but");d=CANVAS_HEIGHT-C.height/2-80;w=new CTextButton(860,d,C,TEXT_COIN+" "+a.toFixed(2),FONT_GAME_1,"#ffffff",
24,s_oAttachSection);w.addEventListener(ON_MOUSE_UP,this._onBet,this);C=s_oSpriteLibrary.getSprite("but_maxbet_bg");p=CANVAS_HEIGHT-C.height/2-80;K=new CTextButton(1080,p,C,TEXT_MAX_BET,FONT_GAME_1,"#ffffff",25,s_oAttachSection);K.addEventListener(ON_MOUSE_UP,this._onMaxBet,this);C=s_oSpriteLibrary.getSprite("but_spin");m=CANVAS_WIDTH-100;g=CANVAS_HEIGHT-C.height/2;z=new CSpinBut(m-s_iOffsetX,g-s_iOffsetY,C,C.width/5,C.height,s_oAttachSection);z.addEventListener(ON_MOUSE_UP,this._onSpin,this);q=CANVAS_HEIGHT-
140;L=new createjs.Text(TEXT_MONEY+": "+e.toFixed(2)+TEXT_CURRENCY,"26px "+FONT_GAME_2,"#ffde00");L.x=375;L.y=q;L.textAlign="left";L.textBaseline="alphabetic";s_oAttachSection.addChild(L);r=CANVAS_HEIGHT-140;v=new createjs.Text(TEXT_BET+": "+c.toFixed(2)+TEXT_CURRENCY,"26px "+FONT_GAME_2,"#ffde00");v.x=715;v.y=r;v.textAlign="left";v.textBaseline="alphabetic";v.shadow=new createjs.Shadow("#000000",1,1,2);s_oAttachSection.addChild(v);F=new createjs.Text(TEXT_WIN+": 0"+TEXT_CURRENCY,"26px "+FONT_GAME_2,
"#ffde00");F.x=1050;F.y=CANVAS_HEIGHT-140;F.textAlign="center";F.textBaseline="alphabetic";F.shadow=new createjs.Shadow("#000000",1,1,2);s_oAttachSection.addChild(F);h=CANVAS_WIDTH-108;k=CANVAS_HEIGHT-108;I=new createjs.Text("","70px "+FONT_GAME_1,"#ffde00");I.x=h-s_iOffsetX;I.y=k-s_iOffsetY;I.textAlign="center";I.textBaseline="alphabetic";s_oAttachSection.addChild(I);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){J.unload();J=null;z.unload();z=null;G.unload();G=null;B.unload();
B=null;w.unload();w=null;K.unload();K=null;!1===DISABLE_SOUND_MOBILE&&(E.unload(),E=null);for(var a=0;a<NUM_PAYLINES;a++)A[a].unload();H&&M.unload();s_oInterface=null};this.refreshButtonPos=function(a,c){J.setPosition(b-a,c+f);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||E.setPosition(x-a,c+y);m-a>CANVAS_WIDTH-300&&(z.setPosition(m-a,g-c),I.x=h-a,I.y=k-c);H&&M.setPosition(n+a,u+c)};this._initPaylines=function(){var a=s_oSpriteLibrary.getSprite("bet_but4");A=[];var c=a.height/2,b=77+c,d=new CBetBut(200+
a.width/2,b,s_oSpriteLibrary.getSprite("bet_but4"),"4",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,4);A[3]=d;b+=50;d=new CBetBut(200+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but2"),"2",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,2);A[1]=d;b+=50;d=new CBetBut(200+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but20"),"20",FONT_GAME_1,"#ffd202",24,s_oAttachSection);
d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,20);A[19]=d;b+=50;d=new CBetBut(200+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but17"),"17",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,17);A[16]=d;b+=50;d=new CBetBut(200+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but10"),"10",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,10);A[9]=d;b+=50;d=new CBetBut(200+
a.width/2,b,s_oSpriteLibrary.getSprite("bet_but1"),"1",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,1);A[0]=d;b+=51;d=new CBetBut(200+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but11"),"11",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,11);A[10]=d;b+=50;d=new CBetBut(200+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but16"),"16",FONT_GAME_1,"#ffd202",24,s_oAttachSection);
d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,16);A[15]=d;b+=50;d=new CBetBut(200+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but3"),"3",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,3);A[2]=d;d=new CBetBut(200+a.width/2,b+50,s_oSpriteLibrary.getSprite("bet_but5"),"5",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,5);A[4]=d;b=77+c;d=new CBetBut(1175+
a.width/2,b,s_oSpriteLibrary.getSprite("bet_but12"),"12",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,12);A[11]=d;b+=50;d=new CBetBut(1175+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but14"),"14",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,14);A[13]=d;b+=50;d=new CBetBut(1175+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but9"),"9",FONT_GAME_1,"#ffd202",24,s_oAttachSection);
d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,9);A[8]=d;b+=50;d=new CBetBut(1175+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but18"),"18",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,18);A[17]=d;b+=50;d=new CBetBut(1175+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but6"),"6",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,6);A[5]=d;b+=51;d=new CBetBut(1175+
a.width/2,b,s_oSpriteLibrary.getSprite("bet_but7"),"7",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,7);A[6]=d;b+=50;d=new CBetBut(1175+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but19"),"19",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,19);A[18]=d;b+=50;d=new CBetBut(1175+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but8"),"8",FONT_GAME_1,"#ffd202",24,s_oAttachSection);
d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,8);A[7]=d;b+=50;d=new CBetBut(1175+a.width/2,b,s_oSpriteLibrary.getSprite("bet_but13"),"13",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,13);A[12]=d;d=new CBetBut(1175+a.width/2,b+50,s_oSpriteLibrary.getSprite("bet_but15"),"15",FONT_GAME_1,"#ffd202",24,s_oAttachSection);d.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,15);A[14]=d;D=[];for(a=0;a<
NUM_PAYLINES;a++)c=createBitmap(s_oSpriteLibrary.getSprite("payline_"+(a+1))),c.visible=!1,s_oAttachSection.addChild(c),D[a]=c};this.refreshMoney=function(a){L.text=TEXT_MONEY+": "+a.toFixed(2)+TEXT_CURRENCY};this.refreshBet=function(a){w.setText(TEXT_COIN+" "+a.toFixed(2))};this.refreshTotalBet=function(a){v.text=TEXT_BET+": "+a.toFixed(2)+TEXT_CURRENCY};this.refreshNumLines=function(a){B.setText(TEXT_LINES+" "+a);for(var b=0;b<NUM_PAYLINES;b++)b<a?(A[b].setOn(),D[b].visible=!0):A[b].setOff();setTimeout(function(){for(var a=
0;a<NUM_PAYLINES;a++)D[a].visible=!1},1E3)};this.resetWin=function(){F.text=TEXT_WIN+": 0"+TEXT_CURRENCY};this.refreshWinText=function(a){F.text=TEXT_WIN+": "+a.toFixed(2)+TEXT_CURRENCY};this.refreshFreeSpinNum=function(a){I.text=a};this.showLine=function(a){D[a-1].visible=!0};this.hideLine=function(a){D[a-1].visible=!1};this.hideAllLines=function(){for(var a=0;a<NUM_PAYLINES;a++)D[a].visible=!1};this.disableBetBut=function(a){for(var b=0;b<NUM_PAYLINES;b++)A[b].disable(a)};this.enableGuiButtons=
function(){z.enable();K.enable();w.enable();B.enable();G.enable()};this.enableSpin=function(){z.enable();K.enable()};this.disableSpin=function(){z.disable();K.disable()};this.disableGuiButtons=function(){z.getState()!==SPIN_BUT_STATE_FREESPIN&&z.setState(SPIN_BUT_STATE_STOP);K.disable();w.disable();B.disable();G.disable()};this.toggleAutoSpinImage=function(){z.toggleAutoSpinImage()};this.setSpinState=function(a){z.setState(a)};this._onBetLineClicked=function(a){this.refreshNumLines(a);s_oGame.activateLines(a)};
this._onExit=function(){s_oGame.onExit()};this._onSpin=function(a){if(a===SPIN_BUT_STATE_AUTOSPIN)s_oGame.onAutoSpin();else if(a===SPIN_BUT_STATE_SPIN||a===SPIN_BUT_STATE_AUTOSPIN)s_oGame.onSpin();else if(a===SPIN_BUT_STATE_SKIP)s_oGame.onSkip();else s_oGame.forceStopReel()};this._onAddLine=function(){s_oGame.addLine()};this._onInfo=function(){s_oGame.onInfoClicked()};this._onBet=function(){s_oGame.changeCoinBet()};this._onMaxBet=function(){s_oGame.onMaxBet()};this._onFullscreenRelease=function(){s_bFullscreen?
(N.call(window.document),s_bFullscreen=!1):(H.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.update=function(){z.update()};s_oInterface=this;this._init(a,e,c);return this}var s_oInterface=null;
function CPayTablePanel(){var a,e,c,b,f,h,k,n,u,r,q,t;this._init=function(){c=0;h=[];q=new createjs.Container;q.on("click",function(){});q.visible=!1;s_oAttachSection.addChild(q);var l=new createjs.Container;q.addChild(l);var d=createBitmap(s_oSpriteLibrary.getSprite("paytable1"));l.addChild(d);b=[];var p=544,m=268;b[0]=[];for(d=0;3>d;d++){var g=new createjs.Text("X"+(5-d),"21px "+FONT_GAME_1,"#ffffff");g.textAlign="center";g.x=p;g.y=m;g.textBaseline="alphabetic";l.addChild(g);b[0][d]=g;m+=24}p=764;
m=268;b[1]=[];for(d=0;3>d;d++)g=new createjs.Text("X"+(5-d),"21px "+FONT_GAME_1,"#ffffff"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),b[1][d]=g,m+=24;p=984;m=268;b[2]=[];for(d=0;3>d;d++)g=new createjs.Text("X"+(5-d),"21px "+FONT_GAME_1,"#ffffff"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),b[2][d]=g,m+=24;p=435;m=378;b[3]=[];for(d=0;3>d;d++)g=new createjs.Text("X"+(5-d),"21px "+FONT_GAME_1,"#ffffff"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline=
"alphabetic",l.addChild(g),b[3][d]=g,m+=24;p=655;m=378;b[4]=[];for(d=0;3>d;d++)g=new createjs.Text("X"+(5-d),"21px "+FONT_GAME_1,"#ffffff"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),b[4][d]=g,m+=24;p=875;m=378;b[5]=[];for(d=0;3>d;d++)g=new createjs.Text("X"+(5-d),"21px "+FONT_GAME_1,"#ffffff"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),b[5][d]=g,m+=24;p=1095;m=378;b[6]=[];for(d=0;3>d;d++)g=new createjs.Text("X"+(5-d),"21px "+FONT_GAME_1,
"#ffffff"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),b[6][d]=g,m+=24;p=544;m=488;b[7]=[];for(d=0;3>d;d++)g=new createjs.Text("X"+(5-d),"21px "+FONT_GAME_1,"#ffffff"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),b[7][d]=g,m+=24;p=764;m=488;b[8]=[];for(d=0;3>d;d++)g=new createjs.Text("X"+(5-d),"21px "+FONT_GAME_1,"#ffffff"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),b[8][d]=g,m+=24;p=984;m=488;b[9]=[];for(d=
0;3>d;d++)g=new createjs.Text("X"+(5-d),"21px "+FONT_GAME_1,"#ffffff"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),b[9][d]=g,m+=24;f=[];p=589;m=268;f[0]=[];for(d=0;3>d;d++)g=new createjs.Text("","21px "+FONT_GAME_1,"#ffff00"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),f[0][d]=g,m+=24;p=589;m=268;f[1]=[];for(d=0;3>d;d++)g=new createjs.Text(s_aSymbolWin[1][4-d],"21px "+FONT_GAME_1,"#ffff00"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline=
"alphabetic",l.addChild(g),f[1][d]=g,m+=24;p=809;m=268;f[2]=[];for(d=0;3>d;d++)g=new createjs.Text(s_aSymbolWin[2][4-d],"21px "+FONT_GAME_1,"#ffff00"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),f[2][d]=g,m+=24;p=1029;m=268;f[3]=[];for(d=0;3>d;d++)g=new createjs.Text(s_aSymbolWin[3][4-d],"21px "+FONT_GAME_1,"#ffff00"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),f[3][d]=g,m+=24;p=480;m=378;f[4]=[];for(d=0;3>d;d++)g=new createjs.Text(s_aSymbolWin[4][4-
d],"21px "+FONT_GAME_1,"#ffff00"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),f[4][d]=g,m+=24;p=700;m=378;f[5]=[];for(d=0;3>d;d++)g=new createjs.Text(s_aSymbolWin[5][4-d],"21px "+FONT_GAME_1,"#ffff00"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),f[5][d]=g,m+=24;p=920;m=378;f[6]=[];for(d=0;3>d;d++)g=new createjs.Text(s_aSymbolWin[6][4-d],"21px "+FONT_GAME_1,"#ffff00"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),
f[6][d]=g,m+=24;p=1140;m=378;f[7]=[];for(d=0;3>d;d++)g=new createjs.Text(s_aSymbolWin[7][4-d],"21px "+FONT_GAME_1,"#ffff00"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),f[7][d]=g,m+=24;p=589;m=488;f[8]=[];for(d=0;3>d;d++)g=new createjs.Text(s_aSymbolWin[7][4-d],"21px "+FONT_GAME_1,"#ffff00"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),f[8][d]=g,m+=24;p=809;m=488;f[9]=[];for(d=0;3>d;d++)g=new createjs.Text(s_aSymbolWin[7][4-d],"21px "+FONT_GAME_1,
"#ffff00"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),f[9][d]=g,m+=24;p=1029;m=488;f[10]=[];for(d=0;3>d;d++)g=new createjs.Text(s_aSymbolWin[7][4-d],"21px "+FONT_GAME_1,"#ffff00"),g.textAlign="center",g.x=p,g.y=m,g.textBaseline="alphabetic",l.addChild(g),f[10][d]=g,m+=24;h[0]=l;l=new createjs.Container;l.visible=!1;q.addChild(l);d=createBitmap(s_oSpriteLibrary.getSprite("paytable2"));l.addChild(d);h[1]=l;k=h[c];l=new createjs.Container;l.visible=!1;q.addChild(l);d=
createBitmap(s_oSpriteLibrary.getSprite("paytable3"));l.addChild(d);g=new createjs.Text(TEXT_HELP_BONUS1,"28px "+FONT_GAME_1,"#fff");g.textAlign="center";g.x=976;g.y=264;g.lineWidth=400;l.addChild(g);d=new createjs.Text(TEXT_HELP_BONUS2,"40px "+FONT_GAME_1,"#fff");d.textAlign="center";d.x=976;d.y=430;d.lineWidth=400;l.addChild(d);h[2]=l;l=new createjs.Container;l.visible=!1;q.addChild(l);d=createBitmap(s_oSpriteLibrary.getSprite("paytable4"));l.addChild(d);g=new createjs.Text(TEXT_HELP_FREESPIN,"40px "+
FONT_GAME_1,"#fff");g.textAlign="center";g.x=CANVAS_WIDTH/2;g.y=420;g.lineWidth=400;l.addChild(g);h[3]=l;k=h[c];u=new CGfxButton(CANVAS_WIDTH-290,CANVAS_HEIGHT-160,s_oSpriteLibrary.getSprite("but_arrow_next"),q);u.addEventListener(ON_MOUSE_UP,this._onNext,this);r=new CGfxButton(290,CANVAS_HEIGHT-160,s_oSpriteLibrary.getSprite("but_arrow_prev"),q);r.addEventListener(ON_MOUSE_UP,this._onPrev,this);l=s_oSpriteLibrary.getSprite("but_credits");a=l.width/2+2;e=l.height/2+2;t=new CGfxButton(a,e,l,q);t.addEventListener(ON_MOUSE_UP,
this._onCredits,this);l=s_oSpriteLibrary.getSprite("but_exit_info");n=new CGfxButton(1220,154,l,q);n.addEventListener(ON_MOUSE_UP,this._onExit,this)};this.unload=function(){q.off("click",function(){});n.unload();u.unload();r.unload();t.unload();s_oAttachSection.removeChild(q);for(var a=0;a<b.length;a++)q.removeChild(b[a]);for(a=0;a<f.length;a++)q.removeChild(f[a])};this._onNext=function(){c===h.length-1?c=0:c++;k.visible=!1;h[c].visible=!0;k=h[c]};this._onPrev=function(){0===c?c=h.length-1:c--;k.visible=
!1;h[c].visible=!0;k=h[c]};this._onCredits=function(){new CCreditsPanel};this.refreshButtonPos=function(b,c){t.setPosition(a+b,e+c)};this.show=function(){c=0;k.visible=!1;h[c].visible=!0;k=h[c];q.visible=!0};this.hide=function(){q.visible=!1};this.resetHighlightCombo=function(){for(var a=0;a<b.length;a++)for(var c=0;c<b[a].length;c++)b[a][c].color="#ffffff",f[a][c].color="#ffff00",createjs.Tween.removeTweens(f[a][c]),f[a][c].alpha=1};this.highlightCombo=function(a,b){f[a-1][NUM_REELS-b].color="#ff9000";
this.tweenAlpha(f[a-1][NUM_REELS-b],0)};this.tweenAlpha=function(a,b){var c=this;createjs.Tween.get(a).to({alpha:b},200).call(function(){1===b?c.tweenAlpha(a,0):c.tweenAlpha(a,1)})};this._onExit=function(){s_oGame.hidePayTable()};this.isVisible=function(){return q.visible};this._init()}
function CStaticSymbolCell(a,e,c,b){var f,h,k,n,u=-1,r,q,t,l,d,p,m,g,x;this._init=function(a,b,c,e){k=c;n=e;f=0;g=new createjs.Container;g.visible=!1;s_oAttachSection.addChild(g);m=new createjs.Container;m.visible=!1;m.x=c;m.y=e;g.addChild(m);r=[];for(a=0;a<NUM_SYMBOLS;a++)b=createSprite(s_aSymbolAnims[a],"static",0,0,SYMBOL_ANIM_WIDTH,SYMBOL_ANIM_HEIGHT),b.stop(),b.on("animationend",this._onAnimEnded,null,!1),m.addChild(b),r[a]=b,r[a].visible=!1;a=s_oSpriteLibrary.getSprite("amount_win_bg");p=createBitmap(a);
p.regX=a.width/2;p.regY=a.height/2;p.x=SYMBOL_ANIM_WIDTH/2;p.y=SYMBOL_ANIM_HEIGHT;m.addChild(p);d=new createjs.Text("","48px "+FONT_GAME_1,"#000");d.textAlign="center";d.textBaseline="alphabetic";d.x=SYMBOL_ANIM_WIDTH/2+2;d.y=SYMBOL_ANIM_HEIGHT+17;m.addChild(d);l=new createjs.Text("","48px "+FONT_GAME_1,"#ffd102");l.textAlign="center";l.textBaseline="alphabetic";l.x=SYMBOL_ANIM_WIDTH/2;l.y=SYMBOL_ANIM_HEIGHT+15;m.addChild(l);a={framerate:20,images:[s_oSpriteLibrary.getSprite("win_frame_anim")],frames:{width:SYMBOL_WIDTH,
height:SYMBOL_HEIGHT},animations:{"static":[0],anim:[1,19]}};a=new createjs.SpriteSheet(a);t=new createjs.Sprite(a,"static",0,0,SYMBOL_WIDTH,SYMBOL_HEIGHT);t.stop();t.x=c;t.y=e;g.addChild(t)};this.unload=function(){s_oAttachSection.removeChild(g)};this.hide=function(){-1<u&&(stopSound(q),t.gotoAndStop("static"),t.visible=!1,r[u].gotoAndPlay("static"),r[u].visible=!1,g.visible=!1,u=-1)};this.show=function(a,b,c,e,t){f=0;h=t;for(t=0;t<NUM_SYMBOLS;t++)r[t].visible=t+1===a?!0:!1;0<b?(l.text="x"+b,d.text=
"x"+b,p.visible=!0):p.visible=!1;r[a-1].gotoAndPlay("anim");u=a-1;r[a-1].spriteSheet.getNumFrames();m.regX=e.x;m.regY=e.y;m.x=k+c.x;m.y=n+c.y;m.scaleX=m.scaleY=.5;m.visible=!0;m.alpha=1;g.visible=!0;createjs.Tween.get(m).to({scaleX:1,scaleY:1},1500,createjs.Ease.cubicOut);q=9===a||10===a||11===a?playSound("symbol9_10_11",1,0):playSound("symbol"+a,1,0)};this.showWinFrame=function(){t.gotoAndPlay("anim");t.visible=!0;g.visible=!0};this.hideWinFrame=function(){t.gotoAndPlay("static");t.visible=!1;g.visible=
!1};this._onAnimEnded=function(){f++;f===h&&(r[u].stop(),createjs.Tween.get(m).to({scaleX:.52,scaleY:.52,alpha:0},500,createjs.Ease.cubicOut).call(function(){x.stopAnim();s_oGame.showWin()}))};this.stopAnim=function(){stopSound(q);r[u].visible=!1;m.visible=!1;t.gotoAndStop("static");t.visible=!1};x=this;this._init(a,e,c,b)}
function CTweenController(){this.tweenValue=function(a,e,c){return a+c*(e-a)};this.easeLinear=function(a,e,c,b){return c*a/b+e};this.easeInCubic=function(a,e,c,b){b=(a/=b)*a*a;return e+c*b};this.easeBackInQuart=function(a,e,c,b){b=(a/=b)*a;return e+c*(2*b*b+2*b*a+-3*b)};this.easeInBack=function(a,e,c,b){return c*(a/=b)*a*(2.70158*a-1.70158)+e};this.easeOutCubic=function(a,e,c,b){return c*((a=a/b-1)*a*a+1)+e};this.getTrajectoryPoint=function(a,e){var c=new createjs.Point,b=(1-a)*(1-a),f=a*a;c.x=b*
e.start.x+2*(1-a)*a*e.traj.x+f*e.end.x;c.y=b*e.start.y+2*(1-a)*a*e.traj.y+f*e.end.y;return c}}
function CMsgBox(){var a,e,c,b,f;this._init=function(){f=new createjs.Container;f.visible=!1;s_oStage.addChild(f);a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));f.addChild(a);c=new createjs.Text("","30px "+FONT_GAME_1,"#000");c.x=CANVAS_WIDTH/2+2;c.y=CANVAS_HEIGHT/2-48;c.lineWidth=400;c.textAlign="center";f.addChild(c);e=new createjs.Text("","30px "+FONT_GAME_1,"#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-50;e.textAlign="center";e.lineWidth=400;f.addChild(e);b=new CGfxButton(CANVAS_WIDTH/
2+210,CANVAS_HEIGHT/2-110,s_oSpriteLibrary.getSprite("but_exit_info"),f);b.addEventListener(ON_MOUSE_UP,this._onExit,this)};this.show=function(a){c.text=a;e.text=a;f.visible=!0};this.hide=function(){f.visible=!1};this._onExit=function(){this.hide()};this._init();return this}
function CVector2(a,e){var c,b;this._init=function(a,e){c=a;b=e};this.add=function(a,e){c+=a;b+=e};this.addV=function(a){c+=a.getX();b+=a.getY()};this.scalarDivision=function(a){c/=a;b/=a};this.subV=function(a){c-=a.getX();b-=a.getY()};this.scalarProduct=function(a){c*=a;b*=a};this.invert=function(){c*=-1;b*=-1};this.dotProduct=function(a){return c*a.getX()+b*a.getY()};this.set=function(a,e){c=a;b=e};this.setV=function(a){c=a.getX();b=a.getY()};this.length=function(){return Math.sqrt(c*c+b*b)};this.length2=
function(){return c*c+b*b};this.normalize=function(){var a=this.length();0<a&&(c/=a,b/=a)};this.getNormalize=function(a){this.length();a.set(c,b);a.normalize()};this.rot90CCW=function(){var a=c;c=-b;b=a};this.rot90CW=function(){var a=c;c=b;b=-a};this.getRotCCW=function(a){a.set(c,b);a.rot90CCW()};this.getRotCW=function(a){a.set(c,b);a.rot90CW()};this.ceil=function(){c=Math.ceil(c);b=Math.ceil(b)};this.round=function(){c=Math.round(c);b=Math.round(b)};this.toString=function(){return"Vector2: "+c+", "+
b};this.print=function(){trace("Vector2: "+c+", "+b+"")};this.getX=function(){return c};this.getY=function(){return b};this._init(a,e)}
function CBonusPanel(){var a,e=!1,c=!1,b,f,h,k,n,u,r,q,t,l,d,p,m,g,x,y,A,D,J,z,G,B,E,w;this._init=function(){a=!1;e=!0;b=-1;w.removeAllChildren();var c=createBitmap(s_oSpriteLibrary.getSprite("bg_bonus"));w.addChild(c);c=s_oSpriteLibrary.getSprite("ball_shadow");y=createBitmap(c);y.x=CANVAS_WIDTH/2-100;y.y=CANVAS_HEIGHT-330;w.addChild(y);A=new CBonusBall(CANVAS_WIDTH/2,538,w);c=s_oSpriteLibrary.getSprite("but_goal");l=new CGfxButton(425,155,c,w);l.addEventListenerWithParams(ON_MOUSE_UP,this._onShot,
this,BONUS_BUTTON_1);d=new CGfxButton(495,235,c,w);d.addEventListenerWithParams(ON_MOUSE_UP,this._onShot,this,BONUS_BUTTON_2);p=new CGfxButton(565,315,c,w);p.addEventListenerWithParams(ON_MOUSE_UP,this._onShot,this,BONUS_BUTTON_3);m=new CGfxButton(1080,155,c,w);m.addEventListenerWithParams(ON_MOUSE_UP,this._onShot,this,BONUS_BUTTON_4);g=new CGfxButton(1010,235,c,w);g.addEventListenerWithParams(ON_MOUSE_UP,this._onShot,this,BONUS_BUTTON_5);x=new CGfxButton(940,315,c,w);x.addEventListenerWithParams(ON_MOUSE_UP,
this._onShot,this,BONUS_BUTTON_6);D=new CBonusGoalkeeper(w);J=new CBonusPlayer(646,0,w);this._startBonus()};this._loadAllResources=function(){w=new createjs.Container;w.on("click",function(){});s_oAttachSection.addChild(w);var a=s_oSpriteLibrary.getSprite("bg_loading_bonus");G=createBitmap(a);w.addChild(G);a=s_oSpriteLibrary.getSprite("progress_bar");E=createBitmap(a);E.x=CANVAS_WIDTH/2-a.width/2;E.y=CANVAS_HEIGHT-170;w.addChild(E);n=a.width;u=a.height;t=new createjs.Shape;t.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(E.x,
E.y,1,u);w.addChild(t);E.mask=t;B=new createjs.Text("","30px "+FONT_GAME_1,"#fff");B.x=CANVAS_WIDTH/2;B.y=CANVAS_HEIGHT-125;B.shadow=new createjs.Shadow("#000",2,2,2);B.textBaseline="alphabetic";B.textAlign="center";w.addChild(B);s_oSpriteLibrary.init(this._onResourceBonusLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_bonus","./sprites/bonus/bg_bonus.jpg");s_oSpriteLibrary.addSprite("ball_shadow","./sprites/bonus/ball_shadow.png");s_oSpriteLibrary.addSprite("but_goal","./sprites/bonus/but_goal.png");
s_oSpriteLibrary.addSprite("ball_anim","./sprites/bonus/ball_anim.png");s_oSpriteLibrary.addSprite("bonus_panel_bg","./sprites/bonus/bonus_panel_bg.png");for(a=0;23>a;a++)s_oSpriteLibrary.addSprite("gk_idle_"+a,"./sprites/bonus/goalkeeper_idle/gk_idle_"+a+".png");for(a=0;33>a;a++)s_oSpriteLibrary.addSprite("gk_save_left_"+a,"./sprites/bonus/goalkeeper_save_left/gk_save_left_"+a+".png"),s_oSpriteLibrary.addSprite("gk_save_right_"+a,"./sprites/bonus/goalkeeper_save_right/gk_save_right_"+a+".png");for(a=
0;30>a;a++)s_oSpriteLibrary.addSprite("player_"+a,"./sprites/bonus/player/player_"+a+".png");r=0;q=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites();c=!0};this._onResourceBonusLoaded=function(){r++;var a=Math.floor(r/q*100);B.text=a+"%";t.graphics.clear();a=Math.floor(a*n/100);t.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(E.x,E.y,a,u);r===q&&this._init()};this._onAllImagesLoaded=function(){};this.show=function(a){f=a;e?this._startBonus():this._loadAllResources()};this.hide=
function(){a=!1;w.off("click",function(){});w.visible=!1;z.unload();this._enableAllButtons();c=!1};this._startBonus=function(){y.visible=!0;D.show();w.on("click",function(){});a=w.visible=!0;b=STATE_BONUS_IDLE};this._enableAllButtons=function(){d.setVisible(!0);g.setVisible(!0);p.setVisible(!0);x.setVisible(!0);l.setVisible(!0);m.setVisible(!0)};this._disableAllButtons=function(){d.setVisible(!1);g.setVisible(!1);p.setVisible(!1);x.setVisible(!1);l.setVisible(!1);m.setVisible(!1)};this._onShot=function(a){s_oBonusPanel._disableAllButtons();
switch(a){case BONUS_BUTTON_1:h=l.getX();k=l.getY();break;case BONUS_BUTTON_2:h=d.getX();k=d.getY();break;case BONUS_BUTTON_3:h=p.getX();k=p.getY();break;case BONUS_BUTTON_4:h=m.getX();k=m.getY();break;case BONUS_BUTTON_5:h=g.getX();k=g.getY();break;case BONUS_BUTTON_6:h=x.getX(),k=x.getY()}b=STATE_BONUS_KICK;J.show()};this.kick=function(){playSound("kick",1,0);y.visible=!1;A.show(h,k);D.dive(Math.round(Math.random()+1))};this.ballArrived=function(){b=STATE_BONUS_WIN;new CScoreText(f,h,k);setTimeout(function(){z=
new CBonusResultPanel(f,w)},2E3)};this.unload=function(){this.hide();s_oGame.exitFromBonus()};this.isVisible=function(){return c};this.update=function(){if(a)switch(b){case STATE_BONUS_IDLE:D.update();break;case STATE_BONUS_KICK:D.update(),J.update(),A.update()}};s_oBonusPanel=this}var s_oBonusPanel=null,s_aSession=[],NUM_ROWS=3,NUM_REELS=5,_aFinalSymbols=[],_aPaylineCombo=[],_aPaylineCombo=_initPaylines(),_aSymbolWin=[],_aSymbolWin=_initSymbolWin(),_iNumSymbolFreeSpin=0;s_aSession.bBonus=0;
function _initSettings(){s_aSession.iMoney=TOTAL_MONEY;s_aSession.iSlotCash=SLOT_CASH;s_aSession.win_occurrence=WIN_OCCURRENCE;s_aSession.freespin_occurrence=FREESPIN_OCCURRENCE;s_aSession.bonus_occurrence=BONUS_OCCURRENCE;s_aSession.freespin_symbol_num_occur=FREESPIN_SYMBOL_NUM_OCCURR;s_aSession.num_freespin=NUM_FREESPIN;s_aSession.bonus_prize=BONUS_PRIZE;s_aSession.bonus_prize_occur=BONUS_PRIZE_OCCURR;s_aSession.coin_bet=COIN_BET}
function checkLogin(){s_aSession.iTotFreeSpin=0;s_aSession.bFreeSpin=0;_initSettings();_setMinWin();return _tryToCheckLogin()}function callSpin(a,e,c){return _onSpin(a,e,c)}function _tryToCheckLogin(){for(var a=[],e=0;e<_aSymbolWin.length;e++)a[e]=_aSymbolWin[e].join(",");return"res=true&login=true&money="+s_aSession.iMoney+"&bonus_prize="+s_aSession.bonus_prize.join("#")+"&paytable="+a.join("#")+"&coin_bet="+s_aSession.coin_bet.join("#")}
function _setMinWin(){s_aSession.min_win=_aSymbolWin[0][_aSymbolWin[0].length-1];for(var a=0;a<_aSymbolWin.length;a++)for(var e=_aSymbolWin[a],c=0;c<e.length;c++)0!==e[c]&&e[c]<s_aSession.min_win&&(s_aSession.min_win=e[c])}
function _onSpin(a,e,c){if(c>s_aSession.iMoney)_dieError("INVALID BET: "+c+",money:"+s_aSession.iMoney);else{s_aSession.iMoney-=c;s_aSession.iSlotCash+=c;var b=s_aSession.bBonus=0,f=0;if(s_aSession.iSlotCash<s_aSession.min_win)return generLosingPattern(),1===s_aSession.bFreeSpin&&(--s_aSession.iTotFreeSpin,0>s_aSession.iTotFreeSpin&&(s_aSession.iTotFreeSpin=0,s_aSession.bFreeSpin=0)),"res=true&win=false&pattern="+JSON.stringify(_aFinalSymbols)+"&money="+s_aSession.iMoney+"&freespin=0&num_freespin="+
s_aSession.iTotFreeSpin+"&bonus=false&bonus_prize=-1&cash="+s_aSession.iSlotCash;var h;if(Math.floor(100*Math.random())<s_aSession.win_occurrence){0===s_aSession.bFreeSpin&&0===s_aSession.bBonus&&(h=Math.floor(100*Math.random()),0===s_aSession.iTotFreeSpin&&h<s_aSession.freespin_occurrence+s_aSession.bonus_occurrence&&(h=Math.floor(Math.random()*(s_aSession.freespin_occurrence+s_aSession.bonus_occurrence)+1),h<=s_aSession.freespin_occurrence?b=1:f=1));do{generateRandomSymbols(b,f);h=checkWin(b,f,
a);for(var k=0,n=0;n<h.length;n++)k+=h[n].amount;k*=e}while(0===h.length||k>s_aSession.iSlotCash||k<c);s_aSession.iMoney+=k;s_aSession.iSlotCash-=k;a=-1;if(1===b&&2<_iNumSymbolFreeSpin)s_aSession.bFreeSpin=1,s_aSession.iTotFreeSpin=s_aSession.num_freespin[_iNumSymbolFreeSpin-3];else if(1===s_aSession.bFreeSpin)--s_aSession.iTotFreeSpin,0>s_aSession.iTotFreeSpin&&(s_aSession.iTotFreeSpin=0,s_aSession.bFreeSpin=0);else if(1===f){s_aSession.bBonus=1;f=[];for(a=0;a<s_aSession.bonus_prize_occur.length;a++)for(e=
s_aSession.bonus_prize_occur[a],c=0;c<e;c++)f.push(a);a=f[Math.floor(Math.random()*f.length)]}-1!==a&&(s_aSession.iMoney+=s_aSession.bonus_prize[a],s_aSession.iSlotCash-=s_aSession.bonus_prize[a]);return"res=true&win=true&pattern="+JSON.stringify(_aFinalSymbols)+"&win_lines="+JSON.stringify(h)+"&money="+s_aSession.iMoney+"&tot_win="+k+"&freespin="+b+"&num_freespin="+s_aSession.iTotFreeSpin+"&bonus="+s_aSession.bBonus+"&bonus_prize="+a+"&cash="+s_aSession.iSlotCash}generLosingPattern();1===s_aSession.bFreeSpin&&
(--s_aSession.iTotFreeSpin,0>s_aSession.iTotFreeSpin&&(s_aSession.iTotFreeSpin=0,s_aSession.bFreeSpin=0));return"res=true&win=false&pattern="+JSON.stringify(_aFinalSymbols)+"&money="+s_aSession.iMoney+"&freespin=0&num_freespin="+s_aSession.iTotFreeSpin+"&bonus=false&bonus_prize=-1"}}
function _initPaylines(){_aPaylineCombo[0]=[{row:1,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:1,col:4}];_aPaylineCombo[1]=[{row:0,col:0},{row:0,col:1},{row:0,col:2},{row:0,col:3},{row:0,col:4}];_aPaylineCombo[2]=[{row:2,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:2,col:4}];_aPaylineCombo[3]=[{row:0,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:0,col:4}];_aPaylineCombo[4]=[{row:2,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:2,col:4}];_aPaylineCombo[5]=[{row:1,
col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:1,col:4}];_aPaylineCombo[6]=[{row:1,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:1,col:4}];_aPaylineCombo[7]=[{row:2,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:2,col:4}];_aPaylineCombo[8]=[{row:0,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:0,col:4}];_aPaylineCombo[9]=[{row:1,col:0},{row:0,col:1},{row:1,col:2},{row:0,col:3},{row:1,col:4}];_aPaylineCombo[10]=[{row:1,col:0},{row:2,col:1},{row:1,col:2},{row:2,col:3},{row:1,
col:4}];_aPaylineCombo[11]=[{row:0,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:0,col:4}];_aPaylineCombo[12]=[{row:2,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:2,col:4}];_aPaylineCombo[13]=[{row:0,col:0},{row:0,col:1},{row:1,col:2},{row:0,col:3},{row:0,col:4}];_aPaylineCombo[14]=[{row:2,col:0},{row:2,col:1},{row:1,col:2},{row:2,col:3},{row:2,col:4}];_aPaylineCombo[15]=[{row:2,col:0},{row:2,col:1},{row:1,col:2},{row:0,col:3},{row:0,col:4}];_aPaylineCombo[16]=[{row:0,col:0},{row:0,
col:1},{row:1,col:2},{row:2,col:3},{row:2,col:4}];_aPaylineCombo[17]=[{row:0,col:0},{row:0,col:1},{row:2,col:2},{row:0,col:3},{row:0,col:4}];_aPaylineCombo[18]=[{row:2,col:0},{row:2,col:1},{row:0,col:2},{row:2,col:3},{row:2,col:4}];_aPaylineCombo[19]=[{row:0,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:0,col:4}];return _aPaylineCombo}
function _initSymbolWin(){_aSymbolWin[0]=[0,0,0,0,0];_aSymbolWin[1]=[0,0,80,110,160];_aSymbolWin[2]=[0,0,70,100,150];_aSymbolWin[3]=[0,0,50,80,110];_aSymbolWin[4]=[0,0,40,60,80];_aSymbolWin[5]=[0,0,30,50,70];_aSymbolWin[6]=[0,0,20,30,50];_aSymbolWin[7]=[0,0,10,20,30];_aSymbolWin[8]=[0,0,5,15,50];_aSymbolWin[9]=[0,0,5,15,50];_aSymbolWin[10]=[0,0,5,15,50];_aSymbolWin[11]=[0,0,0,0,0,50];_aSymbolWin[12]=[0,0,0,0,0,50];return _aSymbolWin}
function generLosingPattern(){for(var a=[],e=0;e<NUM_ROWS;e++){do var c=Math.floor(Math.random()*s_aRandSymbols.length);while(s_aRandSymbols[c]===BONUS_SYMBOL||s_aRandSymbols[c]===FREESPIN_SYMBOL||s_aRandSymbols[c]===WILD_SYMBOL);c=s_aRandSymbols[c];a[e]=c}for(e=0;e<NUM_ROWS;e++){_aFinalSymbols[e]=[];for(var b=0;b<NUM_REELS;b++)if(0==b)_aFinalSymbols[e][b]=a[e];else{do c=Math.floor(Math.random()*s_aRandSymbols.length),c=s_aRandSymbols[c];while(a[0]===c||a[1]===c||a[2]===c||c===BONUS_SYMBOL||c===FREESPIN_SYMBOL||
c===WILD_SYMBOL);_aFinalSymbols[e][b]=c}}}
function generateRandomSymbols(a,e){for(var c=0;c<NUM_ROWS;c++){_aFinalSymbols[c]=[];for(var b=0;b<NUM_REELS;b++){do iRandSymbol=s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)],_aFinalSymbols[c][b]=iRandSymbol;while(iRandSymbol===BONUS_SYMBOL||iRandSymbol===FREESPIN_SYMBOL)}}if(1===a){for(var f=[],c=0;c<s_aSession.freespin_symbol_num_occur.length;c++)for(b=0;b<s_aSession.freespin_symbol_num_occur[c];b++)f.push(c);_iNumSymbolFreeSpin=3+f[Math.floor(Math.random()*f.length)];c=[0,1,2,
3,4];c=shuffle(c);for(b=0;b<_iNumSymbolFreeSpin;b++)f=Math.floor(3*Math.random()),_aFinalSymbols[f][c[b]]=FREESPIN_SYMBOL}else if(1===e)for(var c=[0,1,2,3,4],c=shuffle(c),h=Math.floor(3*Math.random()+3),b=0;b<h;b++)f=Math.floor(3*Math.random()),_aFinalSymbols[f][c[b]]=BONUS_SYMBOL}
function checkWin(a,e,c){for(var b=[],f=0;f<c;f++){var h=_aPaylineCombo[f],k=[],n=_aFinalSymbols[h[0].row][h[0].col],u=1,r=1;for(k.push({row:h[0].row,col:h[0].col,value:_aFinalSymbols[h[0].row][h[0].col]});n===WILD_SYMBOL&&r<NUM_REELS;)u++,n=_aFinalSymbols[h[r].row][h[r].col],k.push({row:h[r].row,col:h[r].col,value:_aFinalSymbols[h[r].row][h[r].col]}),r++;for(;r<h.length;r++)if(_aFinalSymbols[h[r].row][h[r].col]===n||_aFinalSymbols[h[r].row][h[r].col]===WILD_SYMBOL)u++,k.push({row:h[r].row,col:h[r].col,
value:_aFinalSymbols[h[r].row][h[r].col]});else break;!(0<_aSymbolWin[n-1][u-1])||1===a&&n===FREESPIN_SYMBOL||1===e&&n===BONUS_SYMBOL||(k.sort(sortListByCol),b.push({line:f+1,amount:_aSymbolWin[n-1][u-1],num_win:u,value:n,list:k}))}if(1===a){k=[];for(a=0;a<NUM_ROWS;a++)for(e=0;e<NUM_REELS;e++)_aFinalSymbols[a][e]===FREESPIN_SYMBOL&&k.push({row:a,col:e,value:FREESPIN_SYMBOL});k.sort(sortListByCol);b.push({line:0,amount:0,num_win:k.length,value:FREESPIN_SYMBOL,list:k})}else if(1===e){k=[];for(a=0;a<
NUM_ROWS;a++)for(e=0;e<NUM_REELS;e++)_aFinalSymbols[a][e]===BONUS_SYMBOL&&k.push({row:a,col:e,value:BONUS_SYMBOL});k.sort(sortListByCol);b.push({line:0,amount:0,num_win:k.length,value:BONUS_SYMBOL,list:k})}return b}function shuffle(a){for(var e,c,b=a.length;b;e=Math.floor(Math.random()*b),c=a[--b],a[b]=a[e],a[e]=c);return a}function sortListByCol(a,e){return a.col<e.col?-1:a.col>e.col?1:0}function _dieError(a){return"res=false&desc="+a}
function CSpinBut(a,e,c,b,f,h){var k=!1,n=!1,u,r,q,t,l,d,p,m;this._init=function(a,b,c,e,f){t=[];l=[];d=new createjs.Container;d.x=a;d.y=b;d.regX=Math.floor(e/2);d.regY=Math.floor(f/2);d.cursor="pointer";m.addChild(d);a=new createjs.SpriteSheet({framerate:1,images:[c],frames:{width:e,height:f},animations:{spin:[0],stop:[1],autospin:[2],skip:[3],freespin:[4],disable:[5]}});p=createSprite(a,"spin",0,0,e,f);p.stop();d.addChild(p);u=f;q=SPIN_BUT_STATE_SPIN;this._initListener()};this.enable=function(){k=
!1;p.gotoAndStop(q)};this.disable=function(){k=!0};this.setState=function(a){p.gotoAndStop(a);a!==SPIN_BUT_STATE_STOP&&(q=a)};this.toggleAutoSpinImage=function(){p.currentAnimation===SPIN_BUT_STATE_SPIN?p.gotoAndStop(SPIN_BUT_STATE_AUTOSPIN):p.gotoAndStop(SPIN_BUT_STATE_SPIN)};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease)};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);m.removeChild(d)};this.setVisible=
function(a){d.visible=a};this.addEventListener=function(a,b,c){t[a]=b;l[a]=c};this.buttonRelease=function(){!1===n||k||(n=!1,t[ON_MOUSE_UP]&&t[ON_MOUSE_UP].call(l[ON_MOUSE_UP],p.currentAnimation))};this.buttonDown=function(){k||(r=0,n=!0,t[ON_MOUSE_DOWN]&&t[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN]))};this.setPosition=function(a,b){d.x=a;d.y=b};this.setX=function(a){d.x=a};this.setY=function(a){d.y=a};this.getButtonImage=function(){return d};this.getX=function(){return d.x};this.getY=function(){return d.y};
this.getHeight=function(){return u};this.getSprite=function(){return d};this.getState=function(){return p.currentAnimation};this.update=function(){!1!==n&&(r+=s_iTimeElaps,r>TIME_HOLD_AUTOSPIN&&(r=0,n=!1,t[ON_MOUSE_UP]&&t[ON_MOUSE_UP].call(l[ON_MOUSE_UP],p.currentAnimation,!0)))};m=h;this._init(a,e,c,b,f);return this}
function CBonusGoalkeeper(a){var e=!1,c,b,f,h,k,n,u,r,q,t,l;this._init=function(){u=new createjs.Container;l.addChild(u);r=new createjs.Container;r.x=650;r.y=160;u.addChild(r);q=new createjs.Container;q.visible=!1;q.x=292;q.y=132;u.addChild(q);t=new createjs.Container;t.visible=!1;t.x=662;t.y=132;u.addChild(t);n=[[],[],[]];for(var a=0;23>a;a++){var b=createBitmap(s_oSpriteLibrary.getSprite("gk_idle_"+a));r.addChild(b);n[0].push(b);0<a&&(b.visible=!1)}for(a=0;33>a;a++){b=createBitmap(s_oSpriteLibrary.getSprite("gk_save_left_"+
a));q.addChild(b);n[1].push(b);var c=createBitmap(s_oSpriteLibrary.getSprite("gk_save_right_"+a));t.addChild(c);n[2].push(c);0<a&&(b.visible=!1,c.visible=!1)}};this.show=function(){h=c=0;k=2;b=23;r.visible=!0;q.visible=!1;t.visible=!1;u.visible=!0;n[c][0].visible=!0;f=0;e=!0};this.dive=function(a){h=0;k=1;b=33;c=a;switch(c){case 1:r.visible=!1;q.visible=!0;t.visible=!1;break;case 2:r.visible=!1,q.visible=!1,t.visible=!0}n[c][0].visible=!0;f=0;this.resetIdleAnim();e=!0};this.resetIdleAnim=function(){for(var a=
0;a<n[0].length;a++)n[0][a].visible=!1};this._showWinAnim=function(){u.visible=!1;r.visible=!0;q.visible=!1;e=t.visible=!1};this.playToFrame=function(a){n[c][f].visible=!1;f=a;n[c][f].visible=!0};this.nextFrame=function(){n[c][f].visible=!1;f++;n[c][f].visible=!0};this.update=function(){!1!==e&&(h++,h===k&&(h=0,f===b-1?0===c?this.playToFrame(1):(n[c][f].visible=!1,this._showWinAnim()):this.nextFrame()))};l=a;this._init()}
function CBonusPlayer(a,e,c){var b=!1,f,h,k,n,u;this._init=function(a,b){n=new createjs.Container;n.visible=!1;n.x=a;n.y=b;u.addChild(n);k=[];for(var c=0;30>c;c++){var e=createBitmap(s_oSpriteLibrary.getSprite("player_"+c));n.addChild(e);k.push(e);0<c&&(e.visible=!1)}};this.show=function(){f=30;k[0].visible=!0;h=0;b=n.visible=!0};this.hide=function(){n.visible=!1};this.playToFrame=function(a){k[h].visible=!1;h=a;k[h].visible=!0};this.nextFrame=function(){k[h].visible=!1;h++;k[h].visible=!0};this.update=
function(){!1!==b&&(h===f-1?(b=!1,this.hide()):(this.nextFrame(),9===h&&s_oBonusPanel.kick()))};u=c;this._init(a,e)}
function CBonusBall(a,e,c){var b=!1,f,h,k,n,u,r,q,t,l,d,p;this._init=function(a,b){f=a;h=b;n=1;u=FPS/2;var c=s_oSpriteLibrary.getSprite("ball_anim"),e=new createjs.SpriteSheet({images:[c],frames:{width:211,height:205,regX:105,regY:102},animations:{"static":[0],moving:[1,29,"moving"]}});d=createSprite(e,"static",0,0,c.width/2,c.height);d.visible=!1;d.x=f;d.y=h;d.stop();p.addChild(d);l=new CTweenController};this.show=function(a,c){r=a;q=c;d.x=f;d.y=h;this._calculateMid(new createjs.Point(d.x,d.y),new createjs.Point(r,
q));d.scaleX=d.scaleY=1;d.alpha=1;d.visible=!0;d.gotoAndPlay("moving");k=0;b=!0};this.hide=function(){d.visible=!1};this._resetBall=function(){playSound("avatar_win",1,0);k=0;d.gotoAndStop("static");b=!1;createjs.Tween.get(d).to({y:CANVAS_HEIGHT/2},1500,createjs.Ease.cubicIn);createjs.Tween.get(d).to({alpha:0},1E3,createjs.Ease.cubicIn).call(function(){s_oBonusPanel.ballArrived()})};this._calculateMid=function(a,b){var c;c=b.x<CANVAS_WIDTH/2?new createjs.Point(b.x-100,b.y+40):new createjs.Point(b.x+
100,b.y+40);t={start:a,end:b,traj:c}};this.getX=function(){return d.x};this.getY=function(){return d.y};this.update=function(){if(b)if(k+=n,k>u)this._resetBall();else{var a;a=l.easeOutCubic(k,0,1,u);a=l.getTrajectoryPoint(a,t);d.x=a.x;d.y=a.y;.2<=d.scaleX&&(d.scaleX-=.06,d.scaleY-=.06)}};p=c;this._init(a,e)}
function CScoreText(a,e,c){var b;this._init=function(a,c,e){b=new createjs.Text("00000"," 60px "+FONT_GAME_1,"#ffd202");b.textAlign="center";b.text="+"+a+TEXT_CURRENCY;b.x=c;b.y=e;b.alpha=0;b.shadow=new createjs.Shadow("#000",1,1,1);s_oStage.addChild(b);var n=this;createjs.Tween.get(b).to({alpha:1},200,createjs.Ease.quadIn).call(function(){n.moveUp()})};this.moveUp=function(){var a=b.y-100,c=this;createjs.Tween.get(b).to({y:a},1500,createjs.Ease.sineIn).call(function(){c.unload()});createjs.Tween.get(b).wait(800).to({alpha:0},
500)};this.unload=function(){s_oStage.removeChild(b)};this._init(a,e,c)}
function CBonusResultPanel(a,e){var c,b,f;this._init=function(a){c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;f.addChild(c);b=new createjs.Container;b.x=-CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2;f.addChild(b);var e=s_oSpriteLibrary.getSprite("bonus_panel_bg"),n=createBitmap(e);n.regX=e.width/2;n.regY=e.height/2;b.addChild(n);e=new createjs.Text(TEXT_CONGRATS,"52px "+FONT_GAME_1,"#fff");e.textAlign="center";e.y=-110;e.shadow=new createjs.Shadow("#000",
1,1,1);b.addChild(e);a=new createjs.Text(TEXT_YOU_WIN+"\n"+a+TEXT_CURRENCY,"50px "+FONT_GAME_1,"#fff");a.y=10;a.textAlign="center";a.lineHeight=50;a.shadow=new createjs.Shadow("#000",1,1,1);b.addChild(a);createjs.Tween.get(b).to({x:CANVAS_WIDTH/2},1E3,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(c).to({alpha:.6},400)}).call(function(){setTimeout(function(){s_oBonusPanel.unload()},2E3)});playSound("bonus_win",1,0)};this.unload=function(){f.removeChild(c);f.removeChild(b)};f=e;this._init(a)}
function CFreespinPanel(a){var e,c,b,f;this._init=function(){b=new createjs.Container;b.visible=!1;f.addChild(b);var a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));b.addChild(a);e=new createjs.Text(TEXT_CONGRATS,"50px "+FONT_GAME_1,"#fff");e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=400;e.x=CANVAS_WIDTH/2;e.y=300;b.addChild(e);c=new createjs.Text("","55px "+FONT_GAME_1,"#fff");c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=400;c.lineHeight=66;c.x=CANVAS_WIDTH/
2;c.y=420;b.addChild(c)};this.show=function(a){c.text=TEXT_YOU_WIN+" "+a+" "+TEXT_FREESPINS;b.on("click",function(){});b.alpha=0;b.visible=!0;var e=this;createjs.Tween.get(b).to({alpha:1},800,createjs.Ease.cubicOut).call(function(){setTimeout(function(){e.hide()},3E3)});playSound("bonus_win",1,0)};this.hide=function(){b.off("click",function(){});createjs.Tween.get(b).to({alpha:0},800,createjs.Ease.cubicOut).call(function(){b.visible=!1});s_oGame.exitFromFreespinPanel()};f=a;this._init()}
function CAvatar(a){var e,c=!1,b=!1,f,h=2,k=0,n,u=0,r,q,t,l,d;this._init=function(){e=50;l=new createjs.Container;l.x=130;l.y=252;d.addChild(l);q=new createjs.Container;l.addChild(q);t=new createjs.Container;t.visible=!1;l.addChild(t);r=[[],[]];for(var a=0;30>a;a++){var b=createBitmap(s_oSpriteLibrary.getSprite("avatar_idle_"+a));q.addChild(b);r[0][a]=b;b.visible=!1}for(a=0;38>a;a++)b=createBitmap(s_oSpriteLibrary.getSprite("avatar_win_"+a)),t.addChild(b),r[1][a]=b,b.visible=!1;this.refreshButtonPos(s_iOffsetX)};
this._hideAllAnims=function(){for(var a=0;a<r[0].length;a++)r[0][a].visible=!1,r[1][a].visible=!1,r[2][a].visible=!1};this.refreshButtonPos=function(a,b){130>e+a&&(l.x=e+a)};this.show=function(a){r[u][k].visible=!1;u=a;switch(a){case 0:q.visible=!0;t.visible=!1;break;case 1:q.visible=!1,t.visible=!0}n=r[u].length;h=2;r[u][0].visible=!0;b=k=f=0;c=!0};this.playToFrame=function(a){r[u][k].visible=!1;k=a;r[u][k].visible=!0};this.nextFrame=function(){r[u][k].visible=!1;k++;r[u][k].visible=!0};this.update=
function(){!1!==c&&(f++,f===h&&(f=0,k===n-1?(this.playToFrame(1),b++,2===b&&1===u&&this.show(0)):this.nextFrame()))};d=a;this._init()}
function CCreditsPanel(){var a,e,c;this._init=function(){a=new createjs.Container;a.on("mousedown",function(){});s_oStage.addChild(a);var b=s_oSpriteLibrary.getSprite("msg_box"),b=createBitmap(b);a.addChild(b);b=new createjs.Text(TEXT_DEVELOPED," 34px "+FONT_GAME_1,"#000000");b.x=CANVAS_WIDTH/2;b.y=336;b.textAlign="center";b.textBaseline="middle";b.lineWidth=300;b.outline=5;a.addChild(b);var f=new createjs.Text(TEXT_DEVELOPED," 34px "+FONT_GAME_1,"#ffffff");f.x=CANVAS_WIDTH/2;f.y=b.y;f.textAlign=
"center";f.textBaseline="middle";f.lineWidth=300;a.addChild(f);b=new createjs.Text("www.codethislab.com"," 34px "+FONT_GAME_1,"#000000");b.x=CANVAS_WIDTH/2;b.y=460;b.textAlign="center";b.textBaseline="middle";b.lineWidth=300;b.outline=5;a.addChild(b);f=new createjs.Text("www.codethislab.com"," 34px "+FONT_GAME_1,"#ffffff");f.x=CANVAS_WIDTH/2;f.y=b.y;f.textAlign="center";f.textBaseline="middle";f.lineWidth=300;a.addChild(f);b=s_oSpriteLibrary.getSprite("ctl_logo");c=createBitmap(b);c.on("mousedown",
this._onLogoButRelease);c.regX=b.width/2;c.regY=b.height/2;c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;a.addChild(c);b=s_oSpriteLibrary.getSprite("but_exit_info");e=new CGfxButton(970,264,b,a);e.addEventListener(ON_MOUSE_UP,this.unload,this);a.alpha=0;createjs.Tween.get(a).to({alpha:1},1E3,createjs.Ease.cubicOut)};this.unload=function(){e.unload();a.off("mousedown",function(){});c.off("mousedown",this._onLogoButRelease);s_oStage.removeChild(a)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};
this._init()};
