(function(c){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(c)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(c.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);function trace(c){console.log(c)}$(window).resize(function(){sizeHandler()});function isIOS(){for(var c="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");c.length;)if(navigator.platform===c.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function playSound(c,a,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(c,{loop:b,volume:a}):null}
function stopSound(c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||c.stop()}function setVolume(c,a){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c.volume=a}function setMute(c,a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||c.setMute(a)}
function getSize(c){var a=c.toLowerCase(),b=window.document,d=b.documentElement;if(void 0===window["inner"+c])c=d["client"+c];else if(window["inner"+c]!=d["client"+c]){var g=b.createElement("body");g.id="vpw-test-b";g.style.cssText="overflow:scroll";var k=b.createElement("div");k.id="vpw-test-d";k.style.cssText="position:absolute;top:-1000px";k.innerHTML="<style>@media("+a+":"+d["client"+c]+"px){body#vpw-test-b div#vpw-test-d{"+a+":7px!important}}</style>";g.appendChild(k);d.insertBefore(g,b.head);
c=7==k["offset"+c]?d["client"+c]:window["inner"+c];d.removeChild(g)}else c=window["inner"+c];return c}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var c=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<c?c:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var c;c=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var a=getSize("Width"),b=Math.min(c/CANVAS_HEIGHT,a/CANVAS_WIDTH),d=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,g=0;b<c?(g=c-b,b+=g,d+=CANVAS_WIDTH/CANVAS_HEIGHT*g):d<a&&(g=a-d,d+=g,b+=CANVAS_HEIGHT/CANVAS_WIDTH*g);var g=c/2-b/2,k=a/2-d/2,e=CANVAS_WIDTH/d;if(k*e<-EDGEBOARD_X||g*e<-EDGEBOARD_Y)b=Math.min(c/(CANVAS_HEIGHT-2*EDGEBOARD_Y),a/(CANVAS_WIDTH-2*
EDGEBOARD_X)),d=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,g=(c-b)/2,k=(a-d)/2,e=CANVAS_WIDTH/d;s_iOffsetX=-1*k*e;s_iOffsetY=-1*g*e;0<=g&&(s_iOffsetY=0);0<=k&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oHealthBar&&s_oHealthBar.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMobileControls&&s_oMobileControls.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos(s_iOffsetX,
s_iOffsetY);null!==s_oSelectTeam&&s_oSelectTeam.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oPlayerProgress&&s_oPlayerProgress.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile&&!s_bIsIphone?($("#canvas").css("width",d+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=d,s_oStage.canvas.height=b,s_oStage.scaleX=s_oStage.scaleY=Math.min(d/CANVAS_WIDTH,b/CANVAS_HEIGHT));0>g?$("#canvas").css("top",g+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",k+"px")}}
function createBitmap(c,a,b){var d=new createjs.Bitmap(c),g=new createjs.Shape;a&&b?g.graphics.beginFill("#fff").drawRect(0,0,a,b):g.graphics.beginFill("#ff0").drawRect(0,0,c.width,c.height);d.hitArea=g;return d}function createSprite(c,a,b,d,g,k){c=null!==a?new createjs.Sprite(c,a):new createjs.Sprite(c);a=new createjs.Shape;a.graphics.beginFill("#000000").drawRect(-b,-d,g,k);c.hitArea=a;return c}
function randomFloatBetween(c,a,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(c+Math.random()*(a-c),a).toFixed(b))}function rotateVector2D(c,a){var b=a.getX()*Math.cos(c)+a.getY()*Math.sin(c),d=a.getX()*-Math.sin(c)+a.getY()*Math.cos(c);a.set(b,d)}function tweenVectorsOnX(c,a,b){return c+b*(a-c)}function shuffle(c){for(var a=c.length,b,d;0!==a;)d=Math.floor(Math.random()*a),--a,b=c[a],c[a]=c[d],c[d]=b;return c}
function bubbleSort(c){var a;do{a=!1;for(var b=0;b<c.length-1;b++)c[b]>c[b+1]&&(a=c[b],c[b]=c[b+1],c[b+1]=a,a=!0)}while(a)}function compare(c,a){return c.index>a.index?-1:c.index<a.index?1:0}function easeLinear(c,a,b,d){return b*c/d+a}function easeInQuad(c,a,b,d){return b*(c/=d)*c+a}function easeInSine(c,a,b,d){return-b*Math.cos(c/d*(Math.PI/2))+b+a}function easeInCubic(c,a,b,d){return b*(c/=d)*c*c+a}function easeOutCubic(c,a,b,d,g){return b*((c=c/d-1)*c*c+1)+a}
function getTrajectoryPoint(c,a){var b=new createjs.Point,d=(1-c)*(1-c),g=c*c;b.x=d*a.start.x+2*(1-c)*c*a.traj.x+g*a.end.x;b.y=d*a.start.y+2*(1-c)*c*a.traj.y+g*a.end.y;return b}function formatTime(c){c/=1E3;var a=Math.floor(c/60),b=Math.floor(c-60*a),d=Math.floor(1E3*c%1E3);c=":"+d;10>d?c=":00"+d:100>d&&(c=":0"+d);d="";d=10>a?d+("0"+a+":"):d+(a+":");return d=(10>b?d+("0"+b):d+b)+c}function degreesToRadians(c){return c*Math.PI/180}
function checkRectCollision(c,a){var b,d;b=getBounds(c,.9);d=getBounds(a,.98);return calculateIntersection(b,d)}function calculateIntersection(c,a){var b,d,g,k,e,l,f,h;b=c.x+(g=c.width/2);d=c.y+(k=c.height/2);e=a.x+(l=a.width/2);f=a.y+(h=a.height/2);b=Math.abs(b-e)-(g+l);d=Math.abs(d-f)-(k+h);return 0>b&&0>d?(b=Math.min(Math.min(c.width,a.width),-b),d=Math.min(Math.min(c.height,a.height),-d),{x:Math.max(c.x,a.x),y:Math.max(c.y,a.y),width:b,height:d,rect1:c,rect2:a}):null}
function getBounds(c,a){var b={x:Infinity,y:Infinity,width:0,height:0};if(c instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var d=c.children,g=d.length,k,e;for(e=0;e<g;e++)k=getBounds(d[e],1),k.x<b.x&&(b.x=k.x),k.y<b.y&&(b.y=k.y),k.x+k.width>b.x2&&(b.x2=k.x+k.width),k.y+k.height>b.y2&&(b.y2=k.y+k.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var l,f;c instanceof createjs.Bitmap?
(g=c.sourceRect||c.image,e=g.width*a,l=g.height*a):c instanceof createjs.Sprite?c.spriteSheet._frames&&c.spriteSheet._frames[c.currentFrame]&&c.spriteSheet._frames[c.currentFrame].image?(g=c.spriteSheet.getFrame(c.currentFrame),e=g.rect.width,l=g.rect.height,d=g.regX,f=g.regY):(b.x=c.x||0,b.y=c.y||0):(b.x=c.x||0,b.y=c.y||0);d=d||0;e=e||0;f=f||0;l=l||0;b.regX=d;b.regY=f;g=c.localToGlobal(0-d,0-f);k=c.localToGlobal(e-d,l-f);e=c.localToGlobal(e-d,0-f);d=c.localToGlobal(0-d,l-f);b.x=Math.min(Math.min(Math.min(g.x,
k.x),e.x),d.x);b.y=Math.min(Math.min(Math.min(g.y,k.y),e.y),d.y);b.width=Math.max(Math.max(Math.max(g.x,k.x),e.x),d.x)-b.x;b.height=Math.max(Math.max(Math.max(g.y,k.y),e.y),d.y)-b.y}return b}function NoClickDelay(c){this.element=c;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(c){for(var a=c.length,b,d;0<a;)d=Math.floor(Math.random()*a),a--,b=c[a],c[a]=c[d],c[d]=b;return c}
NoClickDelay.prototype={handleEvent:function(c){switch(c.type){case "touchstart":this.onTouchStart(c);break;case "touchmove":this.onTouchMove(c);break;case "touchend":this.onTouchEnd(c)}},onTouchStart:function(c){c.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(c){this.moved=!0},onTouchEnd:function(c){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){c=document.elementFromPoint(c.changedTouches[0].clientX,c.changedTouches[0].clientY);3==c.nodeType&&(c=c.parentNode);var a=document.createEvent("MouseEvents");a.initEvent("click",!0,!0);c.dispatchEvent(a)}}};
(function(){function c(c){var d={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};c=c||window.event;c.type in d?document.body.className=d[c.type]:(document.body.className=this[a]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var a="hidden";a in document?document.addEventListener("visibilitychange",c):(a="mozHidden")in document?document.addEventListener("mozvisibilitychange",c):(a="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",c):(a="msHidden")in document?document.addEventListener("msvisibilitychange",c):"onfocusin"in document?document.onfocusin=document.onfocusout=c:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=c})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(c){for(var a=window.location.search.substring(1).split("&"),b=0;b<a.length;b++){var d=a[b].split("=");if(d[0]==c)return d[1]}}
function CSpriteLibrary(){var c,a,b,d,g,k;this.init=function(e,l,f){b=a=0;d=e;g=l;k=f;c={}};this.addSprite=function(b,d){c.hasOwnProperty(b)||(c[b]={szPath:d,oSprite:new Image},a++)};this.getSprite=function(a){return c.hasOwnProperty(a)?c[a].oSprite:null};this._onSpritesLoaded=function(){g.call(k)};this._onSpriteLoaded=function(){d.call(k);++b==a&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in c)c[a].oSprite.oSpriteLibrary=this,c[a].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
c[a].oSprite.src=c[a].szPath};this.getNumSprites=function(){return a}}
function CVector2(c,a){var b,d;this._init=function(a,c){b=a;d=c};this.add=function(a,c){b+=a;d+=c};this.addV=function(a){b+=a.getX();d+=a.getY()};this.scalarDivision=function(a){b/=a;d/=a};this.subV=function(a){b-=a.getX();d-=a.getY()};this.scalarProduct=function(a){b*=a;d*=a};this.invert=function(){b*=-1;d*=-1};this.dotProduct=function(a){return b*a.getX()+d*a.getY()};this.set=function(a,c){b=a;d=c};this.setV=function(a){b=a.getX();d=a.getY()};this.length=function(){return Math.sqrt(b*b+d*d)};this.length2=
function(){return b*b+d*d};this.normalize=function(){var a=this.length();0<a&&(b/=a,d/=a)};this.getNormalize=function(a){this.length();a.set(b,d);a.normalize()};this.rot90CCW=function(){var a=b;b=-d;d=a};this.rot90CW=function(){var a=b;b=d;d=-a};this.getRotCCW=function(a){a.set(b,d);a.rot90CCW()};this.getRotCW=function(a){a.set(b,d);a.rot90CW()};this.ceil=function(){b=Math.ceil(b);d=Math.ceil(d)};this.round=function(){b=Math.round(b);d=Math.round(d)};this.toString=function(){return"Vector2: "+b+", "+
d};this.print=function(){trace("Vector2: "+b+", "+d+"")};this.getX=function(){return b};this.getY=function(){return d};this._init(c,a)}
var CANVAS_WIDTH=1360,CANVAS_HEIGHT=640,EDGEBOARD_X=275,EDGEBOARD_Y=50,FONT="arialbold",FONT_2="pixel_lcd7regular",FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,PLAYER_X_POSITION_IN_SELECTION=CANVAS_WIDTH/2,PLAYER_Y_POSITION_IN_SELECTION=CANVAS_HEIGHT/2+29,NUM_RUNNERS=8,PLAYER_WIDTH=165,PLAYER_HEIGHT=103,NUM_ROUNDS,NUM_POWER_UP_AVAILABLE=4,PLAYER_MAX_SPEED,PLAYER_MIN_SPEED,PLAYER_ENERGY,PLAYER_RESISTENCE_STEP,PLAYER_MAX_SPEED_ADDER,PLAYER_ENERGY_ADDER,ANIMATION_POSITION="position",ANIMATION_STARTING=
"starting",ANIMATION_RUNNING="run",ANIMATION_ENDING="ending",SPEED_DECELERATION=.3,MODIFIER_SPEED_ADDER=3,ENERGY_INCREASE=.15,ENEMY_MAX_SPEED=[19,20,20,,20,20,20,19],ENEMY_MIN_SPEED=[3,3,4,,4,4,3,3],ENEMY_ENERGY=[80,70,80,,100,90,80,80],ENEMY_RESISTENCE_STEP=[.5,.4,.4,,.3,.35,.4,.5],ENEMY_OCCURRENCE_RUN=[.7,.75,.75,,.75,.75,.75,.7],PLAYER_NAME_AND_SPRITE,WAIT_FOR_GAME_START=0,CONFIRMATION_ON_EXIT=1,CONFIRMATION_ON_CAREER_RESET=2,DIST_FROM_ARRIVAL,TEAM_0=0,TEAM_1=1,TEAM_2=2,TEAM_3=3,TEAM_4=4,TEAM_5=
5,TEAM_6=6,TEAM_7=7,LEFT_DIR=37,RIGHT_DIR=39,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,TEXT_SCORE="SCORE: ",TEXT_POSITION="\u00b0 PLACE",TEXT_SCORE="SCORE:       ",TEXT_CREDITS_DEVELOPED="DEVELOPED BY",TEXT_LINK1="WWW.CODETHISLAB.COM",TEXT_START_MOVEMENT="MASH THE LEFT AND RIGHT KEYS TO BOOST YOUR POWER",TEXT_START_MOVEMENT_MOBILE="MASH THE LEFT AND RIGHT BUTTONS TO BOOST YOUR POWER",HELP_ENERGY=
"KEEP YOUR ENERGY BAR FULL TO GO FASTER!",TEXT_ON_EXIT="DO YOU REALLY WANT TO QUIT THE GAME?",TEXT_ON_CAREER_RESET="ARE YOU SURE? ALL YOUR PREVIOUS SCORES WILL BE DELETED!",TEXT_CURRENCY="$",TEXT_LANE="LANE",TEXT_TIME="Time",TEXT_DISCIPLINE="MEN'S 100 METRES",TEXT_RESULT="RESULT",TEXT_UPGRADE="Upgrades - Medals",TEXT_BUY="BUY",TEXT_MONEY="MONEY",TEXT_TEAM_0="GERMANY",TEXT_TEAM_1="U.K.",TEXT_TEAM_2="TRINIDAD AND TOBAGO",TEXT_TEAM_3="RUSSIA",TEXT_TEAM_4="JAMAICA",TEXT_TEAM_5="U.S.A.",TEXT_TEAM_6="FRANCE",
TEXT_TEAM_7="NETHERLANDS",CITY_NAME="SEATTLE;SAN FRANCISCO;MIAMI;NEW ORLEANS;CHICAGO;WASHINGTON;NEW YORK;LOS ANGELES;CLEVELAND;RIO".split(";"),TEXT_RUNNER="SELECT RUNNER",TEXT_MODE="SELECT MODE",TEXT_CHALLENGE="SELECT TRACK",TEXT_SHARE_IMAGE="200x200.jpg",TEXT_SHARE_TITLE="Congratulations!",TEXT_SHARE_MSG1="You collected <strong>",TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!",TEXT_SHARE_SHARE1="My score is ",TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var c,a,b,d,g,k,e;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();e=new createjs.Container;s_oStage.addChild(e)};this.unload=function(){e.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(k).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));e.addChild(l);l=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(l);d.x=CANVAS_WIDTH/2-l.width/2;d.y=CANVAS_HEIGHT-145;e.addChild(d);c=l.width;a=l.height;g=new createjs.Shape;g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,a);e.addChild(g);d.mask=
g;b=new createjs.Text("","30px Arial","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-150;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";e.addChild(b);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=0;e.addChild(k)};this.refreshLoader=function(e){b.text=e+"%";g.graphics.clear();e=Math.floor(e*c/100);g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,e,a)};this._init()}
function CMain(c){var a,b=0,d=0,g=STATE_LOADING,k,e,l;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile?(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1})):s_iScale=2;s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;e=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();a=!0};this.soundLoaded=function(){b++;e.refreshLoader(Math.floor(b/d*100));b===d&&(e.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.ogg","press_button"),createjs.Sound.registerSound("./sounds/crowd-cheers.ogg","crowd_cheers"),createjs.Sound.registerSound("./sounds/crowd.ogg","crowd"),createjs.Sound.registerSound("./sounds/start_race.ogg","start_race"),createjs.Sound.registerSound("./sounds/prepare_runner.ogg","prepare_runner"),createjs.Sound.registerSound("./sounds/crowd_arrival.ogg",
"crowd_arrival"),createjs.Sound.registerSound("./sounds/upgrade.ogg","upgrade")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.mp3","press_button"),createjs.Sound.registerSound("./sounds/crowd_cheers.mp3","crowd_cheers"),createjs.Sound.registerSound("./sounds/crowd.mp3","crowd"),createjs.Sound.registerSound("./sounds/start_race.mp3",
"start_race"),createjs.Sound.registerSound("./sounds/prepare_runner.mp3","prepare_runner"),createjs.Sound.registerSound("./sounds/crowd_arrival.mp3","crowd_arrival"),createjs.Sound.registerSound("./sounds/upgrade.mp3","upgrade")),d+=7)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_continue",
"./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_continue_small","./sprites/but_continue_small.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("left_button","./sprites/left_button.png");s_oSpriteLibrary.addSprite("right_button","./sprites/right_button.png");s_oSpriteLibrary.addSprite("but_skip","./sprites/but_skip.png");
s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_select_team","./sprites/bg_select_team.jpg");s_oSpriteLibrary.addSprite("bg_podium","./sprites/bg_podium.jpg");s_oSpriteLibrary.addSprite("bg_select_challenge","./sprites/bg_select_challenge.jpg");s_oSpriteLibrary.addSprite("result_panel","./sprites/result_panel.png");s_oSpriteLibrary.addSprite("upgrade_panel","./sprites/upgrade_panel.png");s_oSpriteLibrary.addSprite("select_challenge","./sprites/select_challenge.png");
s_oSpriteLibrary.addSprite("are_you_sure_panel","./sprites/are_you_sure_panel.png");s_oSpriteLibrary.addSprite("final_score","./sprites/final_score.png");s_oSpriteLibrary.addSprite("help_panel","./sprites/help_panel.png");s_oSpriteLibrary.addSprite("logo_credits","./sprites/logo_credits.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("level_sprite","./sprites/level_sprite.png");s_oSpriteLibrary.addSprite("energy_bar","./sprites/energy_bar.png");
s_oSpriteLibrary.addSprite("health","./sprites/health.png");s_oSpriteLibrary.addSprite("horizontal_bar","./sprites/horizontal_bar.png");s_oSpriteLibrary.addSprite("arrival_panel","./sprites/arrival_panel.png");s_oSpriteLibrary.addSprite("select_character","./sprites/select_character.png");s_oSpriteLibrary.addSprite("bar-1","./sprites/bar-1.png");s_oSpriteLibrary.addSprite("bar-2","./sprites/bar-2.png");s_oSpriteLibrary.addSprite("gold_medal","./sprites/gold_medal.png");s_oSpriteLibrary.addSprite("silver_medal",
"./sprites/silver_medal.png");s_oSpriteLibrary.addSprite("bronze_medal","./sprites/bronze_medal.png");s_oSpriteLibrary.addSprite("arrow_bar","./sprites/arrow_bar.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("bg_credits","./sprites/bg_credits.png");s_oSpriteLibrary.addSprite("left_directional_arrows","./sprites/left_directional_arrows.png");s_oSpriteLibrary.addSprite("right_directional_arrows","./sprites/right_directional_arrows.png");s_oSpriteLibrary.addSprite("time_panel",
"./sprites/time_panel.png");s_oSpriteLibrary.addSprite("podium","./sprites/podium.png");for(var a=0;a<NUM_RUNNERS;a++)s_oSpriteLibrary.addSprite("flag_runner_"+a,"./sprites/flag_runner_"+a+".png"),s_oSpriteLibrary.addSprite("flag_runner_"+a+"_game","./sprites/flag_runner_"+a+"_game.png"),s_oSpriteLibrary.addSprite("flag_"+a,"./sprites/flag_"+a+".jpg"),s_oSpriteLibrary.addSprite("runner_"+a,"./sprites/runners/runner_"+a+".png"),s_oSpriteLibrary.addSprite("runner_"+a+"_pose","./sprites/runners/poses/runner_"+
a+"_pose.png");if(s_bMobile)for(a=0;18>a;a++)s_oSpriteLibrary.addSprite("track_"+a,"./sprites/track/redux/track_"+a+".jpg");else for(a=0;18>a;a++)s_oSpriteLibrary.addSprite("track_"+a,"./sprites/track/track_"+a+".jpg");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;e.refreshLoader(Math.floor(b/d*100));b===d&&(e.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=
function(){new CMenu;g=STATE_MENU};this.gotoTeamSelect=function(){new CSelectTeam;g=STATE_MENU};this.gotoSelectLevel=function(){new CLevelMenu;g=STATE_MENU};this.gotoGame=function(a){l=new CGame(k,a);g=STATE_GAME};this.gotoPlayerProgress=function(){new CPlayerProgress;g=STATE_MENU};this.gotoHelp=function(){new CHelp;g=STATE_HELP};this.stopUpdate=function(){a=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();a=!0;createjs.Ticker.paused=
!1;$("#block_game").css("display","none")};this._update=function(c){if(!1!==a){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);g===STATE_GAME&&l.update();s_oStage.update(c)}};s_oMain=this;k=c;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_bIsIphone=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iLevelReached=1,s_iPlayerMoney=0,s_iSpeedBought=0,s_iEnergyBought=0,s_iSpeedAdder=0,s_iEnergyAdder=0,s_iTeamSelected=0,s_szTeamSelectedSprite="runner_0",s_aRunnersScore=[0,0,0,0,0,0,0,0],s_iScale=1,s_oCityInfos=null,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack=null,s_oCanvas;
function CTextButton(c,a,b,d,g,k,e){var l,f,h,m,q;this._init=function(a,c,b,d,g,e,k){l=[];f=[];var w=createBitmap(b),x=Math.ceil(k/20);q=new createjs.Text(d," "+k+"px "+g,"#000000");q.textAlign="center";q.textBaseline="alphabetic";var B=q.getBounds();q.x=b.width/2+x;q.y=Math.floor(b.height/2)+B.height/3+x;m=new createjs.Text(d," "+k+"px "+g,e);m.textAlign="center";m.textBaseline="alphabetic";B=m.getBounds();m.x=b.width/2;m.y=Math.floor(b.height/2)+B.height/3;h=new createjs.Container;h.x=a;h.y=c;h.regX=
b.width/2;h.regY=b.height/2;h.addChild(w,q,m);s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown");h.off("pressup");s_oStage.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){oParent=this;h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){l[a]=c;f[a]=b};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(f[ON_MOUSE_UP])};this.buttonDown=
function(){h.scaleX=.9;h.scaleY=.9;l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN])};this.setTextPosition=function(a){m.y=a;q.y=a+2};this.setPosition=function(a,c){h.x=a;h.y=c};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(c,a,b,d,g,k,e);return this}
function CToggle(c,a,b,d){var g,k,e,l=[],f;this._init=function(a,c,b,d){k=[];e=[];var l=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}});g=d;f=createSprite(l,"state_"+g,b.width/2/2,b.height/2,b.width/2,b.height);f.x=a;f.y=c;f.cursor="pointer";f.stop();s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);s_oStage.removeChild(f)};
this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){k[a]=c;e[a]=b};this.addEventListenerWithParams=function(a,c,b,d){k[a]=c;e[a]=b;l=d};this.setActive=function(a){g=a;f.gotoAndStop("state_"+g)};this.buttonRelease=function(){f.scaleX=1;f.scaleY=1;playSound("press_button",1,0);g=!g;f.gotoAndStop("state_"+g);k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(e[ON_MOUSE_UP],l)};this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;k[ON_MOUSE_DOWN]&&
k[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],l)};this.setPosition=function(a,c){f.x=a;f.y=c};this.setVisible=function(a){f.visible=a};this.getY=function(){return f.y};this._init(c,a,b,d)}
function CGfxButton(c,a,b,d){var g,k,e,l=[],f,h;this._init=function(a,c,b){g=1;k=[];e=[];f=createBitmap(b);f.x=a;f.y=c;f.regX=b.width/2;f.regY=b.height/2;f.cursor="pointer";h.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);h.removeChild(f)};this.setVisible=function(a){f.visible=a};this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){k[a]=
c;e[a]=b};this.addEventListenerWithParams=function(a,c,b,d){k[a]=c;e[a]=b;l=d};this.buttonRelease=function(){f.scaleX=g;f.scaleY=g;playSound("press_button",1,0);k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(e[ON_MOUSE_UP],l)};this.buttonDown=function(){f.scaleX=.9*g;f.scaleY=.9*g;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],l)};this.setScale=function(a){g=a;f.scaleX=a;f.scaleY=a};this.setPosition=function(a,c){f.x=a;f.y=c};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=
function(){return f};this.getX=function(){return f.x};this.getY=function(){return f.y};h=d;this._init(c,a,b);return this}
function CMenu(){var c,a,b,d,g,k,e,l,f,h,m=null,q,n,r,p=null;this._init=function(){null===localStorage.getItem("LevelReached")||s_iLevelReached>=s_oCityInfos.getNumLevels()?this.removeLocalStorage():(s_iLevelReached=parseInt(localStorage.getItem("LevelReached")),s_iPlayerMoney=parseInt(localStorage.getItem("Money")),s_iSpeedBought=parseInt(localStorage.getItem("SpeedBought")),s_iEnergyBought=parseInt(localStorage.getItem("EnergyBought")),s_iSpeedAdder=parseInt(parseInt(localStorage.getItem("SpeedAdder"))),
s_iEnergyAdder=parseInt(localStorage.getItem("EnergyAdder")),s_iTeamSelected=parseInt(localStorage.getItem("TeamSelected")),s_szTeamSelectedSprite=localStorage.getItem("TeamSelectedSprite"),s_aRunnersScore=JSON.parse(localStorage.getItem("Scores")),s_oCityInfos.getCitiesStorage());f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(f);if(2>s_iLevelReached){var p=s_oSpriteLibrary.getSprite("but_play");g=CANVAS_WIDTH/2;k=CANVAS_HEIGHT-110;h=new CGfxButton(g,k,p,s_oStage);h.addEventListener(ON_MOUSE_UP,
this._onButPlayRelease,this)}else p=s_oSpriteLibrary.getSprite("but_play"),g=CANVAS_WIDTH/2-200,k=CANVAS_HEIGHT-110,h=new CGfxButton(g,k,p,s_oStage),h.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this),p=s_oSpriteLibrary.getSprite("but_continue"),b=CANVAS_WIDTH/2+200,d=CANVAS_HEIGHT-110,m=new CGfxButton(b,d,p,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this);p=s_oSpriteLibrary.getSprite("but_credits");c=CANVAS_WIDTH-p.height/2-10;a=p.height/2+10;q=new CGfxButton(c,a,
p,s_oStage);q.addEventListener(ON_MOUSE_UP,this._onCredits,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p=s_oSpriteLibrary.getSprite("audio_icon"),e=CANVAS_WIDTH-p.height/2-90,l=p.height/2+10,r=new CToggle(e,l,p,s_bAudioActive),r.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),null===s_oSoundtrack&&(s_oSoundtrack=playSound("soundtrack",1,-1));n=new createjs.Shape;n.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(n);createjs.Tween.get(n).to({alpha:0},
1E3).call(function(){n.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){h.unload();h=null;n.visible=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r.unload(),r=null;null!==p&&(p.unload(),p=null);s_oStage.removeChild(f);s_oMenu=f=null};this.removeLocalStorage=function(){s_iLevelReached=1;s_iTeamSelected=s_iEnergyAdder=s_iSpeedAdder=s_iEnergyBought=s_iSpeedBought=s_iPlayerMoney=0;s_szTeamSelectedSprite="runner_0";s_aRunnersScore=[0,0,0,0,0,0,0,0];s_oCityInfos.removeCitiesStorage();
localStorage.removeItem("LevelReached");localStorage.removeItem("Money");localStorage.removeItem("SpeedBought");localStorage.removeItem("EnergyBought");localStorage.removeItem("SpeedAdder");localStorage.removeItem("EnergyAdder");localStorage.removeItem("TeamSelected");localStorage.removeItem("TeamSelectedSprite");localStorage.removeItem("Scores")};this.refreshButtonPos=function(f,p){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.setPosition(e-f,p+l);h.setPosition(g,k-p);m&&m.setPosition(b,d-p);q.setPosition(c-
f,p+a)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCredits=function(){new CCreditsPanel};this._onButPlayRelease=function(){$(s_oMain).trigger("start_session");2>s_iLevelReached?(this.unload(),s_oMain.gotoTeamSelect()):null===p&&(p=new CVariousHelp(TEXT_ON_CAREER_RESET,CONFIRMATION_ON_CAREER_RESET))};this._onButContinueRelease=function(){$(s_oMain).trigger("start_session");this.unload();s_oMain.gotoSelectLevel()};this.unloadVariousHelp=
function(){p.unload();p=null};this.onContinue=function(){this.removeLocalStorage();this.unload();s_oMain.gotoTeamSelect()};s_oMenu=this;null!==s_oCityInfos&&(s_oCityInfos.unload(),s_oCityInfos=null);s_oCityInfos=new CCitySettings;this._init()}var s_oMenu=null;
function CSelectTeam(){var c,a,b,d,g,k,e=0,l,f,h,m,q,n,r,p,t,z,A,u,w,x,B,C;this._init=function(){s_iTeamSelected=0;s_szTeamSelectedSprite="runner_0";x=createBitmap(s_oSpriteLibrary.getSprite("bg_select_team"));s_oStage.addChild(x);var e=new createjs.Shape;e.graphics.beginFill("rgba(0,0,0,0.6)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(e);var e=s_oSpriteLibrary.getSprite("select_character"),f=createBitmap(e);f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2;f.regX=e.width/2;f.regY=e.height/
2;s_oStage.addChild(f);h=new createjs.Text(TEXT_RUNNER," 20px "+FONT,"#ffffff");h.x=CANVAS_WIDTH/2-180;h.y=128;h.textAlign="left";h.textBaseline="alphabetic";h.lineWidth=1E3;s_oStage.addChild(h);m=new createjs.Text(TEXT_TEAM_0," 20px "+FONT,"#ffffff");m.x=CANVAS_WIDTH/2-180;m.y=155;m.textAlign="left";m.textBaseline="alphabetic";m.lineWidth=1E3;s_oStage.addChild(m);e=s_oSpriteLibrary.getSprite("but_continue_small");c=CANVAS_WIDTH/2+340;a=CANVAS_HEIGHT-140;q=new CGfxButton(c,a,e,s_oStage);q.addEventListener(ON_MOUSE_UP,
this._onButNextRelease,this);e=s_oSpriteLibrary.getSprite("but_exit");g=CANVAS_WIDTH-e.height/2-10;k=e.height/2+10;B=new CGfxButton(g,k,e,s_oStage);B.addEventListener(ON_MOUSE_UP,this._onExit,this);b=CANVAS_WIDTH-e.width/2-90;d=e.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e=s_oSpriteLibrary.getSprite("audio_icon"),C=new CToggle(b,d,e,s_bAudioActive),C.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);l=new createjs.Container;s_oStage.addChild(l);this.showPlayerPose(PLAYER_X_POSITION_IN_SELECTION,
PLAYER_Y_POSITION_IN_SELECTION,s_szTeamSelectedSprite);e=s_oSpriteLibrary.getSprite("flag_runner_0");w=new CToggle(CANVAS_WIDTH/2-180,CANVAS_HEIGHT/2-100,e,!1);w.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_0);e=s_oSpriteLibrary.getSprite("flag_runner_1");u=new CToggle(CANVAS_WIDTH/2-180,CANVAS_HEIGHT/2-20,e,!0);u.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_1);e=s_oSpriteLibrary.getSprite("flag_runner_2");p=new CToggle(CANVAS_WIDTH/2-180,CANVAS_HEIGHT/
2+60,e,!0);p.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_2);e=s_oSpriteLibrary.getSprite("flag_runner_3");t=new CToggle(CANVAS_WIDTH/2-180,CANVAS_HEIGHT/2+145,e,!0);t.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_3);e=s_oSpriteLibrary.getSprite("flag_runner_4");n=new CToggle(CANVAS_WIDTH/2+180,CANVAS_HEIGHT/2-100,e,!0);n.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_4);e=s_oSpriteLibrary.getSprite("flag_runner_5");z=new CToggle(CANVAS_WIDTH/
2+180,CANVAS_HEIGHT/2-20,e,!0);z.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_5);e=s_oSpriteLibrary.getSprite("flag_runner_6");A=new CToggle(CANVAS_WIDTH/2+180,CANVAS_HEIGHT/2+60,e,!0);A.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_6);e=s_oSpriteLibrary.getSprite("flag_runner_7");r=new CToggle(CANVAS_WIDTH/2+180,CANVAS_HEIGHT/2+145,e,!0);r.addEventListenerWithParams(ON_MOUSE_UP,this._onModeToggle,this,TEAM_7);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};
this._onModeToggle=function(a){playSound("select_team",1,0);var c;switch(a){case TEAM_0:w.setActive(!1);u.setActive(!0);p.setActive(!0);t.setActive(!0);n.setActive(!0);z.setActive(!0);A.setActive(!0);r.setActive(!0);e=TEAM_0;m.text=TEXT_TEAM_0;c="runner_0";break;case TEAM_1:w.setActive(!0);u.setActive(!1);p.setActive(!0);t.setActive(!0);n.setActive(!0);z.setActive(!0);A.setActive(!0);r.setActive(!0);e=TEAM_1;m.text=TEXT_TEAM_1;c="runner_1";break;case TEAM_2:w.setActive(!0);u.setActive(!0);p.setActive(!1);
t.setActive(!0);n.setActive(!0);z.setActive(!0);A.setActive(!0);r.setActive(!0);e=TEAM_2;m.text=TEXT_TEAM_2;c="runner_2";break;case TEAM_3:w.setActive(!0);u.setActive(!0);p.setActive(!0);t.setActive(!1);n.setActive(!0);z.setActive(!0);A.setActive(!0);r.setActive(!0);e=TEAM_3;m.text=TEXT_TEAM_3;c="runner_3";break;case TEAM_4:w.setActive(!0);u.setActive(!0);p.setActive(!0);t.setActive(!0);n.setActive(!1);z.setActive(!0);A.setActive(!0);r.setActive(!0);e=TEAM_4;m.text=TEXT_TEAM_4;c="runner_4";break;
case TEAM_5:w.setActive(!0);u.setActive(!0);p.setActive(!0);t.setActive(!0);n.setActive(!0);z.setActive(!1);A.setActive(!0);r.setActive(!0);e=TEAM_5;m.text=TEXT_TEAM_5;c="runner_5";break;case TEAM_6:w.setActive(!0);u.setActive(!0);p.setActive(!0);t.setActive(!0);n.setActive(!0);z.setActive(!0);A.setActive(!1);r.setActive(!0);e=TEAM_6;m.text=TEXT_TEAM_6;c="runner_6";break;case TEAM_7:w.setActive(!0),u.setActive(!0),p.setActive(!0),t.setActive(!0),n.setActive(!0),z.setActive(!0),A.setActive(!0),r.setActive(!1),
e=TEAM_7,m.text=TEXT_TEAM_7,c="runner_7"}this.showPlayerPose(PLAYER_X_POSITION_IN_SELECTION,PLAYER_Y_POSITION_IN_SELECTION,c);s_iTeamSelected=e;s_szTeamSelectedSprite=c};this.showPlayerPose=function(a,c,b){s_oStage.removeChild(f);b=s_oSpriteLibrary.getSprite(b+"_pose");f=createBitmap(b);f.x=a;f.y=c;f.regX=b.width/2;f.regY=b.height/2;s_oStage.addChild(f)};this._onExit=function(){s_oMain.gotoMenu();$(s_oMain).trigger("end_session")};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this.unload=function(){n.unload();r.unload();z.unload();p.unload();A.unload();t.unload();u.unload();w.unload();s_oSelectTeam=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(a,c){B.setPosition(g-a,c+k);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||C.setPosition(b-a,c+d)};this._onButNextRelease=function(){this.unload();s_oMain.gotoSelectLevel()};s_oSelectTeam=this;this._init()}var s_oSelectTeam=null;
function CGame(c,a){var b=0,d=0,g=s_iTeamSelected,k=0,e=!1,l=!1,f=!1,h=!1,m,q,n,r,p=null,t=null,z,A,u,w,x=[],B=[TEAM_0,TEAM_1,TEAM_2,TEAM_3,TEAM_4,TEAM_5,TEAM_6,TEAM_7],C=[{x:404,y:228},{x:452,y:255},{x:504,y:279},{x:556,y:304},{x:608,y:327},{x:657,y:353},{x:709,y:376},{x:758,y:402}],I=[{x:8106,y:-1640},{x:8154,y:-1616},{x:8202,y:-1592},{x:8250,y:-1568},{x:8298,y:-1544},{x:8346,y:-1520},{x:8394,y:-1496},{x:8442,y:-1472}],D=[],J=[],E=[];this._init=function(){$(s_oMain).trigger("start_level",a);playSound("crowd",
1,-1);setVolume(s_oSoundtrack,0);u=new createjs.Container;s_oStage.addChild(u);A=new CScrollingBg(u);A.setArrivalPositions(I);var c=B[g];B[g]=null;w=new createjs.Container;s_oStage.addChild(w);for(var b=0;b<NUM_RUNNERS;b++)if(3!==b){null!==B[b]?(E.push(B[b]),B[b]=null):b===NUM_RUNNERS-1?(E.push(B[3]),B[3]=null):(E.push(B[b+1]),B[b+1]=null);var d=ENEMY_MAX_SPEED[b]+s_iSpeedAdder,e=ENEMY_MIN_SPEED[b],h=ENEMY_ENERGY[b]+s_iEnergyAdder,f=ENEMY_RESISTENCE_STEP[b],l=ENEMY_OCCURRENCE_RUN[b];x.push(new CRunner(C[b].x,
C[b].y,w,b,!1,PLAYER_NAME_AND_SPRITE[E[E.length-1]],d,e,h,f,l))}else E.push(c),d=PLAYER_MAX_SPEED+s_iSpeedAdder,e=PLAYER_MIN_SPEED,h=PLAYER_ENERGY+s_iEnergyAdder,f=PLAYER_RESISTENCE_STEP,l=0,x.push(new CRunner(C[b].x,C[b].y,w,b,!0,PLAYER_NAME_AND_SPRITE[E[E.length-1]],d,e,h,f,l));q=new CInterface;n=new CHealthBar;DIST_FROM_ARRIVAL=30;s_bMobile?r=new CMobileControls:document.onkeydown=this.onKeyDown;this.enableMovement()};this.enableMovement=function(){for(var a=[],b=0;b<NUM_RUNNERS;b++)a.push(x[b].getInfos());
m=new CShowNationalityInLane(a,u);p=new CVariousHelp(TEXT_START_MOVEMENT,WAIT_FOR_GAME_START)};this.startGame=function(){if(e){l=!0;for(var a=0;a<NUM_RUNNERS;a++)x[a].playAnimation()}else e=!0,q.setGUIClickable(),setTimeout(function(){s_oGame.prepareRunners()},2E3)};this.prepareRunners=function(){playSound("prepare_runner",1,0);for(var a=0;a<NUM_RUNNERS;a++)x[a].playAnimation();setTimeout(function(){s_oGame.startRunners()},1500)};this.startRunners=function(){playSound("start_race",1,0);playSound("crowd_cheers",
1,0);for(var a=0;a<NUM_RUNNERS;a++)x[a].changeAnimation(ANIMATION_STARTING);m&&(m.unload(),m=null);l=!0};this.onKeyDown=function(a){if(l)return a||(a=window.event),a.keyCode===LEFT_DIR?f=!0:a.keyCode===RIGHT_DIR&&(h=!0),f&&h&&x[3].addSpeed(),a.preventDefault(),!1};this.onButtonDown=function(a){null!==p&&(z.unloadVariousHelp(),m.unload(),m=null,e=!0,q.setGUIClickable());l&&(a===LEFT_DIR?f=!0:a===RIGHT_DIR&&(h=!0),f&&h&&x[3].addSpeed())};this.moveRunnersWithBG=function(a){A.move(a);for(var b=A.getDirectionVector(),
c=0;c<NUM_RUNNERS;c++)x[c].movementAffectedByPlayer(a,b)};this.moveEnemies=function(){for(var a=0;a<NUM_RUNNERS;a++)3!==a&&(!1===x[a].isArrived()&&Math.random()>x[a].getOccurrenceRun()*x[a].getEnergyProportion()&&x[a].addSpeed(),x[a].move()),x[a].decreaseSpeed(),x[a].increaseEnergy()};this.checkIfIsElapsedTooMuchTimeBetweenPress=function(){b+=s_iTimeElaps;200<b?b=0:f&&h&&(h=f=!1,b=0)};this.checkDistanceFromArrivalPoint=function(){for(var a=0;a<NUM_RUNNERS;a++)x[a].checkDistance(A.getArrivalPositions(a))};
this.addInArrayPlayerArrived=function(b,c){D.push({lane:b,name:c,time:formatTime(d)});1===D.length&&playSound("crowd_arrival",1,0);var e=D.length-1;J.push({player:E[b],position:e});q.addArrivalPanel(D[e]);3===b&&3>=e+1?(k=e,s_oCityInfos.setRewardTaken(a,k)):3===b&&(k=e);3===b&&null!==s_oCityInfos.getTimeSpent(a)?s_oCityInfos.getTimeSpent(a)>d&&s_oCityInfos.setTimeSpent(a,d):3===b&&s_oCityInfos.setTimeSpent(a,d);D.length===NUM_RUNNERS&&(s_oCityInfos.setPlayersArrivals(a,J),setTimeout(this.gameOver(),
1E3))};this.changeBGsDirection=function(){A.changeDir()};this.unloadVariousHelp=function(a){p.unload();p=null;if(a===CONFIRMATION_ON_EXIT)for(l=e=!0,a=0;a<NUM_RUNNERS;a++)x[a].playAnimation();q.setGUIClickable()};this.unload=function(){s_bMobile?r.unload():document.onkeydown=null;createjs.Sound.stop();s_oSoundtrack=playSound("soundtrack",1,-1);q.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onInfo=function(){if(l){p=new CVariousHelp(TEXT_START_MOVEMENT,WAIT_FOR_GAME_START);
l=!1;for(var a=0;a<NUM_RUNNERS;a++)x[a].stopAnimation()}};this.onInfoExit=function(){p.unload();p=null;if(e){l=!0;for(var a=0;a<NUM_RUNNERS;a++)x[a].playAnimation()}};this.onExitMessage=function(){if(null===p&&l){p=new CVariousHelp(TEXT_ON_EXIT,CONFIRMATION_ON_EXIT);e=l=!1;for(var a=0;a<NUM_RUNNERS;a++)x[a].stopAnimation()}};this.onExit=function(){$(s_oMain).trigger("end_level");$(s_oMain).trigger("end_session");this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this.onContinue=function(){$(s_oMain).trigger("end_level");
$(s_oMain).trigger("show_interlevel_ad");this.unload();s_oMain.gotoPlayerProgress()};this.gameOver=function(){3>k&&s_iLevelReached<a+2&&(s_iLevelReached=a+2);setTimeout(function(){r&&r.hideButtons();q.unloadArrivalPanel();e=l=!1;for(var a=0;a<NUM_RUNNERS;a++)x[a].stopAnimation()},500);a<s_oCityInfos.getNumLevels()-1?t=CEndPanel(D,a):(setVolume(s_oSoundtrack,1),t=new CPodiumScreen(a));t.show()};this.update=function(){if(l){if(!1===x[3].isArrived()){var a=x[3].getSpeed();this.moveRunnersWithBG(a)}else x[3].move();
d+=s_iTimeElaps;q.refreshTime(formatTime(d));this.moveEnemies();n.refreshMask(x[3].getEnergy());this.checkIfIsElapsedTooMuchTimeBetweenPress();this.checkDistanceFromArrivalPoint()}};PLAYER_MAX_SPEED=c.player_max_speed;PLAYER_MIN_SPEED=c.player_min_speed;PLAYER_ENERGY=c.player_energy;PLAYER_RESISTENCE_STEP=c.player_resistence_step;PLAYER_MAX_SPEED_ADDER=c.player_max_speed_adder;PLAYER_ENERGY_ADDER=c.player_energy_adder;PLAYER_NAME_AND_SPRITE=[{name:TEXT_TEAM_0,sprite:0},{name:TEXT_TEAM_1,sprite:1},
{name:TEXT_TEAM_2,sprite:2},{name:TEXT_TEAM_3,sprite:3},{name:TEXT_TEAM_4,sprite:4},{name:TEXT_TEAM_5,sprite:5},{name:TEXT_TEAM_6,sprite:6},{name:TEXT_TEAM_7,sprite:7}];s_oGame=this;z=this;this._init()}var s_oGame;
function CInterface(){var c,a,b,d,g,k,e,l,f,h=[],m,q=0,n=!1,r,p;this._init=function(){var t=s_oSpriteLibrary.getSprite("but_exit");g=CANVAS_WIDTH-t.width/2-10;k=t.height/2+10;l=new CGfxButton(g,k,t,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onExit,this);t=s_oSpriteLibrary.getSprite("but_info");b=CANVAS_WIDTH-t.width/2-90;d=t.height/2+10;f=new CGfxButton(b,d,t,s_oStage);f.addEventListener(ON_MOUSE_UP,this._onInfo,this);c=CANVAS_WIDTH-t.width/2-170;a=t.height/2+10;if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)t=s_oSpriteLibrary.getSprite("audio_icon"),e=new CToggle(c,a,t,s_bAudioActive),e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);r=createBitmap(s_oSpriteLibrary.getSprite("time_panel"));r.x=10;r.y=15;s_oStage.addChild(r);p=new createjs.Text("00:00:000"," 34px "+FONT_2,"#fff");p.x=24;p.y=60;p.textAlign="left";p.textBaseline="alphabetic";s_oStage.addChild(p);m=[{x:CANVAS_WIDTH-250,y:100},{x:CANVAS_WIDTH-250,y:150},{x:CANVAS_WIDTH-250,y:200},{x:CANVAS_WIDTH-250,y:250},{x:CANVAS_WIDTH-
250,y:300},{x:CANVAS_WIDTH-250,y:350},{x:CANVAS_WIDTH-250,y:400},{x:CANVAS_WIDTH-250,y:450}];for(t=0;t<NUM_RUNNERS;t++)h.push(new CArrivalPanel(CANVAS_WIDTH,m[t].y,s_oStage));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.addArrivalPanel=function(a){h[q].show(CANVAS_WIDTH-s_iOffsetX-250,a,q+1);q++};this.unloadArrivalPanel=function(){for(var a=0;a<h.length;a++)h[a].hide(CANVAS_WIDTH+250)};this.refreshTime=function(a){p.text=a};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),
e=null;l.unload();f.unload();s_oInterface=null};this.refreshButtonPos=function(m,n){l.setPosition(g-m,n+k);f.setPosition(b-m,n+d);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||e.setPosition(c-m,n+a);p.x=24+m;p.y=60+n;r.x=10+m;r.y=15+n;for(var q=0;q<NUM_RUNNERS;q++)h[q].refreshButtonPos(m,n)};this.setGUIClickable=function(){n=!0};this._onButRestartRelease=function(){s_oGame.restartGame()};this.onExitFromHelp=function(){_oHelpPanel.unload()};this._onAudioToggle=function(){n?(createjs.Sound.setMute(s_bAudioActive),
s_bAudioActive=!s_bAudioActive):e.setActive(!0)};this._onInfo=function(){if(n)s_oGame.onInfo()};this._onExit=function(){if(n)s_oGame.onExitMessage()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CEndPanel(c,a){var b,d,g=0,k,e,l,f,h,m,q,n=s_oCityInfos.getPlayersArrivals(),r=[],p=[100,50,25,10,9,8,7,6];this._init=function(){h=new createjs.Container;h.alpha=0;h.visible=!1;s_oStage.addChild(h);q=new createjs.Shape;q.graphics.beginFill("rgba(0,0,0,0.6)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q.on("click",function(){});h.addChild(q);var a=s_oSpriteLibrary.getSprite("result_panel");f=createBitmap(a);f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2;f.regX=a.width/2;f.regY=a.height/2;h.addChild(f);
e=new createjs.Text(TEXT_DISCIPLINE," 20px "+FONT,"#ffffff");e.x=500;e.y=160;e.textAlign="left";e.textBaseline="alphabetic";h.addChild(e);l=new createjs.Text(TEXT_RESULT," 22px "+FONT,"#ffffff");l.x=500;l.y=190;l.textAlign="left";l.textBaseline="alphabetic";h.addChild(l);a=s_oSpriteLibrary.getSprite("but_continue_small");b=CANVAS_WIDTH/2+340;d=CANVAS_HEIGHT-172;m=new CGfxButton(b,d,a,h);m.addEventListener(ON_MOUSE_UP,this._onContinue,this);this.getRunnerInLane();this.addScoreToPlayers()};this.show=
function(){for(var b=450,d=210,e=0;e<n[a].length;e++){var f=createBitmap(s_oSpriteLibrary.getSprite("flag_"+n[a][e].player));f.x=b;f.y=d;h.addChild(f);b+=118;d+=17;f=new createjs.Text(e+1," 20px "+FONT,"#ffffff");f.x=b-155;f.y=d;f.textAlign="left";f.textBaseline="alphabetic";h.addChild(f);f=new createjs.Text(c[e].name," 20px "+FONT,"#ffffff");f.x=b;f.y=d;f.textAlign="left";f.textBaseline="alphabetic";h.addChild(f);b+=305;f=new createjs.Text(c[e].time," 20px "+FONT,"#ffffff");f.x=b;f.y=d;f.textAlign=
"left";f.textBaseline="alphabetic";h.addChild(f);b=450;d+=20}h.visible=!0;createjs.Tween.get(h).to({alpha:1},500).call(function(){});$(s_oMain).trigger("save_score",g);localStorage.setItem("LevelReached",s_iLevelReached);localStorage.setItem("Money",s_iPlayerMoney);localStorage.setItem("SpeedBought",s_iSpeedBought);localStorage.setItem("EnergyBought",s_iEnergyBought);localStorage.setItem("SpeedAdder",s_iSpeedAdder);localStorage.setItem("EnergyAdder",s_iEnergyAdder);localStorage.setItem("TeamSelected",
s_iTeamSelected);localStorage.setItem("TeamSelectedSprite",s_szTeamSelectedSprite);localStorage.setItem("Scores",JSON.stringify(s_aRunnersScore));s_oCityInfos.addCitiesStorage()};this.getRunnerInLane=function(){for(var b=0;b<n[0].length;b++)r.push(PLAYER_NAME_AND_SPRITE[n[a][b].player].sprite),r[b]===s_iTeamSelected&&(k=b)};this.addScoreToPlayers=function(){for(var b=0;b<n[a].length;b++)s_aRunnersScore[n[a][b].player]+=p[n[a][b].position];g=s_aRunnersScore[n[a][k].player]};this._onContinue=function(){playSound("click",
.5,0);s_oStage.removeChild(h);m.unload();q.off("click",function(){});s_oGame.onContinue()};this._init();return this}
function CRunner(c,a,b,d,g,k,e,l,f,h,m){var q=!1,n=0,r=0,p=f,t=p,z=k.name,A=k.sprite,u,w=null,x=new CVector2(0,1),B=new CVector2;this._init=function(){this.createRunner()};this.createRunner=function(){var d={images:[s_oSpriteLibrary.getSprite("runner_"+A)],framerate:15,frames:{width:PLAYER_WIDTH,height:PLAYER_HEIGHT,regX:PLAYER_WIDTH/2,regY:PLAYER_HEIGHT/2},animations:{position:[0,10,!1],starting:[11,39,!1],run:[40,45,"run"],ending:[46,56]}},d=new createjs.SpriteSheet(d);u=new createjs.Sprite(d,"position");
u.addEventListener("animationend",this._onAnimationEnd);u.x=c;u.y=a;u.currentAnimationFrame=0;b.addChild(u);r=ANIMATION_POSITION;u.stop();rotateVector2D(Math.PI/180*104,x);g&&(w=createBitmap(s_oSpriteLibrary.getSprite("arrow_bar")),w.x=u.x+40,w.y=u.y-60,w.scaleX=.4,w.scaleY=.4,s_oStage.addChild(w),this._cursorAnimationDown())};this.stopAnimation=function(){u.stop()};this.playAnimation=function(){u.play()};this.changeAnimation=function(a){u.gotoAndPlay(a);r=a;r===ANIMATION_STARTING&&g&&(this._stopCursorAnim(),
a=u.y-80,createjs.Tween.get(w).to({y:a},500).call(function(){C._cursorAnimationDown()}))};this.checkDistance=function(a){this.distance2(B,a)/100<DIST_FROM_ARRIVAL&&r===ANIMATION_RUNNING&&!1===q&&(q=!0,this.changeAnimation(ANIMATION_ENDING),s_oGame.addInArrayPlayerArrived(d,z),null!==w&&(createjs.Tween.removeTweens(w),s_oStage.removeChild(w)))};this._onAnimationEnd=function(){r===ANIMATION_STARTING&&C.showRunningAnimation()};this.showRunningAnimation=function(){r=ANIMATION_RUNNING;u.gotoAndPlay(ANIMATION_RUNNING);
g&&B.set(u.x,u.y)};this._stopCursorAnim=function(){createjs.Tween.removeTweens(w)};this._cursorAnimationDown=function(){createjs.Tween.get(w).to({y:w.y+10},500).call(function(){C._cursorAnimationUp()})};this._cursorAnimationUp=function(){createjs.Tween.get(w).to({y:w.y-10},500).call(function(){C._cursorAnimationDown()})};this.distance2=function(a,b){return(b.getX()-a.getX())*(b.getX()-a.getX())+(b.getY()-a.getY())*(b.getY()-a.getY())};this.move=function(){u.x+=n*x.getX();u.y+=n*x.getY();B.set(u.x,
u.y)};this.movementAffectedByPlayer=function(a,b){g||(u.x+=a*b.getX(),u.y+=a*b.getY())};this.addSpeed=function(){if(0<=p){p-=h;var a=p/t*MODIFIER_SPEED_ADDER;a<h&&(a=h);n+=a;n>=e?n=e:n<=l&&(n=l)}};this.changeDirection=function(){rotateVector2D(Math.PI/180*180,x)};this.decreaseSpeed=function(){n-=SPEED_DECELERATION;n<=l&&(n=l)};this.increaseEnergy=function(){p<t&&(p+=ENERGY_INCREASE)};this.getEnergyProportion=function(){return p/t};this.getOccurrenceRun=function(){return m};this.getInfos=function(){return{sprite:A,
nationality:z}};this.getSpeed=function(){return n};this.isArrived=function(){return q};this.getEnergy=function(){return p};this.unload=function(){u=null;b.removeAllChildren()};var C=this;this._init()}
function CScrollingBg(c){var a=[],b,d=new CVector2(0,1);this._init=function(){var b=s_oSpriteLibrary.getSprite("track_0");a[0]=createBitmap(b);a[0].scaleX=a[0].scaleY=s_iScale;c.addChild(a[0]);b=s_oSpriteLibrary.getSprite("track_1");a[1]=createBitmap(b);a[1].y=-CANVAS_HEIGHT;a[1].scaleX=a[1].scaleY=s_iScale;c.addChild(a[1]);b=s_oSpriteLibrary.getSprite("track_2");a[2]=createBitmap(b);a[2].x=CANVAS_WIDTH;a[2].scaleX=a[2].scaleY=s_iScale;c.addChild(a[2]);b=s_oSpriteLibrary.getSprite("track_3");a[3]=
createBitmap(b);a[3].x=CANVAS_WIDTH;a[3].y=-CANVAS_HEIGHT;a[3].scaleX=a[3].scaleY=s_iScale;c.addChild(a[3]);b=s_oSpriteLibrary.getSprite("track_4");a[4]=createBitmap(b);a[4].x=2*CANVAS_WIDTH;a[4].scaleX=a[4].scaleY=s_iScale;c.addChild(a[4]);b=s_oSpriteLibrary.getSprite("track_5");a[5]=createBitmap(b);a[5].x=2*CANVAS_WIDTH;a[5].y=-CANVAS_HEIGHT;a[5].scaleX=a[5].scaleY=s_iScale;c.addChild(a[5]);b=s_oSpriteLibrary.getSprite("track_6");a[6]=createBitmap(b);a[6].x=2*CANVAS_WIDTH;a[6].y=2*-CANVAS_HEIGHT;
a[6].scaleX=a[6].scaleY=s_iScale;c.addChild(a[6]);b=s_oSpriteLibrary.getSprite("track_7");a[7]=createBitmap(b);a[7].x=3*CANVAS_WIDTH;a[7].y=-CANVAS_HEIGHT;a[7].scaleX=a[7].scaleY=s_iScale;c.addChild(a[7]);b=s_oSpriteLibrary.getSprite("track_8");a[8]=createBitmap(b);a[8].x=3*CANVAS_WIDTH;a[8].y=2*-CANVAS_HEIGHT;a[8].scaleX=a[8].scaleY=s_iScale;c.addChild(a[8]);b=s_oSpriteLibrary.getSprite("track_9");a[9]=createBitmap(b);a[9].x=4*CANVAS_WIDTH;a[9].y=-CANVAS_HEIGHT;a[9].scaleX=a[9].scaleY=s_iScale;c.addChild(a[9]);
b=s_oSpriteLibrary.getSprite("track_10");a[10]=createBitmap(b);a[10].x=4*CANVAS_WIDTH;a[10].y=2*-CANVAS_HEIGHT;a[10].scaleX=a[10].scaleY=s_iScale;c.addChild(a[10]);b=s_oSpriteLibrary.getSprite("track_11");a[11]=createBitmap(b);a[11].x=4*CANVAS_WIDTH;a[11].y=3*-CANVAS_HEIGHT;a[11].scaleX=a[11].scaleY=s_iScale;c.addChild(a[11]);b=s_oSpriteLibrary.getSprite("track_12");a[12]=createBitmap(b);a[12].x=5*CANVAS_WIDTH;a[12].y=2*-CANVAS_HEIGHT;a[12].scaleX=a[12].scaleY=s_iScale;c.addChild(a[12]);b=s_oSpriteLibrary.getSprite("track_13");
a[13]=createBitmap(b);a[13].x=5*CANVAS_WIDTH;a[13].y=3*-CANVAS_HEIGHT;a[13].scaleX=a[13].scaleY=s_iScale;c.addChild(a[13]);b=s_oSpriteLibrary.getSprite("track_14");a[14]=createBitmap(b);a[14].x=5*CANVAS_WIDTH;a[14].y=4*-CANVAS_HEIGHT;a[14].scaleX=a[14].scaleY=s_iScale;c.addChild(a[14]);b=s_oSpriteLibrary.getSprite("track_15");a[15]=createBitmap(b);a[15].x=6*CANVAS_WIDTH;a[15].y=2*-CANVAS_HEIGHT;a[15].scaleX=a[15].scaleY=s_iScale;c.addChild(a[15]);b=s_oSpriteLibrary.getSprite("track_16");a[16]=createBitmap(b);
a[16].x=6*CANVAS_WIDTH;a[16].y=3*-CANVAS_HEIGHT;a[16].scaleX=a[16].scaleY=s_iScale;c.addChild(a[16]);b=s_oSpriteLibrary.getSprite("track_17");a[17]=createBitmap(b);a[17].x=6*CANVAS_WIDTH;a[17].y=4*-CANVAS_HEIGHT;a[17].scaleX=a[17].scaleY=s_iScale;c.addChild(a[17]);rotateVector2D(Math.PI/180*-76,d)};this.setArrivalPositions=function(a){b=a};this.changeDir=function(){rotateVector2D(Math.PI/180*180,d)};this.move=function(a){c.x+=a*d.getX();c.y+=a*d.getY();for(var k=0;k<b.length;k++)b[k].x+=a*d.getX(),
b[k].y+=a*d.getY()};this.getArrivalPositions=function(a){return new CVector2(b[a].x,b[a].y)};this.getDirectionVector=function(){return d};this._init()}
function CHealthBar(){var c,a,b=100,d,g,k,e=CANVAS_WIDTH/2+170,l=CANVAS_HEIGHT-110,f=e-4,h=l+30;this.init=function(){var b=s_oSpriteLibrary.getSprite("health");g=createBitmap(b);g.x=f;g.y=h;g.regX=b.width;g.alpha=.9;s_oStage.addChild(g);c=b.width;a=b.height-6;k=new createjs.Shape;k.graphics.beginFill("rgba(0,255,255,1)").drawRect(g.x-c,g.y,c,a+3);s_oStage.addChild(k);b=s_oSpriteLibrary.getSprite("energy_bar");d=createBitmap(b);d.x=e;d.y=l;d.regX=b.width;s_oStage.addChild(d);g.mask=k;this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.refreshMask=function(d){b=d;k.graphics.clear();d=Math.floor(b*c/100);k.graphics.beginFill("rgba(0,255,255,0.01)").drawRect(g.x-c,g.y+3,d,a)};this.refreshButtonPos=function(a,c){g.y=h-c;d.y=l-c;this.refreshMask(b)};s_oHealthBar=this;this.init()}var s_oHealthBar=null;
function CMobileControls(){var c=CANVAS_HEIGHT-150,a,b=CANVAS_WIDTH-100,d=CANVAS_HEIGHT-150,g;this.init=function(){var k=s_oSpriteLibrary.getSprite("left_button");a=new CGfxButton(100,c,k,s_oStage);a.addEventListenerWithParams(ON_MOUSE_DOWN,s_oGame.onButtonDown,this,LEFT_DIR);k=s_oSpriteLibrary.getSprite("right_button");g=new CGfxButton(b,d,k,s_oStage);g.addEventListenerWithParams(ON_MOUSE_DOWN,s_oGame.onButtonDown,this,RIGHT_DIR);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.spawnButtonForBar=
function(){a.setVisible(!1);g.setVisible(!1)};this.hideButtonForBar=function(){a.setVisible(!0);g.setVisible(!0)};this.hideButtons=function(){a.setVisible(!1);g.setVisible(!1)};this.refreshButtonPos=function(k,e){a.setPosition(100+k,c);g.setPosition(b-k,d)};this.unload=function(){a.unload();g.unload()};s_oMobileControls=this;this.init()}var s_oMobileControls=null;
function CPrintInfosOnPanel(c,a,b,d){var g=d+1,k,e=b.lane+1,l=b.name,f=b.time,h;this.init=function(){h=new createjs.Container;h.x=c;h.y=a;h.alpha=0;s_oStage.addChild(h);switch(g){case 1:k=g+"st";break;case 2:k=g+"nd";break;case 3:k=g+"rd";break;case 4:case 5:case 6:case 7:case 8:k=g+"th"}var b=new createjs.Text(k," 15px "+FONT,"#ffffff");b.x=10;b.y=20;b.textAlign="left";b.textBaseline="alphabetic";h.addChild(b);b=new createjs.Text(l," 12px "+FONT,"#ffffff");b.x=10;b.y=38;b.textAlign="left";b.textBaseline=
"alphabetic";h.addChild(b);b=new createjs.Text(TEXT_LANE+": "+e," 15px "+FONT,"#ffffff");b.x=230;b.y=20;b.textAlign="right";b.textBaseline="alphabetic";h.addChild(b);b=new createjs.Text(f," 15px "+FONT,"#ffffff");b.x=230;b.y=40;b.textAlign="right";b.textBaseline="alphabetic";h.addChild(b);createjs.Tween.get(h).to({alpha:1},400,createjs.Ease.quadInOut).call(function(){})};this.setPos=function(a,b){h.x=a;h.y=b};this.unload=function(){createjs.Tween.get(h).to({alpha:0},400,createjs.Ease.quadInOut).call(function(){s_oStage.removeChild(h)})};
this.init()}
function CLevelMenu(){var c,a,b,d,g,k=[],e,l,f;this._init=function(){e=createBitmap(s_oSpriteLibrary.getSprite("bg_select_challenge"));s_oStage.addChild(e);var h=new createjs.Shape;h.graphics.beginFill("rgba(0,0,0,0.6)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(h);h=s_oSpriteLibrary.getSprite("select_challenge");e=createBitmap(h);e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2;e.regX=h.width/2;e.regY=h.height/2;s_oStage.addChild(e);g=new createjs.Text(TEXT_CHALLENGE," 20px "+FONT,"#ffffff");
g.x=CANVAS_WIDTH/2-180;g.y=128;g.textAlign="left";g.textBaseline="alphabetic";g.lineWidth=1E3;s_oStage.addChild(g);for(var h=CANVAS_WIDTH/2-240,m=0,q=50,n=0;n<s_oCityInfos.getNumLevels();n++,m+=120){500<m&&(m=0,q+=175);var r=s_oCityInfos.getCityName(n),p=s_oCityInfos.getRewards(n);n<s_iLevelReached?k.push(new CLevelBut(h+m,215+q,s_oSpriteLibrary.getSprite("level_sprite"),!0,n+1,r,p)):k.push(new CLevelBut(h+m,215+q,s_oSpriteLibrary.getSprite("level_sprite"),!1,n+1,r,p));k[n].addEventListenerWithParams(ON_MOUSE_UP,
this._onClick,this,n);k[n].addEventListenerWithParams(ON_MOUSE_DOWN,this._onMouseDown,this,n);s_bFirstTime=!0}h=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-h.height/2-10;d=h.height/2+10;l=new CGfxButton(b,d,h,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onExit,this);c=CANVAS_WIDTH-h.width/2-90;a=h.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h=s_oSpriteLibrary.getSprite("audio_icon"),f=new CToggle(c,a,h,s_bAudioActive),f.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);
this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){for(var a=0;a<s_oCityInfos.getNumLevels();a++)k[a].unload();s_oLevelMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(e,g){l.setPosition(b-e,g+d);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||f.setPosition(c-e,g+a)};this._onNumModeToggle=function(a){a===NUM_ACTIVE?((void 0).setActive(!1),(void 0).setActive(!0)):((void 0).setActive(!0),(void 0).setActive(!1))};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onMouseDown=function(a){k[a].scaleText()};this._onClick=function(a){playSound("press_button",1,0);k[a].ifClickable()&&(s_oLevelMenu.unload(),s_oMain.gotoGame(a))};this._onExit=function(){s_oLevelMenu.unload();1===s_iLevelReached?(s_oMain.gotoMenu(),$(s_oMain).trigger("end_session")):s_oMain.gotoPlayerProgress()};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(c,a,b,d,g,k,e){var l,f,h,m=[],q=[],n,r,p,t,z;this._init=function(a,b,c,d){f=[];h=[];z=new createjs.Container;z.x=a;z.y=b;s_oStage.addChild(z);var g=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});l=d;n=createSprite(g,"state_"+l,c.width/2/2,c.height/2,c.width/2,c.height);n.mouseEnabled=d;n.x=0;n.y=0;n.cursor="pointer";n.stop();z.addChild(n);m.push(n);c=new createjs.Text(k,
" 13px "+FONT,"#ffffff");c.x=a;c.y=b-70;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=200;s_oStage.addChild(c);r=new createjs.Text(e.first+TEXT_CURRENCY," 20px "+FONT,"#fff");r.x=8;r.y=-40;r.textAlign="center";r.textBaseline="middle";r.lineWidth=200;z.addChild(r);p=new createjs.Text(e.second+TEXT_CURRENCY," 20px "+FONT,"#fff");p.x=8;p.y=r.y+35;p.textAlign="center";p.textBaseline="middle";p.lineWidth=200;z.addChild(p);t=new createjs.Text(e.third+TEXT_CURRENCY," 20px "+FONT,"#fff");t.x=
8;t.y=r.y+70;t.textAlign="center";t.textBaseline="middle";t.lineWidth=200;z.addChild(t);this._initListener()};this.scaleText=function(){z.scaleY=.9};this.unload=function(){n.off("mousedown",this.buttonDown);n.off("pressup",this.buttonRelease);s_oStage.removeChild(n)};this._initListener=function(){n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.viewBut=function(a){s_oStage.addChild(a)};this.addEventListener=function(a,b,c){f[a]=b;h[a]=c};this.addEventListenerWithParams=function(a,
b,c,d){f[a]=b;h[a]=c;q=d};this.ifClickable=function(){return!0===n.mouseEnabled?1:0};this.setActive=function(a,b){l=b;m[a].gotoAndStop("state_"+l);m[a].mouseEnabled=!0};this.buttonRelease=function(){z.scaleX=1;z.scaleY=1;playSound("press_button",1,0);l=!l;n.gotoAndStop("state_"+l);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(h[ON_MOUSE_UP],q)};this.buttonDown=function(){z.scaleX=.9;z.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN],q)};this.setPosition=function(a,b){n.x=a;n.y=b};this.setVisible=
function(a){n.visible=a};this._init(c,a,b,d)}
function CCitySettings(){var c=[],a=[],b=[],d=[],g=[],k=[],e=[];this._init=function(){this.initCityName();this.initRewards();this.initRewardTaken();this.initTimeSpent();this.initRewardEarned();this.initValueToAddInEachLevelToCPU();this.initArrivalsPosition()};this.initCityName=function(){for(var a=0;10>a;a++)c.push(CITY_NAME[a])};this.initRewards=function(){a.push({first:100,second:50,third:25});a.push({first:100,second:50,third:25});a.push({first:100,second:50,third:25});a.push({first:100,second:50,
third:25});a.push({first:100,second:50,third:25});a.push({first:100,second:50,third:25});a.push({first:100,second:50,third:25});a.push({first:100,second:50,third:25});a.push({first:125,second:75,third:50});a.push({first:150,second:100,third:75})};this.initRewardTaken=function(){b.push(!1);b.push(!1);b.push(!1);b.push(!1);b.push(!1);b.push(!1);b.push(!1);b.push(!1);b.push(!1);b.push(!1)};this.initTimeSpent=function(){d.push(null);d.push(null);d.push(null);d.push(null);d.push(null);d.push(null);d.push(null);
d.push(null);d.push(null);d.push(null)};this.initRewardEarned=function(){g.push(null);g.push(null);g.push(null);g.push(null);g.push(null);g.push(null);g.push(null);g.push(null);g.push(null);g.push(null)};this.initValueToAddInEachLevelToCPU=function(){k.push({speed:0,energy:0});k.push({speed:.2,energy:2});k.push({speed:.4,energy:4});k.push({speed:.6,energy:6});k.push({speed:.8,energy:8});k.push({speed:1,energy:10});k.push({speed:1.2,energy:12});k.push({speed:1.4,energy:14});k.push({speed:1.6,energy:16});
k.push({speed:1.8,energy:18})};this.initArrivalsPosition=function(){e.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);e.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);e.push([{player:0,position:-1},{player:0,position:-1},
{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);e.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);e.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},
{player:0,position:-1}]);e.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);e.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);e.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},
{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);e.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}]);e.push([{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1},{player:0,position:-1}])};this.addCitiesStorage=
function(){localStorage.setItem("RewardTaken",JSON.stringify(b));localStorage.setItem("TimeSpent",JSON.stringify(d));localStorage.setItem("RewardEarned",JSON.stringify(g));localStorage.setItem("ArrivalsPosition",JSON.stringify(e))};this.removeCitiesStorage=function(){b=[];d=[];g=[];e=[];this.initRewardTaken();this.initTimeSpent();this.initRewardEarned();this.initArrivalsPosition();localStorage.removeItem("RewardTaken");localStorage.removeItem("TimeSpent");localStorage.removeItem("RewardEarned");localStorage.removeItem("ArrivalsPosition")};
this.getCitiesStorage=function(){b=JSON.parse(localStorage.getItem("RewardTaken"));d=JSON.parse(localStorage.getItem("TimeSpent"));g=JSON.parse(localStorage.getItem("RewardEarned"));e=JSON.parse(localStorage.getItem("ArrivalsPosition"))};this.getLevel=function(a){return a};this.getNumLevels=function(){return c.length};this.getCityName=function(a){return c[a]};this.getRewards=function(b){return a[b]};this.getValuesToAdd=function(a){return k[a]};this.setRewardTaken=function(c,d){if(!b[c]){b[c]=!0;switch(d){case 0:g[c]=
a[c].first;break;case 1:g[c]=a[c].second;break;case 2:g[c]=a[c].third}s_iPlayerMoney+=g[c]}};this.setPlayersArrivals=function(a,b){e[a]=b};this.getPlayersArrivals=function(){return e};this.getRewardTaken=function(a){return b[a]?g[a]:0};this.getMedal=function(b){return g[b]===a[b].first?"gold":g[b]===a[b].second?"silver":g[b]===a[b].third?"bronze":null};this.setTimeSpent=function(a,b){d[a]=b};this.getTimeSpent=function(a){return d[a]};this.unload=function(){c=[];a=[];b=[];d=[];g=[];k=[];e=[]};this._init()}
function CShowNationalityInLane(c,a){var b,d,g=[{x:446,y:228},{x:496,y:252},{x:547,y:276},{x:598,y:300},{x:649,y:324},{x:700,y:348},{x:751,y:372},{x:804,y:396}],k;this._init=function(){b=new createjs.Container;d.addChild(b);for(var a=0;a<c.length;a++){var l=s_oSpriteLibrary.getSprite("flag_runner_"+c[a].sprite+"_game");k=createBitmap(l);k.x=g[a].x;k.y=g[a].y;b.addChild(k)}};this._onButNextRelease=function(){s_oGame.enableMovement();this.unload()};this.unload=function(){createjs.Tween.get(b).to({alpha:0},
500).call(function(){d.removeChild(b)})};s_oShowLevelInfos=this;d=a;this._init()}var s_oShowLevelInfos=null;
function CPlayerProgress(){var c,a,b,d,g,k,e=[100,150,200,250],l,f=[50,75,100,125],h,m,q=[],n=[],r=CANVAS_WIDTH/2-135,p=175,t,z=[],A=[],u=CANVAS_WIDTH/2+165,w=175,x=s_iPlayerMoney,B,C,I,D,J=CANVAS_WIDTH/2-200,E=222,Q=CANVAS_WIDTH/2-120,K=235,F,R=CANVAS_WIDTH/2-265,L=235,G,S=CANVAS_WIDTH/2+200,M=236,H,N,O,P;this._init=function(){var v=createBitmap(s_oSpriteLibrary.getSprite("bg_select_team"));s_oStage.addChild(v);v=new createjs.Shape;v.graphics.beginFill("rgba(0,0,0,0.6)").drawRect(0,0,CANVAS_WIDTH,
CANVAS_HEIGHT);s_oStage.addChild(v);var v=s_oSpriteLibrary.getSprite("upgrade_panel"),y=createBitmap(v);y.x=CANVAS_WIDTH/2;y.y=CANVAS_HEIGHT/2;y.regX=v.width/2;y.regY=v.height/2;s_oStage.addChild(y);v=new createjs.Text(TEXT_UPGRADE," 20px "+FONT,"#ffffff");v.x=CANVAS_WIDTH/2-180;v.y=75;v.textAlign="left";v.textBaseline="alphabetic";s_oStage.addChild(v);m=new createjs.Shape;m.graphics.beginFill("#000000").drawRect(r-165,p-60,285,90);m.alpha=.01;m.on("mousedown",this.tryingToBuySpeed);m.cursor="pointer";
s_oStage.addChild(m);t=new createjs.Shape;t.graphics.beginFill("#000000").drawRect(u-160,w-60,285,90);t.alpha=.01;t.on("mousedown",this.tryingToBuyEnergy);t.cursor="pointer";s_oStage.addChild(t);v=new createjs.Text(TEXT_BUY," 20px "+FONT,"#ffffff");v.x=CANVAS_WIDTH/2-275;v.y=175;v.textAlign="left";v.textBaseline="alphabetic";s_oStage.addChild(v);v=new createjs.Text(TEXT_BUY," 20px "+FONT,"#ffffff");v.x=CANVAS_WIDTH/2+30;v.y=175;v.textAlign="left";v.textBaseline="alphabetic";s_oStage.addChild(v);for(y=
0;y<NUM_POWER_UP_AVAILABLE;y++)q.push(createBitmap(s_oSpriteLibrary.getSprite("bar-1"))),q[y].x=r,q[y].y=p,s_oStage.addChild(q[y]),n.push(createBitmap(s_oSpriteLibrary.getSprite("bar-2"))),n[y].x=r,n[y].y=p,n[y].visible=!1,s_oStage.addChild(n[y]),l=new createjs.Text(e[y]+TEXT_CURRENCY," 10px "+FONT,"#ffffff"),l.x=r+50,l.y=p+11,l.textAlign="center",l.textBaseline="alphabetic",s_oStage.addChild(l),z.push(createBitmap(s_oSpriteLibrary.getSprite("bar-1"))),z[y].x=u,z[y].y=w,s_oStage.addChild(z[y]),A.push(createBitmap(s_oSpriteLibrary.getSprite("bar-2"))),
A[y].x=u,A[y].y=w,A[y].visible=!1,s_oStage.addChild(A[y]),h=new createjs.Text(f[y]+TEXT_CURRENCY,"10px "+FONT,"#ffffff"),h.x=u+50,h.y=w+11,h.textAlign="center",h.textBaseline="alphabetic",s_oStage.addChild(h),p-=15,w-=15;for(y=0;y<s_iSpeedBought;y++)this.makeVisibleSpeedBought(y);for(y=0;y<s_iEnergyBought;y++)this.makeVisibleEnergyBought(y);D=new createjs.Text(TEXT_MONEY+": "+x+TEXT_CURRENCY," 20px "+FONT,"#ffffff");D.x=CANVAS_WIDTH/2-180;D.y=106;D.textAlign="left";D.textBaseline="alphabetic";s_oStage.addChild(D);
for(y=0;y<s_oCityInfos.getNumLevels();y++)B=s_oCityInfos.getCityName(y),C=formatTime(s_oCityInfos.getTimeSpent(y)),I=s_oCityInfos.getRewardTaken(y),v=s_oCityInfos.getMedal(y),G=new createjs.Text(I+TEXT_CURRENCY," 15px "+FONT,"#ffffff"),G.x=R,G.y=L,G.textAlign="center",G.textBaseline="alphabetic",s_oStage.addChild(G),v&&(v=createBitmap(s_oSpriteLibrary.getSprite(v+"_medal")),v.x=J,v.y=E,v.scaleX=.6,v.scaleY=.6,s_oStage.addChild(v)),F=new createjs.Text(B," 15px "+FONT,"#ffffff"),F.x=Q,F.y=K,F.textAlign=
"left",F.textBaseline="alphabetic",s_oStage.addChild(F),H=new createjs.Text(C," 15px "+FONT,"#ffffff"),H.x=S,H.y=M,H.textAlign="left",H.textBaseline="alphabetic",s_oStage.addChild(H),K+=37,E+=37,L+=37,M+=37;v=s_oSpriteLibrary.getSprite("but_continue_small");c=CANVAS_WIDTH/2+340;a=CANVAS_HEIGHT-91;N=new CGfxButton(c,a,v,s_oStage);N.addEventListener(ON_MOUSE_UP,this._onButNextRelease,this);v=s_oSpriteLibrary.getSprite("but_exit");g=CANVAS_WIDTH-v.height/2-10;k=v.height/2+10;O=new CGfxButton(g,k,v,s_oStage);
O.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)b=CANVAS_WIDTH-v.width/2-90,d=v.height/2+10,v=s_oSpriteLibrary.getSprite("audio_icon"),P=new CToggle(b,d,v,s_bAudioActive),P.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(a,c){O.setPosition(g-a,c+k);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||P.setPosition(b-a,c+d)};this.makeVisibleSpeedBought=function(a){q[a].visible=!1;
n[a].visible=!0};this.makeVisibleEnergyBought=function(a){z[a].visible=!1;A[a].visible=!0};this.tryingToBuySpeed=function(){s_iSpeedBought<NUM_POWER_UP_AVAILABLE&&s_iPlayerMoney>=e[s_iSpeedBought]&&(s_oPlayerProgress.makeVisibleSpeedBought(s_iSpeedBought),s_iSpeedAdder+=PLAYER_MAX_SPEED_ADDER,s_iPlayerMoney-=e[s_iSpeedBought],s_oPlayerProgress.refreshMoneyCurrency(),s_iSpeedBought++,localStorage.setItem("Money",s_iPlayerMoney),localStorage.setItem("SpeedBought",s_iSpeedBought),localStorage.setItem("SpeedAdder",
s_iSpeedAdder),s_iSpeedBought<NUM_POWER_UP_AVAILABLE&&playSound("click",.5,0))};this.tryingToBuyEnergy=function(){s_iEnergyBought<NUM_POWER_UP_AVAILABLE&&s_iPlayerMoney>=f[s_iEnergyBought]&&(s_oPlayerProgress.makeVisibleEnergyBought(s_iEnergyBought),s_iEnergyAdder+=PLAYER_ENERGY_ADDER,s_iPlayerMoney-=f[s_iEnergyBought],s_oPlayerProgress.refreshMoneyCurrency(),s_iEnergyBought++,localStorage.setItem("Money",s_iPlayerMoney),localStorage.setItem("EnergyBought",s_iEnergyBought),localStorage.setItem("EnergyAdder",
s_iEnergyAdder),s_iEnergyBought<NUM_POWER_UP_AVAILABLE&&playSound("upgrade",1,0))};this.refreshMoneyCurrency=function(){D.text="Money:           "+s_iPlayerMoney+TEXT_CURRENCY};this._onButNextRelease=function(){this.unload();s_oMain.gotoSelectLevel(x)};this._onExit=function(){s_oMain.gotoMenu();$(s_oMain).trigger("end_session")};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.unload=function(){s_oStage.removeAllChildren();N.unload();s_oPlayerProgress=
null};s_oPlayerProgress=this;this._init()}var s_oPlayerProgress=null;
function CVariousHelp(c,a){var b,d,g=CANVAS_WIDTH/2,k=CANVAS_HEIGHT/2,e,l,f,h;this._init=function(){d=new createjs.Container;d.x=g;d.y=k;d.alpha=0;l=new createjs.Shape;l.graphics.beginFill("#000000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.alpha=.7;l.on("mousedown",this._onClick);s_oStage.addChild(l);if(a===WAIT_FOR_GAME_START){var m=s_oSpriteLibrary.getSprite("help_panel");b=createBitmap(m);b.regX=m.width/2;b.regY=m.height/2;d.addChild(b);e=new createjs.Text("HELP"," 20px "+FONT,"#ffffff");e.x=
-155;e.y=-193;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=200;d.addChild(e);e=new createjs.Text(c," 24px "+FONT,"#fff");e.x=0;e.y=-70;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=300;d.addChild(e);s_bMobile?(e.text=TEXT_START_MOVEMENT_MOBILE,m=createBitmap(s_oSpriteLibrary.getSprite("left_button")),m.x=-267,m.y=-121,d.addChild(m),m=createBitmap(s_oSpriteLibrary.getSprite("right_button"))):(m=createBitmap(s_oSpriteLibrary.getSprite("left_directional_arrows")),m.x=-267,
m.y=-121,d.addChild(m),m=createBitmap(s_oSpriteLibrary.getSprite("right_directional_arrows")));m.x=143;m.y=-121;d.addChild(m);m=createBitmap(s_oSpriteLibrary.getSprite("horizontal_bar"));m.x=-140;m.y=20;m.scaleX=.5;m.scaleY=.5;d.addChild(m);m=new createjs.Text(HELP_ENERGY," 18px "+FONT,"#fff");m.x=0;m.y=145;m.textAlign="center";m.textBaseline="alphabetic";m.lineWidth=250;d.addChild(m);var m=s_oSpriteLibrary.getSprite("health"),q=createBitmap(m);q.x=96;q.y=84;q.regX=m.width;q.scaleX=.59;q.scaleY=.5;
q.alpha=.9;d.addChild(q);m=s_oSpriteLibrary.getSprite("energy_bar");q=createBitmap(m);q.x=100;q.y=65;q.scaleX=.6;q.scaleY=.6;q.regX=m.width;d.addChild(q)}else a===CONFIRMATION_ON_EXIT?(m=s_oSpriteLibrary.getSprite("are_you_sure_panel"),b=createBitmap(m),b.regX=m.width/2,b.regY=m.height/2,d.addChild(b),e=new createjs.Text(c," 26px "+FONT,"#fff"),e.x=0,e.y=-70,e.textAlign="center",e.textBaseline="alphabetic",e.lineWidth=300,d.addChild(e),f=new CGfxButton(-160,80,s_oSpriteLibrary.getSprite("but_exit"),
d),f.addEventListener(ON_MOUSE_UP,this._onNo,this),h=new CGfxButton(160,80,s_oSpriteLibrary.getSprite("but_yes"),d),h.addEventListener(ON_MOUSE_UP,this._onYes,this)):a===CONFIRMATION_ON_CAREER_RESET&&(m=s_oSpriteLibrary.getSprite("are_you_sure_panel"),b=createBitmap(m),b.regX=m.width/2,b.regY=m.height/2,d.addChild(b),e=new createjs.Text(c," 24px "+FONT,"#fff"),e.x=0,e.y=-70,e.textAlign="center",e.textBaseline="alphabetic",e.lineWidth=350,d.addChild(e),f=new CGfxButton(-160,80,s_oSpriteLibrary.getSprite("but_exit"),
d),f.addEventListener(ON_MOUSE_UP,this._onNoCareerReset,this),h=new CGfxButton(160,80,s_oSpriteLibrary.getSprite("but_yes"),d),h.addEventListener(ON_MOUSE_UP,this._onYesCareerReset,this));s_oStage.addChild(d);this.show()};this.show=function(){createjs.Tween.get(d).to({alpha:1},500)};this._onNo=function(){s_oGame.unloadVariousHelp(a)};this._onYes=function(){s_oGame.onExit()};this._onNoCareerReset=function(){s_oMenu.unloadVariousHelp()};this._onYesCareerReset=function(){s_oMenu.onContinue()};this._onClick=
function(){a===WAIT_FOR_GAME_START&&(s_oGame.unloadVariousHelp(a),s_oGame.startGame())};this.unload=function(){createjs.Tween.get(d).to({alpha:0},500).call(function(){s_oStage.removeChild(d)});if(a===CONFIRMATION_ON_EXIT||a===CONFIRMATION_ON_CAREER_RESET)f.unload(),h.unload();l.off("mousedown",this._onClick);s_oStage.removeChild(l)};this._init();s_oVariousHelp=this;return this}var s_oVariousHelp=null;
function CPodiumScreen(c){var a,b,d=0,g,k,e,l,f=[],h=s_oCityInfos.getPlayersArrivals(),m=[100,50,25,10,9,8,7,6],q=[0,1,2,3,4,5,6,7],n=[{x:CANVAS_WIDTH/2-215,y:CANVAS_HEIGHT/2-80},{x:CANVAS_WIDTH/2-322,y:CANVAS_HEIGHT/2-56},{x:CANVAS_WIDTH/2-108,y:CANVAS_HEIGHT/2-30}];this._init=function(){this.getRunnerInLane();this.addScoreToPlayers();this.findBestRunners();e=new createjs.Container;e.alpha=0;e.visible=!1;k=createBitmap(s_oSpriteLibrary.getSprite("bg_podium"));e.addChild(k);var c=new createjs.Shape;
c.graphics.beginFill("rgba(0,0,0,0.6)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e.addChild(c);c=createBitmap(s_oSpriteLibrary.getSprite("podium"));c.x=298;c.y=348;e.addChild(c);var f=createBitmap(s_oSpriteLibrary.getSprite("final_score"));f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-150;e.addChild(f);s_oStage.addChild(e);var g=s_oSpriteLibrary.getSprite("but_restart");a=CANVAS_WIDTH/2+150;b=CANVAS_HEIGHT-160;l=new CGfxButton(a,b,g,e);l.addEventListener(ON_MOUSE_UP,this._onContinue,this);for(c=0;3>c;c++)g=
s_oSpriteLibrary.getSprite("runner_"+q[c]+"_pose"),f=createBitmap(g),f.x=n[c].x,f.y=n[c].y,f.regX=g.width/2,f.regY=g.height/2,f.scaleX=f.scaleY=.85,s_oStage.addChild(f);for(c=0;c<q.length;c++)q[c]===s_iTeamSelected&&(f=new createjs.Text(c+1+TEXT_POSITION," 30px "+FONT,"#ffffff"),f.x=CANVAS_WIDTH/2+180,f.y=CANVAS_HEIGHT/2-90,f.textAlign="center",f.textBaseline="alphabetic",s_oStage.addChild(f),f=new createjs.Text(TEXT_SCORE+d," 30px "+FONT,"#ffffff"),f.x=CANVAS_WIDTH/2+20,f.y=CANVAS_HEIGHT/2-23,f.textAlign=
"left",f.textBaseline="alphabetic",s_oStage.addChild(f));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.show=function(){e.visible=!0;createjs.Tween.get(e).to({alpha:1},500).call(function(){});$(s_oMain).trigger("share_event",d);$(s_oMain).trigger("save_score",[d])};this.getRunnerInLane=function(){for(var a=0;a<h[0].length;a++)f.push(PLAYER_NAME_AND_SPRITE[h[c][a].player].sprite),f[a]===s_iTeamSelected&&(g=a)};this.addScoreToPlayers=function(){for(var a=0;a<h[c].length;a++)s_aRunnersScore[h[c][a].player]+=
m[h[c][a].position];d=s_aRunnersScore[h[c][g].player]};this.findBestRunners=function(){for(var a=[],b=0;b<s_aRunnersScore.length;b++)a[b]=s_aRunnersScore[b];var c;do for(c=!1,b=0;b<a.length;b++)a[b]<a[b+1]&&(c=a[b],a[b]=a[b+1],a[b+1]=c,c=q[b],q[b]=q[b+1],q[b+1]=c,c=!0);while(c)};this._onContinue=function(){s_oStage.removeChild(e);l.unload();s_oGame.onExit()};this.refreshButtonPos=function(c,d){l.setPosition(a,b-d)};this._init();return this}
function CCreditsPanel(){var c,a,b,d,g,k,e,l;this._init=function(){l=new createjs.Container;s_oStage.addChild(l);var f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));l.addChild(f);g=new createjs.Shape;g.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.addChild(g);f=s_oSpriteLibrary.getSprite("bg_credits");a=createBitmap(f);a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;a.regX=f.width/2;a.regY=f.height/2;l.addChild(a);k=new createjs.Shape;k.graphics.beginFill("#0f0f0f").drawRect(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=.01;k.on("click",this._onLogoButRelease);l.addChild(k);f=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH/2+100;b=new CGfxButton(c,124,f,l);b.addEventListener(ON_MOUSE_UP,this.unload,this);d=new CFormatText(CANVAS_WIDTH/2,350,TEXT_CREDITS_DEVELOPED,"#ffffff",l,"#410701",20);var f=s_oSpriteLibrary.getSprite("logo_credits"),h=createBitmap(f);h.regX=f.width/2;h.regY=f.height/2;h.x=CANVAS_WIDTH/2;h.y=400;l.addChild(h);e=new CFormatText(CANVAS_WIDTH/2,450,TEXT_LINK1,
"#ffffff",l,"#410701",16)};this.unload=function(){k.off("click",this._onLogoButRelease);b.unload();b=null;d.unload();e.unload();s_oStage.removeChild(l)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()}
function CFormatText(c,a,b,d,g,k,e){var l,f,h,m,q,n;this._init=function(a,b,c,d,e,g,k){l=c;m=new createjs.Container;m.x=a;m.y=b;e.addChild(m);a=k+"px";f=new createjs.Text;f.text=l;f.font="bold "+a+" "+FONT;f.color=g;f.textAlign="center";f.textBaseline="middle";f.lineWidth=600;f.outline=4;h=new createjs.Text;h.text=l;h.font="bold "+a+" "+FONT;h.color=d;h.textAlign="center";h.textBaseline="middle";h.lineWidth=600;m.addChild(h)};this.unload=function(){g.removeChild(m)};this.disableOutline=function(){m.removeChild(f)};
this.setVisible=function(a){m.visible=a};this.isVisible=function(){return m.visible};this.setOutline=function(a){f.outline=a};this.setShadow=function(a){f.shadow=a?new createjs.Shadow("#333333",2,2,6):null};this.setAlign=function(a){f.textAlign=a;h.textAlign=a};this.setWidth=function(a){f.lineWidth=a;h.lineWidth=a};this.setText=function(a){h.text=a;f.text=a};this.setColor=function(a,b){h.color=a;f.color=b};this.setFont=function(a){var b=e+"px";h.font="bold "+b+" "+a;f.font="bold "+b+" "+a};this.getText=
function(){return m};this.setPos=function(a){m.y=a};this.getPos=function(){return{x:m.x,y:m.y}};this.playText=function(){q="";this.setText("");this._slideText(0)};this._slideText=function(a){q+=b[a];this.setText(q);a<b.length-1&&setTimeout(function(){n._slideText(a+1)},40)};this.setPosition=function(a,b){m.x=a;m.y=b};n=this;this._init(c,a,b,d,g,k,e)}
function CArrivalPanel(c,a,b){var d,g,k,e,l,f,h,m;this._init=function(){d=c;g=a;h=new createjs.Container;h.x=d;h.y=g;h.visible=!1;m.addChild(h);var b=createBitmap(s_oSpriteLibrary.getSprite("arrival_panel"));h.addChild(b);k=new createjs.Text(""," 15px "+FONT,"#ffffff");k.x=10;k.y=20;k.textAlign="left";k.textBaseline="alphabetic";h.addChild(k);e=new createjs.Text(""," 12px "+FONT,"#ffffff");e.x=10;e.y=38;e.textAlign="left";e.textBaseline="alphabetic";h.addChild(e);l=new createjs.Text(TEXT_LANE+": ",
" 15px "+FONT,"#ffffff");l.x=230;l.y=20;l.textAlign="right";l.textBaseline="alphabetic";h.addChild(l);f=new createjs.Text(""," 15px "+FONT,"#ffffff");f.x=230;f.y=40;f.textAlign="right";f.textBaseline="alphabetic";h.addChild(f)};this.refreshButtonPos=function(a,b){h.visible&&(h.x=d-a,h.y=g+b)};this.show=function(a,b,c){var m="";switch(c){case 1:m=c+"st";break;case 2:m=c+"nd";break;case 3:m=c+"rd";break;case 4:case 5:case 6:case 7:case 8:m=c+"th"}c=b.lane+1;var t=b.name;b=b.time;k.text=m;l.text=TEXT_LANE+
": "+c;e.text=t;f.text=b;h.visible=!0;createjs.Tween.get(h).to({x:a},100,createjs.Ease.quadInOut).call(function(){d=h.x;g=h.y})};this.hide=function(a){createjs.Tween.get(h).to({x:a},300,createjs.Ease.quadInOut).call(function(){h.visible=!1})};this.getX=function(){return h.x};this.getY=function(){return h.y};m=b;this._init()};
