(function(b){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(b)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(b.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);function trace(b){console.log(b)}$(window).resize(function(){sizeHandler()});function isIOS(){for(var b="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");b.length;)if(navigator.platform===b.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function getParamValue(b){for(var d=window.location.search.substring(1).split("&"),a=0;a<d.length;a++){var c=d[a].split("=");if(c[0]==b)return c[1]}}
function getSize(b){var d=b.toLowerCase(),a=window.document,c=a.documentElement;if(void 0===window["inner"+b])b=c["client"+b];else if(window["inner"+b]!=c["client"+b]){var e=a.createElement("body");e.id="vpw-test-b";e.style.cssText="overflow:scroll";var g=a.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+d+":"+c["client"+b]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";e.appendChild(g);c.insertBefore(e,a.head);
b=7==g["offset"+b]?c["client"+b]:window["inner"+b];c.removeChild(e)}else b=window["inner"+b];return b}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var b=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<b?b:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var b;b=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width");_checkOrientation(d,b);var a=Math.min(b/CANVAS_HEIGHT,d/CANVAS_WIDTH),c=CANVAS_WIDTH*a,a=CANVAS_HEIGHT*a,e;a<b?(e=b-a,a+=e,c+=CANVAS_WIDTH/CANVAS_HEIGHT*e):c<d&&(e=d-c,c+=e,a+=CANVAS_HEIGHT/CANVAS_WIDTH*e);e=b/2-a/2;var g=d/2-c/2,f=CANVAS_WIDTH/c;if(g*f<-EDGEBOARD_X||e*f<-EDGEBOARD_Y)a=Math.min(b/(CANVAS_HEIGHT-2*EDGEBOARD_Y),
d/(CANVAS_WIDTH-2*EDGEBOARD_X)),c=CANVAS_WIDTH*a,a*=CANVAS_HEIGHT,e=(b-a)/2,g=(d-c)/2,f=CANVAS_WIDTH/c;s_iOffsetX=-1*g*f;s_iOffsetY=-1*e*f;0<=e&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile?($("#canvas").css("width",c+"px"),$("#canvas").css("height",a+"px")):(s_oStage.canvas.width=c,s_oStage.canvas.height=
a,s_oStage.scaleX=s_oStage.scaleY=Math.min(c/CANVAS_WIDTH,a/CANVAS_HEIGHT));0>e?$("#canvas").css("top",e+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",g+"px")}}
function _checkOrientation(b,d){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(b>d?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(b){return!0}}function createBitmap(b,d,a){var c=new createjs.Bitmap(b),e=new createjs.Shape;d&&a?e.graphics.beginFill("#fff").drawRect(0,0,d,a):e.graphics.beginFill("#ff0").drawRect(0,0,b.width,b.height);c.hitArea=e;return c}function createSprite(b,d,a,c,e,g){b=null!==d?new createjs.Sprite(b,d):new createjs.Sprite(b);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-a,-c,e,g);b.hitArea=d;return b}
function randomFloatBetween(b,d,a){"undefined"===typeof a&&(a=2);return parseFloat(Math.min(b+Math.random()*(d-b),d).toFixed(a))}function rotateVector2D(b,d){var a=d.getX()*Math.cos(b)+d.getY()*Math.sin(b),c=d.getX()*-Math.sin(b)+d.getY()*Math.cos(b);d.set(a,c)}function tweenVectorsOnX(b,d,a){return b+a*(d-b)}function shuffle(b){for(var d=b.length,a,c;0!==d;)c=Math.floor(Math.random()*d),--d,a=b[d],b[d]=b[c],b[c]=a;return b}
function bubbleSort(b){var d;do{d=!1;for(var a=0;a<b.length-1;a++)b[a]>b[a+1]&&(d=b[a],b[a]=b[a+1],b[a+1]=d,d=!0)}while(d)}function compare(b,d){return b.index>d.index?-1:b.index<d.index?1:0}function easeLinear(b,d,a,c){return a*b/c+d}function easeInQuad(b,d,a,c){return a*(b/=c)*b+d}function easeInSine(b,d,a,c){return-a*Math.cos(b/c*(Math.PI/2))+a+d}function easeInCubic(b,d,a,c){return a*(b/=c)*b*b+d}
function getTrajectoryPoint(b,d){var a=new createjs.Point,c=(1-b)*(1-b),e=b*b;a.x=c*d.start.x+2*(1-b)*b*d.traj.x+e*d.end.x;a.y=c*d.start.y+2*(1-b)*b*d.traj.y+e*d.end.y;return a}function formatTime(b){b/=1E3;var d=Math.floor(b/60);b=Math.floor(b-60*d);var a="",a=10>d?a+("0"+d+":"):a+(d+":");return 10>b?a+("0"+b):a+b}function degreesToRadians(b){return b*Math.PI/180}function checkRectCollision(b,d){var a,c;a=getBounds(b,.9);c=getBounds(d,.98);return calculateIntersection(a,c)}
function calculateIntersection(b,d){var a,c,e,g,f,h,k,l;a=b.x+(e=b.width/2);c=b.y+(g=b.height/2);f=d.x+(h=d.width/2);k=d.y+(l=d.height/2);a=Math.abs(a-f)-(e+h);c=Math.abs(c-k)-(g+l);return 0>a&&0>c?(a=Math.min(Math.min(b.width,d.width),-a),c=Math.min(Math.min(b.height,d.height),-c),{x:Math.max(b.x,d.x),y:Math.max(b.y,d.y),width:a,height:c,rect1:b,rect2:d}):null}
function getBounds(b,d){var a={x:Infinity,y:Infinity,width:0,height:0};if(b instanceof createjs.Container){a.x2=-Infinity;a.y2=-Infinity;var c=b.children,e=c.length,g,f;for(f=0;f<e;f++)g=getBounds(c[f],1),g.x<a.x&&(a.x=g.x),g.y<a.y&&(a.y=g.y),g.x+g.width>a.x2&&(a.x2=g.x+g.width),g.y+g.height>a.y2&&(a.y2=g.y+g.height);Infinity==a.x&&(a.x=0);Infinity==a.y&&(a.y=0);Infinity==a.x2&&(a.x2=0);Infinity==a.y2&&(a.y2=0);a.width=a.x2-a.x;a.height=a.y2-a.y;delete a.x2;delete a.y2}else{var h,k;b instanceof createjs.Bitmap?
(e=b.sourceRect||b.image,f=e.width*d,h=e.height*d):b instanceof createjs.Sprite?b.spriteSheet._frames&&b.spriteSheet._frames[b.currentFrame]&&b.spriteSheet._frames[b.currentFrame].image?(e=b.spriteSheet.getFrame(b.currentFrame),f=e.rect.width,h=e.rect.height,c=e.regX,k=e.regY):(a.x=b.x||0,a.y=b.y||0):(a.x=b.x||0,a.y=b.y||0);c=c||0;f=f||0;k=k||0;h=h||0;a.regX=c;a.regY=k;e=b.localToGlobal(0-c,0-k);g=b.localToGlobal(f-c,h-k);f=b.localToGlobal(f-c,0-k);c=b.localToGlobal(0-c,h-k);a.x=Math.min(Math.min(Math.min(e.x,
g.x),f.x),c.x);a.y=Math.min(Math.min(Math.min(e.y,g.y),f.y),c.y);a.width=Math.max(Math.max(Math.max(e.x,g.x),f.x),c.x)-a.x;a.height=Math.max(Math.max(Math.max(e.y,g.y),f.y),c.y)-a.y}return a}function NoClickDelay(b){this.element=b;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(b){for(var d=b.length,a,c;0<d;)c=Math.floor(Math.random()*d),d--,a=b[d],b[d]=b[c],b[c]=a;return b}
NoClickDelay.prototype={handleEvent:function(b){switch(b.type){case "touchstart":this.onTouchStart(b);break;case "touchmove":this.onTouchMove(b);break;case "touchend":this.onTouchEnd(b)}},onTouchStart:function(b){b.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(b){this.moved=!0},onTouchEnd:function(b){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){b=document.elementFromPoint(b.changedTouches[0].clientX,b.changedTouches[0].clientY);3==b.nodeType&&(b=b.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);b.dispatchEvent(d)}}};
(function(){function b(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",b):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",b):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",b):(d="msHidden")in document?document.addEventListener("msvisibilitychange",b):"onfocusin"in document?document.onfocusin=document.onfocusout=b:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=b})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function CSpriteLibrary(){var b,d,a,c,e,g;this.init=function(f,h,k){a=d=0;c=f;e=h;g=k;b={}};this.addSprite=function(a,c){b.hasOwnProperty(a)||(b[a]={szPath:c,oSprite:new Image},d++)};this.getSprite=function(a){return b.hasOwnProperty(a)?b[a].oSprite:null};this._onSpritesLoaded=function(){e.call(g)};this._onSpriteLoaded=function(){c.call(g);++a==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in b)b[a].oSprite.oSpriteLibrary=this,b[a].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
b[a].oSprite.src=b[a].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=640,CANVAS_HEIGHT=960,EDGEBOARD_X=80,EDGEBOARD_Y=80,FONT="rocks__gregular",FONT2="suplexmentary_comic_ncregular",LEVEL_NUM=10,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,START_X_GRID=100,START_Y_GRID=261,CELL_WIDTH=74,CELL_HEIGHT=74,STAR_WIDTH=80,STAR_HEIGHT=80,NUM_ROWS=6,NUM_COLS=6,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,EASY_MODE=0,NORMAL_MODE=1,HARD_MODE=2,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;
TEXT_GAMEOVER="CONGRATULATIONS! YOU HAVE COMPLETED ALL THE LEVELS!\nYOUR TOTAL SCORE IS: ";TEXT_SCORE="\nYOU USED: ";TEXT_PAUSE="PAUSE";TEXT_MOVES="MOVES";TEXT_NEXT_LEVEL="CONGRATULATIONS! YOU MOVE TO THE NEXT LEVEL!";TEXT_SELECT_LEVEL="SELECT LEVEL";TEXT_SCORE="SCORE";TEXT_LEVEL="Lvl";TEXT_YOUR_SCORE="YOUR SCORE IS";TEXT_MOVES_OUT="MOVES OUT OF";TEXT_HELP="Get the cart full of gold out of the mine by sliding those filled with rocks out of the way";TEXT_DEVELOPED="DEVELOPED BY";TEXT_SHARE_IMAGE="200x200.jpg";
TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var b,d,a,c,e,g,f;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();f=new createjs.Container;s_oStage.addChild(f)};this.unload=function(){f.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));f.addChild(h);h=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(h);c.x=CANVAS_WIDTH/2-h.width/2;c.y=CANVAS_HEIGHT-250;f.addChild(c);b=h.width;d=h.height;e=new createjs.Shape;e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,d);f.addChild(e);c.mask=
e;a=new createjs.Text("","30px Arial","#fff");a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT-250;a.shadow=new createjs.Shadow("#000",2,2,2);a.textBaseline="alphabetic";a.textAlign="center";f.addChild(a);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;f.addChild(g)};this.refreshLoader=function(f){a.text=f+"%";e.graphics.clear();f=Math.floor(f*b/100);e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,f,d)};this._init()}
function CMain(b){var d,a=0,c=0,e=STATE_LOADING,g,f,h;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;f=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();d=!0};this.soundLoaded=function(){a++;f.refreshLoader(Math.floor(a/c*100));a===c&&this._onRemovePreloader()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/cart.ogg","cart"),createjs.Sound.registerSound("./sounds/cart_exit.ogg","cart_exit"),createjs.Sound.registerSound("./sounds/press_but.ogg","click"),createjs.Sound.registerSound("./sounds/stage_clear.ogg","stage_clear")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3",
"soundtrack"),createjs.Sound.registerSound("./sounds/cart.mp3","cart"),createjs.Sound.registerSound("./sounds/cart_exit.mp3","cart_exit"),createjs.Sound.registerSound("./sounds/press_but.mp3","click"),createjs.Sound.registerSound("./sounds/stage_clear.mp3","stage_clear")),c+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_play_small","./sprites/but_play_small.png");
s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("msg_box_2","./sprites/msg_box_2.png");s_oSpriteLibrary.addSprite("level_sprite","./sprites/LevelSprite.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("balloon_1","./sprites/balloon_1.png");s_oSpriteLibrary.addSprite("balloon_2","./sprites/balloon_2.png");
s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("player","./sprites/player.png");s_oSpriteLibrary.addSprite("horizzontal_3","./sprites/horizzontal_3.png");s_oSpriteLibrary.addSprite("vertical_3","./sprites/vertical_3.png");s_oSpriteLibrary.addSprite("horizzontal_2","./sprites/horizzontal_2.png");s_oSpriteLibrary.addSprite("vertical_2",
"./sprites/vertical_2.png");s_oSpriteLibrary.addSprite("star_filled","./sprites/star_filled.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){a++;f.refreshLoader(Math.floor(a/c*100));a===c&&this._onRemovePreloader()};this._onAllImagesLoaded=
function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._onRemovePreloader=function(){f.unload();isIOS()||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1}));this.gotoMenu()};this.gotoMenu=function(){new CMenu;e=STATE_MENU};this.gotoLevelMenu=function(){new CLevelMenu;e=STATE_MENU};this.gotoGame=function(a,b){h=new CGame(g,a,b);e=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelpPanel(s_oSpriteLibrary.getSprite("msg_box_2"));
e=STATE_HELP};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=
1E3,s_iCntFps=0);e===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;g=b;ENABLE_CHECK_ORIENTATION=b.check_orientation;ENABLE_FULLSCREEN=b.fullscreen;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iLevelReached=1,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack=null,s_oCanvas,s_bFullscreen=!1;
function CTextButton(b,d,a,c,e,g,f){var h,k,l,m,r;this._init=function(a,b,c,d,e,f,g){h=[];k=[];var n=createBitmap(c),v=Math.ceil(g/20);r=new createjs.Text(d,"bold "+g+"px "+e,"#000000");r.textAlign="center";r.textBaseline="alphabetic";var p=r.getBounds();r.x=c.width/2+v;r.y=Math.floor(c.height/2)+p.height/3+v;m=new createjs.Text(d,"bold "+g+"px "+e,f);m.textAlign="center";m.textBaseline="alphabetic";p=m.getBounds();m.x=c.width/2;m.y=Math.floor(c.height/2)+p.height/3;l=new createjs.Container;l.x=a;
l.y=b;l.regX=c.width/2;l.regY=c.height/2;l.addChild(n,r,m);s_bMobile||(l.cursor="pointer");s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;k[a]=c};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};
this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setTextPosition=function(a){m.y=a;r.y=a+2};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(b,d,a,c,e,g,f);return this}
function CToggle(b,d,a,c){var e,g,f,h=[],k;this._init=function(a,b,c,d){g=[];f=[];var h=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});e=d;k=createSprite(h,"state_"+e,c.width/2/2,c.height/2,c.width/2,c.height);k.x=a;k.y=b;k.stop();s_bMobile||(k.cursor="pointer");s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);
s_oStage.removeChild(k)};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;f[a]=c};this.addEventListenerWithParams=function(a,b,c,d){g[a]=b;f[a]=c;h=d};this.setActive=function(a){e=a;k.gotoAndStop("state_"+e)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");e=!e;k.gotoAndStop("state_"+e);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(f[ON_MOUSE_UP],
h)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],h)};this.setPosition=function(a,b){k.x=a;k.y=b};this.setVisible=function(a){k.visible=a};this._init(b,d,a,c)}
function CGfxButton(b,d,a){var c,e,g,f=[],h;this._init=function(a,b,d){c=1;e=[];g=[];h=createBitmap(d);h.x=a;h.y=b;h.regX=d.width/2;h.regY=d.height/2;s_bMobile||(h.cursor="pointer");s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);s_oStage.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=
function(a,b,c){e[a]=b;g[a]=c};this.addEventListenerWithParams=function(a,b,c,d){e[a]=b;g[a]=c;f=d};this.buttonRelease=function(){h.scaleX=c;h.scaleY=c;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(g[ON_MOUSE_UP],f)};this.buttonDown=function(){h.scaleX=.9*c;h.scaleY=.9*c;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],f)};this.setScale=function(a){c=a;h.scaleX=a;h.scaleY=a};this.setPosition=function(a,b){h.x=a;h.y=b};this.setX=
function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(b,d,a);return this}
function CMenu(){var b,d,a,c,e,g,f,h,k,l,m,r,p=null,v=null;this._init=function(){f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(f);var n=s_oSpriteLibrary.getSprite("but_play");h=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-225,n);h.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n=s_oSpriteLibrary.getSprite("audio_icon"),e=CANVAS_WIDTH-n.height/2-10,g=n.height/2+10,l=new CToggle(e,g,n,s_bAudioActive),l.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);n=s_oSpriteLibrary.getSprite("but_credits");a=n.height/2+10;c=n.height/2+10;m=new CGfxButton(a,c,n,s_oStage);m.addEventListener(ON_MOUSE_UP,this._onButInfoRelease,this);var n=window.document,t=n.documentElement;p=t.requestFullscreen||t.mozRequestFullScreen||t.webkitRequestFullScreen||t.msRequestFullscreen;v=n.exitFullscreen||n.mozCancelFullScreen||n.webkitExitFullscreen||n.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(p=!1);p&&!1===inIframe()&&(n=s_oSpriteLibrary.getSprite("but_fullscreen"),
b=a+n.width/2+10,d=n.height/2+10,r=new CToggle(b,d,n,s_bFullscreen,s_oStage),r.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(k);createjs.Tween.get(k).to({alpha:0},1E3).call(function(){k.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){h.unload();h=null;k.visible=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;p&&!1===inIframe()&&
r.unload();m.unload();s_oStage.removeAllChildren();s_oMenu=null};this.refreshButtonPos=function(f,h){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(e-f,h+g);p&&!1===inIframe()&&r.setPosition(b+f,d+h);m.setPosition(a+f,c+h)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!isIOS()||null!==s_oSoundtrack||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundtrack=createjs.Sound.play("soundtrack",
{loop:-1}));s_oMain.gotoLevelMenu();$(s_oMain).trigger("start_session")};this._onButInfoRelease=function(){new CCreditsPanel};this._onFullscreenRelease=function(){s_bFullscreen?(v.call(window.document),s_bFullscreen=!1):(p.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(b,d,a){var c,e,g,f,h,k,l=0,m=0,r,p,v,n=null,t=!1,A=!1,w=!1,B=!1,E=!1,F=!1,C,x,q=[],u=[],y=0;this._init=function(){$(s_oMain).trigger("start_level",d);var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);C=new CLevel;x=C.getLevel(d);r=C.getGoalInLevel(d);v=new CInterface(r,d+1,m);q=[];for(a=0;a<NUM_ROWS;a++){q[a]=[];for(var b=0;b<NUM_COLS;b++)q[a][b]=0}for(y=0;y<x.length;y++)u.push(new CBlocks(x[y].obj_x,x[y].obj_y,x[y].obj_type,y)),this._updateGrid(x[y].obj_x,
x[y].obj_y,x[y].obj_type)};this._updateGrid=function(a,b,c){switch(c){case "player":case "horizzontal_2":q[a][b]=1;q[a+1][b]=1;break;case "horizzontal_3":q[a][b]=1;q[a+1][b]=1;q[a+2][b]=1;break;case "vertical_2":q[a][b]=1;q[a][b+1]=1;break;case "vertical_3":q[a][b]=1,q[a][b+1]=1,q[a][b+2]=1}};this._unloadFromGrid=function(a,b,c){switch(u[c].getType()){case "player":case "horizzontal_2":q[a][b]=0;q[a+1][b]=0;break;case "horizzontal_3":q[a][b]=0;q[a+1][b]=0;q[a+2][b]=0;break;case "vertical_2":q[a][b]=
0;q[a][b+1]=0;break;case "vertical_3":q[a][b]=0,q[a][b+1]=0,q[a][b+2]=0}};this.onFormContainerClick=function(a,b,d){g=b.x;f=b.y;var n=Math.round((b.x-START_X_GRID)/CELL_WIDTH),v=Math.round((b.y-START_Y_GRID)/CELL_HEIGHT);h=b.x;k=b.y;c=a.stageX-g;e=a.stageY-f;this._unloadFromGrid(n,v,d)};this.dragForm=function(a,b,d){var f=Math.round((a.stageX-c-START_X_GRID)/CELL_WIDTH),g=Math.round((a.stageY-e-START_Y_GRID)/CELL_HEIGHT);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||F||(p=createjs.Sound.play("cart",
{loop:-1}),p.volume=.5,F=!0);switch(b){case "player":case "horizzontal_2":a.stageX-c>START_X_GRID&&a.stageX-c<START_X_GRID+(4*CELL_WIDTH+10)&&(h<=a.stageX-c?0===q[f+1][g]&&!1===t?(u[d].setPos(a.stageX-c,u[d].getPosY()),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:.5},100,createjs.Ease.cubicIn)):(t=!0,A=!1,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:0},100,createjs.Ease.cubicIn)):0===q[f][g]&&!1===A?(u[d].setPos(a.stageX-
c,u[d].getPosY()),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:.5},100,createjs.Ease.cubicIn)):(A=!0,t=!1,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:0},100,createjs.Ease.cubicIn)));break;case "horizzontal_3":a.stageX-c>START_X_GRID&&a.stageX-c<START_X_GRID+(3*CELL_WIDTH+10)&&(h<=a.stageX-c?0===q[f+2][g]&&!1===t?(u[d].setPos(a.stageX-c,u[d].getPosY()),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,
{override:!0}).to({volume:.5},100,createjs.Ease.cubicIn)):(t=!0,A=!1,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:0},100,createjs.Ease.cubicIn)):0===q[f][g]&&!1===A?(u[d].setPos(a.stageX-c,u[d].getPosY()),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:.5},100,createjs.Ease.cubicIn)):(A=!0,t=!1,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:0},100,createjs.Ease.cubicIn)));
break;case "vertical_2":a.stageY-e>START_Y_GRID&&a.stageY-e<START_Y_GRID+(4*CELL_HEIGHT+10)&&(k<=a.stageY-e?0===q[f][g+1]&&!1===w?(u[d].setPos(u[d].getPosX(),a.stageY-e),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:.5},100,createjs.Ease.cubicIn)):(w=!0,B=!1,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:0},100,createjs.Ease.cubicIn)):0===q[f][g]&&!1===B?(u[d].setPos(u[d].getPosX(),a.stageY-e),!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:.5},100,createjs.Ease.cubicIn)):(B=!0,w=!1,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:0},100,createjs.Ease.cubicIn)));break;case "vertical_3":a.stageY-e>START_Y_GRID&&a.stageY-e<START_Y_GRID+(3*CELL_HEIGHT+10)&&(k<=a.stageY-e?0===q[f][g+2]&&!1===w?(u[d].setPos(u[d].getPosX(),a.stageY-e),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:.5},100,createjs.Ease.cubicIn)):
(w=!0,B=!1,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:0},100,createjs.Ease.cubicIn)):0===q[f][g]&&!1===B?(u[d].setPos(u[d].getPosX(),a.stageY-e),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:.5},100,createjs.Ease.cubicIn)):(B=!0,w=!1,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:0},100,createjs.Ease.cubicIn)))}};this.releaseForm=function(a,b,c,f){B=w=A=t=!1;var e=
u[f].getPosX(),g=u[f].getPosY(),n=0,v=0;a=Math.round((e-START_X_GRID)/CELL_WIDTH);b=Math.round((g-START_Y_GRID)/CELL_HEIGHT);switch(c){case "player":case "horizzontal_2":n=2;break;case "horizzontal_3":n=3;break;case "vertical_2":v=2;break;case "vertical_3":v=3}if(!0===this.checkPieceIfFitInPos(a,b,n,v)){if(e="vertical_2"===c||"vertical_3"===c?START_X_GRID+CELL_WIDTH*a-12:START_X_GRID+CELL_WIDTH*a-5,g=START_Y_GRID+CELL_HEIGHT*b-5,u[f].placeInGrid(e,g),e=Math.round((k-START_Y_GRID)/CELL_HEIGHT),Math.round((h-
START_X_GRID)/CELL_WIDTH)!==a||e!==b)l++,m=l<=r?m+5*(d+1):m-6*d,this._refreshScore()}else e=u[f].getOldX(),g=u[f].getOldY(),a=Math.round((e-START_X_GRID)/CELL_WIDTH),b=Math.round((g-START_Y_GRID)/CELL_HEIGHT),u[f].goBack(e,g);this._updateGrid(a,b,c);"player"===c&&(e=u[f].getOldX(),a=Math.round((e-START_X_GRID)/CELL_WIDTH),4===a&&(u[f].moveOut(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("cart_exit")));!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Tween.get(p,{override:!0}).to({volume:0},
100,createjs.Ease.cubicIn)};this.checkPieceIfFitInPos=function(a,b,c,d){var f=!0;if(0<c)for(var e=0;e<c;e++){if(0!==q[e+a][b]){f=!1;break}}else if(0<d)for(e=0;e<d;e++)if(0!==q[a][e+b]){f=!1;break}return f};this._refreshScore=function(){v.refreshMoves(l,r);v.refreshScore(m)};this.unload=function(){v.unload();null!==n&&n.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu();d<LEVEL_NUM-1&&$(s_oMain).trigger("end_level",d);$(s_oMain).trigger("show_interlevel_ad");
$(s_oMain).trigger("end_session");$(s_oMain).trigger("save_score",a);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack.volume=1};this.onExitEndPanel=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session");$(s_oMain).trigger("save_score",a);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack.volume=1};this.onRestart=function(){for(var a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_COLS;b++)q[a][b]=0;for(var c=0;c<y;c++)a="vertical_2"===
x[c].obj_type||"vertical_3"===x[c].obj_type?START_X_GRID+CELL_WIDTH*x[c].obj_x-12:START_X_GRID+CELL_WIDTH*x[c].obj_x-5,b=START_Y_GRID+CELL_HEIGHT*x[c].obj_y-5,u[c].placeInGrid(a,b),this._updateGrid(x[c].obj_x,x[c].obj_y,x[c].obj_type);m=l=0;this._refreshScore();$(s_oMain).trigger("restart_level",d);$(s_oMain).trigger("show_interlevel_ad")};this.onNextLevel=function(b){d+1===LEVEL_NUM?(E=!0,this.gameOver()):(this.unload(),s_iLevelReached=d+2,s_oMain.gotoGame(d+1,b+a));if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)s_oSoundtrack.volume=1;$(s_oMain).trigger("restart")};this.gameOver=function(){E?($(s_oMain).trigger("end_level",d),n=CEndPanel(s_oSpriteLibrary.getSprite("msg_box_2")),n.show(d+1,m+a)):($(s_oMain).trigger("end_level",d),n=CEndPanel(s_oSpriteLibrary.getSprite("msg_box_2")),n.nextLevel(l,d+1,r,m))};this.update=function(){};s_oGame=this;this._init()}var s_oGame;
function CInterface(b,d,a){var c,e,g,f,h,k,l,m,r,p,v,n,t=null,A=null,w,B,E=CANVAS_WIDTH/2+50,F=CANVAS_HEIGHT-100,C,x,q=CANVAS_WIDTH/2-290,u=CANVAS_HEIGHT-100,y,D,G=CANVAS_WIDTH/2-290;this._init=function(a,b,d){var z=s_oSpriteLibrary.getSprite("but_exit");l=CANVAS_WIDTH-z.height/2;m=z.height/2+10;p=new CGfxButton(l,m,z,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onExit,this);z=s_oSpriteLibrary.getSprite("but_restart");c=l-z.width;e=z.height/2+10;v=new CGfxButton(c,e,z,s_oStage);v.addEventListener(ON_MOUSE_UP,
this._onRestart,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(z=s_oSpriteLibrary.getSprite("audio_icon"),h=c-z.width/2,k=z.height/2+10,r=new CToggle(h,k,z,s_bAudioActive),r.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),g=h-z.width/2):g=c-z.width/2;f=z.height/2+10;var z=window.document,H=z.documentElement;t=H.requestFullscreen||H.mozRequestFullScreen||H.webkitRequestFullScreen||H.msRequestFullscreen;A=z.exitFullscreen||z.mozCancelFullScreen||z.webkitExitFullscreen||z.msExitFullscreen;!1===
ENABLE_FULLSCREEN&&(t=!1);t&&!1===inIframe()&&(z=s_oSpriteLibrary.getSprite("but_fullscreen"),n=new CToggle(g,f,z,s_bFullscreen,s_oStage),n.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));B=new createjs.Text(TEXT_MOVES+": 0/"+a," 40px "+FONT,"#000000");B.x=E;B.y=F;B.textAlign="left";B.textBaseline="alphabetic";B.lineWidth=650;B.outline=8;s_oStage.addChild(B);w=new createjs.Text(TEXT_MOVES+": 0/"+a," 40px "+FONT,"#ffc600");w.x=E;w.y=F;w.textAlign="left";w.textBaseline="alphabetic";w.lineWidth=
650;s_oStage.addChild(w);x=new createjs.Text(TEXT_SCORE+": "+d," 40px "+FONT,"#000000");x.x=q;x.y=u;x.textAlign="left";x.textBaseline="alphabetic";x.lineWidth=650;x.outline=8;s_oStage.addChild(x);C=new createjs.Text(TEXT_SCORE+": "+d," 40px "+FONT,"#ffc600");C.x=q;C.y=u;C.textAlign="left";C.textBaseline="alphabetic";C.lineWidth=650;s_oStage.addChild(C);y=new createjs.Text(TEXT_LEVEL+": "+b," 30px "+FONT,"#000000");y.x=G;y.y=40;y.textAlign="left";y.textBaseline="alphabetic";y.lineWidth=650;y.outline=
8;s_oStage.addChild(y);D=new createjs.Text(TEXT_LEVEL+": "+b," 30px "+FONT,"#ffc600");D.x=G;D.y=40;D.textAlign="left";D.textBaseline="alphabetic";D.lineWidth=650;s_oStage.addChild(D);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshMoves=function(a,b){B.text="MOVES: "+a+"/"+b;w.text="MOVES: "+a+"/"+b};this.refreshScore=function(a){x.text="SCORE: "+a;C.text="SCORE: "+a};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r.unload(),r=null;t&&!1===inIframe()&&n.unload();p.unload();
v.unload();s_oInterface=null};this.refreshButtonPos=function(a,b){p.setPosition(l-a,b+m);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.setPosition(h-a,b+k);t&&!1===inIframe()&&n.setPosition(g-a,f+b);v.setPosition(c-a,b+e);B.x=E-a;w.x=E-a;x.x=q+a;C.x=q+a;y.x=G+a;D.x=G+a;y.y=40+b;D.y=40+b};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};this._onRestart=function(){s_oGame.onRestart()};this._onFullscreenRelease=
function(){s_bFullscreen?(A.call(window.document),s_bFullscreen=!1):(t.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oInterface=this;this._init(b,d,a);return this}var s_oInterface=null;
function CEndPanel(b){var d,a,c,e,g,f,h,k,l,m,r=CANVAS_WIDTH/2-150,p=CANVAS_HEIGHT/2-120;this._init=function(b){a=createBitmap(b);a.x=0;a.y=0;c=new createjs.Container;c.alpha=0;c.visible=!1;f=createBitmap(s_oSpriteLibrary.getSprite("star_filled"));f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-60;f.regX=STAR_WIDTH/2;f.regY=STAR_HEIGHT/2;f.scaleX=.1;f.scaleY=.1;f.visible=!1;h=createBitmap(s_oSpriteLibrary.getSprite("star_filled"));h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2-60;h.regX=STAR_WIDTH/2;h.regY=STAR_HEIGHT/
2;h.scaleX=.1;h.scaleY=.1;h.visible=!1;k=createBitmap(s_oSpriteLibrary.getSprite("star_filled"));k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2-60;k.regX=STAR_WIDTH/2;k.regY=STAR_HEIGHT/2;k.scaleX=.1;k.scaleY=.1;k.visible=!1;c.addChild(a,g,e,f,h,k);s_oStage.addChild(c)};this.unload=function(){c.off("mousedown",this._onExit)};this.show=function(a,b){d=b;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.play("stage_clear"),s_oSoundtrack.volume=0;e=new CComic(CANVAS_WIDTH/2-10,CANVAS_HEIGHT/2-60,c,
TEXT_GAMEOVER+b,2);c.visible=!0;var f=s_oSpriteLibrary.getSprite("but_restart");l=new CGfxButton(CANVAS_WIDTH/2-40,CANVAS_HEIGHT/2+110,f);var g=this;createjs.Tween.get(c).to({alpha:1},500).call(function(){l.addEventListener(ON_MOUSE_DOWN,g._onExit,this)});$(s_oMain).trigger("share_event",b);$(s_oMain).trigger("save_score",b)};this.nextLevel=function(a,b,t,A){d=A;m=new createjs.Text(TEXT_YOUR_SCORE+": "+A," 40px "+FONT,"#000000");m.x=r;m.y=p;m.textAlign="left";m.textBaseline="alphabetic";m.lineWidth=
650;m.outline=8;s_oStage.addChild(m);g=new createjs.Text(TEXT_YOUR_SCORE+": "+A," 40px "+FONT,"#ffc600");g.x=r;g.y=p;g.textAlign="left";g.textBaseline="alphabetic";g.lineWidth=650;s_oStage.addChild(g);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.play("stage_clear"),s_oSoundtrack.volume=0;e=new CComic(CANVAS_WIDTH/2-50,CANVAS_HEIGHT/2+180,c,TEXT_NEXT_LEVEL+TEXT_SCORE+" "+a+" "+TEXT_MOVES_OUT+" "+t,1);var n=s_oSpriteLibrary.getSprite("but_play_small");l=new CGfxButton(CANVAS_WIDTH/2+
160,CANVAS_HEIGHT-270,n);a>=t+5?(f.visible=!0,createjs.Tween.get(f).wait(500).to({scaleX:1,scaleY:1},500,createjs.Ease.bounceOut).call(function(){l.addEventListener(ON_MOUSE_DOWN,v._onNextLevel,this)})):a>=t+2?(f.visible=!0,createjs.Tween.get(f).wait(500).to({scaleX:1,scaleY:1},500,createjs.Ease.bounceOut).call(function(){h.visible=!0;createjs.Tween.get(f).to({x:CANVAS_WIDTH/2-40,y:CANVAS_HEIGHT/2-55,rotation:-20},250,createjs.Ease.linear).call(function(){});createjs.Tween.get(h).to({scaleX:1,scaleY:1,
x:CANVAS_WIDTH/2+40,y:CANVAS_HEIGHT/2-55,rotation:20},500,createjs.Ease.bounceOut).call(function(){l.addEventListener(ON_MOUSE_DOWN,v._onNextLevel,this)})})):a<t+2&&(f.visible=!0,createjs.Tween.get(f).wait(500).to({scaleX:1,scaleY:1,rotation:0},500,createjs.Ease.bounceOut).call(function(){h.visible=!0;createjs.Tween.get(f).to({x:CANVAS_WIDTH/2-40,y:CANVAS_HEIGHT/2-55,rotation:-20},250,createjs.Ease.linear).call(function(){});createjs.Tween.get(h).to({scaleX:1,scaleY:1,x:CANVAS_WIDTH/2+40,y:CANVAS_HEIGHT/
2-55,rotation:20},500,createjs.Ease.bounceOut).call(function(){k.visible=!0;createjs.Tween.get(f).to({x:CANVAS_WIDTH/2-75,y:CANVAS_HEIGHT/2-50},250,createjs.Ease.linear).call(function(){});createjs.Tween.get(h).to({x:CANVAS_WIDTH/2+75,y:CANVAS_HEIGHT/2-50},250,createjs.Ease.linear).call(function(){});createjs.Tween.get(k).to({scaleX:1,scaleY:1,x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2-60},700,createjs.Ease.bounceOut).call(function(){l.addEventListenerWithParams(ON_MOUSE_DOWN,v._onNextLevel,this,b)})})}));
c.visible=!0;var v=this;createjs.Tween.get(c).to({alpha:1},500).call(function(){});$(s_oMain).trigger("share_event",A)};this._onExit=function(){c.off("mousedown",this._onExit);s_oStage.removeChild(c);l.unload();s_oGame.onExitEndPanel()};this._onNextLevel=function(a){c.off("mousedown",this._onNextLevel);s_oStage.removeChild(c);s_oGame.onNextLevel(d)};this._init(b);return this}
function CLevel(b){var d=[],a=[],c=[];this._init=function(){a[0]=[];a[0].push({obj_x:4,obj_y:0,obj_type:"vertical_3"});a[0].push({obj_x:3,obj_y:3,obj_type:"vertical_2"});a[0].push({obj_x:4,obj_y:4,obj_type:"horizzontal_2"});a[0].push({obj_x:2,obj_y:2,obj_type:"player"});c.push(5);d[0]=a[0];a[1]=[];a[1].push({obj_x:0,obj_y:0,obj_type:"vertical_2"});a[1].push({obj_x:5,obj_y:0,obj_type:"vertical_3"});a[1].push({obj_x:4,obj_y:3,obj_type:"horizzontal_2"});a[1].push({obj_x:2,obj_y:4,obj_type:"vertical_2"});
a[1].push({obj_x:3,obj_y:5,obj_type:"horizzontal_3"});a[1].push({obj_x:0,obj_y:2,obj_type:"player"});c.push(5);d[1]=a[1];a[2]=[];a[2].push({obj_x:2,obj_y:0,obj_type:"vertical_3"});a[2].push({obj_x:5,obj_y:1,obj_type:"vertical_2"});a[2].push({obj_x:1,obj_y:3,obj_type:"vertical_2"});a[2].push({obj_x:2,obj_y:4,obj_type:"horizzontal_2"});a[2].push({obj_x:4,obj_y:3,obj_type:"vertical_3"});a[2].push({obj_x:0,obj_y:2,obj_type:"player"});c.push(12);d[2]=a[2];a[3]=[];a[3].push({obj_x:2,obj_y:0,obj_type:"horizzontal_3"});
a[3].push({obj_x:2,obj_y:1,obj_type:"vertical_2"});a[3].push({obj_x:5,obj_y:0,obj_type:"vertical_3"});a[3].push({obj_x:2,obj_y:4,obj_type:"horizzontal_2"});a[3].push({obj_x:4,obj_y:4,obj_type:"horizzontal_2"});a[3].push({obj_x:0,obj_y:2,obj_type:"player"});c.push(5);d[3]=a[3];a[4]=[];a[4].push({obj_x:2,obj_y:0,obj_type:"vertical_3"});a[4].push({obj_x:0,obj_y:4,obj_type:"vertical_2"});a[4].push({obj_x:1,obj_y:4,obj_type:"horizzontal_2"});a[4].push({obj_x:4,obj_y:3,obj_type:"vertical_3"});a[4].push({obj_x:0,
obj_y:2,obj_type:"player"});c.push(11);d[4]=a[4];a[5]=[];a[5].push({obj_x:2,obj_y:0,obj_type:"vertical_2"});a[5].push({obj_x:2,obj_y:2,obj_type:"vertical_3"});a[5].push({obj_x:0,obj_y:5,obj_type:"horizzontal_3"});a[5].push({obj_x:5,obj_y:3,obj_type:"vertical_3"});a[5].push({obj_x:0,obj_y:2,obj_type:"player"});c.push(8);d[5]=a[5];a[6]=[];a[6].push({obj_x:2,obj_y:1,obj_type:"horizzontal_2"});a[6].push({obj_x:4,obj_y:0,obj_type:"vertical_2"});a[6].push({obj_x:4,obj_y:2,obj_type:"vertical_2"});a[6].push({obj_x:5,
obj_y:0,obj_type:"vertical_3"});a[6].push({obj_x:4,obj_y:4,obj_type:"horizzontal_2"});a[6].push({obj_x:3,obj_y:4,obj_type:"vertical_2"});a[6].push({obj_x:2,obj_y:3,obj_type:"vertical_3"});a[6].push({obj_x:2,obj_y:2,obj_type:"player"});c.push(9);d[6]=a[6];a[7]=[];a[7].push({obj_x:3,obj_y:0,obj_type:"vertical_2"});a[7].push({obj_x:3,obj_y:2,obj_type:"vertical_2"});a[7].push({obj_x:4,obj_y:2,obj_type:"vertical_2"});a[7].push({obj_x:4,obj_y:0,obj_type:"horizzontal_2"});a[7].push({obj_x:5,obj_y:1,obj_type:"vertical_3"});
a[7].push({obj_x:0,obj_y:4,obj_type:"vertical_2"});a[7].push({obj_x:1,obj_y:4,obj_type:"horizzontal_3"});a[7].push({obj_x:4,obj_y:4,obj_type:"vertical_2"});a[7].push({obj_x:0,obj_y:2,obj_type:"player"});c.push(10);d[7]=a[7];a[8]=[];a[8].push({obj_x:1,obj_y:1,obj_type:"vertical_2"});a[8].push({obj_x:1,obj_y:0,obj_type:"horizzontal_2"});a[8].push({obj_x:3,obj_y:0,obj_type:"vertical_2"});a[8].push({obj_x:4,obj_y:0,obj_type:"horizzontal_2"});a[8].push({obj_x:5,obj_y:1,obj_type:"vertical_3"});a[8].push({obj_x:4,
obj_y:1,obj_type:"vertical_2"});a[8].push({obj_x:4,obj_y:3,obj_type:"vertical_3"});a[8].push({obj_x:2,obj_y:3,obj_type:"vertical_2"});a[8].push({obj_x:0,obj_y:3,obj_type:"horizzontal_2"});a[8].push({obj_x:2,obj_y:2,obj_type:"player"});c.push(11);d[8]=a[8];a[9]=[];a[9].push({obj_x:0,obj_y:0,obj_type:"horizzontal_2"});a[9].push({obj_x:2,obj_y:0,obj_type:"vertical_2"});a[9].push({obj_x:4,obj_y:0,obj_type:"horizzontal_2"});a[9].push({obj_x:4,obj_y:2,obj_type:"vertical_2"});a[9].push({obj_x:0,obj_y:4,
obj_type:"horizzontal_2"});a[9].push({obj_x:2,obj_y:4,obj_type:"horizzontal_3"});a[9].push({obj_x:5,obj_y:4,obj_type:"vertical_2"});a[9].push({obj_x:2,obj_y:2,obj_type:"player"});c.push(8);d[9]=a[9]};this.getLevel=function(a){return d[a]};this.getCellValueInLevel=function(a,b){return(void 0)[parseInt(d[a].charAt(b))]};this.getGoalInLevel=function(a){return c[a]};this.getGoalNumberInLevel=function(a){return(void 0)[a].length};this._init()}
function CBlocks(b,d,a,c){var e,g={x:0,y:0};this._init=function(a,b,c,d){e=new createjs.Container;g="vertical_2"===c||"vertical_3"===c?{x:START_X_GRID+CELL_WIDTH*a-12,y:START_Y_GRID+CELL_HEIGHT*b-5}:{x:START_X_GRID+CELL_WIDTH*a-5,y:START_Y_GRID+CELL_HEIGHT*b-5};"player"===c?(a={images:[s_oSpriteLibrary.getSprite("player")],framerate:9,frames:{width:159,height:90,regX:0,regY:0},animations:{idle:[0,11,"idle"]}},a=new createjs.SpriteSheet(a),a=createSprite(a,"idle",0,0,159,90),e.x=g.x,e.y=g.y,s_oStage.addChild(a)):
(a=createBitmap(s_oSpriteLibrary.getSprite(c)),e.x=g.x,e.y=g.y);e.addChild(a);s_oStage.addChild(e);createjs.Touch.enable(e);e.on("mousedown",this._onFormContainerClick,this);e.on("pressup",this._releaseForm,this);e.on("pressmove",this._dragForm,this)};this._onFormContainerClick=function(a){s_oGame.onFormContainerClick(a,e,c)};this._dragForm=function(b){s_oGame.dragForm(b,a,c)};this._releaseForm=function(b){s_oGame.releaseForm(b,g,a,c)};this.placeInGrid=function(a,b){createjs.Tween.get(e,{override:!0}).to({x:a,
y:b},500,createjs.Ease.cubicOut).call(function(){});g={x:a,y:b}};this.goBack=function(a,b){createjs.Tween.get(e).to({x:a,y:b},200,createjs.Ease.cubicOut).call(function(){})};this.moveOut=function(){createjs.Tween.get(e,{override:!0}).to({x:CANVAS_WIDTH},500,createjs.Ease.cubicIn).call(function(){s_oGame.gameOver()})};this.setPos=function(a,b){e.x=a;e.y=b};this.getPosX=function(){return e.x};this.getPosY=function(){return e.y};this.getOldX=function(){return g.x};this.getOldY=function(){return g.y};
this.getType=function(){return a};this.deleteForm=function(){e.off("mousedown",this._onFormContainerClick,this);e.off("pressmove",this._dragForm,this);e.off("pressup",this._releaseForm,this);s_oStage.removeChild(e)};this._init(b,d,a,c)}
function CLevelBut(b,d,a,c,e){var g,f,h,k=[],l=[],m;this._init=function(a,b,c,d){f=[];h=[];var n=new createjs.SpriteSheet({images:[c],frames:{width:d?c.width/2-5:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});g=d;m=createSprite(n,"state_"+g,c.width/2/2,c.height/2,c.width/2,c.height);m.mouseEnabled=d;m.x=a;m.y=b;m.stop();s_bMobile||(m.cursor="pointer");s_oStage.addChild(m);k.push(m);c=new createjs.Text(e,"bold 30px "+FONT,"#000000");c.x=a-
5;c.y=b+5;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=200;c.outline=8;s_oStage.addChild(c);c=new createjs.Text(e,"bold 30px "+FONT,"#ffc600");c.x=a-5;c.y=b+5;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=200;s_oStage.addChild(c);this._initListener()};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);s_oStage.removeChild(m)};this._initListener=function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};
this.viewBut=function(a){s_oStage.addChild(a)};this.addEventListener=function(a,b,c){f[a]=b;h[a]=c};this.addEventListenerWithParams=function(a,b,c,d){f[a]=b;h[a]=c;l=d};this.ifClickable=function(){return!0===m.mouseEnabled?1:0};this.setActive=function(a,b){g=b;k[a].gotoAndStop("state_"+g);k[a].mouseEnabled=!0};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");g=!g;m.gotoAndStop("state_"+g);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(h[ON_MOUSE_UP],
l)};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN],l)};this.setPosition=function(a,b){m.x=a;m.y=b};this.setVisible=function(a){m.visible=a};this._init(b,d,a,c)}
function CLevelMenu(){var b,d,a,c,e,g,f,h=[],k,l,m,r,p=null,v=null;this._init=function(){k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(k);k=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));s_oStage.addChild(k);f=new createjs.Text(TEXT_SELECT_LEVEL," 50px "+FONT,"#000000");f.x=CANVAS_WIDTH/2;f.y=370;f.textAlign="center";f.textBaseline="alphabetic";f.lineWidth=1E3;f.outline=8;s_oStage.addChild(f);f=new createjs.Text(TEXT_SELECT_LEVEL," 50px "+FONT,"#ffc600");f.x=CANVAS_WIDTH/
2;f.y=370;f.textAlign="center";f.textBaseline="alphabetic";f.lineWidth=1E3;s_oStage.addChild(f);for(var n=CANVAS_WIDTH/2+70,t=0,A=0,w=0;w<LEVEL_NUM;w++,t+=90)300<t&&(t=0,A+=90),w<s_iLevelReached?h.push(new CLevelBut(n-200+t,430+A,s_oSpriteLibrary.getSprite("level_sprite"),!0,w+1)):h.push(new CLevelBut(n-200+t,430+A,s_oSpriteLibrary.getSprite("level_sprite"),!1,w+1)),0===w?h[w].addEventListenerWithParams(ON_MOUSE_UP,this._onClickHelp,this,w):h[w].addEventListenerWithParams(ON_MOUSE_UP,this._onClick,
this,w),s_bFirstTime=!0;n=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-n.height/2-10;g=n.height/2+10;l=new CGfxButton(e,g,n,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onExit,this);a=CANVAS_WIDTH-n.width/2-110;c=n.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n=s_oSpriteLibrary.getSprite("audio_icon"),m=new CToggle(a,c,n,s_bAudioActive),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);n=window.document;t=n.documentElement;p=t.requestFullscreen||t.mozRequestFullScreen||
t.webkitRequestFullScreen||t.msRequestFullscreen;v=n.exitFullscreen||n.mozCancelFullScreen||n.webkitExitFullscreen||n.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(p=!1);p&&!1===inIframe()&&(n=s_oSpriteLibrary.getSprite("but_fullscreen"),b=n.width/4+10,d=n.height/2+10,r=new CToggle(b,d,n,s_bFullscreen,s_oStage),r.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){for(var a=0;a<LEVEL_NUM;a++)h[a].unload();p&&!1===inIframe()&&
r.unload();s_oLevelMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(f,h){l.setPosition(e-f,h+g);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(a-f,h+c);p&&!1===inIframe()&&r.setPosition(b+f,d+h)};this._onNumModeToggle=function(a){a===NUM_ACTIVE?((void 0).setActive(!1),(void 0).setActive(!0)):((void 0).setActive(!0),(void 0).setActive(!1))};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onClickHelp=function(a){h[a].ifClickable()&&
(s_oLevelMenu.unload(),s_oMain.gotoHelp(a))};this._onClick=function(a){h[a].ifClickable()&&(s_oLevelMenu.unload(),s_oMain.gotoGame(a,0))};this._onModeAdventure=function(){_oMode.setActive(!0)};this._onExit=function(){$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session");s_oLevelMenu.unload();s_oMain.gotoMenu()};this._onFullscreenRelease=function(){s_bFullscreen?(v.call(window.document),s_bFullscreen=!1):(p.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};
s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CHelpPanel(b){var d,a,c,e;this._init=function(b){var f=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));d=createBitmap(b);c=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));c.x=CANVAS_WIDTH/2-180;c.y=CANVAS_HEIGHT/2-150;a=new createjs.Container;a.addChild(f,d,c);new CComic(CANVAS_WIDTH/2-50,CANVAS_HEIGHT/2+180,a,TEXT_HELP,1);a.alpha=0;s_oStage.addChild(a);b=s_oSpriteLibrary.getSprite("but_play_small");e=new CGfxButton(CANVAS_WIDTH/2+160,CANVAS_HEIGHT-270,b);var g=this;createjs.Tween.get(a).to({alpha:1},
500).call(function(){e.addEventListener(ON_MOUSE_DOWN,g._onButPlayRelease,this)})};this._onButPlayRelease=function(){e.unload();s_oStage.removeChild(a);s_oMain.gotoGame(0,0)};this._init(b);return this}
function CComic(b,d,a,c,e){var g,f;this._init=function(a,b,c,d,e){e=s_oSpriteLibrary.getSprite("balloon_"+e);g=createBitmap(e);g.regX=e.width/2;g.regY=e.height/2;g.x=a;g.y=b;c.addChild(g);f=new CFormatText(a-145,b-85,d,"#000000",c,"#000000",24);f.disableOutline();f.setFont(FONT2);f.setWidth(250);f.setAlign("left");f.playText()};this.unload=function(){a.removeChild(g);f.unload()};this.flip=function(){g.scaleX=g.scaleY=-1;f.setPosition(b-180,d-80)};this._init(b,d,a,c,e)}
function CFormatText(b,d,a,c,e,g,f){var h,k,l,m,r,p;this._init=function(a,b,c,d,e,f,g){h=c;m=new createjs.Container;m.x=a;m.y=b+15;e.addChild(m);a=g+"px";k=new createjs.Text;k.text=h;k.font="bold "+a+" "+FONT2;k.color=f;k.textAlign="center";k.lineWidth=100;k.outline=4;m.addChild(k);l=new createjs.Text;l.text=h;l.font="bold "+a+" "+FONT2;l.color=d;l.textAlign="center";l.lineWidth=100;m.addChild(l)};this.unload=function(){e.removeChild(m)};this.disableOutline=function(){m.removeChild(k)};this.setVisible=
function(a){m.visible=a};this.isVisible=function(){return m.visible};this.setOutline=function(a){k.outline=a};this.setShadow=function(a){k.shadow=a?new createjs.Shadow("#333333",2,2,6):null};this.setAlign=function(a){k.textAlign=a;l.textAlign=a};this.setWidth=function(a){k.lineWidth=a;l.lineWidth=a};this.setText=function(a){l.text=a;k.text=a};this.setColor=function(a,b){l.color=a;k.color=b};this.setFont=function(a){var b=f+"px";l.font="bold "+b+" "+a;k.font="bold "+b+" "+a};this.getText=function(){return m};
this.setPos=function(a){m.y=a};this.getPos=function(){return{x:m.x,y:m.y}};this.playText=function(){r="";this.setText("");this._slideText(0)};this._slideText=function(b){r+=a[b];this.setText(r);b<a.length-1&&setTimeout(function(){p._slideText(b+1)},25)};this.setPosition=function(a,b){m.x=a;m.y=b};p=this;this._init(b,d,a,c,e,g,f)}
function CCreditsPanel(){var b,d,a,c,e,g,f,h;this._init=function(){h=new createjs.Container;s_oStage.addChild(h);var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));h.addChild(k);e=new createjs.Shape;e.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.addChild(e);k=s_oSpriteLibrary.getSprite("msg_box");d=createBitmap(k);d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2;d.regX=k.width/2;d.regY=k.height/2;h.addChild(d);g=new createjs.Shape;g.graphics.beginFill("#0f0f0f").drawRect(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=.01;g.on("click",this._onLogoButRelease);h.addChild(g);k=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH/2+220;a=new CGfxButton(b,270,k,h);a.addEventListener(ON_MOUSE_UP,this.unload,this);c=new createjs.Text(TEXT_DEVELOPED,"42px "+FONT,"#ffffff");c.x=CANVAS_WIDTH/2;c.y=390;c.textAlign="center";h.addChild(c);var k=s_oSpriteLibrary.getSprite("ctl_logo"),l=createBitmap(k);l.regX=k.width/2;l.regY=k.height/2;l.x=CANVAS_WIDTH/2;l.y=CANVAS_HEIGHT/2;h.addChild(l);
f=new createjs.Text("www.codethislab.com","36px "+FONT,"#ffffff");f.x=CANVAS_WIDTH/2;f.y=520;f.textAlign="center";h.addChild(f)};this.unload=function(){g.off("click",this._onLogoButRelease);a.unload();a=null;s_oStage.removeChild(h)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()};
