function CTimeBoard(a,b,c){var d,e,f,g;this._init=function(a,b,c){d={x:b,y:c};e=new createjs.Container;e.x=d.x;e.y=d.y;f=createBitmap(a);f.x=0;f.y=0;f.regX=0;f.regY=0;e.addChild(f);g=new createjs.Text("00:00:00","34px "+PRIMARY_FONT,TEXT_COLOR);g.x=.3*a.width;g.y=.65*a.height;g.textAlign="left";g.textBaseline="middle";e.addChild(g);s_oStage.addChild(e)};this.getStartPosition=function(){return d};this.setPosition=function(a,b){e.x=a;e.y=b};this.unload=function(){s_oStage.removeChild(e)};this.refresh=
function(a){g.text=a};this._init(a,b,c);return this}
function CTextToggle(a,b,c,d,e,f,g,l,k){var h=1,q,n=!1,r,v,t,w,p,u;this._init=function(a,b,c,h,d,f,e,k,E){q=!1;r=[];v=[];u=createBitmap(c);var F=Math.ceil(e/20);p=new createjs.Text(h," "+e+"px "+d,"#000000");p.textAlign="center";p.textBaseline="alphabetic";var g=p.getBounds();p.x=c.width/2+F;p.y=Math.floor(c.height/2)+g.height/3+F-7;w=new createjs.Text(h," "+e+"px "+d,f);w.textAlign="center";w.textBaseline="alphabetic";g=w.getBounds();w.x=c.width/2;w.y=Math.floor(c.height/2)+g.height/3-7;t=new createjs.Container;
t.x=a;t.y=b;t.regX=c.width/2;t.regY=c.height/2;k||(a=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}}),u=createSprite(a,"state_false",c.width/2/2,c.height/2,c.width/2,c.height),p.x=F,p.y=F+17,w.x=0,w.y=17,t.regX=0,t.regY=0);t.addChild(u,p,w);E.addChild(t);this._initListener()};this.unload=function(){t.off("mousedown");t.off("pressup");k.removeChild(t)};this.setVisible=function(a){t.visible=a};
this._initListener=function(){oParent=this;t.on("mousedown",this.buttonDown);t.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){r[a]=c;v[a]=b};this.buttonRelease=function(){q||n||(t.scaleX=1*h,t.scaleY=1*h,r[ON_MOUSE_UP]&&r[ON_MOUSE_UP].call(v[ON_MOUSE_UP]))};this.buttonDown=function(){q||n||(t.scaleX=.9*h,t.scaleY=.9*h,r[ON_MOUSE_DOWN]&&r[ON_MOUSE_DOWN].call(v[ON_MOUSE_DOWN]))};this.enable=function(){q=!1;l||u.gotoAndStop("state_true")};this.disable=function(){q=!0;l||u.gotoAndStop("state_false")};
this.setTextPosition=function(a,c){var b=Math.ceil(g/20);p.x=a+b;p.y=c+b;w.x=a;w.y=c};this.setText=function(a){w.text=a;p.text=a};this.setPosition=function(a,c){t.x=a;t.y=c};this.setX=function(a){t.x=a};this.setY=function(a){t.y=a};this.getButtonImage=function(){return t};this.getX=function(){return t.x};this.getY=function(){return t.y};this.block=function(a){n=a};this.setScale=function(a){h=a;t.scaleX=a;t.scaleY=a};this.setScaleX=function(a){u.scaleX=a};this._init(a,b,c,d,e,f,g,l,k);return this}
function CTextButton(a,b,c,d,e,f,g){var l,k,h,q,n;this._init=function(a,c,b,d,e,f,g){l=[];k=[];e=createBitmap(b);var x=Math.ceil(g/20);n=new createjs.Text(d,"bold "+g+"px "+PRIMARY_FONT,"#000000");n.textAlign="center";n.textBaseline="alphabetic";var m=n.getBounds();n.x=b.width/2+x;n.y=Math.floor(b.height/2)+m.height/3+x;q=new createjs.Text(d,"bold "+g+"px "+PRIMARY_FONT,f);q.textAlign="center";q.textBaseline="alphabetic";m=q.getBounds();q.x=b.width/2;q.y=Math.floor(b.height/2)+m.height/3;h=new createjs.Container;
h.x=a;h.y=c;h.regX=b.width/2;h.regY=b.height/2;h.addChild(e,n,q);s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown");h.off("pressup");s_oStage.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){oParent=this;h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){l[a]=b;k[a]=c};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};
this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setTextPosition=function(a){q.y=a;n.y=a+2};this.setPosition=function(a,b){h.x=a;h.y=b};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(a,b,c,d,e,f,g);return this}
function CPreloader(){var a,b,c,d,e,f,g;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();g=new createjs.Container;s_oStage.addChild(g)};this.unload=function(){g.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(f).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));g.addChild(l);l=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(l);d.x=CANVAS_WIDTH/2-l.width/2;d.y=CANVAS_HEIGHT-180;g.addChild(d);a=l.width;b=l.height;e=new createjs.Shape;e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,b);g.addChild(e);d.mask=
e;c=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT-205;c.shadow=new createjs.Shadow("#000",2,2,2);c.textBaseline="alphabetic";c.textAlign="center";g.addChild(c);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;g.addChild(f)};this.refreshLoader=function(f){c.text=f+"%";e.graphics.clear();f=Math.floor(f*a/100);e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,f,b)};this._init()}
function CPause(){var a,b,c,d,e;this._init=function(){a=new createjs.Container;a.alpha=0;b=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));a.addChild(b);var f=s_oSpriteLibrary.getSprite("msg_box");c=createBitmap(f);c.x=CANVAS_WIDTH_HALF;c.y=CANVAS_HEIGHT_HALF;c.regX=.5*f.width;c.regY=.5*f.height;a.addChild(c);f=s_oSpriteLibrary.getSprite("logo_small");d=new CLogo(.5*f.width+15,.5*f.height+15,f,a);a.on("click",function(){});f=new createjs.Text(TEXT_PAUSE,"60px "+PRIMARY_FONT,TEXT_COLOR);f.x=.5*
CANVAS_WIDTH;f.y=.5*CANVAS_HEIGHT-160;f.textAlign="center";a.addChild(f);s_oStage.addChild(a);f=s_oSpriteLibrary.getSprite("but_continue");e=new CGfxButton(.5*CANVAS_WIDTH,.5*CANVAS_HEIGHT+70,f,a);e.addEventListener(ON_MOUSE_UP,this._onLeavePause,this);this.onPause(!0);createjs.Tween.get(a).to({alpha:1},300,createjs.quartOut).call(function(){createjs.Ticker.paused=!0});this.refreshPosLogo(s_iOffsetX,s_iOffsetY)};this.onPause=function(a){s_oGame.setPause(a)};this.unload=function(){b.off("click",function(){});
s_oStage.removeChild(a)};this.refreshPosLogo=function(a,b){var c=d.getStartPos();d.setPosition(c.x+a,c.y+b)};this._onLeavePause=function(){playSound("click",1,0);createjs.Ticker.paused=!1;createjs.Tween.removeTweens(a);var b=this;createjs.Tween.get(a).to({alpha:0},300,createjs.quartIn).call(function(){b.onPause(!1);e.unload();s_oInterface.unloadPause()})};this._init();return this}
function CNumToggle(a,b,c,d){var e,f,g,l,k,h,q,n=[];this._init=function(a,b,c,d){f=!1;g=[];l=[];k=new createjs.Container;k.x=a;k.y=b;d.addChild(k);a=s_oSpriteLibrary.getSprite("num_button");b={images:[a],framerate:5,frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{state_true:[0],state_false:[1]}};b=new createjs.SpriteSheet(b);e=!1;h=createSprite(b,"state_"+e,a.width/2/2,a.height/2,a.width/2,a.height);h.stop();a=s_oSpriteLibrary.getSprite("ball");b={images:[a],
frames:{width:a.width/NUM_DIFFERENT_BALLS,height:a.height,regX:a.width/NUM_DIFFERENT_BALLS/2,regY:a.height/2},animations:{red:[0],green:[1],cyan:[0],violet:[1],blue:[1]}};b=new createjs.SpriteSheet(b);q=createSprite(b,"red",a.width/NUM_DIFFERENT_BALLS/2,a.height/2,a.width/NUM_DIFFERENT_BALLS,a.height);q.gotoAndStop(0);q.visible=!1;k.addChild(h,q);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);d.removeChild(k)};this._initListener=
function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;l[a]=c};this.addEventListenerWithParams=function(a,b,c,h){g[a]=b;l[a]=c;n=h};this.setActive=function(a){e=a;h.gotoAndStop("state_"+e)};this.buttonRelease=function(){f||(playSound("click",1,0),e=!e,h.gotoAndStop("state_"+e),g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(l[ON_MOUSE_UP],n))};this.buttonDown=function(){f||g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],n)};this.setPosition=
function(a,b){k.x=a;k.y=b};this.getGlobalPosition=function(){return{x:k.localToGlobal(0,0).x,y:k.localToGlobal(0,0).y}};this.block=function(a){f=a};this.setExtracted=function(a,b){q.visible=a;q.gotoAndStop(b)};this.highlight=function(){h.gotoAndPlay(0)};this.stopHighlight=function(){h.gotoAndStop(1)};this._init(a,b,c,d)}
function CMenu(){var a,b,c,d,e,f,g,l,k;this._init=function(){e=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(e);var h=s_oSpriteLibrary.getSprite("but_play");f=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+250,h);f.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h=s_oSpriteLibrary.getSprite("icon_audio"),c=CANVAS_WIDTH-h.width/2+15,d=h.height/2+15,k=new CToggle(c,d,h,s_bAudioActive),k.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);h=s_oSpriteLibrary.getSprite("but_info");a=h.width/2+15;b=h.height/2+15;g=new CGfxButton(a,b,h);g.addEventListener(ON_MOUSE_UP,this._onCredits,this);l=new createjs.Shape;l.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(l);createjs.Tween.get(l).to({alpha:0},1E3).call(function(){s_oStage.removeChild(l)});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){f.unload();f=null;s_oStage.removeChild(e);e=null;if(!1===DISABLE_SOUND_MOBILE||!1===
s_bMobile)k.unload(),k=null;createjs.Tween.removeAllTweens();s_oMenu=null};this.refreshButtonPos=function(h,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||k.setPosition(c-h,d+e);g.setPosition(a+h,b+e)};this._onCredits=function(){new CCreditsPanel;playSound("click",1,0)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();playSound("click",1,0);s_oMain.gotoLanguageMenu()};s_oMenu=this;this._init()}
var s_oMenu=null;
function CMain(a){var b,c=0,d=0,e=STATE_LOADING,f,g,l;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();b=!0};this.soundLoaded=function(){c++;g.refreshLoader(Math.floor(c/d*100));if(c===d){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<
navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/guessed.ogg","guessed"),createjs.Sound.registerSound("./sounds/wrong.ogg","wrong"),createjs.Sound.registerSound("./sounds/game_completed.ogg","game_completed")):(createjs.Sound.alternateExtensions=
["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.mp3","click"),createjs.Sound.registerSound("./sounds/guessed.mp3","guessed"),createjs.Sound.registerSound("./sounds/wrong.mp3","wrong"),createjs.Sound.registerSound("./sounds/game_completed.mp3","game_completed")),d+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,
this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_pause","./sprites/but_pause.png");s_oSpriteLibrary.addSprite("icon_audio","./sprites/icon_audio.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart",
"./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_level","./sprites/but_category.png");s_oSpriteLibrary.addSprite("hit_area_cell","./sprites/hit_area_cell.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("arrow_right","./sprites/arrow_right.png");s_oSpriteLibrary.addSprite("arrow_left","./sprites/arrow_left.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");
s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("but_not","./sprites/but_not.png");s_oSpriteLibrary.addSprite("game_panel","./sprites/game_panel.png");s_oSpriteLibrary.addSprite("word_panel","./sprites/word_panel.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("img_help","./sprites/img_help.png");s_oSpriteLibrary.addSprite("time_board","./sprites/time_board.png");s_oSpriteLibrary.addSprite("logo_small","./sprites/logo_small.png");
for(var a=0;a<NUM_OF_LANGUAGE;a++)s_oSpriteLibrary.addSprite("flag_"+a,"./sprites/flag_"+a+".png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;g.refreshLoader(Math.floor(c/d*100));if(c===d){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onLoadedJSON=function(a){s_aJSONWords=a;s_oMain.gotoLevelMenu()};this.onAllPreloaderImagesLoaded=
function(){this._loadImages()};this.gotoMenu=function(){new CMenu;e=STATE_MENU};this.gotoGame=function(a){l=new CGame(f,a);e=STATE_GAME;$(s_oMain).trigger("start_session")};this.gotoLanguageMenu=function(){new CLanguageMenu;e=STATE_MENU};this.loadJSON=function(a){jQuery.getJSON("json/"+a+".json",this.onLoadedJSON)};this.gotoLevelMenu=function(){new CLevelMenu;e=STATE_MENU};this.stopUpdate=function(){b=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=
(new Date).getTime();b=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==b){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&l.update();s_oStage.update(a)}};s_oMain=this;f=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oAdsLevel=1,s_iLevelReached=1,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas,s_iLanguageSelected,s_oSpriteSheetLora,s_aJSONWords;
function CLogo(a,b,c,d){var e,f,g;this._init=function(a,b,c){e={x:a,y:b};f=createBitmap(c);f.x=e.x;f.y=e.y;f.regX=.5*c.width;f.regY=.5*c.height;g.addChild(f)};this.setPosition=function(a,b){f.x=a;f.y=b};this.getStartPos=function(){return e};this.unload=function(){g.removeChild(f)};g=d;this._init(a,b,c);return this}var NUM_ROWS_PAGE_LEVEL=5,NUM_COLS_PAGE_LEVEL=2;
function CLevelMenu(){var a,b,c,d,e,f,g,l,k,h,q,n,r,v,t,w,p,u=null,y=null,x,m,z,B;this._init=function(){q=0;m=new createjs.Container;s_oStage.addChild(m);var r=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));m.addChild(r);r=s_oSpriteLibrary.getSprite("logo_small");B=new CLogo(.5*r.width+15,.5*r.height+15,r,s_oStage);k=CANVAS_WIDTH/2;h=CANVAS_HEIGHT_HALF-255;x=new createjs.Text(TEXT_SELECT_CATEGORY,"70px "+PRIMARY_FONT,TEXT_COLOR_2);x.x=k;x.y=h;x.textAlign="center";s_oStage.addChild(x);r=s_oSpriteLibrary.getSprite("but_exit");
g=CANVAS_WIDTH-r.height/2-15;l=r.height/2+15;w=new CGfxButton(g,l,r,s_oStage);w.addEventListener(ON_MOUSE_UP,this._onExit,this);n=r.height;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e=w.getX()-r.width-15,f=r.height/2+15,p=new CToggle(e,f,s_oSpriteLibrary.getSprite("icon_audio"),s_bAudioActive),p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this._checkBoundLimits();v=[];for(var r=Math.floor((CANVAS_WIDTH+2*EDGEBOARD_X)/NUM_COLS_PAGE_LEVEL)/2,D=0,A=0;A<NUM_COLS_PAGE_LEVEL;A++)v.push(D),
D+=2*r;t=[];this._createNewLevelPage(0,s_aJSONWords.categories.length);if(1<t.length){for(r=1;r<t.length;r++)t[r].visible=!1;c=CANVAS_WIDTH-80;d=CANVAS_HEIGHT-80;u=new CGfxButton(c,d,s_oSpriteLibrary.getSprite("arrow_right"),s_oStage);u.addEventListener(ON_MOUSE_UP,this._onRight,this);a=80;b=CANVAS_HEIGHT-80;y=new CGfxButton(a,b,s_oSpriteLibrary.getSprite("arrow_left"),s_oStage);y.addEventListener(ON_MOUSE_UP,this._onLeft,this)}z=new createjs.Shape;z.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,
CANVAS_HEIGHT);s_oStage.addChild(z);createjs.Tween.get(z).to({alpha:0},1E3).call(function(){s_oStage.removeChild(z);z=null});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){for(var a=0;a<r.length;a++)r[a].unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;w.unload();w=null;null!==y&&(y.unload(),u.unload());s_oLevelMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(h,k){w.setPosition(g-h,l+k);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(e-
h,k+f);null!==y&&(u.setPosition(c-h,d-k),y.setPosition(a+h,b-k));var m=B.getStartPos();B.setPosition(m.x+h,m.y+k)};this._checkBoundLimits=function(){for(var a=s_oSpriteLibrary.getSprite("but_level"),b=0,c=CANVAS_HEIGHT-2*EDGEBOARD_Y-2*n,h=0;b<c;)b+=a.height+20,h++;NUM_ROWS_PAGE_LEVEL>h&&(NUM_ROWS_PAGE_LEVEL=h);c=b=0;h=CANVAS_WIDTH-2*EDGEBOARD_X;for(a=s_oSpriteLibrary.getSprite("but_level");c<h;)c+=a.width/2+5,b++;NUM_COLS_PAGE_LEVEL>b&&(NUM_COLS_PAGE_LEVEL=b)};this._createNewLevelPage=function(a,
b){var c=new createjs.Container;m.addChild(c);t.push(c);r=[];for(var h=0,d=-200,e=1,f=!1,g=s_oSpriteLibrary.getSprite("but_level"),k=a;k<b;k++){var l=new CLevelBut(v[h]+g.width/2,d+g.height/2,s_aJSONWords.categories[k].cat_name,g,!0,c);l.addEventListenerWithParams(ON_MOUSE_UP,this._onButLevelRelease,this,k);r.push(l);h++;if(h===v.length&&(h=0,d+=g.height+20,e++,e>NUM_ROWS_PAGE_LEVEL)){f=!0;break}}c.x=CANVAS_WIDTH/2;c.y=520;c.regX=c.getBounds().width/2;f&&this._createNewLevelPage(k,b)};this._onRight=
function(){t[q].visible=!1;q++;q>=t.length&&(q=0);t[q].visible=!0};this._onLeft=function(){t[q].visible=!1;q--;0>q&&(q=t.length-1);t[q].visible=!0};this._onButLevelRelease=function(a){s_oMain.gotoGame(s_aJSONWords.categories[a])};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){this.unload();s_oMain.gotoLanguageMenu()};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(a,b,c,d,e,f){var g,l,k,h=[],q=[],n,r,v,t;this._init=function(a,b,c,d,e){l=[];k=[];v=new createjs.Container;t.addChild(v);r=createBitmap(d);r.regX=.5*d.width;r.regY=.5*d.height;r.mouseEnabled=e;r.x=a;r.y=b;g=!0;s_bMobile||(v.cursor="pointer");v.addChild(r);h.push(r);n=new createjs.Text(c,"24px "+SECONDARY_FONT,TEXT_COLOR);n.x=a;n.y=b-2;n.textAlign="center";n.textBaseline="middle";n.lineWidth=200;v.addChild(n);this._initListener()};this.unload=function(){v.off("mousedown",this.buttonDown);
v.off("pressup",this.buttonRelease);v.removeChild(r)};this._initListener=function(){v.on("mousedown",this.buttonDown);v.on("pressup",this.buttonRelease)};this.viewBut=function(a){v.addChild(a)};this.addEventListener=function(a,b,c){l[a]=b;k[a]=c};this.addEventListenerWithParams=function(a,b,c,h){l[a]=b;k[a]=c;q=h};this.ifClickable=function(){return!0===v.mouseEnabled?1:0};this.setActive=function(a,b){g=b;h[a].gotoAndStop("state_"+g);h[a].mouseEnabled=!0};this.buttonRelease=function(){g&&l[ON_MOUSE_UP]&&
l[ON_MOUSE_UP].call(k[ON_MOUSE_UP],q)};this.buttonDown=function(){l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],q)};this.setPosition=function(a,b){v.x=a;v.y=b};this.setVisible=function(a){v.visible=a};t=f;this._init(a,b,c,d,e,f)}
function CLanguageMenu(){var a,b,c,d,e,f,g,l,k,h,q;this._init=function(){q=[];f=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(f);var n=s_oSpriteLibrary.getSprite("logo_small");h=new CLogo(.5*n.width+15,.5*n.height+15,n,s_oStage);e=new createjs.Text(TEXT_SELECT_LANG,"65px "+PRIMARY_FONT,TEXT_COLOR_2);e.textAlign="center";e.textBaseline="alphabetic";e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-250;s_oStage.addChild(e);for(var n=180,r=194,v=0;v<NUM_OF_LANGUAGE;v++,n+=285){0===v%2&&
(n=180,r+=162);var t=s_oSpriteLibrary.getSprite("flag_"+v);q.push(this.createFlagButton(n,r,t,v))}n=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-n.height/2-15;b=n.height/2+15;k=new CGfxButton(a,b,n,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c=k.getX()-n.width-15,d=n.height/2+15,l=new CToggle(c,d,s_oSpriteLibrary.getSprite("icon_audio"),s_bAudioActive),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);g=new createjs.Shape;
g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(g);createjs.Tween.get(g).to({alpha:0},1E3).call(function(){s_oStage.removeChild(g);g=null});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.createFlagButton=function(a,b,c,h){a=new CGfxButton(a,b,c,s_oStage);a.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,h);return a};this.unload=function(){e=null;for(var a=0;a<NUM_OF_LANGUAGE;a++)q[a].unload();q=null;if(!1===DISABLE_SOUND_MOBILE||!1===
s_bMobile)l.unload(),l=null;k.unload();k=null;s_oStage.removeAllChildren();s_oLanguageMenu=null};this.refreshButtonPos=function(b,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(c-b,d+e);k.setPosition(a-b,e+d);var f=h.getStartPos();h.setPosition(f.x+b,f.y+e)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){this.unload();s_oMain.gotoMenu()};this._onButPlayRelease=function(a){s_oMain.loadJSON(LANGUAGE_ID[a]);this.unload();
playSound("click",1,0)};s_oLanguageMenu=this;this._init()}var s_oLanguageMenu=null;TEXT_SCORE="SCORE";TEXT_SCORE_GAMEOVER="Total Score";TEXT_PAUSE="PAUSE";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_WIN="YOU WON";TEXT_TOTAL_SCORE="TOTAL SCORE";TEXT_SELECT_LANG="SELECT LANGUAGE";TEXT_SELECT_CATEGORY="SELECT CATEGORY";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";TEXT_LINK1="www.codethislab.com";TEXT_FAIL_GENERATION_MATRIX="FAIL TO GENERATE MATRIX OF WORDS DECREASE THE NUMBER OF WORDS OR WORDS LETTER OR RETRY TO REGENERATE MATRIX";
TEXT_TIME="TIME";TEXT_SUMMARY="HOW TO PLAY";TEXT_HELP="Search up, down, forward, backward, and on the diagonal to find the hidden words.";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CInterface(){var a,b,c,d,e,f,g,l,k,h,q,n,r,v,t,w=null,p,u,y,x,m,z,B=null,C;this._init=function(){var p;a=0;b=115;v=new createjs.Container;s_oStage.addChild(v);v.x=a;v.y=b;p=s_oSpriteLibrary.getSprite("word_panel");m=createBitmap(p);m.x=.1*p.width-20;m.y=.5*-p.height+20;v.addChild(m);u=[];C=[];var A=s_oSpriteLibrary.getSprite("but_exit");e=p=CANVAS_WIDTH-A.width/2-15;f=A.height/2+15;r=new CGfxButton(e,f,A);r.addEventListener(ON_MOUSE_UP,this._onExit,this);A=s_oSpriteLibrary.getSprite("but_pause");
k=p-=A.width+15;h=A.height/2+15;n=new CGfxButton(k,h,A);n.addEventListener(ON_MOUSE_UP,this._onButPauseRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)A=s_oSpriteLibrary.getSprite("icon_audio"),g=p-=A.width/2+15,l=A.height/2+15,q=new CToggle(g,l,A,s_bAudioActive),q.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);c=CANVAS_WIDTH_HALF-50;d=CANVAS_HEIGHT_HALF-450;t=this.createText(c,d,"FPS:",20,"left","middle",400);s_oStage.addChild(t);p=s_oSpriteLibrary.getSprite("time_board");x=new CTimeBoard(p,
15,15);this.createFade();this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.createFade=function(){var a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=1;s_oStage.addChild(a);createjs.Tween.get(a).to({alpha:0},1E3,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(a)})};this.destroyAllLineDrawWordsGuessed=function(){for(var a=0;a<C.length;a++)v.removeChild(C[a]);C=[]};this.createHelpPanel=function(){var a=s_oSpriteLibrary.getSprite("msg_box");
z=new CHelpPanel(a)};this.refreshButtonPos=function(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||q.setPosition(g-a,l+c);n.setPosition(k-a,h+c);r.setPosition(e-a,f+c);t.y=d+c;v.y=b+c;var E=x.getStartPosition();x.setPosition(E.x+a,E.y+c);null!==w&&w.refreshPosLogo(a,c);null!==B&&B.refreshPosLogo(a,c);s_oGame.refreshPositionContainerGrid(c)};this.unloadHelpPanel=function(){z.unload()};this.createText=function(a,b,c,h,e,d,f){c=new createjs.Text(c,h+"px "+PRIMARY_FONT,TEXT_COLOR);c.x=a;c.y=b;c.textAlign=
e;c.textBaseline=d;c.lineWidth=f;return c};this.spawnWords=function(b){for(var c=2*EDGEBOARD_X+15,h=c,e=SPAWN_WORDS_OFFSET_Y,d=0;d<b.length;d++)u.push(new createjs.Text(b[d]," 20px "+SECONDARY_FONT,TEXT_COLOR)),u[d].x=h,u[d].y=e,u[d].textAlign="left",u[d].textBaseline="middle",u[d].lineWidth=400,u[d].x+u[d].getBounds().width>CANVAS_WIDTH-c&&(h=c,e+=u[d].getBounds().height+OFFSET_Y_SPACE_WORDS_LIST,u[d].x=h,u[d].y=e),v.addChild(u[d]),h+=u[d].getBounds().width+15,h>CANVAS_WIDTH-c-u[d].getBounds().width&&
(h=c,e+=u[d].getBounds().height+OFFSET_Y_SPACE_WORDS_LIST);v.x=a};this.drawLineOnWord=function(a){var c;c=new createjs.Shape;c.graphics.setStrokeStyle(STROKE_DIMENSION_MARKED,"round","round");c.graphics.beginStroke(COLOR_STROKE_MARKED);c.graphics.moveTo(u[a].x,u[a].y);c.graphics.lineTo(u[a].x+u[a].getBounds().width,u[a].y);c.graphics.closePath();C.push(c);v.addChild(c)};this.refreshFPSText=function(a){t.text="FPS:"+a};this.createWinPanel=function(a){var c=s_oSpriteLibrary.getSprite("msg_box");p=new CEndPanel(c);
p.show(a)};this._onButReturnToMenuRelease=function(){s_oGame.onExit()};this._onButPauseRelease=function(){w=new CPause};this.numLevel=function(a){};this.unloadPause=function(){w.unload();w=null};this.createFailGridPanel=function(){var a=s_oSpriteLibrary.getSprite("msg_box");y=new CFailGenerateGrid(a)};this.unloadFailPanel=function(){y.unload();y=null};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q.unload(),q=null;r.unload();r=null;n.unload();s_oInterface=n=null};this.refreshTime=
function(a,c,b){a=a.toString();c=c.toString();b=b.toString();a=this.checkIfAddZero(a);c=this.checkIfAddZero(c);b=this.checkIfAddZero(b);x.refresh(a+":"+c+":"+b)};this.checkIfAddZero=function(a){var c=a;2>c.length&&(c="0"+a);return c};this._onExit=function(){B=new CAreYouSurePanel(s_oStage);B.show();playSound("click",1,0)};this.unloadAreYouSure=function(){B.unload();B=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oInterface=this;this._init();
return this}var s_oInterface=null;
function CHelpPanel(a){var b,c,d,e,f,g=!1;this._init=function(a){b=createBitmap(a);b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT;b.regX=.5*a.width;b.regY=.5*a.height;c=new createjs.Container;d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=.5;c.addChild(d);c.addChild(b);s_oStage.addChild(c);this.page1(c);c.on("pressup",function(){s_oHelpPanel._onExitHelp()},null,!0);s_bMobile||(c.cursor="pointer")};this.page1=function(a){var c;c=new createjs.Text(TEXT_SUMMARY,
"44px "+PRIMARY_FONT,TEXT_COLOR);c.x=.5*CANVAS_WIDTH;c.y=.5*CANVAS_HEIGHT-180;c.textAlign="center";a.addChild(c);c=new createjs.Text(TEXT_HELP,"26px "+SECONDARY_FONT,TEXT_COLOR);c.x=.5*CANVAS_WIDTH;c.y=.5*CANVAS_HEIGHT-100;c.textAlign="center";c.lineWidth=430;a.addChild(c);c=s_oSpriteLibrary.getSprite("img_help");f=createBitmap(c);f.x=CANVAS_WIDTH_HALF-100;f.y=CANVAS_HEIGHT_HALF+108;f.regX=.5*c.width;f.regY=.5*c.height;a.addChild(f);createjs.Tween.get(a).to({alpha:1},300,createjs.Ease.cubicOut);c=
s_oSpriteLibrary.getSprite("but_continue");e=new CGfxButton(.5*CANVAS_WIDTH+180,.5*CANVAS_HEIGHT+110,c,a);e.addEventListener(ON_MOUSE_UP,this._onExitHelp,this);e.pulseAnimation();s_oStage.addChild(a)};this.unload=function(){s_oStage.removeChild(c);s_oHelpPanel=null;e.unload();e=null};this._onExitHelp=function(){g||(c.removeAllEventListeners(),g=!0,playSound("click",1,0),createjs.Tween.get(c).to({alpha:0},300,createjs.Ease.cubicOut).call(function(){s_oGame._onExitHelp()}))};s_oHelpPanel=this;this._init(a)}
var s_oHelpPanel=null;
function CGfxButton(a,b,c,d){var e,f,g,l,k=[],h,q,n,r;this._init=function(a,c,b,d){e=f=1;g=[];l=[];h=createBitmap(b);h.x=a;h.y=c;h.regX=b.width/2;h.regY=b.height/2;s_bMobile||(h.cursor="pointer");n?n.addChild(h):s_oStage.addChild(h);r=!1;this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);n?n.removeChild(h):s_oStage.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){h.on("mousedown",this.buttonDown);
h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){g[a]=c;l[a]=b};this.addEventListenerWithParams=function(a,c,b,d){g[a]=c;l[a]=b;k=d};this.buttonRelease=function(){r||(h.scaleX=f,h.scaleY=e,g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(l[ON_MOUSE_UP],k))};this.buttonDown=function(){r||(h.scaleX=.9*f,h.scaleY=.9*e,g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],k))};this.setScale=function(a){e=f=a;h.scaleX=a;h.scaleY=a};this.setScaleX=function(a){f=a;h.scaleX=a};this.setPosition=
function(a,c){h.x=a;h.y=c};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};this.block=function(a){r=a};this.pulseAnimation=function(){createjs.Tween.get(h).to({scaleX:.9*f,scaleY:.9*e},850,createjs.Ease.quadOut).to({scaleX:f,scaleY:e},650,createjs.Ease.quadIn).call(function(){q.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(h).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},
140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){q.trebleAnimation()})};n=d;q=this;this._init(a,b,c,d);return this}
function CGame(a,b){var c,d,e,f,g,l,k,h,q,n,r,v,t,w,p,u,y,x,m,z,B=!0,C=!1,D,A;this._init=function(){D=!0;f=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(f);w="";p=b.words;k=b.rows;h=b.cols;m=[];u=[];z=[];x=[];y=[];this._createGrid();A=0;g=new CInterface;this.controlWords();this.fillGridAttempts();for(var a=0;a<p.length;a++)y[a]=null;p.sort();g.spawnWords(p);g.createHelpPanel();s_oStage.on("pressup",this._onStageRelease);setVolume(s_oSoundTrack,.3)};this.restartLevel=function(){C=
D=!1;this.unloadGrid();u=[];z=[];x=[];m=[];this._createGrid();this.clearCharGridCell();this.deleteAllLineDraw();this.fillGridAttempts();A=0;this.time();g.createFade();g.refreshButtonPos(s_iOffsetX,s_iOffsetY);g.destroyAllLineDrawWordsGuessed()};this.unloadGrid=function(){for(var a=0;a<k;a++)for(var c=0;c<h;c++)m[a][c].unload();m=null;s_oStage.removeChild(l)};this.deleteAllLineDraw=function(){for(var a=0;a<x.length;a++)s_oStage.removeChild(y[a]),y[a]=null};this.setPause=function(a){D=a};this.refreshPositionContainerGrid=
function(a){l.y=e.y+a;this.setRectCells()};this._createGrid=function(){l=new createjs.Container;s_oStage.addChild(l);r=parseInt(GRID_AREA_SIZE/h);n=parseInt(GRID_AREA_SIZE/k);v=r/2;t=n/2;for(var a=0;a<p.length;a++)u.push("");for(var c=a=0;c<k;c++){m[c]=[];for(var b=0;b<h;b++)m[c][b]=new CWordCell(c,b,START_X_GRID+b*r+v,START_Y_GRID+c*n+t,l,"hide",GRID_AREA_SIZE/h/CELL_SIZE.width,a),a++}l.x=0;l.y=-l.getBounds().height-10;a=s_oSpriteLibrary.getSprite("game_panel");a=createBitmap(a);a.x=35;a.y=l.getBounds().height+
220;l.addChild(a);l.setChildIndex(a,0);e={x:l.x,y:l.y};this.setRectCells()};this.onContinue=function(){this.unload();setVolume(s_oSoundTrack,1);s_oMain.gotoLevelMenu();$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("end_session")};this.fillGridAttempts=function(){var a,c=0;do a=this.fillGrid(),c++;while(!1===a&&1E3>c);a||(g.createFailGridPanel(),D=!0)};this.setRectCells=function(){for(var a=0;a<k;a++)for(var c=0;c<h;c++)m[a][c].setRecOffset({x:l.x,y:l.y})};this._onExitHelp=function(){this.setPause(!1);
$(s_oMain).trigger("start_level",1);g.unloadHelpPanel()};this.controlWords=function(){(k>MAX_NUM_OF_COL_AND_ROW||h>MAX_NUM_OF_COL_AND_ROW)&&trace("MATRICE TROPPO GRANDE")};this.orderWordsDescendant=function(){var a;do{a=!1;for(var c=0;c<p.length-1;c++)p[c].length<p[c+1].length&&(a=p[c],p[c]=p[c+1],p[c+1]=a,a=!0)}while(a)};this.onExit=function(){s_oGame.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");setVolume(s_oSoundTrack,
1)};this.unload=function(){g.unload();s_oStage.removeEventListener("pressup",this._onStageRelease);s_oStage.removeEventListener("pressmove",this._onPressMove);for(var a=0;a<k;a++)for(var c=0;c<h;c++)m[a][c].unload();m=null;createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onCellSelected=function(a){if(B){B=!1;z.push(a);a.setActive(!0);w+=a.getChar();q=ALL_DIRECTION;if(null===y[x.length]){var c;c=new createjs.Shape;c.graphics.setStrokeStyle(STROKE_DIMENSION,"round");c.graphics.beginStroke(COLOR_STROKE);
c.graphics.moveTo(a.getX(),a.getY());c.graphics.lineTo(a.getX(),a.getY()-2);y[x.length]=c;y[x.length].mouseEnabled=!1;l.addChild(y[x.length])}s_oStage.addEventListener("pressmove",this._onPressMove)}};this.drawLine=function(a,c){y[x.length].graphics.clear();y[x.length].graphics.setStrokeStyle(STROKE_DIMENSION,"round","round");y[x.length].graphics.beginStroke(COLOR_STROKE);y[x.length].graphics.moveTo(z[0].getX(),z[0].getY());y[x.length].graphics.lineTo(a,c)};this.fillGrid=function(){this.clearCharGridCell();
var a=[LEFT,RIGHT,UP,DOWN,UP_LEFT,UP_RIGHT,DOWN_LEFT,DOWN_RIGHT];if(!this.placeFirstWordInRandomPos(p[0],a))return!1;for(var c,b=1;b<p.length;b++){for(var d=[],a=shuffle(a),e=!1,f=0;f<a.length;f++){c=a[f];switch(c){case LEFT:c=this.searchAFreePosition(placeWordsLeft,p[b],m);c.success&&(d.push(c),e=!0);break;case RIGHT:c=this.searchAFreePosition(placeWordsRight,p[b],m,h);c.success&&(d.push(c),e=!0);break;case UP:c=this.searchAFreePosition(placeWordsUp,p[b],m);c.success&&(d.push(c),e=!0);break;case DOWN:c=
this.searchAFreePosition(placeWordsDown,p[b],m,k);c.success&&(d.push(c),e=!0);break;case UP_LEFT:c=this.searchAFreePosition(placeWordsUpLeft,p[b],m);c.success&&(d.push(c),e=!0);break;case UP_RIGHT:c=this.searchAFreePosition(placeWordsUpRight,p[b],m,h);c.success&&(d.push(c),e=!0);break;case DOWN_LEFT:c=this.searchAFreePosition(placeWordsDownLeft,p[b],m,k);c.success&&(d.push(c),e=!0);break;case DOWN_RIGHT:c=this.searchAFreePosition(placeWordsDownRight,p[b],m,k,h),c.success&&(d.push(c),e=!0)}if(f===
a.length-1&&!e)return!1}this.searchWordWithMinWeight(d)}for(a=0;a<k;a++)for(b=0;b<h;b++)""===m[a][b].getChar()&&m[a][b].setRandomChar(Math.floor(Math.random()*s_aJSONWords.alphabet.length));return!0};this.searchWordWithMinWeight=function(a){for(var c=a[0].list[0].weight,b=a[0].list[0],d=0;d<a.length;d++)for(var h=0;h<a[d].list.length;h++)c>a[d].list[h].weight&&(b=a[d].list[h],c=a[d].list[h].weight);this.insertWordOnGrid(b)};this.insertWordOnGrid=function(a){for(var c=this.getRandomColor(),b=0;b<a.list_cell.length;b++){var d=
a.list_cell[b];m[d.r][d.c].changeCellText(d["char"]);SHOW_SOLUTION&&m[d.r][d.c].changeTextColor(c)}};this.getRandomColor=function(){return"rgba("+(Math.floor(127*Math.random()+128)-128)+","+(Math.floor(127*Math.random()+128)-128)+","+(Math.floor(127*Math.random()+128)-128)+",1)"};this.searchAFreePosition=function(a,c){for(var b=[],d=!1,h=0;h<m.length;h++)for(var e=0;e<m[h].length;e++){var f=a(c,h,e,m);f.success&&(b.push(f),d=!0)}return{list:b,success:d}};this.clearCharGridCell=function(){for(var a=
0;a<m.length;a++)for(var c=0;c<m[a].length;c++)m[a][c].changeCellText("")};this.placeFirstWordInRandomPos=function(a,c){var b=Math.floor(Math.random()*k),d=Math.floor(Math.random()*h),e=0;c=shuffle(c);for(var f,g=0;g<c.length;g++)switch(f=c[g],f){case LEFT:if(-1<d-a.length){for(g=d;g>d-a.length;g--)m[b][g].changeCellText(a.charAt(e)),e++;return!0}break;case RIGHT:if(d+a.length<h+1){for(g=d;g<d+a.length;g++)m[b][g].changeCellText(a.charAt(e)),e++;return!0}break;case UP:if(-1<b-a.length){for(g=b;g>
b-a.length;g--)m[g][d].changeCellText(a.charAt(e)),e++;return!0}break;case DOWN:if(b+a.length<k+1){for(g=b;g<b+a.length;g++)m[g][d].changeCellText(a.charAt(e)),e++;return!0}break;case UP_LEFT:if(f=d,-1<b-a.length&&0<d-a.length){for(g=b;g>b-a.length;g--)m[g][f].changeCellText(a.charAt(e)),f--,e++;return!0}case UP_RIGHT:f=d;if(-1<b-a.length&&d+a.length<h){for(g=b;g>b-a.length;g--)m[g][f].changeCellText(a.charAt(e)),f++,e++;return!0}break;case DOWN_LEFT:f=d;if(b+a.length<k+1&&0<d-a.length){for(g=b;g<
b+a.length;g++)m[g][f].changeCellText(a.charAt(e)),f--,e++;return!0}break;case DOWN_RIGHT:if(f=d,b+a.length<k+1&&d+a.length<h){for(g=b;g<b+a.length;g++)m[g][f].changeCellText(a.charAt(e)),f++,e++;return!0}}return!1};this._onPressMove=function(a){s_oGame.lineDrawing(a.stageX-l.x,a.stageY-l.y);var c,b;null!==y[x.length]?(c=y[x.length].graphics.command.x+l.x,b=y[x.length].graphics.command.y+l.y-2):(c=a.stageX,b=a.stageY);for(var d=0;d<k;d++)for(var e=0;e<h;e++)if(s_oGame.dirByMouse(a.stageX,a.stageY,
d,e),!1===m[d][e].isActive()&&pointInRectangle(c,b,m[d][e].getRectPos())){s_oGame.onCellOver(m[d][e]);break}};this.dirByMouse=function(a,c,b,d){pointInRectangle(a,c,m[b][d].getRectPos())&&(q=s_oGame.directionCell(z[0],m[b][d]))};this.onCellOver=function(a){B||(c=a.getRow(),d=a.getCol(),z.push(a))};this.lineDrawing=function(a,c){if(null!==y[x.length])switch(q){case LEFT:case RIGHT:case UP:case DOWN:case UP_LEFT:case UP_RIGHT:case DOWN_LEFT:case DOWN_RIGHT:var b=this.constrainLineDrawAngle(z[0].getX(),
z[0].getY(),a,c);this.drawLine(b.x,b.y-2);break;case ALL_DIRECTION:this.drawLine(a,c)}};this.directionCell=function(a,c){if("undefined"!==a){var b={x:a.getX(),y:a.getY()},d={x:c.getX(),y:c.getY()};return directionNextCell(b,d)}};this.constrainLineDrawAngle=function(a,c,b,d){b-=a;var e=d-c;d=Math.sqrt(b*b+e*e);b=Math.atan2(e,b)/Math.PI*180;b=b%360+180;22.5>=b||337.5<=b?b=0:67.5>=b?b=45:112.5>=b?b=90:157.5>=b?b=135:202.5>=b?b=180:247.5>=b?b=225:292.5>=b?b=270:337.5>b&&(b=315);b-=180;return{x:d*Math.cos(b*
Math.PI/180)+a,y:d*Math.sin(b*Math.PI/180)+c}};this._onStageRelease=function(){B||(s_oStage.removeEventListener("pressmove",s_oGame._onPressMove),B=!0,s_oGame._onCheckWord())};this.deleteALineDraw=function(a){y[a].graphics.clear();s_oStage.removeChild(y[a]);y[a]=null};this._onCheckWord=function(){var a=this.checkWord();if(2>w.length)this.deleteALineDraw(x.length),this._clearMatrix(),playSound("wrong");else{for(var c,b=-1,d=0;d<p.length;d++)if(p[d]===w){b=1;c=d;break}if(-1===b)this._clearMatrix(),
this.deleteALineDraw(x.length),playSound("wrong");else{b=!1;for(d=0;d<x.length;d++)if(x[d]===w){b=!0;this.deleteALineDraw(x.length);playSound("wrong");break}b||(this.drawLine(a.x,a.y),y[x.length].graphics.endStroke(),x.push(w),g.drawLineOnWord(c),this.checkFinishWordList(),playSound("guessed"));this._clearMatrix()}}};this.checkFinishWordList=function(){x.length===p.length&&(g.createWinPanel(Math.floor(BONUS_TIME/60-A/60)),playSound("game_completed"),C=!0)};this.checkWord=function(){var a=y[x.length].graphics.command,
b=z[0].getRow(),e=z[0].getCol(),f=z[0].getX()+l.x,g=z[0].getY()+l.y,k;switch(q){case LEFT:for(var n=e;n>d-1;n--)for(e=a.x;e<f;e+=.07*CELL_SIZE.width)if(!1===m[b][n].isActive()&&pointInRectangle(e,g,m[b][n].getRectPos())){w+=m[b][n].getChar();m[b][n].setActive(!0);k={x:m[b][n].getX(),y:m[b][n].getY()};break}break;case RIGHT:for(n=e;n<d+1;n++)for(e=a.x;e>f;e-=.07*CELL_SIZE.width)if(!1===m[b][n].isActive()&&pointInRectangle(e,g,m[b][n].getRectPos())){w+=m[b][n].getChar();m[b][n].setActive(!0);k={x:m[b][n].getX(),
y:m[b][n].getY()};break}break;case UP:for(;b>c-1;b--)for(n=a.y+l.y;n<g;n+=.07*CELL_SIZE.height)if(!1===m[b][e].isActive()&&pointInRectangle(f,n,m[b][e].getRectPos())){w+=m[b][e].getChar();m[b][e].setActive(!0);k={x:m[b][e].getX(),y:m[b][e].getY()};break}break;case DOWN:for(;b<c+1;b++)for(n=a.y+l.y;n>g;n-=.07*CELL_SIZE.height)if(!1===m[b][e].isActive()&&pointInRectangle(f,n,m[b][e].getRectPos())){w+=m[b][e].getChar();m[b][e].setActive(!0);k={x:m[b][e].getX(),y:m[b][e].getY()};break}break;case UP_LEFT:for(f=
e;b>c-1;b--){e=a.x;for(n=a.y+l.y;n<g;n+=.07*CELL_SIZE.height){if(!1===m[b][f].isActive()&&pointInRectangle(e,n,m[b][f].getRectPos())){w+=m[b][f].getChar();m[b][f].setActive(!0);k={x:m[b][f].getX(),y:m[b][f].getY()};break}e+=.07*CELL_SIZE.width}f--;if(0>f)break}break;case UP_RIGHT:for(f=e;b>c-1;b--){e=a.x;for(n=a.y+l.y;n<g;n+=.07*CELL_SIZE.height){if(!1===m[b][f].isActive()&&pointInRectangle(e,n,m[b][f].getRectPos())){w+=m[b][f].getChar();m[b][f].setActive(!0);k={x:m[b][f].getX(),y:m[b][f].getY()};
break}e-=.07*CELL_SIZE.width}f++;if(f>h-1)break}break;case DOWN_RIGHT:for(f=e;b<c+1;b++){e=a.x;for(n=a.y+l.y;n>g;n-=.07*CELL_SIZE.height){if(!1===m[b][f].isActive()&&pointInRectangle(e,n,m[b][f].getRectPos())){w+=m[b][f].getChar();m[b][f].setActive(!0);k={x:m[b][f].getX(),y:m[b][f].getY()};break}e-=.07*CELL_SIZE.width}f++;if(f>h-1)break}break;case DOWN_LEFT:for(f=e;b<c+1;b++){e=a.x;for(n=a.y+l.y;n>g;n-=.07*CELL_SIZE.height){if(!1===m[b][f].isActive()&&pointInRectangle(e,n,m[b][f].getRectPos())){w+=
m[b][f].getChar();m[b][f].setActive(!0);k={x:m[b][f].getX(),y:m[b][f].getY()};break}e+=.07*CELL_SIZE.width}f--;if(0>f)break}}return k};this._clearMatrix=function(){for(var a=0;a<k;a++)for(var b=0;b<h;b++)m[a][b].setActive(!1);z=[];B=!0;w=""};this.time=function(){A+=FPS_TIME;g.refreshTime(Math.floor(A/3600)%99,Math.floor(A/60)%60,Math.floor(A)%60)};this.update=function(){!1===D&&(C||this.time(),g.refreshFPSText(Math.floor(createjs.Ticker.getMeasuredFPS())))};s_oGame=this;BONUS_TIME=a.bonus_time;NUM_LEVELS_FOR_ADS=
a.num_levels_for_ads;this._init()}var s_oGame;
function CFailGenerateGrid(a){var b,c,d,e,f;this._init=function(a){f=new createjs.Container;s_oStage.addChild(f);d=new createjs.Shape;d.graphics.beginFill("#000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=.5;d.on("click",function(){});d.cursor="pointer";f.addChild(d);b=createBitmap(a);b.x=CANVAS_WIDTH_HALF;b.y=CANVAS_HEIGHT_HALF;b.regX=.5*a.width;b.regY=.5*a.height;f.addChild(b);c=new createjs.Text(TEXT_FAIL_GENERATION_MATRIX,"24px "+PRIMARY_FONT,TEXT_COLOR);c.textAlign="center";c.textBaseline=
"alphabetic";c.lineWidth=450;c.x=CANVAS_WIDTH/2;c.y=380;f.addChild(c);e=new CGfxButton(CANVAS_WIDTH/2,.5*CANVAS_HEIGHT+100,s_oSpriteLibrary.getSprite("but_restart"),f);e.addEventListener(ON_MOUSE_UP,this._onPressButRestart,this)};this.unload=function(){d.off("click",function(){});e.unload();e=null;playSound("click",1,0);s_oStage.removeChild(f)};this._onPressButRestart=function(){s_oInterface.unloadFailPanel();s_oGame.restartLevel()};this._init(a);return this}
function CEndPanel(a){var b,c,d,e,f,g,l,k;this._init=function(a){k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=0;s_oStage.addChild(k);e=new createjs.Container;e.alpha=1;e.visible=!1;e.y=CANVAS_HEIGHT;b=createBitmap(a);b.x=CANVAS_WIDTH_HALF;b.y=CANVAS_HEIGHT_HALF;b.regX=.5*a.width;b.regY=.5*a.height;e.addChild(b);c=new createjs.Text("","50px "+PRIMARY_FONT,TEXT_COLOR);c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT_HALF-180;c.textAlign="center";e.addChild(c);
d=new createjs.Text("","46px "+PRIMARY_FONT,TEXT_COLOR);d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-60;d.textAlign="center";e.addChild(d);a=s_oSpriteLibrary.getSprite("but_restart");g=new CGfxButton(.5*CANVAS_WIDTH-180,.5*CANVAS_HEIGHT+110,a,e);g.addEventListener(ON_MOUSE_DOWN,this._onRestart,this);g.pulseAnimation();a=s_oSpriteLibrary.getSprite("but_home");f=new CGfxButton(.5*CANVAS_WIDTH+180,.5*CANVAS_HEIGHT+110,a,e);f.addEventListener(ON_MOUSE_DOWN,this._onExit,this);a=s_oSpriteLibrary.getSprite("but_continue");
l=new CGfxButton(.5*CANVAS_WIDTH,.5*CANVAS_HEIGHT+110,a,e);l.addEventListener(ON_MOUSE_DOWN,this._onContinue,this);s_oStage.addChild(e)};this.unload=function(){f&&(f.unload(),f=null);g&&(g.unload(),g=null);k.removeAllEventListeners();s_oStage.removeChild(e,k)};this.show=function(a){c.text=TEXT_WIN;d.text=TEXT_TOTAL_SCORE+": "+a;e.visible=!0;createjs.Tween.get(k).to({alpha:.5},500,createjs.Ease.cubicOut);createjs.Tween.get(e).wait(250).to({y:0},1250,createjs.Ease.bounceOut).call(function(){s_oAdsLevel===
NUM_LEVELS_FOR_ADS?($(s_oMain).trigger("show_interlevel_ad"),s_oAdsLevel=1):s_oAdsLevel++});$(s_oMain).trigger("save_score",a);$(s_oMain).trigger("share_event",a)};this._onContinue=function(){this.createFade(this.onUnloadContinue)};this.createFade=function(a){var b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.alpha=0;s_oStage.addChild(b);var c=this;createjs.Tween.get(b).to({alpha:1},750,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(b);
a(c)})};this._onRestart=function(){this.createFade(this.onUnloadRestart)};this.onUnloadRestart=function(a){a.unload();s_oGame.restartLevel()};this.onUnloadContinue=function(a){a.unload();s_oGame.unload();s_oMain.gotoLevelMenu();$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");setVolume(s_oSoundTrack,1)};this.onUnloadExit=function(a){a.unload();s_oGame.onExit()};this._onExit=function(){this.createFade(this.onUnloadExit)};this._init(a);return this}
function CCreditsPanel(){var a,b,c,d,e,f,g,l;this._init=function(){l=new createjs.Container;s_oStage.addChild(l);var k=s_oSpriteLibrary.getSprite("msg_box");f=new createjs.Shape;f.graphics.beginFill("#000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=.5;f.on("click",this._onLogoButRelease);f.cursor="pointer";l.addChild(f);b=createBitmap(k);b.x=CANVAS_WIDTH_HALF;b.y=CANVAS_HEIGHT_HALF;b.regX=.5*k.width;b.regY=.5*k.height;l.addChild(b);k=s_oSpriteLibrary.getSprite("but_not");a=.5*CANVAS_WIDTH+
210;d=new CGfxButton(a,330,k,l);d.setScale(.4);d.addEventListener(ON_MOUSE_UP,this.unload,this);e=new createjs.Text(TEXT_CREDITS_DEVELOPED,"42px "+PRIMARY_FONT,TEXT_COLOR);e.textAlign="center";e.textBaseline="alphabetic";e.x=CANVAS_WIDTH_HALF;e.y=400;l.addChild(e);k=s_oSpriteLibrary.getSprite("logo_ctl");c=createBitmap(k);c.regX=k.width/2;c.regY=k.height/2;c.x=CANVAS_WIDTH_HALF;c.y=e.y+80;l.addChild(c);g=new createjs.Text(TEXT_LINK1,"50px "+PRIMARY_FONT,TEXT_COLOR);g.textAlign="center";g.textBaseline=
"alphabetic";g.x=CANVAS_WIDTH_HALF;g.y=e.y+180;l.addChild(g)};this.unload=function(){f.off("click",this._onLogoButRelease);d.unload();d=null;playSound("click",1,0);s_oStage.removeChild(l)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()}
function CAreYouSurePanel(a){var b,c,d,e,f,g,l,k;this._init=function(){f=new createjs.Container;f.alpha=0;f.visible=!1;g.addChild(f);l=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));f.on("click",function(){});f.addChild(l);var a=s_oSpriteLibrary.getSprite("logo_small");k=new CLogo(.5*a.width+15,.5*a.height+15,a,f);a=s_oSpriteLibrary.getSprite("msg_box");b=createBitmap(a);b.x=CANVAS_WIDTH_HALF;b.y=CANVAS_HEIGHT_HALF;b.regX=.5*a.width;b.regY=.5*a.height;f.addChild(b);c=new createjs.Text(TEXT_ARE_SURE,
"40px "+PRIMARY_FONT,TEXT_COLOR);c.x=CANVAS_WIDTH_HALF;c.y=400;c.textAlign="center";c.textBaseline="middle";f.addChild(c);d=new CGfxButton(CANVAS_WIDTH/2+150,.5*CANVAS_HEIGHT+110,s_oSpriteLibrary.getSprite("but_yes"),f);d.addEventListener(ON_MOUSE_UP,this._onButYes,this);e=new CGfxButton(CANVAS_WIDTH/2-150,.5*CANVAS_HEIGHT+110,s_oSpriteLibrary.getSprite("but_not"),f);e.addEventListener(ON_MOUSE_UP,this._onButNo,this);this.refreshPosLogo(s_iOffsetX,s_iOffsetY)};this.show=function(){s_oGame.setPause(!0);
f.visible=!0;createjs.Tween.get(f).to({alpha:1},300,createjs.quartOut).call(function(){createjs.Ticker.paused=!0})};this.refreshPosLogo=function(a,b){var c=k.getStartPos();k.setPosition(c.x+a,c.y+b)};this._onButYes=function(){s_oGame.setPause(!1);createjs.Ticker.paused=!1;s_oGame.onExit();f.removeAllEventListeners()};this.unload=function(){createjs.Tween.get(f).to({alpha:0},300,createjs.quartOut).call(function(){g.removeChild(f)})};this._onButNo=function(){createjs.Ticker.paused=!1;s_oGame.setPause(!1);
s_oInterface.unloadAreYouSure();f.removeAllEventListeners()};g=a;this._init()}
function CSpriteLibrary(){var a,b,c,d,e,f;this.init=function(g,l,k){c=b=0;d=g;e=l;f=k;a={}};this.addSprite=function(c,d){a.hasOwnProperty(c)||(a[c]={szPath:d,oSprite:new Image},b++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){e.call(f)};this._onSpriteLoaded=function(){d.call(f);++c===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=640,CANVAS_HEIGHT=960,CANVAS_WIDTH_HALF=.5*CANVAS_WIDTH,CANVAS_HEIGHT_HALF=.5*CANVAS_HEIGHT,EDGEBOARD_X=20,EDGEBOARD_Y=95,FPS=30,FPS_TIME=1/FPS,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="blackplotanregular",SECONDARY_FONT="arial",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,STROKE_DIMENSION=17,STROKE_DIMENSION_MARKED=7,MAX_NUM_OF_COL_AND_ROW=11,SIZE_TEXT_CELL=60,MAX_ITERATION_RANDOM_NUMBER=
1E3,TEXT_COLOR="#ffffff",TEXT_COLOR_2="#018def",SPAWN_WORDS_OFFSET_Y=-10,SHOW_SOLUTION=!1,NUM_OF_LANGUAGE=6,LANGUAGE_ID="english french german italian portoguese spanish".split(" "),COLOR_STROKE_MARKED="rgba(255,0,0,0.7)",COLOR_STROKE="rgba(92,190,248,0.5)",OFFSET_Y_GRID_LETTER=-125,OFFSET_Y_SPACE_WORDS_LIST=7,NO_DIRECTION=-1,LEFT=0,RIGHT=1,UP=2,DOWN=3,UP_LEFT=4,UP_RIGHT=5,DOWN_LEFT=6,DOWN_RIGHT=7,ALL_DIRECTION=8,CELL_SIZE={width:100,height:100},TEXT_WORD_COLOR="#2f2f2f",MAX_WORD_LENGTH=9,GRID_AREA_SIZE=
525,START_X_GRID=(CANVAS_WIDTH-GRID_AREA_SIZE)/2,START_Y_GRID=CANVAS_HEIGHT-200;
function placeWordsLeft(a,b,c,d){var e=[],f=0,g=0,l=!1,k=c-a.length;if(0>k)return{success:!1};for(;c>k;c--)if(void 0!==d[b]&&void 0!==d[b][c])if(""===d[b][c].getChar()||a.charAt(f)===d[b][c].getChar()){var h="";a.charAt(f)!==d[b][c].getChar()?g++:h=d[b][c].getChar();e.push({r:b,c:c,"char":a.charAt(f),char_compare:h});f++;a.length===f&&(l=!0)}else return{success:!1};else return{success:!1};return{list_cell:e,weight:g,success:l}}
function placeWordsRight(a,b,c,d,e){var f=[],g=0,l=0,k=!1,h=c+a.length;if(h>e)return{success:!1};for(;c<h;c++)if(void 0!==d[b]&&void 0!==d[b][c])if(""===d[b][c].getChar()||a.charAt(g)===d[b][c].getChar())e="",a.charAt(g)!==d[b][c].getChar()?l++:e=d[b][c].getChar(),f.push({r:b,c:c,"char":a.charAt(g),char_compare:e}),g++,a.length===g&&(k=!0);else return{success:!1};else return{success:!1};return{list_cell:f,weight:l,success:k}}
function placeWordsUp(a,b,c,d){var e=[],f=0,g=0,l=!1,k=b-a.length;if(0>k)return{success:!1};for(;b>k;b--)if(void 0!==d[b]&&void 0!==d[b][c])if(""===d[b][c].getChar()||a.charAt(f)===d[b][c].getChar()){var h="";a.charAt(f)!==d[b][c].getChar()?g++:h=d[b][c].getChar();e.push({r:b,c:c,"char":a.charAt(f),char_compare:h});f++;a.length===f&&(l=!0)}else return{success:!1};else return{success:!1};return{list_cell:e,weight:g,success:l}}
function placeWordsDown(a,b,c,d,e){var f=[],g=0,l=0,k=!1,h=b+a.length;if(h>e)return{success:!1};for(;b<h;b++)if(void 0!==d[b]&&void 0!==d[b][c])if(""===d[b][c].getChar()||a.charAt(g)===d[b][c].getChar())e="",a.charAt(g)!==d[b][c].getChar()?l++:e=d[b][c].getChar(),f.push({r:b,c:c,"char":a.charAt(g),char_compare:e}),g++,a.length===g&&(k=!0);else return{success:!1};else return{success:!1};return{list_cell:f,weight:l,success:k}}
function placeWordsUpLeft(a,b,c,d){var e=[],f=0,g=0,l=!1,k=b-a.length,h=c-a.length;if(0>k&&0>h)return{success:!1};for(;b>k;b--)if(void 0!==d[b]&&void 0!==d[b][c])if(""===d[b][c].getChar()||a.charAt(f)===d[b][c].getChar())h="",a.charAt(f)!==d[b][c].getChar()?g++:h=d[b][c].getChar(),e.push({r:b,c:c,"char":a.charAt(f),char_compare:h}),f++,c--,a.length===f&&(l=!0);else return{success:!1};else return{success:!1};return{list_cell:e,weight:g,success:l}}
function placeWordsUpRight(a,b,c,d,e){var f=[],g=0,l=0,k=!1,h=b-a.length,q=c+a.length;if(0>h&&q>e)return{success:!1};for(;b>h;b--)if(void 0!==d[b]&&void 0!==d[b][c])if(""===d[b][c].getChar()||a.charAt(g)===d[b][c].getChar())e="",a.charAt(g)!==d[b][c].getChar()?l++:e=d[b][c].getChar(),f.push({r:b,c:c,"char":a.charAt(g),char_compare:e}),g++,c++,a.length===g&&(k=!0);else return{success:!1};else return{success:!1};return{list_cell:f,weight:l,success:k}}
function placeWordsDownLeft(a,b,c,d,e){var f=[],g=0,l=0,k=!1,h=b+a.length,q=c-a.length;if(h>e&&0>q)return{success:!1};for(;b<h;b++)if(void 0!==d[b]&&void 0!==d[b][c])if(""===d[b][c].getChar()||a.charAt(g)===d[b][c].getChar())e="",a.charAt(g)!==d[b][c].getChar()?l++:e=d[b][c].getChar(),f.push({r:b,c:c,"char":a.charAt(g),char_compare:e}),g++,c--,a.length===g&&(k=!0);else return{success:!1};else return{success:!1};return{list_cell:f,weight:l,success:k}}
function placeWordsDownRight(a,b,c,d,e,f){var g=[],l=0,k=0,h=!1,q=b+a.length,n=c+a.length;if(q>e&&n>f)return{success:!1};for(;b<q;b++)if(void 0!==d[b]&&void 0!==d[b][c])if(""===d[b][c].getChar()||a.charAt(l)===d[b][c].getChar())e="",a.charAt(l)!==d[b][c].getChar()?k++:e=d[b][c].getChar(),g.push({r:b,c:c,"char":a.charAt(l),char_compare:e}),l++,c++,a.length===l&&(h=!0);else return{success:!1};else return{success:!1};return{list_cell:g,weight:k,success:h}}
function CWordCell(a,b,c,d,e,f,g,l){var k,h,q,n,r,v=!1,t,w=s_aJSONWords.alphabet,p,u,y;this._init=function(a,b,c,d,f,g,l){k=a;h=b;q=g;r=l;t=f;n=null;p=new createjs.Text("",SIZE_TEXT_CELL+"px "+SECONDARY_FONT,TEXT_WORD_COLOR);p.x=c;p.y=d+5;p.textAlign="center";p.textBaseline="alphabet";p.lineWidth=500;p.scaleX=p.scaleY=q;e.addChild(p);a=s_oSpriteLibrary.getSprite("hit_area_cell");u=new CGfxButton(c,d,a,e);u.addEventListener(ON_MOUSE_DOWN,this._onCellClicked,this);u.regX=a.width/2;u.regY=a.height/2;
e.addChild(u.getButtonImage())};this.isActive=function(){return v};this.changeCellState=function(a){(void 0).gotoAndStop("selected_"+a)};this.getID=function(){return r};this.changeCellText=function(a){p.text=a};this.checkInPlace=function(a){return""===p.text||p.text===a?!0:!1};this.getChar=function(){return p.text};this.setRecOffset=function(a){y=new createjs.Rectangle(a.x+u.getX()-25,a.y+u.getY()-25,a.x+u.getX()+5,a.y+u.getY()+5)};this.setRandomChar=function(a){""===p.text&&(p.text=w[a])};this._onCellClicked=
function(){s_oGame.onCellSelected(this,k,h)};this.setActive=function(a){v=a};this.getX=function(){return c};this.getY=function(){return d};this.getValue=function(){return t};this.getState=function(){return n};this.changeTextColor=function(a){p.color=a};this.getRotation=function(){return(void 0).rotation};this.getRow=function(){return k};this.getCol=function(){return h};this.getRectPos=function(){return y};this.unload=function(){u.unload();u=null;e.removeChild(void 0)};this._init(a,b,c,d,f,g,l);return this}
function CToggle(a,b,c,d){var e,f,g,l=[],k;this._init=function(a,b,c,d){f=[];g=[];var l=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});e=d;k=createSprite(l,"state_"+e,c.width/2/2,c.height/2,c.width/2,c.height);k.mouseEnabled=!0;k.x=a;k.y=b;k.stop();s_bMobile||(k.cursor="pointer");s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",
this.buttonRelease);k.mouseEnabled=!1;s_oStage.removeChild(k)};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;g[a]=c};this.addEventListenerWithParams=function(a,b,c,d){f[a]=b;g[a]=c;l=d};this.setActive=function(a){e=a;k.gotoAndStop("state_"+e)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("click",1,0);e=!e;k.gotoAndStop("state_"+e);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(g[ON_MOUSE_UP],l)};
this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],l)};this.setPosition=function(a,b){k.x=a;k.y=b};this.setVisible=function(a){k.visible=a};this._init(a,b,c,d)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return!0;return!1}
function getSize(a){var b=a.toLowerCase(),c=window.document,d=c.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var e=c.createElement("body");e.id="vpw-test-b";e.style.cssText="overflow:scroll";var f=c.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+b+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+b+":7px!important}}</style>";e.appendChild(f);d.insertBefore(e,c.head);
a=7==f["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(e)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var b=getSize("Width"),c=Math.min(a/CANVAS_HEIGHT,b/CANVAS_WIDTH),d=CANVAS_WIDTH*c,c=CANVAS_HEIGHT*c,e;c<a?(e=a-c,c+=e,d+=CANVAS_WIDTH/CANVAS_HEIGHT*e):d<b&&(e=b-d,d+=e,c+=CANVAS_HEIGHT/CANVAS_WIDTH*e);e=a/2-c/2;var f=b/2-d/2,g=CANVAS_WIDTH/d;if(f*g<-EDGEBOARD_X||e*g<-EDGEBOARD_Y)c=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),b/(CANVAS_WIDTH-2*EDGEBOARD_X)),
d=CANVAS_WIDTH*c,c*=CANVAS_HEIGHT,e=(a-c)/2,f=(b-d)/2,g=CANVAS_WIDTH/d;s_iOffsetX=-1*f*g;s_iOffsetY=-1*e*g;0<=e&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oLanguageMenu&&s_oLanguageMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",d+"px");$("#canvas").css("height",c+
"px");0>e?$("#canvas").css("top",e+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",f+"px")}}function createBitmap(a,b,c){var d=new createjs.Bitmap(a),e=new createjs.Shape;b&&c?e.graphics.beginFill("#fff").drawRect(0,0,b,c):e.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=e;return d}
function createSprite(a,b,c,d,e,f){a=null!==b?new createjs.Sprite(a,b):new createjs.Sprite(a);b=new createjs.Shape;b.graphics.beginFill("#000000").drawRect(-c,-d,e,f);a.hitArea=b;return a}function randomFloatBetween(a,b,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(b-a),b).toFixed(c))}function formatTime(a){a/=1E3;var b=Math.floor(a/60);a=Math.floor(a-60*b);var c="",c=10>b?c+("0"+b+":"):c+(b+":");return 10>a?c+("0"+a):c+a}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var b=a.length,c,d;0<b;)d=Math.floor(Math.random()*b),b--,c=a[b],a[b]=a[d],a[d]=c;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var b=document.createEvent("MouseEvents");b.initEvent("click",!0,!0);a.dispatchEvent(b)}}};
(function(){function a(a){var d={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in d?document.body.className=d[a.type]:(document.body.className=this[b]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var b="hidden";b in document?document.addEventListener("visibilitychange",a):(b="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(b="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(b="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var b=window.location.search.substring(1).split("&"),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0]==a)return d[1]}}function playSound(a,b,c){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:c,volume:b}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}function setVolume(a,b){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=b}
function setMute(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(b)}function between(a,b,c){var d=!1;a<c&&b>a&&b<c&&(d=!0);a>c&&b>c&&b<a&&(d=!0);if(b===a||b===c)d=!0;return d}function pointInRectangle(a,b,c){var d=!1,e=c.y,f=c.height;between(c.x,a,c.width)&&between(e,b,f)&&(d=!0);return d}
function directionNextCell(a,b){if(a.x<b.x&&a.y===b.y)return RIGHT;if(a.x>b.x&&a.y===b.y)return LEFT;if(a.x===b.x&&a.y>b.y)return UP;if(a.x===b.x&&a.y<b.y)return DOWN;if(a.x>b.x&&a.y<b.y)return DOWN_LEFT;if(a.x>b.x&&a.y>b.y)return UP_LEFT;if(a.x<b.x&&a.y>b.y)return UP_RIGHT;if(a.x<b.x&&a.y<b.y)return DOWN_RIGHT}function rotate(a,b,c){return{x:a*Math.cos(c)+b*Math.sin(c),y:a*-Math.sin(c)+b*Math.cos(c)}};